### ISSUE TITLE
InlinePanel displayed within MultiFieldPanel needs visual improvements

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#100]
The rules for when a label/heading should or shouldn't appear are causing undesirable effects when inline panels are not a direct child of a content/promote panels. The labels/headings are hidden creating a confusing and unlabelled output of lots of fields and buttons. 

The CSS needs to cater for a wider range of permutations of one panel-type appearing within another.

**Comment by thibaudcolas** [comment]
This feels a bit too vague - overlaps with what we’re up to with the page editor redesign, so I’ll close this now.
