### ISSUE TITLE
Show usage summary when unpublishing/deleting an object

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#10008]
When unpublishing or deleting a page or snippet, it would be useful to have a summary of what other objects uses the page/snippet, so that users know what the implications are.

The snippet delete confirmation page currently shows the number of other objects that use the snippet. Now that we have the powerful reference index, we should be able to show all the usages efficiently.

Meanwhile, for other views (page delete confirmation and page/snippets unpublish confirmation), we do not show any usage information at all.

For the record, we currently don't have a Usage view for pages (see #1722). The existing "usage" view for pages shows you the usage of the page types, not the page instances themselves. Before adding this usage summary to the delete/unpublish views, I think ideally we should have the Usage view itself first.

Work required:
- Extract the usage view for snippets, images, and docs into a generic view and make the other views extend from it.
  - #10007
- Implement a page usage view based on the generic usage view.
  - #1722
- Add the usage summary on the delete and unpublish confirmation views on pages and snippets.
  - #10072

**Comment by jsma** [comment]
FYI, there was a draft PR to handle displaying uses and delete confirmation warnings based on the old reference counting here https://github.com/wagtail/wagtail/pull/4702#issuecomment-1268810782

I have not looked at it closely, but perhaps #4702 can be closed if your new PRs cover the intended features.

**Comment by jsma** [comment]
> As a compromise, we show the usage count (just the count, not the references list) on the delete confirmation. The usage count is a link to the usage view. This is currently how it works on some delete confirmation views (see snippets, images, etc.), and I think we can keep this as-is. Perhaps we could improve the message a bit, though.

> The usage view can be made more useful by adding the "on delete" description to each reference (e.g. whether it'll cascade, set default, set null, etc.). Showing this information doesn't make much sense when you're viewing the usage view on its own (outside the context of the delete confirmation), so we'll likely use a URL parameter to show/hide this information. The link to the usage view from the delete confirmation page would have the URL parameter set so that the "on delete" information is shown.

Thanks @laymonage, this seems like a reasonable path forward and would allow us to retire our homegrown solution that overrides the delete confirmation templates. As long as we can link folks to the usages from the "confirm delete" step, and then toggle the display of the `on_delete` situation when in "confirm delete" mode, that solves it for us. 

I've asked the same question [here](https://github.com/wagtail/wagtail/issues/9731#issuecomment-1416300929) but will the on_delete stuff be inspected in real-time or will this be "cached" in the ReferenceIndex? If cached, there will need to be some way of handling of the fact that the `on_delete` behavior can change over time (PROTECT => SET_NULL or vice versa, etc.).
