### ISSUE TITLE
Page type usage table shows a bulk actions checkbox in the header

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#10003]
### Issue Summary

The page type usage table incorrectly shows a bulk actions checkbox in the header, making the table body incorrectly aligned with the header:

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/6379424/216116773-0db9ff63-82d2-4aa1-a41d-a20db8d8b27c.png">

### Steps to Reproduce

1. Spin up bakerydemo
2. Click on "Add child page" while browsing the "Welcome to the Wagtail Bakery" page
3. Click on the "Pages using ... page" link on the right hand side of the page type name (this is a bit hidden, I think we could improve the UI somehow)
  <img width="785" alt="image" src="https://user-images.githubusercontent.com/6379424/216117602-f5d351a5-7a31-465f-8683-15100d16d8de.png">
4. See result

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
The bulk actions checkbox shouldn't be present, so that the table body correctly aligns with the header.

**Comment by gasman** [comment]
Fixed in #10004
