### ISSUE TITLE
Documentation search incorrectly links to wagtail.io not wagtail.org

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10027]
### Pertinent section of the Wagtail docs

When using the search dialog/popup - it appears that the links that are shown in the response use the old domain. 

This causes a significant delay sometimes as the page needs to redirect (at the cdn level I assume).

### Details

On any device, do a search for something and then click the link in the box that appears. Observe that the link is the `.io` domain not the new `.org` one. 

![Screenshot_20230205-180911](https://user-images.githubusercontent.com/1396140/216808534-75b76e9a-b0ef-45d9-bbf1-63318eb87f12.png)

## Related links

- https://github.com/wagtail/wagtail/issues/7841

**Comment by salty-ivy** [comment]
@lb- the search is from algolia, would you mind sharing its integration or perhaps where does these search results coming from?

**Comment by RyanWalker277** [comment]
Hey @lb- @salty-ivy ! I would like to work on this issue

**Comment by lb-** [comment]
I've flagged a question to the core team. I don't have access to the Algolia search config. However, it may be something we can change on the Wagtail repo but U doubt it, I haven't dug too deep though.

**Comment by salty-ivy** [comment]
yup, a rough lookup search didn't get me any useful  instance  of `wagtail.io` in the codebase ; )

**Comment by thibaudcolas** [comment]
This has been fixed for `latest`, and will make its way to other versions next week.

**Comment by lb-** [comment]
Thanks Thibaud. This is awesome

**Comment by lb-** [comment]
![Screenshot_20230311-103512](https://user-images.githubusercontent.com/1396140/224453861-f8ec5b9b-8c83-4257-b80c-2b52866e9814.png)

Confirming this is working on the latest docs now.
