### ISSUE TITLE
Replace usage of `text/django-form-template` script with `template` element

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10034]
### Is your proposal related to a problem?

As part of the [Stimulus  🎛️ RFC 78](https://github.com/wagtail/rfcs/pull/78) adoption, it would be good to ensure that all usage of `script` tags that are simply present to represent HTML snippets (templates) be replaced with the `template` element.

This is so that we can avoid using inline scripts and that future Stimulus adoption is easier to migrate towards. 

### Describe the solution you'd like

* Replace the existing usage of `<script ... type="text/django-form-template"` with simply `<template ...`
* Update the JS behaviour accordingly (see important note in context below)
* Update any Python or JS unit tests that will be impacted by this chance to ensure they pass
* Resolve any edge cases that we encounter with changing from `script` to `template`

#### Current Implementations

* [client/src/components/ExpandingFormset/index.js](https://github.com/wagtail/wagtail/blob/main/client/src/components/ExpandingFormset/index.js) (reads the content, parses it, adds it to DOM, beware of the double script encoding which will no longer be needed)
* [wagtail/admin/templates/wagtailadmin/panels/inline_panel.html](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/panels/inline_panel.html)
* [wagtail/admin/templates/wagtailadmin/permissions/includes/collection_member_permissions_formset.html](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/permissions/includes/collection_member_permissions_formset.html)
* [wagtail/admin/templates/wagtailadmin/workflows/includes/workflow_pages_formset.html](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/workflows/includes/workflow_pages_formset.html)
* [wagtail/contrib/search_promotions/templates/wagtailsearchpromotions/includes/searchpromotions_formset.html](https://github.com/wagtail/wagtail/blob/main/wagtail/contrib/search_promotions/templates/wagtailsearchpromotions/includes/searchpromotions_formset.html)
* [wagtail/users/templates/wagtailusers/groups/includes/page_permissions_formset.html](https://github.com/wagtail/wagtail/blob/main/wagtail/users/templates/wagtailusers/groups/includes/page_permissions_formset.html)

#### Important note about using `template`

* Read this before starting https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template
* Most important https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template#avoiding_documentfragment_pitfall
* Correct implementation: `const myClone = template.content.firstElementChild.cloneNode(true);`
* Note: jQuery `.html()` may be enough but do check that event listeners correctly get added

#### Related items

* https://github.com/wagtail/wagtail/issues/10033 &  #10045 (this is a similar, but simpler problem, a good reference of what needs to be done)
* This will also make a lot more template code CSP compliant - see #1288 & #7053

**Comment by lb-** [comment]
Note: https://github.com/wagtail/wagtail/issues/10033 should be done before this one, this issue is not really a good first issue as it requires extra context and understanding of double encoding script tags and inline panel code is quite fragile.

**Comment by Ananjan-R** [comment]
Could I attempt this issue?

**Comment by lb-** [comment]
Go for it @Ananjan-R  if you are still keen on it.

**Comment by lb-** [comment]
@mansi0829  - this might also be a good one to pick up if you are keen, it's a good starting issue that helps for the future Stimulus migration in this area of code.

See #10045 as a reference of a similar piece of work done to what's needed for this issue.

**Comment by mansi0829** [comment]
![Screenshot from 2023-03-19 22-59-20](https://user-images.githubusercontent.com/81025790/226195345-6a33aeab-4056-4489-bb57-bc7540bf28df.png)

In script form this add workflow form had only workflow heading and not the task as input as when i checked its python file for post request to add workflow it had task as an element as well so while changing that to template should i add task as well.

**Comment by lb-** [comment]
@subhajit20 if you're keen on a similar kind of Issue - take a look at this one. 

There's already a PR up but it's likely not going to get further work on it. The PR has some feedback thoug that may be useful, you can also see what was started. 


https://github.com/wagtail/wagtail/pull/10245

**Comment by subhajit20** [comment]
> @subhajit20 if you're keen on a similar kind of Issue - take a look at this one.
> 
> There's already a PR up but it's likely not going to get further work on it. The PR has some feedback thoug that may be useful, you can also see what was started.
> 
> #10245

Cool I am up for taking it.
Thanks.
