### ISSUE TITLE
Replace usage of `text/template` script with `template` element

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10033]
### Is your proposal related to a problem?

As part of the [Stimulus  🎛️ RFC 78](https://github.com/wagtail/rfcs/pull/78) adoption, it would be good to ensure that all usage of `script` tags that are simply present to represent HTML snippets (templates) be replaced with the `template` element.

This is so that we can avoid using inline scripts and that future Stimulus adoption is easier to migrate towards. 

### Describe the solution you'd like

* Replace the two usages of `<script ... type="text/template"` with simply `<template ...`
* Update the JS behaviour accordingly (see important note in context below)
* Update any Python or JS unit tests that will be impacted by this chance to ensure they pass
* Resolve any edge cases that we encounter with changing from `script` to `template`
* Do not worry about refactoring things in the duplicated JS, in time this will move to Stimulus, for now this is about removing any script usage that should be template usage

#### Current Implementations

* https://github.com/wagtail/wagtail/blob/main/wagtail/documents/static_src/wagtaildocs/js/add-multiple.js#L14
* https://github.com/wagtail/wagtail/blob/main/wagtail/images/static_src/wagtailimages/js/add-multiple.js#L25
* https://github.com/wagtail/wagtail/blob/main/wagtail/images/templates/wagtailimages/multiple/add.html#L49-L74
* https://github.com/wagtail/wagtail/blob/main/wagtail/documents/templates/wagtaildocs/multiple/add.html#L49-L65

#### Important note about using `template`

* Read this before starting https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template
* Most important https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template#avoiding_documentfragment_pitfall
* Correct implementation: `const myClone = template.content.firstElementChild.cloneNode(true);`
* Note: jQuery `.html()` may be enough but do check that event listeners correctly get added

#### Related items

* https://github.com/wagtail/wagtail/issues/10034 (should be done **after** this issue)

**Comment by lb-** [comment]
Flagging as a good first issue, this will aid in prep work for Stimulus adoption & CSP compliance.

**Comment by RyanWalker277** [comment]
Hey @lb- ! Can I work on this?

**Comment by lb-** [comment]
@RyanWalker277 go for it. Please read the issue carefully and make sure you understand where the existing code is used. Feel free to ask questions. 

Also make sure you take the time to understand the nuances of using `template`

**Comment by RyanWalker277** [comment]
Ya sure! Will need some time to get myself familiar with stimulus.

**Comment by lb-** [comment]
@RyanWalker277 Stimulus knowledge is not a pre-requisute for this issue, but it will help a bit to understand the future goals. 

The main thing on this issue is ensuring the existing jQuery usage of the html inside the script element still works the same when we use content from inside a template element.

**Comment by RyanWalker277** [comment]
Understood @lb- ! The approach is clear to me now. Will try to close it as soon as possible. Thanks for the guidance.

**Comment by rishabhDev2700** [comment]
I just created a pull request for this issue. Sorry, when I started working on this issue no one was working on it.
