### ISSUE TITLE
Update Jest version to 29

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10043]
### Is your proposal related to a problem?

We are running into a few issues with unit tests and some features of `jsdom` that are not available for unit tests, it would be good to update from 26 to 29.

Read the release notes to ensure we cover anything that may cause breaking changes to our existing tests.

* https://jestjs.io/blog/2021/05/25/jest-27
* https://jestjs.io/blog/2022/04/25/jest-28
* https://jestjs.io/blog/2022/08/25/jest-29

**Comment by Lovelyfin00** [comment]
I keep getting this error after upgrading `ts-jest` `@types/jest` `jest` to version 27.

`Test suite failed to run`
    `The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    ReferenceError: document is not defined`

The way `jsdom` works is one of the breaking changes introduced in jest version 27
[https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults](https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults)

And their fix was to change the testEnvironment to `"testEnvironment": "jsdom"`

But Wagtail uses `puppeteer` for the testEnvironment which I thought would have fixed the issue.
[\wagtail\client\tests\integration\jest.config.js](https://github.com/wagtail/wagtail/blob/main/client/tests/integration/jest.config.js)
[\wagtail\client\tests\integration\PuppeteerEnvironment.js](https://github.com/wagtail/wagtail/blob/main/client/tests/integration/PuppeteerEnvironment.js)

Another way of fixing it was to add `@jest-environment` docblock at the top of the file which I did but I still got the same error

[https://jestjs.io/docs/configuration#testenvironment-string](https://jestjs.io/docs/configuration#testenvironment-string)

**Comment by chiggshiggs** [comment]
@Lovelyfin00 Are you working on this one? In case not, I would like to work on this one.

**Comment by lb-** [comment]
@chiggshiggs  feel free to give this ago - please only pick this up if you are somewhat familiar with Jest. Also ensure you review the comments above from Loveth.

**Comment by lb-** [comment]
Removing from Stimulus project as not a critical item for now.

**Comment by lb-** [comment]
PR up https://github.com/wagtail/wagtail/pull/10598
