### ISSUE TITLE
Dark mode for the admin interface

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#10056]
### Is your proposal related to a problem?

With all of Wagtail’s colors now defined from one set of CSS variables (#2943) – we can now embark on adding a dark theme to the admin!

### Describe the solution you'd like

@benenright will be working on the color palette and any other UI adjustments (theme switcher?). If possible, the dark theme should use the same number of shades per hue. Ideally, it’d also not require re-work of which hue is applied to which part of the UI. We’ll see!

We’ll also need:

- [x] The theme switcher (potentially leaving room for more than two themes? Dark, dark high contrast, light, light high contrast)
- [x] Support / documentation updates for color customisations
- [x] Adding the dark theme colors to our developer docs
- [x] Some of #8883

---

Implementation notes:

- Stimulus for toggle UI
- Cookies for state (no flash on first load).

**Comment by lb-** [comment]
Yay ! 🧛

Note: We would need to add some blocking JS to ensure we do not get a flash of the wrong styles. We could also use cookies on the template rendering to aid in setting up the 'default' class.

Also, a Stimulus controller would be a good way to implement the toggle, with the `afterLoad` static method running quite early in the browser JS lifecycle it could cover some of the flashing problems maybe.

https://stimulus.hotwired.dev/reference/controllers#trigger-behaviour-when-a-controller-is-registered

See other Wagtail dark mode adoption PRs for reference

* https://github.com/wagtail/sphinx_wagtail_theme/pull/217
* https://github.com/wagtail/guide/pull/197

**Comment by thibaudcolas** [comment]
For anyone interested in this, here is a static snapshot of Wagtail I’ve set up to experiment with color theming: https://static-wagtail-dark-theme-playground.netlify.app/admin/. This has a "⚙️ CSS" button which will reveal editable CSS. We can use this to edit CSS variables defining the colors used across the CMS.

@benenright will be experimenting with different color combinations, with the goal that the majority of UI components can be restyled with different colors only. Elements which are already "light text on dark background" (sidebar, tooltips) will likely warrant special treatment.

We’re also considering "High contrast light" and "High contrast dark" themes, which likely wouldn’t require much more work than just separate light/dark themes, while allowing us to meet WCAG AAA contrast requirements for people who need this.

---

For the theme switcher, the two options we’ve considered so far are:

- In the sidebar under the "username" expandable section. 
- In the "Account" profile page (potentially changing its link to "Account settings" so it’s more discoverable).

Compared to websites, we don’t think the switcher necessarily needs to be accessible prominently from all pages, but having it in the sidebar would allow people to preview the appearance of different themes right away.

**Comment by ShravaniAK** [comment]
Hello!
I am Shravani kaware, currently a sophomore pursuing a bachelor's in technology at India institute of information technology Vadodara. I am a tech enthusiast and love to learn and explore different areas of technology. I am good at javascript, typescript, React js, Next js, React native, material ui, chakra UI, etc.

I would like to work on this issue!

**Comment by thibaudcolas** [comment]
@ShravaniAK 👋 as you can see in the GitHub UI this is currently already assigned.
