### ISSUE TITLE
Permissions set on different pages for a group is interfering with each other.

### ISSUE THREAD

**Issue by sahilrl** [wagtail/wagtail#10063]
### Issue Summary

If we have two pages like below

```
root --> PageA
         PageB
```

If we set different Page permissions on different pages for Editors Group like below
- **add**  on **PageA**
- **add** & **edit**  on **PageB**

In the case above, the group user is able to edit **PageA** as well as any descendant of **PageA**

Also, if we have permissions like below
- **edit** on **PageA**
- **add** & **edit** on **PageB**

In this case, the group user is able to add child pages to **pageA**

**Comment by gasman** [comment]
Hi @sahilrl - which versions of Wagtail, Django and Python are you running?

**Comment by sahilrl** [comment]
Python 3.10.6
Django 4.1.6
Wagtail 4.1.1

**Comment by gasman** [comment]
I'm unable to replicate this issue as described. Starting from a fresh installation of Wagtail 4.1.1:

* Log in as superuser
* Under Home, create and publish child pages Page A and Page B
* Change the page permissions for the Editors group as follows:
  * remove permission from Root
  * Add "Add" permission for Page A
  * Add "Add" and "Edit" permissions for page B
* Create a user in the Editors group
* Log out and log in as that user
* From the Pages menu, navigate to Page A - user has the option to "Add child page" but not "Edit"
* Navigate to Page B - user has both options "Edit" and "Add child page"

There are some subtleties in the permission model as detailed in https://docs.wagtail.org/en/stable/topics/permissions.html#page-permissions that might cause different behaviour - for example, if you didn't remove the Root-level permission from the Editors group, or Page A was created by the editor-level user, then they would indeed be able to edit Page A.

I'll close this for now, but if you can provide a set of steps that reproduce the problem, we'll be happy to reopen and investigate further.

**Comment by sahilrl** [comment]
@gasman 
I indeed had **edit** permission set on Root Page.
Thank you for explaining in detail and looking into it!
