### ISSUE TITLE
sort menu

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#10068]
### Issue Summary
If you have 2 menu items. And move item 1 to position the sort does not save.
But if you move from pos to 1 the the sort saves.

-   Wagtail version: 4.2

**Comment by gasman** [comment]
Sorry, this description is too vague for us to work with - "menu items" can mean a lot of things in Wagtail. Please open a new issue, filling in all the details requested in the issue template, including steps to reproduce the issue starting from a new Wagtail instance.
