### ISSUE TITLE
Duplicate StreamField block ids when duplicating ListBlock

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#10073]
### Issue Summary

When duplicating a ListBlock, the child block identifiers are not updated, resulting in duplicate block ids on the page.

This is problematic because a lot of functionality in the CMS relies on those identifiers being unique (minimap UI, commenting, revisions, etc).

### Steps to Reproduce

1. On the bakerydemo, go to a Recipe page.
2. Duplicate the Ingredients or Steps block.
3. Inspect the HTML to see the `data-contentpath` being equal.

### Technical details

This seems to be present since quite a few versions ago.

**Comment by mgax** [comment]
I tried to reproduce the issue but failed, the block IDs in the copied block are different. Digging through the code, it seems the bug was fixed in https://github.com/wagtail/wagtail/pull/9108.

**Comment by thibaudcolas** [comment]
Thank you @mgax! Assigning to @albinazs to report back after attempting to reproduce this.

**Comment by thibaudcolas** [comment]
👍 can confirm this is no longer an issue, closing.
