### ISSUE TITLE
Add pre-commit config for curlylint

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#10079]
### Issue Summary

Our CircleCI config runs `curlylint`:

https://github.com/wagtail/wagtail/blob/4c4c88ace64a1431c0b421fa2a778bd2729d0310/.circleci/config.yml#L27

Our `make lint` config also runs `curlylint`:

https://github.com/wagtail/wagtail/blob/4c4c88ace64a1431c0b421fa2a778bd2729d0310/Makefile#L25

However, we don't have `curlylint` as part of our [pre-commit config](https://github.com/wagtail/wagtail/blob/4c4c88ace64a1431c0b421fa2a778bd2729d0310/.pre-commit-config.yaml), even though [it does support pre-commit](https://github.com/thibaudcolas/curlylint/blob/main/.pre-commit-hooks.yaml).

Let's add `curlylint` to our pre-commit config using the version we've specified in `setup.py`:

https://github.com/wagtail/wagtail/blob/4c4c88ace64a1431c0b421fa2a778bd2729d0310/setup.py#L65-L66

**Comment by laymonage** [comment]
Looks like the `djhtml` and `semgrep` versions in the pre-commit config are out-of-sync with the ones in `setup.py` as well, would be nice to update those.

**Comment by gasman** [comment]
@MJCoder15 As a contributor, your task is to find out that answer and confirm that it works. If we already knew the answer, there would be no open issue here.

**Comment by HimanshuGarg47** [comment]
#10081 I have merged suggested changes. It would be great to review again.
