### ISSUE TITLE
Missing StreamField block ids when creating blocks within ListBlock

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#10074]
### Issue Summary

When creating blocks within a ListBlock, we seem to be creating them with a `null` or `undefined` id. This is problematic for functionality that relies on those ids being unique (minimap UI, commenting, revisions, etc).

### Steps to reproduce

1. On the bakerydemo, go to a Recipe page.
2. Create a new block within the Ingredients or Steps block.
3. Inspect the HTML to see the `data-contentpath` being set to `null` (or minimap links using `null` as href).

### Technical details

Here is at least one occurrence of `id` being missing (should be the third array item): 

https://github.com/wagtail/wagtail/blob/3db5053bedb71aef38bb31057610721a59bdc05a/client/src/components/StreamField/blocks/ListBlock.js#L160

Compare with:

https://github.com/wagtail/wagtail/blob/3013c4b8b1934efb125dfefd5186f7c41b120896/client/src/components/StreamField/blocks/StreamBlock.js#L385

I have seen both `null` and `undefined` values, so wouldn’t be surprised if there were at least two problematic scenarios.

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by jams2** [comment]
I wrote https://github.com/wagtail/wagtail/pull/9108 to deal with duplicate block IDs not too long ago, possibly related?

**Comment by Srishti-j18** [comment]
Hi @thibaudcolas , If this issue is still open, may I work on it? I would be happy to contribute. I can aim to have a draft ready for review by the start or, at most, mid-December 2024. Would that be okay?

**Comment by thibaudcolas** [comment]
@Srishti-j18 please go for it! This has been open for quite a while, any improvements at any point are very welcome

**Comment by Srishti-j18** [comment]
Hi Thibaud, I have made some changes. Please let me know if any further modifications are needed.

**Comment by lb-** [comment]
![Image](https://github.com/user-attachments/assets/313d9750-b2a3-4721-b867-5e259d898c95)

Just confirming this issue, also running this script can output duplicate IDs.

```js
Object.entries(
  Array.from(document.querySelectorAll("[id]"))
    .map((v) => v.id)
    .reduce((acc, v) => {
      acc[v] = (acc[v] || 0) + 1;
      return acc;
    }, {})
)
  .filter(([, value]) => value > 1)
  .map(([key]) => key);
```
