### ISSUE TITLE
🎛️ Migrate `updateFooterSaveWarning` to a Stimulus Controller `w-messages`

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10091]
> ℹ️ **Part of the [Stimulus  🎛️ RFC 78](https://github.com/wagtail/rfcs/pull/78)**

### Is your proposal related to a problem?

In `client/src/entrypoints/admin/page-editor.js` there is an ad-hoc JavaScript implementation attached to the HTML `wagtail/admin/templates/wagtailadmin/pages/_unsaved_changes_warning.html` to show a warning if there are unsaved changes in the UI.

It would be good to have this code implemented as a Stimulus controller, so that there is no longer this `window.updateFooterSaveWarning` approach to make it more flexible and more testable.

### Describe the solution you'd like

Given the HTML in `wagtail/admin/templates/wagtailadmin/pages/_unsaved_changes_warning.html`...

```html
{% load wagtailadmin_tags i18n %}
<li class="footer__container footer__container--hidden" data-controller="w-unsaved" data-w-unsaved-hidden-class="footer__container--hidden" data-action="w-unsaved:update@window->w-unsaved#update">
    <div hidden data-unsaved-type="any" class="footer__save-warning footer__emphasise-span-tags">
        <div>
            <b hidden data-w-unsaved-target="edits">{% blocktrans trimmed %}You have <span>unsaved edits</span>{% endblocktrans %}</b>
            <b hidden data-w-unsaved-target="comments">{% blocktrans trimmed %}You have <span>unsaved comments</span>{% endblocktrans %}</b>
            <b hidden data-w-unsaved-target="all">{% blocktrans trimmed %}You have <span>unsaved edits</span> and <span>comments</span>{% endblocktrans %}</b>
            <p>{% trans 'Save the page before leaving' %}</p>
        </div>
    </div>
</li>

```

The existing behaviour should be preserved 100% compared to `client/src/entrypoints/admin/page-editor.js`.

As for the `window.updateFooterSaveWarning`, this should be changed to be a document dispatched event, so that the JS snippet in `wagtail/admin/templates/wagtailadmin/pages/create.html` (and edit.html) changes to;

```js
            enableDirtyFormCheck(
                '#page-edit-form',
                {
                    confirmationMessage: '{{ confirmation_message|escapejs }}',

                    {% if has_unsaved_changes %}
                        alwaysDirty: true,
                    {% endif %}
                    commentApp: window.comments.commentApp,
                    callback: (formDirty = false, commentsDirty = false) => document.dispatchEvent('w-unsaved:update', new CustomEvent({ detail { commentsDirty, formDirty }})),
                }
            );
```

#### Controller specification

* `class` hidden - replaces the hard-coding of `footer__container--hidden` in the js - see https://stimulus.hotwired.dev/reference/css-classes
* `target` edits - label target element for edits being dirty
* `target` comments - label target element for comments being dirty
* `target` all - the label element if all items are flagged
* `method` `update` (maybe a better name) this essentially just does the update as per the current JS implementation
* Values - we could store the two dirty checks as values if we want, we may want to use a data attribute to store 'active' or 'visible' though.

### Describe alternatives you've considered

* Leave as is.

### Additional context

- This is part of a larger goal to migrate to Stimulus.
- Longer term, this will set us up to tackle `enableDirtyFormCheck` probably as part of the same controller, from there we can make it easier to tackle #8453
- Not a good first issue but good for anyone semi-confident with Jest testing, JavaScript and who has taken the time to read the Stimulus docs in full.
- This is also part of a larger goal to avoid `wagtail/admin/templates/wagtailadmin/pages/_editor_js.html` being used everywhere and minimise global usage in JS See #2936
- Might be able to take a look at fixing #7188 in this issue or at least getting closer
- See https://github.com/wagtail/wagtail/tree/main/client/src/controllers for existing controller implementations

**Comment by suyash5053** [comment]
I'm researching the thing and have started working for the issue.

**Comment by lb-** [comment]
@suyash5053 go for it, you will need to read up on Stimulus and also look at how we have implemented other controllers in the src/controllers folder. 

Start small and work your way towards the goal, please ask questions on this issue if you get stuck. Even if that means putting code snippets with questions in the issue. 

Importantly, make sure you understand how the existing code is used in full so you can reproduce the behaviour before and after. Hence why we want to add unit tests - so we can have more confidence on functionality in the future.

**Comment by Hussain0520** [comment]
Hey @lb- , Can you tell me where can I find other stimulus controllers code?

**Comment by lb-** [comment]
> Hey @lb- , Can you tell me where can I find other stimulus controllers code?

https://github.com/wagtail/wagtail/tree/main/client/src/controllers

**Comment by Hussain0520** [comment]
Can I create a new Controller for this?

**Comment by lb-** [comment]
@Hussain0520 you will need to dig into some docs and code to work that out, here's some recommendations for reading. 

- Stimulus documentation (do read the whole thing if you haven't yet) https://stimulus.hotwired.dev/
- Wagtail's Stimulus controller creation guide - https://docs.wagtail.org/en/latest/contributing/ui_guidelines.html#stimulus
- Watch the webinar about Stimulus in Wagtail - [Introduction to Stimulus in Wagtail for contributors (video)](https://youtu.be/5WS7B8R0x0U)
- Read through the changes in this PR for a bit of a look at what's involved https://github.com/wagtail/wagtail/pull/10062/files or https://github.com/wagtail/wagtail/pull/10182/files

Hope that helps.

**Comment by Hussain0520** [comment]
Is there any other option apart from creating a new Controller? Like which implemented controller i can use for this implementation.

**Comment by lb-** [comment]
@Hussain0520  ok did  bit of a mock idea, I think this could work. Please note I have NOT tested, this, if you are keen it will be up to you get this functional in a PR.

The HTML would look similar to `w-messages` usage in `wagtail/admin/templates/wagtailadmin/base.html`
```html
{% load wagtailadmin_tags i18n %}
<li
    class="footer__container footer__container--hidden"
    role="status"
    data-controller="w-messages"
    data-action="w-unsaved:show@document->w-messages#add w-unsaved:hide@document->w-messages#clear"
    data-w-messages-clear-delay-value="1050"
    data-w-messages-clear-param="true"
    data-w-messages-show-class="footer__container--visible"
    >
    <div class="footer__save-warning footer__emphasise-span-tags" hidden data-w-messages-target="container"></div>
    {% trans 'Save the page before leaving' as generic_save_page_message %}
    <template data-w-messages-target="template" data-type="edits">
        <div>
            <b>{% blocktrans trimmed %}You have <span>unsaved edits</span>{% endblocktrans %}</b>
            <p>{{ generic_save_page_message }}</p>
        </div>
    </template>
    <template data-w-messages-target="template" data-type="comments">
        <div>
            <b>{% blocktrans trimmed %}You have <span>unsaved comments</span>{% endblocktrans %}</b>
            <p>{{ generic_save_page_message }}</p>
        </div>
    </template>
    <template data-w-messages-target="template" data-type="all">
        <div>
            <b>{% blocktrans trimmed %}You have <span>unsaved edits</span> and <span>comments</span>{% endblocktrans %}</b>
            <p>{{ generic_save_page_message }}</p>
        </div>
    </template>
</li>
```

Observe we have three templates; for the three variants of message (aka warning) to show), we also have where to put the content (in the `data-w-messages-target="container"`). Additionally we have a global event listener added `data-action="w-unsaved:update@document->w-messages#add"` so that other code can 'trigger' the message.

The styling would probably need to be revised to allow for a 'showing' class instead of a 'hiding' class.

As for the controller  in `client/src/controllers/MessagesController.ts`, it would need some added functionality.

* `add` method will need to be able to pull out whether it should clear from the event detail AND event params (read up on Stimulus action params).
  * `const { clear = event.params.clear || false, text = '', type } = event?.detail || {};` (this should get you close)
  * Additionally, will need to handle the delayed clearing of things.
* Likely need a new `clearDelay` value that defaults to `0` (backwards compatibility), then this would be changed in the value.
* Need to ensure that the `hidden` attribute on the container target can be conditionally added/removed based on content changes.
* The `clear` method would need some solid work, probably needs to return a promise so that new additions can be done after clearing is completed. It would also need to ensure the right classes are removed (see show class).

Finally, the callback would need to now dispatch an event, here is a rough idea of what this could look like.

```
                    callback: function(formDirty, commentsDirty) {
                        const anyDirty = formDirty || commentsDirty;
                        const allDirty = formDirty && commentsDirty;
                        // one of edits, comments, all
                        const type = allDirty ? 'all': 'comments' ; // etc - need to work this out.
                        const detail = { type };
                        document.dispatchEvent(new CustomEvent( anyDirty ? 'w-unsaved:show': 'w-unsaved:hide',  { detail } ));
                    }
```

An alternative approach is to put a replace of the current global `updateFooterSaveWarning` in the messages controller `afterLoad` method. This way we can just replace this completely correctly later when `enableDirtyFormCheck` is done.

**Comment by Hussain0520** [comment]
@lb- I'll look into it and get back to you

**Comment by Hussain0520** [comment]
Hey @lb- , so I went through the documentation and the existing controllers and this is what I was able to make. Tell me if its aligned to the issue and that my understanding of the problem is proper.

`import { Controller } from '@hotwired/stimulus';

export class DempController extends Controller<HTMLElement> {
  static targets = ["edits", "comments", "all"];
  static classes = ["hidden"];

  initialize() {
    this.hiddenClass = this.hasHiddenClass ? this.hiddenClass : "hidden";
    this.update = this.update.bind(this);
    this.enableDirtyFormCheck();
  }

  enableDirtyFormCheck() {
    const { confirmation_message, has_unsaved_changes } = this.data;
    enableDirtyFormCheck("#page-edit-form", {
      confirmationMessage: confirmation_message,
      alwaysDirty: has_unsaved_changes,
      commentApp: window.comments.commentApp,
      callback: (formDirty = false, commentsDirty = false) => {
        const detail = { commentsDirty, formDirty };
        this.update(new CustomEvent("w-unsaved:update", { detail }));
      },
    });
  }

  update(event) {
    const { commentsDirty, formDirty } = event.detail;
    if (commentsDirty && formDirty) {
      this.showAll();
    } else if (commentsDirty) {
      this.showComments();
    } else if (formDirty) {
      this.showEdits();
    } else {
      this.hideAll();
    }
  }

  showEdits() {
    this.showTarget("edits");
  }

  showComments() {
    this.showTarget("comments");
  }

  showAll() {
    this.showTarget("all");
  }

  hideAll() {
    this.hideTarget("edits");
    this.hideTarget("comments");
    this.hideTarget("all");
  }

  showTarget(target) {
    this.findTarget(target).classList.remove(this.hiddenClass);
  }

  hideTarget(target) {
    this.findTarget(target).classList.add(this.hiddenClass);
  }
}`

**Comment by lb-** [comment]
@Hussain0520 - sorry but that controller code is not really close to the goal. 

Please have another read of my comment above. As per your idea of simply reusing an existing controller, I think this could work with the MessageController.

I recommend taking a look at the message controller code and usage, and at the example HTML above. Give it another go and see if it makes sense. 

Additionally, this code should no call `enableDirtyFormCheck` - that will be a different controller in the future.

Thanks for giving this a go and getting some feedback, hope this direction helps you out a bit.

**Comment by Hussain0520** [comment]
Okay @lb- thanks for the feedback, I'll take a look at it again and try to implement my code in existing messagecontroller of the demo  HTML code you provided yesterday. I might require some time but I'll get back to you asap.

**Comment by Hussain0520** [comment]
Hey @lb- , here is my new code can you check and tell me the corrections and if there is any progress.

```
import { Controller } from "stimulus";

export default class extends Controller {
  static targets = ["container", "template"];
  static values = { clearDelay: Number };

  connect() {
    document.addEventListener(
      "w-unsaved:update",
      this.add.bind(this),
    );
  }

  add(event) {
    const { clear = event.params.clear || false, text = '', type } = event?.detail || {};
    const template = this.templateTarget.querySelector(`[data-type="${type}"]`);
    const message = template.content.cloneNode(true);
    message.querySelector("p").textContent = text;
    this.containerTarget.appendChild(message);

    if (clear) {
      setTimeout(() => {
        this.clear().then(() => {
          this.add(event);
        });
      }, this.clearDelayValue);
    }
  }

  clear() {
    return new Promise((resolve) => {
      this.containerTarget.classList.remove("footer__container--visible");
      setTimeout(() => {
        this.containerTarget.innerHTML = "";
        this.containerTarget.hidden = true;
        resolve();
      }, this.clearDelayValue);
    });
  }

  show() {
    this.containerTarget.hidden = false;
    this.containerTarget.classList.add("footer__container--visible");
  }

  hide() {
    this.containerTarget.classList.remove("footer__container--visible");
    this.containerTarget.hidden = true;
  }

  handleEvent(event) {
    const { formDirty, commentsDirty } = event.detail;
    const anyDirty = formDirty || commentsDirty;
    const allDirty = formDirty && commentsDirty;
    const type = allDirty ? "all" : commentsDirty ? "comments" : "edits";
    const detail = { type };
    const eventName = anyDirty ? "w-unsaved:show" : "w-unsaved:hide";
    document.dispatchEvent(new CustomEvent(eventName, { detail }));
  }
}

```

**Comment by lb-** [comment]
@Hussain0520 great stuff. This is getting closer, a few points of note. 

1. You should not need to add he event listener yourself on connect, this is something that stimulus can do with data-action attributes (in the html)
2. HandleEvent method - this should not be a an instance method but rather something that gets created by the afterLoad static method. See here for a similar approach https://github.com/wagtail/wagtail/blob/main/client/src/controllers/ProgressController.ts#L53 or see my other PR code that is similar also in preparing a global window.foo function https://github.com/lb-/wagtail/blob/feature/10100-stimulus-taggit/client/src/controllers/TagController.ts#L49
3. A reminder that you won't be creating a new controller but rather enhancing the existing MessagesController https://github.com/wagtail/wagtail/blob/main/client/src/controllers/MessagesController.ts

Next steps are probably to start seeing if you can get this controller modification working with the html changes also in your local Dev environment.

**Comment by Hussain0520** [comment]
Are there any steps I need to follow for local dev env setup?

**Comment by lb-** [comment]
@Hussain0520 
See section 5 here https://github.com/wagtail/wagtail/issues/10070
Or see specific docs for development set up here https://docs.wagtail.org/en/latest/contributing/developing.html

Please reach out on Slack if you need support `#new-contributors` - O that this issue can stay focused on the specific solution.

**Comment by Hussain0520** [comment]
What's the slack channel name?

**Comment by Hussain0520** [comment]
Hey @lb- does it code align with the changes that you mentioned after the previous version of the code?

`import { Controller } from '@hotwired/stimulus';

export default class extends Controller {
  static targets = ["container", "template"];
  static values = { clearDelay: Number };

 static afterLoad() {
    window.handleUnsavedEvent = (event) => {
      const { formDirty, commentsDirty } = event.detail;
      const anyDirty = formDirty || commentsDirty;
      const allDirty = formDirty && commentsDirty;
      const type = allDirty ? "all" : commentsDirty ? "comments" : "edits";
      const detail = { type };
      const eventName = anyDirty ? "w-unsaved:show" : "w-unsaved:hide";
      document.dispatchEvent(new CustomEvent(eventName, { detail }));
    };
  }

  add(event) {
    const { clear = event.params.clear || false, text = '', type } = event?.detail || {};
    const template = this.templateTarget.querySelector(`[data-type="${type}"]`);
    const message = template.content.cloneNode(true);
    message.querySelector("p").textContent = text;
    this.containerTarget.appendChild(message);

    if (clear) {
      setTimeout(() => {
        this.clear().then(() => {
          this.add(event);
        });
      }, this.clearDelayValue);
    }
  }

  clear() {
    return new Promise((resolve) => {
      this.containerTarget.classList.remove("footer__container--visible");
      setTimeout(() => {
        this.containerTarget.innerHTML = "";
        this.containerTarget.hidden = true;
        resolve();
      }, this.clearDelayValue);
    });
  }

  show() {
    this.containerTarget.hidden = false;
    this.containerTarget.classList.add("footer__container--visible");
  }

  hide() {
    this.containerTarget.classList.remove("footer__container--visible");
    this.containerTarget.hidden = true;
  }
}
`

**Comment by lb-** [comment]
PR up for full implementation of this https://github.com/wagtail/wagtail/pull/10835
