### ISSUE TITLE
Downloading form submissions spreadsheet/csv with filters applied

### ISSUE THREAD

**Issue by KIRA009** [wagtail/wagtail#10101]
## Problem
I came across a situation where the client wants to download a list of submissions with the same filters applied when viewing the submissions in the admin. Digging through the code, I identified the source of this issue.

https://github.com/wagtail/wagtail/blob/0187a1494bc56bab4592dc0d3d314121edf590d0/wagtail/contrib/forms/templates/wagtailforms/submissions_index.html#L86

This is used by [`SubmissionsListView`](https://github.com/wagtail/wagtail/blob/0187a1494bc56bab4592dc0d3d314121edf590d0/wagtail/contrib/forms/views.py#L177)

The mixin class [`SpreadsheetExportMixin`](https://github.com/wagtail/wagtail/blob/0187a1494bc56bab4592dc0d3d314121edf590d0/wagtail/admin/views/mixins.py#LL128) has a property [`xlsx_export_url`](https://github.com/wagtail/wagtail/blob/0187a1494bc56bab4592dc0d3d314121edf590d0/wagtail/admin/views/mixins.py#L282) which does include the filter parameters from the query string in the url, but this isn't used in the `submissions_index` template.

## Alternative solutions
The current alternative is to overwrite the entire `submissions_index` template and just change these two specific urls (for xlsx and csv), but this isn't very maintainable.

## Proposed solution
Make use of the `xlsx_export_url` and the `csv_export_url` instead of hardcoding the urls in the template.

**Comment by lb-** [comment]
Labelling as enhancement, I think this would be a nice feature and seems pretty intuitive.

**Comment by suyash5053** [comment]
A possible solution can be updating https://github.com/wagtail/wagtail/blob/0187a1494bc56bab4592dc0d3d314121edf590d0/wagtail/contrib/forms/templates/wagtailforms/submissions_index.html#L86 
as `<a href="{{ view.xlsx_export_url }}{{ request.META.QUERY_STRING }}" class="button button-small">Export to spreadsheet</a>` and a similar approach can be used for `csv_export_url` .
@lb- review it so that I can start the work.
@KIRA009 is this the thing you are asking?

**Comment by lb-** [comment]
@suyash5053  this looks ok, I am not sure we will need to add the `request.META.QUERY_STRING` as it looks like the `xlsx_export_url` will include this, but please validate either way.

If you feel confident to prepare a PR along these lines and also write unit tests for it, feel free to give this a go.

You will need to add some tests in the test block `TestFormsSubmissionsList` - see https://github.com/wagtail/wagtail/blob/main/wagtail/contrib/forms/tests/test_views.py#L330

Either appending to some of the tests inside or adding new tests in that class.

**Comment by lb-** [comment]
Closed and fixed via https://github.com/wagtail/wagtail/pull/10194

This should be in the 5.0 release
