### ISSUE TITLE
outdated dependency on draftjs-exporter (by 3 years)

### ISSUE THREAD

**Issue by jorenham** [wagtail/wagtail#10106]
The [draftjs_exporter](https://github.com/springload/draftjs_exporter) dependency is restricted to be <3.0, which officially has no support python>3.7. 
Given that 3.0 has been out for over 3 years, and that it's currently at 5.0 (which has python 3.11 support), I guess it could be worth considering upgrading.

**Comment by thibaudcolas** [comment]
@jorenham 👋 thanks for reporting this. Have you encountered any issues with a specific Python version?

**Comment by jorenham** [comment]
Even though I'm running python-poetry, the draftjs-exporter python restriction seems to be only a formal one; poetry let's me install wagtail on python 3.11 without complaining. 
Aside from the classifiers, there don't appear to be any explicit python runtime version requirement in the [setup.py](https://github.com/springload/draftjs_exporter/blob/v2.1.7/setup.py) either.

**Comment by gasman** [comment]
> There is no way (that I’m aware of) to define Python version support in a `setup.py`.

FWIW: https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires :-)

**Comment by lb-** [comment]
Removing unconfirmed and bug label. Not sure if there is a clear direction or plan here but for now it appears to not be causing active problems as is.

**Comment by jorenham** [comment]
@lb- I agree that the relevance of the 'bug' label is questionable. But apart from the Python version classifiers. there have been many improvements to draftjs-exporter since [v2.1.7](https://github.com/springload/draftjs_exporter/releases/tag/v2.1.7), most of which I believe to be relevant to Wagtail, e.g.

- several performance improvements ([v3.0.0](https://github.com/springload/draftjs_exporter/releases/tag/v3.0.0) and [v3.0.1](https://github.com/springload/draftjs_exporter/releases/tag/v3.0.1))
- type annotations of the public API ([v3.0.0](https://github.com/springload/draftjs_exporter/releases/tag/v3.0.0))
- support for custom ordering of html attributes and inline styles ([v4.0.0](https://github.com/springload/draftjs_exporter/releases/tag/v4.0.0))
- more sensical escaping of quotes and double quotes ([v4.0.0](https://github.com/springload/draftjs_exporter/releases/tag/v4.0.0))
- wheel distributions ([v4.1.0](https://github.com/springload/draftjs_exporter/releases/tag/v4.1.0))
- a higher version upper bound for `html5lib` ([v4.1.1](https://github.com/springload/draftjs_exporter/releases/tag/v4.1.1))
- the `string_compat` engine for maximum output stability ([v5.0.0](https://github.com/springload/draftjs_exporter/releases/tag/v5.0.0))

**Comment by lb-** [comment]
Thanks @jorenham - I'm not super familiar with this area of code. I think a PR would be welcome, however, there may be a reason we are not yet supporting that newer version - @thibaudcolas ?

**Comment by Stormheg** [comment]
Wagtail 6.0 will support draftjs-exporter v5.

See commit https://github.com/wagtail/wagtail/commit/de70673bee4816d2382fdd8b93f04acde5fed20
