### ISSUE TITLE
🎛️ Migrate Breadcrumbs to a Stimulus Controller `w-breadcrumbs`

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10118]
> ℹ️ **Part of the [Stimulus  🎛️ RFC 78](https://github.com/wagtail/rfcs/pull/78)**

### Is your proposal related to a problem?

The current implementation for breadcrumbs is ad-hoc JavaScript, to support a more robust implementation that is more flexible it would be good to migrate this to Stimulus.

### Describe the solution you'd like

Migrate the existing implementation [`client/src/includes/breadcrumbs.js`](https://github.com/wagtail/wagtail/blob/main/client/src/includes/breadcrumbs.js) to a Stimulus Controller so that it can be used with HTML as follows (roughly).

```html
<div
    class="w-breadcrumb ...100-classes"
    data-controller="w-breadcrumbs" // replaces data-breadcrumb-next
    data-action="keydown.esc@document->w-breadcrumbs#collapse mouseleave@document->w-breadcrumbs#hover"
    data-w-breadcrumbs-expanded-value="false" // optional (state) - value used to store whether the breadcrumbs are expanded
    data-w-breadcrumbs-fixed-value="false" // optional (state) - value used to store whether the user has opted to keep it open
    data-w-breadcrumbs-header-value="header" // optional - replaces data-header-selector="header", defaults to 'header' - for the hover zone target
    data-w-breadcrumbs-max-width-class="w-max-w-4xl" // replaces the hard-coded cssClass.maxWidth in the JS
>
    <button
        class="...classes"
        type="button"
        aria-label="{% trans 'Toggle breadcrumbs' %}"
        aria-expanded="false"
        data-w-breadcrumbs-target="toggle"
        data-action="mouseenter->w-breadcrumbs#hover mouseleave->w-breadcrumbs#hover keydown.enter->w-breadcrumbs#toggle keydown.space->w-breadcrumbs#toggle w-breadcrumbs#toggle"
    >
        {% icon name="breadcrumb-expand" classname="w-w-4 w-h-4" %}
    </button>
    <div>
        <nav>
            <ol>
                {% for item in items %}
                <li class="...classes" hidden data-w-breadcrumbs-target="item" //this replaces data-breadcrumb-item>
                    <a
                        class="{{ breadcrumb_link_classes }}"
                        href="{% url 'wagtailsnippets:index' %}"
                    >
                        {% trans "Snippets" %}
                    </a>
                    {% icon name="arrow-right" classname=icon_classes %}
                </li>
                {% endfor %}
            </ol>
        </nav>
    </div>
</div>
```

There is some nuanced behaviour of the breadcrumbs but generally there is the 'manual click to keep expanded or close' and then the 'hover to make it expand while in the hover zone'.

The new Controller should be written in TypeScript and replace the current includes implementation and also have the same unit test coverage.

Finally, remember that there are duplicate breadcrumb implementations in HTML in the following files;

* [`wagtail/admin/templates/wagtailadmin/shared/breadcrumbs.html`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/breadcrumbs.html)
* [`wagtail/snippets/templates/wagtailsnippets/snippets/headers/_base_header.html](https://github.com/wagtail/wagtail/blob/main/wagtail/snippets/templates/wagtailsnippets/snippets/headers/_base_header.html)`
* Additionally the storybook will need updating - [`wagtail/admin/templates/wagtailadmin/shared/breadcrumbs.stories.tsx`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/breadcrumbs.stories.tsx)

There are two events that get dispatched `'wagtail:breadcrumbs-expand'` & `'wagtail:breadcrumbs-collapse'` - these can be easily done using the `this.dispatch('expand')` but the event name will be `'w-breadcrumbs:expand'`. This will require an update to any listeners to these events and an update in the documentation.

### Describe alternatives you've considered

* Leave as is, while this code is a lower risk area (no Script tags), it is a great candidate

### Additional context

* While not critical, please consider the #9666 items raised about the breadcrumbs hover interaction, along with a way to ensure this hover behaviour is off (and breadcrumbs are expanded) by default #9498
* #9227
* #8767
* #8037

**Comment by lb-** [comment]
@PaarthAgarwal  - all yours if you wanted to give this a go.

**Comment by suyash5053** [comment]
In order to migrate existing `breadcrumbs.js` to stimulus we have to install stimulus and typescript dependencies and then create a typescript file for the same and then we have to update the html as well as css.

**Comment by PaarthAgarwal** [comment]
> @PaarthAgarwal - all yours if you wanted to give this a go.

I'm on it

**Comment by Lovelyfin00** [comment]
> In order to migrate existing `breadcrumbs.js` to stimulus we have to install stimulus and typescript dependencies and then create a typescript file for the same and then we have to update the html as well as css.

No you don't
All the dependencies for Stimlus is already in the core code

**Comment by lb-** [comment]
New PR up https://github.com/wagtail/wagtail/pull/10793
