### ISSUE TITLE
Adopt `pageurl` tag in all Wagtail admin URL usage

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10125]
### Is your proposal related to a problem?

As per the documentation recommendations, the tag `page_url` is preferred over `page.url` and it would be good to ensure our existing code uses this where appropriate.

* See https://docs.wagtail.org/en/stable/advanced_topics/performance.html#page-urls

### Describe the solution you'd like

* Find all usages of `{{ page.url }}` (or similar) in template tags and replace with the template tag usage `{% page_url ...`
* Example: `wagtail/admin/templates/wagtailadmin/shared/page_status_tag_new.html`
* Example: `wagtail/admin/templates/wagtailadmin/chooser/tables/page_title_cell.html`
* Example: `wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html` (note the different syntax `{% with page_url=page.url %}`

### Describe alternatives you've considered

Leave as is, this code has been there for a while but would be good to clean up.

### Additional context

* See #9361
* note: please use the `pageurl` tag (`{% pageurl page as page_url %}` as it make use of the request and benefit from cached site parts and more. _Originally posted by @zerolab in https://github.com/wagtail/wagtail/pull/9721#discussion_r1111873249_

**Comment by GeekGawd** [comment]
Cool! Seems like a simple task, will make a quick pull request...

**Comment by satvikvash** [comment]
Hi @lb- , while working on this issue I found one usage of `{{section_page.url}}`, do I have to change this usage?

**Comment by satvikvash** [comment]
Hi @GeekGawd , I have almost resolved the issue, so I will create a pull request if that is okay with you.

**Comment by GeekGawd** [comment]
@satvikvash Coolio! but atleast next time do inform me... as I was also making progress on the issue throughout the week...

**Comment by salty-ivy** [comment]
> @satvikvash Coolio! but atleast next time do inform me... as I was also making progress on the issue throughout the week...

Agree !! should give at-least 2-3 days of time before taking over, even in case you have solved it you should definitely discuss/ask the former.

Cc: @satvikvash  @GeekGawd
