### ISSUE TITLE
Document the built in way to use trans/translate in a Django template filter

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10126]
**UPDATE: This is now mostly a documentation piece, the pattern (see comments) is good and maybe a PR with documentation updates AND a few changes to existing templates is all that is needed.**

### Is your proposal related to a problem?

We often find ourselves having to build translated values with `{% trans ... as foo %}`, not a fragment but for use in some other variable passed into a template.

As we adopt more shared template tags, this is becoming a bit of code smell and it would be great to be able to simplify this approach.

### Describe the solution you'd like

It would be great if we could do something like the following:

```html
{% status url=page_url title="Visit the live page"|trans hidden_label="Current page status"|trans classname="primary" %}
```

This would then be picked up by the translation system as if we had used

```html
{% trans "Current page status" as hidden_label %}
{% trans "Visit the live page" as status_label %}
{% status url=page_url title=status_label hidden_label=hidden_label classname="primary" %}
```

### Describe alternatives you've considered

Leave as is, keep declaring translate blocks /content in the vanilla Django way.

### Additional context

* _Originally posted by @gasman in https://github.com/wagtail/wagtail/issues/9721#issuecomment-1351503209_

**Comment by gasman** [comment]
A potential showstopper that's just occurred to me (sorry!) - we need `./manage.py makemessages` to be able to extract those strings from the template, and I'm not sure that mechanism is hackable enough to set up our own pattern matching.

**Comment by lb-** [comment]
Yeah I thought about that - but surely there is a way :)

**Comment by AceHunterr** [comment]
Hey... I looked into the issue and the details and I've opened a PR ... 
I had some problems as well that I've mentioned in my PR... it'd be great help if I can get some key points for the problems I'm facing

Kindly review my PR and let me know the further changes to be done.

**Comment by lb-** [comment]
Did some digging on the open PR and maybe this is actually supported out of the box in Django. 

### Docs snippets

https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#string-literals-passed-to-tags-and-filters

```py
{% some_tag _("Page not found") value|yesno:_("yes,no") %}
```


### Example usage for above scenarios

```html
{% status url=page_url title=_("Visit the live page") hidden_label=_("Current page status") classname="primary" %}
```

Have not tested but maybe see if this could work without any custom code @AceHunterr (find a status tag, e.g. on the dashboard page, replace the template tag and see if it does work). 

We would also need to ensure this works with make translations and what differences we may see in the .po files if any.

**Comment by loicteixeira** [comment]
Sidenote, the `trans` and `blocktrans` tags were renamed `translate` and `blocktranslate` in [Django 3.1](https://docs.djangoproject.com/en/4.1/releases/3.1/#templates) for inclusivity (similarly to the `master` to `main` change on GitHub). Although we haven't updated the codebase accordingly yet, if we are creating a filter, best go with the new naming.

**Comment by AceHunterr** [comment]
So @lb- what you mentioned is using "gettext as _" and then applying it directly without any custom filter?

Surely I'll give that a go and update my PR

**Comment by lb-** [comment]
@AceHunterr ok I have done a bit of digging, I do not think we need to add any new template filter.

Note: To test how the translations get built you will need to run `/scripts/rebuild-translation-sources.sh` (you may need to install gettext e.g. `apt-get install gettext`). https://github.com/wagtail/wagtail/wiki/Managing-Wagtail-translations#generating-new-source-files-for-translation

In the file [`wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html) we have the following HTML:


```html
{% load i18n wagtailadmin_tags %}
{% if page.live %}
    {% with page_url=page.url %}
        {% trans "Current page status:" as status_hidden_label %}
        {% if page_url is not None %}
            {% trans 'Visit the live page' as status_title %}
            {% status page.status_string url=page_url title=status_title hidden_label=status_hidden_label classname="primary" attrs='target="_blank" rel="noreferrer"' %}
        {% else %}
            {% status page.status_string hidden_label=status_hidden_label classname="primary" %}
        {% endif %}
    {% endwith %}
{% else %}
    {% status page.status_string hidden_label=status_hidden_label %}
{% endif %}
```

We can change this to the following, which is much more condensed and hopefully less prone to typos, we do have to duplicate the current page status label for screen readers here but we could still keep that 'above'.

```
{% load i18n wagtailadmin_tags %}
{% if page.live %}
    {% with page_url=page.url %}
        {% comment %}Translators: Keep trailing comma{% endcomment %}
        {% status page.status_string url=page_url title=page_url|yesno:_("Visit the live page,") hidden_label=_("Current page status:") classname="primary" attrs=page_url|yesno:"target='_blank' rel='noreferrer'," %}
    {% endwith %}
{% else %}
    {% status page.status_string hidden_label=_("Current page status:") %}
{% endif %}
```

This gives us almost the exact same `.po` file (with the comment about the trailing comma as follows:

```
#. Translators: Keep trailing commas
#: templates/wagtailadmin/shared/page_status_tag.html:5
msgid "Visit the live page,"
msgstr ""

#: templates/wagtailadmin/shared/page_status_tag.html:5
#: templates/wagtailadmin/shared/page_status_tag.html:8
msgid "Current page status:"
msgstr ""
```

I think this is a solid approach and if you think this makes sense and want to do a PR for this file and a small subset of other files it may be good to provide a pattern to build upon. Alternatively you could just make this one change and add some documentation `docs/contributing/translations.md` with an example of how to use this pattern & a link to the Django docs.

@loicteixeira  - any thoughts on all this?

**Comment by lb-** [comment]
Yep

**Comment by AceHunterr** [comment]
> Wait. Not variable but rather the string. It's important to understand that the translation system does not have any way to translate dynamic values and know the base string in advance. So you either pass a translated value prepared in Python to the template OR translate it within the template.
> 
> So `{% tag _("My String") %}` for example.

Oh ok cool... so not any value but only the strings... Got it

**Comment by loicteixeira** [comment]
I'm surprised it works, but I guess `makemessages` command (used by the rebuild translation script) does indeed [inspect HTML files by default](https://docs.djangoproject.com/en/4.1/ref/django-admin/#cmdoption-makemessages-extension) and probably looks for all patterns in all file types.

That being said, does it also properly translate when being displayed? Django is known for limiting what you can do in templates, and here we would use a python function which isn't even in scope? I'm having a hard time wrapping my head around how the tag token parser would interpret this 😕 

Also, you show that it keeps comments, but what if I want to add a comment on the second string instead? Do we simply fall back to a separate `translate/blocktranslate` tag? I think that's fine, but I'm just trying to find the limitation of the approach before we commit to it.

**Comment by lb-** [comment]
@loicteixeira 

* Does it properly translate - it is a documented feature of Django since v1 so I would assume so, I can do a manual test though.
* If you are talking about the yesno syntax, this is treated as any kind of string with the `,`  separator.
* I do not think it would be able to associate the comment in this granular way based on my digging, so if we needed that level of comment nuance we would have to reach out for a different approach. However, we use either none or almost no translator comments today so we could just make that nuance clear in our own developer documentation.

I guess the core goal here is to have our translations 'in situ', without having this interim variable and I think this approach from Django fits the bill.

We could of course say we do not want this and the current way of declaring and then passing into the template tag is actually preferred. As noted in my example above, in some cases it can lead to the translation being written twice if we use it as our only method.

I would see this as a 'recommended approach' and not a 'required approach', it us unlikely we would ever enforce it at any CI level.

**Comment by lb-** [comment]
Just manually confirmed to be 100% sure, the translation approach works fine in actual other languages. I think the use of the trailing comma is probably not worth the compact code benefits, it's likely to easily break if translators are not careful.

<img width="936" alt="Screenshot 2023-03-18 at 6 57 24 am" src="https://user-images.githubusercontent.com/1396140/226045537-f15da82c-b905-4fb6-92f0-38d3e78d9de9.png">


```html
{% load wagtailcore_tags %}
{% load i18n wagtailadmin_tags %}
{% if page.live %}
    {% pageurl page as page_url %}
    {% if page_url is not None %}
        {% status page.status_string url=page_url title=_("Visit the live page") hidden_label=_("Current page status:") classname="primary" attrs='target="_blank" rel="noreferrer"' %}
    {% else %}
        {% status page.status_string classname="primary" %}
    {% endif %}
{% else %}
    {% status page.status_string %}
{% endif %}
```

I will put this change in #10157 PR - because I actually found that the original status tag work introduced a subtle bug where `hidden_label` would be added incorrectly and `title` would be added when not used on draft pages.

**Comment by loicteixeira** [comment]
Thank you for testing this. I didn't know that we could use `_()` in templates as well (I thought some black magic was at play), but since it's [officially supported](https://docs.djangoproject.com/en/4.1/topics/i18n/translation/#string-literals-passed-to-tags-and-filters), I have no issue with it.
As for translating twice the same string, although I don't have a benchmark ready, I would bet it won't make a meaningful difference.
So let's go 🚀

**Comment by lb-** [comment]
**UPDATE: This is now mostly a documentation piece, the pattern (see comments) is good and maybe a PR with documentation updates AND a few changes to existing templates is all that is needed.**
