### ISSUE TITLE
Add ability to support `attrs` in `Panel` and by extension `FieldPanel`

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10133]
### Is your proposal related to a problem?

With the adoption of Stimulus under way and plans for developer facing documentation (non-contributors) coming up soon, it would be good to be able to provide a concise way to allow for HTML attributes to be easily passed from `Panel`/`FieldPanel` through to the HTML template.

This would allow for official support for much simpler customisations where using/adding data attributes is needed (e.g. `data-controller="custom-controller"`) or even common requirements like aria or ID attributes.

### Describe the solution you'd like

* `Panel` class should allow a new kwarg `attrs` - https://github.com/wagtail/wagtail/blob/main/wagtail/admin/panels/base.py#L48 (including support for cloning this in `clone_kwargs`)
* `FieldPanel` should support have something similar to `BASE_ATTRS` on the class as a property, similar to `TEMPLATE_VAR` https://github.com/wagtail/wagtail/blob/main/wagtail/admin/panels/field_panel.py#L12
* `FieldPanel` could have `BASE_ATTRS` set to `{"data-field-wrapper": true}` by default and then on the `FieldPanel` init, it sets this as the `attrs`, and extends it with any `attrs` provided to the `FieldPanel` instance, before calling `super`. Note that someone should be able to override the `data-field-wrapper` if they chose (although this would probably break things).
* `BoundPanel.get_context_data` should support passing in the `attrs` to the template (probably at the root `Panel` implementation.
* The template `wagtail/admin/templates/wagtailadmin/shared/field.html` should support rendering the attributes in the same way that Django attrs are rendered.
* Extending `FieldPanel` or `Panel` and the BoundPanel's `get_context` should easily allow appending/adjusting the `attrs` through the inheritance chain as needed.

### Example usage

Trivial example but shows off how it would work

```py
# models.py
class OperatingHours(models.Model):

    day = models.CharField(max_length=4, choices=DAY_CHOICES, default="MON")

    panels = [
        FieldPanel("day", attrs={"data-controller": "today"}),
    ]
```

```js
// .../static/js/TodayController.js - added via hooks

const FilterController = window.Stimulus.constructor.createController({
  connect() {
    const field = this.element.querySelector('[data-field] input');
    const todayWeekday = 3; // get today's weekday as a number
    if (field.value === todayWeekday) {
        this.element.classList.add('highlight');
    }
  }
});

window.Stimulus.register('today', FilterController);
```

#### `attrs` rendering should emulate Django widget attrs

Using Django's terminology and ways of working with widget attrs on panels feels intuitive and is also very powerful, note that this is not a proposal to allow for non-called `Panel/FieldPanel` as is done with Widgets.

The way that `attrs` in Django widgets get rendered is a bit nuanced and has some really nice defaults, the main one being how True/False items are handled. True will just add the attribute as is (no value) and False will not add the attribute at all. There are also the built in escaping benefits that come with this being driven at the Django side.

There is also some nice handling of cloning/extending the `attrs` object.

* https://docs.djangoproject.com/en/4.1/ref/forms/widgets/#django.forms.Widget.attrs
* See https://github.com/django/django/blob/main/django/forms/widgets.py#L281
* https://github.com/django/django/blob/main/django/forms/templates/django/forms/attrs.html

### Describe alternatives you've considered

* Wagtail provides a documented way to add attributes to a field, via the `widget=` param on `FieldPanel`, this is often enough to get an attribute inside the element.
* Maybe we do not want to add another kwarg to `Panel`, we already do support `classname` and that may be enough at the root level.
* We may not want to provide the ability to do this at the panel level and instead want to push this kind of thing to the template level, however, our `field_panel` does not allow for appending `attrs` by extension right now so it's very difficult to do this without just adding another `div` around it. Additionally, when putting attrs in the template's HTML, there are further escaping considerations that have to be done manually and add developer overhead / security risks.

### Additional context

* See answer to a problem in a comment - https://github.com/wagtail/wagtail/issues/7417#issuecomment-1438396850 - this would be easier to implement (when that solution ends up in the docs for example).
* `PageChooserPanel`, `InlinePanel` and other custom Panels could much more easily support Stimulus controller attributes without needing to change much/any of the template HTML files if needed.
* We can provide some nice documented / answered solutions to #161 & #1063 via essentially adding some JavaScript snippets and adding `attrs` to the `FieldPanel`.

**Comment by lb-** [comment]
Spoke about this at core team and approval that this would be a useful enhancement.

**Considerations**

* Ensure developers can use the calling kwargs but also override when extending the `FieldPanel` class or similar.
* Double check other Panel templates in use and how they would or would not support this (e.g. `MultiFieldPanel` - does not have a root element), may need some nuance in the docs.

**Comment by salty-ivy** [comment]
would like to pick this one up, after i am done with https://github.com/wagtail/wagtail/issues/10090
if anyone else is willing to try let me know.

**Comment by lb-** [comment]
@salty-ivy this one might be a bit chunky, but if you feel up for it - sounds good. I am happy to answer questions as needed.

No pressure though, I was also happy to do this one as I originally requested this and am hopeful this will make developer facing Stimulus usage much easier.

**Comment by salty-ivy** [comment]
@lb-  do we need to render these attrs next to `data-field-input` in the `dive`?  in `field.html`
```html
<div class="w-field__input" data-field-input>
            {% if icon %}
                {% icon name=icon classname="w-field__icon" %}
            {% endif %}

            {% block form_field %}
                {% if rendered_field %}
                    {{ rendered_field }}
                {% elif field %}
                    {{ field|render_with_errors }}
                {% elif children %}
                    {{ children }}
                {% endif %}
            {% endblock %}

            {% if show_add_comment_button %}
                <button class="w-field__comment-button w-field__comment-button--add u-hidden" type="button" data-component="add-comment-button" data-comment-add aria-label="{% trans 'Add comment' %}" {% if label_for %}aria-describedby="{{ label_id }}"{% endif %}>
                    {% icon name="comment-add" %}
                    {% icon name="comment-add-reversed" %}
                </button>
            {% endif %}
        </div>
```

**Comment by lb-** [comment]
Thanks Aman. Looks like you have found the answer. Happy to help with this though if you do get stuck.

**Comment by salty-ivy** [comment]
@lb-  I didn't understand this point 
`BoundPanel.get_context_data` should support passing in the `attrs` to the template (probably at the root Panel implementation).

what exactly do you mean by `root panel implementation`?

**Comment by lb-** [comment]
@salty-ivy sorry, my choice of words is probably confusing. The goal is to ensure that the attrs get passed through to the rendered template. To do that, you'll need to pass it through the BoundPanel's context. 

By root panel implementation I meant the 'base' or 'common' template html file.

**Comment by salty-ivy** [comment]
@lb-  Hi sorry for the delay, could you have a quick review my draft PR, I am not sure why `attrs` is rendering to `None`.
