### ISSUE TITLE
Soft line break button missing in Draftail panel

### ISSUE THREAD

**Issue by andre-fuchs** [wagtail/wagtail#10142]
### Issue Summary

Comparing two Wagtail instances – <v3.0 and v4.2 – the newer Draftail editor UI is missing the button for "soft line break", the one with the return arrow icon. See screenshots.

Before (with line break button):
![Screenshot from 2023-02-23 11-03-52](https://user-images.githubusercontent.com/43378427/220880732-4fa246ff-ab37-4fa3-9ded-b703f5a74b56.png)

After (without line break button:
![Screenshot from 2023-02-23 11-04-54](https://user-images.githubusercontent.com/43378427/220879166-6fcd9636-2598-4c62-bd0e-a1109e17288f.png)

I tried to add this button via the feature list, but both "linebreak", "line-break" and "br" didn’t work as I was hoping. The docs and release notes are not mentioning this as well, as far as I can tell after a quick search. How can I get this button in the most recent Wagtail versions?

**Comment by thibaudcolas** [comment]
Hi @andre-fuchs, thank you for the report. This is likely an unintended regression from previous releases – will investigate further.

**Comment by thibaudcolas** [comment]
Hi @andre-fuchs, I’m unable to reproduce this so far. We did change this toolbar quite a bit in the next release but it looks to me like it’s still not possible for the line break feature to be missing (it’s hard-coded, see #4445).

Here is a screenshot of the default toolbar options in a brand new site with no customisations:

![rte-toolbar-10142](https://user-images.githubusercontent.com/877585/224329320-2800e4e0-db2f-48a8-8465-cf89970eff5c.png)

You might have more customisations on your site that explain this?

**Comment by andre-fuchs** [comment]
Thanks @thibaudcolas for looking into it. I cannot find any customization to this line break feature. Here is the list of features for this specific TextBlock that lacks the line break button in the UI.

``` python
class BaseTextBlock(StructBlock):
    style = ChoiceBlock(TEXT_STYLES, icon='cog', required=False)
    text = RichTextBlock(
        label="Text",
        icon="pilcrow",
        template="blocks/text_block.html",
        features=['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'artist', 'small', ],
    )

    class Meta:
        label="Text"
        icon = "pilcrow"
        template = "blocks/text_block.html"
        group = '(1)  Text'
```

It contains two custom buttons, named 'artist' and 'small'. The one is an inline feature the other a block feature. If I remove these the line break button is still missing.

**Comment by andre-fuchs** [comment]
> We’ve added it back in v4.2, along with all other toolbar options except for undo/redo buttons, so the toolbar options are the same for both floating and pinned toolbars.

This solves it. Thanks!
