### ISSUE TITLE
Tree Models

### ISSUE THREAD

**Issue by kiyoshi-satoo** [wagtail/wagtail#10164]
I want to make a simple nested categories for blogs, but I think I will have to write all the functionality and UI in the admin panel from scratch.
It would be cool to use the same functionality and UI as in Djnago-MPTT or Django treebeard(I know wagtail use this)
Also,does anyone have any suggestions on how to do this the right way?

**Comment by AnuragMishraa** [comment]
If you want to implement nested categories for your blog in Django, you can use existing packages such as Django-MPTT or Django treebeard. These packages provide models and APIs for hierarchical data structures, which can be used to create nested categories.

Using an existing package not only saves you time but also ensures that your implementation is efficient and reliable. These packages have been used and tested by the Django community for many years, so you can be confident that they are well-maintained and robust.

Then you can create a model for your categories using the MPTTModel class provided by the package:

from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

class Category(MPTTModel):
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['name']


In this, each category has a name and a parent category, which is also a Category instance. The TreeForeignKey field is used to specify this relationship.

Then you can create a model for your categories using one of the classes provided by the package, such as MaterializedPathNodeMixin:

from django.db import models
from treebeard.mp_tree import MP_Node

class Category(MP_Node):
    name = models.CharField(max_length=50)

    node_order_by = ['name']

In this, each category has a name, and the node_order_by attribute is used to specify the order in which nodes are displayed.

Both Django-MPTT and Django treebeard provide APIs for working with hierarchical data, such as querying for descendants or ancestors of a node, and moving nodes around in the tree.

As for implementing the UI in the admin panel, you can use Django's built-in admin site, which provides a convenient way to manage your data models. You can customize the admin interface by creating custom admin forms or by using third-party packages such as django-mptt-admin or django-treebeard-admin, which provide pre-built UI components for working with hierarchical data.

Overall, using an existing package such as Django-MPTT or Django treebeard is the right way to implement nested categories in Django, as it saves you time and ensures a reliable and efficient implementation.

**Comment by AnuragMishraa** [comment]
Can you please assign this issue to me?

**Comment by laymonage** [comment]
@AnuragMishraa we do not assign issues to non-core team members. Please read #10070 thoroughly before spamming issues.

**Comment by lb-** [comment]
@kiyoshi-satoo this is more of a question about how to do something and not an enhancement request. I'll close this for now and recommend you ask in Slack or Stackoverflow. 

See https://github.com/wagtail/wagtail/#-community-support

I have an older blog post that may be useful also https://posts-by.lb.ee/building-a-configurable-taxonomy-in-wagtail-django-94ca1080fb28

Also note that Collections are built into Wagtail and are already tree models, that may be enough for you to use without custom models.

**Comment by chosak** [comment]
@kiyoshi-satoo you might also consider https://github.com/cfpb/wagtail-treemodeladmin to see if that fits your needs for nested tree models in Wagtail.

**Comment by kiyoshi-satoo** [comment]
@chosak this is what I needed. Thank you

**Comment by kiyoshi-satoo** [comment]
> @kiyoshi-satoo this is more of a question about how to do something and not an enhancement request. I'll close this for now and recommend you ask in Slack or Stackoverflow.
> 
> See https://github.com/wagtail/wagtail/#-community-support
> 
> I have an older blog post that may be useful also https://posts-by.lb.ee/building-a-configurable-taxonomy-in-wagtail-django-94ca1080fb28
> 
> Also note that Collections are built into Wagtail and are already tree models, that may be enough for you to use without custom models.

of course I know, but there is no functionality and no interface in the admin panel, so you have to customize it yourself. It would be cool if it was
