### ISSUE TITLE
🎛️ Migrate `includes/dialog` to a Stimulus Controller `w-dialog`

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10174]
> ℹ️ **Part of the [Stimulus 🎛️ RFC 78](https://github.com/wagtail/rfcs/pull/78)**

### Is your proposal related to a problem?

The current `dialog` implementation is relatively simple and uses `a11y-dialog` under the hood. The wrapper is written in JavaScript and it would be great to see this move to Stimulus with adoption of TypeScript.

### Describe the solution you'd like

See the current implementation in the following files

* [client/src/includes/dialog.js](https://github.com/wagtail/wagtail/blob/main/client/src/includes/dialog.js)
* [wagtail/admin/templates/wagtailadmin/shared/dialog/dialog.html](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/dialog/dialog.html)

**Proposed implementation**

> **IMPORTANT:** Read comments, this approach has been refined further down with the creation of TWO controllers.

We create one new controller `DialogController`/`w-dialog` that has two main modes, the first is the template mode, and the second is the dialog mode.

The template mode will only trigger if there is a `template` target, this will do the bulk of the work in `client/src/includes/dialog.js` of creating a DOM copy of the content, appending it the selected root container (or body).

The dialog mode however, will do the instantiation to `A11yDialog`, when there is no template target. The existing declared show/hide event listeners no longer need to be declared in JS but instead can be declared on the HTML elements via data attributes.

The new controller will need to have unit tests to support the behaviour.

Finally, the `body` content will be used as a target and other selectors to be updated to align with this.

```html
{% load wagtailadmin_tags i18n %}
<template
    data-wagtail-dialog
    data-controller="w-dialog"
    data-w-dialog-target="template"
    {% if dialog_root_selector %}data-w-dialog-root-selector-value="{{ dialog_root_selector }}"{% endif %}
>
    <div
        id="{{ id }}"
        aria-labelledby="title-{{ id }}"
        aria-hidden="true"
        class="w-dialog {% if theme %}w-dialog--{{ theme }}{% endif %} {% if classname %} {{ classname }}{% endif %}"
        data-controller="w-dialog"
        data-action="w-dialog:hide->w-dialog#hide w-dialog:show->w-dialog#show"
        {% if data_url %}data-url="{{ data_url }}"{% endif %}
        {% if theme %}data-w-dialog-theme-value="{{ theme }}"{% endif %}
    > 
    {% comment %} ... all the other stuff - as is {% endcomment %}

                <div data-w-dialog-target="body">
                    {{ children }}
                </div>
            </div>
        </div>
    </div>
</template>
```

The new controller will have the following

* Targets; `body` and `template`
* Methods:
  * `connect` (if in template mode, calls clone, otherwise create)
  * `create` (for when in dialog mode, connects to the A11y instance, e.g. `this.a11y = A11y(this.element);`)
  * `clone` (for when connected and a template target exists)
  * `hide` - calls hide on the A11y instance
  * `show`- calls show on the A11y instance
  * `disconnect` - should call `destroy` on the A11y instance
* Values:
  * `container` (or `rootSelector`) where the dialog should be created, note that it should default to `body`. This is only 
applicable in the template mode.
  * `theme`, this is only applicable on the dialog mode, used to determine behaviour of body scroll (see JS implementation)
* Dispatched events
  * Along with the supported listeners for `w-dialog:show` & `w-dialog:hide` (added in the DOM)
  * We should also dispatch some ``w-dialog:shown` ``w-dialog:hidden` (or similar) when the actual modal does toggle, this ability needs to be registered on the A11y instantiation.

### Describe alternatives you've considered

* Leave as is, the current implementation covers most cases.

### Additional context

* We will need to ensure that the userbar can support this new approach, it will need to potentially create its own Stimulus application instance.
* We will need to ensure that any existing data attributes in use, or other event listeners/dispatching usage has the code updated.

**Comment by Hussain0520** [comment]
Hey, I would like to work on this issue!

**Comment by lb-** [comment]
Go for it @Hussain0520  - just a heads up though that this will take a bit of reading and learning to get done if you have not yet done much TypeScript or read about Stimulus.

I do recommend you read about making your first contribution here https://github.com/wagtail/wagtail/issues/10070

And then read the Stimulus docs https://stimulus.hotwired.dev/ & the a11y modal docs https://a11y-dialog.netlify.app/usage/instantiation/

After reviewing those items and if you have had a chance to get your head around how you would implement this, feel free to start. Just add a comment when you are 'starting' and go for it.

**Comment by Hussain0520** [comment]
Thanks! @lb- I'll go through it and ask for help if I need any.

**Comment by Hussain0520** [comment]
I went through the docs and I am confident that I can create the stimulus script. On the other hand I am unclear how I can specify the modes template and dialog. Can you let me know how I can go about that part of the script.

**Comment by lb-** [comment]
@Hussain0520  great question, I can see now that this approach is probably a bit confusing.

We have one controller 'mode' that does the job of grabbing the `template` content and transporting it to another part of the DOM this has nothing to do with the modal itself. Then we have the second mode which is purely concerned about ensuring the a11y dialog gets instantiated against the DOM element and some extra handling for events.

As I write this, I think these should probably be two controllers;

1. `w-teleport` or `w-portal` - similar to https://alpinejs.dev/directives/teleport or https://reactjs.org/docs/portals.html - the job of this controller is only to copy some content to another part of the DOM. The reason for this is so that the modal template content can be handled where the Django template exists but the actual HTML renders at the end of the `body` tag.
2. `w-dialog` - just does the work of connecting with a11y modal.

If we did this, the HTML Django template content would look something like this instead.

```html
{% load wagtailadmin_tags i18n %}
<template
    data-controller="w-teleport"
    {% if dialog_root_selector %}data-w-teleport-target-value="{{ dialog_root_selector }}"{% endif %}
>
    <div
        id="{{ id }}"
        aria-labelledby="title-{{ id }}"
        aria-hidden="true"
        class="w-dialog {% if theme %}w-dialog--{{ theme }}{% endif %} {% if classname %} {{ classname }}{% endif %}"
        data-controller="w-dialog"
        data-action="w-dialog:hide->w-dialog#hide w-dialog:show->w-dialog#show"
        {% if data_url %}data-url="{{ data_url }}"{% endif %}
        {% if theme %}data-w-dialog-theme-value="{{ theme }}"{% endif %}
    > 
    {% comment %} ... all the other stuff - as is {% endcomment %}

                <div data-w-dialog-target="body">
                    {{ children }}
                </div>
            </div>
        </div>
    </div>
</template>
```

We would then have two controllers;


```js
// w-teleport / TeleportController
export class TeleportController extends Controller<HTMLTemplateElement> {
  static values = { target: {default: 'body', type: String } };
  connect() {
    this.targetContainer = document.querySelector(this.targetValue);
    if (!this.targetContainer) {
       // maybe throw an error instead?
      return;
    }
    this.append();
  }
  append() {
    // something like this?
    const node = this.element.content.firstElementChild.cloneNode(true);
    this.targetContainer.append(node);
  }
}
```

```js
export class DialogController extends Controller<HTMLElement> {
  static values = { theme { default: '', type: String} };
  connect() {
    this.dialog = a11y(this.element);

    if (theme !== 'floating') {
      // Prevent scrolling when dialog is open
      this.dialog
        .on('show', () => {
          html.style.overflowY = 'hidden';
        })
        .on('hide', () => {
          html.style.overflowY = '';
        });
    }
  }
}
```

Let me know if that makes sense and I can update the main issue description.

**Comment by Hussain0520** [comment]
Thanks! @lb- for this elaborate explanation, I'll try it and get back to you.

**Comment by lb-** [comment]
@Hussain0520 no rush, it's a lot to learn, my I also suggest that a more simpler Stimulus adoption could be a better first task though.

https://github.com/wagtail/wagtail/issues/10091 might be a more suitable one, another contributor has said they were looking at this (amount a month ago) but they have since also said they are doing 3 other things so I think this issue (footer save) would be a good one to give a go at.

**Comment by Hussain0520** [comment]
@lb- Thanks! I'll look into the other issue as well.

**Comment by lb-** [comment]
@Hussain0520 as per our chat on Slack, you will just try to focus on one issue for now. Specifically https://github.com/wagtail/wagtail/issues/10091

This issue may be looked at by others.

**Comment by Lovelyfin00** [comment]
Hey @lb- 
Would like to work on this after #10318 gets merged in

**Comment by lb-** [comment]
Awesome. Thanks @Lovelyfin00

**Comment by Lovelyfin00** [comment]
Working on this

**Comment by laymonage** [comment]
- `stable/5.1.x`: 0a9f7d67261aea5e29b4bd6eeede2a5d1acf35df
- `main`: 39a723f9d1e585100a10054686835847b54198a6
