### ISSUE TITLE
Cannot type accents in RichText using FireFox

### ISSUE THREAD

**Issue by perepicornell** [wagtail/wagtail#10179]
### Issue Summary

In FireFox, when I type a letter with an accent it gets removed (the letter not the accent).
Examples:
à á è é
If I just type the accent and then space, it removes the accent as well (should leave the accent there, normally).

Copying and pasting text with accents works fine so, to reproduce, you'll need a keyboard layout that actually lets you type accents.
In Chrome everything works fine.

### Steps to Reproduce

1. Add a RichText field to a page like this:

```
    text = RichTextField(
        _("Text"),
        features=[
            "h2",
            "h3",
            "bold",
            "italic",
            "link",
            "ol",
            "ul",
        ]
    )
    content_panels = [
        FieldPanel(
            "text",
        ),
    ]
```

2. Edit the page with FireFox and type accents in it.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: 3.9.5
-   Django version: 4.1.7
-   Wagtail version: 4.2
-   Browser version: FireFox in which it doesn't work: https://www.whatsmybrowser.org/b/ACWRL. Chrome in which it does work: https://www.whatsmybrowser.org/b/YM3LC

**Comment by gasman** [comment]
Thanks for the report @perepicornell! There's an existing open issue about this at #7386.

**Comment by perepicornell** [comment]
Oh I'm sorry, I searched before posting but clearly not enough.
Thanks for the other issue's reference!
