### ISSUE TITLE
Dialog component's message does not have rounded corners at the top

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#10177]
### Issue Summary

When using the dialog component with a message, the dialog's top side does not have rounded corners:

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/6379424/221899780-b4a3a258-9454-459c-ad65-763e26158b17.png">

This was a regression in 55d04366f7dd57141de9ec9282d8978b3ccbd7cc when `overflow: hidden;` was added to `.w-dialog__box` in the base dialog styles.

I'm assuming that the `overflow: hidden;` was only removed so that we can display the close button at an offset in the userbar's accessibility checker, and not necessarily required for the generic floating version of the dialog:

<details>
<summary>Screenshot</summary>
<img width="639" alt="image" src="https://user-images.githubusercontent.com/6379424/221900475-51f69e29-f68b-4219-ac92-6a2e8c81f99b.png">
</details>

In fact, the generic floating dialog uses the same close button styles as the other ones, so this means the `overflow: hidden;` was only necessary for the accessibility checker's dialog:

<details>
<summary>Screenshot</summary>
<img width="697" alt="image" src="https://user-images.githubusercontent.com/6379424/221900984-04624a8d-b0d3-469d-830c-d74ac2467dd2.png">
</details>

### Steps to Reproduce

1. Spin up bakerydemo
2. Open Settings > Styleguide
3. Try the "Dialog with success/warning/error" variants of the Dialog component
4. See that the top side of the dialog has no rounded corners

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The top side should be rounded like the bottom, which was how it has been before Wagtail 4.2.

### Suggested fix

Reintroduce `overflow: hidden;` to the `.w-dialog__box` styles in `_dialog.scss` like how we had it before, and add `.w-dialog__box { overflow: visible; }` to the userbar's dialog override in `_userbar.scss`.

Alternatively, add `border-top-*-radius` to `.w-dialog__message` with the same value as the one set in `.w-dialog__box`.

**Comment by TheLazron** [comment]
Can I be assigned with this issue

**Comment by gasman** [comment]
Thanks for your interest @TheLazron! You are welcome to work on this. We do not assign issues outside of the core team - we just ask that people indicate their intention to work on an issue (as you have now done), to avoid duplicating efforts.

For further help in getting started, please see https://dev.to/lb/ten-tasty-ingredients-for-a-delicious-pull-request-hgc - you may also wish to join [our #new-contributors channel on Slack](https://github.com/wagtail/wagtail/wiki/Slack).

**Comment by soumik-saha** [comment]
Hey, can I try to fix this bug?

**Comment by Hussain0520** [comment]
Hey @gasman , I would like to work on this issue!

**Comment by Scotchester** [comment]
@soumik-saha and @Hussain0520, please give @TheLazron some time to attempt the issue (at least a week) before asking if you can pick it up.

**Comment by Hussain0520** [comment]
Sure!

**Comment by soumik-saha** [comment]
Okay!

**Comment by sagarsangwan** [comment]
Hey @gasman can i try to fix this issue

**Comment by sivangbagri** [comment]
Hii @gasman I want to work on this issue

**Comment by lb-** [comment]
Thanks for your interest all, as you can see above, 5 people have already expressed an interest in working on this and there is already a PR up from a 6th person. So it's likely that you would be duplicating those existing efforts. Nevertheless, if you're OK with this, you can proceed.

@sagarsangwan @sivangbagri 

Additionally - please read our guide to your first contribution as it covers many of the basics for how to get involved before reaching for issues. https://github.com/wagtail/wagtail/issues/10070


I'll remove the good first issue label for now to avoid additional interest.
