### ISSUE TITLE
🎛️ Rename `w-slug` Stimulus Controller to `w-clean`

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10198]
> ℹ️ **Part of the [Stimulus  🎛️ RFC 78](https://github.com/wagtail/rfcs/pull/78)**

### Is your proposal related to a problem?

The `w-slug` / `SlugController` was named as such on the initial implementation because it was only being used for slugs. However, this seems to make more sense as `w-clean` (as in to clean a field), it would be good to rename this.

### Describe the solution you'd like

Rename all usages of `w-slug` to `w-clean` in unit tests, templates and anywhere else it's used. Additionally rename the controller from `SlugController` to `CleanController`.

We could additionally split out the `trim` function from inside `slugify` to it's own method and then make slugify call trim first.

### Describe alternatives you've considered

* Leave as is, but it boxes this controller in to dealing with slugs only and it appears that there are other common use cases that are slightly broader.
* Additional names to consider; `w-filter`, `w-cleanse`, `w-text`.

### Additional context

* This is part of a larger goal to migrate to Stimulus.
* Initial implementation via https://github.com/wagtail/wagtail/issues/10086 
* Spilt from discussion https://github.com/wagtail/wagtail/issues/10088#issuecomment-1454913500

**Comment by ksba2004** [comment]
Hey @lb- , I would like to work on this. Can you please how can I get started?

**Comment by gasman** [comment]
Thanks for your interest @ksba2004! Please see the guide here: https://github.com/wagtail/wagtail/issues/10070

**Comment by thibaudcolas** [comment]
@lb- without any further specifiers, I’d have expected "clean" to do something else than what this controller does (slug-specific string processing). What are the other use cases you’re referring to? At least right now `cleanForSlug` seems to only be used for slugs.

**Comment by lb-** [comment]
@thibaudcolas good call out, my thinking was that this controller could be used to solve some of the use cases in #1063 / #161 / #7417 - even if that was by an example of how to extend this controller class.

Additionally, it felt like a nice way to account for some future enhancements for similar behaviour that we may want to provide out of the box (escaping, trim, upper/lower case) while avoiding a new controller or renaming this one.

However I agree that this probably feels like too much 'thinking of the future' I'm happy to close. It will be quite easy for us to rename and deprecate if needed one day, plus it will be possible to answer those issues above with a standalone custom controller example in the docs.
