### ISSUE TITLE
🎛️ Add basic Stimulus documentation for developers building with Wagtail

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10197]
As part of the [Stimulus  🎛️ RFC 78](https://github.com/wagtail/rfcs/pull/78) it would be good to ensure that there is a basic set of documentation for how to use Stimulus in Wagtail.

### Pertinent section of the Wagtail docs

There is a section in the Wagtail docs [Customising Admin Templates > Extending client-side components](https://docs.wagtail.org/en/stable/advanced_topics/customisation/admin_templates.html#extending-client-side-components), it would be good to either split this out to its own page and/or extend this with an introduction to using Stimulus within Wagtail

### Details

The RFC contains a proposed draft for this section - https://github.com/wagtail/rfcs/blob/main/text/078-adopt-stimulus-js.md#a-documentation-for-developers

### Clarity required

* Should we split out `Custom user interface fonts`, `Custom user interface colours` and `Extending client-side components` to a new page maybe called `Customising the user interface`?
* Are we happy to document four levels of customisation; a. fonts & colours, b. dispatching / listening to DOM events, c. Stimulus, d. React?
* Is there somewhere else we want to put this documentation?
* What controllers, if any, do we want to formalise in the docs (maybe; `w-action`, `w-sync`, `w-slug/clean`?).

### Additional details

* Example use cases could be the following issues;
  * Adding a keyboard shortcut (w-action) - pending https://github.com/wagtail/wagtail/issues/10167
  * Adding a global message (via event dispatching) - pending https://github.com/wagtail/wagtail/issues/9493
  * A live field - could close https://github.com/wagtail/wagtail/issues/1063 & pending https://github.com/wagtail/wagtail/issues/10088
  * A dynamic field - could close https://github.com/wagtail/wagtail/issues/161 & probably also pending https://github.com/wagtail/wagtail/issues/10088
  * A smart validator field - could copy/paste the answer here and close this issue https://github.com/wagtail/wagtail/issues/7417#issuecomment-1438396850
* Documentation examples may be revised based on the progress of https://github.com/wagtail/wagtail/issues/10133
* Should link to the contributor documentation for general Stimulus tips & approach - based on result of https://github.com/wagtail/wagtail/issues/10093 PRs

**Comment by lb-** [comment]
Assigning myself for now - will raise this for a quick bit of clarity at the next Core Team meeting.

@thibaudcolas  any thoughts on documentation structure here?

**Comment by thibaudcolas** [comment]
@lb- I think we could rename this existing page to "Customising the admin interface", and give Stimulus its own page if we think it’ll be long enough to justify it?

If we want to document specific controllers I’d keep it to a minimum (name and description?) so we still have room to change how they work in the future.

**Comment by lb-** [comment]
@thibaudcolas good idea.

**Comment by lb-** [comment]
General vibe from core team is a new page within Extending Wagtail would make more sense https://docs.wagtail.org/en/stable/extending/index.html

**Comment by lb-** [comment]
Would be good to include a replacement for WidgetWithScript (just using a static js with Stimulus attached to a widget so the JS only loads when needed). See https://github.com/wagtail/wagtail/pull/10311 for context.

**Comment by lb-** [comment]
Made a start https://github.com/lb-/wagtail/tree/docs/10197-extending-wagtail-with-stimulus

**Comment by lb-** [comment]
Going to pull from 5.0, I have something close but likely no time to get it reviewed and merged.
