### ISSUE TITLE
Tests fail against Django's `main` (5.0) branch

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#10200]
### Issue Summary

Our tests seem to fail against Django's `main` branch with `AttributeError: 'IndexView' object has no attribute 'add_facets'` as of a few days ago.

Possible cause: https://github.com/django/django/pull/16495

Will investigate later.

**Comment by laymonage** [comment]
Sounds like it's failing again for a different reason this time, but it fails *really hard*. I wonder what's causing it...

**Comment by gasman** [comment]
Yep, very weird. Looks like the new failure was introduced in [dde2537f](https://github.com/django/django/commit/dde2537fbb04ad78a673092a931b449245a2d6ae) and is specific to Postgres. Was wondering if outdated postgres / psycopg versions might be the cause (i.e. the new Django commit is a breaking change against older versions, intentionally or not) but it doesn't seem so - Django's test suite passes in the same environment that Wagtail's test suite is massively failing on.

**Comment by laymonage** [comment]
Thanks for verifying the commit, I had guessed it was that one but I hadn't tested it. It's strange though as the commit seems harmless.

One of the reasons why it's massively failing is because the user login for the tests, either with the utilities provided by `WagtailTestUtil` or `self.client.login`, doesn't seem to work. There's a signal handler that updates the last login timestamp, and it calls `save(update_fields=[...])` but it doesn't affect any rows.

I'm reopening this until we figure it out.

**Comment by laymonage** [comment]
Reopening as one test fails after https://github.com/django/django/pull/16621. Fix is at #10242.

**Comment by laymonage** [comment]
Failing again after https://github.com/django/django/pull/16632. (Great PR that finally solves Django's ticket 16055, [a pain point for us](https://github.com/search?q=repo%3Awagtail%2Fwagtail%2016055&type=code).)

Per https://github.com/django/django/pull/16632#discussion_r1169839703, it's possible that the case with `get_reverse_joining_fields` was overlooked.

**Comment by laymonage** [comment]
Actually, not going to reopen as I suspect the issue is in upstream. I'll investigate when I have the time.
