### ISSUE TITLE
Allow seo_title to be omitted from promote_panels

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#1023]
Encountered while testing #1022. As #972 points out, the concept of 'promoting' pages does not make sense on all Wagtail sites (e.g. intranets) - and since all of these fields other than slug are `blank=True` at the model level, it should be possible for site developers to omit these fields from the page editor. This is not the case for `seo_title`, because the create/edit views force a `clean_seo_title` method onto it, and fail if it's missing from the form object.

**Comment by jaap3** [comment]
Seems like this has been fixed at some point? I was able to create pages with only the slug field in the promote panels tab `promote_panels = [edit_handlers.FieldPanel('slug')]`

**Comment by gasman** [comment]
@jaap3 I think you're right... looks like this might have been fixed soon afterward, in #1217. Thanks for spotting!
