### ISSUE TITLE
Long preview mode name overflows the side panel container

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#10240]
### Issue Summary

With a really long preview mode label, the select element overflows the side panel container:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/6379424/225895881-67926aa5-9eeb-4594-9ae6-6f1c3fc6c449.png">

### Steps to Reproduce

1. Spin up bakerydemo
2. Edit `Person.preview_modes` and change the label of the `blog_post` preview mode to a really long string
3. Try to edit a Person snippet and open the preview panel

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The select element should be constrained within the side panel's container.

### Additional details

Even with the fix in #10239, this is still an issue.

I think we should change the design a bit, instead of inlining the "Preview mode" input label, we should just put it in a separate line like we do for normal inputs. Also, the select should probably always have full-width. For example, instead of:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/6379424/225896943-8ed5d1fd-675e-450e-81a6-860c7570a90b.png">

We should do:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/6379424/225897272-a152dbaa-d455-4ba1-91fa-4bcbf0b2a0f9.png">

### Alternatives to consider

- Keep the label inline, but make sure to constraint the input within the side panel container.
- Break it into two lines, but do not expand it to the full width of the container. Instead, just use the smallest possible width (which is the default behaviour)

**Comment by Rohitrky2021** [comment]
@laymonage Sir, will i do this work ,can u assign it?

**Comment by Rohitrky2021** [comment]
Sir can u plz provide the screenshot page and its source code link?

**Comment by laymonage** [comment]
@Rohitrky2021 We do not assign issues to anyone outside of the core team. Please read our contributing guide (#10070) thoroughly.

As you can see, I already self-assigned this issue because I intended to work on the fix. However, feel free to give this one a go. We'd like this issue to be fixed sooner rather than later though, so if we don't have a PR to fix this within the next week, I'll do it.

The screenshot is in the issue description, you can replicate the issue by running the [bakerydemo](https://github.com/wagtail/bakerydemo) and following the described steps. The files to edit would likely be:

- https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/side_panels/preview.html
- https://github.com/wagtail/wagtail/blob/main/client/scss/components/_preview-panel.scss

but there might be other files that need to be changed as well.

**Comment by Rohitrky2021** [comment]
ok , Sir i get to know u contributed in gsoc 2019 in Django companies ,i need your guidance regarding this plz sir provide the org i should apply and your experience while contributing through Django plz sir .,thank you

**Comment by thibaudcolas** [comment]
@Rohitrky2021 I’ve hidden your previous comment as spam. Please keep the conversation on our GitHub issues to what the issues are about, this isn’t an appropriate forum to ask for career advice.

**Comment by thibaudcolas** [comment]
Fixed in #10354.
