### ISSUE TITLE
Timezone handling buggy since 4.1.3/4.2.1

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#10243]
### Issue Summary

https://github.com/wagtail/wagtail/pull/9628#issuecomment-1450070061
Unfortunately, my fix from #9628 breaks something...

If you set your admin user's timezone to something differing from the default timezone, and then open the schedule-publication-dialog for a page, the set date will change with every save-request... **edit:** since the date fields are part of the form, every save just changes the dates in the form

I'm quite sure it has something to do with the deferred rendering of `TemplateResponse`s (see [django docs](https://docs.djangoproject.com/en/3.2/ref/template-response/#post-render-callbacks)).
In case of TemplateResponses, the set timezone is reset to the old value before the template is rendered...

I think we have to combine it with the similar handling for the current language here:
https://github.com/wagtail/wagtail/blob/fdc36a69891a92db6dca32703cddec1d573c193f/wagtail/admin/auth.py#L182-L207

I really don't know, why I have missed that language handling and the comments about the deferred rendering, sorry... :disappointed: 

Unfortunately I'm not able to make a PR before monday. The fix should be not that hard, it probably duplicates some of the language related code. As a quick, temporary alternative, you could of course revert the commits (which will probably break the tests, that have been fixed with #9628):

- https://github.com/wagtail/wagtail/commit/f05cbb2f0e62dc3a1f40f91da5a569175924e54e
- https://github.com/wagtail/wagtail/commit/b745dfd0dcf76c90e7c1603147865ed6586a64e4

### Steps to Reproduce

1. In your new virtualenv: `pip install wagtail && wagtail start mysite && cd mysite && pip install -r requirements.txt && ./manage.py makemigrations && ./manage.py migrate && ./manage.py createsuperuser && ./manage.py runserver`
2. Login to the CMS
3. Go to the account settings, and at least change the timezone to something other than UTC (the default timezone)
4. Add a new page (http://127.0.0.1:8000/admin/pages/add/home/homepage/3/) and save it as a draft.
5. Set a schedule by using the side panel and configure a date in the future.
6. Open the schedule overlay again, the time should be different to the one you have used previously. You can repeat step 5 and 6 again and again, it will change the date everytime. You don't even have to use the overlay, since the date fields are part of the form, you can just save the draft.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11
-   Django version: 3.2, 4.1.7
-   Wagtail version: 4.1.3, 4.2.1
-   Browser version: Firefox 111

**Comment by laymonage** [comment]
Hey, no worries! This is partly my fault too for not noticing it during the review. Thanks for catching it, though!

I don't think I'll make a PR before Monday either, but I wonder if this can be fixed by moving the `override_tz` context manager to also happen at the same line as the second locale `override()`?

https://github.com/wagtail/wagtail/blob/fdc36a69891a92db6dca32703cddec1d573c193f/wagtail/admin/auth.py#L198

**Comment by th3hamm0r** [comment]
I think it should be executed everywhere where the language is overridden, but also in the else block(?)

- https://github.com/wagtail/wagtail/blob/fdc36a69891a92db6dca32703cddec1d573c193f/wagtail/admin/auth.py#L183
- https://github.com/wagtail/wagtail/blob/fdc36a69891a92db6dca32703cddec1d573c193f/wagtail/admin/auth.py#L198
- https://github.com/wagtail/wagtail/blob/fdc36a69891a92db6dca32703cddec1d573c193f/wagtail/admin/auth.py#L207

**Comment by laymonage** [comment]
It feels like the `if hasattr(response, "render"):` should probably be outside, e.g.

```py
with override_tz(time_zone), LogContext(user=user):
    if preferred_language:
        with override(preferred_language):
            response = view_func(request, *args, **kwargs)
    else:
        response = view_func(request, *args, **kwargs)
    
    if hasattr(response, "render"):
        render = response.render

        def overridden_render(response):
            with override_tz(time_zone):
                if preferred_language:
                    with override(preferred_language):
                        return render()
                return render()

        response.render = types.MethodType(
            overridden_render, response
        )
    return response
```

**Comment by th3hamm0r** [comment]
Nice, that's even better! 👍

**Comment by laymonage** [comment]
While reviewing this issue, I found other places where we override the locale to use the user's preferred language, but not the timezone:

- Emails: https://github.com/wagtail/wagtail/blob/8705124eaff349f4a2160a514ed9fba40034f5a0/wagtail/admin/mail.py#L267-L269
- Userbar: https://github.com/wagtail/wagtail/blob/8705124eaff349f4a2160a514ed9fba40034f5a0/wagtail/admin/templatetags/wagtailuserbar.py#L58
- On saving the account form: https://github.com/wagtail/wagtail/blob/8705124eaff349f4a2160a514ed9fba40034f5a0/wagtail/admin/views/account.py#L266-L269

I think we should also do the same for all of them, especially emails. I think userbar and account form are not relevant for vanilla Wagtail projects, but there may be other projects where they define a custom userbar item or a custom account settings template with datetimes.

It's out of scope for this issue though, considering that it has always been the behaviour and not a regression.
