### ISSUE TITLE
Missing media files for filters on snippets listing view

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#10254]
### Issue Summary

When using a custom `filterset_class` on a custom `SnippetViewSet`, if the `FilterSet` class produces an input widget that needs additional JS files e.g. a datetime picker, the JS file won't be included in the HTML. Thus, an error may show up on the client side, e.g. `Uncaught ReferenceError: initDateChooser is not defined`:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/6379424/226655055-a3cdb0a0-83ec-4de2-8f5b-493413be0309.png">

### Steps to Reproduce

1. Spin up bakerydemo
2. Remove `@register_snippet` from the `Person` model in `bakerydemo/base/models.py`
3. Edit `bakerydemo/base/wagtail_hooks.py` to have the following:
    ```py
    from wagtail.admin.filters import WagtailFilterSet
    from wagtail.snippets.views.snippets import SnippetViewSet


    class FilterableSnippetFilterSet(WagtailFilterSet):
        class Meta:
            model = Person
            fields = ["first_published_at"]


    class PersonViewSet(SnippetViewSet):
        filterset_class = FilterableSnippetFilterSet


    register_snippet(Person, viewset=PersonViewSet)
    ```
4. Run the server and open the listing page
5. Click on the filter field for "First published at", the date picker will not show up
6. Upon checking the browser console, `Uncaught ReferenceError: initDateChooser is not defined` can be seen.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The date picker should show up and the error shouldn't exist.

**Comment by lb-** [comment]
<img width="1543" alt="Screenshot 2023-03-23 at 7 51 50 am" src="https://user-images.githubusercontent.com/1396140/227046815-49fd7279-fe1a-4d8d-bb9c-84d382984cf8.png">

Can confirm the steps to reproduce cause the bug.
