### ISSUE TITLE
jsi18n URL causes a MIME type error on Wagtail pages when the user is not authenticated

### ISSUE THREAD

**Issue by kbayliss** [wagtail/wagtail#10293]
### Issue Summary

`wagtail.admin.urls` includes the `JavaScriptCatalog` catalogue (https://github.com/wagtail/wagtail/blob/main/wagtail/admin/urls/__init__.py#L96-L100), which works fine when the user is authenticated, but on the Wagtail login page and forgotten password page (i.e. when the user is not authenticated), this causes the following error:

> Refused to execute script from 'https://some-domain/admin/login/?next=/admin/jsi18n/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Screenshot:

![Screenshot 2023-03-30 at 11 33](https://user-images.githubusercontent.com/3009233/228811483-a0a03b73-116e-4d75-922b-33b24fa5e3f9.png)

### Steps to Reproduce

1. View the Wagtail login page or forgotten password page
2. Open the developer console
3. You should see the MIME type error

### Technical details

-   Python version: 3.10.2
-   Django version: 3.2.13
-   Wagtail version: 4.1.1
-   Browser version: Chrome version 111.0.5563.146 (Official Build) (x86_64)

**Comment by gasman** [comment]
Confirmed on current main.
