### ISSUE TITLE
PagePermissionTester should be in the testing docs

### ISSUE THREAD

**Issue by schlich** [wagtail/wagtail#10317]
Trying to write some basic unit tests for Wagtail Page permissions. The docs are IMO very unclear about how to programmatically interact with the permissions assignment, and I only was able to find the PagePermissionsTester object via ChatGPT 🙂. I think this would be a great addition to the testing docs.

### Pertinent section of the Wagtail docs

[Testing your Wagtail Site](https://docs.wagtail.org/en/stable/advanced_topics/testing.html)

### Details

API documentation and a simple example test should be sufficient

I am happy to work on this as PR myself if anyone else is not able to pick it up, especially if other folks think this is a good idea.

**Comment by SAMAD101** [comment]
@lb- So, we have to write docs for the permission tests provided within the `PagePermissionTester` class of `wagtail.core.permissions` module. I also to confirm if these can be documented within the same [Testing your Wagtail site](https://docs.wagtail.org/en/stable/advanced_topics/testing.html#) section or if will we create a separate section for it? 

Lastly can this issue be assigned to me?

**Comment by lb-** [comment]
@SAMAD101 we don't assign issues outside of the core team. 

I don't think that the testing section is the right place for this documentation, probably somewhere in the reference section. 

As noted, despite the name, the PagePermissionTester has nothing to do with testing (as in unit testing). Its simply a utility class for working with permission restrictions across Page models. 

I'm going to flag this as needs design decision as I'm not sure thw util should be documented (as it means we can't easily change it later).

However, if you wanted to help write some documentation on how to fake permissions for unit tests, that's fine, but I don't think you need PagePermissionTester to do that.

**Comment by lb-** [comment]
@SAMAD101 thanks for raising this, after a cross check with another core team member we agreed that documenting PagePermissionTester is not really appropriate. 

As such, I'll close this issue.

However, if you would like to document how to test permission related functionality, please raise a new issue with your suggested approach. And yes, testing your Wagtail site would be the right place for this, but just a reminder that the example testing should be written in a way that does not rely on Wagtail's un-documented internals. Even if ChatGPT says to do it that way 😅

Also, you may find that searching for how to do this in Django, not Wagtail, will be enough for what's needed. E.g this snippet looks like a good start. https://gist.github.com/treyruncie/a292366d8ae0de4e50f8
