### ISSUE TITLE
Extraneous Locale query with `WAGTAIL_I18N_ENABLED = False`

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#10329]
When i18n is not enabled, we are making a Locale query on every page view

h/t to @Tijani-Dia and his https://github.com/Tijani-Dia/dj-tracker

<details>
<summary>Traceback/reference</summary>
![nn](https://user-images.githubusercontent.com/31622/231769225-ecff22fe-238c-4544-9f30-5d6fe8d3877f.png)
</details>

In pretty much all other places we check that i18n is enabled, but 
https://github.com/wagtail/wagtail/blob/70a6230a650f8ce299d6f883483c37bacfc325d6/wagtail/models/i18n.py#L234-L251 doesn't

Proposal: update `TranslatableMixin.localized_draft` to something like:

```python
    @property
    def localized_draft(self):
        """
        Finds the translation in the current active language.

        If there is no translation in the active language, self is returned.

        Note: This will return translations that are in draft. If you want to exclude
        these, use the ``.localized`` attribute.
        """
        if not getattr(settings, "WAGTAIL_I18N_ENABLED", False):
            return self

        try:
            locale = Locale.get_active()
        except (LookupError, Locale.DoesNotExist):
            return self

        if locale.id == self.locale_id:
            return self

        return self.get_translation_or_none(locale) or self
```

**Comment by lb-** [comment]
@zerolab I can confirm this issue exists, when disabling `WAGTAIL_I18N_ENABLED` this code locale query still runs when viewing any page.

I think your solution makes sense and agree we do that check in other places that run a similar query.

**Comment by tbrlpld** [comment]
I am currently working an implementation for localization of querysets. Do we know what is causing these queries to be fired? I.e. why is anything calling `localized`/`localized_draft`?

**Comment by tbrlpld** [comment]
I guess I just found that answer... was much easier to find than I expected: https://github.com/wagtail/wagtail/blob/678dd1585246b3afd48a3cd915f6102523bc0647/wagtail/views.py#L19
