### ISSUE TITLE
Update the existing documentation to increase readability and understanding

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [wagtail/wagtail#10350]
### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/stable/advanced_topics/accessibility_considerations.html#alt-text-in-templates

### Details

As I reviewed the Content Modeling documentation, I noticed several paragraphs that could benefit from improved sentence structure to better convey their meaning. As community members, it's our responsibility to ensure that readers can understand the documentation in a single reading. To that end, let's consider ways to refine these paragraphs and make them more clear and more concise.

**Comment by SanjaySinghRajpoot** [comment]
I would like to work on this issue. Thank you!

**Comment by lb-** [comment]
Closing as a non-issue - see https://github.com/wagtail/wagtail/pull/10351#issuecomment-1515475405

If there is something specific about this section of the docs that caused a bug on implementation or a lot of confusion, please explain it in a new issue in detail. Thanks @SanjaySinghRajpoot
