### ISSUE TITLE
Enormous amount of ReferenceIndex churn tracked down to possible bug in Wagtail API v2

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#10353]
### Issue Summary
In short, I think Wagtail's default serializer for StreamFields has a bug that's stripping essential identifying information from the contents of `ListBlock`s.

### Steps to Reproduce

1. I've created a repo that shows this issue off with minimal code here: https://github.com/coredumperror/wagtail_api_test
2. Follow the readme to reproduce the issue. 
3. In short, the output of the API loses crucial info compared to what's in the database, for no apparent reason.

DB contents: 
```
[
    {
        "type": "carousel",
        "value":
        {
            "items":
            [
                {
                    "type": "item",
                    "value":
                    {
                        "image": 1,
                        "video": "",
                        "caption": "test",
                        "photo_credit": "test"
                    },
                    "id": "499c302f-6230-45ed-90d4-62ecd2e845ea"
                }
            ]
        },
        "id": "5bd471ea-1fe5-4fc2-a76a-3c70897d3895"
    }
]
```

API output:
```
[
    {
        "type": "carousel",
        "value": {
            "items": [
                {
                    "image": 1,
                    "video": "",
                    "caption": "test",
                    "photo_credit": "test"
                }
            ]
        },
        "id": "5bd471ea-1fe5-4fc2-a76a-3c70897d3895"
    }
]
```

As described in the repo's readme, we're using Wagtail API v2 as a cross-server Page-syncing tool. In our full code, we're copying NewsPages from our source server to multiple client servers. Unfortunately, ever since we updated to Wagtail 4, and the `ReferenceIndex` model became a thing, our syncs have been causing extremely high database churn, even when all they're doing is copying identical data over top of existing NewsPages. The references aren't actually changing, but `ReferenceIndex` models keep being added and deleted anyway.

I ultimately tracked the problem down to the fact that the `MixedMediaBlock`s aren't retaining their IDs across the sync, and are thus being detected as having entirely new `content_path` values in the `ReferenceIndex` model. The *only* difference is the `id` field, though, as the actual image references in these blocks are identical to their pre-sync values (we convert the origin's image IDs to local image IDs for identical files, sync'd separately).

The reason these block IDs are different is that the API isn't including them in its output, so when we populate the `NewsPage.body` field on the client, we're sending in that "API output" dict, instead of the "DB contents" dict, and Wagtail's system is automatically wrapping a new `"type": "item"` dict around those dictionaries in the "items" `ListBlock` when we save the NewsPage. And since a new StreamBlock dict inherently has a new, random ID, despite the sync overwriting old data with identical new data, the `NewsPage.body` field still changes enough for `ReferenceIndex` to notice.

Why are `ListBlock` items being stripped like this by the Wagtail API serializer?

I realize that changing the way the API outputs `ListBlock`s is probably not ideal, but maybe a setting can be added to make the API output more suitable for sync'ing? 

### Technical details

-   Python version: 3.8.13
-   Django version: 4.1.8 (also happens in 3.2.16)
-   Wagtail version: 4.2.2

**Comment by cnk** [comment]
Using Wagtail's API v2 for syncing data between installations is an unusual use case and while it would be nice to be able to support this, doing so would require changing the API output in ways that might cause difficulties for all projects that use the API for headless frontends. So I am closing this issue.
