### ISSUE TITLE
Darkmode: modal close button visibility

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#10379]
The new dark mode is pretty neat. kudos for all the work @thibaudcolas @benenright 

While testing some updates for wagtailmedia, I noticed the ❌ button is very hard to see when in dark mode:

default:
![modal](https://user-images.githubusercontent.com/31622/233807340-cd988f04-161c-4f6f-b961-01b61b7a8de6.png)

hover:
![modal-hover](https://user-images.githubusercontent.com/31622/233807341-2445a627-96e7-443f-a448-fa0353d103b8.png)

**Comment by shindodkar** [comment]
@zerolab  I would like to work on this. will you assign me this?

**Comment by zerolab** [comment]
@shindodkar we do not assign issues to anyone outside the core team.
Please read https://github.com/wagtail/wagtail/issues/10070 and https://dev.to/lb/ten-tasty-ingredients-for-a-delicious-pull-request-hgc

And by all means, go for it

**Comment by shindodkar** [comment]
Hii @zerolab I am new to open source I've been search which file to make changes for a hour. can you help to walk me through it? I go though the read.me file install all the installation and now I am stuck.

**Comment by zerolab** [comment]
@shindodkar https://docs.wagtail.org/en/stable/contributing/index.html and specifically https://docs.wagtail.org/en/stable/contributing/developing.html are good reads for setting up for developing Wagtail. I would add that setting up https://github.com/wagtail/bakerydemo/ would give you a much more realistic demo site to test your changes against, and it includes various things like StreamField examples, Snippets and more

Other than that, once you have a local development instance up and running, you'll want to replicate the issue. In this case you need a page model with a foreign key to the Wagtail image model, which then allows you to choose images via the modal. 

I strongly recommend joining the #new-contributors channel in [Slack](https://github.com/wagtail/wagtail/wiki/Slack) where you can get a lot more detailed help

**Comment by laymonage** [comment]
Fixed in #10467.
