### ISSUE TITLE
Show accessibility checker in inline-preview

### ISSUE THREAD

**Issue by cnk** [wagtail/wagtail#10394]
I want my content editors to make incremental improvements to my site's accessibility and mobile formatting. The accessibility checker is getting better and better - but at the moment it's warnings are only available from the userbar on live pages or when viewing the preview in a separate page. I would love for my users to be able to see accessibility warnings while they are using the mobile preview pane inside the page editor. The most consistent option is probably to add the userbar to the inline preview panels (perhaps only displaying the accessibility link), but there may be better options.

**Comment by thibaudcolas** [comment]
@cnk 👋 I believe this is the same as #10136? We’ve been very keen to do this from the get-go but it proved more complex than expected.
