### ISSUE TITLE
TimeZone Support for Content Scheduling 

### ISSUE THREAD

**Issue by saad2311** [wagtail/wagtail#10390]
Currently, the content scheduling feature for publishing in Wagtail CMS only allows users to schedule content based on the timezone of the server. It can be difficult for users to publish scheduled content at a specific time in different time zones.

I proposed adding a feature of time zone support for content scheduling in Wagtail CMS. It allows users to schedule content for publishing based on their local time zone.

**Implementation:**

The steps to implement the time zone support feature in Wagtail CMS

- Adding a timezone selector to the content scheduling interface for allowing users to select the time to schedule content for publishing.
- Store the timestamp for scheduled content publishing in UTC rather than the server timestamp.
- Convert the timestamp to the selected time zone in the CMS website.
- Display the scheduled content timestamp in UTC format on the CMS website.

**Benefits:**

The benefits of adding a time zone support feature in Wagtail CMS include:

- Allow users to schedule content for publishing at a specific time in different time zones.
- Display scheduled content in UTC timestamp rather than server timestamp in the CMS website.
- Better Timezone support for publishing content in Wagtail CMS.

Adding time zone support in Wagtail CMS is an important feature for scheduling content at a specific time in different time zones.

**Comment by laymonage** [comment]
There's already a user account setting to use a preferred timezone:

<img width="675" alt="image" src="https://user-images.githubusercontent.com/6379424/236105342-2511b0b6-9835-4b8f-832d-5b8707367cd3.png">

If it is set, the scheduled publishing fields will be shown in the user's timezone. Is this not what you want?

**Comment by laymonage** [comment]
I'm closing this for now, as I think it's been covered through the time zone settings in the user profile. Let us know if it's not enough for your use case.
