### ISSUE TITLE
Deprecate insert_editor_css hook

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#10402]
Follow-up to https://github.com/wagtail/wagtail/pull/8564. `insert_editor_css` usage can be replaced with `insert_global_admin_css`, since both hooks are always used together.

We should deprecate `insert_editor_css`, preserving its documentation but adding a note that this is deprecated and going away.

And adding a deprecation warning to `hook_output` for this specific hook name.

**Comment by estyxx** [comment]
Working on this one :)

**Comment by zerolab** [comment]
Would be worth coordinating with #10459 which does the actual replacements
