### ISSUE TITLE
Update Wagtail logo to latest version

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#10404]
Wagtail’s logo has recently been refined to make it easier to read, in particular with the white wing gap better defined:

![latest logo art](https://user-images.githubusercontent.com/877585/236043212-56cfb63d-4bbb-42c0-b16a-b1f3043a85e5.png)

We need to update this in the CMS, as well as the README, and potentially other parts of the project. Here are all the areas where work is needed.

## Documentation

- [ ] README
- [ ] Favicon
- [ ] Documentation site `logo.png`

## CMS interface

- [ ] Sidebar logo
- [x] 404 page
- [x] Footer of the login screen (cf #10418)
  - Use the design system "grey on black" logo variation incl. "wagtail" logotype, but with a circle showing in WHCM only to guarantee enough contrast there.
- [x] Userbar / edit bird (cf #10418)
- [ ] Favicon

## Other

- [ ] Test image "wagtail.png"
- [x] Styleguide test image

**Comment by YashTote** [comment]
Hello! I would be pleased to contribute here. Can you please assign this to me ?

**Comment by lb-** [comment]
Partial progress completed on https://github.com/wagtail/wagtail/pull/10656 but I have left this ticket open as there is still a question of whether we want the Readme updated and a separate PR #10659

**Comment by lb-** [comment]
Can we also add the new logo to the devicon package request for our Wagtail logo.
https://github.com/devicons/devicon/issues/1559

It may be nice to also 'bump' that issue to see if it can get resolved, or even better, create a PR that puts our new logo into the requested formats.

https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#overview-on-submitting-icons

**Comment by OsafAliSayed** [comment]
where can I get the new logo .png file? to restructure the docs?

**Comment by lb-** [comment]
@OsafAliSayed I'd say first step would be prepare a new PR that rebases https://github.com/wagtail/wagtail/pull/10659 and maybe just solves the one use case of the sidebar menu. 

Either in that new PR or another after it, try to fill in the other gaps where the new logo is not updated. 

If you need source images - best place to look would be in the files updated in the first PR. These are likely SVGs only but can be converted without too much issue, you could even convert them within Wagtail or some online tool. 

https://github.com/wagtail/wagtail/pull/10656

**Comment by lb-** [comment]
@OsafAliSayed  - I ended up just doing the last few image changes when merging your PR, as they needed to have SVGs prepared and ico files etc.

However, if you are up for it, maybe you could bring the new files over to a PR on the Sphinx Wagtail theme https://github.com/wagtail/sphinx-wagtail-theme/issues/287

**Comment by OsafAliSayed** [comment]
Sure, I will give it a go!

**Comment by lb-** [comment]
Just a note for future logo updates - looks like the email header got missed.

https://github.com/wagtail/wagtail/issues/12369

Nice pick-up @Stormheg
