### ISSUE TITLE
Comment button is shown despite WAGTAILADMIN_COMMENTS_ENABLED = False

### ISSUE THREAD

**Issue by jeromelebleu** [wagtail/wagtail#10406]
### Issue Summary

The comment button is shown even if `WAGTAILADMIN_COMMENTS_ENABLED = False` is set in settings. It is however not possible to add a comment since it is not initialized.

I would suggest that the [`FieldPanel.comments_enabled`](https://github.com/wagtail/wagtail/blob/v5.0/wagtail/admin/panels/field_panel.py#L199) property should take into account `WAGTAILADMIN_COMMENTS_ENABLED`'s value. This setting is an interesting feature when comments are not wanted in a project - which is by the way easier and faster than definning `disable_comments=True` to each panel.

### Technical details

-   Python version: 3.11.2
-   Django version: 4.2.1
-   Wagtail version: 5.0

**Comment by gasman** [comment]
Confirmed on a fresh Wagtail instance running from main. Thanks for the report @jeromelebleu!

**Comment by thibaudcolas** [comment]
Thanks for the report @jeromelebleu. I thought I had covered this but it looks like I then refactored the CSS in a way that breaks this scenario. The current implementation is unfortunately very inelegant, with the setting only toggling a CSS class that shows/hides the buttons. It’d be nice to revisit it like you suggest.

**Comment by zerolab** [comment]
Related: #9670
