### ISSUE TITLE
Publishing page in draft state linked via ParentalKey deletes linked model

### ISSUE THREAD

**Issue by ramonwenger** [wagtail/wagtail#10405]
### Issue Summary

When using a Page model (`MyPage`) with another Django model (`SomeModel`) having a ParentalKey to said Page model, creating a `MyPage` in draft mode, then linking `SomeModel` to it, `SomeModel` gets deleted as soon as the `MyPage` gets published.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Install `django_modelcluster` in project
3. Add `wagtail.contrib.modeladmin` to `settings/base.py`
4. Add some page model to `models.py`, also add a related model with a ParentalKey.
```
from django.db import models
from wagtail.models import Page, Orderable
from wagtail.fields import RichTextField
from wagtail.admin.panels import FieldPanel
from modelcluster.fields import ParentalKey

class MyPage(Page):
    pass 
    # add any properties, not relevant for reproduction (just dont add an InlinePanel for the next model!)

class SomeModel(Orderable):
    page  = ParentalKey(MyPage, on_delete=models.PROTECT, related_name='related_items')
    name = models.CharField(max_length=255)

    panels = [FieldPanel('name'), FieldPanel('page')]

    def __str__(self):
        return self.name

```
5. Add a menu item for the related model inside a `wagtail_hooks.py`:
```
from wagtail.contrib.modeladmin.options import ModelAdmin, modeladmin_register

from .models import SomeModel


class SomeModelAdmin(ModelAdmin):
    model = SomeModel


modeladmin_register(SomeModelAdmin)

```
6. Migrate the project with `python manage.py makemigrations` and `python manage.py migrate`
7. Go to the admin and create a new instance of type `MyPage`, and save it as a draft
8. Create a new instance of the `SomeModel` type and link the page you just created to it
9. Go back to the page and publish it
10. The instance of `SomeModel` has been deleted

I would not expect the instance to be deleted, as there is no InlinePanel defined on the page where the relationship between the two models could be manipulated. Also, when publishing the same page again after assigning the model instance, no deletion happens.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10.6
-   Django version: 4.2.1
-   Wagtail version: 5.0
-   Browser version: Firefox 113

**Comment by gasman** [comment]
This is by design. If a model is designated as an inline child via InlinePanel / ParentalKey, its data is managed as part of the page's revision history and draft state. This means it isn't valid to also make that model editable through a view of its own, since changes made there are liable to be overwritten when saving the page, and vice versa.

**Comment by ramonwenger** [comment]
@gasman I can understand the design decision, but the relationship was just not very obvious to me, that by just having that ParentalKey defined the related items can be deleted, even without having a form element in the parent model. Maybe there could be a sentence or two in the documentation about that. Would a pull request be welcome?

**Comment by gasman** [comment]
@ramonwenger Unfortunately it's quite hard to give advice of the form "do not do X" inside documentation - it's only useful if the person is reading exactly the right page at exactly the right moment, and for everyone else it's just unhelpful clutter. If there was a recurring pattern of people making this mistake then we'd consider covering it in the documentation - but we haven't really seen any evidence of that.
