### ISSUE TITLE
Bug with removing meta fields from API

### ISSUE THREAD

**Issue by henryh9n** [wagtail/wagtail#10411]
### Issue Summary
The `_get_serializer_class` method of the `BaseAPIViewSet` class implements this code snippet which causes some (probably) unexpected errors when removing the meta fields.

```python
        all_fields = body_fields + meta_fields

        # Remove any duplicates
        all_fields = list(OrderedDict.fromkeys(all_fields))

        if not show_details:
            # Remove detail only fields
            for field in cls.detail_only_fields:
                try:
                    all_fields.remove(field)
                except KeyError:
                    pass
```

`all_fields` is converted to a `list` but then a few lines down, we try to handle `KeyError`. The list will never give a `KeyError`, but rather `ValueError: list.remove(x): x not in list`.
This can cause weird behavior when you try to remove meta fields, for instance.

### Steps to Reproduce

1. Create the following custom `APIViewSet`
```python
class BlogAPIEndpoint(PagesAPIViewSet):
    base_serializer_class = PageSerializer

    body_fields = [
        'title',
    ]

    meta_fields = []
```
2. Register the endpoint with the custom View Set: `api_router.register_endpoint('blog', BlogAPIEndpoint)`
3. Try to call the endpoint to get the results. You will get the error.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: `Python 3.8.1`.
-   Django version: `4.1.7`.
-   Wagtail version: `4.1.2`.
-   Browser version: irrelevent.

**Comment by henryh9n** [comment]
Since it's Saturday and probably many people are off, and I have some spare time, I've opened a PR fixing this issue.
Please find it here: https://github.com/wagtail/wagtail/pull/10413.
Feel free to merge it or to post your objections and suggestions.

**Comment by lb-** [comment]
<img width="1016" alt="Screenshot 2023-07-06 at 12 33 06 pm" src="https://github.com/wagtail/wagtail/assets/1396140/e9d16b16-5c96-4673-97a6-62e1fcc9bd1e">
Can confirm this issue exists
