### ISSUE TITLE
Broken Link on Core team participation page

### ISSUE THREAD

**Issue by jmgutu** [wagtail/wagtail#10410]
### Pertinent section of the Wagtail docs

[Core Participation Team](https://github.com/wagtail/wagtail/wiki/Core-team-participation)

### Details

Under the 'Core team onboarding' title, where it says 'Add to [Github Team](https://github.com/orgs/wagtail/teams/core/members) ', but the link is broken.

**Comment by gasman** [comment]
Thanks for the report @jmgutu! This section of the wiki is directed towards existing members of the core team, and I can confirm that the link does work for members with the relevant permissions, so no action needs to be taken here.

**Comment by jmgutu** [comment]
Thanks @gasman  Well noted!
