### ISSUE TITLE
register_form_field_override not working as expected

### ISSUE THREAD

**Issue by RandomJo** [wagtail/wagtail#10424]
The register_form_field_override function is not working as expected for models.TextField. I will highlight what I was trying to do as an example.

### Steps to Reproduce

1. Install django-countable-field==1.3
2. Add 'countable_field' to INSTALLED_APPS in settings.py
3. Define custom widget class:
```python
from countable_field.widgets import CountableWidget
from wagtail.admin.widgets.auto_height_text import AdminAutoHeightTextInput


class CountableAdminAutoHeightTextInput(AdminAutoHeightTextInput, CountableWidget):
    def __init__(self, attrs=None):
        print('in CountableAdminAutoHeightTextInput.__init__')
        attrs = attrs or {}
        attrs['data-count'] = 'characters'
        super().__init__(attrs)
```
4. Override TextField in an AppConfig (my file is named `core.models`):
```python
from django.apps import AppConfig
from django.db.models import TextField


class CoreConfig(AppConfig):
    name = 'core'

    def ready(self):
        from wagtail.admin.forms.models import register_form_field_override
        from core.models import CountableAdminAutoHeightTextInput  # This may be different if your widget class is defined elsewhere
        register_form_field_override(
            TextField,
            override={'widget': CountableAdminAutoHeightTextInput},
        )
```
5. Create a Page (or an inherited class) in the CMS. The search description field is a text field so it should have an active character count. In addition to not showing the character count, my print statement in CountableAdminAutoHeightTextInput.__init__ is not showing in the console so I think my override is not getting picked up. I'm wondering if Wagtail's own override is taking precedence over mine.

This was working on Wagtail 2.16.13 using a more manual method of modifying DIRECT_FORM_FIELD_OVERRIDES and overriding AdminPageForm with a custom subclass so that my change to that variable got picked up.

Please let me know if I'm doing anything incorrectly! I was attempting to use the new method after an upgrade to Wagtail 4, but it's not working as expected.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **no**

### Technical details

-   Python version: 3.8.13
-   Django version: 4.0.10
-   Wagtail version: 4.1.5
-   Django Countable Field version: 1.3
-   Browser version: Chrome 112

**Comment by gasman** [comment]
@RandomJo Does it work if you pass `exact_class=True` as an argument on register_form_field_override? I think you'll need that to ensure that it overrides [the AdminAutoHeightTextInput widget registered by Wagtail](https://github.com/wagtail/wagtail/blob/f1560625aa0dacd11bff010a641170d20258f4d4/wagtail/admin/forms/models.py#L64-L69) - that's what sets it up as the equivalent of DIRECT_FORM_FIELD_OVERRIDES, rather than FORM_FIELD_OVERRIDES. (You'll probably also need your 'core' app to appear after `wagtail.admin` in INSTALLED_APPS.)

**Comment by RandomJo** [comment]
Hey! Using `exact_class=True` did the trick! Moving 'core' to appear after 'wagtail.admin` in INSTALLED_APPS didn't matter either way, interestingly.

So, I guess I'm confused as to why `exact_class=True` works. Here's the documentation:

> exact_class – If true, the override will only take effect for model fields that are of the exact type given by model_field_class, and not a subclass of it.

That makes it sound like using exact class is _more_ discriminating, not less discriminating. Is it simply because Wagtail already has an override for TextField that uses exact class?

Regardless, thank you very much!

**Comment by gasman** [comment]
Yep, exactly - Wagtail registers `AdminAutoHeightTextInput` with exact_class=True (to ensure that it's applied to plain text fields but not rich text), and that takes priority over any definitions with exact_class=False.
