### ISSUE TITLE
Table block content is (still) not editable after it has been saved

### ISSUE THREAD

**Issue by ethanaward** [wagtail/wagtail#10427]
### Issue Summary

This is a re-opened version of #10335 - Table blocks are still not editable after the first time saving a page. This was supposed to be fixed in 4.1.5 (and #10367), but I updated my project to that version and this issue is still there. I've copied over the same reproduction steps, since it's the same issue. I also created a fresh project to make sure that it wasn't an implementation issue, and the same thing happens there.

### Steps to Reproduce

1. In a Wagtail project, create a Page with a StreamField that contains TableBlock in its block_types.
2. In the Wagtail admin, create an instance of this page and save it.
3. Add a table to your stream field, editing it as you like. This works fine.
4. Save the page.
5. Try to edit the table again.
6. Cry.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project:  (yes)

### Technical details

-   Python version: 3.10.9
-   Django version: 3.2.16
-   Wagtail version: 4.1.5
-   Browser version: Firefox 112

**Comment by laymonage** [comment]
Thanks for the report! Confirmed in 4.1.5, but not on 4.2.3 and later releases. Fix in #10430.

**Comment by ethanaward** [comment]
Appreciate the fix! Sounds like a frustrating confluence of different minor changes, glad it got resolved though.
