### ISSUE TITLE
Horizontal Filters

### ISSUE THREAD

**Issue by pySilver** [wagtail/wagtail#10439]
### Is your proposal related to a problem?

Managing custom models (registered via `Snippets` or `ModelAdmin`) would be so much easier if there would be an option to place filters horizontally (using a custom sub-template for instance). Many times, the content area is simply way too narrow to fit a table and the filter. 

The horizontal filter could be collapsible by default. I've managed to do something like that back in Wagtail 2.8

<img width="1576" alt="CleanShot 2023-05-15 at 20 15 52@2x" src="https://github.com/wagtail/wagtail/assets/1113925/f377716b-a247-47f2-82b9-4156cc13957c">

**Comment by gasman** [comment]
We're planning to redesign the way listing filters work as part of the [Universal listings](https://github.com/wagtail/roadmap/issues/33) roadmap item (previously named "[Treeless page listings](https://github.com/wagtail/rfcs/pull/82)"). We have some designs in the works that eliminate the right-hand-column layout, but nothing public as yet.

**Comment by gasman** [comment]
We've published some designs for this now - https://github.com/wagtail/wagtail/discussions/10446

**Comment by thibaudcolas** [comment]
See #11332.

**Comment by gasman** [comment]
Implemented in #11332 (and various follow-ups).
