### ISSUE TITLE
'usage_count' argument to 'blocktrans' tag must be a number. When bulk delete single snippet.

### ISSUE THREAD

**Issue by rhizodigital** [wagtail/wagtail#10441]
### Issue Summary
I get this error when using bulk delete for single item.
<img width="835" alt="Screenshot 2023-05-16 at 08 19 27" src="https://github.com/wagtail/wagtail/assets/69630853/1a044ce3-75cc-4a95-b14b-5a91edb9d630">

### Steps to Reproduce

1. Create a snippet model
2. Create single snippet item
3. Click checkbox to bulk delete, and click delete, instead of showing usage page I get the above error.

**Comment by rhizodigital** [comment]
<img width="846" alt="Screenshot 2023-05-16 at 08 39 38" src="https://github.com/wagtail/wagtail/assets/69630853/14b5cedd-1f07-42bd-9148-9a089d6713e9">

Tested again with basic single text field snippet on a fresh install in fresh venv, and got same error trying to checkbox delete (bulk delete) single item.

**Comment by laymonage** [comment]
Thanks for the report, I can confirm this issue happens when you try to delete one snippet using the bulk actions interface.
