### ISSUE TITLE
Possible bug in filter images by tag

### ISSUE THREAD

**Issue by Elrigor** [wagtail/wagtail#10450]
Howdy! I think I've found a bug on the new Wagtail 5.0. The filter images by tag doesn't work anymore. I don't know if it's just _a me thing_ or it's an actual bug, so I wanted to report it to you guys just in case!

<html>
<body>

Django Version: | 4.1.6
-- | --
FieldError
Related Field got invalid lookup: name
/home/user/project/venv/lib/python3.10/site-packages/django/db/models/sql/query.py, line 1466, in build_filter
wagtail.images.views.images.IndexView
/home/user/project/venv/bin/python
Python 3.10.6

</body>
</html>

Found that this code fragment of code in **/wagtail/images/views/images.py** may be the problem:

```py
        # Filter by tag
        self.current_tag = self.request.GET.get("tag")
        if self.current_tag:
            try:
                images = images.filter(tags__name=self.current_tag) # <--- this line 
            except (AttributeError):
                self.current_tag = None
```

If you need any further information, please let me know! 
Thank you!

**Comment by gasman** [comment]
Hi @Elrigor - thanks for the report. I'm not able to replicate this issue as described on a fresh Wagtail 5.0 instance, using the following steps:

```
pip install wagtail
wagtail start imagetags
cd imagetags
./manage.py migrate
./manage.py createsuperuser
./manage.py runserver
```

* Log in to http://localhost:8000/admin/ and upload two images through http://localhost:8000/admin/images/multiple/add/
* From the "Upload successful" view, tag the first one with "first" and the second one with "second"
* From http://localhost:8000/admin/images/ , click "first" under "popular tags"
* The listing is filtered to a single image, as expected.

If you can provide a set of steps that demostrate the problem starting from a fresh instance, I'll be happy to reopen and investigate further.

**Comment by roodie** [comment]
I am late to the party, but encountered the same problem. Upgrading django-taggit helped (we had an old 2.x version in the virtualenv which produced the same error).
