### ISSUE TITLE
Deprecation warning about using DEFAULT_FILE_STORAGE

### ISSUE THREAD

**Issue by phijma-leukeleu** [wagtail/wagtail#10461]
Inside `admin/checks.py` the setting `DEFAULT_FILE_STORAGE` is being accessed. But (at least) in Django 4.2.1 this will lead to a deprecation warning.

This line:
https://github.com/wagtail/wagtail/blob/aca340f3686cad74a7e91818c0e3b7bdb49de62c/wagtail/admin/checks.py#L192

will lead to:

```
RemovedInDjango51Warning: The DEFAULT_FILE_STORAGE setting is deprecated. Use STORAGES instead.
```

Probably better to try accessing the settings `STORAGES` first.

**Comment by gasman** [comment]
Fixed in #10462
