### ISSUE TITLE
Accessibility dialog box with class w-dialog has z-index of 130 and hides behind other elements on the page

### ISSUE THREAD

**Issue by fourfridays** [wagtail/wagtail#10471]
### Issue Summary
On Wagtail v4.2.3 websites that use Bootstrap v4+ that have right side elements on a page using [sticky and fixed classes from bootstrap](https://getbootstrap.com/docs/4.6/layout/overview/#z-index) their z-index (1020, and 1030) are higher than Wagtail's Tailwind w-dialog z-index of 130. As a result, the accessibility checker dialog box on the front-end of the website is hidden behind the elements of the page.

![image](https://github.com/wagtail/wagtail/assets/2013123/7af0defd-9b32-4b0d-b063-9501fbb11f5e)

### Technical Details
Propose changing w-dialog z-index to 9999 in tailwind.config.js
https://github.com/wagtail/wagtail/blob/9790cccd9cbe5aa957fff98663f5dfc6ac7c9ab3/client/tailwind.config.js#L119

**Comment by rgs258** [comment]
Changing to 9999 would be in line with the userbar: https://github.com/wagtail/wagtail/blob/main/client/scss/components/_userbar.scss#L42

**Comment by rgs258** [comment]
@lb- while https://github.com/wagtail/wagtail/pull/10484 is now closed, this Issue still exists and I think should be addressed by someone with the knowledge and skill to correctly solve it.

**Comment by lb-** [comment]
PR up https://github.com/wagtail/wagtail/pull/10514
