### ISSUE TITLE
MultipleChooserPanel causes a crash when comparing page revisions

### ISSUE THREAD

**Issue by jstamp** [wagtail/wagtail#10472]
### Issue Summary

If MultipleChooserPanel is used in a Page model, then comparing page revisions will cause a crash.

### Steps to Reproduce

You can confirm this by modifying the bakery demo.

1. Modify BlogPage to use a MultipleChooserPanel for the authors instead of an InlinePanel.
2. Create a few drafts of a blog page.
3. Go to the page's history and click "Compare with previous version".

You'll get an AttributeError: 'BoundPanel' object has no attribute 'formset'

It looks like it's because `MultipleChooserPanel.BoundPanel.__init__()` assumes that self.formset exists.  However, when we're comparing changes, the parent `InlinePanel.BoundPanel.__init__()` will return early.

Shouldn't MultipleChooserPanel also check if self.form is None?

**Comment by lb-** [comment]
Confirmed this issue.

```py
    # example BlogPage change
    content_panels = Page.content_panels + [
        FieldPanel("subtitle"),
        FieldPanel("introduction"),
        FieldPanel("image"),
        FieldPanel("body"),
        FieldPanel("date_published"),
        MultipleChooserPanel(
            "blog_person_relationship",
            heading="Authors",
            label="Author",
            panels=None,
            min_num=1,
            chooser_field_name="person"
        ),
        FieldPanel("tags"),
    ]
```

<img width="1040" alt="Screenshot 2023-06-14 at 7 51 05 am" src="https://github.com/wagtail/wagtail/assets/1396140/c527e080-aeb5-4341-b209-a381886eca9d">
