### ISSUE TITLE
AVIF support in Wagtail

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#10486]
AVIF is a modern image format based on the AV1 video format. It has [good browser support](https://caniuse.com/avif), notably with [only Microsoft Edge missing](https://stackoverflow.com/questions/75459594/why-doesnt-edge-support-avif-images) (licensing issues?). 

Adding it to Wagtail similarly to WebP support (#5092) would result in devs being able to convert images to AVIF via image renditions – and also I imagine allow uploading of AVIF files / support for resize operations on AVIF files.

---

As with WebP, the first step here would be [AVIF support in Willow](https://github.com/wagtail/Willow/issues/111). This seems like it could be done relatively simply since Willow already includes [pillow-heif](https://pypi.org/project/pillow-heif/) – Python bindings for libheif, which (surprise!) includes a number of AV1 codecs for AVIF support.

**Comment by thibaudcolas** [comment]
Assigning this to @salty-ivy for the time being at least so we explore what’s involve 🚀

**Comment by mrchrisadams** [comment]
hey @thibaudcolas , I've been chatting to @salty-ivy about this, and he's dones some work into this already. We have a call on Friday to explorer what this work would entail, and one of us will update this issue with more in the next day or so.

**Comment by salty-ivy** [comment]
https://docs.google.com/document/d/1u9F8Pw4TLGRBIwOt2Fofma3ER8yB9y2MEZ_-U3K9-Zg/edit

additional info about the approach is here In my proposal.

**Comment by salty-ivy** [comment]
opened a PR https://github.com/wagtail/Willow/pull/115 for the willow support

**Comment by mrchrisadams** [comment]
Hey @salty-ivy 

I ended up doing a bit of research about AVIF over the weekend, and I figured it might be useful adding some links that might be relevant for 

This post is one of the best ones I have found for understanding the file size savings compared to png or jpeg.

https://jakearchibald.com/2020/avif-has-landed/

The short version is that in lossless mode (which would probably be what we would want to save them as) these take up _more_ space than other lossless formats like png, but in renditions, as long as there is browse support, AVIF represents a significant saving.

The links above show avif files coming in around a quarter of the size of comparable photo jpegs, and for simpler illustrations it's typically half the size or better.

There seem to two main gotchas:

- encoding is more computationally expensive when creating the files
- decoding is also more computationally expensive in browsers (I wonder if we'd be able to see this in GMT...)

More below:
https://avif.io/blog/comparisons/avif-vs-png/

**Comment by thibaudcolas** [comment]
@mrchrisadams in our case, support for any given image format means:

- CMS users being able to upload images in that format, and Wagtail serving those images as-is. In this case there is no re-encoding necessary.
- Uploading in a format and generating renditions in the same format. Here, whether the renditions are lossless or not is up to the developer who set up the site.
- Uploading in a format and generating renditions in another format. Same as above.

Encoding performance isn’t really a concern for us because it only happens once per AVIF rendition of the image – and renditions are heavily cached (effectively forever)

For decoding performance, that’s a concern, but from what I understood modern software decoders put AVIF within the same order of magnitude as WebP:

- First chart of [Contemplating Codec Comparisons](https://cloudinary.com/blog/contemplating-codec-comparisons)
- First chart of [Image Coding Comparisons](https://storage.googleapis.com/avif-comparison/index.html) (note: by the AVIF team).

I think the main gotchas of AVIF compared to JPEG specifically is decoders currently expecting the full image data before starting, and the lack of progressive rendering.
