### ISSUE TITLE
Feature request: Ability to add hreflang attribute to page links inserted in the Wagtail rich text editor

### ISSUE THREAD

**Issue by sonnakim** [wagtail/wagtail#10480]
### Is your proposal related to a problem?
 
We should be using language attributes in the front-end HTML to identify changes in the human language. https://www.w3.org/TR/WCAG20-TECHS/H58.html. Because we set the `lang` language attribute properly to English on the overall html tag, web browsers and screen readers will assume that the entire page is English unless we indicate differently in the code. Rather than `<a href="/link-url/">Leer en Español</a>`, we should be writing `<a lang=”es” href="/link-url/">Leer en Español</a>`. 

Without the proper language attribute on the change, screen readers will read the changed language text with incorrect accents and phrasing, and will therefore be potentially unintelligible for say a Chinese-speaking user who wants to read the page in their native language.

This is a Section 508 accessibility bug that prevents us from following WCAG guidance about how to deal with multiple languages on a single webpage. 

### Describe the solution you'd like

We would like the ability to add `hreflang` attributes to page links inserted in the Wagtail rich text editor. 
 

### Additional context

@chosak filed a related issue here: https://github.com/wagtail/wagtail/issues/5876. In [this comment](https://github.com/wagtail/rfcs/pull/81#pullrequestreview-1195831090) (scroll down a bit) he notes:  

>Supporting `{% include_block %}` for rich text opens up the promising possibility of passing template context to rich text rendering, which is not possible with the current `| richtext` filter. This would be very useful to, for example:

- Render page links as relative, not absolute (https://github.com/wagtail/wagtail/issues/5876#issuecomment-613735337)
- Add `hreflang` attributes to page links, but only if the target page's language differs from the current page

Semi related to this: https://github.com/wagtail/wagtail/issues/4694 

Thank you for your consideration!

**Comment by sonnakim** [comment]
@thibaudcolas Thanks for getting back to me and sorry for the delay (😷 + other stuff happening). I talked with the team and you're right, it seems like the ability to add `lang` is actually what's at play — so it's really another request for the features described in #4964. I'll close this; if it's helpful, I can add a comment to #4964 to buttress that request?

**Comment by thibaudcolas** [comment]
@sonnakim no worries! Yes please, more activity on #4694 would be great. You’re the first person I see requesting this for links in particular – that could be a quicker win than adding `lang` attribute support for arbitrary text.
