### ISSUE TITLE
Chooser widget button redesign

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#10487]
- Refactor to either: “…”, dropdown tooltip – Or two buttons, edit (linked to item metadata) and clear
- Make sure chooser buttons wrap under title when there is no space
- Refine Image chooser widget styles according to designs (image thumbnail size)
- Revisit labels if desired?
- Chooser thumbnail icon padding
- Chooser buttons styles (see designs below)

Option:
![Image](https://user-images.githubusercontent.com/4907819/238614538-7453d6c8-ab6c-4fb0-ab09-234c68808ef7.png)

![Image](https://user-images.githubusercontent.com/4907819/238655516-becb2bf2-cc96-4462-8963-f3d863f39e0b.png)

As part of this work can we update the default+hover styling on the default (empty) chooser button. See:

![Image](https://user-images.githubusercontent.com/4907819/239266373-27897f57-60cb-4f1c-aa5d-ff87a357562d.png)

(top is current, bottom is new) Essentially so the padding and hover behaviour are more consistent with the other small outline buttons.

**Comment by zerolab** [comment]
@thibaudcolas 
> (top is current, bottom is new)

The images are reversed - top is new, bottom is current


Playing devil's advocate: the current UI is intuitive in that you don't need to click something to view what the options are. They appear on hover. Did we do any user testing on this?

**Comment by thibaudcolas** [comment]
@zerolab those kinds of "reveal on hover" patterns are unfortunately completely impossible to use with speech recognition software (#9666). The only option that would be viable is if we supported both hover and click (like we do for the breadcrumbs). We felt it safer for the "…" ellipsis action to consistently be on click and consistently display this kind of popover menu.

We might revisit this and support both hover and click – it’d have to be done for all instances of this "falafel actions" pattern though.

**Comment by lb-** [comment]
Relevant accessibility guideline also - https://www.w3.org/WAI/WCAG22/Understanding/content-on-hover-or-focus

---

Where receiving and then removing pointer hover or keyboard focus triggers additional content to become visible and then hidden, the following are true:

**Dismissible**
A [mechanism](https://www.w3.org/WAI/WCAG22/Understanding/content-on-hover-or-focus#dfn-mechanism) is available to dismiss the additional content without moving pointer hover or keyboard focus, unless the additional content communicates an [input error](https://www.w3.org/WAI/WCAG22/Understanding/content-on-hover-or-focus#dfn-input-error) or does not obscure or replace other content;

**Hoverable**
If pointer hover can trigger the additional content, then the pointer can be moved over the additional content without the additional content disappearing;

**Persistent**
The additional content remains visible until the hover or focus trigger is removed, the user dismisses it, or its information is no longer valid.
