### ISSUE TITLE
Choose an image modal (ImageChooser)  - whole page is redirected on error

### ISSUE THREAD

**Issue by nrezvoi** [wagtail/wagtail#10498]
### Steps to Reproduce

1.  Start a new project with `wagtail start myproject`
2. Edit home -> HomePage class as follows...

```
image = models.ForeignKey("wagtailimages.Image", on_delete=models.SET_NULL, null=True, blank=True, related_name="+")

content_panels = Page.content_panels + [
    FieldPanel("image"),
]
```
3. make && run migrations
4. Go to page edit and click on choose an image button
![image](https://github.com/wagtail/wagtail/assets/15609653/a05e1afa-9c69-4c8b-b21e-2f1dd12de106)
5.  Select Upload tab and click on Upload button without filling out the form
![image](https://github.com/wagtail/wagtail/assets/15609653/58e2864c-24fa-4227-bed7-f7ef3e838a87)

#### Expected outcome
Should see validation errors in the form

#### Actual outcome
Whole page is redirected to `/admin/images/chooser/create/`

![image](https://github.com/wagtail/wagtail/assets/15609653/eb138e42-b846-46c8-86e7-95da601a8084)

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **yes**

### Technical details

-   Python version: **3.11.3**
-   Django version: **4.2.1**
-   Wagtail version: **5.0.1**
-   Browser version: **Google Chrome 113**

**Comment by gasman** [comment]
Thanks for the report @nrezvoi! Can confirm I'm seeing this on a fresh Wagtail 5.0.1 installation.

**Comment by zerolab** [comment]
Can also confirm it happens with other choosers. e.g. https://github.com/torchbox/wagtailmedia/issues/206

**Comment by lb-** [comment]
I wonder if this broke with the w-progress adoption, this button previously had the loader classes but the associated JS would have never run.


https://github.com/wagtail/wagtail/commit/c52074250be785adaffe2a0120afe6e39e81c09b

**Comment by gasman** [comment]
Looks like this regression was introduced in fd9eed97d793c7decda25db7ee405f87827e9ba8

**Comment by lb-** [comment]
PR up with a fix https://github.com/wagtail/wagtail/pull/10506
