### ISSUE TITLE
Reports section required

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#105]
When creating a page the list of pages to choose from also links to a report listing the other pages using each page type.

This report would be better placed somewhere it could be accessed from a content auditor's perspective, without having to fake adding a page.

I dare say a reporting section to the admin might help: Content type usage, orphaned images, orphaned docs, most active users, recent user activity, search keywords etc.

**Comment by thibaudcolas** [comment]
Starting with Wagtail 2.9, the admin has a Reports section, with an API to add custom ones: https://docs.wagtail.io/en/stable/advanced_topics/adding_reports.html

I’ll close this issue as the capability is there, individual reports should be discussed in separate issues (or built as third-party extensions).
