### ISSUE TITLE
Add marking for LTS releases

### ISSUE THREAD

**Issue by WilliamHenryTanza** [wagtail/wagtail#10508]
In the [Release Notes](https://docs.wagtail.org/en/stable/releases/index.html) section, add a marker (can be something as simple as the one shown in the screenshot) to show which releases are LTS
![image](https://github.com/wagtail/wagtail/assets/16981020/c5a716fa-ef29-43b9-9ad7-a7ca8629bffc)

**Comment by souzathg** [comment]
I can work on this issue.
@lb-, what do you think about this feature?

**Comment by lb-** [comment]
Go for it @WilliamHenryTanza here is a release schedule with all previous LTS releases shown. 

https://github.com/wagtail/wagtail/wiki/Release-schedule

Updating the title may be the best way to do this for each release notes page but do investigate any Sphinx or RTD approach that is out there first.

**Comment by souzathg** [comment]
Created a pull request. Please feel free to review and suggest changes.
