### ISSUE TITLE
Configuring block_counts on a StreamField no longer disables adding blocks after max_num is reached

### ISSUE THREAD

**Issue by eyemyth** [wagtail/wagtail#10504]
### Issue Summary

In versions of Wagtail before 5.0, if a `StreamField` was defined with a `block_counts` parameter limiting the `max_num` of a given block, the block would become greyed out in the CMS once the defined limit was reached.

In Wagtail 5, the CMS user is free to add as many blocks of any type as they want. An error message only appears after they attempt to save the page or snippet.

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Edit models.py as follows:
```
from wagtail import blocks
from wagtail.admin.panels import FieldPanel
from wagtail.fields import StreamField
from wagtail.models import Page


class BlockCountPage(Page):
    body = StreamField(
        [
            ("only_one", blocks.CharBlock()),
            ("paragraph", blocks.RichTextBlock()),
        ],
        use_json_field=True,
        block_counts={
            "only_one": {"max_num": 1},
        },
    )

    content_panels = Page.content_panels + [
        FieldPanel("body"),
    ]
```
3. Make and apply migrations, then create a new "Block count page" in the CMS. Add as many of the "Only one" type blocks to the body.

<img width="942" alt="block_counts" src="https://github.com/wagtail/wagtail/assets/476078/4235cb0a-9455-41f0-b7e2-ac8a907a24fb">

- I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes

### Technical details

- Python version: 3.11.3
- Django version: 4.2.1
- Wagtail version: 5.0.1
- Browser version: Any (confirmed in Safari, Firefox, and Chrome)

**Comment by gasman** [comment]
Thanks for the report @eyemyth! I believe this is covered by #9513 - in short, the change towards not strictly enforcing block limits during editing was an intentional one (because that doesn't play well with the block splitting/insertion mechanism, and there are valid cases for temporarily exceeding the limit while copying blocks around), but there are still open issues with the UI as a result of that, which we'll address by having error indicators showing up on the excess blocks at the point they're created. As such, I'll close this as a duplicate.

**Comment by eyemyth** [comment]
I just tested with Wagtail 4.2 and that version is also affected.

Using Wagtail 4.1.6, the block is disabled as expected:

<img width="905" alt="block_counts_disabled" src="https://github.com/wagtail/wagtail/assets/476078/fa9346dd-816a-411d-b63f-4c8fcbe820ae">

**Comment by eyemyth** [comment]
@gasman  - Ah, I was searching issues for "block_counts"

I'd love to be able to enforce the older behavior. We use StreamField in a few cases where we want to impose lots of structure and our CMS users would never be doing any kind of large-scale restructuring.

For example, this is used to add valuations on a page for an appraisal:

```
from wagtail.blocks import IntegerBlock
from wagtail.blocks import StreamBlock
from wagtail.blocks import StructBlock
from wagtail.blocks import StructValue


class EstimateBlock(StructBlock):
    lower = IntegerBlock()
    upper = IntegerBlock(required=False)


class AuctionEstimateValue(StructValue):
    @property
    def context(self):
        return "Auction"


class RetailEstimateValue(StructValue):
    @property
    def context(self):
        return "Retail"


class InsuranceEstimateValue(StructValue):
    @property
    def context(self):
        return "Insurance"


class EstimateStreamBlock(StreamBlock):
    auction = EstimateBlock(value_class=AuctionEstimateValue)
    retail = EstimateBlock(value_class=RetailEstimateValue)
    insurance = EstimateBlock(value_class=InsuranceEstimateValue)

    class Meta:
        min_num = 1
        block_counts = {
            "auction": {"max_num": 1},
            "retail": {"max_num": 1},
            "insurance": {"max_num": 1},
        }
```
