### ISSUE TITLE
find_embed hook

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#1050]
Wagtail provides two options for finding embeds
- A fixed list of provider URLs
- Embedly

So if you need an embed provider that isn't in wagtails built in list, your only option is to sign up to embedly.

I propose that we add a `find_embed` hook. Developers can use this hook to register embed handlers containing their own custom logic.

The embed finder functions will take 1 positional argument (the URL) and return an `Embed` object (or `None`). They must also have `**kwargs` allowing the get_embed function to pass in any extra hints to the function without other functions breaking (they can choose to ignore the kwargs though).

Example

```
@register_hook('find_embed')
def youtube(url, **kwargs):
    if url.startswith('http://www.youtube.com'):
        ...
        return Embed(...)
```

**Comment by gasman** [comment]
:+1:

**Comment by davecranwell** [comment]
The need for this came from recent sites which are all on secure HTTP. OEmbed doesn't appear to provide a method of requesting the secure version of a URL. Embedly does.

Having discovered this limitation I'm personally more inclined to always install Embedly on all future sites, but for those without that luxury it might be nice to package a few common `find_embed` hooks with wagtail. Otherwise it feels like rather a lot of work to create such a minor feature for every single site created.

**Comment by tomdyson** [comment]
I'm in favour of Karl's suggestion. It's a nuisance to sign up to an Embedly account just to make YouTube work on secure sites, or to embed gists. Can / should we bundle the common ones?

**Comment by chrxr** [comment]
@kaedroho will create new python library which we will reference for this.

**Comment by kaedroho** [comment]
One issue with using hooks is that the order isn't guarenteed and you would want some handlers to run before others (``youtube_https`` before ``oembed`` for example).

One other idea could be to change ``WAGTAILEMBEDS_EMBED_FINDER`` to accept a list of values so the order can be defined by the developer:

Eg:
```
WAGTAILEMBEDS_EMBED_FINDERS = [
    'myproject.embed_finders.youtube_https',
    'wagtail.wagtailembeds.finders.oembed',
]
```

**Comment by kaedroho** [comment]
This is covered by the "class-based embed finders" and new embeds configuration that was introduced in Wagtail 1.12.

http://docs.wagtail.io/en/v1.13/advanced_topics/embeds.html
