### ISSUE TITLE
Snippet view list - unable to switch language when search query has been filled

### ISSUE THREAD

**Issue by nrezvoi** [wagtail/wagtail#10528]
### Issue Summary
![image](https://github.com/wagtail/wagtail/assets/15609653/98d8d970-4676-4344-b7ce-fc5992359460)

When something has been filled in the search input, clicking on the language switcher to change lang does nothing. No JS errors in the console as well.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Create `TestSnippet` model as follows
```
class TestSnippet(index.Indexed, TranslatableMixin, models.Model):
    title = models.CharField(max_length=255)

    panels = [
        FieldPanel('title'),
    ]

    search_fields = [
        index.AutocompleteField('title'),
        index.FilterField('locale_id'),
    ]

    def __str__(self):
        return self.title

    class Meta(TranslatableMixin.Meta):
        pass
```
3. Add `wagtail_hooks.py` with the following:
```
from wagtail.snippets.views.snippets import SnippetViewSet
from wagtail.snippets.models import register_snippet
from .models import TestSnippet

class TestSnippetViewSet(SnippetViewSet):
    model = TestSnippet
    base_url_path = "test/test-snippet"
    list_display = ("title",)


register_snippet(TestSnippet)
```
4. In `settings/base.py` add
```
"wagtail.locales",
"wagtail.contrib.simple_translation",
```
to installed apps + enable i18n
```
WAGTAIL_I18N_ENABLED = True

LANGUAGES = WAGTAIL_CONTENT_LANGUAGES = [
    ("en", "English"),
    ("et", "Estonian"),
]
```

6. Make && run migrations
7. Add langs through UI in `Settings -> Locales`

8. Go to the snippet's list view, type something in the search input and try to select other language

#### Expected outcome
Language is switched

#### Actual outcome
Nothing happens

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **yes**

### Technical details

-   Python version: **3.11.3**
-   Django version: **4.2.1**
-   Wagtail version: **5.0.1**
-   Browser version: **Google Chrome 114**

**Comment by evilmonkey19** [comment]
Hi!

I've been trying to replicate your bug, but I couldn't. I've used Firefox Developer Edition _118_ and Chrome _116_. I've tried with different ways to replicated. I'm sorry but perhaps you could be more specific if the problem still exists. Are you sure there is no log info you can show?

![ezgif com-optimize](https://github.com/wagtail/wagtail/assets/56732262/96eb7f24-bb83-4fbb-b09d-7c48786bb904)

**Comment by lb-** [comment]
Closing for now, if this can be reproduced with a bit more info, feel free to comment and we can reopen.
