### ISSUE TITLE
Replace `total_ordering` usage with comparison functions implementation

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#10526]
### Is your proposal related to a problem?

We have two instances of `total_ordering` usage within the codebase:

https://github.com/wagtail/wagtail/blob/cd5200c8e1ac0d7299fd9c398b2b994606b3c7d2/wagtail/admin/search.py#L12-L13

https://github.com/wagtail/wagtail/blob/cd5200c8e1ac0d7299fd9c398b2b994606b3c7d2/wagtail/admin/widgets/button.py#L11-L12

Even though it's convenient, `total_ordering` is known to be slow. According to [Python's docs](https://docs.python.org/3/library/functools.html#functools.total_ordering):

> **Note**
> While this decorator makes it easy to create well behaved totally ordered types, it does come at the cost of slower execution and more complex stack traces for the derived comparison methods. If performance benchmarking indicates this is a bottleneck for a given application, implementing all six rich comparison methods instead is likely to provide an easy speed boost.

Django recently removed their usage of `total_ordering` in https://github.com/django/django/pull/16958/commits/ee36e101e8f8c0acde4bb148b738ab7034e902a0 (probably not all usages, I haven't checked).

### Describe the solution you'd like

Replace `total_ordering` with implementations of `__eq__()`, `__ne__()`, `__lt__()`, `__le__()`, `__gt__()`, and `__ge__()`.

### Describe alternatives you've considered

Keep using `total_ordering`

### Additional context

I found this while fixing an incorrect import of `total_ordering` in #10525.

**Comment by MikeMavrok** [comment]
I am pretty sure I can contribute to solving this issue

**Comment by WhatIsThisVJ** [comment]
Hi @laymonage, I tried implementing the functions and have linked a PR. Please let me know if anything's wrong, Thanks in advance :)

**Comment by gasman** [comment]
Thanks @WhatIsThisVJ! I see you've made the change on your own fork of Wagtail, but it looks like you haven't actually opened a PR yet to get it merged into Wagtail itself - you'll need to do that from https://github.com/wagtail/wagtail/pulls.

**Comment by WhatIsThisVJ** [comment]
Hey @laymonage!
I have now linked a PR, please review it.

**Comment by WhatIsThisVJ** [comment]
Hey @gasman @laymonage,

I have opened a PR but there seems to be a failing test case, and I am not able to figure out the reason. Can you please  help me with that

**Comment by gasman** [comment]
@WhatIsThisVJ Don't worry about that one - that's testing against the git main version of Django, which has recently made some incompatible changes that we haven't addressed yet, and so that's failing across the board, not just on your PR.

**Comment by WhatIsThisVJ** [comment]
Okay, Thanks @gasman  for clearing up the doubt. Let me know if there's anything wrong with the PR.

**Comment by infraredCoding** [comment]
Hello @laymonage,
I'm new to the codebase so decided to start off here. I've made a PR, can you please check it? As I've said, I'm new here. So if I've missed something, feel free to let me know

**Comment by rohitsrma** [comment]
I would like to work on this issue!

**Comment by lb-** [comment]
@rohitsrma thanks but there is already a PR up. 

https://github.com/wagtail/wagtail/pull/10545

**Comment by rohitsrma** [comment]
@lb- thanks for the reply. I apologize for not seeing the existing PR.
