### ISSUE TITLE
Missing variables in template _modern_dropdown.html

### ISSUE THREAD

**Issue by serl** [wagtail/wagtail#10538]
### Issue Summary

I installed [django-fastdev](https://github.com/boxed/django-fastdev) in my project, and now I cannot access the Wagtail admin anymore.
While I take full responsibility on my misadventures 😆, the error points me to this line:

https://github.com/wagtail/wagtail/blob/7b3b55ff93c223b2d7b1d25910c32db963be5ce2/wagtail/admin/templates/wagtailadmin/pages/listing/_modern_dropdown.html#L3

Telling me that `self` is not defined there.

The next error reported is in this line:

https://github.com/wagtail/wagtail/blob/7b3b55ff93c223b2d7b1d25910c32db963be5ce2/wagtail/admin/templates/wagtailadmin/pages/listing/_modern_dropdown.html#L13

It says that `title` does not exist in `attrs`, but `aria-label` does (so I guess it should read `{{ button.attrs }}` instead of `aria-label="{{ button.attrs.title }}"`?)

Then a new error popped up and I disabled fastdev 😮‍💨 

While [I already suggested that no check on external libraries should be made in fastdev](https://github.com/boxed/django-fastdev/issues/29), I think that the errors reported above are valid and maybe a tool like fastdev could be helpful to increase the quality of Wagtail's templates.

What do you think? Should I have posted this on Slack instead? 😊 

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Install django-fastdev
3. Open the admin site

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11.3.
-   Django version: 4.2.2.
-   Wagtail version: 5.0.1.
-   Browser version: Firefox 113.

**Comment by thibaudcolas** [comment]
Thank you @serl, that’s definitely worth reporting! I don’t know whether one of Wagtail’s templates having an issue like this qualifies as a bug or not. Compatibility with `fastdev` / `string_if_invalid` / etc would certainly be nice.

For what it’s worth I’m working on this very template right now, so there’s a chance those will be fixed _soon_, assuming the template is indeed never used with those variables.

**Comment by thibaudcolas** [comment]
This has indeed been fixed _soon_ some time between June and now, I forget when. We don’t have a process for `string_if_invalid` so this could well pop up elsewhere, but not _this one_.
