### ISSUE TITLE
Title/slug autosync is broken for Cyrillic characters in 5.0

### ISSUE THREAD

**Issue by drimacus182** [wagtail/wagtail#10532]
### Issue Summary

When using Cyrillic letters for a page title, the corresponding slug isn't synced as expected. It is changed only the first time, all subsequent changes to the title don't affect slug at all.

It is happening on a **Page model**, with **unmodified panels** for 'slug' and 'title' fields, on a fresh bakerydemo

### Steps to Reproduce

I'm using a fresh [bakerydemo](https://github.com/wagtail/bakerydemo) instance in gitpod (commit 046eb8ecf866b88b6e4f402a66e04eefea93f504)

1. Log in as admin
2. Under **Pages** -> **Blog**  create a new child page (BlogPage)
3. Input `Тестовий заголовок` as a title
4. Switch to the "Promote" tab. Observe a slug `testovij-zagolovok`
5. Now switch to the "Content" tab again. Change a title to `А зараз щось зовсім інше`
6. Switch to the "Promote" tab. Observe that the slug is still `testovij-zagolovok`. It hasn't changed.

<br>

![wagtail-slug-issue](https://github.com/wagtail/wagtail/assets/3090883/73852d22-f9e9-40cf-b541-363dbcd8f48d)

<br>

This behaviour is completely different to what it was prior to 5.0. It needs to be fixed or at least documented. 

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes, on a fresh bakerydemo in gitpod

### Technical details

-   Python version: 3.8.12
-   Django version: 4.2.2
-   Wagtail version: 5.0.1
-   Browser version: Tested in Firefox 113, Chrome 114

**Comment by lb-** [comment]
I have confirmed I can reproduce this issue and I'm working on a fix. 

Thank you for the detailed bug report @drimacus182

**Comment by lb-** [comment]
PR up #10541
