### ISSUE TITLE
Long textareas scroll to top on every keypress

### ISSUE THREAD

**Issue by chosak** [wagtail/wagtail#10549]
### Issue Summary

In Wagtail versions 4.1.6 and 4.2.4, pressing a key inside a long textarea scrolls back to the top, making it impossible to edit long text. This bug appears fixed in 5.0, but I'm wondering if it might be possible to get the fix backported to the older versions.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`, then `cd myproject`.
2. Edit models.py as follows:
   ```py
   from django.db import models
   
   from wagtail.admin.panels import FieldPanel
   from wagtail.models import Page
   
   class HomePage(Page):
       body = models.TextField(null=True, blank=True)
   
       content_panels = Page.content_panels + [
           FieldPanel('body'),
       ]
   ```
4. `./manage.py makemigrations && ./manage.py migrate && ./manage.py createsuperuser`
5. `./manage.py runserver` then log in and edit the existing page at http://localhost:8000/admin/pages/3/edit/.
6. Try pasting a large amount of text, then scroll to the bottom and try pressing keys. The page will scroll back to the top of the textarea:

![scroll](https://github.com/wagtail/wagtail/assets/654645/4b81b90c-b033-408c-b278-01ff4ef25196)

This doesn't happen in 5.0. Looking at the [5.0 release notes](https://docs.wagtail.org/en/latest/releases/5.0.html) I saw two bug fixes which seem potentially related (https://github.com/wagtail/wagtail/commit/e72e454ba506dec7dfa34dad7a621741b9824aff and https://github.com/wagtail/wagtail/pull/10366), but without better understanding of this code I'm not exactly sure what the problem is/was.

If the fix is something that can be isolated from a larger set of changes, it would be great to get it backported to the 4.1 or 4.2 versions.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.8.16
-   Django version: 4.1.9
-   Wagtail version: Confirmed on 4.1.6 and 4.2.4
-   Browser version: Chrome 114

**Comment by lb-** [comment]
@chosak glad to hear that this issue does not happen in 5.0, sorry it's a problem in earlier versions. 

It may be a bit tricky to backport this to the earlier versions of Wagtail as we have built this on Stimulus and adopted a much newer (many years) package for autosize instead of the jQuery one.

**Comment by gasman** [comment]
Unless we can establish that this is a regression from an earlier release (in which case that'll give us a pointer to how to fix it again without requiring Stimulus), I don't think this is really a candidate for backporting.

**Comment by lb-** [comment]
Here is a rough work around, not 100% sure this will work but should be an ok start, if you add this script after the main Wagtail scripts it should hopefully replace the global `window.autosize` with the new module.

This may cause a bit of memory bloat as we are not removing the resizeObserver when the textarea gets removed from the DOM (e.g. streamfield removal), but should not really be noticeable. Adding a mutation observer for when this gets removed from the DOM is probably a lot more work. This should be pretty close to the new Stimulus implementation.

```
<script type="module">
// See https://www.npmjs.com/package/autosize documentation. - multiple CDNs available or host your own locally
// import autosize from 'https://cdn.jsdelivr.net/npm/autosize@6.0.1/+esm'
import * as autosizeUtil from 'https://esm.run/autosize';


document.addEventListener("DOMContentLoaded", () => {
  const debounce = (callback, wait) => {
    let timeoutId = null;
    return (...args) => {
      window.clearTimeout(timeoutId);
      timeoutId = window.setTimeout(() => {
        callback.apply(null, args);
      }, wait);
    };
  }

  window.autosize = function($element) {
    autosizeUtil.default($element);
    const handleResize = debounce(() => autosizeUtil.default.update($element), 50);
    const resizeObserver = new ResizeObserver(handleResize);
    resizeObserver.observe($element);
  };
});
</script>
```

**Comment by chosak** [comment]
Thanks for the quick feedback, and for the workaround @lb-! 

I tried out some older versions and it looks like this behavior first showed up in Wagtail 3.0, and is related to the old jQuery autosize plugin. Trying out some newer versions of the autosize plugin, on Wagtail 4.1 the bug goes away with autosize v5.0.2, but using the latest autosize v6.0.1 also works.

We'll investigate your suggested approach and can post back if we confirm a workaround.

**Comment by lb-** [comment]
@chosak how did you go? Can we close this issue?

**Comment by chosak** [comment]
@lb- we ended up using autosize v6.0.1 (in https://github.com/cfpb/consumerfinance.gov/pull/7913) and it seems to be working well! Closing this, thanks again.
