### ISSUE TITLE
StreamField: Automatically select when single block type

### ISSUE THREAD

**Issue by SebCorbin** [wagtail/wagtail#10584]
### Is your proposal related to a problem?

Let's take a FAQ StreamField

```python
class FaqStreamBlock(StreamBlock):
    required = True
    question = StructBlock(
        [
            ("title", CharBlock(label="Question")),
            (
                "answer",
                RichTextBlock(
                    label="Answer",
                    features=["bold", "italic", "link", "ul"],
                ),
            ),
        ],
        icon="help",
    )

    class Meta:
        template = "blocks/accordion_block.html"
        label = "FAQ question"

class HelpPage(Page):
    # Body section of the HomePage
    faq = StreamField(
        FaqStreamBlock,
        verbose_name="FAQ",
        blank=True,
        use_json_field=True,
    )
    ...
```

### Describe the solution you'd like

Now in the UI, I get a single block type when clicking the "plus" button, there's even the "search block type" field displayed, which is a bit overkill, and we could add the block already as there is a unique block type.

### Describe alternatives you've considered

I've considered using the parameters `min_num=1, max_num=1` with a default, but the value could be empty so I'm not willing to force the user's hand. 

### Additional context

This problem could also be taken from another angle, is there a better way to handle non-mixed StreamFields?

**Comment by laymonage** [comment]
Thank you for filing the issue, I believe this is a duplicate #3998.
