### ISSUE TITLE
Small instruction how to work with forks

### ISSUE THREAD

**Issue by pySilver** [wagtail/wagtail#10594]
I've had hard times using a fork in production while PR is not landed into the main. The main problem was the lack of information on how to build it in a way that Wagtail fork would contain static files. Turns out there is perfect instruction on SO for that.

### Pertinent section of the Wagtail docs

Development section that may benefit of few words regarding builds: https://docs.wagtail.org/en/stable/contributing/developing.html#development

### Details

The content of the following SO answer made by @gassan really deserves a place in that section. 

https://stackoverflow.com/questions/57404087/how-does-one-package-a-fork-of-wagtail-for-installation/57407742#57407742

**Comment by gassan** [comment]
It was @gasman - not me))

**Comment by pySilver** [comment]
Haha, correct!:) sorry for typo

**Comment by anshikavashistha** [comment]
@pySilver May I work on this issue?

**Comment by zerolab** [comment]
@anshikavashistha thank you for your interest. Please have a read through https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html, and specifically https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html#finding-an-issue

**Comment by anshikavashistha** [comment]
Okay Thankyou
