### ISSUE TITLE
StreamField: Split action does not respect max_num

### ISSUE THREAD

**Issue by SebCorbin** [wagtail/wagtail#10614]
### Issue Summary

When using `max_num` option on a StreamField, the '+' insert buttons are successfully disabled once max_num is reached. But when adding multiple paragraphs in a paragraph block, it is possible to split them using the Split action (via '+' in the sidebar) and thus going over the limit of blocks

### Steps to Reproduce

1. Use the bakerydemo project for instance
2. Change one of the StreamField to add `max_num=1`
3. In the admin interface, add a paragraph block, the '+' is disabled
4. In that paragraph block, add 2 text paragraph
5. Place your cursor on one of them, a '+' button appear in the streamfield sidebar
6. Click that '+' button and choose split action, and paragraph block

_Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?_
The split action should do nothing (if paragraph block means another block), it should still for other block (heading) as they work inside Draftail

- I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes (main branch - 5.1.0a)

### Technical details

-   Python version: 3.10.6
-   Django version: 4.2
-   Wagtail version: Wagtail v5.1a0
-   Browser version: Firefox 114

**Comment by gasman** [comment]
Thanks for the report @SebCorbin! See the discussion on #9513 - our plan going forward is to remove the hard restriction on exceeding max_num during editing, but have validation errors display at that point, as they do on save. Will close this as a duplicate.

**Comment by gasman** [comment]
Looks like I never actually closed this as a duplicate as I said I would :-)
