### ISSUE TITLE
Add support for Pillow 10.0.0

### ISSUE THREAD

**Issue by yuekui** [wagtail/wagtail#10631]
### Is your proposal related to a problem?

Pillow 10.0.0 [has just been released.](https://github.com/python-pillow/Pillow/releases/tag/10.0.0) Wagtail 5.0.2 [restricts Pillow support to <10.0.0.](https://github.com/wagtail/wagtail/blob/a68f69f2d7f46943cc23b7f65349448b23044869/setup.py#L30)

Adding support for the new Pillow release is desired.

### Describe the solution you'd like

Add support for Pillow 10.0.0

### Describe alternatives you've considered

Not applicable.

### Additional context

This is a relevant dependency to the project, and to sites running it.

**Comment by G-Rath** [comment]
I have requested this be backported to v4.1 to allow addressing [PYSEC-2023-175](https://osv.dev/vulnerability/PYSEC-2023-175) while remaining on the current LTS version.
