### ISSUE TITLE
Convert initTooltips to Stimulus

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#10668]
Follow-up to #8565 (and more recently #10620). We no longer use Bootstrap for tooltips. Some of our tooltips were switched over to Tippy.js before the introduction of Stimulus in Wagtail, and it’d be great to convert them over to the new `w-tooltip` controller introduced in #10620.

Specifically, it’s the vanilla JS `initTooltips` function looking for `data-tippy-content` attributes that we need to replace with Stimulus. For example:

```diff
<a href="{% url 'wagtailadmin_pages:history' parent_page.id %}"
    class="{{ nav_icon_button_classes }}"
+   data-controller="w-tooltip"
+   data-w-tooltip-content-value="{% trans 'History' %}"
-    data-tippy-content="{% trans 'History' %}"
    data-tippy-offset="[0, 0]"
+    data-w-tooltip-placement-value="bottom"
-    data-tippy-placement="bottom"
    aria-label="{% trans 'History' %}"
>
    {% icon name="history" classname=nav_icon_classes %}
</a>
```

Files
1. wagtail/admin/templates/wagtailadmin/pages/page_listing_header.html
2. wagtail/admin/templates/wagtailadmin/shared/human_readable_date.html
3. wagtail/admin/templates/wagtailadmin/shared/page_status_tag_new.html
4. wagtail/admin/templates/wagtailadmin/shared/side_panel_toggle.html
5. wagtail/admin/templates/wagtailadmin/shared/headers/page_edit_header.html
6. wagtail/admin/templates/wagtailadmin/shared/workflow_history/list.html
7. wagtail/contrib/modeladmin/tests/test_simple_modeladmin.py (unit test update)
8. wagtail/snippets/templates/wagtailsnippets/snippets/headers/edit_header.html

The main benefit here is simpler initialisation of those tooltip components regardless of where they are used. Additionally we could also convert more of those Tippy.js data-tippy to Stimulus-powered equivalents, though this isn’t needed for what the tooltips are used for currently.

Here is a rough start on how to enhance `TooltipController` for support of the `offset` value.

```diff
// FILE: client/src/controllers/TooltipController.ts
export class TooltipController extends Controller<HTMLElement> {
  static values = {
    content: String,
+    offset: Array,
    placement: { default: 'bottom', type: String },
  };

+  declare readonly hasOffsetValue: boolean;
  declare contentValue: string;
+  declare offsetValue: [number, number];
  declare placementValue: Placement;
  tippy?: Instance<Props>;

  // ...
  get options(): Partial<Props> {
    return {
      content: this.contentValue,
      placement: this.placementValue,
      plugins: [hideTooltipOnEsc],
+      ...(this.hasOffsetValue && { offset: this.offsetValue }),
    };
  }
// .. 
```

Additionally, here is a rough unit test to check that the offset value works correctly.

```js
// FILE client/src/controllers/TooltipController.test.js
  it('should support passing the offset value', async () => {
    document.body.innerHTML = `
    <section>
      <button
        id="button"
        type="button"
        data-controller="w-tooltip"
        data-w-tooltip-offset-value="[10, 20]"
      >
        CONTENT
      </button>
    </section`;

    await Promise.resolve(requestAnimationFrame);

    const tippy = application.getControllerForElementAndIdentifier(
      document.getElementById('button'),
      'w-tooltip',
    ).tippy;

    expect(tippy.props).toHaveProperty('offset', [10, 20]);
  });
```

Once this is done, the data-tippy-offset can be replaced with a Stimulus value in all usage.

```diff
-    data-tippy-offset="[0, 0]"
+    data-w-tooltip-offset="[0, 0]"
```

Stimulus will parse this as a JSON string automatically.

Important: Once done...

1. `initTooltips` export from `client/src/includes/initTooltips.ts` can be fully removed and all usage in other code removed.
2. `client/src/includes/initTooltips.ts` can be renamed to `client/src/utils/tooltips.ts`, and imports of things from this file can be updated to the new path.

**Comment by lb-** [comment]
I have updated this ticket with a bunch more info on how to make the required changes to the JS and unit tests.

Flagging as a good first issue for anyone who is keen on a HTML template update with some small scale JS changes.

Please ensure you have a read of the Stimulus docs to understand the JS changes.

**Comment by phil-marshall-dev** [comment]
Hi! I'd like to work on this issue

**Comment by lb-** [comment]
Go for it @phil-marshall-dev - add a comment if you have any questions before digging into it.

**Comment by lb-** [comment]
@subhajit20 here's our guide for making your first contribution - https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html

Please have a read and if you have general getting started questions it's best to reach out in Slack.

**Comment by subhajit20** [comment]
@lb- made a pr. 
Please check and let me know about further modifications.
