### ISSUE TITLE
Issue with TypedTableBlock Meta Class

### ISSUE THREAD

**Issue by tsmaddox15** [wagtail/wagtail#10677]
### Issue Summary

I've been working with the TypedTableBlock trying to create my own templates to eventually use them in snippets. I've ran into an issue where if I try to change Class Meta, the object returns with type 'wagtail.blocks.stream_block.StreamValue' instead of type 'wagtail.contrib.typed_table_block.blocks.TypedTable'>.  This is causing issues where _raw_data is never being converted into rows and columns making it impossible to grab the blocks from those list.

### Steps to Reproduce

1. Create a TypedTableBlock following the doc, but include a meta class
```
from wagtail.contrib.typed_table_block.blocks import TypedTableBlock
from wagtail import blocks
from wagtail.images.blocks import ImageChooserBlock

class DemoStreamBlock(blocks.StreamBlock):
    title = blocks.CharBlock()
    paragraph = blocks.RichTextBlock()
    table = TypedTableBlock([
        ('text', blocks.CharBlock()),
        ('numeric', blocks.FloatBlock()),
        ('rich_text', blocks.RichTextBlock()),
        ('image', ImageChooserBlock())
    ])
     class Meta: 
       template = "/new_template.html"

```
2. Add block to a model.
3. Create new table in admin editor.
4. Run debugger with breakpoint inside of new template. Value.row and .column weren't created and you are left with raw_data.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I've tried the above on a fresh install. 
- Here are screenshots of using no meta class
[Screenshot of correct Type]( https://prnt.sc/QKmWP86M4-W4)
[Correct Value Data](https://prnt.sc/6uRwYlNScaYu)

- Screenshots when using meta class.
[Screenshot of incorrect type](https://prnt.sc/TtROkb98NiHb)
[Incorrect Value Data](https://prnt.sc/oHSdyTpC2_xV)
### Technical details

-   Python version: 3.10.6
-   Django version: 4.1.9
-   Wagtail version: 4.2.4
-   Browser version: Firefox 110

**Comment by gasman** [comment]
As far as I can see, what you're describing is the intended behaviour. Your Meta class with the template is defined on the StreamBlock class, so the `value` you receive in that template will be the StreamBlock value, not a TypedTableBlock value.

Perhaps you wanted

    table = TypedTableBlock([
        ('text', blocks.CharBlock()),
        ('numeric', blocks.FloatBlock()),
        ('rich_text', blocks.RichTextBlock()),
        ('image', ImageChooserBlock())
    ], template="/new_template.html")

instead?

**Comment by tsmaddox15** [comment]
That worked, however when I try to make the table accessible through a snippet I'm getting the same issue as before. Probably because my snippetblock has a meta class.

Is accessing it through a snippet just not possible? Sorry if I'm missing something.

**Comment by gasman** [comment]
Accessing a TypedTableBlock through a snippet should be possible, but without more details it's hard to say what's going wrong there - probably best to take this to [the #support channel in the Wagtail Slack](https://docs.wagtail.io/en/stable/support.html).
