### ISSUE TITLE
Saving draft changes of snippets doesn't save tags

### ISSUE THREAD

**Issue by gsakkis** [wagtail/wagtail#10675]
### Issue Summary

The `DraftStateMixin` doesn't play well with `django-taggit` for adding tags to snippets.

### Steps to Reproduce

1. Add to models.py
```py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel
from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase
from wagtail.admin.panels import FieldPanel
from wagtail.models import DraftStateMixin, RevisionMixin
from wagtail.snippets.models import register_snippet


class AdvertTag(TaggedItemBase):
    content_object = ParentalKey('Advert', on_delete=models.CASCADE, related_name='tagged_items')


@register_snippet
class Advert(DraftStateMixin, RevisionMixin, ClusterableModel):
    text = models.CharField(max_length=255)
    tags = TaggableManager(through=AdvertTag, blank=True)
    _revisions = GenericRelation("wagtailcore.Revision", related_query_name="advert")

    panels = [
        FieldPanel('text'),
        FieldPanel('tags'),
    ]
```

3. Run `./manage.py makemigrations` and `./manage.py migrate`
4. Add a new model from the admin UI (http://127.0.0.1:8000/admin/snippets/demo/advert/add/) with some tags. The tags are saved at creation as expected.
5. Edit the created model by adding and/or removing some tags. The updated set of tags is not saved.

### Technical details

-   Python version: 3.8
-   Django version: 4.1.7
-   Wagtail version: 4.2

**Comment by gasman** [comment]
Was already fixed as part of #10388.
