### ISSUE TITLE
Avoid purging Revisions in use by third-party packages

### ISSUE THREAD

**Issue by Stormheg** [wagtail/wagtail#10678]
I originally raised this as part of some rework on the `purge_revisions` management command in https://github.com/wagtail/wagtail/pull/10619#pullrequestreview-1528373346. We considered it out of scope to fix the issue in that PR since Wagtail has always worked like this. Hence I'm raising it again separately in this issue.

### Is your proposal related to a problem?

Wagtail provides a `purge_revisions` management command to delete stale `Revision` objects from the database. This command is aware of revisions that are still in use by Wagtail's workflow feature and avoids deleting those revisions ([link to source](https://github.com/wagtail/wagtail/blob/3d0282573d0d23f9eabe2fb6427e58b01f79ffe0/wagtail/management/commands/purge_revisions.py#L61-L66)).

However, it is somewhat common for third-party packages to rely on a specific revision. [wagtail-ab-testing](https://github.com/wagtail-nest/wagtail-ab-testing/blob/d04bd0032c4335a839c781851b12fe16037950de/wagtail_ab_testing/models.py#L76) is a real world example of this. It maintains a ForeignKey to a specific revision to track an AB experiment. If `purge_revisions` were to remove a revision in use by wagtail-ab-testing, experiment data loss would occur.

Data loss can be prevented by specifying the ForeignKey with `on_delete=models.PROTECT` but `purge_revisions` wouldn't be able to handle this and crash with a `ProtectedError`. This means third-party packages have no recourse: either they allow the revisions they depend on to be deleted or they mark their relations as protected and break Wagtails `purge_revisions` command.

### Describe the solution you'd like

I propose `purge_revisions` gracefully recovers from `ProtectedError` when trying to delete a revision. I also propose we document that relations to a `Revision` should be marked with `on_delete=models.PROTECT` if data loss is not desirable.

I also feel like the `purge_revisions` command should report the number of revisions that it couldn't delete because they were protected.

### Describe alternatives you've considered

An alternative mechanism I considered would be an API that allows packages to inform Wagtail which revisions they still use. The `purge_revisions` command can take this information into account and avoid revisions still in use.

This is a more complex solution with no apparent benefit over the solution described above.

**Comment by Stormheg** [comment]
I discussed this approach with @laymonage and @gasman today and we feel the solution described is appropriate. The alternative considered is not an appropriate solution and must be ignored.

Tasks to fix this issue:
 - **Code**: wrap the call to `revision.delete()` in the purge_revisions command with try/except and make it ignore `ProtectedError`. That change would need to be made here: https://github.com/wagtail/wagtail/blob/main/wagtail/management/commands/purge_revisions.py#L78-L79
 - **Code**: create and increment an counter every time a ProtectedError occurs and display this counter when the command finishes.
 - **Tests:** write an unit test that proves the purge_revisions command won't crash when a ProtectedError occurs. Here is a good place to add a new test: https://github.com/wagtail/wagtail/blob/dec8ec47ed45560d575d03365ca3198162f171a9/wagtail/tests/test_management_commands.py#L619 _I understand writing a unit test may be difficult for people new to coding but I encourage you to try!_
 - **Docs**: document that purge_revisions won't delete revisions that are protected here: https://docs.wagtail.org/en/latest/reference/management_commands.html#purge-revisions
 - **Docs**: add a note to the [revision reference documentation](https://docs.wagtail.org/en/latest/reference/pages/model_reference.html#revision-model-ref) explaining that stale revisions may be deleted by the purge_revisions command. Also document that Wagtail implementors may want to use a ForeignKey with `on_delete=models.PROTECT` when referring to a specific revision they don't want to be deleted.

I encourage new contributors to try work on this issue, I hope the steps I described above help you.

**Comment by disconnect821** [comment]
Giving it a shot.

**Comment by salty-ivy** [comment]
@disconnect821  Go ahead let me know if you need any help.

**Comment by MeghanaNalla** [comment]
I'm starting to work on it.

**Comment by lb-** [comment]
New PR up - https://github.com/wagtail/wagtail/pull/10961 @Stormheg requesting a review when you have some time thank you.

**Comment by buildwithaman** [comment]
Hello @Stormheg 
I am a beginner in this world of open source contribution
I would like to work on this issue . Please assign me this issue

**Comment by zerolab** [comment]
@buildwithaman thank you for your interest. We do not assign issues to anyone outside of the core team. Please to read https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html as it outlines everything one needs to know for first time contributions.

Finally, there is a PR for this - #10961 and it is mentioned in the update just before yours.

**Comment by dorcas-tech** [comment]
hi. Started working on this, and I wanna know, do I make changes to the file on https://github.com/wagtail/wagtail/blob/main/wagtail/management/commands/purge_revisions.py#L78-L79.

**Comment by laymonage** [comment]
@dorcas-tech there is already a PR for this: #10961.
