### ISSUE TITLE
SnippetViewSetGroup has no attribute 'icon'

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#10685]
Change icon to menu_icon in code example.

### Pertinent section of the Wagtail docs
[section link](https://docs.wagtail.org/en/stable/topics/snippets.html#customising-the-menu-item)
### Details

SnippetViewSetGroup has no attribute 'icon', it should be 'menu_icon'.

**Comment by laymonage** [comment]
Thanks, this was fixed in #10599, though the stable docs haven't been rebuilt as no new 5.0.x release has been created.

Same section in `latest`:
https://docs.wagtail.org/en/latest/topics/snippets/customising.html#menu-item
