### ISSUE TITLE
Building a slug without hyphens (last Wagtail version)

### ISSUE THREAD

**Issue by francuz08011990** [wagtail/wagtail#10680]
### Issue Summary
I used last Wagtail version.
The documentation says that we should use '**TitleFieldPanel**' for field 'title' instead '**FieldPanel**'
Here is link: https://docs.wagtail.org/en/stable/releases/5.0.2.html#use-of-titlefieldpanel-for-the-page-title-field

```
content_panels = [
        MultiFieldPanel(
            [
                TitleFieldPanel('title'),
                FieldPanel('description'),
                .....
             ]
]   
```
                
This is create 'slug', but without hyphens (and it throws errors )
![image](https://github.com/wagtail/wagtail/assets/25440614/ecb5674c-03bb-4aff-9683-f16134a209a0)

In Wagtail version 4.2.4 all works fine

### Technical details

-   Python version: 3.8.10
-   Django version: 3.2.12
-   Wagtail version: 5.0.2
-   Browser version: Chrome 114

**Comment by gasman** [comment]
Hi @francuz08011990 - thanks for the report. Have you confirmed that this bug can be reproduced as described on a newly-created Wagtail project?

**Comment by lb-** [comment]
@francuz08011990 do you have anything overridden in the other panels where the slug is declared (`content_panels`)?

**Comment by francuz08011990** [comment]
> 
No, i don't have.
My structure is:

```
class PromotePageModel(Page, SEOModel, OGModel):
    class Meta:
        abstract = True

    promote_panels = [
        FieldPanel('show_in_menus'),
        FieldPanel('slug'),
        MultiFieldPanel(
            [
                FieldPanel('seo_title'),
                FieldPanel('search_description'),
                FieldPanel('seo_keywords'),
                FieldPanel('seo_noindex'),
            ],
            heading=_('SEO'),
        ),
        MultiFieldPanel(
            [
                FieldPanel('og_title'),
                FieldPanel('og_description'),
                FieldPanel('og_image'),
                FieldPanel('og_image_width'),
                FieldPanel('og_image_height'),
                FieldPanel('og_site_name'),
                FieldPanel('og_url'),
            ],
            heading=_('Open Graph'),
        ),
    ]
```
```
class PostModel(PromotePageModel):
        class Meta:
        abstract = True
        
    content_panels = [
        MultiFieldPanel(
            [
                TitleFieldPanel('title'),
                FieldPanel('headline'),
                FieldPanel('is_anchored'),
                FieldPanel('preview'),
                FieldPanel('preview_title'),
                FieldPanel('preview_alt'),
                FieldPanel('cover'),
                FieldPanel('cover_title'),
                FieldPanel('cover_alt'),
                FieldPanel('description'),
            ],
            heading=_('Common info'),
        ),
        MultiFieldPanel(
            [
                FieldPanel('content'),
            ],
            heading=_('Content'),
        ),
    ]
```
```
class ArticlePage(PostModel):
    content_panels = [
        MultiFieldPanel(
            [
                PageChooserPanel('category'),
                MultiFieldPanel(
                    [
                        LocalizedSelectPanel('tag', widget_class=forms.CheckboxSelectMultiple)
                    ],
                    heading=_('Tags')
                ),
            MultiFieldPanel(
                    [
                        LocalizedSelectPanel('author', widget_class=forms.CheckboxSelectMultiple)
                    ],
                    heading=_('Authors')
                ),
            ],
            heading=_('Related info'),
        ),
        MultiFieldPanel(
            [
                FieldPanel('is_nav_active'),
            ],
            heading=_('Nav bar')
        ),
    ] + PostModel.content_panels
```

**Comment by francuz08011990** [comment]
> Hi @francuz08011990 - thanks for the report. Have you confirmed that this bug can be reproduced as described on a newly-created Wagtail project?

No, this is a problem in an existing project

**Comment by francuz08011990** [comment]
> @francuz08011990 do you have anything overridden in the other panels where the slug is declared (`content_panels`)?



No, i don't have.
My structure is:

class PromotePageModel(Page, SEOModel, OGModel):
    class Meta:
        abstract = True

    promote_panels = [
        FieldPanel('show_in_menus'),
        FieldPanel('slug'),
        MultiFieldPanel(
            [
                FieldPanel('seo_title'),
                FieldPanel('search_description'),
                FieldPanel('seo_keywords'),
                FieldPanel('seo_noindex'),
            ],
            heading=_('SEO'),
        ),
        MultiFieldPanel(
            [
                FieldPanel('og_title'),
                FieldPanel('og_description'),
                FieldPanel('og_image'),
                FieldPanel('og_image_width'),
                FieldPanel('og_image_height'),
                FieldPanel('og_site_name'),
                FieldPanel('og_url'),
            ],
            heading=_('Open Graph'),
        ),
    ]

class PostModel(PromotePageModel):
        class Meta:
        abstract = True
        
    content_panels = [
        MultiFieldPanel(
            [
                TitleFieldPanel('title'),
                FieldPanel('headline'),
                FieldPanel('is_anchored'),
                FieldPanel('preview'),
                FieldPanel('preview_title'),
                FieldPanel('preview_alt'),
                FieldPanel('cover'),
                FieldPanel('cover_title'),
                FieldPanel('cover_alt'),
                FieldPanel('description'),
            ],
            heading=_('Common info'),
        ),
        MultiFieldPanel(
            [
                FieldPanel('content'),
            ],
            heading=_('Content'),
        ),
    ]

class ArticlePage(PostModel):
    content_panels = [
        MultiFieldPanel(
            [
                PageChooserPanel('category'),
                MultiFieldPanel(
                    [
                        LocalizedSelectPanel('tag', widget_class=forms.CheckboxSelectMultiple)
                    ],
                    heading=_('Tags')
                ),
            MultiFieldPanel(
                    [
                        LocalizedSelectPanel('author', widget_class=forms.CheckboxSelectMultiple)
                    ],
                    heading=_('Authors')
                ),
            ],
            heading=_('Related info'),
        ),
        MultiFieldPanel(
            [
                FieldPanel('is_nav_active'),
            ],
            heading=_('Nav bar')
        ),
    ] + PostModel.content_panels

**Comment by lb-** [comment]
@francuz08011990 - sorry I meant promote panels.

You will need to set the slug widget on your slug field. 

https://docs.wagtail.org/en/stable/releases/5.0.html#slug-field-auto-cleaning-now-relies-on-data-attributes

```
from wagtail.admin.widgets.slug import SlugInput
# ... other imports

class MyPage(Page):
    promote_panels = [
        FieldPanel("slug", widget=SlugInput),
        # ... other panels
    ]
```

**Comment by francuz08011990** [comment]
> @francuz08011990 - sorry I meant promote panels.
> 
> You will need to set the slug widget on your slug field.
> 
> https://docs.wagtail.org/en/stable/releases/5.0.html#slug-field-auto-cleaning-now-relies-on-data-attributes
> 
> ```
> from wagtail.admin.widgets.slug import SlugInput
> # ... other imports
> 
> class MyPage(Page):
>     promote_panels = [
>         FieldPanel("slug", widget=SlugInput),
>         # ... other panels
>     ]
> ```

Thanks a lot !
Was inattentive and missed important information in release 5.0 :)

**Comment by lb-** [comment]
No problems, I know these changes are hard sometimes but this means that the previous 'magic' behaviour is now opt in. And can be used on other slug fields in the admin, even when the field is not named slug.
