### ISSUE TITLE
Allow variable filter specifications in the image template tag

### ISSUE THREAD

**Issue by PetrDlouhy** [wagtail/wagtail#10712]
## Is your feature request related to a problem? Please describe

The current implementation of the Wagtail `{% image %}` tag requires filter specifications to be hard-coded strings (like "width-800" or "fill-300x300"). This makes it difficult to dynamically adjust image sizes based on variables in the template context. For example, the following is not currently possible:

```django
{% for res, spec in specs.items %}
    {% image image spec format-webp as block_image_res %}
{% endfor %}
```

In this case, `spec` is a string variable in the context that contains a filter specification like "fill-300x300". However, the `{% image %}` tag doesn't interpret `spec` as a filter specification and throws an error.

## Describe the solution you'd like

I would like to see the `{% image %}` tag be able to interpret string variables in the template context as filter specifications. This would make the tag more flexible and powerful, allowing for more dynamic image sizes without having to resort to custom template tags or other workarounds.

## Describe alternatives you've considered

A possible workaround is to create a custom template tag that behaves similarly to the `{% image %}` tag but accepts variable filter specifications:

```django
from django import template
from wagtail.images.templatetags.wagtailimages_tags import image

register = template.Library()


@register.tag(name="image_var")
def image_var(parser, token):
    return image(parser, token)
```

However, this solution can have performance implications and also adds an extra layer of complexity to the code. It would be simpler and more efficient if this functionality were built into the `{% image %}` tag directly.

## Additional context

This feature would be particularly useful for responsive design, where the optimal image size can depend on the viewport size or other dynamic factors.

**Comment by gasman** [comment]
Thanks for the suggestion @PetrDlouhy! We previously considered and rejected this at #4895. In short, it's not possible to add this to the `{% image %}` tag without breaking backwards compatibility - but on the other hand, it's fairly easy to roll your own solution (which might be a custom template tag, or something else) based a the `get_rendition` function.
