### ISSUE TITLE
{% page_header_buttons %} crashes when used due to typo in the first line

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#10730]
### Issue Summary

The `{% page_header_buttons %}` template tag from `wagtailadmin_tags` crashes when used.

### Steps to Reproduce

1. Put `{% page_header_buttons None None %}` anywhere in a template that includes `{% load wagtailadmin_tags %}`. Any other arguments work, too, as the crash happens before they get used.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

The problem is that the first line of code is 
```
    next_url = context.request.path
```
It should instead be:
```
    next_url = context["request"].path
```

@gasman fixed a similar issue with the `{% page_listing_buttons %}` template tag last month, as part of #10592.

I submitted #10731 as a fix.

**Comment by lb-** [comment]
<img width="1458" alt="Screenshot 2023-08-01 at 7 37 07 am" src="https://github.com/wagtail/wagtail/assets/1396140/166c8079-5109-4bb5-96ca-c0f9639b2ce9">

Can confirm this issue exists and also our usage of `context.request.*` appears to be the issue.
