### ISSUE TITLE
Document how to disable audit logging from appearing in development console

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#10769]
### Pertinent section of the Wagtail docs

The audit logging section describes a mechanism for logging activities related to pages, such as creating pages and redirects. However, it doesn't mention this feature in the context of development. In particular, since Wagail 5.1 the audit log messages are appearing in the development console.

<img width="923" alt="Screenshot 2023-08-08 at 18 36 04" src="https://github.com/wagtail/wagtail/assets/17307/a6c05c68-8ac8-4ee5-a862-f10d46d1af2d">

https://docs.wagtail.org/en/stable/extending/audit_log.html

### Details

Since upgrading to Wagtail 5.1, it seems that the Wagtail audit log actions are being printed to the development console. This is very noisy and is interfering with other important log messages and progress indicators.

Unpublished: "Page One" pk=282

Page deleted: "Page One" id=282

Creating redirects for page: 'Windward Oahu Worship Group' id=3471 1/1 redirects were created successfully.

Page moved: "West Side Worship Group" id=3432 path=/welcome/community/meetings/intermountain-yearly-meeting/mountain-view-friends-meeting/west-side-worship-group/

How can I disable the Wagtail 5.1 audit log console output?

I tried searching the documentation for a configuration flag where I could tell Wagtail to disable console logging.

**Comment by brylie** [comment]
I also raised this question on StackOverflow, since it seems most probably to be a support/documentation issue: https://stackoverflow.com/questions/76843354/disable-wagtail-5-1-audit-log-from-appearing-in-console-output

**Comment by gasman** [comment]
I'm not seeing this on my development instance - have you been able to replicate this behaviour on a fresh Wagtail installation?

**Comment by brylie** [comment]
Here is my Django logging configuration, in case that shines any light on the issue:

```py
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "debug.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
        },
    },
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "DEBUG",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "WARNING"),
        },
    },
}
```
