### ISSUE TITLE
When inserting a new InlinePanel, focus goes to the wrong place.

### ISSUE THREAD

**Issue by nimasmi** [wagtail/wagtail#10764]
### Issue Summary

When inserting a new InlinePanel, focus goes to the wrong place.

### Steps to Reproduce

1. Navigate to the edit view for a page with an inline panel.
2. Use keyboard navigation to focus the "add foos" button.
3. Hit enter.
4. Observe that:
    1. focus remains on the "add foos" button
    2. this is now at the end of the newly inserted InlinePanel / formset form element
    3. you must navigate back with shift+tab to get to the start of the newly inserted form

https://github.com/wagtail/wagtail/assets/1473980/b2a516d5-9316-48ad-be6f-471927967d29

This adds confusion and extra work for users relying on keyboard navigation or screen readers.

I would instead expect focus to move to the first field in the newly-inserted form.

### Technical details

-   Wagtail version: 5.0.2

**Comment by faishal882** [comment]
hey @nimasmi  i have looked into your problem and i think the default behavior is it does not focus on any inline field,
[Screencast from 24-08-23 10:21:16 PM IST.webm](https://github.com/wagtail/wagtail/assets/68147015/526997fd-0c30-4518-88d0-002f90db272e)

**Comment by faishal882** [comment]
btw it would have been better if focus goes on first inline field

**Comment by faishal882** [comment]
hey @nimasmi  i have gone through documentation in field panel you can pass widget arguments like django as wagtail documentation says ``FieldPanel('caption_test', widget=forms.TextInput(attrs={'autofocus': 'autofocus'}))`` in your first inlineField it should work

**Comment by nimasmi** [comment]
Thanks for the suggestion @faishal882. It did not work for me, although the inline field was created with the `autofocus=autofocus` attribute. I don't think this is the right solution, though, because the [MDN docs for autofocus](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus) this say

- it should receive focus when the `dialog` that it is part of is displayed, but we don't have that
- it should receive focus on page load also, but we don't want that

I believe a JS change is the right fix here.

**Comment by faishal882** [comment]
hey @nimasmi  i tried to do achieve same autofocus in inline model in django,  and the same problem happened i think it is the issue which can be raised in django

**Comment by lb-** [comment]
I agree a JS change is needed and this will be tricky to add a workaround for as there's no JS DOM events for when InlinePanel items are added - https://github.com/wagtail/wagtail/issues/9105 . 

This won't be a Django problem though as this is a Wagtail implementation. 

It's a bit nuanced also, as the movement of focus to the input won't always be possible as a different target may make sense. 

A possibility is to focus on maybe the container or title, adding tabIndex -1, then when focus moves away it will remove the tabIndex. 

There are plans to redo parts of the InlinePanel with Stimulus but that may not happen for the next release. 

I'm happy to help review any PRs that someone wants to submit for this.

**Comment by faishal882** [comment]
[Screencast from 30-08-23 03:31:35 AM IST.webm](https://github.com/wagtail/wagtail/assets/68147015/15d3d7b6-0f8e-48ff-a62d-982b0fb293dc)

hey @lb-  i think on autoscroll to view newly created form is better  then not having it,  even though it didn't completely solved the issue on adding tabindex -1 on newly created inlinePanel the autofocus attribute added via widget still not works. If you permit i can create a PR or if any other solutions in mind please suggest

**Comment by lb-** [comment]
Another thing to call out is that this will make subsequent 'add item' a bit more annoying. You will not be able to click this multiple times to add a bunch of new items as the scroll will shift your focus away.

However, this is aligned with the similar functionality for adding blocks, where we take you to the field / container that has just been added. So it's probably best to be consistent.

**Comment by nimasmi** [comment]
Thanks for addressing this @faishal882!
