### ISSUE TITLE
FieldPanel with read_only=True does not work for a choice field whose labels are translatable

### ISSUE THREAD

**Issue by fle** [wagtail/wagtail#10772]
### Issue Summary

`FieldPanel('myfield', read_only=True)` does not work for a choice field whose labels are translatable (using `gettext_lazy`)

### Steps to Reproduce

1. Create a model containing a CharField using translatable choices:

```python

AUDIENCE_CHOICES = (
    ("public", _("Public")),
    ("private", _("Private")),
)

class Event(model.Model):
    
    audience = models.CharField(
        max_length=255,
        choices=AUDIENCE_CHOICES,
        editable=False
    )
        
    edit_handler = MultiFieldPanel(
        [
            FieldPanel("audience", read_only=True)
        ]
    )
```
2. Make the appropriate migration and migrate your instance
3. Open the edit form of your Event model in the admin of Wagtail

Here is the end of the traceback you will obtain:

```console
  File "/home/florent/dev/wagtail-raw/wagtail/wagtail/admin/panels/field_panel.py", line 120, in format_value_for_display
    return ", ".join(display_values)
TypeError: sequence item 0: expected str instance, __proxy__ found
```

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10.12
-   Django version: 4.0.10 and 4.2.3
-   Wagtail version: 5.1

Here is a simple diff that makes the unit test `wagtail.admin.tests.test_edit_handlers.TestFieldPanel.test_format_value_for_display_with_choicefield` fail with the same error:

```diff
diff --git a/wagtail/test/testapp/models.py b/wagtail/test/testapp/models.py
index 63c4840..debf5e8 100644
--- a/wagtail/test/testapp/models.py
+++ b/wagtail/test/testapp/models.py
@@ -81,8 +81,8 @@ from wagtail.snippets.models import register_snippet
 from .forms import FormClassAdditionalFieldPageForm, ValidatedPageForm
 
 EVENT_AUDIENCE_CHOICES = (
-    ("public", "Public"),
-    ("private", "Private"),
+    ("public", _("Public")),
+    ("private", _("Private")),
 )
```

**Comment by laymonage** [comment]
Thanks! I can confirm this issue.
