### ISSUE TITLE
Move the UI Styleguide to the Help menu

### ISSUE THREAD

**Issue by Ash-Crow** [wagtail/wagtail#10783]
### Is your proposal related to a problem?

When the [Styleguide](https://docs.wagtail.org/en/stable/contributing/styleguide.html) is activated, it appears in the Settings menu, which is not ideal as this is not a setting.

### Describe the solution you'd like
As the title says, move this entry to the Help menu, which is more logical for it.

### Additional context
I'm not sure if this is much of a feature but it seemed the best place to suggest this change.

**Comment by lb-** [comment]
Not sure about this, the help feature is meant to be user facing for most users. Settings menu is normally going to be restricted somewhat. 

The styleguide is meant for developers mainly, it's even been called I to question about whether it should exist at all. However, it's useful for validation and package maintainers.

I would recommend we keep it as is.

**Comment by gasman** [comment]
I agree with keeping this as is - the use cases for enabling the styleguide on any Wagtail installation are very narrow, and giving it a location that communicates "this is for administrative users only" is more important than making it discoverable.
