### ISSUE TITLE
404 Not found on Image upload and edit after updating to latest version

### ISSUE THREAD

**Issue by ihaiderj** [wagtail/wagtail#10824]
### Issue Summary

I am gettting 404 : Not Found page after updating to latest wagtail version. It come when I try to change or upload an image from Admin.

What it is not finding.

plz check the image on the link:
https://drive.google.com/file/d/1oSoz4zYSNqJIlrTlcFeuH_MNnvRF9Gkk/view

### Technical details

Django>=3.2,<3.3
wagtail>=2.14,<2.15
Browser: Chrome

**Comment by Scotchester** [comment]
It's trying to load the homepage editing view. Not sure why it would be failing if you were just on it trying to change an image. Could you provide specific steps for how to reproduce the issue?

**Comment by ihaiderj** [comment]
I updated my wagtail project to latest version, and made all the changes to run the project successfully. It already had some data , I am not updating few images in the project and when I click on chnage or upload new image it brings this Not Found error page but in the background I could see the images I wast tring to upload have uploaded

**Comment by gasman** [comment]
Based on the styling, this error is coming from django-debug-toolbar, not Wagtail. If you close the debug panel using the button in the top right, you should be able to use Wagtail as normal.

**Comment by ihaiderj** [comment]
> Based on the styling, this error is coming from django-debug-toolbar, not Wagtail. If you close the debug panel using the button in the top right, you should be able to use Wagtail as normal.

ok let me try

**Comment by ihaiderj** [comment]
> > Based on the styling, this error is coming from django-debug-toolbar, not Wagtail. If you close the debug panel using the button in the top right, you should be able to use Wagtail as normal.
> 
> ok let me try

Yes, you are right, it worked. Thanks a lot for your help:)
