### ISSUE TITLE
Root page title does not display in breadcrumb navigation on multi-site install

### ISSUE THREAD

**Issue by UDAR-TomH** [wagtail/wagtail#10829]
I have a Wagtail install that is running multiple sites. I have different groups for each site, setting up editor and moderator permissions. For each site, I have "page permissions" to add/edit/publish per particular group, granting it to the homepage. When I log in as a user of that group, and navigate to the homepage of the site, I can edit the page, but the title of the page does not display. 
![image](https://github.com/wagtail/wagtail/assets/111092434/5b755691-b634-432a-b31a-884ebc4a82bd)

### Steps to Reproduce

1. Start with a fresh install of Wagtail.
2. Create multiple homepages.
3. Create multiple sites under Settings > Sites, and point them to the respective pages.
4. Create a different group for each site under Settings > Groups, adding the homepage under the "Page permissions" section. Grant Add/Edit/Publish to the group.
5. Create a user, add it to one of the groups.
6. Log in as the user, and navigate to Pages > homepage.
7. Notice at the top of the screen, the page title will not be displayed. You should be able to click the three dot menu in order to edit the page, and when you are in the edit interface, the title will also not be displayed there. Pages nested under the homepage will display the title properly.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

What should happen: Users of a group with the proper permissions to edit a page should be able to see the page title. 
Additional notes: Admin users, or users of a group that has permissions to edit the "root" page can see the page title just fine. 

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11
-   Django version: 4.2
-   Wagtail version: 5.1.1
-   Browser version: Firefox 117.b9 and Chrome 116.0.5845.96

**Comment by laymonage** [comment]
Thank you, I believe this has been fixed in #11541.
