### ISSUE TITLE
Password strip policy in Wagtail

### ISSUE THREAD

**Issue by DimonLavron** [wagtail/wagtail#10839]
### Issue Summary

Recently I was trying to check some of the password requirements inside Wagtail for my project and found an interesting issue. I observed that all Wagtail forms overriding password fields strip leading and trailing whitespaces in passwords ([LoginForm](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/forms/auth.py#L11), [UserForm](https://github.com/wagtail/wagtail/blob/main/wagtail/users/forms.py#L87)), with the exception of one specific case. The **"Account"** page in the **"Password"** section uses [PasswordChangeForm](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/forms/auth.py#L49), which doesn't override password field. Instead, it uses the Django [PasswordChangeForm](https://github.com/django/django/blob/main/django/contrib/auth/forms.py#L422), wherein the password field is implemented with the `strip=False` argument for the `CharField`, so it doesn't strip password. Consequently, passwords entered on the **"Account"** page with leading or trailing whitespaces are saved as it is, and the login form subsequently removes these whitespaces during the login attempt, making it impossible to log in again.

In fact, all Django forms containing password fields have `strip=False` argument for `CharField`, so Django preserves leading and trailing whitespaces in passwords ([AuthenticationForm](https://github.com/django/django/blob/main/django/contrib/auth/forms.py#L206), [SetPasswordForm](https://github.com/django/django/blob/main/django/contrib/auth/forms.py#L387), etc.). To maintain consistency with Django's approach, it would be beneficial for Wagtail to adopt the same behavior, thereby retaining leading and trailing whitespaces in passwords.

### Steps to Reproduce

1. Create a fresh new admin user and log in to admin panel.
2. Proceed to the **"Account"** page and modify the password, incorporating leading or trailing whitespaces. For instance, use the password " lorem ".
3. Log out from admin panel and try to log in with the new password. You will discover that you can't log in again.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Expected Result: Successful login after password change.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.8.2
-   Django version: 4.2.4
-   Wagtail version: 5.1.1
-   Browser version: Google Chrome 116.0.5845.96

**Comment by allcaps** [comment]
Wagtail is a CMS on top of Django. I'd say we better follow Django's practices and add `strip=False` to password fields. Make Wagtail behave like Django does.

**Comment by lb-** [comment]
Thanks @DimonLavron - consensus is that Wagtail should align with consistency here and also align with the way Django treats these fields. 

I'm not sure on priorities of the core team, would you be willing to put together a PR with some tests for this? I'd be more than happy to help review it.

**Comment by DimonLavron** [comment]
@lb- Sure, I'll do my best to make a PR for a fix to this issue.

**Comment by NXPY123** [comment]
Adding `strip=False` to the password's CharField would resolve this, right?
Like this:
```python
class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=254, widget=forms.TextInput())

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": gettext_lazy("Enter password"),
            }
        ),
        strip=False,
    )
```

**Comment by lb-** [comment]
I think that looks good.
