### ISSUE TITLE
The image is not visible on the website if we add it inside TypedTableBlock.

### ISSUE THREAD

**Issue by krishav43** [wagtail/wagtail#10845]
### Issue Summary

We are facing the issue when we have added the image inside the TypedTableBlock. The image is not visible in the preview, and it is also not visible on the frontend.

Below is the HTML tag stored in the Wagtail database. There are no image tags, and no image URL is present inside the wagtail.
embed alt="Test" embedtype="image" format="center" id="11***"

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Create a StreamField with TypedTableBlock as one of the option.
3. In TypedTableBlock use RichTextBlock as one of the option.
4. Go to wagtail, and add the image inside the TypedTableBlock section.
5. Check in the preview you will not able to see the image inside the table. Same for the frontend side also.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes) 

### Technical details

-   Python version: 3.10.10.
-   Django version: 3.2.19
-   Wagtail version: 4.2.4
-   Browser version: Chrome 116

**Comment by gasman** [comment]
Hi @krishav43 - thanks for the report. However, I'm unable to replicate this as described. Starting from a fresh Wagtail 4.2.4 instance, I added `"wagtail.contrib.typed_table_block",` to INSTALLED_APPS, edited home/models.py to:

```python
from django.db import models

from wagtail.models import Page
from wagtail.fields import StreamField
from wagtail.admin.panels import FieldPanel
from wagtail import blocks
from wagtail.contrib.typed_table_block.blocks import TypedTableBlock


class HomePage(Page):
    body = StreamField([
        ('table', TypedTableBlock([
            ('text', blocks.RichTextBlock()),
        ])),
    ], blank=True, null=True, use_json_field=True)

    content_panels = Page.content_panels + [
        FieldPanel('body'),
    ]
```

and home/templates/home/home_page.html to:

```html+django
{% extends "base.html" %}
{% load static wagtailcore_tags %}

{% block body_class %}template-homepage{% endblock %}

{% block extra_css %}{% endblock extra_css %}

{% block content %}

{% include_block page.body %}

{% endblock content %}
```

I then created a table containing an image:
![Screenshot 2023-08-31 at 09 50 10](https://github.com/wagtail/wagtail/assets/85097/7a4e5698-3144-459b-b1ab-ef87aa7c6206)

and this displayed correctly in preview and on the live page:
![Screenshot 2023-08-31 at 09 51 30](https://github.com/wagtail/wagtail/assets/85097/b943f2fb-50cc-4293-93bf-0a1ee23cb48b)

If you can provide more detailed steps that replicate the issue, I'll be happy to reopen and investigate further. Note that the `<embed>` tag in the database content is expected - see https://docs.wagtail.org/en/stable/extending/rich_text_internals.html#data-format.
