### ISSUE TITLE
Template move missing from 5.1 release notes

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail#10874]
### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/stable/releases/5.1.html#other-features

### Details

The template `wagtailadmin/tables/attrs.html` was moved to `wagtailadmin/shared/attrs.html`

The result of this was to break all the custom cell types in our generic chooser views. A note on this in the release notes could have avoided the lengthy troubleshooting.

**Comment by lb-** [comment]
This shared template was not documented I believe. We do our best to try to consider undocumented use cases but as you can imagine, that would mean documentation for a lot of things in release notes. 

I'll try to get a PR up to backport this upgrade consideration though.
