### ISSUE TITLE
image purge command

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#10872]
### Issue Summary
Image you have this (see page. in you code for some image

 ```
           <div class="offset-lg-1 hero__img">
                {% if page.header_image %}
                    {% image page.header_image fill-898x844-c100 format-avif preserve-svg as avif %}
                    {% image page.header_image fill-898x844-c100 format-webp preserve-svg as webp %}
                    {% image page.header_image fill-898x844-c100 format-jpeg preserve-svg as jpg %}
                    {% include "components/_responsive_img.html" with avif=avif webp=webp jpg=jpg class="fill-img" %}
                {% endif %}
            </div>
```
you install on new server and empty your files and use the command, want to use avif files :)
./manage.py wagtail_update_image_renditions

so you trow away your render images to let the new ones render.
The command will render images with slight diffrent filename then that now stored in the db.
```
<div class="offset-lg-1 hero__img">              
<picture>
    <source srcset="/media/images/homeheader.2e16d.2e16d0ba.fill-898x844-c100.format-avif.avif" type="image/avif">
    <source srcset="/media/images/homeheader.2e16d.2e16d0ba.fill-898x844-c100.format-webp.webp" type="image/webp">
    <img class="fill-img" src="/media/images/homeheader.2e16d0.2e16d0ba.fill-898x844-c100.format-jpeg.jpg" alt="homeheader.2e16d0ba.fill-898x846-c100.format-webp">
</picture></div>
```

notice that each srcset get "format-avif" in the file name. While the rendered result is this is not correct.
homeheader.2e16d0ba.fill-898.2e16d0ba.fill-898x844-c100.avif

A work around is to remove the rendered image table from the database and do this manualy.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11
-   Wagtail version: 5.1.1

**Comment by gasman** [comment]
Sorry, it's not clear what you're reporting here - please open a new issue giving exact steps for reproducing the problem, starting from a fresh Wagtail project.
