### ISSUE TITLE
Allow admin backend login URL to be customised

### ISSUE THREAD

**Issue by SebCorbin** [wagtail/wagtail#10882]
### Issue Summary
By integrating `django-allauth`, I wish to customize `WAGTAIL_FRONTEND_LOGIN_URL` to `/accounts/login/` bu the admin access is not redirected to this url.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Install and enable `django-allauth` (`allauth` and `allauth.account`)
3. Add `path("accounts/", include("allauth.urls")),` to the project urls
4. Set `WAGTAIL_FRONTEND_LOGIN_URL` to `/accounts/login/`
5. Access `/admin/`

You are redirected to `http://127.0.0.1:8000/admin/login/?next=/admin/` instead of `http://127.0.0.1:8000/accounts/login/?next=/admin/`

### Technical details

-   Python version: 3.10.12
-   Django version: 4.2.4
-   Wagtail version: 5.1.1

**Comment by gasman** [comment]
This is expected - WAGTAIL_FRONTEND_LOGIN_URL is for front-end pages that require authentication (i.e. set as "Accessible to logged-in users" through the [Private Pages](https://docs.wagtail.org/en/stable/advanced_topics/privacy.html) feature), not the admin backend.

The backend login view can be overridden by adding a URL route for `admin/login/` somewhere above the `include(wagtailadmin_urls)` line in your project's URLconf. However, I think it would be worth adding a dedicated config setting to allow customising this in a more standardised way.

**Comment by faizan2700** [comment]
I want to work on this. please.

**Comment by SebCorbin** [comment]
Feel free if you want, in the meantime @gasman solved my case by overriding `admin/login/`

**Comment by Athrav04** [comment]
is it still open ?

**Comment by varunsaral** [comment]
Hey @gasman, do we have to override the get_redirect_url() if our custom variable is set, ex : WAGTAIL_BACKEDN_LOGIN_URL = '/some/path'

```
class LoginView(auth_views.LoginView):
    template_name = "wagtailadmin/login.html"
    
    def get_redirect_url():
        if WAGTAIL_BACKEDN_LOGIN_URL:
            return WAGTAIL_BACKEDN_LOGIN_URL
       else:
            return '/admin/login'
```

**Comment by lb-** [comment]
@varunsaral  I think you are on the right track but we would probably want to put this redirection in the get method though.

Here's a rough draft (have not tested but should get you started).

```py
    def get(self, *args, **kwargs):
        # If user is already logged in, redirect them to the dashboard
        if self.request.user.is_authenticated and self.request.user.has_perm(
            "wagtailadmin.access_admin"
        ):
            return redirect(self.get_success_url())
        
        login_url = getattr(settings, "WAGTAILADMIN_USER_LOGIN_URL", None)

        if login_url:
            # something like this
            return HttpResponseRedirect(login_url)

        return super().get(*args, **kwargs)
```

**Comment by gasman** [comment]
The way I imagined it, the update would be applied to [the `reject_request` method in `wagtail.admin.auth`](https://github.com/wagtail/wagtail/blob/db00f05a474c87fe00e1d60e704dd35f9ac3b90f/wagtail/admin/auth.py#L123-L125) - so that when a request to the admin comes in from a non-logged-in user, they'd be redirected to whatever the developer specifies for `WAGTAILADMIN_LOGIN_URL` in preference to the hard-coded redirect to the `wagtailadmin_login` view.

**Comment by gasman** [comment]
To expand on the above - the goal here (if I've understood correctly...) is to be able to replace the standard Wagtail username/password login screen with some other login workflow, such as a single-sign-on service ("Sign in with Google" or similar). The developer would set that up at some URL outside of `/admin/`, so that when a non-logged-in user visits a page anywhere under `/admin/`, then rather than being sent to `/admin/login/` as normal, they'd be sent to that new login workflow. This means that the best place to put this new code is inside the "is this user logged in?" check that happens on every admin page, rather than on the login view itself.

**Comment by disconnect821** [comment]
Would like to work on this one, will soon open a PR

**Comment by disconnect821** [comment]
> @lb- @gasman thanks for the explanation, i understood what we have to do, but since lots of people want to work on this, it's probably best to leave them for first timers. I will probably look into management command which is used to build the indexes for full text search, don't know if the issue is still open?

@varunsaral thanks for the consideration, since it's going to be my first contribution in wagtail so, I'll try to take this one up if I may.

**Comment by gasman** [comment]
> I will probably look into management command which is used to build the indexes for full text search, don't know if the issue is still open?

@varunsaral Yep, #10933 is still open - it may not be a particularly easy one to pick up as it'll require studying the reindexer classes to understand how they work, then figuring out how to rework them to support the new feature - but you're very welcome to give it a go.

**Comment by varunsaral** [comment]
@gasman I'll definitely pick it up and do, i read around rebuilder base class and how different backends(postgres, elasticsearch,etc) are using it. It is challenging and hence fun 😎 thanks for the opportunity.

**Comment by NXPY123** [comment]
@disconnect821 are you still working on this?

**Comment by Pratikdate** [comment]
I have good understanding about Django, assign me I will work on it

**Comment by lb-** [comment]
@Pratikdate we don't assign issues outside of the core team, if you've got a PR ready just raise it. 

Have a read of this section. https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html#how-can-i-be-assigned-an-issue-to-contribute-to
