### ISSUE TITLE
I can make 2 blocks even if I set the limit for this block to max=1

### ISSUE THREAD

**Issue by MrKalister** [wagtail/wagtail#10888]
### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Create new app with 'python manage.py startapp blog'
3. Create new block:
class CompetenceBlock(StructBlock):
    """Block which contains info about Competence."""

    header = CharBlock(max_length=200)
    body_text = RichTextBlock(features=[])
4. Create new model:
class CompetenceNewPage(Page):
    """Page with the competence."""

    # Database fields
    competencies = StreamField(
        [
            ('competencies', CompetenceBlock(),
        ], use_json_field=True, max_num=1)
5. python manage.py makemigrations && python manage.py migrate && python manage.py runserver
6. Expectation: You can't add second block. Reality: You can't add second block, because button "+" doesn't available, but you can do it with button "duplicate", because it's still available. The good news is that you won't be able to save it anyway and will get a corresponding error.

### Technical details

-   Python version: 3.10.12
-   Django version: 4.1.3
-   Wagtail version: 5.1.1
-   Browser version: Firefox 117.

**Comment by gasman** [comment]
Thanks for the report! There's an existing issue covering this, at #9513.
