### ISSUE TITLE
Snippet Copy Function

### ISSUE THREAD

**Issue by dkirkham** [wagtail/wagtail#10921]
### Is your proposal related to a problem?

In some use cases, it may be useful to be able to **copy** a Snippet, so as to make small changes for separate inclusion in pages. If a snippet has only a small number fields this can be done manually, but if it is quite complicated, for instance because it includes a lengthy StreamField, it can become a chore and error-prone.

Note, this has a different intent to the new Revision capability in Snippets. The outcome of the copy is an independent snippet instance.

### Describe the solution you'd like

Add an optional copy function, accessed via a `Copy` button adjacent to each snippet (like `Edit` and `Delete`). Pressing the `Copy` button will bring up a new Snippet editor page preloaded with a copy of the source snippet. It can then be edited as required and saved in the same way as new snippet created via the Add Snippet button.

### Describe alternatives you've considered

I have implemented a `CopyableSnippetViewSet` class which incorporates an implementation of Snippet copy by subclassing existing Snippet classes and using hooks. See https://gist.github.com/dkirkham/7d2a63528e5754cdbd82ffabdd68584f

<img width="587" alt="image" src="https://github.com/wagtail/wagtail/assets/1977376/8679b31d-f192-4bb0-827c-fa5f2ecf0582">

The code is written such that it could be merged into the core Snippet codebase relatively easily. It would be preferable to have this maintained within the Snippet codebase since it uses one "hidden" API and depends on near copies of two templates.

### Additional context

The copy function should be made optional, and enabled in a similar way to the inspect function.

#9296 talks about a snippet copy function, but that is in the context of the Wagtail documentation which is prepared in Markdown, not Wagtail itself.

**Comment by smark-1** [comment]
I am working on this right now. 
When the user clicks the Copy button should the view look any different than the create view except that it is prepopulated?
If the user has the correct permissions to create a new snippet, does it make sense for the user to be able to copy as well or should this be a separate permission?
Is this new copy button enabled by default?

**Comment by gasman** [comment]
Thanks for picking this up @smark-1!
For consistency with how we handle copying pages, I think it should follow the same permission as the create view, and be available as standard to anyone with 'create' permission.
I think it's fine for the copy view to look the same as the creation view - I don't think we even particularly need to change the page title to 'Copy' - but happy to hear other views on this.

**Comment by dkirkham** [comment]
Hi @smark-1, thanks for progressing this. As the original reporter and author of the referenced workaround, I was waiting for the SnippetViewSet and ModelViewSet code to settle down a bit before rebasing and submitting a PR.

Personally, I'd like to see the copy version of the create view have "Copy" as the title (translated accordingly), or an easy way to make this possible if it isn't the default - I expect this would require some parametrisation of the page title. This would be preferable to having to make an almost exact copy of the template.

**Comment by dkirkham** [comment]
And I should have added, I'd also prefer that the copy function/button is optional, in the same way as the inspect function is optional.

**Comment by gasman** [comment]
> And I should have added, I'd also prefer that the copy function/button is optional, in the same way as the inspect function is optional.

Curious why you say this - are there any situations where a copy function _wouldn't_ add value?

**Comment by dkirkham** [comment]
Maybe the snippet/model represents a person or some other object where it is unlikely you'd want to copy it. For instance, one of my snippet models is a list of composers. I already have one Ludwig van Beethoven there, I don't want to make it too easy to have a second. (Yes, I have uniqueness constraints, but why lead the editor towards a failure scenario?)

**Comment by gasman** [comment]
Maybe not Beethoven, but surely there are enough composers in the Bach family to warrant a copy function... :-)

I suppose the real question is - will it serve users better if the copy function is available without the developer having to explicitly think "the copy feature would be useful here - let's enable it"? So maybe the best way forward is - have a flag to enable/disable it, but have it enabled by default.

**Comment by smark-1** [comment]
I added a setting `copy_view_enabled = True`. What changes should be made to the documentation?

**Comment by dkirkham** [comment]
Another functionality question around this issue, @gasman and @laymonage. In my [gist](https://gist.github.com/dkirkham/7d2a63528e5754cdbd82ffabdd68584f), I added two hooks, `before_copy_snippet` and `after_copy_snippet`, analogous with `before_edit_snippet` and `after_edit_snippet`. I couldn't think of an obvious use for these hooks, and didn't test them at the time.

On reflection, with the gist as coded, I expect only the `before_copy_snippet` hook from `CopyView` will get called, because when the new copied snippet is saved, `CreateView` will be used, which will call the `after_create_snippet` hook. Is this a reasonable behaviour, or do we want something different? Is there a practical reason to add the `after_copy_snippet` hook when we already have the `after_create_snippet` hook?
