### ISSUE TITLE
Pages in moderation shows as "Live + Draft" in the page listing view instead of "Live + In Moderation"

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#10925]
### Issue Summary

When a page is submitted for moderation, the "Status" column in the listing view shows it as "Live + Draft" instead of "Live + In Moderation". In other places e.g. dashboard, workflow usage this doesn't seem to be an issue.

### Steps to Reproduce

1. Spin up bakerydemo
2. Sign in as an admin user
3. Notice that on the dashboard, in the "Your most recent edits" section, the "Southern Cornbread" page is shown with the "Live + In Moderation" tag in the Status column
   <img width="793" alt="image" src="https://github.com/wagtail/wagtail/assets/6379424/cd43bc45-b118-444f-99c1-3201a6e40ada">
5. Go to the listing view for the "Recipes" page
6. Notice that the "Southern Cornbread" page is shown with the "Live + Draft" tag in the Status column instead of "Live + In Moderation"
   <img width="874" alt="image" src="https://github.com/wagtail/wagtail/assets/6379424/765567f3-c4e6-4716-a375-f902e96bb06d">

I haven't confirmed it but it's very likely this was a regression in #9817, specifically 301c6d9040642deaa8528d5bdbf3d02b81bb345a.

The `ForeignKey` to `Page` in `WorkflowState` was replaced with a `GenericForeignKey` + `GenericRelation` to add workflows support for snippets. Django [did not support](https://code.djangoproject.com/ticket/33651) `prefetch_related` with a custom queryset (via `Prefetch`) object, and instead of failing, the prefetch just silently results in an empty list. As a result, the usage of the prefetched `WorkflowState`s in the `workflow_in_progress` property in the following code: https://github.com/wagtail/wagtail/blob/da636f6b613d46d01c5ef6177f5f84c665363f3e/wagtail/models/__init__.py#L990-L1006
makes the logic assume there are no workflows in progress, and the `status_string` property resolves to `live + draft`:
https://github.com/wagtail/wagtail/blob/da636f6b613d46d01c5ef6177f5f84c665363f3e/wagtail/models/__init__.py#L1046-L1065

Django added support for prefetching with generic relations and custom querysets via `GenericPrefetch` in django/django#17136, which literally was merged only 2 days ago. In the future, we can make use of it, but for now we'll likely have to figure out a way to rework the optimisation or drop it entirely.

Simon Charette's `GenericForeignKey` subclass might help: https://gist.github.com/charettes/3dcdec3bf66257b0299455a70559f47d

Or the one in this StackOverflow answer: https://stackoverflow.com/a/71109009/8360509

Though it seems those are for prefetching GFKs instead of the reverse (`GenericRelation`). Not sure if that would work automatically or a subclass of `GenericRelation` would be needed.

**Comment by thibaudcolas** [comment]
Can confirm this is an issue. Compare Southern Cornbread on:

- https://static-wagtail-v5-1.netlify.app/admin/
- https://static-wagtail-v5-1.netlify.app/admin/pages/80/
- https://static-wagtail-v5-1.netlify.app/admin/pages/82/edit/

**Comment by wanjugucode** [comment]
Hi @laymonage.
I would like to taking up this task.

**Comment by laymonage** [comment]
@wanjugucode go ahead! This issue is not a very easy one though, but of course you are very welcome to try.

**Comment by wanjugucode** [comment]
Okay

**Comment by gasman** [comment]
Fixed in #11013
