### ISSUE TITLE
Search Query Behavior Issue with Multiple Fields in SnippetViewSet

### ISSUE THREAD

**Issue by AndreMorais98** [wagtail/wagtail#10938]
### Issue Summary

I'm declaring a `SnippetViewSet` on `wagtails_hooks.py`, for an external Model. The problem arises when I specify multiple fields in the search_fields parameter. The search functionality in the Wagtail admin panel fails to work correctly. It is worth noting, that the external model does not inherit from wagtail.search.index.Indexed.

### Steps to Reproduce

To reproduce this issue, follow these steps using an external model or your own model that does not extend `wagtail.search.index.Indexed`. For example, I will use the `SocialApp` model from `django-allauth`:

1. Define a `SnippetViewSet`:
```python
from allauth.socialaccount.models import SocialApp

class SocialAppSnippetViewSet(BaseSnippetViewSet):
    model = SocialApp
    icon = "link"
    menu_order = 100
    inspect_view_enabled = True
    list_display = ("provider", "name", "client_id")
    list_filter = ["provider"]
    search_fields = ["provider", "name", "client_id"]
```

### Relevant Information
Upon analyzing the `search_queryset()` function from the IndexView code in Wagtail, we find the following code:
```python
    def search_queryset(self, queryset):
        if not self.search_query:
            return queryset

        if class_is_indexed(queryset.model) and self.search_backend_name:
            search_backend = get_search_backend(self.search_backend_name)
            return search_backend.autocomplete(
                self.search_query, queryset, fields=self.search_fields
            )

        filters = {
            field + "__icontains": self.search_query
            for field in self.search_fields or []
        }
        return queryset.filter(**filters)
```
In my case, where the class `SocialApp` is not indexed, the code performs a loop over `self.search_fields` and populates the filters dictionary. This results in a query like this, for example, if the search query was 'hello': `{'provider__icontains': 'hello', 'name__icontains': 'hello', 'client_id__icontains': 'hello'}`.  Is this intentional behavior, or should it use an OR condition?

In my case, I have rewritten the `search_queryset()` as follows:
```python
    from django.db.models import Q

    def search_queryset(self, queryset):
        if not self.search_query:
            return queryset

        if class_is_indexed(queryset.model) and self.search_backend_name:
            search_backend = get_search_backend(self.search_backend_name)
            return search_backend.autocomplete(
                self.search_query, queryset, fields=self.search_fields
            )
            
        query = Q()
        for field in self.search_fields or []:
            query |= Q(**{field + "__icontains": self.search_query})

        return queryset.filter(query)
```
With this modification, my query searches for a `SocialApp` with a 'provider' that contains 'hello,' or a 'name' that contains 'hello,' or a 'client_id' that contains 'hello.' This differs from the previous behavior, where it searched for all fields simultaneously with 'hello.'

### Technical details

- Python version: 3.11.5.
- Django version: 4.2.5.
- Wagtail version: 5.1.1.
- Browser version: Chrome 117.

**Comment by varunsaral** [comment]
Hey @laymonage @AndreMorais98 I can do the changes and raise a PR if that's fine.

**Comment by laymonage** [comment]
Yep, go ahead!
