### ISSUE TITLE
NameEmailSettingsPanel should be titled "Name" when email management is disabled

### ISSUE THREAD

**Issue by SebCorbin** [wagtail/wagtail#10937]
### Issue Summary

As NameEmailForm handles working without email, NameEmailSettingsPanel should be titled "Name" when email management is disabled

### Steps to Reproduce

1. `WAGTAIL_EMAIL_MANAGEMENT_ENABLED = False` in your settings
2. Go to your account

**Comment by lb-** [comment]
Can confirm this issue.

<img width="1113" alt="Screenshot 2023-09-26 at 5 22 17 am" src="https://github.com/wagtail/wagtail/assets/1396140/0b3ce297-033e-4d96-ac99-385ae226beb9">

With `WAGTAIL_EMAIL_MANAGEMENT_ENABLED = False`. Observe the email is no longer editable but the panel title still says 'Name and Email'.
<img width="1121" alt="Screenshot 2023-09-26 at 5 22 46 am" src="https://github.com/wagtail/wagtail/assets/1396140/32f7fc64-992c-486e-b033-8b34a41e700b">

## Potential fix

In [`wagtail/admin/views/account.py`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/account.py#L139) we could make the title dynamic as follows;

```py
class NameEmailSettingsPanel(BaseSettingsPanel):
    name = "name_email"
    # title = gettext_lazy("Name and Email")
    order = 100
    form_class = NameEmailForm

    @property
    def title(self):
        from wagtail.admin.views.account import email_management_enabled

        if email_management_enabled():
            return gettext_lazy("Name and Email")
        return gettext_lazy("name")
```

I will flag this as a good first issue, this is quite simple to validate manually but will need unit tests for a PR.

**Comment by FatGuyy** [comment]
Hello, I am new contributor here, Can I work on this issue?

**Comment by lb-** [comment]
@FatGuyy go for it.  Just put up a PR when you're ready.

**Comment by lb-** [comment]
Please remember to include unit tests.

**Comment by FatGuyy** [comment]
I am super new, it might take a bit of time and a bit of help(I'll ask in slack [new contributors]), but get it done!

**Comment by HarshithaPerumalla** [comment]
Can work on this issue. I want to contribute to Wagtail. and also I'm new to opensource so I want to start with good first issue

**Comment by zerolab** [comment]
I'm afraid there is already a PR for this issue. Please do read https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html
