### ISSUE TITLE
Ancestor query N+1 problem.

### ISSUE THREAD

**Issue by Nigel2392** [wagtail/wagtail#10941]
### Is your proposal related to a problem?

Page.get_ancestors() recursively fetches parent pages. It does so by querying the database again, once it reaches the parent.
This can easily be fixed by prefetching the related parent page recursively, possibly with a developer-specified depth.
I have implemented this with MPTT, and the question is viewable on stackoverflow.

### Describe the solution you'd like
My answer to the question applied to django_mptt, but seeing as wagtail also provides a tree structure, I think it can be done.
[stackoverflow answer](https://stackoverflow.com/a/73600241/18020941)

The gist is basically, you make one query (this can be a logical decision if depth is only one, or two.)
This query gets the max depth of the current page's parents, or children in the case of descendants.
Then it is trivial to traverse and prefetch the page tree.
Again, this example is for django_mptt, but it should apply.

> This will require an extra query though. (But that's better than the possible hundreds. - if not more.)
> 
> Some explanation;
> 
> **First:** We will need to determine how many levels deep the categories are for the active products, or in this case, how deep does the page tree go.
> ```
> max_level = Category.objects.filter(product_set__active=True)\ # Reverse lookup on product
>     .values('level')\
>     .aggregate(
>         max_level=models.Max('level')
>     )['max_level']
> ```
> **Second:** We will need to create the prefetch string based on the levels. The maximum amount of levels is equal to the maximum amount of parents. 
> ```
> level 0 = no parents
> level 1 = 1 parent
> level 2 = 2 parents (nested)
> level 3 = 3 parents (nested)
> ```
> This means that we can easily loop over the `range` of the levels, and append the parent (string) to a list.
> ```
> prefetch_string = 'category'
> prefetch_list = []
> for i in range(max_level):
>     prefetch_string += '__parent'
>     prefetch_list.append(prefetch_string)
> ```
> **Third:** We pass in the `prefetch_list`, also unpacking it.
> ```
> Product.objects.filter(active=True).prefetch_related(
>     'category__root',
>     'category', 
>     *prefetch_list) # unpack the list into args.
> ```
> 
> 
> ----------
> 
> 
> We can then easily refactor this into a single dynamic function.
> ```
> def get_mptt_prefetch(field_name, lookup_name='__parent', related_model_qs=None): 
>     max_level = related_model_qs\
>             .values('level')\
>             .aggregate(
>                 max_level=models.Max('level')
>             )['max_level']
>     prefetch_list = []
>     prefetch_string = field_name
>     for i in range(max_level):
>         prefetch_string += lookup_name
>         prefetch_list.append(prefetch_string)
>     return prefetch_list
> ```

This will create a query for prefetching the parent pages, and will vastly reduce overall queries if the tree goes deep enough.

**Comment by gasman** [comment]
Are you sure this is an N+1 query in Wagtail? Testing on the `./manage.py shell` command line with the [bakerydemo](https://github.com/wagtail/bakerydemo) project gives me:

```
>>> from bakerydemo.blog.models import BlogPage
>>> bp = BlogPage.objects.first()
>>> str(bp.get_ancestors().query)
'SELECT "wagtailcore_page"."id", "wagtailcore_page"."path", "wagtailcore_page"."depth", "wagtailcore_page"."numchild", "wagtailcore_page"."translation_key", "wagtailcore_page"."locale_id", "wagtailcore_page"."latest_revision_id", "wagtailcore_page"."live", "wagtailcore_page"."has_unpublished_changes", "wagtailcore_page"."first_published_at", "wagtailcore_page"."last_published_at", "wagtailcore_page"."live_revision_id", "wagtailcore_page"."go_live_at", "wagtailcore_page"."expire_at", "wagtailcore_page"."expired", "wagtailcore_page"."locked", "wagtailcore_page"."locked_at", "wagtailcore_page"."locked_by_id", "wagtailcore_page"."title", "wagtailcore_page"."draft_title", "wagtailcore_page"."slug", "wagtailcore_page"."content_type_id", "wagtailcore_page"."url_path", "wagtailcore_page"."owner_id", "wagtailcore_page"."seo_title", "wagtailcore_page"."show_in_menus", "wagtailcore_page"."search_description", "wagtailcore_page"."latest_revision_created_at", "wagtailcore_page"."alias_of_id" FROM "wagtailcore_page" WHERE ("wagtailcore_page"."path" IN (0001, 00010002, 000100020004, 0001000200040001) AND NOT ("wagtailcore_page"."id" = 62)) ORDER BY "wagtailcore_page"."path" ASC'
```
which seems to me to be the correct query for retrieving all ancestors in one query.

In any case, Wagtail's tree implementation is provided by [django-treebeard](https://github.com/django-treebeard/django-treebeard), so any issues most likely belong there.

**Comment by zerolab** [comment]
The relevant bit in django-treebeard: https://github.com/django-treebeard/django-treebeard/blob/f9674d0adf2ae3077c4475895f0df074179102c7/treebeard/mp_tree.py#L1121-L1134
