### ISSUE TITLE
More documentation around the recommended database

### ISSUE THREAD

**Issue by Nigel2392** [wagtail/wagtail#10949]
### Pertinent section of the Wagtail docs
https://docs.wagtail.org/en/stable/advanced_topics/performance.html#database

### Details
I feel like there isn't enough documentation around the preferred database.
In my experience, MySQL is a good production database. Ofcourse, so is Postgres.
However, in the documentation it is stated:

> We recommend PostgreSQL for production use.

Is there any particular reason for this?
I have been looking through stackoverflow, github and the wagtail documentation to find any kind of explanation, but there isn't really a question asked or an answer given.
It would be nice to also have a reason why in the documentation, this way, developers can weigh the benefits against the drawbacks, and make better, and more concise decision for them, and their team.

**Comment by RealOrangeOne** [comment]
As you say, there's little difference between the 2. If you prefer one, use it. In many situations, SQLite can be limiting, hence it's not the recommended, but PostgreSQL and MySQL do very similar things. PostgreSQL has more features and complex capabilities than MySQL, but perhaps not ones which matter for a CMS. MySQL backs some of the largest sites on the planet, but more and more newer sites are backed by PostgreSQL.

It's recommendation here is more on personal preference than it being objectively better. 99% of Torchbox's applications, including all Wagtail organisation projects run on PostgreSQL in production. Wagtail is actively tested against all 3 backends. 

Above all else, you should use the engine you're most comfortable working with, deploying and administering.

**Comment by MelakuAlehegn** [comment]
Hi @thibaudcolas please assign this to me.

**Comment by thibaudcolas** [comment]
@MelakuAlehegn we do not assign issues, please read our documentation for contributors if you’re not sure where to start.

**Comment by jadesola123** [comment]
Hello

 I'm jadesola, an outreachy contributor and I attempted to solve this issue [here](https://github.com/wagtail/wagtail/pull/11126)
