### ISSUE TITLE
Slug in wagtail not generate

### ISSUE THREAD

**Issue by thevinhhuynh** [wagtail/wagtail#10945]
Version for me:
Python: 3.10
Django: 4.2.3
Wagtail: 5.0
 I follow with: https://docs.wagtail.org/en/stable/releases/5.0.html#slug-field-auto-cleaning-now-relies-on-data-attributes
but this not working.

**Comment by lb-** [comment]
What's the code you are using for your Page panels?

**Comment by thevinhhuynh** [comment]
> What's the code you are using for your Page panels?

@lb-  I'm using:
content_panels = [
        FieldPanel('title'),
        MultiFieldPanel([
            GeoAddressPanel("diachi", geocoder=geocoders.GOOGLE_MAPS),
            LeafletPanel('location', address_field='diachi'),
        ],('Geo details')),
]

promote_panels = [
        FieldPanel('slug', widget=SlugInput),
    ]

SlugInput: from wagtail.admin.widgets.slug import SlugInput

**Comment by lb-** [comment]
You will need to also use `TitleFieldPanel`


```py
from wagtail.admin.panels import FieldPanel, TitleFieldPanel

#...

content_panels = [
  TitleFieldPanel('title'),
  #...
```

See https://docs.wagtail.org/en/stable/releases/5.0.html#changes-to-title-slug-field-synchronisation

**Comment by lb-** [comment]
Alternatively you can use the base Page.content_panels and extend as follows. 

```py
class MyPage(Page):
   content_panels = Page.content_panels + [
      MultiFieldPanel(...),
   ]
```

The base content_panels includes the built in title field. 

https://docs.wagtail.org/en/stable/topics/pages.html#editor-panels

**Comment by thevinhhuynh** [comment]
Ok, tks so much @lb-
