### ISSUE TITLE
"Aging pages"-report visible to CMS users without page permissions

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#10952]
### Issue Summary

We have a very restricted user group, which cannot view/edit pages, but some other models (e.g. images for galleries).
Unfortunately, they still see the "Reports"-menu item, with the single "Aging pages"-report.

Of course, due to the filtering in `get_queryset()` ([here](https://github.com/wagtail/wagtail/blob/a50cc707a2d1bfd05c0df5e4784312a4a34279af/wagtail/admin/views/reports/aging_pages.py#L103)), they will always see an empty list, but it would be nice to skip the menu entry similar to the site history report ([here](https://github.com/wagtail/wagtail/blob/a50cc707a2d1bfd05c0df5e4784312a4a34279af/wagtail/admin/wagtail_hooks.py#L946)).

Note: In a fresh wagtail installation, a user without any permission will also see the workflow menus, but we're not using workflows atm, so I'm not into it, whether it is OK to show it(?)

### Possible Solution

I think there are 2 places to change:
1) the menu item (`is_shown()`)
2) the view (`dispatch()`)

I'm not completely sure, which check is the best one, some views in wagtail use the `user_has_any_page_permission()`-helper ([code](https://github.com/wagtail/wagtail/blob/a50cc707a2d1bfd05c0df5e4784312a4a34279af/wagtail/admin/auth.py#L120-L127)), others check for `explorable_root_instance()` ([code](https://github.com/wagtail/wagtail/blob/a50cc707a2d1bfd05c0df5e4784312a4a34279af/wagtail/permission_policies/pages.py#L178)), but probably the `user_has_any_page_permission()` should be ok, I think(?).

**Menu:**
For the menu item, similar to the `SiteHistoryReportMenuItem`, we could add a permission-check to `is_shown()`.
This is the current state of both menu items:
https://github.com/wagtail/wagtail/blob/a50cc707a2d1bfd05c0df5e4784312a4a34279af/wagtail/admin/wagtail_hooks.py#L944-L951
As mentioned above, I'm not sure which check fits better, `explorable_root_instance()` or `user_has_any_page_permission()`, but the basically lead to the same result(?)

**View:**
We could add a very basic permission check to the base `PageReportView` ([here](https://github.com/wagtail/wagtail/blob/a50cc707a2d1bfd05c0df5e4784312a4a34279af/wagtail/admin/views/reports/base.py#L30)), by overriding the `dispatch()`.
This would by default prevent any new subclasses to expose any information to users without any page permission, but I'm not completely sure, if this is too restrictive(?)
Currently there are 2 subclasses, the `AgingPagesView` and the `LockedPageView` (the later one already checks for the "unlock" permission [here](https://github.com/wagtail/wagtail/blob/a50cc707a2d1bfd05c0df5e4784312a4a34279af/wagtail/admin/views/reports/locked_pages.py#L65-L68)).

Alternatively we could override the `dispatch()`-method only in the `AgingPagesView`.
I'm not sure if there is a cleaner option?

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. `cd myproject && ./manage.py makemigrations && ./manage.py migrate && ./manage.py createsuperuser && ./manage.py runserver`
3. Login to the CMS
4. Create a new group, only select "Can access Wagtail admin"
5. Create a new user and assign it to the new group
6. Login with this user
7. You will now see the "Reports"-menu and the "Aging pages"-item
    As noted in the summary above, in a fresh wagtail installation, also the workflow menus are visible.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11
-   Django version: 4.2.5
-   Wagtail version: 5.1.2 (this is probably the case since the feature has been implemented in #7696, so >=2.16)

**Comment by Temidayo32** [comment]
@th3hamm0r let me try reproducing this error

**Comment by th3hamm0r** [comment]
This has been fixed with #11205
