### ISSUE TITLE
SetActiveStateBulkAction is missing translatable label

### ISSUE THREAD

**Issue by SebCorbin** [wagtail/wagtail#10963]
### Issue Summary

"Mark as active" is not translated when using this bulk action

More technically: the `mark_as_active` field is missing an explicit label in `ActivityForm`, it is generated from its name, hence not translated

### Steps to Reproduce

1. Configure your wagtail site into a fully translated language
2. Go to users list and create one
3. Check it and use the "Set active state" button
4. The form presented has a radio field which is not translated

**Comment by lb-** [comment]
These labels seem to be translated for me, what language did you use?

I can see the code also has these translated. https://github.com/wagtail/wagtail/blob/main/wagtail/users/views/bulk_actions/set_active_state.py#L11
```py
class ActivityForm(forms.Form):
    mark_as_active = forms.TypedChoiceField(
        choices=((True, _("Active")), (False, _("Inactive"))),
        widget=forms.RadioSelect,
        coerce=lambda x: x == "True",
    )
```

<img width="1131" alt="Screenshot 2023-09-29 at 7 17 27 am" src="https://github.com/wagtail/wagtail/assets/1396140/487303a4-4a32-4d1d-a961-5f3ecbaf537b">

<img width="1133" alt="Screenshot 2023-09-29 at 7 16 45 am" src="https://github.com/wagtail/wagtail/assets/1396140/2f07a786-11a3-497c-83cb-fd551e3e970e">

**Comment by lb-** [comment]
Can confirm this issue (ignore my initial deleted comment, I was looking at the wrong thing).

<img width="1425" alt="Screenshot 2023-09-29 at 7 19 39 am" src="https://github.com/wagtail/wagtail/assets/1396140/ece461d2-9c20-4351-a37e-81800e576fba">

Flagging this as a good first issue, should just be a matter of adding a form label here https://github.com/wagtail/wagtail/blob/main/wagtail/users/views/bulk_actions/set_active_state.py#L11

```diff
class ActivityForm(forms.Form):
    mark_as_active = forms.TypedChoiceField(
        choices=((True, _("Active")), (False, _("Inactive"))),
+++        label=_("Mark as active"),
        widget=forms.RadioSelect,
        coerce=lambda x: x == "True",
    )
```

**Comment by rohitsrma** [comment]
Hi @lb-  I'm interested in working on this issue and making the label translateable. To achieve this, should i use the ``{% trans %}`` tag. 

Could you please point me to any other file in the project where a similar approach has been used for translating labels? This would help me better understand the existing conventions and ensure consistency in my implementation. 

Looking forward to your guidance! 🚀

**Comment by SebCorbin** [comment]
@rohitsrma as @lb- stated, `_("Mark as active")` is sufficient, it is aliased to `gettext_lazy` and will be picked up by `./manage.py makemessages`

**Comment by lb-** [comment]
You can read more about how these translation utils work here. 
https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#standard-translation

And about form labels here https://docs.djangoproject.com/en/4.2/ref/forms/fields/#label

**Comment by lb-** [comment]
Note that this will be translatable in the next release, it depends on translators to provide translations but most new translations get covered each release.
