### ISSUE TITLE
SnippetBulkAction not respecting models definition

### ISSUE THREAD

**Issue by srtab** [wagtail/wagtail#10965]
### Issue Summary

I'm registering a bulk action for a snippet model and declared the bulk action as specific for a model with class variable `models`, but the bulk action is being showed on all snippet models and not only the one I've declared.

### Steps to Reproduce

1. Declare on `wagtail_hooks.py` the snippet:
    ```python
    class PeriodicTaskSnippetViewSet(SnippetViewSet):
        model = PeriodicTask
        icon = "tasks"
        menu_order = 100
        list_display = ("name", "enabled", "scheduler", "interval", "start_time", "last_run_at", "one_off")
        list_filter = ["enabled", "one_off", "task", "start_time", "last_run_at"]
        search_fields = ["name"]
    ```
1. Also declare the bulk action:
    ```python
    @hooks.register("register_bulk_action")
    class EnableTaskBulkAction(SnippetBulkAction):
        models = [PeriodicTask]
        display_name = _("Enable")
        aria_label = _("Enable selected tasks")
        action_type = "enable"
        template_name = "core/wagtailadmin/bulk_action_enable_tasks.html"

        @classmethod
        def execute_action(cls, objects, **kwargs):
            for obj in objects:
                obj.enabled = True
                obj.save()
            rows_updated = len(objects)
            return rows_updated, rows_updated
    ```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The documentation (https://docs.wagtail.org/en/stable/extending/custom_bulk_actions.html#adding-bulk-actions-to-the-snippets-listing) says how to limit action to specific models on snippets, but that's not happening.

After checking the code, I think that because `get_models` is being overwritten on `SnippetBulkAction` which ignores if `models` is already defined by the user or not. 

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes 

### Technical details

-   Python version: 3.11.5
-   Django version: 4.2.5
-   Wagtail version: 5.1.2.
-   Browser version: Chrome 117.

**Comment by laymonage** [comment]
Thanks, this might be a regression in c1a4528b8a91ebdb5018837c37ffd54ef34f0aba.

In the meantime you could override `get_models()`, though looking back I think we should've made use of the `classproperty` decorator from `django.utils` instead: https://docs.djangoproject.com/en/4.2/ref/utils/#django.utils.functional.classproperty

**Comment by srtab** [comment]
@laymonage What would you suggest solving this regression? I want to contribute. 

I read the last paragraph of the comment in the `get_models()`, and it's an important concern, but I don't know how to solve without breaking possible direct accesses to `cls.models`.

**Comment by laymonage** [comment]
> @laymonage What would you suggest solving this regression? I want to contribute. 
> 
> 
> 
> I read the last paragraph of the comment in the `get_models()`, and it's an important concern, but I don't know how to solve without breaking possible direct accesses to `cls.models`. 

Could we perhaps start off by reverting the changes in the commit I linked, and instead of adding a get_models method, turn it into a classproperty as I mentioned above? Not sure if that'd work, but I guess it's worth trying

**Comment by srtab** [comment]
@laymonage PR created. Your suggestion worked nicely!
