### ISSUE TITLE
Remove unused userbar views

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#10970]
The userbar was built within the iframe, with Django views that render the iframe's content.

- It first appeared in edd757c5787fd971f620902f6421cc1b51a2b76b.
- Then further refactored in 637899f6c2b82a27bc774121be2dac5c97f6f94c and 5e17881f2d85e8f153c88fdf3bb35e4eecdfcc07. Take note of the latter in particular, where the view was split into `for_frontend` and `for_moderation` views.
- There was a discussion in #2164 which suggested refactoring of the userbar to not use an iframe.
- #2201 did away with the refactoring, removed the iframe and the `wagtailadmin/userbar/frame.html` template.
- Unfortunately, the refactoring did not remove the Django views for the iframe's content, leaving the code unused for 7+ years.

I believe the views are not used anywhere by us and they're very unlikely to be used by developers. As far as developers are concerned, they've been using the `{% wagtailuserbar %}` tag which abstracts the implementation details, including whether it used the iframe or not.

I suggest we remove:
- The whole file for the views https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/userbar.py
- The URLs https://github.com/wagtail/wagtail/blob/a1bd357092bc7107c3d41477536f471a1f3f307d/wagtail/admin/urls/__init__.py#L135-L146
- The tests https://github.com/wagtail/wagtail/blob/a1bd357092bc7107c3d41477536f471a1f3f307d/wagtail/admin/tests/test_userbar.py#L362-L483

**Comment by wanjugucode** [comment]
Hi @laymonage .
I will be taking up this task. Hoping to present a positive report in a short while.

**Comment by laymonage** [comment]
@wanjugucode there is already a PR for this: #10971.
