### ISSUE TITLE
Allow querystrings in email links

### ISSUE THREAD

**Issue by vsalvino** [wagtail/wagtail#10996]
### Issue Summary

Within the rich text editor, it's impossible to insert email links with querystrings. Query parameters such as "subject" and "body" are universally recognized by mail handlers for mailto links. For example: `mailto:info@example.com?subject=Website Inquiry`

See details here: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#specifying_details

### Steps to Reproduce

Open the rich text editor, and insert a link, using the example above. Neither the external link nor email link options allow this syntax, with or without the "mailto:"

![image](https://github.com/wagtail/wagtail/assets/13453401/d64c7eeb-830c-4537-9708-8ecef4afee34)

### Technical details

-   Python version: 3.11
-   Django version: 4.1
-   Wagtail version: 4.2
-   Browser version: Tested in latest Chrome, Edge 117

**Comment by lb-** [comment]
@vsalvino I think this may be fixed in the next release. See https://github.com/wagtail/wagtail/pull/10920 & https://github.com/wagtail/wagtail/issues/5950

**Comment by vsalvino** [comment]
Excellent, somehow I missed those other issues. Thanks!
