### ISSUE TITLE
Consistent Usage of URLs

### ISSUE THREAD

**Issue by codewithmide** [wagtail/wagtail#11007]
### Pertinent section of the Wagtail docs

[Blog index and posts](https://docs.wagtail.org/en/stable/getting_started/tutorial.html#blog-index-and-posts)

### Details

I've noticed that there is an inconsistency in the usage of URLs throughout the Wagtail documentation. In some parts, the documentation uses "http://127.0.0.1:8000/," while in others, it uses "http://localhost:8080/." This inconsistency could potentially confuse users and visitors who are trying to set up a local development environment.

### Proposed Solution

I suggest standardizing the usage of URLs in the documentation to avoid any confusion. We should choose one format (either "http://127.0.0.1:" or "http://localhost:") and ensure that it is used consistently throughout the documentation.

```[tasklist]
### Tasks
```

**Comment by felp99** [comment]
Is someone working on this?

**Comment by anshikavashistha** [comment]
Please assign this issue to me

**Comment by gasman** [comment]
Thanks for your interest @anshikavashistha! We do not assign issues outside of the core team - anyone is free to work on any issue. However, this one already has a PR - #11009
