### ISSUE TITLE
Complete Command in Documentation

### ISSUE THREAD

**Issue by codewithmide** [wagtail/wagtail#11008]
### Pertinent section of the Wagtail docs

![migrate](https://github.com/wagtail/wagtail/assets/81376427/2c11e083-fbf5-44cc-adf9-8d6796dec5d5)

[Tag post](https://docs.wagtail.org/en/stable/getting_started/tutorial.html#tag-posts)

### Details

In the [Tag post](https://docs.wagtail.org/en/stable/getting_started/tutorial.html#tag-posts) section of the documentation, there is an incomplete command provided. It currently says "python manage.py" without specifying the intended operation, such as "migrate" or other management commands. This omission can be confusing for users who are new to Wagtail and trying to follow the instructions.

### Proposed Solution

To improve the clarity and completeness of the documentation, I suggest specifying the full command that users should run. In this case, the documentation should provide the complete command, such as "python manage.py migrate," to ensure that users can follow the steps accurately and without ambiguity.

**Comment by gasman** [comment]
Thanks for reporting! This has already been reported and fixed for the next version of the docs, in #10974 and #10975.

**Comment by codewithmide** [comment]
Oh, great!
