### ISSUE TITLE
Wagtail 4 not support django-filter 23

### ISSUE THREAD

**Issue by vologzzzhanin** [wagtail/wagtail#11019]
### Pertinent section of the Wagtail docs

[Updated django-filter version to support 23 (Yuekui)](https://docs.wagtail.org/en/latest/releases/4.0.html#:~:text=Updated%20django%2Dfilter%20version%20to%20support%2023%20(Yuekui))

### Details

The package version support stated in the documentation is not true - [link](https://github.com/wagtail/wagtail/blob/677df057960c48256118f40aad105acedf67c42e/setup.py#L28)

While I realize that this may not be a major inconsistency, I would like to see it fixed - either in the documentation or in setup.py

**Comment by laymonage** [comment]
Yep looks like the release notes for #8724 were incorrectly written in 920c0afdf435556342d92ab9926f26c9b8ebc411. The upper bound was indeed moved to 23, but it uses `<` so the release notes shouldn't say `support 23`.

**Comment by gasman** [comment]
Looks like the same thing happened again in #10632!

**Comment by lb-** [comment]
Yeah, see 91a3c6d2c2faf0315f5b498e20ce3e30d50d9379 - I must have read the previous number and just increased it.

**Comment by gasman** [comment]
Updated in a7f7757630c83eec12e819a4ea329abffac2d1a6 / a7f7757630c83eec12e819a4ea329abffac2d1a6 and backported to older branches as far as stable/4.1.x (the current LTS release) so that the docs will be updated if we make another patch release on those versions. Thanks for reporting, @vologzzzhanin!
