### ISSUE TITLE
updating document

### ISSUE THREAD

**Issue by akshayamadhuri** [wagtail/wagtail#11010]

**Comment by gasman** [comment]
Hi @akshayamadhuri - thanks for the contribution, but you've left the description blank here, so we have no way of knowing what you're trying to fix here - "updating document" does not tell us anything. Please edit the issue title and description to tell us what problem you're aiming to solve.

**Comment by thibaudcolas** [comment]
@akshayamadhuri I’m not sure what you’re trying to do here but looking at pull request #11011 this looks a lot like straight up spam from our perspective. Please review our contribution guidelines before opening issues or pull requests in the future.
