### ISSUE TITLE
🎛️ Add ability to pass `attrs` into the Dialog template tag & merge data-controller/data-action

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#11030]
### Is your proposal related to a problem?

When writing up the issue #11029 I realised it would be nicer if we could attach the event listeners for this to the Dialog HTML element. However, it's not currently possible to add arbitrary attributes to the dialog element.

Additionally, due to the usage of `data-controller` / `data-action` on this element it will not be possible to easily just pass them through.

### Describe the solution you'd like

Taking the code example from `wagtail/admin/templates/wagtailadmin/panels/publishing/schedule_publishing_panel.html`

```html
{% dialog id='schedule-publishing-dialog' dialog_root_selector='[data-edit-form]' classname=classname icon_name='calendar-alt' title=schedule_publishing_dialog_title subtitle=schedule_publishing_dialog_subtitle|capfirst message_icon_name='info' message_status='info' message_heading=message_heading message_description=message_description %}
    {% include 'wagtailadmin/panels/multi_field_panel.html' %}
    ... other stuff
{% enddialog %}
```

I would like to suggest we could do something like this.

```html
{% dialog id='schedule-publishing-dialog' dialog_root_selector='[data-edit-form]' classname=classname icon_name='calendar-alt' title=schedule_publishing_dialog_title subtitle=schedule_publishing_dialog_subtitle|capfirst message_icon_name='info' message_status='info' message_heading=message_heading message_description=message_description attrs=attrs %}
    {% include 'wagtailadmin/panels/multi_field_panel.html' %}
    ... other stuff
{% enddialog %}
```

Where `attrs` would be any arbitrary (maybe without class/id) attributes we can then output on the result dialog HTML element. We could use this in the publishing side panel  as so.

```py
class PublishingPanel(MultiFieldPanel):
    # ...

    class BoundPanel(MultiFieldPanel.BoundPanel):
        template_name = "wagtailadmin/panels/publishing/schedule_publishing_panel.html"

        def get_context_data(self, parent_context=None):
            context = super().get_context_data(parent_context)
            # ... other things
            context["attrs"] = {
                "data-controller": "w-action",
                "data-action": "w-dialog:->w-action#reset",
                "data-w-action-target-param": "#id_go_live_at,#id_expire_at",
            }
            return context
```

The template output would be something like this

```html
{% load wagtailadmin_tags i18n %}
<template
    data-controller="w-teleport"
    {% if dialog_root_selector %}data-w-teleport-target-value="{{ dialog_root_selector }}"{% endif %}
>
    <div id="{{ id }}"
        aria-labelledby="title-{{ id }}"
        aria-hidden="true"
        class="w-dialog {% if theme %}w-dialog--{{ theme }}{% endif %} {% if classname %} {{ classname }}{% endif %}"
        {% include "wagtailadmin/shared/attrs.html" with attrs=attrs %}
    >
        <div data-a11y-dialog-hide class="w-dialog__overlay"></div>
```

The way we could implement this in the Dialog node would be something like this `wagtail/admin/templatetags/wagtailadmin_tags.py`. (have not thought about class or id removal yet).

```py
class DialogNode(BlockInclusionNode):
    template = "wagtailadmin/shared/dialog/dialog.html"

    def get_attrs(self, context):
        """
        Returns a dictionary of attributes to be added to the inner dialog element.
        `data-controller` & `data-action` will be merged with any values within the
        context's `attrs`.
        """
        attrs = context.get("attrs", {}).copy()
        attrs["data-controller"] = " ".join(
            filter(None, [attrs.get("data-controller", ""), "w-dialog"])
        )
        attrs["data-action"] = "".join(
            filter(
                None,
                [
                    attrs.get("data-action", ""),
                    "w-dialog:hide->w-dialog#hide",
                    "w-dialog:show->w-dialog#show",
                    # RemovedInWagtail60 - Remove the following two actions.
                    "wagtail:hide->w-dialog#hide",
                    "wagtail:show->w-dialog#show",
                ],
            )
        )
        theme = context.get("theme")
        if theme:
            attrs["data-w-dialog-theme-value"] = theme
        data_url = context.get("data_url")
        if data_url:
            attrs["data-url"] = data_url
        return attrs

    def get_context_data(self, parent_context):
        context = super().get_context_data(parent_context)
        context["attrs"] = self.get_attrs(context)
        # .. rest of method
```

### Describe alternatives you've considered

- We could just not allow this pattern, it's maybe not something we want to support at all, in which case, we can find other ways to reach our goals of dialog related event listeners and behaviour.
- We may not want to treat data-controller/data-action specially, however, we have done this for the `TitleFieldPanel` and it seems like a nice approach for lots of customisability but simple Python driven logic.
- We could be more explicit by passing specific attrs to the dialog, similar to how we do for `dialog_root_selector`, but this will get verbose quickly.
- We could 'merge' the attrs with a new template tag, something like below, however this feels wrong as we need to parse the text into objects, do the merging and then output again as a string.

```html
<div
  {% merge_attrs  with attrs=attrs %}
    data-controller="w-is-merged"
    data-anything="overrides-provided"
  {% endmerge_attrs %}
 >
</div>
```

### Additional context

* This came out of trying to solve for #11029 (simple way to use our existing Controllers) and realising we cannot easily attach event listeners to the dialog HTML via Stimulus actions in an intuitive way.

**Comment by lb-** [comment]
Will flag for discussion at the next core team meeting, just want to get consensus on this approach (or other ideas) before proceeding.

**Comment by gasman** [comment]
Having to shift these `data-` attributes all the way from HTML into Python code feels like a clear violation of [locality of behaviour](https://htmx.org/essays/locality-of-behaviour/), which I figure must be a strong design principle of Stimulus as it is for HTMX.

I'm not really close enough to this code to offer any actionable suggestions, but I think it's worth taking a step back and figuring out what's pushed us down this path. Some initial thoughts:

* If the 'dialog' component needs to expose more and more of its internal workings to achieve what we need, is it fit for purpose as an abstraction, or is it just adding an extra hoop to jump through when we might as well just be writing out `<div>` tags longhand with whatever attributes we need?
* I wonder if the deeper problem here is that template tags don't have a built-in concept of inheritance - if we need to augment or specialise an existing pattern that's implemented as a template tag, then passing parameters is the natural go-to way of doing that. If all you have is a hammer, every problem looks like a nail... and so we're overloading the "dialog" tag with extra parameters, when we should really be introducing a new tag/component that inherits from the base "dialog" to provide a "scheduled publishing dialog", or "resettable dialog" or similar.

**Comment by lb-** [comment]
Thank you Matt, this is a very helpful perspective and I agree, it doesn't feel right to be doing this passing/massaging of attrs here. 

I guess my actual, current, problem is that I want an element inside the dialog to know (via events) that the modal containing it is about to close / has closed. 

Maybe a simpler approach would be to add a 'notify' target, any of those targets within the dialog will get the opened/closed events dispatched on them.

This keeps things generic, but still let's us do some really flexible things with elements inside the dialog. The dialog outer element does not need any attributes. Only the field needing these events just declares itself as a notify target. 

```html
<input type="date" data-controller="w-action" data-w-dialog-target="notify" data-action="w-dialog:closed->w-action#reset />
```

I'll have a bit more of a play with this idea, but would love any feedback. 

As for the idea of the 'resettable dialog' or similar, I think it could be an approach also. But we then face the problem of this kind of dialog needing to know what fields inside to target. To be fair, that same problem exists with the passing of the `attrs`. The outside 'panel that renders the modal' would need to have knowledge of the fields that require resetting.

Instead, we probably want the fields that require resetting to simply set their own attributes to achieve that behaviour.

**Comment by lb-** [comment]
Opting to close this as not required, the internal notify target is a simpler approach and also gives us a lot more flexibility for content within modals in the future.

We wont have to add 'knowledge' of these internal elements' requirements to the dialog level this way either. Plus no special treatment of the data-controller/data-action attributes required here.
