### ISSUE TITLE
Using the sidebar's explorer triggers action-button of current view

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#11037]
### Issue Summary

I've stumbled over this weird issue, which is really hard to reproduce, but it happens now and then.
This issue happens, when you're on a screen with a actions-dropdown in the header, e.g. the site report view, where you can export the report, but also on the redirects admin view for example, where you can export/import redirects.
In some rare cases, if I'm on this screen, and I use the explorer-menu to go to a page, it actually triggers an action from the dropdown...
I was able to capture it once, but I haven't found a clean way to reproduce it:
![wagtail_csv_export_issue](https://github.com/wagtail/wagtail/assets/468164/ec0be1df-edbe-4443-bcbb-18a0ff6d1191)

Note: Normally, I don't click on the top-right dropdown, before I use the explorer, and it still triggers the action. So the screencapture only captured one of my attempts.

It seems like it only happens with Firefox, at least I wasn't able to reproduce it with Chrome.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. `cd myproject && ./manage.py makemigrations && ./manage.py migrate && ./manage.py createsuperuser && ./manage.py runserver`
3. Login to the CMS
4. Create one child page under "Home" (it seems to happen more often when navigating in the explorer)
5. Go to the site history
6. Do something, which isn't clear to me yet.
7. Open the "Pages" explorer, navigate to the subpage, and click on the title of the page, or the area beside it.
8. If the issue occurs, it should actually download the report's csv/xlsx.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11
-   Django version: 4.2.6
-   Wagtail version: 5.1.2
-   Browser version: Firefox 118 (but this happened with older versions too)

**Comment by Temidayo32** [comment]
@th3hamm0r let me try me hands on reproducing this issue.

**Comment by Temidayo32** [comment]
> 7. Open the "Pages" explorer, navigate to the subpage, and click on the title of the page, or the area beside it.

can you clarify what you mean by pages explorer?

> If the issue occurs, it should actually download the report's csv/xlsx.
Can you clarify what is meant here?

**Comment by laymonage** [comment]
@Temidayo32 The "page explorer" is the "Pages" menu item in the main menu on the left side.

Report pages (e.g. go to "Reports" -> "Site history" in the main menu) gives you the option to download the report as a spreadsheet.

For some reason, interacting with the page explorer while you're on an admin view (e.g. Report) would cause the action button (e.g. download XLSX) to be triggered, which is not a desired behaviour.

You can see the screen record in the issue description for an example of the issue.

**Comment by th3hamm0r** [comment]
Thanks @laymonage for the clarification.

I think I've now found the underlying problem: its the "overflow-menu", or the hidden actions of the dropdown in the top right.
If the screen size is big enough (like in the screenshot below), the hidden items of the menu actually sit on the left of the content area, near the explorer's menu, and also with a higher z-index, and those hidden items are clickable.
So you don't actually need to use the explorer, you can just click in that area, but even with an overlapping explorer, the hidden link is clickable.

With this learning, I can now also reproduce it with Chrome (just the window must be large enough).

![wagtail_dropdown_issue](https://github.com/wagtail/wagtail/assets/468164/61cc8f9a-d1fb-4914-a0c7-5a6d1550e61a)

**Comment by laymonage** [comment]
Oh, great, thanks @th3hamm0r I can reproduce this.

https://github.com/wagtail/wagtail/assets/6379424/5d67634f-6589-45a0-8555-7a268fbea11b

We can probably fix this with CSS in the short term, but for the long-term I think it's best to reimplement this button using our Stimulus `DropdownController`. Not to mention the possibility of moving the action buttons somewhere in the header (e.g. after the breadcrumbs) when we continue the work for #10446.

**Comment by Temidayo32** [comment]
@laymonage Thanks for the clarification. Can I take it up to fix with CSS as you mentioned?

**Comment by Temidayo32** [comment]
@th3hamm0r You are right about the size of the screen. The error doesn't show up on smaller window screen sizes. 
![Uploading JNChV1DVTp.png…]()

**Comment by lb-** [comment]
Can confirm this also, it appears that when you have viewports over ~2400 px wide the dropdown toggle button appears right where the page explorer menu is.

The closed dropdown options are offset by ~2000px and this means they will be clickable when closed at wide viewports.

The PR up should fix this.

**Comment by lb-** [comment]
Will be fixed in the next release of Wagtail (5.3)
