### ISSUE TITLE
Nested orderable panels incorrectly disabling move on children

### ISSUE THREAD

**Issue by seb-b** [wagtail/wagtail#11041]
### Issue Summary

If you have a nested inline panel, and it's parent inline panel has just one child, you cannot move the children, in my example screenshot the parent has 1 child panel, and none of the children are moveable. Adding another parent (Date) makes the children (Rows) become moveable and enables the buttons - 

![image](https://github.com/wagtail/wagtail/assets/1635388/378b9444-cd73-4895-993b-c897a2e0c995)

I believe this is a specificity problem from here: https://github.com/wagtail/wagtail/blob/main/client/src/components/InlinePanel/index.js#L130

I found this in 4.1, but the code looks unchanged. 

### Steps to Reproduce

1. Create an nested orderable within and orderable
2. In the admin create one parent, multiple children
3. Cannot re-order the children

**Comment by gasman** [comment]
Hi @seb-b - I think this might be the same issue described by #5919. Can you confirm?

**Comment by seb-b** [comment]
@gasman Yep that's the same issue. I just realised that re-ordering the children re-orders the parent after it's enabled!
