### ISSUE TITLE
Draftail toolbar items with custom svg path icon not being rendered as svg in block menu

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail#11051]
### Issue Summary

If a block style has been registered with an svg path for the control icon, it displays correctly in the toolbar (either pinned or unpinned) but in the block pop-over menu, the path is passed as text into the icon `<div>` element.

For example, a left-align button registered with

```python
control["icon"] = [
        "M 584.19821,168.76226 H 73.024776 C 32.701407,168.76226 0,137.69252 0,99.38113 0,\
        61.069736 32.701407,30 73.024776,30 H 584.19821 c 40.39183,0 73.02477,31.069736 73.02477,\
        69.38113 0,38.31139 -32.63294,69.38113 -73.02477,69.38113 z m 0,\
        555.04902 H 73.024776 C 32.701407,723.81128 0,692.80659 0,654.43015 0,616.05372 32.701407,\
        585.04902 73.024776,585.04902 H 584.19821 c 40.39183,0 73.02477,31.0047 73.02477,69.38113 0,\
        38.37644 -32.63294,69.38113 -73.02477,69.38113 z M 0,376.90564 C 0,338.5292 32.701407,\
        307.52451 73.024776,307.52451 H 949.32209 c 40.39183,0 73.02481,31.00469 73.02481,69.38113 0,\
        38.37644 -32.63298,69.38113 -73.02481,69.38113 H 73.024776 C 32.701407,446.28677 0,415.28208 0,\
        376.90564 Z M 949.32209,1001.3358 H 73.024776 C 32.701407,1001.3358 0,970.3311 0,931.95467 0,\
        893.57823 32.701407,862.57354 73.024776,862.57354 H 949.32209 c 40.39183,0 73.02481,\
        31.00469 73.02481,69.38113 0,38.37643 -32.63298,69.38113 -73.02481,69.38113 z"
    ]
```

On the toolbar:

```html
<button name="left-align"
        class="Draftail-ToolbarButton  Draftail-ToolbarButton--active"
        type="button"
        aria-label="Left align text"
        tabindex="-1"
        data-draftail-balloon="up">
    <svg width="16"
         height="16"
         viewBox="0 0 1024 1024"
         class="Draftail-Icon "
         aria-hidden="true">
        <path d="M 584.19821,168.76226 H 73.024776 C 32.701407,168.76226 0,137.69252 0,99.38113 0,        61.069736 32.701407,30 73.024776,30 H 584.19821 c 40.39183,0 73.02477,31.069736 73.02477,        69.38113 0,38.31139 -32.63294,69.38113 -73.02477,69.38113 z m 0,        555.04902 H 73.024776 C 32.701407,723.81128 0,692.80659 0,654.43015 0,616.05372 32.701407,        585.04902 73.024776,585.04902 H 584.19821 c 40.39183,0 73.02477,31.0047 73.02477,69.38113 0,        38.37644 -32.63294,69.38113 -73.02477,69.38113 z M 0,376.90564 C 0,338.5292 32.701407,        307.52451 73.024776,307.52451 H 949.32209 c 40.39183,0 73.02481,31.00469 73.02481,69.38113 0,        38.37644 -32.63298,69.38113 -73.02481,69.38113 H 73.024776 C 32.701407,446.28677 0,415.28208 0,        376.90564 Z M 949.32209,1001.3358 H 73.024776 C 32.701407,1001.3358 0,970.3311 0,931.95467 0,        893.57823 32.701407,862.57354 73.024776,862.57354 H 949.32209 c 40.39183,0 73.02481,        31.00469 73.02481,69.38113 0,38.37643 -32.63298,69.38113 -73.02481,69.38113 z">
        </path>
    </svg>
</button>
```
![image](https://github.com/wagtail/wagtail/assets/72310199/de7f7ed0-dc98-4639-ad7c-15fb5b0e5bf0)

On the block pop-over menu:

```html
<div role="option"
     aria-selected="false"
     id="downshift-0-item-9"
     class="w-combobox__option w-combobox__option--col2">
    <div class="w-combobox__option-icon">
        M 584.19821,168.76226 H 73.024776 C 32.701407,168.76226 0,137.69252 0,99.38113 0,        61.069736 32.701407,30 73.024776,30 H 584.19821 c 40.39183,0 73.02477,31.069736 73.02477,        69.38113 0,38.31139 -32.63294,69.38113 -73.02477,69.38113 z m 0,        555.04902 H 73.024776 C 32.701407,723.81128 0,692.80659 0,654.43015 0,616.05372 32.701407,        585.04902 73.024776,585.04902 H 584.19821 c 40.39183,0 73.02477,31.0047 73.02477,69.38113 0,        38.37644 -32.63294,69.38113 -73.02477,69.38113 z M 0,376.90564 C 0,338.5292 32.701407,        307.52451 73.024776,307.52451 H 949.32209 c 40.39183,0 73.02481,31.00469 73.02481,69.38113 0,        38.37644 -32.63298,69.38113 -73.02481,69.38113 H 73.024776 C 32.701407,446.28677 0,415.28208 0,        376.90564 Z M 949.32209,1001.3358 H 73.024776 C 32.701407,1001.3358 0,970.3311 0,931.95467 0,        893.57823 32.701407,862.57354 73.024776,862.57354 H 949.32209 c 40.39183,0 73.02481,        31.00469 73.02481,69.38113 0,38.37643 -32.63298,69.38113 -73.02481,69.38113 z
    </div>
    <div class="w-combobox__option-text">Left align text</div>
</div>
```

![image](https://github.com/wagtail/wagtail/assets/72310199/d2c3c2b0-cffd-4350-8870-870362a1f35f)

The centre-align, right-align and code-block icons are also registered with svg paths and display the same behaviour.

### Steps to Reproduce

Create a block style in wagtail_hooks. Use the [help-text example](https://docs.wagtail.org/en/stable/extending/extending_draftail.html#creating-new-blocks) from docs, but replace label with icon defined as svg path (question mark):

```python
import wagtail.admin.rich_text.editors.draftail.features as draftail_features
from wagtail.admin.rich_text.converters.html_to_contentstate import BlockElementHandler

@hooks.register('register_rich_text_features')
def register_help_text_feature(features):
    """
    Registering the `help-text` feature, which uses the `help-text` Draft.js block type,
    and is stored as HTML with a `<div class="help-text">` tag.
    """
    feature_name = 'help-text'
    type_ = 'help-text'

    control = {
        'type': type_,
        'icon': ["m 334.22246,308.44491 c 0,-76.23832 61.98413,-138.22245 138.22245,-138.22245 h 69.11123 c 76.23832,0 138.22246,61.98413 138.22246,138.22245 v 7.77502 c 0,47.08202 -23.97296,90.92446 -63.49594,116.19325 l -91.14044,58.52857 c -54.42509,34.98756 -87.25292,95.24391 -87.25292,159.81972 v 3.23958 c 0,38.22715 30.88408,69.11123 69.11123,69.11123 38.22715,0 69.11123,-30.88408 69.11123,-69.11123 v -3.02361 c 0,-17.70975 9.07084,-34.12367 23.75698,-43.62646 L 691.00917,548.8224 C 770.05514,497.85287 818.00105,410.38397 818.00105,316.21993 v -7.77502 C 818.00105,155.75229 694.24876,32 541.55614,32 H 472.44491 C 319.75229,32 196,155.75229 196,308.44491 c 0,38.22715 30.88408,69.11123 69.11123,69.11123 38.22715,0 69.11123,-30.88408 69.11123,-69.11123 z M 507.00053,999.5572 a 86.38904,86.38904 0 1 0 0,-172.77808 86.38904,86.38904 0 1 0 0,172.77808 z"],
        'description': 'Help text',
        # Optionally, we can tell Draftail what element to use when displaying those blocks in the editor.
        'element': 'div',
    }

    features.register_editor_plugin(
        'draftail', feature_name, draftail_features.BlockFeature(control, css={'all': ['help-text.css']})
    )

    features.register_converter_rule('contentstate', feature_name, {
        'from_database_format': {'div[class=help-text]': BlockElementHandler(type_)},
        'to_database_format': {'block_map': {type_: {'element': 'div', 'props': {'class': 'help-text'}}}},
    })
```

Include the feature in your draftail-editor. 
In a rich text editor, check button displays correctly on the toolbar
![image](https://github.com/wagtail/wagtail/assets/72310199/1bad6c44-bede-4cc9-abc4-aa599abb3645)

Select the '+' or type '/' for the block popover menu, icon is rendered as path text instead:
![image](https://github.com/wagtail/wagtail/assets/72310199/9e5337b6-3486-41a6-8a5f-c31d1c7793f9)

### Technical details

-   Python version: 3.10.6
-   Django version: 4.2.2
-   Wagtail version: 5.1.1
-   Browser version: Chrome 118

**Comment by rajesh604** [comment]
hi can you assign me this issue

**Comment by kanugurajesh** [comment]
hi @enzedonline can you assign me this issue?

**Comment by lb-** [comment]
@kanugurajesh we don't assign issues outside of the core team. If you'd like to see if you can reproduce this issue with the steps provided, that would be helpful. 

Here's a link to our contribution guide for more info. https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html

**Comment by Temidayo32** [comment]
I will like to work on the issue

**Comment by Temidayo32** [comment]
@enzedonline I have followed your steps to reproduce the error, and here is the output I got.

![msedge_CrCLn08DAn](https://github.com/wagtail/wagtail/assets/87539866/44c9fdcb-3b5d-47b6-bff7-991f3cbf5481)

I used the technical specification provided. Perhaps, it might be different issue as I couldn't reproduce the error. I used `RichTextField`. Perhaps, `RichTextBlock` it is?

**Comment by gasman** [comment]
This was previously reported at #10319 - however, since the report here is more detailed I'll keep this one and close the older one as a duplicate.

**Comment by Temidayo32** [comment]
Still on this issue. So I made a little change. I removed `help-text` from `WAGTAILADMIN_RICH_TEXT_EDITORS`, then refreshed my wagtail site. Then, I readded `help-text`, and refreshed again and now the issue @enzedonline reported shows up. This issue also shows up on my Microsoft Edge browser (Version 118.0.2088.46)

![chrome_4c3qTOXRYl](https://github.com/wagtail/wagtail/assets/87539866/448239fb-152e-40c8-869b-fb4fa402fdd2)

**Comment by enzedonline** [comment]
@Temidayo32 it looks like the first time around you had the character '?' rather than the svg - perhaps you'd copied the code from the example and run before amending label to icon?

**Comment by enzedonline** [comment]
I guess the obvious workaround for this is to just register the custom icons and reference those by id's. I only came across this from upgrading 3.x sites. Since this issue has been around since 4.x, maybe the better route now is to just amend the docs to say it's not supported since 3.x??

**Comment by Temidayo32** [comment]
@

> @Temidayo32 it looks like the first time around you had the character '?' rather than the svg - perhaps you'd copied the code from the example and run before amending label to icon?

Actually, I used the svg from the very start. That's why it seems wierd it displayed the svg on the second try.

**Comment by Temidayo32** [comment]
> I guess the obvious workaround for this is to just register the custom icons and reference those by id's. I only came across this from upgrading 3.x sites. Since this issue has been around since 4.x, maybe the better route now is to just amend the docs to say it's not supported since 3.x??

By 3.x sites, are you referring to the python versions used by these sites or django version? 
If I understand you, you are saying defining icons as done above is not supported any longer?

**Comment by enzedonline** [comment]
Wagtail 3.x

_"If I understand you, you are saying defining icons as done above is not supported any longer?"_
No, just that it appears it's never been compatible with the combo-box since it was introduced in Wagtail 4.x. It's likely that using svg paths directly in the icon definition wasn't widely used, otherwise there would have been more reports of it by now. If that's the case, a doc update to point people to registering custom icons instead would be the easier route, more inline with how Wagtail 5.x should be used at least.

**Comment by Temidayo32** [comment]
@enzedonline  I think current Wagtail documentation still supports the use of SVG paths . Here is a snippet from the documentation:

> > For detailed configuration options, head over to the [Draftail documentation](https://www.draftail.org/docs/formatting-options) to see all of the details. Here are some parts worth highlighting about controls:
> 
> The type is the only mandatory piece of information.
> 
> To display the control in the toolbar, combine icon, label and description.
> 
> The controls’ icon can be a string to use an icon font with CSS classes, say 'icon': 'fas fa-user',. **It can also be an array of strings, to use SVG paths, or SVG symbol references for example 'icon': ['M100 100 H 900 V 900 H 100 Z'],. The paths need to be set for a 1024x1024 viewbox.**

So this is a bug that needs to be fixed.

**Comment by Temidayo32** [comment]
@enzedonline I have found the cause of the error. Current Wagtail implementation doesn't handle the rendering of SVG path, hence the error. It only handles SVGs passed as `name` to `href`. I will making a PR that fixes this soon.
