### ISSUE TITLE
Dark mode - Colour variable updates

### ISSUE THREAD

**Issue by benenright** [wagtail/wagtail#11060]
Track changes to base colours and colour tokens here:

https://docs.google.com/spreadsheets/d/16CY8ClwPgywN5aJrXZ57ePrAXGpeDpPaXsaUjWgTXnM/edit#gid=1503114917

**Comment by zerolab** [comment]
@benenright any chance you can make that spreadsheet readable by anyone with the link?

**Comment by benenright** [comment]
> @benenright any chance you can make that spreadsheet readable by anyone with the link?

Done.

**Comment by benenright** [comment]
Ref a related issue: https://github.com/wagtail/wagtail/issues/10875 I suggest we do as part of this one.

**Comment by thibaudcolas** [comment]
The spreadsheet in Markdown for future ref:

| Col      | Col    |
| -------- | ------ |
| grey-600 | 262626 |
| grey-700 | 222222 |
| grey-800 | 1D1D1D |
| red-50   | FEF0F0 |
| red-200  | CA3B3B |
| blue-50  | E2F5FC |
| blue-100 | 1D7792 |

| Colour Tokens                 | Light      | Dark     |
| ----------------------------- | ---------- | -------- |
| surface-menus                 | indigo-100 | grey-800 |
| surface-menu-item-active      | indigo-200 | grey-700 |
| surface-header                | grey-50    | grey-700 |
| text-button-outline-default   | teal-200   | teal-100 |
| text-button-outline-hover     | teal-400   | teal-100 |
| border-button-outline-default | teal-200   | teal-100 |
| border-button-outline-hover   | teal-400   | teal-100 |
| surface-button-outline-hover  | teal-50    | grey-700 |

**Comment by lb-** [comment]
Fixed via https://github.com/wagtail/wagtail/pull/11463
