### ISSUE TITLE
Documentation - Update all `FieldPanel('title'...` examples to use `TitleFieldPanel('title'...`

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#11078]
Wagtail 5.0.2 introduced a new recommended `TitleFieldPanel` that supports the linking for the slug field and other UI improvements for the title field. However, many of our documentation examples do not use this and it could cause confusion if the slug field is not working as expected.

- https://docs.wagtail.org/en/stable/releases/5.0.2.html#use-of-titlefieldpanel-for-the-page-title-field
- https://docs.wagtail.org/en/stable/reference/pages/panels.html#title-field-panel

### Pertinent section of the Wagtail docs

There are a few places, listed below, but generally where we have `FieldPanel('title'...` set, we would want this to be updated to `TitleFieldPanel('title'...`.  A reminder that not all title fields used in the documentation are for `Page` models, so we cannot just bulk update, we should also update the imports in code snippets if applicable.

#### Example `docs/advanced_topics/customisation/page_editing_interface.md`

```diff
- from wagtail.admin.panels import TabbedInterface, ObjectList
+ from wagtail.admin.panels import TabbedInterface, TitleFieldPanel, ObjectList

class BlogPage(Page):
    # field definitions omitted

    content_panels = [
-        FieldPanel('title', classname="title"),
+        TitleFieldPanel('title', classname="title"),
        FieldPanel('date'),
```

### Details

The following files would need to be updated.

- `docs/advanced_topics/customisation/page_editing_interface.md`, see `content_panels` & `shared_panels` in code examples (3 all up).
- `docs/reference/pages/panels.md` see `Placeholder text` section ~L380
- There may be more, we do not want to update any of the ModelAdmin docs as these are all non-page models, even though they have a 'title' field for some of those models.

**Comment by vinayakhegde1** [comment]
@lb- I would like to work on this issue

**Comment by lb-** [comment]
Go for it @vinayakhegde1 - we don't assign issues so just put up a PR when you're ready.

**Comment by vinayakhegde1** [comment]
@lb- thanks

**Comment by Chinex-Boroja** [comment]
@lb- I would to work on this too

**Comment by Chinex-Boroja** [comment]
Hi @lb-, I just raised a PR for this issue. Could you check and provide feedback or possible changes if needed? Thank you
