### ISSUE TITLE
Can't scroll down to bottom items in the `Switch locales` dropdown since the menu overflows off screen

### ISSUE THREAD

**Issue by TheBoroer** [wagtail/wagtail#11108]
Hey!

It seems like (at least in wagtail v5) if we have many locales added to the site, the switch locales dropdown list overflows past the height of wagtails side panel. Which leads us not being able to scroll down and click on the locales at the bottom of that list unless we zoom out on the page.

This is where it gets cut off for us when the window/screen resolution is 1680x1050:
![image](https://github.com/wagtail/wagtail-localize/assets/5162876/0980c0fc-b498-4ae0-9d97-3df8e2f1699d)
We're unable to scroll down and click on `Vietnamese`.

I could take a stab at fixing this when i have some free time but in case someone else can fix this quicker than me, feel free :)

**Comment by Chiemezuo** [comment]
I just reproduced the issue and made a working fix for it. I'll be raising a PR for the changes in a bit.

**Comment by Chiemezuo** [comment]
## Steps to Reproduce
1. You are going to need a project to see the problem in. You can use any existing one, but I personally chose the [bakerydemo](https://github.com/wagtail/bakerydemo) project.
2.  You will need to add locales to the project. For this, you will edit the `bakerydemo/settings/base.py` file from within the `bakerydemo` folder. This is done by modifying `WAGTAIL_CONTENT_LANGUAGES`. You can replace the code with the following sample:
```python
WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [
    ("en", "English"),
    ("de", "Deutsch"),
    ("ar", "العربيّة"),
    ('fr', 'French'),
    ('it', 'Italian'),
    ('pt', 'Portuguese'),
    ('ru', 'Russian'),
    ('ko', 'Korean'),
    ('sv', 'Swedish'),
    ('tr', 'Turkish'),
    ('sv', 'Swedish'),
    ('es', 'Spanish'),
    ('zh', 'Chinese (Simplified)'),
    ('ja', 'Japanese'),
    ('pl', 'Polish'),
    ('el', 'Greek'),
    ('cs', 'Czech'),
    ('no', 'Norwegian'),
    ('fi', 'Finnish'),
]
```
3. As a precautionary step, run `python manage.py migrate` in the root of the project (in my case, `bakerydemo`).
4. Log into the admin dashboard, and by the left panel, select `settings` and select `locale`. Add the locales. The locales will appear based on the changes you made in step 2.
5. Still in the admin dashboard, go to any page (or create a new one). I used the `Welcome to your wagtail site` page.  When you get there, click on the three dots `...` by the side of the title, and select `translate`.
6. You will be prompted to select the locales you want to make translations for. For the purpose of reproducing this bug, select all.
7. Step 6 will lead to a lot of page drafts getting created, but go to the main English version of the page from step 5, click on `edit`, and by the side panel, you will see a drop-down for selecting locales. That is the bug.

**Comment by lb-** [comment]
Note, this is better with https://github.com/wagtail/wagtail/pull/11456 (in 6.0).

The overall page height gets longer if there is a super long dropdown.

<img width="1272" alt="Screenshot 2024-03-14 at 7 13 24 am" src="https://github.com/wagtail/wagtail/assets/1396140/470fad12-eda0-42f5-aebb-bb8e365166a6">

However, it may be nice to introduce some kind of reasonable max height as proposed by #11124 anyway.
