### ISSUE TITLE
Spin off template components into their own package

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#11105]
Wagtail's [template components](https://docs.wagtail.org/en/stable/extending/template_components.html) module has been identified as a good candidate for spinning off into a standalone package - it's proved broadly useful across Wagtail and would be of use to the wider Django ecosystem, and the API has remained mostly stable over the last few releases. Spinning it out into its own package would encourage better separation of concerns, allow it to be better tested and documented, and would generally reduce the "walled garden" effect of Wagtail having its own internal conventions not seen elsewhere.

Further down the line, this could be followed up by releasing the table UI component as another standalone package.

**Comment by tbrlpld** [comment]
Happy to help out here 😄

I have create a [package](https://github.com/tbrlpld/laces) (for now under my user namespace) and pulled the "template component" related code from Wagtail into it. 

This is the PR that adds the code from Wagtail: https://github.com/tbrlpld/laces/pull/3 

@gasman It would be great to get your eyes on the PR to check if that's what your are envisioning. 

Once that PR is merged, I can work on creating a first release and then add a PR to add the package to Wagtail.

**Comment by gasman** [comment]
@tbrlpld That looks like exactly what we're looking for, thanks!

Happy to keep the name. We should transfer it to the @wagtail organisation at some point, but no urgency on that.

Thinking ahead to when we move Wagtail over to use the package - we'll hopefully be able to just add the relevant imports into wagtail.admin.ui.components and wagtail.admin.templatetags.wagtailadmin_tags to keep existing code unchanged (and save people from having to add laces to INSTALLED_APPS in their projects).

**Comment by tbrlpld** [comment]
Thanks @gasman. I will move this forward then and create the release and PR to Wagtail. 

I like that import suggestion 👍 Makes the transition super smooth.
