### ISSUE TITLE
Edit the Documentation on generating new source files for translation in Wiki

### ISSUE THREAD

**Issue by Chiemezuo** [wagtail/wagtail#11114]
### Pertinent section of the Wagtail Wiki

https://github.com/wagtail/wagtail/wiki/Managing-Wagtail-translations#generating-new-source-files-for-translation

![wiki fix](https://github.com/wagtail/wagtail/assets/29470516/7823f409-2ff8-4dc5-9d0e-2ced08029b0d)

### Details

A fix I worked on from another issue needed me to generate new source files for translations. I followed instructions but the command failed. It failed because it was run in the wrong directory. The docs were a bit misleading.
The command is not supposed to be run from within the `scripts` directory, but from its parent; the root directory, because the `rebuild-translation-sources.sh` references a sibling of the `scripts` directory; the `./wagtail` directory.
I think that the 'From `scripts`, run:' should be edited.

**Comment by aditya123473892** [comment]
can i work on this issue

**Comment by aditya123473892** [comment]
i created a pull request in which i changed script with `./wagtail` in the doc pls review it whenever you can its my first pull request so pardon me for any mistake

**Comment by Chiemezuo** [comment]
I'm just a contributor, not a core member of the team. I think it's up to the core team to make a decision on it, and how they might want it to be (or even for it to be left as it is). Also, I didn't quite see your pull request, but `./wagtail` might also be just as misleading.

**Comment by gasman** [comment]
Thanks for reporting, @Chiemezuo! Have now updated the page to say "from the root of the wagtail codebase" instead.

@aditya123473892 I don't see a pull request from you, and in fact this documentation isn't part of the Wagtail code repository (or any other repository), so the pull request process doesn't apply here.

**Comment by aditya123473892** [comment]
ok thanks i understood will work try to work on other issues thanks for guiding

**Comment by Chiemezuo** [comment]
The pleasure is all mine @gasman
