### ISSUE TITLE
Broken checkboxes in MultipleChooserPanel modal when USE_THOUSAND_SEPARATOR is True

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#11134]
Reported by @lucasmoeskops on Slack:

> I have a funny error with a MultipleChooserPanel (Wagtail version 5.0.2). The cell select values are integers but they get printed with thousand separators:
> 
> ```
> <input type="checkbox" id="chooser-modal-select-19,925" data-multiple-choice-select="" name="id" value="19,925" title="Select Don Jose Miguel ...">
> ```
> (this should be pk 19925).

On further investigation, [USE_THOUSAND_SEPARATOR](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-USE_THOUSAND_SEPARATOR) is set to True on this project, so that's presumably the cause.

I think the fix is to add the `|unlocalize` filter to the two occurrences of https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/generic/chooser/checkbox_select_cell.html, similar to what was done elsewhere in #3478.

~I don't think this needs any new tests (since we didn't add them when adding `|unlocalize` previously), but please make sure that the existing tests pass.~ We need tests for this, since it seems there's currently no test coverage for this template at all.

**Comment by codesmith25103** [comment]
Hey @gasman, I have identified the issue and implemented the necessary fix. I am now submitting my code for review.

**Comment by codesmith25103** [comment]
Hey @gasman I have successfully opened pull request. Please merge it.

**Comment by ambiguousphoton** [comment]
Is this Issue still open, or is somebody working on this.. if not can I work on this ?

**Comment by samridhsri** [comment]
Can I work on this issue? Is this open?

**Comment by sastatic** [comment]
claim

**Comment by Reetinder932** [comment]
I have created a pull request please merge it

**Comment by gasman** [comment]
@Reetinder932 Thanks for the contribution, but there's already an existing pull request for this (#11137) as mentioned above, and your version has some problems that have already been addressed there (such as not loading the `l10n` tag library).

For anyone interested in working on this - please use #11137 as your starting point. The remaining task is to add test coverage, as detailed on https://github.com/wagtail/wagtail/pull/11137#issuecomment-1782311428.

**Comment by rohitsrma** [comment]
@gasman I am interested in working on this.

Is it possible to set the page ID to a value greater than 1000 directly?
