### ISSUE TITLE
MutationObserver in dirty form check only tests direct descendants

### ISSUE THREAD

**Issue by SebCorbin** [wagtail/wagtail#11142]
### Issue Summary

I'm in the process of writing a custom widget based on a (very) custom mix of `Chooser` and a Formset-like behavior.
My widget is quite ready and finished but in the process I found something I consider a bug:
 - The form starts being checked 10 seconds after the page being loaded
 - It stores `initialData` and then check every 3sec or 300 or upon keyup or input change
 - It also registers a `MutationObserver` to monitor nodes being removed or added

This lasts one should be triggered by my widget (when adding new lines of inputs for example) but it is not. I'm suggesting the [`validInputNodeInList` check](https://github.com/wagtail/wagtail/blob/0513a78fb5ec4eb02ef5f602fa182eb885e3c787/client/src/entrypoints/admin/core.js#L158) on added or removed nodes to be inputs (INPUT, TEXTAREA or SELECT) should not only check child nodes but use a `querySelectorAll` instead.

If you consider this a bug, I'm willing to do a PR. In the meantime I'm working around this problem by adding an direct INPUT descendant to trigger the check

### Steps to Reproduce

1. Make a widget that adds a div with an input inside
2. Wait 10 sec for a form with this widget to load
3. Trigger addition in your widget
4. The unsaved message should appear

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: 3.10
-   Django version: 4.2
-   Wagtail version: 5.2rc1
-   Browser version: FF118

**Comment by SebCorbin** [comment]
If you consider this a bug, I'm willing to do a PR. In the meantime I'm working around this problem by adding an direct INPUT descendant to trigger the check

**Comment by lb-** [comment]
I think your suggestion makes sense.

**Comment by lb-** [comment]
https://github.com/wagtail/wagtail/pull/11373 has migrated this logic to Stimulus. It's still the same mutation observer under the hood but might make it easier to write unit tests for these edge cases and then some fixes. 

@the-r3aper7 this may be a small next step on improvements, more simple than #7188

**Comment by kituuu** [comment]
I'm working on this.

**Comment by lb-** [comment]
Awesome @kituuu  - add comments to this issue if you have questions about the approach to take.

**Comment by kituuu** [comment]
@lb- Can you describe the issue more? Would you like me to write a unit test for this change only?

**Comment by lb-** [comment]
@SebCorbin  do you mind helping out @kituuu here - do you have a simple widget code snippet that could be used on bakerydemo to reproduce this scenario.

As for the change, the goal is to fix the problem but ensure that we have a unit test covering this case also so it's tracked for future changes.

**Comment by SebCorbin** [comment]
@kituuu in `UnsavedController.ts` 
- you have a `MutationObserver` that is watching added and removed nodes from the DOM tree
- each node is checked by [`isValidInputNode()`](https://github.com/wagtail/wagtail/blob/main/client/src/controllers/UnsavedController.ts#L291) to determine if we should check the form values for changes

This works well when for example single `<input />` are added, but it does not work when they are deeply nested, e.g. `<div><input /></div>` because `isValidInputNode()` will be called on the `div`.

The current unit tests are lacking any check on a modified DOM tree, so we should have:
- `it('should not fire an event when a paragraph is added'` (because that's not an input)
- `it('should fire an event when an input is removed`
- `it('should fire an event when a textarea is added'`
- `it('should fire an event when a select contained in a div is added'`

You can add these to the `describe('checking for edits'` section of `UnsavedController.test.js`

**Comment by kituuu** [comment]
> @kituuu in `UnsavedController.ts`
> 
> * you have a `MutationObserver` that is watching added and removed nodes from the DOM tree
> * each node is checked by [`isValidInputNode()`](https://github.com/wagtail/wagtail/blob/main/client/src/controllers/UnsavedController.ts#L291) to determine if we should check the form values for changes
> 
> This works well when for example single `<input />` are added, but it does not work when they are deeply nested, e.g. `<div><input /></div>` because `isValidInputNode()` will be called on the `div`.
> 
> The current unit tests are lacking any check on a modified DOM tree, so we should have:
> 
> * `it('should not fire an event when a paragraph is added'` (because that's not an input)
> * `it('should fire an event when an input is removed`
> * `it('should fire an event when a textarea is added'`
> * `it('should fire an event when a select contained in a div is added'`
> 
> You can add these to the `describe('checking for edits'` section of `UnsavedController.test.js`

Okay got it.

**Comment by lb-** [comment]
Note. I manually validated this bug when reviewing the PR.
