### ISSUE TITLE
Moving page copies privacy settings which cannot be changed

### ISSUE THREAD

**Issue by rikva** [wagtail/wagtail#11144]
### Issue Summary

This might be a duplicate/subissue of #4277 but I'm not 100% sure. Feel free to close this issue if it is.

### Steps to Reproduce

1. Have Wagtail 5.1.2.
2. Create new page A with privacy setting "logged in users only".
3. On the same level, create second new page B with different privacy setting "password required".
4. Move page B under page A (making page B a child page of page A).
5. Observe that:
  a. When visiting page B, it now requires a logged in user AND a password, so effectively two privacy settings are being enforced.
  b. This behavior cannot be changed.

What I would expect to happen:
  - Privacy settings of page B to be overridden with privacy settings of page A
  - OR both privacy settings being enforced like now, but the ability to change privacy options of page B. 

### Technical details

-   Python version: 3.11.4
-   Django version: 4.2.6
-   Wagtail version: 5.1.2
-   Browser version: irrelevant

**Comment by gasman** [comment]
Thanks for reporting! Yep, I think this the same as #4277.
