### ISSUE TITLE
txt comment email notifications rendering escaped strings into email template.

### ISSUE THREAD

**Issue by richie-blake** [wagtail/wagtail#11143]
### Issue Summary

Comment notifications sent using the updated_comments.txt template are rendering escaped comment and reply text into the email template. 

The offending code is seen here:
```
{% trans "Deleted comments:" %}{% for comment in deleted_comments %}
 - "{{ comment.text|safe }}"
{% endfor %}{% endif %}{% spaceless %}

{% endspaceless %}{% if replied_comments %}

{% trans "New replies:" %}{% for thread in replied_comments %}

  {% trans 'New replies to:' %} "{{ thread.comment.text }}"{% for reply in thread.replies %}
   - "{{ reply.text }}"{% endfor %}{% endfor %}{% endif %}
```

The bottom two lines are outputting reply.text and thread.comment.text without using the "safe" template filter resulting in the content being escaped for display to the user. You'll note that other output in the file does use the "safe" template filter, as seen above in the "Delete comments" code snippet.

### Steps to Reproduce

1. Enabled comment notifications on a page.
2. As one user make a comment. Be sure to include characters that would normally be escaped. e.g. < > '
3. As a second user, reply to that comment. Be sure to include characters that would normally be escaped. e.g. < > '
4. Inspect the sent email and see that these characters are escaped for presentation to the user.

### Technical details

Found on 
- Wagtail version: 4.1.9 - appears, from the code, to be a problem on latest Wagtail versions also.

**Comment by gasman** [comment]
Thanks for the detailed report @richie-blake! Tagging as a good first issue.

**Comment by rohitsrma** [comment]
I can confirm the issue exist. When replying to a comment containing easily escapable characters, the output in the terminal is as follows:

```
Hello rohit,

Testuser has updated comments on "Bread and Circuses".    

New replies:

  New replies to: "good job"
   - "&lt;&gt;&#x27;"

You can edit the page here: http://localhost:8000/admin/pages/68/edit/

Edit your notification preferences here: http://localhost:8000/admin/account/#tab-notifications
```

I will come with a solution for this issue shortly!!

**Comment by lb-** [comment]
Removing good first issue - PR is up now https://github.com/wagtail/wagtail/pull/11147
