### ISSUE TITLE
 Comment not formatted  ,when adding multiline in the comment box 

### ISSUE THREAD

**Issue by elhussienalmasri** [wagtail/wagtail#11171]
### Issue Summary

when write a comment with multiline or some paragraphs in Comment Box ,
after submit the comment , the content not formatted like the user write it .
and this  make the content hard to understand , and some users want their content 
appear like what they write, and
this problem appear clearly when add content with order or unordered list like this Screenshot

![Screenshot1](https://github.com/wagtail/wagtail/assets/90080237/1629bc2c-2e6e-46af-8ffb-dff721d188bc)

### Steps to Reproduce

1.open any Edit page for any  page.
2. write a comment with multiline in the "comment Box".
3. after submit the comment , the content become not formatted like the user write it.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Expected Behavior:
the comment must formatted like the user write it, for user experience , like this

![Screenshot3](https://github.com/wagtail/wagtail/assets/90080237/026d10be-3670-48b6-87f9-a57bbe8c3232)

Current Behavior:
the comment with multiline not formatted like the user write it ,like this 

![Screenshot2](https://github.com/wagtail/wagtail/assets/90080237/52b986cf-15e1-4ed3-a05f-b34a8aa8fafa)

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes 

### Technical details

-   Python version: 3.8.12
-   Django version: 4.0.10
-   Wagtail version:  v5.3a0
-   Browser version: Chrome 119

**Comment by elhussienalmasri** [comment]
please assign this issue for me

**Comment by gasman** [comment]
@elhussienalmasri We don't assign issues (outside of the core team) - if you're happy to work on this, please go ahead.

**Comment by elhussienalmasri** [comment]
Thanks for reply , I already raise a PR , and it contain few changes but it 
solve the issue , and I hope this PR get merged.
