### ISSUE TITLE
`next_url` can end up with the IndexResultsView when searching and then clicking on an action button that receives the `next_url`

### ISSUE THREAD

**Issue by fadedsky** [wagtail/wagtail#11177]
### Issue Summary

While in the page explorer, if I search for a title and then click on an action button, the populated `next_url` includes `/results/` at the end. Action buttons that take the `next_url` includes "Copy," "Delete," and "Unpublish."

### Steps to Reproduce

1. In wagtail admin page explorer, search for a page title
2. In the results, open on of the page's listing buttons
3. Hover over "Copy," you should see `?next=/admin/pages/10000/results/`, in my screenshots you'll see: `https://localhost:7443/admin/pages/43169/copy/?next=%2Fadmin%2Fpages%2F43164%2Fresults%2F`
4. Click "Copy," change the title and slug a bit, and click "Copy this page"
5. I end up on `https://localhost:7443/admin/pages/43164/results/`

My dev screenshots:
<img width="1379" alt="search-then-copy" src="https://github.com/wagtail/wagtail/assets/5419301/a271d5f7-140f-4b04-acc5-7df29b4fc6f1">
<img width="1381" alt="copy-form-page" src="https://github.com/wagtail/wagtail/assets/5419301/fbdd6568-ebdc-43ac-a3ac-f9e4a2f819e4">
<img width="1378" alt="copy-and-delete-success-redirect" src="https://github.com/wagtail/wagtail/assets/5419301/2fd4c799-5ce1-43c5-b520-a52729edea09">
<img width="1382" alt="search-then-delete-button" src="https://github.com/wagtail/wagtail/assets/5419301/cbfb7e5d-8d01-437f-9d3b-3f9fb9691e44">
<img width="1378" alt="delete-copy-confirm" src="https://github.com/wagtail/wagtail/assets/5419301/0d1f56d2-f0f6-490a-bcae-639efb9e7d15">

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-  I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes, in bakerydemo on GitPod

![bakerydemo-search-for-about](https://github.com/wagtail/wagtail/assets/5419301/6ff7629e-5ffd-49df-bbf1-fba236cab372)
![bakerydemo-after-copying](https://github.com/wagtail/wagtail/assets/5419301/ab67c20e-9dfb-4b7d-ba20-b928ee56fb33)

- I also opened a PR: https://github.com/wagtail/wagtail/pull/11175

### Technical details

-   Python version: 3.10.11
-   Django version: 4.2.4
-   Wagtail version: 5.2rc1
-   Browser version: Chrome 119

**Comment by lb-** [comment]
I think #11170 may actually be a more generic fix for this.

**Comment by gasman** [comment]
@lb- I don't think so - if I'm reading right, #11170 is simply adding `next_url` to the add/edit page actions so that they redirect back to the original location, just like move/delete etc do. It won't do anything to address next_url pointing to the wrong thing.

**Comment by lb-** [comment]
Sorry, pushed the wrong button, comment updated now.
