### ISSUE TITLE
Live preview iframe needs a white background

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#11174]
### Issue Summary

When using Wagtail’s live preview iframe, the page’s content can be unreadable if it has no set background color. Here is an example, where the preview page has been changed to not have a set background:

![live-preview-iframe-bg](https://github.com/wagtail/wagtail/assets/877585/563b540e-0ad1-4f98-a27b-5e67f719ff09)

It’s relatively rare for production websites to _not_ define their own background color, but is very common when developers get started with Wagtail (for example as part of a tutorial).

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Turn on the dark theme
3. Go to the live preview

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

Wagtail 5.2 (and below)

**Comment by iansprice** [comment]
Hey all, 

I'm interested in working on this issue, have a simple PR ready to push. Introduced myself on Slack. Thanks!

**Comment by lb-** [comment]
Go for it @iansprice
