### ISSUE TITLE
Picture formats

### ISSUE THREAD

**Issue by Rezyapkin** [wagtail/wagtail#11186]
Doesn't work: 
```
{% picture page.photo format-{avif,jpeg} as tmp_photo %}

{{ tmp_photo.avif.0.url }}
{{ tmp_photo.jpeg.0.url }}
```
Work: 
```
{% picture page.photo format-{avif,jpeg} as tmp_photo %}

{{ tmp_photo.formats.avif.0.url }}
{{ tmp_photo.formats.jpeg.0.url }}
```

**Comment by gasman** [comment]
Thanks for the report, @Rezyapkin!

I take it this is a fix for https://docs.wagtail.org/en/stable/topics/images.html#generating-the-image-as-foo-to-access-individual-properties ?

**Comment by thibaudcolas** [comment]
Thanks @Rezyapkin, indeed the docs refer to a previous draft of the API that never shipped.
