### ISSUE TITLE
Allow to disable ajax-search in generic listings

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#11197]
### Is your proposal related to a problem?

If you use `ModelViewSet` (or anything that uses the [`BaseListingView`](https://github.com/wagtail/wagtail/blob/e16614bce8c2433e012df2d3f60b1dde9465b7de/wagtail/admin/views/generic/base.py#L127) in its default implementation), you get a nice ajax-search out of the box.

Unfortunately, this ajax-search does not work nicely with the export-actions:
The export-actions don't consider anything that has been search with ajax. The browser's location gets changed automatically while you type, that works, but you have to reload the page first before using the export links (where the url does not change automatically).

Of course, this could be fixed, but I think there is always a chance that some custom features won't work with the ajax-search. So it would be nice if it could be disabled per `View`/`ModelViewSet` programmatically.

There seems to be a way already to disable the async functionality (or some specific parts) here:
https://github.com/wagtail/wagtail/blob/e16614bce8c2433e012df2d3f60b1dde9465b7de/wagtail/admin/templates/wagtailadmin/shared/header.html#L47-L70

I don't know if this is a bug or not, but when disabling it for a `ModelViewSet` (by overriding the index template to pass `search_disable_async` to the include of the header.html), the search does not work at all, because the `<div class="visuallyhidden"><input disabled type="submit" aria-hidden="true"/></div>` (see line [65](https://github.com/wagtail/wagtail/blob/e16614bce8c2433e012df2d3f60b1dde9465b7de/wagtail/admin/templates/wagtailadmin/shared/header.html#L65) above) blocks the "Enter"-button to work.

### Describe the solution you'd like

If the above issue with `search_disable_async` is a bug, a simple solution would be to also hide the disabled submit-button, when `search_disable_async` is set. But I'm not really sure if that may has some implications on the code that uses this feature (e.g. the [chooser](https://github.com/wagtail/wagtail/blob/e16614bce8c2433e012df2d3f60b1dde9465b7de/wagtail/admin/templates/wagtailadmin/chooser/browse.html#L8)).

With this, disabling the functionality is not the easiest, since you have to duplicate the view's template only to pass the `search_disable_async` to the header.html, but it would work. An enhancement to this would be to pass some class/instance variable to the template, which allows to disable the ajax-search on the python/View/ViewSet-level.

**Comment by lb-** [comment]
Good call on the hidden submit buttons, I'm quite sure those should only be there **if** we are using the Async search.

Using a simple / manual search should allow submitting with `enter`.

**Comment by th3hamm0r** [comment]
Fyi: I've quickly tried to hide the submit buttons with the same check `{% if not search_disable_async %}` in a demo project.

The only usage of the `search_disable_async=True` in Wagtail is the [`browse.html`](https://github.com/wagtail/wagtail/blob/845a2acb365241643c2f453e4b962a586ae5e713/wagtail/admin/templates/wagtailadmin/chooser/browse.html#L8), which is used by the page-chooser.

Unfortunately, it now produces an xhr-request (which has been prevented by the disabled submit-button) and a javascript error, when hitting enter in the search-box of the chooser. So this probably requires changes there too, as the chooser seems to disable the default js-search, but uses a custom js-search which also depends on those buttons.

One quick fix would be to add an additional argument to the template, to hide the submit buttons separately. But this seems not very clean to me.
I'm questioning, why the async code needs those buttons (especially the disabled one), instead of just preventing the form-submission by JS, but I'm not an expert in wagtail's frontend and specifically the accessibility topic, so there may be obvious reasons.

**Comment by th3hamm0r** [comment]
With 6.0, the export buttons now work with the ajax search/filter too (https://github.com/wagtail/wagtail/pull/11522). Looking on how it has been implemented with the new `LinkController` in JS, this could be applied to other cases as well, so I don't see the need to be able to disable the ajax-search for now.
