### ISSUE TITLE
Search no longer respects `fields` parameter

### ISSUE THREAD

**Issue by scott-8** [wagtail/wagtail#11208]
### Issue Summary

As shown [here](https://docs.wagtail.org/en/stable/topics/search/searching.html#specifying-the-fields-to-search), the `search` function lets the user specify which fields to search on. 

If any `boost` parameter is specified in `index.SearchField`, all fields are searched even if you specify a limited subset. This seems to be a regression after [this PR](https://github.com/wagtail/wagtail/pull/10653). The query compiler adds a [combined field](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/copy-to.html) with a name similar to `_all_text_boost_2` to each query, even if the `fields` parameter was used. This boosted field contains data from every field, so in effect all fields are searched.

An example of what the compiled query looks like exists in the tests [here](https://github.com/wagtail/wagtail/blob/5cf37f3a9dd586f1a1a86e831bae0a6f1eff2b3b/wagtail/search/tests/test_elasticsearch7_backend.py#L350). I'm not sure that `_all_text_boost_2_0^2.0` and `_all_text_boost_10_0^10.0` should be in this test.

I'm not sure what the intended behavior is. If the goal is only to have `boost` apply when searching all fields, you could only add these boosted fields when `fields` is not specified. Otherwise I think a different way of adding the boost is necessary ([this issue](https://github.com/wagtail/wagtail/issues/5422#issuecomment-645435567)).

I found this issue using the ElasicSearch7 backed. I'm not sure if it applies to database backends. I did not have this issue after removing all `boost` parameters from the models.

### Steps to Reproduce

1. Start a new project and setup ElasicSearch as the search backend. Create a model `Model` with 2 searchable fields, `title` and `author`.
2. Create a dummy entry, such as `Model(title="Title", author="Author"). 
3. Index the data
4. Run the following searches. This is the correct behavior.
```python
backend.search("Title", qs)  # 1 result
backend.search("Author", qs)  # 1 result
backend.search("Title", qs, fields=["author"])  # 0 results
backend.search("Author", qs, fields=["title"])  # 0 results
```
5. Add a `boost` parameter to each searchable field in `Model`
6. Re-index the data
7. Run the following code. This behavior is incorrect.
```python
backend.search("Title", qs)  # 1 result
backend.search("Author", qs)  # 1 result
backend.search("Title", qs, fields=["author"])  # 1 result, should be 0
backend.search("Author", qs, fields=["title"])  # 1 result, should be 0
```

### Technical details

-   Python version: 3.10
-   Django version: 4.2.7
-   Wagtail version: 5.2
-   Browser version: N/A

**Comment by gasman** [comment]
@scott-8 Thanks for the report and the detailed investigation! Can confirm I'm seeing the same issue.

**Comment by gasman** [comment]
PR created: #11216 

@scott-8 Sure, a `fields` parameter on those classes sounds like a worthwhile addition! I suspect that the database backends are a long way from being able to support that, but I think it's fine for different backends to be at varying levels of feature-completeness.
