### ISSUE TITLE
Translatable snippets history view breaks with 'Cannot resolve keyword 'locale' into field'.

### ISSUE THREAD

**Issue by happygrizzly** [wagtail/wagtail#11206]
### Issue Summary

Translatable snippet models history view breaks upon navigating with the exception message:

> FieldError at /admin/snippets/[YOUR_APP_NAME]/[YOUR_MODEL_NAME]/history/1/ 
> Cannot resolve keyword 'locale' into field. Choices are: action, content_changed, content_type, content_type_id, data, deleted, id, label, object_id, revision, revision_id, timestamp, user, user_id, uuid
> **Request Method**: GET
> **Request URL**: http://localhost:5080/admin/snippets/[YOUR_APP_NAME]/[YOUR_MODEL_NAME]/history/1/
> **Django Version**: 4.2.7
> **Exception Type**: FieldError
> **Exception Location**:  [YOUR_PROJECT_PATH]\venv\lib\site-packages\django\db\models\sql\query.py, line 1724, in names_to_path
> **Raised during**: wagtail.snippets.views.snippets.HistoryView

### Steps to Reproduce

1. Create a starter wagtail project (windows/linux)
2. Add `wagtail.contrib.simple_translation`, `wagtail.locales` to the base settings
3. Add `WAGTAIL_I18N_ENABLED = True` and several languages of your choice as `LANGUAGES` / `WAGTAIL_CONTENT_LANGUAGES`. 
4. Add a snippet model of your liking and extend it with the mixins: `WorkflowMixin`, `PreviewableMixin`, `DraftStateMixin`, `RevisionMixin`, `TranslatableMixin`.
5. Make / apply migrations, create super user.
6. In the admin check the **Settings > Locales** if at least one locale is activated. In my case it's just the default 'en-US'.
7. Create an instance of your snippet and publish it.
8. Navigate back to the instance's editor and try opening the history panel.

Here's a small repo with the `Recipe` snippet: https://github.com/happygrizzly/wt_translated_snippets_history_issue.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes.

### Technical details

-   Python version: 3.11.4 / 3.10.
-   Django version: 4.2.7.
-   Wagtail version: 5.2.
-   Browser version: Latest Firefox, Edge, Chrome.

**Comment by laymonage** [comment]
Thank you! I can confirm this issue using bakerydemo and accessing the History view for the `FooterText` snippet.

Seems to be a regression in dc049cd.
