### ISSUE TITLE
Dynamically set action_url for adding a new item in snippet index.html

### ISSUE THREAD

**Issue by bezidejni** [wagtail/wagtail#11218]
### Is your proposal related to a problem?
Hey folks!

On a project I needed to pass some GET query parameters from the snippet index view to the snippet create view, based on the current value of the filter, to prefill an initial value on the snippet create form.

Right now, the action_url value is being set [here](https://github.com/wagtail/wagtail/blob/main/wagtail/snippets/templates/wagtailsnippets/snippets/index.html#L17), meaning that it takes a static parameter from the view. 

The only option I see is to fully override the `index.html` template by extending the base one, copying the whole `content` block and setting the desired value.

### Describe the solution you'd like

Ideally, we wouldn't take the static value, but instead use [get_add_url()](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/generic/models.py#L378C5-L378C5) here which we can override in a custom `IndexView`. This seems easier than overriding basically the whole template, and is already being done in generic views. ([view](https://github.com/wagtail/wagtail/blob/af1ce3ff88ff8c906470d3a9a6a2e8bf9d68b59b/wagtail/admin/views/generic/models.py#L482), [template](https://github.com/wagtail/wagtail/blob/af1ce3ff88ff8c906470d3a9a6a2e8bf9d68b59b/wagtail/admin/templates/wagtailadmin/generic/index.html#L10))

Is there a reason why the behavior is different in those two cases?

### Describe alternatives you've considered

As I mentioned above, overriding the template seems like the only way to do it.

### Additional context

If we agree that this is something that should be changed in the future, I could potentially take on the work of doing so and creating a PR, if you want me to.

**Comment by laymonage** [comment]
Hi, thank you for the report. This seems like what #11133 aims to fix.

> Is there a reason why the behavior is different in those two cases?

I don't think there's a specific reason. The view was gradually migrated over from a function based view to a class-based view, from using its own template, to extending the generic views' templates. It's likely this just wasn't picked up in the process 🙂

**Comment by bezidejni** [comment]
I agree, it does seem like it's the same thing. My bad, I searched for `get_add_url` in issues, but not in pull requests as well. I think that this can be closed, thanks for the quick reply!
