### ISSUE TITLE
 Starter tutorial doesn't explain what to do when SQLite does not support JSONFields

### ISSUE THREAD

**Issue by rob-sullivan** [wagtail/wagtail#11241]
### Pertinent section of the Wagtail docs

- [ Your first Wagtail site](https://docs.wagtail.org/en/stable/getting_started/tutorial.html)

- [Create the database](https://docs.wagtail.org/en/stable/getting_started/tutorial.html#create-the-database)

### Details

The starter tutorial doesn't explain what to do when SQLite does not support JSONFields and users will be hit with this error message. This [article](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.JSONField) mentions for using JSONField with Django 3.1+ and sqlite, the JSON1 sqlite extension must be installed.

```bash
pip install -r requirements.txt
python manage.py migrate
SystemCheckError: System check identified some issues:

ERRORS:
wagtailcore.ModelLogEntry: (fields.E180) SQLite does not support JSONFields.
wagtailcore.PageLogEntry: (fields.E180) SQLite does not support JSONFields.
wagtailcore.Revision: (fields.E180) SQLite does not support JSONFields.
wagtailforms.FormSubmission: (fields.E180) SQLite does not support JSONFields.
wagtailusers.UserProfile: (fields.E180) SQLite does not support JSONFields.
```

**Comment by lb-** [comment]
Here's the relevant release notes and readme section that does call this out. 

https://docs.wagtail.org/en/stable/releases/3.0.html#sqlite-now-requires-the-json1-extension-enabled
https://github.com/wagtail/wagtail#-compatibility

See https://code.djangoproject.com/wiki/JSON1Extension for info on what should have this set up by default and how to install if not.

But it's interesting it needs explicit installation on your set up, my understanding was that most environments would not need this. Can you explain the environment you are using? Python version, OS and any other useful info.

**Comment by anshikavashistha** [comment]
I want to work on this issue.Please assign this to me @lb-

**Comment by lb-** [comment]
@rob-sullivan are you able to give some more information about your environment/setup.

@anshikavashistha - I am not sure where we would want to put this info yet, as noted above it's already listed on the Readme and is part of Django docs. We could duplicate this table in the docs but then it would need to be kept in sync manually.

For now I think this may need a core team quick discussion (I will add a label for this).

**Comment by rob-sullivan** [comment]
Hi @lb- sorry for the delay in reply. Thanks very much for looking into this. Hopefully it is just a _me_ problem.

See the steps I followed, environment setup and logs (attached) of terminal output:

Following [Build your first site](https://docs.wagtail.org/en/stable/getting_started/tutorial.html).

Environment:
```
ASUS Laptop x64 based, model GL502VMK
Intel i7
Nividia GeForce GTX 1060

Windows 10 Home version 10.0.1

Visual Studio Code
Version: 1.84.2
```
Tutorial Steps:
```bash
# inside vs code
python --version
# output: Python 3.8.0
python -m venv venv_wt
.\venv_wt\Scripts\activate
# inside python environment
pip install wagtail
# log saved to wagtail_pip_install_log.txt
mkdir blog
wagtail start blog blog
# Success! blog has been created
cd ./blog/
pip install -r requirements.txt
#log saved to wagtail_pip_install_requirements.txt
python manage.py migrate
#SystemCheckError: SQLite does not support JSONFields
```
[wagtail_pip_install_log.txt](https://github.com/wagtail/wagtail/files/13439267/wagtail_pip_install_log.txt)
[wagtail_pip_install_requirements.txt](https://github.com/wagtail/wagtail/files/13439268/wagtail_pip_install_requirements.txt)
[wagtail_systemcheck_error.txt](https://github.com/wagtail/wagtail/files/13439269/wagtail_systemcheck_error.txt)

**Comment by laymonage** [comment]
Ah, OK. So, the SQLite bundled in Python on Windows did not include the JSON1 extension until python/cpython@58d6f2ee3aeb699156d4784acccd2910d27982e7 (Python 3.9).

If we want to add a warning, the Quick install guide's "Common quick install issues" section seems like a good fit: https://docs.wagtail.org/en/stable/getting_started/quick_install.html#common-quick-install-issues

Although I think it would be great if we also have a Databases section somewhere in the docs where we talk about compatibility, e.g. after the Django/Python compatibility table https://docs.wagtail.org/en/stable/releases/upgrading.html#compatible-django-python-versions

That would also be a place to add details on e.g. us not supporting Oracle Database, or multiple database setups (#11237).

**Comment by anshikavashistha** [comment]
@lb- sure No problem.I want to contribute to Wagtail.Could you please suggest me some beginner friendly issues nd contributions?

**Comment by lb-** [comment]
@anshikavashistha this issue should be good now, see the above comment from @laymonage 

I think this approach makes sense, just add an item to the common quick install issues.

As for the databases section, I think we can cover that in a different issue.

**Comment by rob-sullivan** [comment]
Are actions added yet to common quick install issues related to resolving
this?

What can I do to resolve, manually install update?

**Comment by lb-** [comment]
@rob-sullivan sorry if it was not clear from my messages above.

You will need to follow the Windows specific instructions here https://code.djangoproject.com/wiki/JSON1Extension

> [As of Python 3.9](https://github.com/python/cpython/commit/58d6f2ee3aeb699156d4784acccd2910d27982e7), the official Python installer on Windows already includes the JSON1 extension by default. If you're using an earlier version of Python or unofficial installers, you can do the following:
>  *   Download the [precompiled DLL](https://www.sqlite.org/download.html) that matches your Python installation (32-bit or 64-bit).
> *    Locate your Python installation. By default, it should be in %localappdata%\Programs\Python\PythonXX, where XX is the Python version. For example, it's located in C:\Users\<username>\AppData\Local\Programs\Python\Python37. If you added Python installation directory to your PATH environment variable, you can run the command where python on a command prompt to locate it.
> *   Enter the DLLs directory in your Python installation.
>  *    Rename (or delete) sqlite3.dll inside the DLLs directory.
>  *   Extract sqlite3.dll from the downloaded DLL archive and put it in the DLLs directory.
> *    Now, the JSON1 extension should be ready to be used in Python and Django.

**Comment by rob-sullivan** [comment]
Ahw ok thanks @lb- for the help. I needed an older version of python due to other projects. If you want I can make a PR, update the issues section of docs and if whomever is reviewing is happy you can merge.

**Comment by anshikavashistha** [comment]
@lb-  Thank you for the response
I will keep an eye on this issue and will start working on it
