### ISSUE TITLE
Document how to create pages on tests

### ISSUE THREAD

**Issue by maribedran** [wagtail/wagtail#11244]
### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/stable/advanced_topics/testing.html#testing-reference

(Insert the permalink of the section heading in the Wagtail docs. Choose the most specific section / lowest-level heading to which your suggested change would apply. (In the docs, hover over the heading to see the permalink icon.))

### Details

 The docs section about testing shows how to use `WagtailPageTestCase`, but omits the actual creation of the page on the test case setup. I had to do some research to figure out how to create a page and set content to its stream field. Here's how my tests are looking now:

```python
from model_bakery import baker
from wagtail.models import Page, Site
from wagtail.rich_text import RichText
from wagtail.test.utils import WagtailPageTestCase

from authentication.models import User
from home.models import HomePage
from publication.models import Article, Author, PaywallType
from subscription.models import Subscription


class ArticlePageTest(WagtailPageTestCase):
    @classmethod
    def setUpTestData(cls):
        root = Page.get_first_root_node()
        home = HomePage(title="Home")
        root.add_child(instance=home)
        Site.objects.create(
            hostname="testserver",
            root_page=root,
            is_default_site=True,
            site_name="testserver",
        )
        cls.subscription_1 = baker.make(Subscription)
        cls.subscription_2 = baker.make(Subscription)
        cls.author = baker.make(Author, user__is_staff=True)
        cls.article = Article(
            title="Article",
            slug="article",
            publication=cls.subscription_1,
            author=cls.author,
            excerpt="AAA",
            paywall=PaywallType.DISABLED,
        )
        home.add_child(instance=cls.article)
        cls.article.subscriptions.add(cls.subscription_2)
        cls.article.content.extend(
            [
                ("paragraph", RichText("<p>First paragraph</p>")),
                ("paragraph", RichText("<p>Second paragraph</p>")),
                ("paragraph", RichText("<p>Third paragraph</p>")),
            ]
        )
        cls.article.save()
        cls.user = baker.make(User)

    def test_get(self):
        response = self.client.get(self.article.url)
        self.assertEqual(response.status_code, 200)

    def test_anonymous_user_can_see_content_without_paywall(self):
        response = self.client.get(self.article.url)
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "<p>First paragraph</p>")
        self.assertContains(response, "<p>Second paragraph</p>")
        self.assertContains(response, "<p>Third paragraph</p>")

    def test_anonymous_user_can_only_see_teaser_with_teaser_paywall(self):
        self.article.paywall = PaywallType.TEASER
        self.article.save()
        response = self.client.get(self.article.url)
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "<p>First paragraph</p>")
        self.assertNotContains(response, "<p>Second paragraph</p>")
        self.assertNotContains(response, "<p>Third paragraph</p>")
```

This isn't a super complex test and the use case it covers is probably similar to what you would find in other applications: some business logic changes what shows up on the page depending on some state and the user that's logged in. It took me a while and some reading to figure out a few things to make this work.
- A Page can't be created with `MyPage.objects.create()` as you would expect from a Django model. This information is somewhere on the docs, but if you go directly to the testing docs you'll likely miss it.
- You have to create the entire page tree from the root and add pages to their parents. Same issues as noted above.
- The site has to be created with the right hostname and the root page.
- When testing a page you probably want content in it. Adding stream field content is also not obvious and it's not documented near the testing topic.

I'll open a PR with a smaller test example, but I'm not sure what would be the best place to put this. Maybe it could be another section of the testing page called "Creating Page objects for tests". Better title suggestions would be great.

**Comment by thibaudcolas** [comment]
Thank you @maribedran, "Creating Page objects for tests" sounds like a great section title to me until someone can think of a better one. Or we can use that forever and ever.

Possibly related: #10628.

IMHO the [testing page](https://github.com/wagtail/wagtail/blob/main/docs/advanced_topics/testing.md) is definitely the right one, and I think it matters more that we add this information, than thinking of the best information architecture possible.

**Comment by maribedran** [comment]
I'd still like to add examples for creating images and docs, but I'll have to find out how to do it.
