### ISSUE TITLE
Easily override the Settings -> Users display table

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#11255]
### Is your proposal related to a problem?

We have a custom user model where we have different fields than the default Django AbstractBaseUser class as well as reverse-name fields from related model(s). I need to display the custom fields, property method(s), and values from related models in the Wagtail Admin Settings -> Users display.

When [asking on StackOverflow](https://stackoverflow.com/questions/77490288/how-to-customize-the-wagtail-admin-settings-users-list-view-admin-users/77490622#77490622), I was advised to [create a template HTML and copy/paste the code from the Wagtail internal templates to make my changes](https://stackoverflow.com/a/77490622/1191545). While this is pragmatic, it would lead to a flaky solution where our temlpate markup would be frozen in time at the point where I copy pasted the code.

### Describe the solution you'd like

It would be useful to be able to use something like `wagtail_hooks` to override the Settings -> Users listing to specify our custom model as well as specific model fields, property methods, and related fields to be displayed in the UI.

### Describe alternatives you've considered

I am still considering the StackOverflow suggestion, but it doesn't seem ideal. Alternatively, I can define a `ModelAdmin` view for the Users, but `ModelAdmin` is slated for deprecation and that view would be a bit confusing to admin users who would wonder why we have two places to manage users.

**Comment by brylie** [comment]
One use-case that came up is:

> How can we add an export button on the Users table and define `list_export` columns for the Users listing?

We need to compare registered user emails against a list of active subscriptions in a workflow outside of Wagtail, so we would like to export some user details as a spreadsheet.

**Comment by laymonage** [comment]
This will be possible once #11952 is merged.

**Comment by gasman** [comment]
Fixed in #11952
