### ISSUE TITLE
UI for first_published_at

### ISSUE THREAD

**Issue by chrxr** [wagtail/wagtail#1126]

**Comment by miltontony** [comment]
Hi guys, any tips on ways to make `first_published_at` editable? We're using it for ordering, but the editors have no way of changing it.

**Comment by nadersoliman** [comment]
@miltontony have you found a solution for this? Our content editors would like to control the publish date as they are moving content from another website.

**Comment by miltontony** [comment]
@nadersoliman not quite..we've kinda just left it.

**Comment by gasman** [comment]
Have discussed amongst the core team, and have no objections to making this editable (possibly in the 'settings' tab).

**Comment by nikolaik** [comment]
Would love to see this. Our use case is manually migrating old content (articles) from an existing CMS to wagtail.

**Comment by khink** [comment]
starting work (wagtail space sprint, ticket destroyer team)

**Comment by lb-** [comment]
cleaning up labels, removed some older ones, looks like this approach has been agreed on in general.
Adding good first issue.

**Comment by lb-** [comment]
Sounds good. Thanks
