### ISSUE TITLE
OrderByFieldError: Cannot sort search results with field "page_ptr". Please add index.FilterField('page_ptr')

### ISSUE THREAD

**Issue by madatbay** [wagtail/wagtail#11263]
### Issue Summary
I'm getting the error below when trying to both search and order queryset in wagtail admin.

wagtail.search.backends.base.OrderByFieldError: Cannot sort search results with field "page_ptr". Please add index.FilterField('page_ptr') to Article.search_fields.
I've already added index.FilterField('page_ptr') to my model, but still getting that error. I can see it in search fields of my model:

 ...
 <SearchField: short_description>,
 <wagtail.search.index.RelatedFields at 0xffff922eb730>,
 <wagtail.search.index.RelatedFields at 0xffff922eb5b0>,
 <wagtail.search.index.RelatedFields at 0xffff922eb490>,
 <FilterField: page_ptr>]

### Steps to Reproduce
1. Order column in cms
2. Search any keyword in searchbar
3. 
### Technical details

-   Python version: 3.9.
-   Django version: 3.2.11.
-   Wagtail version: 2.16.3
-   Browser version: Chrome 119

**Comment by gasman** [comment]
Hi @madatbay - thanks for the report. Unfortunately this doesn't give us enough information to handle this as a bug report - we need to know specific steps that will reproduce this error starting from a fresh Wagtail instance.

Also, support for Wagtail 2.16 ended in May 2022 - please upgrade to a current version.
