### ISSUE TITLE
System checks for content/promote panel definitions

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#1127]
A couple of system checks to make sure that all panels point to a field/child relation that exists would be really handy.

**Comment by lb-** [comment]
Adding notes for anyone looking at this (+ marking as good first issue).

* See the docs for the Django system check framework https://docs.djangoproject.com/en/4.0/topics/checks/
* Checks can exist on a model and also app wide
* We would likely want to scope these checks at the app wide level so we can pick up `edit_handler` usage across any models, not just pages
* We already have some similar checks here https://github.com/wagtail/wagtail/blob/stable/2.16.x/wagtail/admin/checks.py#L94
* A good reference is the `check_stream_field_panel_type` function in this file, it checks that any `StreamField` fields also have used the `StreamFieldPanel` in the edit_handlers

Rough idea of how we could do this below

```
def traverse_edit_handlers(edit_handler):
    errors = []

    try:
        for child in edit_handler.children:
            errors += traverse_edit_handlers(child)
    except AttributeError:
        # new code from here
        stream_field_panel_error = check_stream_field_panel_type(edit_handler)
        if stream_field_panel_error:
            errors.append(stream_field_panel_error)
        panels_have_field_error = some_new_check_function(edit_handler)
    return errors
```

**Comment by sandilsranasinghe** [comment]
Shall I take a look at this? Is there anything that should be specifically included in the error message?

**Comment by lb-** [comment]
Nothing specific I can think of, have a read of the messages in the linked file above `wagtail/admin/checks.py` and base the messaging off that.

**Comment by bilalshaikh292** [comment]
Hello, Can i work on this issue. Thers arent any PRs so if its possible can i try this one?

**Comment by gasman** [comment]
@bilalshaikh292 See the link above - I think #8258 covers this already.

**Comment by ArijeetBanerjee** [comment]
I want to work on this issue. kindly give me permission and access to work on this issue

**Comment by Aym-n** [comment]
@gasman is this issue already been resolved?

**Comment by ArijeetBanerjee** [comment]
Hey there 
It would be an honor to work in this issue
If it is still available, I'd be glad to work in it

**Comment by lb-** [comment]
If anyone is keen to pick up this issue, the PR https://github.com/wagtail/wagtail/pull/8258 has a review now. The code is a good start but needs to be done again on the latest `main` branch.

**Comment by NXPY123** [comment]
I am working on reviewing the PR and making changes to it accordingly

**Comment by lb-** [comment]
OK after a fresh round of digging, I actually think this may not be required.

I should have re-validated this before flagging this as ready to work on but I think the FieldPanel and nested Panels now fully check for fields that do not exist.

Example errors
> django.core.exceptions.FieldError: Unknown field(s) (job_title_x) specified for Person (FieldPanel)
> AttributeError: type object 'LocationPage' has no attribute 'hours_of_operationS' (InlinePanel)


@gasman - do you think these checks are needed, now that we seem to throw errors when there are missing links to fields in all our panels.

**Comment by lb-** [comment]
After reviewing again I think we can close this issue as not required, if there is something I have missed in terms of the existing FieldPanel errors not being sufficient or supporting some cases we can re-open this issue or raise a new one.

Sorry for the confusion @NXPY123  - probably always a good call out to see if the problem/goal is still valid before we get started on a new solution. Thank you for redoing that PR though, it's really appreciated, maybe that checks knowledge will come in handy in the future.

**Comment by NXPY123** [comment]
Yeah my bad I'll keep that in mind next time. Was really useful in helping me get started on the repo though ✌️
