### ISSUE TITLE
Provide a robust way to add extra buttons to the snippet index header

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#11275]
### Is your proposal related to a problem?

It's sometimes desirable for a Wagtail project or add-on package to insert extra buttons in the header of the index view, as in this example from [wagtail-airtable](https://github.com/wagtail-nest/wagtail-airtable/):

<img width="691" alt="Screenshot 2023-11-23 at 20 30 25" src="https://github.com/wagtail/wagtail/assets/85097/7f80e202-95b8-47b4-8f12-85ec83b3f37a">

In wagtail-airtable, this is done by [overriding the template](https://docs.djangoproject.com/en/stable/howto/overriding-templates/) for this index view - [wagtailsnippets/snippets/index.html](https://github.com/wagtail-nest/wagtail-airtable/blob/107a1d9358a42abda2afd519e50c5bac5a76d2c1/wagtail_airtable/templates/wagtailsnippets/snippets/index.html). (Note: this links to the PR https://github.com/wagtail-nest/wagtail-airtable/pull/56/, which has not yet been merged at the time of writing - if you look at the wagtail-airtable repo right now, you'll see this being applied to wagtailsnippets/snippets/type_index.html instead, which was the equivalent template in Wagtail 4.x.)

As seen in that template, the only way to do this is to replicate the entire `{% block content %}...{% endblock %}` from Wagtail's own template, and make the change within there. This is very fragile - this template is liable to change between Wagtail releases, and when it does, the customisation will break and need to be fixed.

### Describe the solution you'd like

I think that all that's needed is a new block inside the `extra_actions` fragment:

```diff
    {% fragment as extra_actions %}
+        {% block extra_actions %}
            {% if view.list_export %}
                {% include view.export_buttons_template_name %}
            {% endif %}
+        {% endblock %}
    {% endfragment %}
```

With this in place, the template override for adding a button should be as simple as:

```
{% extends "wagtailsnippets/snippets/index.html" %}
{% block extra_actions %}
    {{ block.super }}
    <a href="https://example.com" class="button">Click me</a>
{% endblock %}
```

**To anyone wishing to pick up this issue:** Before opening a PR, please test this out on a Wagtail project (such as the bakery demo project) - beyond that, I don't think any unit tests or documentation will be required. If you include a screenshot showing it in action as part of your PR description, even better 👍

**Comment by rohitsrma** [comment]
I would like to work on this!

**Comment by rohitsrma** [comment]
![image](https://github.com/wagtail/wagtail/assets/111359305/517b993e-7235-496e-be40-e55f26bc7b65)

The suggested approach works very well. I'm not creating a PR since there is already one up!
