### ISSUE TITLE
Remove need for inline scripts to enable commenting client-side

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#11287]
### Is your proposal related to a problem?

Currently we expose a global `window.comments` and use this to initialise the commenting JS. This forces us and other developers to lean towards inline scripts when needing to leverage the commenting UI.

However, we should instead support this behaviour through DOM events and make it easier to instantiate without globals.

### Describe the solution you'd like

The inline JS we want to replace is this part in both [`edit.html`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/pages/edit.html) and [`create.html`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/pages/create.html).

```
    <script>
       // ...
            {% get_comments_enabled as comments_enabled %}
            {% if comments_enabled %}
                // Initialise comments UI
                window.comments.initCommentsInterface(document.getElementById('page-edit-form'));
            {% endif %}
        });
    </script>
```

Observe above, we are checking if the comments are enabled then call a global with an inline script. This approach will not be compliant for CSP.

#### 1. Create an event listener for initialising comments

Something like this could do the job, we basically keep the global exposed (for now) but let it be called via an event.

```js
# client/src/entrypoints/admin/comments.js
# ...
  document.addEventListener('w-init:init', ({ target }) => {
    initCommentsInterface(target);
  });

  return {
    commentApp,
    getContentPath,
    isCommentShortcut,
    initAddCommentButton,
    initCommentsInterface,
  };
})();
```

#### 2. Support an arbitrary event name prefix for `w-init` controller

We need a way to dispatch this custom event name easily with Stimulus, we already have a controller that gets is 95% of the way there. `w-init` will dispatch an event against a DOM element as soon as the DOM is available.

We would need to modify this to accept a way to change the event name, by default this will be `w-init:ready`.

Something like below should get us close (not tested), unit tests would need to be added of course.

```diff
export class InitController extends Controller<HTMLElement> {
  static classes = ['ready', 'remove'];

  static values = {
    delay: { default: -1, type: Number },
+    event: { default: '', type: String },
  };

  declare readonly readyClasses: string[];
  declare readonly removeClasses: string[];

  declare delayValue: number;
+  declare eventValue: string;

  connect() {
    this.ready();
  }

  /**
   * Add the ready classes and remove the remove classes after a delay.
   * By default, the action will be immediate (negative value).
   * Even when immediate, allow for a microtask delay to allow for other
   * controllers to connect, then do any updates do classes/dispatch events.
   */
  ready() {
    const delayValue = this.delayValue;

    debounce(() => true, delayValue < 0 ? null : delayValue)().then(() => {
      this.element.classList.add(...this.readyClasses);
      this.element.classList.remove(...this.removeClasses);
-      this.dispatch('ready', { bubbles: true, cancelable: false });
+      this.events.forEach(([eventName, options]) => {
+        this.dispatch(eventName, options);
+      });
      this.remove();
    });
  }

// ... remove method

  /**
   * Parse event names from the event value or default to 'ready'.
   * If custom event name(s) have been provided, ensure we do not use
   * the prefix for these.
   */
  get events() {
    const event = this.eventValue;

    const eventNames = event
      ? event
          .split(' ')
          .map((str) => str.trim())
          .filter(Boolean)
      : [null];

    return eventNames.map((eventName) => [
      eventName || 'ready',
      { bubbles: true, cancelable: false, ...(eventName && { prefix: '' }) },
    ]);
  }
}
```

#### 3. Finally, remove the inline script & use the HTML attributes

This is from the create.html but would be similar for the edit.html. We can remove the `window.comments.initCommentsInterface` global and instead add two HTML attributes.

```
{% if comments_enabled %}data-controller="w-init" data-w-init-event-value="w-comments:init"{% endif %}
```

This will make the event dispatch on load with `w-comments:ready`.

```html

{% block content %}

    {% include 'wagtailadmin/shared/headers/page_create_header.html' %}

    {% get_comments_enabled as comments_enabled %}

    <form id="page-edit-form" action="{% url 'wagtailadmin_pages:add' content_type.app_label content_type.model parent_page.id %}" method="POST" novalidate{% if form.is_multipart %} enctype="multipart/form-data"{% endif %} data-edit-form{% if comments_enabled %}data-controller="w-init" data-w-init-event-value="w-comments:init"{% endif %}>
        {% csrf_token %}
# ...
```

### Describe alternatives you've considered

- We may want to abstract the comments into a full controller and avoid the entire need for the comments global. However, this would be a huge change and is unlikely to be a big priority.

### Additional context

- This will help us towards the CSP goals https://github.com/wagtail/wagtail/issues/1288
- This will further bolster our usage of Stimulus, making our controllers more useful https://github.com/wagtail/rfcs/pull/78

**Comment by disconnect821** [comment]
I would like to give this a shot, working on it

**Comment by disconnect821** [comment]
@disconnect821 let me know if you need any help on this one.

**Comment by salty-ivy** [comment]
@disconnect821 let me know if you need any help on this one

**Comment by salty-ivy** [comment]
@sivangbagri we don't usually assign issues to anyone rather than core team members at the moment regardless, @disconnect821 is already working on it perhaps you should confront him first just to avoid duplication of efforts.

**Comment by disconnect821** [comment]
@lb got it, thanks for the quick updates and letting me know, on it.
