### ISSUE TITLE
Show the version of Wagtail being run in the Wagtail Admin all the time—not just when there's newer versions out

### ISSUE THREAD

**Issue by nutjob4life** [wagtail/wagtail#11280]
### Is your proposal related to a problem?

Yes, it's related to a problem—but a minor problem, to be sure. Really low priority.

I manage a fair number of Wagtail sites; some run on hosts and some in containers. Configurations vary. It'd be nice to know what version of Wagtail is running where.

I can get that information when there's a new version of Wagtail:

<img width="600" alt="Wagtail upgrade available. Your version: 5.2. New version: 5.2.1" src="https://github.com/wagtail/wagtail/assets/814813/5f52621b-235c-432f-ad5e-da3fe9cbc168">

But it'd be a nice little improvement to quality of life if the Admin had this info _always_ available.

### Describe the solution you'd like

I'd like to see a little info panel somewhere in the admin that had something like the following:

> Wagtail version: **5.2**
> Django version: **4.2.6**
> Python version: **3.11.6**

Heck, to be really thorough, you could add in:

> WSGI: **yes**
> Server: **Gunicorn 20.1.0**
> My IP: **18.106.31.256**

(The "My IP" is nice for those Wagtail systems that make outgoing connections for app-specific reasons so I can make firewall exceptions to those destinations. That's a niche use case, though.)

Other ideas: load average, detection if inside a container yes/no, host OS type, etc.

### Describe alternatives you've considered

I could roll my own I guess using `wagtail_hooks.py` and the `wagtail_version` template tag.

### Additional context

This was inspired by two things recently (aside from the "My IP" case I made above):

1. I have a QC engineer on one project who checks, amongst other things, the version of Wagtail running. She does so by looking for the "Wagtail upgrade available". If there's no upgrade available, QC fails. There's got to be a better way!
2. Plone does this; from their control panel:

<img width="472" alt="Screenshot of Plone's control panel showing version information" src="https://github.com/wagtail/wagtail/assets/814813/a92e0a81-69c2-4083-8933-d04b780ce9b0">

**Comment by gasman** [comment]
@nutjob4life It's at the bottom of the settings menu - does that do the job?
