### ISSUE TITLE
`ActionController` allows non-input controlled elements to call `select` method

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#11307]
### Issue Summary

When attempting to use the `ActionController` (`w-action`), it's possible to use on a non-input element and trigger the select method in a way that throws an error.

This is a bit of an edge case but after some digging it seems our Type check is could be better written.

See https://github.com/wagtail/wagtail/blob/b7beb36df6bc89e6152eae6c7d2dabaee7bd660a/client/src/controllers/ActionController.ts#L106

### Steps to Reproduce

1. Try to use `data-controller="w-action" data-action="click->w-action#select:prevent"` on a Link or other non-button, non-input element.
2. For example - add this to `wagtail_hooks.py` in the project.
```py
from wagtail import hooks
from wagtail.admin.menu import MenuItem

@hooks.register('register_help_menu_item')
def register_explain_menu_item():
  """
  See https://docs.wagtail.org/en/stable/reference/hooks.html#construct-help-menu
  """

  return MenuItem(
        'Explain',
        '#explain-content',
        icon_name='clipboard-list',
        order=10000,
        attrs={
            'data-controller': 'w-action',
            'data-action': 'click->w-action#select:prevent:stop',
            'data-a11y-dialog-show': 'explain-content',
            'role': 'button'
        }
    )
```
3. Reload the application and observe there should be a new help menu item called 'Explain'
4. Open the browser console & click the item in the menu.
5. Observe in the console, when clicked, it triggers an error.

#### Screenshots

<img width="757" alt="Screenshot 2023-12-06 at 6 41 01 am" src="https://github.com/wagtail/wagtail/assets/1396140/95e3b7b0-1c13-4f5b-87e2-6a64f9897279">
<img width="1605" alt="Screenshot 2023-12-06 at 6 39 10 am" src="https://github.com/wagtail/wagtail/assets/1396140/5a55c138-ae6b-495e-826a-05bac8a804f3">

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Proposed solution

We could either try to check for `select` being a function on the element OR just reverse our Type checks, instead of checking for not being a Button.

Something like this

```ts
  /**
   * Select all the text in an input or textarea element.
   */
  select() {
    if (
      this.element instanceof HTMLInputElement ||
      this.element instanceof HTMLTextAreaElement
    ) {
      this.element?.select();
    }
  }
```

We would need to write a Jest unit test that confirms this will work for an Input (text) element and TextArea - if not already in the unit tests.

### Further enhancement

This is a minor item but would be nice to fix up if we get the time, additionally, we may want to add a `noop` method to this controller for the cases where we just want to attach some behaviour that intentionally does nothing.

**Comment by lb-** [comment]
Flagging as a good first issue, this is a small TypeScript & Stimulus change and only requires a small unit test on existing test suite.

**Comment by nandini584** [comment]
Is this issue there for new projects on wagtail, I have tried reproducing it but my console had no errors, here is the code. Could you please verify it? 
![Screenshot 2023-12-05 182907](https://github.com/wagtail/wagtail/assets/117419442/8a356729-19e2-4ba6-a30a-f9f77df52893)
![Screenshot 2023-12-05 182919](https://github.com/wagtail/wagtail/assets/117419442/1587e5d2-16a0-4abf-916b-ae3dc0732590)

**Comment by laymonage** [comment]
@nandini584 it's an issue in the admin, not the front-facing website. Try replicating it in the admin e.g. `/admin/`

**Comment by lb-** [comment]
@nandini584 I have updated the steps to reproduce to be a bit clearer, I hope that helps.

Note for all - this is a bit of an edge case and is not a documented usage of this Stimulus controller. However, I think it would be good for us to fix this to have more robust code for the admin and eventual use for customising Wagtail.

**Comment by nandini584** [comment]
I am able to reproduce the issue and am planning to work on the same, this is the ss for the same: 
![Uploading Screenshot 2023-12-06 172407.png…]()

**Comment by lb-** [comment]
Awesome. Let me know if you need a hand @nandini584 thanks.
