### ISSUE TITLE
Wrong command to create virualenv in linux

### ISSUE THREAD

**Issue by dhruvpal05** [wagtail/wagtail#11388]
In Getting started, in Your first wagtail site the command given to create virtual environment for linux is is wrong, it does not work for linux I don't know whether it works for mac of not. [here](https://docs.wagtail.org/en/stable/getting_started/tutorial.html) . It has  `python -m venv mysite/env` this command, instead it should be `virtualenv mysite/env` or `python3 -m venv mysite/env` for creating env inside mysite directory. Still I don't know about mac but for linux it does not work.

![Screenshot from 2023-12-22 14-26-22](https://github.com/wagtail/wagtail/assets/91111849/9f11345d-c559-4453-959e-deddf893717e)

This is what happens on linux

`virtualenv mysite/env` 

![Screenshot from 2023-12-22 14-31-05](https://github.com/wagtail/wagtail/assets/91111849/562861c5-75cd-440e-8ed5-ca5baf357e5f)

`python3 -m venv mysite/env`

![Screenshot from 2023-12-22 15-12-15](https://github.com/wagtail/wagtail/assets/91111849/4b314767-eb26-4b48-950d-ce44301967a8)

This is what should actually happen

### Details

I can create a PR if someone can review this issue, and verify. We can create a separate code block for linux in docs or can edit the existing on if it does not work for mac too.

**Comment by thibaudcolas** [comment]
Hi @dhruvpal05, thanks for the report. Could you report which version of Python you’re using?

`python -m venv` is [recommended by Python](https://docs.python.org/3/library/venv.html#creating-virtual-environments) since version 3.5, so I suspect you’re using a version we don’t support here.

**Comment by laymonage** [comment]
I think in some Linux distros e.g. Ubuntu, venv is not included in the Python installation by default and it needs to be installed manually via `apt install python-venv` (or python3-venv), I forgot.

**Comment by dhruvpal05** [comment]
Hi @thibaudcolas , thanks for responding, I am using `Python 3.10.12`, I meant to say that for using venv we have to use `python3 -m venv mysite/env`  as  `python -m venv mysite/env` does not work for linux (Ubuntu 22.04.3 LTS). Will surely avoid using screenshots/images in future.

**Comment by thibaudcolas** [comment]
Thanks @dhruvpal05, yes we recommend using `python3` in the tutorial. And we also recommend doing `sudo apt install python3-venv` in Ubuntu.
