### ISSUE TITLE
No permission check for "why not add one?" link in snippets index view

### ISSUE THREAD

**Issue by saevarom** [wagtail/wagtail#11393]
### Issue Summary
Two templates in the snippets app do not check permissions before rendering a link to the create view for for the snippet model.

In the index results when there are no entries:
https://github.com/wagtail/wagtail/blob/8a6ab175fc1ee2eab53f7223a5bb24e97a2a278f/wagtail/snippets/templates/wagtailsnippets/snippets/index_results.html#L17-L21

In the chooser:
https://github.com/wagtail/wagtail/blob/8a6ab175fc1ee2eab53f7223a5bb24e97a2a278f/wagtail/snippets/templates/wagtailsnippets/chooser/results.html#L8-L11

I'm not sure what the policy is in Wagtail but I think it is counter-intuitive to render a link to a create form when the user does not have privileges to do so.

**Comment by Chiemezuo** [comment]
I'd like to work on this, but would need a bit of guidance.

**Comment by noobCoderVP** [comment]
I would like to work on this issue, We should have the logic "default: without link"/"if privileges: render link". Can you assign me this issue?

**Comment by lb-** [comment]
PR up with a fix already https://github.com/wagtail/wagtail/pull/11444

cc @Chiemezuo @noobCoderVP
