### ISSUE TITLE
Can't insert links into RichTextField when editing custom image model

### ISSUE THREAD

**Issue by st3iny** [wagtail/wagtail#11421]
### Issue Summary

It should be possible to use a `RichTextField` on a custom image model since https://github.com/wagtail/wagtail/issues/4466.

However, it is not possible to insert links. The editor will crash each time the "insert link" action is triggered.

### Steps to Reproduce

1. Create a custom image model.
2. Add a `RichTextField` and add it do `admin_form_fields`.
3. Edit an existing image.
4. Type `/` and embed a link.
5. The rich text editor crashes.

Console log:
```
TypeError: Cannot read properties of undefined (reading 'pageChooser')
    at LinkModalWorkflowSource.getChooserConfig (draftail.js?v=6949acd0:2:271933)
    at LinkModalWorkflowSource.componentDidMount (draftail.js?v=6949acd0:2:247330)
    at ll (vendor.js?v=6949acd0:2:146973)
    at gu (vendor.js?v=6949acd0:2:164599)
    at t.unstable_runWithPriority (vendor.js?v=6949acd0:2:205430)
    at Bi (vendor.js?v=6949acd0:2:108702)
    at vu (vendor.js?v=6949acd0:2:161265)
    at ru (vendor.js?v=6949acd0:2:157419)
    at vendor.js?v=6949acd0:2:108993
    at t.unstable_runWithPriority (vendor.js?v=6949acd0:2:205430)
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no
-   Could this be related to the caveats mentioned in https://github.com/wagtail/wagtail/issues/4466#issuecomment-393291159?

### Technical details

-   Python version: 3.11.7
-   Django version: 4.2.8
-   Wagtail version: 5.2.2
-   Browser version: Chromium 120.0.6099.129 (64-Bit)

**Comment by st3iny** [comment]
## My custom image model
```py
from wagtail.images.models import AbstractImage, Image
from wagtail.fields import RichTextField

class CustomImage(AbstractImage):
    description = RichTextField(blank=True)

    admin_form_fields = Image.admin_form_fields + (
        'description',
        'invert_top_text',
        'invert_bottom_text',
    )
```

**Comment by gasman** [comment]
> Could this be related to the caveats mentioned in https://github.com/wagtail/wagtail/issues/4466#issuecomment-393291159?

No, I don't think so - that only applies to the "upload an image" tab / form within the image chooser (because it would result in a popup within a popup, which is not supported as per #1144), not editing an existing image through the Images section of the admin.

**Comment by lb-** [comment]
Can confirm this error.

## When bulk uploading

<img width="1796" alt="Screenshot 2024-02-02 at 7 25 35 am" src="https://github.com/wagtail/wagtail/assets/1396140/ac916423-dfbf-42ad-b727-f10fa86d81be">

## When editing an image

<img width="2016" alt="Screenshot 2024-02-02 at 7 26 49 am" src="https://github.com/wagtail/wagtail/assets/1396140/7a89a784-7cd4-4859-8dc3-9215c2ef0573">
