### ISSUE TITLE
Field defined in exclude_fields_in_copy still gets copied (Wagtail 5.2.2)

### ISSUE THREAD

**Issue by drimacus182** [wagtail/wagtail#11428]
### Issue Summary
This is a follow-up to the issue  #10001 as **I can reproduce it in Wagtail 5.2.2**

@Tijani-Dia perfectly described the problem I've been having for ages, so I'll copy the steps from #10001 with a few unimportant changes:

When I copy a page in the admin, some fields get copied even if added to the `exclude_fields_in_copy` list.

### Steps to Reproduce
1. Start a new project with wagtail start myproject
2. Edit models.py as follows:

```python3
from django.db import models

from wagtail.models import Page
from wagtail.admin.panels import FieldPanel


class HomePage(Page):
    pass


class TestPage(Page):
    name = models.CharField(max_length=255, default="name")

    content_panels = Page.content_panels + [FieldPanel("name")]

    exclude_fields_in_copy = ["name"]
```
3. Create and run migrations, create superuser, run server
```bash
./manage.py makemigrations
./manage.py migrate
./manage.py createsuperuser
./manage.py runserver
```

4. Create and publish a TestPage in the admin UI and set any value other than the default one for the name field e.g original:
<img width="769" alt="orig" src="https://github.com/wagtail/wagtail/assets/3090883/51fecb13-fc79-4c39-a4b8-d82dc550908a">

5. Copy the page (without ticking the Publish copied page and Alias checkboxes):
<img width="608" alt="copying" src="https://github.com/wagtail/wagtail/assets/3090883/d1334053-c61a-43f7-a6a3-180f8a6a49cc">

6. Go to the edit view for the copied page: **the name value is copied from the original page**
<img width="628" alt="copy" src="https://github.com/wagtail/wagtail/assets/3090883/4487ea43-8350-47d1-a25d-c385453cb848">

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

- Since I've added the `name` field in the `exclude_fields_in_copy` list, I'd expect the copied page to have the default value for that field.

- This issue is related to #10922 where the problem occurs while publishing the copied page with a unique and hidden `uuid` field, that should be auto-generated but somehow makes it into the copy page.   
- It reproduces in Wagtail 5.2.2. I was trying to reproduce it in 4.1, but everything is fine there
- It works fine when `Publish copied page` checkbox is ticked

 
- I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: `3.11.5`
-   Django version: `5.0.1`
-   Wagtail version: `5.2.2`
-   Browser version: `Firefox 121`

**Comment by lb-** [comment]
Can confirm this issue exists I have been able to reproduce with the steps provided.
