### ISSUE TITLE
Wagtail rich text field broken on mobile device (Android S23)

### ISSUE THREAD

**Issue by anthonyrubin** [wagtail/wagtail#11425]
### Issue Summary
Unable to edit a richtext field on mobile devices (tested on Android). Our blog is deployed in production and this is a critical issue if there is a need to edit an article on the fly.

A similar issue was raised 3.5 years ago and remains open
https://github.com/wagtail/wagtail/issues/6534

Re-raising the issue in its current state with up-to-date Django and Wagtail versions.

### Steps to Reproduce
Attempt to edit a rich text field on an Android device (Samsung s23 used in this video).

https://github.com/wagtail/wagtail/assets/25280259/ca7e95cd-2f42-484d-95f1-b64258cade94

### Technical details

-   Python version: 5.12.
-   Django version: 5.0.
-   Wagtail version: 5.2.2.
-   Browser version: Chrome 120

**Comment by gasman** [comment]
Thanks for the report, but there's no need to re-raise this as a new issue - if an issue remains open, then the assumption is that it's still an issue on current versions unless we have new information to suggest otherwise. Closing as duplicate.
