### ISSUE TITLE
Path typos

### ISSUE THREAD

**Issue by KalobTaulien** [wagtail/wagtail#11424]
### Pertinent section of the Wagtail docs
https://docs.wagtail.org/en/stable/reference/viewsets.html#snippetviewset

### Details

Every instance of `wagtail.snippet.views.snippets` should be `wagtail.snippets.views.snippets`. Example below. 

![image](https://github.com/wagtail/wagtail/assets/4743971/bbac2999-df90-4234-a119-40331abb2b21)
(Insert the permalink of the section heading in the Wagtail docs. Choose the most specific section / lowest-level heading to which your suggested change would apply. (In the docs, hover over the heading to see the permalink icon.))
(Write your answer here.)

**Comment by laymonage** [comment]
Thank you, this was fixed in #11390, the `latest` docs have been updated with the fix: https://docs.wagtail.org/en/latest/reference/viewsets.html

The stable version will be updated when the next 5.2.x release is out.
