### ISSUE TITLE
MenuItem.is_active appears to be dead code

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#11433]
It seems like the `is_active(request)` method on `wagtail.admin.menu.MenuItem` is dead code. It does not appear to be actually called from anywhere, except by other code that is also never called.

A search through the Wagtail codebase shows that the only place where `MenuItem.is_active()` gets called appears to be `wagtail.admin.menu.Menu.active_menu_items()`. And *that* method only gets called by `wagtail.admin.menu.SubmenuMenuItem.is_active()`. The only other code that calls any of these three functions is one test: `wagtail.admin.tests.tests.TestMenuItem.test_menuitem_reverse_lazy_url_pass`.

I *believe* this may have happened because the `is_active` behavior was moved entirely into the javascript. I see that the `sidebar-menu-item--active` class, which is what causes "active" menu items to be themed by the CSS, is exclusively manipulated by JS code (specifically, code in `.tsx` files, which I think is TypeScript?). When this change was made, the removal of the old python code that used to be responsible for that behavior seems to have been forgotten.

I propose that `wagtail.admin.menu.MenuItem.is_active`, `wagtail.admin.menu.Menu.active_menu_items`, and `wagtail.admin.menu.SubmenuMenuItem.is_active` be removed.

**Comment by lb-** [comment]
I can confirm this appears to be the case, that code is unused.

I will remove 'bug' and add this as a clean up task instead.

Great find @coredumperror

**Comment by Srishti-j18** [comment]
Hi LB, I have made some changes. Please let me know if any further modifications are needed. Thank you, @coredumperror , for identifying this optimization.
