### ISSUE TITLE
Add comment button should move focus to the new comment

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#11450]
Issues reported by @albinazs as part of [WCAG 2.2 accessibility audit](https://github.com/wagtail/wagtail/discussions/11180).

### Issue Summary

When editing pages and adding the first comment, focus doesn't move to the comment box. This works as expected when the comment panel is already opened, but not when it’s closed.

Illustration:

![add comment interaction recording](https://github.com/wagtail/wagtail/assets/877585/36fc0bc3-0791-4188-8c93-053ce6226b6c)

### Steps to Reproduce

1. Go to any page editing form (for example https://static-wagtail-v5-2.netlify.app/admin/pages/60/edit/)
2. With the keyboard or mouse, active a "Add comment" button next to a field
3. Observe focus isn’t moving to the commenting box

### Working on this

This requires investigating the comment implementation in JS/React/Redux. Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by nandini584** [comment]
I understood the issue, I am working on this.

**Comment by lb-** [comment]
Could be a duplicate of https://github.com/wagtail/wagtail/issues/11021

PR up with a fix from October last year. https://github.com/wagtail/wagtail/pull/11022

Just awaiting a review.

**Comment by thibaudcolas** [comment]
Thank you @lb-, yes I believe it is :) I thought we had an issue opened for this but couldn’t find it for some reason.
