### ISSUE TITLE
Slim header breadcrumb renders incorrectly when explorable root is not the tree root

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#11451]
The breadcrumb in the slim header renders oddly when a user is viewing the root page of the subtree that they have access to, and that root is NOT the overall root of the tree. For example, a user on bakerydemo with edit access to the 'breads' section and nowhere else sees:

<img width="902" alt="Screenshot 2024-01-12 at 14 41 03" src="https://github.com/wagtail/wagtail/assets/85097/9c483914-fde1-42fa-8037-bac11e567f68">

And on hover:

<img width="1080" alt="Screenshot 2024-01-12 at 14 41 21" src="https://github.com/wagtail/wagtail/assets/85097/29b4459c-5b97-4a86-8076-b5a133c1b226">

Since this is a real page that the user can edit (unlike the overall tree root) I would expect the page title here to show as "Breads", and appear without needing to hover.

Wagtail 6.0a0 (main), Django 4.2.9, Python 3.12.0

**Comment by ACK1D** [comment]
@gasman  If [11265](https://github.com/wagtail/wagtail/issues/11265) is implemented, it would make sense for the two display options to remain.

**Comment by laymonage** [comment]
I can confirm this issue:

<img width="480" alt="image" src="https://github.com/wagtail/wagtail/assets/6379424/35d6a4c9-0b54-4684-89ee-d9e2840e058e">

<img width="480" alt="image" src="https://github.com/wagtail/wagtail/assets/6379424/5a825045-cdaf-4617-9fe3-d3d9227dcdc2">
