### ISSUE TITLE
Stylesheets variables and mixins clean-up

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#11458]
Follow-up to #11365 - there are a number of quick win improvements with how we write Sass:

- Remove the unused `$grid-content-indent` and `$grid-max-width`.
- Move `$grid-columns` and `$grid-gutter-width` to the one mixin file they’re used in. I don’t see ourselves reusing those outside that file ever.
- Replace $font-sans with direct usage of `theme('fontFamily.sans')`, possibly re-testing the different places it’s used as I suspect lots of them are completely unnecessary.
- Replace $font-mono with direct usage of `theme('fontFamily.mono')`
- Move `$sidebar-toggle-size` and `$sidebar-toggle-spacing` to the one file they’re used in.
- Remove all unused mixins in `_mixins.grid.scss`
- Remove the unused `$object-title-height`

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start. This is pretty mechanical work but in CSS / Sass only, so requires an awareness of the syntax and how to test different types of changes in Wagtail.

**Comment by nandini584** [comment]
I will also have a look at this issue.

**Comment by nandini584** [comment]
I apologise I wasn't aware.

**Comment by thibaudcolas** [comment]
@nandini584 no worries. This is a general etiquette thing in open source for projects that accept community contributions, though the specifics vary. For Wagtail specifically, please make sure to read all comments before starting on any tasks. I’ve also linked to our contribution guidelines in the issue description, and there’s at the bottom of this page too. From there you’ll find a list to our first contribution guide and in particular guidelines on [finding an issue](https://docs.wagtail.org/en/latest/contributing/first_contribution_guide.html#finding-an-issue), where we recommend the following steps:

> -   [ ] Confirm that there is not someone actively working on it (no recent PR or comments in the last ~2 months)
> -   [ ] Ensure you can reproduce the problem/scenario in your local version of Wagtail
> -   [ ] Ensure that you feel confident to write a unit test (if it's a code change) to validate that the solution **is** implemented

**Comment by nandini584** [comment]
I understand, thank you so much.
