### ISSUE TITLE
N + 1 Queries with richtext hyperlinks

### ISSUE THREAD

**Issue by bmoe872** [wagtail/wagtail#11484]
### Issue Summary
Started getting N+1 Query issues from Sentry. Investigated some of the underlying causes and found that the N+1 Query is due to hyperlinks put on page. This is a problem for us because on any given page we'll have 30+ links to other wagtail pages. 

### Steps to Reproduce
Best to have Django Debug toolbar installed to view the queries being made on a given page. 

1. Create several pages in the admin
2. Create one page that contains hyperlinks within the richtext to all of these other pages. 
3. View Django debug toolbar to see the SQL
4. In debug toolbar you'll see that each hyperlink is doing a separate query against the wagtail page database to get the linked-to page's url.

This causes the N + 1 problem that I believe could be optimized. The query being made to the pages is doing a `SELECT *` to get all the fields when it really only needs the url. 

Ideally this would happen in a single query to get all the necessary pages vs doing a query for every different hyperlink. 

### Technical details
-   Python version: 3.11
-   Django version: 4.2.7
-   Wagtail version: 5.2
-   Browser version: N/A

**Comment by chosak** [comment]
Hi @bmoe872, thanks for submitting this. Back in 2020 I submitted #5875 to try to address this issue, but unfortunately it never got a review and has since diverged from main and will need some rebasing.

**Comment by zerolab** [comment]
@bmoe872 thanks for raising this. @chosak if you have the time to rebase/update #5875 I vouch the perf sub-team will look at it as a matter of high importance. Sorry it went unnoticed for this long

**Comment by chosak** [comment]
@zerolab thanks! I've rebased #5875 and it should be ready for review.

**Comment by chosak** [comment]
#5875 is now merged in and addresses the reported issue. A single rich text field with multiple page links will now optimize the database queries so that all pages are fetched at once.
