### ISSUE TITLE
`Page.get_children()` is not documented in `Page` model reference

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#11499]
### Pertinent section of the Wagtail docs

The `get_children()` method is mentioned a few times in the tutorial, but it's missing from the Page model reference itself: https://docs.wagtail.org/en/stable/reference/pages/model_reference.html#methods-and-properties

### Details

The documentation does give a link to django-treebeard's node API and it also mentions that `Page` is an `MP_Tree` subclass. While it can be deduced that `Page` has a `get_children()` method, the fact that other methods like `get_parent()`, `get_ancestors()`, and `get_descendants()` are explicitly mentioned in the Wagtail docs begs the question why `get_children()` isn't.

### Working on this

The `get_children()` method should be added either after `get_parent()` or before `get_descendants()`.

https://github.com/wagtail/wagtail/blob/5b1ab02be55b3f99035bdb46af5b0a9c4336b378/docs/reference/pages/model_reference.md?plain=1#L203-L207

Note: since the method isn't overridden, this will output the docstring from django-treebeard. However, this is also the case with `Page.get_parent()`. If that's OK then just use `automethod` like the docs for `get_parent()`, otherwise use `method` and manually document the method (and perhaps update `get_parent()` as well.

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by salvo-polizzi** [comment]
I'd like to work on this
