### ISSUE TITLE
LookupError for invalid bulk action URL

### ISSUE THREAD

**Issue by tomkins** [wagtail/wagtail#11491]
### Issue Summary

500 LookupError for invalid bulk actions URL. 

### Steps to Reproduce

```
pip install wagtail==5.2.2
wagtail start mysite
cd mysite
./manage.py makemigrations
./manage.py migrate
./manage.py createsuperuser
./manage.py runserver
```

Go to: http://127.0.0.1:8000/admin/bulk/test/test/test/

See a 500:

LookupError at /admin/bulk/test/test/test/
No installed app with label 'test'.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.12 / any
-   Django version: 5.0 / any
-   Wagtail version: 5.2.2 / main
-   Browser version: n/a

### Working on this

Following up with a PR shortly.

**Comment by lb-** [comment]
<img width="1139" alt="Screenshot 2024-01-21 at 8 04 32 am" src="https://github.com/wagtail/wagtail/assets/1396140/ae578150-951e-445b-941b-e08661480218">


Can confirm this issue exists. Great bug report @tomkins  thank you.
