### ISSUE TITLE
Using a related field in Snippet/ModelViewSet causes exception when index list requested

### ISSUE THREAD

**Issue by dkirkham** [wagtail/wagtail#11494]
### Issue Summary
When referencing a related model field in a SnippetViewSet or ModelViewSet, requesting the index view causes an exception because the column label cannot be determined.

Specifically, it fails within the Django `label_for_field()` function:

```
Traceback (most recent call last):
  File ".../.venv/lib/python3.10/site-packages/django/db/models/options.py", line 673, in get_field
    return self.fields_map[field_name]
KeyError: 'full_featured.text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../.venv/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 333, in label_for_field
    field = _get_non_gfk_field(model._meta, name)
  File ".../.venv/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 302, in _get_non_gfk_field
    field = opts.get_field(name)
  File ".../.venv/lib/python3.10/site-packages/django/db/models/options.py", line 675, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: SnippetChooserModel has no field named 'full_featured.text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../wagtail/snippets/tests/test_viewset.py", line 748, in test_snippetchoosermodel_related_fields
    response = self.client.get(self.get_url("list"))
  File ".../.venv/lib/python3.10/site-packages/django/test/client.py", line 836, in get
    response = super().get(path, data=data, secure=secure, **extra)
  File ".../.venv/lib/python3.10/site-packages/django/test/client.py", line 424, in get
    return self.generic(
  File ".../.venv/lib/python3.10/site-packages/django/test/client.py", line 541, in generic
    return self.request(**r)
  File ".../.venv/lib/python3.10/site-packages/django/test/client.py", line 810, in request
    self.check_exception(response)
  File ".../.venv/lib/python3.10/site-packages/django/test/client.py", line 663, in check_exception
    raise exc_value
  File ".../.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File ".../.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".../.venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File ".../wagtail/admin/urls/__init__.py", line 180, in wrapper
    return view_func(request, *args, **kwargs)
  File ".../wagtail/admin/auth.py", line 167, in decorated_view
    response = view_func(request, *args, **kwargs)
  File ".../.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 78, in view
    self.setup(request, *args, **kwargs)
  File ".../wagtail/admin/views/generic/models.py", line 111, in setup
    self.columns = self.get_columns()
  File ".../wagtail/snippets/views/snippets.py", line 180, in get_columns
    *super().get_columns(),
  File ".../wagtail/admin/views/generic/models.py", line 336, in get_columns
    column = self._get_custom_column(field)
  File ".../wagtail/admin/views/generic/models.py", line 309, in _get_custom_column
    label, attr = label_for_field(field_name, self.model, return_attr=True)
  File ".../.venv/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 361, in label_for_field
    raise AttributeError(message)
AttributeError: Unable to lookup 'full_featured.text' on SnippetChooserModel
```

### Steps to Reproduce

1. Clone the wagtail branch at https://github.com/dkirkham/wagtail/commit/e942cae55fe7e8324eca942b29638c2af9551f48 within a working Wagtail development environment
2. Run the test: `python runtests.py wagtail.snippets.tests.test_viewset.TestRelatedFieldColumns`
3. Note the crash backtrace in the test report.

### Background
I've found myself wanting to refer to fields within related models within ModelViewSet index lists. This is because the `__str__` methods in those referenced models often include other contextual information which is useful in other circumstances, but too much for the index list (which often has that context in adjacent columns). I'd also like to avoid creating extra methods in models to access related model fields.

I (perhaps naïvely) tried using `list_display = ["field__related_field"]` a format which works in `search_fields` and `ordering`, but this fails. Digging into the code, `list_display` ultimately uses `multigetattr()` as the data accessor which reproduces template semantics using dot-separated fields: `list_display = ["field.related_field"]`. Neither format however works to automatically obtain a column label.

It is possible to use the `Column()` class to directly provide a label: `list_display = [Column("field.related_field", label="Related Field")]`

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)
-   I have confirmed that this issue can be demonstrated in a Wagtail test case: (yes)

Is it a bug? The fact that there is code to allow access to the related field data, but the code fails trying to work out the column name would suggest so. The generality of the `multigetattr()` data accessor might be difficult to reproduce when finding the label, so the workaround using `Column()` may be an acceptable and more dependable solution. If so, it might be useful to both detect the failure to find a label and raise this as a warning or configuration error, rather than failing when the index list is requested; and to document the preferred solution.

### Technical details

-   Python version: 3.10, but likely not relevant.
-   Django version: 4.0.10 and 4.2.8, probably others.
-   Wagtail version: 5.2 and wagtail#main
-   Browser version: irrelevant

### Working on this

I've started a [branch](https://github.com/dkirkham/wagtail/tree/fix-index-view-get-related-field-label) with the test demonstrating the failure. I haven't yet started looking to see if an automatic method of determining the label for a related field is possible.

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by abdlrhman08** [comment]
I cloned the repo and can confirm that the test fails. I am going to try to take a deep dive into the issue.

**Comment by abdlrhman08** [comment]
I don't know if this is a correct conclusion, but I think what happens is when `label_for_field` get called, it is given two arguments, the field name and the model. What happens during your test case is `label_for_field` receives `full_featured.text` in field name, and `SnippetChooserModel` for the model parameter. What causes the error is that there is no field called `full_featured.text` in `SnippetChooserModel`, which is correct. It will only work in way when `label_for_field` is passed `full_featured.__class__` is pased in the model parameter, since `label_for_field` can only access the models fields only. Feel free to correct me, I may be to totally wrong.

**Comment by abdlrhman08** [comment]
This fixes it for me, i'll figure proper namings and submit a pull request

```python
    def _get_custom_column(self, field_name, column_class=Column, **kwargs):
        field_name_list = field_name.split(".")
        
        field_name = field_name_list[0]
        model = self.model
        
        if len(field_name_list ) > 1:
            field_name = field_name_list[0]
            foreign_field_name = field_name_list[1]
        
            foreign_relation = getattr(self.model, field_name)

            field_name = foreign_field_name
            model = foreign_relation.field.related_model

        label, attr = label_for_field(field_name, model, return_attr=True)

        sort_key = getattr(attr, "admin_order_field", None)

        # attr is None if the field is an actual database field,
        # so it's possible to sort by it
        if attr is None:
            sort_key = field_name

        return column_class(
            field_name,
            label=capfirst(label),
            sort_key=sort_key,
            **kwargs,
        )

**Comment by laymonage** [comment]
While I agree that this would be great to have, we've never publicly documented that this is possible, so I'm inclined to mark this as an enhancement, not a bug.

As you mentioned, the other properties like `search_fields` and `ordering` uses the lookup format (`__`), so I think we should use the same format in `list_display`.

The `multigetattr` is an implementation detail of the `Column` class, not the `list_display` attribute, so I think we shouldn't be constrained with what that function supports. We could pre-process `list_display` to split by the lookup separator `__` so it correctly retrieves the label for related fields, but maybe convert it to use `.` in the `Column` accessor.

For background, `list_display` is a higher-level abstraction on top of the `Column` class, to ease transition from Wagtail's legacy `ModelAdmin`. Wagtail's `ModelAdmin` is largely inspired from Django's `ModelAdmin`, and the latter just added support for related lookups two weeks ago (!): https://github.com/django/django/pull/17357

Django also uses the `__` format, so we have another good reason to use it.

**Comment by dkirkham** [comment]
Happy to see this as an enhancement request, @laymonage. I think having `__` as the lookup separator consistently across the API is a desirable outcome, and clearly the Django team think so too.

Thanks @abdlrhman08 for preparing the PR.
