### ISSUE TITLE
Add system checks for `WAGTAIL_DATE_FORMAT`, `WAGTAIL_DATETIME_FORMAT`, `WAGTAIL_TIME_FORMAT` being listed in Django configured formats

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#11504]
### Is your proposal related to a problem?

When configuring any of the `WAGTAIL_*_FORMAT` configs, these must be included in the relevant Django formats.

https://docs.wagtail.org/en/stable/reference/settings.html#wagtail-date-format-wagtail-datetime-format-wagtail-time-format

> ...must be one of the recognised formats listed in the DATE_INPUT_FORMATS, TIME_INPUT_FORMATS, or DATETIME_INPUT_FORMATS setting respectively 

This config coordination is easy to to get wrong causing non-intuitive behaviour as Wagtail/Django will fallback to defaults.

### Describe the solution you'd like

* Using the [Django system check framework](https://docs.djangoproject.com/en/5.0/topics/checks/) or similar, ensure that if there are misconfiguration issues there will be an error thrown or report at app startup.

### Describe alternatives you've considered

* Leave as is, the documentation advises what to do.

### Additional context

* An older PR had a really solid start to this but had a few questions and was only a draft. https://github.com/wagtail/wagtail/pull/6168
* It may make sense to start with a simple version of these checks as a smaller scoped PR.

### Working on this

* This would be good for anyone willing to dig deep into these configs & their Django equivalents.
* Some knowledge or learning of the way the Django system check framework works and exploration of the current usage in Wagtail.
* The PR linked above would be a good start but may not be the right way forward, it also did not have tests and tests are a must.
* View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by laymonage** [comment]
@riddhisharma-sudo Please refrain from using AI to write comments that do not add any meaningful value to the issue. Your comment just rephrases the issue description.

**Comment by riddhisharma-sudo** [comment]
No I'm just asking because as a beginner I have questions!

**Comment by lb-** [comment]
@rohitsrma happy to help with any specific questions you have about how to go about implementing this. 

Here's two PRs that added system checks that may help guide you or anyone else. 

- https://github.com/wagtail/wagtail/pull/8258
- https://github.com/wagtail/wagtail/pull/10873

**Comment by rohitsrma** [comment]
Thank you @lb-,  I'm eager to give this a try!
