### ISSUE TITLE
Uneven text baseline in zero-results search query message (Wagtail 6.0rc1)

### ISSUE THREAD

**Issue by dkirkham** [wagtail/wagtail#11534]
### Uneven text baseline in zero-results search query message
When searching for a page that fails to produce a result, the message has an uneven baseline:

<img width="1070" alt="image" src="https://github.com/wagtail/wagtail/assets/1977376/e5c2afa5-7827-4f87-b8ef-d77d131687da">

I think this is to do with the height properties for each part of that line of text:

<img width="403" alt="image" src="https://github.com/wagtail/wagtail/assets/1977376/cb12f516-ad5c-4166-9f45-058130c40a03">
<img width="464" alt="image" src="https://github.com/wagtail/wagtail/assets/1977376/b3b637c0-fa88-4634-9433-e68d9dd13daf">

### Steps to Reproduce

1. Start a new project in Wagtail 6.0rc1 using the quick start instructions
2. Navigate to the Admin and to the Home Page list
3. Search for some text that isn't present in the page or child pages, so that there are no results
4. Observe the search message, that the page name has a lower baseline than the rest of the text

### Expected Outcome
The text baseline should be the same for the entire line of text.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

-   Python version: 3.11.5
-   Django version: 4.2.9, 5.0.1
-   Wagtail version: 6.0rc1
-   Browser version: Firefox 121.0.1 and Chrome 119.0.6045.159

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by thibaudcolas** [comment]
Thank you @dkirkham! This is the first feedback we received for 6.0rc1 I believe – on it :)

**Comment by riddhisharma-sudo** [comment]
I am ready to work on this bug but can you tell me html file for the same

**Comment by gasman** [comment]
@riddhisharma-sudo This is in [/wagtail/admin/templates/wagtailadmin/pages/listing/_page_title_column_header.html](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/pages/listing/_page_title_column_header.html).

**Comment by laymonage** [comment]
Fixed in #11608.
