### ISSUE TITLE
Add the ability to disable usage of shared password for page privacy

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#11536]
### Is your proposal related to a problem?

We currently allow private pages to be set with a 'shared password'. This password is stored in plain text (intentionally) and is not the most secure option, some site admins may want to avoid this feature being allowed completely.

See #10588 for parent issue covering a range of improvements.

### Describe the solution you'd like

Create two new settings;

* `WAGTAIL_ALLOW_SHARED_PASSWORD_PAGE`
* `WAGTAIL_ALLOW_SHARED_PASSWORD_COLLECTION`

These settings would be `True` by default.

If set to `False` these would remove the ability for the users to set the 'shared password' option for page or collection privacy respectively.

<img width="644" alt="Screenshot 2024-01-26 at 5 22 38 pm" src="https://github.com/wagtail/wagtail/assets/1396140/e16ebdb5-3ebb-427d-85ba-6c5a4fce4ac0">

It may also be good to take the time to add a bit of nuance to the usage of the shared passwords. Similar to https://github.com/wagtail/wagtail/pull/10729/files

> Shared passwords should not be used to protect sensitive content, as the password is shared between all users, and stored in plain text in the database. Where possible, it's recommended to require users log in to access private page content.

~~If any shared passwords exist, these pages would need to trigger a HTTP 405 (not allowed), even if signed in. It would be up to site admins to either change the access globally to some other privacy method (logged in, logged in group) or editors to update pages / collections manually.~~

~~The reason for the 405 is that the current behavior will not even allow logged in users to see the page without the shared password being entered so we do not want to change any access to 'less' access.~~

Update: We will simply not show the option in the dialog, even if there is an existing shared password value saved.

### Describe alternatives you've considered

* Various discussions have already been had on https://github.com/wagtail/wagtail/pull/10729

### Additional context

* A PR has already been done that does part of this (and a few more things), it could be used as a starting point https://github.com/wagtail/wagtail/pull/10729 (however, it has not got logic for collection privacy, nor the 405 response for existing data in place).
* See https://github.com/wagtail/wagtail/pull/10729
* Documentation must be added 
  * Settings documented on this page https://docs.wagtail.org/en/stable/reference/settings.html
  * A new issue created on the Wagtail guide would be needed to add nuance that the 'shared password' feature may not be enabled https://guide.wagtail.org/en-latest/how-to-guides/manage-collections/#privacy-settings
  * https://docs.wagtail.org/en/stable/advanced_topics/privacy.html will need to be updated with reference to this new setting.

### Working on this

* @RealOrangeOne may want to pick this up as a refinement (smaller scope with some tweaks) from https://github.com/wagtail/wagtail/pull/10729
* However, anyone can contribute to this if that is not the case.
* View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by RealOrangeOne** [comment]
I'm definitely happy to leave this and help a new contributor pick it up! Here's the commit from my previous PR for reference: https://github.com/wagtail/wagtail/pull/10729/commits/a6afe99bcf097d4248256cf8a416392da3dc7371

**Comment by lb-** [comment]
@gasman any thoughts on this settings approach or would app settings be better?

**Comment by salvo-polizzi** [comment]
Hi, I'd like to work on this issue but I have some questions to do. Where do I need to check if any shared password exists and then trigger an HTTP 405? From what I understand, the restrictions are set by calling the set_privacy method. To determine if a shared password exists, you can use the following condition: 
```python
if restriction.password is not None
```
However, in this case, you don't need to check if the password exists because you are setting it. This aspect confused me. Please let me know if I am mistaken. I might have misunderstood the purpose, so I would appreciate some feedback.

**Comment by gasman** [comment]
The 405 error thing feels a little like overkill to me - I think the aim here is to prevent the creation of _new_ password-protected sections. If there are any existing ones at the point when the setting is activated, I think it's reasonable enough to allow those to continue working.

I'd say that `WAGTAIL_ALLOW_SHARED_PASSWORD_PAGE = False` just needs to remove the "shared password" option from the form, except in the case that they're editing an existing restriction using that type. I don't think there needs to be any change to how the restrictions behave.

**Comment by lb-** [comment]
Thanks. That's a much simpler approach. I'll update the description accordingly.
