### ISSUE TITLE
Docs: use American English in 'customizing admin template' section

### ISSUE THREAD

**Issue by Stormheg** [wagtail/wagtail#11539]
We are in the process of transitioning from British English to American English spelling in the docs. See https://github.com/wagtail/wagtail/issues/10608 for context.

I've stumbled upon one area in the docs that hasn't been updated yet: [customising admin templates](https://docs.wagtail.org/en/latest/advanced_topics/customisation/admin_templates.html) ([source here](
https://github.com/wagtail/wagtail/blob/main/docs/advanced_topics/customisation/admin_templates.md))

Specific issues I see from a quick glance so far:

- Colour (british) should become color (american)
- customising -> customizing
- ...there are probably more...

One way to go about this might be to run a spell checker set to American English on the page.

Fixing this does not require programming knowledge. Which means this issue might be a good fit for a non-technical contributor. 

---

## Contributing tips

If you are not familiar with git, you might find it easier to use GitHub's web editing interface. [Here is are instructions on how do so](https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files)

**Note**: at step 9 in the GitHub documentation, it says to enter a description. Please reference this issue number in the description so we can keep track of work that has been done to fix this issue. Thanks!

**Comment by Buraah** [comment]
I will start working on this right away

**Comment by Stormheg** [comment]
Amazing, that was very quick @Buraah!

To all other contributors: if you discover instances of British spelling in other places in docs ([docs.wagtail.org](https://docs.wagtail.org/en/latest/)), feel free to make a pull request (please mention issue #10608 in the description)

Pro tip: click the 'edit on GitHub' button at the top-right of the page to quickly go to the right source document 🤠

**Comment by h-lakshman** [comment]
Hello, I've noticed that nobody has made a pr yet. If I finish earlier. Can i send a pr making the changes. Thank you.

**Comment by Stormheg** [comment]
Hi @h-lakshman

You are right there was no PR yet at the time you posted your comment, but someone else recently commented that they were working or a PR.

Please give others a chance to work on the issue. This is not a competition, finishing earlier does not have any meaning here. 

As a rule of thumb for next time:

1. If someone has posted a comment indicating they are working on the issue; AND this person hasn't opened a PR after a reasonable amount of time (say: one week, maybe two weeks for more complex issues)
2. Post a comment asking if they are still working on a PR.
3. You may get a reply. Or, in the case of no reply for a couple days, you may post a comment stating you will work on the issue given the amount of inactivity.
