### ISSUE TITLE
custom workflow model

### ISSUE THREAD

**Issue by arshyia3000** [wagtail/wagtail#11538]
### Is your proposal related to a problem?

yes, need to add some fields to Workflow model

### Describe the solution you'd like

suggest to make Workflow model be able to customized, same as Document as Image

### Describe alternatives you've considered

i can add a field to Workflow model myself, but in the future that customized Workflow model is provided, I would  need to migrate

### Additional context

>  Is there anything else you can add about the proposal?

No.

### Working on this

Workflow model needs to be abstracted from AbstractWorkflow. def get_workflow_model(): needs to  be defined, same as Document and image models. 

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by lb-** [comment]
Also I did a blog post on adding fields, it should be possible to add a field (relation to another model) without needing to modify the underling task model.

https://dev.to/lb/adding-tasks-with-a-checklist-to-wagtail-workflows-29b8

**Comment by arshyia3000** [comment]
I should add that my purpose can be achieved by showing the queryset of the workflow objects that is created by user, or their related profile. but having an abstract workflow model would give other capabilities to work around as well and customize workflow model more.

**Comment by arshyia3000** [comment]
also, this can be achieved by injecting new filed to Workflow model, per this similar question:
https://stackoverflow.com/questions/2181039/how-do-i-extend-the-django-group-model

```python
if not hasattr(Workflow, 'extra_field'):
    field = models.CharField(max_length=180, null=True, blank=True)
    field.contribute_to_class(Workflow, 'extra_field')
```


Though, i think making Workflow abstracted would be beneficial. I'll try to make PR this week.

**Comment by lb-** [comment]
@arshyia3000 - #11584 has been raised that may make some kinds of customisations like this easier.

Once merged we will close this issue as you should have a bit more capability once that gets released.

We may not officially support a full set of custom workflows though, so if you feel that this should be a documented approach with more capabilities maybe we can re-open this issue.

There's also the potential avenue for proxy models which are being explored in other areas like Pages.  See https://github.com/wagtail/wagtail/issues/4973 & other related items.
