### ISSUE TITLE
Update wording and help text for private pages using shared password

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#11535]
### Is your proposal related to a problem?

Wagtail's page privacy feature could be improved to communicate better to the user that the password created is different from using authentication (log in) to restrict access.

This issue is one part of a wider plan to improve this feature - see #10588

### Describe the solution you'd like

For private access dialogs (collection and page privacy), the following should be changed;

1. Update the ordering of the private access so that it goes from most public to most secure. 
  * The current ordering with the 'shared password' between the two logged in options does not make it easy to communicate the differences.
2. Change the wording for the labels:
  * "Private, accessible with the following password" -> "Private, accessible with a shared password"
  * "Private, accessible to logged-in users" -> "Private, accessible to any logged-in users"
3. Update the field label from "Password" to "Shared password"
4. Add help text (use our shared field template includes for this) with help text as follows:
  * "Shared passwords should not be used to protect sensitive content, anyone who has this password will be able to view the content."
5. Ensure all other references for private pages/collections are updated with references to 'password' becoming 'shared password'. Such as;
  * Documentation - https://docs.wagtail.org/en/stable/advanced_topics/privacy.html & https://docs.wagtail.org/en/stable/topics/permissions.html#image-document-permissions
  * Audit logging
  * Selected state in the side panel or the collection edit page
6. [ ] Once merged - a new issue on the Wagtail Guide will be needed to ensure screenshots get updated https://guide.wagtail.org/en-latest/how-to-guides/manage-collections/#privacy-settings

#### Screenshots of current state

<img width="1011" alt="Screenshot 2024-01-26 at 4 51 17 pm" src="https://github.com/wagtail/wagtail/assets/1396140/193360ea-bfc5-4483-9c1b-9e51f6ecd2ac">

<img width="739" alt="Screenshot 2024-01-26 at 4 49 44 pm" src="https://github.com/wagtail/wagtail/assets/1396140/fa20ec2d-8c8f-4fa7-ab67-ea77c4be0cee">

Audit logging

![247612418-69278dd0-028d-4e69-a81e-493d8e161367](https://github.com/wagtail/wagtail/assets/1396140/7088d8fd-184c-4c75-ba47-e19a54a01b79)

### Describe alternatives you've considered

There were various discussions on https://github.com/wagtail/wagtail/issues/10588 about other approaches, the core team have agreed that this is a good first step.

### Additional context

* Some of this (help text) was done in https://github.com/wagtail/wagtail/pull/10729 - but do not use this PR, instead create a new one.
* Documentation - https://docs.wagtail.org/en/stable/advanced_topics/privacy.html & https://docs.wagtail.org/en/stable/topics/permissions.html#image-document-permissions

#### Out of scope

Updating the default password template form does not need to be changed. Many sites will customise this.

<img width="611" alt="Screenshot 2024-01-26 at 4 52 14 pm" src="https://github.com/wagtail/wagtail/assets/1396140/aedf2161-46ec-4ad2-8229-62e87cdcb2c1">

### Working on this

* Anyone can contribute to this who is willing to take the time to understand how the private access features work and review the changes suggested above and work through the code to find out where to update this.
* Unit tests and documentation must be updated with any PR
* View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by rohitsrma** [comment]
I would like to work on this!

**Comment by lb-** [comment]
Go for it @rohitsrma

**Comment by lb-** [comment]
@rohitsrma are you able to create an issue with a new screenshot or two on the Wagtail guide repo.

Advise that the screenshots and description within this page - https://guide.wagtail.org/en-latest/how-to-guides/manage-collections/#privacy-settings - will need to be updated for 6.2. 

Include a link to this issue and your PR. Thanks again for helping to improve Wagtail. 

https://github.com/wagtail/guide/issues/new

**Comment by rohitsrma** [comment]
Thanks @lb- I've created issue https://github.com/wagtail/guide/issues/390.

**Comment by lb-** [comment]
Legend! Thanks.
