### ISSUE TITLE
Grammar check does not work

### ISSUE THREAD

**Issue by Vladorld** [wagtail/wagtail#11545]
The site is in Russian and for some reason it stopped emphasizing words with errors in Russian and English.

**Comment by gasman** [comment]
Hi @Vladorld - Wagtail does not provide a grammar checker. Are you using the [Wagtail AI](https://github.com/wagtail/wagtail-ai) add-on package, perhaps?

**Comment by Vladorld** [comment]
@gasman I see what the problem is. It's Google Chrome emphasizing the errors)
