### ISSUE TITLE
Changelog for 6.0 is missing rename of `{% field %}` to `{% rawformattedfield %}`

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#11550]
### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/latest/releases/6.0.html

### Details

When trying to upgrade a large project from 5.2 to 6.0 I stumbled over the (breaking) rename of the `{% field %}` tag.
I think sooner or later a developer will use this tag to customize/add some forms with correct styling, so this should be mentioned in the changelog.

For example, it also breaks the modeladmin-package, see the fixing [PR](https://github.com/wagtail-nest/wagtail-modeladmin/pull/32/files).

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by lb-** [comment]
Relevant PR https://github.com/wagtail/wagtail/pull/11271

**Comment by gasman** [comment]
Documenting this in the release notes is a little problematic: in most cases, where the tag pair has no content, something like `{% field field=form.email %}{% endfield %}` should become `{% formattedfield form.email %}`. However, as per https://github.com/wagtail/wagtail/pull/11271#issuecomment-1852315135, we're not yet ready to make the new `formattedfield` and `rawformattedfield` tags a public API - so the release note would essentially be telling people to replace one undocumented tag with another undocumented tag, when clearly we'd rather discourage them from using undocumented APIs at all :-)

I'd argue that our stance on this should be the same as for any other occasion people have borrowed bits of Wagtail internal code for their own use: if it breaks, it's your own responsibility to figure out how to update it.

**Comment by th3hamm0r** [comment]
> I'd argue that our stance on this should be the same as for any other occasion people have borrowed bits of Wagtail internal code for their own use: if it breaks, it's your own responsibility to figure out how to update it.

You're right, makes total sense! 👍
