### ISSUE TITLE
Any hook to set content-disposition in wagtail? 

### ISSUE THREAD

**Issue by atbug** [wagtail/wagtail#1158]
I want to serve some pdfs and I want them to be opened in the browser by default. I know in django development response['content-disposition'] does this trick, and I wonder if there is a hook in wagtail that has the same effect.

**Comment by kaedroho** [comment]
Theres a PR that makes Wagtail set this header automatically here: https://github.com/torchbox/wagtail/pull/733

Would this solve your issue?

**Comment by taishizhiqiu** [comment]
yeah, I hope it will soon be merged into master branch

**Comment by nutztherookie** [comment]
Hellu,

the linked issue #733 actually never got resolved in that respect (opening PDFs with content disposition "inline").

So *bump* - can we reopen this issue?

Thanks

**Comment by gasman** [comment]
This is in the list of things to be addressed by #1420 - however, since the scope of that issue is quite a bit larger, and we'd welcome a PR that deals with content-disposition specifically, I'll reopen.

**Comment by alexgleason** [comment]
Just wanted to share my solution for a workaround.

https://github.com/ProjectTIER/projecttier.org/blob/cb402b0102cdcb830e24341f15615e74814fb8fd/project_tier/urls.py#L14

https://github.com/ProjectTIER/projecttier.org/blob/cb402b0102cdcb830e24341f15615e74814fb8fd/project_tier/core/views.py#L1-L22

Therefore, visiting `/document/view/<mydoc>` will make the document viewable rather than downloaded.

It's pretty simple. It just calls the normal document view function in Wagtail to get the response, then alters the content-disposition of that response before returning it.

**Comment by johnraz** [comment]
I'm wondering why inline isn't the default here?
This seems to be the spec's default ([from MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#As_a_response_header_for_the_main_body)).

@gasman are you still open to a PR on this?

What would be the way to go? A settings? A hook?

Thanks 😉

**Comment by gasman** [comment]
@johnraz Yes, a PR for this would be very welcome, thanks! The approach I'd suggest would be:

* Add a setting named something like `WAGTAILDOCS_INLINE_CONTENT_TYPES`, defaulting to the list `['application/pdf']`
* Define two new properties on the `AbstractDocument` model:
  * `content_type`, which returns the MIME type for the document as determined by [`mimetypes.guess_type`](https://docs.python.org/3.7/library/mimetypes.html#mimetypes.guess_type)
  * `content_disposition`, which returns `'inline'` or `'attachment'` depending on whether `content_type` is found in `WAGTAILDOCS_INLINE_CONTENT_TYPES`
* Update the `wagtail.documents.views.serve` view to use these properties when generating HTTP headers

This way, we'll be doing the right thing out of the box for the majority of users (I think most people just want PDFs to display inline); people who want to recognise additional content types have an easy setting to do that; and people with more complex requirements can use a custom Document model and override those methods.

**Comment by gasman** [comment]
See also https://github.com/wagtail/wagtail/issues/1420#issuecomment-524561077, where @Pomax proposes a `WAGTAIL_DOCUMENT_CONTENT_TYPES` mapping in settings to take priority over the `mimetypes.guess_type` result.

**Comment by gasman** [comment]
PR: https://github.com/wagtail/wagtail/pull/6229
