### ISSUE TITLE
Documentation search results are out of date

### ISSUE THREAD

**Issue by jsma** [wagtail/wagtail#11619]
The Migrating from ModelAdmin to Snippets guide was deleted in this [commit](https://github.com/wagtail/wagtail/commit/c363f6dd27ada5d6b5eeeec1628119d6d7ac215d#diff-2ce6c1fd36f0fafaed13c950679ac91d9ae11f56b4f65420b97bd477aec5f533) but it's still appearing in the "stable" docs search results:

<img width="573" alt="image" src="https://github.com/wagtail/wagtail/assets/24574/7a099b3c-9181-4dcc-a069-1463f2a4a62e">

Clicking the result of course leads to a 404 page.

**Comment by gasman** [comment]
Thanks for the report! Should be fixed now - normally the indexer is set to run once a week on Mondays, which meant that it hadn't updated since the 6.0 release.
