### ISSUE TITLE
Optimize Page Routing by Caching Parent Instance

### ISSUE THREAD

**Issue by Nigel2392** [wagtail/wagtail#11625]
### Issue Summary

Calling `page.get_parent` inside your `serve` method performs a query. Why?

### Steps to Reproduce

Call `page.get_parent`.

### Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
I consider this a bug because the parent was likely already fetched before. Better yet - you should be able to walk all the way back up the tree inside your serve method without executing a single query, and have access to every **specific** instance of that parent. Simply finding a way to set the parent inside the `page.route(request, path_components)` method (likely as simple as `setattr(subpage.specific, "get_parent", lambda: self)`), you can save so many queries for the cost of a little bit of memory - which might not even be garbage collected by the time the request/response cycle is over.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (**yes** / no)

A fun and nice side effect of fixing this would be breadcrumbs on pages using 0 queries.

### How can we fix this?

As routing now goes - we are walking down the tree.
Let's visualize this.
```
root.route() -> subpage.route() -> subpage.route()
```
This performs a database query each time to get the child, great - no better options available as of now.
What we can do though - is cache the previous route as an attribute on it's respective sub-route.
```
root.route()
... no parent to store

    -> subpage.route() 
    ... store parent as attribute

        -> subpage.route()
        ... store parent as attribute
```

This then prevents further queries to `get_parent` in the view itself as we have stored it on the respective child page.
With some creativity - this can be extended to `Page.get_ancestors`. The best part? Every instance stored **is** the specific instance of the model.

[Quicklink for clarity](https://github.com/wagtail/wagtail/issues/11625#issuecomment-1961507449)

**Comment by Chiemezuo** [comment]
I think the 'why' part of your question would be because the method is from `django-treebeard`'s `MP_Node` class. So, it's not wagtail-specific code per se.

**Comment by Nigel2392** [comment]
> I think the 'why' part of your question would be because the method is from `django-treebeard`'s `MP_Node` class. So, it's not wagtail-specific code per se.

It might be an oversight - but it very much is wagtail specific.  
It is up to us to build upon the implementation that treebeard provides us. The method really doesn’t matter IMO; if we are walking down a tree - any tree, we should be able to do the same in reverse.  
Except that now we are given an opportunity to optimize and save the network IO and latency because we’ve already fetched it once.  
I understand it can easily be overlooked. No one can think about everything all the time - and it might even seem counterintuitive.

Anyways, just wanted to bring it to attention.

**Comment by Chiemezuo** [comment]
Cheers @Nigel2392 
It's a good topic for discussion.

**Comment by ababic** [comment]
@Nigel2392 in response to your question... 
> If we're worrying about memory usage - should we really be writing Python with Wagtail when you can write something for your specific goals in for example Golang, and save (at least) 10x the memory?
I'm guessing this is in response to my point about wasted database queries and memory, which I made in response to the original issue, which is redundant since we clarified things. But, did you just volunteer to reimplement Wagtail in Golang?? 😉

**Comment by Nigel2392** [comment]
> @Nigel2392 in response to your question... 
> 
> > If we're worrying about memory usage - should we really be writing Python with Wagtail when you can write something for your specific goals in for example Golang, and save (at least) 10x the memory?
> 
> 
> 
> I'm guessing this is in response to my point about wasted database queries and memory, which I made in response to the original issue, which is redundant since we clarified things. But, did you just volunteer to reimplement Wagtail in Golang?? 😉
> 
> 

I have been dreaming of this for months. Sadly don't do Go for work - feel I've come a good way with my Go-Django project ❤️

**Comment by ababic** [comment]
@Nigel2392 Would you be interested in submitting a PR for this (the `route()` view optimisation)? The change seems pretty uncontroversial to me.

**Comment by gasman** [comment]
Completed in #11737
