### ISSUE TITLE
When on 5.2 LTS should we see upgrade notices for non-LTS 6.0 version

### ISSUE THREAD

**Issue by robvdl** [wagtail/wagtail#11632]
### Issue Summary

5.2 was meant to be a LTS version, so I am not expecting to see an upgrade notice for 6.0, but only for 5.2.x

### Steps to Reproduce

1. Have a Wagtail 5.2.3 LTS site
2. Wagtail 6.0 upgrade notice shows on dashboard

Is there a way to say in settings.py "I am sticking to the LTS for a while" and not see 6.0 upgrade notices?

### Technical details

-   Python 3.11
-   Django 4.2 LTS
-   Wagtai 5.2.3
-   Chrome 121

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by robvdl** [comment]
It's not really a bug, but I am not sure if anyone has ever asked this. 5.2 was meant to be an LTS version and I currently can't move to 6.0 yet, but I don't want customers to constantly see the upgrade notice for 6.0.

When on an LTS version I would expect it to only show 5.2.x releases.

**Comment by gasman** [comment]
See https://docs.wagtail.org/en/stable/reference/settings.html#wagtail-enable-update-check - you should set `WAGTAIL_ENABLE_UPDATE_CHECK = "lts"`.
