### ISSUE TITLE
Wagtail Documentation favicon icon is missing (Not Found)

### ISSUE THREAD

**Issue by dostogircse171** [wagtail/wagtail#11630]
### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/stable/getting_started/index.html
https://docs.wagtail.org/en/stable/getting_started/tutorial.html
https://docs.wagtail.org/en/stable/reference/index.html
https://docs.wagtail.org/en/stable/reference/pages/index.html

The issue persists in all the pages of documentation. 

### Details

Wagtail has a nice favicon as per the logo which is displayed fine on this page of the documentation https://docs.wagtail.org/en/stable/
But on all the other pages the favicon is missing and not showing on the tab of chrome or any other browser tabs. When I checked the page source I found the favicon.ico is linked via `<link rel="shortcut icon" href="../../_static/favicon.ico" />` and this is going to https://docs.wagtail.org/en/_static/favicon.ico which is Not Found! 
When I checked other sources for example CSS or logo image I found that is sourced like `src="../_static/img/wagtail-logo-new.svg` and takes to https://docs.wagtail.org/en/stable/_static/img/wagtail-logo-new.svg which is correct. 

The difference between the favicon going 404 and the logo being available is that the favicon icon source is '../../_static' with an extra `../` which needs to be removed. 

<img src="https://img001.prntscr.com/file/img001/zEYpfzNSQHqssOSc2_naxg.png" width="500">

### Working on this

It's a very minor fix and I already described the issue above. I could fix it but I am not sure exactly where in the documentation this favicon is coming from.

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by lb-** [comment]
Thanks @dostogircse171 - we'll keep this issue open but it also has been raised on the Sphinx theme. 

https://github.com/wagtail/sphinx-wagtail-theme/issues/281

We thought we had fixed it in time for 6.0 but it wasn't a full fix. 

Any suggestions for code changes or a PR would be appreciated on that repo if you have time. 

There is this PR up also that may fix it. https://github.com/wagtail/sphinx-wagtail-theme/pull/282

**Comment by dainik10** [comment]
Please Assign me this task

**Comment by arnit-coder** [comment]
> Please Assign me this task. I can solve this issue, please assign it to me.

Actually I am working on this issue. Have find the solution and will fix it as soon as possible.

**Comment by dainik10** [comment]
> > Please Assign me this task. I can solve this issue, please assign it to me.
> 
> Actually I am working on this issue. Have find the solution and will fix it as soon as possible.

Ohk Bro no issues you can give it a go if you figured this out. Thank you.

**Comment by laymonage** [comment]
This has been fixed in upstream https://github.com/wagtail/sphinx-wagtail-theme/pull/282

Once a new release of the `sphinx-wagtail-theme` package is out, I'll update our version in `setup.py` in #11660.
