### ISSUE TITLE
🎛️ Migrate `draftail.initEditor` inline script usage to leverage Stimulus `w-init` controller

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#11644]
> ℹ️ **Part of the [Stimulus 🎛️ RFC 78](https://github.com/wagtail/rfcs/pull/78)**

### Is your proposal related to a problem?

Our current approach for bootstrapping the Draftail editor (non-StreamField usage) relies on inline scripts.

https://github.com/wagtail/wagtail/blob/e03c41250776612468226597a077ba1fc2d9b865/wagtail/admin/templates/wagtailadmin/widgets/draftail_rich_text_area.html#L1

This approach is not CSP compliant and it would be good to find a better way to achieve the same goals.

### Describe the solution you'd like

We further enhance the existing Stimulus controller `InitController` that allows arbitrary events to be dispatches on the target element.

We will need a way to support arbitrary event `detail` being passed to the init events that are dispatched.

This would be very similar to the solution implemented for the comments initialisation, except that this may be initialised multiple times (so no need for `'once': true`). See https://github.com/wagtail/wagtail/issues/11287 & https://github.com/wagtail/wagtail/pull/11294

https://github.com/wagtail/wagtail/blob/e03c41250776612468226597a077ba1fc2d9b865/client/src/entrypoints/admin/comments.js#L341-L350

#### Part 1 - `InitController` add support for `detail` value

In the [`client/src/controllers/InitController.ts`](https://github.com/wagtail/wagtail/blob/main/client/src/controllers/InitController.ts) file.

* Add a new `detail` [Stimulus value](https://stimulus.hotwired.dev/reference/values) to the controller, this would be used with `data-w-init-detail-value='{"some": "json"}'`.
* Read out the detail value object in the `ready` method, something like `const detail = { ...(this.detailValue || {}) }; // Coerce to object`
* When dispatching both the `ready` event and the custom events, pass the `detail` object to those events.
* Add the removal of this attribute and other attributes in `remove` so that the initial data is not lying around in the DOM, example code below.
* Must have - unit tests added for this new functionality.
* Must have - update JSDoc for controller (including new example), methods and the `declare detailValue: Record<string, unknown>;` statement so that the code is well documented.
* Nice to have - add the ability for the `ready` event to have it's default prevented, returning early to stop the other events & removal.
* Nice to have - re-order the values to be in alpha order, in the `static values = {...` and the `declare` statements.

```ts
  remove() {
    const element = this.element;

    (this.constructor as typeof InitController).classes.forEach((key) => {
      element.removeAttribute(`data-${this.identifier}-${key}-class`);
    });

    Object.keys((this.constructor as typeof InitController).values).forEach(
      (key) => {
        element.removeAttribute(`data-${this.identifier}-${key}-value`);
      },
    );
   /// ... existing stuff 
```

#### Part 2 - Add support for an event listener to instantiate Draftail

In [`client/src/entrypoints/admin/draftail.js`](https://github.com/wagtail/wagtail/blob/main/client/src/entrypoints/admin/draftail.js) we will want to add the event listener to wrap the `initDraftail` function call.

Something like this.

```js
/**
 * Initialize a Draftail editor on a given element when the w-draftail:init event is fired.
 */
document.addEventListener('w-draftail:init', ({ detail = {}, target }) => {
  const id = target.id;
  if (!id) {
    throw new Error('w-draftail:init event must have a target with an id');
  }
  window.draftail.initEditor(`#${id}`, detail, document.currentScript);
});
```

#### Part 3 - Update the Django widget to use the new attributes

See [`wagtail/admin/rich_text/editors/draftail/__init__.py`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/rich_text/editors/draftail/__init__.py) and [`wagtail/admin/templates/wagtailadmin/widgets/draftail_rich_text_area.html`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/widgets/draftail_rich_text_area.html).

* Update the template to ONLY render the hidden field, `{% include 'django/forms/widgets/hidden.html' %}` and remove the `<script...` tags. We want to keep this template just in case other developers have customised this template for their own code.
* We will want to update the approach in this Widget to set the Stimulus data attributes and replace the way we are passing options, instead we will pass this as `w-init-detail-value`.
* Python unit tests may need to be updated to reflect the way this new behaviour works.

```
class DraftailRichTextArea(widgets.HiddenInput):
    template_name = "wagtailadmin/widgets/draftail_rich_text_area.html"
    # ...

    def __init__(self, *args, **kwargs):
        # ...
        default_attrs = {
            "data-draftail-input": True,
            # add the Stimulus attributes to the `default_attrs`
            "data-controller": "w-init",
            "data-w-init-event-value": "w-draftail:init",
        }
        attrs = kwargs.get("attrs")
        # ...

    # ... other methods

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        context["widget"]["attrs"]["data-w-init-detail-value"] = json.dumps(self.options) # update this line
        return context
```

### Describe alternatives you've considered

* We already have a `data-draftail-input` and may want to leverage that, or maybe change that, but this would require building out a new mutation observer OR changing the documentation. It's probably best to just leave this attribute usage as is and avoid the added code churn. We can revisit this later if needed.
* Maybe a discrete controller specific to Draftail, however, the init controller is so close to doing exactly what we need it makes sense to add one additional value to this instead.

### Additional context

* As noted above, this is very similar to the approach in See https://github.com/wagtail/wagtail/issues/11287 & https://github.com/wagtail/wagtail/pull/11294
* This issue is similar in goals to https://github.com/wagtail/wagtail/issues/11597 but taking an intentionally different approach to just leverage an existing controller.

### Working on this

* Anyone can contribute to this if they are able to work with Stimulus and create Jest tests, plus feel confident in modifying Python tests.
* View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by lb-** [comment]
@gasman  or @thibaudcolas - just wanted to see if you had any input or thoughts on this proposed approach.

I also wonder if we should rework the requirements on https://github.com/wagtail/wagtail/issues/11644 to be very similar, just add a `initBlock` event listener. Not trying to abstract to much but just thinking of other ways to tackle the same problems.

Hopefully with this issue and the block issue we will be inching closer to being able to make Wagtail CSP compliant.

**Comment by Chiemezuo** [comment]
Hi @lb- 
I'd like to give this one a go.

**Comment by lb-** [comment]
Go for it, have a read through and feel free to ask any questions on this issue.

**Comment by Chiemezuo** [comment]
For sure!
I'll ping you on slack in a few hours.
