### ISSUE TITLE
Block Publishers from publishing their own pages.

### ISSUE THREAD

**Issue by salvadormrf** [wagtail/wagtail#1164]
Add permissions to allow pages to be only published by other reviewers/publishers.

In some scenarios we need to prevent that pages are published by the same person, forcing to have one more person to do the review and publishing.

**Comment by thibaudcolas** [comment]
I see this has had no comment or reaction in 9 years. It’s an interesting idea but doesn’t have any traction, so I’ll close this now. If this has potential, please re-open with our current feature request template so we’re clearer on why this is needed.
