### ISSUE TITLE
wagtail_update_image_renditions documents invalid argument (possible typo)

### ISSUE THREAD

**Issue by jakeisonline** [wagtail/wagtail#11646]
Documentation for `wagtail_update_image_renditions` states that `–purge-only` can be used as an argument. However, this should likely be `--purge-only` (noting the extra `-`).

Attempting to execute `./manage.py wagtail_update_image_renditions -purge-only` will result in `error: unrecognized arguments: -purge-only`

### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/stable/reference/management_commands.html#wagtail-update-image-renditions

### Details

Simply changing from `-purge-only` to `--purge-only` would resolve the problem.

Or, potentially adding a sub-section within "wagtail_update_image_renditions" to document the argument, as per other commands within that same page.

**Comment by Beeram12** [comment]
Can I start doing this

**Comment by lb-** [comment]
Yes please. Go for it - thanks @Beeram12 

Be sure to run the correct command yourself and include a screenshot or similar of the console output with your PR. This way we know it's working as expected with whatever the updated docs will be.

**Comment by Beeram12** [comment]
Sure
