### ISSUE TITLE
Cannot configure model permissions after a `RenameModel` migration operation

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#11650]
### Issue Summary

Found while investigating #10982.

After renaming a model (the actual model, not just the verbose name) by changing the Python class name and running migrations (which will perform a `migrations.RenameModel` operation), it is impossible to configure the permissions for the model in Wagtail's Group create/edit view.

### Steps to Reproduce

1. Spin up a fresh bakerydemo (run the migrations and `load_initial_data`
2. Grant model permissions to a group, e.g. edit the Moderators group to have add, change, delete, publish, and view permissions on the Person snippet
   <img width="955" alt="image" src="https://github.com/wagtail/wagtail/assets/6379424/e329936e-c284-4575-af5c-c27ed54f8b21">
3. Rename the snippet model, e.g. rename the `Person` model class to `Author`
   - I have a branch with the rename here for quick testing: https://github.com/laymonage/bakerydemo/tree/person-author
4. Make and run the migrations
5. Run the server and sign in as a moderator
6. You no longer have permissions for the snippet (expected, as Django doesn't migrate the permissions https://code.djangoproject.com/ticket/27489)
   <img width="186" alt="image" src="https://github.com/wagtail/wagtail/assets/6379424/5613e171-15c8-4bf7-9b53-8c4571f50133">
7. Sign in as a superuser and edit the Moderators group again
8. Notice that all the boxes are still ticked <img width="955" alt="image" src="https://github.com/wagtail/wagtail/assets/6379424/11c4f7cf-b29c-4a04-9c71-011686347bf5">
9. If you try to clear out the boxes, save, and tick them again, it doesn't work either

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Django doesn't migrate the permissions. This means when you rename a model, all the old permission records still exist in the database. New permissions are generated using the new name when `migrate` finishes, so you end up with duplicate permission entries for the same content type. This is expected as it's the current Django behaviour.

However, the Wagtail UI should also reflect that fact. The boxes should become unticked and they should represent foreign keys to the new permission entries instead of the old one. The old permissions should be put into the "Custom permissions" column (ideally they should be hidden, but we can't determine whether they're from an old name or legit custom permissions).

This is not a regression from #11606. The issue exists both before and after that PR.

The reason for this is because the code naively checks for the first part of the permission codename (before `_`) and see if it's in a main list of actions we're expecting (`add`, `change`, etc.):

https://github.com/wagtail/wagtail/blob/bfa314d22fa0a9a6e8a8698f28a3872084c83378/wagtail/users/templatetags/wagtailusers_tags.py#L86-L95

It then puts the permission in a dictionary using the action as the key. This means if there are multiple matches for the same content type e.g. `add_person` and `add_author`, whatever processed last will be what's displayed by Wagtail. A potential fix would be to sort the permission objects by the id (the new permissions should be last). However, this isn't robust and just ignores the fact that there are multiple permissions.

As you may guess, this also causes any custom permissions for that model that start with the same action e.g. `change_something_else` to be incorrectly recognised as the main `change_author` permission.

### Fix

#11648 includes the fix for this issue by explicitly checking whether the codename is `{action}_{content_type.model}` for the main permissions. An active model is guaranteed to have one content type in the database, and the `model` field is also updated on a `RenameModel` operation.

(There may be cases where a content type exists without a model class, but this isn't an issue as long as we don't use `content_type.model_class()` and assuming the class exists.)

**Comment by laymonage** [comment]
Ah, just noticed that this was acknowledged in #9411.

So I guess this could be relabelled as an enhancement to support custom permissions with codenames that start with `change_` etc.

**Comment by gasman** [comment]
Fixed in #11667
