### ISSUE TITLE
Streamfield max_num validates on submission rather than blocking in frontend beforehand

### ISSUE THREAD

**Issue by A-Amen** [wagtail/wagtail#11669]
### Issue Summary

Streamfield max_num block count dict is allows adding more than 1 in admin panel, but will never validate.

### Steps to Reproduce

1. Add the line `block_counts={"block_name" : {"max_num" : 1}}` as an argument to any streamfield in Page.
2. Go to admin and try to edit page and add more than one blocks for which you edited the above argument.

I believe the intended behaviour is to have the frontend grey out the '+' buttons within the CMS after adding the max_num amount of blocks. This disables you from adding more blocks for that type, rather than validating that after submission.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes

### Technical details

-   Python version:  3.11.7
-   Django version: 5.0.1
-   Wagtail version: 5.2.3
-   Browser version: Chrome 119

**Comment by gasman** [comment]
Thanks for the report! There's an open issue discussing this at https://github.com/wagtail/wagtail/issues/9784.
