### ISSUE TITLE
ModelViewSet listing results are not horizontally scrollable even if table is larger than viewport

### ISSUE THREAD

**Issue by omialon** [wagtail/wagtail#11675]
### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Create a new model with a lot of fields (ex : 20 CharField with a max size at )
3. Create a ModelViewSet using this model and list all the fields to display on index

![image](https://github.com/wagtail/wagtail/assets/25825464/669bc3e6-9ea3-4cd4-aa8a-dd7a956ed60e)
As you can see the last cell is cut and I can't scroll to the right to see its content. (I can only zoom-out a lot to see the full table)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11.7
-   Django version: 4.2.9
-   Wagtail version: 6.0.1
-   Browser version: Firefox 122.0.1 & Chrome 120.0.6099.129

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by A-Amen** [comment]
Reproducible on 

Django : 4.1.13
Wagtail : 5.2
Python : 3.12.1
Chrome 121

One possible solution for your case is to override the template for listing following this on the documentation https://docs.wagtail.org/en/stable/extending/generic_views.html#templates . 

I was able to place a scrollbar by setting 'overflow-x:auto;' to the listing class div on the page, however I am not well versed in front end so do not take that as reliable.

**Comment by lb-** [comment]
I think we should set this as an enhancement, it would be nice to support this but maybe have it as an opt in feature.

There may also be some nice CSS solutions that allow for scrolling content only when it's really needed.

Ideally, tables should not be too wide and adding so many columns is not recommended, but I understand that real world usage will not be that simple.

**Comment by A-Amen** [comment]
> I think we should set this as an enhancement, it would be nice to support this but maybe have it as an opt in feature.
> 
> There may also be some nice CSS solutions that allow for scrolling content only when it's really needed.
> 
> Ideally, tables should not be too wide and adding so many columns is not recommended, but I understand that real world usage will not be that simple.

Ideally yes so many columns are not required but I have done some school/academic web projects that involve displaying a ton of student application data which include 18 or so columns, so it has its use cases. We didn't use any tables in those projects however.
