### ISSUE TITLE
get_sprite_hash() slows import time unnecessarily

### ISSUE THREAD

**Issue by adamchainz** [wagtail/wagtail#11680]
### Issue Summary

`wagtail.admin.urls.get_sprite_hash` calls the `sprite` view, which renders >100 icons. It showed up in a profile of a project’s system checks as taking ~100ms in my project, about 15% of the total time.

### Steps to Reproduce

With IPython:

```
$ ./manage.py shell
Python 3.12.2 (main, Feb 17 2024, 06:21:07) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.21.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %prun -s cumtime import wagtail.admin.urls
         925421 function calls (909183 primitive calls) in 0.414 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      100    0.001    0.000    1.169    0.012 __init__.py:1(<module>)
       15    0.000    0.000    0.471    0.031 views.py:1(<module>)
        5    0.000    0.000    0.454    0.091 urls.py:1(<module>)
...
        4    0.000    0.000    0.179    0.045 hooks.py:110(get_hooks)
        4    0.000    0.000    0.179    0.045 hooks.py:103(search_for_hooks)
    12/11    0.000    0.000    0.179    0.016 apps.py:16(get_app_submodules)
       10    0.000    0.000    0.178    0.018 wagtail_hooks.py:1(<module>)
        3    0.000    0.000    0.137    0.046 models.py:1(<module>)
        3    0.000    0.000    0.134    0.045 mixins.py:1(<module>)
        3    0.000    0.000    0.130    0.043 workbook.py:1(<module>)
2218/2105    0.015    0.000    0.111    0.000 {built-in method builtins.__build_class__}
        1    0.000    0.000    0.084    0.084 __init__.py:126(get_sprite_hash)
        1    0.000    0.000    0.084    0.084 home.py:377(sprite)
        1    0.000    0.000    0.083    0.083 home.py:354(icons)
      117    0.000    0.000    0.083    0.001 loader.py:52(render_to_string)
      117    0.000    0.000    0.081    0.001 loader.py:5(get_template)
```

This should work similarly on any Wagtail projcet.

### Technical details

-   Python version: 3.12
-   Django version: 5.0
-   Wagtail version: 6.0
-   Browser version: n/a

### Working on this

One idea: define the URL as taking any hash:

```py
    path("sprite-<str:hash>/", home.sprite, name="wagtailadmin_sprite"),
```

Then move the hashing into the `sprite()` view. The view should render the content, hash it, and compare with the hash from the URL path. If they don’t match, it can return a redirect.

This would need reworking of places that reverse `wagtailadmin_sprite`.

Alternatively, maybe the sprite view can be sped up. Django templates are fairly slow and rendering 100+ templates will always cost something. Perhaps the icons can be treated as pure strings instead.

---

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by zerolab** [comment]
@adamchainz thank you for this. We will investigate how to improve the sprite generation. Your ideas are most useful

**Comment by HamaBarhamou** [comment]
hi, i'm willing to work on the subject. i'll learn and discover what there is to know along the way.

**Comment by adamchainz** [comment]
Can you defer calculating the template and hash, at least away from import time? You will probably still need to do it during the render of a referring page, but at least it won’t run during every reload of `runserver`, management command, etc.

**Comment by RealOrangeOne** [comment]
We do it this way so the regular `reverse` mechanics still work, replacing them could be a breaking change. 

We currently append a hash based on the Wagtail version as a querystring param for the rest of the admin's static assets. We could move the hash to the querystring, and redirect when one isn't provided. That way anyone matching on `reverse` wouldn't notice a change, old references would still work, and we can move the hash calculation to a cached template tag. That'd move the overhead from import time to the first request, which _I guess_ is better.
