### ISSUE TITLE
Date format in mails rendered by `EmailFormMixin` are not localized due to wrong call of  `date_format`

### ISSUE THREAD

**Issue by maqnius** [wagtail/wagtail#11696]
### Issue Summary

Dates rendered via `EmailFormMixin.render_email()` are not localized.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit settings to use eg. german localization

```python
LANGUAGE_CODE = "de-de"
USE_I18N = True
USE_L10N = True
```

3. [Implement form page using EmailFormMixin](https://docs.wagtail.org/en/stable/reference/contrib/forms/customisation.html#using-formmixin-or-emailformmixin-to-use-with-other-page-subclasses)
4. Create form page with date or datetime fields
5. Check notification mails send after submit and find `m/d/Y` instead of the german format `d.m.Y.`

### Fix

The bug is due to the call of `date_format` in `wagtail/contrib/forms/models.py`.

Instead of 

```python
if isinstance(value, datetime.datetime):
    value = date_format(value, settings.SHORT_DATETIME_FORMAT)
elif isinstance(value, datetime.date):
    value = date_format(value, settings.SHORT_DATE_FORMAT)
```

it should be

```python
if isinstance(value, datetime.datetime):
    value = date_format(value, "SHORT_DATETIME_FORMAT")
elif isinstance(value, datetime.date):
    value = date_format(value, "SHORT_DATE_FORMAT")
```
I guess it is quite straight forward, so I'll will open a pr soon.

**Comment by shutupatul** [comment]
I'd love to fix this bug.
