### ISSUE TITLE
Unwanted left column padding in listings with chooser modals

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#11704]
### Issue Summary

Chooser listings appear to have an unwanted padding.

<img width="1643" alt="Screenshot 2024-02-28 at 8 35 54 pm" src="https://github.com/wagtail/wagtail/assets/1396140/cbd25122-f691-49d0-bb19-2c7f1d516cc9">

### Steps to Reproduce

1. Open any page editor where the page model has RichText enabled
2. Navigate to the RichText field
3. Select to add a link
4. Observe in the chooser modal that there is a large amount of additional padding on the left column
5. Expected: This padding should not be there.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

-  Wagtail version: 6.1a
-  See file `client/scss/components/_listing.scss`, somewhere around the lines indicated below
- This nested usage of not/has is overly complex and may need to be reviewed across all usage of listings
- Possibly from this commit 81ea6d6266f72bc313bf4358cbc8f16eca8ed472 / #11332

https://github.com/wagtail/wagtail/blob/bded2cb98bef3dacb5b39ba739496a9101885fec/client/scss/components/_listing.scss#L612-L626

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

Be sure to fully understand the impact of any changes here with nested usage of `not` `has` and other selectors, plus the listings are used within modals and outside of modals.

**Comment by laymonage** [comment]
Thank you! I can confirm this, and yeah it does seem to be a regression from the PR.

<img width="1084" alt="image" src="https://github.com/wagtail/wagtail/assets/6379424/b9add117-2d37-4da1-8294-81b6490024c3">


On another note, I also noticed that there might be another regression from #1150 when the side panel is opened:

<img width="1432" alt="image" src="https://github.com/wagtail/wagtail/assets/6379424/7ca13e38-d2f9-49bf-a13f-9df54bceced0">

**Comment by laymonage** [comment]
Oh, sorry, just noticed that you've opened #11703 for the other issue. Thanks!
