### ISSUE TITLE
get_add_url() value in IndexView overriden by client side LinkController

### ISSUE THREAD

**Issue by bezidejni** [wagtail/wagtail#11726]
### Issue Summary

I'm trying to override `get_add_url()` method on snippets `IndexView` to include the URL query parameter of the currently active parent FK filter in the list view, in order to prepopulate the parent field on the add form.

This indeed works on the backend and when looking at the page source, the correct URL is set on the add button, but [LinkController](https://github.com/wagtail/wagtail/blob/main/client/src/controllers/LinkController.ts#L11C14-L11C28) strips those query parameters and overwrites the link.

### Steps to Reproduce

models.py
```py
import uuid
from django.db import models

# Create your models here.
class Parent(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    title = models.CharField(max_length=100)


class Child(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    title = models.CharField(max_length=100)
    parent = models.ForeignKey(Parent, on_delete=models.CASCADE)

```

wagtail_hooks.py
```py
from wagtail.admin.utils import set_query_params
from wagtail.snippets.models import register_snippet
from wagtail.snippets.views.snippets import (
    IndexView,
    SnippetViewSet,
)


from .models import Child, Parent

class PrefilledParentIndexView(IndexView):

    def get_add_url(self):
        add_url = super().get_add_url()
        if self.filters.data.get("parent"):
            add_url = set_query_params(
                add_url, {"parent": self.filters.data["parent"]}
            )
        return add_url


class ParentViewSet(SnippetViewSet):
    model = Parent

class ChildViewSet(SnippetViewSet):
    model = Child
    list_filter = ["parent"]
    index_view_class = PrefilledParentIndexView


register_snippet(ChildViewSet)
register_snippet(ParentViewSet)

```

You can find the whole project [here](https://github.com/bezidejni/get_add_url_repro).

Steps to reproduce:
1. Set up the project
2. Go into the admin panel and create a new parent
3. Go into the child index view and turn on the filter by parent, adding `?parent=<parent_uuid>` to the URL.
4. Click on the "add" button.
5. I would expect that the URL I'm taken to is `/admin/snippets/bug/child/add/?parent=<parent_uuid>`, but is `/admin/snippets/bug/child/add/` instead.

In general, I would expect whatever I set in `get_add_url()` to be, in fact, the URL that's set in the UI.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: Python 3.10.4
-   Django version: Version: 5.0.3
-   Wagtail version: Version: 6.0.1
-   Browser version: https://www.whatsmybrowser.org/b/HMGAR

### Working on this

Unfortunately at this time, I don't have enough time and probably not enough JS skills to work on this.

**Comment by laymonage** [comment]
Hi, this is expected. The reason why we resorted to client-side updates for the add link is because the listing results get refreshed via AJAX as you apply search/filtering, so we need to have a way to reflect the filters query params to the add URL on the client side.

Looking at your configuration, you should be able to fix this by overriding `header_buttons` on the `IndexView` class so that the `parent` key is reflected:

https://github.com/wagtail/wagtail/blob/caf9142c5dac1fbd8555569f2d30c187ba4dd740/wagtail/admin/views/generic/models.py#L328-L340

e.g.

```diff
     @cached_property
     def header_buttons(self):
         buttons = []
         if self.add_url:
             buttons.append(
                 HeaderButton(
                     self.add_item_label,
                     url=self.add_url,
                     icon_name="plus",
-                    attrs={"data-w-link-reflect-keys-value": '["locale"]'},
+                    attrs={"data-w-link-reflect-keys-value": '["parent"]'},
                 )
             )
         return buttons
```

You can verify that when the `parent` filter value is changed in the filter popup, the add URL will also be updated to reflect the `parent` URL param.

For completeness sake, if you have URL params in the `add_url` that you want to preserve regardless of what happens after filtering, you can add `"data-w-link-preserve-keys-value"` to the `attrs`. Any keys specified in this list will never be removed/updated on the client side.

**Comment by bezidejni** [comment]
Hi @laymonage , thanks for the quick reply and the solution to this!

If this is the intended behavior, it might be good to add a note to the documentation indicating that as it's not really quite clear right away why the link is being overwritten, and what's the relationship between the default add_url and the client side code.

**Comment by bezidejni** [comment]
> Although now that you mention it, perhaps we should change the default behaviour of the controller to use the keys of the params that are in the URL (at the time the controller is loaded) as the default value for preserve-keys. That way, as long as the server adds the params to the initial link, they will be updated when the listing is refreshed (provided the filter uses the same URL param key). This should make the header_buttons override unnecessary, which makes it easier to upgrade.

That seems like a great solution, I think this is a good default behavior that would be expected from a user.
