### ISSUE TITLE
Document chooser doesn't work in ModelViewSet

### ISSUE THREAD

**Issue by seb-b** [wagtail/wagtail#11739]
### Issue Summary

In the release notes for 6.0 it was mentioned that panel definitions can be used with `ModelViewSet`s, when I try to use a document chooser there's JS errors and the modal won't open. Works fine with a `SnippetViewSet` but I'm trying not to use them as the term snippet appearing in urls and title tags is causing a lot of confusion for our users.

### Steps to Reproduce

```python
# models.py
class Resource(models.Model):
    file = models.ForeignKey(
        "wagtaildocs.Document", on_delete=models.CASCADE, related_name="+"
    )

    panels = [FieldPanel("file")]


# wagtail_hooks.py
from wagtail import hooks
from wagtail.admin.viewsets.model import ModelViewSet

from .models import Resource


class ResourceViewSet(ModelViewSet):
    icon = "doc-full"
    model = Resource
    add_to_admin_menu = True


@hooks.register("register_admin_viewset")
def register_resource_viewset():
    return ResourceViewSet()
```

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11
-   Django version: 4.2
-   Wagtail version: 6.0
-   Browser version: Firefox latest, Chromium latest

**Comment by lb-** [comment]
I wonder if this will already be fixed by https://github.com/wagtail/wagtail/pull/11620

That PR added the JS for modal workflow to all admin pages, not just those that randomly happened to include the `editor_js_html` shared include.

I have not tested but it would be good to review of this can be reproduced in the latest `main` branch.

**Comment by seb-b** [comment]
Can confirm that this issue can't be reproduced in the latest main branch

**Comment by lb-** [comment]
Thanks @seb-b I'll close as fixed by https://github.com/wagtail/wagtail/pull/11620

**Comment by laymonage** [comment]
It's a new feature in Wagtail 6.0 though, so we may want to backport (a simpler solution) to the `stable/6.0.x` branch for the next patch release.

**Comment by lb-** [comment]
My understanding is that the Chooser Workflow support was never there, (in ModelViewSets) you would have had to import the right JS. 

So it's not really a regression, but rather a new feature to better support Choosers throughout the admin.

**Comment by lb-** [comment]
We could just add a comment as to what to do to include this JS on this issue. It's probably not a huge thing to workaround in any code on 6.0 or earlier.

Not at my laptop now but can look at that later.

**Comment by seb-b** [comment]
From my reading of the release notes I expected this to work out of the box, as far as I know there's no easy way to insert extra js into a `ModelViewSet` without overriding the template, it'd be great if this could be backported

**Comment by lb-** [comment]
OK I think we can cherry pick 266faf63c2967f01c7be01afb0fdaf92bc77c5c4 and that should allow choosers across any admin views to work.

I will prep a PR.
