### ISSUE TITLE
Clearing database + deleting all migrations is not enough to reset wagtail app. Needs removal of venv.

### ISSUE THREAD

**Issue by mjmare** [wagtail/wagtail#11743]
I'm trying to upgrade an app to Wagtail 6.0.1+Django 5.02+python 3.12.2, and it is not going well. 

In the process to find the root cause I need to frequently reset the sqlite database and remove all migrations. I expected that after nuking everything, even my custom Pages, that a migration would result in a clean environment. 
Instead I get this error: 
```
django.core.exceptions.FieldDoesNotExist: NewQueryDailyHits has no field named 'query'
```

The only way to 'fix' this is to recreate the venv. Then makemigrations+migrate will work again. 
I can't say I'm quite sure why this happens, but haven't had this with other Django packages. 

Any suggestions welcome.

**Comment by lb-** [comment]
I think your issue may be the same or similar to https://github.com/wagtail/wagtail/issues/11690

See the documentation update here https://github.com/wagtail/wagtail/pull/11712

Sorry this has caused you frustration. Please have a look at the PR and see if updating your installed apps makes a difference.

**Comment by mjmare** [comment]
Yes, thank you. I can confirm that adding `wagtail.contrib.search_promotions` to the installed apps fixes the problem.

**Comment by lb-** [comment]
Thanks. I'll close this issue then.
