### ISSUE TITLE
Index filters visible in ModelViewSet history view

### ISSUE THREAD

**Issue by seb-b** [wagtail/wagtail#11753]
### Issue Summary

The index filters are visible in a ModelViewSet's history. It might be in other mixin views, this was just the one I noticed. They don't do anything when clicked except update the url 

![image](https://github.com/wagtail/wagtail/assets/1635388/60a70ed0-b5f4-4eb9-a9d7-06bd4e986546)

### Steps to Reproduce

```python
# models.py
from wagtail.models import RevisionMixin

class Product(RevisionMixin):
    name = models.CharField(max_length=255)
    in_stock = models.BooleanField()
    
    panels = [
        FieldPanel('name'),
        FieldPanel('in_stock')
    ]
    
 # wagtail_hooks.py
 from wagtail.admin.viewsets.model import ModelViewSet
 from .models import Product
 
 class ProductViewSet(ModelViewSet):
    model = Product
    list_filter = ('in_stock',)
  
# register viewset via the hook
```   

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: 3.11
-   Django version: 4.2
-   Wagtail version: 6.0.1

**Comment by laymonage** [comment]
Thanks for the report, but I wasn't able to replicate this with a fresh Wagtail project and the given model and the following viewset registered:

```py
from wagtail import hooks
from wagtail.admin.viewsets.model import ModelViewSet
from .models import Product


class ProductViewSet(ModelViewSet):
    model = Product
    list_filter = ("in_stock",)
    add_to_admin_menu = True
    icon = "pick"


# register viewset via the hook
@hooks.register("register_admin_viewset")
def register_product_viewset():
    return ProductViewSet("products")
```

The history view shows the filters for the log actions and can be used to filter the listing:

<img width="1110" alt="image" src="https://github.com/wagtail/wagtail/assets/6379424/6b986834-6503-43c4-9cff-9f3d6a3d47a2">

If you encounter this issue, perhaps check whether you pass the viewset's `list_filter` to the history view, e.g. via `get_history_view_kwargs`, `get_common_view_kwargs`, or the `history_view` property. Passing a `list_filter` to the HistoryView could give you unexpected behaviour.

**Comment by seb-b** [comment]
ah my mistake, I didn't realise these filters were for filtering the history view and got a bit mixed up. I'll close this
