### ISSUE TITLE
`ModelIndexView` does not work with custom object managers

### ISSUE THREAD

**Issue by jhonatan-lopes** [wagtail/wagtail#11765]
### Issue Summary

In `ModelIndexView._get_snippet_types`, the `count` is done by accessing `model.objects.all().count()`. This does not work with models that have a default manager that is not `objects`.

When registering a model as a snippet that defines a custom default manager with a name different than `objects` it will throw an exception. In our case:

```
AttributeError: type object 'ParserError' has no attribute 'objects'
(4 additional frame(s) were not displayed)
...
  File "wagtail/admin/auth.py", line 165, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "django/views/generic/base.py", line 98, in view
    self.setup(request, *args, **kwargs)
  File "wagtail/snippets/views/snippets.py", line 85, in setup
    self.snippet_types = self._get_snippet_types()
  File "wagtail/snippets/views/snippets.py", line 88, in _get_snippet_types
    return [
  File "wagtail/snippets/views/snippets.py", line 91, in <listcomp>
    "count": model.objects.all().count(),
```

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Add a new model that has a manager not named "objects" (see example below)
3. Register that model as a snippet
4. Go to snippets view
5. See error

```py
from django.db import models
from wagtail.snippets.models import register_snippet

class ParserErrorManager(models.Manager):
   pass

@register_snippet
class ParserError(models.Model):
   err_msg = models.CharField(max_length=250)

    errors = ParserErrorManager()
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: 3.10.
-   Django version: 4.2.8.
-   Wagtail version: 5.2.3.
-   Browser version: https://www.whatsmybrowser.org/b/RFN3C

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by laymonage** [comment]
Thanks! I can confirm the issue.

<img width="507" alt="image" src="https://github.com/wagtail/wagtail/assets/6379424/6fbc8198-18ad-4ddb-9107-049caced37a7">
