### ISSUE TITLE
wagtail command doesn't work

### ISSUE THREAD

**Issue by eliasfinn251** [wagtail/wagtail#11849]
### Issue Summary
Firstly, I attempted to install wagtail from source the usual way :
pip install -e ."[testing,docs]" -U

But it always returned TypeError : excepted string or bytes.
I then tried to reinstall python and pip altogether.
Through many researches on stackoverflow, I found to try install with sudo.
Then It worked.

But when I do wagtail command, it returns :
```
Traceback (most recent call last):
  File "/usr/local/bin/wagtail", line 33, in <module>
    sys.exit(load_entry_point('wagtail', 'console_scripts', 'wagtail')())
  File "/usr/local/bin/wagtail", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

I desperate with Wagtail application for more than one month.
I'm hoping for your kind help please. Thanks community. 

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Edit models.py as follows...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: Run `python --version`.
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
Closing as this is a support query rather than a Wagtail bug report
