### ISSUE TITLE
The PostgresSearchBackend autocomplete and search functions do not return any results if the fields parameter is not provided.

### ISSUE THREAD

**Issue by itbabu** [wagtail/wagtail#11846]
### Issue Summary

I don't get any result if I don't explicitly pass the fields parameter to the search or autocomplete methods of PostgresSearchBackend.

I was debugging the AdminSnippetChooser  (no results after searching).

SearchFilterMixin
```python
   def filter(self, objects): 
        .....
        if search_query:
            search_backend = get_search_backend()
            if objects.model.get_autocomplete_search_fields():
                objects = search_backend.autocomplete(search_query, objects) # <--  here
        ....        
```
following the documentation it should work:
https://docs.wagtail.org/en/stable/topics/search/indexing.html#options

### Steps to Reproduce

example model
```python

class Season(Tmodels.Model, index.Indexed):
    """
    """
    title = models.CharField(_('title'), max_length=100, db_index=True)
    description = models.CharField(_('description'), max_length=300)
    
   search_fields = [
        index.SearchField('title'),
        index.AutocompleteField('title')
    ]
        
```

```python

from wagtail.search.backends import get_search_backend

s = get_search_backend()   # PostgresSearchBackend

s.autocomplete("spri", Season)  # it returns no results  <SearchResults []>
s.search("spri", Season)  # it returns no results  <SearchResults []>

s.autocomplete("spring", Season, fields=['title',])  # it returns <SearchResults [<Season: spring>]>
s.search("spring", Season, fields=['title',])  # it returns <SearchResults [<Season: spring>]>
```

### Technical details

-   Python version: Python 3.12.2
-   Django version: 5.0.4
-   Wagtail version: 6.0.2

**Comment by gasman** [comment]
Hi @itbabu,

Thanks for the report - however, I'm unable to reproduce this as described. From a fresh `wagtail start` project, I changed the database to `"django.db.backends.postgresql"`, then edited home/models.py to

```python
from django.db import models

from wagtail.models import Page
from wagtail.search import index
from wagtail.snippets.models import register_snippet
from django.utils.translation import gettext as _


class HomePage(Page):
    pass


@register_snippet
class Season(models.Model, index.Indexed):
    """
    """
    title = models.CharField(_('title'), max_length=100, db_index=True)
    description = models.CharField(_('description'), max_length=300)

    def __str__(self):
        return self.title

    search_fields = [
        index.SearchField('title'),
        index.AutocompleteField('title')
    ]
```

and ran `./manage.py makemigrations`, `./manage.py migrate`, `./manage.py createsuperuser`, `./manage.py runserver`.

I then logged in to the admin and created several Season snippets. Then, from `./manage.py shell`:

```
>>> from wagtail.search.backends import get_search_backend
>>> from home.models import Season
>>> s = get_search_backend()
>>> s
<wagtail.search.backends.database.postgres.postgres.PostgresSearchBackend object at 0x109b152e0>
>>> s.autocomplete("spri", Season)
<SearchResults [<Season: Spring>]>
```

Will close for now, but if you can provide reliable steps to reproduce, I'm happy to reopen and investigate further.

**Comment by itbabu** [comment]
Thanks, @gasman . 
After further debugging in ```wagtail.search.backends.database.postgres.postgres.ObjectIndexer```, I realized that the PostgreSQL full-text search indexes were broken. Running the ```wagtail_update_index``` command solved the issue.
