### ISSUE TITLE
Add ability to make a keyboard shortcut global with the Stimulus `KeyboardController`/`w-kbd`

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#11844]
### Is your proposal related to a problem?

Currently, the global shortcuts for saving the page or toggling the preview pane change behaviour when you are focused on a text field.

![Screenshot 2024-04-13 at 12 30 27 pm](https://github.com/wagtail/wagtail/assets/1396140/69be8bae-18f8-48d6-9ef9-7d7127326583)

For example, when editing a page, `cmd + s` will save the page normally (as in save the new edited page to the CMS database) but if you are focused on a text input field it will fall-back to the browser behaviour and try to save the HTML of the current page to your downloads folder.

![Screenshot 2024-04-13 at 12 33 06 pm](https://github.com/wagtail/wagtail/assets/1396140/53bad0ca-e3a9-4a25-bae0-f87a50ae986a)

Similarly, the `cmd + p` will try to print the page when focused on a text input instead of toggling the preview pane.

![Screenshot 2024-04-13 at 12 32 57 pm](https://github.com/wagtail/wagtail/assets/1396140/b3ce6922-30c7-4907-bda5-509e492c216b)

### Describe the solution you'd like

I have assumed we do not want to avoid conflicting shortctuts with the browser, the `cmd+s` and `cmd+p` usage conflicts with the browser's normal behaviour. This is probably OK as the user is very unlikely to mean 'save html to the desktop' and 'print the view', plus these shortcuts have been in use for many years so we do not want to change that.

Instead, I recommend we enhance the newly introduced ( https://github.com/wagtail/wagtail/pull/11740 ) Stimulus `KeyboardController` to allow for a 'scope' to be set to global.

Introducing a new Stimulus value `scope` as a String would allow the current behaviour to be defaulted to an empty string and allow for a new `global` scope to be introduced as part of this change.

#### Example of current state

```html
<button type="submit" class="button action-save" data-controller="w-kbd" data-w-kbd-key-value="mod+s">
    Save draft
</button>
```

#### Example of proposed usage

```html
<button type="submit" class="button action-save" data-controller="w-kbd" data-w-kbd-key-value="mod+s" data-w-kbd-scope-value="global">
    Save draft
</button>
```

#### Code approach (suggested)

We would add a new package https://www.npmjs.com/package/bind-mousetrap-global that is the recommended MouseTrap way to do this.

```diff
# ... other imports
++import addGlobalBinds from 'bind-mousetrap-global';
++
++addGlobalBinds(Mousetrap);

# ... other stuff
export class KeyboardController extends Controller<
  HTMLButtonElement | HTMLAnchorElement
> {
  static values = {
    key: { default: '', type: String },
++    scope: { default: '', type: String },
  };

  /** Keyboard shortcut string. */
  declare keyValue: string;
++  /** Scope of the keyboard shortcut, defaults to the normal MouseTrap (non-input) scope. */
++  declare scopeValue: '' | 'global';

# ... other stuff
  keyValueChanged(key: string, previousKey: string) {
    if (previousKey && previousKey !== key) {
      Mousetrap.unbind(previousKey);
    }

--    Mousetrap.bind(key, this.handleKey);
++    if (this.scopeValue === 'global') {
++      Mousetrap.bindGlobal(key, this.handleKey);
++    } else {
++      Mousetrap.bind(key, this.handleKey);
++    }
  }
}
```

### Describe alternatives you've considered

* As noted above, we could avoid risky global keyboard shortcuts but that seems unhelpful.
* We could leave this as is but as we want to communicate keyboard shortcuts more I recommend we make the behaviour the same for suitable shortcuts.

### Additional context

* See https://github.com/wagtail/wagtail/pull/11740 for the addition of the Stimulus controller approach
* See https://github.com/wagtail/wagtail/issues/3949 for the main issue covering the longer term goals for keyboard shortcuts

### Working on this

* Anyone can contribute to this.
* JavaScript unit tests are a must for this new behaviour
* All existing `mod+s` (save) and `mod+p` preview panel shortcuts MUST be updated to use this new behaviour.
* View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by NXPY123** [comment]
I'll look into this
