### ISSUE TITLE
Redirect to unstyled search results page after completing editorial action on page

### ISSUE THREAD

**Issue by alxbridge** [wagtail/wagtail#11856]
### Issue Summary

When doing an admin-wide search, results pulled in via XMLHttpRequest use an incorrect `next` querystring parameter in their action links. This means that editors are brought to an unstyled search results page on completing their action.

### Steps to Reproduce

1. Start a new project and create test content which can be searched for
2. Navigate to _/admin/pages/search/_
3. Enter a search query into the box at the top of the page
4. Open the `...` action menu for one of the search results, and choose the _Edit_ (*) action.
5. Edit the page and publish it
6. The browser is redirected to  _/admin/pages/search/results/_, which is unstyled.
  - Expected behaviour: the `next` parameter ends the action journey on _/admin/pages/search/_.

(*also applies to any action which sets a `next` parameter in its link querystring)

Screenshots

![Screenshot from 2024-04-17 12-14-58](https://github.com/wagtail/wagtail/assets/8955716/0859cf7a-2016-4fc1-97ee-0375060fb78f)

![Screenshot from 2024-04-17 12-10-26](https://github.com/wagtail/wagtail/assets/8955716/7ff92e50-9016-4a07-8650-9a5efe8b082c)

This appears to be similar to https://github.com/wagtail/wagtail/issues/11177

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10.12
-   Django version: 5.0.3
-   Wagtail version: 6.0.2
-   Browser version: Firefox 125.0

**Comment by gasman** [comment]
Confirmed on current main branch.

**Comment by gasman** [comment]
Fixed in #11881
