### ISSUE TITLE
Issue with Missing Static Files in Wagtail 6.0.2 with DEBUG=False

### ISSUE THREAD

**Issue by alyrace** [wagtail/wagtail#11866]
Similar to #11643 

If DEBUG is False, have to collectstatic first.

For one site where I had upgraded from 5.2 and collected static beforehand. There was no issue then when upgrading to 6.0.1 and then 6.0.2.

However when from 3.0 to 6.0.2 for another site, received that error, when collectstatic was not run beforehand with DEBUG false.

**Comment by gasman** [comment]
Sorry, there's not enough detail here for us to work with - we need to know exactly what the error is and when it occurs, not just that it's "similar" to a previous issue. Please open a new issue, providing all the information requested in the issue template.
