### ISSUE TITLE
Inheritance does not work for StructBlock attributes

### ISSUE THREAD

**Issue by pupattan** [wagtail/wagtail#11877]
### Issue Summary
Inheritance does not work for StructBlock attributes

### Steps to Reproduce
Please find the code 
```
class GridSizePosition(blocks.StructBlock):
    width = blocks.ChoiceBlock(choices=[
        ('narrow', 'Narrow'),
        ('wide', 'Wide'),
    ])
    position = blocks.ChoiceBlock(choices=[
        ('left', 'Left'),
        ('right', 'Right'),
    ])


class ImageBlock(blocks.StructBlock, GridSizePosition):
    image = ImageChooserBlock(required=False)
```
Here for ImageBlock when used in streamfield, does not show width , position attributes

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: Run `python --version`. Python 3.10.5
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`. 5.0.4
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`. 6.0.2
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out. Chrome 124

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
You don't need `blocks.StructBlock` in the definition of ImageBlock - it should be

    class ImageBlock(GridSizePosition):

If you make that change, does it fix the problem?

**Comment by pupattan** [comment]
Working fine. But width, position shows before image field

**Comment by gasman** [comment]
Thanks for confirming. There's an existing open PR at #8504 dealing with specifying the ordering of blocks when inheritance is in use.
