### ISSUE TITLE
6.1rc1. Strange positioning of the language label on dashboard or page explorer

### ISSUE THREAD

**Issue by ACK1D** [wagtail/wagtail#11875]
### Issue Summary

In the dashboard or page explorer for long titles or when zooming in the browser or for small screens, the language label hangs next to the "Actions" button, which looks weird and broken.

![w1](https://github.com/wagtail/wagtail/assets/63553768/73e2afdb-9db3-45c0-bd2c-914ddf601f4a)
![wbd2](https://github.com/wagtail/wagtail/assets/63553768/c83ff6c5-1e14-4a69-a94a-5e9d2e0809b8)

### Steps to Reproduce

1. Run https://gitpod.io/#https://github.com/wagtail/bakerydemo/
2. Update Wagtail to 6.1rc1
3. Make long title in " Welcome to the Wagtail Bakery!" page and save changes

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.12.2
-   Django version: 5.0.4
-   Wagtail version: 6.1rc1
-   Browser version: Firefox 126

**Comment by thibaudcolas** [comment]
Thank you @ACK1D! This has been fixed and will be working properly in the final release of v6.1.
