### ISSUE TITLE
Duplicate button on the block header is always active when the max_num in the ListBlock is reached.

### ISSUE THREAD

**Issue by msochel** [wagtail/wagtail#11897]
### Issue Summary

It is possible to add multiple blocks to a ListBlock using the duplicate functionality even when the max_num limit has already been reached. It is important to mention that when the page is saved, an error message is thrown indicating that the max_num has been exceeded.

### Steps to Reproduce

Taking as reference the site bakarydemo

1. Go to edit a recipe page
2. Step list has a configuration of 10 maximum items to add
3. The icon duplicate is always active although the plus icons are disabled when the limit is reached

https://github.com/wagtail/wagtail/assets/19751214/2ff2bbea-20b3-46d7-84cc-184a04ae4ee9

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: 3.9.16.
-   Django version: 4.2.9.
-   Wagtail version: 5.2.3.
-   Browser version: Multiple browsers

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
Thanks for the report! This is covered by #9513.
