### ISSUE TITLE
Add Accessibility section on prefers-reduced-motion

### ISSUE THREAD

**Issue by CharlesBelov** [wagtail/wagtail#11890]
### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/stable/advanced_topics/accessibility_considerations.html#content-modeling

### Details

It would be good for the Accessibility page to have a section on prefers-reduced-motion.

Respect for prefers-reduced-motion is not required by WCAG 2.0-2.2, but is a best practice. If the website visitor or editor has set their OS to indicate they don't want animation, the site doesn't serve them cosmetic animation. Supported by Chrome, Safari, Firefox.

Note: The word "reduced" is an artifact of Apple using the terminology "reduce motion" in iOS and macOS before other operating systems implemented this feature. In Windows and Android the settings terminology implies all or nothing, but is actually the same signal to browsers.

**Comment by thibaudcolas** [comment]
Done in #12038
