### ISSUE TITLE
styleguide - Wagtail javascript does not load

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail#11896]
### Issue Summary

The wagtail javascript (I'm guessing the telepath libraries?) does not load when viewing the style guide. There are several related javascript errors in the console:

```javascript
styleguide/:1745 Uncaught TypeError: Cannot read properties of undefined (reading 'initEditor')
    at styleguide/:1745:25
(anonymous) @ styleguide/:1745
styleguide/:1867 Uncaught ReferenceError: initDateChooser is not defined
    at styleguide/:1867:9
(anonymous) @ styleguide/:1867
styleguide/:1909 Uncaught ReferenceError: initTimeChooser is not defined
    at styleguide/:1909:9
(anonymous) @ styleguide/:1909
styleguide/:1951 Uncaught ReferenceError: initDateTimeChooser is not defined
    at styleguide/:1951:9
(anonymous) @ styleguide/:1951
styleguide/:2458 Uncaught ReferenceError: PageChooser is not defined
    at styleguide/:2458:9
(anonymous) @ styleguide/:2458
styleguide/:2571 Uncaught ReferenceError: ImageChooser is not defined
    at styleguide/:2571:9
(anonymous) @ styleguide/:2571
styleguide/:2685 Uncaught ReferenceError: DocumentChooser is not defined
    at styleguide/:2685:9
(anonymous) @ styleguide/:2685
styleguide/:2799 Uncaught ReferenceError: SnippetChooser is not defined
    at styleguide/:2799:9
```

The wagtail widgets that rely on these (including the draftail editor) do not load as a result.

![image](https://github.com/wagtail/wagtail/assets/72310199/8123aeff-4651-41bf-896f-2d15db0c2ada)

In the extra_js block is a call to render `{{ example_form.media.js }}` - this attribute is empty when rendering the style guide. May be the cause?

### Steps to Reproduce

No special steps needed to reproduce. Default behaviour with Wagtail 6.0.x

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.12
-   Django version: 4.2.7
-   Wagtail version: 6.0.2
-   Browser version: Chrome 124

**Comment by gasman** [comment]
Fixed in #11902
