### ISSUE TITLE
Deleting form data

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#1190]
After enabling the form builder in Wagtail there is no way of clearing/deleting data from form submissions within the admin area. Ideally it would be good to be able to remove data one submission/line at a time, multiple specified lines, everything (though probably with some sort of robust warning system).

I guess a different solution would be to add some sort of archiving system with filters that would allow you to export different sets of data as .csv so that no data is actually ever deleted as such but that admin can make more sense of the data that has been collected.

**Comment by lb-** [comment]
@kaedroho I think this issue can be closed, it appears to be implemented now.

**Comment by timorieber** [comment]
At least with #3233 I think all requirements were implemented.
