### ISSUE TITLE
Improved Scheduling experience

### ISSUE THREAD

**Issue by luisvillalba** [wagtail/wagtail#11925]
### Is your proposal related to a problem?
We have received feedback from several of our authors that the scheduling experience is not intuitive, specifically, the fact that you have to set a publishing schedule and then that doesn't have any effect until you actually hit *Publish* is confusing and "slightly nerve-wrecking" as that can give the impression that it will get published immediately.

### Describe the solution you'd like
It'd be a lot more intuitive and predictable if there was a "Schedule" button that lets authors set the publishing schedule and doesn't require any further action for it to work.

### Describe alternatives you've considered
We have tried documenting the behavior and clarifying this on trainings but it does continue to be a constant source of confusion.

### Additional context
N/A

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by thibaudcolas** [comment]
Hi @luisvillalba, could you clarify what version of Wagtail you’re basing this feedback on?

We made a lot of changes to the scheduled publishing UX in Wagtail 5.1, with a very prominent _"This publishing schedule will only take effect after you select the 'Publish' option"_. I don’t think this leaves too much room for confusion?

![Set publishing schedule](https://github.com/wagtail/wagtail/assets/877585/733e3eb9-2f92-4829-a22e-0daa827981bb)

Even once the schedule has been saved, the UI says "Once published":

![Once published](https://github.com/wagtail/wagtail/assets/877585/eb5dd912-3389-41a0-9347-13f342fab2d4)

---

We considered what you describe as the ideal solution but decided against it, as it makes it impossible for an unpublished page to have its "go live" field set without also being scheduled.

Perhaps we could keep the current UX, but when a page has a saved schedule, change its "Publish" button label to "Schedule" or "Schedule for publishing"?

**Comment by gasman** [comment]
Closing due to lack of response.
