### ISSUE TITLE
CopyView stopped to work for Snippets on Wagtail 6.1

### ISSUE THREAD

**Issue by ducolares** [wagtail/wagtail#11940]
### Issue Summary

The copy functionality for snippets isn't working in Wagtail 6.1, although it works perfectly for pages.
I tested with a downgraded version, and it works fine.

### Steps to Reproduce

1. On Wagtail CMS, on a Index View, try to copy a snippet instance.
2. The form fields are blank on the CopyView.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)
Yes

### Technical details

-   Python version: 3.9
-   Django version: 4.2.6
-   Wagtail version:  6.1
-   Browser version: Chrome 124

**Comment by laymonage** [comment]
Thank you for the report! I can confirm this issue exists (and for `ModelViewSet` as well). It's a regression in ee57f6d4dc0724e11169672a31aa9c3557c0313a and (e1728f6d8fd99926de5028092d07f59fb387e8c4 for `stable/6.0.x`). We'll pick this up for 6.1.1.

Not sure if we'll put out a 6.0.4 release though, as it's technically out of support.

**Comment by nqcm** [comment]
I am testing it wit Wagtail 6.0.3 and the copy functionality is not working. It was working perfectly fine in 6.0.2
