### ISSUE TITLE
missing migration 0094_query_searchpromotion_querydailyhits.py

### ISSUE THREAD

**Issue by cesar-benjamin** [wagtail/wagtail#11941]
### Issue Summary

I'm working on a project and i notice that on migration the console told me that there is migrations that must be done, so i tried makemigrations and a new one in wagtail was created: 0094_query_searchpromotion_querydailyhits.py

this is a problem because i want to redistribute my project but if i try to make a fresh install i got this: 

django.db.migrations.exceptions.NodeNotFoundError: Migration xxx.0001_initial dependencies reference nonexistent parent node ('wagtailcore', '0094_query_searchpromotion_querydailyhits')

### Steps to Reproduce

1. make a fresh project
2. start  a new app
3. add a few models
4. do makemigrations

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: 3.11
-   Django version: 5.0.6
-   Wagtail version: 6.1
-   Browser version: Firefox 125

**Comment by laymonage** [comment]
Hello, please see #11928 and check whether it’s the same issue. Thanks!

**Comment by cesar-benjamin** [comment]
thanks! as in #11928 i was using an old project and trying to upgrade but adding wagtail.contrib.search_promotions in INSTALLED_APPS it works.

**Comment by laymonage** [comment]
Thanks for confirming!
