### ISSUE TITLE
wagtailimages "file" field length should be 255 not 100

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#1195]
I see no reason to limit this to less than the db field maximum. More importantly a 255 limit would be more compatible with imports from other CMS, where an arbitrary limit of 100 might not exist (as was the case with a recent client)

**Comment by thibaudcolas** [comment]
No one has commented on this in 9 years so I’ll close this now. If anyone feels this is important please re-open with our current feature request template so the request is clearer.
