### ISSUE TITLE
Allow to customize UserViewset like GroupViewset

### ISSUE THREAD

**Issue by NotANormalNerd** [wagtail/wagtail#11954]
### Is your proposal related to a problem?

You are already allowed to customize the GroupViewset by specifing a new GroupViewset in the AppConfig. It would be amazing to have the same for UserViewset to be able to add Custom Columns or other Customizations to the Viewsets.

https://docs.wagtail.org/en/latest/extending/customizing_group_views.html

### Describe the solution you'd like

Allow to provide a Custom UserViewset

**Comment by laymonage** [comment]
Thanks for the suggestion! This has been implemented in #11952 and is awaiting review. When it's merged, it will be available in the next release 🙂

**Comment by NotANormalNerd** [comment]
We are currently using all the settings named above. If there is a way to do that easily in UserViewset, I am all for doing that there. Deprecating would therefor be no problem.

Aside from that: Is this also planned for the PageTree? It would be amazing if we could replace the current ViewSet with a customized one. RIght now it is really a lot of monkey patching.

**Comment by gasman** [comment]
Fixed in #11952
