### ISSUE TITLE
Uncaught TypeError in page-editor.js - MultipleChooserPanel

### ISSUE THREAD

**Issue by patillacode** [wagtail/wagtail#11955]
### Issue Summary

I have selection of authors for a book in my site 

![Screenshot 2024-05-14 at 15 51 11](https://github.com/wagtail/wagtail/assets/10074977/e0883697-3622-43c9-8f18-17cc1e15384e)

And I can select whichever one without issue!

The problem comes when I try to filter by author name, the filtering occurs without any problems but I cannot select any of the authors from the output.

The result is correct, I get the color change on hover meaning I can click on it:

![Screenshot 2024-05-14 at 15 54 27](https://github.com/wagtail/wagtail/assets/10074977/27938ae7-caea-4fb3-aef0-7c72c3f8f0e1)

But when I do I get this in the console making reference to `page-editor.js` 

![Screenshot 2024-05-14 at 15 56 55](https://github.com/wagtail/wagtail/assets/10074977/40fbaec3-8b17-4352-b3fe-03e4450970d7)
![Screenshot 2024-05-14 at 15 56 47](https://github.com/wagtail/wagtail/assets/10074977/ccf50a16-9d01-4084-a99c-12f1a0e04460)

### Steps to Reproduce

Assuming you have a working Wagtail app running:

1. Go to edit any page with a MultipleChooserPanel (classic example of a Blog Post with an Author)
2. Filter by the author name
3. See you cannot select any of the given results after the filtering is done.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: `3.9.15`
-   Django version: `4.2.11`
-   Wagtail version: `5.2.3`
-   Browser version: `Chrome 124`

### Working on this

In the [original conversation](https://wagtailcms.slack.com/archives/C81FGJR2S/p1715695098743519) on the Slack support channel @lb- mentioned that his guess was that the chooser JS is not being reinstated after the filtering occurs.

**Comment by gasman** [comment]
Thanks for reporting! I see that the checkboxes are missing from the second screenshot, which probably means that the URL parameter that enables multiple choice has not been preserved when loading the filtered results - it then ends up returning a single result (rather than the expected array of results) to the calling page, which fails as the calling page tries to loop over the results.

**Comment by patillacode** [comment]
FYI, in case it helps, the behaviour is correct when you try to change an existing author.

If you have a selected item in your `MultipleChooserPanel` and want to change it, using the menu option "Choose another page" you get the pop-up/modal and filtering works there without issue.
![Screenshot 2024-05-14 at 16 04 13](https://github.com/wagtail/wagtail/assets/10074977/57f47671-2d6b-44f8-b95d-295faa9951a3)

I still don't get the checkboxes but I can click the results and the value changes correctly.

![Screenshot 2024-05-16 at 12 11 19](https://github.com/wagtail/wagtail/assets/10074977/6059b430-118b-4912-b481-a457c439d05c)

![Screenshot 2024-05-16 at 12 17 21](https://github.com/wagtail/wagtail/assets/10074977/e0289ec6-0f67-48cd-b1c5-355d37886d7d)
