### ISSUE TITLE
Invalid Email Format Accepted in User Registration Form

### ISSUE THREAD

**Issue by MarcoTulioSoares** [wagtail/wagtail#11971]
### Issue Summary
The user registration form currently accepts email addresses that do not follow a valid format. This issue poses a risk as it allows invalid email addresses to be registered, potentially causing communication failures and other related issues.

### Steps to Reproduce
1-Navigate to the user registration form.
2-Enter a username, first name, last name, and a valid password.
3-In the email field, enter an invalid email address (e.g., "user@@example.com" or "userexample.com").
4-Complete the registration process by filling out all required fields and submitting the form

**Comment by gasman** [comment]
It seems to be correctly rejecting it for me...?

![Screenshot 2024-05-21 at 22 46 59](https://github.com/wagtail/wagtail/assets/85097/3293a464-19cb-4334-b6a8-17bc71ed03c4)

**Comment by MarcoTulioSoares** [comment]
sorry, I put the wrong case, try user@test.co
