### ISSUE TITLE
Page privacy model renders 2 headers and icons

### ISSUE THREAD

**Issue by smark-1** [wagtail/wagtail#11984]
### Issue Summary
Page privacy model renders 2 headers and icons when a parent page has been made private.
![image](https://github.com/wagtail/wagtail/assets/75799735/26ca0fb8-f086-4bb2-9e1d-78e1cd4517fc)

### Steps to Reproduce

1. Set a page to private.
2. Visit a child page and click change privacy

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I expect for only the second heading and icon to be displayed.
-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version:  3.12
-   Django version: 5.0.6
-   Wagtail version: 6.2 (latest) and 6.1
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by laymonage** [comment]
Thanks for the report! I can confirm this issue: 
<img width="590" alt="image" src="https://github.com/wagtail/wagtail/assets/6379424/a7c26541-1a93-4956-9aab-3b5014f7889f">

For anyone interested in working on this issue, we need to remove the header from the template: https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/page_privacy/ancestor_privacy.html

and I think the `nice-padding` wrapper should be removed too.

Then we need to add some assertions to the existing test to ensure there's no header being rendered:
https://github.com/wagtail/wagtail/blob/a7798c1b806fb1c7cfdf5c9fcb80dae3133a759d/wagtail/admin/tests/test_privacy.py#L104-L122
