### ISSUE TITLE
Wagtail 6.1.x update breaks `RadioSelect` initialiastion after replacing jQuery with vanilla JS

### ISSUE THREAD

**Issue by urlsangel** [wagtail/wagtail#11990]
### Issue Summary

Wagtail 6.1.x update breaks `RadioSelect` initialiastion after replacing jQuery with vanilla JS.  

The JS adapter [`BoundRadioSelect`](https://github.com/wagtail/wagtail/blob/main/client/src/entrypoints/admin/telepath/widgets.js#L150) previously tested and set the checked option by comparing the element value against an array value - an array value is passed to the constructor:

#### Wagtail 6.0 implementation
```
setState(state) {
    this.element.find('input[name="' + this.name + '"]').val([state]);
}
```

It now tests against a string, and the equality operator fails, so the radio option is not correctly set as `checked` on initialisation:

#### Wagtail 6.1.x implementation
```
  setState(state) {
    const inputs = this.element.querySelectorAll(`input[name="${this.name}"]`);
    for (let i = 0; i < inputs.length; i += 1) {
      inputs[i].checked = inputs[i].value === state;
    }
  }
  ```

The breaking change is here:

https://github.com/wagtail/wagtail/compare/v6.0.3...v6.1#diff-70fd977dfb7c5b823eab70485fa842987589fc8656203ffb729a4b7d688c1d04L130

### Steps to Reproduce

1. Use a choice block within a Streamfield such as:

```
link_type = blocks.ChoiceBlock(
    choices=[
        ('page', 'Page'),
        ('document', 'Document'),
        ('url', 'URL'),
    ],
    widget=forms.RadioSelect,
    required=True,
    default='page',
)
```
2. View/edit a page/snippet where this field is used
3. In Wagtail 6.0.x the first choice is `checked` as expected
4. In Wagtail 6.1.x the first choice is not `checked` as expected

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: Python 3.12.3
-   Django version: 5.0.6
-   Wagtail version: 6.1.x
-   Browser version: Chrome 125

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
Thanks for the report! Can confirm I'm seeing this too - the bug is present on [bakerydemo](https://github.com/wagtail/bakerydemo/), on the "difficulty" options on the recipe page.
