### ISSUE TITLE
Rich text external-to-internal link converter not working when using a non-root path for `wagtail_serve`

### ISSUE THREAD

**Issue by maliahavlicek** [wagtail/wagtail#11996]
### Issue Summary

Entering an Internal link in the External Link for Rich Text Editor isn't converting to an internal link.

### Steps to Reproduce

1. in settings.py enable Link Conversion by setting
-  WAGTAILADMIN_EXTERNAL_LINK_CONVERSION = "confirm"  
        or
-  WAGTAILADMIN_EXTERNAL_LINK_CONVERSION = "all"
2. Open a page in wagtail to edit
3. Add a paragraph tag, link some text using the link builder
![image](https://github.com/wagtail/wagtail/assets/23039742/09f50e2e-ad22-4728-ab93-eca4d5a1f43d)

I have tried a relative link and a fully qualified URL in my local, feature, and production environments, but the link isn't converting.

- /the-ascent/credit-cards/best-hotel-credit-cards/

**To get this functionality to work locally,** 
I had to hack the **.venv/lib/python3.11/site-packages/wagtail/admin/views/chooser.py**  file to remove the first instance of things in the components when doing a page match. 

``` python

                    components = [
                        component for component in url.split("/") if component
                    ]
                    if "localhost" in settings.WAGTAILADMIN_BASE_URL:
                        components = components[1:]
                    route = Site.objects.get(pk=pk).root_page.specific.route(
                        request,
                        components,
                    )
```

if the setting is ="confirm", 
I'd expect to get the popup:
![image](https://github.com/wagtail/wagtail/assets/23039742/96150939-b5cb-4aaa-9c82-dfc8f0a847a6)

If it's "all, I'd expect the next time I'd edit the link it would be automatically set to "Internal Link" and the page that it's currently set to as the highlighted option. **NOTE this is not what is highlighted**, its parent page or the parent page of the page I'm linking from is what is highlighted:
![image](https://github.com/wagtail/wagtail/assets/23039742/9d348b30-f129-4379-892d-927e7f225307)

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

-   Python version:3.11.1
-   Django version: 5.0.3
-   Wagtail version: 6.1.2
-   Browser version: Chrome on Mac 125.0.6422.113

**Comment by laymonage** [comment]
Hi @maliahavlicek, thanks for the report!

Do you have multiple sites configured in Settings > Sites? If so, then relative links are not automatically converted. Here's the relevant code:

https://github.com/wagtail/wagtail/blob/ebc77dda8338299c0612b0734b3d383d84491b33/wagtail/admin/views/chooser.py#L632-L646

I didn't see this behaviour mentioned in https://docs.wagtail.org/en/stable/reference/settings.html#wagtailadmin-external-link-conversion, so I think we need to document this.

**Comment by laymonage** [comment]
After further investigation, this seems to be a bug that occurs if the `wagtail_serve` URL pattern isn't handled at the root URL of the server, e.g.

```py
path("the-ascent/", include(wagtail_urls))
```

instead of

```py
path("", include(wagtail_urls))
```

The external URL converter doesn't take this into account when doing the matches:

https://github.com/wagtail/wagtail/blob/ac38343957787b7d7a2ff34164a98538e177ff96/wagtail/admin/views/chooser.py#L632-L687

so the logic needs to be updated to consider such cases.
