### ISSUE TITLE
Rich Text Internal Links to pages do not show up in page usage report.

### ISSUE THREAD

**Issue by maliahavlicek** [wagtail/wagtail#12021]
### Steps to Reproduce

1. create a new page that is super simple
2. open an existing page and add a rich text internal link to the new page 
![image](https://github.com/wagtail/wagtail/assets/23039742/9807a5d3-a9ac-47c3-9031-01c8402c312e)
3. Publish your changes
4. Go to the new page and click the info and see 0 references under usage:
![image](https://github.com/wagtail/wagtail/assets/23039742/66b373d6-f801-4080-a149-822e1b26e2aa)

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

- Python version:3.11.1
- Django version: 5.0.3
- Wagtail version: 6.1.2
- Browser version: Chrome on Mac 125.0.6422.113

### Working on this

It looks like the **extract_rerences** method for various field types needs to find these things. I managed to add a money patch to get internal links created in ReferenceIndex in my local environment by adding this to pages/wagtail_hooks.py
``` python
def extract_references(self, value):
    source_value = value.source if hasattr(value, "source") else value
    yield from extract_richtext_link_references(source_value)

def extract_richtext_link_references(value, get_content_path_extra=lambda _: ""):
    """
    Yields:
        A tuple (content_type_id, object_id, model_path, content_path) for each
        reference found.

        content_type_id (int): The ID of the ContentType record representing
                               the model of the referenced object

        object_id (str): The primary key of the referenced object, converted
                         to a string

        model_path (str): The path to the field on the model of the source
                          object where the reference was found

        content_path (str): The path to the piece of content on the source
                            object instance where the reference was found
    """
    pattern = r"<a id=\"(\d+)\" linktype=\"page\">"
    for match in re.finditer(pattern, str(value)):
        try:
            model = "wagtailcore.page"
            model = apps.get_model(model)
            content_string = r"<a id=\"ID\" linktype=\"page\">"
            content_string_match = content_string.replace("ID", match.group(1))
            yield (
                model,
                str(match.group(1)),
                "",
                get_content_path_extra(content_string_match),
            )
        except LookupError:
            logger.error(
                f"Couldn't find page for link reference with pk {match.group(1)}"
            )
            continue

```

and the usage count increases.

**BUT...**
When I remove the internal link it's NOT removed from the ReferencesIndex. I have a feeling that maybe my yield to create a ReferenceIndex might be slightly off making the  **def create_or_update_for_object** bit of finding existing_references miss the internal link items.

**Comment by laymonage** [comment]
Hi, thanks for the report! I couldn't replicate this with the bakerydemo nor a fresh Wagtail project.

The `RichTextField` already has a built-in mechanism to extract references in the content:

https://github.com/wagtail/wagtail/blob/ebc77dda8338299c0612b0734b3d383d84491b33/wagtail/fields.py#L57-L58

https://github.com/wagtail/wagtail/blob/ebc77dda8338299c0612b0734b3d383d84491b33/wagtail/rich_text/__init__.py#L23-L63

https://github.com/wagtail/wagtail/blob/ebc77dda8338299c0612b0734b3d383d84491b33/wagtail/rich_text/__init__.py#L29-L38

https://github.com/wagtail/wagtail/blob/ebc77dda8338299c0612b0734b3d383d84491b33/wagtail/rich_text/pages.py#L37-L40

Do you perhaps have registered any custom rewrite handlers (or other rich text-related customisations) as described in https://docs.wagtail.org/en/stable/extending/rich_text_internals.html? If so, some of them may have changed the final markup in a way that causes the default mechanism to not be able to detect the references.

**Comment by maliahavlicek** [comment]
Thanks, it does look like our code is skipping this because of our customizations.

**Comment by gasman** [comment]
Closing as not reproducible.
