### ISSUE TITLE
Extended redirect behaviour to allow 'failover' to another site 

### ISSUE THREAD

**Issue by stevejalim** [wagtail/wagtail#1204]
Does Wagtail already handle failing over to a different domain if it can't resolve a url? My scanning of the docs implies not.
ie: imagine a wagtail public site of CMS-driven content (eg a campaign/marketing/info site), plus a parallel application site.

My ideal would be if a url can't be resolved by the wagtail-powered site, then there's a 301 to the same full path (including querystrings) on a different domain.

(This may be something I write anyway and offer as contrib or a straight PR, but thought I'd float the idea first)

**Comment by marteinn** [comment]
No, this is not something Wagtail does out of the box. This is sort of a edge case so the best solution for this is to specify that behavior in a 404-handler in Django. https://docs.djangoproject.com/en/3.0/ref/urls/#django.conf.urls.handler404

(I know this is a late answer (5 years later) but might be of interest to others)
