### ISSUE TITLE
Add a method to deactivate ProgressController

### ISSUE THREAD

**Issue by mgax** [wagtail/wagtail#12057]
### Is your proposal related to a problem?

The [ProgressController](https://github.com/wagtail/wagtail/blob/main/client/src/controllers/ProgressController.ts) provides an `activate` method, and it automatically deactivates after a timeout. However, if the action completes successfully, without having to reload the page, the button should revert to its initial (non-disabled) state. Currently one must set `loadingValue = false` on the controller to achieve this.

### Describe the solution you'd like

The controller should provide a `deactivate` method that:
* Sets `this.loadingValue = false`
* Calls `clearTimeout(this.timer)`.

### Describe alternatives you've considered

I'm currently clearing the `loading` value directly:

```javascript
this.application.getControllerForElementAndIdentifier(
  this.sendButtonTarget, "w-progress"
).loadingValue = false;
```

### Working on this

I'd be happy to submit a PR to implement this.

**Comment by gasman** [comment]
Sounds good to me - what do you think @lb-?

**Comment by lb-** [comment]
Great idea. Thanks @mgax - please remember to include unit tests with your PR. 

Happy to review when it's up, just ping me on the PR.
