### ISSUE TITLE
Tidy up oembed_providers.py

### ISSUE THREAD

**Issue by tomkins** [wagtail/wagtail#12054]
### Issue Summary

Currently [oembed_providers.py](https://github.com/wagtail/wagtail/blob/ac38343957787b7d7a2ff34164a98538e177ff96/wagtail/embeds/oembed_providers.py) has a list of providers that no longer exist. A quick example would be Revision3.com, it longer exists as a service.

### Steps to Reproduce

```
from wagtail.embeds.embeds import get_embed
get_embed('http://www.revision3.com/demo')
```

Returns an `EmbedNotFoundException` exception, but there's other exceptions underneath because the URL/hostname doesn't exist.

Not a huge issue, but if there's a dead provider that isn't accepting connections - it just hangs:

```
get_embed('http://qik.com/demo')
```

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: Any
-   Django version: Any
-   Wagtail version: 6.1 / main
-   Browser version: n/a

### Working on this

I think this is probably a "good first issue", so would love to see someone else give this one a go.

**Comment by isatyamks** [comment]
@tomkins @zerolab Hello, I would like to work on issue #12054. Could you please assign it to me?

**Comment by zerolab** [comment]
Feel free to do so. We don't assign issues to non-core members

**Comment by isatyamks** [comment]
@zerolab, I've submitted a pull request (https://github.com/wagtail/wagtail/pull/12055#)  and would appreciate your review and analysis of the solution.

**Comment by vishu1089** [comment]
hey, would like to give it a try!

**Comment by zerolab** [comment]
Go for it. Please see the comments on #12055

**Comment by vishu1089** [comment]
Thanks, I will!

**Comment by sanskarprasad** [comment]
I am a first-time Wagtail contributor, and I am eager to take on this issue. 
Looking forward to contributing!

**Comment by Rvaibhavv** [comment]
hello, I am really looking forward to resolve this issue #12054

**Comment by Rohit-Singh-01** [comment]
hii , is this still open , can I work on it ??

**Comment by Rohit-Singh-01** [comment]
@tomkins hii , actually i was working on it, and done the mostly the same thing, Removed defunct providers from oembed_providers.py.

    Updated embeds.py to handle width and height values more robustly. but how exactly can I find the other non-existing providers ??

**Comment by tomkins** [comment]
Go to each site, and see if it exists. It'll be manual work to verify if the site is still there with an oEmbed endpoint.

With a bit of effort, you could build a test script that provides a URL (for that particular site) to each endpoint and verify that it's returning valid content. Although it's probably one that shouldn't be added to the Wagtail repo.

**Comment by NikitaJaiswal77** [comment]
@zerolab could you please assign this to me.
