### ISSUE TITLE
Add documents broken link in catalan translation

### ISSUE THREAD

**Issue by csalom** [wagtail/wagtail#12067]
### Issue Summary

The link to add the first file is broken in catalan translation.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Enable internationalization following https://docs.wagtail.org/en/stable/advanced_topics/i18n.html#id30
3. Add catalan as one of your languages adding `("ca", "Catalan") to your languages.
4. Set catalan as your user language on Wagtail User Account
5. Go to documents section and check the `pujes un ara?` link to see how a quote is beig added at the end `...documents/multiple/add/%22"`

![Captura de pantalla de 2024-06-20 17-19-12](https://github.com/wagtail/wagtail/assets/16468446/09118ce4-103e-4516-bced-5b3a1dc7b72b)

After clicking on the link, you will be redirected to 404 page:

![Captura de pantalla de 2024-06-20 17-20-29](https://github.com/wagtail/wagtail/assets/16468446/abe3e15d-3f5b-448b-a707-cd977e36ce57)

The reason of this broken link is the following translation, which is not well scapped 
https://github.com/wagtail/wagtail/blob/4e2afc966bc4b37dd425d99c83cfe715563ffcc8/wagtail/documents/locale/ca/LC_MESSAGES/django.po#L230 

The expected behaviour will be to be able to arrive to the add document view.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11.1
-   Django version: 4.2.4
-   Wagtail version: 6.1.2

### Working on this

I'm happy to create a PR to fix the translation, if you agree on it.

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by csalom** [comment]
Ok! Will take a look, I've not used Transifex yet

**Comment by csalom** [comment]
Suggestion added, I think that someone has to apply it https://app.transifex.com/torchbox/wagtail/translate/#ca/wagtaildocs/21857929

**Comment by gasman** [comment]
Thanks! For some reason your version was showing with extra backslashes before the quote characters, but I think the correct version is in place now.
