### ISSUE TITLE
Concurrent editing notifications - displaying active sessions

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#12078]
Part of [RFC 95 - concurrent editing notifications](https://github.com/wagtail/rfcs/pull/95). Integrate the EditingSession model (as defined in #12077) into the page / snippet editing interface as described in the "Base implementation" section of the RFC:

* On opening the interface, a new EditingSession is created and the "cleanup" method on EditingSession is called to remove stale sessions
* We display a list of other editors viewing the edit interface for the current object, as part of the initial page render
* This list is kept up to date by periodically calling the 'ping' endpoint
* The 'release' endpoint is called upon leaving the page

### Working on this

To be implemented by the Wagtail product team at Torchbox - we are not seeking external contributors for this.

**Comment by thibaudcolas** [comment]
Implemented in #12099.
