### ISSUE TITLE
Concurrent editing notifications - showing users with unsaved changes

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#12079]
Part of [RFC 95 - concurrent editing notifications](https://github.com/wagtail/rfcs/pull/95)

As per the RFC section 'Distinguishing between "currently viewing" and "currently editing"', extend the EditingSession model, ping endpoint and front-end to indicate editors who have unsaved changes in their browser, as determined by the "dirty changes" mechanism.

(As part of this, evaluate whether the dirty changes mechanism works well enough for this purpose, and whether any fixes need to be applied.)

### Working on this

To be implemented by the Wagtail product team at Torchbox - we are not seeking external contributors for this.

**Comment by laymonage** [comment]
@gasman Do you need the frontend in place to implement this? I'm afraid the PR at #12099 already combines both #12078 and #12081 (as I wanted to ensure they both fall into place nicely), and the latter would need this ticket implemented. I could trim the scope down to only what's necessary for #12078, but given that we're tight on time I don't think it's a good idea.

I assume this can be implemented without any frontend, as long as the backend accepts the "dirty changes" flag and the revision ID in some way and saves it to the `EditingSession` model – but let me know if you would rather have the frontend first. Thanks!
