### ISSUE TITLE
Concurrent editing notifications - frontend notifications

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#12081]
Part of [RFC 95 - concurrent editing notifications](https://github.com/wagtail/rfcs/pull/95). As per the 'Notifying users on changes' section of the RFC:

* implement 'toast' popups against the list of active editors showing when one has made an edit, with options to dismiss or refresh
* implement a confirmation dialog to appear if the user tries to submit the form after conflicting edits have been identified.

### Working on this

To be implemented by the Wagtail product team at Torchbox - we are not seeking external contributors for this.

**Comment by thibaudcolas** [comment]
Implemented in #12099.
