### ISSUE TITLE
Bulk actions needed

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#121]
It would be nice if actions could be performed on several items at once in an admin listing. Deleting and moving in particular (for pages, images, documents, snippets etc) also publishing (for pages only).

Also for enabling/disabling user accounts.

**Comment by aldyahsn** [comment]
any update for this?

**Comment by allcaps** [comment]
No. This issue tracks all updates on the matter. If there are updates you read it here.

Bulk actions for various content types is an enhancement that requires a lot of work. 
We are happy if anyone would like to help. It is probably best to start with one of the following:

- Write an RFC
- Design mock-ups
- Create a prove of concept

**Comment by ecolss** [comment]
> No. This issue tracks all updates on the matter. If there are updates you read it here.
> 
> Bulk actions for various content types is an enhancement that requires a lot of work.
> We are happy if anyone would like to help. It is probably best to start with one of the following:
> 
> * Write an RFC
> * Design mock-ups
> * Create a prove of concept

If bulk actions not supported in wagtail, would it be possible to use django admin features instead?
This is in-convenient without bulk actions.

**Comment by anefta** [comment]
Any update on this?

**Comment by allcaps** [comment]
Only your comment. If there would be any update, it will appear here. So
no, no active development.

Anyone who needs this feature, is welcome to pick it up and submit a pull
request.

Tip/workaround/not ideal: Wagtail extends Django, so you can register the
Django admin in parallel to Wagtail admin. If you do not want to leave the
Wagtail admin UI, an simple custom Wagtail admin view with an iframe can
bring any view into Wagtail.

YMMV.

**Comment by thibaudcolas** [comment]
It’s here :) #7573 https://docs.wagtail.io/en/latest/releases/2.15.html#bulk-actions 

```
pip install wagtail==2.15rc1
```
