### ISSUE TITLE
"wagtailroutablepage_tags" is not a registered tag library.

### ISSUE THREAD

**Issue by rubenhesselink** [wagtail/wagtail#12113]
### Issue Summary

When trying to get a routablepageurl I load the wagtailroutablepage_tags but isn't recognized as a registered tag library

### Steps to Reproduce

1. Create a RoutablePage
2. Create a corresponding html file for the RoutablePage
3. Add the following line of code to your HTML: `{% load wagtailroutablepage_tags %}`
4. You will see the following error when trying to view the page: `'wagtailroutablepage_tags' is not a registered tag library.`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)
-   I would expect the tag to be registered by default

### Technical details

-   Python version: 3.12.3.
-   Django version: 4.2.13.
-   Wagtail version: 5.2.5.
-   Browser version: Chrome 126.

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by zerolab** [comment]
Have you added `wagtail.contrib.routable_page` to `INSTALLED_APPS` as per https://docs.wagtail.org/en/stable/reference/contrib/routablepage.html#installation ?

**Comment by rubenhesselink** [comment]
This fixes the issue. My apologies for not reading the documentation thoroughly enough.
