### ISSUE TITLE
Action buttons are easy to miss in list views for high contrast mode users

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#12126]
### Issue Summary

Reported by partially sighted users and then confirmed:

> The “…” buttons were completely missed by some users who were not aware that these page controls were available in the list view
> […]
> Three dot menus were also not always visible under high contrast.

Here is how those buttons currently appear in a forced-colors "dark" theme:

![forced colors dark list view with three-dot action buttons in rows](https://github.com/user-attachments/assets/82d8737d-0c08-4dc8-8351-fa39009ae49d)

### Proposed solution

A simple improvement would be to add a border around those buttons in forced colors mode, similarly to how we adapt the "Add" button. It seems like this could be done for all `w-dropdown__toggle`.

### Steps to Reproduce

1. Enable forced-colors mode
2. Go to a view with a listing of items such as the dashboard panels or Pages section

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by AyushDharDubey** [comment]
I am opening a PR to fix this issue.

**Comment by AmandaaMoura** [comment]
I am a first-time Wagtail contributor, and I am eager to take on this issue.
Looking forward to contributing!

**Comment by Scotchester** [comment]
@AmandaaMoura, thank you for your interest, but @AyushDharDubey has already submitted a pull request to solve this issue. If you wanted to review the PR (#12144) and confirm whether you think it solves the issue, that would be helpful!

**Comment by lb-** [comment]
Fixed via https://github.com/wagtail/wagtail/pull/12365 also, but this issue was not mentioned. I did a search but must not have searched for the right words.
