### ISSUE TITLE
Use `event.preventDefault()` to trigger the browser confirmation dialog in `UnsavedController`

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#12132]
### Issue Summary

The `UnsavedController` uses the `beforeunload` event to trigger a browser confirmation when the user is about to leave the page editor while having unsaved changes. This trigger is done by setting `event.returnValue` to a truthy value. The event handler also returns a confirmation string when the dialog is triggered:

https://github.com/wagtail/wagtail/blob/2d568dd825e4b087d7cea1c4d1fa49d916b395c2/client/src/controllers/UnsavedController.ts#L174-L191

However, according to MDN docs of the `beforeunload` event, this approach is deprecated.

In summary, of the three available approaches:
- Preferred: Calling the event object's `preventDefault()` method. Introduced in Chrome 119 (Released 2023-10-31), with other Chromium-based browsers followed, and much earlier for other browsers.
- Deprecated, currently used: Setting the event object's `returnValue` property to a non-empty string value or any other truthy value. This was also introduced in Chrome 119.
- Deprecated, currently **incorrectly** used: Returning any truthy value from the event handler function, e.g. `return "string"`.
  From MDN:
  > Note that this only works when the function is attached via the `onbeforeunload` property, not the `addEventListener()` method. This behavior is consistent across modern versions of Firefox, Safari, and Chrome.

> The last two mechanisms are legacy features; best practice is to trigger the dialog by invoking `preventDefault()` on the event object, while also setting returnValue to support legacy cases.

We should refactor the `UnsavedController.confirm()` method to use `event.preventDefault()` instead.

In addition, I'm pretty sure we no longer need the `confirmationValue` as a string:

https://github.com/wagtail/wagtail/blob/2d568dd825e4b087d7cea1c4d1fa49d916b395c2/client/src/controllers/UnsavedController.ts#L77-L78

We can no longer customise the browser confirmation message, per MDN:

> Only show a generic browser-specified string in the displayed dialog. This cannot be controlled by the webpage code.

This means we can simplify `confirmationValue` into something like `confirmValue` with a boolean type to allow dynamically toggling whether to show the dialog or not.

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

Don't forget to update the corresponding tests for the controller as well.

**Comment by lb-** [comment]
Thanks for raising this.
