### ISSUE TITLE
Error in working with page instance after removing it's child pages: AttributeError: 'NoneType' object has no attribute '_inc_path' 

### ISSUE THREAD

**Issue by TohidN** [wagtail/wagtail#12159]
### Issue Summary
error created after performing delete() operation on page children and adding new pages..
```
AttributeError: 'NoneType' object has no attribute '_inc_path' 
```

### Steps to Reproduce
1. get an instance of Page.
2. Remove it's children.
3. add new Page instances as children to the Page instance in step 1.
```python
home = Page.objects.get(url_path="/home/")
home.get_children().delete()

# main pages
blog = BlogIndexPage(title="Blog")
home.add_child(instance=blog)
```
error happens in add_child() function.
It's not a tree structure error and running `Page.fix_tree(destructive=False, fix_paths=True)` after delete doesn't fix it. I expect that it's only related to "Page instance variable" not being updated after `delete()` function, since running `home = Page.objects.get(url_path="/home/")` again after `delete()` to get the update parent page again solves the issue.

**Comment by gasman** [comment]
This is a documented caveat of the django-treebeard library (https://django-treebeard.readthedocs.io/en/latest/caveats.html#raw-queries):

> django-treebeard uses Django raw SQL queries for some write operations, and raw queries don’t update the objects in the ORM since it’s being bypassed.

> Because of this, if you have a node in memory and plan to use it after a tree modification (adding/removing/moving nodes), you need to reload it.
