### ISSUE TITLE
Translation concern in Wagtail 6.2 save dialog

### ISSUE THREAD

**Issue by Stormheg** [wagtail/wagtail#12167]
## Issue

Wagtail 6.2rc1 introduces a confirmation dialog when you are about to override changes made in a different window.

The text in this dialog uses a [demonstrative pronoun](https://www.grammarly.com/blog/demonstrative-pronouns/) (this/that/these/those) in combination with a templated, unknown, noun. 

https://github.com/wagtail/wagtail/blob/6c11616bd6cb3803e00fb03c10d48b0a97b2442a/wagtail/admin/templates/wagtailadmin/shared/editing_sessions/list.html#L114

This poses an issue for Dutch (and likely other languages) because the correct translation of _this_ differs depending on the gender of `model_name`. Unfortunately, _this_ (😉)  is not a solved problem in gettext.

## Proposal

I propose we remove the reference to a model from the dialog text. The surrounding context on the page should be plenty clear enough, the message will not lose any clarity.

<img width="738" alt="image" src="https://github.com/user-attachments/assets/8b634e00-1b26-4553-9e0e-3572c300b459">

```diff
- {{ user_name }} has saved a newer version of this {{ model_name }}
+ {{ user_name }} has saved a newer version

- You have saved a newer version of this {{ model_name }} in another session
+ You have saved a newer version in another session
```

---

More generally speaking, use of demonstrative pronouns in combination with some unknown noun is a recurring issue in Wagtail. Often, there are ways to creatively rewrite a sentence to avoid use demonstrative pronouns but Transifex makes this hard because it marks strings as invalid if you don't include the placeholder value for the noun, limiting translator options.

**Comment by laymonage** [comment]
Thanks for the report! I was in two minds about adding the model name, as it required passing the content type to the component, which added a small complexity. Removing this would make the editing session component code simpler, so I wouldn't be opposed to that.
