### ISSUE TITLE
Overriding choose_results_view in ChooserViewSet will break the search in the chooser

### ISSUE THREAD

**Issue by BigWhale** [wagtail/wagtail#12163]
### Issue Summary

Trying to override `choose_results_view` when creating a custom `ChooserViewSet` will break the search. This happens even if override is done with the default `ChooseResultsView`.

I was working with a custom ChooseResultsView at first and when I could not get it to work, I tried with the on that is set by default. That failed with the same error and then I started digging and I cannot figure out what happens when `choose_results_view` is overridden with the same viewset that is used in the parent.

### Steps to Reproduce

1. Create new wagtail site:
2. Add the following code to `models.py`

```
class Article(Page):
    body = models.TextField()
    parent_page_types = ['home.HomePage']
    content_panels = Page.content_panels + [FieldPanel('body'),
                                            MultipleChooserPanel(
                                                "articles",
                                                chooser_field_name="related_article",
                                                label="Articles",
                                            )
                                            ]

class RelatedArticles(Orderable):
    article = ParentalKey('Article', on_delete=models.CASCADE, related_name='articles')
    related_article = ParentalKey('Article', on_delete=models.CASCADE, related_name='related_articles')


class ArticleChooserViewSet(ChooserViewSet):
    icon = "doc-full-inverse"
    name = "article_chooser"
    model = "home.Article"
    page_title = "Choose thy article"
    per_page = 10

    # This will break search in the chooser
    choose_results_view = chooser_views.ChooseResultsView

def register_article_chooser_viewset() -> ArticleChooserViewSet:
    return ArticleChooserViewSet()

```
3. Add the following code to `wagtail_hooks.py`:
```
from home.models import register_article_chooser_viewset
from wagtail import hooks

hooks.register("register_admin_viewset", register_article_chooser_viewset)
```

4. Open wagtail admin and create one article
5. Edit this article, open the multiple chooser panel, try using search.
6. Observe the following exception in the console:
```
Internal Server Error: /admin/article_chooser/results/
Traceback (most recent call last):
  File "/Users/bigwhale/.virtualenvs/test-venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bigwhale/.virtualenvs/test-venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bigwhale/.virtualenvs/test-venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bigwhale/.virtualenvs/test-venv/lib/python3.12/site-packages/wagtail/admin/urls/__init__.py", line 178, in wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bigwhale/.virtualenvs/test-venv/lib/python3.12/site-packages/wagtail/admin/auth.py", line 151, in decorated_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: View.__init__() takes 1 positional argument but 2 were given
[24/Jul/2024 12:59:37] "GET /admin/article_chooser/results/?multiple=1&q=s HTTP/1.1" 500 76530
```

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes

### Technical details

-   Python version: 3.12.4
-   Django version: 5.07
-   Wagtail version: 6.1.3 / 6.2rc1
-   Browser version: Chrome 126

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by laymonage** [comment]
`choose_results_view` is for the view instance. If you're overriding the class, you should use `choose_results_view_class` instead.

https://github.com/wagtail/wagtail/blob/526c7da018692a1eb454af87ae65f92ceeb269d0/wagtail/admin/viewsets/chooser.py#L129-L134

https://github.com/wagtail/wagtail/blob/526c7da018692a1eb454af87ae65f92ceeb269d0/wagtail/admin/viewsets/chooser.py#L45-L46

**Comment by BigWhale** [comment]
I shall be wearing a brown paper bag over my head for the next couple of months.

Of course, this works as it expected, thank you.
