### ISSUE TITLE
Block count issue

### ISSUE THREAD

**Issue by mimzyi** [wagtail/wagtail#12183]
Wagtail 6.2rc1, block count doesn't disable plus sign (adding a new block)
code:
```
featured_block = StreamField(
        [
            ("FeaturedImage", ImageWithCaptionBlock()),
            ("FeaturedVideo", VideoStreamBlock(max_num=1)),
        ],
        block_counts={
            "FeaturedImage": {"max_num": 1},
            "FeaturedVideo": {"max_num": 1},
        },
        min_num=0,
        max_num=2,
        blank=True,
        verbose_name="Featured block",
    )
```

before wagtail upgrade:
![Screenshot 2024-07-29 at 14 58 42](https://github.com/user-attachments/assets/d1e63391-7da0-4d2f-9689-7903032b3504)

wagtail 6.2rc1:
![Screenshot 2024-07-29 at 14 59 13](https://github.com/user-attachments/assets/e2cee666-ec60-455a-a752-811dee5b2c41)

**Comment by laymonage** [comment]
This is intentional per #12023. Validation errors will be shown as soon as you add a new block.
