### ISSUE TITLE
Name column in Group Editor / Object Permissions should be left aligned (in LTR), not centre aligned

### ISSUE THREAD

**Issue by dkirkham** [wagtail/wagtail#12196]
### Issue Summary

Since Wagtail 6.1, the Name column in the Settings -> Group Editor -> Object Permissions section is centre aligned, rather than left aligned (for LTR) as it was before:

Wagtail 6.1 and 6.2:
<img width="918" alt="image" src="https://github.com/user-attachments/assets/4435dd93-bbd9-42a5-be1e-832a246128ed">

Wagtail 6.0:
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/7aecfa21-e9f1-4687-ada5-e443dd8ec414">

### Steps to Reproduce

1. Build and start the same project (eg. bakerydemo) with both Wagtail 6.0.x and Wagtail 6.1.x or 6.2. The project should avoid having any admin style customisations
2. In the admin, navigate to Settings -> Groups -> (group) to edit the group
3. Observe the alignment of the Name column in the Object permissions section

_Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?_

For LTR languages such as English, left aligned simply looks better in less congested examples (eg. as above) than the centre aligned. This is effectively a regression that wasn't noticed in 6.1 and which has now found its way to 6.2.

It is acknowledged that the more congested example (see below), where there are additional permissions type columns, suffers from the additional challenge of extremely narrow columns. This bug might therefore be addressed as part of a more general effort to improve the overall styling of the object permissions table.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)
However, @gasman shared a similar issue with his bakerydemo instance via Slack:

![image](https://github.com/user-attachments/assets/f6f052ef-ccc7-4c92-9244-ebecfb244bf4)

### Technical details

-   Python version: 3.8, 3.10, 3.11 - believed to be Python version agnostic.
-   Django version: 4.2 series - believed to be Django version agnostic.
-   Wagtail version: 6.1 and 6.2 (vs 6.0 and earlier)
-   Browser version: Firefox, Chrome (current) - believed to be browser agnostic.

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by Swarnim114** [comment]
Can I work on this issue?

**Comment by gasman** [comment]
Fixed in #12223
