### ISSUE TITLE
Cannot create a page due to "Page with this Path already exists" error: potentially linked to an ordering issue in `treebeard.mp_tree.MP_AddChildHandler.get_last_child()`

### ISSUE THREAD

**Issue by martibosch** [wagtail/wagtail#12190]
### Issue Summary

I am encountering a `django.core.exceptions.ValidationError: {'path': ['Page with this Path already exists.']}` when attempting to create a new page from wagtail's admin) under '/en-us/events' in the following tree:

```
$ from wagtail.models import Page

$ [(p.url, p.path) for p in Page.objects.all()]

[(None, '0001'),
 ('/en-us/', '00010001'),
 ('/en-us/events/', '000100010001'),
 ('/en-us/events/webinars/', '0001000100010001'),
 ('/en-us/events/webinars/some-webinar/', '00010001000100010001'),
 ('/en-us/events/newsletter/', '0001000100010002')]
```

I posted it [in stackoverflow](https://stackoverflow.com/questions/78759351/django-core-exceptions-validationerror-path-page-with-this-path-already-e) and at the end found the issue:

mp tree gets "webinars" as the last child (here: [github.com/django-treebeard/django-treebeard/blob/4.7.1/…](https://github.com/django-treebeard/django-treebeard/blob/4.7.1/treebeard/mp_tree.py#L383)), but the last child would actually be "newsletter", i.e.: 

```
>>> self.node.get_last_child()
<Page: Webinars>
>>> self.node.get_last_child().path
'0001000100010001' 
>>> for page in self.node.get_children(): print(page, page.path)
Newsletter 0001000100010002
Webinars 0001000100010001
```

I do not know whether this is an issue of wagtail or treebeard..

### Steps to Reproduce

1. Deploy [African-Cities-Lab/african-cities-lab-org](https://github.com/African-Cities-Lab/african-cities-lab-org) locally using docker (see https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html).
2. Using the wagtail admin, create the tree above where the root page is an instance of (in `african_cities_lab.home.models`) `HomePage`, "events" is `EventIndexPage`, "webinars" is `WebinarIndexPage`, "some-webinar" is `FlatPage` and "newsletter" is `NewsletterPage`
3. Try to create a `FlatPage` under "webinars"

We are also using:

wagtail==5.2.3  # https://github.com/wagtail/wagtail
wagtail-localize==1.8  # https://github.com/wagtail/wagtail-localize
wagtailmenus==3.1.9  # https://wagtailmenus.readthedocs.io/en/stable
wagtail-metadata==4.0.2  # https://github.com/neon-jungle/wagtail-metadata

but only the default locale (en-us) is active.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.12.4
-   Django version: 4.2.9
-   Wagtail version: 5.2.3
-   Browser version: https://whatismybrowser.com/w/LXR7X3Z

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by zerolab** [comment]
Have you tried running the [`fixtree`](https://docs.wagtail.org/en/stable/reference/management_commands.html#fixtree) management command?

**Comment by martibosch** [comment]
Yes, sorry that I forgot to mention it, but I tried fixtree and also with the —full flag, no luck with any of them (see the comments in the linked stackoverflow question for more details).

**Comment by martibosch** [comment]
actually I just found out that wagtail does get the order correctly, i.e.:

```
from african_cities_lab.home.models import Page

p = Page.objects.get(title="Events")
for page in p.get_children(): print(page, page.path)
```

outputs:

Webinars 0001000100010001
Newsletter 0001000100010002

so the issue comes from how wagtail admin delegates this to treebeard (as shown in the issue description above).

**Comment by gasman** [comment]
I checked out and built https://github.com/African-Cities-Lab/african-cities-lab-org , but it doesn't seem to have any references to Wagtail at all...?

**Comment by laymonage** [comment]
@gasman I think it’s in the develop or stage branch

**Comment by martibosch** [comment]
Hello @gasman, I am sorry. As @laymonage mentioned, you should build the stage branch (the develop would also work).

Thank you!

**Comment by gasman** [comment]
I'm unable to replicate this as described - I can create a second webinar page with no problems. Can you confirm that you've been able to replicate the error starting from a fresh installation of the project - not just the initial installation where you first encountered this? If so, please can you give an exact sequence of steps starting from the `docker-compose up` command (for example, is it necessary to delete the initial "Welcome to your new Wagtail site!" page, or update the site record to point to the created home page)?

**Comment by gasman** [comment]
Still working fine for me using the backup. Screen capture here: https://drive.google.com/file/d/1MPApDDRrSPQBhpoYn8njbggcmDT6SK2v/view?usp=sharing

**Comment by martibosch** [comment]
I just wiped everything clean and noticed I made a mistake in my description: the error appears when creating a `FormationIndexPage` under "Events" (http://localhost:3000/admin/pages/add/home/formationindexpage/4/).

**Comment by gasman** [comment]
You have overridden the `get_children` method on `IndexPage` to change the ordering: https://github.com/African-Cities-Lab/african-cities-lab-org/blob/364654597f555e9e47e31e73ca3c1398e9cb3e23/african_cities_lab/home/models.py#L213-L216

This is not supported - Treebeard internals expect children to be returned in path order.
