### ISSUE TITLE
Admin tag manager or documentation on how to remove tags

### ISSUE THREAD

**Issue by JoshBarr** [wagtail/wagtail#1220]
## Example use case
- Created a Page
- Tagged with "Social Mdia"
- List of all tags shows "Social Mdia"
- Remove tag from Page
- Tag remains in the `taggit_tag` table. 

That might be the correct behaviour to keep them around, but it's tricky to manage if you accidentally spell the name of a tag wrong (like my example above) and want to get rid of it when you list all tags via `Tag.objects.all()`. 

We could implement a "Tag Manager" view in the admin that lets you manually administer all the tags? 

## Proposal 2 - Admin tag manage recipe `recommended start`

Update - an initial approach may be to document a recipe (how to guide) that provides the details of how to do this.

This could be added to the docs here https://docs.wagtail.org/en/stable/reference/pages/model_recipes.html#tagging

Leveraging Wagtail's `ModelAdmin` it should not be too difficult to create a basic admin interface within the main settings menu that only admins can use, this would allow the removal of tags.

It could even allow for the linking of related items.

If this documented approach becomes well used, it could become part of core in the future.

Here is a post that has a good starting point https://groups.google.com/g/wagtail/c/GARQW3ODGr0?pli=1 (snippet pasted below)

```
#### Tags ####
from wagtail.contrib.modeladmin.options import ModelAdmin, modeladmin_register
from taggit.models import Tag, TaggedItem

class TagsModelAdmin(ModelAdmin):
    model = Tag
    menu_label = 'Tags' # ditch this to use verbose_name_plural from model
    menu_icon = 'tag' # change as required
    menu_order = 311 # will put in 3rd place (000 being 1st, 100 2nd)
    add_to_settings_menu = True # or True to add your model to the Settings sub-menu
    list_display = ["name", "slug"]
    #list_filter = ('live',)
    #search_fields = ('title',)

# Now you just need to register your customised ModelAdmin class with Wagtail
modeladmin_register(TagsModelAdmin)
```

**Comment by akhayyat** [comment]
A way to manage tags in the admin would be useful, indeed.

**Comment by lb-** [comment]
There is a documentation guide on using a separate `Tag` model for separate use cases, not a solution for the issue but good to know.

https://docs.wagtail.org/en/stable/reference/pages/model_recipes.html?highlight=tags#tagging

**Comment by lb-** [comment]
I have updated the description, I recommend we approach this as a documentation solution first and then in the future if this feature is requested it could become part of the core code.

Tagging (pun intended) as a good first issue and documentation.
