### ISSUE TITLE
InvalidFilterSpecError when using format and preserve-svg with no other operation

### ISSUE THREAD

**Issue by Chadys** [wagtail/wagtail#12201]
### Issue Summary

When you use the image template tag with a conversion operation and `preserve-svg` option with no other image transformation operation, and the image is actually an svg, the registered operations will be empty.
This will make `Filter.operations` raise an `InvalidFilterSpecError`, "Unrecognised operation: " on an empty string

### Steps to Reproduce

In one of your template, use image tag as follow:
```
{% image your_image format-png preserve-svg %}
```
(format-png can be replaced with any other conversion operation)

`your_image` needs to be an SVG image.

In that situation, `Filter.operations` should return an empty list instead of raising an exception. A simple
```
if not self.spec:
    return []
```
will probably do the trick

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: 3.12.3
-   Django version: 5.0.7
-   Wagtail version: 6.2
-   Browser version: Firefox 128

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
Thanks for reporting, @Chadys! It looks like this is already covered by the existing issue #12008.

**Comment by Chadys** [comment]
You are right! sorry for the duplicate, I'll close this one.
I have looked at #12008 and confirmed (via live debugging) that the proposed solution fix the issue in my example usage also :)
