### ISSUE TITLE
Limit of the title's characters to improve Wagtail usage

### ISSUE THREAD

**Issue by AmandaaMoura** [wagtail/wagtail#12217]
### Is your proposal related to a problem?

 This is a proposal to improve the function of adding images into the Wagtail images library because there's no limit of characters to insert an Image's Title. 

### Describe the solution you'd like

Seeking to improve the investment of data into a Wagtail project, I would like to insert a limit to the image's title between 30-50 characters, for a better use of the platform.

![image](https://github.com/user-attachments/assets/6d82e79f-0960-4c6a-ac78-9980bf612e74)

### Working on this

At first, I will consider myself to work on this issue

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
Hi @AmandaaMoura - thanks for the proposal.

As standard there is a 255 character limit on image title, but a developer can change this by defining [a custom image model](https://docs.wagtail.org/en/stable/advanced_topics/images/custom_image_model.html) that redefines the `title` field:

```python
class CustomImage(AbstractImage):
    title = models.CharField(max_length=30)

    admin_form_fields = Image.admin_form_fields
```

I don't think we'd want to enforce a stricter limit within Wagtail itself, as this is a decision for site owners to make - sites with large image collections or highly technical images might have legitimate reasons for using longer titles.
