### ISSUE TITLE
Error on migration for ListBlock - Wagtail 6.2 - IndexError: tuple index out of range

### ISSUE THREAD

**Issue by ducolares** [wagtail/wagtail#12212]
### Issue Summary

My StructBlock has a ListBlock declared keyword arg child_block. 

```
class ElementGradientBlock(blocks.StructBlock):
    element = blocks.CharBlock(label=_("Elemento"), required=True, max_lenth=80, icon="view")
    colors = blocks.ListBlock(
        label=_("Cores"), child_block=blocks.CharBlock(label=_("Cor"), required=True, max_lenth=8, icon="radio-empty")
    )

    class Meta:
        icon = "sliders"
```

When migrating after 6.2, I receive the following error:
IndexError: tuple index out of range

Caused by this method of ListBlock: 

```
def deconstruct_with_lookup(self, lookup):
        path, args, kwargs = super().deconstruct_with_lookup(lookup)
        if getattr(self.__init__, "has_child_block_arg", False) and isinstance(
            args[0], Block
        ):
            block_id = lookup.add_block(args[0])
            args = (block_id, *args[1:])
        return path, args, kwargs
```

To fix it, I had to remove the child_block keyword argument, and use the child_block as position argument, including on the migrations.

### Technical details

-   Python version: Python 3.9.0
-   Django version: Version: 4.2.10
-   Wagtail version: 6.2
-   Browser version: N/A

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
Thanks for the report @ducolares! There's an existing issue #12202 for this, which has now been addressed in #12208 and will be part of a 6.2.1 patch release.
