### ISSUE TITLE
Additional fields when using custom form_class in CreateView for SnippetViewset looks odd

### ISSUE THREAD

**Issue by Quadric** [wagtail/wagtail#12224]
### Issue Summary
I was looking for a solutiion everywhere (even asking AI models :P) without success. I'm not sure if this is a bug, this is not supported or maybe I'm doing something wrong.
I want to add some additional fields to CreateView, fields that are not a part of model - I guess I should be using a custom form class - but when I'm doing this - these custom fields are rendered using only widgets (inputs, etc), without any label, error info and overall UX.

### Steps to Reproduce

1.  I have some model: Wizard:
```python
class Wizard(models.Model):
    title = models.CharField(
        _("title"),
        max_length=256, help_text=_("A short descriptive title.")
    )
```
2. I register this model with SnippetViewSet with custom CreateView
```python
class WizardAdmin(SnippetViewSet):
    model = Wizard
    add_view_class = WizardCreateView
```
3. Make a custom form with field "file" and "abc" (I've also tested form.Form and form.ModelForm as parent class)
```python
class CreateForm(WagtailAdminModelForm):
    file = forms.FileField(label=_("file"))
    abc = forms.CharField(label=_("abc"))

    class Meta:
        model = Wizard
        fields = ["title"]
```
4. Make a WizardCreateView (setting form_class as property doesn't work
```python
class WizardCreateView(CreateView):
    # form_class = CreateForm

    def get_form_class(self):
        return CreateForm
```

And the effect is that it has "title" which is a part of Model - but these two fields "file" and "abc" are rendered only with it's input (no label. no hints, no error messages. ("wybierz plik" <- It renders in polish <- it's "Select file")
![image](https://github.com/user-attachments/assets/0a9a9e0a-1182-42d3-99e5-c5c58779a96a)

If I submit form - it has error handling - but only for title
![image](https://github.com/user-attachments/assets/02005f19-057f-4c43-b4d9-0fa6d23c0648)

### Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I expect that if I use a custom form with additional field the UI will render them the same way as fields that are part of the model. In pure django this method works

### What I was trying to do?
1. I can't use "panels" (FieldPanel) and edit_handlers becaouse "FieldPanel" complains that "file" and "abc" are not a part of Wizard (which is true)
2. I've made some weird idea and made a HelpPanel with custom template that contains 
```django
{% include "wagtailadmin/shared/field.html" with show_label=True help_text=self.help_text field=self.form.file %}
```
and
```django
{% include "wagtailadmin/shared/field.html" with show_label=True help_text=self.help_text field=self.form.abc %}
```
and
```python
    def add_view_edit_handler(self):
        return ObjectList(
                [
                    HelpPanel("file", template="wagtailsnippets/snippets/blueboosterformfactory/wizard/file_panel.html"),
                    HelpPanel("abc", template="wagtailsnippets/snippets/blueboosterformfactory/wizard/abc_panel.html")
                ]
            ).bind_to_model(self.model)
```

And they are rendered quite nice but also these "broken" fields are renderd too - so I guess it's not a good idea and feels like "workaround".

There is ariticle in docs: https://docs.wagtail.org/en/v5.2.6/extending/forms.html - but, well.. nothing usefull to me. 

I don't know. Am I doing something wrong or this is not supported?

### Technical details

-   Python version: 3.11.9
-   Django version: 4.2.13
-   Wagtail version: 5.2.6
-   Browser version:  Edge 127

**Comment by laymonage** [comment]
Hi, thanks for the report.

Have you tried setting `base_form_class = CreateForm` on the `Wizard` model, and adding `FieldPanel("file")` and `FieldPanel("abc")` for the model's `panels` definition (either on the model or the `SnippetViewSet`). You shouldn't need the custom view subclass and the `CreateForm.Meta` class, or any custom templates.

This is outlined in https://docs.wagtail.org/en/v5.2.6/advanced_topics/customisation/page_editing_interface.html#customising-generated-forms.

**Comment by laymonage** [comment]
The base `Panel` class (which `ObjectList` is a subclass of) accepts `base_form_class` as a kwarg, so you can pass that .

So to avoid duplicated code I suppose you can override `get_edit_handler` to also accept a `for_update` kwarg just like `get_form_class()`. Something like


```py
class MySnippetViewSet(SnippetViewSet):
    panels = [
        FieldPanel("file"),
        FieldPanel("abc"),
    ]

    def get_edit_handler(self, for_update=False):
        base_form_class = EditForm if for_update else CreateForm
        edit_handler = ObjectList(self.panels, base_form_class=base_form_class)
        return edit_handler.bind_to_model(self.model)

    def get_form_class(self, for_update=False):
        return self.get_edit_handler(for_update=for_update).get_form_class()

    def get_add_view_kwargs(self, **kwargs):
        return super().get_add_view_kwargs(
            form_class=self.get_form_class(for_update=False),
            panel=self.get_edit_handler(for_update=False),
            **kwargs,
        )

    def get_edit_view_kwargs(self, **kwargs):
        return super().get_edit_view_kwargs(
            form_class=self.get_form_class(for_update=True),
            panel=self.get_edit_handler(for_update=True),
            **kwargs,
        )
```

For more details on how the panels are instantiated, see https://docs.wagtail.org/en/stable/extending/forms.html#panels

**Comment by Quadric** [comment]
Ooooh... thank you! I didn't think of that. Setting base_form_class for ObjectList did the trick.  That was exacly I was looking for ;) Thank you again ;)
