### ISSUE TITLE
 Logged-in users without rights still see the 'edit arrow' visible in the page explorer

### ISSUE THREAD

**Issue by rvoorhorst** [wagtail/wagtail#12240]
### Issue Summary

The 'edit arrow' remains visible for pages in the page explorer for logged in users that belong to a group of users without rights to edit the page in question. Only after clicking on the 'edit arrow' an error message appears that the logged in user does not have rights to edit this page.

### Steps to Reproduce

1. Create page
2. Create user group without permissions to edit this specific page
3. Create user 
4. Add user to the created user group without permissions to edit this specific page
5. Log in as created user without permissions to edit this specific page
6. Edit arrow still appears for this specific page 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I would expect and find it more user friendly to simply NOT show the 'edit arrow'. This does not confuse users and mislead them into thinking that they do have rights to edit the page in question.

<img width="682" alt="Screenshot 2024-08-19 at 12 37 44" src="https://github.com/user-attachments/assets/dc00b01e-f135-451c-a2a9-8102e96a3787">

### Technical details

-   Python version: 3.12
-   Django version: 5.0
-   Wagtail version: 6.1
-   Browser version: issue appears in all browsers

### Working on this

It seems like a fairly easy issue to fix and maybe it's even a conscious choice to show the arrow. I don't know. Unfortunately, I can't fix this issue myself because I'm not a developer.

**Comment by gasman** [comment]
Hi @rvoorhorst - thanks for the report. There's an existing issue open for this at #4660.
