### ISSUE TITLE
504 Gateway Timeout error when attempting to upload or image file

### ISSUE THREAD

**Issue by soukainakhalkhouli** [wagtail/wagtail#12255]
When I click the "Upload" button to upload an image/file from a chooser field, I get 504 error contact your administrator 

<img width="1354" alt="Screenshot 2024-08-26 at 13 14 41" src="https://github.com/user-attachments/assets/3c5272bf-b009-462e-9a3c-8381765a9044">

**Comment by gasman** [comment]
We cannot provide troubleshooting of server issues here, sorry. Please use [the #support channel in the Wagtail Slack](https://docs.wagtail.io/en/stable/support.html) for support queries.
