### ISSUE TITLE
New page shows incorrect privacy info

### ISSUE THREAD

**Issue by smark-1** [wagtail/wagtail#12277]
### Issue Summary
When creating a new page that is a child of a private page the info section shows "Visible to all" but it should be "Private"
![image](https://github.com/user-attachments/assets/c46cf09b-4f3f-4fb3-9680-9cd0f456fc93)

### Steps to Reproduce
- In wagtail bakery create a new page as a child of a private page.
- Click the status icon, see the privacy option

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

- It should show something similar to the edit view, like this:
![image](https://github.com/user-attachments/assets/39805886-3aaf-419b-a903-5eebb8334513)

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.12.5
-   Django version: 5.0.8
-   Wagtail version: 6.2a0 (dev)
-   Browser version: Chrome 128.

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by lb-** [comment]
I can confirm this problem exists. From some quick digging it appears that within the tag `def test_page_is_public(context, page):` there is no `page.path` available when the page is not yet created (which makes sense).

![Image](https://github.com/user-attachments/assets/08676b3f-fda5-4ba2-8431-4efe4b05f392)

https://github.com/wagtail/wagtail/blob/09a9261f7dc90608abb8e3ec00f7f2e83b021294/wagtail/admin/templatetags/wagtailadmin_tags.py#L276-L279

A potential fix might be to either just not show this panel when creating new pages in [`wagtail/admin/ui/side_panels.py`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/ui/side_panels.py#L257).

```py
class PageStatusSidePanel(StatusSidePanel):
    # ...
    def get_status_templates(self, context):
        templates = super().get_status_templates(context)
        # only inject the privacy status if the page exists (not for create page views)
        if self.object.id:
            templates.insert(
                -1, "wagtailadmin/shared/side_panels/includes/status/privacy.html"
            )
        return templates
``

Another potential fix would be to pass in a way to access the parent page to the template, this appears to be a bit of a larger change.

[`wagtail/admin/templates/wagtailadmin/shared/side_panels/includes/status/privacy.html`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/side_panels/includes/status/privacy.html#L5)
```html
{% extends 'wagtailadmin/shared/side_panels/includes/action_list_item.html' %}
{% load i18n wagtailadmin_tags %}

{% block content %}
    {% if page.id %}{% test_page_is_public page as is_public %}{% else %}{% test_page_is_public parent_page as is_public %}{% endif %}
```

Then, we need to pass the `parent_page` through from `wagtail/admin/views/pages/create.py` in the `CreateView.get_side_panels` method, then pass it through to the context in `PageStatusSidePanel`. We may need to also do the same for the `EditView`.
