### ISSUE TITLE
Unable to share a preview link

### ISSUE THREAD

**Issue by willcook4** [wagtail/wagtail#12282]
### Issue Summary

Unable to share a preview link with other admin users.

### Steps to Reproduce
1. On an existing project e.g Pull the latest [wagtail bakery](https://github.com/wagtail/bakerydemo).
2. Open admin in one browser e.g. Chrome (simulating one user)
3. Login and edit a page. Copy the Preview link from the 'Preview in a new tab button'  
e.g. http://localhost:8000/admin/pages/60/edit/preview/?mode=
4. Open another browser e.g. Safari (simulating second user) and go to the copied link
5. The user will not be logged in and will be taken to the login screen with a redirect url e.g.
http://localhost:8000/admin/login/?next=/admin/pages/60/edit/preview/%3Fmode%3D
6. Login with credentials
7. An Error shows on the route e.g. http://localhost:8000/admin/pages/60/edit/preview/?mode=
**Preview not available**
Preview cannot display due to validation errors.
Click save to highlight the relevant fields.

This can be a useful feature that some of our content loaders use to share working status changes of pages internally. This used to be something that worked in older versions of Wagtail. Sorry I am unable to provide a version of Wagtail where it broke. Maybe we just need to be better at using the Moderators workflows.

I consider this a bug. I would expect the latest draft revision for that page to render when the second user visits the page after logging in.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **Yes**

### Technical details
As tested with the latest Wagtail Bakery
-   Python version: 3.12.5
-   Django version: 5.0.8
-   Wagtail version: Version: 6.2.1
-   Browser version: Chrome: 128.0.6613.86, Safari 17.5

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by laymonage** [comment]
This is expected, that preview link is specific to your current editing session and not meant to be viewed when you're not editing, because the data comes from the form that has not been saved into a revision.

To share a preview of a saved draft revision, you can go to the history view and click on the three-dot menu and click Preview. That link can be shared to other admin users who have permissions to edit the page.

![image](https://github.com/user-attachments/assets/b8aaea6f-8b59-4dbd-a827-956fddc15f72)

**Comment by willcook4** [comment]
Thank you for reviewing @laymonage. It's nice to find things like the ability to share a preview of a saved draft revision! Thanks for sharing. I figured that there must be something specific to the users editing session, appreciate you confirming.
