### ISSUE TITLE
Report for (search) query hits

### ISSUE THREAD

**Issue by robmoorman** [wagtail/wagtail#12294]
### Is your proposal related to a problem?

In order to gain insight into the popular search teams as a content editor and/or marketeer I want to view a report.

Currently the only way is to view this by registering a (django) ModelAdmin config or use the popup via search promotions.

### Describe the solution you'd like

An option to add a report with search teams with relevant filters via the settings, just as any other wagtail report.
As reports are not often familiar for content editors it would be nice to switch this feature on/off via django settings.

### Working on this

We have capacity to create this report as a pull request. Planned already to implement this within an active project.

**Comment by thibaudcolas** [comment]
Sounds great @robmoorman! I can see why it’d be useful to view this information in a filterable / export-able report.

> An option to add a report with search teams with relevant filters via the settings, just as any other wagtail report.
> As reports are not often familiar for content editors it would be nice to switch this feature on/off via django settings.

From my perspective I’d expect the presence of the report by default for sites using this app to not be much of an issue, as reports have their own menu item to be hidden inside of. It’d be nice to align with other apps / reports on how exactly this is configurable

**Comment by robmoorman** [comment]
Ok great! We will see if we can put a PR in on short notice. I expect it's an easy feature to implement and review as it makes pretty sense what to do here and put in the report.

Looking at other "feature flags" the name of the setting can be something like `WAGTAIL_SEARCHPROMOTION_REPORT_ENABLED` (default set to `True`). It's sort of a convention to put the `xxx_ENABLED` to turn a feature on/off.

**Comment by gasman** [comment]
Completed in #12341.
