### ISSUE TITLE
404 page in admin Search

### ISSUE THREAD

**Issue by smark-1** [wagtail/wagtail#12297]
### Issue Summary
When clicking the user tab in search a 404 error appears.

![image](https://github.com/user-attachments/assets/be2d9737-d771-4f3d-ab65-50f271a0772a)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject` or use bakery demo/existing project
2. go to the universal search page (search for "a" in the admin nav bar)
![image](https://github.com/user-attachments/assets/72f118e4-523e-4713-ac92-3ed57fe2fa27)
3. click the "users" option.
![image](https://github.com/user-attachments/assets/be2d9737-d771-4f3d-ab65-50f271a0772a)
You will then see a 404 error
![image](https://github.com/user-attachments/assets/38776598-378b-43ae-82df-fe12ecaa4252)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

- The error is do to the link using the namespace without converting to url - "http://localhost:8000/admin/pages/search/wagtailusers_users:index/?q=a"
-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details
-   Django version: 5.1
-   Wagtail version: 6.2 and 6.3 (dev)

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by smark-1** [comment]
Likely the same issue when go to settings>users and search the Users menu item does not change to be the active color

**Comment by gasman** [comment]
Fixed in #12298
