### ISSUE TITLE
Update `BaseGroupApprovalTaskStateEmailNotifier` to check for `AbstractGroupApprovalTask` instances

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#12328]
#11653 added `AbstractGroupApprovalTask` and `GroupApprovalTask` inherits from it.

howevere the `BaseGroupApprovalTaskStateEmailNotifier` still checks `GroupApprovalTask` - https://github.com/wagtail/wagtail/blob/6affa04d320f50b6a3babd8afc1a590e02e84a5d/wagtail/admin/mail.py#L368-L373

This means any custom group tasks derived from `AbstractGroupApprovalTask`s require adding custom notifiers and wiring in a signal handler

**Comment by its-kunal** [comment]
I like to work on this issue, please assign.

**Comment by zerolab** [comment]
We don't assign issues to anyone outside the core team. Feel free to work on this.
I suggest reading https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html

**Comment by sumana-2705** [comment]
@zerolab I have attempted to solve the issue, please have a look and suggest me the changes required
