### ISSUE TITLE
`wagtail start mysite mysite` is very slow and causes 100% CPU spikes

### ISSUE THREAD

**Issue by raffaelj** [wagtail/wagtail#12334]
### Issue Summary

I tried wagtail on my local machine and followed this quick start tutorial:

https://docs.wagtail.org/en/stable/getting_started/tutorial.html

After running `wagtail start mysite mysite` my fans got louder and louder, all CPU cores were on 99-100%. Also the RAM of the terminal spiked to around 800MB. After 1 to 2 minutes, the setup is done and successful. Before and after this command, everything worked fast and without CPU spikes.

### Steps to Reproduce

```bash
# everything works and is fast
mkdir test && cd test
python3 -m venv mysite/env
source mysite/env/bin/activate
pip install wagtail

# Takes 1-2 minutes, 100% CPU on all cores
wagtail start mysite mysite

# everything works and is fast again
cd mysite
pip install -r requirements.txt
python manage.py migrate
python manage.py createsuperuser
python manage.py runserver
```

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11.9
-   Django version: 5.0.9
-   Wagtail version: 6.2.1
-   Browser version: irrelevant
-   OS: openSUSE Tumbleweed, Desktop: sway (Tiling window manager, Wayland), Terminal: Konsole (default KDE terminal)

### Working on this

I never did anything in Python, except reading some source code for inspiration, so I can't do much myself. But I was able to trace the bug down with some `print` commands to `utility.execute()` in:

https://github.com/wagtail/wagtail/blob/main/wagtail/bin/wagtail.py#L120

So it might be a django issue and not a wagtail issue. But it's a show stopper to give wagtail another try.

**Comment by thibaudcolas** [comment]
Hi @raffaelj, thank you for reporting. Could you share what happens when you run Django’s `startproject` command directly? Our `start` command is a very thin wrapper around Django’s command, with different defaults. So I’d be surprised if there was a Wagtail-specific implementation that caused this issue, but we can rule that out if you report how `startproject` works.

Re giving Wagtail a try, you could go with a more fully-fledged project like https://github.com/wagtail/bakerydemo. Then there’s no need for the `start` command. Or this: https://github.com/thibaudcolas/wagtail-tutorial-site is the same code as our `start` command’s template.

**Comment by raffaelj** [comment]
> Could you share what happens when you run Django’s startproject command directly?

For some reason, it was much faster this time (only 36 seconds, instead of 100 seconds).

```bash
# same install steps like in the initial issue description above

# Takes 36 seconds, CPU at 100%
# wagtail start mysite mysite
time wagtail start mysite mysite

# Install only django
# Takes 36 seconds, CPU at 100%
time django-admin startproject --ext=html,rst --name=Dockerfile mysite mysite

# Install Wagtail
# Takes 36 seconds, CPU at 100%
time django-admin startproject --template=/path/to/wagtail/test/mysite/env/lib64/python3.11/site-packages/wagtail/project_template --ext=html,rst --name=Dockerfile mysite mysite
```

So it looks like a django problem...

---

> Re giving Wagtail a try [...] Then there’s no need for the start command.

This defeats the purpose of a stable, reproducable install script. And I won't jump from PHP into Python just for fun if I'm not able to run a simple hello world page.

---

Now I tried it on a different PC in another room (EndeavourOS/Arch, still on X with i3 window manager, Python 3.12.6, Django 5.0.9, Wagtail 6.2.1).

Only Python 3.12.6 is installed. The failing test was on a system with multiple python versions (2.7, 3.8, 3.10, 3.11).

The `start` command took less than a second. Now it looks like a me problem :-(

Maybe it's finally time to reinstall my whole dev setup and move to Arch. It slowly falls apart since openSUSE forced Wayland with Plasma6 a few months ago...

But still a very weird issue, that feels like an endless loop in a sub-process problem somewhere in the install process...

**Comment by thibaudcolas** [comment]
👍 "less than a second" is the kind of time we expect. All `startproject` does is creating directories and creating or copying files + some chmod + some umask (source is here: [django/django template.py](https://github.com/django/django/blob/main/django/core/management/templates.py)). I’d expect one of the underlying system calls is causing trouble on your machine but have no idea which one might cause such a big CPU + RAM usage spike. 

---

I’ve had a look at [Django tickets](https://code.djangoproject.com/query) to see if similar issues had been reported and can’t find anything, so if you want to take this further I’d recommend reporting there.

**Comment by raffaelj** [comment]
@thibaudcolas Thanks for the pointers. I found the underlying issue :smiley:. `black` is installed globally on my machine and Django forces running `black` if it is in `$PATH` in [django/django utils.py](https://github.com/django/django/blob/main/django/core/management/utils.py#L164). This in turn iterates through 178,1 MiB, 14.574 files, 5.884 sub-folders to check for formatting issues.

On my other machine, `black` is not installed. So all went smooth.

My main system has black globally installed:

```bash
which black
# /usr/bin/black

black --version
# black, 24.4.2 (compiled: no)
# Python (CPython) 3.10.14
```

The 100% CPU load is also reproducable when installing `black` locally:

```bash
pip install black
$(which black) --version
# black, 24.8.0 (compiled: yes)
# Python (CPython) 3.11.9

pip install wagtail
time wagtail start mysite mysite
# real    0m40,662s
```

This also solves two other things, I didn't mention yet:

1. Deleting everything in `mysite`, except the `env` folder and running `wagtail start` again was always fast and I had to delete and reinstall everything to reproduce this issue. Black caches it's previous runs, so only the first run causes this massive load.
2. After running the `start` command, with my debugging `print()` commands all over the place, my text editor showed a message, that the file was modified on disk. With many files copied around during these tests, I didn't look deeper into that one. But running a diff on the changes showed, that single quotation marks in my local changes were converted to double quotation marks. Now it's clear, that `black` caused it.

## Workarounds/solution

Uninstall the globally installed `black`.

If this is not possible or not wanted, a quick and dirty override helps to bypass this massive CPU load:

```bash
# everything works and is fast
mkdir test && cd test
python3 -m venv mysite/env
source mysite/env/bin/activate
pip install wagtail

# quick and dirty: disable globally installed black formatter
printf '#!'"/bin/bash\necho 'Black is disabled'" > mysite/env/bin/black
chmod +x mysite/env/bin/black

# Takes less than a second
# 'Black is disabled' doesn't show up, because it runs in a subprocess
wagtail start mysite mysite
```
