### ISSUE TITLE
User deletion not possible - relation "wagtailcore_uploadedfile" does not exists

### ISSUE THREAD

**Issue by ryanfadeau** [wagtail/wagtail#12345]
Hi guys, I've just tried to delete a user in the django admin (not even wagtail admin) and I have a migration error:
- `relation "wagtailcore_uploadedfile" does not exists`
I don't understand why I have this error since when I'm doing `python manage.py makemigrations` no migrations are detected...

I'm on my local machine but I'm scared that this happens in production and do not know what steps I have to do...

I will appreciate any help, thank you guys !
### Steps to Reproduce

1. Go to your django admin
2. Try delete a user

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project:  no, it's on a project already running

### Technical details

-   Python version: 3.10
-   Django version: 5.1.
-   Wagtail version: 6.2.1
-   Browser version: Chrome 127

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by laymonage** [comment]
You mentioned running `python manage.py makemigrations`, but have you run `python manage.py migrate`?

**Comment by ryanfadeau** [comment]
Yes I also tried this, it's in my docker compose so at each build those commands are run

And I even try this within my docker container, so it's quit strange :/

**Comment by laymonage** [comment]
@ryanfadeau could you run `python manage.py showmigrations wagtailcore` and let us know the output? Thanks!

**Comment by ryanfadeau** [comment]
```
[X] 0001_squashed_0016_change_page_url_path_to_text_field (16 squashed migrations)
 [X] 0017_change_edit_page_permission_description
 [X] 0018_pagerevision_submitted_for_moderation_index
 [X] 0019_verbose_names_cleanup
 [X] 0020_add_index_on_page_first_published_at
 [X] 0021_capitalizeverbose
 [X] 0022_add_site_name
 [X] 0023_alter_page_revision_on_delete_behaviour
 [X] 0024_collection
 [X] 0025_collection_initial_data
 [X] 0026_group_collection_permission
 [X] 0027_fix_collection_path_collation
 [X] 0024_alter_page_content_type_on_delete_behaviour
 [X] 0028_merge
 [X] 0029_unicode_slugfield_dj19
 [X] 0030_index_on_pagerevision_created_at
 [X] 0031_add_page_view_restriction_types
 [X] 0032_add_bulk_delete_page_permission
 [X] 0033_remove_golive_expiry_help_text
 [X] 0034_page_live_revision
 [X] 0035_page_last_published_at
 [X] 0036_populate_page_last_published_at
 [X] 0037_set_page_owner_editable
 [X] 0038_make_first_published_at_editable
 [X] 0039_collectionviewrestriction
 [X] 0040_page_draft_title
 [X] 0041_group_collection_permissions_verbose_name_plural
 [X] 0042_index_on_pagerevision_approved_go_live_at
 [X] 0043_lock_fields
 [X] 0044_add_unlock_grouppagepermission
 [X] 0045_assign_unlock_grouppagepermission
 [X] 0046_site_name_remove_null
 [X] 0047_add_workflow_models
 [X] 0048_add_default_workflows
 [X] 0049_taskstate_finished_by
 [X] 0050_workflow_rejected_to_needs_changes
 [X] 0051_taskstate_comment
 [X] 0052_pagelogentry
 [X] 0053_locale_model
 [X] 0054_initial_locale
 [X] 0055_page_locale_fields
 [X] 0056_page_locale_fields_populate
 [X] 0057_page_locale_fields_notnull
 [X] 0058_page_alias_of
 [X] 0059_apply_collection_ordering
 [X] 0060_fix_workflow_unique_constraint
 [X] 0061_change_promote_tab_helpt_text_and_verbose_names
 [X] 0062_comment_models_and_pagesubscription
 [X] 0063_modellogentry
 [X] 0064_log_timestamp_indexes
 [X] 0065_log_entry_uuid
 [X] 0066_collection_management_permissions
 [X] 0067_alter_pagerevision_content_json
 [X] 0068_log_entry_empty_object
 [X] 0069_log_entry_jsonfield
 [X] 0070_rename_pagerevision_revision
 [X] 0071_populate_revision_content_type
 [X] 0072_alter_revision_content_type_notnull
 [X] 0073_page_latest_revision
 [X] 0074_revision_object_str
 [X] 0075_populate_latest_revision_and_revision_object_str
 [X] 0076_modellogentry_revision
 [X] 0077_alter_revision_user
 [X] 0078_referenceindex
 [X] 0079_rename_taskstate_page_revision
 [X] 0080_generic_workflowstate
 [X] 0081_populate_workflowstate_content_type
 [X] 0082_alter_workflowstate_content_type_notnull
 [X] 0083_workflowcontenttype
 [X] 0084_add_default_page_permissions
 [X] 0085_add_grouppagepermission_permission
 [X] 0086_populate_grouppagepermission_permission
 [X] 0087_alter_grouppagepermission_unique_together_and_more
 [X] 0088_fix_log_entry_json_timestamps
 [X] 0089_log_entry_data_json_null_to_object
 [X] 0090_remove_grouppagepermission_permission_type
 [X] 0091_remove_revision_submitted_for_moderation
 [X] 0092_alter_collectionviewrestriction_password_and_more
 [X] 0093_uploadedfile
 [X] 0094_alter_page_locale
```
Here's the output

**Comment by laymonage** [comment]
Hi @ryanfadeau, sorry for the late reply.

That's strange – the `0093_uploadedfile` migration should have created the `wagtailcore_uploadedfile` table. Could you perhaps try the following:

```
python manage.py migrate --fake wagtailcore 0092_alter_collectionviewrestriction_password_and_more
python manage.py migrate wagtailcore 0093_uploadedfile
python manage.py migrate --fake 0094_alter_page_locale
```

The first command will fake the migration state to before migration 0093 is run (without actually rolling back the migrations). The second command will re-run migration 0093 (so the table should be created). The second command fakes the migration state to after migration 0094 is run, so that we don't apply it twice.

**Comment by ryanfadeau** [comment]
Well I think I have done something wrong with my migrations in the first place.
I deleted all my database for another issue and the bug that I've reported is no longer here.
I have maybe do a --fake on all my migration at a certain time which caused the supposed bug. I think we can close this issue

**Comment by gasman** [comment]
Thanks for confirming @ryanfadeau!
