### ISSUE TITLE
Update notification email header image

### ISSUE THREAD

**Issue by Stormheg** [wagtail/wagtail#12369]
### Issue Summary

When receiving an email notification from Wagtail, the image header appears to use the old logo and green/teal background.

<img width="619" alt="Screenshot 2024-09-27 at 11 49 07 AM" src="https://github.com/user-attachments/assets/e907f1cb-e43d-401d-b7fe-6591fd6cd51d">

### Steps to Reproduce

1. On a Wagtail site, submit a page for moderation in a workflow.
2. A moderator should receive a notification email from Wagtail
3. If applicable, click 'load images' in your email client.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.12.4
-   Django version: 5.0.9
-   Wagtail version: 6.1.3
-   Browser version: N/A

### Working on this

Relevant image file is located at: https://github.com/wagtail/wagtail/blob/main/wagtail/admin/static_src/wagtailadmin/images/email-header.jpg

I'd expect an image with the new Wagtail logo (see https://github.com/wagtail/wagtail/pull/11756) and a dark purple background, like Wagtail uses these days.

The base notifications template: https://github.com/wagtail/wagtail/blob/abcb2da37259c16d1efd16d7233794f00bb29680/wagtail/admin/templates/wagtailadmin/notifications/base.html

**Comment by ovindu-a** [comment]
Hi, I would like to work on this

**Comment by ShreeHarish** [comment]
Hey, I would like to work on this issue.

**Comment by ShreeHarish** [comment]
Hi, I would like to work on this issue.

**Comment by Itzyashraj** [comment]
Hi sir , I am a beginner to this open source but I feel confident that I can give my best and help solving this issue , it would be really helpful if you let me handle this issue

**Comment by zerolab** [comment]
Hi all potential contributors, welcome, and please do read https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html and take it from there
