### ISSUE TITLE
Support Latest Version of django-taggit (6.1+)

### ISSUE THREAD

**Issue by dustinblanchard** [wagtail/wagtail#12372]
### Is your proposal related to a problem?

Right now Wagtail requires django-taggit `<5.1,>=5.0`. The newer versions include performance fixes, explicit django 5 support and helpful tooling for merging, deduplicating and removing orphan tags.  

### Describe the solution you'd like

Update django-taggit version constraints at least to allow <7

### Describe alternatives you've considered

N/A

### Additional context

The newer versions do not list any breaking changes / backwards incompatibility in the changelog.

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
Already done for the next release in #12220.

**Comment by gasman** [comment]
Ah, sorry, missed the mention of 6.1 :-)
