### ISSUE TITLE
Images Admin Api Unauthorized Request

### ISSUE THREAD

**Issue by JeroenJADS** [wagtail/wagtail#12386]
### Issue Summary

Upon translating a page from EN to Dutch that has an image uploaded, Wagtail tries to call an url "en/cms/api/main/images/1/", which is called the Images Admin Api but is unauthorized to do so. This in turn leads to an error in wagtail-localize.js since the image can not be found.
<img width="1463" alt="Screenshot 2024-10-03 at 8 02 35 AM" src="https://github.com/user-attachments/assets/4cece57b-d05a-4adf-b1be-fa7e6bcdfb06">

### Steps to Reproduce

1. Add a page in the original Wagtail Language
2. Add an image field and upload any image
3. Translate the page, select the desired language and hit confirm
4. The next page will throw the 2 errors above.

### Technical details

-   Wagtail 6.2
-   Django version: 5.0.4
-   Browser version: Chrome 129.

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by zerolab** [comment]
Closing as this is potentially a wagtail-localize issue and you've opened one there as well https://github.com/wagtail/wagtail-localize/issues/827
