### ISSUE TITLE
Add roadmap link to the README

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#12399]
It would be good to see a link to our [roadmap](https://wagtail.org/roadmap/) in the readme. While we're at it it may make sense to make the words 'release notes' into a link to our [docs releases](https://docs.wagtail.org/en/stable/releases/index.html) page. 

https://github.com/wagtail/wagtail/blob/912c0881f9bf17adb03a8c7fe83ab36c969b0521/README.md?plain=1#L73

![Screenshot_20241010-221231](https://github.com/user-attachments/assets/34445560-8e22-460e-b40d-c7ebb4f862ea)

**Comment by Suraj-kumar00** [comment]
Hi @lb- , how have you been?
Can I work on this issue?

**Comment by Rohit-Singh-01** [comment]
Hi @lb- and @Suraj-kumar00, I’m really excited about the opportunity to contribute to Wagtail and would love to work on issue #12399. Could I please be assigned to it? Thank you for considering my request!

**Comment by gasman** [comment]
Hi @Suraj-kumar00 and @Rohit-Singh-01 - thanks for your interest! We do not assign issues outside of the core team - anyone is free to work on any issue.

We recommend thoroughly reading https://docs.wagtail.org/en/latest/contributing/first_contribution_guide.html before making your first contribution. You may also wish to join [our #new-contributors channel on Slack](https://github.com/wagtail/wagtail/wiki/Slack).

**Comment by Rohit-Singh-01** [comment]
thanks for the response @gasman , ll take care of it
