### ISSUE TITLE
Custom Richtext features not persistant

### ISSUE THREAD

**Issue by byfarm** [wagtail/wagtail#12401]
### Custom Rich text feature not persistent

I have made a custom richtext feature that changes the color of the text to a custom color. I am able to save and publish and it shows up correctly on the live page. However, when I go back to edit the page, the colors are not there anymore, and if I publish the page with no changes, the live page no longer shows the custom colors I made.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject` and create a page with a rich text field.
2. Create a template for the page that shows the rich text field.
3. Register a custom hook using `@hooks.register('register_rich_text_features')`. I have included some example code of mine bellow.
4. Apply the feature to an element in the page, publish the page, then go back to edit the page. The feature should no longer be applied to the element.

```
def register_new_feature(
    features,
    feature_name,
    type_,  # type (must be different for each feature)
    tag,  # html tag
    label,  # label in editor
    description,
    style=None,  # style in editor
    position=None,
): 
    # add to controls so draftail can see it
    control = {
        'type': type_,
        'label': label,
        'description': description,
    }

    if style:
        control['style'] = style

    # register the feature on draftail
    features.register_editor_plugin('draftail', feature_name, draftail_features.InlineStyleFeature(control))

    # register the feature on the db
    db_conversion = {
        'from_database_format': {tag: InlineStyleElementHandler(type_)},
        'to_database_format': {'style_map': {type_: tag}},
    }
    features.register_converter_rule('contentstate', feature_name, db_conversion)

    if position is None:
        # add the feature to the end of the editor
        features.default_features.append(feature_name)
    else:
        # add the feature to the specified position
        features.default_features.insert(position, feature_name)

@hooks.register('register_rich_text_features')
def register_text_colors(features):
    colors = [
        (
            'lightorange',  # feature name
            'LIGHT_ORANGE',  # type (must be different for each)
            'span class="text-orange"',  # html tag
            'L-Orange',  # label in editor
            'Light Orange',  # help text
            {'color': '#de774a'},  # style in editor
        ),
    ]

    for c in colors:
        register_new_feature(features, *c, 0)
```
Note that I do have a css class for `text-orange`.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: 3.11.9
-   Django version: 5.0.9
-   Wagtail version: 6.2.1
-   Browser version: firefox 131

**Comment by gasman** [comment]
Hi @byfarm,

```python
'span class="text-orange"',  # html tag
```

This is not valid. As per [the examples further down the "Extending Draftail" docs](https://docs.wagtail.org/en/stable/extending/extending_draftail.html#creating-new-blocks), the conversion from database format back to Draftail works by matching elements based on CSS-like rules, so the dictionary that you pass as `from_database_format` would have to be something like:

```python
{"span[class=text-orange]": InlineStyleElementHandler(type_)}
```

This in turn means you'll have to refactor your `register_new_feature` function to account for the fact that you can't pass a single `tag` parameter to define the conversions in both directions.

**Comment by byfarm** [comment]
Hello @gasman ,
Awesome! Thank you, I have split the `tag` variable into `tag_from_db` and `tag_to_db` and inserted them like this on the db_conversion:
```
    tag_from_db = 'span[class=text-orange]'
    tag_to_db = 'span class="text-orange"'

    db_conversion = {
        'from_database_format': {tag_from_db: InlineStyleElementHandler(type_)},
        'to_database_format': {'style_map': {type_: tag_to_db}},
    }
```
and now it works! thank you so much!
