### ISSUE TITLE
Documentation - Clean up the *Reference > Pages* sub-pages to be only about Page models

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#12435]
### Pertinent section of the Wagtail docs

> https://docs.wagtail.org/en/stable/reference/pages/index.html
![Image](https://github.com/user-attachments/assets/ac9d2dee-c0ab-4f7c-8360-165a9477a122)

### Details

* Within the `Reference` section of our documentation, we have a sub-page called `Pages`. This contains the 'Model reference' and 'Panel types' documentation, however, these are not specific to the Page models.
* I have found it confusing but have kind of gotten used to it, but from a newcomer perspective it feels odd. Panels are now fully supported across Snippets and Pages, the Model reference page has all models (not just pages).
* There are a few other changes that would make this 'Reference > Pages' section a bit more consistent and predictable.

#### Proposed changes

1. Move [`Panel types`](https://docs.wagtail.org/en/stable/reference/pages/panels.html) directly under [`Reference`](https://docs.wagtail.org/en/stable/reference/index.html).
2. Move [`Model Reference`](https://docs.wagtail.org/en/stable/reference/pages/model_reference.html) directly under [`Reference`](https://docs.wagtail.org/en/stable/reference/index.html).
3. Update the title of [`Model Reference`](https://docs.wagtail.org/en/stable/reference/pages/model_reference.html) to `Model reference` (lower case `r`, as this is the way most page titles are capitalised and `Reference` is not a proper noun.
4. Split the **tagging** section from [`Recipes`](https://docs.wagtail.org/en/stable/reference/pages/model_recipes.html) out to a new page called Tags to directly under `Advanced topics` called `Tags`.
5. Fix the incorrect heading level nesting in [`Recipes`](https://docs.wagtail.org/en/stable/reference/pages/model_recipes.html) for the 'adding endpoints with custom route methods, it should be the same level as 'overriding the serve method' not one under it.
6. Minor update to the text `wagtail.models` to use double backticks so that it appears highlighted as code. See https://github.com/wagtail/wagtail/blob/105338d0d63c5a8adf285d3c077a922f53a15d02/wagtail/models/__init__.py#L2 (we may also want to fix up the other backtick usage in that docstring to be double backticks)  * See https://github.com/wagtail/wagtail/blob/105338d0d63c5a8adf285d3c077a922f53a15d02/wagtail/models/__init__.py#L331C16-L331C31 for an example of the double backticks being used correctly to style as pre/code in the published docs. 

### Working on this

* Feel free to cover items 1-3 as a stand-alone PR, it may make reviews easier.
* Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by Srishti-j18** [comment]
Hi @lb- 
Could you please review my PR and suggest me if any changes are required?

**Comment by thibaudcolas** [comment]
@Srishti-j18 there’s no need to @-mention reviewers, please wait for people to get to pull requests on their own schedule.

**Comment by lb-** [comment]
Thanks @Srishti-j18 I've added a review to one of them.

**Comment by gasman** [comment]
Hi @lb- - just saw (via #12438) that the "wagtail.models is split into submodules for maintainability..." text now appears on the model reference page. This is actually guidance for Wagtail developers working on the wagtail.models module, so isn't really appropriate to be surfaced on documentation about _using_ the code. (In hindsight, it should probably have been a plain code comment rather than a docstring...)

**Comment by lb-** [comment]
Hmm good point, I will raise an issue about that - should we try to fix for 6.3? (it's there currently, but not sure how long it's been like that).

https://docs.wagtail.org/en/stable/reference/pages/model_reference.html

![Image](https://github.com/user-attachments/assets/45c56494-ff0d-42f7-9457-adf0904eef42)

@gasman

**Comment by laymonage** [comment]
It's been the case since 2.14 it seems...

- https://docs.wagtail.org/en/v2.14.2/reference/pages/model_reference.html
- https://docs.wagtail.org/en/v2.13.5/reference/pages/model_reference.html

**Comment by laymonage** [comment]
I've added a redirect on the RTD dashboard for this. See:
- https://docs.wagtail.org/en/latest/reference/pages/model_reference.html
- Should redirect to https://docs.wagtail.org/en/latest/reference/models.html
- Older version(s) should still be under the old URL: https://docs.wagtail.org/en/stable/reference/pages/model_reference.html

**Comment by gasman** [comment]
> It's been the case since 2.14 it seems...
> 
> * https://docs.wagtail.org/en/v2.14.2/reference/pages/model_reference.html
> * https://docs.wagtail.org/en/v2.13.5/reference/pages/model_reference.html

Ah, hadn't realised this was a long running issue! Definitely doesn't need to be fixed for 6.3 then.

(Thanks for sorting the redirects, @laymonage!)

**Comment by lb-** [comment]
@gasman  @laymonage  - PR up for the code modules reference text fix.
https://github.com/wagtail/wagtail/pull/12485
