### ISSUE TITLE
Error 400 due to hitting the DATA_UPLOAD_MAX_NUMBER_FIELDS limit

### ISSUE THREAD

**Issue by Ash-Crow** [wagtail/wagtail#12452]
### Issue Summary
In the Wagtail admin, I get blank "error 400" pages when editing some pages.

### Steps to Reproduce
1. Start a new project with `wagtail start myproject`
3. Create a model with a streamfield that includes a variety of complex blocks such as the ContentPage model of https://github.com/numerique-gouv/sites-faciles/
4. Create a page that includes a lot of these blocks and try to save. Add some more and try to save again. Repeat a few times.

When running this on a production site, I just get an error 400 with no further explanation. Doing the same in a local environment with DEBUG at True, I can see the actual error: `The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.` I think Wagtail should capture this error and display a readable error message in the admin instead of the blank error 400 (which by the way should be an error 500 as it is server side, and it seems to have been at some point, per #6198.)

Maybe the documentation page for Streamfields should also be updated so that users are made aware of the issue, with a suggestion for a new sensible value (when searching for this bug, I've seen 10000 either here #4254 or [there](https://issues.apache.org/jira/browse/AIRAVATA-3365).

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: 3.12.3
-   Django version: 5.1.2
-   Wagtail version: 6.2.2
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
Hi @Ash-Crow - thanks for the report. While I wouldn't expect developers to run into this limit unless they had an unusually large and complex page (and in that sense the DATA_UPLOAD_MAX_NUMBER_FIELDS setting is serving its intended purpose of flagging this up as suspicious...), I will concede that it's more likely to be encountered legitimately in the Wagtail admin (and StreamField in particular) than most Django apps - and so there's a good argument for raising it.

I'd propose increasing this in Wagtail's [default project template](https://github.com/wagtail/wagtail/blob/main/wagtail/project_template/project_name/settings/base.py), as well as documenting it as a recommendation in the [Integrating into Django](https://docs.wagtail.org/en/stable/getting_started/integrating_into_django.html) docs.

Will raise this with the rest of the core team today to see what they think.

**Comment by gasman** [comment]
> I'd propose increasing this in Wagtail's [default project template](https://github.com/wagtail/wagtail/blob/main/wagtail/project_template/project_name/settings/base.py), as well as documenting it as a recommendation in the [Integrating into Django](https://docs.wagtail.org/en/stable/getting_started/integrating_into_django.html) docs.

Core team is happy with bumping the default to 10000 as per above.

**Comment by tm-kn** [comment]
Could we also create a specific QueryDict for Wagtail forms and have a custom setting for those, rather than affecting the settings of the whole Django project?
https://github.com/django/django/blob/2d612162d8cabfe7dcfe07e097ec8d198b3ff8cd/django/http/request.py#L546

**Comment by gasman** [comment]
@tm-kn I feel like that might over-complicate things if people want to override the value to something different (e.g. they have a _really_ complex streamfield that exceeds 10000 fields).

**Comment by krystianmagdziarz** [comment]
@gasman Not really. Timeline components on news sites generate such cases. One of my clients reached this limit very quickly and a complete remodeling of the business logic was necessary.
