### ISSUE TITLE
Missing Cache-Control Headers for Password-Protected Pages

### ISSUE THREAD

**Issue by krystianmagdziarz** [wagtail/wagtail#12455]
### Issue Summary

When serving password-protected pages in Wagtail, the application does not set appropriate cache-control headers to prevent these pages from being cached by browsers or intermediary proxies like Squid. This can lead to security issues where protected content may be inadvertently exposed to unauthorized users through cached content.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`.
2. Create a new page (e.g., `ProtectedPage`) and publish it.
3. In the Wagtail admin interface, add a password restriction to the page:
   - Go to the page in the admin.
   - Click on **"Settings" > "Privacy"**.
   - Select **"Private, accessible with the following password"** and set a password.
4. Access the password-protected page in a web browser.
5. Enter the correct password when prompted.
6. Use browser developer tools or a tool like `curl` to inspect the response headers.

**Observed Behavior:**

- The response headers do not include `Cache-Control`, `Pragma`, or `Expires` headers to prevent caching.
- As a result, the password-protected page may be cached by the browser or intermediary caches.

**Expected Behavior:**

- The response should include headers that prevent caching, such as:

**Cache-Control: no-store, no-cache, must-revalidate, max-age=0 Pragma: no-cache Expires: 0**

- This ensures that password-protected content is not cached and remains secure.

- **I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes**

### Working on this

I am willing to work on this issue and submit a pull request. My proposed solution involves adding appropriate cache-control headers to the HTTP response to prevent caching.

**Additional Notes:**

- The lack of cache-control headers on password-protected pages poses a security risk, as sensitive content might be stored in browser caches or intermediary proxies.
- Implementing this fix will enhance the security of Wagtail applications by ensuring that protected content is not inadvertently exposed.

**Proposed Solution:**

```python
from django.utils.cache import add_never_cache_headers


@hooks.register("before_serve_document")
def check_view_restrictions(document, request):
    """
    Check whether there are any view restrictions on this document which are
    not fulfilled by the given request object. If there are, return an
    HttpResponse that will notify the user of that restriction (and possibly
    include a password / login form that will allow them to proceed). If
    there are no such restrictions, return None
    """
    for restriction in document.collection.get_view_restrictions():
        if not restriction.accept_request(request):
            if restriction.restriction_type == BaseViewRestriction.PASSWORD:
                from wagtail.forms import PasswordViewRestrictionForm

                form = PasswordViewRestrictionForm(
                    instance=restriction,
                    initial={"return_url": request.get_full_path()},
                )
                action_url = reverse(
                    "wagtaildocs_authenticate_with_password", args=[restriction.id]
                )

                password_required_template = getattr(
                    settings,
                    "WAGTAILDOCS_PASSWORD_REQUIRED_TEMPLATE",
                    "wagtaildocs/password_required.html",
                )

                if hasattr(settings, "DOCUMENT_PASSWORD_REQUIRED_TEMPLATE"):
                    warn(
                        "The `DOCUMENT_PASSWORD_REQUIRED_TEMPLATE` setting is deprecated - use `WAGTAILDOCS_PASSWORD_REQUIRED_TEMPLATE` instead.",
                        category=RemovedInWagtail70Warning,
                    )

                    password_required_template = getattr(
                        settings,
                        "DOCUMENT_PASSWORD_REQUIRED_TEMPLATE",
                        password_required_template,
                    )

                context = {"form": form, "action_url": action_url}

                response = TemplateResponse(request, password_required_template, context)
                add_never_cache_headers(response)
                return response

            elif restriction.restriction_type in [
                BaseViewRestriction.LOGIN,
                BaseViewRestriction.GROUPS,
            ]:
                return require_wagtail_login(next=request.get_full_path())
```

**Comment by RealOrangeOne** [comment]
This sounds like an issue to me, and something Wagtail should do better.

I think your proposed solution makes sense too. Would you be interesting in opening it as a PR?

**Comment by krystianmagdziarz** [comment]
@RealOrangeOne I have just created a PR.

**Comment by thibaudcolas** [comment]
Assigning to @cnk to take a look. Can you also consider #1111 and whether we might be able to work on that at the same time?
