### ISSUE TITLE
Documentation - Update page titles to align better to writing style guide

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#12466]
Our writing style guide advises we should align with the Google developer documentation style guide. However, some page titles are still using an inconsistent style.

* https://docs.wagtail.org/en/latest/contributing/documentation_guidelines.html#writing-style-guide
* https://developers.google.com/style/headings

### Pertinent section of the Wagtail docs

There are a few pages that have inconsistent main titles that do not adhere to the usage of sentence case.

> Use sentence case for headings and titles.

These are minor changes but help us present a consistent tone in our documentation (at least in the TOC - Table of Contents).

### Details

These are the ones I have found, there could be others.

| URL | Change to make |
|-|-|
| https://docs.wagtail.org/en/latest/advanced_topics/images/feature_detection.html | `Feature detection` (lower case d) |
| https://docs.wagtail.org/en/latest/advanced_topics/api/v2/configuration.html | `Wagtail API v2 configuration guide` (lower case c & g) |
| https://docs.wagtail.org/en/latest/advanced_topics/api/v2/usage.html | `Wagtail API v2 usage guide` (lower case u & g) |

We do have the page [Managing the Reference Index](https://docs.wagtail.org/en/latest/advanced_topics/reference_index.html), we either need to change the title to be lower case 'reference index' or update the content to consistently use the proper noun 'Reference Index'.

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by Lipikacodes264** [comment]
@lb-  Can I work on this issue? I fyes, please assign this to me

**Comment by lb-** [comment]
@Lipikacodes264 please have a read of our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html) or  https://docs.wagtail.org/en/latest/contributing/first_contribution_guide.html#do-i-need-to-ask-for-permission-to-work-on-an-issue we do not assign issues outside of the core team.

You or anyone are free to pick up an issue.
