### ISSUE TITLE
Configure Read The Docs to build all formats

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#12484]
### Issue Summary

The Wagtail documentation for version 4.0.4 provides multiple downloadable formats (EPUB, HTML, and PDF), but these formats are unavailable for version 4.1.9 and later. This change appears to coincide with a ReadTheDocs (RTD) change, specifically around the time RTD transitioned to the .readthedocs.yaml configuration (v2). The default configuration setting for downloadable formats is an empty list ([]), which likely led to Wagtail's offline docs no longer being built when the migration to the v2 configuration occurred.

Restoring downloadable formats would improve accessibility for users who prefer offline documentation. Django has implemented a similar change to enable _all formats_, as seen in their [pull request](https://github.com/django/django/pull/15101).

### Steps to Reproduce

1. Go to the Wagtail documentation for version 4.0.4: https://docs.wagtail.org/en/v4.0.4/.
2. Observe that the options to download EPUB, HTML, and PDF formats are available.
3. Go to the documentation for version 4.1.9 (or later): https://docs.wagtail.org/en/v4.1.9/.
4. Notice that the options for downloadable formats are missing.

This is considered a bug because users who rely on offline documentation formats expect consistency across Wagtail versions. Restoring these formats would provide continuity and accessibility.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: N/A

### Technical details

-   Python version: N/A
-   Django version: N/A
-   Wagtail version: 4.0.4
-   Browser version: N/A

### Working on this

Any contributor can help with this issue by updating the .readthedocs.yaml configuration file to enable all documentation formats, using Django's implementation as a reference. Additionally, please verify that all formats still build correctly:

```
cd docs
make html
make epub
make pdf
```

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by lb-** [comment]
Can confirm this issue exists. Thanks for raising @allcaps 

| Before | Current|
|-|-|
| ![Image](https://github.com/user-attachments/assets/4773ffc3-6d57-48ff-853f-c550208cddf0) | ![Image](https://github.com/user-attachments/assets/c4e7e543-55f5-45e4-86ac-562d0c3b45a9) |

**Comment by lb-** [comment]
Ok. So the PR didn't seem to work. 

Looks like RTD is now failing. I'm yet to dig into the logs fully, it failed on the EPUB generation. 

https://app.readthedocs.org/projects/wagtail/builds/26114790/

>  **Unknown problem**
>
> We encountered a problem with a command while building your project. To resolve this error, double check your project configuration and installed dependencies are correct and have not changed recently.

**Comment by lb-** [comment]
@joelwilliam2005 if you're up for it, maybe let's try to suppress the warnings for unknown file mime types in EPUB. 

See

- https://stackoverflow.com/questions/77882704/warning-unknown-mimetype-for-pdf-filetype-on-sphynx-read-the-docs
- https://github.com/IQSS/dataverse/pull/3542/files

**Comment by allcaps** [comment]
See the description. Locally, this doesn't work too, we need to make sure it does.

cd docs
make html
make epub
make pdf

**Comment by allcaps** [comment]
```
epub_exclude_files = ['_static/favicon.ico', "_static/wagtail_colors_tables.txt", "_static/wagtail_icons_table.txt"]
```

**Comment by lb-** [comment]
https://github.com/wagtail/wagtail/pull/12507 has fixed the build issues.

Sage has a new PR up with some further refinements https://github.com/wagtail/wagtail/pull/12507
