### ISSUE TITLE
🎛️ Add unit tests for Stimulus `DrilldownController`

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#12511]
### Is your proposal related to a problem?

All our Stimulus controllers have over 60% unit test coverage except the `DrilldownController` which currently does not have a single unit test.

### Describe the solution you'd like

1. Add a unit test file for the `DrilldownController` and set up a basic suite of unit tests.
2. Add a Storybook file for the `DrilldownController` so it can easily be demoed outside of Wagtail admin.
3. Add an `@example` to the JSDoc, see other controllers for how this is done, it's incredibly helpful to have a quick reference example at the top of the JS file.
4. Update the other controller imports in the file as `type` imports as they are not used for any actual code (example below)

```js
import { Controller } from '@hotwired/stimulus';

import type { ActionController } from './ActionController';
import type { DropdownController } from './DropdownController';


/**
 * Drilldown menu interaction combined with URL-driven
 * state management for listing filters.
 */
```

### Describe alternatives you've considered

* N/A - we should be fixing this.

### Additional context

**Original PRS**

* https://github.com/wagtail/wagtail/pull/11559
* https://github.com/wagtail/wagtail/pull/11516

**Other context**

* See `client/src/controllers/RevealController.test.js` for a good example of a full set of unit tests and feel free to copy the `setup` and `errors` collection functions.
* Read through the other unit test files in the `src/controllers` folder for examples of unit tests.

### Working on this

* Anyone can contribute to this, it's a good early issue for someone who has a basic understanding (or can learn) of Jest/Stimulus.
* View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by Srishti-j18** [comment]
Hi, I am new to writing unit tests and need to learn Jest/Stimulus first. Can I work on this issue?

**Comment by Sumitsh28** [comment]
I will also make an attempt

**Comment by Srishti-j18** [comment]
Hello, I've made a draft PR, as I've only added one basic test (when the toggle is clicked) in the test file so far. I wanna ask for suggestions on what other kinds of tests would be useful to include. This is my first time writing unit tests, so I'm still getting familiar with what to cover.

**Comment by lb-** [comment]
Thanks @Srishti-j18 - I've done a basic pass over the code in the PR and have added comments there. 

A few general tips though. 

1. Run `npm run format` or ensure your editor is set up to run prettier formatting on save, it helps to avoid any nitpicky formatting issues. 
2. Run `npm run lint` to check for any misc linting issues that could cause issues. 
3. Run `npm run test:unit:coverage` - review the folder called `.coverage`, inside this folder should be a build folder with an `index.html` file. Viewing this file in your browser can let you see a line by line coverage of what the unit tests cover for every file. It's a great way to get a sense of what code is not run through the tests you have written. It's not perfect but it's a good sense check. 

What you want to consider for testing. 

1. Avoid calling methods directly on your controller instance, instead set up your html with the appropriate Stimulus actions. 
2. Test a scenario of open/close
3. Test a scenario where delayed close is used, checking timings 
4. Test a scenario where the Outlets are connected/disconnected 
5. Test the outside click (click away) behaviour works. 
6. Test the updating of counts. 

As noted in other comments, your html for storybook and unit tests will need to also include other controllers that are used as outlets. You'll also need to register these other controllers within the test and storybook files. 

When writing tests, like you're already doing, start small. Get the tesf passing, save a commit and then move on to a more complex case, and repeat.

**Comment by Srishti-j18** [comment]
Thank you for your valuable suggestions and guidance. I’ll take some time to review and analyze each point carefully and follow up with the necessary changes soon.
