### ISSUE TITLE
Eliminate need to subclass AbstractRendition or add signal receivers when subclassing AbstractImage

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#1254]
(I've no understanding of the ramifications of this request, I'm just experiencing implementation work which I feel is unnecessary).

Could `WAGTAILIMAGES_IMAGE_MODEL` be reused more to achieve this?

See: https://github.com/torchbox/wagtail/issues/1253

**Comment by thibaudcolas** [comment]
No one has commented on this in 9 years so I’ll close this now. If anyone feels this is important please re-open with our current feature request template so the request is clearer.
