### ISSUE TITLE
get_admin_default_ordering documentation

### ISSUE THREAD

**Issue by bmihelac** [wagtail/wagtail#12558]
The get_admin_default_ordering method documentation lists available sort orders, but in practice, anything valid for `PageQuerySet.order_by` can be used.

### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/stable/reference/pages/model_reference.html#wagtail.models.Page.get_admin_default_ordering

### Details

I have tried  sorting with  other Page model fields, such as `-first_published_at` , using `F` expressions and even fields from specific page class.

ie:

```python
    def get_admin_default_ordering(self):
        return ["-first_published_at"]
        # return [F("first_published_at").desc(nulls_last=True)]
        # return ["-blogentrypage__publish_date"]
```

I propose removing the phrase  "The following sort orders are available:" from the documentation.
Perhaps adding something like, "The result of `get_admin_default_ordering` is passed to `PageQuerySet.order_by`."

**Comment by unyimeudemy** [comment]
@bmihelac  I would love to work on this

**Comment by bmihelac** [comment]
Hey @unyimeudemy - great to know. Once someone from the Wagtail team confirms it, I think it would be great to not only update the documentation but also add some tests to prove it works.

**Comment by gasman** [comment]
Hi @bmihelac - thanks for the suggestion.
I don't think this should be a documented feature until we have the ability to customise the columns (#11931), as it breaks the consistency of the user interface - a non-standard ordering can't be represented in the state of the arrows in the column headers, and if the user reorders the listing by clicking on them, there's no way for them to return to the original ordering.

**Comment by bmihelac** [comment]
@gasman Thanks for the clarification; this makes sense.
