### ISSUE TITLE
🎛️ Create a new `ZoneController` to remove reliance on jQuery for toggling classes based on DOM events

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#12563]
### Is your proposal related to a problem?

Currently we use jQuery for common behaviour such as 'add this class when hovered' or 'remove this class when event fires', these are common use cases that would be great candidates for our Stimulus migration.

As a start, we should replace this specific jQuery usage with a new Stimulus controller.

https://github.com/wagtail/wagtail/blob/246f3c7eb542be2081556bf5334bc22256776bf4/client/src/entrypoints/admin/core.js#L62-L71

### Describe the solution you'd like

Introduce a new Stimulus controller (calling this `ZoneController` for now, better names can be suggested), that allows us to use events to add/remove classes declaratively within HTML.

We could remove the above referenced code in `core.js` and then update the HTML in [`wagtail/documents/templates/wagtaildocs/multiple/add.html`](https://github.com/wagtail/wagtail/blob/main/wagtail/images/templates/wagtaildocs/multiple/add.html) & [`wagtail/images/templates/wagtailimages/multiple/add.html`](https://github.com/wagtail/wagtail/blob/main/wagtail/images/templates/wagtailimages/multiple/add.html).

> This is used in the multiple upload views for both images & documents.
![Image](https://github.com/user-attachments/assets/e3168e75-47cc-4918-a4f6-eca513150738)

Finally, we could probably also remove the need for the `preventDefault` calls in both JS variations. This can be done on the controller instead.

https://github.com/wagtail/wagtail/blob/246f3c7eb542be2081556bf5334bc22256776bf4/wagtail/documents/static_src/wagtaildocs/js/add-multiple.js#L2-L5

e.g. 

```html
{% block main_content %}
    <div class="drop-zone w-mt-8" data-controller="w-zone" data-w-zone-active-class="hovered" data-action="dragover->w-zone#activate:prevent dragleave->w-zone#deactivate dragend->w-zone#deactivate drop->w-zone#deactivate:prevent">
```

#### Example controller

Below is a starting controller implementation (not tested) that shows example usage.

```ts
import { Controller } from '@hotwired/stimulus';

/**
 * Adds the ability for a zone (the controlled element) to be activated
 * or deactivated, allowing for dynamic classes triggered by events.
 *
 * @example - add .hovered when dragging over the element
 * ```html
 * <div data-controller="w-zone" data-w-zone-active-class="hovered" data-action="dragover->w-zone#activate dragleave->w-zone#deactivate dragend->w-zone#deactivate drop->w-zone#deactivate">
 *   ... drop zone
 * </div>
 * ```
 *
 * @example - add .visible when the DOM is ready for interaction, removing .hidden
 * ```html
 * <div class="hidden" data-controller="w-zone" data-w-zone-inactive-class="hidden" data-w-zone-active-class="visible" data-action="load@window->w-zone#activate">
 *   ... shows as visible when ready to interact with
 * </div>
 * ```
 */
export class ActionController extends Controller<HTMLElement> {
  static classes = ['active', 'inactive'];

  declare activeClasses: string[];
  declare inactiveClasses: string[];

  connect() {
    this.dispatch('ready', { cancelable: false }); // note: This is useful as a common pattern, allows the controller to change itself when connected
  }

  activate() {
    this.element.classList.removethis.activeClasses);
    this.element.classList.add(...this.inactiveClasses);
  }

  deactivate() {
    this.element.classList.remove(...this.inactiveClasses);
    this.element.classList.add(...this.activeClasses);
  }
}
```

### Describe alternatives you've considered

* For this specific jQuery, we could just 'move' it around, as per https://github.com/wagtail/wagtail/pull/12497 - but this felt like a bad approach as we eventually do want to remove jQuery.

### Additional context

* This is part of the ongoing Stimulus migration as per https://github.com/wagtail/rfcs/pull/78
* See the `client/src/controllers/` for examples of unit tests and other usage.
* This could be further leveraged in a few places (e.g. `image-url-generator`) and also potentially be enhanced to support more than just two states (active/inactive).

### Working on this

Ensure that the PR includes a full unit test suite, adoption in the HTML/removal of referenced jQuery in `core.js` and a Storybook story.

* Anyone can contribute to this, please read the Stimulus docs in full if you have not already done so  https://stimulus.hotwired.dev/
* Please include the removal of the `preventDefault` in `wagtail/documents/static_src/wagtaildocs/js/add-multiple.js` & `wagtail/images/static_src/wagtailimages/js/add-multiple.js` also
* Ensure all behaviour across images/docs is correctly manually tested.
* Please review our contributing guidelines specifically for Stimulus https://docs.wagtail.org/en/stable/contributing/ui_guidelines.html#stimulus
* View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by ayaan-qadri** [comment]
@lb- Instead of creating a ZoneController, what if we develop a generic controller that can handle any event (in this case dragover, dragleave dragend, drop) and dynamically classes to toggle (add/remove)? 
This would allow us to reuse the same controller in the future whenever similar functionality is needed.

**Comment by lb-** [comment]
@ayaan-qadri that's what I have proposed, Stimulus actions are already generic to any events. 

But if you want to suggest a different name, go for it.

**Comment by ayaan-qadri** [comment]
Oh My bad @lb-, I'm thinking to name it 'toggleClassController (w-toggle)' and its method addClass() and rmClass(), Is it fine to go with these names?

**Comment by lb-** [comment]
@ayaan-qadri I think that may get confused with toggle (as in the radio switch UI component), in addition, I expect that long term this may do more than toggle between two states, possibly ad-hoc states could be allowed.

Finally, this may not just do classes, long term we may want to consider setting attributes (`hidden` for example).

**Comment by ayaan-qadri** [comment]
Got it then it would be better to keep the name as you mentioned.
