### ISSUE TITLE
ChooserViewSet with custom ChooseView paginated results only default columns

### ISSUE THREAD

**Issue by bruecksen** [wagtail/wagtail#12632]
### Issue Summary
I have a `ChooserViewSet` for a model with a custom `ChooseView` where i override the column property. If the modal is opened  and the initial results are shown, all columns are correctly displayed. If i have click to the next page, the results only show the default column and not the added one.

```
class ProductGroupChooseView(ChooseView):
    @property
    def columns(self):  # type: ignore
        return super().columns +  [
            Column("product_count", label="Produkte", accessor="product_count"),
        ]

class ProductGroupChooserViewSet(ChooserViewSet):
    model = ProductGroup
    icon = "clone"
    per_page = 2
    choose_view_class = ProductGroupChooseView
```

### Steps to Reproduce
1. Add ChooserViewSet for a model
2. Add custom ChooseView for the ChooserViewSet
3. Add columns property and add an additional column
4. Add enought entries in the model so that paginated results are shown (or set per_page to a small number)
5. Go to the Wagtail admin and use the model chooser modal
6. Click to the next page

### Technical details

-   Python version: 3.11
-   Django version: 4.2
-   Wagtail version: 6.3.1

**Comment by gasman** [comment]
Hi @bruecksen,
You need to override `choose_results_view_class` too - this view renders just the results portion of the template and is used when navigating, searching or filtering within the chooser. This should be a subclass of `wagtail.admin.views.generic.chooser.ChooseResultsView` and can be customised in exactly the same way as `ChooseView` (so it often makes sense to put your method overrides into a mixin class that's used on both view classes).
