### ISSUE TITLE
Search results not choosable in AdminPageChooser

### ISSUE THREAD

**Issue by ralnss** [wagtail/wagtail#12640]
### Steps to Reproduce

1. Checkout the bakery demo (tested: Commit d026264)
2. Edit bakerydemo/blog/models.py in the following way: 

```
from wagtail.admin.widgets import AdminPageChooser
from bakerydemo.base.models import StandardPage, GalleryPage
```

in the class `BlogPage` add:

```
    content_panels = Page.content_panels + [
        MultipleChooserPanel(
            "blog_page_relationship",
            chooser_field_name="ref_page",
            heading="LINKS",
            label="LINKS",
        ),
        ...
```

add the class:
```
class BlogPageRelationship(Orderable, models.Model):
    page = ParentalKey(
        "BlogPage", related_name="blog_page_relationship", on_delete=models.CASCADE
    )
    ref_page = models.ForeignKey(
        Page, related_name="page_blog_relationship", on_delete=models.CASCADE
    )
    panels = [
        FieldPanel("ref_page", widget=AdminPageChooser([StandardPage, GalleryPage]))
    ]

```

4.  Open the admin interface, navigate to a BlogPage, open the AdminPageChooser via add "LINK" in the MultiplaChooserPanel. You see the selectable pages with checkboxes.
![Image](https://github.com/user-attachments/assets/81ded052-35d5-49f7-ad34-3be3b6e503bf)

5. Type something in the search bar, e.g. "Gallery".
**Now you see the search result, but the check boxes are not there any more and it's not possible to select pages from the search results.**
![Image](https://github.com/user-attachments/assets/902964ed-1f08-41bb-86ed-217c2f7917a4)

### Technical details

-   Python version: 3.12.7
-   Django version: 5.1
-   Wagtail version: 6.3
-   Browser version: Firefox 133.0

**Comment by gasman** [comment]
Thanks for the report @ralnss! I think this is the same issue as #11955 - the URL flag to say that multiple selection is active (and therefore we should show the checkboxes) is not being passed on when you load a new set of results (by either navigating or searching within the chooser).

**Comment by ralnss** [comment]
Thanks for linking @gasman, I didn't notice #11955.
