### ISSUE TITLE
Enhance capabilities for `WAGTAIL_GRAVATAR_PROVIDER_URL` URL to support merging of URL params

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#12659]
### Is your proposal related to a problem?

Currently, there is no simple way to [`WAGTAIL_GRAVATAR_PROVIDER_URL`](https://docs.wagtail.org/en/stable/reference/settings.html#wagtail-gravatar-provider-url) to support being given URL params.

For example, setting the following;

```py
WAGTAIL_GRAVATAR_PROVIDER_URL = '//www.gravatar.com/avatar?d=robohash'
```

Will result in the request being made to 

`http://www.gravatar.com/avatar?d=robohash/<the-hash>?s=50&d=mm`
But this is not a valid Gravatar URL, it will not correctly hq dle the hash, it should be:
`http://www.gravatar.com/avatar/<the-hash>?s=50&d=mm&d=robohash`

If there are valid Gravatar email addresses, these would never show. 

![Image](https://github.com/user-attachments/assets/da5b435e-b95a-464d-b9b0-85e1c3e0462c)

### Describe the solution you'd like

The ideal solution would be to support smarter merging of these params with the existing params set by `get_gravatar_url`, while also making this function a bit more versatile.

https://github.com/wagtail/wagtail/blob/c2676af857a41440e05e03038d85a540dcca3ce2/wagtail/users/utils.py#L28-L48

This could be updated to something like this rough idea, not sure if this will work but might be a good starting point.

1. Rework where the default/size are declared to closer to where we need them.
2. Parse the URL provided, allowing us to pull out and merge the query string, then re-build the URL while merging params allowing the params on the setting URL to override this
3. Still strip the last slash to support existing compatibility
4. Update the default to be `mp` as per the Gravatar docs, add docstring for reference to these docs
5. Add the reference to the settings documentation page https://docs.wagtail.org/en/stable/reference/settings.html#wagtail-gravatar-provider-url (using the appropriate MyST syntax to include docstrings OR just put the example within that settings section).

```py
from urllib.parse import parse_qs, urlparse
# ...

def get_gravatar_url(email, size=50, default_params={"d": "mm"}):
    """
    See https://gravatar.com/site/implement/images/ for Gravatar image options
    ...put an example here with proper escaping
    ...reference this in the settings docs.
    """

    gravatar_provider_url = getattr(
        settings, "WAGTAIL_GRAVATAR_PROVIDER_URL", "//www.gravatar.com/avatar"
    )

    if (not email) or (gravatar_provider_url is None):
        return None

    # requested at retina size by default and scaled down at point of use with css
    size = int(size) * 2
    url = urlparse(gravatar_provider_url)
    email_bytes = email.lower().encode("utf-8")
    hash = safe_md5(email_bytes, usedforsecurity=False).hexdigest()
    gravatar_url = "{base_url}/{hash}?{params}".format(
        gravatar_provider_url="".join(url[:3]).rstrip("/"),
        hash=hash,
        params={"z": size, **default_params, **parse_qs(url.query)},
    )

    return gravatar_url
```

### Describe alternatives you've considered

- At a minimum, we should support stripping params from the provided URL so that adding params does not break things.
- Next best solution is preserving them (pulling them out, moving them back into the URL at the end.
- However, as above, the ideal solution would be great to be able to support and be a more intuitive developer experience

### Additional context

- Two PRs have attempted this, please look at them and also look at the comments/reviews, please only pick up this issue if you are willing to work through feedback, add unit tests and add documentation.
- #11800 & #11077

### Working on this

- Anyone can contribute to this, it may make sense to do this other simpler issue first though - https://github.com/wagtail/wagtail/issues/12658
- The PR cannot be reviewed without unit tests and documentation first, if you are not sure on the approach, please add comments to this issue for discussion.
- View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by lb-** [comment]
See also, some related requests to enhance how the avatar can be used for customisations - https://github.com/wagtail/wagtail/issues/12661

As an aside (probably needs a different issue), I wonder if we should rename `WAGTAIL_GRAVATAR_PROVIDER_URL` to `WAGTAIL_EXTERNAL_AVATAR_PROVIDER_URL`.

Also, I have updated the code example.

**Comment by joelwilliam2005** [comment]
I edited `wagtail/docs/reference/settings.md ` as you mentioned.

`WAGTAIL_GRAVATAR_PROVIDER_URL = '//www.gravatar.com/avatar'` --> `WAGTAIL_GRAVATAR_PROVIDER_URL = '//www.gravatar.com/avatar?d=robohash'`

Changes I saw:

Before:

![Image](https://github.com/user-attachments/assets/34c1e470-a059-4e62-9a06-9381ff22a0f3)

After:

![Image](https://github.com/user-attachments/assets/bbe3bf49-8baa-43eb-a442-534c126ebef0)

Is this the issue you faced and is reproduced correctly, as the whole UI seems to broken this way? 
Let me know so that I can work on it further.

**Comment by lb-** [comment]
@joelwilliam2005 I did not see the UI break like that, I only saw that the Gravatar URL is malformed. While it still worked it would not work correctly for valid email addresses. Due to the hash being appended after the URL param `?`

**Comment by ayaan-qadri** [comment]
Current code:

![Image](https://github.com/user-attachments/assets/910a4fef-98d7-4800-a929-e793847fd4ae)

Changing to `//www.gravatar.com/avatar?d=robohash` in default of `getattr`

![Image](https://github.com/user-attachments/assets/b5bac3a2-d690-403b-a26a-92b003d28ca7)

I do not see `301` as per your Screenshot but what i noticed that provider query parameter is coming first and then default paramter should come as you mentioned:

> http://www.gravatar.com/avatar?d=robohash/<the-hash>?s=50&d=mm
But this is not a valid Gravatar URL, it will not correctly hq dle the hash, it should be:
http://www.gravatar.com/avatar/<the-hash>?s=50&d=mm&d=robohash

Manually i did:
`https://www.gravatar.com/avatar?d=robohash/3ec564d1f50ebaa304b1393eb7241f76?s=50&d=mm`

to

`https://www.gravatar.com/avatar?d=mm/3ec564d1f50ebaa304b1393eb7241f76?s=50&d=robohash`

this is what it gives (binding with img tag):

<img src="https://www.gravatar.com/avatar?d=mm/3ec564d1f50ebaa304b1393eb7241f76?s=50&d=robohash" />

this is not exact URL pattern what you mentioned but still working, or it is wrong avatar?

But changing to pattern (`avatar/<the-hash>?s=50&d=mm&d=robohash
`) you mentioned gives another avatar

`https://www.gravatar.com/avatar/3ec564d1f50ebaa304b1393eb7241f76?s=50&d=mm&d=robohash` :

<img src="https://www.gravatar.com/avatar/3ec564d1f50ebaa304b1393eb7241f76?s=50&d=mm&d=robohash"/>

I'm not familiar with Gravatar APIs but i assuming that we need default parameter first and rest provider url query parameters if this is what we need i almost understood the issue (will have to look past PRs precisely)  and can start working on it @lb- .

**Comment by lb-** [comment]
If you have a look at the current code, it makes the assumption that a URL without query string params will be provided. 

This is ok, but as you've seen through testing, it produces a malformed URL if the setting is set to anything with query string params. It just appends the hash and additional query string params at the end. 

The ordering of the params doesn't usually matter, it's the position of the hash (path part, not the URL fragment) that the Wagtail function appends that is the issue. 

- `example.com/path/code-abc/?a=47` (what we should get)
Vs
- `example.com/path/?a=47/code-abc` (what's being produced)

This is a simplified example but shoes that the hash (aka `code-abc`) accidentally is becoming part of the `a` param's value. When it should be part of the URL path. 

Here's a good guide on all the parts of a URL. https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL

Hopefully that makes it a bit clearer, let me know if that makes sense.

**Comment by lb-** [comment]
Another way to understand the issue is that when the hash is part of the param value, it basically gets ignored. 

There three are malformed and will produce the exact same image. 

1. https://www.gravatar.com/avatar?d=mm/3ec564?s=50&d=robohash
2. https://www.gravatar.com/avatar?d=mm/323abc&s=50&d=robohash
3. https://www.gravatar.com/avatar?d=mm/564auye?s=50&d=robohash


Whereas these three are correctly formed and will produce different avatars based on the hash as it should be part of the URL **path** and not in the **params**. 


1. https://www.gravatar.com/avatar/3ec564?d=mm&s=50&d=robohash
2. https://www.gravatar.com/avatar/323abc?d=mm&s=50&d=robohash
3. https://www.gravatar.com/avatar/564auye?d=mm&s=50&d=robohash

**Comment by ayaan-qadri** [comment]
Thanks for the explanation @lb-,make sense to me one last thing that same key-value pair will not override by last one so do we still need that ?? isn't it redundent ?

e.g. : 

?d=mm&s=50&d=robohash
- `robohash` wins here

?d=robohash&s=50&d=mm
- `mm`  wins here

**Comment by lb-** [comment]
If you see the code example I have suggested, it will actually do the merging of the params as dicts. This should mean that a param provided in the setting would override the default params. 

As for what websites do when there are two params of the same key, that's potentially complicated. Depending on the code they use, they will sometimes just break, or ignore one (usually the last) or treat the value as an array.

Gravatar appears to use the last param, but that can't be assumed to be reliable. Their documentation does not say they will do this so it could just be the web framework they use that has this behaviour.

I think we should try to end up with a solution that at a minimum strips any params from the settings but I think the best option is to parse them and merge them with the params our Wagtail admin code wants to use. Then rebuild the new URL with the merged params, not having any duplicates.

Note that it gets even more nuanced when you read that Gravatar supports a long and short form of each param key. E.g. `size` and `s` both work, that's just a Gravatar specific thing though. https://docs.gravatar.com/api/avatars/images/

I wouldn't worry about our code needing to be smart about the short/long params, but worth understanding.

**Comment by ayaan-qadri** [comment]
@lb- understood and almost achieved what we wanted

```python
merged_params = {
        **default_params,
        **{key: value[0] for key, value in existing_params.items()},
    }
```
- gravatar_provider_url's parameters get precedence here 

```python
    gravatar_url = f"//{parsed_url.netloc}{parsed_url.path}/{hash}?{urlencode(merged_params)}"
```
- this makes cleaner and i choose 'f' string formatting here because it is faster string concatenation in python as proof i once benchmark for string concatenation when checking for on a issue copy and pasting benchmark result from comment to here:

replace path: 0.49085860000923276
format with assignment: 0.7151281999831554
format with index: 0.3822980000113603
_**fstring path: 0.15623890000279061**_
concatenation path: 0.24857970001176
join path: 0.19559379998827353

code:  https://pastebin.com/XRPJpHRi

final result:

![Image](https://github.com/user-attachments/assets/fbdcda8c-53c3-4327-a762-3d6f71a90cf9)

**Comment by lb-** [comment]
Looking good, I'd suggest you also have a think about the minds of unit test scenarios. 

- Setting with params that don't overlap 
- Setting with params that do overlap 
- Setting with Url that has a trailing slash / no slash and ending `?` but no params. 
- etc.

**Comment by ayaan-qadri** [comment]
Sure, Thank you !

**Comment by joelwilliam2005** [comment]
@ayaan-qadri Wagtail doesn't assign issues to contributors, so anyone can work on it. 
I think the ultimate goal is to solve the issue here, so your contribution towards it is also more than welcomed. 
Also looks like you've come up with a solution, you can open a new PR with it. I'll try to assist with the knowledge I have been getting while working on this.

**Comment by ayaan-qadri** [comment]
@lb- raised PR for this
