### ISSUE TITLE
Default URL param value for Gravatar URL have been deprecated (`mm` -> `mp`)

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#12658]
### Issue Summary

We currently pass in `mm` to the `d` (default) param, this is used to determine what avatar will show if there's no matching avatar. However, the latest documentation advises that this should be `mp` (mystery person) instead.

https://github.com/wagtail/wagtail/blob/c2676af857a41440e05e03038d85a540dcca3ce2/wagtail/users/utils.py#L28-L29

https://github.com/wagtail/wagtail/blob/c2676af857a41440e05e03038d85a540dcca3ce2/wagtail/users/utils.py#L45

https://docs.gravatar.com/api/avatars/images/#default-image

### Describe the solution you'd like

Update the param value from `mm` to `mp` and ensure any unit tests are updated.

This way, if the support for this legacy value gets dropped, it will not be a breaking change for Wagtail users.

### Describe alternatives you've considered

It might be nice to have a better approach to this by allowing the param to be passed into the function / overridden somehow. Best to discuss that in a different issue though - see https://github.com/wagtail/wagtail/issues/12659

### Additional context

Two PRs have attempted this (and other changes), see the feedback and the PRs for reference.

- #11077
- #11800

### Working on this

- Anyone can contribute to this, be sure you understand how to reproduce the avatar scenario.
- It might be good to tackle this small change before tackling the other related issues.
- View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by hsd2514** [comment]
hey if this issue is open i cant start working on it

**Comment by joelwilliam2005** [comment]
@hsd2514  If you're interested to work on it, go for it.
Wagtail team doesn't assign issues to contributors, so you can just start working on it and open a PR with your fix.
If you start working on it just leave a comment, to let others know this issue is being worked on.

**Comment by hsd2514** [comment]
just made a pr can u check it

**Comment by lb-** [comment]
> just made a pr can u check it

Thanks @hsd2514 - please see that the PR is failing the CI. Most likely due to tests that are not updated.

Here's the contributing docs on how to run the tests locally - https://docs.wagtail.org/en/stable/contributing/developing.html#testing
