### ISSUE TITLE
django-taggit migration error

### ISSUE THREAD

**Issue by kesara** [wagtail/wagtail#12698]
### Issue Summary

Updating from version `5.2.7` to `6.3.1` resulted a `django-taggit` migration error.

### Steps to Reproduce

1. Web app was running on Wagtail `5.2.7` with `django-taggit==4.0.0`.
2. Updating to Wagtail `6.3.1` installs `django-taggit==6.1.0`
3. Run `python manage.py migrate`.

I have reported this on the upstream project as well: https://github.com/jazzband/django-taggit/issues/929

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: 3.12.8
-   Django version: 4.2.17
-   Wagtail version: 6.3.1
-   Browser version: n/a

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
Thanks for the report! Closing as this appears to be a django-taggit issue rather than Wagtail, and is being handled on that project.

**Comment by kesara** [comment]
@gasman, Yeah, Thanks.

If anyone come across this issue, see https://github.com/jazzband/django-taggit/issues/882#issuecomment-1909688346
