### ISSUE TITLE
Stop loading radio-full.svg for preview sizes

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#12708]
Spotted as part of [Wagtail 6.3 admin UI performance audit](https://github.com/wagtail/wagtail/discussions/12578). Our `radio-full.svg` background image is being loaded for the preview sizes radio buttons, despite the buttons not actually displaying the image.

This should be a simple CSS fix to avoid, further overriding the `::before` pseudo element so the background doesn’t load at all.

**Comment by laymonage** [comment]
This was already done in #12579.
