### ISSUE TITLE
Restrict globally documents and images to certain types

### ISSUE THREAD

**Issue by salvadormrf** [wagtail/wagtail#1285]
In some cases, we want to restrict globally documents and images to certain types.
Eg: "only pdf can be uploaded to documents"

A global settings could be helpful, example:
WAGTAIL_DOCS_ALLOWED_EXTENSIONS = ['pdf']
WAGTAIL_IMAGES_ALLOWED_EXTENSIONS = ['png', 'jpeg', 'jpg']

**Comment by davecranwell** [comment]
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/fields.py currently defines the allowed extensions and while `WAGTAILIMAGES_MAX_UPLOAD_SIZE` is a global setting, `ALLOWED_EXTENSIONS` isn't.

It looks like it would be pretty trivial to make it a setting, although the "humanised" versions in `SUPPORTED_FORMATS_TEXT` would be a bit tedious. The latter was created to cater for how GIF is known by its initials, whereas "WebP" is camel case. I doubt any user actually cares though and this could be removed.

**Comment by zerolab** [comment]
Not that we support global docs extensions via [`WAGTAILDOCS_EXTENSIONS]`(https://docs.wagtail.org/en/stable/reference/settings.html#wagtaildocs-extensions) via #6423

**Comment by benitaanawonah** [comment]
Please is this still an issue? i would like to work on it

**Comment by 4the4ryushin** [comment]
may i work on this?

**Comment by Ananjan-R** [comment]
If this issue is still open, I would like to work on it

**Comment by salty-ivy** [comment]
@zerolab  made the [PR](https://github.com/wagtail/wagtail/pull/9860) also added tests and Docs and additionaly one more issue i came across fixed along with this PR

**Comment by salty-ivy** [comment]
@laymonage it had few issues so I created a new which is perfectly working along with tests and docs 

Additionally it deals with one minor typo/issue which is not part of this one and it wasn't worth enough to open a ticket for it I would appreciate to have a look into it however 
It's a matter of consideration so no problem! thanks

**Comment by ArijeetBanerjee** [comment]
I want to work on this issue. kindly give me permission and access to work on this issue
