### ISSUE TITLE
Make gravatar optional

### ISSUE THREAD

**Issue by salvadormrf** [wagtail/wagtail#1286]
I have been recently trying to add CSP directives to wagtail admin interface.
We need to limit/control where the resources are coming from.

By security reasons, I don't want gravatar resources to be loaded on website.
Would be nice to make it optional with a global settings, instead of forcing me to override a lot of templates.

**Comment by apidictor** [comment]
:+1:

**Comment by davecranwell** [comment]
Ideally I'd like this to be done as part of https://github.com/torchbox/wagtail/issues/319 and https://github.com/torchbox/wagtail/issues/774 however neither of these are likely to be a priority, so in the meantime we may just add the setting and accept that some builds will have no avatars at all, which is obviously the developer's choice.

**Comment by SalahAdDin** [comment]
Yes!!! :+1:

**Comment by kidlj** [comment]
:+1:

**Comment by SalahAdDin** [comment]
What's about favicon branding? I can't see where i can put my custom favicon. :'(

**Comment by kidlj** [comment]
Here in China, gravatar service is blocked, so it always takes a long time to load  admin page.

I hope we can make gravatar optional.

**Comment by davecranwell** [comment]
I definitely want to make gravatar optional, but I'd also like to increase the display of people's avatars - it makes dull interfaces much more lively and interesting and of course also provides valuable information. However to use avatars more and gravatar less, we need #319.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by sedrubal** [comment]
:+1: :grey_exclamation:

**Comment by SalahAdDin** [comment]
What's about make an especial image type for users avatar?

**Comment by dahrens** [comment]
:+1:

**Comment by SalahAdDin** [comment]
:+1:
