### ISSUE TITLE
Wagtail allows truncated images to be uploaded (which crash whenever displayed)

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#1326]
Steps to reproduce:
1) Find a valid jpeg file
2) Truncate it a bit
3) Upload it to wagtail (should work if the headers are still intact)
4) Find a view that renders it (will crash with TruncatedImageException)

**Comment by salsotto** [comment]
I I had this problem also with the version 1.9.5

**Comment by Vorlif** [comment]
Images can be deleted via the Django Admin Interface. As workaround...

**Comment by thibaudcolas** [comment]
Closing in favour of #1354 which looks like the exact same issue (assuming we’d handle truncated images and other broken images in the same way)
