### ISSUE TITLE
Login admin after session end bug

### ISSUE THREAD

**Issue by emg36** [wagtail/wagtail#1359]
I left my project open overnight and when I tried to change page in the admin I guess my session had ended and it wanted me to login again. I got the following pop up on my page. But once I clicked on it, it opened a new tab with the correct login page.

![wagtail_-_editing_home_page__home_page](https://cloud.githubusercontent.com/assets/5077135/7899687/e70e417c-0781-11e5-96bc-a7c903962d53.png)

**Comment by kaedroho** [comment]
Thanks! I've noticed this one before too.

I guess we could tweak "is logged in check" to return a 403 error instead of redirecting for AJAX requests.

**Comment by timheap** [comment]
This also happens with the AJAX explorer menu.

**Comment by gasman** [comment]
Partially fixed by #3046 - AJAX requests now return a 403 error in this situation. The calling code now needs updating to recognise this and respond accordingly (possibly by opening a modal login box).

**Comment by thibaudcolas** [comment]
I believe this is now better covered by #5048. Closing.
