### ISSUE TITLE
Reference docs for internal models

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#1437]
- [x] Page (some methods missing)
- [x] Site
- [x] PageRevision
- [x] PageViewRestriction
- [x] GroupPagePermission
- [ ] Image
- [ ] Filter
- [ ] Rendition
- [ ] Document
- [ ] UserProfile
- [x] Embed
- [x] Redirect
- [x] Query
- [ ] QueryDailyHits
- [ ] SearchPromotion

**Comment by kaedroho** [comment]
Reference docs for Embed added in https://github.com/wagtail/wagtail/pull/2127

**Comment by thibaudcolas** [comment]
I see we’re about halfway through the list after 8.5 years. It seems to me like each of those remaining items could warrant its own ticket so it’s more actionable, so I’ll close this now.
