### ISSUE TITLE
Adding external links can insert url into field

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#1548]
There is an odd behaviour when adding external links in the rich text field. If you select a whole line and add an external link then the url gets inserted into content rather than wrapping around the piece of text you selected.

**Comment by tmsndrs** [comment]
![wagtail-external-linking 1](https://cloud.githubusercontent.com/assets/7290588/8852203/b4ede190-314b-11e5-8ade-1e4aba63a3c9.gif)

**Comment by thibaudcolas** [comment]
This issue isn't present in Draftail. Still there in Hallo though.
