### ISSUE TITLE
Previewing pages launches a tab/window which can't be refreshed

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#168]
Previewing using the drop-up at the bottom of the edit page, creates a new window/tab with the URL: http://mysite.com/admin/pages/preview_placeholder/

If you then make a change in the page you're previewing, this tab/window can't be refreshed to see the changes.

Presumably this pop-under method is to avoid pop-up blocks catching the preview window? Can we not make it a little more usable?

**Comment by ghostwords** [comment]
I can confirm that users tend to expect to be able to share previews. (I had to explain each time that they need to save a draft if they want a shareable link.) A preview feels like a regular page, but it isn't.
