### ISSUE TITLE
Field Permission in Admin

### ISSUE THREAD

**Issue by tiagofmc** [wagtail/wagtail#1680]
Right now, Wagtail provides Page permission. 
I want to add a field permission to a certain Page, but I can't. Basically this field ('owner') needs to be shown to the admin, but not to other users. The admin and the others users should edit that page fields, except for the 'owner' field. 
I tried to use a bunch of hooks, context processor and middleware and nothing worked. 

Is there any way to do this? If not, are you thinking about implementing field permissions to Wagtail?

**Comment by gasman** [comment]
Hi @tiagofmc - we haven't seen a need for this yet, but we would happily consider this as a contributed feature.

How do you see this working? Perhaps something like:

    MyPage.content_panels = [
        FieldPanel('title'),
        FieldPanel('owner', permission='myapp.change_page_owner'),
        ...
    ]

- where `myapp.change_page_owner` would be a permission defined in Django's usual permissions framework.

**Comment by tiagofmc** [comment]
Thanks for the quick reply @gasman 

The problem with Django default permission framework is that it also applies to the model, and not to a specific field, so I would have the same problem.
Also, I tried to use third-party Django apps that add the option to set permissions to certain fields, and they didn't work because they derived from Django Admin.

**Comment by shacker** [comment]
+1 from us here at CCA - actively looking for a way to provide certain fields that are editable only by superusers. At first I thought I would leave those fields out of content_panels and require use of Django admin, but unfortunately those fields don't even appear in Page instances viewed in Django admin.

**Comment by ChristophTrappe** [comment]
+1. Any update on this issue?

**Comment by loicteixeira** [comment]
There has been no work on such feature as far as I'm aware.

However, since 2.1, edit handlers' `bind_to_instance` method will receive the `request` object (see #4382) so you should be able to create a subclass of `FieldPanel` which will show/hide/readonly the field as needed.

**Comment by ChristophTrappe** [comment]
@loicteixeira Thanks for the hint. I'll give it a try.

**Comment by DzMkh** [comment]
@loicteixeira 
Thanks for the information.
Also I found the similar question on SO and I left a comment with implementation basing on your tip.
The [link](https://stackoverflow.com/a/53421701/9160338) =)

**Comment by dest81** [comment]
I know it's quite old topic but might be still relevant.
I couldn't find too much info about it except this issue and one stackoverflow page. For my needs I came up with this:
```
class BlogPage(Page):
    ...
    edit_permissions = [
        Permission(
            action="hide", # or show
            groups=["Editors"],
            fields=["slug", "seo_title", "tags"]
        )
    ]
    edit_handler = RestrictedTabbedInterface([
        ...
    ])
```

You can find full code here https://gist.github.com/dest81/8696ad77588098d5d213f001b1cc7fcb
It's not a final version and I am still working on it. 
It would cover many cases. Let me know what do you think and if it worse to be a part of wagtail core.
If yes I can improve it and send PR.

**Comment by kpsaurus** [comment]
Yes, it would've been a great feature as @gasman mentioned above. However, overriding the required_fields method also worked out for me. For example, I did something like: 

`class RestrictedFieldPanel(FieldPanel):
    def required_fields(self):
        if self.request and self.request.user.is_superuser:
            return super().required_fields()
        return []`

**Comment by gasman** [comment]
Completed in #8060
