### ISSUE TITLE
Configurable moderation workflow

### ISSUE THREAD

**Issue by kurtrwall** [wagtail/wagtail#1712]
Sometimes an organization wants to be able to share content without having to give members user accounts on the CMS because of man power, bureaucracy, etc. Should there be a mechanism that allows this sort of behavior? 

I'm thinking of having multiple sites that could provide two different versions of the content based on a "shared" status. 

I'm cooking up a PR that would support this though subclassing the Page model and making good use of Wagtail's Site class, but I thought I might get the community's thoughts on it.

**Comment by gasman** [comment]
Hi @kurtw - can you give some more details of the mechanism you're proposing, and how you expect it to be used? It sounds like you're suggesting having a secondary site with locked-down access (e.g. by IP block, or htaccess password) but I'm not quite sure.

**Comment by kurtw** [comment]
@gasman The first part is basically covered in the concept you proposed in [1283 (comment)](https://github.com/torchbox/wagtail/issues/1283#issuecomment-100470750). Imagine a scenario of having `www.website.com` and `content.website.com` where www is public facing and content is internal (only accessible via VPN or something), but they both exist on the production server so they can use the same database. In essence, they are just two versions of the same site.

What I'm suggesting is that there be some way of "replicating" the publishing workflow on a per site basis. One site would be used for sharing content among those with access without the need for an account and the other would be where the finalized content goes. 

I opened [a PR](https://github.com/torchbox/wagtail/pull/1713/files) that illustrates what I'm talking about. It works in combination with some [wagtail hooks](https://gist.github.com/kurtw/6ee8e27aa8e158c52e9a) that are in my app. Admittedly, there's some bugs in it and again it won't work without the hooks but it does the job okay. I'm not necessarily suggesting this be the way it's done but it's one way I guess.

**Comment by gasman** [comment]
@kurtw Thanks for the clarification! Looking at the PR, this feels like a very "heavy" change (in terms of additions to the admin UI, and the work involved in dealing with it during future Wagtail development) for something that's only useful to a minority of users.

This is really hinting at a much bigger feature, the idea of "configurable workflow". Currently Wagtail implements one simple kind of workflow, the "submit for moderation" button - and your PR implements a different workflow, designed for your own organisation's requirements (namely, the ability for users without Wagtail accounts to review pages). Undoubtedly other organisations will have different requirements - such as multiple levels of moderators, perhaps. It wouldn't be practical for Wagtail to implement each organisation's requirements on an individual basis - it would quickly become unmaintainable.

A better approach would be to create a general framework that allows organisations to build their own workflows. I believe other CMSes use the concept of a 'state machine' for this, where a page has any number of available statuses, and there is a configurable set of rules for changing from one status to another. (In Wagtail's case, these status changes could be represented as actions in the footer of the 'edit page' view.) This is probably something for Wagtail's far future, though - it's not something we've even considered up to now.

**Comment by tomdyson** [comment]
Paging @mitchellrj - is this (configurable workflow) the kind of thing your team has in mind?

**Comment by kurtw** [comment]
@gasman thanks a lot for the reply. We've gone with configuring our own django project instead of editing Wagtail. The idea of a configurable workflow is very interesting. In any organization, there's always a need for a custom workflow so I could see this being a huge feature for Wagtail users. 

I would like to see document management part of this future custom workflow. It's amazing how many well known organizations use archaic and arduous technologies for document management.

**Comment by Onuonga** [comment]
Hi folks, 
I would like to find out of this feature(Configurable moderation workflow) was actually worked on.
If so , please provide a link, if not, I would like to work on it.

**Comment by dwasyl** [comment]
Just stumbled across this, and it seems that [https://github.com/cfpb/wagtail-sharing](https://github.com/cfpb/wagtail-sharing) could be a pretty good start for this feature. Not quite as all encompassing as the original ask, but a step in the right direction.

**Comment by gasman** [comment]
Configurable workflow is part of the forthcoming 2.10 release, with the ability to have external users as reviewers being provided by the [wagtail-review](https://github.com/wagtail/wagtail-review) add-on package.
