### ISSUE TITLE
Required StreamField blocks don't indicate that they're required

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#1732]
The user has click "Publish" then get an error before they can see that the field was required. The labels could have a red asterisk next to them to indicate that they're required.

**Comment by riceyrice** [comment]
This might work: https://github.com/isotoma/wagtail/commit/33a33cf97617add14a7a2efef81203cb260ec0d8

**Comment by alexgleason** [comment]
Nice, thank you @riceyrice !

**Comment by riceyrice** [comment]
OK I've done a proper PR against a not-ancient branch now.

**Comment by gasman** [comment]
Fixed in #2663
