### ISSUE TITLE
Docs required for enabling embedly

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#1756]
The `WAGTAILEMBEDS_EMBEDLY_KEY` setting is only briefly mentioned in http://docs.wagtail.io/en/v1.0b1/howto/settings.html

Also requires `pip install embedly`

**Comment by kaedroho** [comment]
Documentation in https://github.com/wagtail/wagtail/pull/2127

**Comment by SalahAdDin** [comment]
:+1:
