### ISSUE TITLE
High density screen (retina) support

### ISSUE THREAD

**Issue by hacksaw6** [wagtail/wagtail#1825]
I think that it would be helpful to support high density images perhaps in the wagtail images tag so an image can appear crisp on HDPI devices such as phones and newer computers.

For example:
`{% image profile_image fill-200x200-c90-hdpi %}`

**Comment by davecranwell** [comment]
I created a responsive image tag for another project, the code for which is here (I've quickly copied this from another codebase and stripped out the stuff which is private, therefore this gist is untested, be warned): https://gist.github.com/davecranwell/baf42b089d71b94fd229

It's intended for use with picturefill (http://scottjehl.github.io/picturefill/) so supports 2x images through the `srcset` attribute. It doesn't currently support `picture`.

One significant problem with this tag is that it immediately generates all the various image sizes you define in your `srcset`, the instant the tag is run during template compilation. I believe this is problematic for sites hosting their images off-server e.g S3, where images renditions need to be compiled offline.

You may find this tag is suitable for your needs though.

**Comment by urlsangel** [comment]
Hey Dave - how goes?

I've just had a quick play with the gist above, but get the following error at line 45:

`'ResponsiveImageNode' object has no attribute 'image_var'`

Have you had this template tag working at all? Be great to have a srcset solution in Wagtail.

Cheers,

Russ.

**Comment by davecranwell** [comment]
Yeah I discovered this just this week in fact. If you check the gist again, I've updated it. basically ImageNode has been updated replacing `image_var` with `image_expr`.

**Comment by davecranwell** [comment]
I've also updated it so that the kwarg `srcset` can be returned as part of the image object, which makes it easier to use this tag via `{% responsiveimage as foo %}` with libs like Lazysizes, which requires `data-srcset` instead of `srcset`.

**Comment by urlsangel** [comment]
Cheers Dave - just gave it a play, but it's throwing a ValueError at line 43 - I'm using the tag with the format:

`{% responsiveimage page.conference_logo height-40 srcset="40h" %}`

Please don't worry if you're busy, I can revisit this later!

**Comment by gasman** [comment]
Covered by #285 and #3573
