### ISSUE TITLE
Provide better access to View Draft of pages

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#1836]
When editing a new page, yet to be published, it's not possible to view the Draft version of a page from within the page editor. The "Draft" button is in fact only present in the Explorer. You can "Preview" it from within the page editor, but as this isn't refreshable it isn't always useful.

Viewing the draft version should at least be a button added to the save success notification.

**Comment by vgpena** [comment]
+1 on this, I think I'll be adding https://github.com/cfpb/wagtail-sharing to provide this functionality, but would be lovely to have Previews available for logged-in users via a direct link.

**Comment by tomdyson** [comment]
Draft versions are available to logged-in users via a direct link. The URL format is 

/admin/pages/{{Page ID}}/view_draft/

and it's accessible from the explorer, for pages that have draft states (i.e. they have unpublished changes). Perhaps it should be more obvious?

![screenshot 2018-08-29 21 11 13](https://user-images.githubusercontent.com/15543/44812866-44c35780-abd0-11e8-92b2-1af42193fa12.png)

**Comment by vgpena** [comment]
Thanks @tomdyson! I juuust realized that the Draft link is readily available on the parent page -- I think editors are hitting Save Draft and then Preview right on the page they're editing.

![captura de pantalla 2018-08-29 a la s 2 22 21 p m](https://user-images.githubusercontent.com/1166226/44816418-17a68300-ab97-11e8-897a-d70014765bc3.png)

I think another link on the page that links out to the Draft, if there's Live + Draft available, would be really helpful here.

![captura de pantalla 2018-08-29 a la s 2 23 49 p m](https://user-images.githubusercontent.com/1166226/44816477-386ed880-ab97-11e8-8036-8b691415a5e6.png)

If this sounds like a good addition to the Edit page, I'm happy to implement that (I'll be doing it for this project, either way) and open a pull request.

Thanks!

**Comment by thibaudcolas** [comment]
Closing! Reading through the messages, I believe this is no longer relevant as of Wagtail 4.0 with the auto-refreshing live preview. Viewing the draft is just a matter of opening the preview panel.
