### ISSUE TITLE
Need an admin-accessible UI to regenerate image renditions, if quality is changed in settings

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#187]
Via the command line this can be achieved thus:

```
$ ./manage.py dbshell
=> delete from wagtailimages_rendition;
```

A button to do the same via the admin would be grand.

**Comment by dperetti** [comment]
Definitely needed as a management command.
Typical scenario : you backup your db and the original_images folder and don't need to backup renditions. 
But then, If you need to restore your website, you need to flush the cache.
We need [something like sorl thumbnail does](http://sorl-thumbnail.readthedocs.io/en/latest/management.html).

**Comment by robslotboom** [comment]
[remove_renditions.py.zip](https://github.com/wagtail/wagtail/files/3026607/remove_renditions.py.zip)

File with a command to remove the renditions and the rendered images.

In your project create:

```
management/
    __init__.py
    commands/
        __init__.py
        remove_renditions.py

```
then run:
python manage.py remove_renditions
