### ISSUE TITLE
Make rendering of EmbedBlock less opinionated

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#1872]
Currently, `EmbedBlock` calls `embed_to_frontend_html` (https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailembeds/blocks.py#L21). This adds a `<div>` with some inline styling around the embed which can lead to some really tricky to solve bugs.

I think we should remove this for streamfield blocks (but not rich text fields). Here's a rough plan for doing that:
- Define a `get_context` method on `EmbedBlock` outputting the`embed` variable into the template
- Move `ratio` calculation into the `Embed` model (so it can be used in the template)
- Allow the template to be configured using the `template` attribute
- Rename the old template (https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailembeds/templates/wagtailembeds/embed_frontend.html) to something that shows it is opinionated (eg `embed_responsive.html`)
- Provide a new, unopionated template and set it as the default

**Comment by gasman** [comment]
Related: #1495

I don't think we should bother with the deprecation period here. The current behaviour has caused confusion for lots of people, and I think the net benefit of fixing it immediately is greater than the hassle of existing users having to take specific steps to restore the old behaviour.

**Comment by kaedroho** [comment]
Agreed, I've amended the above.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by gasman** [comment]
I think we can declare this fixed by #5758 / #5769. (The fix there is missing a lot of the "giving developers control over the responsive CSS at the template level" nuance proposed here, but I get the impression that the only control developers really want is "being able to kill it with fire" 😁. If I'm wrong about that, feel free to reopen...)
