### ISSUE TITLE
Tags field needs universal help text to explain need to quote multi-word tags

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#1874]
Wagtail's tagging system requires multi-word tags to be quoted, to prevent a two-word tag becoming two separate tags. This appears to catch users out repeatedly and has generated several Issues in recent months.

The tag field widget, wherever used (page models, images, documents etc) should have standard help text (appearing beneath it like all help text) explaining the need for quoting. Explaining the need for comma-delimiting might also be worth adding while we're at it.

**Comment by khink** [comment]
I'd like to work on this today. I'm at the Django under the Hood sprint. We have about 3 hours of sprinting left.

**Comment by khink** [comment]
starting on this (wagtail space sprint, ticket destroyer team)

**Comment by khink** [comment]
I think this can be closed, as https://github.com/wagtail/wagtail/issues/3488 makes the default behaviour different.

**Comment by gasman** [comment]
I think it's still a good idea to have help text explaining the behaviour, whatever that behaviour is... I guess that with #3488 in place, we'd need two different help messages depending on the value of `TAG_SPACES_ALLOWED`.

**Comment by amajai** [comment]
Hello @lb- . I would like to have a shot with this issue.

**Comment by lb-** [comment]
@amajai  no need to ask permission, review the comments and the PRs that are linked and give it a go :)
