### ISSUE TITLE
Image Chooser pop up doesn't close after insert in Streamfield paragraph block

### ISSUE THREAD

**Issue by jossingram** [wagtail/wagtail#1880]
When you add a paragraph then insert an image upon choosing a format and inserting the image the format box does not disappear like it should do. You can see the image has been placed in the background though.

If you close this box or click off it and either save or preview wagtail will throw an error saying the field cannot be blank. 

This will either break the Streamfield interface completely so you are stuck (no + sign) or on occasions it will simply delete the column which you need to recreate again. 

Screenshots below show the issue occuring. Noticed this after upgrade to 1.1 but could have been there before.

![largewt](https://cloud.githubusercontent.com/assets/5364807/10824916/7393677c-7e5a-11e5-8ed2-01ee9cea6e9b.png)
![largewt2](https://cloud.githubusercontent.com/assets/5364807/10824914/738f9dd6-7e5a-11e5-9af7-dce43cc40c69.png)
![largewt3](https://cloud.githubusercontent.com/assets/5364807/10824915/73906964-7e5a-11e5-8320-dcce6ac2a2e0.png)

**Comment by jossingram** [comment]
Sorry should add this issue only occurs sometimes (so far always in Chrome Browser)

**Comment by gasman** [comment]
Hi @jossingram - I haven't immediately been able to replicate this. Please can you check if anything appears in the Developer Tools console when this occurs?

**Comment by jossingram** [comment]
'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).
c47c9bb0186d.js:19 We don't execute document.execCommand() this time, because it is called recursively.
c47c9bb0186d.js:19 We don't execute document.execCommand() this time, because it is called recursively.
e86f06efe089.js:1 Uncaught RangeError: Maximum call stack size exceededx.event.dispatch @ e86f06efe089.js:1v.handle @ e86f06efe089.js:1x.event.trigger @ e86f06efe089.js:1(anonymous function) @ e86f06efe089.js:1x.extend.each @ e86f06efe089.js:1x.fn.x.each @ e86f06efe089.js:1x.fn.extend.trigger @ e86f06efe089.js:1jQuery.widget.execute @ c47c9bb0186d.js:19(anonymous function) @ e86f06efe089.js:23jQuery.widget.cleanupContentClone @ c47c9bb0186d.js:237

**Comment by SalahAdDin** [comment]
:+1:

**Comment by thibaudcolas** [comment]
Looking at the stack trace above, this was a contenteditable text selection issue. This shouldn't affect the new editor, so I'll close this for now.
