### ISSUE TITLE
updated_at field for Documents

### ISSUE THREAD

**Issue by jordij** [wagtail/wagtail#1903]
We find that a good amount of users like to replace existing documents files with new versions. This allows them to keep the references and links from any page to the document. Bad news is that the model only keeps track of the first upload date `created_at`, causing a bit of confusion as they like to use the documents interface to keep track of the new uploaded versions.
It would be nice and useful to add a new datetime field to solve this.

**Comment by JoshBarr** [comment]
Yeah, I can see revisions of binary assets being a very useful feature for some of our users.

**Comment by gasman** [comment]
This was touched on in #1420, although we'll probably use the SHA1 hash / Etag route for that...

To clarify, would you want this timestamp to update on *any* edit to the document record (e.g. editing the title), or only when uploading a new file? Or would this be a user-facing field for them to fill in themselves?

Also, would this replace the current 'uploaded' column in the documents listing, or be in addition to it?

**Comment by davecranwell** [comment]
In a broader sense this was touched on in #496 to, created because I thought that sites with a more complex structure, or a bigger body of contributors would require a better paper trail for alterations to each of the objects tracked by wagtail.

**Comment by jordij** [comment]
@gasman Just to clarify, we were more thinking of a timestamp that gets updated each time **any field** of the Document (file and/or title) is edited. From what we've learnt from our users, most of the time it's just the file is being updated. ie: a pdf monthly review gets updated each month, title stays the same *Monthly review* but file is replaced. We understand that other case scenarios are possible though.

The new datetime field wouldn't be editable but only visible, complementing or replacing the *uploaded* (potentially *created*) column in the admin interface.

However I also like where @davecranwell is going with the generic logging system. I agree with the images thing but imho I consider the documents a bit more critical as the user can't see the contents of the doc at first sight. They need to download and open the file to see what's in it. With images the user can see how they do look like, knowing what version is in the CMS at first sight.

**Comment by jordij** [comment]
With documents now being easily customised through `WAGTAILDOCS_DOCUMENT_MODEL` this can be easily achieved.
@davecranwell I'd like to know about the _history_ feature you were mentioning above. Has some work been done on this? Cheers

**Comment by davecranwell** [comment]
A comprehensive logging system hasn't become any more real than the comments on these Issues and it's not on the roadmap yet either. If you're interested in taking it on, an RFC would certainly be welcomed.

**Comment by chosak** [comment]
Adding a +1 to this issue. Today I worked with a new Wagtail user who was very confused that the "Uploaded" column in the documents list view doesn't get updated when a document gets replaced with a new version. Their use case is very similar to what @jordij describes above; replacing a document with new versions periodically.

Labeling the `created_at` column "Uploaded" is thus a bit misleading. As an immediate UX fix short of any code changes, could this be changed to something like "First Uploaded" or maybe "Created"?

**Comment by zerolab** [comment]
Closing in favour of #5658
