### ISSUE TITLE
Document the ajax_template mechanism

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#1945]
Doesn't seem to be covered in the documentation at the moment. An example setup is described here - just needs writing up as proper documentation: https://groups.google.com/d/msg/wagtail/O44bT6qXFaU/B5IAd8qNBAAJ

**Comment by RatanShreshtha** [comment]
I would like to add this in documentation, how I should proceed ?

**Comment by lb-** [comment]
@RatanShreshtha just saw that you never got a reply to this question, let us know if you are still keen to get started.

For documentation it is pretty easy to get started.

1. Go to the docs page you want to edit (for this docs it should go here: http://docs.wagtail.io/en/v1.13.1/advanced_topics/customisation/page_editing_interface.html )
2. Near the top right click 'edit on github'
3. Switch to the branch 'Master' on the tree menu on the left, under the code tab
4. Click 'edit this file' the pencil button on the right
5. Make changes / follow the [restructured text format](https://en.wikipedia.org/wiki/ReStructuredText)
6. Propose your changes by filling in the details at the end of the file (in the 'commit file') section

Full details on how to get started with developing below, more suitable for checking changes and checking that the files all compile well.
 
http://docs.wagtail.io/en/v1.13.1/contributing/index.html

Thanks
