### ISSUE TITLE
Not enough contrast between logo and background in admin

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#1947]
![screenshot from 2015-11-20 01 58 12](https://cloud.githubusercontent.com/assets/3639540/11290014/4827ce9e-8f2a-11e5-9de9-4a9d0e0d0f38.png)

The beak is barely visible on the dark background.

**Comment by davecranwell** [comment]
What would you suggest to solve that? I've tried adding a subtle white shadow/outline but it looks a bit odd.

**Comment by tmsndrs** [comment]
- [ ] UX/UI working group to discuss and add further actions

**Comment by thibaudcolas** [comment]
@rgs258 to have a look

**Comment by thibaudcolas** [comment]
Well, this took a while! Finally fixed in #5467 – thank you @alexgleason for the initial report.

This will be released in Wagtail 2.9.
