### ISSUE TITLE
Nested InlinePanel

### ISSUE THREAD

**Issue by abhirocks9636** [wagtail/wagtail#1952]
First of all thank you for this wonderful software.
I struggled alot to add related_links InlinePanel into Another Section InlinePanel  but it gives attribute error of HomePageAnotherSection has no attribute related_links  PLEASE HELP.
Example Code:

``` python
class HomePageAnotherSectionRelatedLink(Orderable, RelatedLink):
    page = ParentalKey('demo.HomePage', related_name='related_links')

class AnotherSection(LinkFields):
    intro = models.CharField(max_length=200, blank=False)
    panel =[
InlinePanel('related_links', label="Related Links")
]
```

**Comment by gasman** [comment]
Hi @abhirocks9636 - unfortunately we don't support nested InlinePanels at the moment. There are a couple of possible workarounds, such as defining your content with [StreamField](http://docs.wagtail.io/en/v1.2/topics/streamfield.html) (in this case you could define Section as a StructBlock, consisting of an 'intro' CharBlock plus a ListBlock for related links), or by making each section a child page. (This doesn't mean they have to be presented as multiple pages to the end user - the child pages would just be placeholders for the data, retrieved and displayed using a query on the parent page.)

I'll leave this ticket open, as I don't think we currently have one covering the nested InlinePanels issue.

**Comment by heymonkeyriot** [comment]
Hi @gasman 

I haven't heard this mentioned in a _long_ time, but a problem I've bumped in to on a project that reminded me that we can't nest inline panels within inline panels (we got around it by defining lots of different models, which worked but was a little clumsy)

Do you know if there's been any more thought on how nested inline panels may be possible?

**Comment by alexfromvl** [comment]
HI. The problem with nested InlinePanel remains. Tried to link the page to another model. Getting an error. The only solution is to bring the first InlineIanel to snippet

**Comment by Sam-Costigan** [comment]
I have been doing some digging on this as it's something I'd really love to be able to do. It seems to me that for the most part this limitation is imposed by django-modelcluster. For that reason I have created an issue on that repository: https://github.com/wagtail/django-modelcluster/issues/105
