### ISSUE TITLE
Editing Image Bug - NotImplementedError

### ISSUE THREAD

**Issue by chadsaun** [wagtail/wagtail#1996]
I am using django-offsite-storage to store all my images on S3.  When I go to edit an image, I get the following error...

```
NotImplementedError at /cms/images/157/
No exception message supplied
```

![Imgur](http://i.imgur.com/yBNyOnV.png)

If Wagtail can't get the file size or the dimensions, could it just say "N/A" so that we can at least edit the title, tags, etc. ?

**Comment by kaedroho** [comment]
Thanks for reporting @chadsaun 
This definitely looks like a bug in django-offsite-storage (they haven't implemented their own version of ``.size()`` so it's falling back to Django's default one). But I agree that Wagtail should catch this error.

**Comment by thibaudcolas** [comment]
I see `django-offsite-storage` has had no support in 9 years and is now archived. Closing. If we have similar compatibility issues with other storage options we can open new issues.
