### ISSUE TITLE
Add "view site" button to admin

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2047]
Similar to how WordPress has this "view site" button at the very top of the dashboard. This is useful if you want to quickly get back to your live site from the admin.

![screenshot from 2015-12-16 13 12 03](https://cloud.githubusercontent.com/assets/3639540/11851126/9d0a905a-a3f6-11e5-9914-4789b8720960.png)

**Comment by davecranwell** [comment]
:+1:

**Comment by SalahAdDin** [comment]
:+1:
