### ISSUE TITLE
Cassandra database support

### ISSUE THREAD

**Issue by jodroid** [wagtail/wagtail#2082]
Does Wagtail supports Cassandra database? I have installed django-cassandra-engine and not having too much luck getting it going yet. Any pointers will be much appreciated.

**Comment by gasman** [comment]
Hi @jodroid,
We don't currently support Cassandra, and haven't yet investigated how feasible it would be to do so. I'm not aware of any specific reason why it wouldn't work (although Wagtail is designed to run with a standard SQL database, so it could be a lot of work depending on how far Cassandra deviates from that).

For further support queries, please use the [Wagtail Google group](https://groups.google.com/forum/#!forum/wagtail).

**Comment by auvipy** [comment]
there is django cassandra engine to add cassandra support

**Comment by jodroid** [comment]
@gasman Thanks for the insight. Will do for further support with the Google group. 

@auvipy I believe that might be the same package I'm trying out to get it Cassandra working with Wagtail.

**Comment by kaedroho** [comment]
Closing as this doesn't highlight a bug in Wagtail or a feature we need to implement (at least for now anyway)
