### ISSUE TITLE
Passing template variable as a filter to Image tags

### ISSUE THREAD

**Issue by DiogoMarques29** [wagtail/wagtail#2090]
Hi,

Have you consider doing something like this:

```
{% for img in self.get_images %}
    {% get_custom_filter forloop.counter as my_filter_var %}
    {% image img my_filter_var %}
{% endfor %}
```

This is useful when we want to assign different filters depending on the forloop counter, or some other condition.

I'm working on a solution, but for now, my solution only accepts a variable or chained filters.
Do you see this being integrated in wagtail?

**Comment by gasman** [comment]
Hi @DiogoMarques29,
This would go against the intention of the `{% image %}` tag, I think. It's designed on the principle that there will be a small, limited number of filters in use on a site - each generated image is kept on the filesystem forever, and we don't want to end up in a situation where there are thousands of images with hundreds of different renditions each. Allowing variables here would make it too easy for developers to get into bad practices without realising it - such as allowing editors to generate images at arbitrary sizes (or worse, allowing front-end site visitors to generate them).

If you need this feature, I would suggest implementing it as a separate custom tag.

**Comment by timheap** [comment]
I've also come up against this issue before, where I needed to output different sizes based on some criteria. A giant `if/elif` block in the template is very ugly. Repeat that a number of times if you need to reuse the logic, and accepting a variable for the image filter spec becomes much more desirable.

If a developer abuses this feature, that is on their head. A note could be put in the docs mentioning that making arbitrary sizes will fill up the file system, but limiting the developers freedom hurts more than it helps from where I am coming from.

As an aside, this is actually possible in the Jinja version of the `image` tag. It accepts a string argument: `{{ image(my_img, "max-200x100") }}` or `{{ image(my_img, my_filter_var) }}`.

**Comment by JoshBarr** [comment]
@gasman I've just come up against this too. The ability to pass variable arguments into image tags would be extremely useful, especially when you think about colour operations (where the colour may be dependent on something set in the CMS).

Could we consider re-opening this?

**Comment by gasman** [comment]
Reopening as requested...

Writing out my thoughts on filters / renditions at https://groups.google.com/d/msg/wagtail-developers/cSRtU-xN4ZE/47bPm5mQDAAJ has allowed me to get to the bottom of why I was uncomfortable about this feature - essentially, it doesn't fit with my mental model of filters as persistent objects that are attached to a given `{% image %}` tag and perform a pre-determined operation. The fix is for me to update that mental model, not to veto this as a feature :-)

With that in mind - and in line with what I wrote on that mailing list thread - I'd like to eliminate `Filter` as a Django model as a pre-requisite to implementing this, and have the Rendition table just store the filter strings instead. (Filter can still exist as a Python object, if appropriate.) As it stands, we'd be creating a new Filter record in the database for every different value that ever gets passed into the `{% image %}` tag - which probably doesn't cause any harm, but it's certainly an artefact of the old mental model (i.e. of filters being persistent things that are largely set in stone at design time) and I'd like to make a clean break from that.

(As a separate note, I think it would be good to implement some sort of 'garbage collection' for image renditions, so that renditions that were created as a one-off in the distant past don't sit around in the database and filesystem forever.)

**Comment by ebertti** [comment]
@gasman I believe it is right to leave with the developer to worry of the amount of images that it can create and eventually need to delete. The responsibility is his and not the wagtail.

See my case, as I had to deal with this limitation:

```
{% if item.value.type== 'wide' %}
  {% image item.value.file fill-600x250 as photo_resized %}
{% elif item.value.type== 'tall' %}
  {% image item.value.file fill-300x500 as photo_resized %}
{% elif item.value.type== 'wide tall' %}
  {% image item.value.file fill-600x500 as photo_resized %}
{% else %}
  {% image item.value.file fill-300x250 as photo_resized %}
{% endif %}
```

**Comment by moaxey** [comment]
For my use case which would benefit from the ability to specify image width and height in the template tags directly. My template logic would need to be exponentially larger than shown above.

I come from a history of using sorl.thumbails for a few years and am attracted to wagtail for a variety of reasons, one being automatic cropping around a defined feature of an image. As you are probaly aware, sorl.thumbnail allows specifying sizes directly to the tag and has management commands for cleaning up the file cache. I think their image name is a hash from the properties passed to the tag, but I do like your more meaningful image names more.

My site is experimental, but I have a history of very visual personal sites and creating them when getting interested in a new system or platform as a practical learning and evaluation exercies. And that is where I am at.

The only frontend javascript I am using is to set a cookie for the width and height of the window, and am hoping to send visitors images which match relatively well to that. In the past I have used divs with css background cover as responsive images. I really want to take advantage of your system's ability to crop around a point in the image in combination with that technique as I sometimes ends up with important features missing from the displayed image.

So regardless of the image's original format, I might need it in landscape, square or portrait depending on the request.COOKIE. 

I'd be happy to have a bit of a hack around to see if I can help, but might need a little more direction first to have a better chance of an acceptable pull-request.

**Comment by gasman** [comment]
As of #3351 the Filter model has now been completely dropped and replaced with a plain Python object, so this can go ahead.

**Comment by mikemonteith** [comment]
My use-case for this is for the srcset attribute (https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images).

I'd like a developer to be able to define an image width & height and have our templates generate 2x and 3x images without the developer having to explicitly define the exact widths and heights for each size inside an {% image %} tag.

Basic example:
_Page template_:
```
{% include "image_template.html" with base_size="300x200" %}
```


_Image template_:
```
{% get_image_sizes img base_size as image_sizes %}

{% image img image_sizes.small.crop as img_small %}
{% image img image_sizes.medium.crop as img_medium %}
{% image img image_sizes.large.crop as img_large %}

<img sizes="..." srcset="... (use the three different image sizes here) ..." />
```

I can't see a way of doing this without being able to pass args into the `{% image %}` tag

**Comment by favoyang** [comment]
Here's a monkey patch to resolve image specs from a context variable.

https://gist.github.com/favoyang/0641c63fea72485f412ec97de7035691

**Comment by enzedonline** [comment]
Is this not already available just using the `get_rendition()` method of the image object?

```
@register.simple_tag()
def get_rendition(image, image_options):
    return image.get_rendition(image_options)
```

```
{% get_rendition self.some_image some_rendition_options as img %}
```

Multiple options just need to be concatenated with "|" instead of a space (e.g. "width-500|format-webp")

**Comment by gasman** [comment]
@enzedonline Yes, and in fact this was the ultimate conclusion we came to on https://github.com/wagtail/wagtail/pull/4895#issuecomment-1344904186 which implements this feature but was somehow never linked to this issue...

Closing as wontfix.
