### ISSUE TITLE
Maybe you can distribute static assets as bower packages or via cdn?

### ISSUE THREAD

**Issue by MechanisM** [wagtail/wagtail#2098]
I always use gulp, stylus, coffeescript and other things to build static assets in my projects, I'm maintaining separate repos for front-end only code(just like taiga.io does), and all vendor assets are linked from cdnjs or installed via bower and uploaded to AWS s3 by gulp. I think it would be nice to have all static assets from wagtail to be installable/available via bower(or even better uploaded to cdn like cdnjs.com or jsdelivr.com).
Maybe some settings can be used for this purpose.. like WAGTAIL_USE_CDN = True or smth like that.

**Comment by thibaudcolas** [comment]
Hi @MechanisM, could you expand a bit why you think either of those additions are interesting?
