### ISSUE TITLE
Embed Soundcloud: In HTML is wrong padding attribute

### ISSUE THREAD

**Issue by netAction** [wagtail/wagtail#2122]
After embedding a Soundcloud source in richtext editor it renders like this:

```
<div style="padding-bottom: 0;" class="responsive-object">
  <iframe width="100%" height="400" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?visual=true&url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F235591558&show_artwork=true"></iframe>
</div>
```

The Soundcloud IFRAME is invisible because of unset height in the wrapper .responsive-object. The _padding-bottom_ property should be set to _400px_ instead of _0_.

This is the CSS used:

```
.responsive-object {
  position:relative;
}

.responsive-object iframe, .responsive-object object, .responsive-object embed {
  position:absolute;
  top:0;
  left:0;
  width:100%;
  height:100%;
}
```

**Comment by kaedroho** [comment]
Related: #1495

**Comment by thibaudcolas** [comment]
We now have a `WAGTAILEMBEDS_RESPONSIVE_HTML` setting which is disabled by default, so I believe this is no longer an issue.
