### ISSUE TITLE
Make InlinePanel Collapsible?

### ISSUE THREAD

**Issue by mainderay** [wagtail/wagtail#2123]
While I believe it is possible to put an Inline panel inside of a MultiField panel, it seems a bit hackish. Given the nature of Inline Panels (list of items), would it be more elegant to support the collapsible and collapsed classes for them?

**Comment by gasman** [comment]
Related: #1336

**Comment by kaedroho** [comment]
This might be useful: https://github.com/kaedroho/wagtail-condensedinlinepanel

**Comment by BertrandBordage** [comment]
I confirm that this is already possible using `MultiFieldPanel`.

**Comment by andsimakov** [comment]
@BertrandBordage, I'm just wondering, in what way? I've wrapped Inline panel inside one MultiFieldPanel into another MultiFieldPanel. Nothing has happened. kaedroho's solution looks cool but native way is preferred.

**Comment by BertrandBordage** [comment]
As part of the Wagtail’s first Kickstarter campaign, I’m working on this!
https://www.kickstarter.com/projects/noripyt/wagtails-first-hatch
