### ISSUE TITLE
IntegrityError not caught when saving snippet InlinePanel (unique constraint violation)

### ISSUE THREAD

**Issue by bgrace** [wagtail/wagtail#2136]
The following model relates two snippets to create an orderable list of items managed through InlinePanel. A unique constraint is added to disallow duplicate entries. When duplicate items are added and the list is saved, an exception is raised (appropriately) but not handled. I suspect this is generally true for IntegrityErrors across the admin interface. Reproducible on Wagtail 1.2.0 _and_ 1.3.1, Django 1.8.7, and Python 3.4

``` python
class ArrangementCategoryItem(Orderable, models.Model):
    category = ParentalKey(ArrangementCategory, related_name='arrangements')
    arrangement = models.ForeignKey('Arrangement', related_name='categories')

    panels = [
        SnippetChooserPanel('arrangement')
    ]

    class Meta:
        unique_together = ['category', 'arrangement']
```

**Comment by rmartins90** [comment]
+1

**Comment by AdamBolfik** [comment]
+1

**Comment by PresidentNick** [comment]
Yup, same issue. Duplicates on fields that should be unique are not handled.

**Comment by dpratter** [comment]
+1
