### ISSUE TITLE
Support multiple global menus for pages to appear in

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2177]
We currently have one tickbox, [show_in_menus](https://github.com/torchbox/wagtail/blob/0845f1e1c1122e6ec4a9d75d488a23ed3d834554/wagtail/wagtailcore/models.py#L317).

I would like to see a more configurable option. Some sites, for instance, have a top and bottom menu which must be managed. There's currently no easy way to insert another tickbox for `show_in_bottom_menu` or the like.

**Comment by timorieber** [comment]
+1. I've implemented input and logic to handle an additional bottom menu a year ago, but not with a generic approach. Would really like to see this in future versions.

**Comment by alexgleason** [comment]
Notes:

* Menus are instances of a Menu model
* Options: depth, pages?
* Should pages to assigned to menus (harder to implement) or menus assigned to pages?
* I wonder if we can automatically add all menu tickboxes under a FieldPanel('show_in_menus') render?

**Comment by alexgleason** [comment]
Upon further reflection and considering #836 I think it would make the most sense for site menus to be separate from the explorer, but with some features that make building them easy.

For instance, you can create a "top menu" which you add configurable items to.

**Comment by JoshBarr** [comment]
You might be interested in this solution: http://jordijoan.me/simple-orderable-menus-wagtail/

**Comment by zerolab** [comment]
Closing in favour of #7767
