### ISSUE TITLE
Autocomplete of slug field doesn't work when django.contrib.admin not in INSTALLED_APPS

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#2178]
Autocomplete of slug field doesn't work on Wagtail 1.3.\* when `django.contrib.admin` not in `INSTALLED_APPS` because `wagtail.wagtailadmin` [uses urlify.js](https://github.com/torchbox/wagtail/blob/v1.3.1/wagtail/wagtailadmin/templates/wagtailadmin/pages/_editor_js.html#L25) from `django.contrib.admin`.

As workaround we can add `django.contrib.admin`'s static directory to [`STATICFILES_DIRS`](https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-STATICFILES_DIRS) or just add `django.contrib.admin` to `INSTALLED_APPS`.

**Comment by gasman** [comment]
Related (since it implies that we might want to drop our reliance on urlify.js completely): https://github.com/torchbox/wagtail/issues/1443#issuecomment-148395601

**Comment by lb-** [comment]
Closing as this was fixed sometime around 1.7

https://github.com/wagtail/wagtail/blob/v1.7/wagtail/wagtailadmin/templates/wagtailadmin/pages/_editor_js.html#L24
