### ISSUE TITLE
Difficult to create multi-level lists

### ISSUE THREAD

**Issue by heymonkeyriot** [wagtail/wagtail#2212]
Within the richtext field it's difficult to create multilevel ordered, or unordered, lists. e.g. the following are impossible directly within the richtext editor
1. This is a list
   1. This is a second level to the list
      1. And a third level
- Unordered list
  - Also is
    - difficult to do

The 'intuitive' way of doing it would be to click `tab` to define the sub-levels (the behaviour in TinyMCE in Wordpress for example). This isn't possible in the richtext editor clicking tab will, probably correctly, select a different page element.

There is a workaround to copy and paste from another source (e.g. a word document) where there are already lists correctly structured but this feels undesirable.

Other platforms, such as Google Mail, get around this with an indent button as below
![image](https://cloud.githubusercontent.com/assets/11335309/12910208/6503bb7a-cf00-11e5-9101-59679f18c593.png)

**Comment by JoshBarr** [comment]
Occasionally we have this issue too. Clients will create some content with nested lists and want to be able to easily recreate it in the editor. 

Moving to something like https://trix-editor.org/ might help?

**Comment by thibaudcolas** [comment]
Fixed in the new editor. Still there for Hallo though.
