### ISSUE TITLE
Separating publish delete actions and meta information on edit screen 

### ISSUE THREAD

**Issue by heymonkeyriot** [wagtail/wagtail#2214]
A number of times rather than click `publish` I've clicked `delete` on the edit screen. This is because I'm clumsy, but also because the two actions are next to one another in the toggleup menu, and have the same colouring / hierarchical weight.

Thinking about that problem led me to realise there are a few other possible issues with the action footer
- There's a potentially strange hierarchy (e.g the `preview` button is always accessible whilst `publish` isn't)
- There's an inconsistent use of colour (e.g. `preview` is grey, whilst the `save draft` is green)
- There's an inconsistent use of icons (only `preview` has one)
- Certain meta data (e.g. when it was last modified, and by whom) is on the same horizontal layer as the actions)
- Other meta data, e.g. status, privacy and edit lock isn't available on the footer
- There's friction in the user journey by the fact that most actions are hidden within the toggleup menu.

**Current footer**
![image](https://cloud.githubusercontent.com/assets/11335309/12911108/db028f66-cf07-11e5-8808-b3938b5ca72a.png)
# Possible amends

Below are some early ideas I was playing with, which
- Try and more clearly separate delete/ unpublish actions from save/ publish actions
- Try and separate out the meta data from actions (to enable more meta data to be included, and potentially increase extensibility)
- Try and increase consistency between button styles and icons
- Try and increase accessibility to all the actions (so we're not pre-judging which actions are most important to the user)

**Amended (white buttons on green)**
![image](https://cloud.githubusercontent.com/assets/11335309/12911194/8dd09b9c-cf08-11e5-9aad-67a9d08ac9c9.png)

**Amended (green buttons on black)**
![image](https://cloud.githubusercontent.com/assets/11335309/12911147/2e3d7920-cf08-11e5-9cac-180814a48f38.png)
_Closer to the existing UI_

**Amended (medium-esque UI)**
![image](https://cloud.githubusercontent.com/assets/11335309/12911159/3fa52744-cf08-11e5-9ec8-b5ea904a4007.png)
_Continuing with the idea of a toggle menu, with delete/unpublish in a different font-weight to publish. I don't think this is an improvement (I think it adds a different kind of complexity with the `...` menu, but here in case it sparks any better ideas)_

I recognise the above are quite opinionated suggestions so wanted to start a discussion around gathering thoughts before thinking about any sort of pull request.

**Comment by davecranwell** [comment]
Love where you're going with this. I've wanted a redesign of parts of the page editor interface for a while. While I don't want to pile on the work, I've mentioned various other gripes with this UI before, some of which you've already tackled here:

https://github.com/torchbox/wagtail/issues/1836
https://github.com/torchbox/wagtail/issues/439
https://github.com/torchbox/wagtail/issues/622

Back to your designs... I particularly like the dots for more content in that medium-esque UI, as it allows for many of the page actions which are curiously absent from this interface (copy, move, preview draft).

I also like the status, visibility, and lock information: as I've mentioned in my tickets it's cluttered and confusing at the top of the screen. The header bar was never intended to contain that much.

**Comment by tomdyson** [comment]
Great work, @heymonkeyriot! FYI we're also planning to link to revisions from the footer, e.g. in @kaedroho's PR #2170 (demo available at http://wagtail-revisions-ui.demo.torchboxapps.com/admin/pages/4/edit/ with admin/changeme).

**Comment by alexgleason** [comment]
Yes please

**Comment by heymonkeyriot** [comment]
Ah #439 is a gripe I've had as well. Will certainly find some time to look in to that. #622 and #1836 both feel like there would be potentially more technical rather than visual solutions to improve the user experience but will have a think about them too.

To move back to this I would worry that taking the Medium approach may draw us in to looking for the perfect solution. When there's more functionality on the page that certainly does feel as though it would be 

I wonder, in terms of making iterative improvements whether something like the following may be the best first step?
![image](https://cloud.githubusercontent.com/assets/11335309/12970960/dbd0ee7a-d08c-11e5-9aff-c0ecc721da77.png)

That uses functionality that's already in existence in the footer area, and becomes then an issue of visual amends, rather than functional amends. I think it will also help users to not have the UI dramatically change in one go.

**Comment by davecranwell** [comment]
I'm inclined towards a combination of your screenshots 1 and 3. #622 is now rather out of date, given it mentions not being able to order the explorer by last edit, which is no longer a problem. The remaining problem in that ticket is still however present: the fact that within the page editor UI, you can't actually fully control the page.

Screenshot 3, specifically the "More" dots, provides a perfect container in which we can continue to add functionality later, without constant changes to the user experience. Screenshot 1 puts the most-used features directly in view. The combination of the two, I think, could be powerful.

The one possible problem I see with screenshot 1, is the amount of horizontal space required for the number of buttons visible. Anything less than a 'decent' resolution will incur some significant wrapping, which will take up a lot of screen space. The "More" dots could actually come in handy here though. They could take the overflow of buttons less frequently used e.g "Submit for moderation", "Unpublish" and "Delete".

**Comment by strindhaug** [comment]
I've created a working pull request with my suggestion for improving this footer menu: https://github.com/wagtail/wagtail/pull/3247

It's inspired by the "Amended (medium-esque UI)" example. But I've reused the existing "drop-up" widget with slight modifications instead of creating a whole new widget for the "..." menu.

Please comment if you have any suggestions or feedback.

**Comment by tmsndrs** [comment]
Any objections to closing this? We're going to take this on from ticket #3269

**Comment by thibaudcolas** [comment]
Closing per https://github.com/wagtail/wagtail/issues/2214#issuecomment-346598716. We can reopen if needed.
