### ISSUE TITLE
Certain colours combinations not validating against WCAG AA

### ISSUE THREAD

**Issue by heymonkeyriot** [wagtail/wagtail#2224]
There are a couple of colour combinations used across the admin area that don't validate against [WCAG 2.0](https://www.w3.org/TR/WCAG20/). The teal-color on white, or white on teal-color doesn't validate 

```
color: #43b1b0
bg: #fafafa
contrast: 2.47:1

color: #fff
bg: #43b1b0
contrast: 2.58:1
```

Note: To validate against AA there needs to be a contrast of 4.5:1

We use it on the dashboard
![image](https://cloud.githubusercontent.com/assets/11335309/12971797/de17f296-d096-11e5-9430-cbe839f41946.png)

And on button hover states 
![image](https://cloud.githubusercontent.com/assets/11335309/12971791/c07ca45c-d096-11e5-8eb3-f6ea5ab29c2f.png)

There's a couple of ways we could move around this in the short term:
### Using color-teal-dark

![image](https://cloud.githubusercontent.com/assets/11335309/12971707/f7b878f2-d095-11e5-81bf-d6cdf4ae3166.png)
Since it's already in the sass variables would be to use `$color-teal-dark: #246060;` for the header area and buttons. The issue with the color-teal-dark is that it loses quite a lot of saturation and we'd need to change all the examples through the sass files
### Amend color-teal

![image](https://cloud.githubusercontent.com/assets/11335309/12971692/cde83634-d095-11e5-85ba-1c76b2c1d9a4.png)
Slightly more straight-forward (as it'd be changing a single variable) we could amend the color-teal to something more saturated, and lighter than `color-teal-dark`, which validates 4.5:1 in contrast. The above uses `#198180`. 
### Use `#333` text

![image](https://cloud.githubusercontent.com/assets/11335309/12971687/c1057648-d095-11e5-9bd0-642855f316a9.png)
Another alternative is that `#333` validates against `#43b1b0` but it really flattens out the visual style by darkening everything.

As with some other issues I've raised it's potentially quite an opinionated change as it'll have quite an impact on the UI so would be good to have thoughts.

**Comment by thibaudcolas** [comment]
Moving the discussion over from #3106, which demonstrates the types of changes required that we can't merge as is.

> To test this:
> The colours were run through http://webaim.org/resources/contrastchecker/ and http://leaverou.github.io/contrast-ratio/

> Core team position:
> Those are quite sweeping visual changes so they won't be merged as is. We want a visual design person to get involved to assess this further.
> A potential alternative approach would be to have settings of sorts for a separate "high-contrast mode". I think the default install shouldn't compromise on accessibility, but realistically it would be easier to solve this within Wagtail itself with a separate code path.

**Comment by marteki** [comment]
I'll be looking at this during the Wagtail Space US sprint. I'm a UX designer with experience making accessibility improvements.

**Comment by gasman** [comment]
Completed in #4788.
