### ISSUE TITLE
Use case(s) for non-404 redirects?

### ISSUE THREAD

**Issue by mainderay** [wagtail/wagtail#2228]
I've got a site with parent pages that have no content, but define a category for leaf pages. I'd like the this empty parent page to redirect to one of its children. In looking at the middleware source, it appears the redirect is ignored if the from page exists. Are there any downsides to the idea of not checking for 404 when executing the the redirect!

**Comment by timheap** [comment]
This can be done by modifying the parent page, rather than reworking the redirect middleware. By overriding the `serve` method on the parent page:

```python
from django.http import Http404
from django.shortcuts import redirect

class ParentPage(Page):
    def serve(self, request):
        # Get the first child page
        child = self.get_children().live().public().first()
        # There were no children. Return a 404 page
        if child is None:
            raise Http404
        # Redirect to the first child page
        return redirect(child.url)
```

**Comment by lb-** [comment]
Reasonable work around provided, closing issue
