### ISSUE TITLE
StreamBlock(required=True) doesn't work

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#2236]
Setting `required=True` on a streamblock seems to be ignored, without error. Also, if your `StreamField` has `blank=False` (the default) it will not give an error if there is no content.

**Comment by riceyrice** [comment]
I guess there's always some JSON...

**Comment by kingel** [comment]
Might https://github.com/torchbox/wagtail/issues/536 of use too?

**Comment by gasman** [comment]
Fixed in #3315
