### ISSUE TITLE
Document `{% embed %}` tag

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#2238]
As far as I can tell embeds don't have any documentation, only an passing reference in the editor's manual (http://docs.wagtail.io/en/v1.3.1/editor_manual/new_pages/inserting_videos.html#inserting-videos).

Documentation is required of 
- `{% embed %}`
- the fact there is no `EmbedField` or similar
- suggested approaches for responsive scaling.

See also #1553, #1894, #1756 amongst others.

**Comment by kaedroho** [comment]
Renamed to "Document {% embed %} tag" now that https://github.com/torchbox/wagtail/pull/2975 is merged

**Comment by kaedroho** [comment]
Documentation in https://github.com/wagtail/wagtail/pull/2127
