### ISSUE TITLE
Consider adding an opensearch for wagtail.wagtailsearch

### ISSUE THREAD

**Issue by MechanisM** [wagtail/wagtail#2241]
I think it would be good addition! I know there's a few ready django apps for this purpose(like [django-opensearch](https://github.com/vint21h/django-opensearch)), but having such option in wagtail out of the box will be great!

**Comment by BertrandBordage** [comment]
We won’t get that in Wagtail itself for now, until OpenSearch is more widely used.
However, it’s easy to create a third-party app serving XML files following the OpenSearch specification and using the Wagtail search API inside its views.

So feel free to create such a third-party app and add it to https://github.com/springload/awesome-wagtail! :)
