### ISSUE TITLE
FileField in an InlineModel not adding enctype="multipart/form-data"

### ISSUE THREAD

**Issue by iammattq** [wagtail/wagtail#2251]
Hey, I noticed #1741 the fix you did for getting the `enctype="multipart/form-data"` to appear. However, it doesn't want to appear when the FileField is part of an InlineModel (like in your BlogRelatedLinks example). Do you think we could get this fixed up?

I've tested adding the FileField to the parent model and it works great. Thanks

**Comment by bmihelac** [comment]
This also applies to new *ModelAdmin*. 

It looks like EditHandler should be extended with `is_multipart` method, instead of checking main form.

**Comment by gasman** [comment]
Fixed in #3501 for the page editor (and separately in the next release of django-modelcluster: https://github.com/wagtail/django-modelcluster/pull/73)
