### ISSUE TITLE
Add filter spec option for background color

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#2259]
Cleaned up photos are often extracted from a background. For example product beauty shots.  It would be nice if these images could be uploaded to wagtail as transparent png files and then templates could specify the background matte to apply to the image for the rendition.  This way the images appear to be transparent but jpeg compression can be used.  Right now one must either use transparent PNG and accept the large file size or apply the jpeg background matte before uploading the image.  If you go with the jpeg option when the page css changes all images on the site have to be replace and reuploaded which is a time consuming and difficult process (also error prone when the images can be displayed on different background colors)

Would it be feasible to add background matte into the filter spec options?  And perhaps rendition format?  So jpeg could be forced using a specific background color?

**Comment by JoshBarr** [comment]
I'm working on the first part of the request (add background matte into the filter spec options) but I don't understand enough of Willow/Wagtailimages internals to manipulate the output format just yet.

**Comment by kaedroho** [comment]
https://github.com/torchbox/wagtail/pull/2474 Implements an ``outformat`` filter so I think we just need something to fill in the background color now.

**Comment by thenewguy** [comment]
So it doesn't appear that this ever gained any traction and I'd like to pick it up. I've implemented the background matte operation as a 3rd party app using the willow/wagtail hooks.  Is this filter something that would be integrated into wagtail? If so I am happy to post it to github for review and I would be happy to refactor it for inclusion to willow/wagtail proper if it would be merged

**Comment by kaedroho** [comment]
Just implemented a ``set_background_color_rgb`` operation in Willow: https://github.com/wagtail/Willow/pull/61

**Comment by BertrandBordage** [comment]
Fixed by #3911.
