### ISSUE TITLE
Duplicate image detection and prompt for verification image is not duplicate

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#2261]
I've been reading about duplicate image detection and I figured it would be a neat feature for wagtail image handling.

It would be a very helpful flow if an image upload in the dashboard would ask to verify image is not a duplicate of near matches already in the database.

Not sure if this is something the project is interested but here are a few links I put aside for later:
- https://realpython.com/blog/python/fingerprinting-images-for-near-duplicate-detection/
- https://pypi.python.org/pypi/ImageHash
- https://github.com/JohannesBuchner/imagehash
- http://hzqtc.github.io/2013/04/image-duplication-detection.html
- http://blog.iconfinder.com/detecting-duplicate-images-using-python/
- https://news.ycombinator.com/item?id=7521844

There are python implementations available for computing the hashes.  It might be something that would need to be offloaded into celery tasks though.  I haven't looked into the implementation very far.

**Comment by davecranwell** [comment]
:+1: Anything that helps users maintain order is worth it, in my book.

**Comment by heymonkeyriot** [comment]
Agree with Dave. This would be great to have. I've made the mistake a few times of adding the same image multiple times without realising! 

The only issue may be from a UI perspective of how to communicate the alert to the user without putting too much friction in the way of the task they're working on. But overall it'd be something really positive to introduce.

**Comment by thibaudcolas** [comment]
See #7819.

**Comment by zerolab** [comment]
#8284 adds duplicate detection in the multi-add view

**Comment by gasman** [comment]
Completed in #8284
