### ISSUE TITLE
cursor missing after inserting a link in Hallo WYSIWYG

### ISSUE THREAD

**Issue by sf-wind** [wagtail/wagtail#2288]
After inserting a link to the WYSIWYG, the cursor is missing. Need to find the location of last edit and continue. It breaks the normal content editing flow. 

Can the cursor be kept in place after the insertion? 

Thanks.

**Comment by thibaudcolas** [comment]
Reproduced in latest master.

**Comment by thibaudcolas** [comment]
We've replaced Hallo with a new editor, which doesn't have this issue. Closing.
