### ISSUE TITLE
Launching previews is unreliable

### ISSUE THREAD

**Issue by tomdyson** [wagtail/wagtail#2289]
Steps to reproduce:
1. Start editing a page
2. Hit preview, preview loads in a new tab
3. Return to the edit tab, make some changes, hit preview
4. The spinner may just spin
5. Close the preview tab
6. GOTO 2

I get this on Chrome and Safari on OS X, on Wagtail 1.3.1 and earlier.

**Comment by alexgleason** [comment]
Can confirm this. It's also something I've experienced.

**Comment by davecranwell** [comment]
I'm not sure how solvable this is. I've looked into it before and found myself limited by popup blockers, and browser idiosyncrasies concerning iframe, window management and load events.

We have the following challenges:

1. Allowing the submission of invalid forms
2. Previewing a change without it also saving.
3. Avoiding interrupting user workflow by taking the user away from the editor (display in a window)
4. Refreshing the preview
5. Nice loading of previews

1. and 2. seem reasonably stable but the rest need some more thought.

3. Doing this with new windows is clearly part of the problem, so what are the alternatives? I think we may need to accept that although we _can_ avoid taking the user away from the editor, our best solution may still prevent edits while previewing e.g a modal overlay, or the editor sliding away to reveal preview etc.

4. Being unable to refresh the preview is one of the biggest frustrations with editing. Neither our current solution nor, for example, a sliding-over/overlay preview, would solve this. However being prevented from using the editor while previewing and avoiding using a new window would at least remove the suggestion that refreshing is a possibility. Not being allowed to refresh is a symptom of working with models that must validate, which is the heart of all preview problems.

5. Knowing when a preview has loaded isn't so hard, but trying to support refresh of the preview has proven tricky. Ditching windows would certainly help.

**Comment by ababic** [comment]
I've also been experiencing this and have had a client raise it as an issue. The error was a bit harder to identify, though. 

My page type has a StreamField, and when the trying to preview the page without filling out all required fields, the preview page errors with a 'KeyError' when looking for 'content-count' at `/wagtail/wagtailcore/blocks/stream_block.py` in `value_from_datadict`, line 136

I can only see that error if I go to the preview URL directly, though. If I click the 'Preview' button in the footer, the preview opens in another tab, but then just swiftly disappears.

**Comment by ababic** [comment]
Adding to the confusion... if the `ModelAdminMiddleware` from `wagtailmodeladmin` is active, the preview tab redirects to the modeladmin list view for that model before it has chance to close. I think I should be able to patch that, though.

**Comment by timheap** [comment]
For wagtailnews, I implemented previewing in a slightly different manner which I think works better.

When the Preview button is pressed, the page is submitted as if you had hit Save or Publish. The form is validated, and a draft is saved. Then, the edit screen is shown again, with a small bit of JS that loads the preview page in a new window/tag, which just shows the latest draft. This approach has the downside that a draft versions is saved, which differs from the way Page previews work currently, although I may have a way around that...

Part of the problem, from what I understand, is that you are doing funky things with the request to check if the submitted form is valid. If it is valid, you write the response to the preview window. If the response is invalid, you write the response to the edit window. This hijacking of the request cycle is what is leading to some of the drama.

An alternative workflow that blends the two approaches, and might solve some of the issues could be: When the Preview button is pressed, submit the edit form in the normal manner to the backend. The backend validates the form, but does *not* save it. The edit screen is then shown to the user again. When the page loads, and if there were no errors, some JS submits the form data to the preview page. This data has already been checked for validity, so (barring any rare corner cases of the server reloading between requests changing the form definition) this data should be ready to render a preview without using strange JS hacks.

This does not solve the issue of refreshing the preview, as I do not know a way of bringing focus to an unfocused tab through JS. It does solve some of the other problems though, without resorting to `document.write()`

**Comment by benebun** [comment]
We are also running into this issue with a client without being able to reproduce it with the same browser version.
Has anybody found a reliable way to reproduce it and possibly a workaround?

**Comment by kiwiheretic** [comment]
I get the spinner hanging on preview also.  I'm having this issue also on the "pip install" version.  I was looking for a cms to recommend to a client.

**Comment by joyider** [comment]
Is this really a bug? In my case it was simply a matter of making sure that the X_FRAME_OPTIONS is set to SAMEORIGIN and not DENY.

And if you are using a reverse proxy make sure that it is configured for SAMEORIGIN as well. I'm not a nginx ninja but it seems to me that the default behaviour of nginx is to set X_FRAME_OPTIONS=DENY

**Comment by kjartansverrisson** [comment]
This issue can consistently be reproduced in the following way (mostly as @tomdyson describes):

1. Start editing a page
2. Save draft
3. Hit preview, preview loads in a new tab
4. Return to the edit tab, make some changes
5. Save draft
6. Hit preview 
7. The spinner just spin
8. Close the preview tab
9. GOTO 3

What happens is that when a preview window opens, the edit window retains a reference to it which  is then used to close the preview window if the preview button is clicked again. This reference is used to close the preview window to only re-open it as a fresh preview.

This results in the edit window, having lost the reference to the preview window will attempt to open up a new window, but rather than getting a new window it will get a reference to the old window and attempt to reload the preview there and fails.

![image](https://cloud.githubusercontent.com/assets/58954/22792421/96774e6a-eee4-11e6-8dd7-5d7066d41fac.png)

It seems the culprit is this line in page-editor.js, where an addEventListener fails silently, resulting in "submitPreview" never being called:

`previewWindow.addEventListener('load', function() { submitPreview.call($this, true); }, false);`

Why it fails in this scenario is still beyond me, but I'll continue to look into this.

**Comment by jjanssen** [comment]
Fixed in #3359
