### ISSUE TITLE
Document render_form method of blocks

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2291]
Ex:
Our client wants to build a page layout with tabs, where each tab contains a StreamField.

It would be nice to be able to create a TabsBlock and then customize the way it looks in the admin so that, despite functioning and being stored in the DB like a regular ListBlock, it appears in the admin as tabs that the user can add, rearrange, and switch between.

It would be cool to have some sort of API or defined methodology for doing this. I'm not sure it's even possible using our current tools, is it?

I'd be pretty happy to create this as a pip installable app using wagtail_hooks and injecting js and css into the page editor. But can we change the markup at all?

**Comment by gasman** [comment]
This should be possible by subclassing `ListBlock` and overriding the `render_form` method, although that's not really properly documented at present. #2274 will formalise this for `StructBlock`, though.

**Comment by alexgleason** [comment]
Thanks. :smile:

**Comment by thibaudcolas** [comment]
I see render_forms has _some_ documentation since #7164. Closing.
