### ISSUE TITLE
What's the status on supporting multi-tenanted sites?

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#2292]
My team is hoping to be able to move our simple website offering to a multi-tenanted Wagtail setup, replacing our existing single-tenanted Ruby on Rails offering. But looking at the issue queue, it seems like the last time multi-tenanted Wagtail was discussed was back in September 2015 (#1700), and it seemed to be in a mostly-nonworking state at that point.

Has there been any recent progress on making Wagtail capable of supporting a fully multi-tenanted setup? My team needs each Site to be completely separate from each other Site, including editors for one site having no access to (or even knowledge of) the content on another site. Though it would be _really_ cool if superusers _didn't_ have this restriction. Will that be possible in the future?

**Comment by tomdyson** [comment]
Hi @coredumperror. There has certainly been progress towards this, most notably with the Collections feature, which will be released in 1.4 (scheduled for next week):

http://docs.wagtail.io/en/latest/releases/1.4.html

The Collections work sits on top of a revised permissions model, which makes it possible to manage view / edit / delete rights across different slices of content. Some background reading:

https://github.com/torchbox/wagtail/wiki/Collections-RFC
https://github.com/torchbox/wagtail/pull/2243
https://github.com/torchbox/wagtail/pull/2126

Note also this hook (and related issue) for filtering the explorer menu, which may be useful in some multi-tenancy scenarios:

https://github.com/torchbox/wagtail/pull/2219 
https://github.com/torchbox/wagtail/issues/2196

There are several large multi-tenanted Wagtail setups that we know of. There are still aspects of multi-tenancy that could be improved, but Collections addresses the most important issue for most implementations.

**Comment by coredumperror** [comment]
Sweet! I'll check this Collections stuff out ASAP.

**Comment by gasman** [comment]
I should mention that the current implementation of Collections is lacking the ability to restrict *usage* of images / documents by collection, which would be a key feature of true multi-tenancy support - while users can be restricted to particular collections when uploading images, they can still choose from the full set of images when inserting them into pages. We hope to add this feature in a second phase of development.

**Comment by coredumperror** [comment]
I'm curious why you guys decided to push the usage restriction back to a later release. What challenges got in the way of including it in this one? It's something we're definitely going to need, so I may end up implementing it myself. Any insight into this functionality would be much appreciated.

**Comment by gasman** [comment]
Collections was simply a much bigger architectural change than we'd anticipated - it required major refactors to various areas of Wagtail such as permission models, tree structure handling and generic admin views. It also ended up going through a number of iterations and false starts as we found that the original design of the feature didn't satisfy our requirements for backwards compatibility and ease of upgrading.

In order to keep the code changes manageable for reviewing and merging, we had to narrow the scope of the feature quite considerably. As a result, usage restrictions were one thing that got dropped from the initial implementation. I don't believe there are any specific blockers standing in the way of implementing it, and now that the basic collections feature is merged we're in a better position to develop that as an extension.

**Comment by coredumperror** [comment]
> There are several large multi-tenanted Wagtail setups that we know of.

Are you at liberty to divulge which sites those are? I'm getting pretty deep now into research on how to implement our multi-tenant setup, and I'm starting to run into issues where talking to a dev who's already done this would _really_ help.

**Comment by tomdyson** [comment]
http://www.southwales.ac.uk/ is one - they co-sponsored the Collections feature to address some of their multi-tenancy issues. I'll contact you directly to talk about our own experience with this.

**Comment by coredumperror** [comment]
Great! I look forward to hearing your experiences! That'll help a ton with my implementation.

**Comment by viaregio** [comment]
Has there been any progress on "implementation of Collections is lacking the ability to restrict usage of images / documents by collection"?

**Comment by gasman** [comment]
@viaregio Not yet, but that'll be dealt with as part of the permission-limiting work started in #2463.

**Comment by gasman** [comment]
Closing this to reduce duplication of tickets - I'm now treating #2463 as the "master" issue for tracking multi-tenancy support (even if much of the work is happening on other PRs).
