### ISSUE TITLE
Multilingual support for the Wagtail backend

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#23]
Wagtail should be available in other languages. I'd expect the translations themselves would come from contributors, but the support for languages needs adding.

**Comment by nicoepp** [comment]
Looks like in Wagtail 1.10 some of the spanish translations got lost. 

Did some digging in the *.po files of wagtailadmin. Seems like the "es" locale has some translations which the "es_ES" hasn't. For example "Edit" or "Live" exist in the first but not in the second. These two words where translated in 1.9 in the backend (admin) when I had my site switched to spanish. Now if I change the new language setting (in 1.10) to spanish they simply stay in english. Other languages work fine in the newest version of Wagtail.

**Comment by gasman** [comment]
Thanks for the report @nicoepp! I can confirm I'm seeing missing Spanish translations in 1.10 too, and it doesn't seem to be related to the es_ES locale or the language switcher (it also happens with `LANGUAGE_CODE = 'es'` in settings). Investigating...

**Comment by nicoepp** [comment]
Thanks for looking into it. You're right, language switcher works fine and es_ES doesn't seem to be realted.

Before 1.10 our admin interface showed in the language of the django_language cookie which can be changed in our frontend. As detailed in [the docs](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#how-django-discovers-language-preference) the cookie has preference over  LANGUAGE_CODE.

Maybe [this](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailadmin/decorators.py#L30) is not the right place to set the language for the request? Thinking..

**Comment by gasman** [comment]
Have now opened #3600 to address this - unfortunately it looks like this is a Django bug / missing functionality...
