### ISSUE TITLE
React will load twice when using Wagtail components via NPM

### ISSUE THREAD

**Issue by JoshBarr** [wagtail/wagtail#2315]
This issue is summarising a discussion that @timheap, @justinvdm and I are having. React is loaded once in the new webpack entry points in #2297 [WIP] Explorer, then once again by an implementer's custom code that imports React components. E.g: 

``` javascript
// Required to mount React components ...
import ReactDOM from 'react-dom';
import { Explorer } from 'wagtail';

... 
// Now we have two instances of React! Side effects and warnings galore! 
ReactDOM.render(<Explorer />, document.querySelector('.explorer'));
```
### Possible solutions:
- Expose React and other WT dependencies as globals on `window` via [expose-loader](https://github.com/webpack/expose-loader), essentially skip using NPM bundled versions of common libs?
- Force the entire front-end build process to use the implementer's webpack config to build all the admin JS (not ideal!)
-  Have some way of collecting the implementer's code back into Wagtail's internal frontend build process, via a `manifest.json` or similar?

**Comment by justinvdm** [comment]
> Force the entire front-end build process to use the implementer's webpack config to build all the admin JS (not ideal!)

That option might not be too bad if the implementer is provided with a base webpack config they can extend, something like:

```
module.exports = function(entries) {
  // entries === implementer's entry points

  return {
    // base webpack config properties
  };
}
```

The tricky thing is that at some stage, we need to involve the python side at some stage to figure out where wagtail lives in order to find wagtail's internal entry points. Maybe something like [this](gist.github.com/justinvdm/1203d98a4b6be977cea4) might work? Not ideal needing to talk to python over stdout, but seems more sensible than moving part of the build process over to the python side.

**Comment by JoshBarr** [comment]
I was thinking about that too – however it means you have to build the JS inside the same virtual env that the python code is running in... otherwise it could find the wrong version of wagtail, or not find wagtail at all. Node file watchers are really slow inside vagrant boxes, too (but docker is fine, I think?). 

What if we move all the relevant client-side code to the npm package? Then we're not relying on searching site-packages at all... I remember we discussed this originally when creating the npm package, but we decided it would be too much of a departure from the current structure. Now there's a fairly compelling reason to do it. More and more I'm convinced that django's handling of frontend dependencies is prehistoric.

**Comment by JoshBarr** [comment]
Alternatively, we could have the python helper script write a manifest.json into the project directory as a postinstall hook to `pip install wagtail`, which contains the abspaths to all the original js entry points.

**Comment by justinvdm** [comment]
> What if we move all the relevant client-side code to the npm package? Then we're not relying on searching site-packages at all... I remember we discussed this originally when creating the npm package, but we decided it would be too much of a departure from the current structure. Now there's a fairly compelling reason to do it. More and more I'm convinced that django's default handling of frontend dependencies is inflexible unless you want a bunch of simple script files in your static/ dirs.

+1, was thinking this too :) How would we get each bundle webpack builds to the relevant django installed app's static dir though? Or would we use [`STATICFILES_DIRS`](docs.djangoproject.com/en/1.9/ref/settings/#std:setting-STATICFILES_DIRS) or something?

I think we still probably want a base webpack config for implementers to extend though. Maybe it is worth moving the webpack configs into `client/` and changing `webpack.base.config.js` to be usable internally by wagtail's dev and prod webpack configs, and also for implementers to use for their webpack configs.

**Comment by JoshBarr** [comment]
We could have the webpack config include the desired target paths explicitly, and output them into the local project structure, to leverage masking:

```javascript
entry: {
  'static/wagtailadmin/js/admin': './client/src/admin.entry.js',
  'static/wagtailadmin/js/editor': './client/src/editor.entry.js',
  'static/wagtaildocs/js/documents': './client/src/documents.entry.js',
  'static/wagtailimages/js/images': './client/src/images.entry.js'
},
output: {
  path: './',
  filename: '[name].js'
}
```

**Comment by thibaudcolas** [comment]
This isn't documented yet but Wagtail now exposes all of its dependencies as globals. I'd be happier to also have a DLLReferencePlugin to build a DLL bundle shipped via npm, but realistically there is no "Wagtail on npm" at the moment so that's for another time. Closing.
