### ISSUE TITLE
Enhancement: Edit HTML Source in Hallo Editor

### ISSUE THREAD

**Issue by wren-hearn** [wagtail/wagtail#232]
Most WYSIWYG editors allow for a toggle to edit the HTML source which actually fills the input element used with the content. There are lots of use cases where WYSIWYG editors fall short (such as editing tables) and being able to edit the source directly is essential.

The hallo.js shipped with Wagtail includes the HTML source-editor plugin, but changes the namespace (from "IKS" to "ncri") so it is unusable in page-editor.js. However, the hallo.js plugin works mostly fine when changing that namespace back and adding the plugin to page-editor.js. That plugin opens up a modal window which allows for updating the HTML source. Some further window-dragging JS and CSS tweaks would be needed.

An alternative would be to add a toolbar toggle to show the textarea input itself in the place of the rendered HTML.

**Comment by edrex** [comment]
The snippet above works but the resulting dialog is positioned very strangely in Wagtail 0.8.4

**Comment by SalahAdDin** [comment]
@jerel, the hooks file have to called wagtails_hook or can hooks only? where have to put in the code? in the same folder that models.py? is necessary have to plugin file for have html plugin? and if is necessary have the hallohtml plugin, where we have put it?

**Comment by abossard** [comment]
Put it in a file "wagtail_hooks.py" within an app directory, as described here:
http://docs.wagtail.io/en/latest/reference/hooks.html

**Comment by SalahAdDin** [comment]
Oh, thank you.

**Comment by PabloLefort** [comment]
Hi. I'm sharing a simple work around to insert html with template filter.
https://gist.github.com/PabloLefort/00be2b09a26791a467fa2aec83a6e195
```py
"""
  When editing the content use the brackets:
  [[ <iframe>..</iframe> ]]
  And after, use it in templates like this:
  {{ page.body|resolve_html|richtext }}
"""

# templatetags/mytags.py
from django import template

register = template.Library()


@register.filter
def resolve_html(value):
    new = value.replace('<p>[[', '')
    new = new.replace(']]</p>', '')
    new = new.replace('&lt;', '<')
    new = new.replace('&gt;', '>')
    return new
```

**Comment by gasman** [comment]
Hi @PabloLefort,

A StreamField with `RichTextBlock` and `RawHTMLBlock` options is a much better way of achieving this: http://docs.wagtail.io/en/v1.6.2/topics/streamfield.html

**Comment by PabloLefort** [comment]
@gasman 
All right, I'll try that.

Thanks very much
