### ISSUE TITLE
Deeply-nested StreamFields need better UX

### ISSUE THREAD

**Issue by heymonkeyriot** [wagtail/wagtail#2325]
#### Background

StreamField is undoubtedly awesome, but we have a problem that the more complicated a StreamField becomes the more difficult it is for an editor to use or maintain, and has no visual connection to how it will appear to the end-user. 

An example of the problem is a StreamField block called **cards** that we had on a recent project. Out of the box, in StreamField, it looked like this:
![Existing problem](http://eddbaldry.co.uk/wp-content/uploads/2016/03/existing-card-streamfield.jpg) 
_Admin view_

And on the front end as follows:
![Cards on the frontend](http://eddbaldry.co.uk/wp-content/uploads/2016/03/cards-front_end.jpg)
_Front end view_

I'm aware that arguably these cards should have been created in a different way e.g. a page reference that pulls the relevant content from the page it's referencing if the content model allowed; or using a custom block to inject CSS/ JS to allow better styling. @alexgleason ended up using the second option, which he's released as a [pip installable package](https://pypi.python.org/pypi/wagtailblocks-cards/2.0.1). It looks like:
![Improved cards](http://eddbaldry.co.uk/wp-content/uploads/2016/03/existing-card-streamfield-improved.jpg)

I think this is still problematic, though is a vast improvement on how it appears out of the box.
#### Possible solutions

I think there's two ways we can move StreamField from a UX point of view:
1. Take a clearer field approach for each StreamField block (similar to Wordpress's [advanced custom fields](http://www.advancedcustomfields.com/) or CraftCMS's [matrix](https://craftcms.com/features/matrix))
2. Have the semantic value of each block, that isn't purely text, captured outside of StreamField (e.g. in a dialogue, side-panel or separate page) and give the editor a clearer visual representation of what they're creating (similar to the Medium, Squarespace or Google Doc UIs)
#### Attempt at a solution

I think option 2, where the semantic value of each block is introduced outside of StreamField would lead to the richest editorial experience.

**I've uploaded a project on InVision with that in mind**. The first screen is at https://invis.io/ZA64KWAUB. There are hotspots throughout the screens to indicate the user flow, and should allow you to get a general sense of my thinking. I stress it is a little clumsy, and has a number of UI elements changed, which for the purpose of this exercise would have been better left as they currently are within Wagtail, but I think is enough to start a conversation. 

The InVision screen is based on StreamField blocks we needed for a recent project: **text, image, embed, call-to-action, cards, code block** and **downloads**. The workflow is not completely out of keeping with the existing pattern on Wagtail, a user reveals a dialogue if they interact with a `ImageChooserBlock()` or `PageChooserBlock()`.

To take the **cards** as one example (since I used it above to show the problem)
![github_0026_streamfield - card 1 complete 2x](https://cloud.githubusercontent.com/assets/11335309/13627674/ed1ce3d6-e5c3-11e5-9ee3-78ea5ba62910.jpg)
Above: Card presented visually as a card, rather than set of fields, with option to add additional card

![github_0031_streamfiled - create a card dialogue 2x](https://cloud.githubusercontent.com/assets/11335309/13627548/1315b942-e5c3-11e5-9d11-7f217946017e.jpg)
Above: Dialogue opened with set of fields to populated card.

![github_0032_streamfiled - card upload new image 2x](https://cloud.githubusercontent.com/assets/11335309/13627549/131656ea-e5c3-11e5-8451-19b15b6ab1c0.jpg)
Above: Additional elements required to populate the field (here an image) would happen within the dialogue rather than opening a new dialogue (since no-one once modals on top of modals!)

![github_0038_streamfield - create card completed information 2x](https://cloud.githubusercontent.com/assets/11335309/13627550/13176f30-e5c3-11e5-9360-058b572c4ba0.jpg)
Above: Populated field set

![github_0030_streamfield - card 1 hover 2x](https://cloud.githubusercontent.com/assets/11335309/13627685/006eadca-e5c4-11e5-9f3b-de5e13966dc2.jpg)
Above: User has to hover above the card and click `edit` to amend the content within it.

Note: I'm missing controls on the individual cards to move/ delete them, if you could just pretend they are there that would be great :)

The final page, with all elements added is as below:
![_0058_streamfield - download populated 2x](https://cloud.githubusercontent.com/assets/11335309/13632222/83a88d48-e5e0-11e5-88ac-2727aab95167.jpg)
#### Possible UX issues

Beyond the obvious technical issue that what I'm suggesting above is currently impossible within the confines of hallo.js, and difficult to get oEmbed to behave in this way, there are a couple of UX issues that others have flagged since I showed them this work
- Talking with @tmsndrs he noted that we run the risk of trying to pre-define use cases for StreamField. @gasman does a pretty good summation of why that would be a bad idea on the ['Add distinct icons to blocks' pull request](https://github.com/torchbox/wagtail/pull/2285). However, I think there probably is room for us pre-defining things (or at least creating pip installable blocks similar to Alex's cards). Our attempts to avoid pre-definition have led us to a situation where out of the box StreamField blocks can get very confusing, very quickly
- Again talking with @tmsndrs we run the risk that this predicates the population of content around a desktop presentation of the article e.g. an editor could finesse the article around the needs of the desktop user without thinking about mobile devices
- This implementation would still be unable to represent a '[Snow Fall](www.nytimes.com/projects/2012/snow-fall/)' style implementation of StreamField. There's no way I can think of that could actually do that. The few I've seen that try (all Wordpress plugins) that mess with z-indexing or fixed background positioning within the admin get very confusing very quickly. I think it's fine to have that limitation.

Would welcome thoughts, from the perspective of whether this really is a problem, whether my assumption of the direction to take for the solution is the correct one, and then whether the solution itself goes someway towards solving the problem.

**Comment by alexgleason** [comment]
Yep, we're on the same line of thinking. Related: #2291 #2265

Awesome work here!

**Comment by davecranwell** [comment]
Some thoughts:

* How does the developer control or dictate the "visual presentation" of any field or group of fields and how long will that take per field/field-group/panel/whatever?
* Which developer controls the "visual presentation" The wagtail core team, or the implementer?
* Are we not making life much harder by semi-simulating the published page appearance? The closer it looks to the real thing, the more the disparities with the real thing will become apparent and the more clients will request it looks _even more like_ the real thing: it's the WYSIWYG Uncanny Valley.

**Comment by alexgleason** [comment]
I think that ideally each of these elements would stay as close to a standard Wagtail stylesheet as possible. IMO there may be a happy medium between my implementation of cards versus Edd's.

As far as the amount of time, I think we could make most of these blocks somewhat abstract and pip installable. We would only need to produce new ones under special circumstances.

You create them by subclassing a block type and importing custom CSS/JS as well as rendering to a custom template if desired.

**Comment by JoshBarr** [comment]
I think this is heading down the right path: streamfield objects are represented in a list, then their contents are edited in a separate panel/view. We were thinking the implementation might be an overlay, kinda like Prismic.io. Sketches attached:

![streamfield-as-lists-1](https://cloud.githubusercontent.com/assets/1715456/13666457/82a0a3c2-e716-11e5-9a4d-9b7501fb3f87.png)
![streamfield-as-lists-2](https://cloud.githubusercontent.com/assets/1715456/13666459/82c7d37a-e716-11e5-8def-b8e86f1661e8.png)

**Comment by davecranwell** [comment]
Having only stubs of content in the main view also dramatically decreases the amount of scrolling involved. The scrolling was in fact the primary reason why we put labels beside inputs, not above.

**Comment by heymonkeyriot** [comment]
I think showing stubs is a really valid way of trying to solve the issue, though it's definitely taking a field approach to presenting StreamField. Representing streamfield objects as a list I think moves away from @gasman's idea of giving a rich editing experience whilst capturing semantic , but that doesn't mean it's not the right thing to do if we don't think we can offer that rich editing experience either because it's technically impossible, or because we don't think it's the right approach from a UX perspective.

@alexgleason marked the ticket as `For team discussion` and wonder if it may be easiest to have the start of the conversation over a call to try and run through all the thinking that's happening in different places at the moment? As @davecranwell mentions it's all one big web of UI!

**Comment by davecranwell** [comment]
There's a conversation about having a conversation in the Slack channel :P

**Comment by heymonkeyriot** [comment]
Ah, upgrading Slack had meant I lost the slack team !

**Comment by SalahAdDin** [comment]
:+1:

**Comment by Adrian-Turjak** [comment]
@tomdyson Thanks! https://github.com/heymonkeyriot/wagtailclearstream looks good. Will have a play with it, and offer some review/bug testing!

**Comment by SalahAdDin** [comment]
@heymonkeyriot good idea, good package.

**Comment by tmsndrs** [comment]
We ok to close this in favour of keeping the conversation on #3942 ?

**Comment by thibaudcolas** [comment]
@tmsndrs usually we wait for the PR to be merged before closing the relevant issue(s). I doubt it will happen in this case but sometimes PRs stall and don't get merged.

**Comment by gasman** [comment]
Completed as of the StreamField UI updates in 2.7.
