### ISSUE TITLE
Wagtail doesn't cache search results

### ISSUE THREAD

**Issue by danni** [wagtail/wagtail#2332]
```
    return backend.search(data['keywords'] or None, queryset)
```

Has the surprise side effect of launching repeated searches to Elasticsearch every time you iterate, instead of caching the results.

**Comment by kaedroho** [comment]
Wagtailsearch already caches results in the ``SearchResults`` object returned by calling ``.search()``, but the issue here is probably the fact that you may be calling ``.search()`` multiple times.

For example, the following code will only perform one query:

```python
results = backend.search(data['keywords'] or None, queryset)

for result in results:
    # do something

for result in results:
    # do something else
```

But the following will perform two queries:

```python
results = backend.search(data['keywords'] or None, queryset)

for result in results:
    # do something

results = backend.search(data['keywords'] or None, queryset)

for result in results:
    # do something else
```

I think this is expected behaviour as it behaves the exact same way as Django's ``QuerySet`` class does. If you want to cache the results, just keep the previous ``SearchResults`` object around.

**Comment by danni** [comment]
Nope definitely passes through my code once. Wrapping the return in list()
stops the multiple calls.

**Comment by kaedroho** [comment]
Hmm. One possibility could be slicing the results. Slicing a results set will return a new results set with it's own cache, is that happening in your code? (eg pagination)

**Comment by gasman** [comment]
Unable to replicate. With Elasticsearch 7 set up against bakerydemo as per https://docs.wagtail.org/en/stable/topics/search/backends.html#elasticsearch-backend, I am able to run the following within `./manage.py shell`:

```
>>> from wagtail.search.backends import get_search_backend
>>> from wagtail.models import Page
>>> backend = get_search_backend()
>>> backend
<wagtail.search.backends.elasticsearch7.Elasticsearch7SearchBackend object at 0x10c129160>
>>> results = backend.search("bread", Page.objects.all())
>>> [r for r in results]
/Users/matthew/.virtualenvs/wagtailpy312/lib/python3.12/site-packages/elasticsearch/connection/base.py:200: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchWarning)
[<Page: Black bread>, <Page: Bread and Circuses>, <Page: The Greatest Thing Since Sliced Bread>, <Page: The Great Icelandic Baking Show>, <Page: The Joy of (Baking) Soda>]
>>> [r for r in results]
[<Page: Black bread>, <Page: Bread and Circuses>, <Page: The Greatest Thing Since Sliced Bread>, <Page: The Great Icelandic Baking Show>, <Page: The Joy of (Baking) Soda>]
```

with the Elasticsearch server stopped for everything other than the first `>>> [r for r in results]`.
