### ISSUE TITLE
Generic in-admin help, which can be attached to any model and displays in page editor

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#2335]
The configuration of some sites is such that a client, particularly someone new to the project, often has a lot of questions about the behaviour and relationships between content. It would be nice if Wagtail were able to support generic help text, not attached to fields, which could provide this.

E.g A `NewsPage` model has a relationship to multiple `news_authors` in an inline panel, linking to an `Author` model. A `NewsListingPage` allows the visitor to search the `NewsPage`s by author. It's meaningless to list _all_ the authors, particularly if most have no `NewsPage`s to their name, so the filter is programmed to only display `Authors` which have been attributed to a `NewsPage`.

As a client trying to work out why their author isn't selectable from the search filter, its a question of explaining the configuration to the client. We might write separate documentation, but this can be forgotten or ignored. What would be nicer is help text explaining this behaviour, which could be put somewhere in the admin for easy reference when confusion arises.

**Comment by davecranwell** [comment]
It occurs to me that this help is most frequently required when a part of a content type is automated, alongside other content which is not. The apparent omission of the fields for the automated bit can confuse clients. 

Perhaps therefore a "HelpPanel" is a solution of sorts. It would be a Panel in the editor like any other, but rather than containing fields, it just contains text.

**Comment by gasman** [comment]
Implemented in #4374

**Comment by easherma-truth** [comment]
This works well except in cases where we have StructBlocks which themselves have need of placeholders for dynamic info or otherwise need extra helpful content to be shared with authors.

**Comment by thibaudcolas** [comment]
@easherma-truth could you further describe your use case in a separate issue / discussion thread? This has been closed for a while so it’s unlikely lots of people will be following discussions here.
