### ISSUE TITLE
Inconsistent reporting of counts for search results

### ISSUE THREAD

**Issue by ababic** [wagtail/wagtail#2344]
I'm using wagtail with the elasticsearch backend enabled, and have created a custom 'search_results.html' template in my project to override Wagtail's default front-end one, and the default wagtail front-end search view and url are being used (nothing being overridden there)

In our custom template, we want to have a 'total result count' at the top, to indicate the total number of matches, but are having trouble getting the correct number to show.

In my particular test search, the view returns 10 results in total, and those results are spilt into two pages of 5 (despite the default `results_per_page` value being 10 in https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailsearch/views/frontend.py).

I'm outputting the following in my template to try to get a picture of what is going on:

```
<p>1) {{ search_results.paginator.object_list }}</p>
<p>2) {{ search_results.paginator.count }}</p>
<p>3) {{ search_results.paginator.object_list | length }}</p>
<p>4) {{ search_results.paginator.object_list.count }}</p>
<p>5) {{ search_results.object_list.count }}</p>
<p>6) {{ search_results.object_list | length }}</p>
<p>7) {{ search_results.paginator.object_list }}</p>
```
#### Screenshot of above output:

![Output screenshot](http://i.imgur.com/y7Gpbev.png)
#### Thoughts:
1. `{{ search_results.paginator.object_list }}` outputs what looks to be correct... a list of 10 items, in the same order as the items that are split up to make each paginated page.
2.  `{{ search_results.paginator.count }}` shows 20 (would expect this to be 10)
3.  `{{ search_results.paginator.object_list | length }}` show 5 (would expect this to be 10)
4. `{{ search_results.paginator.object_list.count }}` shows 20 (would expect this to be 10)
5. `{{ search_results.object_list.count }}` shows 10 (would expect this to be 5)
6. `{{ search_results.object_list | length }}` shows 5 (correct)
7. `{{ search_results.paginator.object_list }}` now outputs a list of 5 items, which seems to just be the first 5 items... that last 5 seem to have disappeared.

Any ideas what could be causing this odd behaviour?

**Comment by ababic** [comment]
Note: After re-indexing via `update_index` everything seems to be fine on this particular site, so not a blocker for now. Still very odd behaviour being shown above, though.

**Comment by ababic** [comment]
Still experiencing issues with this one, and updating the index doesn't seem to make any difference. Below is some example code, where `filtered_qs` is a queryset that's already been defined, based on a bunch of conditional search filters. A few of the relationships go via through tables, so passing it to the elasticsearch backend's search method just throws up `FieldError`s 

``` 
from wagtail.wagtailsearch.backends import get_search_backend
from django.core.paginator import Paginator

...

search_qs = CustomPageType.objects.filter(pk__in=filtered_qs.values_list('pk', flat=True))
s = get_search_backend()
final_qs = s.search('search keywords', search_qs)

paginator = Paginator(final_qs, 15)
page_obj = paginator.page(1)
```

It seems that the total count returned via `paginator.count` is the same, whether `search_qs` is filtered or not... It's as though the count is reporting 'total hits for the model', and not 'total hits within the supplied qs', even though the results returned are correct.

**Comment by ababic** [comment]
FYI, the site is using wagtail==1.3.1

**Comment by ababic** [comment]
Have skirted the issue for now by cycling through the search result to create a python list of results in the same order, then handing the list to the Paginator instead.

**Comment by kaedroho** [comment]
Hi @ababic

``.search()`` performs a count query against Elasticsearch whereas ``|length`` performs a search query, loads all the results into Django (discarding any that don't exist in the DB), and counts them.

Most of the time they would return the same number. But if there are items in your search index that don't exist in the database, these won't be counted by ``|length`` but will be by ``.count()``.

**Comment by ababic** [comment]
Thanks @kaedroho. What was confusing me the most, is even when passed to a Paginator, evaluated, and split into pages, the counts are still very inconsistent.

**Comment by ababic** [comment]
That's perhaps just me misunderstanding how the Paginator class works, though. I thought it would trigger similar behaviour to `|length` when splitting the results into pages.

**Comment by kaedroho** [comment]
This should be fixed by: https://github.com/wagtail/wagtail/pull/3521 but I think there's another issue for it anyway

**Comment by rinti** [comment]
I just ran into something similar:

```bash
ipdb> search_results
<SearchResults [<ArticlePage: Ice skating in Stockholm>, <ArticlePage: Kayaking in Stockholm Archipelago>, <ArticlePage: Stockholm archipelago>]>
ipdb> search_results.count()
43
ipdb> search_results.results()
[<ArticlePage: Ice skating in Stockholm>, <ArticlePage: Kayaking in Stockholm Archipelago>, <ArticlePage: Stockholm archipelago>, <ArticlePage: Getting around Stockholm’s archipelago>, <ArticlePage: 10 reasons to visit Stockholm’s archipelago off-season>]
ipdb> len(search_results.results())
5
ipdb> search_results._get_es_body()
{'query': {'bool': {'must': {'multi_match': {'query': 'stock', 'fields': ['_all_text', '_edgengrams']}}, 'filter': [{'match': {'content_type': 'main.BasePage'}}, {'bool': {'must': [{'term': {'live_filter': True}}, {'prefix': {'path_filter': '0001000F'}}, {'range': {'depth_filter': {'gte': 2}}}]}}]}}}
```

It seems the es_body doesn't reflect my filters here. I do lots of filtering on primary key.
