### ISSUE TITLE
Site.find_for_request doesn't deal with IPv6 hostnames

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2375]
I suggest [django.http.requests.split_domain_port](https://github.com/django/django/blob/53e8ab580f7c0fcfc589ba0b1b6cc2556080e0b2/django/http/request.py#L516).

We have [this](https://github.com/torchbox/wagtail/blob/6fde6863c5684a3f8583d07efa79178129e128c1/wagtail/wagtailcore/models.py#L111):

``` python
hostname = request.get_host().split(':')[0]
```

but we could do this:

``` python
hostname, port = split_domain_port(request.get_host())
```

Currently splitting the hostname by `:` will erroneously take the first chunk of an IPv6 address. As a reminder, they look like this: `[2001:db8:85a3:8d3:1319:8a2e:370:7348]:443` and could be with or without the port. `split_domain_port` works around this.

**Comment by lb-** [comment]
Merged in via #5997
