### ISSUE TITLE
Minimum length validation ListBLock

### ISSUE THREAD

**Issue by robmoorman** [wagtail/wagtail#2379]
It often occurs when content editors fill in StreamField blocks with invalid content, even the form is submitted correctly. A good example is a Carousel Block. They add a CarouselBlock, but it's not clear they have to add one ore more Slides and why the frontend seems broken. Another scenario would be adding Q/A's for a FAQ, except you don't want empty Categories (so at least one Q/A is required).

From this perspective it would be nice to have an optional min_length field for a ListBlock.

```
class CarouselSlideBlock(blocks.StructBlock):
    caption = blocks.CharBlock(max_length=64)
    image = ImageChooserBlock()


class CarouselBlock(blocks.StructBlock):
    slides = blocks.ListBlock(CarouselSlideBlock, min_length=1)
```

**Comment by JhovaniC** [comment]
+1, yes please.

**Comment by Adrian-Turjak** [comment]
No progress on this? :(

Really useful feature.

I see there is a mostly finished pull request with some unresolved comments, and also missing JS validation, but it doesn't look like too much left to do. If there isn't any activity on this I may do a new pull request based on the old one (rebased to master) and add some js validation.

**Comment by robmoorman** [comment]
Hi @Adrian-Turjak that would be very much appreciated!

**Comment by thibaudcolas** [comment]
I think both #3914 and #4942 are tackling this, with #4942 most likely making it into Wagtail soon-ish.

@BertrandBordage could you confirm whether it will indeed fix this? I can see it mentioned on the PR, but not on #4473 / https://www.kickstarter.com/projects/noripyt/wagtails-first-hatch.

**Comment by BertrandBordage** [comment]
@thibaudcolas I confirm.

**Comment by CuriousLearner** [comment]
Hello, 

Thank you for all your hard work on this. It is a much-needed feature. Is there an expected timeline for its release?

**Comment by gasman** [comment]
Completed in #7334.
