### ISSUE TITLE
Document supported versions of Wagtail, Django and Python

### ISSUE THREAD

**Issue by timorieber** [wagtail/wagtail#2429]
It would be very helpful to have a common place where all supported versions of Wagtail (including support timeline, see https://www.djangoproject.com/weblog/2015/jun/25/roadmap/), Django and Python are documented.

Since Django tells which Python versions are supported by themselves, a link to the relevant docs may be sufficient (e.g. https://docs.djangoproject.com/en/dev/faq/install/#faq-python-version-support).

**Comment by m1kola** [comment]
Hi @timorieber!

You can find information about supported versions of Python and Django in `setup.py` ([example](https://github.com/torchbox/wagtail/blob/v1.4.2/setup.py#L76) from `v1.4.2` tag) or on [pypi page](https://pypi.python.org/pypi/wagtail).

I agree with you that would be nice to have support timeline and information about supported versions of Python and Django in documentation.

**Comment by timorieber** [comment]
Thanks, @m1kola.

Developers are aware of where they can find some of the information, but it's fragmented and incomplete. At least for corporate sites other people involved need to find this information, too, e.g. when planning a roadmap with a estimated timeline.

This document should provide the information at a glance and answer questions like

- "How long will Wagtail 1.4 LTS be supported? Until end of Django 1.8?"
- "Is Wagtail 1.3 still supported?"
- "We are upgrading to Python 3.5, which version of Wagtail and Django can I use?"
