### ISSUE TITLE
Link to access draft from page editing interface for live + draft pages

### ISSUE THREAD

**Issue by ghostwords** [wagtail/wagtail#2430]
This is a page editing interface nit: There should be an easy way to access the draft version of the page for pages in live + draft state, for reviewing and sharing with other people. The page status box (LIVE + DRAFT) links only to the live version. You can click the Preview button, but you can't share that preview with others.

**Comment by timheap** [comment]
:+1: I like this idea. The revisions work done recently should make a button that does this possible, as it is possible to preview any revision through that. A button just needs to be added.

**Comment by SableWalnut** [comment]
#2439

**Comment by lb-** [comment]
Closing as this is now being discussed on #3261
