### ISSUE TITLE
provide a template tag/filter for generating image url with dynamic image serve view

### ISSUE THREAD

**Issue by ychab** [wagtail/wagtail#2457]
Currently, it seems that we must generate dynamic image url ourself in **Python code** : http://docs.wagtail.io/en/latest/advanced_topics/images/image_serve_view.html#generating-dynamic-image-urls-in-python

However, most of the time, we only need to generate it in templates. We cannot use existing template tag `{% image%}` to avoid confusion. So providing a new template tag/filter with the same code as the example function `generate_image_url` could be a solution ?

I was wondering if there is a plan about this?

**Comment by zerolab** [comment]
That was done via #2461 / #4856. The template tag is `image_url`
