### ISSUE TITLE
Proxy models cannot be used with Wagtail Pages

### ISSUE THREAD

**Issue by kurtrwall** [wagtail/wagtail#2480]
Would love to be able to utilize proxy models to cut down on table creation.

``` python
class WagtailPage(Page):
    def fly(self):
        return 'flap'

class EaglePage(WagtailPage):
    class Meta:
        proxy = True
    def fly(self):
        return 'fwop'
...
>>> e = EaglePage()
>>> e.fly()
flap
```

Edit: This is a misleading example because it doesn't actually happen like this in a shell, but the page object passed around requests and such will behave like this as well as `page.specific`.

**Comment by kaedroho** [comment]
Related: https://github.com/torchbox/wagtail/pull/1736

**Comment by kurtw** [comment]
Thanks for doing the fix for this. Sorry I missed it and cluttered your issue inbox!

**Comment by zerolab** [comment]
Closing in favour of #4973 / #5202
