### ISSUE TITLE
datetimepicker doesn't respect locales dateformat

### ISSUE THREAD

**Issue by derhedwig** [wagtail/wagtail#2483]
Unfortunately the format for the datetimepicker is hard-coded in `wagtailadmin/static/wagtailadmin/js/page-editor.js`. But it would be much nicer if that would follow the date format of the locale.

**Comment by kaedroho** [comment]
Thanks for reporting @derhedwig

**Comment by derhedwig** [comment]
This seems to have been fixed some time ago.
