### ISSUE TITLE
Add ability to specify min/max block counts on StreamField / StreamBlock

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#2514]
As requested here: https://groups.google.com/d/msg/wagtail/RLMwoDN_5LA/Endv7GANAQAJ

Suggest this is done with parameters named `min_num` and `max_num`, to match #1529.

Related: #2379

**Comment by chimeno** [comment]
In case it's not possible right now (I haven't tried yet), it would be great to have a ``min_num``and ``max_num`` per field in the StreamField.
Examples:
  - One and only one event block.
  - More than two and less than 5 big images.

As I said, maybe it's possible right now but I'm not aware.

**Comment by StriveForBest** [comment]
@gasman do you guys have an update on this? Would be amazing to be able to limit the streamblock instances.

**Comment by m1kola** [comment]
Fix (#3605) was released in [Wagtail 1.12](http://docs.wagtail.io/en/v1.13.1/releases/1.12.html#other-features):

> StreamBlock now accepts min_num, max_num and block_counts settings to control the minimum and maximum numbers of blocks (Edwar Baron, Matt Westcott)

Closing this issue
