### ISSUE TITLE
Explorer menu scrolls with page content

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2520]
![screenshot from 2016-04-26 12 09 42](https://cloud.githubusercontent.com/assets/3639540/14825409/ce9dddde-0ba7-11e6-8362-38d60c8f70a8.png)

On a page with lots of children, if you open the explorer menu and then scroll, the menu will scroll with the page content, allowing it to be dislocated from its point of origin.

**Comment by gasman** [comment]
Fixed in #2525

**Comment by gasman** [comment]
Reopening as per #2678 - we need a fix that doesn't prevent the menu from scrolling if it exceeds the window height.

**Comment by jjanssen** [comment]
Closing this. Since the merge of the React Explorer (#3012) this will no longer be an issue.
