### ISSUE TITLE
Reduce specificity of CSS icon classes

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2600]
alexgleason/wagtailfontawesome#6

Hallo uses `.hallotoolbar .icon-*`, which is problematic because it makes using custom icon sets non-trivial since it increases specificity of the selector beyond a point that setting `.icon` can't override it.

I believe the same used to be true for `.streamfield .icon-*`, but that was eventually had the specificity removed.

**Comment by thibaudcolas** [comment]
Looking at the icon definitions for Hallo, the `icon-*` classnames are hard-coded in the [vendored dependency](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/static_src/wagtailadmin/js/vendor/hallo.js#L490). I'm very reluctant to change this code, however simple the update, so I think this will stay the same.

The good news is that the new editor simply defers to Wagtail's icon implementation, so overriding the icons there will be the same as anywhere else.
