### ISSUE TITLE
Ability to specify form widget for custom image model fields

### ISSUE THREAD

**Issue by ghostwords** [wagtail/wagtail#2610]
It currently doesn't seem possible to make your custom image model's CharField (for example) use a larger Textarea widget instead of the default TextInput. [admin_form_fields](http://docs.wagtail.io/en/v1.4.4/advanced_topics/images/custom_image_model.html?highlight=admin_form_fields) lets you specify field names only. Do we need something similar to the `widget` parameter used by [FieldPanel](http://docs.wagtail.io/en/v1.4.4/reference/pages/panels.html?highlight=widget#fieldpanel)?

**Comment by jasondilworth56** [comment]
At the risk of digging up something that's super old – is this something worth revisiting?

I'd love to see the ability to change the widget for ParentalManyToMany fields in our custom image model, for instance. If there's a way around that for now then great, but what would be involved in adding this functionality?

**Comment by gasman** [comment]
This was implemented in #6462 (for Wagtail 2.12), so can be closed now.
