### ISSUE TITLE
Make possible to use standard Django permissions for collections and pages

### ISSUE THREAD

**Issue by dburakov** [wagtail/wagtail#2668]
I want to use standard Django permissions for Pages, Documents and Images (without tree-level detalization).
The actual reason for it is that I have a separate Access Control admin panel based on Django (it is a centalized admin panel for several websites). So all the permissions have to be managed there.

In this  admin panel I can operate only standard Django permissions such as:
`wagtailimages | image | Can add image`
`wagtailimages | image | Can change image`
`wagtailimages | image | Can delete image`
`wagtailcore | page | Can add page`
`wagtailcore | page | Can change page`
`wagtailcore | page | Can delete page`
`wagtaildocs | document | Can add document`
`wagtaildocs | document | Can change document`
`wagtaildocs | document | Can delete document`

But granting this permissions has no effect, because Wagtail has it's own permission system (separated tables `wagtailcore_groupcollectionpermission` and `wagtailcore_grouppagepermission`).

So I want to overwrite the Wagtail [permission_policy](https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/permissions.py#L6) for collections and [PagePermissionTester](https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/models.py#L1633) for pages.

A possible solution to achieve it can be adding three hooks:
- One for overwriting Images `permission_policy` class
- One for overwriting Documents `permission_policy` class
- One for overwriting Pages `PagePermissionTester` class

What do you think about it?

**Comment by bobslee** [comment]
+1

**Comment by laymonage** [comment]
Closing in favour of #2907. We have an RFC wagtail/rfcs#92 for a permissions registry that would allow custom permission behaviour for all models, and feedback is welcome. We're aiming to work on the feature in the upcoming release.
