### ISSUE TITLE
Remember data in inputs in page chooser when switching between Internal / External / Email link

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#2692]
Inspired by #2640 and #2677.

It seems to me that would be great to remember a data in inputs in page chooser when switching between Internal / External / Email link.

<img width="970" alt="screen shot 2016-06-08 at 16 59 29" src="https://cloud.githubusercontent.com/assets/509198/15896782/69724fe8-2d9a-11e6-8aab-089b881186da.png">

**Comment by mipashyayalmar** [comment]
Hello there! I'm excited about contributing to this. Please let me know if this is still an open issue. As a novice to this repository, I would value any advice or help from other contributors. Regards ahead of time...

**Comment by m1kola** [comment]
I have a feeling that this is not longer valid since the UI changes significantly. I'll close this.
