### ISSUE TITLE
Need ability to restrict parent page types to "root" page

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#2768]
I want the editor to be able to add a homepage as a child of the "root" page only. Currently there's no way to do that.

The workaround is to use a fixture (or migration) to make the homepage, then restrict its subpage and parent page types to `[]`. But that doesn't stop the editor from deleting the homepage. If they do, they can't add one back again.

The correct behavior should be to set `parent_page_types = ['root']` (maybe a special string) to restrict pages from only being able to be added to the root page.

**Comment by gasman** [comment]
I think `parent_page_types = ['wagtailcore.Page']` will also work, as the root is the only valid instance of the bare Page class.

But yep, we ought to come up with something better... https://github.com/torchbox/wagtail/pull/1736#issuecomment-160944662 has a good suggestion for implementing this.

**Comment by overshard** [comment]
The trick @gasman has no longer works since moving to the new app naming structure in wagtail 2

**Comment by overshard** [comment]
I did try that and it does not work either. I'll fiddle with it some more tomorrow and see what I can do.

**Comment by nbuonin** [comment]
For me, both `parent_page_types = ['wagtailcore.page']` and `parent_page_types = [Page]` work.

**Comment by brylie** [comment]
This should also be added to the docs 📖

**Comment by zeroepix** [comment]
You might need to just use lower case:

`parent_page_types = ['wagtailcore.page']` works but `parent_page_types = ['wagtailcore.Page']` doesn't.

**Comment by y-martinez** [comment]
Hi everyone, this issue is available?

**Comment by tbrlpld** [comment]
I have just tried either spelling:
`parent_page_types = ['wagtailcore.page']` or `parent_page_types = ['wagtailcore.Page']` both work to limit the creation under the root page. 

I guess the only thing left is adding this to the docs.
