### ISSUE TITLE
Support for AWS ElasticSearch

### ISSUE THREAD

**Issue by TuxOtaku** [wagtail/wagtail#2776]
Hey guys, 

So correct me if I'm wrong, but I don't think you guys have any support for AWS' branded ElasticSearch. Is there any plans to support this? Have there been any pull requests that address this? Where should I look if I wanted to add this feature myself?

**Comment by kaedroho** [comment]
Hey @TuxOtaku 

I'm not aware of any differences with AWS' Elasticsearch that would mean Wagtail wouldn't work with it. Their [FAQ says](https://aws.amazon.com/elasticsearch-service/faqs/) that they use version 1.5.2, which is supported by Wagtail.

Have you come across any issues that meant Wagtail wouldn't work with AWS Elasticsearch?

**Comment by TuxOtaku** [comment]
Yeah I get an error from Elasticsearch saying 
`{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet on resource: boxingoctopus"}`

**Comment by kaedroho** [comment]
Thanks!

Just Googled that error message and came across this: http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-signing-service-requests

Looks like AWS needs Elasticsearch requests to be signed. It seems like the best way to do this is documented in the ``elasticsearch-py`` package https://elasticsearch-py.readthedocs.io/en/master/#running-on-aws-with-iam

I think this could be done entirely in settings as extra arguments passed into the ``WAGTAILSEARCH_BACKENDS`` entry are passed straight to the ``Elasticsearch`` constructor. This might work:

```python
# settings.py

from elasticsearch import Elasticsearch, RequestsHttpConnection
from requests_aws4auth import AWS4Auth

WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.wagtailsearch.backends.elasticsearch',
        'URLS': ['YOURHOST.us-east-1.es.amazonaws.com:443'],
        'http_auth': AWS4Auth(YOUR_ACCESS_KEY, YOUR_SECRET_KEY, REGION, 'es'),
        'use_ssl': True,
        'verify_certs': True,
        'connection_class': RequestsHttpConnection,
    }
}
```

**Comment by TuxOtaku** [comment]
@kaedroho Sorry man...no joy:

`  File "/opt/apps/boxingoctopus/boxingoctopus/settings/base.py", line 121, in <module>
    'http_auth': AWS4Auth('xxxxx','xxxxxxx', 'us-west', 'es'),
NameError: name 'AWS4Auth' is not defined`

**Comment by TuxOtaku** [comment]
@kaedroho pretty close. Here's what I ended up using to get things moving:

```
from elasticsearch import Elasticsearch, RequestsHttpConnection
from requests_aws4auth import AWS4Auth

WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.wagtailsearch.backends.elasticsearch',
        'URLS': ['https://YOURCLUSTER.REGION.es.amazonaws.com'],
        'INDEX': 'wagtail',
        'TIMEOUT': 5,
        'http_auth': AWS4Auth('ACCESS_KEY','SECRET_KEY', 'REGION', 'es'),
        'use_ssl': True,
        'verify_certs': True,
        'connection_class': RequestsHttpConnection,
    }
}
```
Thanks for helping to point me in the right direction!

**Comment by gasman** [comment]
Glad you got it working @TuxOtaku! Adding a note for us to add this to the docs.

**Comment by justinoue** [comment]
I've tried @TuxOtaku 's configuration suggestion and it does not work at all. It returns user anonymous cant perform, 443, etc.

The syntax doesn't seem to match the current configuration syntax (perhaps it's changed?)

This is what I have and it's almost working but the RequestsHttpConnection class doesn't seem to know how to handle the AWS4Auth. I'm getting "AttributeError: 'AWS4Auth' object has no attribute 'encode'".

```
WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.wagtailsearch.backends.elasticsearch',
        'INDEX': 'wagtail',
        'TIMEOUT': 5,
        'HOSTS': [{
          'host': 'myserver.region.es.amazonaws.com',
          'port': 443,
          'use_ssl': True,
          'verify_certs': True,
          'http_auth': AWS4Auth('access_key_id', 'secret_key', 'region', 'es'),
          'connection_class': RequestsHttpConnection,
        }],
    }
}
```

**Comment by justinoue** [comment]
This change seems to be working:

```
WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.wagtailsearch.backends.elasticsearch',
        'INDEX': 'wagtail',
        'TIMEOUT': 5,
        'HOSTS': [{
          'host': 'myserver.region.es.amazonaws.com',
          'port': 443,
          'use_ssl': True,
          'verify_certs': True,
          'http_auth': AWS4Auth('access_key_id', 'secret_key', 'region', 'es'),
        }],
        'connection_class': RequestsHttpConnection,
    }
}
```

**Comment by StriveForBest** [comment]
@justinoue this works but only if there are no special characters (é, ü, etc) otherwise getting the following error:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17345: ordinal not in range(128)
```

which what's interesting happens here:

```File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 880, in _send_output
    msg += message_body```

Try with any of the `Page.title` set to `'C\xc3\xa9line'` (Céline)

**Comment by gasman** [comment]
Have added the configuration to the docs in #3345; Unicode issue to be covered separately in #3331.

**Comment by BenSturmfels** [comment]
I'm seeing the same ``AttributeError: 'AWS4Auth' object has no attribute 'encode'`` error as mentioned above in https://github.com/wagtail/wagtail/issues/2776#issuecomment-246393591 by @justinoue.

I'm using Python 3.5, wagtail==1.11.1, elasticsearch==2.4.1 and requests-aws4auth==0.9 and the following config as per 1.11.1 docs (note ``elasticsearch2`` rather than ``elasticsearch``):

    WAGTAILSEARCH_BACKENDS = {
        'default': {
            'BACKEND': 'wagtail.wagtailsearch.backends.elasticsearch2',
            'INDEX': 'staging',
            'TIMEOUT': 5,
            'HOSTS': [{
                'host': 'SOMEID.REGION.es.amazonaws.com',
                'port': 443,
                'use_ssl': True,
                'verify_certs': True,
                'http_auth': AWS4Auth('ACCESS_KEY', 'SECRET_KEY', 'REGION', 'es'),
            }],
            'connection_class': RequestsHttpConnection,
        }
    }

I found that ``connection_class`` needed to be inside ``OPTIONS``, so looks like the docs should be:

    WAGTAILSEARCH_BACKENDS = {
        'default': {
            'BACKEND': 'wagtail.wagtailsearch.backends.elasticsearch2',
            'INDEX': 'staging',
            'TIMEOUT': 5,
            'HOSTS': [{
                'host': 'SOMEID.REGION.es.amazonaws.com',
                'port': 443,
                'use_ssl': True,
                'verify_certs': True,
                'http_auth': AWS4Auth('ACCESS_KEY', 'SECRET_KEY', 'REGION', 'es'),
            }],
            'OPTIONS': {
                'connection_class': RequestsHttpConnection,
            },
        }
    }

Here's the full traceback of error with the first config:
[traceback.txt](https://github.com/wagtail/wagtail/files/1246739/traceback.txt)

**Comment by BenSturmfels** [comment]
I've also just tested with ``elasticsearch`` and ``elasticsearch5`` backends and their equivalent "elasticsearch" Python package versions. Same error, so I think this is just a mistake in the docs.
