### ISSUE TITLE
Getting parent page

### ISSUE THREAD

**Issue by casdr** [wagtail/wagtail#2779]
I would like to be able to get the parent page of a child page. Maybe there is a way already, but I haven't been able to find it in the documentation.

Is this already possible and if not, can this be added?

**Comment by casdr** [comment]
Found it!
```shelf = Shelf.objects.parent_of(self).live().first()```

Maybe it's a good idea to add this to the docs? :)

**Comment by gasman** [comment]
There's an easier way than that... self.get_parent(). This isn't covered in the docs because it's implemented by the third-party [Treebeard](https://tabo.pe/projects/django-treebeard/) library - but I agree, we should at least have a pointer to Treebeard's docs.

**Comment by lb-** [comment]
@gasman not sure if this has been resolved in the way intended but the documentation does now cover `get_parent()`.

http://docs.wagtail.io/en/v1.13/reference/pages/model_reference.html#wagtail.wagtailcore.models.Page.get_parent

There is no reference to Treebeard though, I can add it if we still want that in there.

**Comment by gasman** [comment]
Good spot @lb-! Yep, I think we should still have a general note at the top of the http://docs.wagtail.io/en/v1.13/reference/pages/model_reference.html#methods-and-properties section to say that the Treebeard API is available.

**Comment by lb-** [comment]
I will get on it.
