### ISSUE TITLE
When opening an old revision, the content_type field should be copied from the live object

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#2803]
Revisions store all meta fields as well as content, but most of these meta fields are overwritten with the live version when a revision is loaded (https://github.com/torchbox/wagtail/blob/6ae36c0baa279037821a85b208ac3f00eadea6a6/wagtail/wagtailcore/models.py#L1441-L1448).

One exception to this is the `content_type` field. The value of this field can change if a page model is renamed or a page copied to a different site using `dumpdata/loaddata`. If the `content_type` within the revision is different to the live version of the page, this causes a crash.

For this reason, I think we should add `content_type_id` to the list of fields that are overwritten when a revision is converted into a page object.

**Comment by kaedroho** [comment]
Looks like Django 1.10 solves the issue when renaming page models: https://code.djangoproject.com/ticket/24067

**Comment by vupham04** [comment]
Hi, I'm going through the real-soon-now milestone to find some bugs to fix - it looks like this issue is already addressed by Django?

**Comment by gasman** [comment]
I think this can be closed, yes.

Content type IDs getting reassigned on certain kinds of dumpdata/loaddata operations _is_ a known issue, but I can't see how the proposed fix would address that. It would potentially help in a failure mode where a content type changes ID, and the live page record correctly tracks that change but the page revision JSON doesn't - but I can't see how that would ever happen. (Maybe it did happen for the pre-Django-1.10 renaming case...?)

(And if I'm mistaken about that, I think we can still reasonably remove this from the real-soon-now milestone, given that it doesn't seem to have been a major pain point for 5+ years :-) )
