### ISSUE TITLE
Add a system check for incorrect use of content_panels on non-page models

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#2822]
Using `content_panels` instead of `panels` on non-page models (including snippets, ModelAdmin, wagtailsettings, and InlinePanel child models) seems to be a very common mistake:

http://stackoverflow.com/questions/38207208/add-a-multifieldpanel-in-django-wagtail-basesettings
https://groups.google.com/d/msg/wagtail/nqb24PZRlhk/oKkbmUXZAgAJ
https://github.com/torchbox/wagtail/issues/1456
https://groups.google.com/d/msg/wagtail/hs_mX0xOoyY/fr7ktSTRAAAJ
https://github.com/torchbox/wagtail/issues/1912

I suggest we add a system check to warn about models that set a `content_panels` attribute when a `panels` attribute is expected instead. (The solution would need to take care to avoid false positives, since it _is_ valid to set `content_panels` if the edit_handler property is overridden.)

**Comment by lb-** [comment]
@gasman I have started this and have this mostly working but am stuck with something.

I cannot get the checks to automatically run for `contrib.settings`:

* I added a new checks.py file: [`wagtail/contrib/settings/checks.py`](https://github.com/wagtail/wagtail/compare/master...lb-:2822_panel_usage_checks#diff-515aa016f646d57b4416d128b7464c55)
* I then imported the checks in `wagtail/contrib/settings/apps.py` via `from . import checks  # NOQA`
* I then installed the app in BakeryDemo, ran some testing against settings models that are incorrectly configured.
* The code in contrib/settings/checks.py is never called/run - even though I did a very similar method for snippets and it works fine.

Full Code: https://github.com/wagtail/wagtail/compare/master...lb-:2822_panel_usage_checks

Note: I am still working on the tests so I have not put in a PR yet.

**Comment by gasman** [comment]
@lb- Try merging in my commit from #4164. While working on that fix, I noticed that the appconf for `wagtail.contrib.settings` wasn't being pulled in via `wagtail/contrib/settings/__init__.py`, which would explain why code in apps.py isn't being run...

**Comment by lb-** [comment]
Thanks @gasman - the line : `default_app_config = 'wagtail.contrib.settings.apps.WagtailSettingsAppConfig'` in /contrib/settings/__init__.py did the trick.
