### ISSUE TITLE
Allow access to the parent context inside get_context of StreamField blocks

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#2824]
See @gasman's [comment](https://github.com/torchbox/wagtail/pull/2786#issuecomment-230509762) for details.

**Comment by gasman** [comment]
An incomplete PR for this (functional, but without tests/docs and missing fallback behaviour for user-defined `get_context` methods that haven't been updated to receive a `context` kwarg) exists as #3032.

**Comment by gasman** [comment]
Implemented in #3275
