### ISSUE TITLE
process_form_submission should return the FormSubmission instance

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#2833]
It would be nice if the [process_form_submission](https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailforms/models.py#L159) method returned the FormSubmission instance that was created so the record number could be presented to the viewer / tracked.

The FormSubmission instance should then be passed to the render context for the "landing page".

In the same line of thought... it would also be nice if there was a uuid or some sort of meaningless random token on the FormSubmission instance that could be used as a reference value to pass along to the client.

It would also be nice if this token could be appended to the email subject line to prevent mail clients from grouping into one conversation (aka gmail interface)

**Comment by m1kola** [comment]
> It would be nice if the process_form_submission method returned the FormSubmission instance that was created so the record number could be presented to the viewer / tracked.

[`AbstractForm.process_form_submission`](https://github.com/torchbox/wagtail/blob/b37e8ccbcf2d15785a422ba30ab395435ee077d7/wagtail/wagtailforms/models.py#L160) and [`AbstractEmailForm.process_form_submission`](https://github.com/torchbox/wagtail/blob/b37e8ccbcf2d15785a422ba30ab395435ee077d7/wagtail/wagtailforms/models.py#L222) methods now return `FormSubmission` instance. See #2926 for details.

> The FormSubmission instance should then be passed to the render context for the "landing page".

But we still need to pass a `FormSubmission` instance into a template context on a successful form submission.

> In the same line of thought... it would also be nice if there was a uuid or some sort of meaningless random token on the FormSubmission instance that could be used as a reference value to pass along to the client.

You will be able to define your own form submission class once #2617 will be merged.

> It would also be nice if this token could be appended to the email subject line to prevent mail clients from grouping into one conversation (aka gmail interface)

I don't think that we need to change a default behaviour, but in Wagtail 1.7 you will be able to override the `AbstractEmailForm.send_mail` method to define your own send mail logic.

**Comment by lb-** [comment]
Can this be closed? @m1kola

**Comment by m1kola** [comment]
@lb- I think this bit is still not implemented:

> The FormSubmission instance should then be passed to the render context for the "landing page".

See: https://github.com/wagtail/wagtail/blob/e8720c7627b5f92d23502830198f7119f461776d/wagtail/wagtailforms/models.py#L263-L286

But probably, we should create a separate issue for this.

**Comment by lb-** [comment]
@m1kola I can to a PR for that last change with some tests.

**Comment by m1kola** [comment]
That would be great, thanks!

**Comment by lb-** [comment]
Looks like the PRs for #2834 may be able to solve this issue also, I have suggested a few changes to the first PR - #4024

**Comment by strindhaug** [comment]
Is it okay if the form_submission is `None` in preview? 

Is it sensible if the preview creates a synthetic, unsaved, dummy form submission, or is it enough that you can override serve_preview to do this if your landing page have a special need for the form_submission to be filled?

**Comment by lb-** [comment]
I think it would be best to leave form_submisson as None. Adding the mocking logic would not be easy and also as this is a new feature we don't really know if lots of people will use it yet.

**Comment by lb-** [comment]
The last part of this has been resolved in #4024 - landing pages will now get `form_submission` in their context.
