### ISSUE TITLE
ImageChooserBlock default Image name

### ISSUE THREAD

**Issue by Braintelligence** [wagtail/wagtail#2844]
When you use the ImageChooserBlock to upload an image it would be awesome if the name of the image would be set by the name of the uploaded file initially, so you don't need to type in a name for each image if you don't want to or if your image-files are named properly already.

**Comment by caleyshemc** [comment]
Related to this issue, if you upload an image and don't specify a name, the File field clears and the image must be chosen again.

**Comment by gasman** [comment]
Hi @caleyshemc - a fix for this is coming in Wagtail 1.6 (see #92, #2538).

**Comment by maartenkling** [comment]
I checked this, current state is: uploading image in ImageChooserBlock, the Title is required. If not passing title image stays in image field and shows an error in title field so giving title and a new submit works. Having to set a title is still a bit annoying. @gasman what do you think, should inline images require a title?  At /admin/images/  image titles are not needed, and set automatic.
