### ISSUE TITLE
TableBlock is support merge cells？

### ISSUE THREAD

**Issue by bright-pan** [wagtail/wagtail#2846]
HI，@alexgleason 

i use the feature for my project, but i can not merge cells.

how can i fix it?

**Comment by Proper-Job** [comment]
@bright-pan What do you mean, merge cells?  Do you mean [colspan](http://www.w3schools.com/tags/att_td_colspan.asp)?

**Comment by bright-pan** [comment]
@Proper-Job yes， i have not better way to support colspan in TableBlock.

**Comment by kunambi** [comment]
Please add support for rowspan, if possible

**Comment by gasman** [comment]
Closing this as a duplicate of #5503 (which provides some additional detail).
