### ISSUE TITLE
Create a tag for the picture element + support for responsive image sets

### ISSUE THREAD

**Issue by helenb** [wagtail/wagtail#285]
The picture element which allows different sizes of image for different screen resolutions is becoming the widely accepted standard for responsive images, especially as polyfills are now available for it.

Given that wagtail allows resizing of images on the fly by the server it would be nice to see it supporting the picture element by providing a tag for it.

**Comment by elmcrest** [comment]
Any updates here?

**Comment by lb-** [comment]
Merging in notes from related issue #3573 

Link: https://blog.ycombinator.com/how-to-use-responsive-images/

Comment 

> As far as I can tell, <img srcset="" /> is used for "simple" responsive image. <picture> is for a more of an art direction approach (e.g. show a landscape version under certain conditions, portrait under others).
> Why can't Wagtail support both? Start with srcset then expand to picture?

Also worth reading for best practice: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by stuaxo** [comment]
Supporting srcset with 2x 3x 4x would be a great start

https://webkit.org/demos/srcset/

Support seems good

https://www.keycdn.com/blog/responsive-images/

**Comment by stuaxo** [comment]
A manual approach I tried that works in firefox, looked like this -

```
{% image settings.invest.Branding.logo width-176 as logo %}
{% image settings.invest.Branding.logo width-352 as logo_2x %}

      <img src="{{ logo.url }}" width="{{ logo.width }}" height="{{ logo.height }}" srcset="{{ logo_2x.url }} 2x" alt="{{ logo.alt }}" />
```

**Comment by mathiasp** [comment]
Well, the manual aproach is quite painful when you combine picture for art direction and srcset for different device-pixel-ratios. For this use case I'm just building 2 (3?) src and one img tag within the picture, each having three (two?) resolutions via srcset. That's 8 or 9 image vars to declare,
quite a lot of DRY there.

I'm currently looking into modifying the responsive image tag someone posted to also generate src-tags, that could be a first step for my current needs.

**Comment by DanAtShenTech** [comment]
[This article](https://cloudfour.com/thinks/dont-use-picture-most-of-the-time/) raises a point worth considering:  it advocates only using the `<picture>` tag in the art direction use case and says that `srcset` used on the `<img>` tag is a better choice because it allows the browser to choose which image to use based upon user preferences.

**Comment by PetrDlouhy** [comment]
I have achieved srcset in images inside articles by this code:
```python
# image_formats.py
from wagtail.images.formats import Format, register_image_format, unregister_image_format, get_rendition_or_not_found
from django.utils.html import escape


class SrcsetFormat(Format):
    def __init__(self, name, label, classnames, filter_spec, alternative_filter_specs):
        self.name = name
        self.label = label
        self.classnames = classnames
        self.filter_spec = filter_spec
        self.alternative_filter_specs = alternative_filter_specs

    def image_to_html(self, image, alt_text, extra_attributes=''):
        rendition = get_rendition_or_not_found(image, self.filter_spec)

        rendition_srcset = []
        for alternative_filter_spec in self.alternative_filter_specs:
            rendition_srcset.append(get_rendition_or_not_found(image, alternative_filter_spec))

        if self.classnames:
            class_attr = 'class="%s" ' % escape(self.classnames)
        else:
            class_attr = ''

        return '<img %s%ssrc="%s" alt="%s" srcset="%s">' % (
            extra_attributes, class_attr,
            escape(rendition.url), alt_text,
            ", ".join("%s %sw" % (escape(r.url), r.width) for r in rendition_srcset),
        )


unregister_image_format('fullwidth')
register_image_format(
    SrcsetFormat(
        'fullwidth',
        'Full width',
        'richtext-image full_width',
        'max-640x360',
        ['max-640x360', 'max-768x432', 'max-1024x576', 'max-1600x900', 'max-1920x1080'],
    ),
)
```

Fell free to reuse it or include in Wagtail code.

**Comment by ephes** [comment]
Wagtail is a really great CMS and I would love to use it. But since I don't like blurry images so much I've implemented a srcset_image tag which sets the srcset attribute automatically when a width resize rule was given (the other rules like fill, max etc are still to be done). But since I only use width, it works for me now:

[wagtail-srcset](https://github.com/ephes/wagtail_srcset)

**Comment by CVYY39** [comment]
I wanted to leave a comment for future people trying to get high-DPI images from the built-in Draftail editor. I tested and can confirm that PetrDlouhy's code above works fine on Wagtail 2.9 to allow content made with the rich text editor to display as high-DPI / retina / srcset images. You just cut and paste the code into the /sitename/image_formats.py file - no further edits are necessary. 

Note that by default it only works for full width images, not left- or right-aligned. To include left/right-aligned images, you need to add:
`unregister_image_format('left')
register_image_format(
    SrcsetFormat(
        "left",
        "Left-aligned",
        "richtext-image left",
        "max-640x360",
        [
            "max-640x360",
            "max-768x432",
            "max-1024x576",
            "max-1600x900",
            "max-1920x1080",
        ],
    ),
)

unregister_image_format('right')
register_image_format(
    SrcsetFormat(
        "right",
        "Right-aligned",
        "richtext-image right",
        "max-640x360",
        [
            "max-640x360",
            "max-768x432",
            "max-1024x576",
            "max-1600x900",
            "max-1920x1080",
        ],
    ),
)`

**Comment by thibaudcolas** [comment]
Recently [discussed this on Slack](https://wagtailcms.slack.com/archives/C014L7KJH3N/p1595426013383700) (cc @mikemonteith @vsalvino @fabienheureux), summary for future reference,

- This is feeling more relevant than ever due to Safari 14 coming with WebP support in September to November 2020
- Can either be done at the Wagtail level, or with a reverse proxy that automagically does this, nginx or Apache https://www.modpagespeed.com/, Cloudflare Polish https://support.cloudflare.com/hc/en-us/articles/360000607372-Using-Cloudflare-Polish-to-compress-images
- For Wagtail implementations and WebP support, may need to check needed system dependencies (for example optimized Docker images)
- Could be a good opportunity for Wagtail to provide a first- or third-party opinionated, optimized image / picture implementation, so sites can benefit from optimisations without reinventing the wheel.

Sample React implementation from Fabien:

```jsx
        <picture>
          <source
            type="image/webp"
            sizes="(max-width: 600px) 480px, 920px"
            srcSet={`
                ${image.webp.src} 480w,
                ${image.webp2.src} 920w
              `}
          />
          <img
            sizes="(max-width: 600px) 480px, 920px"
            alt="Information image"
            srcSet={`
                ${image.jpg.src} 480w, 
                ${image.jpg2.src} 920w
              `}
            src={image.jpg2.src}
          />
        </picture>
```

Sample Django templates from Mike:

```jinja
{% with sizes="(min-width: 1000px) 420px, (min-width: 768px) 40vw, 100vw" %}
  {% get_images_by_sizes value.image sizes aspect_ratio as images %}
  <img sizes={{ sizes }} srcset="{% for imgae in images %}{{ image.url image.width{% endfor %}"/>
{% endwith %}
```

**Comment by thibaudcolas** [comment]
Tagging this as "Needs design decision" because I think it’d be worth deciding first whether any of this should happen in Wagtail core, or whether we’d rather encourage third-party implementations as done so far.

**Comment by vsalvino** [comment]
My opinionated design would be one of two things:

1) Keep webp support as-is, and let the developer determine how they should handle it.

2) The wagtail `{% image %}` tag could intelligently decide to produce a webp or fallback to a jpg by reading the HTTP `Accept` header on the request. If it contains `image/webp` then produce webp, as this means the browser supports it. It if does not contain that value, then produce a jpg. The `{% image %}` tag could take an argument `webp-fallback` which would produce this behavior, regular `webp` argument would always produce a webp. This behavior could be further extended to new image formats in the future.

Option 2 above has the advantage of continuing to work, even in ancient browsers, as it adheres to older HTML standards (e.g. HTML 4 / XHTML) The problem with a `<picture>` tag is that older browsers do not reliably support it (especially those of us who still need to support IE).

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values

**Comment by gasman** [comment]
I like the idea of using the `Accept` header, but we'd have to be careful about what it means for caching - if there's no clever way to tell front-end caches to store one webp and one non-webp version, the best we could do is tell them to vary on the `Accept` header, which means saving one copy for each distinct Accept header sent by any browser.

**Comment by thibaudcolas** [comment]
I like the simplicity of being able to keep the `{% image %}` tag as-is, but to me it’s more appealing to consider support for `picture` (or `srcset`) so this can be taken further. Sticking with a single `img` tag means only being able to serve a different image based on the request headers , while `picture` or `srcset` let the user agent be in control, based on file formats they support, and device width, and pixel density.

@vsalvino there is no browser support problem with `<picture>`, browsers that don’t support it would just load the `<img>` inside it as usual, with the fallback JPG or PNG image. Same with `srcset` on the img tag, the `src` attribute still is mandatory and used as a fallback. I just tried http://responsiveimages.org/demos/basic-implementation/index.html in IE6 to confirm, working as expected.

**Comment by helenb** [comment]
If we were to keep using the `{% image %}` tag we need to resolve the fact that you can't currently remove the width and height attributes, which should not be included when using `srcset` and `sizes` - see https://github.com/wagtail/wagtail/issues/5289.

**Comment by vsalvino** [comment]
@thibaudcolas good to hear about the picture tag. Seems to be the way to go then!

**Comment by mattlangeman** [comment]
Thanks to @PetrDlouhy for his code above. Here is modification that allows richtext images to use a picture tag with webp support.

```
# image_formats.py
from wagtail.images.formats import Format, register_image_format, unregister_image_format, get_rendition_or_not_found
from django.utils.html import escape

register_image_format(Format('thumbnail', 'Thumbnail', 'richtext-image thumbnail', 'max-120x120'))

class SrcsetFormat(Format):
    def __init__(self, name, label, classnames, filter_spec, alternative_filter_specs, media_filter):
        self.name = name
        self.label = label
        self.classnames = classnames
        self.filter_spec = filter_spec
        self.alternative_filter_specs = alternative_filter_specs
        self.media_filter = media_filter

    def image_to_html(self, image, alt_text, extra_attributes=''):
        default_rendition = get_rendition_or_not_found(image, self.filter_spec)

        rendition_srcset = []
        for alternative_filter_spec in self.alternative_filter_specs:
            rendition_srcset.append(get_rendition_or_not_found(image, alternative_filter_spec))

        if self.classnames:
            class_attr = 'class="%s" ' % escape(self.classnames)
        else:
            class_attr = ''

        html_str = '<picture>'
        for idx, rendition in enumerate(rendition_srcset):
            file_type = ''
            if rendition.file.name.lower()[-5:] == '.webp':
                file_type = 'type="image/webp"'              

            html_str += f'<source srcset="{rendition.url}" {file_type} media="{self.media_filter[idx]}">'
        
        html_str += f'<img class="{class_attr}" src="{default_rendition.url}">'
        html_str += '</picture>'

        return html_str



# An image format that uses a picture tag along with webp and media queries to optimize image size/format
unregister_image_format('fullwidth')
register_image_format(
    SrcsetFormat(
        'fullwidth',
        'Full width',
        'richtext-image full_width',
        'max-1920x1080',
        ['max-640x360|format-webp', 'max-640x360', 'max-768x432|format-webp', 'max-768x432', 'max-1024x576|format-webp', 'max-1024x576', 'max-1600x900|format-webp', 'max-1600x900', 'max-1920x1080|format-webp', 'max-1920x1080'],
        ['(max-width: 640px)', '(max-width: 640px)', '(max-width: 768px)', '(max-width: 768px)', '(max-width: 1024px)', '(max-width: 1024px)', '(max-width: 1600px)', '(max-width: 1600px)', '(min-width: 1601px)', '(min-width: 1601px)'],
    ),
)
```

**Comment by zerolab** [comment]
This is being implemented via https://github.com/wagtail/rfcs/pull/71. And we will hopefully get a PR in the coming months

**Comment by thibaudcolas** [comment]
For anyone interested in this, we’ve implemented `{% picture %}` and `{% srcset_image %}` in #10781, for release in Wagtail 5.2. 

- The picture tag supports multiple image formats and/or multiple image sizes
- The srcset_image tag supports multiple sizes only
- Both tags allow retrieving image renditions in bulk within a template, so you can generate your own `<picture>` or `srcset` image if there is a need.

We have a bit more docs to write still (see #11068), but the implementation is all there, largely as per [RFC 71](https://github.com/wagtail/rfcs/pull/71).
