### ISSUE TITLE
403 when user tries to copy a page to a place where they don't have permissions

### ISSUE THREAD

**Issue by chrxr** [wagtail/wagtail#2867]
Steps to replicate:
- Create a group that has limited page permissions
- Add user to that group
- Try to copy a page so that the new parent page is one that the user does not have permissions to edit.

Result:
- Plain 403 error page

**Comment by gasman** [comment]
Will be fixed by #2666, I believe.

**Comment by Henk-JanVanHasselaar** [comment]
I'll be having a look at this during the Arnhem sprint.

**Comment by gasman** [comment]
Fixed in #3492
