### ISSUE TITLE
Make streamvalue mutable

### ISSUE THREAD

**Issue by fabiommendes** [wagtail/wagtail#2876]
Implement the MutableSequence methods for StreamValue. It would be useful to be able to insert stream blocks programatically without having to recreate the whole stream value object. I am working on an implementation and can submit a pull request later today.

**Comment by gasman** [comment]
I'm a bit wary of making this change - I'll need to think about it some more.

When I designed the StreamField APIs, I imagined the data as always consisting of immutable [value objects](https://en.wikipedia.org/wiki/Value_object), and I'm not sure what the consequences will be if we break that assumption. However, we haven't been rigorous about that for StructBlock and ListBlock values, and that doesn't seem to have caused any problems...

**Comment by fabiommendes** [comment]
+1 for Immutable by default. However, in this case the API for changing a stream value is very fragile. If page.body is a stream value, it breaks in simple operations such as 
```python
page.body = list(page.body)
```
Hence we cannot convert the immutable sequence to a list, change its contents, and save the immutable version back in the end. Changing stream_data directly is also a bad idea since the user has to check if the stream value is lazy or not and insert data accordingly. This is bug-prone and IMHO .stream_data and .is_lazy attributes are just implementation details that the user should not fiddle with.

When inserting new blocks in a stream block, I want to avoid this ugly code:
```python
body = [(blk.block_type, blk.value) for blk in page.body]
body.append(('paragraph', '<p>hello</p>'))
page.body = body
```

**Comment by gasman** [comment]
OK - having thought about this some more, I'm now more comfortable about the idea of making StreamValue mutable. Looking forward to seeing the patch :-)

**Comment by fabiommendes** [comment]
I sent the pull request.

I'm having a bit of trouble running tox and the full test suite in my computer. "make tests" pass, but tox fails even in the environments available in my computer. What is the recommended workflow? Can I rely that CI will catch any problems not present in my computer?

**Comment by gasman** [comment]
Leaving CI to do the full (all-versions) test run is fine. I almost never run tox locally, since it doesn't play well with Vagrant VMs (it tries to create symlinks, which aren't supported by Vagrant shared folders).

**Comment by zerolab** [comment]
The PR is #2886

**Comment by gasman** [comment]
Completed in #6485
