### ISSUE TITLE
Styling - Streamfield blocks editing interface styling

### ISSUE THREAD

**Issue by muhammad-saleh** [wagtail/wagtail#2888]
Dears,
In Wagtail 1.5.3 I created a struct block contains BooleanBlock for example and I noticed that it looks odd:
![image](https://cloud.githubusercontent.com/assets/1510608/17368056/d099a210-5992-11e6-842a-3849af29d0ae.png)
Please note the alignment issue with the label and the checkbox

After looking into why is this happening it seems that you give the labels a padding:
![image](https://cloud.githubusercontent.com/assets/1510608/17368103/012371f4-5993-11e6-8959-21cc15cab26b.png)

And not the form field itself:
![image](https://cloud.githubusercontent.com/assets/1510608/17368123/124595f2-5993-11e6-8f06-4fff99893bf9.png)

Thanks.

**Comment by thibaudcolas** [comment]
This is fixed as of #8921, with field widgets now consistently displaying below their label.
