### ISSUE TITLE
Wagtail forms: wrong styles for filtering form

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#2891]
Styles for submission filtering form are broken: inputs and buttons in header have different height.

<img width="1206" alt="screen shot 2016-08-04 at 16 23 20" src="https://cloud.githubusercontent.com/assets/509198/17403329/e45f0196-5a5f-11e6-86b4-7e81ad9cdfed.png">

**Comment by thijskramer** [comment]
I'm at the Wagtail Space Sprint in Arnhem and I'm starting to work on this!

**Comment by jjanssen** [comment]
Fixed in #3497
