### ISSUE TITLE
Delete focal point

### ISSUE THREAD

**Issue by tobiase** [wagtail/wagtail#2905]
I can't delete focal points.

I thought, maybe I could select a previously saved focal point and delete it with 'DEL', but I can't select previously saved focal points.

**Comment by maartenkling** [comment]
https://github.com/wagtail/wagtail/pull/3487

<img width="484" alt="screen shot 2017-03-23 at 07 55 52" src="https://cloud.githubusercontent.com/assets/946684/24235558/29a9b00e-0f9e-11e7-92a6-df1949826348.png">

**Comment by jjanssen** [comment]
Merged in 270ac66 with PR #3487
