### ISSUE TITLE
Wagtail can make MANY requests to wagtail_site_root_paths

### ISSUE THREAD

**Issue by danni** [wagtail/wagtail#2916]
One site I'm building is making over 80 requests for the cache key `wagtail_site_root_paths`, which I hadn't noticed until I put a proper caching engine in place and suddenly performance actually dropped due to the round trips.

Perhaps replace all calls to `cache.get('wagtail_site_root_paths')` with a memoized result, so that we're making at most 1 request for this key?

**Comment by kaedroho** [comment]
I think the ideal place for this cache would be on the request object so we fetch this key once per request. We, obviously, can't use a global cache for this as that would be very difficult to invalidate across all instances in multi-server environment.

**Comment by danni** [comment]
@kaedroho you're right. Ironically I then proceeded to make exactly this mistake in trying to write a quick fix. It's not obvious to me how to get access to the current request from this depth of the stack, unless you have the request stashed in thread local storage someone ala Flask.

**Comment by gasman** [comment]
Implemented in #3188 (for the `{% pageurl %}` tag specifically, which I think is the only place where it's feasible to access the request object without hacks...)

**Comment by gasman** [comment]
Fixed in #3354
