### ISSUE TITLE
Add an example on how to override the AbstractEmailForm .send_mail method

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#2954]
Would be great to add an example on how to override the `AbstractEmailForm.send_mail` method which was introduced in #2926.

Docs for `wagtail.wagtailforms` can be found [here](http://docs.wagtail.io/en/v1.6/reference/contrib/forms.html).

(cc @tleguijt)

**Comment by lb-** [comment]
@m1kola 

I have put together a blog post that explains the process and if you feel it is helpful I could try to update the docs accordingly. Either way - I hope this post helps future people who come across this issue.

https://posts-by.lb.ee/dev-wagtail-extending-the-functionality-of-email-forms-232c8469ac97

cc @tleguijt

**Comment by thibaudcolas** [comment]
@lb- Very cool! I've added your post to https://github.com/springload/awesome-wagtail, hope that's ok.

**Comment by lb-** [comment]
@thibaudcolas no problems, glad that helps some people.

**Comment by gasman** [comment]
Completed in #4005
