### ISSUE TITLE
Add select multiple for dropdown form field

### ISSUE THREAD

**Issue by dwasyl** [wagtail/wagtail#2960]
It would be very helpful to have either the ability to toggle the drop down list into a multi-select, or another form element representing multi-select.

Some forms I'm trying to create need multi-selects (and have too many choices to be represented as checkboxes). I ended up doing this manually, but it would be a helpful addition.

**Comment by timmysmalls** [comment]
@dwasyl I agree. I know there's a component out there in a different repository, but why not just use the existing chooserpanels? What if you want to add several snippets/pages/images or some such in an association table? You already have a great interface to deal with this. For now it just works exclusively with one to many and one to one relationships. I think this is related https://github.com/wagtail/wagtail/issues/2203. It discusses a workaround of placing a chooserpanel in an inlinepanel. Imo the multi select widgets are not scalable enough out of the box to work with large sets of options. The Chooser Panels, however, are very useful for this. So I'd like to suggest allowing users to take advantage of the chooser panels in many to many relations like they can in regular foreign key relationships. Especially seen as how the bulk of the work (the chooser panels themselves) are already present in the CMS.

**Comment by gasman** [comment]
@timmysmalls If I'm reading correctly, this issue is about forms created with the wagtail.contrib.forms form builder, not forms within the Wagtail admin.

**Comment by zerolab** [comment]
I believe #3020 solved it for forms, so it could be closed?

**Comment by gasman** [comment]
@zerolab Ah, good spot!
