### ISSUE TITLE
Elasticsearch: Unable to assign different boost values for same-named fields

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#2968]
The following definition is valid for Elasticsearch 1.*, but invalid for 2.*:

``` python
    search_fields = Page.search_fields + [
        index.SearchField('title', partial_match=True, boost=10),
        index.SearchField('intro'),
        index.SearchField('body'),
    ]
```

With Elasticsearch 2 it causes the following error:

> Mapper for [title] conflicts with existing mapping in other types:\n[mapper [title] has different [analyzer], mapper [title] is used by multiple types. Set update_all_types to true to update [boost] across all types.

I think we need to mention it somehow in documentation (maybe in the "Upgrade considerations" section?).

**Important!** The same issue can be reproduced with `wagtail.wagtailadmin.taggable.TagSearchable`. This class is deprecated, but will be removed only in Wagtail 1.8. That's why I marked this issue as "Release blocker".

Refs:
- #2570
- [Conflicts between fields in different types](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-put-mapping.html#merging-conflicts)

(cc @kaedroho)

**Comment by kaedroho** [comment]
To solve this, we would have to add the boosting manually to each document while indexing them instead of on the mapping. It's really annoying how Elasticsearch have added this seemingly artificial restriction in as the boost is stored on a per document-field basis anyway...

It would be better if we could perform field-boosting at query time as this would be faster and give more accurate results but would be trickier to implement.

**Comment by kaedroho** [comment]
> To solve this, we would have to add the boosting manually to each document while indexing them instead of on the mapping

I can't find a way of doing this, looks like query time boosting may be the way to go

**Comment by kaedroho** [comment]
One thing that might make implementing the query-time boost simpler could be to split the _all field into four separate fields for different rank levels. When indexing, each field is indexed twice, once with the usual field name and again in the global field that has the closest rank value.

When querying "all" fields, we query these four fields together setting the rank on the query.

This is basically how PostgreSQL FTS does ranking so restricting Wagtail to four levels of ranking should make it easier to integrate with that.

For example, the mapping of a page could be as follows:

```
{
    "properties" {
        "rank_a": {"type": "string"},
        "rank_b": {"type": "string"},
        "rank_c": {"type": "string"},
        "rank_d": {"type": "string"},
        "title": {"type": "string", "copy_to": "rank_a"},
        "body": {"type": "string", "copy_to": "rank_b"},
        "unimportant_field": {"type": "string", "copy_to": "rank_d"},
    }
}
```

When querying all pages, we only query the ``rank_*`` fields as we are not aware of any specific fields for all pages:

```
{
    "multi_match" : {
        "query": "hello world", 
        "fields": ["rank_a^1.0", "rank_b^0.7", "rank_c^0.5", "rank_d^0.1"] 
    }
}
```

This solves the problem with clashing boosts, it removes the need for index-time boosting (which makes field-length norms more accurate) and it also simplifies the ranking in Wagtail enough to make it fit much better with Postgres FTS.

**Comment by gasman** [comment]
Hi,
We need a resolution on this before we can release 1.7 - this might be fixing the issue directly, noting it in the documentation, or simply reclassifying it as not a release blocker (with appropriate reasoning).

If there's no progress here the only other option I can see is to remove ElasticSearch 2 support from the 1.7 feature list, which obviously I'd like to avoid doing...

**Comment by tomdyson** [comment]
> While obviously not as good as fixing it properly, I think that would be sufficient to make this not a release blocker

+1

**Comment by kaedroho** [comment]
> ...it seems to me (unless I'm getting the wrong end of the stick) that we can make the ES2 behaviour no more broken than ES1 by passing update_all_types=True on the call to put_mapping. While obviously not as good as fixing it properly, I think that would be sufficient to make this not a release blocker. Does that sound like a plan?

+1

**Comment by gasman** [comment]
`update_all_types=True` workaround added in #3050. Have updated the title / milestone of this issue to cover the 'proper' fix.

**Comment by kaedroho** [comment]
This issue only affects ES1, which has been EOL since Janurary. We have good support for ES2 and ES5. Resolving this issue isn't trivial so I think we should spend our time solving other search issues. Those who are affected by this issue should upgrade Elasticsearch.
