### ISSUE TITLE
Using commas in Checkbox option text

### ISSUE THREAD

**Issue by cheluis** [wagtail/wagtail#3001]
When building a form with form-builder, whats the workaround for using a comma inside one option's text, lets say, for a "Accept conditions" checkbox, there is usually a long text which may include commas. But if commas are used, they are taken as a new options, which is wrong.

**Comment by BertrandBordage** [comment]
As part of the Wagtail’s first Kickstarter campaign, I’m working on this!
https://www.kickstarter.com/projects/noripyt/wagtails-first-hatch

**Comment by mjfinney** [comment]
This is the workaround I came up with for dealing with commas in choices. By subclassing `FormBuilder` and splitting on newlines instead of commas. You can also separate value and label with a pipe character ( | ). If no newline is detected it falls back to the original behavior of splitting on comma.

``` python
class CustomFormBuilder(FormBuilder):

    def format_choices(self, field):
        if '\n' in field.choices:
            choice_list = field.choices.split('\r\n')
            choices = []
            for x in choice_list:
                if '|' in x:
                    value,label = x.split('|')
                    choices.append((value,label))
                else:
                    choices = map(
                        lambda x: (x.strip(), x.strip()),
                        choice_list
                    )
        else:
            # fallback on default wagtail way
            choices = map(
                lambda x: (x.strip(), x.strip()),
                field.choices.split(',')
            )

        return choices

    def create_checkboxes_field(self, field, options):
        options['choices'] = self.format_choices(field)
        options['initial'] = [x.strip() for x in field.default_value.split(',')]
        return forms.MultipleChoiceField(
            widget=forms.CheckboxSelectMultiple, **options
        )

    def create_dropdown_field(self, field, options):
        options['choices'] = self.format_choices(field)
        return forms.ChoiceField(**options)

    def create_multiselect_field(self, field, options):
        options['choices'] = self.format_choices(field)
        return forms.MultipleChoiceField(**options)

    def create_radio_field(self, field, options):
        options['choices'] = self.format_choices(field)
        return forms.ChoiceField(widget=forms.RadioSelect, **options)

```

**Comment by lb-** [comment]
I think the newline approach could be good, means this field is a text area instead of a single line.
However, we need to think of existing implementations that use commas.

The backwards compatible approach would be to allow both to exist (as per the implementation above).

Marking this as a good first issue.

**Comment by amajai** [comment]
@lb- Started working on it. Should I include the feature of separating the value and label with a pipe character?

**Comment by amajai** [comment]
Nevermind. I'll just focus on the newline approach only.

**Comment by lb-** [comment]
@amajai good call, newline only is a good way to go for now. We can always add more complexity if needed later. Plus it keeps the scope of the PR simpler. 

Remember to add docs, unit tests please.
