### ISSUE TITLE
Wagtail does not validate passwords

### ISSUE THREAD

**Issue by BertrandBordage** [wagtail/wagtail#3005]
In Django 1.9, [a nice system of password validation](https://docs.djangoproject.com/en/1.10/topics/auth/passwords/#module-django.contrib.auth.password_validation) was at last added.

Unfortunately, the password strength is not checked in the `user.set_password` method, maybe for backwards-compatibility reasons. This means we need to manually call [`django.contrib.auth.password_validation.validate_password`](https://docs.djangoproject.com/en/1.10/topics/auth/passwords/#django.contrib.auth.password_validation.validate_password) each time we want to change a password.

Currently, Wagtail is not validating passwords in its back office. A call to `validate_password` should be added to `wagtail.wagtailusers.forms.UserCreationForm` and `UserEditForm`.

Since the current version of Wagtail – 1.6.x – also supports Django 1.8, this will either require to create a small compatibility code, or to wait for a release dropping Django 1.8 support. IMHO I think we should do it now, because it’s misleading: when you define `AUTH_PASSWORD_VALIDATORS` you don’t even think it will not be respected by Wagtail and you generally assume such settings will work without testing manually.

I can make a pull request.

**Comment by gasman** [comment]
This sounds like a good idea to me. I agree that we should make the change now - we have `if django.VERSION >= (1, 9)` checks elsewhere in the code, so there's no harm in adding another.

**Comment by BertrandBordage** [comment]
OK, I’m preparing a pull request.

**Comment by gasman** [comment]
Implemented in #3007
