### ISSUE TITLE
Deleting page from usage view sends user back to wrong place

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#3010]
### Issue Summary

When you delete a page from the page type usage view, you are sent back to the explorer view of the parent page instead of the usage view
### Steps to Reproduce
1. Click "add subpage" somewhere, taking you to the "choose a page type" page
2. On the right hand side, click any of the "pages that use type X" links (if the one you clicked on has no pages, find another)
3. Now delete one of the pages
4. You should now be redirected to the wrong place

I expected to be taken back to the page usage view
### Technical details
- Python version: 2.7
- Django version: 1.9.9
- Wagtail version: 1.6.2
- Browser version: Firefox 46.0.1

**Comment by ramonakira** [comment]
I've looked into it and there's some things of note for this issue:

1) It's not only applicable to the delete action, but also for a few other possible actions,
2) After reviewing the code it seems to me that we need to pass 'next' using GET, for the actions that are created using a hook I don't see a way of getting to the request so I don't see a way to pass the current page.

How should we proceed?

**Comment by Patil2099** [comment]
@kaedroho Can I work on this issue?

**Comment by gasman** [comment]
@Patil2099 Yes, definitely - no need to ask for permission :-)

**Comment by lb-** [comment]
Merged in via #5764
