### ISSUE TITLE
Large number of SQL queries generated on the Group edit page

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#3015]
As reported here: https://groups.google.com/d/msg/wagtail/dDpi6mup_j4/C9ZDmx11AAAJ

The new logic for permission checkboxes in 1.6.2 (#2966) is apparently resulting in a large number of SQL queries. An initial look through the logs suggests that this is caused by an unusually large number of ContentType records in the database, although the [list of models](https://groups.google.com/d/msg/wagtail/dDpi6mup_j4/H-VXT282AgAJ) doesn't seem particularly out-of-the-ordinary.

**Comment by kaedroho** [comment]
> An initial look through the logs suggests that this is caused by an unusually large number of ContentType records in the database

This is quite common if you run migrations with ``manage.py migrate --noinput`` as this doesn't clean up stale ``ContentType`` records of deleted or renamed models.

**Comment by gasman** [comment]
Fixed in #3067
