### ISSUE TITLE
Feature request: bundled live-reload for front-end tooling

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#3022]
When working on websites, I nearly always use a tool called [Browsersync](https://www.browsersync.io/) to speed up the development process. It does the following:
- "Live-reloading" – it watches your files and reloads the pages when you change one (and for CSS it can directly inject the new styles into the page without even reloading the page, very convenient). This speeds up front-end work tremendously.
- Synchronised browsing – if you have the site open in multiple tabs / browsers / devices, it will do its best to reproduce your actions across all of them. Very convenient when doing cross-browser tests.
- It also includes a bunch of useful development aids like weinre for remote debugging (debug the site on an iPad from the computer) and simulated network throttling.

There are multiple ways of using it. The simplest is to install its CLI (`npm install -g browser-sync`), and the most common is to have it more tightly integrated with other build tools (gulp, webpack, etc).

Right now I am using it to develop on Wagtail with the following command (you can run this from the `wagtail` root to try this out on the admin UI:

```
# Start browser-sync, proxying the server within the Vagrant box, watching the admin's templates, CSS and JS files to reload the browser when they change.
browser-sync start --proxy=localhost:8000 --files="wagtail/wagtailadmin/templates/**/*.html, wagtail/wagtailadmin/static/wagtailadmin/css/**/*.css, wagtail/wagtailadmin/static/wagtailadmin/js/**/*.js"
```

Now this works for me but this isn't as nice as having it integrated with the rest of the dev toolchain (one more tool to start, two watchers running at once, watches the output files instead of the ones that are actually changing, etc). If I was to propose a PR where `browser-sync` is added as a `devDependency`, and more tightly integrated with webpack and gulp, would this be of interest?

Here are the drawbacks I'm aware of:
- It's one more npm dependencies, with its own dependencies, some of them native and requiring compilation (for the file watching), so will increase the `npm install` time.
- It's not the bleeding edge in fancy hot module reloading, there are fancier (more recent) ways to auto-live-hot-reload React things. But I'm staying away from them for now.

**Comment by thibaudcolas** [comment]
NB: it's not _that much_ work to put this in place, so if there is sufficient interest in the idea I'll just make a PR so people can try it out.

**Comment by thibaudcolas** [comment]
Closing since there doesn't seem to be much interest. Will revisit another time 🤓.

**Comment by antonzy** [comment]
+1
