### ISSUE TITLE
[FrontCacheInvalidator] 'purge_page_from_cache' is not purging all language urls

### ISSUE THREAD

**Issue by pyMan** [wagtail/wagtail#3027]
### Issue Summary

In a multilingual environment (that is with USE_I18N setted at True and using i18n_patterns in urls.py to serve different languages from different urls) the purge_page_from_cache utility function is purging only the url with the current language used when publishing (editing) a page.
### Steps to Reproduce
1. Set more than one language in settings.LANGUAGES
2. Set USE_I18N True
3. Use i18n_patterns in urls.py ([see here](http://docs.wagtail.io/en/v1.6/advanced_topics/i18n/index.html#serving-different-languages-from-different-urls))
4. Set up a reverse proxy ([see here](http://docs.wagtail.io/en/v1.6.2/reference/contrib/frontendcache.html))
5. Create or edit a page and publish it. Then check the purged urls in the logger wagtail.frontendcache. You will see only the url with the current language instead an url for each managed language.
### Technical details

Wagtail version: 1.6.2
### Pull request

I am sorry, I opened this issue only after the pull request I created to improve the invalidator function. #3024

**Comment by gasman** [comment]
Completed in #3971
