### ISSUE TITLE
'Parent' link in page chooser search should not navigate away

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#3085]
### Issue Summary

The 'Parent' link in search results inside the page chooser navigates away to the explorer, which isn't a very sensible thing to do within a chooser modal.
### Steps to Reproduce
1. Edit a page
2. Within a rich text area, open the link chooser
3. Search for something with at least one result
4. Click on the 'parent' link

Expected: It should switch to the explore view _within the page chooser_, so that you're choosing from the children of that page (including the search result you were just looking at)
Actual: It leaves the page edit interface and takes you to that page in the explorer
### Technical details
- Python version: 3.4.3
- Django version: 1.8.15
- Wagtail version: 1.8a0
- Browser version: Chrome 53.0.2785.143

**Comment by lb-** [comment]
Referencing PR #3120 which was submitted to fix this issue but has status 'needs work'.

**Comment by gasman** [comment]
Fixed in #5011
