### ISSUE TITLE
snippet for a model with custom primary key

### ISSUE THREAD

**Issue by Eraldo** [wagtail/wagtail#3104]
### Issue Summary

Snippets cannot yet handle models with custom primary keys.
### Steps to Reproduce
1. Create a model using a custom primary key. (Thus there is no 'id' field anymore.)
2. Register that model as a snippet. (@register_snippet)
3. Got to wagtail cms backend and check out the snippet menu of the registerd snippet.
4. An error is displayed in DEBUG mode.

I expected a listing of the snippet models, further being able to edit the respective model instances.
### Technical details

Source:
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailsnippets/models.py#L25
There might be more places where this is an issue.

Error:
`Reverse for 'edit' with arguments '('myapp', 'mymodel', '')' and keyword arguments '{}' not found. 1 pattern(s) tried: ['cms/snippets/(\\w+)/(\\w+)/(\\d+)/$']`
- Python version: Python 3.5.1.
- Django version: Django (1.9.9).
- Wagtail version: wagtail (1.7)
- Browser version: Chrome 54.0.2840.71 (64-bit).

Regards,
Eraldo

**Comment by evert-smit** [comment]
Thanks for the summary @Eraldo.

@gasman I'd like to see if I could make a contribution to Wagtail by changing this behaviour. Is there anything I need to keep in mind other than the changes I would make to this particular part of the codebase? I'd like to get the solution right, to avoid sending an unstructurized pull request.

**Comment by gasman** [comment]
Thanks @evert-smit! I think the main thing to watch out for with non-numeric IDs is that they may contain characters that aren't valid in URLs, and so you'll need to ensure that they're escaped when building the URL and un-escaped at the other end. (I think Django's admin package has some code you can borrow...)

Other than that, just ensure that your changes are covered by tests (you'll probably want to add a new model definition to https://github.com/wagtail/wagtail/blob/master/wagtail/tests/snippets/models.py) and follow the [coding guidelines](http://docs.wagtail.io/en/v1.12/contributing/python_guidelines.html) - good luck! :-)

**Comment by saevarom** [comment]
At my company we're currently working on a project with custom primary keys. I could work on this on company time, but I'm wondering if @evert-smit has an ongoing solution that I could contribute to? If not, or if it's inactive or in other ways not available, I'm going to start working on a PR for this.

**Comment by evert-smit** [comment]
That would be fine - I planned working on this but ended up going in a
different direction and didn’t have time to continue with a PR.
