### ISSUE TITLE
Extra Paragraph Tags in Rich Text

### ISSUE THREAD

**Issue by harrislapiroff** [wagtail/wagtail#3111]
### Issue Summary

Sometimes extra paragraph tags appear in the rendering of rich text fields, particularly at the beginning of the field. The problem is twofold: 1. that those tags are appearing at all, 2. that they aren't visible (and therefore aren't obviously editable) when editing pages with rich text fields.
### Steps to Reproduce

I haven't nailed down the exact scenarios in which this happens. I suspect it has something to do with copying and pasting content into rich text fields (which, I know, is the perpetual source of bugs for rich text editing). I'll try to track down a specific reproducible scenario a little later on.
### Technical details
- Python version: 3.5.2
- Django version: 1.9.9
- Wagtail version: 1.6.2
- Browser version: Not sure which browsers this does or doesn't appear in yet. Will update later.

**Comment by rafaponieman** [comment]
Also experiencing this issue, particularly on a RichText Streamfield field. One way I could reproduce it is by pasting some plain text (made plain by pasting onto plain text editor and copying again), and then formatting it into a bullet list. After saving, empty paragraphs appear before and after the list.

My workaround is to copy into plain text editor, delete the RichTextField, create a new one and copy line by line into a bullet list.

**Comment by lb-** [comment]
For reference, the current rich text editor will be replaced with Draftail (new editor) in a future release. See #2409

**Comment by thibaudcolas** [comment]
Related: #559.

This should be solved when switching to Draftail, where there is no direct relation between the formatting of what is entered into the editor and the formatting output on the site's frontend. Still present for Hallo though.
