### ISSUE TITLE
Support for different types of badges in admin tabs

### ISSUE THREAD

**Issue by MechanisM** [wagtail/wagtail#3114]
This is not important, but good to have. Currently wagtail offers only error badge for tabs, but what if I want to indicate something with help of badges? To show 4 processes, I've added error 4 badge, but it is not correct, because there's none any errors.. I think it would be great to have other kinds of badges for tabs. I know I can indicate number in tab name, but I found it more noticeable to show badge instead.
![image](https://cloud.githubusercontent.com/assets/121781/19736447/efe06e30-9bb7-11e6-8b70-417e17f54ffb.png)
Of course I know I can attach admin css and do it, but would be nice to have it out of the box.

**Comment by thibaudcolas** [comment]
It’s not clear to us how this would fit with Wagtail functionality. @MechanisM could you share further examples of the use cases where this would help?
