### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one Filter -- it returned 2!

### ISSUE THREAD

**Issue by husamalfarra** [wagtail/wagtail#312]
Hi
 after I follow the installation instructions
git clone https://github.com/torchbox/wagtaildemo.git
cd wagtaildemo
pip install -r requirements/dev.txt
createdb -Upostgres wagtaildemo
./manage.py syncdb
./manage.py migrate
./manage.py runserver

I got an error

MultipleObjectsReturned: get() returned more than one Filter -- it returned 2!
[07/Jun/2014 19:42:31] "GET / HTTP/1.1" 500 211836
any idea

**Comment by AirnFire** [comment]
proto.teacher.MultipleObjectsReturned: get() returned more than one TeacherReport -- it returned 2!

i do have same issue, i'm using this code to write data into a django model.

lt, created = TeacherReport.objects.get_or_create(
            Teacher_ID=teacher[i],
        )
        if not created:
            lt.Teacher_Name = tname[i]
       lt.save()

Can anyone tell how to resolve it?

**Comment by allcaps** [comment]
@AirnFire , it is not likely that your error happens because of a bug in Wagtail. Best to ask support in one of our support channels.

https://docs.wagtail.io/en/stable/support.html

I think Slack gives the fastest feedback.

**Comment by abdurrehmandaudi** [comment]
**don't :-**  xyz = Blogs.objects.get(user_id=id)
**use:-** xyz = Blogs.objects.all().filter(user_id=id)
