### ISSUE TITLE
Embedded video urls get doubled escaped on save actions

### ISSUE THREAD

**Issue by dpratter** [wagtail/wagtail#3126]
### Issue Summary

When embedding a video url with at least one Ampersand character **"&"** in a **RichTextBlock** inside a **StreamField**, every **"&"** char inside the url get's replaced with **"&amp;"** every time a new revision is saved.

Example: 
Each time a new draft is saved the following transformation happens:
1. https://www.youtube.com/watch?v=uKpfO331DY4&t=10
2. https://www.youtube.com/watch?v=uKpfO331DY4&amp;t=10
3. https://www.youtube.com/watch?v=uKpfO331DY4&amp;amp;t=10
4. https://www.youtube.com/watch?v=uKpfO331DY4&amp;amp;amp;t=10

This does not only make the url uglier, it also increases the url's character length. 

I could reproduce this with two different setups:

1: An older production system I cannot upgrade to a newer version of wagtail

- wagtail==1.5.3
- django==1.8.14
- psql (PostgreSQL) 9.3.14

In this setup, it is impossible to enter a Page's edit page if an embedded video url exceeded a 200 chars length, causing a **DataError** Exception to be thrown:

`DataError: value too long for type character varying(200)`

2: Clean wagtail installation

- wagtail==1.7
- django==1.10.1
- sqlite db

The **DataError** Exception will not be thrown in this setup but the url still grows each time you hit the save button.

### Steps to Reproduce

1. Embed a video with at least to query params which are separated with a "&" char (like https://www.youtube.com/watch?v=uKpfO331DY4&t=10) in RichtTextBlock in Streamfield.
2. Save draft
3. Check url

**Comment by gasman** [comment]
Fixed in #4060
