### ISSUE TITLE
EditHandlers (and Panels) with request-object from wagtailadmin views

### ISSUE THREAD

**Issue by bobslee** [wagtail/wagtail#3129]
Having the **request** object available in **editHandler** object would provide some benefits like accessing the **user** object and it's permissions (to check) etc.
(Which could also be passed throught the EditHandler template)

AFAIK this could be easily implemented in several functions in `wagtailadmin/views/pages.py`, which already get the *request* (object) as function argument and instantiate such an EditHandler object. For example the *edit* function.

So in the `wagtailadmin/views/pages.py` on instantiation of an EditHandler:

```
def edit(request, page_id):
   ...
   edit_handler = edit_handler_class(instance=page, form=form, request=request)
   ...
```

I'll send a PR for this later.

**Comment by BertrandBordage** [comment]
Already fixed by #4382 that’s in 2.1.

**Comment by ideallical** [comment]
Hmm it's still `edit_handler = page_class.get_edit_handler()`
https://github.com/wagtail/wagtail/blob/master/wagtail/admin/views/pages.py#L202

Should this PR make it possible to dynamically render a form with edit_handlers based on the instance (or request) ?

**Comment by ideallical** [comment]
If you're interested, this is my question on SO:
https://stackoverflow.com/questions/50934921/is-it-possible-to-set-edit-handlers-in-wagtail-dynamically
