### ISSUE TITLE
Rich text field and PageChooserBlock should use 'specific' URLs

### ISSUE THREAD

**Issue by dwasyl** [wagtail/wagtail#3164]
I have a site that's implemented `wagtail 1.7` with `wagtail-modeltransation`, but when I use inline PageChooser links in a RichTextBlock I'm unable to get the link for the page in other languages. `wagtail-modeltranslation` generates page URLs by overriding the `.url` method on the Page models configured for translation. This means that the only way to get the right links to use `.specific.url` rather than just `.url` on the generic Page model.

Would it cause any issues to make the `PageLinkHandler` in `rich_text.py` or the `PageChooserBlock` in `blocks/field_block.py` use `value.specific.url` when they render the `value.url`? This would be an easy fix for the problem and better enable the use of translated Page models.

**Comment by gasman** [comment]
Hi @dwasyl - yes, I think it would be appropriate to use `specific` in both PageLinkHandler and PageChooserBlock. Thanks for the report!

**Comment by dwasyl** [comment]
Okay great, thanks @gasman. Is this something you can just include in another patch or would a PR be helpful?

**Comment by gasman** [comment]
A PR would definitely be helpful, thanks!

**Comment by gasman** [comment]
Fixed in #3425 / #3494
