### ISSUE TITLE
Need to tighten up access to the wagtailadmin.pages.view_draft view

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#317]
Currently any user with a wagtailadmin login can view the latest draft of any page just by passing its ID to the view_draft view - no further permission checks are employed. In the default install this is no big deal, because a standard editor has edit access to the full site anyhow - but on sites with more fine-grained user roles (particularly as we implement and employ more features concerned with "keeping information under wraps", such as front-end permissions and scheduled publishing), there is a risk of information being leaked.

We don't yet have a concept of 'view permission' that applies to users, so we need to figure out what permission rules would be appropriate here. I _think_ requiring either edit or publish permission on the page would make sense - I can't think of any other kinds of workflow that would depend on being able to view the draft version.

**Comment by zerolab** [comment]
Agreed to require edit permission to access view_draft.

**Comment by khink** [comment]
starting work

**Comment by khink** [comment]
Using the 'change_page' permission for this. I couldn't find  a 'publish' permission?

**Comment by gasman** [comment]
@khink Page permissions are based on the [`GroupPagePermission` model in wagtailcore](https://github.com/wagtail/wagtail/blob/9257a4a1dc556b2c9b333f26f36ea41229dff755/wagtail/wagtailcore/models.py#L1533) rather than Django's own permission model from `django.contrib.auth` (because the Django permission model wouldn't allow assigning different permissions for different parts of the page tree).

Your best bet is to look at how the other views in [wagtailadmin/views/pages.py](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailadmin/views/pages.py) do permission checks - there's a `page.permissions_for_user` helper method that returns an object you can query for `can_edit()`, `can_publish()` etc.

**Comment by gasman** [comment]
Fixed in #3474
