### ISSUE TITLE
Setting for number of shards on Elasticsearch index

### ISSUE THREAD

**Issue by nikolaik** [wagtail/wagtail#3172]
I have an issue using Wagtail with the Elasticsearch service [Bonsai](https://bonsai.io/) on their free tier ([references in the Wagtail docs](http://docs.wagtail.io/en/v1.7/topics/search/backends.html#elasticsearch-backend)).

After running the `update_index` management command it creates 3 indices each creating multiple shards, which in turn overflows the free tier limit.

I'm thinking this could be solved by using the `number_of_shards` setting [[1](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-create-index.html#indices-create-index)] on the create index call in [ElasticsearchIndex.put](https://github.com/torchbox/wagtail/blob/4c0608cbb79aac349c1b80dbdc9fddba8dee53e7/wagtail/wagtailsearch/backends/elasticsearch.py#L470). Would have to merge the settings in the class with the django settings.

I would really like to test using the free tier on Bonsai before deploying. If this seems like a good idea, I'll try to prepare a PR.

**Comment by kaedroho** [comment]
@nikolaik Thanks for flagging this!

I think https://github.com/torchbox/wagtail/pull/3036 plus some additional documentation would solve this

**Comment by gasman** [comment]
Fixed in #3267.
