### ISSUE TITLE
Uploadable user avatars falling back to Gravatar.

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#319]
Gravatar has become considerably less slick since Wordpress became a requirement. Use of gravatar should really only be a fall back anyway.
- Avatars should be uploaded direct to Wagtail, falling back on Gravatar, then none at all.
- Other services could be considered but ideally we don't want monsterid, wavatar, identicon or any other non-photographic avatars that would detract too much aesthetically.
- Should be stored as part of a "user profile" (see: https://github.com/torchbox/wagtail/issues/248)
- Should be prompted on first login or similar (see: https://github.com/torchbox/wagtail/issues/575)

Somewhat dependent on #755

**Comment by chimeno** [comment]
I'm agree that any third-service (gravatar in this case) should be optional and not the first (and unique) option.
Is this something you would still like to have in core?
I could make a PR with my approach in that case.

**Comment by gasman** [comment]
@chimeno Yes please!
