### ISSUE TITLE
Feature Request: get_settings as assignment tag

### ISSUE THREAD

**Issue by harrislapiroff** [wagtail/wagtail#3213]
It would be really great (and really _explicit_) to make `{% get_settings %}` into an assignment tag that could be used like `{% get_settings as my_settings_var %}`. It's a reasonably common pattern to assign variables from `settings.py` to a template variable called `settings` and it'd be nice to have an easy way not to conflict with that. I think it would also make the tag's behavior a lot clearer to anyone who runs into it and isn't familiar with `wagtail.contrib.settings`.

Backward compatibility could be kept by continuing to assign it to `settings` as long as `as varname` was not provided.

If this is approved, I'd be happy to make a pull request.

**Comment by gasman** [comment]
Sounds like a good idea to me! (Any objections @timheap?)

**Comment by timheap** [comment]
Sounds sensible to me

**Comment by solarissmoke** [comment]
Fixed in 0daae4a
