### ISSUE TITLE
Editing links on images on RichTextField

### ISSUE THREAD

**Issue by rafaponieman** [wagtail/wagtail#3214]
When a link is added on an image on a RichTextField it can't be changed or removed. 

### Steps to Reproduce

Edit any Page that has a RichTextField. On that field, insert an image. Select the image and add a link. O Firefox, images are selectable and resizable, on Chrome they aren't (I think this is a known browser glitch). So, on Firefox I just click on the image, the resize arrows show up and then click on link and add any link. On Chrome, I can only select images using the cursor as if they were text, then I also add link.

On both browsers, the link hover tooltip doesn't appear to be correctly positioned in relation to the image, however, the actual issue is when you want to modify or remove that link, as it doesn't seem to be possible, or it's not working correctly. It seems like sometimes it changes but when the page is published its not actually changed, or sometimes when the image is selected (either by clicking it on Firefox or selecting it as a paragraph on Chrome), the link icon on the editor itself doesn't get highlighted, so there isn't a way to remove or change a link that has been applied.

### Technical details

* Python version: 2.7.8
* Django version: 1.9.10
* Wagtail version: 1.7
* Chrome 55, Firefox 50
* Platform: Kubuntu 16.10

**Comment by gasman** [comment]
Confirmed on both Chrome and Firefox. (However, I think this is more of a browser limitation than something we can fix in Wagtail - browsers simply aren't very good at handling images inside editable HTML areas. I'd definitely encourage using [StreamField](http://docs.wagtail.io/en/v1.7/topics/streamfield.html) instead, which would allow you to define "image with link" as a well-defined content element in its own right, rather than having to assemble one by hand...)

**Comment by rafaponieman** [comment]
That's true... even CKEditor only supports image resizing by corner handlebars on FF (it's almost 2017!!). Anyway, maybe a basic idea that could evolve into an actual solution could be displaying a link icon somewhere before or on top of the image itself.

**Comment by thibaudcolas** [comment]
Adding a link on an image is a common limitation of rich text editors built with `contenteditable`. We are replacing Hallo with a new editor, where this won't work either, but the behavior will be more reliable.

I would suggest using Streamfield to structure content if this is a common use case on your site.
