### ISSUE TITLE
Wagtailadmin wagtailhooks untranslated string. 

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#3219]
### Issue Summary
Wagtailadmin wagtailhooks contains a litle error which causes an untranslated string. 

### Steps to Reproduce
In settings choose another language then 'en'
Login to wagtail and choose the homepage in navigator.
Hover over ‘add child page’ (this one is translated)
Look at the link title (isn’t translated)

### Technical details
* Wagtail version: 2.7

### Solution

wagtailadmin._wagtail_hooks.py
method page_listing_buttons()
    
- attrs={'title': _("Add a child page to '{0}' ".format(page.title))}

+ attrs={'title': _("Add a child page to '{0}' ").format(page.title))}

Cheers,

Robert

**Comment by gasman** [comment]
Thanks @robslotboom! Fixed in #3220.
