### ISSUE TITLE
Page ID>1000 ValueError

### ISSUE THREAD

**Issue by maciejfic** [wagtail/wagtail#3227]
### Issue Summary
Exception: 
> ValueError: invalid literal for int() with base 10: '1,036'

There is a bug with page id greater than 1000 and localization with Page chooser block. It looks like issue occurs in two files:
- wagtail/wagtailadmin/templates/wagtailadmin/pages/listing/_page_title_choose.html
- wagtail/wagtailsearch/templates/wagtailsearch/queries/chooser/results.html (unrelated, but can occur here)

### Steps to Reproduce

1. Have page with ID greater than 1000 and localization turned on
2. Try to select this page with PageChooserPanel and save

### Technical details

One way to resolve it will be to change {{ page.id }} with {{ page.id | unlocalize }}

**Comment by gasman** [comment]
Thanks @maciejfic!

Related: #2699 / 674af5586b4eb4488457fd6762e24bff7b11d69f . At the time I made that fix, I wasn't aware of the `unlocalize` filter - it may well be that we can use `unlocalize` there too, and eliminate the custom `no_thousand_separator` filter.

**Comment by gasman** [comment]
Fixed in #3478
