### ISSUE TITLE
UX issues on form submission page

### ISSUE THREAD

**Issue by gibbsmaya** [wagtail/wagtail#3236]
### Issue Summary

On a form with more than just a few fields, It is unclear on the form submission page that there is further data to scroll to on the right hand side. This is because the left-right scroll bar is only available at the bottom of the page rather than at the bottom of your screen. Screenshot one below demonstrates the form submission screen (submissions blanked out for privacy reasons).

This means that if you want to view the first form submission in full, to view the fields that are off-screen you need to scroll down to the bottom, then scroll to the right, then scroll back up!

There are also some issue with the appearance of the scroll bar - the placement of "Page 1 of 3" makes it look like a pager rather than a scroll bar. This issue may be alleviated if the scroll bar is fixed at the bottom of a users screen rather than at the bottom of the page, but should be considered when the user is at the bottom of the screen. Screenshot 2, attached, demonstrated this.

### Technical details

* Wagtail version: 1.6.2.

![formsubmission1](https://cloud.githubusercontent.com/assets/19690895/21350422/1cfab80e-c6af-11e6-8738-296bce473f32.png)
![formsubmission2](https://cloud.githubusercontent.com/assets/19690895/21350428/1f96da84-c6af-11e6-9599-69a4e41e6dd5.png)

**Comment by smitgol** [comment]
I got this problem.Here we can create button on table head row to scroll the table horizontally like this.


![wag_photo](https://user-images.githubusercontent.com/60008621/163707805-a864f551-6a7e-43da-8de5-998a1c541438.jpg)

can i pick up this issue ??

**Comment by lb-** [comment]
Yep. But remember that the delete button shows in the header also when you select a response. 

Please be sure to review the latest code though, the main branch looks different. 

Finally, I think we could get far by putting the subtitle span in a new line. I think in general that should be outside the h1 element in the header but that will be a global change.
