### ISSUE TITLE
Coping a page to the same Tree will explode recursively

### ISSUE THREAD

**Issue by x-warrior** [wagtail/wagtail#3240]
### Issue Summary

If you try to copy a Page which has childs and use the destination the same tree "branch" it will explode when trying to recursively copy. 

### Steps to Reproduce

1. Access Wagtaildemo
2. Copy Event listing adding the destination as itself
3. ```treebeard.exceptions.PathOverflow: The new node is too deep in the tree, try increasing the path.max_length property and UPDATE your database```

### Technical details

* Python version: Python 3.4.3
* Django version: Django (1.10.4)
* Wagtail version: 1.9a0.
* Browser version: http://whatsmybrowser.org/b/EJM4TK7

**Comment by x-warrior** [comment]
The first commit just add a test which will fail to show the bug I'm relating. 

The second one adds a possible solution to this problem. I'm just raising an Exception for now, how do you want to handle this particular case? I think it is ok to raise an exception in this specific case because Wagtail UI should not let the user get to this state.

We still need to improve UI to show the node being copied and it's children as disabled. 

What is your opinion about this? Do you want me to create a PR?

**Comment by gasman** [comment]
Thanks @x-warrior!

For the 'move page' operation, we dealt with this by adding a permission rule that prevents all users (including superusers) from moving a page into one of its descendants:
https://github.com/wagtail/wagtail/blob/5e13a1d6745a77d558976c33670d9bb79fe1f703/wagtail/wagtailcore/models.py#L1784-L1786

I guess we're missing a similar rule for the 'copy page' operation.

**Comment by x-warrior** [comment]
@gasman I have added a few changes and I think now it is more aligned to the solution we have in Wagtail.

I'm keeping the verification inside the copy method to prevent this scenario if someone try to call copy directly from a different place. (Since the verification is made on the view). 

What do you think? Can I create a PR? 

We will need some UI improvements, because right now the "ModelChooser" does let you select any type of model and in this particular case we want to `exclude` specific pages when copying subpages.

**Comment by gasman** [comment]
> What do you think? Can I create a PR?

Yes please!
