### ISSUE TITLE
Preview that encourages editors to think about different screen sizes

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#3243]
Currently the preview feature just launched the page an editor is working on at whatever size browser window they happen to have open. This encourages editors to think of their content at the size they're producing it at. 

It would be great to have an editor preview UI that allowed/encouraged editors to look at their content at different screen sizes. Perhaps something like Pattern Lab (see attached)? 
![screen shot 2016-12-21 at 17 26 07](https://cloud.githubusercontent.com/assets/7290588/21399232/beb90a62-c7a2-11e6-93d1-0860df9d98e3.png)

**Comment by gasman** [comment]
Thanks for the suggestion @tmsndrs!

In an ideal world editors shouldn't be making design-related decisions at all... on balance I think this is a step in the right direction, though.

**Comment by pvetch** [comment]
I don't think this is a design related decision - it's about shaping optimal content, consonant with http://alistapart.com/blog/post/content-first-design

**Comment by tmsndrs** [comment]
Agree with Paul. It's about writing content appropriate for different devices. I'm all for separation of presentation and content. Ultimately though editors are always going to want to see how their content is being represented and it would be great if Wagtail encouraged them to be thinking about that for different screen sizes.

**Comment by tmsndrs** [comment]
I did a really quick mock-up of this. I've come across lots of instances of clients only thinking about how their content is presented on desktop, especially when using streamfield for more complex content structures and think this would be a good way to get people to think about multiple devices sizes. 

The design is really rough and needs some work to make it a bit more visually pleasing but wanted to share the idea. 

![preview-devices](https://user-images.githubusercontent.com/7290588/30157752-05569748-93bb-11e7-8f79-3b2d10d56eea.png)

**Comment by tmsndrs** [comment]
https://html5up.net/massively example with nice transitions between sizes.

**Comment by ollywillans** [comment]
I think that's really nice Tom. Would be great to implement this.

**Comment by pvetch** [comment]
+1!

**Comment by tmsndrs** [comment]
Hey @thibaudcolas I was wondering if you had done any work on this? I'm going to develop the design further.

**Comment by thibaudcolas** [comment]
👋 no, didn't do anything. I'm really interested to see this happen though.

**Comment by thibaudcolas** [comment]
@tmsndrs we should chat again and make this happen 🙂

**Comment by easherma** [comment]
FWIW, with our work at the city of austin we've instead opted for a preview panel on the same page (esp since we are using wagtail headless). 

I'd recommend thinking about these contexts, I think a side by side view is better UX overall and more flexible. 

![example](https://user-images.githubusercontent.com/10539855/59872839-42e5a300-9360-11e9-8f51-b2f350969ab7.png)

**Comment by lb-** [comment]
Not sure on the technical implementation here but if we are going down the iframe or separate tab path - this library may be useful (even as a reference).

https://github.com/jcubic/sysend.js

**Comment by easherma** [comment]
@KalobTaulien also made a version of the side by side preview at some point

**Comment by zerolab** [comment]
> @KalobTaulien also made a version of the side by side preview at some point

That would be https://github.com/KalobTaulien/wagtail-livepreview

City of Austin also had a toggle-able preview sidebar - https://github.com/cityofaustin/joplin/search?q=preview

**Comment by thibaudcolas** [comment]
For people interested in this – I have good news and bad news. This is tentatively in scope of the [page editor 2022](https://github.com/wagtail/wagtail/discussions/7739) for Wagtail 4. It’s unfortunately at risk – as per our most recent [build update blog post](https://wagtail.org/blog/build-update-on-new-page-editor/), we’re currently looking for funding to support this project, and this is one of the features that could be de-scoped if we don’t find this funding.

Here is what we’re planning to build for reference, as a side panel that would live update when authoring content, with three supported breakpoints, and a way to keep using the existing full-page preview if needed:

<img width="1440" alt="live preview screenshot" src="https://user-images.githubusercontent.com/877585/170532869-b9025e13-83d7-426e-b3e6-b9e6760e5806.png">

**Comment by thibaudcolas** [comment]
PR: #8671.

**Comment by thibaudcolas** [comment]
This has been implemented, and will ship in the next release :)

**Comment by easherma-truth** [comment]
@thibaudcolas very exciting!!
