### ISSUE TITLE
BASE_URL setting should be renamed

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#3248]
The ``BASE_URL`` setting used by ``wagtailadmin`` for generating URLs to put in emails is a bit inconsistent with the rest of Wagtail's settings, which are all prefixed with the module name.

I think this should be renamed to ``WAGTAILADMIN_BASE_URL`` (with backwards compatibilty for the previous setting).

**Comment by timheap** [comment]
May I also suggest:

1. Documenting the WAGTAILADMIN_BASE_URL setting. BASE_URL is currently not documented.
2. If WAGTAILADMIN_BASE_URL is not set, falling back on `request.site.root_url`, then falling back to building a URL from the request HOST_NAME.

**Comment by ShwetKhatri2001** [comment]
Hello, I'd like to work on this issue.

**Comment by lb-** [comment]
@ShwetKhatri2001 go for it - reach out if you need a hand. Remember that unit tests and docs are a must for any pull request.

**Comment by sandilsranasinghe** [comment]
is this still open?

**Comment by lb-** [comment]
Yep. I haven't seen a PR come in that links to this.

**Comment by sandilsranasinghe** [comment]
um I have a couple of small questions; 

- there are some usages of `settings.BASE_URL` in some html templates. Should I replace those with the tag as base_url or just change them to `settings.WAGTAILADMIN_BASE_URL`
- by pull out to a generic util do you mean add a util in admin and then use that util in the base_url_setting tag?

**Comment by lb-** [comment]
Hey @sandilsranasinghe here are some answers. 

>     * there are some usages of `settings.BASE_URL` in some html templates. Should I replace those with the tag as base_url or just change them to `settings.WAGTAILADMIN_BASE_URL`
- adding a tag is probably the best for in template usage. 


>     * by pull out to a generic util do you mean add a util in admin and then use that util in the base_url_setting tag?
- yes, there should be one place (util) that does all the fallback behaviour+ read settings for this as there are two fallbacks

>     * for the reference should I add documentation under the topic Email Notifications or just create a new topic for this
- good question, not sure but a new section makes sense I think. As you have done in your PR looks good
