### ISSUE TITLE
Revisions list doesn't show current published state

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#3251]
When reviewing revisions for a page there is no indication of which revision is currently live.

I've attached a mock-up. Could probably improve the visual design here but thought I would start basic. 
![revisions](https://cloud.githubusercontent.com/assets/7290588/21453162/5f87f996-c904-11e6-9d96-995f604a14eb.png)

**Comment by gasman** [comment]
Implemented in #3302
