### ISSUE TITLE
Status link behaviour is unexpected

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#3261]
Now that we have revisions the status link behaviour feels unexpected especially when the status is 'live + draft'. I wouldn't expect the link to take me to the live page. 

I think the 'indicator' buttons could do with some additional thought overall but for now I would suggest all status links should take you to the revisions listing. 

![screen shot 2017-01-05 at 12 39 36](https://cloud.githubusercontent.com/assets/7290588/21680861/3a787d34-d344-11e6-8c6d-475b7897fd15.png)
![screen shot 2017-01-05 at 12 39 42](https://cloud.githubusercontent.com/assets/7290588/21680866/3c586e98-d344-11e6-8caf-9286a304a8d1.png)

**Comment by tmsndrs** [comment]
- [ ] Write up plan for logic
- [ ] Visual design of status buttons 

#3269 related

**Comment by lb-** [comment]
Additional comments from older duplicate issue #2430 to consider:

>...There should be an easy way to access the draft version of the page for pages in live + draft state, for reviewing and sharing with other people. The page status box (LIVE + DRAFT) links only to the live version. You can click the Preview button, but you can't share that preview with others.

**Comment by tmsndrs** [comment]
@benenright can you add your design work for reference?

**Comment by benenright** [comment]
This is how far I got @tmsndrs 
![edit-header](https://user-images.githubusercontent.com/4907819/33565500-3131da22-d915-11e7-8b6f-58657ab82826.png)

**Comment by thibaudcolas** [comment]
This whole area has been revamped recently, with UX improvements to the page history, locking, and live/draft links, so I’ll close this now.
