### ISSUE TITLE
draft and live action labels are unclear 

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#3262]
![screen shot 2017-01-05 at 12 42 52](https://cloud.githubusercontent.com/assets/7290588/21680947/944efe00-d344-11e6-9cbd-870f91fe9d5f.png)

I don't think it's clear what the 'draft' and 'live' buttons will do. Could we include the full labels 'Preview draft' and 'View live'?

**Comment by gasman** [comment]
NHS UK also found that these buttons were causing confusion in user testing, and have customised them to "View Draft" and "View Live" in their installation:

https://github.com/nhsuk/nhsuk-content-store/blob/383430a9861035f12a679f24a15e15955d87c2a9/nhs_wagtailadmin/locale/en/LC_MESSAGES/django.po#L83-L91

+1 for changing these.

**Comment by tomdyson** [comment]
Agreed. I favour 'view' for both.

**Comment by zerolab** [comment]
Changed in #3304

**Comment by kaedroho** [comment]
#3304 merged. Thanks @zerolab!
