### ISSUE TITLE
Unable to click sequence controls when stream field has help text

### ISSUE THREAD

**Issue by iaindillingham** [wagtail/wagtail#3264]
### Issue Summary

Adding `help_text` to a stream field adds a hidden (`opacity: 0`) `div` element to the UI with the classes `object-help` and `help`. This element overlaps the sequence controls of the first block in the stream field (_Move down_ and _Delete_), meaning that these sequence controls cannot be clicked.

### Steps to Reproduce

1. Add `help_text` to a stream field. `HomePage.body` in the demo site, for example.
2. Assuming the demo site has content, try to click either the _Move down_ or _Delete_ sequence control of the first block.

### Technical details

* Python version: 2.7.12
* Django version: 1.9
* Wagtail version: 1.7
* Browser version: FF 50.1.0 Ubuntu (http://whatsmybrowser.org/b/ILSMFTP)

**Comment by gasman** [comment]
Hi @iaindillingham - thanks for reporting! This has just been fixed in #3168.

**Comment by iaindillingham** [comment]
Aargh! I should have been more precise with my search terms. Thanks for the speedy response.
