### ISSUE TITLE
hardcoded strings in wagtailadmin and wagtaildocs

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#3265]
### Issue Summary

There are hardcoded strings in the folowing templates:

wagtailadmin/home/pages_for_moderation.html line 53
wagtailadmin/home/recent_edits.html line 37
wagtaildocs/documents/list.htmlline 40
wagtailadmin/pages/listing/_list.html 26 + 65

All with the frase “ago”

Cheers,

Rob

**Comment by gasman** [comment]
Fixed in #3266
