### ISSUE TITLE
Status and workflow bar designs

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#3269]
Had a think about the task bar menu (off topic but as it stands, this is marked up as footer element though it's definitely a menu element) reference in #3247 and #2214 

Currently at the top of the page you have a menu that lets you lock, password protect or view the live version of the page. In the bottom menu you have a lot of other options relating to workflow and revisions. 

I think it makes sense to rationalise these two areas of the UI. I see the top section as being the 'status' bar. It's information you might want to know before you make any changes to the document but are unlikely to need at any other point whilst editing content. 

The bottom bar, or 'workflow menu' relates to workflow and utility. Of course status and workflow aren't mutually exclusive but I think it helps to think about the menus in these terms. 

I've mocked up some suggested designs which I'll cover below. I've tried to consider visual consistency with the rest of the Wagtail UI.

Firstly you have the Admin/Mod 'workflow menu'. This presents the user with two primary button: 

- 'save draft', a soft action therefor uses a ghost button
- 'publish', a hard action so uses a solid button. It still has the additional 'more' menu which in this instance would only contain 'submit for moderation'. I'm making a presumption here that this would be a secondary action but without user research it's hard to say which is more important to admin/mods. 

I've then added a simple status option to show the current state of the page, removing the revisions info (I'll get to this later) 

Then we've got a pretty basic utility menu for preview, locking and deleting. These are common only in the sense that they don't belong to the publishing workflow. 

![desktop copy 4](https://cloud.githubusercontent.com/assets/7290588/21727639/2c4d37da-d43a-11e6-8f5d-28501d64e3d1.png)

Next up we've got the Editor 'workflow menu'. The same apart from only allowing the editor to submit content for moderation (therefore a primary task). I'm a little unclear on the permissions here and wasn't sure if Editors can delete or lock pages but I've left that in. 

![desktop copy 5](https://cloud.githubusercontent.com/assets/7290588/21727914/7bbd11a4-d43b-11e6-9e05-8c4649f4a391.png)

Once a page is published Admin/Mods get a few extra options and the publish button copy changes... 
![desktop copy 2](https://cloud.githubusercontent.com/assets/7290588/21727937/9a9a125c-d43b-11e6-9cd0-41ce89410399.png)

I've also done a design for when the page is locked. 
![desktop copy 6](https://cloud.githubusercontent.com/assets/7290588/21727970/c6a9b514-d43b-11e6-9dfe-c249eb7228c3.png)

And when it's locked but the user is able to unlock the page. 
![desktop copy 7](https://cloud.githubusercontent.com/assets/7290588/21727987/db6ee744-d43b-11e6-976d-8d6656fb5e6a.png)

Next up is the 'status bar' at the top of the page. As mentioned previously I find the buttons at the top right very confusing and the behaviours unexpected. I think there's also additional information we could include here. I think this still needs work both in terms of visual design and interaction but I wanted to get people's thoughts before I spent much more time on it. Pretty obvious what's going on in each of these I think... 

![desktop copy](https://cloud.githubusercontent.com/assets/7290588/21728060/2664f310-d43c-11e6-8062-f6bcb61b03d3.png)

![desktop copy 9](https://cloud.githubusercontent.com/assets/7290588/21728080/37451bce-d43c-11e6-90da-45e93716394e.png)

![desktop copy 11](https://cloud.githubusercontent.com/assets/7290588/21728088/42d618b2-d43c-11e6-8cfd-ea333ed577d9.png)

One thing I've left out is the privacy status. To me this is a setting and should live in the settings tab but it's probably worth including something in the 'status bar' if the page is password protected. This would need to be worked out. 

Anyway, I'm sure this needs more work but I'm hoping it can provoke some further conversation. I've added the Sketch file I used to create these. They're not meant to be pixel perfect at this stage and the file is a bit messy but feel free to use as people wish.  
[Workflow and status bar.zip](https://github.com/wagtail/wagtail/files/690509/Workflow.and.status.bar.zip)

**Comment by tomdyson** [comment]
Thanks @tmsndrs, this is excellent. As with @strindhaug's #3247, there's a lot for us to think about here. I slightly worry that the preview link - which is probably the most frequently used action - has become harder to find / click, but testing may prove otherwise. It took me a while to spot the revisions link, but perhaps that wouldn't be a problem at full size.

**Comment by strindhaug** [comment]
I like this design!

One small thing: I'd might want to reverse the order of the 3 icons in the bottom right, since preview is (hopefully) more frequently used than delete and the corners of the screen is slightly easier to aim for  assuming a full screen sized window (see https://blog.codinghorror.com/fitts-law-and-infinite-width/ ), or even moved elsewhere completely. I personally dont like it when destructive actions is just a few pixels away from common non-destructive actions (even when there is a confirmation screen).

**Comment by strindhaug** [comment]
Note that it's actually possible to have more than one preview mode (i noticed this in the code when messing around with my own design ideas); not really sure how common this is (or whether it's used by anyone ever) but have you any idea how multiple preview modes would work in this design?

**Comment by heymonkeyriot** [comment]
This is great, and I think a better direction than the proposal I made this time last year (#2214), and clearly a vast improvement on what we currently have. I think it makes sense to separate the meta information from the action buttons.

@tomdyson on the topic of:
> I slightly worry that the preview link - which is probably the most frequently used action - has become harder to find / click, but testing may prove otherwise.

I've heard this said a few times, but never seen any metrics to back it up. Are people using preview more than other buttons?

**Comment by tomdyson** [comment]
> I've heard this said a few times, but never seen any metrics to back it up. Are people using preview more than other buttons?

I'm afraid I don't have metrics. My statement was based on the way that I use Wagtail, which is lots of edits and previews before a save or publish.

**Comment by tmsndrs** [comment]
@benenright can you add you design work to this ticket for reference.

**Comment by thibaudcolas** [comment]
Copying the WIP from @strindhaug here for reference, see for the full discussion:

--------------------

> Another example of a slightly more radical approach to fixing https://github.com/wagtail/wagtail/issues/2214
implementing some of the ideas I mentioned in my comments on the less radical https://github.com/wagtail/wagtail/pull/3241 pr.

> This solution is a lot more compact and responsive even though it has an additional button.

> Current footer, for width comparison (note that the preview button is actually wider than it appears):
![orig](https://cloud.githubusercontent.com/assets/2144849/21424754/179847ae-c845-11e6-9948-57149a621686.png)

> New footer in the same width (the preview button now doesn't have extra width since it's not a dropdown anymore; extra preview modes are shown in the common dropdown):
![wide](https://cloud.githubusercontent.com/assets/2144849/21424783/3673c81a-c845-11e6-825b-e04781d82773.png)

> Some of the meta-data is hidden (and revisions link is moved to the menu), to allow narrowers screen without wrapping:
![narrow](https://cloud.githubusercontent.com/assets/2144849/21424804/5815e3ea-c845-11e6-8349-697bcccefca8.png)

> The 3 direct buttons with icons (save draft, publish, preview) become icon only on smaller widths to avoid wrapping on phone sizes:
![phone](https://cloud.githubusercontent.com/assets/2144849/21424809/5bfd00ba-c845-11e6-8fce-713629630ea3.png)

> Color coded (only on hover) delete and unpublish with red and yellow respectively:
![color_code_on_hover](https://cloud.githubusercontent.com/assets/2144849/21424858/b3addb22-c845-11e6-8118-7103ab8088c2.png)

> The "Submit for moderation" button  replaces the "Publish" button when the user is not allowed to publish:
![cant_pub](https://cloud.githubusercontent.com/assets/2144849/21424875/d6ae9ce2-c845-11e6-927b-f3409b0e2c6d.png)
It's deliberately not color coded green like the publish button to avoid confusion.

> **NOTE** The css is currently hardcoded in a `<style>` block in the template for easy development and there is a lot of commented code for reference while developing. This needs to be cleaned up and the styles must be moved to the sass files before this can be merged.
But even though this code is somewhat ugly; it *is* functional and can be checked out locally for testing.

**Comment by thibaudcolas** [comment]
This has recently been revamped as part of Wagtail 2.10’s page editor enhancements related to the new workflow feature, which reduce the space occupied by the action bar, and bring some of the "page edits metadata" into the page header, so I think we can consider this to be done and I’ll close it as such.

Release notes: https://docs.wagtail.io/en/latest/releases/2.10.html#what-s-new.

![page-editor-enhancements-2 10](https://user-images.githubusercontent.com/877585/89426079-a9c74680-d731-11ea-97a7-884d1b5a74ef.png)
