### ISSUE TITLE
Document requirement for using 'routablepageurl'

### ISSUE THREAD

**Issue by tombreit** [wagtail/wagtail#3286]
In oder to use the ``routablepageurl`` template tag (as described in http://docs.wagtail.io/en/v1.8/reference/contrib/routablepage.html#the-routablepageurl-template-tag), ``wagtail.contrib.wagtailroutablepage`` has to be added to ``INSTALLED_APPS``. This should be mentioned explicitly in the contrib doc (see above). 

### Technical details

* Python version: 3.5.3rc1
* Django version: 1.10.4
* Wagtail version: 1.8

**Comment by gasman** [comment]
Thanks! Have now added this in 29645c0f6a7ce5e732ba63af69daa2469412aba9.
