### ISSUE TITLE
TableBlock inside StructBlock rendered with its raw value

### ISSUE THREAD

**Issue by pyMan** [wagtail/wagtail#3289]
Wagtail 1.7

If I use a TableBlock in a StreamBlock the table is rendered as expected.

If I use a TableBlock inside a StructBlock in a StreamBlock the table is then rendered using its raw value (a dict with data and metadata).

In the next sample code both nested_table and nested_table2 are being rendered as dict

```
from wagtail.wagtailcore.blocks import StructBlock, StreamBlock
from wagtail.contrib.table_block.blocks import TableBlock

class MyTableBlock(StructBlock):
    table = TableBlock(label = "table")
    
    class Meta:
        template = "my_table_block.html"

class MyStreamBlock(StreamBlock):
    simple_table = TableBlock(label = "table")
    nested_table = StructBlock([('table', TableBlock(label = "table"))], label = "nested table")
    nested_table2 = MyTableBlock(label = "nested table2)
```

MyStreamBlock's template
```
{% load wagtailcore_tags %}

<div class="stream-field">
	{% for block in value %}
		{% include_block block %}
	{% endfor %}
</div>
```

MyTableBlock's template (my_table_block.html)
```
{% load wagtailcore_tags %}
{% include_block value.table %}
```

TableBlock's render is not being called when TableBlock is in a StructBlock, so it's default value is used.

I don't know if this is a real issue or I'm missing something.

**Comment by gasman** [comment]
Hi @pyMan,

This is explained in http://docs.wagtail.io/en/v1.8/topics/streamfield.html#boundblocks-and-values - `{% include_block value.bound_blocks.table %}` should do what you want.

**Comment by pyMan** [comment]
Thanks @gasman !
