### ISSUE TITLE
Default avatar is visible when using a transparent gravatar image

### ISSUE THREAD

**Issue by jaap3** [wagtail/wagtail#3291]
Not really a big issue, but when you have a partially transparent gravatar img parts of the fallback avatar are visible: 

![screen shot 2017-01-23 at 17 15 55](https://cloud.githubusercontent.com/assets/48517/22212213/16939b38-e190-11e6-8fd4-2201549d60c8.png)

**Comment by jjanssen** [comment]
Merged in 20e8aab
