### ISSUE TITLE
Make arguments of PageChooserBlock more similar to PageChooserPanel

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#3299]
In Wagtail 1.8 we introduced the the `target_model` argument in `PageChooserBlock` which takes a page model class or string representation of model like `tests.EventPage` (see #3072). It's a good idea, but some people (including me :)) were confused by interface `PageChooserBlock` provides. The `PageChooserBlock` block is very similar to the `PageChooserPanel` panel, but there are some differences in interfaces:

* `PageChooserBlock` provides the `target_model` argument to filter models in a chooser. In `PageChooserPanel` similar argument have a different name (`page_type`). Moreover we usually use the "page type" term in Wagtail (see [`Page.subpage_types`](http://docs.wagtail.io/en/v1.8/reference/pages/model_reference.html#wagtail.wagtailcore.models.Page.subpage_types) and [`Page.parent_page_types`](http://docs.wagtail.io/en/v1.8/reference/pages/model_reference.html#wagtail.wagtailcore.models.Page.parent_page_types), for example.
* `PageChooserBlock`'s `target_model` argument accepts only one page type. `PageChooserPanel` allows to pass a list or tuple of page types.

TODO:

- [x] Allow `PageChooserBlock` to take a list of page types in the `target_model` argument (PR #3297)
- [ ] Rename the `target_model` argument to `page_type` with a deprecation period

**Comment by gasman** [comment]
Completed in #4653
