### ISSUE TITLE
Make admin language configurable on a per-user basis

### ISSUE THREAD

**Issue by chimeno** [wagtail/wagtail#3306]
**Issue**
I was trying to have the admin in my native language ``es-es`` (in order to improve translations) without setting the ``LANGUAGE_CODE`` in a global way.

**Solution**
Make the language of the admin being configurable on a per-user basis, adding a ``prefered_language`` field in the ``UserProfile``.

Is this something you could see in wagtail core? I can make a PR in that case.

Related issue: #3205

**Comment by kaedroho** [comment]
I think this is a good idea. Thanks!

We would need to add some special logic to the email notifications to make sure emails are sent in the language of the person recieving them and not the language of the person who triggered them.

**Comment by chimeno** [comment]
Ok!
Just a UI question, do you prefer the widget form in the ``account`` page or under a new page ``account/language_preferences`` ?

**Comment by gasman** [comment]
> Just a UI question, do you prefer the widget form in the account page or under a new page account/language_preferences ?

Whatever's easiest, I think! Ideally I'd like to combine everything into one form (password, notification preferences, language, timezone - and _possibly_ username / real name / email, although I guess there are differing opinions about whether they should be editable) - but I appreciate that's probably out of scope for this change.

**Comment by gasman** [comment]
Implemented in #3310.
