### ISSUE TITLE
Add ability to run only some tests or TestCases

### ISSUE THREAD

**Issue by chimeno** [wagtail/wagtail#3307]
Django has the ability to run only some TestCases or individual tests, after tried within wagtail with:
````python runtests.py wagtail.wagtailadmin.TestAccountSection```` or
````python runtests.py wagtail.wagtailadmin.tests.TestAccountSection```` gives:
````AttributeError: 'module' object has no attribute 'TestAccountSection'````

We should add a feature like this in order to reduce tests duration.

[Django docs about testing](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/unit-tests/#running-only-some-of-the-tests)

**Comment by gasman** [comment]
Hi @chimeno,

This does work - you've just got the module path wrong :-) Try:

    python ./runtests.py wagtail.wagtailadmin.tests.test_account_management.TestAccountSection
