### ISSUE TITLE
Relevance searching for database backend

### ISSUE THREAD

**Issue by Sheepzez** [wagtail/wagtail#3312]
As mentioned in the backends documentation, Wagtail does not support relevance when using the database backend. Using ElasticSearch isn't an option for me as I don't require (or can afford) the kind of hardware that it requires.

I would like to implement relevance searching on my pages with a Postgres backend. Is this something that could possibly be added to the Wagtail database backend? Or would it be idiomatic to add it myself on top using something like Haystack (http://haystacksearch.org/)?

I read in #2342 that PostgreSQL FTS and Whoosh are planned additions, is this still in progress? :)

Edit: Could it be worth creating a new contrib app that adds a database backend with relevance searching using something like Haystack?

**Comment by BertrandBordage** [comment]
This is implemented in #3515.
