### ISSUE TITLE
Django 1.11 compatibility

### ISSUE THREAD

**Issue by tomdyson** [wagtail/wagtail#3314]
Our plan is to make Wagtail 1.10 (due April 1st 2017) compatible with Django 1.11 (also due April 2017). Like Django 1.11, we expect to designate Wagtail 1.10 as a long term support release.

We are seeking help from the community - especially @timgraham :) - to track and advise us on Django compatibility issues.

**Comment by gasman** [comment]
see also: #3283, #3284

**Comment by gasman** [comment]
Right now it looks like the main blocker is going to be https://github.com/wagtail/django-modelcluster/issues/66 - where Django has added new validation that conflicts with the way django-modelcluster handles unsaved instances in modelformsets. I haven't yet dug into the codebases far enough to figure out if this can be reconciled / worked around, but it's _possible_ that it'll call for an option on the Django side to disable the check, similar to https://code.djangoproject.com/ticket/24495.

**Comment by chimeno** [comment]
Just note there are changes in how widgets are rendered  [changelog](https://docs.djangoproject.com/en/dev/releases/1.11/#template-based-widget-rendering) that will need some effort.
There are various (32) tests failing because of that in Django1.11b1, and I'm not enough familiar with that part to work on that :(.

**Comment by timgraham** [comment]
For the widget rendering changes, it looks like the assertions need to be modified to ignore HTML attribute ordering. Here's a start: http://dpaste.com/16A210H though not all the modified tests are all passing. I'm not planning to continue on that but feel free to let me know if you find some issue that you have trouble solving.

I also sent https://github.com/wagtail/wagtail/pull/3397 to allow the tests to run.

**Comment by gasman** [comment]
Modelcluster issue fixed in https://github.com/wagtail/django-modelcluster/pull/70 (essentially adding a monkeypatch to reverse the Django-side change, which feels messy but is probably the right thing to do, given that it boils down to a fundamental difference over what's considered a valid form within a ModelFormSet vs modelcluster's TransientModelFormSet).

**Comment by gasman** [comment]
#3406, #3413 and #3414 hopefully fix all the remaining tests against Django 1.11b1.

There are also lots of warnings in the test output, which we should address.

**Comment by gasman** [comment]
There was some low-hanging fruit among those warnings (a missing on_delete setting, and pagination being applied to non-ordered querysets) which I've fixed in #3417. As per Tim's suggestion, I'll hold off on the remaining ones as they'd require fallback code for Django 1.8.

**Comment by m1kola** [comment]
Remaining work:

- [ ] Elasticsearch backends should process `In` lookup correctly on `Django>=1.11`. Refs:
  * Test failures:
    * [TOXENV=py27-dj111-postgres-elasticsearch5 INSTALL_ELASTICSEARCH5=yes](https://travis-ci.org/wagtail/wagtail/jobs/210230896)
    * [TOXENV=py35-dj111-postgres-elasticsearch](https://travis-ci.org/wagtail/wagtail/jobs/210230901)
    * [TOXENV=py36-dj111-postgres-elasticsearch](https://travis-ci.org/wagtail/wagtail/jobs/210230905)
    * [TOXENV=py36-dj111-postgres-elasticsearch2 INSTALL_ELASTICSEARCH2=yes](https://travis-ci.org/wagtail/wagtail/jobs/210230906/)
    * [TOXENV=py36-dj111-postgres-elasticsearch5 INSTALL_ELASTICSEARCH5=yes](https://travis-ci.org/wagtail/wagtail/jobs/210230907/)
  * [Django ticket](https://code.djangoproject.com/ticket/27930) (confirms that change were made in a private API, so we should fix it on our side)
- [ ] Once `Django==1.11` is released, change test matrix to not allow failures on Django 1.11 (except tests with Elasticsearch).
- [ ] Release notes: review all ticket/PRs and mention people who contributed

**Comment by BertrandBordage** [comment]
Only the release notes are remaining for this :)

**Comment by gasman** [comment]
Release notes added in fb82650943a0542788e9de49917ee364b40876de. Thanks everyone!
