### ISSUE TITLE
Multilingual

### ISSUE THREAD

**Issue by cristovao-alves** [wagtail/wagtail#3317]
### Multilingual CMS
Simple tutorial to show how to use multilingual.
After I've search around all the web and didn't found any complete tutorial or something that helped me, I have developed one simple app to show how to implement this.

The repo is here:
https://github.com/cristovao-alves/Wagtail-Multilingual

**Comment by gasman** [comment]
Thanks @cristovao-alves! I've added this to the "Third-party tutorials" section of the documentation now.
