### ISSUE TITLE
Beautiful Soup reports warnings when performing revision comparison of URL fields

### ISSUE THREAD

**Issue by nfletton** [wagtail/wagtail#3340]
### Issue Summary

Not a big issue but warnings of the form below are displayed by the development server when comparing changes on URL fields. The output to the user is exactly what you'd expect though.

Here's the development server output I get after changing a URL field from example.com to google.com

```
/home/vagrant/ATESL_CA/lib/python3.5/site-packages/bs4/__init__.py:282: UserWarning: "http://www.example.com" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup
/home/vagrant/ATESL_CA/lib/python3.5/site-packages/bs4/__init__.py:282: UserWarning: "http://www.google.com" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup
[06/Feb/2017 16:22:56] "GET /atesladmin/pages/13/revisions/compare/333...334/ HTTP/1.1" 200 17714
```

### Steps to Reproduce

1. Change the URL field of a page with that field type
2. Compare the change with the revisions comparison feature.
3. Observe the warnings displayed in the development server output.

### Technical details

* Python version: 3.5.2
* Django version: 1.10.5
* Wagtail version: 1.9rc1

PS.Thank you to the the developers and sponsors for the revisions comparison feature.

**Comment by gasman** [comment]
It appears that all `CharField` / `TextField`s are currently being compared as HTML (and thus passed through BeautifulSoup), not just rich text fields: https://github.com/wagtail/wagtail/blob/0dc9e5f4a47aaae68dbf18cbaca548b7e5f9fbc0/wagtail/wagtailadmin/edit_handlers.py#L491

(@kaedroho, is there a reason for doing it this way?)
