### ISSUE TITLE
Site-specific template paths

### ISSUE THREAD

**Issue by snimavat** [wagtail/wagtail#3341]
What is is the right way to have seperate templates for different sites when i am hosting multiple sites with same wagtail instance.

It would be great if wagtail came with this support outof thebox,
eg. if the template exists et /sitename/xx-page.html pick it, or else use the default template..
so that templates can be overriden for different sites.

**Comment by gasman** [comment]
You can do this by defining a `get_template` method on your model, something like:

    class StandardPage(Page):
        def get_template(self, request):
            if request.site.name == 'sitename':
                return "sitename/standard_page.html"
            else:
                return super(StandardPage, self).get_template(request)

The [`wagtail.contrib.settings`](http://docs.wagtail.io/en/v1.8.1/reference/contrib/settings.html) module is also a good way to vary template properties between sites.

I like the idea of making this a built-in feature of Wagtail, though - I'll leave this open as a feature request.

**Comment by tomdyson** [comment]
See https://github.com/moorinteractive/wagtail-themes by Wagtail core developer @robmoorman.

**Comment by robmoorman** [comment]
Hi @snimavat as Tom suggested please see my wagtail-themes package, I specially created this as I had the same request you asking for. Please let me know if you have any problems installing it!

**Comment by snimavat** [comment]
Great, thanks, will close the ticket
