### ISSUE TITLE
1.9rc1 regression in Block.render()

### ISSUE THREAD

**Issue by mvantellingen** [wagtail/wagtail#3346]
The ``Block.render()`` (see https://github.com/wagtail/wagtail/blob/827149f5d21620f8bbbc9b6517e7cc686c52b487/wagtail/wagtailcore/blocks/base.py#L229) accepts an optional context however a few lines below (https://github.com/wagtail/wagtail/blob/827149f5d21620f8bbbc9b6517e7cc686c52b487/wagtail/wagtailcore/blocks/base.py#L250) it is assumed that it is a dictionary.

We hit this issue since we implemented a ``get_context()`` override on a subclass of a ``blocks.StructBlock``. Adding the parent_context kwarg and passing it down works the issue.

cc @mikedebock

**Comment by gasman** [comment]
Fixed in #3347
