### ISSUE TITLE
Repeating an edit/publish/view cycle results in multiple browser tabs

### ISSUE THREAD

**Issue by nfletton** [wagtail/wagtail#3348]
### Issue Summary

It could just be my personal preference, but I'm not keen on the direction of the change to make the live button open consistently in a new window. The consistency part is a good thing - I'd always thought there was some user experience logic behind the inconsistency that I just didn't get.

If your edit cycle revolves around the Wagtail user bar and you perform multiple page edits you end up with multiple tabs open. I personally find that a little irritating.

### Steps to Reproduce
For instance, repeating this cycle a few times results in multiple windows:

1. Click 'edit page' on userbar widget 
2. Edit page
3. Publish change
4. Click View Live in the publish confirmation message (_previously this step opened page in same tab_)
5. Browse frontend to another page
6. Repeat cycle....

Maybe a future version should have a config setting to control if new windows are opened or not

### Technical details

* Wagtail version: 1.9rc1

**Comment by thibaudcolas** [comment]
I’m going to close this in favour of #6123, where we generally advocate getting rid of all "force open in new window", with View Live mentioned in particular.
