### ISSUE TITLE
Strings for wagtailform date filder has not marked for translation

### ISSUE THREAD

**Issue by Vorlif** [wagtail/wagtail#3364]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

'[Date from](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailforms/forms.py#L115)' and '[Date to](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailforms/forms.py#L119)' are not marked for translation. 

### Technical details

* Wagtail version: github master

**Comment by gasman** [comment]
Fixed in #3365
