### ISSUE TITLE
Warn people when they're looking at the development version of the docs

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#3375]
Occasionally people find their way to the development version of the tutorial page, and get tripped up when things don't match the current release version:
https://groups.google.com/d/msg/wagtail/HPL5w1LIrAw/SvVLJKgGCgAJ

[Django's docs](https://docs.djangoproject.com/en/dev/) display a notice:

> This document is for Django's development version, which can be significantly different from previous releases. For older releases, use the version selector floating in the bottom right corner of this page.

We should see if readthedocs allows us to do the same, and add one if so.

**Comment by zerolab** [comment]
RTD show a notice when viewing an old tag - https://github.com/rtfd/readthedocs.org/blob/499a74076f0debae09acc1d4c4eeeab03f8f557e/media/javascript/rtd.js#L14

I think the same can possibly be done with https://github.com/rtfd/readthedocs.org/issues/152#issuecomment-186115025

**Comment by lb-** [comment]
After a bit of digging, it looks like a fix to Readthedocs may already be in the works.

Others have run into this issue here: https://github.com/rtfd/readthedocs.org/issues/3481

Also, there is a reasonably recent PR to fix it here: https://github.com/rtfd/readthedocs.org/pull/3547

I will keep an eye on that issue/PR but if others want to +thumbsup on the issue - it might help the RTD team flag that this is important.

**Comment by lb-** [comment]
I'm not sure if this is new, maybe a Read the Docs option/update?

I noticed today that a small popover appears for a few seconds on the `latest` docs. 

![Image](https://github.com/user-attachments/assets/2800dfda-bce3-4001-8871-033ffa306c85)

**Comment by laymonage** [comment]
@lb- yep, it's the new readthedocs addons https://about.readthedocs.com/blog/2024/07/addons-by-default/

We enabled the feature when it was still in beta a few months back, but there was an issue with our theme https://github.com/wagtail/sphinx-wagtail-theme/issues/296 so it didn't show up immediately. It's fixed now though, so I think we can close this – thanks!

**Comment by lb-** [comment]
Thanks @laymonage - this is an awesome win.
