### ISSUE TITLE
Cannot add_child after deleting a parent's only child.

### ISSUE THREAD

**Issue by matthewquinn** [wagtail/wagtail#3402]
### Issue Summary

page_instance.delete() is not clearing the treebeard numchild value of the parent page node.
This has been causing me issues when trying to remove the default wagtail home page and place my own custom one in.

The error will only be hit if you are deleting the only child of a page and then trying to add a child to that page. In the [add child process](https://github.com/django-treebeard/django-treebeard/blob/4.1.0/treebeard/mp_tree.py#L347) treebeard treats the root as a branch and attempts to run queries on the children. 

Treebeard has [warnings](http://django-treebeard.readthedocs.io/en/latest/caveats.html#custom-managers) for manages that do not subclass its manages. I could not see wagtail referencing the treebeard manager when looking though the source but it looks like [this code](https://github.com/django-treebeard/django-treebeard/blob/4.1.0/treebeard/mp_tree.py#L51) or the equivalent is not being run.

### Steps to Reproduce

1. Get the root page instance.
2. Get the child page instance.
3. Delete the child page.
4. Create a new child page instance.
5. Add the child to the root with the add_child(instance=child) method

Or on a fresh install:
```
from wagtail.wagtailcore.models import Page
root = Page.objects.get(path='0001')
home = Page.objects.get(path='00010001')

home.delete()
root.add_child(instance=Page(title='New only child that throws errors'))
```

### Technical details

* Python version: 3.5.2
* Django version: 1.10.5.
* Wagtail version: 1.9.

Full stack trace:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in
execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in
execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_
from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 345, in exec
ute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line
224, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/usr/local/lib/python3.5/site-packages/django/core/management/sql.py", line 53, in emit_p
ost_migrate_signal
    **kwargs
  File "/usr/local/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/api/api/apps.py", line 60, in create_default_pages
    root.add_child(instance=home)
  File "/usr/local/lib/python3.5/site-packages/treebeard/mp_tree.py", line 976, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/usr/local/lib/python3.5/site-packages/treebeard/mp_tree.py", line 359, in process
    newobj.path = self.node.get_last_child()._inc_path()
AttributeError: 'NoneType' object has no attribute '_inc_path'
```

**Comment by aabele** [comment]
This also affect versions starting 1.5 (haven't checked earlier).

**Comment by gasman** [comment]
Hi @matthewquinn and @aabele,

I think this is working as designed. From the [treebeard docs](https://django-treebeard.readthedocs.io/en/latest/caveats.html):

> django-treebeard uses Django raw SQL queries for some write operations, and raw queries don’t update the objects in the ORM since it’s being bypassed.
>
> Because of this, if you have a node in memory and plan to use it after a tree modification (adding/removing/moving nodes), you need to reload it.

Your example code above isn't following this rule - you're calling `add_child` on a stale copy of the root node. Moving the line `root = Page.objects.get(path='0001')` after the deletion makes it work again.
