### ISSUE TITLE
Explorer Screen Content Not 100% Width

### ISSUE THREAD

**Issue by tkjone** [wagtail/wagtail#3408]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When viewing the `Explorer` screen for a new project the content width is capped at `100em`.

### Steps to Reproduce

1. Start a new wagtail project
2. Login to the admin panel
3. Visit the explorer screen for your HomePage (http://localhost:8000/admin/pages/3/)

You can see below, as depicted by the arrow to the right, that the content of the screen never reaches 100%.  

<img width="1583" alt="100-percent-width" src="https://cloud.githubusercontent.com/assets/8523922/23386031/118f241a-fd22-11e6-9179-edeb8c39ac1e.png">

### Technical details

* Python version: 3.6.
* Django version: 1.10.
* Wagtail version: 1.9.
* Browser version: Chrome latest, Firefox latest, Safari latest.
* Dockerized environment

### Notes

This is my first time submitting an Issue to wagtail.  I have reviewed the process and quickly reviewed the current issues and PR's - could not immediately see an Issue that matches this one.  I apologize if this is a duplicate.  Either way, happy to resolve this issue.

**Comment by gasman** [comment]
Hi @tkjone - thanks very much for the report! This has now been addressed in #3124, and the fix will be released in Wagtail 1.10.
