### ISSUE TITLE
'Footer' is invalid tab heading

### ISSUE THREAD

**Issue by rvdrijst** [wagtail/wagtail#3409]
### Issue Summary
When you create a new tab in the admin with heading 'Footer', you don't get any errors (in python nor javascript) but the tab doesn't work. You can click on the tab but the content doesn't change.
Note: when 'Footer' is the first tab it works initially, but you cannot go back and forth between the tabs.

### Steps to Reproduce

1. Create a tab with name 'Footer':
```python
edit_handler = TabbedInterface([
    ...
    ObjectList([...], heading='Footer'),  # < this heading doesn't work
    ...
])
```
2. Edit or create a page with this tab
3. Try to click back and forth to this tab and notice it's not working.

A workaround is to name the tab something else like 'Footer content', but since we mark these headings as translatable there is no guarantee that they will not be named 'footer' or some other 'forbidden' name.
This issue has probably something to do with the fact that the tab has `href="#footer"` and there is an actual (unrelated) element with that ID. Maybe a prefix for this would be safer, like `href="#editor-tab-footer"`.

### Technical details

* Python version: 3.6
* Django version: 1.10
* Wagtail version: 1.9
* Browser version: Latest Firefox and Chrome

**Comment by gasman** [comment]
Fixed in #3410
