### ISSUE TITLE
Adding new users - You are able to leave the password confirmation blank despite completing the password field

### ISSUE THREAD

**Issue by Lydia01** [wagtail/wagtail#3416]
### Issue Summary

When adding a new user, if you input a password but leave the password confirmation field blank then you can still save that user

### Steps to Reproduce

1) Log into Wagtail
2) Select the 'Settings' tab
3) Select the 'Users' option
4) Select the 'Add A User' button
5) Complete all mandatory fields
6) Within 'Password' input a password
7) Leave 'Password Confirmation' blank
8) Save the new user
9) Log out
10) Navigate to the logint page
11) Input the correct username
12) Input the password used on the first field
13) Select the 'Login' button
14) See that login is successful

I would expect there to be a validation message when saving the user informing you that the passwords do not match

### Technical details

* Python version: Python 3.5.2
* Django version: Django 1.10.2
* Wagtail version: Wagtail 1.8
* Browser version: Chrome 55

**Comment by chimeno** [comment]
I confirm this happens with Wagtail==1.8 and Wagtail==1.9 but not with Wagtail (master), I guess the last commits #https://github.com/wagtail/wagtail/commit/87e11bec86d4d6404ee4bec14c59f3502af99129 and #https://github.com/wagtail/wagtail/commit/9216d434dbd9ceeeac033611b3254c705ba96af0 ) have solved the issue.

**Comment by jjanssen** [comment]
This got fixed in PR #3007 and is available when we release Wagtail 1.10
