### ISSUE TITLE
Wagtail 1.8.1 migration issue, migration erroneously reporting duplicate renditions

### ISSUE THREAD

**Issue by jossingram** [wagtail/wagtail#3420]
We've realised that the error we get when trying to run migrations after upgrading from Wagtail 1.7 to 1.8.1 detailed here http://stackoverflow.com/questions/42365685/wagtail-1-8-1-migration-issue is in fact not an issue with duplicates as such, but the focal_point_key is being truncated by two characters at the end, which makes it appear that duplicate renditions exist.

In the error it says DETAIL: Key (image_id, filter_id, focal_point_key)=(788, 4, 3231-1430-5472x28) is duplicated. When I bring back all renditions for image 788, the three records have focal key points like "3231-1430-5472x2874" , so it's cutting off the last two characters, and thinking we have duplicates 

We haven't used any custom image models, or made any specific changes to the migrations or db.

Although deleting the entire renditions table allows the migrations to run, is there any other solution?

This query (below) which was kindly offered as a fix, doesn't work because there are no duplicate entries

DELETE FROM wagtailimages_rendition
WHERE image_id || '-' || filter_id || '-' || focal_point_key IN (
    SELECT image_id || '-' || filter_id || '-' || focal_point_key
    FROM (
        SELECT image_id, filter_id, focal_point_key, COUNT(*) AS count
        FROM wagtailimages_rendition GROUP BY image_id, filter_id, focal_point_key
    ) AS renditions
    WHERE count > 1
);

Have we missed out some step historically which would have made our focal_point_key not be so long or is this a bug?

Thanks

Joss

**Comment by benjaoming** [comment]
Is the problem in this line? `Rendition.unique_together` is `('image', 'filter_spec', 'focal_point_key')`, so in case focal_point_key is supposed to say `3231-1430-5472x28`, that would be 17 chars.

    focal_point_key = models.CharField(max_length=16, blank=True, default='', editable=False)

**Comment by lb-** [comment]
Closing as 1.8 is no longer supported and needs more info.

@jossingram let us know if you did not resolve this issue with upgrading.

**Comment by gasman** [comment]
The issue of focal point key potentially being truncated is still an open bug, I think.

**Comment by jossingram** [comment]
I think we ran a query to delete the offending rows, but I can't honestly remember 100% now.

**Comment by lb-** [comment]
@gasman I have been digging into this a bit and yes it appears that this issue is because of a fix for #3256 where the field was truncated to resolve a different issue.

**Comment by zerolab** [comment]
Do we have numbers on how many sites are on Wagtail < 1.8?
Can this be closed since we did not have more reports for 4+ years?

**Comment by lb-** [comment]
I think yes.
