### ISSUE TITLE
[IE10+] Odd pagination behaviour on users list in wagtail admin 

### ISSUE THREAD

**Issue by ababic** [wagtail/wagtail#3433]
### Issue Summary

In Internet Explorer 10 and 11 (Chrome, Safari and Internet Explorer 9 seems to be fine), we're seeing some strange behaviour when the pagination links are used on the users list in Wagtail's admin area. 

### Steps to Reproduce

1. Log into the wagtail admin area
2. Go to the users list page by clicking the link in the menu **Settings > Users**
3. Scroll to the bottom of the first page and click on the **Next** link in the bottom right
4. The pagination link takes you to the correct URL, and the correct users flash up for a split second, but then something kicks in and redirects you to a page without the page number in the querystring (so back to the first page).

The expected behaviour would be that you stay on page 2, and not be redirected away from it.

I'm guessing it has something to do with search feature prematurely initiating a search, as the search input is focussed on page load.

### Technical details

* Django version: 1.10.4
* Wagtail version: 1.8.1
* Browser version: Issue has been confirmed in Internet Explorer 10 and 11 (on different windows versions)

**Comment by ralphjacobs** [comment]
Problem found!

core.js ->         // auto focus on search box
        $(window.headerSearch.termInput).trigger('focus');
triggers a         $(window.headerSearch.termInput).on('input', function() {
which triggers a search in IE10 + IE11.

https://connect.microsoft.com/IE/feedback/details/810538/ie-11-fires-input-event-on-focus

Now the solution :)

**Comment by jjanssen** [comment]
Merged in cf815e8 with PR #3476
