### ISSUE TITLE
Cloudflare API v4 error message may cause TypeError.

### ISSUE THREAD

**Issue by hdnpl** [wagtail/wagtail#3436]
### Issue Summary

Wagtail's Cloudflare frontend cache backend assumes that error message is a string. It causes TypeError when a message is boolean.

Example response_json from Cloudflare API: 
```
{'errors': 
    [
        {'code': 1082, 'message': False},
        {'code': 1016, 'message': 'One or more cache purge errors'}
    ],
 'messages': [],
 'result': None,
 'success': False}
```

Backend.py 104 line:

`error_messages = ', '.join([err['message'] for err in response_json['errors']])`

### Steps to Reproduce

1. Incorrectly setup domain in Cloudflare zone
2. Setup Cloudflare backend in wagtail app
3. Try to publish any modified page.

### Technical details

* Cloudflare API version: v4
* Wagtail version: 1.9

**Comment by gasman** [comment]
Fixed in #3437
