### ISSUE TITLE
cannot start wagtail in an alpine Linux container

### ISSUE THREAD

**Issue by digrouz** [wagtail/wagtail#3438]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

manage.py runserver coredumps when I try to start wagtail:
```
# python3 manage.py runserver
Performing system checks...

Segmentation fault (core dumped)
```
dmesg reports:
`python3[4738]: segfault at 7fbc7e14fff8 ip 00007fbc7ed934da sp 00007fbc7e14fff0 error 6 in libpython3.5m.so.1.0[7fbc7ec8e000+3d6000]`

Any  idea what's wrong ? How do I know what's in the coredump ?  I think I followed closely the installation guide.

### Steps to Reproduce
I did start an empty alpine linux container and then I ran the following commands in the same order:
```
apk add python3-dev g++ gcc musl-dev wget make cmake zlib-dev libjpeg-dev libwebp-dev libpng-dev tiff-dev jasper-dev linux-headers postgresql-dev
apk add python3 zlib libjpeg libwebp libpng tiff libjasper
ln -s /usr/include/locale.h /usr/include/xlocale.h
pip3 install cython numpy
wget --no-check-certificate https://github.com/Itseez/opencv/archive//master.zip -O /tmp/opencv.zip 
cd /tmp && unzip /tmp/opencv.zip
cd /tmp/opencv-master
mkdir build && cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF  -D WITH_FFMPEG=NO -D WITH_IPP=NO -D WITH_OPENEXR=NO ..
make && make install
pip3 install wagtail django-redis psycopg2 wand
mkdir /wagtail && cd /wagtail
wagtail start mysite
cd mysite
pip3 install -r requirements.txt
python3 manage.py migrate
python3 manage.py createsuperuser
python3 manage.py runserver
```

### Technical details

* Python version: 3.5.2
* Django version: 1.10.6.
* Wagtail version: 1.9
* Browser version: not working up to there.

**Comment by gasman** [comment]
Hi @digrouz,

I can confirm I'm seeing this when using vagrant with https://atlas.hashicorp.com/maier/boxes/alpine-3.4-x86_64 as the base image - trying to pin down exactly what's triggering it now. This is very unlikely to be a Wagtail-specific issue, since Wagtail is pure Python code - a segfault would have to originate from (Alpine's build of) the Python interpreter, or one of Wagtail's native dependencies such as Pillow.

**Comment by gasman** [comment]
From further experimenting, and reading related issues such as https://github.com/python-pillow/Pillow/issues/1935 and https://github.com/lovell/sharp/issues/242, it appears that Alpine Linux (and specifically the musl-libc library it uses) has a very limited stack size by default, and Wagtail is hitting that limit. I've replicated the issue on a plain Django project by adding `from import1 import foo` to `urls.py`, where `import1.py` is a module consisting of `from import2 import foo` and so on up to `import30`. 

It looks like you can raise the limit by adding a line such as the following to `manage.py`, just after the `from __future__ import` line:

    import threading; threading.stack_size(100000)

...but personally I'd recommend switching to a more tried-and-tested Linux distro such as Ubuntu or Debian. If Alpine needs a workaround for something as routine as this, I suspect there'll be more problems further down the line..

**Comment by digrouz** [comment]
ok, thanks for figuring out what was the issue, I'll give a try to ubuntu then.
