### ISSUE TITLE
Wagtail inpage menu display with firefox 52

### ISSUE THREAD

**Issue by frague59** [wagtail/wagtail#3443]
### Issue Summary

The wagtail in page menu does not displays with firefox 52, with transitions glitches

### Steps to Reproduce

1. Install firefox 52 (in my case, debian did it to me)
2. Connect and login into a wagtail application 
3. Click on the bird at bottom right of a page 

The menu items does not displays anymore. I think the problems come from the css transitions

### Technical details

* Python version: 2.7.9 (debian stable)
* Django version: 1.10.6
* Wagtail version: 1.9
* Browser version: http://whatsmybrowser.org/b/V24FOR9

**Comment by tomdyson** [comment]
![ff-edit-bird-issue](https://cloud.githubusercontent.com/assets/15543/23852570/642352be-07e0-11e7-9f0e-2639229c84fc.gif)

Confirmed on Firefox 52, OS X. Thanks for the report, @frague59

**Comment by gasman** [comment]
Minimal code to replicate the Firefox glitch:

    <!DOCTYPE html>
    <html>
    <head>
        <style>
            .items {
              visibility: hidden;
            }

            .userbar.is-active .items {
              visibility: visible;
            }

            .item {
              background-color: lime;
              opacity: 0;
              transition-duration: 1s;
            }

            .userbar.is-active .item {
              opacity: 1 !important;
            }

        </style>
    </head>
    <body>
        <button id="trigger">click me</button>
        <div class="userbar" id="userbar">
            <div class="items">
                <div class="item">hello world</div>
            </div>
        </div>
        <script>
            document.getElementById('trigger').addEventListener('click', function() {
                var userbar = document.getElementById('userbar');
                userbar.classList.add('is-active');
            }, false);
        </script>
    </body>
    </html>

For some reason the `visibility: hidden` style is being re-applied as soon as the transition is finished...

**Comment by thibaudcolas** [comment]
As far as I can see, this is a bug in Firefox 52.0 not Wagtail (tested in 51, 53.0b2, and 55ish) so I don't think it should qualify as a bug. 

Firefox 52.1 will only be around in one month, and removing `!importants` is great, so I merged anyway.
