### ISSUE TITLE
StreamField: js error in adding component field

### ISSUE THREAD

**Issue by frague59** [wagtail/wagtail#3444]
### Issue Summary

Error in back-office when trying to add items in a StreamField

### Steps to Reproduce

1. Define a StreamField :
```python
class EventPage(PublicationItemPage):
    """
    Simple event, providing:

    + date/time start
    + date/time end
    + location
    + audience
    + a signup link
    """
    #: Date from
    date_from = models.DateField(verbose_name=_('Start date'))

    #: Date to
    date_to = models.DateField(verbose_name=_('End date'),
                               null=True, blank=True,
                               help_text=_('Not required if event is on a single day'))

    #: Time from
    time_from = models.TimeField(verbose_name=_('Start time'), null=True, blank=True)

    #: Time to
    time_to = models.TimeField(verbose_name=_('End time'), null=True, blank=True)

    #: Audience can be `private` or `public`
    audience = models.CharField(verbose_name=_('Audience'), max_length=255, choices=EVENT_AUDIENCE_CHOICES)

    #: A Location
    location = models.ForeignKey('publications.Location',
                                 verbose_name=_('Location'),
                                 on_delete=models.SET_NULL,
                                 null=True, blank=True)

    #: A description of the event
    body = StreamField([('paragraph', blocks.RichTextBlock()),
                        ('image', ImageChooserBlock()),
                        ('url', blocks.URLBlock()),
                        ('date', blocks.DateBlock()),
                        ('page', blocks.PageChooserBlock())],
                       verbose_name=_('Body'),
                       null=True, blank=True)
```
2. Defines some content panels 
```python
# Content panels
    content_panels = [FieldPanel('title', classname="full title"),
                      FieldPanel('date_from'),
                      FieldPanel('date_to'),
                      FieldPanel('time_from'),
                      FieldPanel('time_to'),
                      FieldPanel('location'),
                      FieldPanel('audience'),
                      FieldPanel('signup_link'),
                      FieldPanel('body'), ]
```
3. When adding a new Event, I've some weird comportment

4. When recording, I've a 500 error :

Internal Server Error: /admin/pages/add/publications/eventpage/7/

MultiValueDictKeyError at /admin/pages/add/publications/eventpage/7/
"u'body-0-deleted'"

### Technical details

* Python version: 2.7.9
* Django version: 1.10.6
* Wagtail version: 1.9
* Browser version: firefox 51 / firefox 52 / chrome 57

**Comment by Proper-Job** [comment]
@frague59 body should be added to content_panels using a StreamFieldPanel, not a FieldPanel.
Does that help?

**Comment by frague59** [comment]
![optimised](https://cloud.githubusercontent.com/assets/1118696/23855895/c9d9c130-07f7-11e7-9af9-4c1f88f7f71d.gif)

**Comment by frague59** [comment]
JS error: 

Uncaught TypeError: Cannot read property 'initializer' of undefined
    at Object.onInitializeMember (stream.js:87)
    at postInsertMember (sequence.js:95)
    at Object.self.insertMemberAtStart (sequence.js:196)
    at Object.onChooseBlock (stream.js:140)
    at HTMLButtonElement.<anonymous> (stream.js:60)
    at HTMLButtonElement.dispatch (jquery-2.2.1.js:4732)
    at HTMLButtonElement.elemData.handle (jquery-2.2.1.js:4544)

**Comment by Proper-Job** [comment]
@frague59 Did you see my comment, I believe we commented at the same time? Did that solve your issue?

**Comment by frague59** [comment]
Yeah, got it, StreamFieldPanel solves the problem, Sorry !

**Comment by jasmine-scott** [comment]
Also, note that if you are trying to use a StreamField in the Settings tab (instead of Pages) on wagtail you must use:
`panels = [
        StreamFieldPanel('body'),
    ]` and not `content_panels`. This causes a JS error as well.
