### ISSUE TITLE
userbar stopped working in Firefox 52

### ISSUE THREAD

**Issue by derhedwig** [wagtail/wagtail#3455]
### Issue Summary

When trying to open the userbar on Firefox 52 it opens only to immediately close afterwards.

### Steps to Reproduce

1. Login to your wagtail site
2. Return to frontpage
3. Click on the wagtail bird aka userbar

### Technical details

* Python version: 3.4.2
* Django version: 1.10.6
* Wagtail version: 1.9
* Browser version: Firefox 52

### Fix

The following CSS fixes the problem, but disables the opening animation:
```
.wagtail-userbar__item {
  transition: none !important;
}
```

**Comment by gasman** [comment]
Hi @derhedwig - thanks for the report! This was reported earlier (#3443) and has now been fixed in #3447.
