### ISSUE TITLE
usability: new item order at bottom or top

### ISSUE THREAD

**Issue by maartenkling** [wagtail/wagtail#3457]
Having a page including many subpages, ordered in the way you like. When you create a new page, this will alway be at the bottom. In many use-cases the client would like to choose, bottom or top. So they don't have to rearrange all the items.

**Comment by gasman** [comment]
I believe #882 will address this.

Giving editors the option of inserting new pages at the top would help in the cases where we want content to be listed newest-first, such as a blog. However, in that situation, editors shouldn't have to care about ordering at all - it should happen automatically. #882 proposes a way of specifying an automatic ordering on the parent page model, such as newest-first, title, or some page-model-specific field such as event date. There will still be cases where we want a manual ordering that doesn't correspond to any particular property of the page (such as on a site's top level menu, where 'news' typically comes first and 'contact us' comes last, simply by convention) - but I believe that in those cases the list of pages will be fairly short and not change very often, so the existing interface for manual ordering works fine (and 'insert at top' / 'insert at bottom' wouldn't help much there).
