### ISSUE TITLE
UX: Top bar is too green on green

### ISSUE THREAD

**Issue by maartenkling** [wagtail/wagtail#3458]
Multiple clients complaining about the green on green on green in the top where the main actions are.
<img width="667" alt="wagtail_-_home" src="https://cloud.githubusercontent.com/assets/946684/24032730/c48a7b94-0ae9-11e7-8935-10ec28030583.png">

**Comment by heymonkeyriot** [comment]
@maartenkling see also #2224. Contrast is an issue for quite a few elements imho.

**Comment by thibaudcolas** [comment]
Closing this now with the merge of #4788.
