### ISSUE TITLE
PagePermissionTester.can_reorder_children checks is_creatable

### ISSUE THREAD

**Issue by dnsl48** [wagtail/wagtail#3465]
### Summary
The current wagtailcore.models.PagePermissionTester.can_reorder_children implementation just returns self.can_publish_subpage(), which has a side-effect of checking the page has creatable children. In case it has children with `is_creatable=False`, we cannot reorder them, even though we have permissions to edit them (i.e. only creation of new ones should be restricted).

Method `can_reorder_children` should probably be reimplemented in a different way, checking only editing permissions for children.

### Steps to reproduce

1. Create a parent page model
2. Create a child page model
3. Make `is_creatable` field of the child to be a descriptor returning false in case there are more then two instances. For example (pseudo code):
```python
class NoMoreThanTwoDescriptor(object):
    def __get__(self, obj, cls):
        return cls.objects.count() < 2

class ChildPage(Page):
   is_creatable = NoMoreThanTwoDescriptor()

class IndexPage(Page):
    subpage_types = [ChildPage]
```

4. Go to the admin panel and create the IndexPage and 2 children.
5. Ordering of the children will not be available in the admin panel

### Technical details

* Wagtail version: `1.9`

**Comment by gasman** [comment]
Fixed in #12156
