### ISSUE TITLE
Multiply images delete

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [wagtail/wagtail#3475]
Not really an issue. But it is really annoying to delete images one by one if needed to delete more than 10.
Way to  represent : 
1) Upload 1000 - 2000 images 
2) Open admin page and start to delete them.
Sorry if i complain about something already implemented. 
May be exist something to delete in one click ?

**Comment by khink** [comment]
I think this is a duplicate of https://github.com/wagtail/wagtail/issues/121.

**Comment by gasman** [comment]
I think so too. Thanks for the report @jpVm5jYYRE1VIKL!
