### ISSUE TITLE
wagtailimages.Image - 'NoneType' object has no attribute 'size'

### ISSUE THREAD

**Issue by bmcool** [wagtail/wagtail#3486]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

wagtailimages.Image - 'NoneType' object has no attribute 'size'

### Steps to Reproduce

1. Upload Image 'A' to AWS S3
2. Remove 'A' from AWS S3
3. Edit 'A' on Wagtail admin
4. Error ''NoneType' object has no attribute 'size''

### Technical details

* boto==2.46.1
* Django==1.10.6
* django-storages==1.5.2
* wagtail==1.9

The error occur from here.
```
    def get_file_size(self):
        if self.file_size is None:
            try:
                self.file_size = self.file.size
            except OSError:
                # File doesn't exist
                return
            self.save(update_fields=['file_size'])
```

**Comment by sonnybaker** [comment]
I had this issue with using the `s3boto3.S3Boto3Storage` backend in Storages - switching to ` storages.backends.s3boto.S3BotoStorage` solved it.

**Comment by bmcool** [comment]
I really use it.
```
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
```

**Comment by gasman** [comment]
This is expected behaviour - if you delete a file (from S3 or anywhere else) that Wagtail is using as an image, then naturally it's going to throw an error when Wagtail tries to access the file again.

(If I've misunderstood, please clarify and I'll be happy to re-open...)
