### ISSUE TITLE
coveralls service links to old repo

### ISSUE THREAD

**Issue by chimeno** [wagtail/wagtail#3506]
Not a code issue, but it seems that Coveralls is linking to the old repo since no builds have been executed since December 2016.
https://coveralls.io/github/torchbox/wagtail

**Comment by mvantellingen** [comment]
I propose to just switch to codecov.io. It's much better. I can do the implementation if there are no objections

**Comment by thibaudcolas** [comment]
No particular objections but why is it better and what issues do we have with Coveralls that it will solve?

**Comment by mvantellingen** [comment]
Fair question, so codecov.io has imo the following benefits over coveralls:

 - A better webinterface (https://codecov.io/gh/django-oscar/django-oscar vs https://coveralls.io/github/torchbox/wagtail)
 - A Chrome plugin to see code coverage while browsing GitHub (https://github.com/codecov/browser-extension)
 - Github PR's status indicators for code coverage changes
 - Better configuration options (https://github.com/codecov/support/wiki/Codecov-Yaml)

**Comment by gasman** [comment]
Updated in df4708f088ea3349797dd4772d1c1cb83957a377.
Happy to switch to codecov.io - coveralls does feel a bit clunky.
