### ISSUE TITLE
API search order has no effect

### ISSUE THREAD

**Issue by BertrandBordage** [wagtail/wagtail#3514]
Steps to reproduce:
- use wagtail 1.9 & elasticsearch 2 or any version of [wagtail-pg-search-backend](https://github.com/wagtail/wagtail-pg-search-backend)
- install Wagtail’s API
- go to `http://localhost:8000/api/v2/pages/?search=a+non-empty+search&order=first_published_at` where you replace `a+non-empty+search` with any search query that returns results
- go to `http://localhost:8000/api/v2/pages/?search=a+non-empty+search&order=-first_published_at` (with the same replacement as before)
- compare the results

As you should see, ordering has no effect on the actual order of results.
I discovered this issue while trying to implement search ordering (not to be confused with ranking) in wagtail-pg-search-backend. And I couldn’t find how to do it with the current way search is implemented.

So I guess searching doesn’t handle custom ordering. Unfortunately, [the opposite is written in the docs](http://docs.wagtail.io/en/v1.9/advanced_topics/api/v2/usage.html#search-operator), even with details on how to use it.

**Comment by kaedroho** [comment]
Hi @BertrandBordage 

I can't reproduce this issue locally, are you sure that all your pages have a ``first_published_at`` value? (the pages in Wagtaildemo have probably all got null in that field).

**Comment by BertrandBordage** [comment]
Hi @kaedroho,

Yes, all pages have a `first_published_at` value, as you can see below.
The pages are sorted by id or maybe by path. It is the same order as `first_published_at` by chance, but if I sort them in a descending order, nothing changes as you can see below.

Note that sorting works when I don’t use search.

![unsorted-api](https://cloud.githubusercontent.com/assets/1119169/24502143/cfafd1d2-154c-11e7-8cc9-45978511afda.png)

Maybe I missed something in the docs? I followed exactly the installation docs, but I could still miss something.

**Comment by DanAtShenTech** [comment]
@BertrandBordage I am implementing search for the first time (database is PostgreSQL).  I placed an `.order_by('title')` at the end of my documents queryset just before the `.search(query)`.  I was stunned to see that it had no effect.  Some searching turned up this issue started by you.  Is it true that we cannot order search results?

**Comment by BertrandBordage** [comment]
@DanAtShenTech It’s not related. By default, when you search, it sorts result by relevance. Do `.order_by('title').search(query, order_by_relevance=False)` to keep your ordering, as seen in the reference docs: http://docs.wagtail.io/en/v2.0/reference/pages/queryset_reference.html#wagtail.core.query.PageQuerySet.search

**Comment by DanAtShenTech** [comment]
Thanks very much @BertrandBordage!  It would be nice if Read the Docs had a promoted search results feature like Wagtail does.  I think I was searching on `order_by` which, of course, turned up no relevant results.  It would be nice if a search on `order_by` also brought you to the page with `order_by_relevance`.

**Comment by m1kola** [comment]
I recently hand a similar issue with:

* Elasticsearch 5
* Django 2.1.3 and 2.1.5
* Wagtail 2.3 and 2.4. Pretty sure it affects 2.5 too.

This happens because Wagtail API sets reverse order using the [`reverse()` on a `QuerySet`](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#reverse):

https://github.com/wagtail/wagtail/blob/58135ccf6ea06095379c32e07578095545b37762/wagtail/api/v2/filters.py#L79-L95

And Elasticsearch backends do not detect reverse order set using this method:

https://github.com/wagtail/wagtail/blob/58135ccf6ea06095379c32e07578095545b37762/wagtail/search/backends/base.py#L120-L140

Note that `wagtail.contrib.postgres_search.backend` doesn't use `_get_order_by` method, so it works with fine.

**Comment by m1kola** [comment]
#5318 should hopefully fix the issue with API. To make code snippets work from my previous comment - we will also need to make changes in the elastcisearch backends. I think it's a separate issue so I created #5319

**Comment by thibaudcolas** [comment]
A few years later – just trying to reproduce this and I’m not able to, so I assume this has either been fixed, or is specific to the Elasticsearch backend and as such is better covered by #5319.

My test case:

```
https://wagtail.org/api/v2/pages/?search=headless
https://wagtail.org/api/v2/pages/?search=headless&order=first_published_at
https://wagtail.org/api/v2/pages/?search=headless&order=-first_published_at
```

All three queries retrieve three pages. The "relevance" order looks decent enough, the `first_published_at` order is different and seems correct, and `-first_published_at` is the opposite as expected.
