### ISSUE TITLE
Replace Ruby's SCSS Lint with Stylelint

### ISSUE THREAD

**Issue by jjanssen** [wagtail/wagtail#3516]
During the Wagtail sprint in Arnhem there were some questions about how runs the `scss-lint`. Within development this actually requires an additional dependency to Ruby to install its `scss-lint` gem dependency. Within the current ecosystem it is also possible to move this linting process into the NodeJS environment, where already all our front-end tooling resides.

In todays core meeting we have discussed `stylelint` and `scss-lint` for node. Based on our own experiences we decided to pursue the `stylelint` implementation with scss functionalities, mainly because our experience with `scss-lint` for node isn't that great due the frequent problems with its underlying parser.

If we implement this we can ditch the Ruby dependency when developing on Wagtail.

**Comment by thibaudcolas** [comment]
🎉  next steps: #3804.
