### ISSUE TITLE
Add autosave to the edit

### ISSUE THREAD

**Issue by sasha0** [wagtail/wagtail#3527]
It would be great to add autosave to the content editor with given periodicity , since revisions already implemented, so that admin can restore changes in case of unexpected issue (with browser, network connection, hardware etc).

Bringing it up again since #450 is closed.

**Comment by BertrandBordage** [comment]
I included a similar feature in #3383. It’s only for previews and it sends data via AJAX calls.
Since this is a quite heavy feature, I think it would be better to add it if Django supports websockets or when Channels will become more mature. See [the Django blog post](https://www.djangoproject.com/weblog/2016/sep/09/channels-adopted-official-django-project/) about it.

**Comment by sasha0** [comment]
It's not clear if Channels going to be part of Django anytime soon, and it's quite stable now.

I'd be happy to provide PR for this.

**Comment by BertrandBordage** [comment]
I only used Channels once so you probably know better. (However I often use websockets with Flask, so I can still make a review)
A pull request would be very much appreciated, thanks!

**Comment by tmsndrs** [comment]
+1

**Comment by rberrima** [comment]
Hello, do we know the status on the request for an auto save functionality in Wagtail?

**Comment by BertrandBordage** [comment]
@tomdyson It’s on the 2017-2018 roadmap we created last year ;) https://github.com/wagtail/wagtail/projects/2
We should probably rename it to 2018-2019 Roadmap :s

**Comment by tomdyson** [comment]
Whoops, sorry!

**Comment by rberrima** [comment]
Thanks a lot guys!

**Comment by thibaudcolas** [comment]
👋 for people interested in this, there is a much more recent Discussions thread: #7636. I’m going to close this issue now. As the thread is much more up-to-date, it’ll be where we share updates on this over time.

The high-level state of this is we’re interested in bringing autosave to Wagtail, have made visual designs for this as well as high-level tech analysis of implementation options (as per the thread). This feels like a large change though, and right now we’re [looking for funding](https://wagtail.org/blog/build-update-on-new-page-editor/) to bring this specific feature to Wagtail.
