### ISSUE TITLE
Userbar JS exit condition looks broken

### ISSUE THREAD

**Issue by HannesWaechter** [wagtail/wagtail#3530]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

wagtailadmin userbar.js line 11:

    if (!'classList' in userbar)

evaluates to

    if(false in userbar)

this might not be the wanted behavior?

**Comment by gasman** [comment]
Check removed in 6630d4b66c4c5291c76c50e8c7c8c2f220e30268, as per #3531.

**Comment by gasman** [comment]
Thanks @HannesWaechter!
