### ISSUE TITLE
Facebook oEmbed support

### ISSUE THREAD

**Issue by ahayzen** [wagtail/wagtail#3532]
### Issue Summary

When embedding facebook posts or videos using streamfield they are unsupported.

### Steps to Reproduce

1. Create a post
2. Add a streamfield embed part
3. Enter a facebook post/video eg https://www.facebook.com/20531316728/posts/10154009990506729/
4. Note nothing is show in the post

It appears support just needs to be added to this file - https://github.com/wagtail/wagtail/blob/1874b8b259e1295370b1c2122966d96668db7eec/wagtail/wagtailembeds/oembed_providers.py

Facebook oEmbed docs - https://developers.facebook.com/docs/plugins/oembed-endpoints

Note a stackoverflow answer suggests that mobiles may need to request a subtly different domain - http://stackoverflow.com/questions/5752345/does-facebook-support-oembed/33895663#33895663

### Technical details

* Python version: Python 3.5.2
* Django version: Django (1.10.5)
* Wagtail version: wagtail (1.9)
* Browser version: Firefox (52)

**Comment by m1kola** [comment]
@ahayzen, thanks for the report.

I've prepared PR - #3545. Could you, please, review and/or test it?
