### ISSUE TITLE
RoutablePage subclasses cannot override routes

### ISSUE THREAD

**Issue by fabiommendes** [wagtail/wagtail#3533]
Say you have an abstract routable model

```python
from wagtail.wagtailcore.models import Page
from wagtail.contrib.wagtailroutablepage.models import RoutablePageMixin, route

class AbstractPage(RoutablePageMixin, Page):
    class Meta:
        abstract = True
    
    @route(r'^foo/$')
    def view_func(self, request):
        ...

class ConcretePage(AbstractPage):
    @route(r'^foo/$')
    def view_func(self, request):
        ...

```

A subclass cannot override the route since RoutablePageMixin orders the urlpattern priorities using order of definition. This happens because get_subpage_urls() sort routes by the index
they were created. This have the nice property of using the same order as the routes were
defined in the source code, but brakes inheritance.

**Comment by gasman** [comment]
Thanks for the report @fabiommendes! This should be addressed by #3344 (specifically commit https://github.com/wagtail/wagtail/pull/3344/commits/2918735684cbbbc1a71a82fe79bfe629ebde32e0).
