### ISSUE TITLE
delete signal listeners should use on_commit

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#3534]
The delete signal handlers like https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailimages/signal_handlers.py#L9 should use `transaction.on_commit()` so that they wait to delete until the sql delete is successful

Something like:
```
from django.db import transaction
def post_delete_file_cleanup(instance, **kwargs):
    transaction.on_commit(lambda: instance.file.delete(False))
```

**Comment by BertrandBordage** [comment]
That’s right, we may lose files otherwise.

Documents are also concerned: https://github.com/wagtail/wagtail/blob/master/wagtail/wagtaildocs/signal_handlers.py

`transaction.on_commit` was added in Django 1.9 if I remember well.
Currently, Wagtail still supports Django 1.8, so this has to wait a bit, or we can implement it with a check in the meantime.

Would you like to provide a pull request for this?

**Comment by thenewguy** [comment]
@BertrandBordage Sure. I will try to get to it tomorrow. I've already written tests that I should be able to copy and paste

**Comment by BertrandBordage** [comment]
Awesome!

**Comment by thenewguy** [comment]
@BertrandBordage have a problem with me making the signal handlers generic and moving them to wagtailcore so they don't have to be duplicated between wagtailimages and wagtaildocs?

**Comment by thenewguy** [comment]
[This test](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtaildocs/tests.py#L853) is failing because the test uses a file name that clashes with other tests that do not clean up their test documents.

The other failing tests occur on databases other than sqllite are slightly more difficult to fix because the vagrant-wagtail-development doesn't seem to offer testing on the different databases and travis tests are slow.  Seems to be related to `serialized_rollback = True` which wasn't required when I originally wrote the tests against postgres.  But copying them over to the vagrant-wagtail-develop box seems to force sqlite
