### ISSUE TITLE
Focal point fails for large images

### ISSUE THREAD

**Issue by krisero** [wagtail/wagtail#3547]
### Issue Summary

Focal point not working for large images (1000px +).

### Steps to Reproduce

1. Upload image with size larger than 1000px.
2. Start editing this image.
3. Add focal point
4. Save. 

### Expected result:
Image focal point is saved.

### Actual result:
Error appears: The image could not be saved due to errors. 

This error occurs with wagtail 1.9. It is working with Wagtail 1.6 and django 1.9 . Any idea how to fix this?

### Technical details

* Python version: 3.5.3
* Django version: 1.10.7
* Wagtail version: 1.9
* Browser version: Chrome 57

**Comment by krisero** [comment]
This problem may occurs because of localize used for image sizes, so over 1k it fails.
`<img alt="a_wooden_house_forest-wallpaper-1024x576121233.jpg" height="450" src="/media/images/a_wooden_house_forest-wallpaper-1024x576.max-800x600.jpg" width="800" data-original-width="1&nbsp;024" data-original-height="576" class="show-transparency" style="display: block; visibility: visible; width: 470px; height: 264px; border: none; margin: 0px; padding: 0px; position: absolute; top: 0px; left: 0px;">`

**Comment by gasman** [comment]
Thanks for the report @krisero! It looks like the localisation is very likely to be the problem. We've made similar fixes elsewhere in #3478.

**Comment by saevarom** [comment]
I can't reproduce this issue on wagtail 1.12.1 with django 1.10.7. I've tried a bunch of different locales, including some the have non-breaking spaces as thousands separators, like French.

Also, I can't see from the template code (https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailimages/templates/wagtailimages/images/edit.html) that any localization is taking place when writing out the image size...

Am I missing something?

**Comment by gasman** [comment]
Hi @saevarom - I believe it's the `USE_THOUSAND_SEPARATOR = True` setting that triggers this issue. (@krisero, can you confirm?)

**Comment by saevarom** [comment]
Ahh, of course. I can reproduce with that setting.
