### ISSUE TITLE
Core API Schemas support

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#3549]
Since version 3.4 Django Rest Framework provides an ability to generate API schemas automatically. Nice feature that also allows to use DRF's [built-in interactive API documentation](https://www.django-rest-framework.org/community/3.6-announcement/).

Unfortunately `WagtailAPIRouter` and endpoint classes (these that inherited from the `wagtail.api.v2.endpoints.BaseAPIEndpoint` class) do not support this feature.

`rest_framework.schemas.SchemaGenerator` generates wrong schema documents for them: 

```
coreapi get http://localhost:8000/api_docs/
<Document "http://localhost:8000/api_docs/">
    admin: {
        api: {
            v2beta: {
                listing_view()
                detail_view(id)
            }
        }
    }
    api: {
        v2: {
            listing_view()
            detail_view(id)
        }
    }
```

So there is no way to access each endpoint's schema separately: you can only access a schema for an endpoint that has been registered last. 

This happens because `BaseAPIEndpoint`-based classes use custom method names, so they fall [under this condition](https://github.com/encode/django-rest-framework/blob/3.6.2/rest_framework/schemas.py#L659).

Refs:
* http://www.django-rest-framework.org/api-guide/schemas/
* http://www.coreapi.org/

**Comment by thibaudcolas** [comment]
I’m going to close this in favour of #6209. It seems at this point CoreAPI is no longer relevant as a separate concept from OpenAPI.

My understanding is CoreAPI was built for DRF specifically, as part of their OpenAPI schema generation support. The [DRF schemas docs](https://www.django-rest-framework.org/api-guide/schemas/) say their built-in support for schema generation is deprecated, and they instead recommend [drf-spectacular](https://drf-spectacular.readthedocs.io/en/latest/readme.html).
