### ISSUE TITLE
Page names with unicode throw logger errors

### ISSUE THREAD

**Issue by loleg** [wagtail/wagtail#3551]
### Issue Summary

Noticed this in the logs in a more or less rudimentary installation of Wagtail:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 19: ordinal not in range(128)
...
File "/usr/local/lib/python3.6/site-packages/wagtail/wagtailcore/models.py", line 1520, in publish
     logger.info("Page published: \"%s\" id=%d revision_id=%d", page.title, page.id, self.id)
     Message: 'Page published: "%s" id=%d revision_id=%d'
     Arguments: ('Geschäftsstelle', 19, 95)
```

This suggests to me that [wagtailcore/models.py](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailcore/models.py#L1455) and other places should use Unicode format strings for full Python 3 support.

### Steps to Reproduce

1. Create a page with umlauts or other funny characters
2. Edit it, and see bug in the logs

### Technical details

* Python version: 3.6
* Django version: 1.10.6
* Wagtail version: 1.9

**Comment by lb-** [comment]
@loleg next major Wagtail version will be Python 3.X only so this may be a non-issue in the future.

**Comment by loleg** [comment]
Good to know - I think we can close this. Thanks.
