### ISSUE TITLE
IntegrityError wagtailcore_page_path_key already exists

### ISSUE THREAD

**Issue by lud2k** [wagtail/wagtail#3553]
I have seen a couple errors like this in our wagtail logs:
django.db.utils.IntegrityError: duplicate key value violates unique constraint "wagtailcore_page_path_key"
DETAIL:  Key (path)=(00010001000G00X9) already exists.

This seems related to: https://github.com/django-treebeard/django-treebeard/issues/53

Sounds like this happened when two page creation were very close (4 milliseconds apart).
Is there any chance this could be fixed in wagtail?

Thanks,
Ludo.

**Comment by gasman** [comment]
Thanks for the report @lud2k! It looks like the Treebeard issue you link to would indeed explain this behaviour, and so this would be best fixed within Treebeard itself rather than trying to work around the issue in Wagtail.
