### ISSUE TITLE
Preview in 1.10rc1 fails if ParentalManytoManyField changes or is set in page

### ISSUE THREAD

**Issue by bauersebastian** [wagtail/wagtail#3564]
### Issue Summary

I make use of the ParentalManytoManyField in a model (for blog categories).
When we tick one ore more categories and save the draft the preview is no longer working. This only happens to newly created pages since the upgrade to 1.10rc1.
On the database everything is fine, since the relationships are saved properly, once the page is published.

In class PreviewOnEdit in wagtailadmin/views/pages.py the method get() --> if form.is_valid() returns false, because the Django Form Validation returns an error 'Please insert list with values'. 
I get a German error message - I hope the one I mention is correct translated for English.

### Steps to Reproduce

1. This is the first step
Make use of the ParentalManytoManyField in a model.
Create a new page and tick several foreignkey entries. Save that draft.

2. This is the second step, etc.
Open the preview of the page. You should see preview error page of wagtail, since the Django Form Validation throws an error, as mentioned above.

### Technical details

* Python version: 3.6.0
* Django version: 1.11
* Wagtail version: 1.10rc1
* Browser version: Chrome latest version

**Comment by bauersebastian** [comment]
Not sure if this issue is related to #3412

**Comment by gasman** [comment]
Confirmed on a fresh 1.10rc1 project. Thanks for reporting, @bauersebastian!

**Comment by gasman** [comment]
Looks like the problem here isn't specifically with (Parental)ManyToManyFields, but rather with our handling of multiple-value fields (such as checkboxes) in form submissions. Adding `print(repr(post_data))` to the `PreviewOnEdit.get_form` method allows us to see the data as it exists on the POST request from the form, and as retrieved on the GET that displays the preview:

	<QueryDict: {'expire_at': [''], 'title': ['test'], 'csrfmiddlewaretoken': ['Dc5IIlwN1YlqnWJXEiXb1ui0uwADi1uT4GFYnZdjH8uMfWVa9tROrxinSC0AyLjc'], 'search_description': [''], 'go_live_at': [''], 'seo_title': [''], 'next': [''], 'slug': ['test'], 'categories': ['2', '3']}>
	[26/Apr/2017 16:11:08] "POST /admin/pages/4/edit/preview/ HTTP/1.1" 200 18
	{'title': 'test', 'expire_at': '', 'go_live_at': '', 'next': '', 'slug': 'test', 'search_description': '', 'seo_title': '', 'categories': '3', 'csrfmiddlewaretoken': 'Dc5IIlwN1YlqnWJXEiXb1ui0uwADi1uT4GFYnZdjH8uMfWVa9tROrxinSC0AyLjc'}
	[26/Apr/2017 16:11:09] "GET /admin/pages/4/edit/preview/ HTTP/1.1" 200 6031

The conversion from a `QueryDict` to a plain dict means that we lose support for multiple values on the `categories` field.

**Comment by gasman** [comment]
Have now created https://github.com/gasman/wagtail/tree/fix/preview-m2m to work on this. Failing test here: https://github.com/gasman/wagtail/commit/bcf15e6429e412f4dcca2eaa8b1c4d8a641e9606
