### ISSUE TITLE
sitemap.xml lastmod should use date last published

### ISSUE THREAD

**Issue by mikemonteith** [wagtail/wagtail#3565]
### Issue Summary

sitemap.xml's `<lastmod>` should show the date that a page was last published to live, not the date that it was last saved as a draft.

### Steps to Reproduce

1. Create a page
2. See `<lastmod>` value in sitemap.xml
3. Make a change to the page (save as draft)
4. `<lastmod>` value in sitemap.xml has changed (remember to refresh the sitemap cache)

### Relevant code
https://github.com/wagtail/wagtail/edit/master/wagtail/contrib/wagtailsitemaps/sitemap_generator.py#L15

**Comment by ababic** [comment]
Related issue: #771
