### ISSUE TITLE
Update docs for "Customising generated forms"

### ISSUE THREAD

**Issue by patta42** [wagtail/wagtail#3571]
The `contents_panel` definition of the example in the docs-section [Customising generated forms](https://github.com/wagtail/wagtail/blob/master/docs/advanced_topics/customisation/page_editing_interface.rst#customising-generated-forms) is confusing, since it does not match the `Page` model used in the example. I suggest to use:

```python
content_panels = [
    FieldPanel('start_date'),
    FieldPanel('end_date),
]
```

**Comment by gasman** [comment]
Thanks for the report @patta42! Now fixed in a3b048d4035dca7ea87814c17893d33691a159b6 (on master) and 6bb91b8f9b1255df1e051dffec3af4bf5f0eaecf (on stable/1.10.x).
