### ISSUE TITLE
Unpublished/not-yet-approved changes found in search

### ISSUE THREAD

**Issue by kbayliss** [wagtail/wagtail#3576]
### Issue Summary

Similar to https://github.com/wagtail/wagtail/issues/3239, when new content is submitted for moderation on an existing live page, the new (not yet approved) content is searchable.

### Steps to Reproduce

Using the default Wagtail search URL and form -

- urls.py: `from wagtail.wagtailsearch import urls as wagtailsearch_urls`
- Form action: `{% url "wagtailsearch_search" %}`

1. Edit an indexed field of an existing published page
2. Insert a unique term in the indexed field
3. Click 'Submit for moderation'
4. On the frontend search for the unique term.
5. The edited page will be returned in the results

### Technical details

* Python version: 2.7.12
* Django version: 1.10.4
* Wagtail version: 1.8.1
* Elasticsearch version: 2.4.0

**Comment by gasman** [comment]
Hi @kbayliss,
I believe this is the exact same issue as #3239 - the bug that happened when saving as draft would also be triggered when submitting for moderation. Please can you upgrade to Wagtail 1.8.2 (or 1.9.1) and see if this still occurs?

**Comment by kbayliss** [comment]
Thanks @gasman, I had misread which version of Wagtail that was fixed for as 1.8.1, d'oh. I'll upgrade ASAP and come back if that doesn't resolve things, though it sounds as though it will.

Cheers
