### ISSUE TITLE
Support custom tag models in autocomplete view

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#3577]
[The tag autocomplete view in wagtailadmin](https://github.com/wagtail/wagtail/blob/85bcd5a176f54b628e6022511a25c10345fd522f/wagtail/wagtailadmin/views/tags.py) currently hard-codes the default `taggit.models.Tag` model. This means that if a [custom tag model](http://django-taggit.readthedocs.io/en/latest/custom_tagging.html#custom-tag) is in use, it will fail to provide autocompletions from the correct set of tags. Ideally, we should pick up the tag model from the field that the `AdminTagWidget` is being used on.

**Comment by coredumperror** [comment]
I'd like to implement this fix as a PR, but I've failed to come up with a method of doing so after digging into the code. 

My first thought what that it would make sense to change how `AdminTagWidget` renders the call to `initTagField()`, passing an identifier for the appropriate Tag class (e.g. dotted class path) into the `wagtailadmin_tag_autocomplete` view. But as far as I've been able to determine, `AdminTagWidget` doesn't know which field it's attached to, so I have no idea how to reference the appropriate custom Tag class.

Any advice would be greatly appreciated. My shop needs to implement Site-specific tags, and having the autocompleter only suggest tags that have been previously used on the same site is one of the primary reasons for that.

**Comment by coredumperror** [comment]
Looks like `wagtailadmin.utils.popular_tags_for_model()` is going to need similar treatment, since it's also hard-coded to use `Tag`.

**Comment by coredumperror** [comment]
OK, I've solved the `popular_tags_for_model()` issue, but it ended up being a lot more complicated than I expected. 

As a form of notes to myself, since I've currently got this implemented outside of the Wagtail, and thus can't put it in a PR yet, the original looks like this:

```
def popular_tags_for_model(model, count=10):
    """Return a queryset of the most frequently used tags used on this model class"""
    content_type = ContentType.objects.get_for_model(model)
    return Tag.objects.filter(
        taggit_taggeditem_items__content_type=content_type
    ).annotate(
        item_count=Count('taggit_taggeditem_items')
    ).order_by('-item_count')[:count]
```

The updated version needs to look like this:

```
def popular_tags_for_model(model, count=10):
    """Return a queryset of the most frequently used tags used on this model class"""
    content_type = ContentType.objects.get_for_model(model)
    return model.tags.through.tag_model().objects.filter(**{
        '{}__content_type'.format(model.tags.through.tag_relname()): content_type
    }).annotate(
        item_count=Count(model.tags.through.tag_relname())
    ).order_by('-item_count')[:count]

```

This assumes that the `TaggableManager` field on the model is called `tags`, but that's mentioned as being required in the docs, so I don't think it'll be a problem. It might be possible to query `model` to find out what its `TaggableManager` field is, but I don't know how.

**Comment by gasman** [comment]
We'll hopefully be working on this for Wagtail 2.9 as part of an update to tag handling (see also https://github.com/wagtail/rfcs/pull/28). Proposed approach:

* Update the admin.views.tags.autocomplete URL route to take a tag class's app_label/name as part of the URL, similarly to what we do on page creation and in modeladmin - and use that instead of hard-coding taggit.Tag. (Need to add a check that the resolved model is indeed a tag model, to prevent people from fiddling the URL to leak arbitrary model data)
* Update admin.widgets.AdminTagWidget to accept an optional `tag_model` parameter on init, defaulting to taggit.Tag, and generate the model-specific URL to wagtailadmin_tag_autocomplete accordingly. This will allow devs to set the tag model manually, via `FieldPanel('tags', widget=AdminTagWidget(tag_model=BlogTag))`
* Update the formfield_for_dbfield logic in admin.forms.models so that the tag model is automatically picked up from the TaggableManager field and passed on to the widget - this may involve defining a new Wagtail-specific subclass of taggit.forms.TagField to act as the glue.

**Comment by coredumperror** [comment]
Sounds great!
