### ISSUE TITLE
Add 'last_published_at' field to Page model

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#3578]
Previously discussed in #577 and #771, but doesn't seem to have been raised as a ticket in its own right up to now. Necessary for #3565.

#3302 is related - it adds a foreign key from `Page` to the current live revision (if any), which would give you access to the revision's `created_at` date - although that isn't an exact match for last published date, because pages that go through moderation or scheduled publishing may have an actual publishing date that's some time after the revision was created.

**Comment by thibaudcolas** [comment]
When this is implemented & documented, it would be interesting to know whether this field's value will be equal to `first_published_at` when pages have only been published once. I'm not sure if this is a worthy behavior in all cases, but it would certainly help [my use case](https://github.com/springload/madewithwagtail/commit/eb3aa13cd644702c2268148739698d325fa01cb5#diff-3e829afe9827798877b79ae10e2aa706R95) for this field.

**Comment by gasman** [comment]
@thibaudcolas I'd say that's the correct behaviour, yes - I can't see any logical basis for doing it any other way.
