### ISSUE TITLE
Django 1.11

### ISSUE THREAD

**Issue by EgonFrerich** [wagtail/wagtail#3579]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

wagtail should be compatible with Django 1.11. 

But in line 14 in https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailimages/models.py there is an import flatatt that doesn't work with Django 1.11

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

* Python version: Run `python --version`.
* Django version: Look in your requirements.txt, or run `pip list | grep -i django`.
* Wagtail version: Hover over the Wagtail bird in the admin, or look in the Settings menu, look in your requirements.txt, or run `pip list | grep -i wagtail`.
* Browser version: You can use http://www.whatsmybrowser.org/ to find this out.

**Comment by Terr** [comment]
This has been fixed already but it's not included in a release yet. See #3526

**Comment by gasman** [comment]
@EgonFrerich In future, please fill out the issue details in full. Since you haven't stated your Wagtail version, I can only assume that you're currently using Wagtail 1.9.x.

Django 1.11 support is added in Wagtail 1.10, due for release this week.
