### ISSUE TITLE
check for raw in signal handlers

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#3589]
The signal handlers such as [pre_save_image_feature_detection](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailimages/signal_handlers.py) should check for `raw` to detect loading from a fixture and do nothing in this case.  Otherwise you get an error loading fixtures if the source file doesn't exist and `WAGTAILIMAGES_FEATURE_DETECTION_ENABLED=True`

**Comment by lb-** [comment]
Update - this likely still exists and file content has moved to 

`https://github.com/wagtail/wagtail/blob/main/wagtail/images/signal_handlers.py`
https://github.com/wagtail/wagtail/blob/main/wagtail/images/signal_handlers.py


```python
def pre_save_image_feature_detection(instance, **kwargs):
    # .. add check here for kwargs['raw']
```

See https://docs.djangoproject.com/en/4.0/ref/signals/#pre-save for `raw`

Flagging as good first issue, best to start with unit tests on this and then work towards solving the issue. use `@override_settings` in the unit tests to trigger the exact scenario as described in the parent comment.

**Comment by rd3m** [comment]
I'll have a look at this one.

**Comment by anujaraj** [comment]
Hello,  Can i work on this issue. Thers arent any PRs so if its possible can i try this one?

**Comment by lb-** [comment]
Go for it @anujaraj - before you start on code be sure to follow the steps above and check you can reproduce the issue. Write a comment with any extra info. Including what version you were using of Wagtail/ Django / Python.

**Comment by anujaraj** [comment]
I use the folowing technologies -
Python - 3.6.8
Django- 3.2.12
Wagtail-2.17.0
Also if i could know the initial first few steps to reproduce the error. By this Is mean. I should first create a fixture. save a image in it. remove the image and load the fixture again ?
I am not sure as to how i should use @override_settings to reproduce the issue. It would be graet if you could guide me on this

**Comment by 4the4ryushin** [comment]
may i work on this issue? it has been inactive for so long

**Comment by lb-** [comment]
Go for it @4the4ryushin - be sure you can reproduce and understand the problem. I'd recommend you find where to write a unit test for this and start with writing a test that fails. Then change the code to get the test passing.

**Comment by 4the4ryushin** [comment]
should i write the tests in wagtail\tests\test_signals.py ?

**Comment by lb-** [comment]
Similar - except this is an images application so it needs to go in https://github.com/wagtail/wagtail/blob/main/wagtail/images/tests/test_signal_handlers.py

**Comment by 4the4ryushin** [comment]
opps yea that's what i meant , my bad

**Comment by 4the4ryushin** [comment]
do i need to write the test that uses fixture ? because that's what raw == true means

**Comment by 4the4ryushin** [comment]
are there any predefined fixtures  in the code base for tests that i can use?

**Comment by lb-** [comment]
@4the4ryushin I encourage you to look through the code yourself and try to find either a. Fixtures that have images or b. Similar test code where we are testing code that has logic based in raw.

**Comment by 4the4ryushin** [comment]
Got it that's what I was thinking just wanted to confirm that it's the right way or not

**Comment by 4the4ryushin** [comment]
@lb-  sorry for the delay , i was little busy, now i am all set to fix this found the fixtures and done with tests, i wanted to ask
a little query in the parent comment it says at raw == True, am i supposed to literally pass and do nothing, or i still should check for focal_points and so as it has been done originally

**Comment by 4the4ryushin** [comment]
@lb-  i have made the PR,  kindly review it and let me know if there is any problem with that
https://github.com/wagtail/wagtail/pull/9533
