### ISSUE TITLE
Make file names of documents / images customizable : max_length

### ISSUE THREAD

**Issue by frague59** [wagtail/wagtail#3590]
### Issue Summary

Adding files into a collection, I'm stuck with an exception about the length of file names :
 (I'm having a long path from /home to media directory on my dev platform)

```python
SuspiciousFileOperation: Storage can not find an available filename for "<long long path>/<file name>". Please make sure that the corresponding file field allows sufficient "max_length".
```
You could introduce a parameter in settings to avoid this: 

``WAGTAIL_FILE_NAME_MAX_LENGTH = 255`` in settings for example

### Steps to Reproduce

+ Having a long path to the ``MEDIA_ROOT`` directory, or really long file names (for now, max_length is 100 chars)
+ Try to add files into a collection, through UI or django command

### Technical details

* Python version: Python 2.7.12+
* Django version: Django==1.11.1
* Wagtail version: 1.10
* Browser version: (not relevant)

**Comment by frague59** [comment]
I've written a monkey patch: 

```python
class OfficeDocument(AbstractDocument):
    ...

# Hook to update the max_length of the
def _update_file_max_length(klass, field_name='file'):
    for item in klass._meta.fields:
        if item.name == field_name:
            item.max_length = 255
            return

_update_file_max_length(OfficeDocument)

...

```

**Comment by lb-** [comment]
@frague59 thanks for this detail, it looks like the filename needs to be 100 characters max due to backwards compatibility with Django.

https://code.djangoproject.com/ticket/9893

Also see
https://github.com/wagtail/wagtail/blob/2231906ebe2cda0f0634c565adf4468c3e48c6a2/wagtail/wagtailimages/models.py#L121
