### ISSUE TITLE
Summary numbers not responsive

### ISSUE THREAD

**Issue by MichaelPalmer1** [wagtail/wagtail#3591]
### Issue Summary

If the summary section has items with more than 4 digits, they will overlap on small screens. The font size really should not be hardcoded like it is currently. It should be responsive and make use of media queries.

#### Desktop
<img width="1443" alt="screen shot 2017-05-11 at 6 38 49 pm" src="https://cloud.githubusercontent.com/assets/5766623/25974866/21eec366-3679-11e7-8774-ce5472fbc2d7.png">

#### Tablet
<img width="771" alt="screen shot 2017-05-11 at 6 38 37 pm" src="https://cloud.githubusercontent.com/assets/5766623/25974868/26d94b12-3679-11e7-89ff-c5d55ea79cf6.png">

#### Mobile
<img width="418" alt="screen shot 2017-05-11 at 6 38 19 pm" src="https://cloud.githubusercontent.com/assets/5766623/25974872/2afdecac-3679-11e7-90b8-9f95b0d4dd9f.png">

### Steps to Reproduce

Create 1000+ items on a summary section

### Technical details

* Python version: 3.5.2
* Django version: 1.11.1
* Wagtail version: 1.11.0
* Browser version: Chrome 58 on Mac OS X 10

**Comment by jjanssen** [comment]
Merged with 8b7510e
