### ISSUE TITLE
Proxy models do not use their own subpage_type property

### ISSUE THREAD

**Issue by patta42** [wagtail/wagtail#3594]
### Issue Summary

When defining a proxy model of a page model, its `subpage_type` property is not used.
### Steps to Reproduce

Assume the following models in `home.models`:

    class A( Page ):
        subpage_types = [ 'home.ChildA' ] 

    class B ( A ):
        subpage_types = [ 'home.ChildB' ]
        class Meta:
            proxy =True

    class ChildA( Page ):
        pass

    class ChildB( Page ):
        pass
         

In the Admin, if you add a page of class `B` and add a child to it, the child will be of `ChildA` instead of `ChildB`.

**Update:** Can confirm this on a fresh install with `mymodel` replaced by `home` in the above code (I have changed the code above).
### Technical details

* Python version: 3.4.5
* Django version: 1.11
* Wagtail version: 1.10
* Browser version: Chrome 58.0.3029.96 on Linux, but that doesn't matter

**Comment by zerolab** [comment]
Closing in favour of #4973 / #5202
