### ISSUE TITLE
Remediating Django 2.x Deprecation Warnings

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#3599]
When you run, for instance, `python -Wd manage.py test` on a project that uses Wagtail, hundreds and hundreds of `RemovedInDjango20Warning` and `RemovedInDjango21Warning` are printed to the screen. It's really overwhelming just how many there are. 

Some examples:
```
wagtail/wagtail/wagtailcore/models.py:503: RemovedInDjango20Warning: Usage of field.rel has been deprecated. Use field.remote_field instead.
```
```
wagtail/wagtail/api/v2/router.py:75: RemovedInDjango20Warning: Specifying a namespace in django.conf.urls.include() without providing an app_name is deprecated. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.
```
```
wagtail/wagtail/wagtailadmin/templatetags/wagtailadmin_tags.py:247: RemovedInDjango21Warning: Add the `renderer` argument to the render() method of <class 'wagtail.wagtailadmin.rich_text.HalloRichTextArea'>. It will be mandatory in Django 2.1.
```

I've begun work on remediating them, but it's a lot of highly manual effort, and I don't actually have time to dedicate to remediating most of them. But I have taken care of a bunch of the low-hanging fruit (imports that have been moved, mostly). I'll put up a PR when I get in to the office tomorrow.

Rather than just a PR, I wanted to make this issue so that we could consolidate discussion regarding deprecation warnings, and the remediation thereof.

**Comment by gasman** [comment]
Hi @coredumperror - thanks for looking into this.

The advice from the Django team (https://github.com/wagtail/wagtail/issues/3314#issuecomment-283094505, https://docs.djangoproject.com/en/dev/releases/2.0/#third-party-library-support-for-older-version-of-django) is that we _don't_ try to deal with these until we're ready to drop support for Django 1.8, which we'll probably be doing around Wagtail 1.12 in 3-4 months' time. A lot of the changes needed for Django 2.0 aren't backwards-compatible with Django 1.8, so making the changes now would involve messy special-casing for different versions.

**Comment by coredumperror** [comment]
Ahh, OK. That makes sense. Having never written a a library, I hadn't considered the necessity to continue to support older versions of Django.

**Comment by lb-** [comment]
Closing as Django 2.0 support is planned and makes this a non-issue.
