### ISSUE TITLE
Missing Spanish translations in Wagtail 1.10

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#3600]
As reported in https://github.com/wagtail/wagtail/issues/23#issuecomment-302138180, the Spanish localisation is showing considerably fewer translated strings than previous releases - for example, the "No pages have been created at this location." message in the explorer listing no longer appears as translated.

**Comment by gasman** [comment]
It seems like this is a Django bug / missing functionality, and I'm quite surprised that we're apparently the first people to encounter it...

In previous releases, wagtailcore/wagtailadmin just had an "es" translation. In 1.10, a small and incomplete "es_ES" (i.e. Spain-specific Spanish) translation was added. By Python / gettext localisation logic, `es_ES` translations take precedence over `es` when a locale of `es` or `es_ES` is active; gettext handles this by returning a translation dictionary object for the `es_ES` translations, with the `es` translations as a fallback.

`django.utils.translation` takes these dictionaries and rebuilds them in order to apply Django's own precedence rules (directories named in `LOCALE_PATHS` first, followed by locale dirs in `INSTALLED_APPS` and finally Django's own translations). This code does not look at the fallback translations returned by gettext at all, and so we end up with a translation dictionary that _only_ consists of the `es_ES` strings.

**Comment by gasman** [comment]
I manage to hack support for gettext fallbacks into Django by patching the `DjangoTranslation.merge` method in `django.utils.translation.trans_real` as follows:

    def merge(self, other):
        """Merge another translation into this catalog."""
        if not getattr(other, '_catalog', None):
            return  # NullTranslations() has no _catalog
        if self._catalog is None:
            # Take plural and _info from first catalog found (generally Django's).
            self.plural = other.plural
            self._info = other._info.copy()
            self._catalog = other._catalog.copy()
        else:
            # custom
            if getattr(other, '_fallback', None):
                self.merge(other._fallback)
            # end custom
            self._catalog.update(other._catalog)

Obviously that doesn't help for running against current Django releases though - I think the short term (= "until we drop Django <2.0 support") fix may be to simply drop the `es_ES` translations from the release.

**Comment by chimeno** [comment]
Sorry about that, I haven't got enough time to properly update the ``es_ES`` translations...Please proceed as you see more convenient.

**Comment by SalahAdDin** [comment]
I have time to finish translations, but I don't know which the difference between our Spanish and Spain Spanish.

**Comment by gasman** [comment]
Have removed `es_ES` (and other relevant cases such as `sv_SV`) from the translations. Fixing the Django bug is still on my todo list...

**Comment by patrys** [comment]
Sorry for resurrecting this but I think Wagtail may be interested in having the fix merged: https://github.com/django/django/pull/9709
