### ISSUE TITLE
[Documentation] The "Tagging" recipe is confusing

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#3602]
In the **Tagging** section of `reference/pages/model_recipes.html`, there's this code block:

```python
class BlogIndexPage(Page):
    ...
    def serve(self, request):
        # Get blogs
        blogs = self.blogs

        # Filter by tag
        tag = request.GET.get('tag')
        if tag:
            blogs = blogs.filter(tags__name=tag)

        return render(request, self.template, {
            'page': self,
            'blogs': blogs,
        })
```

I understand what it's doing, but I can't find anything that explains that first line of code in `serve()`. 

Where does `self.blogs` come from? It appears to be a queryset of `BlogPage`, but I can't figure out where it's supposed to be defined. Which makes it hard to figure out how to add tagging functionality into my own index page model's `serve()` function.

I ultimately solved my particular issue by using `children = MyPageModel.objects.child_of(self).live()` for that line, but I really think the docs should be improved to make it clear what `self.blogs` is. Or just replace it with something like my solution.

**Comment by gasman** [comment]
Thanks for the report! It looks like that bit of documentation was meant to refer to the wagtaildemo project (https://github.com/wagtail/wagtaildemo/blob/6eedaec543554ab51f2e3cfc1c90948cf7f3fa14/demo/models.py#L344), but yep, referencing an unmentioned bit of code from elsewhere isn't very helpful... Have now updated it as per your suggestion in 2f2bfa0159fa262fbd85506a2383dbf4b4c69281.
