### ISSUE TITLE
Tidy up new React + API explorer

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#3607]
Tracking issue for the follow-up work to #3012, #3385. We now need to tidy up the last few pieces before the 1.11 release.

__Help is very welcome so we can release this on time__. This is an idiomatic React + Redux codebase, so a great way to get up to speed with this stack if beginners want to get involved.

### Remaining issues

- [ ] On mobile screen sizes, the last items in the menu require page scrolling as well as menu scrolling.
- [x] On mobile screen sizes, top part of explorer behind address bar.
- ~[ ] On mobile, page overlay doesn't show.~ (desired)
- [x] On touch screens, tweak hover/active styles to not show as often.
- [x] On touch screens, explorer dismissal on touch feels a bit too fast?
- [x] IE11 - Menu items are slightly wider than their container.
- [x] IE11 - Menu items load stacked onto one another.
- ~[ ] Windows – Scrollbars should be hidden during transitions.~ (no, same across all browsers)
- [x] On mobile, Close explorer link does not work, clicking it just brings you back to the first explorer 'home page'
- [x] On mobile, Click on “Pages” the page scrolls down, so I scroll up, then click on “Close explorer”, which closes the explorer but reopens it immediately, while scrolling down again.
- ~[ ] On mobile, on first load of a menu level, focus ends on "Close explorer" button.~ (desired)
- [x] On mobile, explorer shows a shadow even though there is no layering on the page.
- [x] Performance review (CPU and memory, of both the Redux and React hierarchies)

### Features

- [ ] Text truncation of the page title after 60-70 characters;
- ~[ ] Finishing adding the setting to customise the ordering / API behavior – I've added this as a global variable initialised in the templates, but it's not hooked into the Django settings yet (I don't know how to do that)~

## Backlog

- [ ] Code reviews

### Documentation

- [ ] React/Redux code styleguide (action types with keyMirror, FSA or not, file structure)
- [ ] Integrate React components in UI styleguide

### Features

- [ ] Better translation with jsi18n (https://docs.google.com/document/d/1WImkcI1ORB5nj3FeNuVnkPIcjJTIKoMIhCV-Hqj2IEY)
- ~[ ] Better date format client-side (`moment-django` FTW!)~

### Tooling

- [ ] Add front-end test coverage to Codecov
- [x] Update to Webpack 2
- [x] Update to latest Jest
- [x] Update to latest React
- [ ] npm packaging of Wagtail front-end  https://www.npmjs.com/package/wagtail
- [ ] Reach 100% unit test coverage

### Related work to address later

- [ ] @kaedroho's page chooser refactor #3038
- [ ] #1160 
- [ ] #3106 
- [ ] #3442

## Cross-browser test suite (to copy/paste when doing a test run)

- [ ] - Browser	Device/OS	Version(s)
- [ ] - Mobile Safari	iOS Phone	10
- [ ] - Mobile Safari	iOS Phone	9
- [ ] - Mobile Safari	iOS Tablet	10
- [ ] - Mobile Safari	iOS Tablet	9
- [ ] - Chrome	Android	56
- [ ] - Chrome	Android	55
- [ ] - IE	Desktop	11
- [ ] - Chrome	Desktop	56
- [ ] - Chrome	Desktop	55
- [ ] - MS Edge	Desktop	15
- [ ] - MS Edge	Desktop	14
- [ ] - Firefox	Desktop	52
- [ ] - Firefox ESR	Desktop	45.8
- [ ] - Safari	macOS	9
- [ ] - Safari	macOS	8 #

**Comment by jjanssen** [comment]
FYI: I have crossed out the date-formatting handling for now since we are no longer parsing dates within the react-explorer since the Wagtail.space updates. So at the moment it does not relevancy to this update.
