### ISSUE TITLE
Tighter Wagtail Page Editing Theme

### ISSUE THREAD

**Issue by hairypalm** [wagtail/wagtail#3613]
### Feature Request

I make use of Streams quite a bit in the construction of my pages.  In the page editing screens I find that I am losing a lot of real estate by nesting my blocks.  It would greatly help if Wagtail could:

1) Expand the edit page to full screen and 
2) Let the nested blocks cut much less real estate per level.

### Steps to Reproduce

In my example, I have 4 levels of nesting.  I create a row, then a column, then a tabbed control, then contents per-tab.

By the time I'm writing the content, I am down to about 15% of my total screen real estate.  See the screen grab for an example, that bottom H2 input field is only 350 pixels wide on a 1280 monitor.  On a smaller screen, it gets cramped even faster.  It isn't just the edit fields that are small, the field names often get clipped as well..

![image](https://cloud.githubusercontent.com/assets/19241276/26462716/16dfc0c6-413f-11e7-95f5-c95359f29e1c.png)

### Technical details

* Wagtail version: 1.10

**Comment by gasman** [comment]
Thanks for the report @hairypalm! There's currently ongoing work in improving the design of deeply-nested StreamFields, both in the add-on packages [wagtailatomicadmin](https://github.com/alexgleason/wagtailatomicadmin) and [wagtailclearstream](https://github.com/heymonkeyriot/wagtailclearstream), and tracked by ticket #2325.
