### ISSUE TITLE
urlencode wagtail redirect urls?

### ISSUE THREAD

**Issue by tobiase** [wagtail/wagtail#3617]
If I enter redirects with urls containing "ä, ö, ü"-s or similiar characters and open that URL afterwards, no redirect is triggered. If I enter the urlencoded version, the redirect works.

Maybe entered redirects should be urlencoded by default?

**Comment by zerolab** [comment]
PR: #3670 3670

**Comment by kaedroho** [comment]
Fixed by https://github.com/wagtail/wagtail/pull/3670
