### ISSUE TITLE
Wagtail codebase fails import linting with isort 4.2.8

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#3623]
In its default configuration, isort 4.2.8 (released yesterday) is pickier about whitespace than the previous version (4.2.5), and as a result there are now a bunch of validation failures. We need to either: 1) fix all those failures, 2) tweak the `make lint` configuration to disable the stricter checks, or 3) pin isort to the older version. In the case of 2) or 3), we should also update http://docs.wagtail.io/en/v1.10.1/contributing/python_guidelines.html#pep8 to say what our policy is.

**Comment by thibaudcolas** [comment]
I had the same problem. I don't like the idea of CI builds breaking because of "patch" releases from this, so decided to pin.

**Comment by gasman** [comment]
I guess pinning the version is a good idea in any case, since this clearly shows that isort isn't following semantic versioning.

**Comment by gasman** [comment]
Fixed in b976db3afc456695bce57912ad8ef6aec90de5dd by pinning to 4.2.5.
