### ISSUE TITLE
'LogEntry' object has no attribute 'depth'

### ISSUE THREAD

**Issue by truhlik** [wagtail/wagtail#3624]
### Issue Summary
Error in Wagtail Admin UI. 
If you click on menu sidebar, then there is 500 raise.
 debug the issue and the problem is in Page.queryset.specific().
This method return wrong first item in the queryset (first returned item is LogEntry and not Page type). I checked data in DB and there is no wrong record.

See screenshot bellow from debug.
![screenshot 2017-06-01 19 11 32](https://cloud.githubusercontent.com/assets/15262443/26691791/be076f7e-46fe-11e7-9d9b-b38d9481abba.png)

### Steps to Reproduce and Environment
Request Method:	GET
Request URL:	http://localhost:8000/cms/explorer-nav/
Django Version:	1.11.2
Exception Type:	AttributeError
Exception Value:	
'LogEntry' object has no attribute 'depth'
Exception Location:	/Users/truhlik/operatio/lib/python2.7/site-packages/wagtail/wagtailadmin/navigation.py in get_navigation_menu_items, line 111
Python Executable:	/Users/truhlik/operatio/bin/python
Python Version:	2.7.10

**Comment by gasman** [comment]
Hi @truhlik,
There's not enough information here for us to investigate, sorry - we need a full description of how to independently reproduce the error.

(Most likely, your `django_contenttypes` table has been corrupted, and the IDs are no longer pointing to the right models. Did you dump and restore the database from .json fixtures, perhaps?)

**Comment by truhlik** [comment]
Thank you for point me out. I looked to django_contenttypes and wagtailcore_page and found a problem.
In wagtailcore_page, first record for root Page had content_type_id = 1. It is content_type of LogEntry. I change to correct value and everything is fine.
Is possible that this value is hardcoded (or was? I have isntallation since 1.4)?
