### ISSUE TITLE
Better UX for Streamfield and nested Streamfield support

### ISSUE THREAD

**Issue by Adrian-Turjak** [wagtail/wagtail#3630]
The streamfield is probably one of Wagtails best features from a content designers perspective, since if setup right, you can effectively enforce building blocks that pages can be built from. Not only that but the level of flexibility it gives for your content creators while maintaining consistency is amazing.

The problem though, it's also a bit of a pain to use sometimes especially when creating content with almost any form of nesting, and sadly nesting is actually a good way to build useful building blocks. This is often because inline models don't allow the same level of flexibility. You can't have an inline model with three sub model types for example. To achieve that you'd need to build a lot of extra fields into the model itself, and stick in some validation logic to make them mutually exclusive, which is awful code, and UX for content editors.

My suggestion is to make the streamfield much easier to read at a glance, and to better differentiate the layers of blocks. The method of highlighting the current block with the light blue is useful, but there should be a much clearer delineation between each block, and that should always be visible, not just when moused over. Even in very simple streamfields that blue-hightlight is not enough and the list of blocks just blurs together.

It isn't clear in this image, but there are two blocks in that stream field (one of which is then a nested streamfield itself):
![wagtail_streamfield_issues_unclear_delineation png](https://cloud.githubusercontent.com/assets/6404853/26810899/72497e3e-4ac2-11e7-8523-767ce2604e69.png)
There should be a clearly visible delineation between them visible all the time.

Secondly, that same level of delineation needs to be clear for sub-blocks within the main blocks themselves, because even basic nesting just makes almost no sense and is hard to read. Here is the same stream field as above, but with one block hightlighted:
![wagtail_streamfield_issues](https://cloud.githubusercontent.com/assets/6404853/26810465/fede8a2c-4abf-11e7-92bf-da7a3b377fa5.png)

I wrote that block so I at least have an idea of what to expect, but looking at it in the admin it is very hard to understand that it is a nested streamfield, with options: embedblock, list block (of links), and a couple of other options. In fact, that list block is very hard to see as a block of it's own compared to the blocks inside it. The little tabs on the right just aren't enough to tell you where one block starts and the next begins.
![wagtail_streamfield_issues_nesting](https://cloud.githubusercontent.com/assets/6404853/26811302/041958a0-4ac5-11e7-9910-2a16b6909a62.png)

Then to make matters worse, the plus icons and 'add another' buttons further confuse things. You have two plus buttons down the bottom that should be VERY clearly differentiated and not almost stacked. Nor is it entirely clear what the top two plus buttons are for.
![wagtail_streamfield_issues_add](https://cloud.githubusercontent.com/assets/6404853/26811363/715113f4-4ac5-11e7-8750-9da11a74272f.png)

The direction [Wagtail Atomic Admin](https://github.com/alexgleason/wagtailatomicadmin) was going seems to be better, but because it isn't an officially supported library it will never get the love it needs, nor is it a perfect solution (it is broken currently, and visually not as appealing as default). Ideally this support should be baked in, and the streamfield made better. The streamfield is amazingly useful, but limitations like this make it really hard to use when trying to build really nicely structured content. Wagtail supports nesting of blocks in the stream field, but the UI doesn't fully follow in that support (possibly worth considering it a bug?).

**Comment by gasman** [comment]
Thanks for the comments @Adrian-Turjak! We agree there's a lot of room for improvement here. In the interests of keeping the discussion in one place, I suggest we continue the conversation on #2325.

**Comment by tomdyson** [comment]
Thanks @Adrian-Turjak! You may also be interested in @heymonkeyriot's work at https://github.com/heymonkeyriot/wagtailclearstream
