### ISSUE TITLE
Documentation for wagtaildocs serve view

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#3632]
Our recommended way of serving documents from Wagtail (by using the serve view) appears to be undocumented.

**Comment by gasman** [comment]
What needs to be documented here? It's not something that users need to configure themselves (unless they're integrating Wagtail into a vanilla Django project, in which case it's covered in http://docs.wagtail.io/en/v1.10.1/getting_started/integrating_into_django.html#url-configuration) - document links (e.g. ones in rich text) use the view out-of-the-box.
