### ISSUE TITLE
Chooser panels are missing classname

### ISSUE THREAD

**Issue by fosmont** [wagtail/wagtail#3633]
(Issue met on Wagtail version 1.10.1)

I faced this issue while putting `PageChooserPanel`s inside a `FieldRowPanel`, like this:
```python
FieldRowPanel([
    PageChooserPanel('project_left'),
    PageChooserPanel('project_right')
])
```
I got this exception while running any Django command:
```
  File "/home/florent/.virtualenvs/NoriPyt/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 376, in bind_to_model
    if not re.search(r'\bcol\d+\b', child.classname):
AttributeError: 'PageChooserPanel' object has no attribute 'classname'
```

This issue also concerns other panels like `ImageChooserPanel`.

Here’s a workaround overriding the original `PageChooserPanel`:
```python
class PageChooserPanel(PageChooserPanel):
    def __init__(self, *args, **kwargs):
        self.classname = kwargs.pop('classname', '')
        super(PageChooserPanel, self).__init__(*args, **kwargs)

    def bind_to_model(self, model):
        obj = super(PageChooserPanel, self).bind_to_model(model)
        obj.classname = self.classname
        return obj
```

As you can see below, everything works fine with it, so I think we can add `classname` attributes to chooser panels without any issue. 

![image](https://cloud.githubusercontent.com/assets/22519012/26835574/e0d432ac-4ad8-11e7-8b07-b40dc5d613c3.png)

![image](https://user-images.githubusercontent.com/22519012/26837801-a8964ff0-4ade-11e7-91c5-c1a9ed551c29.png)

**Comment by gasman** [comment]
Fixed in #3810
