### ISSUE TITLE
Revisions issue

### ISSUE THREAD

**Issue by mattmillen888** [wagtail/wagtail#3634]
### Issue Summary

Wagtail Page drafts keeps picking up random revisions

### Steps to Reproduce

This issue might not be reproducible. But here's what I do

1) Edit one of my live pages
2) Add a new image block via StreamFields
3) Save Draft and hit Publish
4) Refresh Page 
5) Page shows up with Older content still and at older revision
6) Refresh Page
7) Page shows up with a newer revision

It seems to happen intermittently. Heres a couple of screenshots before and after refresh showing different revisions.

[
![older-revision](https://user-images.githubusercontent.com/25214970/26851185-792226a8-4b4d-11e7-9589-5d33db66a463.png)
](url)

![newest-revision](https://user-images.githubusercontent.com/25214970/26851207-8d06efdc-4b4d-11e7-884b-ba0231772c66.png)

### Technical details

* Python version: 3.5.2
* Django version: 1.10
* Wagtail version: 1.10.1
* Browser version: Chrome

**Comment by gasman** [comment]
Hi @mattmillen888,
Is this happening in a local development environment, or on a production site? This looks like the sort of issue that might result from a misconfigured front-end cache, or multiple app servers getting out of sync.

**Comment by gasman** [comment]
Closing due to lack of updates - we'll be happy to reopen if you can provide the requested info.
