### ISSUE TITLE
KeyError if user open preview URL from bookmarks

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#3639]
### Issue Summary

`KeyError` if user open preview URL from bookmarks or access it directly in some other way.

### Steps to Reproduce

1. Go to the admin UI -> Explorer
2. Pick any page and press an edit button
3. Extract page's ID from an URL (for example, in URL `/admin/pages/3/edit/` id is `3`)
2. Open preview URL for this page directly (for example, `/admin/pages/3/edit/preview/`)

### Result

```
  File "django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "wagtail/wagtailadmin/decorators.py", line 27, in decorated_view
    return view_func(request, *args, **kwargs)
  File "django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "wagtail/wagtailadmin/views/pages.py", line 613, in get
    form = self.get_form()
  File "wagtail/wagtailadmin/views/pages.py", line 584, in get_form
    post_data_dict, timestamp = self.request.session[self.session_key]
  File "django/contrib/sessions/backends/base.py", line 57, in __getitem__
    return self._session[key]
KeyError: 'wagtail-preview-3'
```

### Expected result

Instead of throwing an exception we can do one of the following:

* Try to re-generate preview on the fly
* Gently ask user not to access this URL directly or say something like "Preview for this page has expired"

### Technical details

* Wagtail version: Wagtail>=1.10

**Comment by pkamp3** [comment]
We hit this locally with users pasting links to each other.  Not sure which result you want to go with, but we worked around it by returning an empty form:

https://github.com/pkamp3/wagtail/blob/08f80882353cc67b803d4e1535a215ed662a3470/wagtail/wagtailadmin/views/pages.py#L584-L588

`get()` then eventually hits `return self.error_response(page)`

**Comment by gasman** [comment]
@pkamp3 Isn't that just going to fail on line 592, because `post_data_dict` isn't defined...?

**Comment by atbaker** [comment]
@pkamp3 and I were debugging this together a little bit today. I think you're right @gasman.

What's your preferred solution here? We've both got our heads wrapped around the problem right now, so we're happy to put a PR in.

**Comment by pkamp3** [comment]
For us the issue was with the key missing, so my sneaky return on `588` avoids those lines:

`get()` -> `get_form()` (returns early) -> `get()`

**Comment by BertrandBordage** [comment]
@gasman: Why would `post_data_dict` be undefined?
@pkamp3: It’s clearer to reverse the condition, like this:
```python
if self.session_key not in self.request.session:
    # Session key not in session, returning null form
    return form_class()
post_data_dict, timestamp = self.request.session[self.session_key]
```

**Comment by gasman** [comment]
Ah, sorry, missed that it was returning from the method at that point!

**Comment by pkamp3** [comment]
@BertrandBordage agreed, that looks good - the negative logic first makes much more sense.
@gasman No worries!  Want us to put together a PR with that?

**Comment by gasman** [comment]
@pkamp3 Yes please (assuming @BertrandBordage is happy with that approach)!

**Comment by BertrandBordage** [comment]
Fine with me.
Just one thing though: wouldn’t it be better to bind the instance and parent page? If I’m correct, this will display the preview of the current version of the page instead of showing the preview of an empty page that may break rendering.

**Comment by pkamp3** [comment]
Yes, thank you @BertrandBordage ; better to make it explicit - I added `instance` and `parent_page` in the PR and tested the logic in our environment.

I guess the other solution here is populate what's needed to generate a new preview, but this does avoid the 500.
