### ISSUE TITLE
Long page names overflow their container in explorer menu in Safari 9

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#3649]
### Issue Summary

Initially reported by @jjanssen in #3645. Page names that wrap to a second/third line overflow their container, in both Mobile Safari iOS 9 and (desktop) Safari 9.1 (works in version 10.1).

![image](https://user-images.githubusercontent.com/287422/26967301-fec79c1e-4cfd-11e7-8f60-44ad068cc819.png)

Related to: https://github.com/philipwalton/flexbugs#1-minimum-content-sizing-of-flex-items-not-honored

### Steps to Reproduce

1. Create a page with a long title (100+ chars, create it at the "Homepage" level to get to it faster).
3. Add children to the page so the  `>` caret is displayed in its menu item.
2. Open the pages explorer menu and navigate to the location of this page in the page tree.

### Technical details

- Latest Wagtail / 1.11 RC
- Mobile Safari iOS 9 and (desktop) Safari 9.1

Edit: I spent about half an hour playing with every variation of layout properties I could think of, to no effect. Unless I've missed something obvious (further attempts welcome), I'd probably opt to rebuild this `__link` component without Flexbox.

**Comment by kapito** [comment]
Testing this in with Safari in an iPhone 6s (iOS 9) emulator, the page name looks [exactly as I would expect](https://cdn.pbrd.co/images/GABvhsc.png) -- the same as it does using Firefox on a desktop.

Am I missing something or has this already been patched?

**Comment by jjanssen** [comment]
Hi @kapito,

This has not been fixed just yet. Unless it happened by accident 😄  I'd suggest maybe using the exact example from the issue: _"This is a test to determine how a page will look with an extremely long title, and this should be long enough or should I go on a little longer to be sure?"_

We are using BrowserStack as well. 
![image](https://user-images.githubusercontent.com/287422/28123418-2fbe6554-6721-11e7-94b7-880f25f0830f.png)

**Comment by kapito** [comment]
@jjanssen Ah, my bad -- I didn't create any children pages when I tested it. I'll see if I can find a fix :)

**Comment by jjanssen** [comment]
I'm closing this due the release of Safari 11 for OSX and iOS. According to our [browser support](http://docs.wagtail.io/en/v1.12.2/contributing/developing.html#testing) we only support the last 2 versions.
