### ISSUE TITLE
Documentation: Image and text not in sync between github and readthedocs

### ISSUE THREAD

**Issue by tombreit** [wagtail/wagtail#3659]
The text and image for the current wagtail version on 

http://docs.wagtail.io/en/v1.10.1/editor_manual/finding_your_way_around/the_explorer_menu.html 

is outdated and does not reflect the current state of the explorer menu as described in 

https://github.com/wagtail/wagtail/blob/v1.10.1/docs/editor_manual/finding_your_way_around/the_explorer_menu.rst

![rtdvsgit](https://user-images.githubusercontent.com/1015232/27157804-c10eb032-5163-11e7-8470-473e2adbf7bc.png)

**Comment by gasman** [comment]
It's the other way around - when I built the 1.10.1 release, I initially created the git tag from the master branch by mistake, so readthedocs picked up a newer version of the docs than it was supposed to, including the new explorer UI coming in Wagtail 1.11. I fixed the tag shortly afterwards, but evidently the old docs stuck around...

I've rebuilt it now - thanks for the report!

**Comment by tombreit** [comment]
Cool - looking forward to this new page explorer.
