### ISSUE TITLE
Unable to save - Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

### ISSUE THREAD

**Issue by phoebebright** [wagtail/wagtail#3660]
### Issue Summary

On saving a new page I get this error.  Have gone through the various bug reports and made sure I have the correct versions of wagtail, beautifulsoup4 and html5lib

### Steps to Reproduce

This happens in both my osx environment and linux production environment.

### Technical details

relavent library versions:

Ubuntu
Python 2.7.3
beautifulsoup4==4.5.1  (also tried 4.6.0)
Django==1.10.7
django-treebeard==4.1.1
django-wagtail-feeds==0.0.7
djangorestframework==3.6.3
html5lib==0.999999999
lxml==3.8.0
puput==0.8
six==1.10.0
wagtail==1.10.1
webencodings==0.5.1

OSX
Python 2.7.10
beautifulsoup4==4.6.0
Django==1.10.7
django-treebeard==4.1.1
django-wagtail-feeds==0.0.7
lxml==3.7.2
puput==0.8
six==1.4.1
wagtail==1.10.1
webencodings==0.5.1

**Comment by gasman** [comment]
Hi @phoebebright,

I've found that using html5lib==0.999999 seems to avoid installation issues - I'd suggest trying that version.

Before you do, please can you try running the following on the Python command line, to help diagnose this further:

    import html5lib
    from bs4.diagnose import diagnose
    diagnose("foo")

**Comment by phoebebright** [comment]
Not had a problem installing things, or at least no errors.

Diagnostics::
	
        Found lxml version 3.8.0.0
	Found html5lib version 0.999999999
	
	Trying to parse your markup with html.parser
	Here's what html.parser did with the markup:
	foo
	
	--------------------------------------------------------------------------------
	Trying to parse your markup with html5lib
	Here's what html5lib did with the markup:
	<html>
	 <head>
	 </head>
	 <body>
	  foo
	 </body>
	</html>
	--------------------------------------------------------------------------------
	Trying to parse your markup with lxml
	Here's what lxml did with the markup:
	<html>
	 <body>
	  <p>
	   foo
	  </p>
	 </body>
	</html>
	--------------------------------------------------------------------------------
	Trying to parse your markup with ['lxml', 'xml']
	/home/django/virtualenvs/zen/local/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available XML parser for this system ("lxml-xml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
	
	The code that caused this warning is on line 1 of the file <stdin>. To get rid of this warning, change code that looks like this:
	
	 BeautifulSoup([your markup])
	
	to this:
	
	 BeautifulSoup([your markup], "lxml-xml")
	
	  markup_type=markup_type))
	Here's what ['lxml', 'xml'] did with the markup:
	<?xml version="1.0" encoding="utf-8"?>
	
	--------------------------------------------------------------------------------
	>>>

**Comment by gasman** [comment]
Hmm, no clues there - that's showing html5lib / bs4 behaving exactly as they should. Does installing html5lib==0.999999 fix the issue?

**Comment by phoebebright** [comment]
Tried with 
html5lib==1.0b10  (latest)
then
html5lib==0.999999 (6 9s)
And it worked!

Thought I had tried that before but maybe I got the number of nines wrong.

Thanks for the help.  Will stick with that version now.
