### ISSUE TITLE
Documentation blog tutorial deprecated import from modelcluster.tags

### ISSUE THREAD

**Issue by robvdl** [wagtail/wagtail#3664]
I found a deprecated import in the tutorial part of the docs.

Release: Wagtail 1.10.1

The tutorial gets you to create a blog, then add some tags, it uses the following import which Pycharm marks as deprecated:

    from modelcluster.tags import ClusterTaggableManager

It should be:

    from modelcluster.contrib.taggit import ClusterTaggableManager

**Comment by robvdl** [comment]
it's in this section in the docs: http://docs.wagtail.io/en/v1.10.1/getting_started/tutorial.html#tagging-posts

**Comment by gasman** [comment]
Thanks for the report @robvdl! Fixed in 6bc6480cd29a6606c86d8505a0f3d53ecd3d69df.
