### ISSUE TITLE
Custom Image Model Throwing Error when Saving in page

### ISSUE THREAD

**Issue by jianshen92** [wagtail/wagtail#3666]
### Issue Summary
I used custom image model following wagtail 1.10 documentation. Uploading Images are fine. Initially, using the images in pages are fine. However, when an image is deleted, and subsequent images uploaded are not able to be used in Pages. `Select a valid choice. That choice is not one of the available choices.` is thrown.

### Steps to Reproduce

My custom Image model in `base.py/models`

```
class CustomImage(AbstractImage):
    admin_form_fields = Image.admin_form_fields + (
        # Then add the field names here to make them appear in the form:
        # 'caption',
    )
    api_fields = [
        APIField('file')
    ]

class CustomRendition(AbstractRendition):
    image = models.ForeignKey(CustomImage, related_name='renditions')

    class Meta:
        unique_together = (
            ('image', 'filter_spec', 'focal_point_key'),
        )
```
I have also added `WAGTAILIMAGES_IMAGE_MODEL = 'base.CustomImage'` in the settings file.

In a fresh wagtail,
1. Upload an image, image X.
2. Delete image X.
3. Upload another image, image Y.
4. Using image Y in a Page will throw the error.

**Comment by gasman** [comment]
Hi @jianshen92,
Have you made sure that the image field on your Page model is a foreign key to `CustomImage`, rather than `wagtailimages.Image`?

**Comment by jianshen92** [comment]
Hi, that was my error! Thanks.
