### ISSUE TITLE
Orderable extra arrows in non-content tabs

### ISSUE THREAD

**Issue by BertrandBordage** [wagtail/wagtail#3667]
(Tested with Wagtail 1.10.1)

Currently, Wagtail has some trouble initializing JS in other tabs than the default one (see #2687 for example).

In this case, Wagtail doesn’t properly detects that an orderable item is the first or the last of the panel, so it shows both arrows instead of just the relevant one. But once we reorder any item of the same panel, the issue disappears.

![orderable-extra-arrow-in-tab](https://user-images.githubusercontent.com/1119169/27289198-6270cbec-5509-11e7-9b8f-aa226c147690.png)

**Comment by gasman** [comment]
Related to #3316 (which has a fix in #3679)
