### ISSUE TITLE
RichTextField: Link is not inserted when selected text starts or end with italic and has also non-italic part

### ISSUE THREAD

**Issue by nrsimha** [wagtail/wagtail#3677]
### Issue Summary

Inserting links doesn't work when selection starts or end with italic and have also non italic part.

### Steps to Reproduce

1. Start a new project and use RichTextField or use Wagtail Demo
2. Go to edit page with RichText
3. Insert text into RichText field (e.g. aaaa bbbb cccc dddd eeee)
4. Make cccc part italic
5. Select "cccc dddd" or "bbbb cccc" 
6. Click on link button and choose any page
7. Link is not inserted

### Technical details

* Python version: Run `python --version`.
* Django version: 1.11.2
* Wagtail version: 1.10.1 and 1.11rc1
* Browser version: Mac - Chrome 58.0.3029.110 (64-bit) and Firefox 54.0 (64-bit)

**Comment by lb-** [comment]
Thanks for submitting this issue with great details @nrsimha 

The current rich text editor will be replaced with Draftail (new editor) in a future release. See #2409

**Comment by thibaudcolas** [comment]
I can confirm this is working fine in the new editor.
