### ISSUE TITLE
"View Live" in Wagtail Admin does not use the site associated with a page to display

### ISSUE THREAD

**Issue by eskhool** [wagtail/wagtail#3678]
### Issue Summary
When using the View Live button, it redirects to using the admin to display the page in question, ignoring the Site mapping to the Home Page associated with that Page Tree. Since the associated site has option for a hostname and port those should be

### Steps to Reproduce

Open any page in the wagtail admin and click on the view live button. the link opened is on the same host and port as the wagtail admin

### Technical details

* Python version: Python 3.5
* Django version: Django 1.10
* Wagtail version: Wagtail 1.10.1
* Browser version: All browsers

**Comment by gasman** [comment]
Hi @eskhool,
Please see #1807 - hosting the admin on a different hostname/port from a site is not a configuration that we currently support.
