### ISSUE TITLE
No Wagtail way how to manage menus?

### ISSUE THREAD

**Issue by moreplavec** [wagtail/wagtail#3681]
I can't find any easy way how to create and manage website menu. For external links, ordered links, categories aso. i have to create model or templatetag or snippets. What about something simple link snippet with ordering and possibility to order and add link?

**Comment by webit-mdowney** [comment]
I've written something that might fill the gap; @gasman do you want me to build a PR for this?

![screen shot 2017-06-29 at 9 14 56 am](https://user-images.githubusercontent.com/18178794/27664653-1d28f032-5cac-11e7-9e32-268cdbe795cb.png)
![screen shot 2017-06-29 at 9 16 22 am](https://user-images.githubusercontent.com/18178794/27664656-1d617d26-5cac-11e7-9bd3-4dbbde751af5.png)
![screen shot 2017-06-29 at 9 16 28 am](https://user-images.githubusercontent.com/18178794/27664655-1d5fa564-5cac-11e7-88a3-3d0d5d8388b8.png)
![screen shot 2017-06-29 at 9 16 34 am](https://user-images.githubusercontent.com/18178794/27664659-1d76f840-5cac-11e7-8c39-fb940b58708c.png)
![screen shot 2017-06-29 at 9 16 38 am](https://user-images.githubusercontent.com/18178794/27664657-1d61c7ae-5cac-11e7-8a55-021a353ba72f.png)
![screen shot 2017-06-29 at 9 16 42 am](https://user-images.githubusercontent.com/18178794/27664660-1d80eeae-5cac-11e7-86b7-b2eb1f0dc90c.png)
![screen shot 2017-06-29 at 9 16 46 am](https://user-images.githubusercontent.com/18178794/27664654-1d558eda-5cac-11e7-8b4c-0aa8d6b0792b.png)
![screen shot 2017-06-29 at 9 16 51 am](https://user-images.githubusercontent.com/18178794/27664661-1d8285fc-5cac-11e7-919e-61f96fd219c2.png)

**Comment by massaad** [comment]
And there is this: https://github.com/rkhleics/wagtailmenus

**Comment by webit-mdowney** [comment]
@massaad only problem is this:

> Extend the wagtailmenus.models.MenuPage model instead of the usual wagtail.wagtailcore.models.Page

I like to separate my concerns.

**Comment by ababic** [comment]
Hi @massad, using the `MenuPage` model is entirely optional with wagtailmenus. That's just if you want to make use of some advanced functionality. There's also a `MenuPageMixin` you can use with existing page types if changing base models completely unnerves you.

**Comment by ababic** [comment]
Hi @massad, using the `MenuPage` model is entirely optional with wagtailmenus. That's just if you want to make use of some advanced functionality. There's also a `MenuPageMixin` you can use with existing page types if changing base models unnerves you.

**Comment by webit-mdowney** [comment]
@ababic thanks for the info!

**Comment by ababic** [comment]
Incorrectly mentioned you there @massaad. Sorry for the confusion :)

**Comment by moreplavec** [comment]
So there is no wagtail-way how to manage menus right now or official menu plugin? And this ticket was marked as Milestone: some-day, so it's not going to change in near future, right?

**Comment by SalahAdDin** [comment]
@moreplavec,what's about these package?

**Comment by moreplavec** [comment]
@SalahAdDin You mean mentioned WagtailMenus? I can't use because of it's not supported in Django 1.11.x (doc talks just about 1.10). Second problem is that I'm looking for official or long-term supported solutions not just now working solution.

**Comment by SalahAdDin** [comment]
The first @ababic package, ``modeladmin` support, was officially ported to `wagtail` two version ago if i am not wrong.

**Comment by zerolab** [comment]
@moreplavec you will find https://github.com/wagtail/rfcs/pull/4 useful for background information. tl;dr
The position is to develop this separately to allow for rapid iteration, change etc without the overhead and burden of compatibility and so on. ModelAdmin went that route, so did the API.

Once there are enough approaches, or one emerges as most adopted/liked, it will likely make it into Wagtail (can't speak for the core team, though)

---

There are many approaches to this. You can go abstract and packaged as https://github.com/rkhleics/wagtailmenus does.

Or you can go with a simple implementation:
https://github.com/torchbox/wagtail-torchbox/blob/master/tbx/core/models.py#L1756-L1778
https://github.com/torchbox/wagtail-torchbox/blob/master/tbx/core/templates/torchbox/includes/menu_item.html

I am sure @ababic would welcome a PR for Django 1.11.x compatibility ;)

**Comment by webit-mdowney** [comment]
A super simple method (what we did before migrating to a standalone menus app) is to create an ExternalLink page that on serve redirects to the external URL. That will let you tick the Show In Menu checkbox. You can also create a Redirect page for redirecting locally for your site. Make sure you keep the external links out of the sitemap generation.

**Comment by ababic** [comment]
Hi @moreplavec. I actually don't specify django version support in `wagtailmenus` at all (as far as I'm aware).

My (unwritten) policy is to support whatever versions of Django that a supported version of Wagtail supports, and I don't announce that support for a version of Wagtail until that's the case (and the test configuration is altered to account for the new potential Django/Wagtail version combinations).

By this logic, `wagtailmenus` already supports Django  1.11.x, because Wagtail 1.10.x supports it.

**Comment by moreplavec** [comment]
Sorry, it's not Django but Wagtail version in the DOC. I will try wagtailmenus, it looks like best solution.
