### ISSUE TITLE
React explorer doesn't use get_admin_display_title

### ISSUE THREAD

**Issue by Henk-JanVanHasselaar** [wagtail/wagtail#3689]
### Issue Summary

The admin API for the react explorer doesn't use the `get_admin_display_title` of the`Page` object to determine the page title. 

### Steps to Reproduce

Run any wagtail project on wagtail 1.11 and change the `get_admin_display_title` of your custom Page object.

we used this in wagtail trans to display the language of the page. 
I've added some screenshots for visualization
![with-react-explorer](https://user-images.githubusercontent.com/12495915/27830653-b105b5c8-60c7-11e7-962e-08cf0e432062.png)
![without-react-explorer](https://user-images.githubusercontent.com/12495915/27830652-b104aa0c-60c7-11e7-970e-d2263167f604.png)

### Technical details

* Python version: 3.5.3
* Django version: 1.11.3
* Wagtail version: 1.11

**Comment by tomdyson** [comment]
Thanks very much for this report, @Henk-JanVanHasselaar. We're putting together a fix which we'll release ASAP.

**Comment by gasman** [comment]
Fixed in #3694 (for 1.11.1) and #3697 (for 1.12).

**Comment by Henk-JanVanHasselaar** [comment]
Thanks guys for this quick fix! 👍
