### ISSUE TITLE
Wagtail admin explorer menu broken on Chrome browser after upgrading to Wagtail 1.11

### ISSUE THREAD

**Issue by contactr2m** [wagtail/wagtail#3693]
A summary of the issue.

<img width="810" alt="screen shot 2017-07-05 at 10 18 51 am" src="https://user-images.githubusercontent.com/13003246/27868696-85120b7a-616b-11e7-95ed-4b9681f0f1e1.png">

I do not see this issue on IE, Firefox, Safari browsers.
Steps to Reproduce

1. Start a new project with `wagtail start myproject`  with old version of Wagtail, I am on 1.10.1
2. Upgrade to Wagtail 1.11
3. Login to Wagtail admin and try to use explorer menu.

### Technical details

* Python version: Python 2.7.12
* Django version: 1.11.3
* Wagtail version: 1.11
* Browser version: http://www.whatsmybrowser.org/b/PJ6DP5Q,  Chrome 58

**Comment by iansprice** [comment]
Experiencing this as well on ChromeVersion 59.0.3071.115 (Official Build) (64-bit) and Ubuntu 17.04. 

It's worth noting that the links on the main page (outside the explorer box) are clicked when attempting to click something on the box itself (acts like a z-index issue).

**Comment by jjanssen** [comment]
Thanks for reporting this. Could you validate if this problem still persists after clearing the [browser cache](http://docs.wagtail.io/en/v1.11/editor_manual/browser_issues.html#browser-issues)? 

We have tested the new explorer quite extensively and my only guess is that some of the static files are still being served from the browsers' cache.

**Comment by contactr2m** [comment]
Closing this.. stupid of me to report even before checking simple options. 

PS: Clearing the browser cache solve this problem.
