### ISSUE TITLE
Self-closing anchor tag in create-user template breaks layout 

### ISSUE THREAD

**Issue by sivictorallen** [wagtail/wagtail#3696]
### Issue Summary

Self-closing anchor tag in create-user template breaks layout 

### Steps to Reproduce

In the admin, navigate to Settings > Users > Add User or //admin/users/add/
Separation of "Account" and "Roles" tab is broken, and form cannot be submitted.

### Technical details

Line #33 of ~/wagtailusers/templates/wagetailusers/users/create.html contains a self-closing anchor tag. If the slash is removed, the layout displays correctly.

Before:
`<li><a href="#roles" class="button lowpriority tab-toggle icon icon-arrow-right-after"/>{% trans "Roles" %}</a></li>`

After:
`<li><a href="#roles" class="button lowpriority tab-toggle icon icon-arrow-right-after">{% trans "Roles" %}</a></li>`

This can be correctly locally by overriding the template.

**Comment by gasman** [comment]
Thanks for the report @sivictorallen! Yep, that's definitely wrong - will fix that.

For reference, which specific browser(s) does this fail on? It seems that the offending HTML has been in place since the very first release of Wagtail, and I'm not aware of it causing any problems up to now...

**Comment by sivictorallen** [comment]
I tested with: Chrome 59 and Firefox 54 (both Mac OS X 10.11)

**Comment by gasman** [comment]
Fixed in 6556e0efab47c6a3024a59034a100257a931e025. (Still not able to replicate the bug or see any difference before/after the fix in either of those browsers, though...)
