### ISSUE TITLE
Example of StreamField group

### ISSUE THREAD

**Issue by iaindillingham** [wagtail/wagtail#3698]
### Issue Summary

I've added the `group` argument to several of my StreamField blocks, made a migration, and migrated. I expected a change in the bock menu but everything looks the same! Could you give an example of StreamField group so I can understand this feature better? (It was introduced in Wagtail [1.10](http://docs.wagtail.io/en/stable/releases/1.10.html).)

### Technical details

* Python version: 2.7.12
* Django version: 1.11.3
* Wagtail version: 1.11
* Browser version: Firefox 54 (http://whatsmybrowser.org/b/TDNFZDY) and Chromium 59 (http://whatsmybrowser.org/b/U1GSNCI)

**Comment by zerolab** [comment]
Hi @iaindillingham 

See #3100 for context

**Comment by iaindillingham** [comment]
I might be missing something, but [the docs][1] say that `group` should be passed as a keyword argument to the block's constructor. However, in the pull request, `group` is a property of a block's meta class. Is there a convenient way of setting the latter on built-in blocks, such as `CharBlock`, without extending them, as is done in the tests?

[1]: http://docs.wagtail.io/en/stable/topics/streamfield.html#basic-block-types

**Comment by gasman** [comment]
@iaindillingham Passing a keyword argument (e.g. `CharBlock(group='foo')`) should always be equivalent to setting the property in `Meta` - if that's not the case here, that's a bug.

**Comment by iaindillingham** [comment]
Okay, I think there's a bug, then. I think it's [here][1]...

```obj._constructor_args = (args, kwargs)```

...which I think should read...

```obj._meta_class._constructor_args = (args, kwargs)```

That said, meta classes are still magical to me, so I'd appreciate another point of view!

[1]: https://github.com/wagtail/wagtail/blob/v1.11/wagtail/wagtailcore/blocks/base.py#L68

**Comment by gasman** [comment]
@iaindillingham I don't think that line is the culprit - that's just keeping track of the args passed to the constructor so that we know what to write back to the migration file when running `./manage.py makemigrations`.

If you can confirm (on a fresh Wagtail project) that setting `group` in the `Meta` properties works whereas passing it in the constructor doesn't, I'll be happy to investigate further.

**Comment by iaindillingham** [comment]
Oh dear, looks like the problem is my end! Everything works as expected in the Wagtail demo. Thanks for your speedy reply.
