### ISSUE TITLE
Explorer options overflow container on Safari (mobile)

### ISSUE THREAD

**Issue by kapito** [wagtail/wagtail#3707]
### Issue Summary

In the Wagtail explorer on Safari mobile, the last two options (specifically "Account settings" and "Log out") are both outside of the explorer's container making them hard to read (due to the white background).

Image: https://cdn.pbrd.co/images/GAIVfmL.png
How it should look (how it looks using Chrome on Android Lollipop): https://cdn.pbrd.co/images/GAIXO9S.png

### Steps to Reproduce

Log in to /admin/ using Safari mobile and open the explorer.

### Technical details

* Python version: 2.7.12
* Django version: 1.11.3
* Wagtail version: 1.11.1
* Browser version: Safari mobile on iOS 9

**Comment by thibaudcolas** [comment]
This seems to be working fine in iOS 11 and we've stopped supporting iOS 9 since that got released, closing.
