### ISSUE TITLE
Error "Complex filters with double-underscore clauses are not implemented yet" in page preview

### ISSUE THREAD

**Issue by lumatijev** [wagtail/wagtail#3712]
### Issue Summary

Wagtail admin throws an error "Complex filters with double-underscore clauses are not implemented yet" when trying to preview the page but after it is published everything works as expected.

If I'm not mistaken I think this error did not occur before updating Wagtail to version 1.11.x.

Error details:

Exception Type: NotImplementedError
Exception Value: Complex filters with double-underscore clauses are not implemented yet
Exception Location: /home/lumatijev/.virtualenvs/PROJECT_NAME/lib/python2.7/site-packages/modelcluster/queryset.py in _get_filters, line 48

Project name is removed from the exception location path.

### Steps to Reproduce

In `models.py` I have following code that presumably causes this error:

```python
class LinkOffer(models.Model):
    link_page = models.ForeignKey(
        'Offer',
        null=True,
        blank=True,
        related_name='+',
        limit_choices_to={'live': True},
        help_text=(
            'The link to the page that you\'d like to be seen by the public'
        )
    )

    @property
    def get_offer(self):
        if self.link_page:
            return self.link_page

    panels = [
        FieldPanel('link_page')
    ]

    class Meta:
        abstract = True


class RelatedOffer(LinkOffer):
    panels = [
        MultiFieldPanel(LinkOffer.panels, 'Offer')
    ]

    class Meta:
        abstract = True


class HomePageFeaturedOffer(Orderable, RelatedOffer):
    offer = ParentalKey('HomePage', related_name='featured_offers'


class HomePage(six.with_metaclass(PageBase, MetaData, Page)):
    ...
    @cached_property
    def get_featured_offers(self):
        return self.featured_offers.filter(
            link_page__live=True).select_related(
            'link_page', 'link_page__header_image').all()
    ...
    content_panels = Page.content_panels + [
        ...
        InlinePanel(
            'featured_offers',
            label='Featured offers',
            help_text=(
                'The featured offers that you\'d like to be seen by the public'
            )
        ),
        ...
    ]
```

### Technical details

* Python version: 2.7.13.
* Django version: 1.11.3.
* Wagtail version: 1.11.1.

**Comment by gasman** [comment]
Hi @lumatijev,
This is a limitation of the django-modelcluster library used for previews (and other occasions where we need to work with querysets that don't match the current database state), and this limitation has always existed. Have now opened https://github.com/wagtail/django-modelcluster/issues/82 to address this.
