### ISSUE TITLE
Issue with Pillow >= 4.2.0 - IOError cannot write mode RGBA as JPEG

### ISSUE THREAD

**Issue by rafaponieman** [wagtail/wagtail#3713]
Pillow 4.2.0 (released early July) deprecated removing automatically the alpha channel on PNGs when saving them as JPEG. This won't be a problem if you're not specifying jpeg output on the image template tag (as PNGs output as PNGs), but if you do, it fails while trying to save a jpeg thumbnail for a PNG.

Solved temporarily by hardcoding Pillow 4.1.1 on my requirements.

Running Wagtail 1.11.1 on Django 1.10.7

**Comment by rafaponieman** [comment]
Thank you!! Should I close this issue?

**Comment by kaedroho** [comment]
This issue should automatically close itself as soon as #3911 is merged
