### ISSUE TITLE
jQuery load method is deprecated

### ISSUE THREAD

**Issue by anselmbradford** [wagtail/wagtail#3730]
### Issue Summary

The jQuery `load` method is deprecated per [jQuery docs](https://api.jquery.com/category/deprecated/) and is in use [here](https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/table_block/static/table_block/js/table.js#L135).

**Comment by thibaudcolas** [comment]
Thanks for the report @anselmbradford. Could you also detail why you consider this a bug – is there anything broken in one of your project?

As for a fix, as far as I understand all it would take is to replace this shortcut method with `.on( 'load', handler)`. Could you provide a PR fixing this?

**Comment by gasman** [comment]
Fixed in #3744

**Comment by anselmbradford** [comment]
Thanks @gasman!
