### ISSUE TITLE
[New Feature Request] Implementing Hook for injecting action buttons on object/row level

### ISSUE THREAD

**Issue by nazmulhasan85** [wagtail/wagtail#3732]
Currently Wagtail has the feature to hook on below listed areas

- Admin modules
- Editor interface
- Editor workflow
- Choosers
- Page explorer
- Page serving
- Document serving

But on my last project with wagtail i was looking to do some `hooking` on object/row level.  It was required to add an extra button on user list to approve the requested users and leaving comment during approval process.

I did that by overriding  `get_buttons_for_obj` method and passing this class on Model admin view. Can we suggest to write a hook for that?

See my implementation - 

```python
class SomeButtonHelper(ButtonHelper):
    def get_extra_buttons(self, pk, classnames_add=[], classnames_exclude=[]):
        """ return list that can send multiple buttons. Needs to Override this function."""
        raise []

    def get_buttons_for_obj(self, obj, exclude=[], classnames_add=[], classnames_exclude=[]):
        pk = getattr(obj, self.opts.pk.attname)
        btns = super(SomeButtonHelper, self).get_buttons_for_obj(obj, exclude, classnames_add, classnames_exclude)
        extra_btns = self.get_extra_buttons(pk, classnames_add, classnames_exclude)
        if extra_btns and isinstance(extra_btns, list):
            btns = btns + extra_btns
        return btns
```

We can do it like passing tree parameters --

- Registered admin URL
- Label to show
- Model-admin class

That means developers needs to call two hooks. One for the registering the custom url and another for Setting that URL in object list with label.

**Comment by lb-** [comment]
@nazmulhasan85 thanks for the suggestion, I think that ModelAdmin actually provides the ability to do what you want without adding admin URLs via dedicated register url hooks.

It is not documented but you can override the [`get_admin_urls_for_registration`](https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/modeladmin/options.py#L461) on your ModelAdmin something like this.

```
class MyPageModelAdmin(ModelAdmin):
    # model, menu_label, menu_icon, ect
    def get_admin_urls_for_registration(self):
        urls = Super(MyPageModelAdmin, self).get_admin_urls_for_registration()
        urls += [url(<my url pattern>, <view>, <name>)]
```

Let us know if that is not a suitable existing solution, but for now we will close this.
