### ISSUE TITLE
Inconsistent data format in emails sent by AbstractEmailForm

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#3733]
### Issue Summary

At the moment, [`AbstractEmailForm` sends emails using raw data](https://github.com/wagtail/wagtail/blob/42d274a470fa19d3f60a24361d5153d05ce72cdf/wagtail/wagtailforms/models.py#L299) from the user's input which means that output (email body) will be inconsistent for fields like `DateField` that accept different input formats (both `%m/%d/%Y`and `%m/%d/%y` are valid, for example).

### Steps to Reproduce

1. Create a form with `DateField`.
2. Submit the form with value in format `%m/%d/%Y` (`23/01/2017`, for example)
3. Submit the form with value in format `%m/%d/%y` (`23/01/17`, for example)
4. Check both emails: they will contain `23/01/2017` and `23/01/17` respectively.

I think, both emails should be in single format (let's say in `SHORT_DATE_FORMAT` for `DateField` fields).

Some services can use emails sent by Wagtail for integration purposes, so single format for dates will make integrations easier.

### Technical details

* Wagtail version: all version (tested on 1.6 and 1.11)

**Comment by lb-** [comment]
Merged in via PR #5171
