### ISSUE TITLE
Preview doesn't handle revisions of related pages correctly

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#3734]
## Issue Summary

When editor to previews a page that contains related pages, Wagtail displays data from the real table (not data serialised into and stored in revisions). It's confusing in some scenarios (when you preview a page that has a link to a draft page, for example).

## Steps to Reproduce

Steps to reproduce are based on https://github.com/wagtail/wagtaildemo/commit/64137b0c8720477fdab13956bb7ecc6c5f320c25 and Wagtail 42d274a but can be reproduced on other versions of Wagtail.

### Prepare models and templates

Define models like:

```python
class DemoPreviewOnePage(Page):
    listing_title = models.CharField(max_length=255)
    listing_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    content_panels = Page.content_panels + [
        FieldPanel('listing_title'),
        ImageChooserPanel('listing_image'),
    ]


class DemoPreviewTwoPageRelatedLinks(ClusterableModel):
    page = ParentalKey('DemoPreviewTwoPage', related_name='related_links')
    link = models.ForeignKey('wagtailcore.Page', related_name='+')

    panels = [
        PageChooserPanel('link'),
    ]


class DemoPreviewTwoPage(Page):
    content_panels = Page.content_panels + [
        InlinePanel('related_links', label="Related links"),
    ]

```

And the `demo/demo_preview_two_page.html` template:

```django
{% extends "demo/base.html" %}
{% load wagtailimages_tags %}

{% block content %}

    {% for related in page.related_links.all %}

        <div>Title: {{ related.link.specific.title }}</div>
        <div>Listing title: {{ related.link.specific.listing_title }}</div>

    {% endfor %}

{% endblock %}

```

### Part 1: the first preview of a page with a related draft

1. In the Wagtail admin UI, create a draft page "Demo page 1" (`DemoPreviewOnePage` type) and add values for the following fields:
    * Title: `Demo page 1`
    * Listing title: `Test listing title`
2. Create a draft page "Demo page 2" (`DemoPreviewTwoPage` type) 
3. On "Demo page 2" add a related link to "Demo page 1"
4. Preview "Demo page 2"

**Result:** Wagtail displays the following as expected:

```
Title: Demo page 1
Listing title: Test listing title
```

***Note*** that wagtail pre-populated a real table with draft data (data from a revision). In DB:

```
select wp.title, dp.listing_title from wagtailcore_page as wp join demo_demopreviewonepage as dp on wp.id = dp.page_ptr_id;
    title    |   listing_title
-------------+--------------------
 Demo page 1 | Test listing title
(1 row)
```

### :x: Part 2: the second preview of the page with the related draft

5. On page "Demo page 1" update the following values and save the draft:
    * Title: `Demo page 1 (v2)`
    * Listing title: `Test listing title (v2)`
6. Preview "Demo page 2"

**Result:** Wagtail displays data from the previous revision:

```
Title: Demo page 1
Listing title: Test listing title
```

In DB:

```
select wp.title, dp.listing_title from wagtailcore_page as wp join demo_demopreviewonepage as dp on wp.id = dp.page_ptr_id;
    title    |   listing_title
-------------+--------------------
 Demo page 1 | Test listing title
(1 row)
```

**Expected result:** Wagtail displays data from the latest revision:

```
Title: Demo page 1 (v2)
Listing title: Test listing title (v2)
```

This result is very confusing, because an editor expects preview to work in the same way as the first time.

### Part 3: preview of the related published page

7. Publish "Demo page 1 (v2)"
8. Preview "Demo page 2"

**Result:** Wagtail displays expected data from the live version:

```
Title: Demo page 1 (v2)
Listing title: Test listing title (v2)
```

In DB:

```
select wp.title, dp.listing_title from wagtailcore_page as wp join demo_demopreviewonepage as dp on wp.id = dp.page_ptr_id;
        title        |       listing_title
---------------------+----------------------------
 Demo page 1 (rev 2) | Test listing title (rev 2)
(1 row)
```

All further drafts of "Demo page 1 (rev 2)" will not make any difference on preview of the "Page 2" page: only published changes will be displayed.

## Technical details

* django-modelcluster version: 3.1.
* Wagtail version: any version (tested on 1.6.\*, 1.11.\* and on the current `master` = commit 42d274a)

**Comment by m1kola** [comment]
I think, it's a bug, because of inconsistent behaviour (see results of step 1 and step 2 in the first comment), but I'm not sure how to solve this without breaking existing workflows.

It seems to me that different sites can have different requirements for preview. I can thing of two major groups of projects:

  * Projects that _do not_ display draft versions at all (they exclude them during rendering or in the `Page.get_context` method) and they should be happy with the current implementation, because this bug doesn't cause any issues.

  * Projects where preview of related drafts can be important. For example, projects that use scheduled publishing: you want to publish two linked pages at midnight and be sure that everything will look fine on front-end.

The only solution that comes to mind is to implement separate preview modes:

  * The first mode doesn't get data from the latest revision for related pages (the existing behaviour, but we need to do something to unify experience on the first and on further previews: see step 1 and step 2)
  * The second mode gets the latest revision, if possible.

Any ideas?

**Comment by gasman** [comment]
Going to put this one down as a 'wontfix'. The database table for a page model is meant to represent the published state of the pages; ideally unpublished pages would be omitted entirely, but that's not really feasible, so instead their database record is in an undefined state. If a site implementer chooses not to exclude the `live=False` records from their front-end queries, then they need to either accept the undefined behaviour or implement something better themselves.
