### ISSUE TITLE
Image search unnecessarily refreshes page on enter press

### ISSUE THREAD

**Issue by jckpn** [wagtail/wagtail#3746]
On `/admin/images/`, the results are automatically displayed as you input your query into the search box. However, most users would expect that you would need to press enter after inputting your query (as you do for the other search forms), so it can be frustrating when the results load but the page refreshes anyway due to the user pressing enter (despite the fact the results have already been found and displayed).

https://gfycat.com/UglyEdibleAcornweevil

**Comment by BertrandBordage** [comment]
Yeah, the submit event should be bound and prevented.
But I guess we should keep the ability to submit the form if Javascript is disabled.

**Comment by lb-** [comment]
For anyone looking at this, it would be good to check the behaviour of documents searching also.

**Comment by rd3m** [comment]
Hi @lb-, I'll have a look at this one. At first glance, it appears the behaviour is the same for documents searching as well. I'll create a PR shortly.
