### ISSUE TITLE
Allowing form submitters to receive a confirmation email 

### ISSUE THREAD

**Issue by bcoover** [wagtail/wagtail#3747]
### Issue Summary

FORMS IMPROVEMENT: Although clearly not always wanted, sometimes we want a form to email the result to the end user that submitted the form. Today Wagtail ONLY emails if the form creator specifies an admin email (to address) for the email to be sent to.

### Technical details

I did a workaround to force the behavior dynamically:

```
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.forms.fields import EmailField

class FormPage(AbstractEmailForm):
    ...
    ...
    def process_form_submission(self, form):
        """
        Overriding the base class function to force send of emails to any email fields the user may have submitted
        """
        submission = self.get_submission_class().objects.create(
            form_data=json.dumps(form.cleaned_data, cls=DjangoJSONEncoder),
            page=self,
        )
        self.send_mail(form)  # force attempt at send_mail
        return submission

    def send_mail(self, form):
        to_addresses = [x.strip() for x in self.to_address.split(',')]
        for field in form:
            value = field.value()
            if type(field.field) == EmailField:  # if we find an email field
                if str(value) not in [None, '']:  # if the value is not empty
                    to_addresses.append(str(value)) . # add to the email to addresses

        if to_addresses:  # only try to send if there are to_addresses
            send_mail(...)
```

**Comment by lb-** [comment]
@bcoover thank you for the suggestion.

This is quite a specific use case as there are a lot of ways to implement emailing to additional addresses based on the form (eg. getting the currently logged in user, adding a special form field for this purpose).

On top of that, there are often cases where the public recipient of the email will need to get a differently formatted email, not just the built in wagtail formatted email, or they may want to hook into other things like signals and send emails that way.

As such, we will leave this kind of implementation up to the developer to add as they see fit.

We will have better documentation for `send_mail` overrides in the next version which should make it easier to discover how to do some basic overrides.
