### ISSUE TITLE
Add request.FILES to wagtailforms form creation

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#3757]
I would like to request we add request.FILES to the creation of custom forms.

Reasoning: It makes it much easier to extend the forms with features like file and image uploads, without having to override the whole `serve` method.

File: wagtail/wagtailforms/models.py Line 240
https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailforms/models.py#L240

**Current**
`form = self.get_form(request.POST, page=self, user=request.user)`

**Suggested**
`form = self.get_form(request.POST, request.FILES, page=self, user=request.user)`

I am happy to put through a pull request and check tests against this change, the request.FILES object will be empty when there are no files so it should not affect existing code.

**Comment by gasman** [comment]
I'm happy with this change in principle, but it would only become useful once 'file upload' is added to the available field types - which in turn needs additional handling in the wagtailforms backend (since you can't include a file upload in a CSV export, and need extra logic to add it as an email attachment).

**Comment by lb-** [comment]
@gasman that is correct.

I am drafting a blog post on how to do this logic (with the example of using it to upload images to WagtailImages) and currently overriding the serve method is a pretty heavy handed thing for just this one change.

I will prepare a pull request for this change.

Should we mention something in the docs about this feature or leave it up to people to work out if they need this in the code?

**Comment by BertrandBordage** [comment]
Just adding `request.FILES` is far from enough to make file uploads work on dynamic forms.
A saving mecanism has to be implemented to a special directory, as well as an automatic file deletion on form submission deletion.

I already implemented that as well an extendable `StreamField` based dynamic forms in a closed source project. It’s going to be a new contrib module in a few months, unfortunately I don’t have enough time right now to clean the project, test it and release it.

**Comment by lb-** [comment]
@BertrandBordage I agree - there is a lot involved when you actually want to handle files, however, my main intent is for developers not having to override the whole serve method, just to send request.FILES to the self.get_form method.

This means that for the contrib or any other extending, the serve method can stay as is, even though you will have to extend other methods and classes elsewhere.

**Comment by BertrandBordage** [comment]
OK, then I’m fine with merging your pull request.

**Comment by gasman** [comment]
Implemented in #3803

**Comment by lb-** [comment]
Thanks

**Comment by lb-** [comment]
@BertrandBordage FWIW here is my blog post - slide me an email if you have some thoughts on this implementation. https://posts-by.lb.ee/image-uploads-in-wagtail-forms-3121c9b35d27
