### ISSUE TITLE
The page with form submissions is ugly on screens with >=1280px

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#3759]
### Issue Summary

The page with form submissions looks ugly on screens with >=1280px.

### Steps to Reproduce

1. Create a form page with title ~35 characters
2. Submit some data on front-end
3. Go to the Admin UI -> Forms -> Your form page title

### Result

1. Too much empty space in header when a form page has a long title
2. Too much place for checkboxes in the submissions table

### Expected result

1. I have no idea how to fix the header
2. I guess, it should be possible to make the column with checkboxes to have a fixed width

### Screenshots

Viewport width 1280px-1215px (desktops):

<img width="1327" alt="screen shot 2017-08-12 at 12 25 12" src="https://user-images.githubusercontent.com/509198/29239535-5dc09a3a-7f59-11e7-858a-210f374ee05e.png">

Viewport width ~768px (iPad and other tablets):

<img width="793" alt="screen shot 2017-08-12 at 12 33 26" src="https://user-images.githubusercontent.com/509198/29239573-84b17c30-7f5a-11e7-9386-27ca136953a2.png">

### Technical details

* Wagtail version: 1.12 (from the `master` branch, commit e2b5dc384f1909d95991735a9ef034c0c4bb197e).
* Browser version: Google Chrome 60.0.3112.90, MacOS 10.12.5 (16F73)

**Comment by lb-** [comment]
Proposed solution - we pull out the date search parts from the header completely.

`wagtail/contrib/forms/templates/wagtailforms/index_submissions.html`

All the search content would go under the `<div class="nice-padding">` instead of in the header.

```html
<div class="nice-padding">
        <form action="" method="get" novalidate>
            <div class="col search-bar">
                <ul class="fields row rowflush">
                    {% for field in select_date_form %}
                        {% include "wagtailadmin/shared/field_as_li.html" with field=field field_classes="field-small" li_classes="col4" %}
                    {% endfor %}
                    <li class="submit col2">
                        <button type="submit" name="action" value="filter" class="button button-filter">{% trans 'Filter' %}</button>
                    </li>
                </ul>
            </div>
        </form>
```

Note: we would need to ensure the form row is not centre aligned but other than that - it looks much better I think.

<img width="1039" alt="Screen Shot 2022-07-04 at 4 52 33 pm" src="https://user-images.githubusercontent.com/1396140/177098073-0ee2c6bb-b887-4d6f-b2ef-c667b2f09a09.png">

<img width="1668" alt="Screen Shot 2022-07-04 at 4 52 58 pm" src="https://user-images.githubusercontent.com/1396140/177098134-0d44f166-24b2-4b49-a347-dc77befd175d.png">

**Comment by lb-** [comment]
We will aim to get this resolved as part of the UX unification work in the header  - https://github.com/wagtail/wagtail/issues/8539

But in the mean time - marking as a good first issue for anyone to pick up.

## Actions required

* Pull out the `form` from the header and put into the main content `<div class="nice-padding">`
* Remove any scss that no longer applies
* With styling, fix the date from / date to text wrapping
* With styling (or maybe utility classes), fix the centre alignment of the dates and ensure they are aligned to the left (start)
* Might need to update the `col` classes to be better suited to this row being stand alone
* Validate in multiple browsers
* Update unit tests
* Check the new location works
* Bonus: Get rid of the inline script tag and put the JS into its own file.

**Comment by lb-** [comment]
Will be fixed by https://github.com/wagtail/wagtail/pull/8862 - new layout that streamlines the way the filtering shows.

<img width="1325" alt="Screen Shot 2022-07-19 at 8 39 37 pm" src="https://user-images.githubusercontent.com/1396140/179739314-6da24d21-9fae-4259-b4b0-c5ebf79acb75.png">
