### ISSUE TITLE
"Open Link in New Tab" on a right arrow in page explorer should open page list

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#3760]
### Issue Summary

In the new page explorer we have a right arrow control that makes the explorer show child pages of a specific page by click. But if an user attempts to see the the list of child pages in a new tab/window, he will see the current page which is confusing.

### Steps to Reproduce

1. Create a page tree (or use [`wagtaildem`](https://github.com/wagtail/wagtaildemo)) like `Home page -> Standard Index -> A deeper menu level -> A grandchild page`
2. Click to "Pages", click on the right arrow near the "Home page" and then on a similar arrow near the "Standard Index".
3. Right click on the right arrow near the "A deeper menu level" and click on "Open Link in New Tab" menu item.

### Result

Browser opens the original page in a new tab and appends `#` into the URL.

### Expected result

Browser opens a list of pages under the "A deeper menu level" page in a new tab. Result should be the same as click on the page title in a page explorer.

### Screenshots

<img width="1280" alt="screen shot 2017-08-12 at 13 19 41" src="https://user-images.githubusercontent.com/509198/29239848-f15ea7bc-7f60-11e7-8c39-779a5af4f59e.png">

### Technical details

* Wagtail version: 1.12 (from the `master` branch, commit e2b5dc384f1909d95991735a9ef034c0c4bb197e).
* Browser version: Google Chrome 60.0.3112.90, MacOS 10.12.5 (16F73)

**Comment by thibaudcolas** [comment]
👍  I think it could be enough to add an `href` to that button: https://github.com/wagtail/wagtail/blob/e2b5dc384f1909d95991735a9ef034c0c4bb197e/client/src/components/Explorer/ExplorerItem.js#L52-L59

...matching the one from the previous button:

https://github.com/wagtail/wagtail/blob/e2b5dc384f1909d95991735a9ef034c0c4bb197e/client/src/components/Explorer/ExplorerItem.js#L33

The `onClick` handler on the "Next" button is already preventing the click event, so it _should_ work.

**Comment by thibaudcolas** [comment]
Marking this as **beginner-friendly**. If someone wants to pick this up and doesn't know where to start please drop a comment below and I will be more than happy to help with project set up, solving the problem, and making a pull request.
