### ISSUE TITLE
Form Submission View needs reordering, or newest first default order.

### ISSUE THREAD

**Issue by Adrian-Turjak** [wagtail/wagtail#3761]
### Issue Summary

The current form submission page makes it quite frustrating to actually see your newest submissions. This is because it is ordered oldest first. That ordering makes no real sense as the default, or at least doesn't unless there is a way to override this.

You can filter by a time range, but that isn't really that useful because the returned order is still oldest first.

### Steps to Reproduce

1. Setup form page as per this doc: http://docs.wagtail.io/en/v1.11.1/reference/contrib/forms/index.html
2. Make submissions a few minutes apart
3. go to the form submissions page for your form

The order will be oldest first. If you keep adding submissions eventually the pagination will kick in and move the newest entries onto a second page.

### Possible Solutions

At the very least, adding support for reordering would be good, or a global config setting that overrides the existing one here: https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailforms/views.py#L71

Making newest first the default would be best, but may cause confusion for any users used to the current sorting.

**Comment by Adrian-Turjak** [comment]
@gasman I'm more than happy to do the work on this based on your comments in that pull request.

I can quite likely start looking at making newest first the default while ensuring the csv export does the same thing. That said, reversing a csv isn't exactly too hard either, but we should maintain that export since chances are someone is likely exporting and and then importing that data automatically somewhere, and this could break things for them. The gui change at least won't break things, just confuse someone briefly.

No clue where to start on making the submission list sortable with the gui so some direction there would be great. 

I would love to start properly digging into the Wagtail codebase so this could be a small enough change to get me started. :)

**Comment by lb-** [comment]
Hey, I second that this is an issue (just ran into this myself). I am happy to pitch in to help out, let me know if you want me to look into something here @Adrian-Turjak

**Comment by lb-** [comment]
@Adrian-Turjak @gasman 

**What if the ordering setting was defined by a field on the Form Page?**

* Add a field to the `AbstractForm` Model
* Something like `order_by_recent_first` with this appearing in the Settings tab (or just not visible at all by default)
* DB Migrations for all existing Form Pages set to False
* Defaults to True for all new Pages created, but with the user's ability to override on a form by form basis
* wagtail/wagtailforms/views.py updated to check for the Boolean on the Form Page's specific instance

Downside is that this adds complexity to the UI.

Upsides is that it solves the problem of existing expectations, sets the better UX default for future pages and the setting can be all but hidden for anyone except if they want to make it available or override the default for some reason.

** Migrations to Implement **

Setting up the migration file would be complicated and I am not sure if what this plan entails is possible as we do not necessarily know the models that inherit `AbstractEmailForm` or `AbstractForm`.

* Migration File B - Add the field to `AbstractForm`, with default to `False` (updating all existing Pages). As no forms would have this field, they will all set to `False`.
* Migration File B - Update the default to `True`, which I assume will not update any models already existing as this is not a field creation any more.

**Comment by lb-** [comment]
@Adrian-Turjak 

** Regarding the UI to make the Table Sortable **

`contrib/modeladmin` contains a good reference for how to implement sortable headers, there is no JS involved by the looks of it. 

[Template that build the list](https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/modeladmin/templates/modeladmin/includes/result_list.html)

The Results List is ordered based on the URL Parameters and built in this [Template tag](https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/modeladmin/templatetags/modeladmin_tags.py#L87)

There is some [minor SCSS](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailadmin/static_src/wagtailadmin/scss/components/_listing.scss#L313) that might need to be added for the arrows.

Hope that helps.

**Comment by gasman** [comment]
As I said on https://github.com/wagtail/wagtail/pull/3762#issuecomment-322433203, the best UX design is UX that the user doesn't have to think about - it should just be _there_. The ordering of this index page is a detail that an end user of Wagtail should not have to care about: if they're prompted to make a decision about it, either in the admin or the config file, then we've already failed...

Let's set it to newest-first by default (when viewing as an HTML page, not CSV) - since that's clearly the more friendly option - and let users reverse the order by clicking the heading. It doesn't need any more configuration than that.

**Comment by lb-** [comment]
@gasman sweet, ignore my previous comment.

**Comment by Adrian-Turjak** [comment]
@lb- Do you want to make a pull request to then make the list sortable by submission date, and I'll do another to set the newest first as the default sorting (while making the csv export stay oldest first)?

**Comment by lb-** [comment]
@Adrian-Turjak sounds good - not sure if I will get to mine this week but will see how we go 👍

**Comment by lb-** [comment]
@Adrian-Turjak I have done most of this now, you can see it on my branch here:

https://github.com/lb-/wagtail/tree/3761_sort_by_url_param

* URL parameters such as `?order_by=-submit_time` or `?order_by=submit_time` parsed
* Clickable column header (for submit_time only) that will reorder + visually show the current order
* Styles for the above


I have not done the csv part, currently it will now order by `-submit_time` for that also, maybe this query should go inside the `if request.GET.get('action') == 'CSV':` section? as a reordering of the already queried and filtered submissions.

Have a look at my work so far and let me know what you think.

**Comment by Adrian-Turjak** [comment]
looking at:
https://github.com/wagtail/wagtail/compare/master...lb-:3761_sort_by_url_param

Code makes sense, just haven't gotten a chance to play with it! Too busy with various non-wagtail things. I also stupidly didn't realise how linked this would be! You've pretty much done all the work already. :P

For the csv , reording in `if request.GET.get('action') == 'CSV':` is easy, but I feel like one extra action when we could just have the default itself be different depending on the action in the first place. Not a huge savings, but better than a pointless second reorder.

**Comment by lb-** [comment]
@Adrian-Turjak I have now set it up to do the default sorting of it is returning a CSV, I have also moved the function that processes the ordering over to the form page model, this way it can be overridden by developers.

To do still
* [ ] Header click should consider other URL parameters, not overwrite them
* [ ] Tests of the get_field_ordering functions
* [ ] Tests of the view results
* [ ] Tests of the URL parameters
* [ ] Test that the CSV will export the original - submit_time ascending

Let me know what you think.

**Comment by Adrian-Turjak** [comment]
@lb- Haven't looked at this in ages, am sorry for not responding sooner.

Looking at the pagination, provided you set the ordering in the context, it should render here:
https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailadmin/templates/wagtailadmin/shared/pagination_nav.html#L33
https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailadmin/templates/wagtailadmin/shared/pagination_nav.html#L46

Which means making pagination respect order you just need to add 'ordering' to the context with the current ordering and pagination works.

So the problem is do we want the clicking of the header to respect the page you are on? I'm not so sure we should. When you change the ordering, the page you are on doesn't matter since the order is entirely different, but others may disagree. 

If we did want to preserve page number all we need to do is add "p={{ submissions.number }}" to the url params since the submissions object in the context we're dealing with is a paginated list.

**Comment by gasman** [comment]
Clicking the header to change the ordering should take you back to page 1 - I'm pretty sure that's how it behaves everywhere else.

**Comment by Adrian-Turjak** [comment]
Perfect, then we just need to pass the ordering to the context and pagination is sorted. :)

**Comment by lb-** [comment]
Sweet, taking a look at this all now.

**Comment by lb-** [comment]
This is looking good, since I did not need to worry about the URL parameters conflict issue - I have now written the tests for the URL parameters, there is already a test in place for the correct ordering of the CSV which is passing locally.
