### ISSUE TITLE
RichText fails to add link if selected text contains non-Text node (rangy issue)

### ISSUE THREAD

**Issue by paramono** [wagtail/wagtail#3775]
### Issue Summary

In Wagtail admin, I want to create RichText block with the following contents:

> View all →

I am trying to select this text and add an internal link to it. However, when I select any internal page from "Add/edit link" button of hallo.js, nothing happens - Wagtail doesn't let me select a page I want to link to.

Browser console, though, indicates where's an issue:

```
Uncaught DOMException: Failed to execute 'surroundContents' on 'Range': The Range has partially selected a non-Text node.
    at I.n.surroundContents (http://127.0.0.1:8000/static/wagtailadmin/js/vendor/rangy-core.js:63:276)
    at Object.pageChosen (http://127.0.0.1:8000/static/wagtailadmin/js/hallo-plugins/hallo-wagtaillink.js:82:51)
    at Object.ModalWorkflow.self.respond (http://127.0.0.1:8000/static/wagtailadmin/js/modal-workflow.js:75:45)
    at HTMLAnchorElement.eval (eval at ModalWorkflow.self.loadResponseText (http://127.0.0.1:8000/static/wagtailadmin/js/modal-workflow.js:54:24), <anonymous>:84:19)
    at HTMLAnchorElement.dispatch (http://127.0.0.1:8000/static/wagtailadmin/js/vendor/jquery-2.2.1.min.js:3:7516)
    at HTMLAnchorElement.r.handle (http://127.0.0.1:8000/static/wagtailadmin/js/vendor/jquery-2.2.1.min.js:3:5597)
```
This seems to be an issue with Rangy. 

If I exclude arrow from selection, linking works fine. Likewise, if I select the arrow only, linking also works fine. The problem appears only when I mix text node and non-text node in my selection.

Considering that Wagtail is gradually moving away from hallo.js, I am not sure whether this issue will be addressed. Is there any way to configure Rangy or hallo.js to prevent these exceptions from being thrown?

### Steps to Reproduce

1. Create a Page with either RichTextField or a StreamField containing RichTextBlock;
2. Open Wagtail admin page;
3. Create RichText and fill it with the example text: `View all →`;
4. Select the text you entered and press "Add/edit link";
5. Select any internal page you have on your website;
6. Wagtail admin should ignore your input. Watch for exceptions in browser console.

The desired behavior: website admins should be able to add link to the example text

### Technical details

* Python version: 3.5.2
* Django version: 1.11
* Wagtail version: 1.11.1
* Browser version: Chromium Version 59.0.3071.109 (Developer Build) Built on Ubuntu, running on LinuxMint 18 (64-bit)

**Comment by gasman** [comment]
Working for me in Chrome 60.0.3112.101 on OS X. However, I suspect this is indeed a Hallo/Rangy bug rather than a Wagtail one, and is unlikely to be fixed before we migrate away from Hallo.

**Comment by albing** [comment]
Reproduced!  The trick for me was to:

1. Add several lines (let's say 2) which are in the same paragraph block.
2. Select the whole line through triple-click so you the implied <br>
3. Create the link - note how it works; break the link
4. Select a word on the first line and click the `P` button to space the two lines farther apart and in separate paragraphs
5. Repeat steps 2-3, and note how the "Add Link" button doesn't work.  There is an exception in the browser console.

Breaks in Chrome and Safari (when selecting a line of text at a time, they also include the newline) but not in Firefox (it does not select the newline).

Without looking at the code, it looks like a `.trim()` could fix the issue.

**Comment by thibaudcolas** [comment]
This is working fine in the new Draftail editor. Hallo still has the issue of course.
