### ISSUE TITLE
Applying any heading style to OL or UL increases font size unlimitedly

### ISSUE THREAD

**Issue by evgenymarkov** [wagtail/wagtail#3778]
Steps to Reproduce:
1. Open any rich text field in wagtail admin.
2. Create OL or UL
3. Apply any heading style several times (H1, ..., H6)
![Screenshot](http://i.imgur.com/FmAx09i.png)

Technical details:
* Wagtail version: 1.12
* Browser version: Chromium 60.0.3112.101

In Firefox 55.0.2 it works correctly.

**Comment by AlexeyMis** [comment]
same issue

**Comment by thibaudcolas** [comment]
The new editor doesn't have this issue. Hallo still does ofc.
