### ISSUE TITLE
Tail-wag animation doesn't end smoothly on Chrome

### ISSUE THREAD

**Issue by jckpn** [wagtail/wagtail#3780]
It seems that Chrome handles CSS animations differently than Firefox does, causing the animation to end improperly:

https://gfycat.com/UnfinishedAdolescentGiantschnauzer

How it should look (and how it looks with the latest version of Firefox):

https://gfycat.com/HeartyShallowCobra

I'm not sure about other browsers; if someone could check Safari that would be appreciated.

**Comment by denizdogan** [comment]
Safari 12.1 https://gfycat.com/severalvastgrub

Firefox 66 https://gfycat.com/concretedecentarcticduck

Chrome 73 https://gfycat.com/illequatorialhedgehog

Looks a bit odd in all of them to me. Note in the Chrome one how the bird reverts back correctly unless it's reached "full flight" 😄

**Comment by lb-** [comment]
Fixed and merged in to master https://github.com/wagtail/wagtail/commit/74ce4adb6b4e206861d74d01bee93cea42b56c5f

@denizdogan  - thanks so much for fixing this, great to get this one in :D
