### ISSUE TITLE
Documentation for custom document models

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#3782]
[The `WAGTAILDOCS_DOCUMENT_MODEL` setting](https://github.com/wagtail/wagtail/blob/v1.4/wagtail/wagtaildocs/admin.py#L7) that allows developers to define a custom document model has been introduced in Wagtail v1.4, but it's not properly documented. The only mention about this feature can be found in [the release notes for Wagtail v1.4](http://docs.wagtail.io/en/v1.12/releases/1.4.html#custom-document-models).

For examples, see:
* [Custom image models](http://docs.wagtail.io/en/v1.12/advanced_topics/images/custom_image_model.html)
* [Settings Variables -> Images](http://docs.wagtail.io/en/v1.12/advanced_topics/settings.html#images)
* [Custom user models](http://docs.wagtail.io/en/v1.12/advanced_topics/customisation/custom_user_models.html)
* [Stackoverflow answer: how to define a custom document model](https://stackoverflow.com/questions/43388180/wagtail-custom-document-model/43389396#43389396)

**Comment by m1kola** [comment]
#2001 is about documentation for for the whole documents app. I think we can start from documenting custom models.

**Comment by emilyhorsman** [comment]
I just did this a couple times the other week so I'll submit a PR for this today.

**Comment by emilyhorsman** [comment]
For posterity: this doc will need to be updated again if/when #3539 is fixed.

**Comment by m1kola** [comment]
Fixed in #3789
