### ISSUE TITLE
Styles for the preview button are broken on a page with more than one preview mode

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#3784]
### Issue Summary

Styles for the preview button are broken on a page with more than one preview mode (on form page, for example).

### Steps to Reproduce

1. Define a form page model using `wagtail.wagtailforms`
2. Go to the Wagtail admin UI to create a new page.

### Result

<img width="439" alt="screen shot 2017-08-23 at 13 12 07" src="https://user-images.githubusercontent.com/509198/29615295-48837a98-8805-11e7-9a45-724c2daeadd0.png">
<img width="457" alt="screen shot 2017-08-23 at 13 12 14" src="https://user-images.githubusercontent.com/509198/29615296-4889b912-8805-11e7-8b70-4c1f86b599aa.png">

### Technical details

* Django version: 1.11.3
* Wagtail version: 1.12 (Can't reproduce on 1.11.1)
* OS: MacOS 10.12.5 (16F73)
* Browser versions:
  * Google Chrome 60.0.3112.101
  * Safari 10.1.1 (12603.2.4)
  * FireFox Developer Edition 56.0b2

**Comment by kapito** [comment]
I think I know the cause for this, will release a PR fixing it ASAP.
