### ISSUE TITLE
Admin search not using ``get_admin_display_title()``

### ISSUE THREAD

**Issue by BenSturmfels** [wagtail/wagtail#3793]
### Issue Summary

The ``get_admin_display_title`` method of Page subclasses isn't used when searching in admin; both in page chooser search and in general admin search.

### Steps to Reproduce

For example, I create a subclass of ``Page`` with a ``get_admin_display_title`` method:

    class Artwork(Page):
        accession_number = models.CharField(max_length=50)

        def get_admin_display_title(self):
            return '{}: {}'.format(self.accession_number, self.title)

Then create an Artwork with accession_number "2009.12" and title "Red Flowers". I would expect to see the title always displayed in the Admin as "2009.12: Red Flowers" but it's shown as "Red Flowers" in:

 - page chooser when searching (eg. ``/admin/choose-page/search/``)
 - admin search (eg. ``/admin/pages/search/``)

The title is show as expected in:

 - JavaScript Page menu (eg. ``/admin/api/v2beta/pages/``),
 - page chooser (eg. ``/admin/choose-page/4/``)
 - regular page listing (eg. ``/admin/pages/9/``)

### Technical details

* Python version: 3.4
* Django version: 1.11.4
* Wagtail version: 1,12
* Browser version: Firefox 52.1.2

**Comment by gasman** [comment]
Fixed in #3794
