### ISSUE TITLE
Image URL generator preview is broken

### ISSUE THREAD

**Issue by kapito** [wagtail/wagtail#3796]
On the image URL generator, rather than seeing a preview of my image, I see an endless loop of the spinner loading animation on top of some small 'Preview' text.

![image](https://user-images.githubusercontent.com/14837124/29710336-b54a6618-8987-11e7-99b3-b617162e3cdc.png)

Can anybody else recreate this?

**Comment by lb-** [comment]
@kapito thank you for submitting this.

I just tested this out on Wagtail 1.11, 1.12 and 13.1 on Chrome, Firefox and Safari (macOS) and could not replicate the issue.

Could you please add some more info such as the Wagtail version, browser you were using and check for any Javascript Console errors.

**Comment by gasman** [comment]
Closing as unable to replicate.
