### ISSUE TITLE
UI architecture technical debt

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#3804]
Wagtail's UI codebase is in bad shape. This isn't really surprising – UI/CSS architecture in long-lived projects is a notoriously hard problem. It's not hopeless either. But there is work to do 🙂

I'd like to use this as a tracking issue to discuss the problems this is creating, their causes, potential solutions, and hopefully gather consensus. In my opinion, a good outcome of those conversations would be to agree on a prioritised list of actions to be taken, that can then be worked on by different contributors in separate PRs. Sweeping rewrites are not on the agenda.

> Edit: historically, the following content has been targeted towards CSS architecture in particular. But feel free to discuss any other UI maintainability issues (JS, HTML, fonts, SVG, etc) in this issue.

## Problems

- Maintenance is hard and error-prone. UI regressions are frequent, and hard to correct.
- Trying to implement new UIs, there is a big bias towards creating new styles instead of repurposing existing patterns.
- Third-party plugins have no clear point of integration with Wagtail's UI. [Anecdotal examples](https://github.com/springload/wagtaildraftail/blob/master/client/wagtaildraftail.scss#L8).

## Causes

This is a grab bag of code smells and high-level architectural issues.

- Main admin styles are kept in a few 100+ line files instead of being separated in components. (eg. `_main-nav.scss`, 479 lines)
- Too much nesting, generating overly-specific CSS selectors (eg. `.nav-main .footer-submenu a`).
- Styles rely on qualifying elements, generating overly-specific CSS selectors, making UI components harder to evolve to use different elements.
- No consistent naming convention. We are supposed to use BEM, but a lot of styles do not follow it, and it's not enforced.
- Too many magic values. This is in particular problematic for spacing, where there is no consistency between different UI components.
- Too little architecture. There is a basic separation of components in different files, layouts with their page-specific styles, but it does not go far enough. (eg. for whatever reason all of the components that are specific to the `page-editor` layout have been defined inside of it.
- No clear boundary for plugin integrations.

## Solutions

With #3773 as a foundation, I believe some of the above could easily be addressed by increasing what rules are enforced with tooling.

- Leverage more `stylelint` rules or plugins to enforce stricter guidelines
  - For qualifying elements, `selector-no-qualifying-type`.
  - For magic values, https://github.com/AndyOGo/stylelint-declaration-strict-value.
  - For naming,
    - https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-function-pattern/README.md
    - https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-mixin-pattern/README.md
    - https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/dollar-variable-pattern/README.md
    - https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/percent-placeholder-pattern/README.md
    - https://github.com/davidtheclark/stylelint-selector-bem-pattern
- Find and use an auto-formatting tool, like `stylefmt` or `prettier`.
- Find and use styles reporting tools to keep track of the number of colours, font styles, font sizes in use in the code.
- Use a stricter architecture than BEM, like ITCSS
- Make and mandate the use of a UI component library (#382)
- Expose Wagtail's styles in the `wagtail` npm package so the variables and components can be reused in plugins.
- Define points of extensions for CSS with stable naming conventions.
- Develop and maintain a UI regression test suite to facilitate refactorings (https://github.com/thibaudcolas/wagtail-dev-tooling).
- Use pre-commit hooks to enforce linting when code is authored, rather than in CI.

## Related issues, in no particular order

- z-index mess #1958
- Refactoring away from icon fonts #1224 
- Streamfield UX issues have been left unaddressed in core because it is easier for people to override the styles than fix the problem directly in Wagtail #2325
  - https://github.com/heymonkeyriot/wagtailclearstream
  - https://gitlab.com/alexgleason/wagtailatomicadmin
  - https://github.com/springload/wagtailfacelift
- No documented way to override Wagtail's CSS cleanly #2353
- ~Specificity hacks make it hard to customise Wagtail's UI #2600~
- Theming capabilities would be cool #2943
- UI pattern library #3823 
- Menu layout #4744

**Comment by Meteor0id** [comment]
@thibaudcolas mentions "Too much nesting" as one of the root causes. I like to add this is not just nesting in CSS, it also stems from nesting of tempalte tags and extending templates.

For example:
When editing a page, the header wraps aroudn the entire top portion of the page, like one might expect.
Yet when listing sub pages, a different template is used to generate the page, and the top portion of the page is considered the first "index" row of a table which lists the pages.
Suddenly the same "privacy_indicator" class is no longer within the header.

I think the initial effort should be to normalise the templates, and than refoactor the classes and their corresponding SCSS.


Having digged though the scss and the templates, it is going to be a quite an effort to sort things out, but it is about time to make a start. The milestone "Some day" is a bit concerning. As the CMS grows, this issue will continue to get more complicated every month.

**Comment by Meteor0id** [comment]
I forgot to meantion:
Too much use of Javascript! Things like toggeling .account can be done with a display:none checkbox and some simple CSS. This does not require javascript to toggle.

**Comment by thibaudcolas** [comment]
Thank you for your thoughts @Meteor0id. You're very right to mention there are maintainability issues with the HTML too. One is what you mention. Another is overuse of `table` elements for layout. There are more.

For the milestone, we mark things as "some-day" by default, they only get to another milestone if they are scheduled as part of a release. The things tracked on this issue are separate individual problems, so they are unlikely to be worked on as a single item, and to be considered fixed by any single PR. Lots of people in the core dev team and beyond are aware of those issues, and of their impact on long-term maintainability of the codebase, so we're trying to tackle them.

---

Based on recent discussions among core devs, I have renamed this issue to be about "UI architecture" rather than CSS only (if I had more time, I'd also add HTML/JS items to the problems/caveats/solutions above).

I think now would also be a good time to share notes from the 2018 State of Wagtail meeting about front-end maintainability, which is very relevant to this issue, and shows where the core team is at. I wanted to make a blog post out of those but never got around to doing it 😅. This "State of Wagtail" meeting was held at Wagtail Space 2018, with part of the core dev team present, and open to the public.

---

# State of Wagtail 2018 – Front-end maintainability

> 2pm Amsterdam time, March 15th, 2018.

## The problem

- **TL;DR;**
  - Front-end code reusability and maintainability is an afterthought, refactorings are always painful.
  - Heavy exploratory manual testing is mandatory for even the simplest changes.
  - Mobile support and visual consistency are harder than they should be (eg. breakpoints are not consistent)
  - None of those problems are interesting to work on – people prioritise features over future maintainability
- **No automated tests**
  - Except for the React components (eg. “Pages” explorer menu)
    - But only unit tests, which is quite lame for UIs.
  - Manual testing is a must
    - It takes a good 5-10 minutes to set up 2 Wagtail instances side by side - one with the PR to review, one with master.
    - It takes **± 5 minutes per browser** to review even the simplest of front-end changes (eg. #3069) per browser 
    - Decently reviewing a change is at least 7 browsers: Chrome, Safari, Firefox on macOS + IE11, Edge on BrowserStack + iOS, Android on real devices
    - In theory it’s [15 browser / version / OS combinations](http://docs.wagtail.io/en/v2.0/contributing/developing.html#testing).
- **Loose CSS architecture**
  - https://github.com/wagtail/wagtail/issues/3804#issue-253102237
  - Split between “old style” styles and “new style” styles
- **Loose HTML architecture**
  - Tables and lists for layout
    - Very hard to refactor, and to make work on mobile
    - Unusable page structure for screen readers
  - Very few reusable components/templates
- **Loose JS architecture**
  - JS files loaded here and there, in the global scope, with jQuery code
  - No unit tests
  - Most of the code not using any dependency management
  - Enforce JS style guide: see #2797 
  - Split between “old style” and “new style”

Examples of those problems: 

- Prioritise features over maintainability – #4215
- No tests – jQuery date picker upgrade: #4337
- Overuse of bare-element styles: https://github.com/wagtail/wagtail/blob/e4f4383a586923433d533074305423d01e94b8d6/wagtail/admin/static_src/wagtailadmin/scss/components/_forms.scss#L7
- bakerydemo’s 1000-lines CSS file
  - “The bakery demo avoids using tooling so doesn't use SASS.”
  - https://github.com/wagtail/bakerydemo/blob/master/bakerydemo/static/css/main.css

## Solutions

### Pattern library

- High-value, high cost
- A LIVING pattern library – it should be easier to reuse the patterns than to build without them.
- High-value end to end tests on the patterns
- UI component library: #382, Adds wagtail ui template tag for making buttons: #1435
- This is a process/workflow as much as it is an architecture / code design artefact.
- https://storybook.js.org/ might come in handy here

### Improvements to the existing tooling

- [Prettier](https://prettier.io/)
- Git hooks: whitespace, CSS linting, JS linting, unit tests, snapshots, docs
- Better linting
  - [stylelint config](https://github.com/wagtail/wagtail/blob/master/.stylelintrc.yaml)
- Live reload

### Tests

- Automated test suites
  - Hugo / Alex started working on some automated tests at Lukkien (based on the cucumber boilerplate and BakeryDemo) eventually we could connect this to BrowserStack when we know how to automate a BakeryDemo boot on a certain PR.
  - Tools
    - a11y
    - Visual regression tests
    - E2E tests
  - See https://github.com/springload/draftail/tree/master/tests 
- Flow testing vs visual testing
  - Selenium (& Cucumber) at Four Digits, Lukkien
- Separate project from Wagtail?
  - CI pipeline is slow
  - Could be a separate workflow from CI

### Targeted refactorings (thankless pit of despair)

- Lower the overall CSS complexity by monitoring specificity and rewriting selectors with new classes, without elements. 
- Move all breakpoint-specific CSS to within its target selector
- Move all JS to Webpack (and ES6?)
- Rebuild more high-value components with React and ES6

### (more front-end developers)

  - Doh!

### Impact / effort matrix of the above

![image_preview](https://user-images.githubusercontent.com/877585/45695377-f4556f00-bb69-11e8-9e39-44d582d309b8.png)

## Potential work to trial this on

### Accessibility  improvements

- [label:Accessibility](https://github.com/wagtail/wagtail/issues?q=is%3Aopen+is%3Aissue+commenter%3Athibaudcolas+label%3AAccessibility)
- [Making Wagtail Accessible for users with disabilities](https://github.com/wagtail/wagtail/issues/4199)

### Choosers redesign and rebuild

- Chooser fields: #4055
- Chooser modals: #3038

### New login flow

- See #2309 

### (front-end extensibility by third-party packages)?

- “It’s always good to have dreams”
- npm package for Wagtail, with all client-side code
- Admin color themes and customization: #2943
- Expose admin style to plugins: #2478
- https://github.com/thibaudcolas/wagtail_npm_dependencies_experiment
- https://github.com/springload/draftail/#ui-and-styling

**Comment by patrick91** [comment]
Could be worth having a look at for the e2e tests http://cypress.io/ :)

**Comment by lb-** [comment]
Just wanted to add also that it appears that the version of Eslint we are using (~2.9.0) is now quite old, with v5 being released recently. I know this ticket is mostly about scss/css but just FYI.

**Comment by thibaudcolas** [comment]
FYI we’ve discussed this in today’s core team meeting, specifically from the perspective of legacy (vintage!) JS libraries (raised by @kaedroho).

The TL;DR; from this discussion is that we intend to move away from jQuery (towards vanilla JS), jQuery UI & Bootstrap (towards more purpose-specific libraries). And of course to Webpack as the build tool for all JS & CSS of the Wagtail admin.

**Comment by thibaudcolas** [comment]
I’ve recently been considering which parts of this were still relevant, and whether to make a "2020" update to this all – the answer is that pretty much all of this still is relevant, and it’s felt quite heavily when doing major changes like those necessary for accessibility (#4199), or icons (#6107), which took many months’ more effort than if Wagtail’s front-end was better architected. We essentially waste a lot of time updating patterns copy-pasted inconsistently across a big app, rather than being able to change components in isolation. I’ll focus on the rest of the update on solutions rather than problems though.

## Changes since the last update

- The SCSS refactoring (#6144) led by @nmorduch has been quite successful, moving more of the code to separate files. There’s more to do on that front: #5015.
- There was a similar JS refactoring piece started by @jonnyscholes in #5252, but that has stopped after a couple components.
- As part of the icons’ rework (#4821), @allcaps and @Scotchester took the time to refactor icons to a reusable component (via a template tag), which is essentially exactly what we would want to do for all UI components (or a similar approach with template partials includes, or Jinja2 macros, or React components)
- @lb- did a lot of good work with https://github.com/wagtail/eslint-config-wagtail and https://github.com/wagtail/stylelint-config-wagtail
- With #6105 (draft), we’re getting very close to removing Gulp and switching to Webpack only, which will eventually allow us to do more optimisations about what front-end code is loaded where.
- There’s now clearer plans to set up Prettier (#6059).

## What to do next

The overall direction I would suggest to get out of this mess is to refactor the whole of Wagtail’s UI to be powered by a living pattern library, as suggested in https://github.com/wagtail/wagtail/issues/3804#issuecomment-422424260 and initially in #382.

Now working at Torchbox, I have a pretty clear sense of what this would look like: using https://github.com/torchbox/django-pattern-library, in conjunction with Storybook (https://github.com/torchbox/storybook-django), so we can have a living pattern library for both Django Templates, and React components. Both of those projects are relatively recent, but django-pattern-library has been in use for years internally at Torchbox, and Storybook itself has been around for years too.

The advantages of this approach are that:

- We’d be able to work on UI components in isolation from where they are used in Wagtail.
- We’d be able to _test_ UI components in isolation – for accessibility issues and UI regressions in particular
- Since the components would be defined as isolated React components or template partials, they can be rendered outside of the Wagtail UI. This means we can test them without expensive browser automation to navigate around the Wagtail admin.
- Since each component would have "stories" to demonstrate its different variations, we wouldn’t have to set up expensive browser automation or hard-to-maintain fixtures in order to test specific parts of the UI.

With the Storybook version of this pattern library, we’d be able to leverage the Storybook ecosystem, which has well established tools for UI library smoke testing, visual regression testing, and accessibility checks. As well as integrations with design tools (Sketch, InVision, Zeplin). This could be a way for us to modernize Wagtail’s approach to design, and make it more open to third-party contributions (see https://github.com/wagtail/rfcs/blob/master/text/037-accessibility-support.md#3-make-universal-design-and-accessibility-part-of-wagtails-design-and-development-process).

### What would this look like practically?

Components would be defined as folders, with all of the components’s code co-located:

```
.
├── accordion
│   ├── accordion.html
│   ├── accordion.py
│   ├── accordion.scss
│   ├── accordion.test.js
│   ├── accordion.ts
│   ├── accordion.yaml
│   ├── accordion_section.html
│   └── accordion_section.yaml
├── banner
│   ├── banner.py
│   ├── home_banner.html
│   ├── home_banner.yaml
│   ├── split_banner.html
│   ├── split_banner.scss
│   ├── split_banner.stories.tsx
│   └── split_banner.yaml
└── button
    ├── Button.stories.tsx
    ├── Button.tsx
    ├── button.html
    ├── button.py
    ├── button.scss
    └── button.yaml
```

The template partial, React component, stylesheet, test data, vanilla JS widget, per-component documentation, would all live in the same folder. For a Django templates integration, components that would make use of it could define their own template tag like our new `{% icon %}`.

Here is what component reuse would look like:

```twig
{# Django templates partials #}
{% include "ui/button/button.html" with label="Get started" variant="outline" color="primary" href="/" %}

{# Django templates tags #}
{% button label="Get started" variant="outline" color="primary" href="/" %}

{# React #}
<Button label="Get started" variant="outline" color="primary" href="/" />

{# Jinja macro #}
{{ button(
    label="Get started",
    variant="outline",
    color="primary",
    href="/",
) }}

{# Django templates partials #}
{% include "ui/banner/split_banner.html" with title="Stories from our Salesforce migration" description="Whisperly Ltd" image=image %}

{# Django templates tags #}
{% split_banner title="Stories from our Salesforce migration" description="Whisperly Ltd" image=image %}


{# React #}
<SplitBanner title="Stories from our Salesforce migration" image={image}>
    <p>Whisperly Ltd</p>
    <Button href="/">Get Started</Button>
</SplitBanner>

{# Jinja macro #}
{{ split_banner(
    title="Stories from our Salesforce migration",
    description="Whisperly Ltd",
    image=image,
) }}

{# Jinja macro with children #}
{% call split_banner(title='Hello World') %}
    <p>Whisperly Ltd</p>
    {{ button(label="Get started", href="/") }}
{% endcall %}
```

**Comment by thibaudcolas** [comment]
We’ve discussed the proposal in today’s accessibility team meeting, there was some consensus that this felt like a good way forward. I think I’ll open an RFC to describe this further and more formally ask for feedback.

**Comment by kaedroho** [comment]
@thibaudcolas for React components, have we decided yet how these are going to be exported for third party apps to reuse?

**Comment by thibaudcolas** [comment]
We’ve thought about this in the past but never made any big steps towards that goal. The options are:

- Expose the React components as global variables on the page. This is done with Webpack’s `expose-loader`, and it should be possible to transparently load them as if they were modules by configuring Webpack’s module resolution to fake that. This only goes so far – with this route you also need to use Wagtail’s React library, similarly exposed, otherwise it causes mismatches of React versions (this should hopefully work better in React 17, but still not ideal).
- Bundle the components as a Webpack Dll with DllPlugin and DLLReferencePlugin, which Wagtail could reuse, as well as other projects using Webpack
- Publish the components to npm as a standalone package

**Comment by kaedroho** [comment]
Once we've got rid of IE11 support, we would be able to use ES6 modules in Wagtail.

I'm wondering if this makes this problem easier to solve? I'm thinking that Wagtail could provide a UI component library on an importable path. This UI library would of course have a stable, documented API. 

For example, a third-party app implementor could import the ``Icon`` component with the following:

```javascript
import { Icon } from '/static/wagtail/components.js';
```

Do you think that could work?

**Comment by thibaudcolas** [comment]
Hmm good question, that definitely sounds worth trying :) I don’t know enough about ES modules bundling to have an informed opinion. This sounds similar to the "global variables on the page" option, with the big benefit that you’d be able to dynamically load only the components you need. I imagine this would need to use the [dynamic `import()`](https://github.com/tc39/proposal-dynamic-import) syntax.
