### ISSUE TITLE
Wagtail shows twice in admin

### ISSUE THREAD

**Issue by devisscher** [wagtail/wagtail#3809]
### Issue Summary

I just upgraded to Wagtail 1.12 and I'm getting a layout issue in the admin section. The logo (Wagtail bird) is showing twice.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Create super user. 
3. Log in to admin.
4. View admin and see 2 logos

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

* Python version: 2.7.
* Django version: 1.11.4
* Wagtail version: 1.12
* Browser version: Firefox, Safari, Chrome

<img width="93" alt="wagtail_-_exploring_home" src="https://user-images.githubusercontent.com/9765013/29830090-348223a6-8caf-11e7-8830-7deeedb3d20a.png">

### Markup

```
<a href="/admin/" class="logo" title="Wagtail v.1.12">
     <div class="wagtail-logo-container__mobile u-hidden@medium">
           <img class="wagtail-logo wagtail-logo__full" src="/static/wagtailadmin/images/wagtail-logo.svg" alt="Wagtail" width="80">
     </div>

                    
     <div class="wagtail-logo-container__desktop u-hidden@small">
           <img class="wagtail-logo wagtail-logo__body" src="/static/wagtailadmin/images/logo-body.svg" alt="">
            <img class="wagtail-logo wagtail-logo__tail" src="/static/wagtailadmin/images/logo-tail.svg" alt="">
              <img class="wagtail-logo wagtail-logo__eye--open" src="/static/wagtailadmin/images/logo-eyeopen.svg" alt="">
               <img class="wagtail-logo wagtail-logo__eye--closed" src="/static/wagtailadmin/images/logo-eyeclosed.svg" alt="">
       </div>  
      <span class="u-hidden@medium">Dashboard</span>
</a>
```

**Comment by gasman** [comment]
Hi @devisscher - does the problem persist if you force-refresh the page (shift+ctrl+R, or shift+cmd+R on Mac)?

**Comment by devisscher** [comment]
Hi @gasman, refreshing fixed the problem. Thank you.
