### ISSUE TITLE
Doubled bird logo image

### ISSUE THREAD

**Issue by moreplavec** [wagtail/wagtail#3811]
### Issue Summary
Doubled logo icon in left top corner.

### Steps to Reproduce
Update/install Wagtail 1.12

### Technical details
I tried Safari and Chrome, both running on MacOS (all latest version).

![wagtail_-_images](https://user-images.githubusercontent.com/6907705/29836706-45e48890-8cf6-11e7-8f4b-9b3cea2a80a7.png)

**Comment by gasman** [comment]
Hi @moreplavec,
Please see #3809 - you need to refresh the page.
