### ISSUE TITLE
Disabling related videos for youtube embeds?

### ISSUE THREAD

**Issue by paramono** [wagtail/wagtail#3835]
### Issue Summary

I created a YouTube video on a page; however, after this video finishes playing, YouTube displays related videos. I want to turn these off. 

In general, one can add `rel=0` GET-parameter to a video link to resolve this issue, but this becomes trickier since I use oEmbed. A naive approach (using new configuration options for embeds since 1.12) would be:

```
WAGTAILEMBEDS_FINDERS = [
    {
        'class': 'wagtail.wagtailembeds.finders.oembed',
        'providers': [youtube],
        'options': {'scheme': 'https', 'rel': '0'}
    },
    {
        'class': 'wagtail.wagtailembeds.finders.oembed',
    }
]
```

But the oEmbed endpoint for YouTube simply ignores `rel` parameter and keeps showing related videos. I found a possible workaround - to alter the src attribute of iframe in html returned by oEmbed, but this seems to be too hacky for such a simple thing.

Is there a more obvious way to resolve this issue? 
I understand that this is mostly YouTube's fault, but I wonder whether there's a better workaround.

### Steps to Reproduce

Create a YouTube video on any Wagtail page using embeds. Notice that even if you include `rel=0` in your video url or WAGTAILEMBEDS_FINDERS options, YouTube's oEmbed endpoint still returns html without this parameter in video's url. Manually editing iframe src in browser solves the issue.

### Technical details

* Python version: 3.5.2 
* Django version: 1.11
* Wagtail version: 1.12
* Browser version: Chromium Version 60.0.3112.78 (Developer Build) Built on Ubuntu, running on LinuxMint 18 (64-bit)

**Comment by kaedroho** [comment]
Thanks for the suggestion @paramono 

I think this one is best solved by creating a new embed finder class which parses the HTML returned from YouTube to add that ``?rel=0`` parameter in to it. This should be possible to do in your own project or a third-party app, but I'm very reluctant to support non-standard/provider-specific extensions to the embeds module in Wagtail as these could break over time and become a massive maintainability burden for the core team.

**Comment by paramono** [comment]
>I think this one is best solved by creating a new embed finder class which parses the HTML returned from YouTube to add that ?rel=0 parameter in to it.

I see. I kind of expected this, but was hoping there is some better way.

>This should be possible to do in your own project or a third-party app, but I'm very reluctant to support non-standard/provider-specific extensions to the embeds module in Wagtail as these could break over time and become a massive maintainability burden for the core team.

This is understandable. It would be ideal if YouTube allowed more flexibility, but since it doesn't, integrating workarounds into wagtail code is simply wrong. In that case, I will build a 3rd-party app to handle this issue.

Thank you very much for your comment, @kaedroho!
