### ISSUE TITLE
Editing a link in Rich Text Editor should allow named links (HTML anchor hashes)

### ISSUE THREAD

**Issue by axper** [wagtail/wagtail#3837]
### Issue Summary

I have a page which has multiple sections. Each section has an id like `<div id="section1" ...`. I want to be able to insert links to the same page's other sections using the "link tool" in rich text editor. However there is currently no way to do this.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py as follows:
```
class WhateverPage(Page):
    body = RichTextBlock()

    content_panels = Page.content_panels + [
        FieldPanel('body'),
    ]
```
    Add `{{ page.body }}` to `templates/whatever_page.html`.
3. Open the editor in admin
4. Click the "Add/Edit Link" tool
5. Select "External link"
6. Put `#whatever` in "URL:" field
7. Put `Whatever` in "Link text" field
8. Click "INSERT LINK"

What happens: Validation error appears for "URL:" field with this text: Enter a valid URL.
What is expected: Link should be inserted and the resulting HTML should look like this:

```
<a href="#whatever">Whatever</a>
```

Currently I have 2 solutions for this problem:
1. Put the full url in, i.e. `http://example.com/page#whatever` but this breaks flexibility of changing URLs.
2. Make custom anchor block and hack together the page, but then the content is disjoint and very hard to edit.

Also I have read and 100% agree with "faster horses" (https://torchbox.com/blog/rich-text-fields-and-faster-horses/), but this really feels like it should be possible in current Rich text editor.

### Technical details

* Python version: 3.6.2
* Django version: 1.11
* Wagtail version: 1.12.1
* Browser version: Chrome 61

**Comment by gasman** [comment]
Hi @axper - thanks for the report! This is covered in #1049.
