### ISSUE TITLE
OEmbed bug with Vimeo (plus some others)

### ISSUE THREAD

**Issue by mixxorz** [wagtail/wagtail#3842]
When trying to embed Vimeo videos, it fails with `EmbedNotFoundException`

To duplicate:
```python
from wagtail.wagtailembeds.finders.oembed import OEmbedFinder

finder = OEmbedFinder()
finder.find_embed('https://vimeo.com/8733915')
```

This happens because some of the endpoints have `{format}` in them. `{format}` is meant to be replaced with `json`, but it isn't. There's a line where `{format}` is being replaced with `json` in the urls, but as far as I can tell, urls are just used for pattern matching.

https://github.com/wagtail/wagtail/blob/92b4f68c67e36ee63b0902dbbf5187e8cf243b0c/wagtail/wagtailembeds/finders/oembed.py#L26-L33

Likely a simple mistake.

This issue is new with Wagtail 1.12 introduced in https://github.com/wagtail/wagtail/commit/01e2d5f4a0e94fcb5fdaee0dc8ea93455b6a00ab

**Comment by gasman** [comment]
Fixed in #3843
