### ISSUE TITLE
Missing JS libs

### ISSUE THREAD

**Issue by kakulukia** [wagtail/wagtail#3859]
When starting wagtail i get the following errors (in the browser)
jquery-2.2.1.js is missing
jquery-ui-1.10.3.js is missing 
jquery.dlmenu.js is missing

and indeed in static/wagtailadmin/ja/vendor those files are missing .. but insted there are
jquery-2.2.1.min.js
jquery-ui-1.10.3.min.js
But still no jquery.dlmenu.js

What might be wrong here?

Wagtail versions tested 1.11.1 and 1.12.1 - just deleted my current version and installed a fresh one, but i still get the same error.

**Comment by gasman** [comment]
Hi @kakulukia,
The filenames jquery-2.2.1.js, jquery-ui-1.10.3.js and jquery.dlmenu.js are not referenced anywhere in the Wagtail codebase - dlmenu was removed in Wagtail 1.11 when the new explorer menu was added. If your browser is requesting those files, it must be coming from your own code, a third-party Wagtail library that hasn't been updated for Wagtail >=1.11, or some old cached HTML.

If you can consistently reproduce this problem, please open a new issue giving full details of how to reproduce it, starting from a clean Wagtail installation.

**Comment by kakulukia** [comment]
thanks .. it really were the remains of an old wagtail installation used in a custom template .. THX!
