### ISSUE TITLE
Plans to remove React due to patent issue

### ISSUE THREAD

**Issue by robvdl** [wagtail/wagtail#3861]
I was wondering if Wagtail had any plans to remove React due to the recent licensing issues that have come to light.

Apache projects are already removing it, and so is Wordpress.

https://ma.tt/2017/09/on-react-and-wordpress/

It's a shame because hasn't React only just been added to Wagtail has it not?  A possible alternative would be Vue.js, some people are also talking about Preact as a drop in replacement but I don't know if that really dodges the patent issue.

**Comment by SalahAdDin** [comment]
You are rigth, Torchbox could be have problems with licecing, but i'm not sure about it.

**Comment by robvdl** [comment]
Yes it's a very difficult situation to be in, a number of years ago so many projects chose React and didn't see this coming, I didn't see this coming myself.  I was also thinking if this also affects users of Wagtail, if anyone was to make something with Wagtail that "competes" with Facebook's business would they be in breach of the React license?

**Comment by robvdl** [comment]
Also it seems to be affecting GraphQL as well, which really made me second guess myself using any Facebook tech in my own projects going forward.  I don't fully understand the implications of the whole GraphQL issue, but https://medium.com/@dwalsh.sdlr/using-graphql-why-facebook-now-owns-you-3182751028c9

**Comment by lboaretto** [comment]
A bad news for the new Explorer and Draftail :(

**Comment by SalahAdDin** [comment]
I think we have to wait that `wagtail` staff official comunicate.

**Comment by tomdyson** [comment]
Thanks for raising this, @robvdl. We're discussing it with the core team and will report back here.

**Comment by tkjone** [comment]
Looks like this won't be a problem anymore:  

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

**Comment by robvdl** [comment]
That is very interesting indeed, Facebook did refuse to change the license before and shot the idea down, but it looks like given enough pressure from the community they finally broke. That is good, they must have finally realised there is more value into holding onto your users.

So this can be closed now?

**Comment by BertrandBordage** [comment]
@robvdl: Let’s wait for them to actually perform the licence change before closing this issue.

**Comment by robvdl** [comment]
Yes probably a good idea, I read that Facebook was quite reluctant to change the license and did it mostly to keep the community happy (which isn't exactly a surprise), but ultimately they do still believe that modified BSD could have worked which to me personally still rings warning bells and makes me a bit wary to choose React in future projects at least.

**Comment by sebworks** [comment]
Given that they have modified the license, https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/, I think it safe to use React again.

**Comment by thibaudcolas** [comment]
React 16.0.0 is now out with the new MIT license, and they've also released it under MIT as 15.6.2.

Is anyone interested in submitting a PR with the upgrade to 15.6.2? Wagtail is using 15.5.4 at the moment, so it should be a pretty painless process.

**Comment by coredumperror** [comment]
Is this really resolved? This article seems to indicate that the patent circus isn't truly over:
https://medium.com/@dwalsh.sdlr/reacts-new-mit-license-the-circus-enters-it-s-third-ring-2f1bf989a67f

**Comment by thibaudcolas** [comment]
This is a legal concern, I don't believe anyone contributing to those conversations in the case of Wagtail is in a position to state whether this change can be considered a (legal) resolution or not.

For our current purpose, I do believe that the relicensing and removal of the patents grant puts React (back) on equal footing with the rest of open-source software licensed as MIT (Vue.js, Preact, and many other libraries/frameworks), which do not provide a patent grant with their MIT license either, and for all of which we are in no place to judge whether they contain any more or less patented code than React.

For the purpose of this issue in this repository, #3884 being merged in master and the next release of Wagtail (1.13) shipping with MIT-licensed React, I will consider this resolved and now close the issue. We can of course reopen if necessary.
