### ISSUE TITLE
Directory structure for images/documents

### ISSUE THREAD

**Issue by ppershing** [wagtail/wagtail#3867]
I have a Wagtail travel blog with 1000+ images and counting. Of course, with this number of images selecting an image becomes quite a tricky business if it isn't one of the newly uploaded. Image tags are a bit of a help but it still does not work perfectly.

What I suggest is to extend Images UI with a possibility to categorize images into a directory structure (e.g., I would appreciate if I can organize my images in something like "Trips/Chile/2017-01-01"). Note that this could also affect the location where the physical files are stored (I am not super-happy with flat /media directory with tons of files) but this isn't that important

**Comment by Proper-Job** [comment]
@ppershing have you tried the [collections](http://docs.wagtail.io/en/v1.12.2/releases/1.4.html#collections-for-image-document-organisation) feature for images?

**Comment by luizboaretto** [comment]
@Proper-Job I think Collections is just for organization / permission in UI. 

What I understand is that @ppershing wants to organize the physical files into directories. [[1]](https://stackoverflow.com/questions/42087838/possibility-to-upload-wagtail-documents-to-a-subfolder-of-documents), [[2]](https://stackoverflow.com/questions/37151874/any-way-to-organize-images-into-folders-in-wagtail-cms), [[3]](https://github.com/anteatersa/Wagtail-Image-Folders)

**Comment by Proper-Job** [comment]
@luizboaretto @ppershing IMHO collections address the use case @ppershing is describing exactly.  You can create a new collection called "Trips/Chile/2017-01-01" and add the images you like to that collection.

IMHO maintaining a (dynamic) directory structure in the file system is a recipe for disaster.  Imagine you moved an image from one folder to another: you'd have to mirror that move in the filesystem.  That simple use case could go wrong in so many ways.

**Comment by gasman** [comment]
Yes, I think this is covered by the collections feature.
