### ISSUE TITLE
UnicodeEncodeError with wagtaildocs umlaut in filename with gunicorn and boto

### ISSUE THREAD

**Issue by derhedwig** [wagtail/wagtail#3870]
Hi!
I get `UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 216: ordinal not in range(128)` when documents have umlauts in their filenames.

I am using **gunicorn** on heroku and **S3BotoStorage**, so serve.py is not using sendfile.

### Steps to Reproduce
Use S3BotoStorage,
use gunicorn,
upload a file in wagtaildocs with a filename with some non-ascii chars...

This gunicorn issue looks like gunicorn wants utf8 strings in headers quoted: https://github.com/benoitc/gunicorn/issues/1214

### Possible Solution
In https://github.com/benoitc/gunicorn/issues/1214 they propose `urllib.parse.quote(doc.filename)` in serve.py

### Technical details

* Python 3.5.3
* Django==1.11.5
* wagtail==1.11.1
* gunicorn==19.7.1
* boto3==1.4.7
* botocore==1.7.8

**Comment by lb-** [comment]
Just adding some notes, it looks like this might be a bit more complicated and need some decisions.

Might need someone with some better knowledge around http headers and conventions there to help out.

Helpful links
* https://stackoverflow.com/questions/1361604/how-to-encode-utf8-filename-for-http-headers-python-django
* https://tools.ietf.org/html/rfc6266 (specifically Appendix D)
* https://www.djangosnippets.org/snippets/1710/ (older but helpful snippet)

Rough summary (of RFC6266 appendix D): 
* Include a "filename" parameter when US-ASCII ([US-ASCII]) is sufficiently expressive.
* Avoid including the percent character followed by two hexadecimal characters (e.g., %A9) in the filename parameter.
* Include a "filename*" parameter where the desired filename cannot be expressed faithfully using the "filename" form.

**Comment by gasman** [comment]
Fixed in #5267
