### ISSUE TITLE
Wagtail is not creating unique Rendition file names when using S3

### ISSUE THREAD

**Issue by nathanbegbie** [wagtail/wagtail#3883]
### Issue Summary

*What:* In certain cases, different Image Rendition file names are given the same name and overwriting older files where names collide.

*When:* 
- there are 2 or more images that share the same beginning of the file title e.g. `abcdefghijklmnopqrstuvwxyz.jpg` and `abcdefghijklmnopqrstuv0000.jpg`
- the image file names are very long and need to be truncated when naming the file renditions
- I am using AWS S3 for media storage

*The following happens:* When creating a rendition with the same `filter_spec`, the rendition's file names for 2 or more images, that have above properties, are allocated the same name.
This means that one or more renditions are simply overwritten with the new rendition.
I suspect that this is due to a failing check whether the image with the same name already exists.

### Steps to Reproduce

Below is the **expected** behavior when creating renditions, using local storage:
```
$ ./manage.py shell
Python 2.7.13 (default, Sep 1 2017, 11:24:58)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from wagtail.wagtailimages.models import *
>>> from django.conf import settings
>>> from wagtail import VERSION
>>> print VERSION
(1, 9, 1, u'final', 0)
>>> settings.DEFAULT_FILE_STORAGE
'django.core.files.storage.FileSystemStorage'
>>> Image.objects.count()
2
>>> img_1 = Image.objects.first()
>>> img_2 = Image.objects.last()
>>> img_1.file.name
u'original_images/abcdefghijklmnopqrstuvwxyz.jpg'
>>> img_2.file.name
u'original_images/abcdefghijklmnopqrstuv0000.jpg'
>>> img_1.renditions.all()
[]
>>> img_2.renditions.all()
[]
>>> rend1 = img_1.get_rendition('fill-300x150|jpegquality-60')
>>> rend1.url
'/media/images/abcdefghijklmnopqrs.2e16d0ba.fill-300x150.jpegquality-60.jpg'
>>> rend2 = img_2.get_rendition('fill-300x150|jpegquality-60')
>>> rend2.url
'/media/images/abcdefghijklmnopqrs.2e16d0ba.fill-300x150.jpegquality-60_06esx7Y.jpg'
```

Note that the filenames for the renditions, where there was a naming collision, has added on 
a string of characters at the end of the file name. In this case `_06esx7Y` 
for the second rendition.

This is the behavior that is unexpected, when using AWS S3:
```
$ ./manage.py shell
Python 2.7.13 (default, Sep  1 2017, 11:24:58)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from wagtail.wagtailimages.models import *
>>> from django.conf import settings
>>> from wagtail import VERSION
>>> print VERSION
(1, 9, 1, u'final', 0)
>>> settings.DEFAULT_FILE_STORAGE
'storages.backends.s3boto.S3BotoStorage'
>>> Image.objects.count()
2
>>> img_1 = Image.objects.first()
>>> img_2 = Image.objects.last()
>>>
>>> img_1.file.name
u'original_images/abcdefghijklmnopqrstuv0000.jpg'
>>> img_2.file.name
u'original_images/abcdefghijklmnopqrstuvwxyz.jpg'
>>> img_1.renditions.all()
[]
>>> img_2.renditions.all()
[]
>>> rend1 = img_1.get_rendition('fill-300x150|jpegquality-60')
>>> rend1.url
'https://molotestbucket.s3.amazonaws.com/images/abcdefghijklmnopqrs.2e16d0ba.fill-300x150.jpegquality-60.jpg'
>>> rend2 = img_2.get_rendition('fill-300x150|jpegquality-60')
>>> rend2.url
'https://molotestbucket.s3.amazonaws.com/images/abcdefghijklmnopqrs.2e16d0ba.fill-300x150.jpegquality-60.jpg'
```

Note that the 2 Renditions for different images, now have identical URLs (and thus filenames).
I would expect that they would be different, as seen in the former example.

### Technical details

* Python version: `2.7.13`
* `django==1.9.13`
* `wagtail==1.9.1`
* `boto==2.48.0`
* `django-storages==1.6.3`

**Comment by chosak** [comment]
@nathanbegbie I'm not sure this is a Wagtail issue: have you set `AWS_S3_FILE_OVERWRITE` to `False`? See django-storages docs [here](http://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings) and code [here](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto.py#L180). By default the `S3BotoStorage` class doesn't appear to duplicate the file system behavior of appending random characters as you want.

**Comment by gasman** [comment]
Thanks for the report @nathanbegbie - sounds like this is covered by #3206. (Also related: #1686, #3108)

**Comment by nathanbegbie** [comment]
Thanks @chosak and @gasman,  adding `AWS_S3_FILE_OVERWRITE = False` to settings solved my problem.

**Comment by Xowap** [comment]
@chosak it's 2019 and I've just got the same problem happening. The `AWS_S3_FILE_OVERWRITE` solution worked, yet I'm wondering if some complementary safety could be put in place.

Basically, the issue comes from the fact that file names [are truncated](https://github.com/wagtail/wagtail/blob/88d5a8cfee653e654a6a86b55ea0a365f3733ed0/wagtail/images/models.py#L306). If you have a lot of filters and your users uploaded a lot of pictures starting with the same name ("Screenshot from the ...") then the truncating causes all the files to get the same name.

Thus I'd like to suggest to use the file name directly into the cache key computation, which would greatly reduce the risks of collisions.

What do you think?

(please note I didn't take the time to fully understand your currently open merge request, but I think it does not implement this)
