### ISSUE TITLE
Improvement: Categorization of images for quicker selection

### ISSUE THREAD

**Issue by khink** [wagtail/wagtail#3885]
Currently all images are stored in a single folder. This is a very fine default for smaller numbers of images.

For sites with large amounts of images, it would be handy to be able to have a separate folder for, say, logos / images of products / diagrams / photos of kittens . The scenario here is that when choosing an image, it's a nuisance to have to browse through many pages of possible images. It would be easier if we could narrow down the selection. 

Apart from folders, tags could also be an option.

**Comment by gasman** [comment]
Hi @khink - isn't this just the [collections](http://docs.wagtail.io/en/v1.12.2/releases/1.4.html#collections-for-image-document-organisation) feature?

**Comment by khink** [comment]
@gasman I think this is just what we want Thanks!
