### ISSUE TITLE
Resize in templates is not working?

### ISSUE THREAD

**Issue by moreplavec** [wagtail/wagtail#3888]
### Issue Summary
I can't use resize function in template, only "original" images work.

### Steps to Reproduce
Based on this help page http://docs.wagtail.io/en/v1.12.2/topics/images.html#more-control-over-the-img-tag i created simple image resize in template:

`{% image block.value.image width-400 as picture %}
<img src="{{ picture.url }}">`

but i get only `<img src="/media/not-found">`. If i change image tag to:

`{% image block.value.image original as picture %}`

image is rendered as expected.

### Technical details

* Python version: Python 3.5.2
* Django version: latest
* Wagtail version: latest
* Browser version: firefox, safari, chrome, all latest

**Comment by gasman** [comment]
Hi @moreplavec,
Please tell us the specific versions of Django / Wagtail you're using - simply saying "latest" isn't helpful if we need to review this issue at some point in future.

`<img src="/media/not-found">` indicates that the original image file (in /media/original_images) has been deleted, so it's not possible to generate new rendered versions. If you try to edit the image through the 'images' area of the Wagtail admin, do you get the message "The source image file could not be found. Please change the source or delete the image."? Does the same problem occur when you select other images?

**Comment by moreplavec** [comment]
Looks like my own problem, the hint with original image was the clue. I copied only images not the original-images. So all images showed up in admin area but wasn't there to be served at spec. resolution. Thanks for help!
