### ISSUE TITLE
Make Promoted Search Results Orderable

### ISSUE THREAD

**Issue by mope** [wagtail/wagtail#3897]
In the settings menu there are sections for Users, Groups, Sites, Collections, Redirects and Promoted Search Results. In the Users, Groups, Sites and Redirects sections it is possible to reorder items by clicking on column titles. This is not possible in the Collections and Promoted Search Results sections. Collections are [under development](https://github.com/wagtail/wagtail/pull/3407) and so the inconsistency can be ignored in that case. However it would be useful and consistent if Promoted Search Results could be ordered by number of views, and perhaps search terms as well.

**Comment by lb-** [comment]
Implemented via #5299
