### ISSUE TITLE
Unclear in documentation if PostgreSQL search backend supports indexing extra fields

### ISSUE THREAD

**Issue by sivictorallen** [wagtail/wagtail#3899]
### Issue Summary

Search indexing page warns that "Indexing extra fields is only supported with ElasticSearch as your backend." while PostgreSQL search backend page is described as "Supports all the search features available in Wagtail." The PostgeSQL backend in also recommended for "sites with less than a million pages"

It's unclear from the documentation if the PostgreSQL backend supports indexing extra fields.

### Steps to Reproduce

The extra fields warning can be viewed here: http://docs.wagtail.io/en/v1.12.2/topics/search/indexing.html
The warning has remained unchanged since before the PostgreSQL backend was introduced, which can be seen here:
http://docs.wagtail.io/en/v1.9/topics/search/indexing.html#indexing-custom-models

**Comment by gasman** [comment]
Thanks for the report @sivictorallen! Yes, that sentence is no longer accurate since the PostgreSQL backend was added - updated now.
