### ISSUE TITLE
Please correct text in Getting Started tutorial

### ISSUE THREAD

**Issue by gkahn** [wagtail/wagtail#3909]
I am going through the Getting Started tutorial and I think I found a error in the text. 
http://docs.wagtail.io/en/v1.12.2/getting_started/tutorial.html

In the "Overriding Context" section it says, 
"Now try unpublishing one of your posts - it should disappear from the blog index page. The remaining posts should now be sorted with the most recently modified posts first."

I believe it should be rewritten as, 
"Now try unpublishing one of your posts - it should disappear from the blog index page. The remaining posts should now be sorted with the most recently published posts first."

Since the code says to order_by('-first_published_at') the blog posts should sort on publish date not last modified date.

**Comment by gasman** [comment]
Thanks @gkahn! Now updated, in ef7ef8de13e89d32d0f03dc1e4fa3078da33e70d.
