### ISSUE TITLE
get_document_multi_form doesn't play well with WAGTAILDOCS_DOCUMENT_MODEL.

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#3921]
The function `wagtail.wagtaildocs.forms.get_document_multi_form()` builds it's Form object from a fixed set of field names: `['title', 'collection', 'tags']`. This means that the multiple-upload form can never set any other fields on a custom model that's set through `WAGTAILDOCS_DOCUMENT_MODEL`.

The PR for this would be easy, but I haven't got time to make it right now. You'd just need to change the function to this:
```python
def get_document_multi_form(model):
    return modelform_factory(
        model,
        form=BaseDocumentForm,
        fields=[field for field in model.admin_form_fields if field != 'file'],
        widgets={
            'tags': widgets.AdminTagWidget,
            'file': forms.FileInput()
        })
```
That does the equivalent of what `get_document_multi_form()` does today, while also making sure it includes custom fields.

**Comment by coredumperror** [comment]
I've gone ahead and created a PR for this: #3928.

**Comment by gasman** [comment]
Completed in #4840
