### ISSUE TITLE
V2 API Menu/Navigation endpoint

### ISSUE THREAD

**Issue by jmacaluso711** [wagtail/wagtail#3933]
Curious if there are plans to implement an endpoint for menus.  As it is now I'm making recursive calls to the api and building out the menu that way. Is there a recommended way or any examples of handling menus in a headless setup?

**Comment by kaedroho** [comment]
Menus can be implemented in many different ways in Wagtail, so we haven't pushed for one particular method for the API.

If you want to build a menu from your page tree, I think the best way would be to fetch all the pages with ``&show_in_menus=true`` and build up the tree on the client side (By default, Wagtail API returns pages in Depth-first search order https://en.wikipedia.org/wiki/Depth-first_search).

Currently, it's not possible to limit the max depth so this method might not be a good fit if you have a deep hierachy and want to limit the number of tiers that appear in the main menu.

**Comment by ddokter** [comment]
I'd like to take a long, hard look at the API, and maybe come up with a proposal for a somewhat cleaner and simpler version, based on the principles of HATEOAS. Maybe I should start a new version, say v3, next to v2, so as not to break stuff? Or is this a dumb idea anyway...

**Comment by gasman** [comment]
@ddokter It sounds like this might be a good candidate for an RFC... https://github.com/wagtail/rfcs

**Comment by ddokter** [comment]
Okido. I'll play around a bit first, then come up with a proposal. Should I draft  new one? Given that there already is an API proposal in there?

**Comment by gasman** [comment]
Yep, it should be a new RFC - RFC8 is essentially about the introduction of the v2 API, and other proposed changes are handled in separate RFCs ([RFC15](https://github.com/wagtail/rfcs/blob/master/text/015-revisions-api-revised.md) for example).

**Comment by ddokter** [comment]
@gasman RFC 019 in da house. Pull request done on the wagtail/rfc repo.

**Comment by Bulletninja** [comment]
Is there a way I can see that RFC? I only see up till the 18th one.

**Comment by thibaudcolas** [comment]
I’m unclear what there is to do here if anything, so will close this now. There’s certainly room for more API evolutions, some of which can be proposed as issues, or as RFCs. For menus specifically, I’d recommend following [Define custom, hierarchical navigation menus #12470](https://github.com/wagtail/wagtail/discussions/12470).
