### ISSUE TITLE
Add release channels for update notification

### ISSUE THREAD

**Issue by nek4life** [wagtail/wagtail#3938]
### Issue Summary

Now that there are LTS versions of wagtail add a release channel setting to configure the update message for users and perhaps which users see the upgrade message (I'm always an admin so maybe it already only shows in certain cases)

This request is so that users do not see upgrades if the development team or the business has requested that we only upgrade security patches on the latest LTS version of wagtail. In this case it is not necessary to see every update in between LTS version for our users. 

### Steps to Reproduce

Log into wagtail with a version of wagtail that is not the current version and observe the new upgrade available message.

**Comment by tomdyson** [comment]
Hi @nek4life, thanks for this. The upgrade message is only ever shown to admins. If it's still important for you to hide the message from admins for non-LTS releases, could you please suggest:

 - the message that should be shown when `WAGTAIL_ENABLE_LTS_UPDATE_CHECK` is true
   - when there is a point release to an LTS version that is later than the current version (e.g. you're on 1.8 and 1.8.1 is released)
   - when there is a new LTS release which is later than the current version (e.g. when you're on 1.8 and 2.2 is released)

Perhaps it would be adequate to highlight that the release you're on is an LTS release? E.g. 'Wagtail upgrade available. Your version: 1.8 LTS. New version: 1.13'

**Comment by nek4life** [comment]
@tomdyson that sounds like a pretty solid plan. Ideally we'd like to see if there is a security update available e.g. a point release for the current LTS or if there is a new LTS version available display that version as well.

If that option is on then I would not want to see the next version that is not an LTS version. We have admins who are not necessarily the development team. Why tempt them with new features if our development policy is to only update when a new LTS version is available? :D

**Comment by tomdyson** [comment]
> Ideally we'd like to see if there is a security update available e.g. a point release for the current LTS or if there is a new LTS version available display that version as well.

That makes sense. So, if `WAGTAIL_ENABLE_LTS_UPDATE_CHECK` is true:

 - Your version: 1.8 LTS. New version: 1.12 LTS _or_
 - Your version: 1.8 LTS. New version: 1.18.1 _but not_
 - Your version: 1.8 LTS. New version: 1.9

Does that sound right?

> If that option is on then I would not want to see the next version that is not an LTS version. We have admins who are not necessarily the development team. Why tempt them with new features if our development policy is to only update when a new LTS version is available? :D

Not to hijack your ticket, but Wagtail's release schedule (small, regular, frequent updates) is designed to encourage site owners to take advantage of the new features which are being added all the time, at a minimal expense. We target 30 minutes as the maximum time it should take to upgrade from one version to the next.
