### ISSUE TITLE
ImageChooserBlock label language to change image

### ISSUE THREAD

**Issue by heymonkeyriot** [wagtail/wagtail#3955]
![image](https://user-images.githubusercontent.com/11335309/31827690-4947b1be-b5b0-11e7-8b0f-d623f848df99.png)

Currently to change the image within a StreamField using ImageChooserBlock says `Choose another image`. This is potentially confusing as the user is changing the image and `another` is ambiguous in English (it could be 'to change' or 'add an additional image').

I think it would be clearer if it were to say `Change image`.

**Comment by chosak** [comment]
Would a change to the English phrase here necessitate a change to its various translations, for example [here](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailimages/locale/zh_CN/LC_MESSAGES/django.po#L372)?

**Comment by gasman** [comment]
@chosak Yep - we'd handle that through Transifex as part of our usual release process, though. https://github.com/wagtail/wagtail/wiki/Managing-Wagtail-translations
