### ISSUE TITLE
Ability to create new snippets from within page edit screen

### ISSUE THREAD

**Issue by chrxr** [wagtail/wagtail#396]
- User has almost finished creating a page
- User clicks wants to add a snippet for, say, a Contact.
- User clicks to add a snippet of type "Contact", but the contact they want doesn't yet exist.

Currently the user has to save as a draft, go to the snippets panel, find the right snippet type, and then add a new snippet. Then they have to go back to the page, and insert the correct snippet.

A simpler workflow would be to replicate the image upload modal, in that you can either select an existing snippet of that type, or create a new one inline in a second tab.

**Comment by tmsndrs** [comment]
This is a frustration for me. For me, the primary use case for adding new snippets (at least after an initial content input) is going to be from a specific piece of content. There are UI patterns we could consider that avoids the modal-in-modal effect.

**Comment by gasman** [comment]
A bit more discussion of this feature here: https://groups.google.com/d/msg/wagtail-developers/-78jMbw7spE/t8LwoKOkDwAJ

**Comment by bmoe872** [comment]
Is there any preferred approach to this? e.g. following the same logic that the imagechooserpanel has? I'd be interested in this functionality as well. I'm not sure what the UI patterns are that @tmsndrs mentioned. I'd be willing to give this a shot, but would love some more direction.

**Comment by gasman** [comment]
@lmorillas No, the status is exactly as you see here - feel free to pick this task up!

**Comment by cybertschunk** [comment]
is still no work done in this issue?

**Comment by tobiaghiraldini** [comment]
@cybertschunk it seems not. I am starting to look into this, as it's a really handy feature and should be easy enough to be implemented. Would you like to help addressing this?
I'm already looking into this, even though no one gave any direction on how to approach the implementation or some best practice to follow. But I guess I'll figure out what I need.
Contact me if you're willing to contribute

**Comment by cybertschunk** [comment]
@tobiaghiraldini I would like to but unfortunately I can hardly spare any time right now.

**Comment by benparkins** [comment]
@tobiaghiraldini did you have any luck with this?

I'm probably going to be implementing something similar in a couple of weeks, so was looking to see if anyone else had done it first. Obviously not yet!

The modelcluster module seems pretty useful, allowing you to edit your snippets in memory before you are ready to hit the database: https://github.com/wagtail/django-modelcluster

An example of it in use is the tag support in: https://github.com/AccordBox/wagtail-bootstrap-blog where ClusterableTaggableManager is used to allow adding new tags to a blog post in the page edit screen.

**Comment by tobiaghiraldini** [comment]
@benparkins I've done some work for it, but still it's not ready to be part of a pull request.
I'd like to cover some more scenarios ( e.g.  how to handle multiple levels of FK's depth without spawning modals on modals, as @gasman mentioned above).
I don't personally like how the Django core admin module handles this, so I was still tinkering with it.
It'd be nice if we could put our hands together on this issue, so we can discuss about it and provide with a thoughtful solution.

**Comment by johnraz** [comment]
I'm also interested and could have some time to contribute in the coming weeks as well.

@tobiaghiraldini could you open a draft PR maybe so we can check the code? Or is it glued with a project and you need extra work to extract it?

**Comment by gasman** [comment]
I'm also working on this as part of https://github.com/gasman/wagtail-generic-chooser (which aims to encompass all functionality you might want as part of a chooser modal, to the point where it can become the base implementation for all of Wagtail's choosers, as well as a convenient starting point for custom ones).

Hoping to have something usable in the next week or so, but here's my WIP for now: https://github.com/gasman/wagtail-generic-chooser/commits/feature/create-form

**Comment by tobiaghiraldini** [comment]
@johnraz it's a little tied to my specific implementation for the time being, but it's going to be extracted from it and ported to the wagtail fork in the next days.
i guess we should take a look at the @gasman work though, before going any further.
if the generic chooser is intended to be the base implementation, i'll convert my custom chooser extending it

**Comment by gasman** [comment]
This is now implemented for wagtail-generic chooser in the PRs:
https://github.com/gasman/wagtail-generic-chooser/pull/4
https://github.com/gasman/wagtail-generic-chooser/pull/5

**Comment by thibaudcolas** [comment]
FYI for people still interested in this, we’re considering bringing this in as part of the [Page editor 2022](https://github.com/wagtail/wagtail/discussions/7739) project, as part of general chooser improvements. Follow this discussion thread for upcoming updates / requests for feedback about choosers.

**Comment by benjaoming** [comment]
re: https://github.com/wagtail/wagtail/issues/396#issuecomment-501842719

Corrected links:
https://github.com/wagtail/wagtail-generic-chooser/pull/4
https://github.com/wagtail/wagtail-generic-chooser/pull/5

**Comment by jogwen** [comment]
I've just been able to do this in Wagtail 4.1.8 by creating a ChooserViewSet subclass and registering an instance of it in wagtail_hooks.py - see https://docs.wagtail.org/en/v4.1.8/extending/generic_views.html#chooserviewset

**Comment by gasman** [comment]
Good call @jogwen! Now that Wagtail's own chooser implementation has the functionality that was previously only available through the wagtail-generic-chooser package, this can be closed.
