### ISSUE TITLE
Upgrade to latest jQuery 3.x

### ISSUE THREAD

**Issue by tomdyson** [wagtail/wagtail#3977]
We're on 2.2.1. Google App Engine security scanner reports a vulnerability with this version, and links to https://github.com/jquery/jquery/issues/2432

The latest 2.x version is 2.2.4, available from https://code.jquery.com

Alternatively we could upgrade to the latest jQuery, which is currently 3.2.1. The 'slim, minified' version (excluding `ajax` and animation) would save us 16KB. The plain 'minified' version is the same size as the 2.2.4 equivalent. The 3.x branch promises performance improvements but may have compatibility issues.

**Comment by gasman** [comment]
See #3813. However, the 2.x branch apparently doesn't (and won't) have a fix for https://github.com/jquery/jquery/issues/2432, in which case @thibaudcolas's comment there still stands: we're not aware of any benefits to upgrading to 2.2.4 that would justify the work of re-testing our code against it. (Unless, that is, upgrading to 2.2.4 would - wrongly - silence the warning, and that's counted as a benefit :-) )

FWIW, I don't believe Wagtail is affected by https://github.com/jquery/jquery/issues/2432 - the only external AJAX request is to `releases.wagtail.io`, and that uses `getJSON` (which presumably bypasses the content-type guessing that leads to jQuery executing the response as JS).

**Comment by gasman** [comment]
We've tentatively agreed to upgrade to 3.0 in Wagtail 2.0, pending further investigation of the impact.

**Comment by gasman** [comment]
Completed in #4021
