### ISSUE TITLE
Not specifying a filter for an Image tag

### ISSUE THREAD

**Issue by lirlocker** [wagtail/wagtail#3993]
### Issue Summary

Adding an `{% image %}` tag without specifying a resize rule will cause a very confusing error:
`wagtail.wagtailimages.exceptions.InvalidFilterSpecError: Unrecognised operation: `

which is caused by:
```
        if op_spec_parts[0] not in self._registered_operations:
            raise InvalidFilterSpecError("Unrecognised operation: %s" % op_spec_parts[0])
```

**(wagtail\wagtailimages\models.py", line 360, in operations)**

### Steps to Reproduce

Inserting an `{% image %}` tag to a template without a resize rule like so:
`{% image page.cover_image  class="cover-image" %}`
or:
`{% image page.cover_image %}`

The exception thrown here must be much more explanatory, and also this must be documented in here:
http://docs.wagtail.io/en/v1.13/topics/images.html?highlight=wagtailimages_tags

### Technical details

Python version: 3.6
Django version: 1.11.7
Wagtail version: 1.13
Browser version: Irrelevant.

**Comment by lb-** [comment]
@lirlocker what are your thoughts on these suggestions?


## 1. Documentation Update

File: [/docs/topics/images.rst](https://github.com/wagtail/wagtail/blob/master/docs/topics/images.rst)

### Current
The syntax for the tag is thus:

`{% image [image] [resize-rule] %}`

For example:
...

### Suggested Update

The syntax for the tag is thus:

`{% image [image] [resize-rule] %}`

**Both the image and resize rule must be passed to the template tag.**

For example:
...

## 2. Clearer Error Message

### Current

```
            if op_spec_parts[0] not in self._registered_operations:
                raise InvalidFilterSpecError("Unrecognised operation: %s" % op_spec_parts[0])
```

### Update

Note: we use the terminology 'resize rule' and 'image tag', plus throw a more specific error if no resize rule is provided.

```
            if not op_spec_parts[0]:
                raise InvalidFilterSpecError("No resize rule in image tag")
            if op_spec_parts[0] not in self._registered_operations:
                raise InvalidFilterSpecError("Unrecognised resize rule in image tag: %s" % op_spec_parts[0])
```

**Comment by lirlocker** [comment]
@lb- 
Looks great.
