### ISSUE TITLE
Auto-select default block when there is only one option in StreamField

### ISSUE THREAD

**Issue by lirlocker** [wagtail/wagtail#3998]
### Issue Summary

A `StreamField` with only one block looks like this:
![image](https://user-images.githubusercontent.com/21131799/32498300-0456d522-c3d8-11e7-8a14-3a4b78534f54.png)

Instead, the default block should be selected automatically the same way it happens when removing all content and pressing the (+) button.

This issue leads to bad user experience. 

### Steps to Reproduce

A `StreamField` with only one block.

### Technical details

* Wagtail version: 1.13

**Comment by gasman** [comment]
Thanks @lirlocker. This has also been recently raised at https://stackoverflow.com/a/46727314/1853523 ...

I'd suggest that we only make this change when the StreamField is made a required field via `blank=False` or the `min_num` option on `StreamBlock` - for a non-required field it _is_ valid not to add any blocks (and so we shouldn't pre-emptively add one).

**Comment by lirlocker** [comment]
@gasman 
I agree that it shouldn't be automatically added unless it's required, but when the `StreamField` is not required there should be another way of asking the user if they want to add it or not.
The way it is at the moment (as in the image I attached) is not clear and could be a bit confusing to users. (Unless of course there are multiple options to choose from.)

Thanks.

**Comment by lb-** [comment]
Updating tags, not sure that this is a small one as it will require some reworking of the JS streamfield code

**Comment by thibaudcolas** [comment]
Assigning this to myself as we’re currently revisiting how the "Add" block picker in StreamField, and I’d like to make sure we give this proper thought.

**Comment by mihow** [comment]
Fantastic, thanks for the update. Best of luck implementing this change.
