### ISSUE TITLE
Responsive video iframe in RichText

### ISSUE THREAD

**Issue by lirlocker** [wagtail/wagtail#4000]
Hi again. 😄

When adding an embed youtube video in a rich text, it (the video iframe) has a fixed width which is too large for mobile devices, causing the page to be scrollable horizontally. 
This is a real problem when designing responsively.

![image](https://user-images.githubusercontent.com/21131799/32509348-b6d05db4-c3f5-11e7-9303-06221ac7cf90.png)

### Steps to Reproduce

Embedded youtube video inside a `RichTextBlock` in a `StreamField`.

### Technical details

* Wagtail version: 1.13
* Browser version: Chrome 61

**Comment by ababic** [comment]
Hi @lirlocker. Responsive design is really the job of a front-end/template developer to implement. A CMS shouldn't make assumptions about how the content is used (Wagtail can be used to power much more than just responsive websites) 

One of my go-to solutions for making video iframes responsive is: http://fitvidsjs.com, though there are other (and possibly better) options out there.

**Comment by lirlocker** [comment]
@ababic 
Hi.
When the front-end developer is using an `Image` (for example) which is static in a template, they will also add some styling so that it will look like they want.
The problem is that when using the rich text editor, there is no control over what elements are going to be used by the content creator.
Moreover, Wagtail adds a "width" attribute to the video's iframe which isn't happening in text or images, it's up to the developer to decide. So why do it with embed videos? Isn't that an assumption?

Thanks.

**Comment by ababic** [comment]
To a certain degree, sure. But in most cases I can think of, an iframe without width and height attributes wouldn't be useful.

**Comment by zerolab** [comment]
Please note that the embed width/height comes from oembed/embedly or your custom embed provider if you have it. As @ababic notes the iframe without the dimension attributes is not useful at all.

You can insert additional JavaScript (such as FitVids.js) using http://docs.wagtail.io/en/v1.13/reference/hooks.html?highlight=editor_js#insert-editor-js and customise the iframe behaviour as you like.

**Comment by tomdyson** [comment]
@lirlocker I'm not sure this helps your particular case, but have you seen the note on responsive embeds at

http://docs.wagtail.io/en/v1.13/topics/writing_templates.html#responsive-embeds

?

**Comment by lirlocker** [comment]
Thanks for all the suggestions, but this is easily solved by changing the properties of the iframe in the stylesheets. 
It wasn't that I couldn't get it to be responsive, but that I thought it should be that way by default. 

If anyone think that this should be reopened, let me know.

**Comment by gasman** [comment]
For what it's worth, I dare say the ultimate "resolution" of this issue will be to phase out the practice of embedding media into rich text, by dropping it from the list of on-by-default [rich text features](http://docs.wagtail.io/en/v1.13/advanced_topics/customisation/page_editing_interface.html#limiting-features-in-a-rich-text-field) and requiring developers to explicitly enable it. Embeds in rich text have effectively been obsolete ever since we introduced StreamField - rich text just isn't a very good medium for achieving this kind of element-level configurability.

**Comment by jaypatel0717** [comment]
ss

**Comment by brylie** [comment]
Is there a suggested approach for responsive StreamField embeds? For example, our YouTube StreamField embeds are currently rendering at 200px width while Vimeo embeds default to 400px width.
