### ISSUE TITLE
Snippet editing disabled in recent commit

### ISSUE THREAD

**Issue by saevarom** [wagtail/wagtail#4001]
### Issue Summary

A recent commit https://github.com/wagtail/wagtail/commit/454af89c17e98a6eccdf9b0dd37edbed78414008 moved the save button for snippets out of the `<form>` tag, effectively disabling editing of snippets.

### Steps to Reproduce

It's essential that you provide enough information for someone else to replicate the problem you're seeing. Simply describing something that's broken on your current project is not enough!

1. Create a new snippet (using wagtail from current master)
2. Edit the snippet
3. Hit the save button - nothing happens

**Comment by lb-** [comment]
Just mentioning the appropriate PR that fixes this issue: #4002 

It has also been marked as a release blocker and needs review (on the PR).
