### ISSUE TITLE
Image, Page, Document, Snippet chooser modal loads more than once on multiple clicks

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#4006]
### Issue Summary

When using one of the in line Document or Image choosers on a slow internet connection, the user might click 'Choose An Image' multiple times.

Clicking multiple times loads the modal in the background multiple times, meaning the user has to close each one to get back to the 'base' one before choosing something will actually work.

### Steps to Reproduce

It's essential that you provide enough information for someone else to replicate the problem you're seeing. Simply describing something that's broken on your current project is not enough!

1. Start a project using the wagtaildemo
2. Log into Admin
3. Edit the Blog page which contains an image link
4. On Chrome open developer tools, click the Network tab and change speed to 'slow 3G'
5. Click 'Choose an image' three times quickly (the modal will not appear for about 1500ms
6. Attempt to select an image (or upload one)
6a. Expected - image is selected and modal is closed.
6b. Actual - image is selected, background gets slightly lighter, and you are left with the 'underneath' modal without any selection.

Note: This is even more of an issue if you upload a new image because you will need to upload it multiple times without realising what is happening.

### Technical details

* Python version: 3.4.3
* Django version: 1.11.6
* Wagtail version: 1.13
* Browser version: Chrome 61 on Mac

### Potential Solution - First resolve why Modals can be opened again.

The code for `ModalWorkflow` looks like it should remove existing modals when a new one is opened.

`$('body > .modal').remove();`
[modal-workflow.js](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailadmin/static_src/wagtailadmin/js/modal-workflow.js)

### Potential Solution - Disable Button Until Modal Closed

Whenever `ModalWorkflow` is triggered on `action-choose` buttons we could possibly disable the button until the modal is loaded (or closed).

This also visually indicates that something is happening, maybe we could add a loading indicator in the future. Maybe look at a way to make this easier as part of the `ModalWorkflow` library, eg. add something to opts like an additional function to run on modal close.

```
    $('.action-choose', chooserElement).click(function(event) {
        buttonClicked = event.target;
        buttonClicked.addClass('disabled'); // disables the button immediately on click
        ModalWorkflow({
            url: window.chooserUrls.imageChooser,
            responses: {
                imageChosen: function(imageData) {
                    buttonClicked.removeClass('disabled'); // enable the button when image selected
                    input.val(imageData.id);
                    previewImage.attr({
                        src: imageData.preview.url,
                        width: imageData.preview.width,
                        height: imageData.preview.height,
                        alt: imageData.title
                    });
                    chooserElement.removeClass('blank');
                    editLink.attr('href', imageData.edit_link);
                }
            }
        });
    });
```

The equivalent will need to be reviewed and updated wherever the ModalWorkflow is created, here are some - need to check fully for any others.

* [image-chooser.js](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailimages/static_src/wagtailimages/js/image-chooser.js)
* [document-chooser.js](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtaildocs/static_src/wagtaildocs/js/document-chooser.js)
* [snippet-chooser.js](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailsnippets/static_src/wagtailsnippets/js/snippet-chooser.js)
* [page-chooser.js](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailadmin/static_src/wagtailadmin/js/page-chooser.js)

**Comment by thibaudcolas** [comment]
Draftail doesn't have this issue because as soon as the user clicks the whole editor is switched to "read-only" mode, with a transparent overlay above all of the UI with the buttons (making double actions impossible editor-wide).

Learning from this approach, this issue could be fixed at the same time as #2364 by displaying the dark modal overlay instantaneously, with a spinner to indicate loading.

**Comment by lb-** [comment]
@thibaudcolas yeah - that makes sense

**Comment by gasman** [comment]
Have just rediscovered this bug... An extra source of confusion is that the Search / Upload tabs within the chooser don't work, because both modals use the same element IDs and so the tab controls end up activating the panels on the unseen modal.

![duplicate_image_chooser](https://user-images.githubusercontent.com/85097/49395620-f2458a00-f72e-11e8-9761-827ed8a52bcd.gif)

**Comment by nimasmi** [comment]
The nature of this bug hasn't changed, but a related project, Wagtail Generic Choosers, extends the use of this modal to external APIs. It's possible that these APIs are even slower than DRF's internal object-choosing endpoints.

I haven't merely come across this bug, but the client for whom we've implemented Wagtail Generic Choosers has had to be instructed to exercise patience when opening the chooser modal.

Related: https://github.com/wagtail/wagtail-generic-chooser/issues/25
