### ISSUE TITLE
How to deploy Wagtail?

### ISSUE THREAD

**Issue by neilpanchal** [wagtail/wagtail#4013]
Reading the deployment section here is not very helpful.
http://docs.wagtail.io/en/v1.13/advanced_topics/deploying.html

I can get a site running on my local system but how to now transfer it to a live server (I have a ssh connection to a droplet on digitalocean running ubuntu/nginx)?

I searched on the internet for deployment information but no luck. Also, I don't have any background in django so it would be great if there is a tutorial of some sorts.

Goal is to develop the site locally and push it to a live server.

**Comment by neilpanchal** [comment]
I found a good guide for Django deployement on Nginx server:
http://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html

Perhaps we can link it to the deployment section in the docs? I am not familiar with Wagtail at all so if someone could point out the specifics on deployment that are different from the tutorial above, that'd make an excellent guide to get non-familiar people onboard!

**Comment by gasman** [comment]
Thanks for the report, @neilpanchal.

As the page says, the base requirements for Wagtail deployment are the same as for Django itself (and any optional extras are covered in the [Performance](http://docs.wagtail.io/en/v1.13/advanced_topics/performance.html) docs). Giving detailed deployment instructions here would duplicate the information that already exists for Django, and probably end up not being kept up-to-date. (Keeping the minimal details on this page up-to-date is already enough of a task - see #3898 for a recent example.)

To be honest, I think the real problem newcomers face here is not a lack of documentation, but too much of it. There are any number of different platforms you can deploy on - [the Django documentation alone covers three](https://docs.djangoproject.com/en/1.11/howto/deployment/wsgi/) - and actually understanding the pros and cons of each one involves reading up on things like WSGI and proxy servers. Answering the question "which deployment setup is best _for me_?" is out of scope for the Wagtail documentation - we do the next best thing, which is to identify a setup that works well for us (namely, nginx + gunicorn on Debian). The one you've identified (nginx + uwsgi on Ubuntu) is probably equally good, but we don't have the resources to document every possible setup, or even to recommend specific tutorials for setups other than the one we use.
