### ISSUE TITLE
Cannot edit pictures in RichTextField

### ISSUE THREAD

**Issue by mistguy** [wagtail/wagtail#4020]
### Issue Summary

After I inserted a picture (left or right aligned) in rich text editor in the admin phase, I cannot edit it or even remove it.

### Technical details

* Python version: 3.6.3
* Django version: 1.11.3
* Wagtail version: 1.13
* Browser version: Chrome 62

**Comment by gasman** [comment]
Thanks for the report @mistguy! Images can be deleted by placing the cursor after the image and hitting backspace, but there's a known glitch where this is difficult to do for images at the end of the rich text field - this is covered by #447.

In the next release of Wagtail we plan to replace the rich text component with a new one (#2409), so this should be fixed then.
