### ISSUE TITLE
Deleting home page cascades to site

### ISSUE THREAD

**Issue by stuartaccent** [wagtail/wagtail#4022]
Hi guys, firstly many thanks for the hard work. Just a question really.

Ive seen on several occasions a user deleting the main page linked directly to a site instance and thus deleting the site also. This has had a knock on effect to other apps where they use things like the global settings that are expecting a site instance passed in (mainly i believe from request.site not existing).

https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/settings/models.py#L17

What im wondering is your opinion on where to go with it.

* Can that site model be changed to models.PROTECT or similar? is there a knock on effect? Less im wrong It feels like deleting a site should be a concious decision the user should make.

* Is it best to enable 'django.contrib.sites' so request.site exists? will this have a knock on effect as its not the expected site instance?

* or should all code written work if there is a site or not?

Or anything else I've not considered.

Ty, Stu

**Comment by stuartaccent** [comment]
sorry I just saw https://github.com/wagtail/wagtail/issues/687

**Comment by gasman** [comment]
Thanks for the report! Closing as duplicate.
