### ISSUE TITLE
Moving a page to a place which already has a child with the same slug leads to a `ValidationError`

### ISSUE THREAD

**Issue by konoma-lipp** [wagtail/wagtail#4030]
### Issue Summary

Moving a page with slug "a-b-c-d" to another parent which already contains a child with the same slug "a-b-c-d" causes a `django.core.exceptions.ValidationError: {‘slug’: [‘Dieser Kurztitel wird bereits verwendet’]}` (sorry, not sure what the correct english translation is ;)).

<img width="1057" alt="screen shot 2017-11-17 at 10 02 43" src="https://user-images.githubusercontent.com/21330675/32939315-63e3ff52-cb7f-11e7-87e8-f212c611fda1.png">

Now in production this results in a nasty "Internal Server Error". Only after investigating the logs we were able to resolve the issue.

### Steps to Reproduce

1. Create two top level parents
2. Create a page in one parent and copy it (using the same slug) as a child into the second parent
2. Now try to move the page from one parent to the other

Now from a user perspective I would expect an information message which allows me to quickly change the slug if needed. 
Preferably the slug would be already appended with a number (for example). Assuming the slug is "a-b-c-d" it would be nice if the user gets a hint, that he should update the slug but the system already provides him with something like "a-b-c-d-1".

### Technical details

* Python version: `3.6.2`.
* Django version: `1.11.7`.
* Wagtail version: `1.12.2`.
* Browser version: Independent.

### Test project to reproduce the issue

This sample project contains two parents underneath "Home" which can be used to quickly reproduce the issue.

[move_sample.zip](https://github.com/wagtail/wagtail/files/1481748/move_sample.zip)

Username: `admin`
Password: `testmove`

**Comment by gasman** [comment]
Thanks for the report @konoma-lipp! We already have an issue open for this, at #3281.
