### ISSUE TITLE
Support form_classname attribute on StreamBlock and ListBlock

### ISSUE THREAD

**Issue by mnieber** [wagtail/wagtail#4042]
Version: 1.13

`StructBlock` supports the `form_classname` attribute in its Meta class. It would be nice if `StreamBlock` and `ListBlock` also support it.

**Comment by lb-** [comment]
@mnieber thanks for the suggestion, I have put together a bit of a concept of how this could work using `classname` - check out the PR and give your thoughts.

I am not sure if this is how best to implement this just yet but at least we have a start.

**Comment by lb-** [comment]
Update: New PR with full implementation awaiting review #5100
