### ISSUE TITLE
Potential Bug with ModelAdmin

### ISSUE THREAD

**Issue by DDiran** [wagtail/wagtail#4048]
I think I've found a potential bug with `ModelAdmin` when setting `list_display` and `search_fields` fields

### Steps to Reproduce

When registering a new `ModelAdmin` instance based on a Model with (for example) only one field, you must add a comma to the `list_display` field nonetheless.

1. Create `TestModel(models.Model)` with field `name = models.Charfield(max_length=200)`
2. Edit `wagtail_hooks.py` by creating `TestModelAdmin(ModelAdmin)` and adding `list_display = ('name')`. Finally register the model with `modeladmin_register`.
3. Try accessing the admin interface and encounter an `AttributeError`
4. Go back into `wagtail_hooks.py` and change `('name')` to `('name', )`
5. Should now work

Not sure if this is a bug or simply a Python syntax thing that I wasn't aware of. Thought I should report it anyway just in case.

### Technical details

* Python version: 3.5
* Django version: 1.11
* Wagtail version: 1.12.2
* Browser version: Not relevant

**Comment by Proper-Job** [comment]
@DDiran That's not a Wagtail bug but a mistake in your python syntax.
('name') is not a tuple, ('name',) is.
