### ISSUE TITLE
Improve typography with SmartyPants-like rich text processing

### ISSUE THREAD

**Issue by davelab6** [wagtail/wagtail#4051]
### Issue Summary

Wagtail doesn't automatically replace "dumb quotes" `"` with “smart quotes” `“ + ”`

### Steps to Reproduce

Enter some text with dumb quotes into the rich text editor

Today: On the published page, see the dumb quotes

When fixed: See smart quotes

Longer explanations about this can be found around the web, eg https://www.fastcodesign.com/3018353/be-smart-dont-use-dumb-quote-marks 

A simple plugin for basic CMS that does this, from 2004, is https://daringfireball.net/projects/smartypants/

**Comment by gasman** [comment]
Thanks for the suggestion @davelab6!

As a policy, Wagtail does not impose any opinions about how content is presented on the site front-end - that's entirely down to you as a site developer, and your use of the Django template language. As such, I'd consider this feature to be out of scope of Wagtail itself - it's something you could achieve through a library such as [django-typogrify](https://github.com/chrisdrackett/django-typogrify), though.

**Comment by thibaudcolas** [comment]
There is (very early) discussions of whether this is a desirable feature in a new rich text editor we want to introduce in an upcoming release of Wagtail, over at https://github.com/springload/draftail/issues/53.

Opinions welcome.

**Comment by mikemonteith** [comment]
We're still "pre-release" at the moment while we experiment with this, but here's a small wagtail plugin that will do smartquote replacements on all text input fields on page-edit pages. https://github.com/nhsuk/wagtail-smartquotes/

We've identified a need to do smartquote replacements to help our editors use correct punctuation. I think the right place to do this is in the editor and not on the front-end.
