### ISSUE TITLE
Big files are uploaded with broken permissions

### ISSUE THREAD

**Issue by 5in4** [wagtail/wagtail#4054]
### Issue Summary

Files bigger than 2.48 MB are uploaded with wrong permissions and are not readable from /media/

### Steps to Reproduce

Create two files with content size 2600000 bytes and 2700000 bytes. The second file gets its access rights mangled.
Reproducible for me on two separate installations.

wagtail 1.12.2, Django==1.11, python 3.5.2+ (ubuntu 16.10)

and 

1.13. with python 3.5.3 (ubuntu 17.04):
```
django-analytical==2.3.0
django-compressor==2.2
django-redis==4.8.0
django-sekizai==0.10.0
libsass==0.13.3
psycopg2==2.7.3.1
wagtail==1.13.1
waitress==1.1.0
requests==2.18.4
```

### This is how the files get saved in media 
with the smaller ones working as expected:
<img width="437" alt="screen shot 2017-11-23 at 11 57 46" src="https://user-images.githubusercontent.com/286750/33169650-b2151c4a-d045-11e7-9015-ba110f18d485.png">

Any ideas on how to resolve this issues or where to start digging?

**Comment by thibaudcolas** [comment]
Hey @5in4, thank you for reporting this. I'm not the best place to investigate this issue, but can definitely reproduce on Wagtail's [bakerydemo](https://github.com/wagtail/bakerydemo) Vagrant setup (Ubuntu 14.04.2 LTS):

```text
-rw------- 1 vagrant vagrant 5233997 Nov 23 12:16 jeremy-thomas-98201.jpg
-rw-r--r-- 1 vagrant vagrant 1092783 Nov 23 12:16 nasa-53884.jpg
```

**Comment by gasman** [comment]
Django uses different internal representations of newly-uploaded files (in-memory vs. temporary file) depending on file size, so I guess this could be related to that...

I'd suggest seeing if this can be replicated outside of Wagtail - define a model with a `FileField` and set it up to be editable through the Django admin, and see if the same behaviour occurs there.

**Comment by BertrandBordage** [comment]
Did you try setting [FILE_UPLOAD_PERMISSIONS](https://docs.djangoproject.com/en/1.11/ref/settings/#file-upload-permissions)?

**Comment by tomdyson** [comment]
I'm sure @BertrandBordage's hint is the right one. From the Django documentation:

> If [FILE_UPLOAD_PERMISSIONS] isn’t given or is None, you’ll get operating-system dependent behavior. On most platforms, temporary files will have a mode of 0o600, and files saved from memory will be saved using the system’s standard umask.

**Comment by gasman** [comment]
I agree. If FILE_UPLOAD_PERMISSIONS doesn't help and testing with a FileField shows that this is Wagtail-specific, let us know and we'll reopen.
