### ISSUE TITLE
Improved UI visual styles of chooser fields

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#4055]
Current implementation feels clunky. 
<img width="396" alt="screen shot 2017-11-23 at 12 04 09" src="https://user-images.githubusercontent.com/7290588/33172064-89b392e4-d046-11e7-93a1-885fbab9d484.png">

I've put together some early thinking on how these could be improved but it requires further conversation. 
![image](https://user-images.githubusercontent.com/7290588/33172119-b11d6fe4-d046-11e7-93e6-19981eee7345.png)

**Comment by lb-** [comment]
It might be good to consider #2364 relating to visual indication of loading the next page of selectable images within chooser modal, maybe filling in non-loaded images with a placeholder blank / greyed out image and also add a spinner to indicate loading.

**Comment by benenright** [comment]
Hi

I've refined these designs for the chooser fields - as mocked up by @tmsndrs above. I'm attempting to reflect the global button size/style for the initial view, and then creating a more padded stroked area once the media has been chosen - to house more cleanly the media title and grouped actions associated with it ( Clear / Edit / Replace) - replacing the existing buttons: Trash button / 'Edit this page' /  'Choose another page' 

Ignore the fact the icons vary slightly from the existing ones - happy to continue using existing icons for now (wholesale change to icons would be a separate issue). But I do feel we could move towards using the white icon on teal (default btn view) and the darker shade of grey for the populated item.

One thing to bear in mind is the top aligned label. Labels are currently aligned left but this ties in to work on'WIP Streamfield UI changes' #3942 where there is a move towards top aligned labels.

![screen shot 2018-02-14 at 14 09 26](https://user-images.githubusercontent.com/4907819/36208820-f0d9d6ea-1191-11e8-9af9-2365e027938a.png)

![screen shot 2018-02-14 at 14 09 34](https://user-images.githubusercontent.com/4907819/36208819-f0c56d7c-1191-11e8-878b-ce5fe8d15fd4.png)

Ben

**Comment by benenright** [comment]
Hi

The [designs](https://github.com/wagtail/wagtail/issues/4055#issuecomment-365621149) above are now agreed by the Wagtail UX/UI working group and ready for FE implementation for anyone who is keen to take this on.

Here is a mockup to show how these will work in situ with existing fields (note the key difference in label placement - vertically aligned labels in place of left-aligned which we hope to roll out globally soon to help with narrow screen alignment issues).
![choosers in situ](https://user-images.githubusercontent.com/4907819/36899290-519e4ec6-1e16-11e8-9d13-c4b60d5f8b01.png)

Here's the Sketch file.
[wagtail-chooser-fields.sketch.zip](https://github.com/wagtail/wagtail/files/1775072/wagtail-chooser-fields.sketch.zip)

Ben

**Comment by m1kola** [comment]
Would be great to take have a solution for file field. See discussion in #4790

**Comment by lb-** [comment]
Should be mostly addressed now that https://github.com/wagtail/wagtail/pull/8934 is merged
@thibaudcolas  please can you review this issue.
