### ISSUE TITLE
Location and labelling of 'Pages using...' feature

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#4056]
To me the feature that allows you to see a listing of pages using a specific content type is accessible from an odd location. An editor is required to click to add a new page, then they're taken out of the new page workflow. It's certainly handy to be able to see all pages using a specific content type but not from this screen so I propose we redesign this workflow. 

<img width="1084" alt="screen shot 2017-11-23 at 12 24 11" src="https://user-images.githubusercontent.com/7290588/33180352-50903832-d064-11e7-9c5c-13aae3ace041.png">

**Comment by tmsndrs** [comment]
<img width="1016" alt="screen shot 2017-11-23 at 12 34 42" src="https://user-images.githubusercontent.com/7290588/33180329-3a0715c2-d064-11e7-9648-712783ce5c85.png">

**Comment by thibaudcolas** [comment]
I believe this is no longer relevant as of #9809.
