### ISSUE TITLE
Improved design for Search 'filters'

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#4058]
The current search 'filter' feel undesigned. 
<img width="1029" alt="screen shot 2017-11-23 at 12 40 50" src="https://user-images.githubusercontent.com/7290588/33173383-df659e8a-d04b-11e7-85c3-e0a8e77e8f94.png">

- [x] New visual design 
- [ ] Front end implementation 
- [ ] Add this new pattern to Wagtail's UI pattern library

**Comment by benenright** [comment]
Here is an improved quick win version of this filtering component for better usability.

![screen shot 2018-02-16 at 09 44 26](https://user-images.githubusercontent.com/4907819/36301818-0f96a258-12fe-11e8-9722-ffa7bb3825eb.png)

**Comment by benenright** [comment]
Hi

The [design](https://github.com/wagtail/wagtail/issues/4058#issuecomment-366188697) above is now agreed by the Wagtail UX/UI working group and ready for FE development for anyone who is keen to take this on.

Here's the Sketch file.
[wagtail-search-filters.sketch.zip](https://github.com/wagtail/wagtail/files/1774898/wagtail-search-filters.sketch.zip)

Ben

**Comment by jjanssen** [comment]
Hi @benenright 

Whilst further implementing this during the Minsk sprint some questions came to mind which is probably essential for the bigger picture. Especially for our mobile strategy. Right now the designs reflect on the desktop state which has 2 types of filtering on the search page.

Example screenshot from the Bakery Demo:
![image](https://user-images.githubusercontent.com/287422/47615256-c2ff8580-dabd-11e8-9381-72c40379792b.png)

1. Will the page-type be removed or should it be an iconless adaption of the base filtering? (pages, images, documents, users)
2. How should we handle a long list of these filters in smaller viewports? Should we render multiple rows or should we have a sort of [inline navigation (resize to 1280px)](https://material-ui.com/demos/tabs/#scrollable-tabs)?
3. How should these filters behave on mobile? 

Right now there isn't much room te play with on mobile and that's even without possible increased text labelling in other languages.

**Comment by gasman** [comment]
As of Wagtail 4 this now has an improved design:

![Screenshot 2022-12-09 at 22 27 27](https://user-images.githubusercontent.com/85097/206805816-75e63875-c626-4d16-a7d6-72c0c4152919.png)

I don't know how much of this was an intentional redesign of this particular component, as opposed to emerging organically from the site-wide style updates - but either way, I think this ticket has now outlived its usefulness, and any decision we make about updating this further needs to be re-evaluated in the context of the Wagtail 4 redesign.
