### ISSUE TITLE
Image editing screen feels under designed

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#4087]
When editing an image, the screen feels under designed, including tight field tittles, confusing layout and unstyled buttons. 

<img width="1256" alt="screen shot 2017-12-01 at 18 35 56" src="https://user-images.githubusercontent.com/7290588/33497767-ea1f4b7e-d6c6-11e7-8261-47c005af950b.png">

Relates to #4055 and #2339 (my comment about focal point UI)

**Comment by benenright** [comment]
Here is a layout that should make this screen clearer and more usable on smaller desktop viewports. The idea is we use the 'Replace' link in place of the default 'Choose file' UI element, opening the file choose file dialog.

The styling on the 'File' field is to be consistent with the approach outlined on #4055 

![image editing 2x](https://user-images.githubusercontent.com/4907819/36314168-e1555f14-132b-11e8-8915-c24a974ac500.png)
