### ISSUE TITLE
Empty state for documents and images is undesigned 

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#4088]
<img width="1254" alt="screen shot 2017-12-01 at 18 59 10" src="https://user-images.githubusercontent.com/7290588/33498608-e7a0ca78-d6c9-11e7-9122-b065c9fc1845.png">

**Comment by thibaudcolas** [comment]
Without further context – this doesn’t seem that bad to me, considering this empty state is unlikely to be seen by most people.

I’ll close this now, I believe we’re likely to revisit this as part of work on listings, but that would be for all listings not just images and documents.
