### ISSUE TITLE
Improve UX of password reset and user name reminder email 

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#4098]
Related to #2309 

The current email is very basic. Whilst we probably don't want it to be too opinionated, the copy could be more helpful.

**Comment by ntraikos** [comment]
Hi, do you find there is still an issue with this workflow? I'd like to work on this if so.

**Comment by lb-** [comment]
Flagging as needs info - it would be good if this issue could be updated or added to with current state and ideas or proposals for a better approach. 

Also - maybe we should check what template customisation is available here, it might be a lack of docs.

**Comment by gasman** [comment]
Closing due to lack of detail - this issue does not identify any specific problems or actionable improvements.
