### ISSUE TITLE
Make adding the first related model more intuitive for InlinePanel

### ISSUE THREAD

**Issue by lohmander** [wagtail/wagtail#4102]
We've had multiple people struggle with realizing how to add the first model, that is when the user interface looks as follows.

<img width="325" alt="screen shot 2017-12-05 at 09 34 00" src="https://user-images.githubusercontent.com/2197050/33583797-7926f346-d99f-11e7-9be3-1447608d07b3.png">

As a suggestion, just adding the "Add"-button that appears after one or more entries are added, would solve the problem?

**Comment by thibaudcolas** [comment]
I believe this has been changed a _long_ time ago to always have the "Add" button.
