### ISSUE TITLE
docs: register_page_listing_more_buttons gives wrong button class as example

### ISSUE THREAD

**Issue by robvdl** [wagtail/wagtail#4103]
I found a small issue with the docs, the documentation for register_page_listing_more_buttons gives you an example which appears to be copy-pasted from register_page_listing_buttons above it, because it tells you to use PageListingButton but that really looks out of place as a dropdown item in the More menu.

I had to read the Wagtail source to see how the More menu was constructed and realised the wrong button class was used in the docs, it should just be Button instead of PageListingButton.

I think the example in the docs should be fixed, as it confused me, it's going to confuse others.

**Comment by lb-** [comment]
@robvdl thanks for picking this up - should be fixed soon 👍
