### ISSUE TITLE
Navigate directly to a tab within the admin interface

### ISSUE THREAD

**Issue by benweatherman** [wagtail/wagtail#4111]
### Issue Summary

It would be nice if I could give a user a URL that would take them directly to e.g. the promote tab

![tab nav](http://g.recordit.co/61UcdzRpUJ.gif)

### Steps to Reproduce

1. Give user a URL such as `admin/pages/4/edit/#tab-promote`
2. Paste that into your favorite browser
3. Notice that you're taken to the `Content` tab, but it would be cool if it took me to the `Promote` tab

### Technical details

* Python version: `Python 3.6.3`
* Django version: `Version: 1.11.8`
* Wagtail version: `Version: 1.13.1`
* Browser version: [Firefox 58](whatsmybrowser.org/b/83WUCJC)

**Comment by thibaudcolas** [comment]
Hey @benweatherman, thanks for the suggestion. It makes perfect sense to me, and I see that you've implemented this in your project. Would you be keen to make a pull request to address this in Wagtail? I'm happy give you some guidance with the change if that can help.

**Comment by lb-** [comment]
This would be awesome!

I have run into a similar frustration when publishing a change and then going back to the same edit page only to have to switch tabs to the previous. This would be a good stepping stone to maybe solving that problem in the future.

**Comment by benweatherman** [comment]
Howdy @thibaudcolas! That's absolutely my plan 👍 Wagtail has been really awesome to work with so far so I'm excited to give something back.

I was going to add this function to wagtail https://github.com/cityofaustin/joplin/pull/22/files#diff-385418a588455238c7a9f0fc8874b70dR45

My first thought was to put it in https://github.com/wagtail/wagtail/blob/8aa8ddcde986eee80e62ba6f185071e24669aeea/wagtail/admin/static_src/wagtailadmin/js/core.js#L78

But then wasn't sure if it's only needed on the editor page. I couldn't think of other places in the admin that use tabs. https://github.com/wagtail/wagtail/blob/8aa8ddcde986eee80e62ba6f185071e24669aeea/wagtail/admin/static_src/wagtailadmin/js/page-editor.js#L344

Am I on the right track? Anything else to keep in mind?

**Comment by thibaudcolas** [comment]
@benweatherman let us know if we can help. We're looking into making Wagtail more accessible over at #4199 and I think this navigation improvement would go in the right direction.

**Comment by benweatherman** [comment]
Sorry it took so long for 3 lines of code :) I was trying to setup a docker dev environment that mimics the vagrant environment y'all use.

**Comment by rgant** [comment]
@bauersebastian Did you succeed with Docker setup? I'd be interested in checking out your Dockerfile and other setup requirements.

**Comment by bauersebastian** [comment]
@rgant not sure why you've addressed this to me. Maybe by mistake? I think you've probably wanted to address @benweatherman, as I'm not involved in this. Thanks :-)
