### ISSUE TITLE
Problems using modeladmin with wagtail page models

### ISSUE THREAD

**Issue by nifel87** [wagtail/wagtail#4112]
Hi everyone! How is it going?
I have a little problem with wagtail. I don't know if it's a bug...

At the moment, in Wagtail, there isn't a canonical way or a best practice for:
- changing the default items' order in the explorer page ;
- adding a column in the explorer page.

So in order to offer a better view to the user for a certain page model I've decided to use the modeladmin approach. At the begining it seems to work fine but then I found two problems:
- The add button return a NoReverseMatch error ;
- The modify button return ERR_TOO_MANY_REDIRECTS error (Chrome).

If it isn't a bug, sorry for the post...

Thanks in advance,
best regards,

nifel87

**Comment by gasman** [comment]
Hi @nifel87 - thanks for the report.

This might be a Wagtail bug, but there's not really enough information here to tell... to investigate further, we need a full description of how to replicate the error, starting from a fresh Wagtail project. If you're able to replicate it, please open a new issue, filling in the details requested on the bug report template.
