### ISSUE TITLE
Explorer menu misleading if user has only permissions for one page (with child pages)

### ISSUE THREAD

**Issue by bruecksen** [wagtail/wagtail#4123]
### Issue Summary

The explorer menu is misleading if a user belongs to a group that has permission to only one page and the page has child pages. After a click on pages the explorer menu starts directly with the child pages of the page. The Page (root page, parent page to the user) is only accessible via the very top of the explorer menu beside the little house icon. 

Wouldn't it be better to show the root page in the explorer menu as it s 

### Steps to Reproduce

1. Add a group that has only permission to a single page, this page should have child pages
2. Login with a user that belongs to the group
3. If you click on 'Pages' you will find the child pages of the page you granted access in the explorer menu

### Technical details

* Python version: 3.5.3
* Django version: 1.11
* Wagtail version:  1.13

**Comment by gasman** [comment]
This is the intended behaviour, and I believe it's consistent with how limited-permission user accounts are generally used. For example, if you wanted to give a user edit permission over the 'news' section of a site, you'd assign that permission on the news index page. The explorer menu will then give immediate access to the news items (the pages they'll routinely be editing) as well as the index page.
