### ISSUE TITLE
Explorer menu shows all pages even though the group a user belongs to has only rights for a specific page

### ISSUE THREAD

**Issue by bruecksen** [wagtail/wagtail#4124]
### Issue Summary

This might be related to #3616. If a user belongs to a group that has only access to a specific page the user will see all pages in the explorer menu.

### Steps to Reproduce

1. Add a group that has only permission to a single page, this page should not have any child pages
2. Login with a user that belongs to the group
3. Click on 'Pages', you will see the whole page tree of the whole site, even though you only have permissions for one specific page

### Technical details

* Python version: 3.5.3
* Django version: 1.11
* Wagtail version: 1.13

**Comment by gasman** [comment]
Thanks for the report @bruecksen. When you say "Click on 'Pages'", do you mean the Pages item in the left menu, or the pages count in the main dashboard (https://user-images.githubusercontent.com/300616/27334442-e9909d58-55fb-11e7-898e-2c1bb26de64b.png)?

**Comment by bruecksen** [comment]
@gasman I mean the Pages item in the left menu.

**Comment by gasman** [comment]
Unable to reproduce this when testing against [bakerydemo](https://github.com/wagtail/bakerydemo). Giving a user edit permission over a single blog page results in just that one page appearing in the menu, as expected:

![screen shot 2017-12-15 at 16 57 52](https://user-images.githubusercontent.com/85097/34052196-4ea479d2-e1b9-11e7-87e0-4ee65cb6da72.png)

**Comment by khink** [comment]
@gasman I have reproduced this within the bakerydemo.

Steps to reproduce:
- Add a new Standard Page below the Home Page. Call it "Different Site Section"
- Add a new BreadIndexPage below "Different Site Section". Call it "Different Section Breads".
- Create a new Group. This group will have only the permission to work on Bread pages, so we call them "Breaditors".
- Give the Breaditors group admin acces, and all permissions on both "Different Site Section" and "Different Section Breads". 
- Now add a user, add them to Breaditors and log in as this user.
- Go to the admin and expand the "Pages" explorer. You will see all items below the homepage are showing. That's okay for navigating to the "Different Section Breads".
- But the "Edit" crayon icon is showing on all items. That's a problem.
- Clicking on the edit button of an item where the user has no permissions yields an ugly 403 page. Safe enough, but not nice.

**Comment by khink** [comment]
Our use case is a site with two News folders, one for Dutch and one for English news items. The English version on the site is located under the Dutch home page (not our choice, but there you go). 
```
- + / (Dutch homepage)
  |
  + /nieuws (Dutch news)
  .
  .
  .
  |
  + + /en (English homepage)
    |
    + /en/news (English News)
    .
    .
    .    
```
We have a group of News editors who have permission on both News folders.

**Comment by gasman** [comment]
Thanks @khink! I don't think this is the original problem described here, as it only occurs when the user has permission over multiple pages, but showing the edit icon for all pages definitely looks like a bug. Please could you open this as a new issue?

(Also, +1000 internet points for the name "breaditors" 😁 🍞 )

**Comment by khink** [comment]
Thanks for your reply! I created #4660 .
