### ISSUE TITLE
Missing on_delete argument in documentation (Django 2.0)

### ISSUE THREAD

**Issue by stuaxo** [wagtail/wagtail#4126]
Running through the tutorial, using wagtail from git master and python 3.5, I've got to the image section

http://docs.wagtail.io/en/latest/getting_started/tutorial.html#images

It seems like the line creating the ParentalKey for BlogPage is missing an on_delete parameter, at the line

```
    page = ParentalKey(BlogPage, related_name='gallery_images')
```
in blog/models.py

But since this is my first go at wagtail I'm not sure what this should be.

```
python manage.py makemigrations && python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/mnt/data/home/stu/.virtualenvs/dit-wagtail2/lib/python3.5/site-packages/Django-2.0-py3.5.egg/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/mnt/data/home/stu/.virtualenvs/dit-wagtail2/lib/python3.5/site-packages/Django-2.0-py3.5.egg/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/mnt/data/home/stu/.virtualenvs/dit-wagtail2/lib/python3.5/site-packages/Django-2.0-py3.5.egg/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/mnt/data/home/stu/.virtualenvs/dit-wagtail2/lib/python3.5/site-packages/Django-2.0-py3.5.egg/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/mnt/data/home/stu/.virtualenvs/dit-wagtail2/lib/python3.5/site-packages/Django-2.0-py3.5.egg/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/mnt/data/home/stu/.virtualenvs/dit-wagtail2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/mnt/data/home/stu/projects/work/dit/scratch/mysite/blog/models.py", line 46, in <module>
    class BlogPageGalleryImage(Orderable):
  File "/mnt/data/home/stu/projects/work/dit/scratch/mysite/blog/models.py", line 47, in BlogPageGalleryImage
    page = ParentalKey(BlogPage, related_name='gallery_images')
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

**Comment by stuaxo** [comment]
So I changed the line to ```page = ParentalKey(BlogPage, related_name='gallery_images', on_delete=models.CASCADE)```

But, I have no idea if that is correct - seems to work though

**Comment by stuaxo** [comment]
This applies to all mentions of ParentalKey in the tutorial.

**Comment by lb-** [comment]
@stuaxo as you are using an in development version, there are bound to be some issues, thanks for reporting this though 👍 

FYI you can see what the various on_delete options do in the [Django Docs here](https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.ForeignKey.on_delete).

---

Cause: Django 2.0 requires the `on_delete` argument.

**1.11 Docs**
> A many-to-one relationship. Requires two positional arguments: the class to which the model is related and the on_delete option. (on_delete isn’t actually required, but not providing it gives a deprecation warning. It will be required in Django 2.0.)
> `on_delete` will become a required argument in Django 2.0. **In older versions it defaults to CASCADE**.
https://docs.djangoproject.com/en/1.11/ref/models/fields/#foreignkey

**2.0 Docs**
> class ForeignKey(to, on_delete, **options)
> A many-to-one relationship. Requires two positional arguments: the class to which the model is related and the on_delete option.
https://docs.djangoproject.com/en/2.0/ref/models/fields/#foreignkey

Finally - django-modelcluster extends Django's foreign key with `ParentalKey`.
https://github.com/wagtail/django-modelcluster

I have put an issue on that library also for clarification https://github.com/wagtail/django-modelcluster/issues/89

**Comment by stuaxo** [comment]
Thanks for the info, i was reporting issues as I worked through the tutorial, so shortly after I found reported this, worked out ParentalKey as a ForeignKey .. also been away from Django for a little bit.

Thanks for all the great support and info so far.

**Comment by Zaouaghi** [comment]
there is any method to resolve the problem without touching code

**Comment by Zaouaghi** [comment]
there is any method to resolve the problem without touching code??

**Comment by stuaxo** [comment]
@Zaouaghi The tutorial has been updated to include on_delete so this should not be a problem any more.

**Comment by ZakiAhmedShaikh** [comment]
check if this monkey patch serves the issue:

https://stackoverflow.com/questions/50776076/django-1-to-django-2-on-delete-error/63111357#63111357


There is a workaround for this.

If you have lots and lots of table which needs adding "on_delete" parameter where ever Foreign-key or One-to-One key is used.. then going through all the models to add on_delete parameter would be very hectic. You can perform monkey-patch of foreign key to achieve your goal.

add the below monkey patch file in your project settings folder:

> monkey_patches.py

```

from django.db import models
from django.db.models import ForeignKey


class ForeignKeyMonkeyPatch(ForeignKey):
    def __init__(self, to, on_delete=None, *args, **kwargs):
        super().__init__(to, on_delete, *args, **kwargs)


class OneToOneFieldMonkeyPatch(ForeignKeyMonkeyPatch):
    def __init__(self, to, on_delete=None, *args, **kwargs):
        super().__init__(to, on_delete, *args, **kwargs)


setattr(models, 'ForeignKey', ForeignKeyMonkeyPatch)
setattr(models, 'OneToOneField', OneToOneFieldMonkeyPatch)
```

Now, call this file in your project settings...


`from .monkey_patches import *
`


The above code will reset the ForeignKey and OneToOneField with our monkey-patched classes, thereby setting on_delete as None by default

_P.S. (you can even create an app (named "monkey_patches" or anything that you desire..) and add the above code in models.py)_
