### ISSUE TITLE
Use keyword arguments for all Elasticsearch calls

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#4130]
As pointed out by @m1kola in https://github.com/wagtail/wagtail/pull/4128#issuecomment-351545049:

> We, should, probably replace all positional arguments with keyword arguments:
>
> > All the API calls map the raw REST api as closely as possible, including the distinction between required and optional arguments to the calls. This means that the code makes distinction between positional and keyword arguments; we, however, recommend that people **use keyword arguments for all calls for consistency and safety**.
>
> ---
>
> I don't know, if it's possible to cover this with tests somehow...

**Comment by lb-** [comment]
We may still want to do this but in a few years it appears that the code in question has not changed, I will remap this to a clean up enhancement and not really a bug.

See `wagtail/search/backends/elasticsearch5.py` (snippet below), we have not migrated the other indices calls to kwargs.

https://github.com/wagtail/wagtail/blob/953c980976231d6d2e1d26a58595710dcf10cc71/wagtail/search/backends/elasticsearch5.py#L851-L886

**Comment by gasman** [comment]
This was done as part of https://github.com/wagtail/wagtail/pull/10686.

**Comment by lb-** [comment]
Thanks Matt, I obviously misinterpreted this issue then, thanks for reviewing.
