### ISSUE TITLE
Readme test coverage link may be outdated

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#4143]
The readme list of features states:

> Excellent test coverage

With a link to: https://coveralls.io/github/torchbox/wagtail

That link says the last commit was `COMMITTED 9 DEC 2016 - 17:43`

Just wondering if this link should be updated to codecov or something else?

**Comment by lb-** [comment]
Maybe we should link to https://codecov.io/gh/wagtail/wagtail/

**Comment by thibaudcolas** [comment]
👍 updated to be the same link as the badge at the top of the README.

**Comment by lb-** [comment]
Thanks @thibaudcolas
