### ISSUE TITLE
Change docs link from latest to stable on wagtail.io website

### ISSUE THREAD

**Issue by engineervix** [wagtail/wagtail#4151]
I just recently got started with wagtail, and my first point of contact was the [wagtail.io website](https://wagtail.io). From the website, any wagtail newbie would probably head over to the [get started](https://wagtail.io/developers/) section of the website, which leads the reader through four steps to get up and running with wagtail.

At the bottom of these 4 steps, there's a link to further steps on building the just created site. This link points to http://docs.wagtail.io/en/latest/getting_started/tutorial.html. When I went to that link and started following through the tutorial, I hit a brickwall (#4148), because the code examples are based on the latest (unreleased) version of wagtail (version 2.0).

I'd like to suggest that the link on the wagtail website be changed from http://docs.wagtail.io/en/latest/getting_started/tutorial.html to http://docs.wagtail.io/en/stable/getting_started/tutorial.html, that is, from **latest** to **stable**. This will be less confusing to wagtail newcomers. 

Thanks

**Comment by tomdyson** [comment]
Thanks @engineervix! I tried fixing this but saw that @gasman had beaten me to it :)

**Comment by engineervix** [comment]
Thanks! :smiley: :relaxed: :relaxed:

**Comment by thibaudcolas** [comment]
I see there are [plenty of other links](https://github.com/wagtail/wagtail/search?utf8=%E2%9C%93&q=docs.wagtail.io%2Fen%2F&type=) around the repository pointing to `latest` – should those be updated as well?

**Comment by engineervix** [comment]
> I see there are [plenty of other links](https://github.com/wagtail/wagtail/search?utf8=%E2%9C%93&q=docs.wagtail.io%2Fen%2F&type=) around the repository pointing to `latest` – should those be updated as well?

@thibaudcolas I think it would be good to do so.

**Comment by gasman** [comment]
@thibaudcolas Many of those links are directed at people developing on Wagtail itself - e.g. "you don't have static assets compiled; here's how to fix that", and for those, linking to `latest` is more appropriate. The only one I can see that might be worth fixing is the form builder link in the readme.
