### ISSUE TITLE
wagtail documentation - python3.4 manage.py

### ISSUE THREAD

**Issue by gz1968** [wagtail/wagtail#4155]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
I'm new to Wagtail.  During setup, the wagtail documentation said to run the following commands.
   $ pip install -r requirements.txt
   $ ./manage.py migrate
   $ ./manage.py createsuperuser
   $ ./manage.py runserver

It didn't work for me.  It worked when I put python3.4 before each command as follows
   python3.4 manage.py ...

That's it.

**Comment by gasman** [comment]
Thanks for the report @gz1968! Unfortunately this is something that differs between environments (e.g. operating system, python version, and whether a virtualenv is being used) - covering all the possible variations would be out of scope for the Wagtail documentation.
