### ISSUE TITLE
Group edit permission checkboxes have superfluous labels

### ISSUE THREAD

**Issue by timheap** [wagtail/wagtail#4160]
### Issue Summary

The permission checkboxes on the group add/edit screen have superfluous labels that make the page very awkward to use. I think this might be a bug introduced in Django 1.11 with the widget template changes.

![image](https://user-images.githubusercontent.com/132147/34472752-f3b4832a-efbc-11e7-8282-c687fd398f31.png)

### Steps to Reproduce

1. Navigate to "Settings" -> "Groups"
2. Add a new group, or edit an existing group
3. Observe the checkboxes with extra, unnecessary labels

### Expected behaviour

It looks much more like this: 
![image](https://user-images.githubusercontent.com/132147/34472773-3c9a8ea4-efbd-11e7-8500-190177a423fa.png)

### Technical details

* Python version: 3.6.3
* Django version: 1.11.8
* Wagtail version: 1.13.1

**Comment by timheap** [comment]
Investigating further, this is actually a problem on my end. This project has overridden the `django/forms/widgets/checkbox_option.html` template, used to render all CheckboxSelectMultiple widgets by default, which causes the rendering issue in the Wagtail admin. I'll fix the problem on my end, but does pose a new question: Is it worth coding defensively in Wagtail to prevent this kind of thing from happening? If

**Comment by gasman** [comment]
Thanks for investigating, @timheap. Yep, I think I'd regard this as an expected consequence of overriding the template, so I'll close as wontfix. (Having said that, if there _is_ a neat way of avoiding this without creating a load of work across the codebase, I'd be happy to consider a PR...)
