### ISSUE TITLE
please suport django2

### ISSUE THREAD

**Issue by leeyisoft** [wagtail/wagtail#4161]
please suport django2

**Comment by gasman** [comment]
Hi @leeyisoft,
Django 2.0 support is in place for the next release of Wagtail - please see #3917.

**Comment by leeyisoft** [comment]
I run command " pip install -U wagtail "  that output "Successfully uninstalled Django-2.0.1\nSuccessfully installed Django-1.11.9", How can I use "Django-2.0.1" @gasman

**Comment by gasman** [comment]
@leeyisoft At the moment, Django 2 support is not available on any release that's installable through `pip` - you'll need to wait for the release of Wagtail 2.0 (hopefully later this month), or try out the development version (http://docs.wagtail.io/en/v1.13.1/contributing/developing.html).
