### ISSUE TITLE
Feature Request: Show collection in Document chooser modal

### ISSUE THREAD

**Issue by patta42** [wagtail/wagtail#4162]
Currently, the Document Chooser does not show the collection of the document. If you have multiple documents with the same title or do not remember the exact title or file name, the corresponding collection might provide another hint.

Currently, one has to check every possible collection manually, which is not very helpful if you maintain several hundred collections.

I would also appreciate this for the image chooser, but I think that is not so easy to implement there.

**Comment by gasman** [comment]
Completed in #4854.
