### ISSUE TITLE
ValidationError: A Page with that path already exists

### ISSUE THREAD

**Issue by patta42** [wagtail/wagtail#4168]
I would like to draw attention to a problem that happened to me (and at least one other) with treebeard which is reported here: https://github.com/django-treebeard/django-treebeard/issues/81

I cannot provide steps how to reproduce this issue, but maybe some other people experienced this, too, and I think more people read the wagtail issues than the treebeard ones.

**Comment by gasman** [comment]
Hi @patta42 - thanks for the report.
You can try running the command `./manage.py fixtree`, which is able to fix some page tree integrity issues - unfortunately, without any steps to reproduce, we can't really follow this up further, or determine whether this is an error in Wagtail, treebeard, or in user configuration. (#3658 is a known issue which could cause this kind of error on some configurations.)

**Comment by engineervix** [comment]
> Hi @patta42 - thanks for the report.
> You can try running the command `./manage.py fixtree`, which is able to fix some page tree integrity issues - unfortunately, without any steps to reproduce, we can't really follow this up further, or determine whether this is an error in Wagtail, treebeard, or in user configuration. (#3658 is a known issue which could cause this kind of error on some configurations.)

I encountered this problem recently and I can confirm that running `./manage.py fixtree` fixed the problem. In my case, I must have broken the tree after batch-creating `Page` objects via the Django shell and importing some previously dumped `Page`s via `loaddata`.

Thanks @gasman
