### ISSUE TITLE
new version Deprecated module

### ISSUE THREAD

**Issue by ggzhang0071** [wagtail/wagtail#4177]
### Issue Summary

Deprecated since version 1.10: In older versions, these functions are located in django.core.urlresolvers. Importing from the old location will continue to work until Django 2.0.
__>
https://docs.djangoproject.com/en/1.11/ref/urlresolvers/

### Steps to Reproduce
1.wagtail/wagtailcore/models.py", line 16, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
2.wagtail/wagtailadmin/widgets.py", line 8, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
3.wagtail/wagtailsnippets/models.py", line 3, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
4.wagtail/wagtaildocs/models.py", line 7, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
5.wagtail/wagtailimages/models.py", line 12, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'

from django.urls import  reverse

??????

### Technical details

* Python version: Python 3.6.4rc1
* Django version: 2.0.1
* Wagtail version: 1.13.1
* Browser version: Firefox 52.

👍

**Comment by thibaudcolas** [comment]
Hi @ggzhang0071, the version of Django you're using isn't compatible with Wagtail 1.13.

The next release of Wagtail (Wagtail 2.0) will be compatible with Django 2 – see https://github.com/wagtail/wagtail/issues/4161#issuecomment-355251131 for more details. If you want to help making this happen faster, please have a look at the "Planned for 2.0" column on the roadmap: https://github.com/wagtail/wagtail/projects/1.
