### ISSUE TITLE
Moving a page corrupts the url_path of children pages when using mssql database

### ISSUE THREAD

**Issue by mikemonteith** [wagtail/wagtail#4183]
https://github.com/wagtail/wagtail/blob/d1978995c20e948d1d06d6818a67b0ccee52c40b/wagtail/core/models.py#L563

The `SUBSTRING` method here is doing the opposite of what it should.
It should take a substring from the right of `url_path` but it is taking substring from the left.

SUBSTRING docs: https://docs.microsoft.com/en-us/sql/t-sql/functions/substring-transact-sql
`SUBSTRING ( expression ,start ,length )`.

This means that when moving a parent page from `/home/parent-slug-old/` to `/home/parent-slug-new/`, it's children are given `url_path = /home/parent-slug-new//home/parent-slug-old/` instead of `url_path = /home/parent-slug-new/child-slug/`

**Comment by gasman** [comment]
Thanks for the report @mikemonteith! This was previously noticed by @BertrandBordage https://github.com/wagtail/wagtail/pull/3496#pullrequestreview-29945754 but we weren't able to confirm it as a bug due to us lacking a working mssql testing setup.
