### ISSUE TITLE
Allow setting template_url from block constructor ?

### ISSUE THREAD

**Issue by stuaxo** [wagtail/wagtail#4188]
I'm pretty new to wagtail, but I've noticed, that similarly to someones S/O answer to another question here -

https://stackoverflow.com/a/39438302/62709

I extend various Blocks, mostly to set templates="something".

Would you consider allowing them to be set by passing into the blocks constructor ?

**Comment by gasman** [comment]
Does that not work already? As per the docs http://docs.wagtail.io/en/v1.13.1/topics/streamfield.html#structblock :

> The Meta class supports the properties `default`, `label`, `icon` and `template`, which have the same meanings as when they are passed to the block’s constructor.

**Comment by stuaxo** [comment]
My fault for scan-reading the docs and only looking at the code !

Thanks.   Will re-open if I find it doesn't work.
