### ISSUE TITLE
Can't insert internal #-links with RichTextField

### ISSUE THREAD

**Issue by kunambi** [wagtail/wagtail#4190]
### Issue Summary

When trying to insert a link (by clicking the link-icon in the toolbar) in the RichTextEditor, and only writing `#my_internal_anchor` I get an error message.

### Steps to Reproduce

It's essential that you provide enough information for someone else to replicate the problem you're seeing. Simply describing something that's broken on your current project is not enough!

1. Write text in a RichTextField
2. Highlight some of that text
3. Click the link-icon in the toolbar
4. Click "Insert external link" 
5. Enter "`#my_internal_anchor`" in the URL-field
6. Error message is shown `Enter a valid URL. `

#### Expected result

I wish that it would accept the value I entered. Now I need to edit the value through the database instead.

**Comment by gasman** [comment]
Hi @kunambi - this is covered by #1049.
