### ISSUE TITLE
PasswordResetForm leaks information about registered users

### ISSUE THREAD

**Issue by todd-dembrey** [wagtail/wagtail#4191]
### Issue Summary

The PasswordResetForm returns validation errors about whether the account exists in wagtail or not and some information about whether wagtail manages the password. 

e.g:
"This email address is not recognised."
"Sorry, you cannot reset your password here as your user account is managed by another server."

https://github.com/wagtail/wagtail/blob/master/wagtail/admin/forms.py#L87

The standard django behaviour is to not leak this information. It gets all users with the supplied email and sends them the relevant information. If the user supplies an invalid email they progress to the success screen but no email is sent.

https://github.com/django/django/blob/master/django/contrib/auth/forms.py#L282:28

### Proposed Fix

Change the behaviour of the password reset to inform the user that an email has been sent to the supplied address regardless of whether the email is registered with the site.

Send an email to accounts that do exists. and within the email include any validation messages within that email e.g. who manages the password.

**Comment by tmsndrs** [comment]
This would create a pretty painful user experience...

**Comment by tomdyson** [comment]
> This would create a pretty painful user experience...
Nevertheless, I agree with @todd-dembrey that we shouldn't leak account data.

**Comment by zerolab** [comment]
The Django ticket is https://code.djangoproject.com/ticket/19758 

This is something that comes up regularly in pen test on Drupal sites. We install a separate module for it.

**Comment by loicteixeira** [comment]
Thanks for reporting the issue. I see the `decision needed` tag has been removed already, but to be a bit more verbose, it was decided to follow Django's implementation (similar behaviour and [wording](https://github.com/django/django/blob/d7b2aa24f75434c2ce50100cfef3586071e0747a/django/contrib/admin/templates/registration/password_reset_done.html#L15-L17)) and prevent any leakage).

**Comment by gasman** [comment]
Fixed in #4314.
