### ISSUE TITLE
API lookup by path, not ID

### ISSUE THREAD

**Issue by Designer023** [wagtail/wagtail#4194]
Hi,

Is there any documentation on how I can do a lookup by page path. Currently the V2 API uses the ID as the lookup? I'd also be interested in by slug but this doesn't fit my current use case right now.

I ended up writing new serializers and endpoints but the path lookups are far to closely linked with the model itself. I'm looking for some kind of generic Page by Path endpoint. Does this exists.

My specific use case is for a front end app that takes the path it gets and maps it to the API view. I can't use the id because the front end would have no idea what to look for in the api e.g.

user visits **/page/sub-page/sub-sub-page/**
api call is /api/pages/with-path/**page/sub-page/sub-sub-page/**
api returns **sub-sub-page** detail view

Any pointers or advice would be most welcome, and forgive me if I have missed some really obvious piece of documentation!

**Comment by gasman** [comment]
Hi @Designer023,
Unfortunately this isn't supported yet - there's a feature request open for this at #4154.

**Comment by Designer023** [comment]
Thank you. I didn't see this. I'll subscribe to the issue :)
