### ISSUE TITLE
Page edit is very slow when using nested StructBlocks

### ISSUE THREAD

**Issue by alesdotio** [wagtail/wagtail#4198]
### Issue Summary

I'm experiencing very slow load times for admin edit pages. It usually takes about 20s to open an edit page in the CMS. No other page has this problem.

### Example

I have about 30 custom StructBlocks that can be nested up to 5 levels. For example, I have a "header block" that can contain multiple "row blocks" which in turn can contain multiple "column blocks" which again can contain any of the 30 custom StructBlocks. This causes the edit page HTML form to grow exponentially. My edit pages are now **200k lines of HTML**, which as you can imagine takes a lot of time to load.

### Steps to Reproduce

1. Start a new project
2. Create a lot of nested StructBlocks as described above
3. Open an admin page edit url ``/cms/pages/1/edit/``
4. The page will take a long time to load

### Technical details

* Python 2.7.6
* Django 1.9.5
* wagtail 1.12.2
* any browser

### Possible solution

I realize that this is maybe not the most common way to use Wagtail, but I have found this setup of blocks to work extremely well, since it allows almost endless possibilities for our content creators. Except for the admin edit page load speed, it has been working really well. As a side note, I had to add some custom CSS to be able to view this many levels of nested blocks.

The cause is clearly in the form size. I noticed, most of the form elements are duplicated many times and just hidden. These are used for adding new block, so when the user click on the add button they are simply show with some javascript. One way to solve this would be to not do that for new forms, and instead only load it with AJAX, once the user selects to add that block.

**Comment by gasman** [comment]
Hi @alesdotio - thanks for the report. This is covered by #3062.
