### ISSUE TITLE
Replace div to p in editor_html.py

### ISSUE THREAD

**Issue by gagaga67** [wagtail/wagtail#4220]
Hello! 
We make the plugin by analogy with halloplugin. But for this work, this condition (the substitution of divs for p) hinders us. How do you propose to act in this case?
Links: https://github.com/wagtail/wagtail/blob/ebbbd7ad491fe09a042afe19dab9d0ea57040646/wagtail/admin/rich_text/converters/editor_html.py#L123

### Technical details
* Python version: 3.6.
* Django version: 2.0.1.
* Wagtail version: latest 2.0.beta1.

**Comment by gasman** [comment]
I'd suggest looking at the way Wagtail implements images and media embeds: the element is inserted with a `data-embedtype` attribute, which (through various hooks) is converted to an `<embed>` element in the database representation. This is then converted to your desired front-end HTML when you use the `|richtext` filter.

Rich text editors are generally quite poor at handling "structural" HTML, so this replacement method avoids any issues with preserving HTML in the round trip from database to editor and back.
