### ISSUE TITLE
Draftail documentation

### ISSUE THREAD

**Issue by SalahAdDin** [wagtail/wagtail#4221]
Hi, i'm testing the new beta release and i have two questions:

1. How can we extend draftail toolbar?
I'm seeing in `draftail` page many interesting examples but i can't understand how can i implements other buttons. I saw in this page that we have to modify some `js` files but i wan't to know if we can set this buttons in the settings file.

2. I'm contributting to `wagtailembedvideos` (my own fork) and i implemented the embed video embed feature for `hallo.js` editor. I works in the same way that embed image and it wasn't very hard to implements in the package. But now, it is different. It's harder i think because we have, until i know, use `react` and build it with `npm` to getting using.
 
Finally i want to ask about properly documentation for Draftail in order to customize it and implement his features in other possible packages.

Thank you very much and Good job.

**Comment by thibaudcolas** [comment]
Hey @SalahAdDin, first off thank you so much for taking the time to try out the beta 😄!

Sorry the documentation isn't there yet, I'm going to work on this over the next few days. Ideally, I'll do this while implementing some example controls so there is something to start from.

For extension, here is what I can say quickly:

- Extending the toolbar is done with hooks that I think may be documented – I'll double check.
- Implementing new "inline styles" controls (bold, strikethrough, highlights, etc) should be very straightforward and require only Python code.
- Implementing block-level formats (blockquote, h6, etc) should be straightforward as well, and require only Python code, unless you want to give specific styling to the blocks in the editor in which case you need to write some CSS as well.

Implementing "entities" (things with data, images, video, embeds, etc) is another story. I'll write more about this tomorrow, and also try to look into `wagtailembedvideos`.

**Comment by SalahAdDin** [comment]
Thank you very much,

I'm thinking about implement the next buttons:
- Underline
- Strikethrough
- Mark
- Quotation
- Keyboard
- Blockquote

They aren't very much, hahaha, and in the other hand in `draftail` we can grouping buttons, how can we do this? We hope we can do this with normal `django wagtail` settings.

This feature only exist in my fork, because in the official package never had been implemented, unfortunately; implementing this feature was a few easy with `hallo.js`, but i don't know how can i implementing it in `draftail`, and also putting support for `hallo.js too.

And yes, un `Draftail` documentation there aren't references about this new feature in `wagtail`.

I can help you if you need.

Thank you very much.

**Comment by SalahAdDin** [comment]
I'm reviewing the PR and i found some problems:
- client/src/components/Draftail/blocks/ImageBlock.js
We have to create a new `block` `js` file for integrate it in wagtail.
- client/src/components/Draftail/blocks/ImageBlock.scss
Other for `scss` styles.
I won't take in account his respective test files.
- client/src/components/Draftail/blocks/MediaBlock.js
I can't understand which is the porpouse of this file.
- client/src/components/Draftail/index.js
Of course we have to import this files in `Draftail` index.

The main problem with this files, it is easy to know, is that we can't manipulate the `Draftail` source files since external third packages.

But the next files are more easy to fork:
- wagtail/images/rich_text.py
- wagtail/images/wagtail_hooks.py

I will implement both of them in the package, but i still need help with the package, because i'm not a senior `wagtail` developer, XD, and i think that still my fork need more work with `hallo` and `draftail` integration.

@thibaudcolas Can you help me?

**Comment by thibaudcolas** [comment]
@SalahAdDin I'll be working on proper documentation tomorrow, if you can wait until tuesday-ish it will be much easier for you to find your way around this.

In the meantime, here is one of the simplest examples possible to create a `strikethrough` format that renders `<s>` tags on the site: https://github.com/thibaudcolas/bakerydemo/commit/d7ae253184684b592bc3be4ef82c737fd81cad7f?w=1

**Comment by thibaudcolas** [comment]
My bad, it's simpler than that – `construct_whitelister_element_rules` is what we had before, we now have a new API for this that's part of the rich text features umbrella.

Honestly I don't think it's that hard overall, but I can definitely agree there is a LOT of useless boilerplate, and a lot of potential trial and error figuring out which string to use in which place. Keep in mind though that this is only the first version of this API, we have yet to properly try it with real-world use cases. The current API is quite low-level, but in the future I could very well see Wagtail core (or a plugin) have a better API for simple definitions like `strikethrough`.

For the embed videos case – one word of caution: it's *much* harder to create whole-custom blocks in Draftail rich text, than the 6 cases you described above. I'll document how, but for the foreseeable future **StreamField is the go-to way to implement embed-style rich text**.

**Comment by SalahAdDin** [comment]
@thibaudcolas Yes, i aggree, because implements features like this in this editor could be painfully.

**Comment by SalahAdDin** [comment]
@thibaudcolas I had to pass a lot of suffering for finally get this: https://github.com/SalahAdDin/wagtail-embedvideos/pull/31

I think i won't make the respective `Draftail` implementation. XD

**Comment by gasman** [comment]
Fixed in #4229
