### ISSUE TITLE
Incorrect page title alignment on 'edit page'

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#4227]
As reported on #4222, the page title on the 'edit page' view is incorrectly aligned. `git bisect` shows that this was introduced in commit 5f08013ad2d0a4c31f49fe4177eca4fad96539d5.

Testing against bakerydemo:
<img width="719" alt="screen shot 2018-01-30 at 11 47 19" src="https://user-images.githubusercontent.com/85097/35565537-d8abcb38-05b5-11e8-89ac-84f68874b8a5.png">

Correct rendering:
<img width="878" alt="screen shot 2018-01-30 at 11 50 16" src="https://user-images.githubusercontent.com/85097/35565553-e550269a-05b5-11e8-958c-d48346c300a9.png">

**Comment by thibaudcolas** [comment]
Fixed in #4229 (not merged yet).
