### ISSUE TITLE
Long filename image overlap next image

### ISSUE THREAD

**Issue by luizboaretto** [wagtail/wagtail#4233]
### Issue Summary

When you send an image and not change the title it remains the name of the file. If this name is large it will go over the next image.

![captura de tela 2018-02-01 as 09 14 41](https://user-images.githubusercontent.com/32047234/35678203-3bfc13ce-0731-11e8-88ed-aba7cf0e6adb.png)

This does not happen when you fix the title by swapping "_" by "spaces"

I'm not frontend expert but by including the line in `<h3>` -> `overflow-wrap: break-word;` worked as expected.

### Steps to Reproduce

Just upload an image with long filename.

### Technical details

* Python version: 3.6.4
* Django version: 2.0.1
* Wagtail version: 2.0b1
* Browser version: 58.0.1 (64-bit) - OSX

**Comment by thibaudcolas** [comment]
Thank you for the report @luizboaretto, and the fix suggestion 🙂.

**Comment by luizboaretto** [comment]
Thanks @thibaudcolas 👍
