### ISSUE TITLE
Tell editors if they're short on battery when they start writing a new article. 

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#4240]
Thought this might be a nice simple feature. Just to have some sort of dialog that says 'You've only got 2 minutes battery life left, grab your charger before getting started' or something like that. 

Uses the Battery API in most modern browsers 
https://davidwalsh.name/battery-api

**Comment by SalahAdDin** [comment]
Interesting.

**Comment by thibaudcolas** [comment]
This API got removed in Firefox, and in WebKit (Safari didn’t add it). Right now [only Chrome supports it](https://caniuse.com/#feat=battery-status) which probably isn't enough to justify the effort, so I'll close this.

To achieve a similar-ish outcome we could work towards having some auto-save feature, like suggested for #2199, #995.
