### ISSUE TITLE
Enhancement request: support editing of template HTML files with the Admin UI

### ISSUE THREAD

**Issue by wtorcaso** [wagtail/wagtail#4241]
### Issue Summary

This is a (large) enhancement request, and it is not at all necessary.  

Add a new sidebar section named 'Templates'.  The Admin user can traverse the tree of HTML template files, and edit them in a plain-text window.

The benefit is that the Admin user can more seamlessly configure a StreamField element and the template that renders it.  

An example use case is to add an ImageBlock to a StreamField body, and then hop over into Templates > some_thing.HTML to add html tags for the image.

This proposal only supports editing template files that already exist.  An extension is to allow the creation of an empty HTML file on the fly, and then add content to it, without leaving the Wagtail Admin window.

**Comment by gasman** [comment]
Hi @wtorcaso - thanks for the suggestion.

This isn't really something we'd go for in Wagtail itself, although it would be a good candidate for a third-party add-on. Wagtail takes the approach that programming and editorial responsibilities should be kept separate (see http://docs.wagtail.io/en/v1.13.1/getting_started/the_zen_of_wagtail.html#always-wear-the-right-hat), and if anyone's editing template files, they're (de facto) a programmer, and are better served by giving them established programming tools (including version control, testing environments, full-featured text editors...). Even if we just add a simple editor for one-off changes, the scope is liable to grow to the point where we're reinventing that ecosystem badly...

Also, whether this feature can work at all would depend a lot on how the site is hosted: often the web server process will have read-only access to the files, for security reasons, so it wouldn't be able to write changes back - and I suspect that cloud hosting providers like Heroku, which don't keep a persistent filesystem, will just revert back to the file as it appears in version control.
