### ISSUE TITLE
Page published for a future date, page.live is True

### ISSUE THREAD

**Issue by cheluis** [wagtail/wagtail#4245]
I am using Wagtail 1.9, after creating the page, at the after_create_page, if the page's date is published for a day in the future, page.live is set to True. If I check the same page afterwards, using the console, page.live is False. Is any bug for this particular version?

**Comment by gasman** [comment]
Wagtail 1.9 is no longer supported, sorry.

Note that Wagtail 2.0 (currently in beta) includes an enhancement to allow pages to remain live while a new version is scheduled for publishing: http://docs.wagtail.io/en/latest/releases/2.0.html#scheduled-page-revisions
