### ISSUE TITLE
cannot choose snippets using snippetchooserpanel in wagtail

### ISSUE THREAD

**Issue by divyanshprateek** [wagtail/wagtail#4260]
from django.db import models

from wagtail.wagtailadmin.edit_handlers import FieldPanel,InlinePanel
from wagtail.wagtailsnippets.models import register_snippet
from django.db import models

from wagtail.wagtailcore.models import Page, Orderable
from wagtail.wagtailsnippets.edit_handlers import SnippetChooserPanel

from modelcluster.fields import ParentalKey

...

@register_snippet
class Advert(models.Model):
    url = models.URLField(null=True, blank=True)
    text = models.CharField(max_length=255)

    panels = [
        FieldPanel('url'),
        FieldPanel('text'),
    ]

    def __str__(self):
        return self.text
class BookPageAdvertPlacement(Orderable, models.Model):
    page = ParentalKey('snip.BookPage', on_delete=models.CASCADE, related_name='advert_placements')
    advert = models.ForeignKey('snip.Advert', on_delete=models.CASCADE, related_name='+')

    class Meta:
        verbose_name = "advert placement"
        verbose_name_plural = "advert placements"

    panels = [
        SnippetChooserPanel('advert'),
    ]

    def __str__(self):
        return self.page.title + " -> " + self.advert.text

class BookPage(Page):
    ...

    content_panels = Page.content_panels + [
        InlinePanel('advert_placements', label="Adverts"),
        # ...

**Comment by gasman** [comment]
We can't investigate this without a description of the problem, sorry - please open a new issue with the requested details filled in.
