### ISSUE TITLE
unable to select snippets using snippet chooser panel

### ISSUE THREAD

**Issue by divyanshprateek** [wagtail/wagtail#4265]
![screenshot 1](https://user-images.githubusercontent.com/26978020/36058341-7f8366d8-0e43-11e8-9093-47802a15d44c.png)

I have used the same code from documentation but I am not able to figure out where I did go wrong.The code snippet from models.py is:

from django.db import models

from wagtail.wagtailadmin.edit_handlers import FieldPanel,InlinePanel
from wagtail.wagtailsnippets.models import register_snippet
from django.db import models

from wagtail.wagtailcore.models import Page, Orderable
from wagtail.wagtailsnippets.edit_handlers import SnippetChooserPanel

from modelcluster.fields import ParentalKey

...

@register_snippet
class Advert(models.Model):
    url = models.URLField(null=True, blank=True)
    text = models.CharField(max_length=255)

    panels = [
        FieldPanel('url'),
        FieldPanel('text'),
    ]

    def __str__(self):
        return self.text
class BookPageAdvertPlacement(Orderable, models.Model):
    page = ParentalKey('snip.BookPage', on_delete=models.CASCADE, related_name='advert_placements')
    advert = models.ForeignKey('snip.Advert', on_delete=models.CASCADE, related_name='+')

    class Meta:
        verbose_name = "advert placement"
        verbose_name_plural = "advert placements"

    panels = [
        SnippetChooserPanel('advert'),
    ]

    def __str__(self):
        return self.page.title + " -> " + self.advert.text

class BookPage(Page):
    ...

    content_panels = Page.content_panels + [
        InlinePanel('advert_placements', label="Adverts"),
        # ...
    ]

**Comment by gasman** [comment]
There's still not enough detail here, sorry. Your screenshot simply shows that the "Advert" field has not been filled in, so the error message is correct. If there's more background information leading up to this error (for example: you tried clicking on the 'Choose Advert' button but nothing happened), you need to tell us this as part of your report.

When you open a new issue, there is some text beginning "Found a bug? Please fill out the sections below." This is designed to help you supply the information we need. If you don't fill this in, we can't help you.

**Comment by divyanshprateek** [comment]
I tried clicking on 'choose advert' button but nothing happened
