### ISSUE TITLE
No site on wsgi_request in unittests ?

### ISSUE THREAD

**Issue by stuaxo** [wagtail/wagtail#4272]
I'm trying to write unittest for the navigation tags from here

https://github.com/wagtail/bakerydemo/blob/master/bakerydemo/base/templatetags/navigation_tags.py#L12

In the unittest I get the request object
```python
    client = Client()
    response = client.get('/industries/aerospace')
    request = response.wsgi_request
    context = {
        'request': request
    }
    html = render_to_string(
        "sector/sector_page.html",
        context,
        request=request)
```

This fails because when it goes to render the template tags, it's expecting ```.site``` to exist, but it dies

https://github.com/wagtail/bakerydemo/blob/master/bakerydemo/base/templatetags/navigation_tags.py#L12

I've got the site middleware, and the same code works outside of the unittest.

**Comment by gasman** [comment]
Hi @stuaxo,
By default the Django test client uses the hostname `testserver`, which (probably) doesn't correspond to a recognised site - if you're testing site-dependent code, you need to override this using something like:

    client = Client(SERVER_NAME="mydomain.com")

**Comment by stuaxo** [comment]
Cheers - the code in question was looking for a Site object called site.

Should I create this manually (I'm not entirely sure what it is, I guess, a wagtail thing that defines the root page ?)

**Comment by gasman** [comment]
`request.site` gets populated by the `wagtail.wagtailcore.middleware.SiteMiddleware` middleware when it encounters a known hostname, so - assuming that's enabled in your settings - passing a recognised hostname from the test client should be enough to fix this.

**Comment by stuaxo** [comment]
Cheers.

This is where I wish python had a similar philosophy to rust when it comes to error messages and could have told me that might be what was missing 🤷‍

**Comment by stuaxo** [comment]
Didn't seem to help... I'm starting to wonder if it's because I'm using py.test.

In settings I have:

```BASE_URL = 'http://invest.great.gov.uk'```

My test looks like

```
@pytest.mark.django_db
def test_sector_page():
    client = Client(SERVER_NAME='invest.great.gov.uk')
    response = client.get('/industries/aerospace')
    request = response.wsgi_request
    context = {
        'request': request
    }
    html = render_to_string(
        "sector/sector_page.html",
        context,
        request=request)
    assert html
```


```
Exception raised while rendering {% include %} for template 'sector/sector_page.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/site-packages/django/template/loader_tags.py", line 216, in render
    return template.render(context)
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/site-packages/django/template/loader_tags.py", line 63, in render
    result = self.nodelist.render(context)
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/stu/projects/work/dit/invest/invest/templatetags/navigation_tags.py", line 16, in get_site_root
    return context['request'].site.root_page
AttributeError: 'WSGIRequest' object has no attribute 'site'
```

**Comment by gasman** [comment]
Possibly... note that you'll also need to ensure that the appropriate site record is in place in your test database. Typically you'd do that through a fixture, but not sure if that's the same with py.test - I'd suggest asking via StackOverflow.

**Comment by stuaxo** [comment]
Sorted it, I needed to drop the http:// part, which should have been obvious given the error.

**Comment by stuaxo** [comment]
Oops, failed to mention I sorted it by adding it manually, after I looked at the wagtail site middleware to see what it does -

```        
request.site = Site.find_for_request(request)
```

**Comment by stuaxo** [comment]
Hrm, it turns out pytest-djangos version of request doesn't have get_host and other needed APIs, so I opened a bug there.
