### ISSUE TITLE
[wagtail==2.0b1] django.contrib.gis.db.models.PointField too many digits stored in the db

### ISSUE THREAD

**Issue by cubocsj** [wagtail/wagtail#4275]
### Issue Summary

With wagtail==l2.0b1 there is an issue with GeoDjango and PointField 'from django.contrib.gis.db.models' not getting saved correctly in the database using the default SRID=4326.

The correctly coordinates that should be saved are 1 or 2 digits followed by 15 decimals. Like in this example.

```
{ "type": "Point", "coordinates": [ 9.66796874865269, 56.211592424472038 ] }
```

Instead the coordinates are saved with too big of number, in this case 7 digits before 15 decimals.

```
{ "type": "Point", "coordinates": [ 1117022.040449609048665, 7650220.664336053654552 ] }
```

I have tested this with...
1. wagtail==1.13 and django==1.11 (correct)
2. wagtail==1.13 and django==2 (correct)
3. wagtail==2.0b1 and django==2 (incorrect)
4. django==2 (correct)

DATABASE:
PostgreSQL with PostGIS spatial extension

Therefore I suspect the issue to be related to wagtail==2.0b1

### Steps to Reproduce

It's essential that you provide enough information for someone else to replicate the problem you're seeing. Simply describing something that's broken on your current project is not enough!

1. Start a new wagtail==2.0b1 project with `wagtail start myproject`
2. Make sure you have a spatial PostgreSQL database with PostGIS extension - https://docs.djangoproject.com/en/2.0/ref/contrib/gis/install/geolibs/
3. Add 'django.contrib.gis' to INSTALLED_APPS
4. Make sure you configure 'ENGINE': 'django.contrib.gis.db.backends.postgis' in the settings.py file.
5. And make sure Django know the location of 'GDAL_LIBRARY_PATH' and 'GEOS_LIBRARY_PATH' https://docs.djangoproject.com/en/2.0/ref/contrib/gis/install/geolibs/#gdaltrouble
6. Create a simple model, login to the admin and set point of the map and check what is stored in 'page.coordinates.location'.
```
from django.contrib.gis.db.models import PointField
from django.contrib.gis.forms import OSMWidget
from django.db import models
from wagtail.admin.edit_handlers import FieldPanel
from wagtail.core.models import Page

class Coordinates(Page):
    location = PointField(blank=True, null=True)

    content_panels = Page.content_panels + [
        FieldPanel('location', widget=OSMWidget(
            attrs={
                'default_zoom': 6,
            })),
    ]
```

**Comment by gasman** [comment]
Hi @cubocsj - thanks for the really detailed report!

I'm pretty sure this is a Django 1.11 -> 2.0 change after all. While troubleshooting I found it pretty hard to keep track of the installed versions, so it's understandable that it looked like a Wagtail 2.0 issue - however, here are the exact steps I took which show the Django version making a difference:

* Create a new virtualenv, database and Wagtail project:

        mkvirtualenv wagtailgis --python=/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6
        pip install wagtail==2.0b1 Django==1.11.10 psycopg2
        wagtail start wagtailgis
        createdb wagtailgis
        psql wagtailgis -c "CREATE EXTENSION postgis;"

* Edit wagtailgis/wagtailgis/settings/base.py: add 'django.contrib.gis' to INSTALLED_APPS, and add the following settings:

        DATABASES = {
            'default': {
                'ENGINE': 'django.contrib.gis.db.backends.postgis',
                'NAME': 'wagtailgis',
            }
        }

        # change as appropriate for your installed version of Postgres
        GDAL_LIBRARY_PATH = '/Applications/Postgres.app/Contents/Versions/9.4/lib/libgdal.dylib'
        GEOS_LIBRARY_PATH = '/Applications/Postgres.app/Contents/Versions/9.4/lib/libgeos_c.1.dylib'

* Edit wagtailgis/home/models.py as follows:

        from django.contrib.gis.db.models import PointField
        from django.contrib.gis.forms import OSMWidget
        from django.db import models
        from wagtail.admin.edit_handlers import FieldPanel
        from wagtail.core.models import Page


        class HomePage(Page):
            pass


        class Coordinates(Page):
            location = PointField(blank=True, null=True)

            content_panels = Page.content_panels + [
                FieldPanel('location', widget=OSMWidget(
                    attrs={
                        'default_zoom': 6,
                    })),
            ]

* Run migrations and start server:

        cd wagtailgis
        ./manage.py makemigrations
        ./manage.py migrate
        ./manage.py createsuperuser
        ./manage.py runserver

* Log in to http://localhost:8000/admin/
* Create and publish a Coordinates page as a child of Home
* Confirm that the location has saved correctly:

        ./manage.py shell

        >>> from home.models import Coordinates
        >>> str(Coordinates.objects.first().location)
        'SRID=4326;POINT (4.994163513183592 47.00659225405263)'

* Upgrade to Django 2.0:

        pip install Django==2.0.2
        ./manage.py runserver

* Edit the page and republish it (with the location moved slightly)
* The saved coordinates are now incorrect:

        ./manage.py shell

        >>> from home.models import Coordinates
        >>> str(Coordinates.objects.first().location)
        'SRID=4326;POINT (558393.7241310684 5962297.63805537)'

Running against the Django git repo shows that the breakage was introduced in this commit:

https://github.com/django/django/commit/24023c6a8fc768ccb72108d2dd4fd8ece04075fd
https://code.djangoproject.com/ticket/25874

**Comment by cubocsj** [comment]
@gasman Sorry for the mistake and the confusing I caused. But thanks for clearing it out.
