### ISSUE TITLE
Ancestor page permissions only are reported but other permissions may be enforced

### ISSUE THREAD

**Issue by nimasmi** [wagtail/wagtail#4277]
### Issue Summary

Page permissions are not enforced in the same way as suggested in the editor UI.

In particular, at https://github.com/wagtail/wagtail/blob/f0eef2fc88043ba627b89125876f1cfe53b7fc51/wagtail/admin/views/page_privacy.py#L16 and then https://github.com/wagtail/wagtail/blob/f0eef2fc88043ba627b89125876f1cfe53b7fc51/wagtail/admin/views/page_privacy.py#L52 the editor UI suggests that the first found ancestor restriction is the one which will be enforced, as it doesn't show the permission configuration form if such a restriction is found.

However, it is possible to create a child page with higher permission than a private parent page.

### Steps to Reproduce

Create two user groups. Foo and Bar, and a user in each, foo_user and bar_user.

Create two pages:

- `/general-private-page/`
- `/general-private-page/foo-users-only-page/`

**First** set a group permission on the second page for Foo group users only.

**Only now** set a group permission on the first page for Foo and Bar users.

Now foo_user can visit both pages, whereas bar_user can visit only `/general-private-page/`. However, in the editor, the privacy modal for `/general-private-page/foo-users-only-page/` says:

> This page has been made private by a parent page.
> You can edit the privacy settings on: General private page.

The privacy modal for `/general-private-page/` shows that it is open to Foo group users and Bar group users.

I would expect either that bar_user can visit both pages, as suggested by the privacy modal, or that the admin show the child page permission form.

### Technical details

* Wagtail version: 1.12.1

**Comment by nimasmi** [comment]
Discovering this came about from a use case where we _wanted_ to be able to set extra restrictions on child pages, so personally the implementation is correct, but the admin form is wrong. Changing it the other way round (making the implementation match the admin's reporting) would be a worse step, I think.

**Comment by thorink** [comment]
We also have this problem where we want to further restrict the access for subpages.

We have a menu entry "Intern" which we don't want to show to the public audience. This page has the `LOGIN` restriction. Further down we have different sub pages that have further restrictions based on the users groups. I think this scenario is quite common, so I would argue that the bug is in the admin form (like @nimasmi).

I would like to try to fix this issue, but first I want to know if a pull request that solves this issue in the described way would have a chance to be accepted.

**Comment by thorink** [comment]
@nimasmi Do you have a workaround other than

- moving the page to a unrestricted place
- modifying restriction of subpage
- and moving back again?

**Comment by nimasmi** [comment]
@thorink I was reporting the issue on behalf of a colleague, after she found it and we discussed it together. I don't remember her use case, and I don't have a fix myself. I was arrogantly leaving it in the hands of the Wagtail team.

**Comment by alxbridge** [comment]
This is particularly an issue for intranet sites, where access to any page is restricted to authenticated users, and where you want access to subsections of the content to be restricted further (e.g. by group).

I agree with @nimasmi's assessment that the desired behaviour is to allow the admin form to augment a page's inherited permissions.

**Comment by laymonage** [comment]
There is now a PR for this that is awaiting review: #12124
