### ISSUE TITLE
Embedded video iframe markup and w3c standard

### ISSUE THREAD

**Issue by jossingram** [wagtail/wagtail#4283]
### Issue Summary

Markup produced when embedding a video produce an iframe tag with parameters that cause W3C validation errors

<iframe width="480" height="270" src="https://xxxxxx" frameborder="0" gesture="media" allowfullscreen></iframe>

gesture and  frameborder are the offending ones.

Could a way be added to control which attributes are added to an iframe?

### Steps to Reproduce

Add a video in editor or SF block

### Technical details

* Django version: 1.10.5
* Wagtail version: 1.12.3
* Browser version: Chrome

**Comment by SalahAdDin** [comment]
@jossingram You can use `wagtail-embedvideos` for it, i use this markup. My forks is so long updated.

**Comment by jossingram** [comment]
Thanks, I'll take a look

**Comment by gasman** [comment]
Related: #4203
The HTML we embed comes directly from Youtube's oembed endpoint, and unfortunately Youtube doesn't seem to provide any suitable options for customising this.
