### ISSUE TITLE
IE11 & MS Edge - Remove focal area of images does not work

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#4284]
### Issue Summary

Tested while working on #3771. In IE11 and MS Edge, it's impossible to remove the focal area of an image. On click, the focal area cropper disappears, but after hitting "Save" and loading the image editor again it's still there.

### Steps to Reproduce

1. Open the image editor.
2. Add a focal area, hit "Save", go to the editor again, see the focal area is there.
3. Click "Remove focal area". See the image crop mask disappear.
4. Hit "Save", go to the editor again, see the focal area is still there.

### Technical details

* Wagtail version: 2.0b1, and 1.13 with #3942 (https://bakerydemo-thibaudcolas2.herokuapp.com/), but I think this has been there since forever.
* Browser version: IE11, MS Edge 16

---

I think the issue is likely client-side, here: https://github.com/wagtail/wagtail/blob/c7a418b1c360204ab8393386a2dd72312e21993a/wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js#L78-L88

From my testing, the `removeAttr` calls do remove the `value` attribute from the HTML, but inspecting the fields with `document.querySelector('.focal_point_x').value` (or equivalent) afterwards shows the value is still there. Using `document.querySelector('.focal_point_x').value = ''` instead seems to do the trick.

**Comment by jjanssen** [comment]
Thanks! Merged with 6126510
