### ISSUE TITLE
Ability to add child pages from menu

### ISSUE THREAD

**Issue by bmoe872** [wagtail/wagtail#4286]
### Not a bug - Feature Request
When in the file explorer window it would be nice to be able to add child pages in that menu. Maybe a little plus icon that just brings you to the add child page.

**Comment by thibaudcolas** [comment]
Hey @bmoe872, thank you for the suggestion.

I think we might have considered this during the last explorer overhaul about a year ago. Initially you were only able to access the page or dive deeper, there wasn't even an "Edit" button. We were a bit worried that having too many actions would clutter the UI. You may be able to find traces of this in #2297 or #3012.

Anyway, if you think it's worth implementing – would you be keen to make a design or code prototype of this? It's more likely to happen if you kickstart the work a bit further.

**Comment by gasman** [comment]
Closing in favour of #4658 which has further discussion / mockups.
