### ISSUE TITLE
get_admin_display_title ignored in ordered list display

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#4300]
### Issue Summary

When choosing order by order in PageAdmin, get_admin_display_title is ignored.

### Technical details

* Wagtail version: 1.13.1
![default](https://user-images.githubusercontent.com/8074866/36340232-0aa4701e-13d9-11e8-84ed-584b53344b15.jpeg)
![ordered](https://user-images.githubusercontent.com/8074866/36340238-116968dc-13d9-11e8-8d17-c32b707347b0.jpeg)

**Comment by loicteixeira** [comment]
This happens because the specific version of the pages isn't retrieved when in ordering mode because it is not paginated and could be expensive.

https://github.com/wagtail/wagtail/blob/5300b01fc4b797e355e1d08b6805b5ce5f8c45bd/wagtail/admin/views/pages.py#L77-L85

**Comment by robslotboom** [comment]
I’ll wait and see,

Thanks

**Comment by gasman** [comment]
Have proposed a partial fix in #4410 - adding the `specific()` when there are less than 100 items.

**Comment by chosak** [comment]
The fix in #4410 has been merged and custom `get_admin_display_title` methods will now be used when ordering as long as fewer than 100 pages are being sorted (this limit was chosen to avoid performance issues on extremely large querysets).
