### ISSUE TITLE
Perm checking consistency

### ISSUE THREAD

**Issue by sebrestin** [wagtail/wagtail#4305]
### Issue Summary

page_listing_more_buttons hook uses both page and page_perms to check for permissions. To keep it consistent I suggest only page_perms.page_is_root should be used.

### Technical details

* Python version: 3.6.6.
* Django version: 1.11.
* Wagtail version: 1.13.1.
* Browser version: Firefox 58.

**Comment by gasman** [comment]
Fixed in #4326
