### ISSUE TITLE
Streamfield json outputs int pks even when dumpdata uses natural keys

### ISSUE THREAD

**Issue by stuaxo** [wagtail/wagtail#4317]
I hit this when trying to restore a db backup of pages from my remote server onto a fresh db locally.

I ran migrations on the local server and then attempted loaddata.

Because I had added a new app 'info' after the others, my contenttypes got out of wack when trying to do a restore.

My first attempt to get round this was to use natural keys when exporting.   This didn't work, probably because the keys inside the json from Streamfield don't use natural keys.

After many tries, I got things working by:

Commenting out the newly added app from my settings
Running migrations
Re-adding my new app to settings
Running migrations again

At this point I verified the contenttypes had been created in the same order (and had the same ids) as the remote server by looking at ```[(ct.id, ct.app_name) for ct in ContentTypes.objects.all()]```

I loaded my data and everything was OK.

If the Streamfield JSON understood --natural-foreign / --natural-primary things probably would have worked earlier.

Really, I think this is a django bug - and that it's migrations should preserve the order of app creation and respect it when re-running them, but understanding natural keys would probably be enough for wagtail to work here.

**Comment by gasman** [comment]
Possibly related to / duplicate of #2218?

**Comment by stuaxo** [comment]
Not sure, I'll need to see what happens to images, at the moment I assumed they were not working because I hadn't fixed up the urls.

**Comment by stuaxo** [comment]
I'm going to close this for now, since I don't think I have enough useful info to reproduce this.   I don't *think* it's a dupe of the other bug, having read it.

If I get some time to look at getting data / in-out of my site - I'll try testing this again + see if I can generate some usable info.

The main thing I'd probably try is adding + apps, because of the way ContentTypes works, these often end up in the middle of the list, pushing the remaining ids up.
