### ISSUE TITLE
Uncaught error when deleting ‘protected’ image

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#4323]
### Issue Summary

When an image is defined in a model as models.PROTECT. Deleting the image results in a server error 500.

### Steps to Reproduce

Create a model with an image field:

image = models.ForeignKey(
		'wagtailimages.Image',
		on_delete = models.PROTECT,
		related_name = '+',
	)

Ad an instance for this model and choose an image.
Go to Images and delete the image.

Something like this will be produced in the log:
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'Image' because they are referenced through a protected foreign key: 'SomePage.image'", <QuerySet [<SomePage: Tand des tijds>]>)

### Technical details

Python 3.6.4
Django 1.11.10
Wagtail 1.13.1

**Comment by gasman** [comment]
Hi @robslotboom - thanks for the report. This is covered by #1602, and there's a pull request #3961 awaiting review which will hopefully make it into Wagtail 2.1.
