### ISSUE TITLE
Update datepicker to 2.5.18 to fix CSP errors due to eval()

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#4329]
Would it be possible to switch from the current jquery datepicker for page live/expiry datetime to a non-jquery library that doesn't rely on arbitray code execution? Right now wagtail requires running with `unsafe-eval` turned on for script CSP, which for production websites is an incredibly dangerous setting to have to enable.

This affects both 1.* and the just released 2.0

**Comment by thibaudcolas** [comment]
Hey @Pomax, I see you've commented on #1288 as well – do you think the datepicker in particular is worth a separate issue? As far as I can see removing `unsafe-eval` would also require some work on the modal choosers for links/images/embeds/docs as well:

https://github.com/wagtail/wagtail/blob/e1325ed4d6c9e53a636d9a4fd906a6d95eefea88/wagtail/admin/static_src/wagtailadmin/js/modal-workflow.js#L54-L58

(and also on [this](https://github.com/wagtail/wagtail/blob/c7a418b1c360204ab8393386a2dd72312e21993a/wagtail/admin/static_src/wagtailadmin/js/vendor/jquery.iframe-transport.js#L209), which I don't even know what it's used for)

-----

I think we would be keen to replace the datepicker with one that's more CSP friendly if someone takes on the challenge. Same for the chooser modals, although this is more likely to happen for other reasons than just CSP.

If you can't wait for those things to happen, an alternative would be to serve the site’s back-end from a different origin than the front-end. This way you can have different CSPs for both.

**Comment by gasman** [comment]
Note that there's been quite a lot of work (e.g. #2983) invested in making the current date picker work correctly with Django date formats, including custom / localised ones, so it's probably not going to be as simple as dropping in a new datepicker widget.

In fact, it looks like the offending `eval`s are part of a sub-library that deals with date string formatting and parsing - I'd be happier if we could find (or make) a direct functional replacement for that one component, as that'll give us more confidence that we're not introducing any regressions.

**Comment by Pomax** [comment]
Maybe, but I just dropped in 2.5.18 rather than 2.3.8, which does not rely on `eval()`, and I am no longer seeing CSP issues but do see a perfectly working calendar widget for page publish/expiry, so it's probably worth simply doing a version bump for it and have that automatically solve this particular CSP issue.

**Comment by thibaudcolas** [comment]
@Pomax that sounds great! Could you make a PR for this, highlighting the changelog in that version range?

**Comment by Pomax** [comment]
I'm not sure what the best way to do a version bump is - is there a file similar to requirements.txt that list the vendor dependencies, or should I just update the actual file itself and then file that as PR?

**Comment by thibaudcolas** [comment]
New dependencies are managed with `npm` and the `package.json`. This one dependency is still vendored, so all you need to do is replace the file in https://github.com/wagtail/wagtail/tree/master/wagtail/admin/static_src/wagtailadmin/js/vendor.

(I would _love_ to see those vendored dependencies move to the npm + Webpack build process as well, but that's for another time).

**Comment by gasman** [comment]
Digging through the git history of that file, it looks like the only customisation we've made is https://github.com/wagtail/wagtail/commit/87a7a798c9a4fd9d0036e16c55546c40cf53700d, so as long as that's kept in place we should be good to go.

**Comment by Pomax** [comment]
Is there a test case that verifies that patch "works"? If so, it's worth seeing if 2.5.18 also inherently fixes the problem that patch was for (I mean, it's of course worth seeing even if there is no test case, but if there is automation available here that makes things a lot easier =)

**Comment by Pomax** [comment]
(also was that patch for datetimepicker an-sich or specific in wagtail? Because it's probably worth filing an upstream PR to get that fixed for everyone and then the manual patching won't be necessary anymore here)

**Comment by Pomax** [comment]
@thibaudcolas I've filed a PR that rolls the datetimepicker forward with a line in the changelog, let me know if there's anything I can do in that PR as needed =)
