### ISSUE TITLE
If a user logs in to a protected section then logs into the admin, their login to the admin will expire at the end of the browser session

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#433]
This is because front-end permissions (page privacy) tells the session cookie to expire at the end of the browser session when they first log into a protected section.

**Comment by davecranwell** [comment]
@kaedroho @gasman @tomdyson Is there an obvious route to closing this? Do we have any plans to resolve it?

**Comment by gasman** [comment]
No and no. It's a genuine bug, but it's an exceptionally minor one relative to what would be involved in fixing it (as far as I can see - it would require re-engineering Django's session mechanism to support simultaneous sessions using multiple cookies with different expiry dates). Perhaps we need a 'low priority' milestone / label...

**Comment by davecranwell** [comment]
I can't imagine us ever willingly deciding to set aside time to re-engineer something that fundamental so I think even "low priority" is slightly kidding ourselves. 

Is having to log in after you close your browser *that* much of a hardship? It's certainly a bug but it manifests as more of an interaction-design oddity. I vote for closure.

**Comment by thibaudcolas** [comment]
Reviewed today – unclear if this is still a thing. Possibly just for password-protected sections. Might be worth documenting and then moving on? We generally advise against password-protected page privacy generally.

**Comment by gasman** [comment]
Can confirm that this only affects shared-password view restrictions - the short-lived cookie is set [in `BaseViewRestriction.mark_as_passed`](https://github.com/wagtail/wagtail/blob/71c93cb39c2383c0d408cb2431f63ae59f4d5f2e/wagtail/models/view_restrictions.py#L74-L76), which is only called from the two 'password required' views (for pages and documents).

Can't really see what kind of documentation would make sense for this, beyond the existence of this Github issue - and given the obscurity and benign nature of the bug, difficulty in fixing it, and only affecting a semi-deprecated mode of operation, I'm making the unilateral decision to close this as wontfix.
