### ISSUE TITLE
Adding an .unpublish() method

### ISSUE THREAD

**Issue by DDiran** [wagtail/wagtail#4330]
Hi,

Wagtail `Page` models have a very handy `.publish()` method for programatically adding new pages. It would be very useful for there to be an `.unpublish()` method also. I couldn't find any reference to it in the docs.

**Comment by drunkwcodes** [comment]
Here it is.

http://docs.wagtail.io/en/stable/editor_manual/new_pages/previewing_and_submitting_for_moderation.html

http://docs.wagtail.io/en/v2.0/reference/pages/queryset_reference.html?highlight=unpublish#wagtail.core.query.PageQuerySet.unpublish
