### ISSUE TITLE
install question

### ISSUE THREAD

**Issue by JerryZhou199** [wagtail/wagtail#4338]
![default](https://user-images.githubusercontent.com/25228128/37072191-142c75d4-21fb-11e8-8440-5d220680c9db.PNG)
when I use npm install wagtail, it always has these errors, please help me to deal with it. when I use npm install other module like express, it's going to be right.

**Comment by Proper-Job** [comment]
Wagtail is a python package.  So you'll need to use pip to install it. Have a look at http://docs.wagtail.io/en/v2.0/getting_started/index.html to get started.

**Comment by JerryZhou199** [comment]
but on this page: https://github.com/wagtail/wagtail/tree/master/client
use npm install wagtail.

**Comment by thibaudcolas** [comment]
Hey @JerryZhou199, the `wagtail` package on npm is only meant for Wagtail plugin authors as a development tool. It's a work in progress and as you've seen is not usable as-is. It's also way out of date compared to what is on GitHub, so even if it was installable it wouldn't be of much use.

We don't currently support reusing those components outside of Wagtail (see #2478). If you want to reuse them anyway, your best bet is to either:

- Look for the code you're after in the repository, then copy-paste it into your project.
- `npm install` the whole Wagtail repository via git.
- Reference the Wagtail repository as a [git submodule](https://git-scm.com/docs/git-submodule).

Again, none of this is officially supported so all of these approaches will come with drawbacks, like having to install the right build tools and compiling the components.
