### ISSUE TITLE
Model class panel definition requires CSS class assignment like MultiFieldPanel

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#434]
I discovered this while trying to enhance `AbstractFormField` but realised it applies generally too.

The `panels` property of model classes that we use for inline panels isn't flexible enough for anyone who wants to progressively enhance fields in the admin interface.

I had expected the `panels` property to somewhere translate to being a "MultiFieldPanel" and therefore have the associated `classes`/`classnames` support, but it doesn't. I'd like to be able to add a class to `AbstractFormField` so that javascript could identify that particular inlinepanel and could easily show/hide some of those sub-fields depending on the user's input. (This is the easiest approach to enhancing wagtailforms which doesn't require a ground-up refactor of the whole edit handler concept.)

I'd expect this could be handy for anyone else already using the hooks to inject css/js into the editor interface. Any implementor injecting into the editor is capable of using `FieldPanel`/`MultiFieldPanel` in their models.py of course, dictating `classname` however they wish, but in this instance I needed to add a class name universally, not on a per-implementation basis.

I wonder if `InlinePanels` should more explicitly use `MultiFieldPanel` for their contents by default, rather than this slightly amorphous "other" where the list of fields isn't `single` but isn't `multiple` either.

**Comment by thibaudcolas** [comment]
I believe this has been addressed in #8921, where InlinePanel specifically uses MultiFieldPanel to render its children.
