### ISSUE TITLE
Please set up the Wagtail logo to appear as the favicon in readthedocs.

### ISSUE THREAD

**Issue by DanAtShenTech** [wagtail/wagtail#4340]
When I have multiple readthedocs tabs open side-by-side, I can't tell which tab is for which set of documentation.  [Here is an example of  a site that has done this](http://linuxmint-installation-guide.readthedocs.io/en/latest/).

**Comment by DanAtShenTech** [comment]
It would be nice if the area that is now bluish-green in the Wagtail logo was instead defined as transparent in the favicon graphic ([StackOverflow ](https://www.stackoverflow.com)and [GitHub ](https://www.github.com)are two examples).

**Comment by tomdyson** [comment]
I think I prefer the green background. It's easier to spot in my forest of tabs.
