### ISSUE TITLE
wagtail.images.views.serve.generate_signature should be relocated

### ISSUE THREAD

**Issue by declaresub** [wagtail/wagtail#4347]
I've encountered an issue with wagtail.images.views.serve.generate_signature.  When importing it into a models.py file, the class wagtail.images.views.serve.ServeView is created, which invokes a call to get_image_model, which in turn leads to a AppRegistryNotReady exception.

The functions generate_signature and verify_signature are not used at all in wagtail.images.views.serve. In fact, generate_signature is used in wagtail itself only in wagtail.images.views.images, and verify_signature is not used at all. It would make more sense to move these two functions to wagtail.images.views, or wagtail.images.utils, so that importing them does not result in the aforementioned side-effects.

One could then import these functions into wagtail.images.views.serve so as not to break existing code.

**Comment by izakp** [comment]
Same problem here - it makes it impossible to use `generate_signature` in a models.py file without using a lazy import - my use case it adding a custom property to a Model that gets an image url using `generate_signature` and returning it via an `APIField` for that model.

**Comment by zerolab** [comment]
I do not see why not move the two functions to wagtail.images.utils
You are welcome to open a pull request ;)
