### ISSUE TITLE
Update django dependency version

### ISSUE THREAD

**Issue by drunkwcodes** [wagtail/wagtail#4350]
### Issue Summary

Due to a [security update by django](https://github.com/django/django/commit/5bbbdd26d1ea4f3bb164ad64b0d0d458d8bfdd02),

install requirement for django should be updated to `~=1.11.11, ~=2.0.3` to specify the least safe versions.

After changing to this, the version range follows the old one. No new versions allowed but only stricter.

### Technical details

The line need to update: https://github.com/wagtail/wagtail/blob/master/setup.py#L24

**Comment by gasman** [comment]
Hi @drunkwcodes - thanks for the suggestion. However, in this case I think it's better to leave it as is...

Django bugfix releases are quite frequent (sometimes several times per month), and vary a lot in their severity - in the case of 1.11.11 / 2.0.3, the security fixes aren't particularly critical, as Wagtail doesn't use the affected functions. Updating the version specifier to the latest Django version would become an extra task that we'd have to do on every point release. This is something we might consider if it provided Wagtail users with significantly improved security, but I don't think it will, for a couple of reasons:

Firstly, there might be periods of several months between Wagtail point releases, and so keeping the Django version up to date on every Wagtail release wouldn't replace the need for users to keep track of Django security releases themselves if they want to stay secure.

Secondly, the version of Django installed will generally be determined by the project's requirements.txt, not Wagtail's setup.py. The version in setup.py will only be considered on a manual `pip install wagtail` command on a fresh environment, or `pip install -U` on an existing one, and in those scenarios the existing `>=1.11,<2.1` rule will give you the latest 2.0 release anyway. In fact, if setup.py ever _does_ take precedence on an existing environment, then I think there's a risk that a 1.11.10 (or earlier) project will be upgraded to 2.0 without warning, and that's something we definitely want to avoid.
