### ISSUE TITLE
Allow Documents to be viewed instead of downloaded

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#4359]
### Issue Summary

When accessing a file uploaded via Wagtail's Document manager, the file will always be downloaded. However, sometimes there is a need for a file to be viewed within the browser, instead.

### Steps to Reproduce

1. Upload a file, such as a PDF, under Documents in the admin.
2. Visit the direct link to the file. This would likely be via `{{ page.mydocfield.url }}` in practice. It will be downloaded, even if it could be viewed in the browser (such as a .pdf or .txt).

### Technical details

This is happening because of [`wagtail.documents.views.serve` L67](https://github.com/wagtail/wagtail/blob/master/wagtail/documents/views/serve.py#L67):

```python
response['Content-Disposition'] = 'attachment; filename=%s' % doc.filename
```

**EDIT:** Also [L46](https://github.com/wagtail/wagtail/blob/master/wagtail/documents/views/serve.py#L46) and [L52](https://github.com/wagtail/wagtail/blob/master/wagtail/documents/views/serve.py#L52)

Setting `attachment` here in the HTTP response asks the browser to download the file rather than view it.

My instinct about dealing with this is to have wagtail.documents.serve check for a URL param and change its behavior of it finds one, eg:

```python
if request.GET.get('view'):
    response['Content-Disposition'] = 'filename=%s' % doc.filename
else:
    response['Content-Disposition'] = 'attachment; filename=%s' % doc.filename
```

This way you could embed your file like `/documents/myfile.pdf?view` and it would cause the file to be viewed rather than downloaded.

My particular use case for this is because Project TIER would like to embed PDF files on their site, and the [normal solutions](https://pdfobject.com/static.html) for this (eg `<embed>`, `<object>`, or `<iframe>`) don't work when the linked PDF is delivered as an attachment. I imagine that other sites would like their users to view PDFs directly in the browser as well.

**Comment by alexgleason** [comment]
Actually, I did this on Project TIER:

`project_tier/core/views.py`:
```python
from wagtail.documents.views import serve


def view_document(request, document_id, document_filename):
    """
    Calls the normal document `serve` view, except makes it not an attachment.
    """
    # Get response from `serve` first
    response = serve.serve(request, document_id, document_filename)

    # Remove "attachment" from response's Content-Disposition
    contdisp = response['Content-Disposition']
    response['Content-Disposition'] = "; ".join(
        [x for x in contdisp.split("; ") if x != "attachment"]
    )

    # Return the response
    return response
```

`project_tier/urls.py`:
```python
from django.urls import include, path, re_path
# ...
from project_tier.core.views import view_document

urlpatterns = [
    # ...
    path('documents/', include('wagtail.documents.urls')),
    re_path(r'^document/view/(\d+)/(.*)$', view_document),
    # ...
]
```

and now I access viewable documents via `/document/view/<documentFilename>`.

I'm trying not to overkill a small problem, but I'm tempted to say we should provide these URLs in Wagtail:

* `/document/view/<file>`
* `/document/download/<file>`

and deprecate the plural form `/documents`. We could even add options to the page editor for embeddable vs downloadable files.

**Comment by gasman** [comment]
Thanks @alexgleason! This is covered by #1158, and partially #1420.

Having separate URLs for view and download is a really interesting idea, but I suspect it's a bit too micromanage-y for most purposes - it looks like there's broad agreement that viewing inline is the preferred behaviour for PDFs, so it would make sense to have that Just Work out of the box (and have a setting to override that if necessary).

**Comment by moises-cp** [comment]
@alexgleason 

For some reason the solution for  Project TIER did not work for me.  

Is there anything else that needs to be added in order to make this work?

**Here's the code**
`from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import include, path, re_path

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

def view_document(request, document_id, document_filename):
    """
    Calls the normal document `serve` view, except makes it not an attachment.
    """
    # Get response from `serve` first
    response = serve.serve(request, document_id, document_filename)

    # Remove "attachment" from response's Content-Disposition
    contdisp = response['Content-Disposition']
    response['Content-Disposition'] = "; ".join(
        [x for x in contdisp.split("; ") if x != "attachment"]
    )

    # Return the response
    return response

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^document/view/(\d+)/(.*)$', view_document),

    url(r'^search/$', search_views.search, name='search'),

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r"", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r"^pages/", include(wagtail_urls)),
]
`
