### ISSUE TITLE
EmbedBlock not rendering anything

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#4371]
Hiya,

I'm using wagtail 2.0 and I have a model that looks like this:

```python
from django.db import models

from wagtail.core import blocks
from wagtail.core.models import Page
from wagtail.core.fields import StreamField, RichTextField
from wagtail.admin.edit_handlers import FieldPanel, StreamFieldPanel
from wagtail.embeds.blocks import EmbedBlock

[...]

base_fields = [
    ('heading', blocks.CharBlock()),
    ('paragraph', blocks.RichTextBlock()),
    ('video', EmbedBlock()),
]

class ModularPage(Page):
    """
    The base class offers universal component picking
    """

    header = models.CharField(
        max_length=250,
        blank=True
    )

    body = StreamField(base_fields)

    content_panels = Page.content_panels + [
        FieldPanel('header'),
        StreamFieldPanel('body'),
    ]
```

But creating an instance of this modular page with a video block that has a youtube url, and using the following template, results in nothing getting templated into the page:

```
[...]

{% block html_content %}
  {% for block in page.body %}
    {% if block.block_type == 'heading' %}
      <h1>{{ block.value }}</h1>
    {% else %}
      <h4>{{ block.block_type }}: {{ block.value }}</h4>
      {% include_block block %}
    {% endif %}
  {% endfor %}
{% endblock %}

[...]
```

For the video field, this does show "Video: " but shows nothing after that, as if `{{ block.value }}` is empty or nonexistent.

The heading block works as expect, with content in `block.value`, and the paragraph block also works as expected, doing its thing based on its own block template.

**Comment by Pomax** [comment]
It turns out that while `block.value` doesn't work, `block.value.url` does work, but the documentation for embedblock does not make this clear. http://docs.wagtail.io/en/v2.0/topics/streamfield.html?highlight=embedblock#embedblock can definitely do with additional text along the line of "note that embed blocks content is stored in `block.value.url` rather than `block.value` when using custom templating"?

**Comment by G-kodes** [comment]
Documentation is also almost completely unclear on how one should go about rendering `EmbedBlock()`s rendered from inside a custom `StructBLock()` class. I am struggling as it just refuses to render anything.

**Comment by gasman** [comment]
I'm unable to replicate the original issue reported here when testing against the current main branch, starting from `wagtail start myproject` with home/models.py as follows:

```python
from django.db import models

from wagtail.core import blocks
from wagtail.core.models import Page
from wagtail.core.fields import StreamField, RichTextField
from wagtail.admin.edit_handlers import FieldPanel, StreamFieldPanel
from wagtail.embeds.blocks import EmbedBlock


class HomePage(Page):
    pass


base_fields = [
    ('heading', blocks.CharBlock()),
    ('paragraph', blocks.RichTextBlock()),
    ('video', EmbedBlock()),
]

class ModularPage(Page):
    """
    The base class offers universal component picking
    """

    header = models.CharField(
        max_length=250,
        blank=True
    )

    body = StreamField(base_fields)

    content_panels = Page.content_panels + [
        FieldPanel('header'),
        StreamFieldPanel('body'),
    ]
```

and home/templates/modular_page.html as follows:

```html+django
{% load wagtailcore_tags %}

{% block content %}
  {% for block in page.body %}
    {% if block.block_type == 'heading' %}
      <h1>{{ block.value }}</h1>
    {% else %}
      <h4>{{ block.block_type }}: {{ block.value }}</h4>
      {% include_block block %}
    {% endif %}
  {% endfor %}
{% endblock %}
```

Since this is a rather old bug report it's possible that this was fixed in the meantime, although as far as I can see EmbedBlock has used its own data type that knows its own HTML rendering ever since 1.0 (#1357), so it should never have been necessary to go into the `url` property.


Regarding an EmbedBlock in a StructBlock, it's working for me with the class definition

```python
class VideoWithCaptionBlock(blocks.StructBlock):
    video = EmbedBlock()
    caption = blocks.CharBlock()

    class Meta:
        template = 'blocks/video_with_caption.html'
```

and template

```html+django
<h2>{{ value.caption }}</h2>
{{ value.video }}
```

This follows the same pattern as [the example in the docs for a StructBlock template](https://docs.wagtail.io/en/stable/topics/streamfield.html#per-block-templates), so I'm not sure what we can usefully add to the docs there - feel free to open a new issue if you have a specific suggestion for how we could improve this.
