### ISSUE TITLE
AttributeError when trying to access a customed StructBlock class attribute from within the class

### ISSUE THREAD

**Issue by inredmood** [wagtail/wagtail#4387]
I have an AttributeError: 'CustomStructBlock' object has no attribute 'level_value' in my browser, when I try to access the level_value attribute, from a function (level_label) within the class. But the function passes the tests written in test.py successfully.

blocks.py
```
from wagtail.core import blocks

class CustomedStructBlock(blocks.StructBlock):
    LEVEL1 = 1
    LEVEL2 = 2
    LEVEL3 = 3
    LEVEL4 = 4
    LEVELS = (
        (LEVEL1, 'level one'),
        (LEVEL2, 'level two'),
        (LEVEL3, 'level three'),
        (LEVEL4, 'level four'),
    )
    level_value =  blocks.IntegerBlock(label='Level',choices=LEVELS,null=False,blank=False,default=LEVEL1)

    def get_context(self,value,parent_context=None):
        context = super().get_context(value, parent_context=parent_context)
        context['level_label'] = self.level_label()
        return context

    def level_label(self,levels=LEVELS):
        for level, label in levels:
            if self.level_value == level:
                return label

    class Meta:
        template = 'myapp/customed_struct_block.html'
        icon = 'placeholder'
        label = 'CustomedStructBlock'
```

tests.py
```
from django.test import TestCase
from wagtail.core import blocks
from . import blocks as customblocks

class CustomedStructBlockTestCase(TestCase):

    def setUp(self):
        self.customed_block = customblocks.CustomedStructBlock()
        self.customed_block.level_value = 2

    def testLevelLabel(self):
        self.assertEqual(self.customed_block.level_label(),'level two')

    def testGetContext(self):
        context = self.customed_block.get_context(None)
        self.assertTrue('level_label' in context)
        self.assertEqual(context['level_label'],'level two')
```

models.py
```
from django.db import models

from wagtail.core.models import Page
from wagtail.core import blocks
from wagtail.core.fields import RichTextField, StreamField
from wagtail.admin.edit_handlers import StreamFieldPanel

from . import blocks as customblocks

class CustomedPage(Page):

    introduction = StreamField([
        ('custom',customblocks.CustomedStructBlock())
    ])

    content_panels = Page.content_panels + [
        StreamFieldPanel('introduction')
    ]
```

customed_struct_block.html
```
<div>
  <p>{{ level_label }}</p>
</div>
```

customed_page.html
```
{% extends "base.html" %}

{% load staticfiles %}
{% load wagtailcore_tags wagtailimages_tags %}

{% block body_class %}template-blogindexpage{% endblock %}

{% block content %}
    <div class="row">
      {% for block in page.introduction %}
        {% include_block block %}
      {% endfor %}
    </div>
{% endblock %}
```

### Technical details

* Python version: 3.6
* Django version: 2.0.2
* Wagtail version: 2.0
* Browser version: Firefox Quantum 59.0

**Comment by gasman** [comment]
Hi @inredmood,
Block objects such as `StructBlock` do not hold values; they simply define how values are converted between different representations. They work a lot like Django's form field objects; for example, Django's `forms.CharField` and Wagtail's `CharBlock` both define how to render a string as a form field, and how to retrieve a string from a form submission.

Note that `CharBlock` works with string objects - _not_ instances of `CharBlock`. In the same way, the values returned from `StructBlock` are not instances of `StructBlock` - they are a dict-like object `StructValue`. As a result, defining a method or setting a property on a `StructBlock` subclass won't do what you think it does... Instead, you need to define a subclass of `StructValue`, following the example at http://docs.wagtail.io/en/v2.0/topics/streamfield.html#custom-value-class-for-structblock.

**Comment by inredmood** [comment]
Thanks for the explanation, it solved my problem.
