### ISSUE TITLE
Affordance between small buttons, status tags and clickable meta toggles

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#439]
![screen shot 2014-07-08 at 14 48 07](https://cloud.githubusercontent.com/assets/352835/3510406/66358d76-06a6-11e4-9200-400ed8298152.png)

![screen shot 2014-07-08 at 14 51 10](https://cloud.githubusercontent.com/assets/352835/3510441/cae1c924-06a6-11e4-93cd-c59667908d94.png)

The status tags, toggles and button styles have been developed independently but now don't work so well together. There's a sea of stroked boxes going on. 

There are three pieces of UI where a the stroked box design is reused:
1. Small buttons: as in the explorer or as in the page/image/document/snippet chooser interfaces. 
2. A status indicator: the live/draft/live+draft indicators in the explorer (these _can_ be clicked to see the live/draft preview but this functionality is discoverable, not key)
3. The privacy indicator constitutes a third UI component. Its original design had even less affordance, so it was given the stroked design as an interim measure which didn't help matters:
4. A non-interactive key/value piece of meta information e.g what kind of content type it was, or the date the page was first created.

**Comment by thibaudcolas** [comment]
We’re completely redesigning this this year, so I don’t think the feedback here is still relevant – closing.
