### ISSUE TITLE
more get_admin_display_title not honored

### ISSUE THREAD

**Issue by Speedy1991** [wagtail/wagtail#4396]
Same setup like #4353   with similar bug:
[here](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/templates/wagtailadmin/pages/listing/_page_title_choose.html) and [here](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/templates/wagtailadmin/pages/listing/_page_title_explore.html) and [here](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/templates/wagtailadmin/pages/listing/_page_title_move.html)

Bug:
`page.get_admin_display_title`
Fix:
`page.specific.get_admin_display_title`

Added fixes to existing PR #4354

**Comment by gasman** [comment]
Hi @Speedy1991 - are you sure these are needed? We already call `specific()` on the queryset, inside the view function (except for the 'reorder' view, where it's disabled for performance reasons):
https://github.com/wagtail/wagtail/blob/72e1491f393de6c579595433f4f962c9771ffc0f/wagtail/admin/views/pages.py#L85

(Calling `specific()` on a queryset is a bit more efficient than calling it on an individual page, as it means that multiple pages of the same type are combined into one query.)

**Comment by Speedy1991** [comment]
well, i needed it in the reorder view, due to translated equal titles. E.g:
```
Github
Github
Github
```

I don't get different language codes (defined in `get_admin_display_title`) so i don't know which one is which.

With the fix i get something like this:

```
Github[en]
Github[de]
Github[es]
```

And i know what i just reordered

```
Github[de]
Github[es]
Github[en]
```

**Comment by gasman** [comment]
Fixing this for the reorder view is covered by the existing ticket #4300 - have now proposed a partial fix (avoiding the performance issue of calling `specific()` on very large querysets) in #4410.
