### ISSUE TITLE
Style guide template closing tags mismatch

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#4399]
# Summary
The style guide template at `wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html` is not correctly formatted. There are `td` and `p` tags that are not closed. That is only the beginning: w3c validator reports 31 errors.

I'd also like to rewrite `<img src="{% gravatar_url "david@torchbox.com" %}" />` =>  `<img src="{% gravatar_url 'david@torchbox.com' %}" />`. Single and double quotes makes these tags more legible.

# Steps to reproduce
1) Follow instructions on adding the styleguide http://docs.wagtail.io/en/v2.0/contributing/styleguide.html
2) Lookup the source copy paste in https://validator.w3.org/
3) See errors

**Comment by thibaudcolas** [comment]
👍 there should be no validation errors on any part of Wagtail, including this. For the img tag rewrite – agreed.

**Comment by BertrandBordage** [comment]
Closed by #4400.
