### ISSUE TITLE
FEATURE REQUEST:  Provide for Entry of title and target attributes on links

### ISSUE THREAD

**Issue by DanAtShenTech** [wagtail/wagtail#4405]
Currently, only the text and the url may be specified for a link that is included in a `RichTextField` or `StreamField`.  I would like the link dialog to also include a field for title text as well as a checkbox to provide for opening the link in a new tab.

**Comment by thibaudcolas** [comment]
Hey @DanAtShenTech, adding the target attribute is already covered by #1167.

For the title text, generally I think this is a bad idea. If provided on links it can be harmful to the accessibility of the content, for little benefit. I'll close this now, but you're welcome to open a separate issue to make your case if you want to. For feature requests, I'd suggest spending significant time describing what you're after, with examples. Usually the longer the better.
