### ISSUE TITLE
Implement a ModelChoiceBlock block type

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#4407]
Wagtail currently does not provide a StreamField block equivalent of Django's ModelChoiceField (for giving the user a dropdown of model instances to choose from). People often try using the undocumented internal `ChooserBlock` class for this purpose, but this was only designed for use with our modal choosers (`AdminPageChooser` etc) and can't be relied on to work correctly with a basic `Select` widget; consequently, various PRs have been submitted to fix or extend this functionality (#2714, #3169, #4157, #4351, #4380).

Rather than trying to patch `ChooserBlock` to work with the `Select` widget, I propose that we introduce a new `ModelChoiceBlock`, for the following reasons:

* Consistency with Django's naming scheme
* Where the API of our modal chooser widgets differs from the `Select` widget, we don't have to fudge a single implementation that handles both cases, and may end up being non-optimal with modal choosers. (For example, see https://github.com/wagtail/wagtail/pull/3169#issuecomment-262815168 - our modal widgets are most efficient when the render method receives a model instance, rather than an ID, and the `bulk_to_python` optimisation relies on us being able to do this. However, the `Select` widget only accepts the ID.)
* It avoids creating the expectation that `PageChooserBlock` etc will support all options and functionality of `ModelChoiceBlock`; for example, the modal choosers can't realistically support custom `get_queryset` methods (without a LOT of extra development).

The new `ModelChoiceField` will need documentation, and tests for all methods (to cover all relevant round-trips between database, form and front-end representations); it should also implement a `get_queryset` method as per #4351. `ChooserBlock` might possibly be refactored as a subclass of `ModelChoiceField`, depending on whether there's enough shared logic to make it worthwhile; either way, it should remain as an internal-only class existing for the benefit of `PageChooserBlock` etc.

**Comment by thibaudcolas** [comment]
This sounds like the following packages:

- https://github.com/springload/wagtailmodelchoosers
- https://github.com/Naeka/wagtailmodelchooser
- https://github.com/takeflight/wagtailmodelchooser

I'm not sure how relevant these are compared to your proposed implementation (I'd expect those packages to do much more UI-wise) but thought it would be worth highlighting.

**Comment by gasman** [comment]
Thanks @thibaudcolas! For now my main concern is getting something working with a basic select dropdown, since that's a setup that people are regularly trying to implement (not entirely successfully...) with `ChooserBlock`. A modal chooser for arbitrary models is definitely on the wishlist too (although I'm keen that we should do it in a way that integrates cleanly with modeladmin and/or wagtailadmin itself, rather than adding to the pile of partially-overlapping generic-models-in-wagtail-admin solutions)...

**Comment by pySilver** [comment]
Here is the working code for both `ModelChoiceBlock` and `ModelMultipleChoiceBlock` that uses `Select2` widgets from https://github.com/yourlabs/django-autocomplete-light

https://gist.github.com/pySilver/a2b17f8cb42c18b5c4f2976f2a65b5e2

Usage:

```python
brand = ModelChoiceBlock(
        label=_("Brand"),
        target_model="brands.Brand",  # or model 
        required=False,
        to_field_name="slug",
    )
```

or 

```python
brand = ModelChoiceBlock(
        label=_("Brand"),
        queryset=Brand.objects.all(),  # or callable that returns queryset
        required=False,
        to_field_name="slug",
    )
```

**Comment by pySilver** [comment]
to anyone interested: feel free to form a proper PR out of this code or form a separate package. I'm in deadline rush at the moment. :(

**Comment by dwasyl** [comment]
While it's been a while, this would still be a very useful model to include in Wagtail. My own inheritance of a `ChooserBlock` that was working since the 1.x days, seems to finally no longer work in version 4.x.

**Comment by zerolab** [comment]
@dwasyl https://docs.wagtail.org/en/stable/extending/generic_views.html and in particular https://docs.wagtail.org/en/stable/extending/generic_views.html#chooserviewset should make this a much nicer experience. Have you seen/tried that?

**Comment by merwok** [comment]
This project still works with wagtail 5.2: https://github.com/neon-jungle/wagtailmodelchooser

It could get some polish: translating strings, better docs for customization
and also better/easier customization: support multiple objects, support defining queryset and not just model

**Comment by gasman** [comment]
ChooserViewSet is Wagtail's native solution for this now.

**Comment by merwok** [comment]
Related question: I found the docs explaining how to add filters (on related objects) to a viewset (more involved that one would expect!), but it does not seem to apply when using get_block_class to use with a streamfield. Is it supported?

Also, is there something to add a search field on a specified field (not related object)?
