### ISSUE TITLE
Menu icon overlaps with title in modeladmin on mobile

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#4412]
The menu icon overlaps with page title in model admin on mobile.

Steps to Reproduce:
1. Open a model admin.
2. Create a small 'mobile' viewport.
3. See the overlap.

Expect that there is a margin between menu icon and title.

Technical details: Wagtail 2 / Google Chrome

<img width="969" alt="overlap" src="https://user-images.githubusercontent.com/1969342/37736918-7fe117be-2d52-11e8-92ca-76c1fe7f15e0.png">

**Comment by jjanssen** [comment]
Thanks for reporting! Remember seeing something similar while back: #3703

Dropping this here as a reference.

**Comment by jjanssen** [comment]
Thanks! Merged with 3bcefe3
