### ISSUE TITLE
Hard coded link in 404 template

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#4417]
The 404.html template in wagtail/admin/templates/wagtailadmin/ has a hard coded link.

In {% block furniture %}:
 
`
<a class="page404__button button" href="/admin/">{% trans "Go to Wagtail admin" %}</a>
`

Wagtail 2.0

**Comment by thibaudcolas** [comment]
Hey @robslotboom, thank you for reporting this. Could you submit a PR with the fix?

**Comment by robslotboom** [comment]
Hey @thibaudcolas, I’ll look for a workable sollution.

**Comment by thibaudcolas** [comment]
Well, seems like it was fixed in #4419 🙂.
