### ISSUE TITLE
visual glitch on http://docs.wagtail.io/en/v2.0/

### ISSUE THREAD

**Issue by sir-sigurd** [wagtail/wagtail#4423]
![image](https://user-images.githubusercontent.com/481910/37866775-04fece72-2fb1-11e8-9f16-48a937d6a22b.png)
Only documentation for 2.0 is affected.

It seems that it can be solved by setting `background-color` on `body` instead of `html`.

**Comment by thibaudcolas** [comment]
Hey @sir-sigurd, thanks for the report. Could you try your proposed fix and submit a PR?

**Comment by jjanssen** [comment]
Fixed with #4423 and merged with 63e824f
