### ISSUE TITLE
Cannot create image in link with DraftTail

### ISSUE THREAD

**Issue by k0rmarun** [wagtail/wagtail#4428]
### Issue Summary

Cannot create a link which contains an image instead of/additional to text

### Steps to Reproduce

1. Create image
2. Select image
3. Create link on image

Expected: Image with link (```<a href='other.html'><img src='image.png'/></a>```)
Actual: Link without image (```<a href='other.html'></a>```

Second Option:

1. Create Link
2. Navigate into link text
3. Create image

Expected: Image with link (```<a href='other.html'>Before<img src='image.png'/>After</a>```)
Actual: Image than link (```<img src='image.png'><a href='other.html'>BeforeAfter</a>```)
### Technical details

* Python version: Python 3.5.2
* Django version: 2.0.3
* Wagtail version: 2.0
* Browser version: Firefox 59.0.1

**Comment by thibaudcolas** [comment]
Hey @k0rmarun, thank you for the report. Note that the new editor is called `Draftail` (from Draft.js), not DraftTail.

Adding links on images is not supported. See also #3023. With the steps you reproduce, adding a link on an image like you tried should simply remove the image, and adding an image on a link should split the link in two and add an image in-between. This should all be visually understandable without looking at the HTML output.

---

I'll close this now – if you need links on images for your work I'd suggest the same as https://github.com/wagtail/wagtail/issues/3023#issuecomment-360830635: use StreamField to define some sort of ImageWithLink block (or potentially `ImageWithTextAndLink`) – you'll get much more control over the editing UI and final output this way.
