### ISSUE TITLE
Handling large image galleries

### ISSUE THREAD

**Issue by chrisbarry** [wagtail/wagtail#4429]
I'm just wondering if this is the right place to put discussion like this?

https://groups.google.com/forum/#!topic/wagtail/E6L6LeQLUgU

Let me know if I should move the feature discussion over here?

**Comment by thibaudcolas** [comment]
Hey @chrisbarry,

I think this would be considered a support request, which we [don't want the issue tracker to be for – it's not the right format for those discussions](https://github.com/wagtail/wagtail/blob/master/CONTRIBUTING.md#using-the-issue-tracker), so I'll close this now.

Looking at your post, I can see that you've spent some time to highlight potential improvements with Wagtail. What you're solving seems quite big so I'd suggest for you to open-source it as a third-party app that works with Wagtail – it's quite a bit of effort, but it's the best way to gather feedback from others (people like to try out running code, and see demos). Then, it will be much easier for us to consider changes to Wagtail that would make building those types of feature easier – or even further, to have those features directly in Wagtail.

I hope this helps.

**Comment by chrisbarry** [comment]
Thanks for the response. Makes sense as a way to proceed.
