### ISSUE TITLE
PROBABLE BUG:  Second user's info replaces admin (first) user's info when editing admin user in Wagtail admin

### ISSUE THREAD

**Issue by DanAtShenTech** [wagtail/wagtail#4437]
### Issue Summary

After adding a second user via Django admin, when the admin (first) user is edited in Wagtail admin, the first user's information flashes up and is then replaced by the second user's information.

### Steps to Reproduce

1. After setting up a project with an admin user, create a second user via the Django admin.  Do not assign this user to any Wagtail groups.
2. Refresh the Wagtail admin -> settings -> users page in order to see the newly created user in the list of users.
3. Click on the first (admin) user in order to edit it.
4. Behavior described above occurs.

### Technical details

* Python version: 2.7.12
* Django version: 1.11.11
* Wagtail version: 1.13.1
* Browser version: Chrome 65

**Comment by gasman** [comment]
Unable to replicate this on a fresh Wagtail install. Since there's no Javascript on this form that would cause the field values to change after page load, I suspect this is something misbehaving at the browser's end (perhaps a password manager extension?)
