### ISSUE TITLE
Built-in command `remove_stale_contenttypes` removes `wagtail_admin` permissions

### ISSUE THREAD

**Issue by emorozov** [wagtail/wagtail#4444]
### Issue Summary

When running `remove_stale_contenttypes` it offers to remove `wagtail_admin.admin` content type and all related permissions and all assigned permissions making access to Wagtail admin impossible to anyone but superuser.

### Steps to Reproduce

Run `./manage.py remove_stale_contenttypes`. It will offer:

```
Some content types in your database are stale and can be deleted.
Any objects that depend on these content types will also be deleted.
The content types and dependent objects that would be deleted are:

    - Content type for wagtailadmin.admin
    - 1 auth.Permission object(s)
    - 2 auth.Group_permissions object(s)

This list doesn't include any cascade deletions to data outside of Django's
models (uncommon).

Are you sure you want to delete these content types?
If you're unsure, answer 'no'.
Type 'yes' to continue, or 'no' to cancel:
```

### Technical details

* Python version: 3.5.3
* Django version: 2.0.3
* Wagtail version: 2.0

I suggest using more robust way of creating `wagtail_admin` content type because it is very easy to miss and accidentally remove it along with the permissions if there're lots of stale content types and you just type `yes` to all questions thinking that there're no content types that are actually used by the project.

Maybe there should be a model in Wagtail or wagtailadmin permissions should be tied to some existing model, like `Page`, so that Django doesn't consider wagtailadmin content type unused, stale and safe to remove.

**Comment by gasman** [comment]
For anyone who's encountered this, you can restore the missing permission types by running the following from the `./manage.py shell` command line:

    from django.contrib.contenttypes.models import ContentType
    from django.contrib.auth.models import Permission
    wagtailadmin_content_type, _ = ContentType.objects.get_or_create(app_label='wagtailadmin', model='admin')
    Permission.objects.get_or_create(content_type=wagtailadmin_content_type, codename='access_admin', name='Can access Wagtail admin')

**Comment by adsk2050** [comment]
I faced the same issue, but I never tried the remove_stale_contenttypes command. I have implemented a CustomUser model though. I am trying to find the steps to reproduce. But for sure this issue is deeper than this. Will update once I find the problem

**Comment by richkirsch** [comment]
Would be great to see this fixed. Running `remove_stale_contenttype` is useful in many automated deployment scenarios.

As it stands this issue leads to an extremely opaque debugging problem ... I was relieved to find this thread.

**Comment by berekuk** [comment]
This can be fixed with auxiliary unmanaged model just for permissions.

Details: https://stackoverflow.com/questions/13932774/how-can-i-use-django-permissions-without-defining-a-content-type-or-model/37988537#37988537
