### ISSUE TITLE
feature request: duplicate button for streamfield fields

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#4451]
Is it possible to get an extra button added to the streamfield field options, where it's currently the reorder arrows and the delete button, to duplicate a streamfield field? Especially for richtext fields, where copy/paste has a fair number of bugs that prevent all the markup from surviving a copy-paste attempt, having a duplicate button would be super valuable (there are other use-cases too but that seemed the most obvious one)

**Comment by BertrandBordage** [comment]
Hi @Pomax, this is one of the focuses of the main goal of [Wagtail’s first Kickstarter campaign](https://www.kickstarter.com/projects/noripyt/wagtails-first-hatch) by NoriPyt ;)

**Comment by Pomax** [comment]
Interesting! is this a collab with the wagtail folks, or purely "if you do it well will look at how to best merge it in"?

**Comment by BertrandBordage** [comment]
As part of the Wagtail’s first Kickstarter campaign, I’m working on this!
https://www.kickstarter.com/projects/noripyt/wagtails-first-hatch

**Comment by gasman** [comment]
Now implemented as part of the Streamfield rewrite in 2.13.
