### ISSUE TITLE
Update html5lib to allow 1.0.0+

### ISSUE THREAD

**Issue by overshard** [wagtail/wagtail#4454]
Trying to lock my current dependencies with pipenv and running into an issue that my other libraries all use html5lib 1.0.1 and wagtail requires <1. I'm not sure if this is still needed or just because of 1.x beta issues with html5lib.

**Comment by gasman** [comment]
Excellent, I somehow missed the fact that html5lib finally has a release with a sensible version number 😄 Dependency now updated in 8abceeb166a294ece30dbe4579347142cdda85c7.
