### ISSUE TITLE
'Add user' button label is trimmed when translated using single quotes

### ISSUE THREAD

**Issue by benoitvogel** [wagtail/wagtail#4455]
### Issue Summary

The 'Add user' button has an incorrect label in the Roles selection page when language is set to French (might as well be relevant for other languages).

### Steps to Reproduce

On a fresh Wagtail setup with French language (LANGUAGE_CODE = 'fr-fr'), go to Settings (Paramètres) > Add a user (Ajouter un utilisateur) > Roles tab (Rôles).
On this page the _Add user_ button should be translated as _Ajouter l'utilisateur_ but the label reads _Ajouter l_

The PO file from Transifex has the right translated string in it but the problem lies in the {% trans %} template tag:
 `<input type="submit" value='{% trans "Add user" %}' class="button" />` 
Adding the `|force_escape` filter to this string converts the single quote to its HTML entity equivalent, thus rendering the button correctly by avoiding the value attribute to be closed prematurely.

### Technical details

* Python version: 3.4.3
* Django version: 2.0.4
* Wagtail version: 2.1a0 (official master)
* Browser version: Firefox 59

**Comment by jjanssen** [comment]
Thanks! Merged with 9a21060
