### ISSUE TITLE
how to migrate a block redefinition

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#4459]
Our codebase has several Blocks that all relied on ImageChooserBlock, but got rewritten to now use a custom SizedImageBlock, which itself relies on ImageChooserBlock values. In concept, this is a straight forward change:

```
before: { image=ImageChooserBlock }
after: { image=ImageBlock(StructBlock){image=ImageChooseBlock, size=..., ...} }
```
however, because blocks aren't foreign keys to their own table, there does not seem to be an easy way to effect a traditional forward/backward migration function that takes that top level `image` field using the old model in the db, and then copies it one level deeper using the new model.

What's the correct way to make sure a migration like this doesn't lead to every image on every page getting lost? =)

(Is there a streamfield equivalent to app.get_model that can be used to make sure stored values are migrated corrected to their new location?)

**Comment by chosak** [comment]
@Pomax there's some existing discussion of this challenge on #2110, but unfortunately the Wagtail documentation currently lacks a more formalized description of the process that's needed to do what you want. Generally, though, you'll want to create a data migration using [`RunPython`](https://docs.djangoproject.com/en/2.0/ref/migration-operations/#runpython), iterate over instances of your page model, iterate over those StreamFields on the page instance that you need to update, and manually update the block data to match the new format.

Here's some [documentation](https://cfpb.github.io/cfgov-refresh/wagtail-migrations/) and [source code](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/v1/util/migrations.py) written to tackle this same problem for another site based on Wagtail.

**Comment by Pomax** [comment]
Trying to think of ways to automate this process, out-of-bounds if necessary, is there a way to fetch the streamfield data from a database pre-migration, then just migrate "blindly" (losing fields etc) and then running a script that will repopulate the migrated table?

I tried digging around the tables but couldn't find where the streamfield data is actually kept.

**Comment by chosak** [comment]
@Pomax [here's](http://docs.wagtail.io/en/v2.0.1/topics/streamfield.html?highlight=streamfield#migrating-richtextfields-to-streamfield) some other relevant code from the Wagtail documentation which might be better/clearer at showing a migration example.

The StreamField data is stored as a JSON-like structure, so say you have a page model named `BlogPage` with a StreamField field named `body`, you'd find JSON content in, e.g. your `appname_blogpage.body` database column.

**Comment by Pomax** [comment]
Thanks.

Interestingly, I tried updating the db directly, but that did not quite have the result I expected, showing an empty body after loading a test page. Putting the "right" content in and saving then yielded exactly the same data as I'd updated, so I suspect it's doing a check against revision entries to see if the current data is valid somehow?
