### ISSUE TITLE
Can't add new icon

### ISSUE THREAD

**Issue by xiaohuanlin** [wagtail/wagtail#4463]
### Issue Summary

I followed every steps of [Wiki -->Adding new icons](https://github.com/wagtail/wagtail/wiki/Adding-new-icons) instructions. But the new icon didn't show in base.html.

### Steps to Reproduce

1. The icons I want to add are from Entypo+ set, just like this picture.
![image](https://user-images.githubusercontent.com/33860497/38591161-f1de4d76-3d67-11e8-835b-030010cc0bd4.png)
2. The hex code of these icons like this:
![image](https://user-images.githubusercontent.com/33860497/38591262-7f5cbe08-3d68-11e8-9e0f-a86cc377816d.png)
3. The code block I added to **_variables-icons.scss** just like this:
```  
    ...
    'table': '\f0ce',
    'logout': '\e901',
    'open-book': '\e902',
    'feather': '\e903',
    'mobile': '\e904',
    'youtube': '\e905',
    'location': '\e906',
);
```
4. But, the icons didn't show in the base.html:
![image](https://user-images.githubusercontent.com/33860497/38591343-ca5216e2-3d68-11e8-9500-f994cafc4848.png)

### Technical details

* Python version: 3.6.4
* Django version: django 2.0.4
* Wagtail version: wagtail 2.0
* Browser version: Chrome 65

**Comment by gasman** [comment]
Hi @xiaohuanlin,

The steps on the wiki were just intended as a reference for the core Wagtail team, and weren't intended to be user-facing documentation - as such, they're likely to be out of date. I believe the missing step is to run: `npm run build` (note, you'll need a Wagtail development environment as detailed in http://docs.wagtail.io/en/v2.0.1/contributing/developing.html#setting-up-the-wagtail-codebase).

**Comment by jjanssen** [comment]
In addition, if you would like to customize your Wagtail setup with icons, I'd suggest to take a look at [Wagtail FontAwesome](https://github.com/alexgleason/wagtailfontawesome)

**Comment by xiaohuanlin** [comment]
Thanks very much. I really appreciate what you did. This question confused me quite long time.
