### ISSUE TITLE
feature request: label for FieldPanel

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#4471]
Currently https://github.com/wagtail/wagtail/blob/master/wagtail/admin/templates/wagtailadmin/shared/field.html does not support any kind of label so FieldPanels for things like models.BooleanField look very... sparse in the admin:

![image](https://user-images.githubusercontent.com/177243/38707718-617c1e2e-3e67-11e8-9184-319a6a9de80d.png)

Even with a `help_text` set, having a real label as optional argument to FieldPanel would be quite valuable.

**Comment by Pomax** [comment]
A little wonky, but better than before.

![image](https://user-images.githubusercontent.com/177243/38831339-e80c544a-4173-11e8-9a62-37e519443f26.png)

**Comment by lb-** [comment]
**Update**

This would be a good feature to get in if possible - anyone up for a PR?

This appears to be a practical fix to scenarios such as boolean fields #4476 and also updating the labels for the core Page fields such as `seo_title` in the page editor (via a custom set of panels) #5050.

This may also provide a partial fix to some of the issues mentioned in #161

**Comment by thibaudcolas** [comment]
We’ve redesigned top-level FieldPanels in Wagtail 4, in a way that I think solves this. Here is a BooleanField in a top-level FieldPanel:

<img width="398" alt="boolean-field-label" src="https://user-images.githubusercontent.com/877585/184883187-87158ace-9386-4cf9-b18e-ea1cc937191d.png">

And a BooleanField that’s not at the top level:

<img width="177" alt="boolean-field-nested" src="https://user-images.githubusercontent.com/877585/184883518-6308a847-a833-41ab-9206-39f8cef4191c.png">
