### ISSUE TITLE
Permissions don't work as expected on collections

### ISSUE THREAD

**Issue by DanAtShenTech** [wagtail/wagtail#4479]
After uploading a number of images as superuser, I created a collection named Payment Card Icons into which I placed only these types of icons.  All other images are in the Root collection.  The Editor group is only set to have permission to add/edit images in the Root collection.  However, when I log in as a user in the Editor group, I can still see the payment card icons on the images page, and the Payment Card Icons group shows up in the Collection dropdown.  For the Editor group, I tried adding the Payment Card Icons collection to the Image Permissions while leaving off all permissions (in order to disallow Editors from editing this collection), but the collection with no permissions assigned would not even save under the Image Permissions.  I've confirmed that the payment card icons are only in the Payment Card Icons collection - these images do not show up when I choose the Root collection.  When signed in as an Editor user, I was able to not only see the payment card icons but also change the icon.  If this is proper behavior, then how might I prevent Editors from being able to see (and edit) the payment card icons?

**Comment by chosak** [comment]
@DanAtShenTech any permissions set on the Root group also apply to all child groups; permissions can only be increased going down the tree, not restricted. See [this section of the docs](http://docs.wagtail.io/en/latest/topics/permissions.html#image-document-permissions):

> Permissions set on ‘root’ apply to all collections, so a user with ‘edit’ permission for images on root can edit all images; permissions set on other collections apply to that collection only.

As a workaround, you could remove Root permission from Editors and move all non-Payment Card images into another collection that they do have permissions over.
