### ISSUE TITLE
Document PyPI trove classifiers for Wagtail

### ISSUE THREAD

**Issue by chosak** [wagtail/wagtail#4483]
As of https://github.com/pypa/warehouse/issues/3570, the following Wagtail [trove classifiers](https://pypi.org/pypi?%3Aaction=list_classifiers) are now supported on PyPI:

```
Framework :: Wagtail
Framework :: Wagtail :: 1
Framework :: Wagtail :: 2
```

We should add documentation of this, perhaps under the [Contributing to Wagtail](http://docs.wagtail.io/en/v2.0.1/contributing/index.html) section. This might be a nice opportunity to also add a pointer to https://github.com/springload/awesome-wagtail as part of a new section for people who want to develop packages for Wagtail.

**Comment by thibaudcolas** [comment]
👏 this would be pretty cool! Just added a note in Awesome Wagtail that the classifiers do exist (https://github.com/springload/awesome-wagtail/pull/74). Ideally there would be more info about this, but it's a start.

**Comment by thibaudcolas** [comment]
+1 for a new documentation section "Developing extensions for Wagtail". There is lots we could add in there.
