### ISSUE TITLE
RichTextField doesn't work in Safari (throws Javascript errors)

### ISSUE THREAD

**Issue by wilgucki** [wagtail/wagtail#4484]
### Issue Summary

RichTextField doesn't work in Safari browser. Console shows two Javascript errors:
- TypeError: undefined is not an object (evaluating 't[n].call') - vendor.js:1:101
- TypeError: undefined is not an object (evaluating 'window.draftail.initEditor') - Global Code 3:347

### Steps to Reproduce

1. Create fresh install of wagtail project.
2. Create new model
```
class TestPage(Page):
    body = RichTextField()

    content_panels = Page.content_panels + [
        FieldPanel('body', classname='full')
    ]
```
3. Create new page from that model. At this step RichTextField won't be displayed and Javascript errors will be shown in the console.

### Technical details

* Python version: 3.6.4
* Django version: 2.0.4
* Wagtail version: 2.0.1
* Browser version: Safari Version 11.1 (13605.1.33.1.2)

**Comment by thibaudcolas** [comment]
Hey @wilgucki, this seems to be working for me. Tried with Wagtail 2.0.1 in Safari 11.1 as well.

I would be surprised if this really was happening on a fresh project –  could you make sure this isn't a cache issue based on something you had earlier? See https://github.com/wagtail/wagtail/issues/3700#issuecomment-375474765 (and the linked SO answers) to find cache-clearing instructions.

If that doesn't help, please have a look at the networks tab in the developer tools and check that `vendor.js` and `draftail.js` are getting loaded.

**Comment by wilgucki** [comment]
Hey @thibaudcolas, it was browser cache. I don't know how I could missed this :) Sorry for the trouble.

**Comment by thibaudcolas** [comment]
👌 no worries
