### ISSUE TITLE
Cannot Integrate Wagtail-2.01 with Django-2.04 with Custom User Model

### ISSUE THREAD

**Issue by onsombal** [wagtail/wagtail#4492]
Django-2.04 with Custom User Model using "email address" as username.
Wagtail-2.01
Ubuntu-16.04

The error listed below is returned when attempting to integrate Wagtail with a Django project using a custom User Model defining email address as username.

```
 File "/vagrant_data/djangowagtail/wagenv/lib/python3.5/site-packages/django/forms/models.py", line 266, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (groups) specified for User
```
Is this a bug or an oversight with respect to supporting Django Customer User Models?

Wagtail integration with Django's default User Model works perfectly.

Thanks... Jim

**Comment by gasman** [comment]
Hi @onsombal,
We do support custom user models, provided they implement the fields/relations to support Django's permission model - usually this is done by [inheriting from `PermissionMixin` or `AbstractUser`](https://docs.djangoproject.com/en/2.0/topics/auth/customizing/#custom-users-and-permissions). It looks like your user model isn't currently doing this. It might help to refer to the custom user models that we use in Wagtail's unit tests: https://github.com/wagtail/wagtail/blob/master/wagtail/tests/customuser/models.py
