### ISSUE TITLE
The test_page_is_public templatetag's caching method doesn't seem to work.

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#4499]
I was working on improving the performance of a custom Page listing app that my Site uses to display the entire Page tree in a single request, and I discovered what I believe to be a bug in the caching functionality of `wagtail.admin.templatetags.wagtailadmin_tags.test_page_is_public()`.

It claims to cache the results of the rather large "Give me every single `PageViewRestriction`" query into the context. However, when my code uses this tag (many hundreds of times in a single request), I see that query being executed once for every page, despite the claim at caching. And looking at the context each time that tag is called, the `'all_page_view_restriction_paths'` key is clearly not still set from the last time the tag was called.

Now, this could be an effect of how I have my templates layered. I don't fully understand how the "active context" gets passed up and down through the template render pipeline, so maybe I'm doing something wrong, and it's not Wagtail's fault. But I looked at the entire pipeline from the view code and down through all the templates, and I don't see anything that could obviously be "resetting" the context and causing this cached value to be lost.

My view code renders the main template, which includes the template that renders the table of Pages, which loops through all the pages and includes the table row template for each one (passing the page object in using `{% include "sitemap/sitemap_row.html" with page=page %}`, note the absense of `only`). The table row template includes the page title div template, and that template includes `wagtailadmin/pages/listing/_privacy_indicator.html`, which calls `test_page_is_public`.

Maybe this strategy of caching things into the context just doesn't work? I've currently got the template tag monkey-patched to cache the query results into an attribute on the request, instead of a key in the context, and that definitely works.

**Comment by lb-** [comment]
Been a while since this has been raised. Adding labels and flagging as unconfirmed as this may no longer be applicable to the current code or may have since been fixed.

**Comment by coredumperror** [comment]
Looks like this got fixed at some point in the past. The code that I had felt the need to monkey patch was here: https://github.com/wagtail/wagtail/blob/b25bf0c6bddbfab1b1596d8eb1aa107b59bedd47/wagtail/admin/templatetags/wagtailadmin_tags.py#L151

Notice that it caches the data directly in a context variable.

But today, the `test_page_is_public` tag no longer does that, instead doing the same thing my patch does: caching the data in an attribute on the request object, which it pulls from the context.

I clearly no longer need my patch, though, so thanks for the heads up on this!

**Comment by lb-** [comment]
Awesome. Thanks for checking
