### ISSUE TITLE
Editing without leaving edit interface

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#451]
Add a button to allow users to go back to the edit page after saving. Possibly add this as a user preference.

**Comment by ZackPlauche** [comment]
Why not just make it a setting? Sometimes the javascript throws an error and it breaks the "Preview" button on pages, making it open in a new page (for some reason. I personally think it's weird it doesn't just open on a new page by default all the time, even when the JavaScript breaks).

**Comment by wefhi** [comment]
If you need this kind of functionality for ModelAdmin I recommend you override WagtailModelAdmin with your CustomModelAdmin and use it instead of ModelAdmin



```
from wagtail.contrib.modeladmin.views import EditView

class SaveContinueEditView(EditView):
    def get_success_url(self):
        return self.edit_url  # default is self.index_url

class CustomModelAdmin(WagtailModelAdmin):
    edit_view_class = SaveContinueEditView

```

This code guarentees that after pressing "save" you will be redirected back to edit view instead of index

**Comment by SteanlyCZ** [comment]
> If you need this kind of functionality for ModelAdmin I recommend you override ModelAdmin with your CustomModelAdmin and use it instead
> 
> ```
> from wagtail.contrib.modeladmin.options import ModelAdmin
> from wagtail.contrib.modeladmin.views import EditView
> 
> class SaveContinueEditView(EditView):
>     def get_success_url(self):
>         return self.edit_url  # default is self.index_url
> 
> class CustomModelAdmin(ModelAdmin):
>     edit_view_class = SaveContinueEditView
> ```
> 
> This code guarentees that after pressing "save" you will be redirected back to edit view instead of index

perfect, working!

and how to redirect to edit when create new object? (edit_create_class)
