### ISSUE TITLE
Auto open chooser from InlinePanel with single chooser

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#4510]
### Issue Summary

An InlinePanel with a single chooser field requires 3 clicks to add a reference to the target model.

### Steps to Reproduce

1. Create an InlinePanel with a single chooser field in it
2. In the Wagtail admin, go to edit your page, click "+ Add X". An empty container with a "Choose" button is inserted
3. Click "Choose", then click on the target item.

### Desired behaviour

It makes a lot more sense to get the chooser popup open up when you click "+ Add X". If the user doesn't want to select anything and clicks the modal close button, nothing happens. If they choose something, the populated container gets inserted.

This can be an `InlinePanel` option (e.g. `auto_open_chooser = "model_field"`), or an alternative `InlinePanel` (e.g. `ChooseInlinePanel`)

/cc @kaedroho

**Comment by thibaudcolas** [comment]
We’re considering this as part of the [page editor 2022](https://github.com/wagtail/wagtail/discussions/7739) redesign – assigning to @phildexter for further review.

**Comment by phildexter** [comment]
Yep, this will be covered by the new designs 
![image](https://user-images.githubusercontent.com/34743669/152830392-f8f1782e-30d1-493a-adf1-57ad2ec91554.png)

**Comment by thibaudcolas** [comment]
I believe this has been implemented with the [Multiple-chooser panel](https://docs.wagtail.org/en/stable/releases/4.2.html#multiple-chooser-panel).
