### ISSUE TITLE
Snippet history logging

### ISSUE THREAD

**Issue by mic159** [wagtail/wagtail#4541]
The Wagtail Page model includes a great history tracking interface, but a Snippet has no such history.
Changes made to a Snippet are not recorded anywhere.

The Django Admin has the `LogEntry` model where changes are recorded, I would like to propose Snippet changes are at least recorded in the Django `LogEntry` table, and potentially a history view in the wagtail admin to see the history.

https://docs.djangoproject.com/en/2.0/ref/contrib/admin/#logentry-objects

**Comment by engineervix** [comment]
Looks like this is now possible, beginning from Wagtail 2.15. Here are some relevant links:

- [Wagtail 2.15 Release notes](https://docs.wagtail.org/en/latest/releases/2.15.html#audit-logging-for-all-models)
- [Docs » Extending Wagtail » Audit log » Log models](https://docs.wagtail.org/en/stable/extending/audit_log.html#log-models)

**Comment by gasman** [comment]
@engineervix Good spot! Closing as completed in #7550.
