### ISSUE TITLE
Improvement to error message user receives when moving child page from one parent to another with a child page with the same slug

### ISSUE THREAD

**Issue by melsjoy** [wagtail/wagtail#4542]
### Issue Summary

When a user is moving a page to a new folder, if another page with the existing slug exists, the user receives a 500 error. 

This is not helpful for the user of the CMS as they simply get a 500 error, rather than a useful message that states what they were doing that caused the error. 

### Steps to Reproduce

1. Create a new child page 'test page' under a parent page e.g. 'test parent page'
2. Create another new child page under another parent page e.g. 'test page' in 'test parent page 2'
3. Move 'test page' from 'test parent page 2' to 'test parent page'
4. A 500 error is thrown: `ValidationError: {'slug': ['This slug is already in use']}`. In production environments the user is unaware that the issue is the use of the same slug 

It would be great to have a user-friendly error message that states what the user was doing that is causing the error. 

### Technical details
* Django version: 2.0.4
* Wagtail version: 2.0.1
* Browser version: Chrome 66 
* Python version: 3.6.5

**Comment by rgs258** [comment]
@gasman can you please let me know how WRDS can sponsor this for an upcoming release?

@FlipperPA

**Comment by thibaudcolas** [comment]
👋 I don’t know when, but this has been fixed.

For this scenario, here’s the error message I got:

>  The slug 'about' is already in use at the selected parent page. Make sure the slug is unique and try again
