### ISSUE TITLE
documents are not showing up, while images are.

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#4547]
We've got wagtail 2.0.1 set up to work with AWS S3 for media files, and that works great for images (uploads are sent to S3, the /images route shows all images in the image manager), it does not seem to work correctly for documents.

The settings we use:
```
# Storage for user generated files
if USE_S3:
    # Use S3 to store user files if the corresponding environment var is set
    DEFAULT_FILE_STORAGE = 'filebrowser_s3.storage.S3MediaStorage'
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN')
    AWS_LOCATION = env('AWS_LOCATION')

    MEDIA_URL = 'https://' + AWS_S3_CUSTOM_DOMAIN + '/'
    MEDIA_ROOT = ''

    FILEBROWSER_DIRECTORY = env('FILEBROWSER_DIRECTORY')

else:
    # Otherwise use the default filesystem storage
    MEDIA_ROOT = root('media/')
    MEDIA_URL = '/media/'
```

(note that `filebrowser_s3` is a small library that [extends the S3Boto3Storage class from the `s3boto3` library](https://github.com/Pomax/filebrowser_s3/blob/master/filebrowser_s3/storage.py))

We can upload documents, and these end up on S3 in the correct location, with the database getting a `file` record that points to the correct path to append to the S3 base location, but the /documents route shows "nothing":

![image](https://user-images.githubusercontent.com/177243/40138146-ec506024-5900-11e8-95e6-c0ee7345ea8c.png)

Does the document app use a special wagtail constant that we need to set in addition to the media root/url constants, so that wagtail can show the document list with the associated edit/etc UI?

**Comment by tomdyson** [comment]
Hi @Pomax, [StackOverflow](https://stackoverflow.com/questions/tagged/wagtail) is a better place for questions like this - would you mind reposting there?

I haven't seen `filebrowser_s3` before - the standard Wagtail/S3 setup uses `DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'`. This [blog post](https://wagtail.io/blog/amazon-s3-for-media-files/) might be useful.

**Comment by Pomax** [comment]
I can do that, although from what I've seen on stackoverflow it's literally the same people answering the questions, and as an issue that might require documentation to be updated, github's the far more logical place to have these kind of questions.

**Comment by Pomax** [comment]
https://stackoverflow.com/questions/50378600/wagtail-images-working-fine-documents-not-showing-after-upload
