### ISSUE TITLE
blank=False validation on RichTextField / RichTextBlock is applied inconsistently

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#4549]
### Issue Summary

Submitting an empty `RichTextField` that has been defined as `blank=False` only produces a validation error if the user focuses on the field before submitting the form.

This happens because the spacer paragraph insertion logic in `wagtail.admin.rich_text.converters.html_to_contentstate` normalises empty rich text content to a single empty paragraph, whereas Draftail explicitly tests for this case and returns `null`. If the user never focuses on the field, Draftail is never activated, and so the final value of the field (following conversion back to dbHTML) ends up as `<p></p>`, which is considered non-empty by Django validation.

We propose that `html_to_contentstate` should catch empty content as a special case, and return `null`. (Doing this within `html_to_contentstate`, rather than checking the initial string value before html->contentstate conversion, ensures that we also catch HTML constructions that are semantically empty but not equal to the empty string, such as `<p> </p>`.)

### Steps to Reproduce

From a fresh `wagtail start` project:

    ./manage.py migrate
    ./manage.py createsuperuser

Update home/models.py:

    from django.db import models
    
    from wagtail.admin.edit_handlers import FieldPanel
    from wagtail.core.fields import RichTextField
    from wagtail.core.models import Page
    
    
    class HomePage(Page):
        body = RichTextField(null=False, blank=False)
    
        content_panels = Page.content_panels + [
            FieldPanel('body'),
        ]

Run:

    ./manage.py makemigrations  # (set '' as the default value for the field)
    ./manage.py migrate
    ./manage.py runserver

Edit the homepage; click 'save draft' without focusing on the body field - no validation error

Edit the homepage; focus on the body field then click 'save draft'  - validation error

### Technical details

* Python version: 3.6.1
* Django version: 2.0.5
* Wagtail version: 2.0.1
* Browser version: Chrome/66.0.3359.117 on OS X 10.12.6

**Comment by harrislapiroff** [comment]
Sharing my workaround for use in templates, in case it's helpful to anyone else. There are some pages in our sites that rely on a check like

```html+django
{% load wagtailcore_tags %}

{% if model.text_field %}
    <div class="warning">
        {{ model.text_field|richtext }}
    </div>
{% endif %}
```

For those sites I've written this simple filter as a workaround:

```python
from django import template

register = template.Library()

@register.filter
def richtext_isempty(value):
    """
    Returns True if a value is an empty string, none, or a string containing
    nothing but paragraph tags
    """

    return any([
        value is None,
        value == '',
        value == '<p></p>',
    ])
```

Which can be used like:

```html+django
{% load wagtailcore_tags my_tags %}

{% if not model.text_field|richtext_isempty %}
    <div class="warning">
        {{ model.text_field|richtext }}
    </div>
{% endif %}
```

**Comment by loicteixeira** [comment]
Wagtaildraftail defined `empty_values` on the `TextField` directly (see [definition][1] and [json values][2]) which I know was working for field validation but I don't think it would solve the templating issue. But this was before the whole converter things so I'm not even sure it would still work.

[1]: https://github.com/springload/wagtaildraftail/blob/87f1ae3ade493c00daff021394051aa656136c10/wagtaildraftail/fields.py#L13
[2]: https://github.com/springload/wagtaildraftail/blob/87f1ae3ade493c00daff021394051aa656136c10/wagtaildraftail/validators.py#L4

**Comment by Scotchester** [comment]
@harrislapiroff Thanks so much for the suggested workaround!

If anyone else stumbles upon this, I had to make one tweak in the filter code. The `value` that gets passed in is a `wagtail.core.rich_text.RichText` object. I had to access its `source` property to look for the empty paragraph string:

```diff
 return any([
     value is None,
     value == '',
-    value == '<p></p>',
+    value.source == '<p></p>',
    ])
```

Unsure if that also needs to be added to the line testing against the empty string or not, but this change worked for me.

**Comment by Scotchester** [comment]
Addendum: I didn't make it clear that I needed to make that tweak in order to test the value of a `RichTextBlock` (not a `RichTextField`)`. The `value` that gets passed in if your template usage is a simple `{% if block|richtext_isempty %}` is a `wagtail.core.rich_text.RichText` object, so accessing its `source` property is necessary to look for the empty paragraph string.

Alternatively, you could use Harris's filter as-is and pass `block.source` to the filter, i.e., {% block.source|richtext_isempty %}`.

**Comment by y-martinez** [comment]
Hi everyone, this issue is available?

**Comment by cspollar** [comment]
I am unable to reproduce this bug use using the steps described above. I had older projects that were impacted, but after updating them, it appears validation errors are raised as expected. Can this issue be closed?

## Technical details
Python version: 3.8.3
Django version: 3.2.4
Wagtail version: 2.13.1
Browser version: Chrome/91.0.4472.77 on Mac OS

**Comment by gasman** [comment]
Thanks @cspollar! Yep, looks like this has indeed been fixed - not sure exactly when, but it looks like the relevant bit of activation in Draftail (i.e. the bit that normalises a single empty paragraph to `null`) now happens on page load rather than on focus.
