### ISSUE TITLE
Strange behaviour with BlockFeature adding blockquote feature

### ISSUE THREAD

**Issue by SalahAdDin** [wagtail/wagtail#4556]
I'm working at adding new features for text editor and i tested with [`blockquote`](https://github.com/thibaudcolas/bakerydemo/blob/feature/draftail-demos/draftail_demos/wagtail_hooks.py#L52), but i have an error when i use `type_` in `control` instead `'BLOCKQUOTE'`.

### Steps to Reproduce

1. Create a new feature
2. Create `control` and use `type_` in `'type': type_`
![deepin-screen-recorder_select area_20180522000605](https://user-images.githubusercontent.com/5034215/40329948-086a2e96-5d54-11e8-9d5f-c77e77a370fe.gif)
3. Now replace `'type': type_` by `'type': 'BLOCKQUOTE'`.

You will get the correct behaviour:
![deepin-screen-recorder_select area_20180521235959](https://user-images.githubusercontent.com/5034215/40329747-35469284-5d53-11e8-8ea3-cd024f5eb437.gif)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

* Python `3.6.5`
* Django Version: `2.0.5`.
* Wagtail Version: `2.1rc2`.
* Browser version: https://whatsmybrowser.org/b/QLWTTEV

**Comment by thibaudcolas** [comment]
Hey @SalahAdDin, nice catch.

I imagine you used http://docs.wagtail.io/en/v2.0.1/advanced_topics/customisation/extending_draftail.html. I’m surprised I used lowercase type in one place and uppercase in another. I’ll double check which one is meant to be used.

**Comment by thibaudcolas** [comment]
I tried the official example from the [Draftail docs](http://docs.wagtail.io/en/v2.0.1/advanced_topics/customisation/extending_draftail.html) and it is working as expected. Those `type_`, `feature_name` & other variables aren’t required, they’re just here to make the API easier to follow in the documentations (`blockquote` being one of those examples where feature name, Draft.js block type, and HTML tag are all the same value).

Here is the full example without any variables:

```python
@hooks.register('register_rich_text_features')
def register_blockquote_feature(features):
    """
    Registering the `blockquote` feature, which uses the `blockquote` Draft.js block type,
    and is stored as HTML with a `<blockquote>` tag.
    """
    features.register_editor_plugin(
        'draftail', 'blockquote', draftail_features.BlockFeature({
            'type': 'blockquote',
            'label': '❝',
            'description': 'Blockquote',
            # Optionally, we can tell Draftail what element to use when displaying those blocks in the editor.
            'element': 'blockquote',
        })
    )

    features.register_converter_rule('contentstate', 'blockquote', {
        'from_database_format': {
            'blockquote': BlockElementHandler('blockquote'),
        },
        'to_database_format': {
            'block_map': {
                'blockquote': 'blockquote',
            },
        },
    })
```

**Comment by SalahAdDin** [comment]
Meaybe it was solvet with last release versions, i must to check it.
