### ISSUE TITLE
Cannot install wagtail client from npm.

### ISSUE THREAD

**Issue by tutuca** [wagtail/wagtail#4559]
### Issue Summary

Trying to install the [wagtail client](https://www.npmjs.com/package/wagtail) library from npm raises an error:

```
npm ERR! path /usr/src/app/node_modules/wagtail/src/cli/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/src/app/node_modules/wagtail/src/cli/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-23T00_43_17_365Z-debug.log
```

### Steps to Reproduce

Just follow the instructions on package page: https://www.npmjs.com/package/wagtail

1. `npm install wagtail`

Aditional information:
 ```
$ node --version
v9.7.1
$ npm --version
5.6.0
```

**Comment by gasman** [comment]
Hi @tutuca,
Please see https://github.com/wagtail/wagtail/issues/4338#issuecomment-371215511
