### ISSUE TITLE
Feature request: add more built-in rich text formats

### ISSUE THREAD

**Issue by favoyang** [wagtail/wagtail#4562]
This is a feature request question. When browse the [draftail examples page](https://springload.github.io/draftail/examples/), I could see many formats not included in wagtail 2.1 version (under "All built-in formats" section). 

```
Code: Code
Underline: Underline
Strikethrough: Strikethrough
Mark: Mark
Quotation: Quotation
Small: Small
Sample: Sample
Insert: Insert
Delete: Delete
Keyboard: Keyboard
Superscript: Superscript
Subscript: Subscript
Blockquote
```

Is there a plan to integrate latest version for draftail into wagtail?

**Comment by thibaudcolas** [comment]
Hey @favoyang, thanks for opening this. We initially only added the rich text formats Wagtail was using with its previous editor, but did discuss adding more built-in formats.

I think we would definitely welcome pull requests to add:

- Code (`<code></code>`)
- Blockquote (`<blockquote></blockquote>`)

For other formats, we haven't had a discussion about what should be built-in and what shouldn't.

-----

Coming back to your list, I should add that those things "from Draftail" are just the ones that have predefined styles https://github.com/springload/draftail/blob/df836a502cd4d833c106aa2df7f755254e06ee03/lib/api/constants.js#L53-L112 – it's nothing more than that, so shouldn't weigh in the balance that much when it comes to adding it to Wagtail or not.

I should add though that when I picked things to go on that list, I based it on HTML elements – all of those unambiguously map to an HTML tag. You can see the list of tags in the exporter: https://github.com/springload/draftjs_exporter/blob/220f2b93f2fd39329077058114616314fe495c81/draftjs_exporter/defaults.py#L36-L55.

**Comment by SalahAdDin** [comment]
@favoyang  @thibaudcolas , i added six from that list using `hooks`, it's easy.

**Comment by thibaudcolas** [comment]
Actually, looking at the code again I forgot that the "built-in Draftail formats" go beyond styles. They also come with pre-defined labels and descriptions in english, **and keyboard shortcuts**.

Specifically, here are the ones that come with keyboard shortcuts:

```js
KEYBOARD_SHORTCUTS[INLINE_STYLE.BOLD] = { other: 'Ctrl + B', macOS: '⌘ + B' };
KEYBOARD_SHORTCUTS[INLINE_STYLE.ITALIC] = { other: 'Ctrl + I', macOS: '⌘ + I' };
KEYBOARD_SHORTCUTS[INLINE_STYLE.UNDERLINE] = {
    other: 'Ctrl + U',
    macOS: '⌘ + U',
};
KEYBOARD_SHORTCUTS[INLINE_STYLE.STRIKETHROUGH] = {
    other: 'Ctrl + ⇧ + X',
    macOS: '⌘ + ⇧ + X',
};
KEYBOARD_SHORTCUTS[INLINE_STYLE.SUPERSCRIPT] = {
    other: 'Ctrl + .',
    macOS: '⌘ + .',
};
KEYBOARD_SHORTCUTS[INLINE_STYLE.SUBSCRIPT] = {
    other: 'Ctrl + ,',
    macOS: '⌘ + ,',
};
```

This is not customisable in any way, you have to use the exact identifier (e.g. `SUBSCRIPT` string, uppercase) to get this, so I think it's a good argument to have those four built-in – so people using these benefit from the keyboard shortcut, and there is less risk of defining a feature that does what these do without using the ""right"" identifier.

– and if anyone wonders why these get special treatment, it's because they are available in traditional word processors (Word, Google Docs) and use those shortcuts there.

**Comment by SalahAdDin** [comment]
@thibaudcolas That info is very interesting to put in the documentation.

**Comment by thibaudcolas** [comment]
@SalahAdDin if we can get those into Wagtail then it will be enough to document those "disabled by default but available" features somewhere around http://docs.wagtail.io/en/v2.1/advanced_topics/customisation/page_editing_interface.html#limiting-features-in-a-rich-text-field, and hopefully it will be enough 🙏

Then the keyboard shortcuts are available at the end of the editor's user guide https://github.com/springload/draftail/blob/master/docs/user-guide/README.md#keyboard-shortcuts. It's a bit buried but it's referenced in the Wagtail editor guide too.

**Comment by gasman** [comment]
👍  for adding all the above to Wagtail but disabled by default. (We don't want to encourage use of underline because that style should be reserved for links, and superscript/subscript are probably also 'niche' enough that it makes sense for them to be opt-in.)

**Comment by thibaudcolas** [comment]
#5141 adds built-in support for `blockquote`, `strikethrough`, `superscript`, `subscript`, `code` (inline). These are all disabled by default and can be enabled with the feature identifier. This will be part of Wagtail v2.5.

We've left out:

- `underline`, because even though it's a Draft.js built-in we don't want to encourage using this.
- `code-block`, because there are potential issues with whitespace handling in Wagtail's rich text processing (#4996 is an example). This should be rendered as a `pre` tag, within which whitespace should be handled differently. This is something we could fix later on, but for the moment a [StreamField code block](https://github.com/FlipperPA/wagtailcodeblock) is a very good alternative.

Here are formats that are also left out:

- Mark: Mark
- Quotation: Quotation
- Small: Small
- Sample: Sample
- Insert: Insert
- Delete: Delete
- Keyboard: Keyboard

All of these are even more niche than the ones that were just added. That said, I would really welcome for someone to make a standalone Wagtail extension to declare those so they can then easily be reused.

**Comment by SalahAdDin** [comment]
Totally documented, isn't it?

Thank you!

**Comment by thibaudcolas** [comment]
@SalahAdDin yes! 🙂 docs for this are under:

- https://docs.wagtail.io/en/latest/advanced_topics/customisation/page_editing_interface.html#limiting-features-in-a-rich-text-field
- And in the (unreleased) v2.5 release notes, upgrade considerations: https://docs.wagtail.io/en/latest/releases/2.5.html#new-rich-text-formats

**Comment by JoanEliot** [comment]
I recognize this is a closed issue, but I take issue with the notion that the team thinks its their proper place to decide—for me—that I shouldn't use underlining (or crazy font sizes, or whatever). I would like the rich text editor to offer the full range of standard formatting choices that are available in a rich text environment. I would ask that you reconsider, as of course a lower priority, your decision not to support more formats.

I will not take offense if you think it still wise to disable most of the "niche" formats by default; or if you offer guidance to less guideline-aware/novice developers about formatting choices to avoid as gauche; or even if you tut-tut and frown at me when you see that I've gone ahead and underlined something when the style guide says I should not. Rather, I shall appreciate you for protecting me against unwitting violations of cultural norms.

**Comment by thibaudcolas** [comment]
@JoanEliot Wagtail as a CMS reflects the opinions of the project’s contributors. I think that’s inevitable, and also something we actively seek. It’s not a goal to please everyone all the time, and at times we’ll even make the choice to upset some on the assumption we can achieve a net benefit for most.

This is an open-source project so you’re welcome to disagree and ask us to reconsider – but if you do so you’re expected to make the case for your proposals. Do the research. Provide evidence as to why underlines support is desirable, and why our concerns expressed in this thread don’t outweigh those benefits. We have a pretty good [feature request template](https://github.com/wagtail/wagtail/issues/new?assignees=&labels=type%3AEnhancement&template=FEATURE_REQUEST.md&title=) if you’re unsure what info we’re after exactly. We also have an established [RFC](https://github.com/wagtail/rfcs) format.

Finally, I’d suggest you ground your arguments on practical, specific use cases. We have limited resources as a project, and stating "I want the full range of standard formatting options" doesn’t really pass the bar.

**Comment by m5seppal** [comment]
Even though this is a closed issue, I think it makes most sense to add my comment here.

We need <small> in our project and it was only few lines of code to make it work, but I think it would make sense to add it to Wagtail (disabled by default) as I believe it's generic enough need. It's commonly used to "identify items of secondary importance such as copyright notices, side comments, and legal notices", including fine prints, footnotes, etc. In our case no other feature supported by Wagtail could convey the semantic meaning and also correct styling for the content.

**Comment by tomdyson** [comment]
Thanks for this helpful feedback, @m5seppal.

I edited your comment because `<small>` wasn't displaying without backticks.

**Comment by thibaudcolas** [comment]
@m5seppal it’s completely fine to comment on closed issues. Even though we decided not to add `small` before, I think we’ll happily consider a [new feature request](https://github.com/wagtail/wagtail/issues/new?assignees=&labels=type%3AEnhancement&template=FEATURE_REQUEST.md&title=) for it (or any of the other formats discussed above, really), in a new issue.

Please bear in mind our decisions to support features like this are generally based on a cost-benefit analysis. In this case the cost is quite clear to me (has to be implemented, with an appropriate icon, docs, keyboard shortcut perhaps, translations, etc.). The benefits not so much. We’d also want to see alternatives being considered.

---

In the case for `<small>`, for example, personally if an editor requested this for their content I would be more inclined to provide them with a "Notice", "Footnote", or "Comment" feature that would be more intuitive as a rich text editor format for them, and would happen to be using `<small>` when rendered on a page. But `small` as a rich text format – I’m not too sure the semantics are clear enough to users for it to be provided generically.

**Comment by m5seppal** [comment]
I understand cost-benefit consideration, that's how it should be done.

For us the main reason for the need is that we are replacing our old CMS with Wagtail and importing tens of thousands of articles from the old CMS, where `<small>` has been used as a rich text feature. We need to preserve the semantics so replacing `<small>` with some other tag isn't an option. Having `<small>` as a rich text feature isn't maybe the most intuitive way to do it, I agree on that, but replacing `<small>` with a completely new way of implementation, such as new 'footnote' field, would require a lot of work considering the amount of articles.

We might still consider other approaches, but from cost-benefit perspective it's almost certain that it's best for us to keep using `<small>` as it has been used always before for over 10 years.

**Comment by allcaps** [comment]
This is how you extend Wagtail Draftail rich text features: https://docs.wagtail.io/en/stable/advanced_topics/customisation/extending_draftail.html#extending-the-draftail-editor
