### ISSUE TITLE
Untraslated string

### ISSUE THREAD

**Issue by SalahAdDin** [wagtail/wagtail#4565]
I found two untranslated strings in the admin:
![problema2](https://user-images.githubusercontent.com/5034215/40607890-767aa816-6272-11e8-851d-4ac457f5592c.png)
![problem1](https://user-images.githubusercontent.com/5034215/40607891-769a69e4-6272-11e8-921d-8d4a8d805ed5.png)

The most strange thing is that i translated them in `Transifex`.

### Technical details

* Python `3.6.5`
* Django Version: `2.0.5`.
* Wagtail Version: `2.1`.
* Browser version: https://whatsmybrowser.org/b/QLWTTEV

**Comment by BertrandBordage** [comment]
Already fixed in https://github.com/wagtail/wagtail/commit/03d361b055eca1b7e799a0e2075bcd935986abc0.
