### ISSUE TITLE
Unable to add paragraph for a streamfield for Wagtail 2.x

### ISSUE THREAD

**Issue by badri** [wagtail/wagtail#4569]
### Issue Summary

When I create a new page model with a streamfield containing a rich text block, I'm unable to add/edit it.

### Steps to Reproduce

Follow wagtail's getting started instructions,
1. Install Wagtail

python3 -m pip install wagtail

2. Start your site

wagtail start mysite

3. Set up the database

cd mysite

python3 manage.py migrate

4. Create an administrator account

python3 manage.py createsuperuser

5. Add a page model with a streamfield,

```
class SupportPage(Page):
    body = StreamField([
        ('heading', blocks.CharBlock(classname="full title")),
        ('paragraph', blocks.RichTextBlock()),
        ('image', ImageChooserBlock()),
    ])

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]

```

**Note:** Does not happen in 1.x, only >= 2.0.

![screenshot from 2018-05-31 00-47-48](https://user-images.githubusercontent.com/41959/40742721-009ec56c-646d-11e8-8838-212d75f6808b.png)

### Technical details

* Python version: Run `python --version`.

3.5.2

* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.

Able to reproduce in both Django 2.0 and Django 1.11

* Wagtail version: Hover over the Wagtail bird in the admin, or run `pip show wagtail | grep Version:`.

2.1 and 2.0

* Browser version: You can use http://www.whatsmybrowser.org/ to find this out.

Chrome 66.

**Comment by gasman** [comment]
Hi @badri - thanks for the report.
Please can you try clearing your browser cache? We've found that this error is often caused by caching issues (see #4484, https://stackoverflow.com/questions/49088302/richtextfield-uneditable-with-draftail-in-wagtail-2-0).

**Comment by badri** [comment]
hi @gasman I can confirm that it works now after clearing the cache. Thanks for the quick response!
