### ISSUE TITLE
"fill" image tag creating off-center renditions

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#4572]
I'm quite confused by the output I'm seeing from some of my `fill` image tags, as they do not appear to be cropping the rendition to the center-point that the Image's focal area defines.

Here's what I mean:
![image settings](https://user-images.githubusercontent.com/413571/40804381-f2698faa-64cf-11e8-8710-5b363086c482.png)
![render](https://user-images.githubusercontent.com/413571/40804383-f3d5b65c-64cf-11e8-819a-037b5fd5bdfc.png)

The issue is subtle, but the rendered image `{% image fill-350x400-c100 %}` is slightly off center (to the left) of the focal area's definition. The right edge looks correct, but there are too many pixels to the left side.

I also discovered that reducing the width to 300 causes the rendition to look like this:
![render 2](https://user-images.githubusercontent.com/413571/40805258-8d9876ec-64d2-11e8-99b4-88a7236cff34.png)
The crop's been pulled in much closer on the left side than it has on the right. I'm not sure exactly what that means.

Here's the data in the DB for this image:

	{
		"id": 3244,
		"title": "redacted resize",
		"file": "writing.flint.caltech.edu/original_images/redacted-resize.jpg",
		"width": 600,
		"height": 400,
		"created_at": "2018-04-27 22:39:50.915081",
		"focal_point_x": 327,
		"focal_point_y": 200,
		"focal_point_width": 297,
		"focal_point_height": 400,
		"file_size": 75290,
		"import_id": null,
		"photo_credit": "",
		"caption": "",
		"alt": "redacted resize",
		"collection_id": 46,
		"uploaded_by_user_id": 28
	}

Could this have anything to do with our system using custom Image and Rendition models? We don't redefine any fields having to do with cropping, though.

We're using Wagtail 1.13.1 right now, because we don't currently have time to remediate our numerous monkey patches to wagtail's code to work with 2.x. We plan to upgrade as soon as we get a break in our schedule, though. We have Pillow 5.1.0 installed, in case that's relevant.

**Comment by kaedroho** [comment]
There's more pixels on the left of the focal area then there are on the right, so Wagtail trims more pixels from the left side. This is standard behaviour, it's done this way to preserve composition of the image while cropping (in this example, the photographer probably intended to add the little bit of lead space in front of this person and Wagtail has preserved this).

**Comment by coredumperror** [comment]
That seems to explicitly violate the _user's_ intent, though. If the user chooses a focal area that doesn't conform to the photographer's intent, it seems to me that the cropping system should care more about what the user has to say than the original photographer.

**Comment by kaedroho** [comment]
We only want the user to define the image's "most important region", which is just an area of the image that Wagtail will not crop into (but it's not a crop box). This allows the template author to use many different rendition sizes on the site and Wagtail will be able to crop them without chopping into the main subject of the image.

The aspect ratio of the required rendition almost never matches the aspect ratio of the focal point so Wagtail must pad it out from some pixels somewhere. I think the current method of cropping more of the edge pixels than the centre pixels generally works well. It does the best job of preserving composition and is more likely to include any secondary subjects in the final rendition as well.

I wouldn't be against allowing this to be configurable by the template author though. Perhaps we could add a ``-centered`` suffix to the ``fill`` filter which tells Wagtail to always centre on the main subject.

**Comment by coredumperror** [comment]
> Perhaps we could add a -centered suffix to the fill filter which tells Wagtail to always centre on the focal point.

I like that idea!
