### ISSUE TITLE
wagtailuserbar tag for modeladmin enabled instance

### ISSUE THREAD

**Issue by favoyang** [wagtail/wagtail#4576]
The wagtailuserbar is designed to work with Page instance. If it does not find a page instance, it will return an empty string and skip the reset hook logic, make it impossible to extend it for non-page instance.

```
    # Only render if the context contains a variable referencing a saved page
    page = get_page_instance(context)
    if page is None:
        return ''
    ....
    for fn in hooks.get_hooks('construct_wagtail_userbar'):
        fn(request, items)
```

The modeladmin module allows us to add any model in the Wagtail admin (with add/edit/list features). It will be sweet for wagtailuserbar to support modeladmin enabled instance.

RP: show the wagtailuserbar as long as the "self" variable in template context is a modeladmin enabled instance.
```
[Go to Wagtail Admin]
[Edit this page/object]
```

**Comment by nkuttler** [comment]
I spent a few hours looking into this and it doesn't look very doable, the wagtailuserbar is too tightly coupled with the page model. I built my own solution to display an edit link instead. As all the models I wanted a link for inherited from a base class I added this to the base class:

```
    def modeladmin_url(self):
        import_path = getattr(self, "modeladmin_class", None)
        if import_path:
            modeladmin_module = ".".join(import_path.split(".")[:-1])
            modeladmin_cls = import_path.split(".")[-1]
            module = import_module(modeladmin_module)
            modeladmin = getattr(module, modeladmin_cls)
            return modeladmin().url_helper.get_action_url("edit", self.id)
```

Each model then received a modeladmin_class property that looked like "theapp.admin.ModelAdminClass", and that's used in the already existing menu template. Not really what I wanted, but I wanted to add it here as I lost a lot of time. The permission check is handled in the template.

**Comment by gasman** [comment]
Sorry, I must have missed this issue the first time round!

I don't think this is a feature that Wagtail can usefully provide. The usefulness of the userbar arises from various design decisions built into the Page model: a Page being an object that knows how to serve an HTTPResponse for itself, with URLs defined by slug fields and tree positions and the page object being available in the template context as `self` and `page`. This means that Wagtail has a standardised way to determine which page is being viewed, and can offer context-specific links.

None of this exists for arbitrary modeladmin models - when you write a custom Django view to display a modeladmin object as a front-end page, you're making your own decisions about URLs, context variables and so on. Wagtail has no built-in knowledge of how you chose to build it. In principle we could make the behaviour of the wagtailuserbar tag configurable with rules like "if we are on view A, and variable B exists in the template context, then display a userbar with links X, Y and Z" - but at that point the wagtailuserbar tag is not really adding any value over simply writing those links into the template yourself.
