### ISSUE TITLE
Extending Draftail Docs Don't Work

### ISSUE THREAD

**Issue by KalobTaulien** [wagtail/wagtail#4577]
I'm reading the [Wagtail 2.01 Extending Draftail Docs](http://docs.wagtail.io/en/v2.0.1/advanced_topics/customisation/extending_draftail.html#extending-the-draftail-editor) and following the first example: adding a simple strikethrough to Draftail.

However, no matter what I do, it doesn't seem to take affect for me. I'm trying to apply it to `RichTextBlock()`'s but it's clear I'm missing something. 

Is there something missing from the docs?

**Comment by gasman** [comment]
Hi @KalobTaulien,
Have just tried it, and it's working here. One thing that might not be clear is that any registered feature needs to be specified in a rich text field's `features` list, or added to `default_features` in order for it to appear - I've now updated the docs in 6f92f9a23ae9066d94ac24cfefb61f94e8760ecf to clarify this.

**Comment by KalobTaulien** [comment]
That was probably it, I didn't register it. I'll give it another shot. 
Thanks @gasman !
