### ISSUE TITLE
Moderation panel fails silently and does not render if any PageRevision user is None

### ISSUE THREAD

**Issue by picturedots** [wagtail/wagtail#4578]
### Issue Summary

The rendering of the template page `pages_for_moderation.html` fails silently if any `PageRevision` instance that it attempts to render has no user.  The panel will not appear at all when this error happens.

This line in the template causes the error

`{{ revision.user.get_full_name|default:revision.user.get_username }}`

Since PageRevision's user field is not a required field, this seems like a bug.

The error happened because I was using the `save_revision` in my own custom form handling and neglected to provide a user argument.

It seems that the best solution is to update the template with an if statement, i.e. `{% if revision.user %}{{ revision.user.get_full_name|default:revision.user.get_username }}{% endif %}`

### Steps to Reproduce

1. save a page as a draft and submit for moderation
2. in the wagtail admin, observe that the draft page appears in the "Pages Awaiting Moderation" panel
3. from the django shell, remove the user from the most recent PageRevision object, e.g. revision = PageRevision.objects.last(); revision.user = None; revision.save()
4. observe that in the wagtail admin, the  "Pages Awaiting Moderation"  no longer appears

### Technical details

python 3.6.5
Django 2.0.6
Wagtail 2.1

**Comment by picturedots** [comment]
Encountered this error again -- this time due to a user being deleted, causing `revision.user`  to become None.

**Comment by gasman** [comment]
Fixed in #5971
