### ISSUE TITLE
In Cyrillic the char 'б' is treated as tag separator

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#4580]
### Issue Summary

I have a problem with taggit, Cyrillic keyboard layout and wagtail admin widget. In Cyrillic layout, the letter "б" occupies the same physical button as comma. Consequently, when I try to enter a word containing a letter "б" as a tag, it gets treated as an input break. In fact, I cannot enter any words with "б" in them (only when pasting). Is there an easy way to fix it? I'm using separate snippet for tags as a workaround currently, but this is not really user-friendly.

### Steps to Reproduce

1. Go to Wagtail admin
2. Add an image
3. Put your keyboard input source to Russian
4. In tags field enter 'Hello,world', in Cyrillic keyboard layout this would be 'Руддщбцщкдв'.
5. Got two tags 'Руддщ' and 'цщкдв'.

Expected: "б" is treated as a regular char and not as ',' separator. There should be one tag: 'Руддщбцщкдв'.

**Comment by gasman** [comment]
Hi @allcaps - thanks for the report.
There's an existing issue open for this, at: #2056
