### ISSUE TITLE
Datetimepicker is no longer localized

### ISSUE THREAD

**Issue by linuxsoftware** [wagtail/wagtail#4584]
### Issue Summary

Since the upgrade to jquery.datetimepicker v2.5.19 the widget is no longer being localized to the current language.  That is, the month names and day abbreviations are being displayed in English regardless of the language being selected.

### Steps to Reproduce

1. In any 2.1 version of Wagtail.  Go to the Admin interface | Account settings | Lanuage Preferences.
2. Select Preferred Language: German
3. Bearbeiten (Edit) any page (e.g. Home).  Select Einstellungen|Veröffentlicht ab: (Settings|Go live date/time:)
4. Note how the widget displays English month names and day abbreviations
5. To change back: Kontoeinstellungen |  Spracheinstellungen | Englisch

### My Technical details

* Python version: 3.5.4
* Django version: 2.0.5
* Wagtail version: 2.1
* Browser version: Google Chrome Version 63.0.3239.132

### Analysis

Wagtail localization of datetimepicker used to work by creating a custom locale ('lang') for each widget and setting the widget to that locale using the lang option.
 
Option 'lang' in datetimepicker for every widget was removed in https://github.com/xdan/datetimepicker/commit/9090478658a0a678fd0ea48ecfacb373e5ea7708
Explained in this issue https://github.com/xdan/datetimepicker/issues/331 

The new way to set the locale is using $.datetimepicker.setLocale().  BUT! this no longer allows custom locales.

So without changes to jquery.datetimepicker, I see two possible ways to fix this issue.

Hijack one of datetimepicker's standard locales and use that as the Wagtail custom locale.
https://github.com/linuxsoftware/wagtail/commit/32b25ce1d9489da72d7220ef6b9750b08ded2075

or

Rely on datetimepicker to do the localization.  (Which means we are limited to their translations.)
https://github.com/linuxsoftware/wagtail/commit/09a1f950d625b4a214675856503ea01e775cd3ee

Neither seems perfect, but let me know if you would like a pull-request for either of them.

**Comment by linuxsoftware** [comment]
@Pomax @thibaudcolas  Any thoughts?
(Bug was introduced with https://github.com/wagtail/wagtail/pull/4337)

**Comment by Pomax** [comment]
no immediate thoughts other than "that's an annoying problem to which I don't have an immediate solution". If I'm reading the linked issues for datepicker localization correctly, datepicker was made "not properly localizable" close to three years ago, so apparently it was bound to happen, but that doesn't make it any less annoying for wagtail users. 

Using the datepicker's built in localizations would probably make the most sense from what I understand about how it works.

**Comment by thibaudcolas** [comment]
Thank you for taking the time to track this down and propose solutions @linuxsoftware. Sorry this got introduced in the first place.

I quite like the idea of relying on the widget's built-in translations, but from what I can see there are a few that are missing compared to what Wagtail offers now (see list below). We'd also most likely need to maintain some mapping from Wagtail's locale code to datetimepicker's (eg. `fi_FI` -> `fi`). I think it's better for us to keep on defining our own locale to limit rework. I'll see if there is a way to do this that seems less hacky.

Here's the list of Wagtail Transifex locales (only the ones above 50%) and their corresponding built-in datetimepicker locale code. Two are missing in datetimepicker:

<details>

```
100% Chinese (China) – zh
100% Dutch (Netherlands) – nl
100% French – fr
100% German – de
100% Icelandic (Iceland) – not available
100% Italian – it
100% Norwegian Bokmål – no
100% Polish – pl
100% Spanish – es
100% Swedish – se
99.1% Portuguese (Brazil) – pt-BR
97.9% Romanian – ro
96.3% Korean – ko
95.7% Lithuanian – lt
91.4% Russian – ru
91.4% Slovak (Slovakia) – sk
90.6% Persian – fa
90.1% Ukrainian – uk
86.2% Catalan – ca
85% Greek – not available
82.3% Portuguese (Portugal) – pt
81.7% Finnish – fi
78.5% Galician – gl
67.7% Slovenian – sl
63.5% Dutch – nl
63.1% Japanese – ja
53.1% Indonesian (Indonesia) – id
52.7% Latvian – lv
```

</details>

**Comment by thibaudcolas** [comment]
@linuxsoftware could you have a look at #4675? This is based on https://github.com/linuxsoftware/wagtail/commit/32b25ce1d9489da72d7220ef6b9750b08ded2075, except it uses a custom locale.

**Comment by linuxsoftware** [comment]
Looks excellent!  Great that there is a way to still set a custom locale (using $.fn.datetimepicker.defaults).  Thanks.
