### ISSUE TITLE
Broken sample in Docs - Inline Panels and Model Clusters

### ISSUE THREAD

**Issue by mmmcorpsvit** [wagtail/wagtail#4589]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

sample dont work
http://docs.wagtail.io/en/v2.1/reference/pages/panels.html#inline-panels-and-model-clusters

> Traceback (most recent call last):
>   File "C:\Dev\landing\venv\lib\site-packages\django\db\models\options.py", line 566, in get_field
>     return self.fields_map[field_name]
> KeyError: 'related_links'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files\JetBrains\PyCharm 181.3870.25\helpers\pycharm\django_manage.py", line 59, in <module>
>     run_command()
>   File "C:\Program Files\JetBrains\PyCharm 181.3870.25\helpers\pycharm\django_manage.py", line 46, in run_command
>     run_module(manage_file, None, '__main__', True)
>   File "C:\Python\lib\runpy.py", line 205, in run_module
>     return _run_module_code(code, init_globals, run_name, mod_spec)
>   File "C:\Python\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Python\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:/Dev/landing\manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "C:\Dev\landing\venv\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
>     utility.execute()
>   File "C:\Dev\landing\venv\lib\site-packages\django\core\management\__init__.py", line 365, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "C:\Dev\landing\venv\lib\site-packages\django\core\management\base.py", line 288, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "C:\Dev\landing\venv\lib\site-packages\django\core\management\base.py", line 332, in execute
>     self.check()
>   File "C:\Dev\landing\venv\lib\site-packages\django\core\management\base.py", line 364, in check
>     include_deployment_checks=include_deployment_checks,
>   File "C:\Dev\landing\venv\lib\site-packages\django\core\management\base.py", line 351, in _run_checks
>     return checks.run_checks(**kwargs)
>   File "C:\Dev\landing\venv\lib\site-packages\django\core\checks\registry.py", line 73, in run_checks
>     new_errors = check(app_configs=app_configs)
>   File "C:\Dev\landing\venv\lib\site-packages\wagtail\admin\checks.py", line 62, in get_form_class_check
>     edit_handler = cls.get_edit_handler()
>   File "C:\Dev\landing\venv\lib\site-packages\wagtail\utils\decorators.py", line 53, in __call__
>     return self.value
>   File "C:\Dev\landing\venv\lib\site-packages\django\utils\functional.py", line 36, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "C:\Dev\landing\venv\lib\site-packages\wagtail\utils\decorators.py", line 49, in value
>     return self.fn(self.cls)
>   File "C:\Dev\landing\venv\lib\site-packages\wagtail\admin\edit_handlers.py", line 804, in get_edit_handler
>     return edit_handler.bind_to_model(cls)
>   File "C:\Dev\landing\venv\lib\site-packages\wagtail\admin\edit_handlers.py", line 131, in bind_to_model
>     new.on_model_bound()
>   File "C:\Dev\landing\venv\lib\site-packages\wagtail\admin\edit_handlers.py", line 280, in on_model_bound
>     for child in self.children]
>   File "C:\Dev\landing\venv\lib\site-packages\wagtail\admin\edit_handlers.py", line 280, in <listcomp>
>     for child in self.children]
>   File "C:\Dev\landing\venv\lib\site-packages\wagtail\admin\edit_handlers.py", line 131, in bind_to_model
>     new.on_model_bound()
>   File "C:\Dev\landing\venv\lib\site-packages\wagtail\admin\edit_handlers.py", line 280, in on_model_bound
>     for child in self.children]
>   File "C:\Dev\landing\venv\lib\site-packages\wagtail\admin\edit_handlers.py", line 280, in <listcomp>
>     for child in self.children]
>   File "C:\Dev\landing\venv\lib\site-packages\wagtail\admin\edit_handlers.py", line 131, in bind_to_model
>     new.on_model_bound()
>   File "C:\Dev\landing\venv\lib\site-packages\wagtail\admin\edit_handlers.py", line 688, in on_model_bound
>     self.db_field = self.model._meta.get_field(self.relation_name)
>   File "C:\Dev\landing\venv\lib\site-packages\django\db\models\options.py", line 568, in get_field
>     raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
> django.core.exceptions.FieldDoesNotExist: BookPage has no field named 'related_links'

**Comment by mmmcorpsvit** [comment]
any idea???
can any send minimal demo ForeignKey with model and inline code feature please???
very need

my e-mail: mmmsvit@gmail.com
th!

**Comment by gasman** [comment]
Hi @mmmcorpsvit,

You probably didn't change `demo` in the line `page = ParentalKey('demo.BookPage'...` to the name of your app.

I can confirm that the example works for me on a new project created with `wagtail start`, with the `home/models.py` file edited as follows:

    from django.db import models

    from wagtail.core.models import Page


    class HomePage(Page):
        pass


    from wagtail.core.models import Orderable, Page
    from modelcluster.fields import ParentalKey
    from wagtail.admin.edit_handlers import FieldPanel, InlinePanel


    # The abstract model for related links, complete with panels
    class RelatedLink(models.Model):
        title = models.CharField(max_length=255)
        link_external = models.URLField("External link", blank=True)

        panels = [
            FieldPanel('title'),
            FieldPanel('link_external'),
        ]

        class Meta:
            abstract = True


    # The real model which combines the abstract model, an
    # Orderable helper class, and what amounts to a ForeignKey link
    # to the model we want to add related links to (BookPage)
    class BookPageRelatedLinks(Orderable, RelatedLink):
        page = ParentalKey('home.BookPage', on_delete=models.CASCADE, related_name='related_links')


    class BookPage(Page):
        # ...

        content_panels = Page.content_panels + [
            InlinePanel('related_links', label="Related Links"),
        ]
