### ISSUE TITLE
Feature Request: Limit access to collections on image choose

### ISSUE THREAD

**Issue by alpower** [wagtail/wagtail#4597]
I'm working on a large sporting site with regional team based editing, and looking to set up regional collections, and while I can limit upload to certain collections, I'm trying to restrict regional editors **choosing** images uploaded by other regions.

I would love the ability to have a 'choose' permission to collections, as even though you can restrict user groups to specific collections in terms of adding and editing, when choosing images on a page, they can still browse all collections, even if they don't have permission to add/edit them.

My initial thought was to just used named collections, not the Root one, but it turns out all of these named collections are still visible when choosing. I appreciate the default need for access to all, but given you can restrict people to a certain subtree of the site using page permissions, why not have a similar choose permission for collections? 

E.g. If not specified, can see all in chooser, and if choose permission specified on certain collections, can only select from these.

Have seen it referenced in [SO](https://stackoverflow.com/questions/46397440/can-i-limit-the-visible-collections-in-the-wagtail-admin-image-chooser) and referenced by @gasman [in a comment](https://github.com/wagtail/wagtail/issues/4488#issuecomment-392015019).

Would love to put this forward for a feature request for multi-site & document/image collections - Thanks!

**Comment by gasman** [comment]
Hi @alpower - thanks for the suggestion.
This sounds the same as what's being proposed in #4488, so I suggest we keep the conversation on there.
