### ISSUE TITLE
Is there a bug in WAGTAIL_DATETIME_FORMAT?

### ISSUE THREAD

**Issue by sam-mi** [wagtail/wagtail#4601]
### Issue Summary

We'd like to format our dates Day.Month.Year Hour:Minute in the wagtail admin. I tried to use WAGTAIL_DATETIME_FORMAT along with Django's DATETIME_INPUT_FORMATS and DATETIME_FORMAT to modify the date format only to find that pages in the wagtail admin were not saving due to validation errors. 

I also notice there's a test for this exact format and the test passes.

### Steps to Reproduce

1 - clone the bakery demo, 
2 - paste this into the bottom of the settings file (config/settings/base.py or whatever) (copied directly from http://docs.wagtail.io/en/v2.1/advanced_topics/settings.html?highlight=WAGTAIL_DATETIME_FORMAT)

```
WAGTAIL_DATE_FORMAT = '%d.%m.%Y.'
WAGTAIL_DATETIME_FORMAT = '%d.%m.%Y. %H:%M'

DATETIME_INPUT_FORMATS = [
    '%d.%m.%Y. %H:%M',  
]

DATE_FORMAT = '%d.%m.%Y'
DATETIME_FORMAT = '%d.%m.%Y. %H:%M'
```

Create a page and try to set Go Live At date in the future, it will raise a validation error "Please enter a valid date/time" 

Instead of a validation error, I expected the page to save correctly. 
Removing WAGTAIL_DATETIME_FORMAT from settings allows the page to save correctly again.
DATETIME_INPUT_FORMATS and DATETIME_FORMAT are not necessary (can be removed) for this error to show. 

Is there something I'm missing or is this a bug?

### Technical details

* Python version: 3.6.3
* Django version: 2.0.5
* Wagtail version: 2.0.1
* Browser version: Any

wagtail/admin/forms.py ln 308

```
from django.conf import settings
print('Wagtail: ', settings.WAGTAIL_DATETIME_FORMAT)
print('Django: ', settings.DATETIME_FORMAT)
print('Django Inputs: ', settings.DATETIME_INPUT_FORMATS)
```
Wagtail:  %d.%m.%Y. %H:%M
Django:  %d.%m.%Y. %H:%M
Django Inputs:  ['%d.%m.%Y. %H:%M']

wagtail/admin/widgets.py ln 66

```
    def __init__(self, attrs=None, format=None):
        fmt = format
        print('Init Format', format)
        if fmt is None:
            fmt = getattr(settings, 'WAGTAIL_DATETIME_FORMAT', DEFAULT_DATETIME_FORMAT)
        self.js_format = to_datetimepicker_format(fmt)
        print('Wagtail: ', fmt)
        print('JS: ', self.js_format)
        super().__init__(attrs=attrs, format=fmt)
```

Init Format None
Wagtail:  %d.%m.%Y. %H:%M
JS:  d.m.Y. H:i

That all look correct to me, so why are they not cooperating? 

### Temporary Fix

Removing WAGTAIL_DATETIME_FORMAT and WAGTAIL_DATE_FORMAT from settings fixes the validation error, allowing pages to save again, however dates are represented in ISO format in the Wagtail admin. Not quite ideal as its not in line with what it says in the docs: http://docs.wagtail.io/en/v2.1/advanced_topics/settings.html?highlight=WAGTAIL_DATETIME_FORMAT

**Comment by linuxsoftware** [comment]
Hi @sam-mi 

Do you have USE_L10N=True somewhere in your Django settings?  If this is set then Django will use the locale settings for DATETIME_INPUT_FORMATS, DATE_INPUT_FORMATS, and TIME_INPUT_FORMATS, NOT the settings you put in your settings/base.py.
See https://docs.djangoproject.com/en/2.0/ref/settings/#std:setting-DATE_INPUT_FORMATS

But then the next problem after setting USE_L10N=False is the Datetimepicker widget won't parse the trailing dot in  "%d.%m.%Y. %H:%M"  So can you live with "%d.%m.%Y %H:%M"?  This would be easiest.

For a more sneaky (and probably brittle) way, have a look at what I've done to get widget for 12hr AM/PM times.
https://github.com/linuxsoftware/ls.joyous/blob/master/ls/joyous/widgets.py
https://github.com/linuxsoftware/ls.joyous/blob/master/ls/joyous/static/joyous/js/time12hr_admin.coffee

**Comment by sam-mi** [comment]
Ah yes, of course, thanks for your clarification and example.
