### ISSUE TITLE
Private login-only pages redirect to insecure login form

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#4607]
When you set a Page to have a Privacy setting of "Accessible to logged-in users", and the user isn't currently logged in, the system redirects them to a relative URL (`/_util/login` by default). If the user was visiting the site via http at the time, the login page and the form action will both be insecure, leading any login attempts to transmit the user's credentials in the clear.

This can currently be mitigated on a typical Wagtail site by setting `WAGTAIL_FRONTEND_LOGIN_URL` to a fully qualified https:// URL. 

Unfortunately, that isn't sufficient for my project, because we're using fully separated multitenancy. There isn't a single canonical URL that can be saved in that setting, because the correct login URL depends on which Site the protected page lives on.

I've solved this in a less-than-satisfactory way by monkey-patching `wagtail.wagtailcore.wagtail_hooks.require_wagtail_login()` to check the current request object for the correct hostname and build the URL at runtime. But that's not a very desirable solution.

**Comment by loicteixeira** [comment]
Hi @coredumperror, thanks for the report.

While I agree that we shouldn't present a login form on a non-secure page, I don't think that Wagtail can make the assumption that the application also supports SSL given an initial non-secure request. It's only fair for Wagtail to respect whichever protocol was used for the initial request.

HTTPS should be forced at the Load Balancer/NGINX level or with `SECURE_SSL_REDIRECT` in Django. In this case, the non-secure request would first be upgraded to a secure one, then Wagtail would detect that the page is private and redirect to the form which then will be using HTTPS.

**Comment by coredumperror** [comment]
See, that'd work great on most servers, since they don't have the potential to be hosting hundreds of different sites with potentially a half dozen different domain aliases each. We simply don't have the option of forcing SSL for all visitors, so we have to separate the site between http for anonymous visitors and https for logged in users.

I realize now that this is something that isn't Wagtail's problem, though.
