### ISSUE TITLE
Bug: Site.get_site_root_paths() preferring other sites over the default when more than one sites have the same root_page

### ISSUE THREAD

**Issue by ababic** [wagtail/wagtail#4612]
### Issue Summary

I'm in the process of updating wagtailmenus to support Wagtail 2.1, and have added a new test environment to Travis to see what happens when used with this version of Wagtail.

All of the tests that are now failing are doing so because of what used to be 'relative' page URLs rendering as 'full' page URLs. But, I cannot find anything in the release notes regarding breaking changes for this behaviour.

I think this could have something to do with the changes made in #4390. But, I haven't figured out what yet. I'll try patching those changes out locally and seeing what happens, but in the meantime, I thought I'd see if it rings any bells for anyone?

You can find the results of the failing job here:
https://travis-ci.org/ababic/wagtailmenus/jobs/392322357

The results for the exact same build with Wagtail 2.0.1 can be found here, and are passing:
https://travis-ci.org/ababic/wagtailmenus/jobs/392322356

**Comment by ababic** [comment]
I did some investigation, and the tests passed when I undid the changes made to `get_site_root_paths()` from #4390.

This got me curious, so I then looked at the changes made to `Page.get_url_parts()` too. If this method generally prefers the first item in the list returned by Site.get_site_root_paths(), but more than one Sites exist with the same `root_page`, shouldn't a Site having `is_default=True` put it before the others in Site.get_root_paths(), rather than after them?

I changed the `order_by` options in that method from:

'-root_page__url_path', 'is_default_site', 'hostname'`

To:

'-root_page__url_path', '-is_default_site', 'hostname'

And the tests passed again.

**Comment by ababic** [comment]
@BertrandBordage, are you able to confirm whether the current behaviour is intended, or is this a bug that needs fixing?

**Comment by BertrandBordage** [comment]
I agree, `-is_default_site` is the correct ordering, the default site has to be a preferred option.
This was clearly a mistake, @codiebeulaine & I specified `default_site` for that, but we didn’t check the ordering of booleans and ended up forgetting to test it.

Thank you @ababic :)

**Comment by ababic** [comment]
Thanks for confirming @BertrandBordage. 

This exact thing has tripped me up a few times before, too.

I won't have an opportunity to create a PR for a couple of days, but happy to do so if nobody else gets to it :)

**Comment by ababic** [comment]
Fixed in 5151c5c

**Comment by ababic** [comment]
@BertrandBordage / @loicteixeira,

Hi guys,

Just wondering... are you planning to do a maintenance release (e.g. `2.1.1`) with this fix applied? 

Without a valid 2.1 version to test against, I can't officially support `2.1` in wagtailmenus, because the test suite will never pass.

**Comment by gasman** [comment]
Yep, we should make a 2.1.1 release for this - have added a milestone to track this and any other fixes that should go into it.

**Comment by ababic** [comment]
Great. Thank you both :)
