### ISSUE TITLE
Avatar images are loaded in full resolution

### ISSUE THREAD

**Issue by bentrm** [wagtail/wagtail#4615]
### Issue Summary

Right now, avatar images of users are loaded in full resolution. As the images are only shown in 50x50 and 25x25 this adds up to a lot of unnecessary traffic.

My suggestion would be to improve the `avatar` template tag by deferring to the `image` template tag requesting a rendition in the appropriate size?

**Comment by lb-** [comment]
Some minor improvement will have been made towards this most likely via https://github.com/wagtail/wagtail/pull/8598 (lazy loading).

The underlying issue is not yet fixed I think but just flagging.

**Comment by gasman** [comment]
#12603 duplicates this - I'll close this one, as that one has a linked PR.
