### ISSUE TITLE
upgrade_notify.js XMLHttpRequest cannot load... 

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#4636]
When running Wagtail on a local machine I get the following console messages:

```
Origin http://127.0.0.1:8000 is not allowed by Access-Control-Allow-Origin.
XMLHttpRequest cannot load https://releases.wagtail.io/latest.txt due to access control checks.
Failed to load resource: Origin http://127.0.0.1:8000 is not allowed by Access-Control-Allow-Origin.
```

**Wagtail/admin/templates/wagtailadmin/home/upgrade_notification.html**

```
   ...
   <script src="{% static 'wagtailadmin/js/upgrade_notify.js' %}" async="true"></script>
```

**Wagtailadmin/js/upgrade_notify.js**

```
$(function() {
   ...
    var releasesUrl = 'https://releases.wagtail.io/latest.txt';
});

```

### Technical details

* Python version: 3.6.4.
* Django version: 2.0.5.
* Wagtail version: 2.1.
* Browser version: Safari 11.1.1

**Comment by gasman** [comment]
Clearing the Cloudfront cache seems to have fixed this - I guess S3 must have been returning the wrong headers some time in the last 24 hours for some reason.

**Comment by robslotboom** [comment]
Hi **@gasman**,

Thank You.

**Comment by aliceni** [comment]
Hi, I have this issue again.
![image](https://user-images.githubusercontent.com/41408550/132610114-b8ea0d89-7d4d-47c4-bb6d-525ebe205f4d.png)

**Comment by gasman** [comment]
@aliceni I'm not able to replicate this - the file at `https://releases.wagtail.io/latest.txt` is being fetched correctly when I try, and showing the correct HTTP headers. Perhaps something in your network setup is blocking that URL and serving something else in its place?

**Comment by aliceni** [comment]
@gasman I don't think this URL this blocked by my network because I can access this file. This problem still happens when I start a new wagtail project - using wagtail v2.14.1 and django v3.2.7.

**Comment by mikaraunio** [comment]
Hi, seeing this again. Can access the file, but not getting any `Access-Control` headers.

I'm hitting Cloudfront via IPv6 in case it matters.

**Comment by lb-** [comment]
See also similar issues recently raised but I moved to wagtail.org repo https://github.com/wagtail/wagtail.org/issues/356

**Comment by lb-** [comment]
@mikaraunio  could you please post a comment on https://github.com/wagtail/wagtail.org/issues/356 instead.
