### ISSUE TITLE
Website: update al urls to point to version 2.1 by default, instead of 1.9

### ISSUE THREAD

**Issue by Meteor0id** [wagtail/wagtail#4638]
Noticed the website still has a lot of urls pointign to older documentation by default. Although there is a warning displayed at the top of the page, this is an unnessesary cause for confusion and oversight.

Suggesting to from now on always point to the latest stable release version. At this time the latest stable version is 2.1, and the urls on for example [this page](http://docs.wagtail.io/en/stable/getting_started/integrating_into_django.html) point to 1.9 by default.

**Comment by Meteor0id** [comment]
So actually the tile of the issue report is to spesific, I would go one step further and ask to automate the urls updates to always point to the latest stable version. Maybe also make the the version is promimently displayed at the top of each documentaton page, so it is easily noticed if one is looking at a page for another version than was expected.

**Comment by gasman** [comment]
Hi @Meteor0id,
This was done in #4536, but hasn't made it into the stable version of the Wagtail docs yet (only the 'latest' branch, e.g. http://docs.wagtail.io/en/latest/getting_started/integrating_into_django.html).
