### ISSUE TITLE
Update a file with the same name

### ISSUE THREAD

**Issue by csalom** [wagtail/wagtail#4639]
### Issue Summary
At the documents edit view, if the file has changed the original file is deleted. 
If you edit a document uploading a new version of the file with the same name, the new document will be upload to the file system and the name of the document object will not be changed.
Then, the file is deleted which the reference of the new file.

### Steps to Reproduce
1. Upload a document
2. Enter to its edit view /documents/edit/pk
3. Update the document with a new version of the previous one, with the same name.
4. Enter to the edit view of the document again /documents/edit/pk -> A 404 Error was raised when accessing to the file because of its deletion.

### Technical details

* Python version: Run `3.6`.
* Django version:  `2.0 and previous`.
* Wagtail version: `2.1 and previous`.

**Comment by csalom** [comment]
I've opened a PR with a possible solution: #4640

**Comment by gasman** [comment]
Covered by #4567

**Comment by csalom** [comment]
Hi @gasman 
You're right, thank you!

**Comment by richaagarwal** [comment]
Does it make sense to close this issue if the PRs in question have not been approved or merged?

**Comment by gasman** [comment]
Hi @richaagarwal,
Unlike some other projects, we don't require PRs to have a corresponding issue open - the PR itself can serve as a problem report, that just happens to have a proposed solution attached. In this case, the existing PR #4567 had a more complete description of the problem and some further discussion, so it would be counter-productive to have another issue open covering the same ground.
