### ISSUE TITLE
Edit pages’ sticky footer hides critical parts of the UI

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#4641]
### Issue Summary

You can't add new streamfield blocks at the bottom of a edit page on mobile, and this hides various parts of the UI at other screen sizes.

### Steps to Reproduce

1. On a IOS device open a browser and go to an edit page in the admin.
2. Make sure the last field on that page is a streamfield. Containing a block.
3. Try to add a block below. You can't. The `+` button is behind the save buttons.

I expect the save buttons to go below the form/content. 
I also wonder why the save buttons are always visible. They take up a lot op space. Up to 1/4 of the screen on smaller devices.

In this example the 'Add another' button - for a list stream field item - is also below the save buttons.
![iphone_6s_-_11_4](https://user-images.githubusercontent.com/1969342/41649363-b277254a-747b-11e8-9fd9-e9cdb86aa8cf.png)

### Technical details

* Wagtail version: 2.1
* Browser version: IOS Safari 11.4

**Comment by loicteixeira** [comment]
StreamField front-end will be completely reworked in #4481 but keeping this issue open for now.

**Comment by allcaps** [comment]
The problem is the fact that the save/preview buttons are blocking _any_ content below it. The issue is probably not only with streamfields, but with all page content. 

My suggestions resolve the issue:
1. Save/Preview buttons should not overlap, but just be at the bottom op the page 
OR
2. There should be a bottom padding at the page so the content always can scroll above the Save/Preview buttons.

I think option 1 is best. Since the save buttons can take up to 1/4 of the screen. Which is a waste of space anyway.

I'm happy to submit a PR. But I think a decision has to be made first.

**Comment by allcaps** [comment]
The problem is the fact that the save/preview buttons are blocking _any_ content below it. The issue is probably not only with streamfields, but with all page content. 

My suggestions resolve the issue:
1. Save/Preview buttons should not overlap, but just be at the bottom op the page 
OR
2. There should be a bottom padding at the page so the content always can scroll above the Save/Preview buttons.

I think option 1 is best. Since the save buttons can take up to 1/4 of the screen. Which is a waste of space anyway.

I'm happy to submit a PR. But I think a decision has to be made first.

**Comment by thibaudcolas** [comment]
As you say this has nothing to do with StreamField and everything to do with the buttons overlapping with a quarter of the screen. I think option 1 is by far superior — any overlap is always annoying when you have so little screen space to start with.

**Comment by loicteixeira** [comment]
My bad, this issue and a few others you've opened specifically called for StreamField issue and I did not think this further 😞 

I've now removed the StreamField tag on the issue and would also be in favour of option 1.

**Comment by thibaudcolas** [comment]
@allcaps if you want to make a PR I’m happy to review it 🙂 Implementation-wise — would be best if we could achieve this by removing code, perhaps switching media queries around so the default layout is the mobile one and “up from mobile” gets the overlap added. I haven’t actually looked at the code so this might not be feasible exactly like that though.

**Comment by rifuso** [comment]
It's not just on mobile that this is a problem. It is always blocking fields and feels very claustrophobic. Is there an option to remove it?

**Comment by thibaudcolas** [comment]
@rifuso could you provide us with examples? I think it would be a pretty easy job and clear improvement for someone to make a PR to "un-sticky" this footer on mobile. For other screen sizes, we'll need to look at the actual issues.

**Comment by thibaudcolas** [comment]
With #5946 merged this is now fixed, and will be released in Wagtail 2.10 🙂 thank you to everyone involved!

There may be further UX improvements to do here, so there isn’t as much scrolling to save a page on mobile. Please open another issue to discuss this.
