### ISSUE TITLE
Fields are too small on mobile

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#4642]
### Issue Summary

The width of a (text) fields on mobile are too small.

### Steps to Reproduce

1. On a IOS device open a browser and go to an edit page in the admin.
2. Have a streamfield containing a richtext block
3. The width of the editor is ~1/4 of viewport width

I expect all input fields to be be 100% of the viewport width.

![iphone_6s_-_11_4_and_development_ _wagtail_2_1_documentation 2](https://user-images.githubusercontent.com/1969342/41649909-0b198d22-747d-11e8-8416-2bd586b6034b.png)

### Technical details

* Wagtail version: 2.1
* Browser version: IOS Safari 11.4

**Comment by thibaudcolas** [comment]
Will be fixed by #4942 I believe.

**Comment by gasman** [comment]
Have verified that this is fixed by the CSS-only StreamField update in 2.7 (#5476).
