### ISSUE TITLE
Image input field in streamfield is truncated on mobile

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#4644]
### Issue Summary

The buttons are cut off.

### Steps to Reproduce

1. Create as streamfield with an image block.
2. With a small mobile device go to the edit page.
3. The bottons are partially visible. As a user I wonder if I miss anything else.

I expect the complete buttons to be visible.  

### Technical details

Wagtail 2.1, IOS Safari.

![image2](https://user-images.githubusercontent.com/1969342/41650759-1d1c6ac4-747f-11e8-98ba-faec132f9255.png)

**Comment by loicteixeira** [comment]
StreamField front-end will be completely reworked in #4481 but keeping this issue open for now.

**Comment by allcaps** [comment]
The problem is the fact that the save/preview buttons are blocking _any_ content below it. The issue is probably not only with streamfields, but with all page content. 

My suggestions resolve the issue:
1. Save/Preview buttons should not overlap, but just be at the bottom op the page 
OR
2. There should be a bottom padding at the page so the content always can scroll above the Save/Preview buttons.

I think option 1 is best. Since the save buttons can take up to 1/4 of the screen. Which is a waste of space anyway.

I'm happy to submit a PR. But I think a decision has to be made first.

**Comment by jjanssen** [comment]
In addition to the StreamField: last week I start making some progress on the new chooser fields (#4055) in which I'm also keeping a keen eye on the mobile state of this field and other chooser fields.

**Comment by gasman** [comment]
Fixed in #5476
