### ISSUE TITLE
DecimalBlock values become strings

### ISSUE THREAD

**Issue by balazs-endresz** [wagtail/wagtail#4647]
### Issue Summary

DecimalBlock values work as expected when previewing a page, however they become strings when the published page is rendered.

### Steps to Reproduce

1. Add a StructBlock with a DecimalBlock field
2. Add a template filter that returns the type of the decimal block value, e.g. `register.filter(name='type')(lambda v: type(v))` 
3. Add a custom template for the StructBlock conatining: `{{ value.some_decimal_field|type }}`
4. Previewing the page will print `<class 'decimal.Decimal'>`
5. Publish and view the live page -> the type will be `<class 'str'>`

(As a quick fix I've just added `|add:0` because that converts it to a number.)

### Technical details

* Python version: 3.6
* Django version: 2.0.4
* Wagtail version: 2.1

**Comment by konrad147** [comment]
Another workaround `{{ value.some_decimal_field|floatformat:"2" }}`

**Comment by lb-** [comment]
Probably still happening but should be validated. Good first issue label and other labels added. 

Whoever wants to pick this up should start looking at this code. 

https://github.com/wagtail/wagtail/blob/main/wagtail/blocks/field_block.py

Most likely the value being shown in the Preview is based on the field widget but the value from the DB is from JSON and maybe not getting correctly parsed when pulled back out. 

`value_from_datadict` and `value_from_form` would be good places to start logging on the DecimalBlock and then from there see what may be missing or different.

**Comment by gasman** [comment]
Hi @yvess,
Your test code isn't quite complete - as well as displaying the number, you need to display its type (using the template filter code provided above). This shows the difference in behaviour between the preview and the live page:

(preview)
<img width="887" alt="Screenshot 2022-06-15 at 17 38 40" src="https://user-images.githubusercontent.com/85097/173868585-22ab5edd-a40e-46c3-98ba-ac9c70e57bc0.png">

(live)
<img width="907" alt="Screenshot 2022-06-15 at 17 38 56" src="https://user-images.githubusercontent.com/85097/173868604-bbe89556-3192-4fd0-8429-b3f7a69769fd.png">

I'll open a PR against your bakerydemo fork with this additional code.
