### ISSUE TITLE
Multiple issues with Ustream embeds

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#4651]
Since my company occasionally uses ustream to record events, we recently discovered that Wagtail's Ustream support is lacking in two vital ways.

1) Even if you use an https:// URL for the ustream video, the iframe's URL is rendered as http:// on the page. Browsers refuse to load http:// iframes on pages displayed over https.
2) Ustream's an old site, and they unfortunately still use Flash as their default player. You can convert to using the html5 player by adding `?html5ui` to the iframe URL, but Wagtail's embeds system _also_ strips any GET args from the video's source URL.

I've found a workaround for this by editing the `wagtailembeds_embed` table and manually converting the iframe URLs to https:// and adding `?html5ui`, but that's hardly sustainable. We would greatly appreciate it if you guys could fix this in the wagtail.embeds code.

**Comment by chosak** [comment]
@coredumperror Wagtail uses the Ustream oEmbed API to generate Ustream embeds. Your first item seems to be a bug in Ustream's oEmbed API, and isn't related to Wagtail specifically. For your second item, I'm not sure there's a way to generate an `?html5ui` URL via the Ustream oEmbed API.

For example, these two requests return the same embed content:

```sh
$ curl 'https://www.ustream.tv/oembed?url=https%3A//www.ustream.tv/recorded/41329664'
{"provider_url":"http:\/\/www.ustream.tv\/","html":"<iframe width=\"480\" height=\"302\" src=\"http:\/\/www.ustream.tv\/embed\/recorded\/41329664\" scrolling=\"no\" frameborder=\"0\" style=\"border: 0px none transparent;\"><\/iframe><br \/>","title":"Billick's Power Rankings - Week 14","author_name":"FOXsports","height":320,"thumbnail_width":120,"width":400,"version":"1.0","author_url":"http:\/\/www.ustream.tv","thumbnail_url":"https:\/\/ustvstaticcdn1-a.akamaihd.net\/images\/uphoto_file\/1\/1\/1\/3\/111388\/th\/smalls2_120_111388_fox-sports-140x140_1358183530.jpg","type":"video","thumbnail_height":90}
```

```sh
$ curl 'https://www.ustream.tv/oembed?url=https%3A//www.ustream.tv/recorded/41329664?html5ui'
{"provider_url":"http:\/\/www.ustream.tv\/","html":"<iframe width=\"480\" height=\"302\" src=\"http:\/\/www.ustream.tv\/embed\/recorded\/41329664\" scrolling=\"no\" frameborder=\"0\" style=\"border: 0px none transparent;\"><\/iframe><br \/>","title":"Billick's Power Rankings - Week 14","author_name":"FOXsports","height":320,"thumbnail_width":120,"width":400,"version":"1.0","author_url":"http:\/\/www.ustream.tv","thumbnail_url":"https:\/\/ustvstaticcdn1-a.akamaihd.net\/images\/uphoto_file\/1\/1\/1\/3\/111388\/th\/smalls2_120_111388_fox-sports-140x140_1358183530.jpg","type":"video","thumbnail_height":90}
```

In both cases, the iframe source is http://www.ustream.tv/embed/recorded/41329664 (no `?html5ui` and, as you observe, the iframe URL is http, not https). 

As an alternative to oEmbed, Wagtail supports using the (paid) Embed.ly service, which does seem to support HTML5 video. See for example [this demo link](https://embed.ly/code?url=https%3A%2F%2Fwww.ustream.tv%2Frecorded%2F41329664) that shows how Embed.ly renders a  Ustream video as HTML5 (also properly using HTTPS). I haven't tried this but it might be the case that using `wagtail.embeds.finders.embedly` as your embed finder might work for this case (see docs [here](http://docs.wagtail.io/en/v2.1/advanced_topics/embeds.html#embed-ly)).

Another alternative would be to implement a custom Ustream embed finder as documented [here](http://docs.wagtail.io/en/v2.1/advanced_topics/embeds.html#custom-embed-finder-classes); this would require writing the iframe HTML yourself per [the Ustream API documentation](https://support.video.ibm.com/hc/en-us/articles/207851927-Using-URL-Parameters-and-Embed-API-for-Custom-Players).

**Comment by coredumperror** [comment]
I was not aware that I could write custom code for this. I'll look into that approach. Thanks!

**Comment by coredumperror** [comment]
For anyone who's interested in how I solved this, here's the code I added in `core/embeds.py`:

```
import re
from wagtail.embeds.finders.oembed import OEmbedFinder


class UStreamFinder(OEmbedFinder):
    """
    This custom extension of Wagtail's default OEmbedFinder replaces the output of Ustream's broken and out of date
    OEmbed provider with custom iframe code that actually works.
    """

    def find_embed(self, url, max_width=None):
        embed_dict = super().find_embed(url, max_width)

        video_id = url.split('/')[-1]
        # Replace the src URL with a slightly different one, which uses the HTML5 player instead of Flash.
        new_url = f'https://www.ustream.tv/embed/recorded/{video_id}?html5ui'
        embed_dict['html'] = re.sub(r'src="([^"]+)"', f'src="{new_url}"', embed_dict['html'])
        # Also add the allowfullscreen settings that Ustream's default embed codes include, which enables fullscreen.
        embed_dict['html'] = embed_dict['html'].replace(
            'scrolling="no"', 'scrolling="no" allowfullscreen webkitallowfullscreen'
        )

        return embed_dict

embed_finder_class = UStreamFinder
```

I then set this in settings.py:

```
WAGTAILEMBEDS_FINDERS = [
    # Tells Wagtail to prefer our own custom EmbedFinder, in core/embeds.py, specifically for the Ustream provider.
    {
        'class': 'core.embeds',
        'providers': [ustream],
    },
    # Everything else uses Wagtail's default EmbedFinder.
    {
        'class': 'wagtail.embeds.finders.oembed'
    },
]
```
