### ISSUE TITLE
Unable to remove scheduled revisions for non-live pages.

### ISSUE THREAD

**Issue by richbrennan** [wagtail/wagtail#4657]
### Issue Summary

When a page is added and the first publication is scheduled for a date in the future, an admin user is unable to cancel the scheduled revision due to a 403 Forbidden error.

### Steps to Reproduce

With a working Wagtail installation:

1. Create a new page
2. Set a future Go live date
3. Publish
4. Go to revisions screen of new page
5. Click Cancel Scheduled Revision

The [view](https://github.com/wagtail/wagtail/blob/b4a2e13cb02c8c11368b3639b887066d8a3d306f/wagtail/admin/views/pages.py#L1157) that cancels scheduled revisions calls the [can_unpublish()](https://github.com/wagtail/wagtail/blob/b4a2e13cb02c8c11368b3639b887066d8a3d306f/wagtail/core/models.py#L1741) method on the `PagePermissionTester`. The `can_unpublish()` method returns `False` if the page is live, which it isn't as it hasn't been published yet.

### Technical details

* Python version: 3.6.4
* Django version: 2.0.4
* Wagtail version: 2.0.1
* Browser version: Chrome 67

**Comment by gasman** [comment]
Fixed in #4669
