### ISSUE TITLE
Upgrade CircleCI from 1 to 2

### ISSUE THREAD

**Issue by tomdyson** [wagtail/wagtail#4661]
We're using version 1 of CircleCI for CI on the Wagtail project. According to [their docs](https://circleci.com/docs/1.0/language-python/) August 31st 2018 will be the final day for 1.0 builds.

We'll need to port our CircleCI config from 1.0 to 2.0, following these instructions:

https://circleci.com/docs/2.0/migrating-from-1-2/

**Comment by NDevox** [comment]
I've been doing a fair bit of circleci 2 recently and the config isn't complex, can move it over for you if you want.

**Comment by gasman** [comment]
@NDevox Yes please - that'd be really helpful!

**Comment by gasman** [comment]
Completed in #4712.
