### ISSUE TITLE
Automatic image quality/size

### ISSUE THREAD

**Issue by Speedy1991** [wagtail/wagtail#4663]
This is just an idea, and want to share some thoughts.

Cropping the image to a fixed size could be improved. E.g. a device with `1024x1280` will never render a image with higher resolution (e.g. `3840x2160`) and just burn cpu and waste data. 

It would be great if it's possible to have a dynamic way to archive this.
To keep things simple i'm thinking about creatinging a function which calculates a max image resolution on the users max device size.

E.g. a user hits a template with a `1024x1280` device and a `{% image page.photo width-2048 %}` is specified in the themplate, the function will render it with `width-1280` but keep the ratio

Maybe the image quality can be adjusted too

What do you think about this feature?

**Comment by giohappy** [comment]
I think there would to many cached images if it depends on the currently requested width. Maybe a set of fixed width would be better, like it's normally done for responsive images (e.gn based on media queries). Wordpress and many others adopt this approach.

**Comment by Speedy1991** [comment]
Thanks for your feedback!

Yea i was planing to make containers with 25px

E.g matching all images from 1000-1025 (which would be picked by 1024)

**Comment by thibaudcolas** [comment]
What you're describing sounds a lot like the `picture` element or the `srcset` attribute for `img`, which support for is discussed in #285. I'll close this in favour of that existing issue, let me know if you disagree.
