### ISSUE TITLE
Exactly 0 or 1 blocks of a particular kind in the admin area

### ISSUE THREAD

**Issue by kalsan** [wagtail/wagtail#4672]
I'm currently building a Wagtail model for the website of a student association. We need:

- a single field in the admin area that accepts:
  - exactly one list of:
    - an arbitrary number of `ImageChooserBlock` objects
- a second single field that accepts:
  - exactly zero or one of a particular `StructBlock` instance.

The attributes `min_num`, `max_num` and `block_counts` of `StructBlock` are clearly not satisfactory, since they only take effect upon validation... this is not understandable by our users.

The issue #2048 seems closely related to this wish. Despite the fact that it is three years old, the problem seems unresolved. However I can't really believe that no solution or workaround has been found in the meantime.

Did I miss anything or is this really impossible to achieve with Wagtail?

**Comment by gasman** [comment]
Hi @kalsan,
Enforcing `min_num` / `max_num` on the client side will be implemented as part of the work on unifying StreamField and InlinePanel UX in #4473.

**Comment by kalsan** [comment]
Thanks for your fast reply. I'm looking forward to try out the new version(s). Wagtail is really really promising and I think this will increase its value once more significantly.
