### ISSUE TITLE
Release 2.1.2?

### ISSUE THREAD

**Issue by jaroel** [wagtail/wagtail#4677]
Hi,

Could we get 2.1.2 released with the unidecode changes from https://github.com/wagtail/wagtail/pull/4618 ?

This would allow us to run Wagtail and Oscar in the same Django install, without depending on a source checkout.

Thanks up front!

Also see https://github.com/django-oscar/django-oscar/issues/2767

**Comment by gasman** [comment]
Hi @jaroel - are you sure a new Wagtail release is needed for this? As far as I'm aware, if you specify a Unidecode version in your project's requirements, that should override the Wagtail dependency.

(Either way, there'll hopefully be a 2.2 release candidate out later this week.)

**Comment by jaroel** [comment]
@gasman,
The 2.2 release would do just fine, thanks!

Side note:
Unfortunately not; the versions specifiers are checked on install. ie when running `python setup.py install`.
```
from setuptools import setup, find_packages

# neither work
install_requires: list = ["django-oscar", "wagtail"]
# ->  Unidecode 0.4.21 is installed but Unidecode<1.1,>=1.0 is required by {'django-oscar'}
install_requires: list = ["django-oscar", "wagtail", "Unidecode<2,>=1.0"]
# ->Unidecode 1.0.22 is installed but Unidecode<1.0,>=0.04.14 is required by {'wagtail'}

setup(
    name="snuk",
    version="0.1.0",
    author="Roel Bruggink",
    author_email="roel@jaroel.nl",
    description="",
    packages=find_packages(),
    python_requires=">=3.6",
    install_requires=install_requires,
)

```
