### ISSUE TITLE
Wagtail can only handle one datetime, not a list of datetimes

### ISSUE THREAD

**Issue by Meteor0id** [wagtail/wagtail#4687]
### Issue Summary

Attempting to make migrations before starting my first app. Ran into the following error:

File "/srv/webroot/Env/testsite/lib/python3.5/site-packages/wagtain/admin/datetimepicker.py", line 36, in to_datetimepicker_format
php_format_string = php_format_string_replace(py, php)
AttributeError: 'list' object has no attribute 'replace'

### Steps to Reproduce

1. Edit models.py and make sure to add a list of datetime formats as described at https://docs.djangoproject.com/en/2.0/ref/settings/#std:setting-DATE_INPUT_FORMATS
(according to http://docs.wagtail.io/en/latest/advanced_topics/settings.html)
2. ./manage.py migrate
3. Let me know if you were able to reproduce it, if not I will add more details.

### Technical details

* Python version:  3.5.3
* Django version: 2.0.5
* Wagtail version: 2.0.1

**Comment by Meteor0id** [comment]
Hold on! Dont bother to reproduce just yet. Imight have an error in my settings causing this. Will let know soon.

**Comment by Meteor0id** [comment]
Relevant wagtail documentation shows an odd example with appending dots. Never seen such format. Might be an error in the docs? Either way, my list seems valid to me, it is following Django's docs. I don't see why Wagtail would have issues with it.

**Comment by gasman** [comment]
Hi @Meteor0id,
I think you're misreading the docs: `WAGTAIL_DATETIME_FORMAT` must be a single string, indicating the format to be displayed within the date picker, _and_ this string must be one of the items listed in the `DATETIME_INPUT_FORMATS` setting. Nothing in the Wagtail docs says that `WAGTAIL_DATETIME_FORMAT` accepts a list, and this is consistent with Django's own `DATETIME_FORMAT` setting.
