### ISSUE TITLE
JS error in admin upgrading from 2.0rc1 to 2.0.1/2.1.1

### ISSUE THREAD

**Issue by NDevox** [wagtail/wagtail#4696]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I recently upgraded my wagtail installation from 2.0rc1 to 2.1.1, and subsequently down to 2.0.1.

On both non RC releases I found the JS failing when trying to use the StreamField in the Admin.

The JS error is:

```
Uncaught TypeError: Cannot read property 'parentNode' of null
    at Object._ [as initEditor] (draftail.js:1)
    at <anonymous>:1:17
    at t.activateScript (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at t.run (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at HTMLScriptElement.<anonymous> (rocket-loader.min.js:1)
```

I've cleared the cache, deleted and rebuilt the static files etc. The problem still persists.

Cycling back down to the RC version solves this but is obviously not a long term solution.

### Steps to Reproduce

I have the project open source here: https://gitlab.com/ndevox/nick.sarbicki.com with a Dockerfile.

Currently rolled back to the RC version of wagtail.

### Technical details

* Python version: 3.6.
* Django version: 2.0.2.
* Wagtail version: 2.+ (non RC).
* Browser version: Chrome 67.

Is this a know issue?

**Comment by thibaudcolas** [comment]
Hey @NDevox, thanks for taking the time to report this.

Looking at the stack trace you provided, the error happens on the initialisation of rich text fields (`draftail.js`) – however it also mentions `rocket-loader.min.js`, which isn't part of Wagtail. Would that be [Cloudflare's Rocket Loader feature](https://blog.cloudflare.com/too-old-to-rocket-load-too-young-to-die/)? If so, could you try out your site with that turned off to see if you still get the error?

If it's indeed this Cloudflare optimisation, I wouldn't be surprised if it caused the issue by loading the JS differently from what Wagtail intends. We did change how rich text fields are initialised around the 2.0 release (a35831ce8f12924f8244a95a2870a22d5cc9f15f, 0ce10bd294676e2fb8032a2427f2d82f2a486926), to rely on script location via `document.currentScript`, and from what I could read about Cloudflare's implementation that's something they might not support.

**Comment by thibaudcolas** [comment]
👌 my guess would be that it fails on the last line of this snippet: https://github.com/wagtail/wagtail/blob/0161f2664b8968b6d5649074d3d044a312f1f1c9/client/src/components/Draftail/index.js#L53-L64

If that's not because of the static file serving via rocket loader, then it means that for some other reason the init code fails to find the field based on `selector`. To troubleshoot this you could add a breakpoint in the browser devtools at the start of the function, and look at the values of `selector` and `context` (and potentially `field` too).

**Comment by NDevox** [comment]
Possibly!

Having turned everything back on now it's all working perfectly. Rocket loader is being loaded as well.

Looks like it was something in the way I was managing static files before which whitenoise has fixed.

I'm closing this for now although I wouldn't call it fixed as much as it is covered up by myself...

**Comment by thibaudcolas** [comment]
👍 glad you made it work.
