### ISSUE TITLE
Page's get_full_url does not consider the port part

### ISSUE THREAD

**Issue by Marcnuth** [wagtail/wagtail#4697]
For a page model, if you try to call its function of get_full_url, the result will not include the port in the url even if the server running on a port like 8080 or something else.

**Comment by gasman** [comment]
Hi @Marcnuth,
Did you set the relevant port number under Settings -> Sites?

**Comment by gasman** [comment]
Will close this issue for now, as I assume the config under Settings -> Sites is the issue - let me know if not, and we can reopen / investigate further.
