### ISSUE TITLE
No migrations to apply (Wagtail 1.13.2 + Postgres)

### ISSUE THREAD

**Issue by optimum-web** [wagtail/wagtail#4706]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
root@b62005f63134:/app# python manage.py migrate
Operations to perform:
  Apply all migrations: (none)
Running migrations:
  No migrations to apply.

### Steps to Reproduce
Followed instructions and created a project
`
root@b62005f63134:/app# pip install wagtail==1.13.2
Requirement already satisfied: wagtail==1.13.2 in /usr/local/lib/python3.6/site-packages (1.13.2)
Requirement already satisfied: djangorestframework<3.7,>=3.1.3 in /usr/local/lib/python3.6/site-packages (from wagtail==1.13.2) (3.6.4)
Requirement already satisfied: django-taggit<1.0,>=0.20 in /usr/local/lib/python3.6/site-packages (from wagtail==1.13.2) (0.22.2)
Requirement already satisfied: Pillow>=2.6.1 in /usr/local/lib/python3.6/site-packages (from wagtail==1.13.2) (5.2.0)
Requirement already satisfied: django-modelcluster<4.0,>=3.1 in /usr/local/lib/python3.6/site-packages (from wagtail==1.13.2) (3.1)
Requirement already satisfied: html5lib<1,>=0.999 in /usr/local/lib/python3.6/site-packages (from wagtail==1.13.2) (0.999999999)
Requirement already satisfied: Willow<1.1,>=1.0 in /usr/local/lib/python3.6/site-packages (from wagtail==1.13.2) (1.0)
Requirement already satisfied: beautifulsoup4>=4.5.1 in /usr/local/lib/python3.6/site-packages (from wagtail==1.13.2) (4.6.0)
Requirement already satisfied: Django<1.12,>=1.8.1 in /usr/local/lib/python3.6/site-packages (from wagtail==1.13.2) (1.11.14)
Requirement already satisfied: Unidecode>=0.04.14 in /usr/local/lib/python3.6/site-packages (from wagtail==1.13.2) (1.0.22)
Requirement already satisfied: requests<3.0,>=2.11.1 in /usr/local/lib/python3.6/site-packages (from wagtail==1.13.2) (2.19.1)
Requirement already satisfied: django-treebeard<5.0,>=3.0 in /usr/local/lib/python3.6/site-packages (from wagtail==1.13.2) (4.3)
Requirement already satisfied: pytz>=2015.2 in /usr/local/lib/python3.6/site-packages (from django-modelcluster<4.0,>=3.1->wagtail==1.13.2) (2018.5)
Requirement already satisfied: webencodings in /usr/local/lib/python3.6/site-packages (from html5lib<1,>=0.999->wagtail==1.13.2) (0.5.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.6/site-packages (from html5lib<1,>=0.999->wagtail==1.13.2) (40.0.0)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from html5lib<1,>=0.999->wagtail==1.13.2) (1.11.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests<3.0,>=2.11.1->wagtail==1.13.2) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests<3.0,>=2.11.1->wagtail==1.13.2) (2018.4.16)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests<3.0,>=2.11.1->wagtail==1.13.2) (1.23)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests<3.0,>=2.11.1->wagtail==1.13.2) (2.7)
`

in base.py  I have 
`
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.environ.get('DATABASE_NAME'),
        "HOST": os.environ.get('DATABASE_HOST'),
        "USER": os.environ.get('DATABASE_USER'),
        "PASSWORD": os.environ.get('DATABASE_PASS'),
    }
}`

Here is the problem 

root@b62005f63134:/app# python manage.py migrate
Operations to perform:
  Apply all migrations: (none)
Running migrations:
  No migrations to apply.
root@b62005f63134:/app# ls -la
total 28
drwxr-xr-x 1 root root 4096 Jul 25 11:15 .
drwxr-xr-x 1 root root 4096 Jul 25 10:15 ..
drwxr-xr-x 5 root root 4096 Jul 24 12:33 app
drwxr-xr-x 4 root root 4096 Jul 24 12:33 home
-rwxr-xr-x 1 root root  308 Jul 24 12:33 manage.py
-rw-r--r-- 1 root root   39 Jul 24 12:33 requirements.txt
drwxr-xr-x 3 root root 4096 Jul 24 12:33 search

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

* Python version: Run `python --version`.
Python 3.6.6 (default, Jul 17 2018, 11:12:33)
[GCC 6.3.0 20170516] on linux
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
root@b62005f63134:/app# pip show django | grep Version
Version: 1.11.14
* Wagtail version: Hover over the Wagtail bird in the admin, or run `pip show wagtail | grep Version:`.
1.13.2
* Browser version: You can use http://www.whatsmybrowser.org/ to find this out.

**Comment by gasman** [comment]
Hi @optimum-web - please can you give the complete sequence of steps you took after running `pip install wagtail==1.13.2`?

**Comment by optimum-web** [comment]
one more thing,  I use wsgi.py  , not "python manage.py runserver" , not sure if this is important

**Comment by gasman** [comment]
Do you have any other Wagtail installations on the same server? Is it possible that `os.environ.get('DATABASE_NAME')` is returning some other database name where migrations have already been applied?

**Comment by optimum-web** [comment]
No,  I checked it with env command.  There are no other DB's

**Comment by optimum-web** [comment]
Otherwise, I would receive db connection error.  In wagtail db  I see only one table  

$ psql
psql (10.4 (Debian 10.4-2.pgdg90+1))
Type "help" for help.

postgres=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges

 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres
  +
           |          |          |            |            | postgres=CTc/postgr
es
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres
  +
           |          |          |            |            | postgres=CTc/postgr
es
 wagtail   | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
(4 rows)

postgres=# \c wagtail
You are now connected to database "wagtail" as user "postgres".
wagtail=# \dt
              List of relations
 Schema |       Name        | Type  |  Owner
--------+-------------------+-------+---------
 public | django_migrations | table | wagtail
(1 row)

wagtail=#

**Comment by optimum-web** [comment]
Looks like no fixtures can be found for some reason.  No idea.

**Comment by optimum-web** [comment]
Ok, I think I found out the problem. I created a new app and my  base.py config file is very different to default one and looks like missing important settings.  One minute ..

**Comment by optimum-web** [comment]
@gasman  thank you for quick response
