### ISSUE TITLE
Feature request: When moving pages, filter out impossible targets

### ISSUE THREAD

**Issue by Cward-morris** [wagtail/wagtail#4707]
### Issue Summary

When moving content, such as article pages into section pages it is hard for our users to find the available options they can move it in to. Our users have a lot of content and the list of available options can have 10-50 pages of unavailable selections for our users to move the articles in to. The current option is to click "Next" until they find the page they can select. The available options for our users are located on the last page of this list of options. We would like a way to move the available options to the front of the list that contains all the places they can place the content. Another option would be to add a search bar when moving content so the user can easily find the place they are looking for. 

### Steps to Reproduce

1. Go into your homepage
2. Go into the subsection of one the Parent Section pages that are on the Homepage 
3. Click more and move an article
4. From here click to go to the subsection of the Home page
5. Click to go to the subsection of a section page

### Technical details

* Python version: 3.5.4
* Django version: 1.11.13
* Wagtail version: 1.13.1
* Browser version:  Chrome 67.0.3396.79
![image](https://user-images.githubusercontent.com/41692504/43228893-e2982f14-9030-11e8-9c4c-60029dc43549.png)

![image](https://user-images.githubusercontent.com/41692504/43228914-f10f361e-9030-11e8-9d2a-d680847d9922.png)

![image](https://user-images.githubusercontent.com/41692504/43228939-0a5dfcc2-9031-11e8-8523-64309d22fb5f.png)

**Comment by thibaudcolas** [comment]
I believe this is solved by #8689 / #8647, which changes the "Move" UI to use the page chooser. This is still not sortable / filter-able, but covers the "search" alternative mentioned by @Cward-morris.

It’d still be great to add filters and sorting to the page chooser – which is covered by #8557.
