### ISSUE TITLE
Error message received when InlinePanel nested within InlinePanel:  SomeObject object has no attribute 'formsets'

### ISSUE THREAD

**Issue by DanAtShenTech** [wagtail/wagtail#4708]
### Issue Summary

I have a `SiteInfo` record set up to hold various information for a site including groups of footer links.  `FooterLinkGroup` items can be added/edited successfully and are set up to be edited via an `InlinePanel`.  I also have a `FooterLink` object to hold the individual links, and it foreign keys to `FooterLinkGroup`.  `FooterLink` is set up to be edited within a `FooterLinkGroup` also via an `InlinePanel`, but this generates the error message:  'FooterLinkGroupForm' object has no attribute 'formsets'.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py as follows with `# InlinePanel('links')` in place as shown...

```
from wagtail.core.models import Site, Orderable
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel
from wagtail.snippets.models import register_snippet


@register_snippet
@python_2_unicode_compatible
class SiteInfo(ClusterableModel):
    site = models.OneToOneField(Site, null=True, on_delete=models.SET_NULL)

    panels = [
        InlinePanel('footer_link_groups', label="Footer Links Group")
    ]
    

class FooterLinkGroup(ClusterableModel, Orderable):
    site_info = ParentalKey('SiteInfo', related_name='footer_link_groups')
    title = models.CharField(max_length=100, default='', verbose_name='Group Title')

    def __str__(self):
        return '{}'.format(self.title)

    panels = [
        MultiFieldPanel([
            FieldPanel('title'),
            # InlinePanel('links')
        ])
    ]


class FooterLink(Orderable):
    footer_link_group = ParentalKey('FooterLinkGroup', related_name='links')
    title = models.CharField(max_length=30, default='')
    url = models.URLField(default='')

    def __str__(self):
        return '{}'.format(self.name)

    panels = [
        FieldRowPanel([
            FieldPanel('title'),
            FieldPanel('url')
        ])
    ]
```

3. After the above is working, uncomment `# InlinePanel('links')`

4. Re-run and produce this error:  'FooterLinkGroupForm' object has no attribute 'formsets'

I was hoping to be able to enter/edit footer groups in the above manner, but it seems that nesting an `InlinePanel` within another `InlinePanel` is causing this error.

### Technical details

* Python version: 3.5.2
* Django version: 2.0.7
* Wagtail version: 2.1.1
* Browser version: Chrome 67

**I would be glad to move this to StackOverflow if that is a better forum.**

**Comment by gasman** [comment]
Hi @DanAtShenTech - thanks for the report. Lack of support for nested inline panels is a known issue, covered by #1952.
