### ISSUE TITLE
Server Error on SideBar

### ISSUE THREAD

**Issue by LuisJLopez** [wagtail/wagtail#4710]
### Issue Summary
This issue is concerning wagtail's sidebar, when a user has been created within the CMS, the Root Page/Pages on the sidebar don't load and the following error appears: `status_code : 403` 
Endpoint : `...cms/api/v2beta/pages/?child_of=1&for_explorer=1`

<img width="880" alt="screen shot 2018-07-31 at 15 39 57" src="https://user-images.githubusercontent.com/17165324/43466710-0cf3ed7e-94d8-11e8-987d-ef4280e23c1b.png">

Response : 

<img width="508" alt="screen shot 2018-07-31 at 16 39 54" src="https://user-images.githubusercontent.com/17165324/43470472-8f902916-94e0-11e8-873e-b2dd90ff21ac.png">

Although it works perfectly when the user has been created from the terminal as superuser which makes me think it might be related to permissions. So I tried with many different users and permissions and allowing access to the Root page too and making him an Admin, but the issue remains. The permission side of thingns still works perfectly and can be accessed by the dashboard :

<img width="1173" alt="screen shot 2018-07-31 at 16 05 22" src="https://user-images.githubusercontent.com/17165324/43468322-90d50364-94db-11e8-861a-a87c90bbadc4.png">

### Steps to Reproduce

After setting up a wagtail project with some lists and detail pages with "HomePage" as Root Parent.
Structure :
(Root)HomePage > (List Page) News > (Detail Page) Articles

1. Create a new Permissions Group.
2. Give Group Page Permission to the Root Page & News (Tried all kind of combinations).
3. Create a new user under `Settings > Users > Add a User`.
4. When creating the user, adding it to the correspondent group.
5. Login as the newly created user.
6. Open sidebar and the error should appear.

### Technical details

* Python version: Run 2.7.10
* Django version: 1.11.13
* Wagtail version: 2.1.11
* Browser version: Tried with Firefox 61 & Chrome 67.

Thank You in Advance !!

**Comment by gasman** [comment]
Hi @LuisJLopez - thanks for the report.

The Python / Wagtail versions you've given don't look correct - there is no Wagtail 2.1.11, and Python 2.7 isn't compatible with Wagtail 2.x. What are the correct versions, please?

**Comment by LuisJLopez** [comment]
Thanks for the quick response @gasman 

The correct wagtail version is 2.1.1
and the Python version is 3.6.3

:)

**Comment by gasman** [comment]
Thanks! Just to confirm, have you been able to replicate this on a fresh installation of Wagtail, or only on your existing project?

**Comment by LuisJLopez** [comment]
Currently only on mi existing project, I will try and reproduce it with a fresh/clean installation !

**Comment by LuisJLopez** [comment]
@gasman from a fresh install there is no issue, so it must be related to the way we have setup the structure within the project, thank you for your help :)

**Comment by udanieli** [comment]
I had the same issue adding wagtail to an existing project. In my case this issue was related to my `rest-framework` project configuration.
If you overrode some of the following settings (children of `REST_FRAMEWORK` dictionary):

* `DEFAULT_AUTHENTICATION_CLASSES`
* `DEFAULT_PERMISSION_CLASSES`

be sure that wagtail can use the `rest_framework.authentication.SessionAuthentication`
