### ISSUE TITLE
Missed unlocalize in wagtailadmin/chooser/browse.js

### ISSUE THREAD

**Issue by einsfr** [wagtail/wagtail#4711]
`USE_THOUSAND_SEPARATOR = True` results in invalid value for `pageData.parentId` in this code block with page ids greater than 999:

Template:
```
/* Set up behaviour of choose-page links, to pass control back to the calling page */
$('a.choose-page', modal.body).on('click', function() {
    var pageData = $(this).data();
    pageData.parentId = {{ parent_page.id }};
    modal.respond('pageChosen', $(this).data());
    modal.close();

    return false;
});
```
Result:
```
/* Set up behaviour of choose-page links, to pass control back to the calling page */
$('a.choose-page', modal.body).on('click', function() {
    var pageData = $(this).data();
    pageData.parentId = 1 844;
    modal.respond('pageChosen', $(this).data());
    modal.close();

    return false;
});
```

Using `unlocalize` filter resolves this issue: `pageData.parentId = {{ parent_page.id|unlocalize }};`

**Comment by gasman** [comment]
Hi @einsfr - thanks for the report!

This has been fixed in Wagtail 2.2 - we now pass `parent_page_id` to the JS within a JSON dict, rather than inlining it with a template tag. 61a04dfb5e73781d162d778aa5f79a3176db7f26
