### ISSUE TITLE
FieldComparison.field_label should pick up labels from InlinePanel

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#4732]
For ParentalKey relations (which don't have a `verbose_name` property), FieldComparison creates a verbose_name from the field name:

https://github.com/wagtail/wagtail/blob/7ad79c9a4a7ec89a7d353db442268f24d08064c6/wagtail/admin/compare.py#L26-L28

This isn't ideal, particularly when `related_query_name` has been set on the relation - see https://github.com/wagtail/wagtail/pull/4579#issuecomment-412932533. It would be better to have InlinePanel pass its own label (if one is supplied) to FieldComparison as part of `InlinePanel.get_comparison`.

**Comment by sandilsranasinghe** [comment]
Is this still open? Can I work on it?

**Comment by lb-** [comment]
Go for it @sandilsranasinghe - please be sure to include unit tests with any PR and reach out if you need a hand.

**Comment by sandilsranasinghe** [comment]
Just a couple of questions, is it okay to add a new default argument to ChildRelationComparison init method? Also should I add new unit tests to test_compare or test_edit_handlers if changing the `InlinePanel.get_comparison` method?

**Comment by lb-** [comment]
@sandilsranasinghe 
The default Arg should be ok - if it can be done in a way that won't break existing usage without it. 

Good call on adding those extra unit tests. 

Thanks
