### ISSUE TITLE
custom information block per model in the editors interface

### ISSUE THREAD

**Issue by Meteor0id** [wagtail/wagtail#4734]
Customizable templates for the editor interface, one for each page model.

Say I set up a website for a small news agency. The news agency wants authors(editors) who are new to the organisation to follow the guidelines on how to write a proper article for their website. It would be helpful to them if they could place some text in the admin interface for a certain page model (Article) in which they explain how they expect an article to be marked up.

So instead of just providing this for only the initial editors interface page, I recommand providing customizable blocks per model. Each page model may have its own additional information in the editor interface. The way to gowould be templates for the editor interface, providing acces to a block {% block editor_information %}{% endblock %}.
Of course that also means those templates would have their own model (palcing the information for the editor interface in the database). We end up with having pages in the editor interface solely to edit information on other pages within the editors interface. I don't think that's an issue, but lets lets proceed carefully and not make things overcomplicated.

**Comment by gasman** [comment]
Hi @Meteor0id,
Wouldn't `HelpPanel` achieve what you want? https://github.com/wagtail/wagtail/pull/4374

**Comment by Meteor0id** [comment]
I see HelpPanel is defined in the docs, but no explanation is included of what it does. In the changelog of wagtail 2.1 I find one sentence hinting what I does.
I will try it out when I get around to it, quite possbily this does achive what I want, I hand't tried that panel type yet.

(will let know in a month or so)

**Comment by tomdyson** [comment]
The linked PR includes screenshots demonstrating HelpPanel in use: 

https://github.com/wagtail/wagtail/pull/4374

There's also a good video tutorial on making the most of help text here:

https://www.youtube.com/watch?v=ciYNMcv3lE0

**Comment by gasman** [comment]
Closing for now... will assume that HelpPanel does the job unless we hear otherwise.
