### ISSUE TITLE
Field 'file_hash' doesn't have a default value

### ISSUE THREAD

**Issue by shimulch** [wagtail/wagtail#4735]
### Issue Summary

New file_hash field in wagtailimages Image model having issue with mysql database (v5.7) when uploading images through wagtail admin.

### Steps to Reproduce

1) Install following version described in Technical Details 
2) Try to upload an image.

After looking into wagtail source it seems like, this issue lies in field definition

```python
file_hash = models.CharField(max_length=40, blank=True, editable=False)
```
Possibly MySQL strict mode is throwing error as no default value has been provided for file_hash
 
### Technical details

* Python version: 3.6
* Django version: 2.0.8
* Wagtail version: 2.1.3
* MySQL version: 5.7

### Stack trace

```
Traceback (most recent call last):
  File ".venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File ".venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File ".venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File ".venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File ".venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File ".venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File ".venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File ".venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1364, "Field 'file_hash' doesn't have a default value")
```

### Possible Solution

For now I have manually altered the database with a default value -
```sql
Alter table wagtailimages_image modify column file_hash varchar(40) not null default '';
```

Field declaration might be like following, so that either a default value is there or null is accepted
```python
file_hash = models.CharField(max_length=40, blank=True, null=True, editable=False)
```
Or
```python
file_hash = models.CharField(max_length=40, blank=True, default='', editable=False)
```

**Comment by gasman** [comment]
Hi @shimulch - thanks for the report.

The `file_hash` field does not exist on Image in Wagtail 2.1.3 - it was added in 2.2. Is it possible that you're running Wagtail 2.1.3 against a database that was created for Wagtail 2.2? This would explain the error you're seeing (since Django would normally supply a default value for the field, but doesn't know about the existence of `file_hash` here).

**Comment by shimulch** [comment]
@gasman You were right. Somehow our pipenv lock file were changed. Which led to different version of wagtail when migrating between servers.

Sorry for not checking out that. Anyway, we love wagtail.

**Comment by patjouk** [comment]
Happened to us too two times: in August and again yesterday. Wagtail is pinned to 2.1.3 in our PIpefile.

**Comment by tombola** [comment]
Also of note, If you have upgraded to/past 2.2, and you have any custom image models you will need to run `makemigrations` to add the file hash for the model.

**Comment by Paluschki** [comment]
> Also of note, If you have upgraded to/past 2.2, and you have any custom image models you will need to run `makemigrations` to add the file hash for the model.

This repaired my incompatible database, which was created with a version <2.2, after upgrade to 2.4
