### ISSUE TITLE
Feature request: Language Tool integration

### ISSUE THREAD

**Issue by Bachstelze** [wagtail/wagtail#4742]
I want to integrate https://github.com/languagetool-org/languagetool a style and grammar checker into the frontend editor like in the demo https://languagetool.org . Have there been dicussions about the integration of such a service?
If not i would welcome some hints for the architecture design of the integration to fit well with the new editor and future development of it.

**Comment by Bachstelze** [comment]
A good starting point would be:
https://github.com/vixdigital/wagtail-plugin-base

**Comment by thibaudcolas** [comment]
👋 Closing in favour of #11063. I agree it’d be cool, but I can’t imagine this specific integration with Language Tool built into Wagtail ever. We would however love to have built-in APIs for people to create those types of integrations as external packages.
