### ISSUE TITLE
Menu crops content at an odd place. 

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#4744]
The left hand menu crops menu content at an odd position. This is causing a usability issue where admin/editors aren't always aware of all of the menu items and the ability to scroll. 

<img width="176" alt="screen shot 2018-08-22 at 12 26 49" src="https://user-images.githubusercontent.com/7290588/44460923-dba77700-a606-11e8-9525-75fd4323fe73.png">

This is due to nav-main element having a seemingly arbitrary bottom margin of 127px. Generally the layout for the menu has been built in a pretty hacky way. We should implement a quick fix but in the long run I think the menu could be rebuilt with UI considerations for when the menu overflows.

**Comment by thibaudcolas** [comment]
I think this is addressed by #4746.

I've tried to refactor the menu's styles many times (while working on the explorer menu's new version, and later on) and agree that they should be redone from the ground up. It looks just fine for a Wagtail site that's just been created, but breaks down as soon as the menu has too much content, or the screen has too little space. It also feels weird on mobile that menu and page do not scroll independently: pages can always scroll as much as the menu is long, even when the menu is closed.

**Comment by Meteor0id** [comment]
Yes, that is exactly what I addressed in my PR #4746. Please pull?

**Comment by thibaudcolas** [comment]
#4746 is merged, this will be fixed in Wagtail v2.4!
