### ISSUE TITLE
Conflicting CurrentSiteMiddleware and SiteMiddleware

### ISSUE THREAD

**Issue by martmatwarne** [wagtail/wagtail#4748]
I'm trying to develop a multisite website that also uses Wagtail. Using the '[django.contrib.sites.middleware.CurrentSiteMiddleware](https://docs.djangoproject.com/en/2.1/ref/contrib/sites/#site-middleware)' doesn't work because it appears to conflict with wagtail.core.middleware.SiteMiddleware as they both set request.site either to the standard django Site model or the Wagtail Site model respectively. As highlighted by the Django docs this isn't a deal breaker as CurrentSiteMiddleware is just a time saver for Site.objects.get_current() but it's possibly worth adding a bit into the documentation to explain this as installing Wagtail in the multisite setup suddenly broke stuff. 

Tested with Django 2.0.7 and Wagtail 2.2.1

**Comment by gasman** [comment]
Thanks for the report @martmatwarne! There's a plan to eliminate Wagtail's `request.site` variable outlined here: https://github.com/wagtail/wagtail/issues/3834#issuecomment-340009510 - it probably makes sense to have some documentation of this in the meantime if this doesn't get implemented in the near future, though.

**Comment by gasman** [comment]
Fixed in #5787
