### ISSUE TITLE
empty RichText fields renders as <p></p>

### ISSUE THREAD

**Issue by dpetrov** [wagtail/wagtail#4750]
### Issue Summary

An empty RichText fields on my models are rendering as `<p></p>` the first time they are saved. If I edit the page again and save it, it renders fine (as empty element).

### Steps to Reproduce

1. `wagtail start myproject`
2. Edit models.py as follows

```
from django.db import models

from wagtail.core.models import Page
from wagtail.core.fields import RichTextField

from wagtail.admin.edit_handlers import FieldPanel

class HomePage(Page):
    pass

class ContentPage(Page):
  body = RichTextField(blank=True)

  content_panels = Page.content_panels + [
    FieldPanel('body'),
  ]
```

3. Add a new page and add title only and render the field as:

```
$ cat home/templates/home/content_page.html
{{ self.body }}

```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Python 3.6.5
* Django version: 1.11.5
* Wagtail version: 2.2.1
* Browser version: whatsmybrowser.org/b/33MFAZT (Chrome 68 OS X)

**Comment by twoblokeswithapostie** [comment]
You need to add richtext filter to your {{ self.body }} tag. Like this {{ self.body|richtext }}. I believe it's located in wagtailcore_tags, but I'd need to check.

**Comment by dpetrov** [comment]
@twoblokeswithapostie that will just render it as HTML, but still will be empty. So I have currently:

```
{% if self.body %}
...
```

which evaluates to true

**Comment by gasman** [comment]
Hi @dpetrov - thanks for the report! I think this is covered by #4549.

**Comment by dpetrov** [comment]
It does indeed, I've missed it somehow. Thanks for pointing it out.
