### ISSUE TITLE
How to allow user to select OR create related entity?

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#4758]
The Django admin allows a user to either select OR create a related entity, via the inline form/modal. Wagtail seems to also have both form elements for selecting or creating related entities, but the docs only show those elements in isolation. 

How can we have an inline relationship page element to allow users to either select an existing entity or create a new one?

**Comment by gasman** [comment]
Creating a new object within a modal is possible for images and documents; adding the same functionality for snippets is addressed by #396.
