### ISSUE TITLE
Creating and deleting models can lead to a broken tree in the database

### ISSUE THREAD

**Issue by Meteor0id** [wagtail/wagtail#4759]
### Issue Summary

On my development server I see my site has records which don't match up. It first occured after deleting a number of pages in Wagtail, thus it is likely a bug within Wagtail.

Looking at the table "wagtailcore_page" , the table does NOT match what is shown in wagtail.

In the attachment, notice that "digitale rechten" is a child of "achtergrond & verdieping", yet numchild indicates 0, where it should be 1.  The path does confirm this page is a child of "achtergrond & verdieping" There might be more errors in other tables.
![wagtail bug numchild incorrect](https://user-images.githubusercontent.com/34976212/44990330-f972c580-af90-11e8-83ed-afff5d63e6f9.PNG)

### Steps to Reproduce
Leading up to all this, I was working on the models. Initially a model "Article" was allowed as subpage_type of "PublicationIndex" ("achtergrond & verdieping" is a publication index). I modified the models by adding two new page models in between. Now the subpage_type for PublicaitonIndex would allow for a type "Theme". The subpage_type for "Theme" would allow a type "Subject", and "Subject" would accept a supage_type "Article". I then ran makemigrations, followed by migrate, which ran succesfully. Now I wanted to get rid of the leftover Articles which were still a direct child of "PublicationIndex".

1. In the CMS I deleted a bunch of pages, some had children some did not. The goal was to delete all sub-pages of "PublicationIndex". 2. All subpages seemed to be deleted, I create a new page of type "Theme". 3. The new page created succesfully, but now the list showed my newly created page AND a page which was meant to be deleted, and did not show up before! 4. I deleted the Article page whihc I had meant to delete. 5. If I try to add another subpage to PublicationIndex, I get
`ValidationError at /cms/pages/add/ffs_article/theme/5/{'path': ['Page with this Path already exists.']}`
Besides that, the earlier added page "DigitaleRechten" (of type "Theme") does not show up anywhere in the CMS, while it does show in the database!

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project:
No. But this issue should certainly not occur anyway. A currupted datatable is severe.

### Technical details

* Python version: 3.7.0
* Django version: 2.0.8
* Wagtail version: 2.1.2
* Browser version: Firefox/61.0.2

**Comment by Meteor0id** [comment]
![migrations leading up to wagtail bug](https://user-images.githubusercontent.com/34976212/44991146-828afc00-af93-11e8-9b7d-432b523e15f9.PNG)

**Comment by Meteor0id** [comment]
![error can be pathed using fixtree](https://user-images.githubusercontent.com/34976212/44991286-e01f4880-af93-11e8-9a06-55ee40058cd4.PNG)

**Comment by tomdyson** [comment]
> No. But this issue should certainly not occur anyway. A currupted datatable is severe.

The requirement to reproduce the issue on a fresh Wagtail project isn't about severity, it's about our ability to fix it. If you can't reproduce it, it's very hard for us to help.

**Comment by Meteor0id** [comment]
By no, I emant I have not tried it yet, because I just havent had the time. I could just write the issue report in a month or so, but by than I would have forgotten de details.
Better to write this up right away, and come back to it when I have time to do more testing, or when someone else encounteres the same issue.

**Comment by gasman** [comment]
@Paulmolin FYI, running `./manage.py fixtree`should be able to fix errors of this type.

**Comment by Paulmolin** [comment]
@gasman Thank you for the tip, I will try this!

I just found out that there was a `find_problems` method in mp_tree. The documentation explains that problems can occur when:

1. your code breaks and you get incomplete transactions (always use transactions!)
2. changing the ``steplen`` value in a model (you must :meth:`dump_bulk` first, change ``steplen`` and then :meth:`load_bulk`

I keep investigating this problem.

**Comment by lb-** [comment]
As there is a documented solution to this and no further feedback on this issue being a problem I will close this. 

Feel free to comment if anyone thinks we should re-open.

**Comment by lypwig** [comment]
I can reproduce this error when dumping and loading a database with natural keys:

```
python manage.py dumpdata --natural-foreign --natural-primary > dump.json
python manage.py flush
python manage.py loaddata dump.json
```

Then, when I try to create a new page from the web ui, I get the error `Page with this Path already exists.` described above.

I tried:

- `python manage.py migrate` -> *No migrations to apply.*
- `python manage.py fixtree --full` -> *Incorrect numchild value found for pages: [5] All problems fixed.* but this does not fix the problem.

Edit: the problem seems to originate from this method in a page model:

```
def get_children(self):
    return super().get_children().order_by("title")
```

If I remove this method, there is no error when creating a new page.

**Comment by gasman** [comment]
@njourdane Unfortunately we can't guarantee correctness if any of the [core django-treebeard methods](https://django-treebeard.readthedocs.io/en/latest/api.html) are overridden - it's likely that django-treebeard is internally performing operations like "increase the path index of all children that come after X in the sequence" which would break if the ordering is customised in this way.
