### ISSUE TITLE
Add "Auto-Submitted: auto-generated" header to outgoing notification emails

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#4763]
Often the email address that Wagtail uses for outgoing notification emails is also a monitored mailbox. If Wagtail sends an email to a user that is on holiday, their email server may send an automated "out of office" response to that mailbox which is useless and could get annoying if there are many Wagtail users.

According to RFC 3834, setting the "Auto-Submitted" header to "auto-generated" should prevent the automatic response from being sent back.

See: https://tools.ietf.org/html/rfc3834#section-5

**Comment by gasman** [comment]
Fixed in #4765
