### ISSUE TITLE
Image Chooser Panel Upload in with Google Chrome

### ISSUE THREAD

**Issue by philipjc** [wagtail/wagtail#4767]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When attempting to save an image to a blog post, for example, I am able to select 'choose an image' from the UI, but when I select one of the images, a Chrome pop-up for 'do you want to leave the page' appears. This does not happen in Firefox.

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Edit models.py as follows...
3. Create the blog tutorial
4. Upload images, and select saif image
5. you should see the pop-up which then takes you to a JSON response page

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

* Python version: Run `python --version`. 
3.6.5
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`. Django==2.0.5
* Wagtail version: Hover over the Wagtail bird in the admin, or run `pip show wagtail | grep Version:`.
wagtail==2.2.2
* Browser version: You can use http://www.whatsmybrowser.org/ to find this out.
Latest

**Comment by gasman** [comment]
Hi @philipjc,
Did you upgrade from an earlier version of Wagtail? It sounds like you have an outdated copy of the file `/static/wagtailadmin/js/modal-workflow.js` cached in your browser - please clear your browser cache and retry.

**Comment by philipjc** [comment]
This is the case, thank you!

**Comment by shredding** [comment]
Can you tell me how to spot the difference in that js? I have the same error but it's not related to the browser cache.

**Comment by shredding** [comment]
... got it. I had to add the `IMAGE_CHOOSER_MODAL_ONLOAD_HANDLERS` to my custom image-chooser.
