### ISSUE TITLE
upgrade to 2.2.2 imagechooserpanel not setting image

### ISSUE THREAD

**Issue by scottb0t** [wagtail/wagtail#4769]
### Issue Summary
After upgrading wagtail to 2.2.2, I am unable to set images with image chooser in admin interface. 
When I try to choose an image, Instead of setting the image foreignkey in the DB it links to the images json information.
e.g. I click on an image in an "imagechooserpanel" and it sends me to "http://site.com/admin/images/chooser/10/" where I see the json describing the image.

### Steps to Reproduce
upgrade from v2.1.3
to 2.2.2

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)
no, I have not yet tried.

### Technical details

Python 3.4.9
Django==2.0.8
wagtail==2.2.2.
Chrome 67

**Comment by gasman** [comment]
Hi @scottb0t,
This is a browser caching issue - you have an outdated copy of the file /static/wagtailadmin/js/modal-workflow.js cached in your browser. Please clear your browser cache and retry.

(duplicate: #4767)

**Comment by scottb0t** [comment]
ahhh... I forgot to collectstatic.
I should have known. Thanks!
