### ISSUE TITLE
Remove '+' button For Streamfield Item if 'max_num' is set

### ISSUE THREAD

**Issue by JaredOzzy** [wagtail/wagtail#4770]
Hi there, i have been working with streamfields quite often recently and thought this would be a nice implementation.

Currently if you set 'max_num' property in the Blocks.py or Models.py on a specific streamfield there will always be a '+' icon with the ability to add a new streamfield item in the CMS, if you add a new item you will then only afterwards get the Validation Error Message.

My suggestion is to remove the '+' by the amount of items currently added on a streamfield, if the 'max_num' property is set.

Thanks!

**Comment by loicteixeira** [comment]
Thank for the suggestion @JaredOzzy.

@BertrandBordage worked on a new UI for StreamField (see #4473 and [noripyt/wagtail-react-streamfield](https://github.com/noripyt/wagtail-react-streamfield)) which should handle this case and hopefully be merged to Wagtail soon.

**Comment by BertrandBordage** [comment]
noripyt/wagtail-react-streamfield is indeed already hiding the + button when max_num is reached!

**Comment by JaredOzzy** [comment]
Great Stuff!
