### ISSUE TITLE
Feature request: Add `prepopulated_fields` support to ModelAdmin

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#4778]
Wagtail's ModelAdmin doesn't support this field, found in Django's ModelAdmin: https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.prepopulated_fields

>When set, the given fields will use a bit of JavaScript to populate from the fields assigned. The main use for this functionality is to automatically generate the value for SlugField fields from one or more other fields.

I have a use case for it in Wagtail, where normal Django models need a slug associated with them.

![screenshot from 2018-09-16 14 03 34](https://user-images.githubusercontent.com/3639540/45599425-515df300-b9b9-11e8-9e4f-546d188ea902.png)

Wagtail does support this, because it automatically fills in the slug for a page. There doesn't seem to be a similar option for ModelAdmin.

**Comment by engineervix** [comment]
Hello there, any feedback on this issue?

**Comment by pySilver** [comment]
I made it work. I'll probably make a PR, but since I'm deeply overloaded it lacks of tests, I'll be glad if someone assist me with tests coverage.

**Comment by pySilver** [comment]
@alexgleason @engineervix feel free to help with #5522 to make this feature happen.

**Comment by Cheradenine** [comment]
I am interested in this feature - but then discovered that the page editor kind of has it already for title and slug fields. I was able to get my custom model to behave this way by tricking it into behaving like a page, because all the page editing javascript is loaded. So I wonder what it would take to do this in a cleaner way, leveraging the functionality that is already there. This doesn't fully mimic django admin. Here is my hack, this code is on my ModelAdmin.

`    def create_view(self, request):
        view = super().create_view(request)
        self._enable_slug_editing(view)
        return view

    def _enable_slug_editing(self, view):
        ''' Tricks the editor into enabling some javascript normally
            used on Page models to sync the title with the slug
        '''
        form = view.context_data['form']
        form.fields['name'].widget.attrs['id'] = 'id_title'
        form.fields['slug'].widget.attrs['id'] = 'id_slug'
`

**Comment by dbramwell** [comment]
@Cheradenine this almost worked perfectly, but when clicking save I got an error `'HttpResponseRedirect' object has no attribute 'context_data'`

Had to add in a check like below:
```
    def create_view(self, request):
        view = super().create_view(request)
        self._enable_slug_editing(view)
        return view

    def _enable_slug_editing(self, view):
        ''' Tricks the editor into enabling some javascript normally
            used on Page models to sync the title with the slug
        '''
        if hasattr(view, 'context_data'):
            form = view.context_data['form']
            form.fields['name'].widget.attrs['id'] = 'id_title'
            form.fields['slug'].widget.attrs['id'] = 'id_slug'
```

**Comment by laymonage** [comment]
I believe this was added in #6386.
