### ISSUE TITLE
Wagtail Sitemaps does not allow for Django Sitemap instances

### ISSUE THREAD

**Issue by mixxorz** [wagtail/wagtail#4785]
### Issue Summary

When adding custom entries as Sitemap instances to Wagtail Sitemaps, it errors out with:

```
TypeError: at /sitemap.xml
issubclass() arg 1 must be a class
```

Caused by this line: https://github.com/wagtail/wagtail/blob/088d3ffc219c6a06a5d3daff7ece2a8c9b92f683/wagtail/contrib/sitemaps/views.py#L23

According to the [Django docs](https://github.com/wagtail/wagtail/blob/088d3ffc219c6a06a5d3daff7ece2a8c9b92f683/wagtail/contrib/sitemaps/views.py#L23),

> The sitemap view takes an extra, required argument: {'sitemaps': sitemaps}. sitemaps should be a dictionary that maps a short section label (e.g., blog or news) to its Sitemap class (e.g., BlogSitemap or NewsSitemap). **It may also map to an instance of a Sitemap class (e.g., BlogSitemap(some_var)).**

### Steps to Reproduce

1. Configure Wagtail Sitemaps
2. Add custom sitemaps via Django-documented way:

```python
from wagtail.contrib.sitemaps.sitemap_generator import Sitemap
from wagtail.contrib.sitemaps.views import sitemap

sitemaps = {
    'wagtail': Sitemap,
    'books': BookSitemap(published=True),
}

urlpatterns = [
    ...
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    ...
]
```

3. Go to `sitemap.xml`

I expect that the usage of the Wagtail sitemap view be identical to the Django sitemap view, as is documented on the [Wagtail docs](http://docs.wagtail.io/en/v2.2.2/reference/contrib/sitemaps.html#sitemap-generator).

### Fix

The fix is relatively simple. Check if the mapping is a class before checking if it's a subclass.

```python
from inspect import is_class

...
    if is_class(sitemap_cls) and issubclass(sitemap_cls, Sitemap):
...
```

The above works in my project.

### Technical details

* Python version: 3.6.3
* Django version: 2.0.4
* Wagtail version: 2.1

**Comment by scroogeT** [comment]
Can you please clarify where in code will I be applying the fix because I cannot get it to work with my project here. I think I must be doing something wrong.

Can you provide more context ?

**Comment by mixxorz** [comment]
I've monkey-patched the offending function `prepare_sitemaps` in my code to resolve this.


```python
from wagtail.contrib.sitemaps.sitemap_generator import Sitemap

# Monkey patch because upstream doesn't support Sitemap instances
# https://github.com/wagtail/wagtail/issues/4785
def prepare_sitemaps(request, sitemaps):
    """Intialize the wagtail Sitemap by passing the request.site value. """
    initialised_sitemaps = {}
    for name, sitemap_cls in sitemaps.items():
        if isclass(sitemap_cls) and issubclass(sitemap_cls, Sitemap):
            initialised_sitemaps[name] = sitemap_cls(request.site)
        else:
            initialised_sitemaps[name] = sitemap_cls
    return initialised_sitemaps


views.prepare_sitemaps = prepare_sitemaps
```

**Comment by zerolab** [comment]
@mixxorz submit a PR?
