### ISSUE TITLE
`update_index` throws `AttributeError` on TableBlock when value is `None`

### ISSUE THREAD

**Issue by inostia** [wagtail/wagtail#4822]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

`update_index` fails on StreamField TableBlock when its value is `None`, due to this line: https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/table_block/blocks.py#L79

Throws `AttributeError: 'NoneType' object has no attribute 'get'`

### Steps to Reproduce

1. Add a StreamField to a page
2. Add a TableBlock and leave it empty
3. Publish the page
4. Run `python manage.py update_index`, you will get a traceback leading to the above `AttributeError`

![image](https://user-images.githubusercontent.com/14210438/47188457-f2a7d400-d2ec-11e8-8f71-527531b8e83d.png)

### Technical details

Wagtail version: 2.2.2

**Comment by lucasmoeskops** [comment]
Ran into same issue, so can confirm!

**Comment by riceyrice** [comment]
Also ran into this. Further, the empty TableBlock is rendered on-page as 'None', which is less serious but more complex to fix.
We've observed this in a draft page which even though more recent revisions had removed the empty block, still caused the overnight `update_index` job to fail.
Workaround to stop search indexing breaking: ```
_tableblock_get_searchable_content = TableBlock.get_searchable_content
def _safe_tableblock_get_searchable_content(self, value):
    if value is not None:
        return _tableblock_get_searchable_content(self, value)
    else:
        return []
TableBlock.get_searchable_content = _safe_tableblock_get_searchable_content
```

**Comment by gasman** [comment]
Fixed in #5757.
