### ISSUE TITLE
Not able to make StreamField as blank

### ISSUE THREAD

**Issue by kuntalk** [wagtail/wagtail#4830]
I want to keep the streamfield as blank, I have given blank and null as true but then also in admin panel it shows as a mandatory field. What is the way to keep it as non-mandatory field?

* Python version: 3.6
* Django version: 2.0
* Wagtail version: 2.2.2

**Comment by gasman** [comment]
This was fixed in 2.13: https://docs.wagtail.io/en/stable/releases/2.13.html#updated-handling-of-non-required-streamfields
