### ISSUE TITLE
Wagtail Bakery 404

### ISSUE THREAD

**Issue by ajostergaard** [wagtail/wagtail#4834]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Welcome to Wagtail’s documentation says: "If you’d like to get a quick feel for Wagtail, [explore the Wagtail Bakery](https://docs.wagtail.io/divio.com/wagtail), a fully-functional interactive demo (hosted at Divio Cloud)." Unfortunately the link is dead.

### Steps to Reproduce

1. Go to https://docs.wagtail.io/en/latest/
2. Click the link explore the Wagtail Bakery
3. Fail to see playground

If it is not possible to bring back the playground and a doc PR removing the paragraph would be welcome let me know...

### Technical details

* Wagtail version: 2.2.2
* Browser version: Firefox 62

**Comment by gasman** [comment]
Hi @ajostergaard - thanks for the report! The link is just missing an `https://`- it should be https://divio.com/wagtail . Will fix that now...

**Comment by gasman** [comment]
Fixed in 38ed301e03b8a955769da207664b6d47cb91b2b0
