### ISSUE TITLE
ImageChooserPanel regression with Django 2.1

### ISSUE THREAD

**Issue by lightstrike** [wagtail/wagtail#4882]
### Issue Summary

Hitting `TypeError: render() got an unexpected keyword argument 'renderer'` when I try to launch an `ImageChooserPanel` inside a stream field block. Seems to have the same root Django issue as identified with [django-autocomplete-light](https://github.com/yourlabs/django-autocomplete-light/issues/1026). Downgrading to Django 2.0.8 seems to have fixed the issue. 

I haven't been able to dig into reproduction steps much yet, wanted to post this in case it helps anyone else debug this issue.

**Comment by gasman** [comment]
Hi @lightstrike,
Are you using the `wagtail-react-streamfield` package? This has a known compatibility issue: https://github.com/noripyt/wagtail-react-streamfield/issues/17

**Comment by lightstrike** [comment]
I am not, using the built-in `ImageChooserPanel` and `ImageChooserBlock`.

Here's what popped up in Sentry:

![screenshot from 2018-10-31 19-37-10](https://user-images.githubusercontent.com/1368742/47829388-77aad880-dd44-11e8-8a6f-c4369b34cbb1.png)

**Comment by gasman** [comment]
What versions of `django-taggit` and Wagtail are you running?

**Comment by lightstrike** [comment]
`wagtail`: `2.3`
`django-taggit`: `0.22.2`

**Comment by gasman** [comment]
That's the problem then - you need to upgrade to django-taggit 0.23.
