### ISSUE TITLE
upload image that name's is ads.jpg

### ISSUE THREAD

**Issue by alfuhigi** [wagtail/wagtail#4885]
Hi everyone !

I am try to upload images has name "ads" but image show blank image as screenshot in jpg or png

## 1
![alt text](https://aljf.s3.amazonaws.com/media/images/2.original.png)

## 2
![alt text](https://aljf.s3.amazonaws.com/media/images/3.original.png)

## 3
![alt text](https://aljf.s3.amazonaws.com/media/images/EF.original.jpg)

**Comment by chosak** [comment]
@alfuhigi do you happen to have an adblocker enabled in your browser? I suspect the filename may be triggering a block if so. Does this same image render if embedded into some other HTML document not served by Wagtail?

**Comment by alfuhigi** [comment]
Oops my fault !

thanks @chosak ! , you are right the adblocker is enabled. it detected images as ads
