### ISSUE TITLE
InlinePanel considers error message as form when handling max_num

### ISSUE THREAD

**Issue by sir-sigurd** [wagtail/wagtail#4889]
### Steps to Reproduce

Using https://github.com/wagtail/bakerydemo:
1. add `min_num=1, max_num=1` to [InlinePanel of Location.hours_of_operation](https://github.com/wagtail/bakerydemo/blob/428092df6d4b764d3769952ef2a6b4949767bae2/bakerydemo/locations/models.py#L173)
2. open any location in admin
3. remove all "hours of operation"
4. click "save draft"
5. there is no "hours of operation" forms and "add" button is disabled

![image](https://user-images.githubusercontent.com/481910/48197081-6716e580-e376-11e8-8cef-b8f186cecd93.png)

It seems that it doesn't work correctly because formset error message which is rendered as `<li>` is counted as form [here](https://github.com/wagtail/wagtail/blob/487f1f47b8a581701694cba40a594955cee01de8/wagtail/admin/static_src/wagtailadmin/js/page-editor.js#L179).

**Comment by sir-sigurd** [comment]
PR: https://github.com/wagtail/wagtail/pull/4957

**Comment by gasman** [comment]
Fixed in #4957
