### ISSUE TITLE
Welcome page shows Wagtail Space UFO

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#4891]
The welcome page shows the Wagtail Space UFO (logo for the [https://wagtail.space](https://wagtail.space/2019/) events). The purpose of this page is to 1) confirm creation of the wagtail project is a success. 2) give the developer pointers what to do next. So an event logo is bit out of context here.

Also, the Wagtail UFO is based on a free image pack that requires attribution. The event uses the complete pack and respects the license with an attribution statement. I'm not sure if the license even applies to the logo, since it is redrawn and mashup with the Wagtail logo, but shipping this UFO Wagtail isn't the best idea.

Technical details; the Wagtail Space UFO image isn't released yet. It lives only on the current master.

I created a replacement egg. It gently rocks like it is about to hatch. I will submit a PR, but created a ticket so the intentions are logged.

<img width="1680" alt="screen shot 2018-11-08 at 22 28 21" src="https://user-images.githubusercontent.com/1969342/48229035-2edbcb00-e3a7-11e8-9266-8b2c1baf2221.png">

**Comment by jjanssen** [comment]
**Animation reference:**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/287422/48263244-c5e76800-e425-11e8-8f06-610b04e09bdb.gif)

**Comment by gasman** [comment]
Fixed in #4892
