### ISSUE TITLE
Bulk delete button on snippets

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#4904]
The snippets interface has gained a bulk delete button recently (https://screenshots.firefox.com/Tfj3Gk0okTr0GMqr/localhost)

This button looks very out of place to me, and has a red hover colour when no snippets are selected (which seems weird to me as the button doesn't do anything in this state).

Could the button be hidden when no snippets are selected? and also moved above the snippets listing?

**Comment by vupham04** [comment]
Hi, if I'm correct, it seems that this problem is fixed in https://github.com/wagtail/wagtail/commit/4abfbf89a0122d67fa8be0f076c97162c9167a88 right? If it's not, I hope I can try to work on it.

**Comment by zerolab** [comment]
Good spot, #4912 was merged, but this issue was missed.
