### ISSUE TITLE
Feature request: Navigation menu editor

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#4910]
# Issue Summary
Sites typically need navigation menus. As such, it is often the job of a content manager to determine the layout of menu items, i.e. how they are hierarchically organized. To my knowledge, Wagtail does not have a 'menu editing' UI.

This is a feature request for a standardized way to define empty menu, e.g. by a WagtailMenu class, that would then appear in the Admin UI under a Menus section. The website developer would, at the same time as defining the menu, write a loop that would render the menu in the desired location in the frontend (e.g. as a dropdown menu). After the menu is defined, a content manager could assign internal and external pages to the menu, organize the hierarchy, and publish revisions to the menu.

**Comment by zerolab** [comment]
Hi @brylie, 

While you are asking for a core-driven approach, I would like to point you towards a contributed extension - https://github.com/rkhleics/wagtailmenus - as it ticks all the boxes for the above. 

I think it is worth making use of the Wagtail module ecosystem, while keeping its core lean and extensible. Wagtail needs a better ecosystem discovery mechanism, on or linked from wagtail.io

**Comment by brylie** [comment]
Ah, thanks for the recommendation. I hadn't found that.

I agree with a lean and extensible core philosophy, but also appreciate when contrib ecosystem gets commitment from core developers around common project needs.

By way of counter-example, I have been working in Meteor.js for about four years. One key thing many projects need is a router. However, the Meteor core developers never committed to maintaining a router as part of the project core, and two competing routers emerged with varying degrees of stewardship/abandonment.

In any case, I really appreciate what Wagtail does offer, and would be excited to see core support for a n ecosystem discovery system (perhaps on par with WordPress plugin manager :-).

**Comment by allcaps** [comment]
Some Wagtail package listings:
- https://pypi.org/search/?c=Framework+%3A%3A+Wagtail
- https://djangopackages.org/grids/g/wagtail-cms/
- https://github.com/springload/awesome-wagtail
- https://github.com/search?q=wagtail
- Your favourite search engine

I also like to point out that not having a default menu solution fits the [Zen of Wagtail](http://docs.wagtail.io/en/v2.0/getting_started/the_zen_of_wagtail.html). A part of the philosophy is:

> Wagtail is not an instant website in a box. You can’t make a beautiful website by plugging off-the-shelf modules together - expect to write code.

This is especially true for the website (frontend). Frontend requirements can vary a lot. Therefore there isn't a single menu solution. I don't find it likely that a contrib module for menu's will happen soon. That would assume that there is a best practice. But there obviously isn't a right way to do it. Only the right way for your needs.

It is very easy to create menu's in Wagtail. Just create a page query.
http://docs.wagtail.io/en/stable/reference/pages/queryset_reference.html#page-queryset-reference

**Comment by brylie** [comment]
Thanks for sharing the links to the Wagtail package listings.

As mentioned by @zerolab, it is worth considering an official package listing effort, similar to those available to the [DjangoCMS](https://marketplace.django-cms.org/en/), [Drupal](https://www.drupal.org/project/project_module), [Joomla!](https://extensions.joomla.org/),  [Mezzanine](http://mezzanine.jupo.org/docs/overview.html#third-party-plug-ins), [TYPO3](https://extensions.typo3.org/) [Wordpress](https://wordpress.org/plugins/), and several other open source CMS projects. I would like to help build such a directory for Wagtail, if permissible.

I agree with the philosophy outlined in the Zen of Wagtail, but recognize there are some shades of grey to how it is interpreted. For example, it could be argued that having a UI for managing menu items, whether from contrib ecosystem or not, would support the idea that "[a] CMS should get information out of an editor’s head and into a database, as efficiently and directly as possible."

**Comment by brylie** [comment]
Thanks for sharing the links to the Wagtail package listings.

As mentioned by @zerolab, it is worth considering an official package listing effort, similar to those available to the [DjangoCMS](https://marketplace.django-cms.org/en/), [Drupal](https://www.drupal.org/project/project_module), [Joomla!](https://extensions.joomla.org/),  [Mezzanine](http://mezzanine.jupo.org/docs/overview.html#third-party-plug-ins), [TYPO3](https://extensions.typo3.org/) [Wordpress](https://wordpress.org/plugins/), and several other open source CMS projects. I would like to help build such a directory for Wagtail, if permissible.

I agree with the philosophy outlined in the Zen of Wagtail, but recognize there are some shades of grey to how it is interpreted. For example, it could be argued that having a UI for managing menu items, whether or not from contrib ecosystem, would support the idea that "[a] CMS should get information out of an editor’s head and into a database, as efficiently and directly as possible."

**Comment by tomdyson** [comment]
Thanks very much for your perspective on this, @brylie. 

While I agree with the 'lean core' approach advocated by @zerolab and @allcaps, your Meteor example is a good reminder of the unintended consequences of purism! More importantly, I think it's easy for Wagtail insiders to overestimate the awareness that newcomers have about the ecosystem. With that in mind, I would love to take you up on your offer of building a package listing directory. Could you scope this out, perhaps as a new ticket, so we can discuss and refine the idea?

**Comment by thibaudcolas** [comment]
Looks like this got duplicated in #7767. That has more recent conversation so I’ll close this now.
