### ISSUE TITLE
Exception for ContentType.get_object_for_this_type() not handled in core/models.py

### ISSUE THREAD

**Issue by litobro** [wagtail/wagtail#4914]
### Issue Summary

Wagtail occasionally produces a "X matching query does not exist." on the live pages of the site. 

### Steps to Reproduce

1. This is a partial migration from an existing site with existing tables. Some of those existing tables are for user forms and are empty. 
2. Start a new app.
3. Edit models.py in an app to have an empty model, in my case it's called "Volunteer" and has standard fields such as email, name, phone_number, etc.
4. Edit models.py and register settings, I used the sample SocialMediaSettings from the docs. I also added blank=True to these models. 
5. Save one of the Social Media URLs.
6. Refresh home page of website.

At this point I receive a matching query does not exist error. The stack trace leads to line 588 of core/models.py. This is called by core/views.py line 17. I haven't had much time to muddle through the wagtail code but it appears as though when trying to find the specific route for the page it goes over all models and fails when a model cannot be identified since it has no records.

As can be seen in the django code: 
https://github.com/django/django/blob/master/django/contrib/contenttypes/models.py
```
def get_object_for_this_type(self, **kwargs):
       """
        Return an object of this type for the keyword arguments given.
        Basically, this is a proxy around this object_type's get_object() model
        method. The ObjectNotExist exception, if thrown, will not be caught,
        so code that calls this method should catch it.
        """
        return self.model_class()._base_manager.using(self._state.db).get(**kwargs)
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)
no (I will hopefully have time to attempt this later today)

### Technical details

* Python version: 3.5.2
* Django version: 2.1.3
* Wagtail version: 2.3
* Browser version: Firefox 63

**Comment by gasman** [comment]
Hi @litobro - thanks for the report. Unfortunately, without specific steps for reproducing this on a fresh Wagtail instance there's not much we can do to investigate this - my best guess is that you've run `dumpdata`/`loaddata` at some point and run into #1366. If you are able to replicate this on a new project, please update and we'll be happy to reopen and investigate further.
