### ISSUE TITLE
Some StreamFields are broken with js initializer errors, but not because of using FieldPanel.

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#4919]
### Issue Summary

When the Settings form on my site is set up to use a StreamField, they appear fine when first rendered, but clicking any of the Block buttons in their UI causes a javascript error. This is the exact same symptoms as #3444 and #1207, but we *are* using `StreamFieldPanel`, so the cause is not due to using `FieldPanel`. This did not happen when I first developed the feature that uses this streamfield.

Here's the full error:
```
Uncaught TypeError: Cannot read property 'initializer' of undefined
    at Object.onInitializeMember (stream.js:87)
    at postInsertMember (sequence.js:102)
    at Object.self.insertMemberAtStart (sequence.js:203)
    at Object.onChooseBlock (stream.js:140)
    at HTMLButtonElement.<anonymous> (stream.js:60)
    at HTMLButtonElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.2.1.min.js:3)
```

### Steps to Reproduce

Here's the offending code:
```
@register_setting(order=1000)
class Settings(BaseSetting, ClusterableModel):
    # We define the Utility Menu as a StreamField because we can't define it like the old header menu, due to Wagtail's
    # lack of support for nested InlinePanels. A StreamField with a Block that contains a Listblock (for the child menu
    # items) is the best way this can be done.
    utility_menu = StreamField(
        [get_block_tuple(UtilityMenuItemBlock(required=False, label='Utility Menu Item'))],
        blank=True
    )

    ...

    ####### FORM CODE #######
    setup_panels = [
        ...
    ]
    analytics_panels = [
        ...
    ]
    theme_and_menu_panels = [
        StreamFieldPanel(
            'utility_menu',
            help_text='You can optionally add a Utiluty Menu to your site, which will appear above the Main Menu in '
                      'the header. The items in this menu can optionally have children.',
        ),
       ...
    ]
    social_media_panels = [
        ...
    ]

    edit_handler = TabbedInterface(
        [
            ObjectList(setup_panels, heading='Setup', classname='set-up'),
            ObjectList(theme_and_menu_panels, heading='Theme and Menus', classname='theme-and-menus'),
            ObjectList(analytics_panels, heading='Analytics', classname='analytics'),
            ObjectList(social_media_panels, heading='Social Media', classname='social-media'),
        ],
    )

    class Meta:
        verbose_name = 'Site Preferences'
```

When I attempt to add a `UtilityMenuItemBlock` to the `utility_menu` field of the Site Preferences form, it triggers that JS error and the entire UI for the streamfield vanishes permanently, until I reload the page. Except for the "+" button, which triggers the error again each time it gets pressed.

Did something subtle change in StreamField in the last few versions of Wagtail? Perhaps it now only works on Page forms? I ask because StreamFields that are defined on our Page models all work fine. It's JUST the one in our Settings model that's busted. Back when I developed the UtilityMenu feature a few months ago, this worked just fine, so I'm quite baffled.

### Technical details

* Python version: 3.6
* Django version: 2.0.5
* Wagtail version: 2.3
* Browser version: Chrome 72

**Comment by gasman** [comment]
Hi @coredumperror - thanks for the report. I can confirm that this can be reproduced on a fresh project with a trivial StreamField in a settings object...

    @register_setting
    class SocialMediaSettings(BaseSetting):
        stuff = StreamField([
            ('text', blocks.CharBlock()),
        ])

**Comment by gasman** [comment]
Oops, looks like I made the same mistake as everyone else and forgot to use StreamFieldPanel :-) Adding this now works as expected:

    @register_setting
    class SocialMediaSettings(BaseSetting):
        stuff = StreamField([
            ('text', blocks.CharBlock()),
        ])

        panels = [
            StreamFieldPanel('stuff'),
        ]

Unfortunately that does mean there's not enough info here to reproduce the issue independently - if you're able to reproduce this on a fresh Wagtail instance, please provide further details and we'll be happy to reopen and investigate further.
