### ISSUE TITLE
Page.copy() not copying many to many fields

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#4920]
Spotted in: https://github.com/wagtail/wagtail/pull/4827

According to [this comment](https://github.com/wagtail/wagtail/blob/1ff6a5003aff7e511d45d03b1371d2da3667eaee/wagtail/core/models.py#L1070) M2M fields should be handled as child objects and therefore the new page should have all the same links as the old one.

**Comment by gasman** [comment]
(marking as Needs Info as this needs to be confirmed with a reproduction / test case)

**Comment by lb-** [comment]
Closing as this is now a duplicate of the newer #4931 

Sorry only saw this after adding all the notes/unit test example to the newer ticket.
