### ISSUE TITLE
'register_page_listing_buttons' can only add a button but not remove one.

### ISSUE THREAD

**Issue by mnowotka** [wagtail/wagtail#4925]
Hello,

First of all, I'm really sorry not to follow a bug template but what I want to describe is not a bug. Also, I can't find any information about a mailing list, slack channel or any other blessed way to reach wagtail developers.

I'm creating a wagtail-based administrative back-end but the front-end is rendered by a separate app consuming the wagtail REST API so in my case "View draft" and "View live" buttons don't make any sense.

This is why I'd like to remove them but I can't find an easy way to do this. The 'register_page_listing_buttons' is especially disappointing because unlike `construct_wagtail_userbar` it doesn't give me an access to existing buttons only allows me to add a new one.

Is there any other simple way to remove those buttons. Would you consider changing the interface of the 'register_page_listing_buttons' hook?

**Comment by zerolab** [comment]
Hey @mnowotka, 

please see https://github.com/wagtail/wagtail#community-support for information on reaching the wider Wagtail community (and the core developers too).

I think this could be a useful addition. IMHO, we should follow the register + construct hooks pattern that `register_admin_menu_item ` and `construct_main_menu` or more recently `register_page_action_menu_item ` + `construct_page_action_menu` (#4781) use. That is, `register_page_listing_buttons` continues to work without a change, only a new `construct_page_listing_buttons` hook would come in play at the very end, allowing final customisations.

**Comment by lb-** [comment]
Resolved in https://github.com/wagtail/wagtail/commit/9cd2fc2c82c1a3bc8fd6cbdda4b89781965719c7
via PR #5421 

Thanks

@zerolab  - regarding your comments about additional hooks, I think this would be good but we should raise a new issue for other gaps to be filled for future work. :)
