### ISSUE TITLE
Improved user experience with ForeignKey field displayed in FieldPanel?

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#4936]
I have a project with the following models:

- Article - inherits Page
- Author - regular Django model with two fields (first and last name)
- ArticleAuthor - many-to-many child of Page with FK to Author (using [InlinePanel](http://docs.wagtail.io/en/v2.0/reference/pages/panels.html#inlinepanel))

When selecting the Author while editing an Article, I am presented with a dropdown select menu of articles. This menu does not seem like it would scale well on a magazine with dozens or hundreds of article authors. Also, the select options seem to be ordered by when the Author was added to django, as opposed to something natural like last name.

# Feature/support request
- how can I set the sort order for the Authors in the select box?
- how can I get an enhanced user experience, similar to the [PageChooserPanel](http://docs.wagtail.io/en/v2.0/reference/pages/panels.html#pagechooserpan) whereby I can browse/search a paginated table of authors via a modal dialogue, with the option of creating a new Author without leaving the Article edit page?

**Comment by brylie** [comment]
On further consider, the desired behavior would be similar to Wagtail snippets. The main difference would be that I added an 'Authors' section to the Wagtail Admin menu, rather than having Authors appear under the Snippets section.

**Comment by lb-** [comment]
Closing this as it is more of a question on how to do something instead of a specific enhancement request.

For anyone viewing this issue, there is also now https://github.com/wagtail/wagtail-generic-chooser which offers a great way to give fully customised chooser views of models.
