### ISSUE TITLE
no such table: main.wagtailcore_page__old

### ISSUE THREAD

**Issue by jwogrady** [wagtail/wagtail#4941]
### Issue Summary

While completing the tutorial started getting this error.

return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: main.wagtailcore_page__old

### Steps to Reproduce

Follow the Extend the HomePage model section in the [tutorial](http://docs.wagtail.io/en/v2.3/getting_started/tutorial.html).

I've started a clean project, performed the migrations... but when I save a post I get a no such table error.

### Technical details

Request Method: POST
Request URL: http://localhost:8000/admin/pages/3/edit/

Django Version: 2.1.4
Python Version: 3.7.1
Installed Applications:
['home',
 'search',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'modelcluster',
 'taggit',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'wagtail.core.middleware.SiteMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']

Traceback:

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/backends/utils.py" in _execute
  85.                 return self.cursor.execute(sql, params)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py" in execute
  296.         return Database.Cursor.execute(self, query, params)

The above exception (no such table: main.wagtailcore_page__old) was the direct cause of the following exception:

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/wagtail/admin/urls/__init__.py" in wrapper
  102.             return view_func(request, *args, **kwargs)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/wagtail/admin/decorators.py" in decorated_view
  34.             return view_func(request, *args, **kwargs)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/wagtail/admin/views/pages.py" in edit
  357.                 submitted_for_moderation=is_submitting,

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/wagtail/core/models.py" in save_revision
  639.             approved_go_live_at=approved_go_live_at,

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py" in create
  651.             return super(RelatedManager, self.db_manager(db)).create(**kwargs)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/models/manager.py" in manager_method
  82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/models/query.py" in create
  413.         obj.save(force_insert=True, using=self.db)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/wagtail/core/models.py" in save
  1433.         super().save(*args, **kwargs)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/models/base.py" in save
  718.                        force_update=force_update, update_fields=update_fields)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/models/base.py" in save_base
  748.             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/models/base.py" in _save_table
  831.             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/models/base.py" in _do_insert
  869.                                using=using, raw=raw)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/models/manager.py" in manager_method
  82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/models/query.py" in _insert
  1136.         return query.get_compiler(using=using).execute_sql(return_id)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py" in execute_sql
  1289.                 cursor.execute(sql, params)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/backends/utils.py" in execute
  100.             return super().execute(sql, params)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/backends/utils.py" in execute
  68.         return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/backends/utils.py" in _execute_with_wrappers
  77.         return executor(sql, params, many, context)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/backends/utils.py" in _execute
  85.                 return self.cursor.execute(sql, params)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/utils.py" in __exit__
  89.                 raise dj_exc_value.with_traceback(traceback) from exc_value

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/backends/utils.py" in _execute
  85.                 return self.cursor.execute(sql, params)

File "/Users/{myuser}/projects/podum/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py" in execute
  296.         return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /admin/pages/3/edit/
Exception Value: no such table: main.wagtailcore_page__old

**Comment by gasman** [comment]
Hi @jwogrady - thanks for the report. This is a new one on me... as far as I can see, a table name ending in `__old` is an internal Django implementation detail when running schema migrations on SQLite databases (see [docs](https://docs.djangoproject.com/en/2.1/topics/migrations/#sqlite), [source code](https://github.com/django/django/blob/196b420fcb0cbdd82970e2b9aea80251bde82056/django/db/backends/sqlite3/schema.py)) so it's not clear why anything outside of running the migration would be referring to that table. My best guess is that your `runserver` task still has a connection to sqlite open from before you ran the migration, and sqlite is somehow rewriting queries to redirect them to what it thinks the 'real' table should be.

Did you have `./manage.py runserver` running in another console window while you ran `./manage.py migrate`? If so, does the problem persist if you stop `runserver` with ctrl+C and then start it again?

If you can attach your current home/models.py file as it stands, and the corresponding migration file (there should be three of them in home/migrations, numbered 0001, 0002 and 0003 - 0003 is the relevant one) that might give us some further clues. Also, please let us know if there are any places where you've departed from the instructions in the tutorial (for example, running it through a 'real' webserver rather than `./manage.py runserver`).

**Comment by jwogrady** [comment]
@gasman thanks for the reply.  I rebooted my computer and started over with a clean project and venv, but still getting the same error.  All I'm doing is 'wagtail start podum', creating the super user, and runserver.  So basically, everything through step #5.  However, saving a draft and publishing triggers the error.  Here is my code. https://github.com/jwogrady/podum

**Comment by Zurnaz** [comment]
I'm getting the same thing on a fresh wagtail setup.

I also found uploading an image using the image tab in admin starts causing errors on the page /admin/images/ with "no such table: main.wagtailimages_image__old"

 [Link to traceback](https://gist.github.com/Zurnaz/d43aba6436900ced408b649d1b8fa87d)

**Comment by k0nG** [comment]
I think this might be related to https://code.djangoproject.com/ticket/29182 ?

**Comment by gasman** [comment]
Thanks @k0nG! I can confirm that I'm seeing this issue as described when running against sqlite 3.26.0. Unfortunately it looks like the only workaround for now is to downgrade to an earlier version of sqlite - presumably there'll be a Django patch release in the next few days to mitigate this.

Will close this issue, then, as it's outside of Wagtail's control.

**Comment by jwogrady** [comment]
@gasman, @k0nG, @Zurnaz thanks for your help. Thought I was going crazy! 

Looks like the brew formula updated to SQLite3 `2.26.0` from `2.25.3` formula 5 days ago; around the time I started getting errors.  So expect anyone who brew installs or updates python will experience the same issue.

```
git log master -- Formula/sqlite.rb
commit bd8259b38c63d0e22610381a730af632f0996fff
Author: BrewTestBot <homebrew-test-bot@lists.sfconservancy.org>
Date:   Sun Dec 2 05:06:51 2018 +0000

    sqlite: update 3.26.0 bottle.

commit bd8259b38c63d0e22610381a730af632f0996fff
Author: BrewTestBot <homebrew-test-bot@lists.sfconservancy.org>
Date:   Sun Dec 2 05:06:51 2018 +0000

    sqlite: update 3.26.0 bottle.

commit 7a073fa3952f824dfbb722edf9183163b9180dc1
Author: Tommy Yang <yt940928@gmail.com>
Date:   Sat Dec 1 16:43:19 2018 -0800

    sqlite 3.26.0
    
    Closes #34692.
    
    Signed-off-by: FX Coudert <fxcoudert@gmail.com>

commit bc7324ff6b2c5e6490b91f39e15a04241e6cf3c1
Author: BrewTestBot <homebrew-test-bot@lists.sfconservancy.org>
Date:   Wed Nov 7 03:08:13 2018 +0000

    sqlite: update 3.25.3 bottle.

commit a63e786868cd381d9fef8a0c61411dfc884c83b0
Author: Chongyu Zhu <i@lembacon.com>
Date:   Wed Nov 7 01:44:25 2018 +0800

    sqlite 3.25.3
    
    Closes #33847.
    
    Signed-off-by: Chongyu Zhu <i@lembacon.com>

commit c1ffadb66f1fe29c05f67d3bbfb9febc3228fca0
Author: BrewTestBot <homebrew-test-bot@lists.sfconservancy.org>
Date:   Wed Sep 26 04:14:38 2018 +0000

    sqlite: update 3.25.2 bottle.
```

**Comment by jwogrady** [comment]
Confirming that rolling back to sqlite to 3.25.3 worked for me.

Here is how I downgraded sqlite on my mac with brew....

```
brew unlink sqlite
brew install --force https://raw.githubusercontent.com/Homebrew/homebrew-core/bc7324ff6b2c5e6490b91f39e15a04241e6cf3c1/Formula/sqlite.rb
```

**Comment by dsreliete** [comment]
I don't know if I am doing something wrong but I downgrade de sqlite3 and the error keeps going on. Does anyone have a solution?

**Comment by jwogrady** [comment]
Did you regenerate the database after the migration?  I recall having to do
that.

On Dec 18, 2018, at 11:16 PM, Eliete da Silva Rodrigues <
notifications@github.com> wrote:

I don't know if I am doing something wrong but I downgrade de sqlite3 and
the error keeps going on. Does anyone have a solution?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wagtail/wagtail/issues/4941#issuecomment-448472384>,
or mute
the thread

**Comment by dsreliete** [comment]
I deleted migrations files and ran comands like: 
```
python manage.py make migrations my_app
python manage.py migrate
```

Still the error persists.  
Then I tried the comand 
`python manage.py migrate my_app zero `

and made another migrations and nothing works. 
Is there another way to do that? please let me know :) 
Thanks in advance

**Comment by jchillerup** [comment]
I'm getting this error in a completely unrelated piece of Django code, just FYI. My feeling is that the problem is upstream, too.

**Comment by gasman** [comment]
@vx1234 As far as I can see, the fix from https://code.djangoproject.com/ticket/29182 has not made it into an actual release of Django yet - the most recent new release was [December 3rd](https://www.djangoproject.com/weblog/2018/dec/03/bugfix-releases/) - so any version of Django that you install at the moment will still be affected.

**Comment by vx1234** [comment]
@gasman Thank you! Your links were useful, allowing me to learn from your investigative process.
I will like to check if you will be able to guide on sqlite roll-back steps for Windows, which is a solution to this problem? Thanks again.

**Comment by nerdoc** [comment]
I can confirm that under the current Django dev (pip install git+https://github.com/django/django.git) The bug is gone. Only migrating to that version runs in an error. But with a fresh DB it works.

    Django==2.2.dev20181231154732

Hopefully this is fixed in Django 2.1.5?

**Comment by gasman** [comment]
The fix for this issue has now been released as part of [Django 2.0.10](https://docs.djangoproject.com/en/2.1/releases/2.0.10/) and [Django 2.1.5](https://docs.djangoproject.com/en/2.1/releases/2.1.5/).

**Comment by Kashyab19** [comment]
@gasman  This is the error i get whenever I try to post a "Post"
![error](https://user-images.githubusercontent.com/22251972/52223667-21fa4500-28cc-11e9-858b-d4f884f47418.JPG)
![error2](https://user-images.githubusercontent.com/22251972/52223677-26266280-28cc-11e9-9921-234fa2cf9187.JPG)

**Comment by pyanishjain** [comment]
tum chutiu to answers nahi pata hote to likte kyu ho fukers
