### ISSUE TITLE
Oembed support for decentralized peertube instances

### ISSUE THREAD

**Issue by fpoulain** [wagtail/wagtail#4944]
Hi,

I would like to extend wagtail/embeds/oembed_providers.py in order to include peertube instances. Btw there is for now more than 300 instances and it will probably grow with years.
See e.g. https://instances.joinpeertube.org

So logically I think we should script the needed stuff to build an extension to oembed_providers.py. It could be quite easy using https://instances.joinpeertube.org/api/v1/instances?start=0&count=5000 with some filtering on heath score.

Defining a peertube provider is also quite easy, see e.g.
```python
{
    'endpoint': 'https://framatube.org/services/oembed',
    'urls': [
        '^https://framatube\\.org/videos/watch/[-a-f0-9]+$',
    ]
}
```

The dear wagtail's maintainer could then update the list automatically at each release and wagtail+peertube users would be happy.

I am interested in providing such a support for wagtail+peertube. What do you think about it?

**Comment by fpoulain** [comment]
Another approach is a specific finder, based on URI filtering rather than on url/fqdn. Here follows one I quickly did:

```python
import json
import re
from urllib.parse import urlparse
from urllib import request as urllib_request
from urllib.error import URLError
from urllib.parse import urlencode
from urllib.request import Request

from wagtail.embeds.finders.base import EmbedFinder
from wagtail.embeds.exceptions import EmbedNotFoundException

uuid = r'[0-9a-fA-F]{8}(-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}$'


class PeertubeFinder(EmbedFinder):
    def accept(self, url):
        uri = urlparse(url).path
        return re.match('^/videos/watch/' + uuid, uri)

    def find_embed(self, url, max_width=None):
        parse_result = urlparse(url)
        endpoint = "{}://{}/services/oembed".format(
                parse_result.scheme, parse_result.netloc)

        # Work out params
        params = {}
        params['url'] = url
        params['format'] = 'json'
        if max_width:
            params['maxwidth'] = max_width

        # Perform request
        request = Request(endpoint + '?' + urlencode(params))
        request.add_header('User-agent', 'Mozilla/5.0')
        try:
            r = urllib_request.urlopen(request)
        except URLError:
            raise EmbedNotFoundException
        oembed = json.loads(r.read().decode('utf-8'))

        # Return embed as a dict
        return {
            'title': oembed['title'],
            'author_name': oembed['author_name'],
            'provider_name': oembed['provider_name'],
            'type': oembed['type'],
            'thumbnail_url': oembed['thumbnail_url'],
            'width': oembed['width'],
            'height': oembed['height'],
            'html': oembed['html'],
        }


embed_finder_class = PeertubeFinder
```

What do you think about it?

**Comment by gasman** [comment]
Thanks for the suggestion @fpoulain! As this is probably a fairly "niche" interest, I'd suggest implementing it as an installable add-on package outside of Wagtail itself - that way, it can be developed and improved independently of Wagtail's release cycle. I'm happy to hear other opinions about whether peertube support should be part of core Wagtail, though.
