### ISSUE TITLE
Change Page Type UI

### ISSUE THREAD

**Issue by Collederas** [wagtail/wagtail#4949]
### Issue Summary

Cannot change page type after it has been created.

### Steps to Reproduce

1. Create a cutstom Page mode in the models.py of your app. Migrate
2. Create a new page with that type in Wagtail admin.
3. Create a new cutstom Page mode in the models.py of your app. Migrate
4. Try to change the type of your previously created page to this new type. You can't.

This feature would be an incredible improvement.

**Comment by Scotchester** [comment]
Superseded by #7378
