### ISSUE TITLE
Wagtail package directory

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#4955]
## Challenge
Wagtail plugins are a bit hard to discover, as they are scattered across several channels:

- https://pypi.org/search/?c=Framework+%3A%3A+Wagtail
- https://djangopackages.org/grids/g/wagtail-cms/
- https://github.com/springload/awesome-wagtail
- https://github.com/search?q=wagtail
- https://stackoverflow.com/search?q=%5Bwagtail%5D+menu

## Proposal
Lets build an official listing of Wagtail community plugins. 

## Rationale
Having an official 'Wagtail plugins' app, linked to the primary Wagtail website, would help new developers find out what is available to help them build their Wagtail site and user experience.

## Data model
This is a work in progress, and is subject to change through discussion.

The *initial* data model would contain at least the following elements.

### Package
The main entity in the 'package directory'. It could be based on the Wagtail `Page` class, and might have the following fields:

- `title`: name of the package
- `description`: rich text
- `sourcecode_link`: link to a repository page, such as on GitHub or Gitlab
- `support_link`: link to a place where users can get support, such as GitHub/Gitlab issues pages
- `category`: selection of one (or more?) category where this plugin should be listed

### Automated package analytics
Similar to the Django package index, the Wagtail package directory can collect statistics from the upstream sources, such as GitHub. These statistics could be collected via calls to an API, which would probably need a task runner, like Celery.

## Examples for inspiration
- [DjangoCMS](https://marketplace.django-cms.org/en/)
- [Drupal](https://www.drupal.org/project/project_module)
- [Joomla!](https://extensions.joomla.org/)
- [Mezzanine](http://mezzanine.jupo.org/docs/overview.html#third-party-plug-ins)
- [TYPO3](https://extensions.typo3.org/), [Wordpress](https://wordpress.org/plugins/)

## Original discussion
This idea was brought up while discussing issue #4910

**Comment by brylie** [comment]
I will be adding details to the issue description above, that we explore in the process of discussion.

**Comment by brylie** [comment]
One idea that would use some clarification is how we categorize the addons. E.g. should there be a pre-defined, but not immutable, list or hierarchy of categories (like a software trove)? Should there be a more free-form way to categorize, or tag, addons? Should we take a hybrid approach?

**Comment by brylie** [comment]
What might the process be for listing a package in the package directory? Are there a select few users who are responsible for adding packages? Can authenticated users submit a package for review and publication?

**Comment by allcaps** [comment]
I discussed this issue with some core members. This is what we talked about.

First, a Wagtail packages listing site is a good idea.

There are some concerns:
- There are already many listings out there. All with their own twist and focus.
- Keeping the listing up to date is a lot of work. 

We need:
- A low maintenance/crowdsourced solution for the contents.
- Automated aggregation of package statistics.
- The project to be in Wagtail namespace.
- Documentation pointing to the package listing. (for integrators).
- Documentation on how to add your package (for package creators).

We do not really need:
- Submission review or other quality control (leave this to the community)

Having the listing entries under version control seems obvious. This way anyone can contribute via pull requests and we can use our existing infrastructure.

A related RFC of Rust https://github.com/rust-lang/rfcs/blob/master/text/1824-crates.io-default-ranking.md is a good to read and mentions a few interesting solutions:

- https://github.com/djangopackages/djangopackages. unfortunately db based, but easy to contribute too.
- https://github.com/postlight/awesome-cms, generated readme, no filters.
- https://www.libhunt.com/ eg: https://python.libhunt.com/categories/55-cms scrapes awesome lists.

**Comment by brylie** [comment]
> We do not really need submission review or other quality control (leave this to the community)

How should we mitigate spam submissions?

**Comment by allcaps** [comment]
Related 
https://github.com/librariesio/libraries.io
https://libraries.io/search?q=wagtail

**Comment by thibaudcolas** [comment]
Having worked on both https://github.com/springload/awesome-wagtail and https://madewithwagtail.org/, I find that maintaining such listings takes a lot of effort when they are centrally managed, as opposed to aggregated. It's not just managing the content, but also maintaining the site (upgrades, bug fixes, user administration). Since packages for Wagtail already exist in a central registry (PyPI), I'd strongly suggest integrating their APIs instead of creating another source of truth.

If creating another listing, IMHO having it versioned and editable via GitHub is one of the best ways to reduce the maintenance burden. Most people making packages will already have GitHub accounts, be aware of the PR workflow, and from the maintainer's side it's very easy to manage those submissions. Then you can focus on building a nice UI for the listing, instead of the management workflow.

---

From the wagtail.io side, I think a page pointing to the existing listings would already be super valuable, perhaps also with better documentation on how to create good, discoverable Wagtail packages. At the moment the [Developing packages for Wagtail](http://docs.wagtail.io/en/v2.4/contributing/index.html?highlight=classifier#developing-packages-for-wagtail) docs are a bit hidden, and very short.

**Comment by allcaps** [comment]
DRF docs example on third party apps https://www.django-rest-framework.org/community/third-party-packages/

**Comment by thibaudcolas** [comment]
FYI we’ve discussed / considered this as well during our recent core team meeting(s). We didn’t really decide on what we’d want to do, but decided to first work on a "Guides" section for wagtail.io where we could showcase third-party Wagtail content, inspired by https://www.sanity.io/guides.

From there, we can revisit the topic of a package directory.

**Comment by allcaps** [comment]
There has been progress:

Wagtail Packages that are listed on PyPi are added to Djangopackages.org. See https://www.fourdigits.nl/blog/wagtail-packages/.

Djangopackages.org will be the -community editable- data source to feed a Wagtail package directory page on wagtail.io. See https://github.com/wagtail/wagtail.io/pull/74

**Comment by allcaps** [comment]
New: https://wagtail.io/packages/
