### ISSUE TITLE
More informative error for invalid values passed to `|richtext`

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#4958]
Passing a value other than a string, `None`, or a `wagtail.core.rich_text.RichText` object to the `|richtext` template filter currently throws a hard-to-decipher error: `TypeError: expected string or bytes-like object` in wagtail/core/rich_text/rewriters.py. Reported here: https://stackoverflow.com/q/53790708/1853523

We should add a check to the template filter [here](https://github.com/wagtail/wagtail/blob/5f7b7230a26e244fd9c39d98b6e206902b594a9e/wagtail/core/templatetags/wagtailcore_tags.py#L89) to confirm that the value is a string or bytes object, and if not, throw a `TypeError` with a more meaningful error message e.g. `'richtext' template filter received an invalid value; expected string, got [value]`.

**Comment by mukesh5** [comment]
Hello, I am first time contributor. Can I work on this?

**Comment by gasman** [comment]
@mukesh5 Yes please!
