### ISSUE TITLE
update_index's real-time progress indication broken

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#4959]
### Issue Summary

The update_index command used to print a '.' for every 1000 items it indexed as it indexed them. Now it hangs and suddenly displays all '.'s at once when indexing is finished

### Steps to Reproduce

1. Run ``update_index`` on a project with an indexed model with more than 1000 items

### Technical details

* Wagtail version: 2.4rc1

**Comment by kaedroho** [comment]
Looking at the history, only small changes have been made to ``update_index``. I'll update this ticket when I've figured out what's up with my local setup.

**Comment by gasman** [comment]
Closing due to lack of updates - assuming this was a local environment issue.
