### ISSUE TITLE
Add logging for users' actions/errors on each of wagtail's main features, with UI to browse

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#496]
A UI should be created in the wagtail admin, which allows browsing of any logs (#492 suggests additional logs to the above), filtering by severity, object type, user, date-range and ordering by date.

Severity levels will come from standard Python logging.

Logs should be recorded for activity concerning:
- pages
- docs
- images
- snippets
- redirects
- promoted search results ("editors picks")
- users
- groups
- sites

Logs entries would be timestamped and associated with the user account performing the action.

Generic actions to be recorded:
- create
- edit
- delete

Also:
- page publish
- page unpublish
- page password protect
- page unpassword protect
- page move
- page reorder
- page submit for moderation
- page moderation reject
- page moderation accept
- private page successful front end login
- private page unsuccessful front end login
- wagtail admin login success
- wagtail admin login failure
- user deactivate
- user activate
- back end 404s
- front end 404s
- front end searches

Additionally Errors should be caught for:
- back end 500s
- front end 500s 

There will also need to be provision for actions taken by the system:
- scheduled publish
- scheduled unpublish

I'd presume/suggest logging be done via a method easily copied to new systems, such as via a decorator.

I was also going to suggest we use this system to record document downloads/page views, but the potential discrepancy with Google Analytics is always hard to explain to clients. It might be better to integrate GA Data API directly, rather than try and reinventing that wheel.

**Comment by euan** [comment]
@gasman, Please will you consider changing the milestone from **some-day** to **some-day-soon**.

**Comment by marteinn** [comment]
The Audit Log feature covers (https://github.com/wagtail/wagtail/pull/6084) some of the generic actions mentioned in the issue. Would be good if we revised the issue description so it reflects current state.

**Comment by zerolab** [comment]
Closing this as #6084 added audit logging for page models, then #7550, #7551 and #7557 extended it for other models.

Documentation: https://docs.wagtail.org/en/stable/extending/audit_log.html
