### ISSUE TITLE
Wagtail 2.4 routable page mixin dropped support for current LTS Django but is not in release notes

### ISSUE THREAD

**Issue by robvdl** [wagtail/wagtail#4967]
This is not really a bug but I found out that Wagtail 2.4 just released has dropped support for the current Django 1.11 LTS release (routable page mixin), yet it isn't mentioned in the release notes.

It tries to import django.urls.URLResolver which isn't in the current LTS version of Django.

I think it isn't a good idea to drop support for the current LTS until the next LTS of Django gets released, as there are many people that prefer to follow LTS versions rather than the "latest" Django.

**Comment by robvdl** [comment]
The reason this is a big deal is because I had a site running Wagtail 2.2.x on LTS Django and the admin suggests upgrading to Wagtail 2.4, but in order to do that, I need to get off the LTS version of Django.

In order to upgrade from Django 1.11 to 2.1.4, the user must deal with other issues that need to be resolved.

**Comment by gasman** [comment]
Hi @robvdl,
This is documented in the release notes here: https://docs.wagtail.io/en/stable/releases/2.4.html#removed-support-for-django-1-11
Wagtail's current LTS release is 2.3, so if you're choosing to stay on Django 1.11 due to it being a LTS release, then you should also stay on Wagtail 2.3.
