### ISSUE TITLE
Edit image duplicate buttons

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#4969]
### The edit image view has duplicate buttons

Have a look at the image.

### Technical details

* Python 3.6.4
* Django 2.0.5
* Wagtail 2.4.
![wagtail_images](https://user-images.githubusercontent.com/8074866/50402134-83d77300-0794-11e9-84c0-4381a2d233bf.jpeg)

**Comment by robslotboom** [comment]
Duplicate butters vanished after restart??

**Comment by BronzeCrab** [comment]
@robslotboom  hi, I have exactly the same issue, can you please say how did you solve it?

**Comment by robslotboom** [comment]
@BronzeCrab 

As I wrote; I just restarted the development server (runserver)
Hope this will solve your problem to.

Cheers,

Rob

**Comment by BronzeCrab** [comment]
actually i have it in production. I've tried to restart gunicorn, and it didnt help.

**Comment by robslotboom** [comment]
Maybe clear the browser cache?

**Comment by BronzeCrab** [comment]
didnt help(

**Comment by robslotboom** [comment]
Strange.
Do you use supervisord? If so try to restart it.
Otherwise I have no idea.

**Comment by gasman** [comment]
The buttons are duplicated in the HTML but hidden in CSS to allow them to appear in the right place on different-sized layouts, so it sounds like you have a deployment-related issue that's causing outdated CSS to remain in place (e.g. caching, or not re-running `./manage.py collectstatic` after an upgrade).

Closing as unable to replicate - happy to reopen if you can find steps to consistently reproduce this.
