### ISSUE TITLE
Page edit view incorrectly reporting dirty rich text

### ISSUE THREAD

**Issue by chosak** [wagtail/wagtail#4978]
### Issue Summary

When editing a page that contains Draftail rich text (either as a RichTextField or as a RichTextBlock in a StreamField), navigating away sometimes presents a warning that the page has been changed, even though it hasn't.

This happens for me consistently in Firefox 64, although I haven't been able to reproduce in other browsers. Specifically what is happening is this:

1. The JSON representing the rich text is generated in a nicely formatted way, with line breaks and indents:

    https://github.com/wagtail/wagtail/blob/882f8f3cf8ddd79c30e611a48882b309e90dad0c/wagtail/admin/rich_text/converters/contentstate.py#L87

2. The page edit view HTML contains this JSON as the `<input value>`, including those line breaks and indents:

    <img width="1332" alt="image" src="https://user-images.githubusercontent.com/654645/50656401-14663e00-0f61-11e9-84f9-fbdc6062aeb8.png">

    <img width="1084" alt="image" src="https://user-images.githubusercontent.com/654645/50656499-7030c700-0f61-11e9-87aa-4b5969197a25.png">

3. The dirty form check's `initialData` (generated via `$form.serialize()`) gets set with a serialized version of that initial `value`, including line breaks:

    https://github.com/wagtail/wagtail/blob/882f8f3cf8ddd79c30e611a48882b309e90dad0c/wagtail/admin/static_src/wagtailadmin/js/core.js#L59

4. Certain seemingly innocuous events cause the `<input value>` to change, removing the line breaks and indents:

    <img width="1087" alt="image" src="https://user-images.githubusercontent.com/654645/50656517-7c1c8900-0f61-11e9-8fbd-f9f63373a958.png">

    I can make this happen by highlighting the `<input>` in Firefox Developer Tools and (less predictably) by clicking away to another tab and coming back. Some event seems to cause the normalization of this value to clean it up.

    At first I thought this might be some Firefox quirk around handling of special characters within `<input value>`, but I couldn't reproduce it using some manually generated HTML with the same content. So my guess is this is somehow related to how/when Draftail/Draft.js monitors/updates its state, but I don't know enough about those internals to pinpoint it further.

5. Because the `<input value>` has been changed, the subsequent dirty form check here always fails:

    https://github.com/wagtail/wagtail/blob/882f8f3cf8ddd79c30e611a48882b309e90dad0c/wagtail/admin/static_src/wagtailadmin/js/core.js#L68

    This presents the user with a warning when navigating away, even though they haven't done anything.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Create a simple page type in models.py:

    ```py
    class TestPage(Page):
        body = RichTextField()

        content_panels = Page.content_panels + [
            FieldPanel('body'),
        ]
    ```
3. Create an instance of this page, entering some content in the body field.
4. Save the page, then, after it reloads, try navigating away. You'll see a warning even though you didn't make any further changes.

A simple fix that works for me is to modify [this line](https://github.com/wagtail/wagtail/blob/882f8f3cf8ddd79c30e611a48882b309e90dad0c/wagtail/admin/rich_text/converters/contentstate.py#L87) to remove the nice formatting (just remove the `indent=4, separators=(',', ': ')`). This makes the JSON more normalized upon first load, and so subsequent refreshes don't change it. This does have the slight downside of making the page HTML less readable, and also still relies on the Python JSON formatting exactly matching what the browser regenerates.

Another option would be to add some kind of initial refresh _before_ `initialData` is saved in the dirty check, to ensure that whatever formatting Draftail/Draft.js wants to do to its content happens once before we save the reference state.

Ping @thibaudcolas - any idea what is happening here?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.6.3
* Django version: 2.1.4
* Wagtail version: 2.5a0 (current master)
* Browser version: Firefox 64.0

**Comment by riceyrice** [comment]
I think I'm seeing this in Chrome too, with a blank rich text field that I click on and then click away from. Chrome debugger shows that initialData contains:
```
body=%7B%0D%0A%20%20%20%20%22blocks%22%3A%20%5B%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%22key%22%3A%20%228enu2%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22unstyled%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%22depth%22%3A%200%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%22text%22%3A%20%22%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%22inlineStyleRanges%22%3A%20%5B%5D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%22entityRanges%22%3A%20%5B%5D%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%5D%2C%0D%0A%20%20%20%20%22entityMap%22%3A%20%7B%7D%0D%0A%7D
```
While `$form.serialize()` gets:
```
body=null
```

* Python version: 3.7.2
* Django version: 2.1.4
* Wagtail version: 2.4
* Browser version: Chrome 72.0.3626.96

**Comment by riceyrice** [comment]
Like @chosak with content in the field even where JSON is equivalent I'm seeing it pretty printed versus inline, and key order changing. Seems like a case of needing [canonical JSON](https://tools.ietf.org/html/draft-staykov-hu-json-canonical-form-00)?
I have worked on an app that had to do this as JSON data was hashed on both Python server and JS client.

**Comment by thibaudcolas** [comment]
I can think of two reasons for this to happen:

- What you’ve already mentioned - the serialised format is different client-side and server-side.
- The editor will attempt to save (serialise) content whenever the user interacts with it (e.g. focus), regardless of whether content actually changed.

I think it would be possible to prevent the editor from saving when it’s not actually needed, but there will always be cases that can't be handled (variations of the user making edits and then undoing them). If it seems possible to have the same serialisation format on the client and server, it’s probably worth trying first.

**Comment by thibaudcolas** [comment]
@chosak 

> A simple fix that works for me is to modify [this line](https://github.com/wagtail/wagtail/blob/882f8f3cf8ddd79c30e611a48882b309e90dad0c/wagtail/admin/rich_text/converters/contentstate.py#L87) to remove the nice formatting (just remove the `indent=4, separators=(',', ': ')`). This makes the JSON more normalized upon first load, and so subsequent refreshes don't change it. This does have the slight downside of making the page HTML less readable, and also still relies on the Python JSON formatting exactly matching what the browser regenerates.

do you think this fix would be worth integrating into Wagtail? I'm worried of its reliability, but you might have more insight based on how it's worked for you so far.

**Comment by chosak** [comment]
@thibaudcolas while I believe this would fix the problem, the right fix is probably to do it client-side.

I don't know that we can or should assume that Python JSON formatting exactly matches how the browser JSON formats the same information. The JS code is the place where dirtyness is being detected so it feels like that's where the canonical initial state should be generated (even if in practice it's a superfluous decode/encode).

To do this client-side, something would have to happen to the form element (I'm not sure what) so that the initial [`$form.serialize`](https://github.com/wagtail/wagtail/blob/be03eeee2ea882d2cbd3e8e65fe4618794f3fd2c/wagtail/admin/static_src/wagtailadmin/js/core.js#L59) call would always match [subsequent](https://github.com/wagtail/wagtail/blob/be03eeee2ea882d2cbd3e8e65fe4618794f3fd2c/wagtail/admin/static_src/wagtailadmin/js/core.js#L68) calls. Right now that initial call seems to return the initial data in its exact original form, preserving line breaks, whereas subsequent calls actually generate it from the form inputs.

Would it be possible to force the editor to do an initial save/serialize of content right after it's first initialized (but before the `enableDirtyFormCheck` is set up)? This would persist a client-side-serialized version of the data as the initial version instead of relying on the version from the backend.

**Comment by thibaudcolas** [comment]
Good question. It sounds like something I wouldn't want to have to orchestrate (the different parts of the client-side code of Wagtail are generally very loosely coordinated), but it also does sound like a much better fix. I'll have a look, thanks for getting back to me so quickly.

**Comment by nwjlyons** [comment]
Hi, I suspect Draftail [`1.2.1`](https://github.com/wagtail/wagtail/blob/v2.5.1/package.json#L89) in Wagtail 2.5.1 is removing the indentation in the JSON. It doesn't happen with Draftail [`0.17.2`](https://github.com/wagtail/wagtail/blob/v2.4/package.json) in Wagtail 2.4.

# Wagtail 2.5.1

![wagtail-2 5-about-us-page](https://user-images.githubusercontent.com/126417/60444935-13fbe680-9c16-11e9-9ddd-7bc10d21ef73.png)

# Wagtail 2.4

![wagtail-2 4-about-us](https://user-images.githubusercontent.com/126417/60445015-49a0cf80-9c16-11e9-92be-2b66e8225770.png)

**Comment by thibaudcolas** [comment]
Thanks @nwjlyons, that’s good to know. I’m not sure whether this can be considered a bug, feature, implementation detail – but it’s good to know nonetheless 😄.

Thinking more about this issue, I think a potentially simple solution to this would be to simply delay the initialisation of this "dirty form check" by some time (5-10s? 1min?). Thinking about it from the end user’s perspective, I can see how it wouldn’t be very useful to get this prompt after only a few seconds interacting with the page.

This is rather inelegant from a technical standpoint, but a delay of multiple seconds would remove the need for us to orchestrate field initialisation for the purpose of this dirty field check. And it seems like a UX improvement as well.

---

Alternatively, it would be good to understand why this is only happening in Firefox. I’m still clueless about that.

**Comment by nwjlyons** [comment]
> Alternatively, it would be good to confirm whether this is indeed only happening in Firefox, and if so why.

I can confirm it happens in Chrome, Safari, and Firefox.

An alternative solution might be to listen to change events on the form?

**Comment by thibaudcolas** [comment]
Unless anyone has objections to my proposal in https://github.com/wagtail/wagtail/issues/4978#issuecomment-508016667, I’ll have a look at implementing this. I might consider other options while implementing specifically for rich text fields.

**Comment by easherma** [comment]
@thibaudcolas @KalobTaulien and I were chatting about something related to this; would it be possible to simply wait to do the check until the user actually types some characters or some other user event? Might not actually be a better solution but figured I’d mention it.
