### ISSUE TITLE
Error during template rendering

### ISSUE THREAD

**Issue by Mebus** [wagtail/wagtail#4989]
I get the attached error in Django 2.0.10 and Wagtail 2.4.

Mebus

![screenshot_2019-01-13 keyerror at cms](https://user-images.githubusercontent.com/271557/51087876-11d1c880-1759-11e9-8120-472b7479a3b5.png)

**Comment by gasman** [comment]
Hi @Mebus,
Sorry, we need more information to investigate this. Please can you include the _complete_ text of the error page, and tell us _when_ the error occurs?

**Comment by Mebus** [comment]
It seems that

'django.template.context_processors.request',

was missing.

Mebus
