### ISSUE TITLE
RichRextField ‘features’ keyword not being recognized 

### ISSUE THREAD

**Issue by dilonne** [wagtail/wagtail#4992]
### Issue Summary

The keyword ‘features’ for limiting elements seem not to be recognized

This line here
body = RichTextField(features=[‘h1’, ‘bold’, ‘italic’] 

Produces this error
TypeError: __init__() got an unexpected keyword argument ‘features’

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Edit models.py as follows...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

* Python version: Run `python --version`.
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
* Wagtail version: Hover over the Wagtail bird in the admin, or run `pip show wagtail | grep Version:`.
* Browser version: You can use http://www.whatsmybrowser.org/ to find this out.

**Comment by gasman** [comment]
Hi @dilonne - thanks for the report. Unfortunately there isn't enough information here for us to investigate, as you haven't provided steps to reproduce the error, or version details - without these there's no way for us to tell if this is a genuine bug, or user error.

If you're able to replicate this bug on a newly-created Wagtail project, please open a new issue containing the requested information.
