### ISSUE TITLE
Syntax error in tsquery with Postgres and wagtail.contrib.postgres_search

### ISSUE THREAD

**Issue by hammygoonan** [wagtail/wagtail#4993]
### Issue Summary

I'm getting an error saying `django.db.utils.ProgrammingError: syntax error in tsquery: "'test\'"` whenever I use a `\` in my search term.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Configure site to use Postgres and the `wagtail.contrib.postgres_search` app.
3. Run migrations
4. log into admin
5. add a `\` character to your search term.

Running locally, you replicate the issue by using Postgres, `postgres_search` then going to: [http://127.0.0.1:8000/admin/pages/search/?q=drink%5C](http://127.0.0.1:8000/admin/pages/search/?q=drink%5C).

The error is with all the searches (page, image and document).

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I assume the `\` character should just be stripped out of search queries.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Python 3.7.2
* Django version: 2.1.5
* Wagtail version: 2.4
* Browser version: Firefox 64

**Comment by BertrandBordage** [comment]
FIxed by #4994.
