### ISSUE TITLE
RichRextField ‘features’ keyword not recognized

### ISSUE THREAD

**Issue by dilonne** [wagtail/wagtail#4995]
### Issue Summary
The keyword ‘features’ for limiting elements seem not to be recognized

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py as follows

class ItemPage(Page):
   body = RichTextField(features=['h1', 'bold', 'italic', 'link'])

3. Run the project with python manage.py runserver

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Running the project gives:
super(RichTextField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'features

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Python 3.6.6
* Django version: Version: 1.10.5
* Wagtail version: Version: 1.9
* Browser version: Firefox 64

**Comment by gasman** [comment]
Hi @dilonne,
The `features` keyword was [introduced in Wagtail 1.12](http://docs.wagtail.io/en/v2.4/releases/1.12.html#configurable-rich-text-features) - you will need to upgrade to Wagtail 1.12 or later to use this.

**Comment by dilonne** [comment]
Had missed that, thanks a lot.
