### ISSUE TITLE
Checkboxes in Wagtail forms nearly impossible to style correctly when rendered using as_p

### ISSUE THREAD

**Issue by DanAtShenTech** [wagtail/wagtail#4999]
### Issue Summary
Rendering a form using Django's `as_p` functionality causes a single Checkboxes field to render as follows:

- the label in a `<p>` by itself
- the checkbox options in a `<ul>` (not wrapped by a `<p>`)
- an empty `<p>`

This conglomeration is basically impossible to style correctly.  It would be a tremendous improvement to wrap form elements in `<div>` tags instead of `<p>` tags (being sure to wrap a single Checkboxes field in a single `<div>`).  Then, for instance, in multi-column forms (using the css `column-count` property) it would be possible to keep all related elements together in a single column where relevant.  Right now I can keep the items in the currently rendered `<ul>` together with
```
-webkit-column-break-inside: avoid;
 /* Chrome, Safari, Opera */
page-break-inside: avoid;
/* Firefox */
break-inside: avoid;
/* IE 10+ */
```
But because the `<label>` that is just above the `<ul>` is in its own `<p>`, then at some screen widths the label element falls at the end of one column and the `<ul>` is at the top of the next column.

**Comment by gasman** [comment]
Hi @DanAtShenTech - which particular forms are you referring to? The form builder (wagtail.contrib.forms), forms within the Wagtail admin, or something else?

**Comment by DanAtShenTech** [comment]
You can see an example of what I'm talking about [here](https://cimlg.org/join-the-conococheague-institute/) in the Newsletter Delivery field.  Fortunately, the Newsletter Delivery item works OK when the screen is narrowed if it is positioned where you see it, but if you use the developer tools to change the DOM by switching the Newsletter Delivery item(s) with the Country item, and then narrow the width of the page, you'll see how the ND item(s) run into multiple columns and don't look right.
