### ISSUE TITLE
Wagtail documentation incorrectly states a confirmation step on publishing

### ISSUE THREAD

**Issue by inostia** [wagtail/wagtail#5000]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue.

The Wagtail documentation (as of 2.4) incorrectly states that there's a confirmation step on publishing. http://docs.wagtail.io/en/v2.4/editor_manual/new_pages/previewing_and_submitting_for_moderation.html#previewing-and-submitting-pages-for-moderation

### Steps to Reproduce

1. Create a new page and publish.
2. Notice that there is no confirmation step, as stated in the docs.

**Comment by jhoover4** [comment]
So which is wrong, the documentation or the functionality? 😬

**Comment by gasman** [comment]
The documentation is wrong, I think - I don't see a need for a confirmation step for publishing, as it's a non-destructive action that can easily be reverted if it's done by mistake.

(Admittedly, you could say the same about unpublishing, which _does_ have a confirmation step - but I think it makes more sense there, as there's a natural parallel with deletion.)

**Comment by gasman** [comment]
Fixed in #5006
