### ISSUE TITLE
Unclear error msg when saving img after focal point edit

### ISSUE THREAD

**Issue by HvandenBerg** [wagtail/wagtail#5007]
### Issue Summary

A summary of the issue.
It is not possible to save an image after creating a focal point and clicking next the selected area. 

### Steps to Reproduce

1. Open cms
2. Open images
3. Edit img
4. remove any focal points (if any are present)
5. create focal point (drag mouse across img)
6. click outside the focal point but still within the img 
7. The selection (focal point) now seems to be gone
8. Save the IMG

You are now shown an error msg `The image could not be saved due to errors.`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
In my opinion this is a minor issue but I would expect the img to be saved without having created a focal point (as the  focal point seems to be gone after clicking outside it) OR if it is not possible to save the img after the click outside the focal point I would expect a reason for this to be included in the error msg.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Run `python --version`.
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
* Wagtail version: Hover over the Wagtail bird in the admin, or run `pip show wagtail | grep Version:`.
* Browser version: You can use http://www.whatsmybrowser.org/ to find this out.

**Comment by gasman** [comment]
Confirmed on current master (2.5a0) and bakerydemo with Django 2.1.4 and Chrome 71. Thanks for the report @HvandenBerg!

**Comment by lb-** [comment]
Fixed and merged in #5055  / https://github.com/wagtail/wagtail/commit/74218a7e43f59b329cd7cd890245bcc2764beb3a
