### ISSUE TITLE
Add Mongolian translation to wagtail source code

### ISSUE THREAD

**Issue by miiga** [wagtail/wagtail#5008]
I would like to add Mongolian translation files to wagtail source code.

**Comment by zerolab** [comment]
Hi @miiga,

As per the README, translations should be submitted through Transifex. For Mongolian specifically, go to https://www.transifex.com/torchbox/wagtail/language/mn/

**Comment by gasman** [comment]
Hi @miiga - many thanks for your work on the Mongolian translation!

We always fetch translations from Transifex immediately before a new release, but I've also run an extra fetch now: 67940973b53430466c29733ab95d6d644aa1b320
