### ISSUE TITLE
Create a standard mixin for admin HTML components that render themselves

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#5012]
A pattern we frequently see in Wagtail's extensibility / hook mechanisms is to have third-party code return an object with a `render` method (or `render_html` or similar), and then have the Wagtail view assemble a list of those objects and loop over them during template rendering. This pattern appears in:

* construct_homepage_panels
* construct_homepage_summary_items
* register_admin_menu_item / register_settings_menu_item / construct_main_menu
* register_admin_search_area
* register_page_action_menu_item
* construct_wagtail_userbar
* the proposed view restriction classes in [RFC 32](https://github.com/wagtail/rfcs/pull/32)

There are also looser similarities with EditHanders, StreamField blocks, and Django form widgets.

Because this pattern has been re-implemented from scratch each time, each implementation differs in various details:

* the name of the 'render' method
* the parameters passed to the 'render' method: request, user, parent_context...
* whether we provide a base class with a default render method, so that subclasses can just 'fill in the blanks' rather than constructing an HTML string from scratch
* whether the default render method uses Django templates (and thus allows subclasses to override the template by setting a `template` attribute)
* if so, do they support a `get_template` to allow the template to be chosen dynamically
* whether they provide a `get_context` method to add extra variables to the template context
* if so, whether `get_context` receives a `parent_context` to access variables from the parent template
* whether the object can have [JS/CSS assets](https://docs.djangoproject.com/en/2.1/topics/forms/media/) attached
* whether the object has an `order` property to determine its position in the list
* whether there's an `is_shown` method, allowing the calling template to omit the container block entirely if none of its child objects are shown

If Wagtail were to provide a standard implementation of this pattern, it would reduce code duplication, make APIs more consistent, and make it possible to easily add extension mechanisms to parts of the Wagtail admin that don't currently have one (e.g. the 'switches' area in the top right corner of the page edit view) or have a different, more limited mechanism (register_account_menu_item, register_page_listing_buttons).

I would imagine such an implementation to consist of a mixin class (named `HTMLComponent` or similar) to serve as the basis for a single renderable object, along with some helper functions / classes / template tags for the common tasks around assembling and rendering a list of those objects: providing `register_foo` / `construct_foo` hooks, reordering / checking `is_shown`, combining media declarations into one, and so on.

**Comment by thibaudcolas** [comment]
This looks a lot like template components (#7425) introduced in Wagtail 2.15, so will close now.
