### ISSUE TITLE
Docs should be served as HTTPS-only

### ISSUE THREAD

**Issue by davidjb** [wagtail/wagtail#5045]
### Issue Summary

Currently, the documentation for Wagtail is served over both HTTP and HTTPS, with the HTTP version being most commonly linked to (eg http://docs.wagtail.io/ at the bottom of https://wagtail.io/).  Search engine results (eg Google) mix results as well, so some are HTTP and some are HTTPS.

The certificate and configuration are all up and running so it seems to just be a case of making the site HTTPS-only in Cloudflare (eg https://blog.cloudflare.com/how-to-make-your-site-https-only/) and perhaps updating some of the most obvious `http://` URLs to `https://`.  Otherwise, once HSTS is enabled and someone's visited the docs site once, they'll automatically get sent to HTTPS.

### Steps to Reproduce

1. Load http://docs.wagtail.io and notice it's not HTTPS
2. Load https://docs.wagtail.io and notice that it is valid and configured ready to go.

### Technical details

* Any browser/client

**Comment by gasman** [comment]
Hi @davidjb - thanks for the report.
It looks like redirecting to https is currently unsupported by readthedocs: https://github.com/rtfd/readthedocs.org/issues/2652#issuecomment-413268346
https://github.com/rtfd/readthedocs.org/issues/4641

We do have "Always use HTTPS" enabled in the readthedocs config, so hopefully this should take effect immediately once they implement this feature. (We're also currently looking into dropping readthedocs in favour of a self-hosted solution, which would also address this.)
