### ISSUE TITLE
LANGUAGE_CODE doesn't affect admin interface html 'lang' attribute in skeleton template

### ISSUE THREAD

**Issue by remort** [wagtail/wagtail#5051]
### Issue Summary
`<html>` tag attribute 'lang' in skeleton.html admin template is not being filled with value of LANGUAGE_CODE settings variable
But it supposed to: `<html class="no-js" lang="{{ LANGUAGE_CODE|default:"en-gb" }}">`

### Steps to Reproduce

Set LANGUAGE_CODE in settings.py to, i.e., 'he_IL'.
Restart your application/Reload container and refresh admin page.
Get page source in browser. You'll get `<html lang="en-US">` at the top of the page source.
It seems that LANGUAGE_CODE variable is not accessible while in skeleton.html.

### Technical details
wagtail 2.2.2
python 3.6

**Comment by gasman** [comment]
Thanks for the report @remort! This does look like a bug - as far as I can see there's nothing in place in the Wagtail code to make the `LANGUAGE_CODE` setting available.

Using the variable from the settings file directly wouldn't be correct either, as that wouldn't deal with users setting their own language preference from the 'account settings' area - we should probably be using `request.user.wagtail_userprofile.preferred_language` here instead.

**Comment by gasman** [comment]
Actually, it looks like we should be using the `get_current_language` template tag here: https://docs.djangoproject.com/en/2.1/topics/i18n/translation/#get-current-language
