### ISSUE TITLE
Multisite support for frontend cache invalidator backends

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#5059]
### Issue Summary

Currently [only `CloudfrontBackend` supports](http://docs.wagtail.io/en/v2.4/reference/contrib/frontendcache.html) multisite projects. To be able to use `CloudflareBackend`, for example, with multiple domains you will need to define two separate backends:

```python
WAGTAILFRONTENDCACHE = {
    'website1': {
        'BACKEND': 'wagtail.contrib.frontend_cache.backends.CloudflareBackend',
        'EMAIL': 'some@example.com,
        'TOKEN': 'some_cloudflare_api_token,
        'ZONEID': 'some_zone_id_for_domain_1',
    },
    'website2': {
        'BACKEND': 'wagtail.contrib.frontend_cache.backends.CloudflareBackend',
        'EMAIL': 'some@example.com,
        'TOKEN': 'some_cloudflare_api_token,
        'ZONEID': 'some_zone_id_for_domain_2',
    },
}
```

The problem is that `wagtail.contrib.frontend_cache` attempts to invalidate all pages from all website in all backends. So, for example, if you define 3 `CloudflareBackend`s with different domains (`ZONEID`s) then 3 requests will be sent to the Cloudflare API and only 1 of them will be successful.

### Technical details

* Wagtail version: 2.4

**Comment by RealOrangeOne** [comment]
I've added some configuration to let people define which backends should be used when validating which hostnames: https://github.com/wagtail/wagtail/pull/11858

**Comment by gasman** [comment]
Completed in #11858
