### ISSUE TITLE
AttributeError on Cloudflare cache invalidation

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#5073]
### Issue Summary

As far as I understand, the idea of the following piece of code is to log errors form the API and not interrupt the editing workflow:

https://github.com/wagtail/wagtail/blob/442ab73489d1665e3c451d8356c1c9429e92e5af/wagtail/contrib/frontend_cache/backends.py#L101-L104

The problem is that `requests.exceptions.HTTPError` doesn't seem to have the `message` attribute, so `AttributeError: 'HTTPError' object has no attribute 'message'` will be raised on the line 103. And as a result the request to render the admin UI will fail.

### Technical details

* Python version: 3.6.6
* `requests` version: 2.21.0
* `Django` version: 2.1.5
* `wagtail` version: 2.4

**Comment by harrislapiroff** [comment]
I've come across this a bunch! Would be thrilled to see a resolution.

**Comment by gasman** [comment]
Fixed in #5150
