### ISSUE TITLE
Prevent login for some sites

### ISSUE THREAD

**Issue by JorneVL** [wagtail/wagtail#5084]
### Feature Request
Is it possible to prevent users login on some sites?
For example on sites where they don't have permisions on?

I looked into extending or overwrite the user authorization but I don't think there is a easy way for doing this.

**Comment by gasman** [comment]
Hi @JorneVL - thanks for the suggestion. 
This wouldn't really fit with the current design of the Wagtail admin, where there's a single instance of the admin interface which always works the same way regardless of the hostname used to access it. This is for various reasons as explained here: https://github.com/wagtail/wagtail/issues/4970#issuecomment-455264383 . For example, if we added a rule to say that users can only log in through a hostname that matches a site where they have page permissions, then this would fail for installations that host the admin at a completely separate domain, or for users who have permission over images/documents but not pages.

I wouldn't be opposed to changing this behaviour to support multi-tenant setups better, but we'd need a full proposal (perhaps [as an RFC](https://github.com/wagtail/wagtail/issues/4970#issuecomment-455264383)) to specify exactly what behaviour would change.
