### ISSUE TITLE
Unable to add tel (telephone) or other app handler links in rich text editor.

### ISSUE THREAD

**Issue by vsalvino** [wagtail/wagtail#5086]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Unable to add `tel:` (telephone) links in Rich Text Editor. There are also other app handler type links that I imagine this would apply to. There is a special way of adding `mailto:` links (Email link option in modal).

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Add a rich text block to `models.py`, for example:
```python
from wagtail.core.fields import RichTextField
from wagtail.core.models import Page

class HomePage(Page):

    body = RichTextField(blank=True)
    
    content_panels = Page.content_panels + [
        FieldPanel('body'),
    ]
```
3. Edit the rich text block in the wagtail admin and try to add a `tel:` link, there is no possible way to accomplish this.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7.2
* Django version: 2.1
* Wagtail version: 2.4
* Browser version: Firefox, Edge, Chrome

**Comment by gasman** [comment]
Hi @vsalvino - thanks for the report. This is covered by #3776.

**Comment by vsalvino** [comment]
Thank you, I searched but did not come across that issue. Glad it is already being considered.
