### ISSUE TITLE
How Embed Gist in Wagtail?

### ISSUE THREAD

**Issue by daviluis321** [wagtail/wagtail#5087]
I added  link gist in the rich text and the sentence appears: Can not find an embed for this URL. But I looked at the support in github and got the gist in wagtail integration. What do you think it could be?

**Comment by kaedroho** [comment]
Gist doesn't support the oEmbed standard which Wagtail uses by default. You will have to use a different finder such as Embedly, or create a custom embed finder.

You can find documentation for how to do this here: https://docs.wagtail.io/en/v2.4/advanced_topics/embeds.html?highlight=embedly
