### ISSUE TITLE
Limit image upload size by number of pixels

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#5088]
Wagtail currently limits the file size of images. However, it's possible to craft a JPEG file that is below this limit yet be well over 100 megapixels which may cause the server to run out of memory when the file is decompressed.

We already extract the image size from the file header on upload, so it shouldn't be difficult to add a check here.

We should add a high default threshold (Pillow will give a warning at 128Mpx so maybe this should be our default as well) but allow it to be adjusted/disabled with a setting (maybe called ``WAGTAILIMAGES_MAX_IMAGE_PIXELS`` following the name used by Pillow).

**Comment by tomedelliott** [comment]
@kaedroho I've opened a pull request #5097 that implements is using pillows [Image file.Parser](https://pillow.readthedocs.io/en/3.0.x/reference/ImageFile.html#PIL.ImageFile.Parser) which incrementally reads the file.

Do you have the large file to test it?

**Comment by gasman** [comment]
Completed in #5097
