### ISSUE TITLE
Better user help for PageChooserPanel restricted types 

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#510]
When a PageChooserPanel has been set to only allow a certain type of page to be chosen, the UI in the edit page should warn the user of this _before_ they open the modal.

A PR is currently in flight to better explain this restriction once the modal is open, but it might be better if the standard "Choose a page" button said instead "Choose [type]". Failing that an enforced help message stating "Only [type] pages can be chosen" would also do.

**Comment by gasman** [comment]
Fixed in #3473
