### ISSUE TITLE
API v2 HEAD requests cause 500

### ISSUE THREAD

**Issue by bufke** [wagtail/wagtail#5101]
### Issue Summary

Sending a HEAD request to the wagtail v2 API results in a 500 error:

`Expected view PagesAPIEndpoint to be called with a URL keyword argument named "pk". Fix your URL conf, or set the .lookup_field attribute on the view correctly.`

### Steps to Reproduce

1. Start a wagtail project with the API v2 registered.
2. curl -I yourserver/api/pages/ (or wherever you set the url)

Typically one wouldn't do this. I found this because the service uptimerobot sends HEAD requests by default. It's a low impact issue but still a bug.

### Technical details

* Python version: 3.7
* Django version: 2.1
* Wagtail version: 2.4
* Browser version: curl 7.61.0 (x86_64-pc-linux-gnu)

**Comment by thibaudcolas** [comment]
Testing this quite a few years later – on Wagtial 6.3 / Django 5.1, HEAD requests seem to be working just fine. I’ll close this now, but if there is still an issue we can reopen. Tested with the bakerydemo and wagtail.org:

```bash
curl --head http://localhost:8000/api/v2/pages/
curl --verbose --head https://wagtail.org/api/v2/pages/
```
