### ISSUE TITLE
still possible to create copies of pages that exceed their models' `max_count`

### ISSUE THREAD

**Issue by phette23** [wagtail/wagtail#5111]
### Issue Summary

In Wagtail admin, it's possible to select a page type that has hit its `max_count` limit (introduced in Wagtail 2.4) and then use the "copy" action in the dropdown menu to create another copy, even though no new pages of the type should be allowed to be created.

### Steps to Reproduce

1. Create a new model derived from wagtail.core.models.Page
2. Add a `max_count = 1` property
3. In Wagtail Admin, create a page of this type and publish it
4. In Admin, select the page's **More** > **Copy** action, choose a new slug for it
5. Publish the copy - a new page is created, no error is thrown
6. **Expected behavior**: because the existing page meets the `max_count` limit, an error should be thrown alerting the user that further copies cannot be created

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: Python 3.7.2
* Django version: 2.1.5
* Wagtail version: 2.4
* Browser version: Chrome 72

There's no check against `max_count` in the `Page` model's `copy` method, only in `can_create_at`.

**Comment by lb-** [comment]
Thanks @phette23 for the really helpful steps to reproduce and investigation.

Fixed with #5115 
Merged in https://github.com/wagtail/wagtail/commit/77a8e3b7c08dafa5e18a57ce5e1d8f6ac7d54e1a
