### ISSUE TITLE
Segmentation fault: 11 - Can't create more than two child pages

### ISSUE THREAD

**Issue by jnsdrtlf** [wagtail/wagtail#5121]
### Issue Summary

When creating more than two child pages, python causes a segmentation fault. Restarting `wagtail` works, but as soon as you access the third child page in the admin interface, the segmentation fault is caused again. Deleting the problematic page in `/django-admin` also causes the same error.

### Steps to Reproduce

1. Create new project `wagtail start example`
2. `python managa.py migrate`
3. `python managa.py createsuperuser`
4. `python managa.py runserver`
5. Go to admin page
6. Create two new child pages under **Home**

Creating a **third** child page causes the segmentation fault.

### Technical details

* Python version: `3.7.2` (on macOS Mojave, installed using `brew`)
* Django version: `2.1.7`
* Wagtail version: `2.4`

Using `virtualenenv` for all dependencies (including `wagtail`).

**Comment by gasman** [comment]
Hi @jnsdrtlf - thanks for the report. A segmentation fault would indicate something fundamentally failing within Python or a native extension such as Sqlite, so it's highly unlikely that this is something we can fix within Wagtail - however, I'll keep this issue open in case anyone can track it down further.

**Comment by jnsdrtlf** [comment]
Hi @gasman, that's what I've already been afraid of. I was wondering if anyone can give me advice on how to debug this error.

**Comment by lmiguelvargasf** [comment]
@gasman, I was facing the same issue. I upgraded `sqlite` and it seems it is working now. I am using Python 3.7.2, and I regularly install dependencies using `brew`.

**Comment by jnsdrtlf** [comment]
@lmiguelvargasf updating didn't help. However, I'm now using PostgreSQL which works without a problem. So it most certainly is an issue with sqlite.
