### ISSUE TITLE
Wagtail's labels for inputs need to take 100% width instead of current 16.67%

### ISSUE THREAD

**Issue by vassilyvv** [wagtail/wagtail#5125]
After [this](https://github.com/wagtail/django-modelcluster/pull/106) feature we are able to create nested related objects in the same form. But while nested forms take less width, wagtail fails to show nested form's labels in the same line with inputs. So, I think this CSS rule should be added by default:

```
fieldset > ul > li > div > label {
    width: 100%;
}
```
![screenshot from 2019-03-07 21-07-27](https://user-images.githubusercontent.com/6623466/54013670-77f42e00-4193-11e9-90f9-7c7b28395b3c.png)

**Comment by thibaudcolas** [comment]
This will be fixed in the upcoming Wagtail 4 release. Now inputs take up the whole of the available width to their right – the only reduction in width is indentation from nesting.
