### ISSUE TITLE
ImageChooserField does not work in nested forms.

### ISSUE THREAD

**Issue by l3acucm** [wagtail/wagtail#5126]
After [this](https://github.com/wagtail/django-modelcluster/pull/106) feature we are able to create nested related objects in the same form. But when we use ImageChooserField at the second level or deeper - Wagtail shows regular select instead of `ImageChooserField`. On the screenshot, `ImageChooserField` is setted for the `logo` field.

![screenshot from 2019-03-07 21-07-27](https://user-images.githubusercontent.com/6623466/54013829-05378280-4194-11e9-8be5-8a14b87eeaca.png)

**Comment by gasman** [comment]
@vassilyvv Do you have a `panels` definition on the inner model that includes `ImageChooserPanel`?

**Comment by vassilyvv** [comment]
Yes

**Comment by BramManuel** [comment]
The same issue occurs with PageChooserPanel:
![image](https://user-images.githubusercontent.com/27723033/58172902-20496700-7c9a-11e9-9b23-ef083855be33.png)

**Comment by supermanzer** [comment]
I am running into this issue with nested relations as well:

![Screen Shot 2019-07-29 at 10 55 31 AM](https://user-images.githubusercontent.com/8837217/62070547-8ea52b00-b1ef-11e9-9df9-09b16395802e.png)

I have 
 * Product(Page) 
 * ProductVariant(ClusterableModel) 
 * ProductAndVariant(Orderable, ProductVariant) 
 * LabelRevision(Orderable) 

The ImageChooserPanel is a wonderfully useful and cool piece of UI engineering and I **very much** would like to include it for my admin users.

**Comment by kiwiheretic** [comment]
Is it true that this fix is targeted for wagtail 2.7 or is that just an unfounded rumour that we should all assume is false?

**Comment by zerolab** [comment]
@kiwiheretic if you could help test #5566, it will speed things up and help get in it for 2.7

**Comment by gasman** [comment]
To clarify - #5566 does not fix this particular bug, but does fix some related issues with nested InlinePanels (such as the three blank forms that appear on adding the 'outer' item). It's likely that #5566 will make it into 2.7 as it's just awaiting final review - but as far as I know no-one has started work on a fix for this issue, and it's doubtful whether anyone on the core team will have resources to do so in time for November's release. The best chance of this making it into 2.7 would be if an outside contributor submits a pull request.

**Comment by gasman** [comment]
I think the problem here is that - while https://github.com/wagtail/django-modelcluster/pull/107 and https://github.com/wagtail/wagtail/pull/5566 mean that we can and do use a `ClusterForm`-derived class for the second-level forms (so that they can have formsets of their own) - we haven't updated [`childformset_factory`](https://github.com/wagtail/django-modelcluster/blob/8299b6ac41ac4e01453b28440164b12e393bc37e/modelcluster/forms.py#L169) to pass a `formsets` argument down the line. This would contain the all-important information about which grandchild formsets should be included and which widgets they should include; without this, `ClusterForm` ends up inferring that information from the model schema alone, missing out on the information specified in `panels`.

(On the other hand, the template-rendering half of the EditHandler mechanism _does_ seem to correctly unwrap the nested `panels` definitions, leading to a related issue noticed by @sonnybaker where any model fields not covered by `FieldPanels` end up as unlabelled fields below the main fieldset. This is because the form class believes that they should be part of the form, but FieldPanel correctly doesn't provide a rendering for them.)

It's going to take some time to untangle the interactions between Wagtail and django-modelcluster, so bumping this off the 2.8 release.

**Comment by MaziyarMK** [comment]
Got SnippetChooserPanel working with this:

```
from wagtail.admin.edit_handlers import InlinePanel as BaseInlinePanel

class InlinePanel(BaseInlinePanel):
    def widget_overrides(self):
        widgets = {}
        child_edit_handler = self.get_child_edit_handler()
        for handler_class in child_edit_handler.children:
            widgets.update(handler_class.widget_overrides())
        widget_overrides = {self.relation_name: widgets}
        return widget_overrides
```

Basically the nested-second-layer InlinePanel wasn't providing the Page model with any widgets, while the first layer InlinePanel was doing so. Haven't tested it with different combinations (third layer, all layers having custom panels, etc).

![nested inlinepanel](https://user-images.githubusercontent.com/1495852/77974299-c547be00-7307-11ea-83c1-33db335c1866.jpg)

**Comment by ruisaraiva19** [comment]
> Got SnippetChooserPanel working with this:
> 
> ```
> from wagtail.admin.edit_handlers import InlinePanel as BaseInlinePanel
> 
> class InlinePanel(BaseInlinePanel):
>     def widget_overrides(self):
>         widgets = {}
>         child_edit_handler = self.get_child_edit_handler()
>         for handler_class in child_edit_handler.children:
>             widgets.update(handler_class.widget_overrides())
>         widget_overrides = {self.relation_name: widgets}
>         return widget_overrides
> ```
> 
> Basically the nested-second-layer InlinePanel wasn't providing the Page model with any widgets, while the first layer InlinePanel was doing so. Haven't tested it with different combinations (third layer, all layers having custom panels, etc).

@MaziyarMK thank you for the code snippet, I used on a project running Wagtail 2.9.3 and works as expected 👌 .

**Comment by brylie** [comment]
I am running into this issue as well, but with nested orderables. The following data model renders in the Wagtail Admin, but the `author` field doesn't render a page chooser panel. Instead, it renders a generic dropdown select with around ten pages to choose from.

![image](https://user-images.githubusercontent.com/17307/119647328-cfd8e700-be28-11eb-9384-de32e226d7c7.png)

```py
class Author(Orderable):
    article = ParentalKey(
        "magazine.Article",
        null=True,
        on_delete=models.PROTECT,
        related_name="authors",
    )
    author = models.ForeignKey(
        "wagtailcore.Page",
        null=True,
        on_delete=models.PROTECT,
        related_name="articles_authored",
    )

    panels = [
        PageChooserPanel(
            "author", ["contact.Person", "contact.Organization"]
        )
    ]


class Article(ClusterableModel):
    title = models.CharField(max_length=255)
    issue = ParentalKey(
        "magazine.Issue",
        null=True,
        on_delete=models.CASCADE,
        related_name="archive_articles",
    )
 
    panels = [
        FieldPanel("title", classname="full"),
        InlinePanel(
            "authors",
            heading="Authors",
            help_text="Select one or more authors, who contributed to this article",
        ),
    ]


class Issue(Page):
    publication_date = models.DateField(
        null=True, help_text="Please select the first day of the publication month"
    )

    content_panels = Page.content_panels + [
        FieldPanel("publication_date", widget=DatePickerInput()),
        InlinePanel(
            "articles",
            heading="Table of contents",
            help_text="List one or more articles that appear in this issue",
        ),
    ]
```

Note: this data model is intended only to generate a table of contents for a PDF magazine issue. However, we need to be able to reverse-query the articles from an authors page so need a many-to-many relationship there.

**Comment by frontendr** [comment]
Can confirm that @brylie's `NestedInlinePanel` works like a charm in 2.13.2. It also feels very natural to set the children's widgets but I'm not sure about the consequences. The only thing I've changed is to initialise the `widgets` with `super().widget_overrides()` instead of an empty dict.

**Comment by joshuadavidthomas** [comment]
+1 that the `NestedInlinePanel` provided above fixes the issue for 2.14.1. Like @brylie above, it appears none of the settings carry forward; I am trying to limit the number of forms by setting `max_num`, but it doesn't appear to do anything.

Copying and overriding the default `admin/templates/wagtailadmin/edit_handlers/inline_panel.js`, I threw a few console.logs in there to see what was going on. The `self.formset.max_num` for the `NestedInlinePanel` is 1000. I'm not familiar enough with Wagtail internals to know what to do with that info, but maybe it will help someone else diagnose what's going on.

**Comment by leonardorhojas** [comment]
+1 `NestedInlinePanel `ignores `max_num `

**Comment by gasman** [comment]
This is now working for me with the following setup (in home/models.py on a fresh Wagtail project):

```python
from django.db import models
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel

from wagtail.models import Page, Orderable
from wagtail.admin.panels import InlinePanel, FieldPanel


class HomePage(Page):
    content_panels = Page.content_panels + [
        InlinePanel("gallery_sections", label="Gallery sections")
    ]


class GallerySection(Orderable, ClusterableModel):
    page = ParentalKey(HomePage, on_delete=models.CASCADE, related_name="gallery_sections")
    heading = models.CharField(max_length=255)

    panels = [
        FieldPanel("heading"),
        InlinePanel("images", label="Images")
    ]


class GalleryImage(Orderable):
    section = ParentalKey(GallerySection, on_delete=models.CASCADE, related_name="images")
    image = models.ForeignKey(
        'wagtailimages.Image', on_delete=models.CASCADE, related_name='+'
    )
    caption = models.CharField(blank=True, max_length=250)

    panels = [
        FieldPanel("image"),
        FieldPanel("caption"),
    ]
```

My earlier comment above seems to suggest that #5566 wasn't the key piece that fixed this, although I'm not sure what else would have done so - possibly dropping dedicated panel types such as `ImageChooserPanel` in Wagtail 3.0? Either way, this can be closed now.
