### ISSUE TITLE
Image and document summary item don't take permissions into account for counting number of images/documents

### ISSUE THREAD

**Issue by mr-klint** [wagtail/wagtail#5129]
### Summary

The admin homepage summary items for documents and images don't reflect on the permissions for collections. If a user has permission for any collection the numbers in the summary will show the total number of images/documents in the database. This leaks information to users that might not have permission to more than a single collection

### Steps to Reproduce

1. In any wagtail project with at least one collection more than the root collection create a user that does'nt have permission to the root collection but to at least one other collection
2. Ensure there are images/documents in the root collection
3. Sign in as the new user, when reaching the admin page the numbers telling the amount of images/documents in the system will render the total amount in the database, not what's available to the user

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7.2
* Django version: 2.1.7
* Wagtail version: 2-4
* Browser version: Firefox 65.0

### Proposed solution
Update "get_context" method in "ImagesSummaryItem" in wagtail/images/wagtail_hooks.py according to:

```python
def get_context(self):

    # Fetch all collection user has any permission for to filter image counting
    collections = permission_policy.collections_user_has_any_permission_for(self.request.user, ['add', 'change', 'delete'])
    return {
        'total_images': get_image_model().objects.filter(collection__in=collections).count(),
    }
```

And similar for wagtail/documents/wagtail_hooks.py

**Comment by georgeyk** [comment]
hey @loicteixeira,
If not already taken, I would like to give it shot.

**Comment by loicteixeira** [comment]
Hi @georgeyk. Nobody else has expressed interest so far so go ahead. Good luck!

**Comment by SaptakS** [comment]
@loicteixeira I would love to contribute by fixing this issue.

**Comment by loicteixeira** [comment]
Thank you for your interest @SaptakS. @georgeyk was already keen on tackling this one so I reckon we can leave them some time and if they don't complete it, you could have a go at it.
But if you can't wait getting started on something, maybe you can find something to tackle in the pool of [Hacktoberfest issues](https://github.com/wagtail/wagtail/issues?q=is%3Aopen+label%3AHacktoberfest+sort%3Aupdated-desc).

**Comment by SaptakS** [comment]
Totally fine. Sorry i didn't refresh the page and github somehow didn't update my page. I am fine to take non Hacktoberfest issues too. I don't mind at all.

**Comment by gasman** [comment]
Sorry for not catching on to this earlier, but there's an additional subtlety here: while the set of images / documents shown within the Images / Documents area is indeed filtered by the user's add/edit permissions, the chooser popups still show the full set (because editors need to be able to build pages using images that they don't necessarily have edit rights over - there is no distinct "choose" permission). This _probably_ isn't a big deal, given that:

* the same is already true for pages
* this way, the number shown on the dashboard is consistent with the listing they see when they click on the number

\- however, there is a risk that an editor on a site with a large bank of available images (but without edit rights on them) is accustomed to the dashboard telling them that they have access to 10000 images, and will panic when that number suddenly drops after a Wagtail upgrade...

**Comment by georgeyk** [comment]
hey @gasman 

Sounds reasonable to keep that count as is. After all, the resources are available to them.
I'll close the PR if everyone agrees.

**Comment by mr-klint** [comment]
I understand your comment @gasman, I'm just wondering what would be the best solution for this since there will also be setups where there's users that won't be able to see, nor use the documents but still see the count

**Comment by gasman** [comment]
I don't think this is going to be fixable until Wagtail has proper support for fully isolated multi-site setups (#4288, #4488). As it stands, all users can see the full set of images / documents through the chooser interfaces, so showing the full count is _technically_ correct - in certain situations it might not be the expected value, but within Wagtail's current design there's no way for us to know that.
