### ISSUE TITLE
The HTML tag autocomplete=off is not recognised when two DateTimeField fields are in place

### ISSUE THREAD

**Issue by kevinhowbrook** [wagtail/wagtail#5134]
### Issue Summary

When using 2 instances of DateTimeField, the autocomplete=off implemented in https://github.com/wagtail/wagtail/pull/4793 is visible in the HTML for both fields, but only works for one.

![error example](https://i.imgur.com/0Cvsc0s.jpg)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit home.models.HomePage as follows...

```[python]
from django.db import models

from wagtail.core.models import Page
from wagtail.admin.edit_handlers import FieldPanel

class HomePage(Page):
    publication_date = models.DateTimeField(null=True, blank=True)
    updated_date = models.DateTimeField("Modified date", blank=True, null=True)

    content_panels = Page.content_panels + [
        FieldPanel('publication_date'),
        FieldPanel('updated_date'),
    ]

```
3. Run `python manage.py makemigrations` and `python manage.py migrate`
4. Observe the error by edditing the home page and click to focus between the two new date fields

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7.1
* Django version: 2.1.7
* Wagtail version: 2.4
* Operating System: Linux x86_64
* Browser version: Chrome 70.

**Comment by gasman** [comment]
Fixed in #5136
