### ISSUE TITLE
Modal search doesn't correctly handle results

### ISSUE THREAD

**Issue by Esperk** [wagtail/wagtail#5140]
### Issue Summary

Issue #4594 describes how the page search sometimes shows incorrect results when typing slow. This issue is resolved for the page search modal in PR #5137.
But the same issue applies to other AJAX search functionality. I'm not fully familiar with all search components but i've found this issue in at leats the following components:

1. The `snippet-chooser-modal.js`
2. The image search component `image-chooser-modal.js`

### Steps to Reproduce

_Mostly copied from issue #4594_ 

1. Open any chooser modal, such as the one for creating internal links.
2. Use the search.
Here are two different videos showcasing the issue. https://imgur.com/a/m7Fu4Oj
It's easier to reproduce with throttled internet speed.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: `3.5.6`
* Django version:`2.1.7`
* Wagtail version: `2.5a0`
* Browser version: OSX 10.13.6 with Chrome 72

**Comment by thibaudcolas** [comment]
👍 thanks for opening this. I wouldn't be surprised if it happened with the document chooser as well, and most likely a few other places. Throughout Wagtail’s code, I think it would be good to look at all the AJAX call sites (`$.ajax`, `$.get*`, etc) and make sure they are debounced after user input, and cancel previous requests.

**Comment by SaptakS** [comment]
Hello @thibaudcolas @Esperk ,

I have identified most of the codes that might have a similar issue including the above mentioned ones. I would love to work on this issue, if that's fine.

**Comment by gasman** [comment]
Fixed in #5741
