### ISSUE TITLE
FEATURE REQUEST:  Delete unused tags instead of returning in the list of potential tags

### ISSUE THREAD

**Issue by DanielSwain** [wagtail/wagtail#5152]
In keeping tags organized, it would be helpful if, when a lookup is done in the Wagtail admin while typing a tag name, any tag that is found that is not connected to any items would be deleted.
```
if tag.taggit_taggeditem_items.count() == 0:
    tag.delete()
```
For example, if someone typed "Newsletters" for a tag name but decides that it should really be "Newsletter", "Newsletters" is continually returned along with the preferred "Newsletter" even though "Newsletters" is no longer used as a tag.  This will likely result in user confusion and possible mis-classification on future document uploads.

**Comment by ababic** [comment]
Hi @DanAtShenTech. While I agree things could be improved here, I think deleting tags on lookup like this could result in some undesirable behaviour where multiple editors are using the CMS simultaneously, and might not have saved their changes.

I think we also might need to be cautious of pages saved as drafts. I could be wrong, but I don't think the Page -> Tag relationships are saved to the database until the page is published - which would make it a touch more difficult to work out which tags are definitely not being used.

**Comment by DanAtShenTech** [comment]
@ababic I did wonder if this feature request might be viewed as being risky, and I see the point of your first paragraph.  I haven't looked at the code, but am wondering whether a get_or_create is issued for the Tag in some fashion when an image or a document with a tag is saved.  If so, then it seems it wouldn't matter if a tag that had just been retrieved by user 1 was, in the meantime, deleted by user 2's call to the tags table because it would just be recreated as needed when user 1 saves their image or document.

In your paragraph 2 you mention Page -> Tag relationships.  I hadn't thought about this use case; I was only thinking about the built-in Wagtail tagging functionality for images and documents.  But I'm wondering, again, whether this situation wouldn't be handled automatically if a get_or_create is issued for the Tag upon saving the Page.

Hoping this isn't closed until it's discussed a little more.

**Comment by ababic** [comment]
> Hoping this isn't closed until it's discussed a little more.

Sure, I'm not looking to shut this down. It'd be a decent improvement if done right. I just think it requires further investigation is all :)

**Comment by ababic** [comment]
@DanAtShenTech would you be willing to do a little investigation here into how/when the Tag associations are saved, and possibly some crude experimentation into how the various views handle Tags being deleted before saving/publishing (deleting Tags via a django shell locally might work)? 

If we can rule out the risk, or identify sensible ways to mitigate it, that would put us all in a much better place for deciding what to do next.

**Comment by DanAtShenTech** [comment]
@ababic, yes, I'll look into that.

**Comment by kaedroho** [comment]
There's an open PR for improving tag management here (including an interface for managing available tags): https://github.com/wagtail/rfcs/pull/28

Just awaiting feedback from more people before it can be approved and implemented.

**Comment by fertek** [comment]
There is a way how to delete an unused tags in Wagtail admin. This is all it takes:
```
from taggit.models import Tag as TaggitTag

@register_snippet
class Tag(TaggitTag):
    class Meta:
        proxy = True
```
Now, tags can be edited and deleted in Snippets section of Wagtail admin.

source: https://www.accordbox.com/blog/wagtail-tutorials-building-blog-part-3/#tags

**Comment by kaedroho** [comment]
Thanks @fertek, this feature is actually covered in an RFC: https://github.com/wagtail/rfcs/pull/28

Hopefully will get that approved soon so we can begin development!

**Comment by DanielSwain** [comment]
I just discovered that there is now a [recipe in the Wagtail docs](https://docs.wagtail.org/en/stable/reference/pages/model_recipes.html#managing-tags-with-wagtail-s-modeladmin) that, while not automatic as I had first proposed, provides the functionality needed to accomplish what is needed.  Closing this feature request.

**Comment by DanielSwain** [comment]
I just discovered that there is now a [recipe in the Wagtail docs](https://docs.wagtail.org/en/stable/reference/pages/model_recipes.html#managing-tags-with-wagtail-s-modeladmin) that, while not automatic as I had first proposed, provides the functionality needed to accomplish what is needed.  Closing this feature request.
