### ISSUE TITLE
Can't set image upload directory

### ISSUE THREAD

**Issue by mjlabe** [wagtail/wagtail#5158]
### Issue Summary

I have deployed my Wagtail site and all the static content loads except images uploaded by the user. I have set DEBUG = False, set my directories to:

STATIC_ROOT = home/user/static
MEDIA_ROOT = home/user/media

The problem is that Wagtail is uploading images to:

home/user/project/media/

Is there a way to set the image upload directory that is different than plain Django?

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Change MEDIA_ROOT
3. Set DEBUG = False 
4. Run project, try to upload image and see it all uploads to home/user/project/media/

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7
* Django version: 2.2
* Wagtail version: 2.3
* Browser version: N/A

**Comment by lb-** [comment]
This is possible when using a custom image model. 

However it was not documented. 

Closing as resolved and se below for the WIP documentation for this. 

https://github.com/wagtail/wagtail/pull/8228

Issue raised to add documentation https://github.com/wagtail/wagtail/issues/2601
