### ISSUE TITLE
Add a Whoosh search backend

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#517]
In the database backend, we are unable to search on fields of subclasses of the model being searched. We are also unable to index callable fields. Elasticsearch is quite a heavy dependency and might be overkill for many sites.

I think Whoosh would be a good option for those who need to use the more advanced features of wagtailsearch, but don't wan't to use Elasticsearch which is a bit of a resource-hog.

https://pypi.python.org/pypi/Whoosh/

**Comment by sfermigier** [comment]
OK this issue has been closed but there is nothing that tells us if it has been fixed or rejected.

**Comment by kaedroho** [comment]
Sorry for no update on this. I'm still in favour of a Whoosh search backend in Wagtail.

I closed a few tickets a while ago (including this one) on the grounds that they were just random ideas I had that didn't look like they were going anywhere. I must've misunderestimated the demand for this one so I'll reopen it now!

**Comment by kofic** [comment]
Please give us a status update

**Comment by gasman** [comment]
@kofic No-one has picked this task up, as far as I know.

**Comment by kaedroho** [comment]
This PR, https://github.com/torchbox/wagtail/pull/2571, should make implementing a backend for Whoosh much easier than before. I'll probably wait until all those search PRs have been merged for starting work on this.

**Comment by melinath** [comment]
+1 for a whoosh backend!

**Comment by DDiran** [comment]
Hosting a site on a service that doesn't allow Elasticsearch - so only solution AFAIK is to use default wagtail backend which is not ideal. +1 for whoosh or any viable alternative which is a light dependency

**Comment by BertrandBordage** [comment]
@DDiran You also have the PostgreSQL search backend since Wagtail 1.10.

**Comment by DDiran** [comment]
@BertrandBordage Thanks, but the hosting service I use charges extra for PostgreSQL so I'm stuck with mySQL :/

**Comment by michael-yin** [comment]
@kaedroho @melinath @DDiran 

I have built a whoosh backend for Wagtail [wagtail-whoosh](https://github.com/michael-yin/wagtail-whoosh)

Right now it can work Wagtail 2.0 - 2.1 , it can pass all Wagtail search backend unit tests. And I will keep making it work with latest Wagtail.

It is built to support small Wagtail project or Wagtail project based on Mysql db.

Please create issue if you have any question.

Thanks.

**Comment by kaedroho** [comment]
Hey @michael-yin This looks awesome, thanks for building it!

Would you be happy/is it ready for us to do a detailed review of it? If there are no major issues, I'd be happy to link to it from the Wagtail core docs and consider this issue closed!

**Comment by michael-yin** [comment]
Hi, @kaedroho 

This project now works fine from Wagtail 2.0 to Wagtail 2.1.

And I plan to make it work with the latest stable Wagtail version.

But I also have a problem which might need your help.

In Wagtail 2.2, some low level API has changed, `SearchQueryShortcut` and `Term` has been changed to other class.

I did a simple test it seems some methods also been removed. 

Now I know there are two solutions.

1. I can use this type of code.

```
if wagtail.VERSION >= (2, 2):
    pass
else:
    pass
```

2. I can support Wagtail 2.0-2.1 in 1.x version and support Wagtail 2.2-latest in 2.x version.

**Comment by gasman** [comment]
> Would you be happy/is it ready for us to do a detailed review of it? If there are no major issues, I'd be happy to link to it from the Wagtail core docs and consider this issue closed!

I think there'd be definite advantages to this being part of Wagtail core rather than just a third-party extension - we can set it as the default backend on the project template so that new projects get full-featured search out of the box, rather than the limited database-only backend.

**Comment by gasman** [comment]
Hi @michael-yin - have just given wagtail-whoosh a try, and it's looking really good!

I'd suggest creating a separate 2.x release for Wagtail >2.2 compatibility - the internal API for search queries is not yet stable (although it's on our todo list to standardise and document it - #4170) and I suspect it's going to be difficult to keep a single codebase compatible with multiple versions.

As mentioned above, I'd be keen to merge this into Wagtail core once it's been brought up to date and given some real-world testing. Would you be happy for us to move the wagtail-whoosh repository into the https://github.com/wagtail/ organisation, to make it more "official"? (You'll still remain as maintainer, of course :-) )

**Comment by gasman** [comment]
@michael-yin Excellent, thanks!

I've sent you an invitation to the Wagtail organisation. Once you've accepted this, you'll need to initiate the transfer as described at https://help.github.com/articles/transferring-a-repository/#transferring-a-repository-owned-by-your-personal-account , entering `wagtail` as the organisation name - I'll accept this request when I receive it.

**Comment by thibaudcolas** [comment]
Reviewed today – we have [wagtail-whoosh](https://github.com/wagtail/wagtail-whoosh). If the package gets more maintained, great, if not, the package will move to [wagtail-nest](https://github.com/wagtail-nest).
