### ISSUE TITLE
I reported a critical security issue to hallo@wagtail.io 2 months ago and nothing happened.

### ISSUE THREAD

**Issue by codingcatgirl** [wagtail/wagtail#5170]
On the 30th of January, to be precise. No bugfix on master as far as i can tell since then and no new release either. This is pretty concerning.

What's going on? Does that address not receive emails? Should i send an E-Mail somewhere else? 

To whom it may concern, i sent a second email just now including details on responsible disclosure.

**Comment by codingcatgirl** [comment]
Well this is new. 
```
<hallo@wagtail.io>:
Remote host said: 550 5.1.1 <hallo@wagtail.io>: Recipient address rejected: User unknown in virtual alias table
```

Looks like you removed that address and didn't check your inbox before you did. I emailed you again at 
hello@torchbox.com.

**Comment by tomdyson** [comment]
Thanks for getting in touch. We've received your message today and replied. We've never had a hallo@ email address.

**Comment by codingcatgirl** [comment]
When i found the issue, hallo@wagtail.io was the only address i could find on your website, and it was for your hosting service if i remember correctly.

**Comment by gasman** [comment]
Closing as this is now being handled over email.
