### ISSUE TITLE
StreamField should accept min_num / max_num / block_counts directly

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#5175]
`StreamBlock` accepts keyword arguments `min_num` / `max_num` / `block_types` to limit the number of blocks in the stream:

    body = StreamField(
        blocks.StreamBlock([
            ('heading', blocks.CharBlock()),
            ('paragraph', blocks.RichTextBlock()),
        ], max_num=3)
    )

However, these arguments are only available when using an explicit `StreamBlock` - ideally `StreamField` itself should recognise these too, so that the above could be rewritten as:

    body = StreamField([
        ('heading', blocks.CharBlock()),
        ('paragraph', blocks.RichTextBlock()),
    ], max_num=3)

This probably just requires `StreamField` to pass on these arguments when [creating its internal `StreamBlock`](https://github.com/wagtail/wagtail/blob/3134ffa119c15097c8b3c2a0422dd89f7c23304a/wagtail/core/fields.py#L48) (along with corresponding tests / documentation updates).

**Comment by haydnnewport** [comment]
I've created a PR for this on #5185, but it currently doesn't update any documentation - Would adding some arguments definition to `streamfield.rst`, above the "Basic block types" section sound like roughly what you'd be looking for?

**Comment by paqman85** [comment]
I understand that the only bit left on this one is to update the docs. I'll take care of it if it's still an open issue.

**Comment by gasman** [comment]
@paqman85 Not quite - the issue mentioned on https://github.com/wagtail/wagtail/pull/5185#issuecomment-478083855 (ensuring max_num / min_num are respected when the first argument to StreamField is a StreamBlock class rather than a list of blocks) is still open. That may or may not be solvable without going down the rabbit-hole of #4306...

**Comment by paqman85** [comment]
> @paqman85 Not quite - the issue mentioned on https://github.com/wagtail/wagtail/pull/5185#issuecomment-478083855 (ensuring max_num / min_num are respected when the first argument to StreamField is a StreamBlock class rather than a list of blocks) is still open. That may or may not be solvable without going down the rabbit-hole of #4306...

Oh boy. I'll do some digging and see if I can figure it out.

**Comment by paqman85** [comment]
Yes, this is quite the rabbit hole indeed. I'm afraid it's out of my current understanding. 😞 Perhaps not the best labelling for this one?

**Comment by gasman** [comment]
Fixed in #6718
