### ISSUE TITLE
Use bakerydemo instead of default Wagtail project in Squash PR demos

### ISSUE THREAD

**Issue by tomdyson** [wagtail/wagtail#5178]
We now have #5118 which provides a very useful demo instance for PRs. It currently creates a minimal site using `wagtail start`. It would be more useful to have a demo instance of [bakerydemo](https://github.com/wagtail/bakerydemo), so we can test more features. Since @gasman does all his testing against bakerydemo, we can be confident that it should run against the latest master.

**Comment by Stormheg** [comment]
We finally got around to doing this! Done in https://github.com/wagtail/wagtail/pull/10721

Here is an example deployment of Bakerydemo on Squash: https://stormhegfeaturesquash-use-bake-4lwq9.squash.io/
