### ISSUE TITLE
Wagtail version no longer visible in settings menu

### ISSUE THREAD

**Issue by haydnnewport** [wagtail/wagtail#5189]
### Issue Summary

The wagtail version no longer appears in the Settings sub-nav, where it was added in #2769.
 Initially I thought this was an HTML change, but the text is still there, it's just the same colour as the sub-nav background.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Add an superadmin user
3. Log in to the admin panel
4. Click settings
5. Optionally, try and highlight the bottom of the settings panel, so you can see the version there

This used to be visible with a low contrast (possibly non-compliant) colour difference from the background of the nav.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes. Noticed it in one of the Squash builds

### Technical details

* Python version: 3.6.1
* Django version: 2.1.7, 1.11.18
* Wagtail version: 2.5a0, 2.3
* Browser version: [Chrome 73](whatsmybrowser.org/b/SUXKNHX)

**Comment by thibaudcolas** [comment]
Thanks for the report @haydnnewport! This will be fixed in Wagtail v2.6 (#5236).
