### ISSUE TITLE
Feature Request:  "manage.py" to purge old page revisions

### ISSUE THREAD

**Issue by SundialServices** [wagtail/wagtail#5192]
When you "save a draft," as of course you do many times when working on a new page, it appears that the draft pages are never cleaned-up.  This can cause the database file to grow quite large.

We need a very convenient `manage.py` command option to purge the database of all page revisions that are not the current ones.  Only the most-recent version (published or not) should remain.

**Comment by gasman** [comment]
Thanks for the suggestion @SundialServices! Just to note that we'd additionally need to preserve revisions that are submitted for moderation, and ones that are scheduled for publishing with a future go-live date.

**Comment by SundialServices** [comment]
"Entirely agreeing with the foregoing ..." here for now – and, strictly for the record – is a simple-minded `sqlite3` query that "gets the job done" ... for me ... right now ...

```
delete from wagtailcore_pagerevision 
  where id in (select r.id from wagtailcore_pagerevision r 
    left join wagtailcore_page p on r.id=p.live_revision_id 
    where p.live_revision_id is null);
```

**Comment by unihsing** [comment]
MARK
How might I remove old revisions from the Wagtail database? I see that every time I make a change the previous revision of the page is kept in the database ... very nice, but how do I "take out the trash?"

In other words: "okay, this page is now finished, and I don't wish to keep previous revisions of it anymore." You'd think this would be easy – but, where is it?

**Comment by maziar-dandc** [comment]
> 769625 rows affected in 21 m 41 s 934 ms

**Comment by tomdyson** [comment]
If anyone contributes this feature, I suggest an optional `--days-older-than` argument, so that it could be run on a nightly schedule:

`./manage.py purge_revisions --days-older-than=14`

Note that revisions that are submitted for moderation, and ones that are scheduled for publishing with a future go-live date should be preserved even if they are older than `--days-older-than`.

**Comment by tomdyson** [comment]
Does this look right? If so I'll make a PR with a management command.

```python
import datetime as dt
from wagtail.core.models import PageRevision

def purge_revisions(days=None):
    # exclude revisions which have been submitted for moderation
    purgable_revisions = PageRevision.objects.exclude(
        submitted_for_moderation=True
    ).exclude(
        # and exclude revisions with an approved_go_live_at date
        approved_go_live_at__isnull=False
    )

    if days:
        purgable_until = dt.datetime.now() - dt.timedelta(days=days)
        # only include revisions which were created before the cut off date
        purgable_revisions = purgable_revisions.filter(created_at__lt=purgable_until)

    deleted_revisions_count = 0

    for revision in purgable_revisions:
        # don't delete the latest revision for any page
        if not revision.is_latest_revision():
            revision.delete()
            deleted_revisions_count += 1

    return deleted_revisions_count
```

**Comment by jacobtoppm** [comment]
Once the `feature/workflow` branch is merged, `PageRevision.submitted_for_moderation` will only be used for legacy pages going through the old style moderation system. New pages will be submitted to the workflow system, so an additional check will be required.

Strictly speaking, a check for whether the revision itself is in moderation would simply mean excluding any `PageRevision` linked to a `TaskState` with `status` of `TaskState.STATUS_IN_PROGRESS`. However, in order to maintain a coherent history of the current workflow, I think it would be nicer to delete only revisions with no in progress `WorkflowState` instead. This could be done as follows:

```
import datetime as dt
from wagtail.core.models import PageRevision, WorkflowState

def purge_revisions(days=None):
    # exclude revisions which have been submitted for moderation
    purgable_revisions = PageRevision.objects.exclude(
        submitted_for_moderation=True
    ).exclude(
        # and exclude revisions with an approved_go_live_at date
        approved_go_live_at__isnull=False
    ).exclude(
        task_states__workflow_state__status=WorkflowState.STATUS_IN_PROGRESS
    )

    if days:
        purgable_until = dt.datetime.now() - dt.timedelta(days=days)
        # only include revisions which were created before the cut off date
        purgable_revisions = purgable_revisions.filter(created_at__lt=purgable_until)

    deleted_revisions_count = 0

    for revision in purgable_revisions:
        # don't delete the latest revision for any page
        if not revision.is_latest_revision():
            revision.delete()
            deleted_revisions_count += 1

    return deleted_revisions_count
```

**Comment by tomdyson** [comment]
Thanks @jacobtoppm! And something like this to check for Workflow support?

```python
try:
    from wagtail.core.models import WorkflowState
    workflow_support = True
except ImportError:
    workflow_support = False

def purge_revisions(days=None):
    # exclude revisions which have been submitted for moderation in the old system
    purgable_revisions = PageRevision.objects.exclude(
        submitted_for_moderation=True
    ).exclude(
        # and exclude revisions with an approved_go_live_at date
        approved_go_live_at__isnull=False)

    if workflow_support:
        purgable_revisions = purgable_revisions.exclude(
        # and exclude revisions linked to an in progress workflow state
        task_states__workflow_state__status=WorkflowState.STATUS_IN_PROGRESS
    )
```

**Comment by jacobtoppm** [comment]
No problem - yes, that looks good to me!
