### ISSUE TITLE
Use `template_name` in definition of AdminPageChooser

### ISSUE THREAD

**Issue by patta42** [wagtail/wagtail#5193]
Hi!

The hard-coded definition of the template name in `wagtail.admin.widgets.AdminPageChooser`

https://github.com/wagtail/wagtail/blob/c447f75bd4a74566db71a45037067692b4342b0d/wagtail/admin/widgets.py#L200

makes it complicated to change the template. It is not only that one needs to override a full method instead of a tiny property when deriving from this class. The major problem is that `super().render_html(...)`, as called for the template context,

https://github.com/wagtail/wagtail/blob/c447f75bd4a74566db71a45037067692b4342b0d/wagtail/admin/widgets.py#L198 

does not result in the rendered `input` anymore, but in the `PageChooser`-Panel rendered with the old template if one uses a class derived from `wagtail.admin.widgets.AdminPageChooser`.

Solution would be, of course, to use `template_name`. I would even suggest to use some type of `get_context` or `get_context_data`, which simplifies deriving from any class a lot.

**Comment by gasman** [comment]
Now done in the new BaseChooser implementation in #8501.
