### ISSUE TITLE
Django Template Comments are printed in the output HTML

### ISSUE THREAD

**Issue by jnsdrtlf** [wagtail/wagtail#5194]
### Issue Summary

The comments of a block are printed in the output HTML

### Steps to Reproduce

1. Create the following blocks:
```python
class CustomBlock(StructBlock):
    buttons = OptionalButtonBlock(max_num=2)

    class Meta:
        template = 'blocks/custom.html'

```
2. Create the template for this block. Add a comment `{# Comment #}` to the `blocks/custom.html` file.
3. Add the block to your page:
```python
class HomePage(Page):
    body = StreamField([
        ('custom', CustomBlock()),
    ])

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]
```
4. Render the block on your page:
```jinja
{% for block in page.body %}
    {% include_block block %}
{% endfor %}
```
5. Create a site in the admin panel and test it

The comments in `blocks/custom.html` are printed in the output HTML.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **yes**

### Technical details

* Python version: 3.7.3
* Django version: 2.1.7
* Wagtail version: 2.4

**Comment by timorieber** [comment]
[Django comments](https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#comment) are written `{% comment %}your comment{% endcomment %}`. This template engine is used by default.

I think what you used is Jinja2 syntax. [This engine can be enabled](http://docs.wagtail.io/en/v2.4/advanced_topics/jinja2.html), too.

**Comment by gasman** [comment]
@timorieber `{# comment #}` is valid in Django template syntax too: https://docs.djangoproject.com/en/2.2/topics/templates/#comments

**Comment by jnsdrtlf** [comment]
@timorieber ahh I see, that's my fault. @gasman yes, but only for single line comments. And that is exactly what I did wrong. Thanks for your help
