### ISSUE TITLE
Test fails when user model doesn't have `username` attribute

### ISSUE THREAD

**Issue by victorcarrico** [wagtail/wagtail#5205]
### Issue Summary
 I'm using a custom user model which uses email field as `USERNAME_FIELD` and it doesn't have `username` field. So, when I'm running my tests the `login()` from `WagtailTestUtils` is failing.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. In your user model:
    - Remove the field `username`
    - Set `USERNAME_FIELD = 'email'
3. Create a test class which inherits from `wagtail.tests.utils.WagtailPageTests`
    ```
    class FooTest(WagtailPageTests):
        def test_foo(self):
            pass
    ```
4. Run the test
5. You'll get: AttributeError: 'User' object has no attribute 'username'

- This probably was introduced in this [commit](https://github.com/wagtail/wagtail/commit/9d333760c7f7bae212091af031d6f89c24851da0#diff-14af85e2843905e20acd0fef6d4d1111)
- I think the proper way to fix it may be changing `user.username` to `getattr(user, user_model.USERNAME_FIELD)` in this [line](https://github.com/wagtail/wagtail/commit/9d333760c7f7bae212091af031d6f89c24851da0#diff-14af85e2843905e20acd0fef6d4d1111R36)

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.6.7
* Django version: 2.1.8
* Wagtail version: 2.4

**Comment by gasman** [comment]
Thanks for the report @victorcarrico! I believe this issue is being fixed by #5066, but - as I recall - I was having trouble finding a way to test this fix within Wagtail's own unit tests, because it requires additional customisations to the login template beyond what's documented at http://docs.wagtail.io/en/v2.4/advanced_topics/customisation/custom_user_models.html.

**Comment by victorcarrico** [comment]
Thank you, @gasman!

**Comment by loicteixeira** [comment]
The proposed fix was merged. Closing the issue.
