### ISSUE TITLE
Update Redux DevTools integration

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#5214]
### Issue Summary

The Redux DevTools are logging a deprecation warning in the browser console on Wagtail’s admin:

```
VM23:1 `window.devToolsExtension` is deprecated in favor of `window.__REDUX_DEVTOOLS_EXTENSION__`, and will be removed in next version of Redux DevTools: https://git.io/fpEJZ
```

### Steps to Reproduce

1. Install the Redux DevTools Chrome extension
2. Open the browser console on the admin of any Wagtail site

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

---

Fixing this should just be a matter of replacing the existing function call with the new one. Here is the relevant code:

https://github.com/wagtail/wagtail/blob/d8b2d087ca12840013e72d1ab1e8edc62518b5c2/client/src/components/Explorer/index.js#L31-L35

**Comment by jjanssen** [comment]
I was just about to open this 😂

**Comment by thibaudcolas** [comment]
@jjanssen I saw it on @BertrandBordage's screen sharing and couldn't resist any longer!
