### ISSUE TITLE
Limit max number of pixels for animated GIFs

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#5225]
https://github.com/wagtail/wagtail/pull/5097 implemented a check to prevent images that decompress to too many pixels from being uploaded. It does this by simply multiplying the width with the height.

However, for animated GIFs, we need to also take into account the number of frames in the image.

Note: This number should be total number of pixels in an uncompressed image, so this value shouldn't take into account any savings made by the file format due to techniques like differential encoding.

**Comment by gasman** [comment]
Fixed in #5227 / #5627
