### ISSUE TITLE
Add table caption option as part of TableBlock for accessibility

### ISSUE THREAD

**Issue by zmustapha** [wagtail/wagtail#5235]
Web Content Accessibility Guidelines (WCAG) recommends that tables have labels, or captions, or summaries so users with screen readers can find out ahead about the table contents.

It would be nice to have a caption field option in the TableBlock, and have the tag in the template, something like this:

```
<table>
    {% if table_caption %}
       <caption>{{ table_caption }}</caption>
    {% endif %}
    {% if table_header %}
        <thead>
            ...
        </thead>
    {% endif %}
        <tbody>
            ...
        </tbody>
</table>
```
This way, the heading is associated to the table itself.

By the way, this proposed template improvement is for TableBlock module, the one using `handsontable`. That way, editors can have the option to define column or row header (as it is already), and also add caption.

**Comment by thibaudcolas** [comment]
👍 that would be a valuable addition. If you or anyone else wants to tackle this, PR #4906 might be a good example of the type of changes required – adding a new field in the admin UI, changing the templates to render the table, etc.

**Comment by rjpruitt16** [comment]
I would like to work on this.

**Comment by rjpruitt16** [comment]
im have a little trouble figuring out how to use tableBlock. Can you give me an example @thibaudcolas?

**Comment by gasman** [comment]
Hi @rjpruitt16 - please see http://docs.wagtail.io/en/stable/reference/contrib/table_block.html , or use [our support channels](https://docs.wagtail.io/en/stable/support.html) for further assistance.

**Comment by rjpruitt16** [comment]
@gasman thank you

**Comment by rjpruitt16** [comment]
https://github.com/wagtail/wagtail/pull/5446

**Comment by gasman** [comment]
Completed in #5446.
