### ISSUE TITLE
TestPageEditHandlers test cases not running

### ISSUE THREAD

**Issue by tomkins** [wagtail/wagtail#5237]
### Issue Summary

Tests for `TestPageEditHandlers` aren't being executed.

Code coverage for `test_edit_handlers.py` shows that all of the tests are currently missing: https://codecov.io/gh/wagtail/wagtail/src/56fde4918789210c79e2aac910aaf71335d2571d/wagtail/admin/tests/test_edit_handlers.py#L122

This is due to the decorator being added to most of the tests causing the functions to be replaced with None.

### Steps to Reproduce

Run `tox`, `coverage html` will show missing coverage.

**Comment by lb-** [comment]
Fixed by #5238 
Merged in https://github.com/wagtail/wagtail/commit/0644f90bef282180e0bb1070e056da155213745f
