### ISSUE TITLE
WAGTAIL_ALLOW_UNICODE_SLUGS conflicts with WAGTAIL_APPEND_SLASH

### ISSUE THREAD

**Issue by germn** [wagtail/wagtail#5248]
### Issue Summary

Setting `WAGTAIL_ALLOW_UNICODE_SLUGS=False` breaks `WAGTAIL_APPEND_SLASH=True` redirects

### Steps to Reproduce

1. Set `WAGTAIL_APPEND_SLASH = True` (default value)
2. Ensure slash redirects work: `/example` -> `/example/`
3. Set `WAGTAIL_ALLOW_UNICODE_SLUGS = False`
4. Ensure redirects are broken: `/example2` -> 404

On step 4 it's better to use fresh url to avoid browser redirect info caching.

### Technical details

* Python version: 3.7.3
* Django version: 2.1.8
* Wagtail version: 2.4
* Browser version: Chrome 73

**Comment by lb-** [comment]
@germn  - thank you for submitting clear steps.

I am having trouble reproducing this issue (in Bakery demo, with both 2.4 and 2.6 master branch).

On the non-admin pages (ie. blog, home etc), the append slash works correctly with or without the allow unicode slugs enabled.

* `/blog/bread-circuses` -> `/blog/bread-circuses/` works for any `WAGTAIL_ALLOW_UNICODE_SLUGS` option

On the admin (backend) pages, the slash is never added, no matter what the settings.

* `admin/pages/68/` - always works
* `admin/pages/68` - never works (404)

Could you clarify if this is for front facing pages or admin pages, also could there be any other info that can help reproduce the issue.

**Comment by germn** [comment]
@lb- sorry for not testing it on fresh project first, issue indeed needs another circumstances to be reproduced.

Redirect on non-admin pages can be broken by only one change: by adding `urlpatterns` serving something from `'/'` like shown [here](https://github.com/germn/wagtail_issue_5248/blob/bd29d50363b4d6012930821ace1b71e060103089/mysite/mysite/urls.py#L37) (here's [full repo](https://github.com/germn/wagtail_issue_5248) with simple reproducible project).

Reason I do this is to serve some static assets (like `robots.txt`) from root url. Not sure if it's a best way, but it doesn't seem something is wrong with this pattern either, right?

Anyway it has nothing to do with with what I wrote earlier, so I'm closing this issue. I'll be investigating it further to see if the behavior is expected or has something to do with Wagtail in the first place.

Sorry for trespassing your time.

**Comment by lb-** [comment]
@germn  - no issues at all.

In regards to a making the static URL path the root `/` - this makes sense for things like robots but will potentially cause issues down the road with naming conflicts (eg. if you have a page at 'images' it might conflict with an 'images' folder in the static directory).

not 100% sure as I have never done that, nonetheless it might be best to have a standalone rule for robots.txt 
this article is good: http://fredericiana.com/2010/06/09/three-ways-to-add-a-robots-txt-to-your-django-project/

Have a great rest of the week.
