### ISSUE TITLE
Is there a way to check which page is private or not in template

### ISSUE THREAD

**Issue by rfancn** [wagtail/wagtail#5250]
Sometimes, we need to distinguish the private pages and normal pages in template,  but it seems there is no modal reference for this purpose, the only way is to check the specific page is descendant of PageViewRestriction? Is there a plan to add this feature in the future?

**Comment by lb-** [comment]
@rfancn  - thank you for submitting an issue but Wagtail issues are best suited to bug reports or feature requests.

This kind of support question would be best suited to one of the community support options.

https://github.com/wagtail/wagtail/#community-support

Alternatively, please re-work this issue to use the issue template, for now we will close this issue though.
