### ISSUE TITLE
Ability to configure 'page' layout and 'block' queries via UI?

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#5251]
```
As a content manager
I would like to be able to manage all content, such categories for blog posts
So that I don't have to rely on a developer to manage fields and page layouts
```

```
As a content manager
I would like to configure parameterized queries and add them to a page layout
so I can create generic layouts that can be applied to all instances of a given content type
```

## Background
We are migrating a website from Drupal to Wagtail. In Drupal, we had two site building 'constructs' that we found quite useful:

- [Pages/Panels](https://www.drupal.org/project/panels)
- [Views](https://www.drupal.org/docs/8/core/modules/views)

I am trying to figure out a way to come close to the flexibility these offered in the Wagtail UI.

In effect, Pages/Panels were a semi-drag-and-drop layout builder UI, where a user could create a generic template that would be applied to content. The **layout** could include fields from the content, queries of related content, and even change dynamically based on other context information (like user role).

Views are basically a UI to introspect the database and construct queries, with possibility to pass in arguments from URL or other page context.

## Feature idea
So, I am wanting to explore the idea of a drag-and-drop layout builder for Wagtail that could be applied to 'content types'. It is akin to streamfield, but rather than associating a streamfield with a specific instance, the layout would be associated with a particular model (or even a subset of model instances). This blocks in this 'streamfield' editor could include parameterized queries displaying content in various forms.

I realize there would be some balance here of code and UI config, and that the code to support such capabilities would likely be quite abstract and introspective. 

Apologies if this post is a bit long. I am just wanting to seed the conversation, as these capabilities could be quite useful, at least as plugins, in the Wagtail ecosystem :-)

**Comment by brylie** [comment]
For clarification, I don't mean a 'drag and drop page builder' where end users would create arbitrary page layouts, although that would be cool. I am more specifically describing a 'template builder', where page templates are created and then applied generically to specific content types.

**Comment by gasman** [comment]
Hi @brylie - thanks for the suggestion.
I don't think this is something we want to pursue in Wagtail itself, although that definitely shouldn't rule out implementing it as a plugin.

It's always been a key design principle of Wagtail that we should embrace Django's ORM and templating as the way to do content modelling and page layout, and that replacing coding tasks with UI-based configuration is not necessarily desirable. Indeed, one of the motivations for creating Wagtail in the first place was that our front-end developers and designers found Drupal's panel-based approach too restrictive, and felt railroaded into creating "boxy" designs. Additionally, keeping configuration in code makes it possible to track changes with version control, and allows for reproducible deployments across development / staging / production. (More thoughts about this here: https://docs.wagtail.io/en/stable/getting_started/the_zen_of_wagtail.html#the-best-user-interface-for-a-programmer-is-usually-a-programming-language)

I wouldn't claim that writing code is always going to be superior to UI-based configuration in all circumstances, but coming up with something better is outside the scope of what Wagtail is trying to do.
