### ISSUE TITLE
Reorganise/refactor all JS into wagtail-client

### ISSUE THREAD

**Issue by jonnyscholes** [wagtail/wagtail#5252]
As part of an overall push to bring our frontend up to date with more modern practices we're going to migrate/update all of our JS components. This is a tracking issue to cover the reorganisation of older JS (mostly in `wagtail/wagtail/admin/static_src/`) in Wagtail to the newer paradigm (see `wagtail/client`).

This will require some refactoring as some of the current code is not designed to be transpiled. That required refactoring and some older managing dependancies may make some of this work quite involved. The plan is to take it feature by feature in PRs.

Once this is done that will enable us to work on removing gulp completely and use only Webpack for our frontend pipeline.

Components to move:

- [ ] blocks/*.js
- [ ] hallo-plugins/*.js
- [ ] modal-workflow.js
- [ ] privacy-switch.js
- [ ] core.js
- [ ] page-chooser-modal.js
- [ ] upgrade_notify.js -> #5256
- [ ] expanding_formset.js
- [ ] page-chooser.js
- [x] userbar.js
- [ ] hallo-bootstrap.js
- [ ] page-editor.js
- [x] submenu.js -> #5254

For the most part I'll be working on the refactoring myself with support from @thibaudcolas - but if you're interested in picking off one of these components let me know :)

**Comment by kaedroho** [comment]
Could we should go the other way and refactor the client into the wagtailadmin app? This would allow us to use the `gettext` function for translations (which must be in an app or Django won't be able to extract the strings).

**Comment by thibaudcolas** [comment]
I believe this is fairly out of date now that most of the code in this list has been moved, so will close this now.
