### ISSUE TITLE
False positive accessibility issues because of screen-reader-only content implementation

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#5269]
### Issue Summary

Some implementations of text that's meant only for screen readers are (incorrectly) flagged as having contrast issues by automated accessibility testing tools.

For example, text hidden with:

```css
.icon.text-replace {
    font-size: 0;
    line-height: 0;
    overflow: hidden;
}
```

If the text that this hides had a contrast issue with its background, this would be flagged by Axe and HTMLCS, even if said text is actually visually hidden.

Examples of where this happens:

- [ ] Mobile menu, `<div id="nav-toggle" class="nav-toggle icon text-replace">Menu</div>`
- [ ] "Add child pages" button on listing pages, `<a href="/admin/pages/133/add_subpage/" class="icon text-replace icon-plus-inverse" title="Add a child page to 'To delete'">Add child page</a>`
- [ ] "Explore" button on listing pages, `<a href="/admin/choose-page/63/?page_type=wagtailcore.page&amp;allow_external_link=true&amp;allow_email_link=true&amp;link_text=" class="icon text-replace icon-arrow-right navigate-pages" title="Explore subpages of 'Locations'">Explore</a>`

---

Wagtail already has an implementation of this that's compatible with automated accessibility testing, [`visuallyhidden`](https://github.com/wagtail/wagtail/blob/2668c05146b153be93890dc2331acaf66efd4e91/client/scss/tools/_mixins.general.scss#L61-L80). Parts of the UI using `text-replace` should switch to this.

Related: #1224, #5015, #4871, #2224

**Comment by SimonDEvans** [comment]
Martin Coote is currently working on this.
