### ISSUE TITLE
Possible bug after updating to 2.5: IndexError: list index out of range

### ISSUE THREAD

**Issue by jcuotpc** [wagtail/wagtail#5277]
I have recently updated one of my app to django 2.2 and wagtail 2.5.
Everything works fine when browsing but if I try to edit a page, I get:

`IndexError: list index out of range`

Here is my traceback: https://gist.github.com/jcuotpc/5e49e821d72087c473d7ee7c164a9518

The site is broken until I restart the development server. 
After running `./manage.py runserver` I can browse again, but if I try to edit I get back to the same error.

If I fall back to django 2.1.8 / wagtail 2.4 everything works fine. 
My python version is 3.6.8

Could this be an issue introduced by wagtail 2.5? What am I missing?
Unfortunately I cannot test wagtail 2.5 with Django 2.1.8 to rule out any problems with the newest django version.

**Comment by tomdyson** [comment]
The traceback indicates that the error is triggered by `debug_toolbar`. Is your version of Django Debug Toolbar compatible with Django 2.2?

**Comment by jcuotpc** [comment]
Thanks for the quick response!
Yes, the culprit seems to be the `debug_toolbar`.
I have uninstalled it and everything works fine.
It seems that there is a bug report for a similar issue on the debug_toolbar repo:
https://github.com/jazzband/django-debug-toolbar/issues/1155

**Comment by tomdyson** [comment]
Thanks for confirming.

**Comment by corwin39** [comment]
I have installed new alpha version debug-toolbar from https://github.com/jazzband/django-debug-toolbar/releases/tag/2.0a1
and everithing works fine again

**Comment by peter-brady** [comment]
Adding `django-debug-toolbar==2.0a1` to `requirements.txt` fixed this issue for me too.
