### ISSUE TITLE
Admin crashes when adding 3 children to any page

### ISSUE THREAD

**Issue by mfitzp** [wagtail/wagtail#5282]
Creating my first wagtail project and have stumbled across a particularly weird issue, whereby the admin crashes when adding 3 (>2?) children to any page.

**This is reproducible using a plain test project.**

### Issue Summary

When creating pages in the admin, adding a 3rd child page to a page results in the local server crashing. It does so without giving a traceback (triggers a "Python closed unexpectedly" on Mac).

Restarting the server with `python3 manage.py runserver` will restart without issue and the frontend of the site (including the created pages) remains completely navigable. Accessing the admin will trigger another crash.

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Complete the usual setup (`python3 manage.py migrate`) and create super user (`python3 manage.py createsuperuser`).
2. Access the admin
3. Create 3 child pages to any page (e.g. Home). On Publishing the 3rd wagtail will crash.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

[See here for a video showing the steps to reproduce the bug](https://vimeo.com/334255234/0fd4781b67).

Unfortunately since there is no traceback I imagine it's going to be pretty hard to pin down what the problem actually is. I would expect more people to hit this if it was generally occurring, so may just be a weird combination of system/versions I have.

### Technical details

* Python version: Python 3.7.2
* Django version: 2.2.1 (latest)
* Wagtail version: 2.5 (latest)
* Browser version: Chrome 74 on macOS (Mojave)

**Comment by mfitzp** [comment]
Just to update, this occurs when there are 3 or more pages _of the same type_. You can create as many child pages as you like, but only 2 can be the same class.

**Comment by gasman** [comment]
Hi @mfitzp - this sounds a lot like #5121. Could you try upgrading sqlite, or switching to Postgres?

**Comment by mfitzp** [comment]
Upgrading sqlite3 did the trick, thanks!
