### ISSUE TITLE
Allow images to be generated without width and height attributes

### ISSUE THREAD

**Issue by helenb** [wagtail/wagtail#5289]
### Issue Summary

Allow images to be rendered without width and height attributes when calling Rendition.img_tag.

Responsive images (that use srcset and sizes attributes) should not have width and height attributes.  All examples I have found exclude these attributes, and it makes sense to exclude them as the browser will be selecting the best size image to render on the fly. There is a template tag that we have used on various projects at Torchbox (and which would be useful to get into Wagtail core) which relies on calling Rendition.img_tag to render a responsive image with srcset and sizes attributes. But Rendition.img_tag always returns a width and height. A change was made in [this pull request](https://github.com/wagtail/wagtail/pull/1938) to allow attributes to be overridden, but you can't remove them all together.

I have not included the other parts of the bug report template as this isn't a bug so much as change request.

**Comment by tomdyson** [comment]
Thanks for raising this, @helenb. Can you support this using the `as` syntax? See "Generating the image 'as foo' to access individual properties" in the [image docs](http://docs.wagtail.io/en/v2.5.1/topics/images.html#more-control-over-the-img-tag).

**Comment by helenb** [comment]
@tomdyson yes, and that is how I have used it before. But it would be nice if we could get the responsiveimage tag into core (and perhaps resolve my ancient issue here: https://github.com/wagtail/wagtail/issues/285), and it ought to work as expected by default if it is added.

**Comment by ecolss** [comment]
> Thanks for raising this, @helenb. Can you support this using the `as` syntax? See "Generating the image 'as foo' to access individual properties" in the [image docs](http://docs.wagtail.io/en/v2.5.1/topics/images.html#more-control-over-the-img-tag).

@tomdyson @helenb 
Hey guys, this approach only supports `{% image .. %}` tag. What if I want the same feature when inserting images in `RichTextField`?? 
The `height` and `width` attribute also generated by wagtail, which is not responsive and annoying.

**Comment by thibaudcolas** [comment]
Fixed in #10781.
