### ISSUE TITLE
Django ModelAdmin or Wagtail Admin but not both...

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [wagtail/wagtail#5294]
This is a general question and not a bug report, let me know if there is a better place to ask this.

Wagtail ModelAdmin, sounds, looks and feels like Django ModelAdmin and has essentially the same purpose. However it is a different implementation that doesn't inherit from that class and therefore doesn't share the same code and instead replicate a lot of its listing features. I see some attempts to explain the reasons for that decision that in your documentation, although it's not entirely clear to me **why it has to be that way for 'simple' Django models** (i.e. non-Wagtail models).

The problem with the current implementation is that if a content editor wants to manage a list of model instances with admin actions (e.g. bulk delete or updates) or custom filters, ... site developers have only two options, none of which are particularly appealing:

1) extend Wagtail ModelAdmin and redevelop those features which have been available for many years in Django. That code will also be incompatible with Django so it somehow locks people in and pauses code sustainability issues. I see that as a kind of regression, some other Django CMSes do play better with Django Admin. Moreover it makes it less likely for third party Django admin features to be plugged into Wagtail;

2) use Django ModelAdmin but then the content editors will have to constantly switch between two admin environments (CMS in Wagtail and Models in Django Admin) which causes usability issues, requires them to learn two different user interfaces and provides limited support for integration between the two systems;

**Did I misunderstand something? Are there other options?**

**Comment by ababic** [comment]
Hi @geoffroy-noel-ddh,

>  I see some attempts to explain the reasons for that decision that in your documentation, although it's not entirely clear to me why it has to be that way for 'simple' Django models (i.e. non-Wagtail models).

It's simply a matter of resources, I'm afraid. I worked on `modeladmin` entirely on my own before it became part of Wagtail, and simply didn't get time to add support for bulk actions. And since it was added in version 1.5, I guess nobody has needed bulk actions quite so badly enough to build something and contribute it back (despite it being regularly requested).

> That code will also be incompatible with Django so it somehow locks people in and pauses code sustainability issues. I see that as a kind of regression, some other Django CMSes do play better with Django Admin.

The main reason Wagtail came into existence is because every other Django-based CMS before it had based itself on Django admin... and yet, none of them felt like a good fit for the projects that Wagtail was initially built for. Wagtail's primary focus has always been on delivering the best possible editing experience for content editors. Django is great for many things, but the admin UI has always lent itself better to more technical users.

**Comment by geoffroy-noel-ddh** [comment]
Hi @ababic , thanks for providing some context. I do appreciate that without your contribution there probably wouldn't be a way to list models in Wagtail admin. 

Would you be able to provide more information about the two questions I mentioned above? Namely 

a) the reason for not extending from Django ModelAdmin. I ask this because I could consider trying to adapt Django ModelAdmin for my own projects so it shows in Wagtail admin but if you believe this is not technically feasible and the reason why you decided to recreate your own implementation then I'd be interested to learn about that.

b) are there other options I'm not aware of than the two I mentioned above? If I wanted to have bulk actions or reuse my Django custom filters, I'd have to develop that in a new way, incompatible with Django ModelAdmin?

**Comment by ababic** [comment]
@geoffroy-noel-ddh In answer to your questions:

> a) the reason for not extending from Django ModelAdmin

The original version did! Although, that was a good few year ago, I think the decision to move away from that approach came when I wanted to make things swappable (views, and the various helpers). If you look at the actual implementation in any depth, you'll see that the overall implementation is a little inconsistent and not quite as modular as you'd think (I don't want to diss Django here - it's just very old code that has grown a lot over time). I found myself having to rewrite so much Django code just to get all of my custom bits to work, that it just became a hinderance. Some of the more modular elements are still used by the wagtail version (e.g. Filters) (and I imagine It might be possible to reuse some stuff for bulk actions too), but `ModelAdmin` and the `ChangeListView` were simply not abstract enough to make a good base.

> b)  Are there other options I'm not aware of than the two I mentioned above?

Wagtail has the [Snippets feature]( https://docs.wagtail.io/en/stable/editor_manual/documents_images_snippets/snippets.html) (which I think might even offer bulk deletion), but it doesn't have the configuration options that modeladmin has.

**Comment by geoffroy-noel-ddh** [comment]
Great, thanks for the useful info and taking the time to respond.
