### ISSUE TITLE
IE11 - dashboard icons are too big for all screen sizes up to "large"

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#5297]
### Issue Summary

In IE11, on the admin dashboard, the number of pages / images / docs metrics have enormous icons on most screen sizes (below ±1200px):

<img width="1195" alt="icons" src="https://user-images.githubusercontent.com/877585/57706103-01752000-765d-11e9-9c9c-bc6ed82815a5.png">

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Log into the admin in IE11
3. Look at the icons on screen sizes below 1200px

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Wagtail version: Tested in 2.3, 2.4, 2.5, 2.6a
* Browser version: IE11. Also tested Chrome, works fine there.

---

I think the relevant code is https://github.com/thibaudcolas/wagtail/blob/70a749b10a1b0c4dac527da28e54cbb3581a774e/wagtail/admin/static_src/wagtailadmin/scss/layouts/home.scss#L51-L67.

**Comment by gasman** [comment]
Closing as IE11 support is being dropped in 2.15.
