### ISSUE TITLE
Lack of construct_hook_name for settings_menu

### ISSUE THREAD

**Issue by Quadric** [wagtail/wagtail#5301]
### Issue Summary

There are some instructions how to "remove" unecessary components from main menu using "construct_hook_name" (ex. if we move it to other place in menu) using something like this:

```python
@hooks.register('construct_main_menu')
def hide_documents_menu_item(request, menu_items):
    menu_items[:] = [item for item in menu_items if item.name != 'documents']

```

but there is no "construction_hook_name" for settings_menu. It is possible to "add" new elements but can't remove elements already registered by wagtail... like redirects, collections etc. I have to iterate over menu_items of main menu, search for SettingsMenuItem... then iterate over it's menu_items and then remove what i want. 

### Steps to Reproduce

in file: `wagtail/admin/menu.py`

there are menus defined like this:

```python
admin_menu = Menu(register_hook_name='register_admin_menu_item', construct_hook_name='construct_main_menu')
settings_menu = Menu(register_hook_name='register_settings_menu_item')
```
i guess adding a construction hook would solve the problem

```python
admin_menu = Menu(register_hook_name='register_admin_menu_item', construct_hook_name='construct_main_menu')
settings_menu = Menu(register_hook_name='register_settings_menu_item', construct_hook_name='construct_settings_menu')
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Wagtail version: 2.5.1

**Comment by gasman** [comment]
Added in #5384.

**Comment by m-pasha** [comment]
Hi, @gasman when will released this update?

**Comment by gasman** [comment]
@m-pasha It will be in Wagtail 2.6, which is due for release on 1st August: https://github.com/wagtail/wagtail/wiki/Release-schedule
