### ISSUE TITLE
Error in generating test data for nested stream field blocks

### ISSUE THREAD

**Issue by thclark** [wagtail/wagtail#5323]
### Issue Summary
Error generating nested form data for testing a StreamField.

If a `StructBlock` contains a `StreamBlock(..., required=False)` field, use of `nested_form_data` generates an invalid data structure where that field (which shouldn't be required) is omitted from the data definition. When using this to generate a page in testing, the following error results:
```
Error
Traceback (most recent call last):
  File "/<...>/lib/python3.6/site-packages/django/utils/datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'body-0-value-content-count'
```

### Steps to Reproduce
The offending `block`:
```
class NaughtyBlock(StructBlock):
    title = CharBlock(required=False)   
    content = StreamBlock([
        ('whatever_field', CharBlock(required=False)),
    ], required=False)  # <------ 'content' field not required!!!
```
Put it in a page:
```
class BadPage(Page):
    body = StreamField([
        ('naughty', NaughtyBlock()),
    ], blank=True)

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]
```
The test case which arises the error:
```
class NestedStreamFieldTestCase(WagtailPageTests, WagtailTestUtils):
    def test_nested_streamfields(self):
        root_page = Page.objects.get(pk=1)
        data = nested_form_data({
            'body': streamfield([
                ('naughty', {
                    'title': 'the title',
                    # No 'content' field, since its not required
               }),
            ]),
        })
        print(data) # Prints the following: {'body-0-type': 'hero_section', 'body-0-value-title': 'the title', 'body-0-deleted': '', 'body-0-order': '0', 'body-count': '1'}
        self.assertCanCreate(root_page, SectionPage, data)
```

### Work around
Just add an empty streamfield to make your test case run:
```
data = nested_form_data({
    'body': streamfield([
        ('naughty', {
            'title': 'the title',
            'content': streamfield([]),
        }),
    ]),
})
```

### "So what do you want us to do about it?"

Probably nothing. Stick a wont-fix on and close it. I spent lots of trial and error figuring this out, because the error isn't very informative, and I wasn't familiar with the inner structure of the streamfield data. Googling turned up nothing. However, now that Google will index this issue, that's probably enough for future users to find and fix this quickly if they bump into it :)

If you're moved to do anything, a fuller example in the docs [here](http://docs.wagtail.io/en/v2.5.1/advanced_topics/testing.html#wagtail.tests.utils.form_data.streamfield), containing a nested structure, would probably suffice.

Unless of course this scratches on a deeper issue I haven't seen.

### Technical details

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

* Python version: 3.6.6
* Django version: 2.1
* Wagtail version: 2.3
* Browser version: n/a not a browser issue

**Comment by gasman** [comment]
Rediscovered this while looking through other issues relating to StreamField block validation...

I think your conclusion is correct - the need for the inner `streamfield` does make sense after you've made several non-obvious logical connections (namely: certain block types such as StructBlock and StreamBlock present themselves as bundles of form fields, just like the StreamField as a whole does; these bundles need to be flattened into the final form submission; the `nested_form_data` helper can do that flattening, and for that to happen, the `value` part of the `streamfield` argument needs to be a dict that `nested_form_data` can recurse into; logically there should probably be additional helper functions for building those dicts, except the one for StructBlock would have nothing to do, and the one for StreamBlock exactly matches `streamfield`). Even if we were to cover all of that information in the docs, someone with this problem would have to locate it all and piece it all together for their particular variation of the problem, and that would amount to figuring out the mechanism from first principles for themselves. At that point, having this issue out there and google-able is probably going to be as much or more valuable than anything we can put in the docs :-)
