### ISSUE TITLE
Tabbed UI in editing page are not marked up as tabs for screen readers

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#5330]
In the editing UI, Wagtail makes it possible to use panels to separate page fields into tabs. Unfortunately those tabs are not marked up as such for screen reader users (`tab` / `tablist` / `tabpanel` ARIA roles).

<img width="711" alt="wagtail-edit-tabs" src="https://user-images.githubusercontent.com/877585/58498487-0ca86f80-8176-11e9-8b05-a0023d0988f8.png">

**Comment by harrislapiroff** [comment]
I was also noticing this the other day! Glad someone opened an issue for it.

**Comment by thibaudcolas** [comment]
Fixed in #8266.
