### ISSUE TITLE
Add image dimensions in image gallery for screen reader users

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#5333]
### Issue Summary

In Wagtail’s image gallery, screen reader users navigate all of the available images as a list, with each image represented by its Title. Since titles aren’t always very descriptive, it would be nice to show more information on this to make it easier for users to understand the characteristics of specific images – for example by reading out the image’s dimensions.

Here is the current experience:

![image-metadata](https://user-images.githubusercontent.com/877585/58538557-4799ba00-81ed-11e9-9119-6671ddc89f73.gif)

With the dimensions added, announcing one of these would then be `link, Boston Cream Pie, 1024 by 683`.

### Steps to Reproduce

1. Go to the Wagtail admin’s image gallery, with a screen reader
2. Navigate through the list of images

**Comment by helenb** [comment]
PR: https://github.com/wagtail/wagtail/pull/5355

**Comment by thibaudcolas** [comment]
Fixed in #5355.
