### ISSUE TITLE
Integration of wagtail with django-import-export

### ISSUE THREAD

**Issue by adsk2050** [wagtail/wagtail#5347]
#### Feature request:

does django-import-export work well with  wagtail? It works as far as I have used it. 

But it doesn't have an admin interface for wagtail. 

I want to develop this functionality in wagtail. How to go about it?

**Comment by gasman** [comment]
Hi @adsk2050 - thanks for your interest! Adding new interfaces to the Wagtail admin is generally done by creating them as standard Django views (extending Wagtail's [base templates](https://github.com/wagtail/wagtail/tree/master/wagtail/admin/templates/wagtailadmin) as required), and registering them as part of the admin using hooks: http://docs.wagtail.io/en/v2.5.1/reference/hooks.html . For further pointers, please feel free to make use of our [support channels](https://docs.wagtail.io/en/stable/support.html).
