### ISSUE TITLE
Update the `attachment` policy for Documents, to ensure correct `Content-Disposition` header

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#5348]
The [current `attachment` processing](https://github.com/wagtail/wagtail/blob/master/wagtail/documents/views/serve.py#L45-L54) in the `server` function for `wagtail.documents.views.serve` is set to mark files as attachments without any logic to check whether that makes sense. This leads to a `Content-Disposition: attachment; filename="..."` which [forces the browser to download the document](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#As_a_response_header_for_the_main_body), rather than doing what makes the most sense for that document given what browsers know about what users want from specific documents, so this removes the ability for users to (for instance) click a pdf document link and then read that pdf in the browser itself, if the browser has the ability to natively render the document.

It feels like the correct approach here would be to always set `attachment` to `False`, and to let the browser deal with whether to show that Document or save it, instead.

**Comment by martey** [comment]
I think that this is covered by #1158.

**Comment by gasman** [comment]
Thanks @martey - yep, agreed.
