### ISSUE TITLE
Repeated labels in image gallery and image choosers for screen reader users

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#5350]
### Issue Summary

In the image gallery and image choosers, users are given a list/table of images to choose from, each of which has an `img` and a label within a link to the image editing UI. The `img` uses the image’s title as an `alt` text, and the title is displayed right underneath as well – so screen readers announce the same text twice in a row. It would be better if the title was only announced once.

### Steps to Reproduce

1. With a screen reader, go to the Image gallery (choosers are harder to navigate, see #5338)
2. Tab through the images listed to hear the titles being announced twice.

---

The corresponding Axe issue is `image-redundant-alt`:

> Text of buttons and links should not be repeated in the image alternative (https://dequeuniversity.com/rules/axe/3.2/image-redundant-alt?application=axeAPI)

The solution for this is to switch `img` tags to have an empty alt: `alt=""`.

**Comment by helenb** [comment]
PR: https://github.com/wagtail/wagtail/pull/5355

**Comment by thibaudcolas** [comment]
Fixed in #5355.
