### ISSUE TITLE
Version number label obscures settings menu item

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#5358]
On complex sites, the settings menu can exceed the window height, causing it to receive a scrollbar. When this happens, the version number label scrolls along with the menu items, causing it to permanently obscure one of those items:

![settings_menu_obscuring](https://user-images.githubusercontent.com/85097/59020640-52ce9480-8842-11e9-8264-56bcf63e5821.gif)

It would be better for the version number label to stay fixed on scroll, and for the menu to be given enough bottom padding to ensure that the last item can be scrolled above that label.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.7
* Django version: 2.1.9
* Wagtail version: master
* Browser version: Chrome/74.0.3729.169 https://whatsmybrowser.org/b/ZM555Y9

**Comment by lb-** [comment]
Fixed in a459e91692659aba04e662978857d14061aecaee via #5606

**Comment by abeyerpath** [comment]
The PR that fixed this was reverted, so this issue should probably be reopened, no?

**Comment by gasman** [comment]
@abeyerpath Good point, yep!
