### ISSUE TITLE
Giving non-admins 'create user' permission within wagtailusers, without giving them the ability to create admin users

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#537]
Ref: https://groups.google.com/d/msg/wagtail/t_nnwIO8pSc/T70-N2OMvQUJ

It's currently possible to assign "create/edit/delete user" permissions to non-admin users, to give them access to the user management area. However, there's nothing to stop them from escalating their own permissions by creating their own admin accounts.

Proposed solution: On the 'edit user' form, only provide the 'Administrator' checkbox if the user accessing the form is an administrator themselves. More generally: the list of groups that are shown to a non-admin should only include groups that they are a member of themselves - i.e. there is no way to create a user with more privileges than yourself.

**Comment by pvdvreede** [comment]
I have created a PR for only letting superusers created other superusers (#1149).

The validation is on the Forms and I have injected the `request.user` object into the form. This should make it easy to also filter the groups based on the logged in user. 

For my use case I would like to have non-admin users be able to create other users of the same group as them, but also create users of a lesser group. Just wondering if this would be possible to be able to determine in the code? Seems like it might be hard to do as there is no ordering or hierarchy of groups...

**Comment by gasman** [comment]
Defining an ordering / hierarchy of groups does indeed seem like quite a 'heavyweight' solution to this problem. I guess you could do it by saying "user X can add users to group Y if the permissions of group Y are a subset of user X's own permissions".

For most cases, though, I think it would be sufficient to say that user X must be a member of the relevant groups. For example: if you want user X to be able to create users of type 'editor' and 'moderator', then you should make user X a member of both groups, not just 'moderators'.

**Comment by pvdvreede** [comment]
Thanks @gasman, you make a good point - I can just add that user to both groups, and then the logic can just be a user can only create other users with the groups they are in.

**Comment by hnykda** [comment]
Is there any progress on this? It seems quite silent. I would be happy to work on this if I knew the status.

**Comment by gasman** [comment]
Recent discussion among the core team has raised the point that even with this change in place, a non-superuser with edit permission can still escalate their privileges by changing the password or email address of an existing user and taking over their account.

This would suggest that the user admin views inherently _can't_ be locked down for non-superusers, without removing functionality that people would legitimately want. (I can easily imagine resetting passwords being the kind of task that gets assigned to a "junior admin", non-superuser role.)

Does that mean we shouldn't allow non-superusers into the user admin area at all (since it effectively gives them the power to become a superuser)? Not necessarily - if someone is spending a lot of their time doing user management, it probably makes sense for them to do so through a non-superuser account, as a guard against screwing things up (i.e. for the same reason that UNIX users shouldn't routinely log in as root).

However, it does mean that ultimately that person needs to be a trusted non-evil user. (We will add messaging to the documentation and permissions UI to make this fact clear - I'll open a ticket for this shortly.) With that understanding in place, I'd argue that the risk profile has changed to the point that this issue is no longer valid: if a non-superuser with user-editing powers is NOT an untrusted user, but more like a superuser-level account with voluntarily reduced permissions, then there's no justification for locking down checkboxes here.

**Comment by Luk5553** [comment]
Solution: https://github.com/wagtail/wagtail/pull/11469
