### ISSUE TITLE
FilterQuerySet in ModelAdmin Not Working as expected.

### ISSUE THREAD

**Issue by JaredOzzy** [wagtail/wagtail#5371]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When you try to use get_queryset method on a model in a Wagtail ModelAdmin Class that uses the same Model as another ModelAdmin Class you don't get the expected result, instead you will get the result from the first called get_queryset

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py as follows
```
LANGUAGES = (
    ('en', 'English'),
    ('fr', 'French'),
)

class Resource(models.Model):
    language = models.CharField(max_length=255, choices=LANGUAGES)
    title = models.CharField(blank=True, max_length=255)

    panels = [
        FieldPanel('language'),
        FieldPanel('title'),
    ]
```
3. Create a file called wagtailadminhooks.py and edit it as follows
```
class ResourceAdmin(ModelAdmin):
    model = models.Resource
    menu_label = 'Resources'
    menu_icon = 'snippet'  # change as required
    list_display = (
        'resource_type',
        'title',
    )
    list_filter = (
        'resource_type',
    )
    search_fields = (
        'title',
        'business_email',
    )

class EnResourceAdmin(ResourceAdmin):
    menu_label = 'English Resources'

    def get_queryset(self, request):

        qs = super().get_queryset(request)
        return qs.filter(language='en')


class FrResourceAdmin(ResourceAdmin):
    menu_label = 'French Resources'

    def get_queryset(self, request):
        qs = super().get_queryset(request)

        return qs.filter(language='fr')


class ResourceAdminGroup(ModelAdminGroup):
    menu_label = 'Resources'
    menu_icon = 'snippet'  # change as required
    menu_order = 1000  # (000 being 1st, 100 2nd)
    items = (
        EnResourceAdmin,
        FrResourceAdmin,
    )

modeladmin_register(ResourceAdminGroup)
```

Expected Outcome:
Each Group should only display items filtered in a queryset. 

Current Outcome:
This way it will always only display what is queried first so the EN queryset is the only filter that will be applied.

Extra Info:
I created a stackoverflow question for this about 2 weeks ago and didn't receive any answers [here](https://stackoverflow.com/questions/56376529/filter-queryset-in-wagtail-modeladmin-not-working), i started looking deeper and found that according to the Django docs on default_manager.([here](https://docs.djangoproject.com/en/2.2/topics/db/managers/#django.db.models.Model._default_manager))

> If you use custom Manager objects, take note that the first Manager Django encounters (in the order in which they’re defined in the model) has a special status. Django interprets the first Manager defined in a class as the “default” Manager, and several parts of Django (including dumpdata) will use that Manager exclusively for that model. As a result, it’s a good idea to be careful in your choice of default manager in order to avoid a situation where overriding get_queryset() results in an inability to retrieve objects you’d like to work with.
> 
> You can specify a custom default manager using Meta.default_manager_name.
> 
> If you’re writing some code that must handle an unknown model, for example, in a third-party app that implements a generic view, use this manager (or _base_manager) rather than assuming the model has an objects manager.

Note the last part of the first paragraph. I think that is exactly what is happening here.

**Comment by ababic** [comment]
Hi @JaredOzzy. I'm afraid registering more than one `ModelAdmin` class for the same model will not work the way you are expecting. This is because the URLs generated for each `ModelAdmin` instance are derived from the mode. Because `EnResourceAdmin` and `FrResourceAdmin` use the same model, they want to occupy the same urls by default, which obviously cannot work (it sounds like the `EnResourceAdmin` is winning the battle).

You may be able to make this work by [implementing a custom `URLHelper` class](http://docs.wagtail.io/en/v2.0/reference/contrib/modeladmin/primer.html#modeladmin-url-helper-class), and applying to both classes. If the urls contained the language code, then you should be able to access the URLs for each `ModelAdmin` class separately.

**Comment by JaredOzzy** [comment]
Hi @ababic, Thanks for the reply!

i did implement the second suggestion in the end, i might still look at implementing the custom URLHelper class just so i can get my hands dirty with it and play around there a little.
:D
