### ISSUE TITLE
Wagtail RichTextField Instagram post can't embed problem

### ISSUE THREAD

**Issue by ozanteoman** [wagtail/wagtail#5381]
Hi everyone .
I have problem that when i copy the instagram post link and paste richtextField, wagtail say that **"Cannot find an embed for this URL."**
I upgraded the version 2.5.1 so i have latest version
I copied link is https://www.instagram.com/p/ByfBPgAAgv5/

**Comment by gasman** [comment]
Hi @ozanteoman,
The above URL works fine for me when I try embedding it (testing on an instance of [bakerydemo](https://github.com/wagtail/bakerydemo/)). Do you have a custom `WAGTAILEMBEDS_FINDERS` setting specified in your settings file? (http://docs.wagtail.io/en/v2.5.1/advanced_topics/embeds.html#configuring-embed-finders)

**Comment by ozanteoman** [comment]
> Hi @ozanteoman,
> The above URL works fine for me when I try embedding it (testing on an instance of [bakerydemo](https://github.com/wagtail/bakerydemo/)). Do you have a custom `WAGTAILEMBEDS_FINDERS` setting specified in your settings file? (http://docs.wagtail.io/en/v2.5.1/advanced_topics/embeds.html#configuring-embed-finders)
Hi @gasman ,

after commenting above i put these

```
from wagtail.embeds.oembed_providers import instagram

WAGTAILEMBEDS_FINDERS = [
    {
        'class': 'wagtail.embeds.finders.oembed',
        'providers': [instagram],
    }
]
```
but i take same validation error

**Comment by devski-dev** [comment]
Hey @gasman, 

trying Wagtail the very first time these days, I have a pretty fresh installation with no custom settings yet. I just tweaked the home template like in the docs tutorial and added the RichTextField to the body. To test how it renders stuff I just added random content.

I do have the same issue: 
Embedding _youtube_ worked like a charm (except the extra [padding-bottom](https://github.com/wagtail/wagtail/issues/1495)). But trying to embed an _**[Instagram](https://www.instagram.com/p/B0RRnXDoOpq/)**_ or **_[Soundcloud](https://soundcloud.com/tycho/thievery-corporation-fragments)_** link causes an error (see Screenshot), saying "Für diese URL wurde kein Element gefunden." (--> It did not find a proper element for the given URL)):

<img width="967" alt="richtextfieldEmbedInstagram_noEmbedElmFound" src="https://user-images.githubusercontent.com/52469379/62011634-169d1d80-b17b-11e9-8bf3-3fcfc67bc41f.png">

My system:
- OSX 10.12
- Python 3.7.3
- Wagtail v2.5.1
- (Admin Interface in latest Chrome)

According to your provided link to the docs, which says ".. list of providers which are all enabled by default" and provides a list to that list that includes patterns for Soundcloud and Instagrams it should work, I guess?! Any thoughts what we might have missed? 

Thanks and cheers

**Comment by devski-dev** [comment]
I just wanted to add, that embeds still do not work for me. Updated Wagtail to v2.6 and tried embedding using a `URLField` in _models.py_ and in the template `load { % wagtailembeds_tags %} `and using the `{ % embed %}` tag like[ from the docs](http://docs.wagtail.io/en/v2.6/advanced_topics/embeds.html#embed-tag)
Result is the same: Works fine with YouTube links, but fails to render "silently" for every other provider. I also did a [stackoverflow post](https://stackoverflow.com/questions/57327943/wagtail-cms-embeds-cannot-be-found-for-all-sources-except-youtube) on that bcs. I'm not sure if I'm the problem here or if the embeds (or docs?) really are :-)

**Comment by gasman** [comment]
Hi @ozanteoman and @devski-dev - sorry for the delay in getting back to you. I've just retried this on a clean installation as per [your stackoverflow post](https://stackoverflow.com/questions/57327943/wagtail-cms-embeds-cannot-be-found-for-all-sources-except-youtube) (on OS X 10.14.6, Python 3.7.2, Django 2.2.3 and Wagtail 2.5.1 and 2.6) and embeds are working fine here.

Please could you try the following steps and let me know the results?

1. At the `./manage.py shell` prompt, run the following:

       from wagtail.embeds.embeds import get_embed
       get_embed('https://www.instagram.com/p/ByfBPgAAgv5/').html

   This should give you an HTML fragment.

2. Again at the `./manage.py shell` prompt, run the following:

       from wagtail.embeds.finders.oembed import OEmbedFinder
       finder = OEmbedFinder(providers=[{
           "endpoint": "http://api.instagram.com/oembed",
           "urls": [
               r'^http://instagr\.am/p/.+$',
               r'^http[s]?://(?:www\.)?instagram\.com/p/.+$',
           ],
       }])
       finder.accept('https://www.instagram.com/p/ByfBPgAAgv5/')
       finder.find_embed('https://www.instagram.com/p/ByfBPgAAgv5/')

   The last two lines should return `True` and a dict of embed data.

3. Visit https://api.instagram.com/oembed?url=https://www.instagram.com/p/ByfBPgAAgv5/ in your browser - this should return a dict of embed data.

**Comment by devski-dev** [comment]
Hi @gasman, 

thanks for looking into that (and no worries, I'm sure you have a lot on your plate).

For steps 1. and 2. I pasted the output in 2 text documents, not sure if this is a proper format for github, if you need me to paste it somewhere else let me know :-) 

Step 1 gave a lot of (mostly SSL) errors? And for step 2 I got a _True_ for the first line, but again a lot of SSL stuff for the second line. Step 3: Yep, visiting that link in Chrome returns a dict with the expected data.

[wagtailEmbedsShellOutput-1.txt](https://github.com/wagtail/wagtail/files/3611697/wagtailEmbedsShellOutput-1.txt)
[wagtailEmbedsShellOutput-2.txt](https://github.com/wagtail/wagtail/files/3611698/wagtailEmbedsShellOutput-2.txt)

I hope that helps, let me know if I should try additional things and thanks again for your time.

**Comment by devski-dev** [comment]
Hi @gasman,

thanks for looking into that (and no worries, I'm sure you have a lot on your plate).

For steps 1. and 2. I pasted the output in 2 .txt documents, not sure if this is a proper format for github, if you need me to paste it somewhere else let me know :-)

Step 1 gave a lot of (SSL) errors, not an HTML fragment. And for step 2 I got a True for the first line, but again a lot of SSL stuff for the second line. Step 3: Yep, visiting that link in Chrome returns a dict with the expected data.

[wagtailEmbedsShellOutput-1.txt](https://github.com/wagtail/wagtail/files/3611820/wagtailEmbedsShellOutput-1.txt)
[wagtailEmbedsShellOutput-2.txt](https://github.com/wagtail/wagtail/files/3611821/wagtailEmbedsShellOutput-2.txt)

I hope that helps, let me know if I should try additional things and thanks again for your time.

**Comment by gasman** [comment]
@devski-dev Thanks, that makes sense now! Looks like you need to apply this fix: https://www.dev2qa.com/how-to-fix-python-error-certificate-verify-failed-unable-to-get-local-issuer-certificate-in-mac-os/

**Comment by devski-dev** [comment]
@gasman yes, a simple double click, problem solved. Thank you very much. Ouch, oh no, so this wasn't even Wagtail related. Sorry .. I am a Python beginner, I should invest more time in proper debugging now I guess. :-)
