### ISSUE TITLE
Provide the option to update snapshots with jest in the tooling

### ISSUE THREAD

**Issue by helenb** [wagtail/wagtail#5388]
If you make a change to some wording to elements that use jest tests, then the Circle CI tests will fail when running `expect(value).toMatchSnapshot()`

We should update the `wagtail/package.json` file to provide an npm task to run `jest --updateSnapshot` in the tooling. Ideally the jest commands in the tooling should be documented.

**Comment by thibaudcolas** [comment]
The option is there already, it’s part of Jest’s watch mode (command: `npm run test:unit:watch`). Running this starts Jest in watch mode, through which you can update snapshots when there are test failures (the UI explains how – I think it’s by pressing the `u` key).

So what’s missing is some documentation on how to run JS tests, and updating snapshots.

**Comment by thibaudcolas** [comment]
Thanks to #6471 we’re now using Jest 26, where the command to update snapshots is much more obvious, so I don’t think this is relevant anymore.

```
 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `npm run test:unit -- -u` to update them.
```
