### ISSUE TITLE
Tab text content is being cut off on smaller screens

### ISSUE THREAD

**Issue by kevinhowbrook** [wagtail/wagtail#5399]
### Issue Summary

When viewing the create page form on smaller screens, the panel tabs at the top trim text down due to a set width in the CSS.

![tab eg](https://i.imgur.com/vcBAPVd.png)

### Steps to Reproduce
1. After creating a new site, sign in and add a child page to the home page.
2. Reduce the browser size down to small/mobile screen size when creating the page.
3. Observe the tabs cutting text due to set widths.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7.1
* Django version: Django>=2.1,<2.2,
* Wagtail version: 2.6
* Browser version: Chrome 70. Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

**Comment by kevinhowbrook** [comment]
PR https://github.com/wagtail/wagtail/pull/5392

**Comment by loicteixeira** [comment]
Closing as corresponding PR has been merged.
