### ISSUE TITLE
Implement a skip-link in the CMS admin so users can skip repetitive content

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#5406]
We need to implement a [skip link](https://en.wikipedia.org/wiki/Skip_link) in the CMS admin, so keyboard users can skip navigation menus and go straight to the main content of the page. This is useful for keyboard users who do not rely on a screen reader – screen reader users can already move around with headings and landmarks.

Here is a good example of a skip link:

![skip-link](https://user-images.githubusercontent.com/877585/59933904-3cc7f300-9442-11e9-8c14-bb4c37bb3698.gif)

I think we will want Wagtail’s skip link to have the following characteristics:

- Only becomes visible when the user starts tabbing through the page (`visuallyhidden`, and focusable)
- Should take the user to the `main` landmark
- Should not add a fragment identifier / anchor in the URL bar
- Basically state of the art

**Comment by tomdyson** [comment]
Assigning to @martincoote

**Comment by martincoote** [comment]
Here's my first stab at solving this but it has some issues.
https://github.com/martincoote/wagtail/pull/1/files

Notes: 
- This is implementing a basic anchor link solution. 
- The default tabbing behaviour seems to be being eroded by defaults in Safari (MacOS Version 13.0.4) and Firefox (MacOS Version 72.0.1) Both override a tab press to focus the search field on the page and toggle through various browser features. Safari provides the option to override this in settings 
<img width="886" alt="Screenshot 2020-01-23 at 13 02 51" src="https://user-images.githubusercontent.com/46852326/72986726-c37ded80-3de0-11ea-9fef-4d30a0bc73a1.png">
But i've had no such luck finding an override for firefox. Not super keen on this trend as a rule and think there's some discussion needed about how to handle this.
- IE11 focuses the skiplink and navigates to `#main` on interaction, but with subsequent tab presses it seems to have not moved focus across to the main element.

I'm loath the use JS for this but not sure what the solution is. Could use opinions.
