### ISSUE TITLE
Transitive search from Page model?

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#5413]
Related to issue https://github.com/wagtail/wagtail/issues/237

I have several models that I would like to search via a "site-wide" search page. When building the search page, I have used the `Page` model as the basis for searching. However, this doesn't return results that have matching data in fields other than the `Page` search fields.

How can I tell Wagtail to perform a "transitive" search, to return results from inherited models that define additional search fields?

## Steps to Reproduce

1. create a model inheriting from the `Page` model
2. add a field and search index for the field
3. add content of both `Page` type and the inherited model
4. attempt to search with a term found in the inherited model specific field (e.g. body)

**Comment by gasman** [comment]
Hi @brylie,
As per the note at http://docs.wagtail.io/en/v2.5.1/topics/search/indexing.html#indexing-extra-fields, searching extra fields isn't supported on the default database search backend - you need to use either the [Elasticsearch or Postgresql backend](http://docs.wagtail.io/en/v2.5.1/topics/search/backends.html), or the add-on [wagtail-whoosh](https://github.com/wagtail/wagtail-whoosh/) package.

If you _are_ using one of these backends and believe this might be a Wagtail bug, please provide full details of how to reproduce it on a fresh Wagtail installation (including all configuration steps and relevant code) and we'll be happy to investigate further. Alternatively, drop by one of our [support channels](https://docs.wagtail.io/en/stable/support.html).

**Comment by brylie** [comment]
Since I'm not sure whether this would be a bug or support request, I've opened a StackOverflow question:

https://stackoverflow.com/questions/75266918/wagtail-page-model-transitive-search-on-custom-fields
