### ISSUE TITLE
revisions_view view should check individual page permission

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#5426]
The `wagtail.admin.views.pages.revisions_view` view (which displays a preview of a page at a given revision number, as linked from the page revision listing) does not apply any permission checks other than `user_has_any_page_permission` (which only checks that they have add/edit/publish/lock permission _somewhere_ in the page tree):

https://github.com/wagtail/wagtail/blob/268df8ceeb7ddc7d4e0864b03670052f4338400f/wagtail/admin/views/pages.py#L1177-L1183

This means that if a Wagtail editor is able to guess a page ID and corresponding revision ID, they would potentially be able to view private pages that they would otherwise have no access to.

The `view_draft` view explicitly checks for edit or publish permission on the requested page, and it would make logical sense to do the same here.

https://github.com/wagtail/wagtail/blob/268df8ceeb7ddc7d4e0864b03670052f4338400f/wagtail/admin/views/pages.py#L586-L588

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

**Comment by BramManuel** [comment]
I will work on this one tomorrow, my first wagtail issue!

**Comment by chosak** [comment]
I've opened #5490 to address this issue.

**Comment by gasman** [comment]
Fixed in #5490
