### ISSUE TITLE
Long file titles appear broken on multi image upload success form

### ISSUE THREAD

**Issue by kevinhowbrook** [wagtail/wagtail#5430]
### Issue Summary

When uploading an image is complete, the left side of the rendered form features the image and the file title. The title doesn't have a word break set in the css, meaning filenames_with_underscores_that_are_long will show as one long line:

![bug eg](https://i.imgur.com/so5yexp.png)

What I would expect to see is:

![fix eg](https://i.imgur.com/qxDiC93.png)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Go to image > add
3. Upload an image with a long filename with no spaces
4. Observe error shown in the screenshot above, the long title appears unbroken and behind the right column fields.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details
* Python version: 3.5.2
* Django version: 2.1.8
* Wagtail version: 2.7.a0
* Browser version: Chrome 75

**Comment by gasman** [comment]
Fixed in #5431
