### ISSUE TITLE
Save Draft page action is not overridable

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#5438]
Using the [`construct_page_action_menu`](http://docs.wagtail.io/en/v2.5.1/reference/hooks.html#construct-page-action-menu) hook, we can override the actions that appear in the drop-up box at the bottom of the page editor. However, this [doesn't seem to include](https://github.com/wagtail/wagtail/blob/a2ba2a7a8af9268f2efd0767fe055033c9e2c14a/wagtail/admin/action_menu.py#L123-L140) the "Save Draft" action that appears in the default position.

I think it would be nice if "Save draft" was also configurable using this hook and it was possible to choose a different action as the default one.

## Implementation

We could add a `default` flag to the `ActionMenuItem` class so you could specify which is the default?

For example, to make publish the default action:

```python
@hooks.register('construct_page_action_menu')
def make_publish_default_action(menu_items, request, context):
    menu_items[:] = [
            UnpublishMenuItem(order=10),
            DeleteMenuItem(order=20),
            SubmitForModerationMenuItem(order=30),
            SaveDraftMenuItem(order=40),
            PublishMenuItem(default=True),
    ]
```

If more than one item has `default=True` an error would be raised. If no items have `default=True` then we should automatically add a `SaveDraftMenuItem` as this is what existing implementations would expect.

Alternatively, we could pick which ever item is first (or last) by the `order` field and treat that as the default action.

**Comment by rjpruitt16** [comment]
I will give it a try.

**Comment by kaedroho** [comment]
Thanks @rjpruitt16!

**Comment by rjpruitt16** [comment]
I finished the feature. I am adding test and updating documentation. Should submit pull request by friday.

**Comment by rjpruitt16** [comment]
https://github.com/wagtail/wagtail/pull/5500
