### ISSUE TITLE
Feature request: Documentation API and streamfields

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#5443]
When using the API wagtail headless the documentation is a bid sparse.

For example using streamfield in combination with Snippetchooserblock and image.

I solved it now something like this:

```py
class Someblock(blocks.StructBlock):
    snippet = SnippetChooserBlog('snippet.SomeModel)
    image = ImageChooserBlock()
    content = RichTextBlock()

    def get_api_representation(self, value, context=None):
       img = ImageRenditionField('width-200').to_representation(value['image'])
       return {
          'somefield': value['snippet'].somefield,
          'someotherfield': value['snippet'].some_other_field,
          'image': img,
          'alt': value['image'].title,
          'content': value['content'].source
         }
```

I can't verify in docs if this is correct method or if I'm wrong. So it would be great if a kind of example can be added to the api docs of wagfield.

**Comment by onno-timmerman** [comment]
I added the documentation and did a pull request. I hope I done this correctly. Let me know. I never did write docs

**Comment by loicteixeira** [comment]
FWIW, corresponding PR is #5466

**Comment by thibaudcolas** [comment]
I see our documentation currently covers `ImageRenditionField`, so the only missing piece is `get_api_representation`, which is already covered in #3454. I’ll close this issue in favour of that other one.
