### ISSUE TITLE
Dockerfile exits in with non-zero code 1

### ISSUE THREAD

**Issue by rjpruitt16** [wagtail/wagtail#5444]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue.

Running the base dockerfile from `Wagtail start appname` will error out.

### Steps to Reproduce

install wagtail 
wagtail start appname
docker build .

The error message.

`The command '/bin/sh -c pip install -r /code/requirements.txt' returned a non-zero code: 1
`

**Comment by johnraz** [comment]
Hello @rjpruitt16, I'm afraid the error log is a bit short to be able to help, could you provide the full error log instead?

From what you provided, it seems that something bad occurred when trying to install the Python dependencies but with just that one line of log it's pretty much impossible to tell what happened.

Also providing details about your environment (OS, Docker version, ...) would help as well.

Thanks 😎

**Comment by rjpruitt16** [comment]
Hope this helps

Mac Os
Docker version 18.09.2, build 6247962

```
Sending build context to Docker daemon  569.3kB
Step 1/16 : FROM python:3.7
 ---> 42d620af35be
Step 2/16 : LABEL maintainer="hello@wagtail.io"
 ---> Using cache
 ---> 4087c9a99063
Step 3/16 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> efc3f4988fba
Step 4/16 : ENV DJANGO_ENV dev
 ---> Using cache
 ---> f2396a3cd7ea
Step 5/16 : COPY ./requirements.txt /code/requirements.txt
 ---> Using cache
 ---> fc3fbed3b6c7
Step 6/16 : RUN pip install --upgrade pip
 ---> Using cache
 ---> c4995edfefa9
Step 7/16 : RUN pip install -r /code/requirements.txt
 ---> Running in 062c4a2c3953
Collecting Django<2.3,>=2.2 (from -r /code/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/39/b0/2138c31bf13e17afc32277239da53e9dfcce27bac8cb68cf1c0123f1fdf5/Django-2.2.3-py3-none-any.whl (7.5MB)
Collecting wagtail==2.7a0 (from -r /code/requirements.txt (line 2))
  ERROR: Could not find a version that satisfies the requirement wagtail==2.7a0 (from -r /code/requirements.txt (line 2)) (from versions: 0.1, 0.2, 0.3, 0.3.1, 0.4, 0.4.1, 0.5, 0.6, 0.7, 0.8, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.8.10, 1.0b1, 1.0b2, 1.0rc1, 1.0rc2, 1.0, 1.1rc1, 1.1, 1.2rc1, 1.2, 1.3rc1, 1.3, 1.3.1, 1.4rc1, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.5rc1, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.6rc1, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.7rc1, 1.7, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.9rc1, 1.9, 1.9.1, 1.10rc1, 1.10, 1.10.1, 1.11rc1, 1.11, 1.11.1, 1.12rc1, 1.12, 1.12.1, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.13rc1, 1.13, 1.13.1, 1.13.2, 1.13.3, 1.13.4, 2.0b1, 2.0rc1, 2.0, 2.0.1, 2.0.2, 2.1rc1, 2.1rc2, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.2rc1, 2.2rc2, 2.2, 2.2.1, 2.2.2, 2.3rc1, 2.3rc2, 2.3, 2.4rc1, 2.4, 2.5rc1, 2.5, 2.5.1, 2.6rc1)
ERROR: No matching distribution found for wagtail==2.7a0 (from -r /code/requirements.txt (line 2))
```

**Comment by tomdyson** [comment]
Thanks for the report, @rjpruitt16. This is happening because the version of Wagtail which is referenced in the project template for the current master branch (`wagtail==2.7a0') doesn't exist yet:

https://github.com/wagtail/wagtail/blob/master/wagtail/project_template/requirements.txt#L2

The most recent version on PyPI is 2.6rc1. If you change your `requirements.txt` to `wagtail==2.6rc1`, the Docker build should work. 

@gasman was this deliberate? Shouldn't `master` reference the latest version on PyPI?

**Comment by gasman** [comment]
@tomdyson Yes, this is deliberate - if you've installed Wagtail from git master and run `wagtail start`, you wouldn't want `pip install -r requirements.txt` to downgrade you to the last release version. This does mean that if you launch the created site that isn't the one where you installed Wagtail master - such as a Docker or Vagrant instance - then it's up to you to ensure that the relevant version of Wagtail is available inside that environment.
