### ISSUE TITLE
Feature request: Allow "With" Syntax for Jinja2 include_block tag

### ISSUE THREAD

**Issue by bmoe872** [wagtail/wagtail#5448]
### Issue Summary

When attempting to use Jinja2's `{% with %}` syntax around a block, the variable set in the with is not carried into the block. Even though within the docs it states that the intention behind `include_block` was to be as close to jinja2's include (which can be used with the `with`) 

### Steps to Reproduce
Using Jinja2 template tags
1. Create a model with a Streamfield
2. on the template side of that you could do something like:

```
{% for block in page.body %}
        {% with index = loop.index %}
            {% include_block block %}
        {% endwith %}
{% endfor %}
```

Then within the block you should be able to reference the assigned variable `index`, however currently you can not.

While not well documented on the jinja2 side this does work:
```
{% for block in page.body %}
        {% with index = loop.index %}
            {% include 'path/to/some.html' %}
        {% endwith %}
{% endfor %}
```
Where some.html in the above example can reference `index`

### Technical details

* Python version: 3.6.7
* Django version: 2.1.9
* Wagtail version: 2.5.1
* Browser version: Chrome
* Jinja2 version: 2.10

#### Supporting documentation:

`with` syntax: http://jinja.pocoo.org/docs/2.10/templates/#with-statement
wagtail include_block docs: http://docs.wagtail.io/en/v2.5.1/advanced_topics/jinja2.html#include-block

**Comment by bmoe872** [comment]
This actually might be a duplicate of this one:
https://github.com/wagtail/wagtail/issues/5279

**Comment by gasman** [comment]
Looks like it, yep - thanks for the report.

**Comment by easherma-truth** [comment]
I think this is still an issue in some cases
