### ISSUE TITLE
Wagtail translation: duplicating tree not compatible with static text translation?

### ISSUE THREAD

**Issue by niccolomineo** [wagtail/wagtail#5449]
Hi, I am trying to have Wagtail allow to specify a custom page slug for each language.

[Here](http://docs.wagtail.io/en/v2.5.1/advanced_topics/i18n/duplicate_tree.html) it is suggested to duplicate the tree, but this approach does not seem to work properly with i18n URL patterns - which is the only way I know to trigger the right translations for static text in templates.

The problem with i18n patterns is the language prefix appears in the URL together with the page slug, therefore resulting in a duplication of locales in the url (in the form of `mysite.com/<LOCALE>/<LANGUAGE-PAGE>/mypage` - ex. `mysite.com/en/en/mypage`).

This can be worked around for the default language by setting `prefix_default_language = False` in `urls.py`, but for other languages you get the url as per above.

Am I missing/misunderstanding anything?
How can I work around this limitation without resorting to rewriting the URLs in the `.htaccess`?

**Comment by niccolomineo** [comment]
We found the issue to be in `TranslatablePageMixin`'s `get_language()` needing the translation to be activated:

```
    def get_language(self):
        """
        This returns the language code for this page.
        """
        language_homepage = self.get_ancestors(inclusive=True).get(depth=3)
        
        translation.activate(language=language_homepage.slug)

        return language_homepage.slug
```

**Comment by gasman** [comment]
Closing as the documentation page in question was removed some time ago, and 2.11 is introducing new translation infrastructure with full support for Django's i18n_patterns.
