### ISSUE TITLE
Feature request docs: snippets with clusterable model

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#5451]
I think this is missing in the docs about clusterablemodels. A small example if you want to group items a your snippets. Example you want your member of band group so you can reuse this on other pages.

```
class BandMember(Orderable):
     band = ParentalKey('Band', related_name='members', on_delete=models.CASCADE)
     name = models.CharField(max_length=255)

@register_snippet
class Band(ClusterableModel):
     name = models.CharField(max_length=255)

     panels = [
         FieldPanel('name'),
         InlinePanel('members')
      ]
```

**Comment by zerolab** [comment]
@onno-timmerman why not open a pull request with the missing docs?

**Comment by onno-timmerman** [comment]
Ok I'll try that, in a couple of days. Somebody will have to inspect and correct my dyslectic content. :)

**Comment by onno-timmerman** [comment]
Ok I added the documentation. I hope I done this correctly. Let me know. I never did write docs
