### ISSUE TITLE
Not enough contrast for StreamField group labels on dark background

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#5455]
### Issue Summary

In the current StreamField implementation, StreamField blocks can be groupped in the "Add block" menu, with a label for each block. That label is very hard to see, and very far from WCAG2.1 color compliance:

![image](https://user-images.githubusercontent.com/877585/61903601-d7f53200-aef2-11e9-8e1d-4607f390847b.png)

The label also doesn’t seem to be well aligned with the items in the group 😐

Kudos to @nmorduch for spotting this 😉and suggestion to line up the label with the leftmost block type button.

### Steps to Reproduce

https://docs.wagtail.io/en/stable/topics/streamfield.html#basic-block-types

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Wagtail version: 2.5.1 or 2.6.0rc1

---

I’m not sure whether this will still be relevant after #4942, but still feels worth tracking / fixing in the meantime.

**Comment by cfarm** [comment]
PR https://github.com/wagtail/wagtail/pull/5462

**Comment by thibaudcolas** [comment]
Fixed 🌈
