### ISSUE TITLE
Add javascript testing instructions to docs

### ISSUE THREAD

**Issue by harrislapiroff** [wagtail/wagtail#5468]
The docs currently don't include instructions on how to run javascript tests either under the [contribution guidelines](https://docs.wagtail.io/en/v2.5.1/contributing/) or the [javascript guidelines](https://docs.wagtail.io/en/v2.5.1/contributing/javascript_guidelines.html). Should be added in one or both places.

Looks like the correct command is:

```bash
npm run test
```

but there may also be some options worth documenting.

**Comment by allcaps** [comment]
The Makefile might need updating too. 
`test` and `test-all` will not test the frontend.

**Comment by thibaudcolas** [comment]
https://docs.wagtail.io/en/latest/contributing/developing.html#unit-tests-for-javascript looking good now.
