### ISSUE TITLE
No PageChooserPanel for some related pages

### ISSUE THREAD

**Issue by supermanzer** [wagtail/wagtail#5473]
### Issue Summary

Attempting to use the PageChooserPanel on related pages on the One side of either a `models.ForeignKey` or `ParentalKey` relationship (where the actual field is declared in a separate model) causes a `FieldError` exception, despite using the specified `related_name`.  Inspection in the shell shows that the related object managers are in place and therefore the admin UI should be able to use the `manager.add()` function to assign new child/related pages.

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Use the attached `models.py` definitions
3. Run development server `python manage.py runserver`

<details><summary>models.py</summary>
<p>
# -*- coding: utf-8 -*-
"""
FAQ Page Models.

This file defines the page (and other) models we will use to compose our FAQs app.
"""

from django.db import models
from django import forms
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.fields import AutoSlugField

from modelcluster.fields import ParentalKey, ParentalManyToManyField
from modelcluster.models import ClusterableModel

from wagtail.core.models import Page, Orderable
from wagtail.core.fields import RichTextField, StreamField
from wagtail.admin.edit_handlers import (
    FieldPanel, MultiFieldPanel, InlinePanel, StreamFieldPanel, PageChooserPanel
)
from wagtail.admin.forms import WagtailAdminPageForm
from wagtail.search import index
from wagtail.snippets.models import register_snippet
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.core.forms import forms

from streams import blocks

@register_snippet
class FaqCategory(models.Model):
    name = models.CharField(max_length=60, unique=True)
    slug = models.SlugField(unique=True)

    panels = [
        FieldPanel('name'),
    ]

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

@register_snippet
class ProductType(models.Model):
    """Define a simple product type when we wish to avoid more complicated details."""
    # Choices
    PROD_CLASS = (
        ('bp', 'Bulk Product'),
        ('fp', 'Finished Product'),
    )
    name = models.CharField(
        max_length=50, null=True, blank=False,
        help_text="Enter a short name for this product type."
    )
    slug = models.SlugField(max_length=50, null=True, unique=True)
    description = models.TextField(
        null=True, blank=True,
        help_text='Add any helpful description.'
    )
    product_class = models.CharField(
        null=True, blank=False, choices=PROD_CLASS, max_length=5
    )

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}'

    panels = [
        FieldPanel('name'),
        FieldPanel('description'),
        FieldPanel('product_class')
    ]

    class Meta:
        verbose_name = 'Product Type'
        verbose_name_plural = 'Product Types'

class BulkList(Page):
    """Add a general listing page to facilitate grouping in the Admin interface."""
    max_count = 1

    template = 'faqs/bulks/bulk_list.html'
    subpage_types = ['faqs.BulkGood', ]

    class Meta:
        verbose_name = _("Bulk List")
        verbose_name_plural = "Bulk Lists"

class BulkGood(Page):
    """
    Define a model for our bulk products.
    """
    # Specifying which template will be used to render an individual BulkGood
    template = "faqs/bulks/bulk_good.html"
    # Specifying the valid parent pages for objects of this class.
    parent_page_types = ['faqs.BulkList', ]
    # FIELDS
    bulk_type = models.ForeignKey(
        "faqs.ProductType", related_name="bulks",
        help_text='Select the correct type for this bulk.',
        on_delete=models.SET_NULL, null=True,
        limit_choices_to={'product_class': 'bp'}
    )
    name = models.CharField(
        max_length=150, null=True, blank=False,
        help_text='Provide the name for this bulk product.'
    )
    info = StreamField([
        ('heading_and_content', blocks.InfoBlock())
    ], null=True, blank=False, help_text='Add information sections.')
    faqs = StreamField([
        ('bulk_faqs', blocks.FAQBlock())
    ], null=True, blank=True, help_text="Add FAQs")
    allergens = ParentalManyToManyField(
        'faqs.Allergen',
         blank=True, related_name='+'
    )
    # Admin Interface
    content_panels = [
        MultiFieldPanel([
            FieldPanel('name'),
            FieldPanel('bulk_type', ),
        ], heading='Bulk Details', classname='collapsible'),
        MultiFieldPanel([
            StreamFieldPanel('info')
        ], heading="Bulk Info", classname="collapsible full"),
        MultiFieldPanel([
            FieldPanel('allergens', widget=forms.CheckboxSelectMultiple)
        ], heading="Bulk Allergens", classname="collapsible"),
        MultiFieldPanel([
            InlinePanel('bulk_ingredients', label='Raw Materials')
        ], heading="Bulk Raw Materials", classname="collapsible"),
        MultiFieldPanel([
            PageChooserPanel('bulk_products', 'faqs.FinishedGood')  # <- THIS SHOULD WORK BUT DOES NOT
        ], heading="Bulk Finished Products"),
        MultiFieldPanel([
            StreamFieldPanel('faqs'),
        ], heading='Bulk FAQs', classname="collapsible full")

    ]
    # Search Index Fields
    search_fields = Page.search_fields + [
        index.SearchField('info'),
        index.SearchField('name'),
        index.RelatedFields('allergens', [
            index.FilterField('name')
        ]),
        index.SearchField('faqs'),
        index.RelatedFields('bulk_type', [
            index.SearchField('name'),
            index.FilterField('slug')
        ])
    ]

    # Model class options
    class Meta:
        verbose_name = 'Bulk'
        verbose_name_plural = "Bulks"

    def clean(self):
        if not self.title and self.name:
            self.title = self.name
        cleaned_data = super().clean()

        return cleaned_data

class BulkRawMaterial(models.Model):
    # Custom Many to Many class
    page = ParentalKey('faqs.BulkGood', on_delete=models.CASCADE, related_name='bulk_ingredients')
    bulk_ingredient = models.ForeignKey(
        'faqs.RawMaterial', on_delete=models.CASCADE, related_name='ingredient_bulks',
    )
    # Admin interface components
    panels = [
        PageChooserPanel('bulk_ingredient', 'faqs.RawMaterial')
    ]
    # Model class options
    class Meta:
        unique_together = ('page', 'bulk_ingredient')

class MaterialList(Page):
    """Define aggregation for Raw Materials."""
    max_count = 1
    subpage_types = [
        'faqs.RawMaterial'
    ]

    class Meta:
        verbose_name = 'Raw Material List'
        verbose_name_plural = 'Raw Material Lists'

class RawMaterial(Page):
    """Define a raw material data model."""
    # Specifying valid parent pages
    parent_page_types = ['faqs.MaterialList',]
    # Defining template used to render objects of this class
    template = 'faqs/raw_materials/raw_material.html'
    # FIELDS
    name = models.CharField(
        max_length=100, null=True, blank=False,
        help_text='The name of this raw material'
    )
    active = models.BooleanField(
        help_text='Whether this is an active ingredient in a product or not.',
        choices=(
            (True, "True"),
            (False, "False")
        ), default=False
    )
    info = StreamField([
        ('heading_and_info', blocks.InfoBlock())
    ], null=True, blank=True)
    faqs = StreamField([
        ('faqs', blocks.FAQBlock())
    ], null=True, blank=True)
    allergens = ParentalManyToManyField(
        'faqs.Allergen', blank=True, related_name='+',
        help_text='Select allergens related to this product'
    )
    # Admin Interface Components
    content_panels = [
        MultiFieldPanel([
            FieldPanel('name'),
            FieldPanel('active', widget=forms.RadioSelect),
        ], heading='details'),
        MultiFieldPanel([
            StreamFieldPanel('info', blocks.InfoBlock())
        ], heading='Raw Information', classname="collapsible full"),
        MultiFieldPanel([
            FieldPanel('allergens', widget=forms.CheckboxSelectMultiple)
        ], heading="Raw Allergens", classname="collapsible"),
        MultiFieldPanel([
            PageChooserPanel('ingredient_bulks', 'faqs.BulkGood')  # <- This should work but does not
        ], heading="Raw Material Bulks", classname="collapsible"),
        MultiFieldPanel([
            StreamFieldPanel("faqs", blocks.FAQBlock())
        ], heading="Raw Material FAQs", classname="collapsible full",)
    ]
    # Adding fields to search indices
    search_fields = Page.search_fields + [
        index.SearchField('name'),
        index.FilterField('active'),
        index.SearchField('info'),
        index.SearchField('faqs'),
        index.RelatedFields('allergens', [
            index.FilterField('name')
        ])
    ]

    # Model options
    class Meta:
        verbose_name = "Raw Material"
        verbose_name_plural = "Raw Materials"

    def clean(self):
        if not self.title and self.name:
            self.title = self.name
        cleaned_data = super().clean()

        return cleaned_data

class FinishedGoodList(Page):
    """Define aggregator for Admin interface."""
    max_count = 1  # Maximum number of pages for this class
    # Specifying valid child page classes
    subpage_types = ['faqs.FinishedGood']

    class Meta:
        verbose_name_plural ='Finished Good Lists'
        verbose_name = 'Finished Good List'

class FinishedGood(Page):
    """Define a model for finished goods."""
    # Defining valid  parent page classes
    parent_page_types = ['faqs.FinishedGoodList',]
    # Specifying template used to render objects of this class
    template = 'faqs/products/finished_good.html'
    # FIELDS
    product_type = models.ForeignKey(
        'faqs.ProductType',
        related_name='+',
        on_delete=models.SET_NULL,
        null=True, blank=False
    )
    bulk = ParentalKey(
        'faqs.BulkGood',
        related_name='bulk_products',
        null=True, blank=True,
        on_delete=models.SET_NULL,
    )
    name = models.CharField(max_length=100, null=True, blank=False)
    storage_conditions = RichTextField(
        null=True, blank=True,
        help_text="The ideal storage conditions for this product."
    )
    info = StreamField([
        ('heading_and_content', blocks.InfoBlock())
    ],
        null=True, blank=True, help_text='Add information sections.')
    allergens = ParentalManyToManyField(
        'faqs.Allergen', blank=True, related_name='+',
        help_text='Indicate any allergens present in this product.'
    )
    faqs = StreamField([
        ('bulk_faqs', blocks.FAQBlock())
    ], null=True, blank=True, help_text="Add FAQs")
    # Admin Interface components
    content_panels = [
        MultiFieldPanel([
            FieldPanel('product_type', 'faqs.ProductType'),
            PageChooserPanel('bulk', 'faqs.BulkGood'),
            FieldPanel('name'),
            FieldPanel('storage_conditions'),
        ], heading="Product Details"),
        MultiFieldPanel([
            InlinePanel('product_variants')
        ], heading='Product Variants', classname='collapsible'),
        MultiFieldPanel([
            StreamFieldPanel('info'),
        ], heading='Product Info', classname="collapsible full"),
        FieldPanel('allergens', widget=forms.CheckboxSelectMultiple),
        MultiFieldPanel([
            StreamFieldPanel('faqs')
        ], heading="Product FAQs", classname="collapsible full")
    ]
    # Adding custom fields to search indices
    search_fields = Page.search_fields + [
        index.RelatedFields('product_type',[
            index.FilterField('name')
        ]),
        index.SearchField('name'),
        index.SearchField('info'),
        index.RelatedFields('allergens',[
            index.FilterField('name')
        ]),
        index.SearchField('faqs')
    ]

    # Model options
    class Meta:
        verbose_name = "Finished Good"
        verbose_name_plural = "Finished Goods"

    def clean(self):
        if not self.title and self.name:
            self.title = self.name
        cleaned_data = super().clean()

        return cleaned_data

class ProductVariant(ClusterableModel):
    """Define SKU Specific model."""
    # Specifying valid parent page class
    # parent_page_type = ['faqs.FinishedGood',]
    # Explicitly specifying the template used to render objects of this class
    template = 'faqs/products/product_variant.html'
    # FIELDS
    name = models.CharField(
        max_length=150, null=True, blank=False,
        help_text='The specific product name.'
    )
    sku = models.CharField(
        max_length=30, null=True, blank=False,
        help_text='Enter the SKU for this product variant.'
    )
    wholesale_price = models.FloatField(
        null=True, blank=True, help_text='The wholesale price for this product.'
    )
    retail_price = models.FloatField(
        null=True, blank=True, help_text='The retail price for this product.'
    )
    web_price = models.FloatField(
        null=True, blank=True, help_text='The website price for this product.'
    )
    case_pack_count = models.IntegerField(
        null=True, blank=False,
        help_text='The number of products per case.'
    )
    case_pack_upc = models.CharField(
        max_length=120, null=True, blank=False
    )
    upc = models.CharField(
        max_length=120, null=True, blank=False
    )
    unit_dimensions = models.CharField(
        max_length=200, null=True, blank=False,

    )
    # Admin Interface Components
    panels = [
        MultiFieldPanel([
            PageChooserPanel('finished_good'),
            FieldPanel('name'),
            FieldPanel('sku')
        ], heading='Product Info', classname='collapsible'),
        MultiFieldPanel([
            FieldPanel('wholesale_price'),
            FieldPanel('retail_price'),
            FieldPanel('web_price')
        ], heading='Product Prices', classname='collapsible'),
        MultiFieldPanel([
            FieldPanel('case_pack_count'),
            FieldPanel('case_pack_upc'),
            FieldPanel('upc'),
            FieldPanel('unit_dimensions')
        ], heading='Product Dimensions', classname='collapsible'),
        MultiFieldPanel([
            InlinePanel('label_revisions', classname="full", min_num=1),
        ], heading="Label Revisions")
    ]
    # Adding fields to search indices
    search_fields = Page.search_fields + [
        index.SearchField('name'),
        index.SearchField('sku'),
    ]

    class Meta:
        verbose_name = "Product Variant"
        verbose_name_plural = "Product Variants"

class FinishedGoodProductVariants(Orderable, ProductVariant):
    finished_good = ParentalKey(
        'faqs.FinishedGood',
        on_delete=models.CASCADE,
        related_name='product_variants',
        null=True, blank=True
    )

class LabelRevision(Orderable):
    """Define a model for product label revisions."""
    # The parent page of records of this type.
    product = ParentalKey(
        'faqs.ProductVariant',
        related_name='label_revisions',
        on_delete=models.SET_NULL,
        null=True,
        blank=False
    )
    rev_number = models.CharField(
        max_length=120, null=True, blank=False,
        verbose_name='label rev'
    )
    label_image = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=False,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    label_notes = RichTextField(features='__all__')
    active = models.BooleanField(
        help_text='Indicates the current active label rev',
        default=False
    )
    # Admin Interface Components
    panels = [
        MultiFieldPanel([
            FieldPanel('rev_number'),
            ImageChooserPanel('label_image'),
            FieldPanel('label_notes'),
            FieldPanel('active')
        ], heading='Label Rev', classname='collapsbile')
    ]

    class Meta:
        verbose_name = 'Label Revision'
        verbose_name_plural = "Label Revisions"

class AllergenList(Page):
    """An aggregator of allergen pages to streamline the Admin interface."""

    # Define the max nunber of pages for this class
    max_count = 1
    # Specify the valid classes for child pages of this class.
    subpage_types = ['faqs.Allergen', ]

    # Model meta options
    class Meta:
        verbose_name = "Allergen List"
        verbose_name_plural = "Allergen Lists"

class Allergen(Page):
    """
    Define a model for our allergens
    """
    # Specifying valid parent page classes
    parent_page_types = ['faqs.AllergenList', ]
    # Identifying the template used to render objects of this class.
    template = 'faqs/allergens/allergen.html'
    # FIELDS
    name = models.CharField(
        max_length=50, null=True, blank=False,
        help_text='Provide a helpful name for this allergen.'
    )
    info = RichTextField(
        null=True,
        blank=True,
        help_text='(Optional) Provide some information about this allergen.'
    )
    faqs = StreamField([
        ("faq", blocks.FAQBlock())
    ], null=True, blank=True)
    # Admin Interface components
    content_panels = [
        FieldPanel('name'),
        FieldPanel('info'),
        StreamFieldPanel('faqs'),
    ]

    # Adding custom fields to search indices
    search_fields = Page.search_fields + [
        index.SearchField('name'),
        index.SearchField('info'),
        index.SearchField('faqs'),
    ]
    # Model meta options
    class Meta:
        verbose_name = 'Allergen'
        verbose_name_plural = "Allergens"

    def clean(self):
        if not self.title and self.name:
            self.title = self.name
        cleaned_data = super().clean()

        return cleaned_data

class StandardList(Page):
    """Define aggregator model for Nordic Standards."""
    # Define the maximum number of pages for this class
    max_count = 1
    # Define valid child page classes for this page class
    subpage_types = ['faqs.NordicStandard', ]

    # Model meta options
    class Meta:
        verbose_name = "Standard List"
        verbose_name_plural = "Standard Lists"

class NordicStandard(Page):
    """
    Define a model to capture Nordic standards (testing, manufacturing, etc.).
    """
    # Define template used to render objects of this class
    template = 'faqs/standards/nordic_standard.html'
    # Define valid parent page classes for this class
    parent_page_types = ['faqs.StandardList', ]
    # FIELDS
    name = models.CharField(
        max_length=50, null=True, blank=False,
        help_text='Provide a helpful name for this standard.'
    )
    info = RichTextField(
        null=True,
        blank=True,
        help_text='(Optional) Provide some information about this standard.'
    )
    faqs = StreamField([
        ("faq", blocks.FAQBlock())
    ], null=True, blank=True)

    content_panels = Page.content_panels + [
        MultiFieldPanel([
            FieldPanel('name'),
            FieldPanel('info'),
        ], heading="Standard Info", classname="collapsible full"),
        MultiFieldPanel([
            StreamFieldPanel('faqs'),
        ], heading="Standard FAQs", classname="collapsible full"),
    ]

    class Meta:
        verbose_name = 'Nordic Standard'
        verbose_name_plural = "Nordic Standards"
</details>

The goal is that my admin users should be able to view/assign parent pages from child pages and child pages from parent pages.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: No

### Technical details

* Python version: 3.7.3
* Django version: 2.2.3.
* Wagtail version: 2.5.1.
* Browser version:  Firefox 69.0b8.

**Comment by gasman** [comment]
Hi @supermanzer - please can you put together a minimal example demonstrating the problem? There's too much code in that models.py to know what we're supposed to be looking at.

**Comment by supermanzer** [comment]
@gasman - Sorry, I wanted to be thorough.  The basic gist of it is this:
### ParentalKey Example
```
class BulkGood(Page): <- Parent page
...
content_panels = [
...
MultiFieldPanel([
    PageChooserPanel(
      'bulk_products', 
      'faqs.FinishedGood')  # <- Results in "No Field" error
  ], heading="Finished Products from Bulk", classname="collapsible")
...

class FinishedGood(Page):
...
bulk = ParentalKey( 
             'faqs.BulkGood', 
              related_name='bulk_products', 
              on_delete=models.SET_NULL)
...
```
### Custom M2M Example
```

class BulkGood(Page):
...

class BulkRawMaterial(models.Model):  <- Used for M2M relation between Bulks and Raw Materials
  page = ParentalKey('
                   faqs.BulkGood', 
                   on_delete=models.CASCADE, 
                   related_name='bulk_ingredients')
  bulk_ingredient = models.ForeignKey(
                                  'faqs.RawMaterial, 
                                  on_delete.CASCADE, 
                                  related_name='ingredient_bulks')


class RawMaterial(Page):
...
content_panels = [
  MultiFieldPanel([
    PageChooserPanel('ingredient_bulks', 'faqs.BulkGood') <- Throws "No Field" error
  ], heading='Raw Material Bulks', classname='collapsible')
...
```

I hope that is more clear.  Please let me know if you need more details.

**Comment by gasman** [comment]
Your `PageChooserPanel` definitions are badly defined here - the field referenced by `PageChooserPanel` must be a `ForeignKey` defined on the same model as the panel.

If you want a many-to-many relationship between pages, you should define a child model using `InlinePanel` on one of your pages, and include a `ForeignKey` (and corresponding `PageChooserPanel`) within that child model.

**Comment by supermanzer** [comment]
The many-to-many arrangement makes sense to me however I must say that the `ForeignKey` behavior seems highly unsatisfactory to me.  As the Django `manage.py shell` allows access/assignment on either side of a One-to-Many relationship, I find it confusing that Wagtail would not allow for the same functionality through the Admin interface.  Additionally it is redundant since the related object on the One side of the `ForeignKey` has a property matching the `related_name` as a manager.  Thus, in my case 'BulkGood.bulk_products.all` returns a QuerySet of all related `FinishedGood` objects and calling `BulkGood.bulk_products.add(<FinishedGood>)` would allow the creation of the relationship.

Perhaps I am missing something fundamental about the approach of hierarchical tree models.  I will continue tinkering.

**Comment by supermanzer** [comment]
On further reflection, the M2M relationships are poorly constructed as well.  If I have two interrelated data models I should not need a union entity for each direction of the relationship as this breaks the fundamental utility of the relationship.  That is, if I add Model A to the related set for Model B, I should be able to interact with that relationship from either model.

**Comment by gasman** [comment]
A full two-way relationship wouldn't work with Wagtail's publishing/moderation workflow. If a change was made on one side and then saved as draft, it shouldn't take effect on the other side - but then the two sides have inconsistent data.

**Comment by supermanzer** [comment]
Thank you for clarifying.  I sincerely appreciate the thought and effort put into the Wagtail data models and the flexibility of the platform.  The publishing/moderation workflow is one of the key features that my users and I are excited for so it is good to know how this affects other relationships.
