### ISSUE TITLE
Error in Hungarian translation

### ISSUE THREAD

**Issue by roodie** [wagtail/wagtail#5477]
The new versions have an annoying issue with the Hungarian translations: some of the translation strings are using double quotes instead of single quotes, which causes an arror on the admin page thanks to a faulty JS translation string:

```javascript 
EDIT_PAGE: ""{title}" szerkesztése",
```
The translations are now fixed on Transifex. Since I messed it up, I corrected it - sorry.

**Comment by gasman** [comment]
@roodie No worries, and thanks for catching this and notifying us promptly! We should really apply JS escaping to these strings so that there are no illegal characters - I'll put together a PR to do that now.
