### ISSUE TITLE
Admin sub-menus don't open with 2.6 

### ISSUE THREAD

**Issue by TravellerSam** [wagtail/wagtail#5480]
Version 2.6 breaks the opening of the sub-menus in the admin interface (settings, custom menus) other than the main Pages tree menu, which opens and slides correctly. 
Browser console doesn't give any JavaScript errors. 

Wagtail version 2.5.2 works fine.

### Technical details

* Python version: 3.7.3
* Django version: 2.2.3
* Wagtail version: 2.6
* Browser version: Firefox 68.0.1 and Chromium 75 on Kubuntu 18.04

**Comment by gasman** [comment]
Hi @TravellerSam,
The menus definitely work here - opening the settings menu to check the version number is one of the first things we test when packaging up a new release. Have you tried clearing your browser cache?

**Comment by TravellerSam** [comment]
Hi @gasman,
The caches in all browsers are clean, any blockers turned off. I also used the Firefox Developer Edition, with same effect. I find it very strange that only the sidebar sub-menus don't show up, as the pages and user account slide out correctly. Can't access any non-Linux system at the moment.

The URL on these links gets an # on click.

**Comment by gasman** [comment]
Is this happening on a newly-created project, or one you've upgraded?

**Comment by TravellerSam** [comment]
On upgraded (two different installations).

**Comment by gasman** [comment]
Could you try with a fresh project, please? I'm wondering if there's some sort of customisation (or third-party add-on) in place which is incompatible with 2.6.

**Comment by TravellerSam** [comment]
It sure works perfectly on a fresh installation :/

**Comment by TravellerSam** [comment]
Pip packages I use in affected projects:
`django_compressor~=2.2
csscompressor~=0.9
django-newsletter==0.8b1
django-flags~=4.1
wagtail-flags~=4.0
wagtail-modeltranslation==0.10
Markdown~=3.1
`

**Comment by gasman** [comment]
Will close as unable to replicate - happy to reopen if you can track this down to a regression in Wagtail itself. If the issue is in one of the add-on packages, I'd expect that there'll be a new release with Wagtail 2.6 support in the next few days.

**Comment by TravellerSam** [comment]
Your question about clearing cache was somehow right: after running `collectstatic` on the server the interface got the fresh javascript and the menus are working again.

**Comment by olopost** [comment]
Thanks for the issues. I get the same and the collectstatic + clean browser cache solve the issue.

thanks

**Comment by TravellerSam** [comment]
@gasman Maybe it would be worthwhile to mention the need of running `collectstatic` and clearing the browser cache in the upgrade notes of the changelog.

**Comment by gasman** [comment]
@TravellerSam `collectstatic` and clearing cache are mentioned in the [general upgrading instructions](https://docs.wagtail.io/en/stable/releases/upgrading.html).

**Comment by remilapeyre** [comment]
I have this exact issue even after clearing cache and running `collectstatic`, both on Firefox and Chrome.

Here's my `requirements.txt`: 
```
django>=2.2,<2.3
dj-database-url
sentry-sdk
gunicorn
whitenoise
psycopg2
wagtail>=2.6.1,<2.7
django-storages
boto3
pyyaml
```

An error is thrown in the JavaScript : `TypeError: "i.e.EDIT_PAGE is undefined"`.
