### ISSUE TITLE
Media not loading

### ISSUE THREAD

**Issue by JettChenT** [wagtail/wagtail#5481]
I deployed a wagtail site on Heroku, and the pictures I uploaded always disappear after several hours, but the blog's text part is still working.

**Comment by JettChenT** [comment]
the site is [jettchen.herokuapp.com](jettchen.herokuapp.com).

**Comment by luizboaretto** [comment]
Please read: https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted

**Comment by allcaps** [comment]
You might look into https://djangopackages.org/grids/g/storage-backends/

Wagtail is a Django app, and storages are a Django topic. Please consult the Heroku docs. You might need to choose some other Django file storage. https://djangopackages.org/grids/g/storage-backends/

I'm closing this issue.
