### ISSUE TITLE
Add SECURITY.md to the repo

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#5495]
We already mention what to do with security issues in the project's readme, but we should probably consider adding `SECURITY.md` to show guidance within the Github's interface.

[Example from Electron](https://github.com/electron/electron/security/policy)

**Comment by KalobTaulien** [comment]
I like that idea. I think that'd be a good contribution to the repo so people can find what to do if they find a security flaw a little easier.

**Comment by Patil2099** [comment]
@m1kola  Can I work on this?

**Comment by m1kola** [comment]
@Patil2099 sure! As far as I see no one else is working on it. Thanks!

**Comment by somaran** [comment]
I raised a pull request for this issue at #5536 @m1kola  Could you please review it ?

Thanks!

**Comment by gasman** [comment]
Fixed in #5536
