### ISSUE TITLE
Use InlinePanel on non-Page models (without snippets)

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#5499]
I have a regular Django model (without a `title` field), that I am displaying in a Wagtail ModelAdmin. I would like to add an `InlineModel` to the Django model, so I can display related items. However, the `InlinePanel` does not render in the Wagtail UI.

There are a couple of StackOverflow items that say this should be somewhat possible:

- https://stackoverflow.com/questions/42299519/how-to-use-inlinepanel-in-modeladmin
- https://stackoverflow.com/questions/53512343/is-wagtails-inlinepanel-compatible-w-a-non-page-model
 
At least in the second SO item answer, there is a suggestion to use a Snippet. However, I don't really feel that a snippet, nor inheriting from Page model, is best for the project, as they seem to require a `title` field.

**Comment by gasman** [comment]
Hi @brylie,
Inline panels do work on both snippets and ModelAdmin models, neither of which require a `title` field.

Will close this for now as it sounds like more of a [support query](https://docs.wagtail.io/en/stable/support.html) than a bug report, but if you can provide a standalone example that demonstrates the failure on a fresh Wagtail instance, we'll be happy to investigate further.

**Comment by brylie** [comment]
I had defined a `ModelAdmin` model from `ClusterableModel`, but the `InlineModel` would not render in the UI until I used the `register_snippet` decorator. This is somewhat a feature request, as there doesn't seem to be, at lease a clear example of, a way to define a regular `ClusterableModel`, register it with the Wagtail `ModelAdmin`, and render an `InlinePanel` pointing to an `Orderable` field, without using `register_snippet`.

**Comment by brylie** [comment]
Here is the example code I am working with:

```py
from wagtail.admin.edit_handlers import InlinePanel
from wagtail.core.models import Orderable
from wagtail.snippets.models import register_snippet

from modelcluster.fields import (
    ParentalKey,
)
from modelcluster.models import ClusterableModel


@register_snippet
class Order(ClusterableModel):
   panels = [
        InlinePanel("items", label="Order items"),
    ]

    def __str__(self):
        return f"Order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(Orderable):
    order = ParentalKey(
        Order,
        related_name="items",
        on_delete=models.CASCADE,
        blank=False,
    )
    product = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    panels = [
        FieldPanel("product"),
        FieldPanel("price"),
        FieldPanel("quantity"),
    ]

    def __str__(self):
        return f"{self.quantity}x {self.product} @ { self.price}"

    def get_cost(self):
        return self.price * self.quantity
```

**Comment by brylie** [comment]
I have also converted this to a support request on StackOverflow:

https://stackoverflow.com/questions/57453957/render-wagtail-inlinepanel-on-non-page-model-without-using-snippet

However, I suspect it might be a feature request.

In any case, thanks very much for your prompt support @gasman, and I understand the need to keep support requests in correct channels :-)
