### ISSUE TITLE
Feature request: unregister_rich_text_feature

### ISSUE THREAD

**Issue by pySilver** [wagtail/wagtail#5524]
Looks like we need to think about implementation of `unregister_rich_text_feature` for editor. As a quick idea it can work as a signal based filter that can change stack of registered filters.

For problems caused by lack of this feature see the discussion at #5517

**Comment by KalobTaulien** [comment]
For more issue clarity: the problem arises when two registered rich text features use the same name for the same feature.
![image](https://user-images.githubusercontent.com/4743971/63444747-6a0a3080-c3f4-11e9-90af-f9bab8404772.png)

@pySilver I haven't dug into this yet and I haven't run into this as an issue in Wagtail yet, but if you set specific features using the `features=[]` keyword argument, can you list all the features you want and exclude the doubled feature?

**Comment by pySilver** [comment]
@KalobTaulien thats an interesting point, looks like `features` is good alternative for not writing `unregister_rich_text_feature` code. One can define constant(s) for its project effectively fixing duplicates.
