### ISSUE TITLE
Calculated / annotated fields

### ISSUE THREAD

**Issue by the-moog** [wagtail/wagtail#5526]
I want to include a calculated field in my model.
( a calculcated GUID)

I've looked at https://github.com/schinckel/django-computed-field
but this seems to break with 
'guid' cannot be specified for Item model form as it is a non-editable field

How to include calculated fields in a model form?

**Comment by gasman** [comment]
@the-moog Can you give more details of the functionality you're looking for, please? As far as I can see from the readme, django-computed-fields doesn't deal with forms at all (only populating the field within the model).

**Comment by the-moog** [comment]
I need a calculated searchable field in the model that is infact a 'hash' (not a true hash as it's reversible) of some fields of data in the db that never changes even if the record is updated.  I've manged this in the past in pure Django sites, but never in Wagtail.  From an SQL perspective this would be a calculated field/column.
This calculated field (called guid) needs to appear in the snippet/form for that model.

**Comment by the-moog** [comment]
I'm not specifically looking to use django-computed-fields.
Any means to include a calculated field in my model will do.
I've tried to understand what's happening.  
It looks to me like support for calculated or static fields is there in Django by various means but Wagtail's API does not allow this?
It seems the @register_snippet decorator implies [panels] being a list of Panels derived classes.
These Panels are all derived from admin_edit, so assume any field can be edited.  Passing a non-editable field breaks things.

Am I correct that a Snippet is the correct decorator to use for a dynamic list of user edited records?

Is there another way?

**Comment by gasman** [comment]
Hi @the-moog,
This should be possible by overriding your model's `save` method to populate the field before performing the save. You can make the field non-editable in the form by [passing a `widget` parameter to `FieldPanel`](https://docs.wagtail.io/en/stable/reference/pages/panels.html#fieldpanel) with the `readonly` attribute set - if you're concerned about users tampering with the form then you can also set [`disabled=True` on the field](https://docs.djangoproject.com/en/stable/ref/forms/fields/#disabled), although this will probably require [a custom form class](https://docs.wagtail.io/en/stable/advanced_topics/customisation/page_editing_interface.html#customising-generated-forms).

For further assistance, please ask on one of our [support channels](https://docs.wagtail.io/en/stable/support.html).
