### ISSUE TITLE
KeyError exception when trying to access a streamfield in a hook

### ISSUE THREAD

**Issue by johnraz** [wagtail/wagtail#5537]
### Issue Summary

I have a page model `SimplePage` with a `content` streamfield.
Everything works fine with that page model in usual cases except when I try to access it from within a hook.

There it will raise a `KeyError` exception.

If I fetch the page from DB again it will work.

Note that doing a `refresh_from_db` will not fix the issue, only a plain `objects.get` will.

The above description shown in action in my debugger:
```
(Pdb++) page
<SimplePage: test>
(Pdb++) page.content
*** KeyError: 'content'
Traceback (most recent call last):
  File "/home/myproject/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/wagtail/core/fields.py", line 34, in __get__
    return obj.__dict__[self.field.name]
(Pdb++) page._meta.model.objects.get(pk=page.pk).content
[<wagtail.core.blocks.stream_block.StreamValue.StreamChild object at 0x7fba2f43fb10>]
```

### Steps to Reproduce

1. Create a Page model with a simple streamfield
2. Setup a hook and try to access that streamfield
```
@hooks.register("register_page_listing_buttons")
def page_custom_listing_buttons(page, page_perms, is_parent=False):
    page.my_stream_field
```

It should raise.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

* Python version: 3.7.4
* Django version: 2.2.4
* Wagtail version:2.6.1
* Browser version: not relevant

**Comment by gasman** [comment]
Thanks for the report @johnraz!

Looks like this is caused by the use of `specific(defer=True)` when fetching the page queryset. The same thing can be reproduced on the command line, from a fresh Wagtail install with a `body` StreamField added to the `HomePage` model:

    ./manage.py shell
    Python 3.5.2 (default, Nov 12 2018, 13:43:14)
    [GCC 5.4.0 20160609] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    (InteractiveConsole)
    >>> from wagtail.core.models import Page
    >>> Page.objects.filter(depth=2).specific()[0].body
    []
    >>> Page.objects.filter(depth=2).specific(defer=True)[0].body
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/home/vagrant/.virtualenvsv/tableblock/lib/python3.5/site-packages/wagtail/core/fields.py", line 34, in __get__
        return obj.__dict__[self.field.name]
    KeyError: 'body'

**Comment by gasman** [comment]
Also worth noting that the error doesn't occur if `HomePage.body` is a plain `TextField`. My guess is that `obj.__dict__['some_field']` isn't valid for deferred objects, and needs to be wrapped in a method call that catches that case and fetches from the database where necessary.
