### ISSUE TITLE
ModelAdmin delete error 

### ISSUE THREAD

**Issue by roodie** [wagtail/wagtail#5539]
### Issue Summary

For some reason, if I have a model which is registered as a snippet, and also has it's custom ModelAdmin defined (don't ask...:-D), then if I try to delete an instance using the modeladmin, I get the following error message:

```python

File "C:\virtualenv\wagtail\lib\site-packages\django\core\handlers\exception.py" in inner
  34.             response = get_response(request)

File "C:\virtualenv\wagtail\lib\site-packages\django\core\handlers\base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "C:\virtualenv\wagtail\lib\site-packages\django\core\handlers\base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\virtualenv\wagtail\lib\site-packages\django\views\decorators\cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "C:\virtualenv\wagtail\lib\site-packages\wagtail\admin\urls\__init__.py" in wrapper
  102.             return view_func(request, *args, **kwargs)

File "C:\virtualenv\wagtail\lib\site-packages\wagtail\admin\decorators.py" in decorated_view
  34.             return view_func(request, *args, **kwargs)

File "C:\virtualenv\wagtail\lib\site-packages\wagtail\contrib\modeladmin\options.py" in delete_view
  397.         return view_class.as_view(**kwargs)(request)

File "C:\virtualenv\wagtail\lib\site-packages\django\views\generic\base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)

File "C:\virtualenv\wagtail\lib\site-packages\django\utils\decorators.py" in _wrapper
  45.         return bound_method(*args, **kwargs)

File "C:\virtualenv\wagtail\lib\site-packages\django\contrib\auth\decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "C:\virtualenv\wagtail\lib\site-packages\wagtail\contrib\modeladmin\views.py" in dispatch
  713.         return super().dispatch(request, *args, **kwargs)

File "C:\virtualenv\wagtail\lib\site-packages\django\utils\decorators.py" in _wrapper
  45.         return bound_method(*args, **kwargs)

File "C:\virtualenv\wagtail\lib\site-packages\django\contrib\auth\decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "C:\virtualenv\wagtail\lib\site-packages\wagtail\contrib\modeladmin\views.py" in dispatch
  73.         return super().dispatch(request, *args, **kwargs)

File "C:\virtualenv\wagtail\lib\site-packages\django\views\generic\base.py" in dispatch
  97.         return handler(request, *args, **kwargs)

File "C:\virtualenv\wagtail\lib\site-packages\wagtail\contrib\modeladmin\views.py" in post
  730.                 model=self.verbose_name, instance=self.instance)

Exception Type: KeyError at /admin/home/snippetandadmindemo/delete/2/
Exception Value: 'model_name'
```

Deletion via the snippets interface is flawless. No relations are involved.

### Steps to Reproduce

I was able to reproduce this behaviour using the following simple setup:

models.py:

```python
@register_snippet
class SnippetAndAdminDemo(Indexed, ClusterableModel):
    name = models.CharField(verbose_name="Name", max_length=300)
    description = RichTextField(blank=True, null=True)

    class Meta:
        verbose_name = "demo object"
        verbose_name_plural = "demo objects"

    def __str__(self):
        return self.name
```

wagtail_hooks.py

```python
class DemoAdmin(ModelAdmin):
    model = SnippetAndAdminDemo
    menu_label = "Demo"
modeladmin_register(DemoAdmin)
```

### Technical details

* Python version: 3.6.8.
* Django version: 2.2.3
* Wagtail version: 2.6.1

**Comment by roodie** [comment]
Constistently getting this error in multiple projects.

**Comment by gasman** [comment]
Hi @roodie - thanks for the report.

I'm unable to replicate this as described on a fresh Wagtail instance. The changes I made from the initial `wagtail start` setup were:

* In settings/base.py, add `'wagtail.contrib.modeladmin',` to `INSTALLED_APPS`
* Change home/models.py to:

        from django.db import models

        from wagtail.core.models import Page
        from wagtail.snippets.models import register_snippet
        from wagtail.core.fields import RichTextField

        from wagtail.search.index import Indexed
        from modelcluster.models import ClusterableModel

        class HomePage(Page):
            pass


        @register_snippet
        class SnippetAndAdminDemo(Indexed, ClusterableModel):
            name = models.CharField(verbose_name="Name", max_length=300)
            description = RichTextField(blank=True, null=True)

            class Meta:
                verbose_name = "demo object"
                verbose_name_plural = "demo objects"

            def __str__(self):
                return self.name

* Add home/wagtail_hooks.py:

        from wagtail.contrib.modeladmin.options import (
            ModelAdmin, modeladmin_register)

        from .models import SnippetAndAdminDemo


        class DemoAdmin(ModelAdmin):
            model = SnippetAndAdminDemo
            menu_label = "Demo"
        modeladmin_register(DemoAdmin)

* Run:

        ./manage.py makemigrations
        ./manage.py migrate
        ./manage.py runserver

I then added a `SnippetAndAdminDemo` object through the Snippets interface, and was able to delete it successfully from the ModelAdmin index page.

Can you confirm whether you're able to replicate this issue with the above setup?

Also, is the above error output complete? It looks to me like there might be something missing, as the line it's complaining about (https://github.com/wagtail/wagtail/blob/v2.6.1/wagtail/contrib/modeladmin/views.py#L729-L730) doesn't appear to be doing any dict lookups.

**Comment by roodie** [comment]
Hello,

I am re-tested it, and I was able to reproduce the error. They key was - again - the language settings.

With the default language set to english, it works just fine. If I change the default language code to 'hu', it throws the same exception again.

```python
LANGUAGE_CODE = 'hu'
```

i

**Comment by gasman** [comment]
Thanks - can confirm I'm seeing the same thing with `LANGUAGE_CODE = 'hu'`.

**Comment by gasman** [comment]
I've tracked this down to an error in the Hungarian translation - the translated version had `model_name` instead of `model` as the placeholder variable:

<img width="639" alt="Screenshot 2019-09-03 at 18 13 35" src="https://user-images.githubusercontent.com/85097/64194285-a159f200-ce76-11e9-9c34-635a0d0ae4fa.png">

I've fixed it now, but this is something we should be catching at the point of fetching the translations - I suspect that's not happening because we're using Python's `format` to do the variable interpolation, rather than gettext's own system.

**Comment by gasman** [comment]
PR #5548 opened, to convert this string (and others) to use old-style `%` string formatting instead of `format()` - Transifex and Django's `makemessages` command have validation on these to prevent similar issues from recurring.

**Comment by gasman** [comment]
There will be a 2.6.2 release, probably next week - we'll re-fetch the translations when putting the release together, so this will fix the error on this specific string. #5548 _won't_ be included in 2.6.2, as that will require re-translations of all the affected strings (which is something we'd want to avoid in a patch release) - until that's merged it's possible that there are other as-yet-undiscovered instances of this error.

**Comment by roodie** [comment]
I've tried to go thru the translation files (did some searches for "{") to see if I made another mistake, but couldn't find any other instances. Fingers crossed.

**Comment by roodie** [comment]
I can confirm that #5548 fixes it.
