### ISSUE TITLE
Soundcloud embed doesn't work with links to artist

### ISSUE THREAD

**Issue by kstaikov** [wagtail/wagtail#5562]
### Issue Summary

https://soundcloud.com/hear-the-bern us a valid url that returns an embeddable player with a list of tracks in the soundcloud oembed API. However, this is not a valid embed URL in wagtail, because it expects an extra layer of depth in the URL (hear-the-bern/something-else) - https://github.com/wagtail/wagtail/blob/master/wagtail/embeds/oembed_providers.py#L221-L226. It can currently be hacked by adding a question mark to the URL being sent in (hear-the-bern/?), but this is not very user friendly.

### Steps to Reproduce

1. In the richtext editor, try to embed https://soundcloud.com/hear-the-bern. You get an error about embeddable URL not being found.
2. See that `curl "https://soundcloud.com/oembed"  -d 'format=json' -d 'url=https://soundcloud.com/hear-the-bern/?'` returns a valid embed information.

**Comment by gasman** [comment]
Fixed in #5564
