### ISSUE TITLE
Easily make Wagtail Menu visible on non-Page views/templates

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#5565]
The Wagtail (frontend) menu (with the Wagtail icon) currently only renders on Page model views. It would be consistent, if this menu would appear on all front-end views, showing relevant links depending on the type of view. It is possible to create a custom template that would conditionally render the Wagtail Menu on all frontend templates, but [takes a considerable amount of boilerplate](https://stackoverflow.com/a/57679157/1191545).

Rather, it would be nice to have a default, or configuration option(s), whereby the Wagtail Menu would appear on all frontend templates where the template tag is included.

**Comment by gasman** [comment]
Thanks for the suggestion @brylie!

As far as I can see the only item in the menu that would be meaningful on a non-page view is "Go to Wagtail admin". No reason we can't have a menu containing just that option though...

I don't think we need to make a configuration option for this - anyone who _doesn't_ want the menu to show on non-page views can change the template code to something like:

    {% if page %}{% wagtailuserbar %}{% endif %}

**Comment by tdsprogramming** [comment]
Has this been picked up?

**Comment by gasman** [comment]
@tdsprogramming Yes - #5636

**Comment by brylie** [comment]
> As far as I can see the only item in the menu that would be meaningful on a non-page view is "Go to Wagtail admin". No reason we can't have a menu containing just that option though

Yes, the "Go to Wagtail" link is a convenient shortcut to the Wagtail admin. It would be nice to display it on all site pages for logged in users, so they have a consistent experience and aren't left wondering why the Wagtail flitters away on some pages.

**Comment by lb-** [comment]
Merged in via #6018
