### ISSUE TITLE
EMAIL_HOST_USER is overriding Wagtail Forms From Address when EMAIL_BACKEND is set to SMTP

### ISSUE THREAD

**Issue by davemerwin** [wagtail/wagtail#5572]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
In issue _Originally posted by @davemerwin in https://github.com/wagtail/wagtail/issues/5558#issuecomment-532748050_ I had stated that the from_address was being overridden by whatever the EMAIL_HOST_USER was set to.

I have reproduced the steps as per the comment by @gasman here: https://github.com/wagtail/wagtail/issues/5558#issuecomment-530411138

The only difference is I removed the setting `EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'` wich makes SMTP the default email backend.

I added in settings to use a working email account. When I do that, the EMAIL_HOST_USER overrides the from_address, the DEFAULT_FROM_EMAIL, and the WAGTAILADMIN_NOTIFICATION_FROM_EMAIL

### Steps to Reproduce

1. Install example project exactly as per this comment from @gasman https://github.com/wagtail/wagtail/issues/5558#issuecomment-530411138
2. Comment out the console backend which is for testing only
3. Add in SMTP email settings to send an email from an actual server
4. Submmit form and receive it in mail box
5. From address is always the EMAIL_HOST_USER

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I expect that the from_address would appear in the from for the email sent by the form.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes

### Technical details

* Python version: Python 3.7.3
* Django version: Django 2.1
* Wagtail version: Wagtail 2.5.1
* Browser version: Firefox 69

**Comment by gasman** [comment]
Hi @davemerwin - thanks for the update. If `EMAIL_HOST_USER` is the setting that's being picked up as the email address, then it's safe to say that the From: address is being rewritten at the SMTP server's end, as a precaution against users spoofing email addresses. For example, Gmail's SMTP server does this - see the note at https://www.digitalocean.com/community/tutorials/how-to-use-google-s-smtp-server

(In the general case, there's no guarantee that `EMAIL_HOST_USER` is an email address at all - it's up to the administrator of the SMTP server to decide whether their usernames correspond to email addresses like `bob@example.com` or just plain strings like `bob` - so it wouldn't make sense for Django or Wagtail to attempt to use that as a From address.)

In the case of Gmail in particular, from https://stackoverflow.com/questions/1332510/how-to-change-from-address-when-using-gmail-smtp-server it looks like there are hoops you can jump through to get it to accept addresses other than the account's primary email - but that would be out of Wagtail's scope.
