### ISSUE TITLE
Calendar icon on datefield should be clickable

### ISSUE THREAD

**Issue by bretth** [wagtail/wagtail#5573]
### Issue Summary

When filling in a form containing a datefield (or datetimefield) my user who was new to wagtail clicked on the calendar icon on a datefield and never worked out that you click on the empty space in the formfield and instead assumed the form was broken and didn't complete the form. They had made the mistake once before and I showed them where to click and the calendar widget popped up so they were expecting that to appear but just forgot so I needed to email them a screenshot to show them how to get the date widget.

![Capto_Capture 2019-09-19_11-07-34_am](https://user-images.githubusercontent.com/57012/65208221-b5892a80-dad7-11e9-9edf-77ca5b013f7e.png)

### Technical details
* Wagtail version: 2.6.1

**Comment by gasman** [comment]
Thanks for the report @bretth! As it happens, we've recently been discussing revising the date picker widget, to deal with the fact that Chrome has now made it impossible to avoid autocomplete dropdowns appearing over the top of it - see #5528. If the current version is causing users confusion too, then that's all the more reason to go with @thibaudcolas's suggestion of having the date picker triggered by a dedicated button (https://github.com/wagtail/wagtail/issues/5528#issuecomment-528787591).

I'll merge this issue into #5528 and continue the discussion there.
