### ISSUE TITLE
Image height resize rule documentation

### ISSUE THREAD

**Issue by JeffBobbo** [wagtail/wagtail#5577]
A minor thing, the documentation for the `height` resize rule (https://docs.wagtail.io/en/v2.6.2/topics/images.html#term-height) describes it as resizing, while the `width` one describes it as only reducing. `height` works the same way as `width` and will only reduce the size of the image, not resizing it up to make it fit the height given.

Documentation should be changed to say `height` reduces the size to fit the constraint.

**Comment by gasman** [comment]
Updated in #5593.
