### ISSUE TITLE
Extending draftail with a new block type, re edit page and new style is missing

### ISSUE THREAD

**Issue by bruecksen** [wagtail/wagtail#5582]
### Issue Summary
When I copy the "creating a new block" example from the documentation (https://docs.wagtail.io/en/v2.6.2/advanced_topics/customisation/extending_draftail.html#creating-new-blocks), I can properly use the help-text element and it is also correctly displayed in the frontend. But when I try to edit the page again the previously added help-text block is not being displayed in the richtext editor. When I save the page, obviously the help-text block is missing again in the frontend. 

### Steps to Reproduce

1. Add help-text example from (https://docs.wagtail.io/en/v2.6.2/advanced_topics/customisation/extending_draftail.html#creating-new-blocks) to `wagtail_hooks.py`
2. Edit an page an add help-text block in a richtext field
3. Save page
4. Open page again and find missing help-text block in richtext field

I expect the example from the documentation to work. When I try to add a different block type I have the same error.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.5.3
* Django version: 2.2.5
* Wagtail version: 2.6.1

**Comment by gasman** [comment]
Hi @bruecksen - thanks for the report. This has been fixed in the latest version of the documentation - please see #5571.

**Comment by bruecksen** [comment]
@gasman true story, thanks. Now it is working as expected!
