### ISSUE TITLE
Admin API returning no pages in Wagtail 2.6

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#5585]
Multiple users have reported no pages showing in the explorer menu after upgrading from Wagtail 2.5 to 2.6; checking admin API responses shows that no pages are being returned for the URL `admin/api/v2beta/pages/?child_of=1&for_explorer=1`.

https://stackoverflow.com/questions/57825908/wagtail-admin-api-call-for-fetching-child-pages-returns-0-in-the-explorer
https://stackoverflow.com/questions/58137551/menu-navigator-disappeared-after-upgrading-to-wagtail-2-6-from-2-5
and Slack support conversation copied below.

Unfortunately no-one's been able to pin this down to a reproducible test case yet. #5069 made changes to this part of the admin API in 2.6, but given that this bug occurs for superusers, it's hard to see how that can be the culprit (since `user_perms.explorable_pages()` returns early with `Page.objects.all()` for them).

```
miric 1:43 PM
I’ve just upgraded Wagtail from 2.3 to 2.6.1 and made migrations. My project is seemed to work but I’ve noticed Pages menu in Admin panel is empty now. What might be a reason of this? Response for ?child_of=1&for_explorer=1 is almost empty :disappointed:

mattwestcott  22 days ago
@miric First thing to try is to clear your browser cache / force refresh - a lot of people have reported broken menus because they had outdated javascript files cached

mattwestcott  22 days ago
Also, if this is a production site (i.e. NOT running locally with manage.py runserver), make sure you've re-run ./manage.py collectstatic

miric  22 days ago
Unfortunately they didn’t worked.

mattwestcott  22 days ago
OK - what do you mean by the response for ?child_of=1&for_explorer=1 being "almost empty"? Normally it would have one entry in it

miric  22 days ago
Here are two screenshots of responses from issue project and normal project:
<responses.jpg>

mattwestcott  22 days ago
Hmm, that's not good - pages have disappeared for some reason. Can you still get at them from /admin/pages/ and see them on the front-end?

miric  22 days ago
Yes. I see root Translatable site root page (I use WagtailTrans)

mattwestcott  22 days ago
Running manage.py fixtree might help... otherwise I'm out of ideas.

mattwestcott  22 days ago
If you can downgrade back to 2.3 and then upgrade one version at a time (2.4, 2.5, 2.6), that might give us some more clues

miric  22 days ago
I did it right after upgrade. No problems found. I’ll restore my DB and try to upgrade from very beginning

miric  22 days ago
Menu has been broken after 2.5.2>2.6 upgrade

mattwestcott  22 days ago
Are you logged in as a superuser/administrator, or a user with limited permissions? There were some changes to the permission model in 2.6 that might affect this: https://github.com/wagtail/wagtail/pull/5069

KalobTaulien  22 days ago
I had this happen once and ./manage.py fixtree is the trick for me as @mattwestcott suggested.

miric  22 days ago
Done right after 2.5.2>2.6 upgrade. No problems found (edited) 

KalobTaulien  22 days ago
Call me a tree cuz I’m stumped :thinking_face:

miric  22 days ago
@mattwestcott Yes, I’m on Admin level (edited) 

miric  22 days ago
It seems I have to roll back to 2.5.2 because I’m on budget with estimates. I’ll back to this some day if no solutions for now

miric  22 days ago
There were no any Wagtail-related migrations during 2.5.2>2.6. Is this OK? (edited) 

mattwestcott  22 days ago
@miric That's entirely possible, yes.

```

**Comment by kaedroho** [comment]
Have they changed anything in the `REST_FRAMEWORK` setting?

**Comment by inostia** [comment]
@kaedroho I encountered this issue after changing my REST_FRAMEWORK settings on 2.6.2. I changed it to this: 

    REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': (
            'rest_framework_simplejwt.authentication.JWTAuthentication',
        ),
    }

Should I add another class for authentication?

**Comment by kaedroho** [comment]
Yep, sounds like this could be an instance of the issue desribed in #5628. Could you try adding `rest_framework.authentication.SessionAuthentication` to your `DEFAULT AUTHENTICATION_CLASSES`?

**Comment by inostia** [comment]
Yep I did exactly that, and it fixed the issue. The page tree is now appearing in the admin API and in the page explorer 🎉
