### ISSUE TITLE
Text pasted into rich text editor doesn't always get wrapped with Paragraph tags

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#559]
1. Visit http://www.torchbox.com/blog
2. Copy text "Thoughts on the work we do, the web, and the wider world"
3. paste into rich text field

This results in much of the styling from the text copied displaying in wagtail's editor, which is itself an ugliness, but at least the editor toolbar identifies the `h2` and `i` text.

Instead:
1. Visit tbox blog again
2. Copy intro from whatever the top blog item is
3. paste, as before.
4. save
5. edit again.

This time, none of the styling is included, but the text isn't identified as a Paragraph either. This is probably because the section copied is from a `div` not a `p` and Hallo is trying to be clever. 

Given that there is no way to _deliberately_ enter completely unformatted text it shouldn't be possible to paste it in either.

**Comment by balazs-endresz** [comment]
I've just installed wagtail from master but this still doesn't work for me. The first time I start editing a richtext field it leaves it as a text node and the following blocks are wrapped in a `div` not a `p`. This happens even if you start typing (without pasting anything). 

However, the behaviour is different if you delete all the content and start typing again. Sometimes hallo leaves an empty text node in the DOM after deleting everything, and if there's an empty div right next to it then it will put the text in the div instead.

I can get back to this later this week, and try to make it wrap text in `<p>`  by default, or at least be consistent about using a `div` for the first block of text.

**Comment by gasman** [comment]
Sounds like we'd be better off applying the fixup on the server side, at the point of submitting the form (probably by creating a `RichTextFormField` class in wagtailcore/fields.py with a custom `clean` method, and having `RichTextField.formfield` use that in place of the CharField-with-a-RichTextArea-widget that it currently uses).

That would hopefully be more reliable than applying it within hallo.js. Re the current fix f0f7bc8e3216c09f126d2ac3b762deef5af5c2a9, I'm also slightly concerned about how often `cleanupContentClone` is fired - if it's on every keypress, then that's going to be a bit of a resource hog.

**Comment by davecranwell** [comment]
The trouble with doing anything server-side for a wysiwyg interface is that what users see before save isn't necessarily what they see after save, for example if DIVs get converted to Ps and suddenly margins are present where previously there were none before. Users have to learn by trial and error to mitigate it, or just learn to expect everything to change on save, which is frustrating experience.

This is actually already a problem, albeit not experienced regularly - it's possible to paste content which looks like a perfectly space set of paragraphs which somehow become double-spaced on save.

It feels like hallo's plugin system is where this ought to be fixed, since it's where it's being caused, but I'd agree the `cleanupContentClone` isn't very optimised at the moment. Indeed that plugin I added really only focused on new (blank) fields, not those with existing content.

**Comment by balazs-endresz** [comment]
In the current version of Wagtail I've also noticed that if you press a single key and hit enter very fast after each other then you can always reproduce the plain text node followed by divs. If you do it slowly then it will be converted to paragraphs. 

And I've managed to come up with another quite a bit more convoluted fix (that converts any existing content too): https://gist.github.com/balazs-endresz/5050df80015cdf443f01

It's using the `hallomodified` event instead of overriding `cleanupContentClone` (the latter seems to be triggered asynchronously), and takes care of a few additional edge cases too. Another gotcha was that we need to reposition the cursor after making changes to the DOM (see `setCursor()`).

Perhaps it can be simplified a bit but it in any case we'll have to execute something after each keyup event.

Next, we'll give it a try on a staging site first but given the complexity of all this I'm not sure it should be included in wagtail by default.

**Comment by DiogoMarques29** [comment]
Hi,
I got a similar problem: when inserting text copied from an other source, if I paste it with ctr+v there is no problem, but if I paste it with right click + paste and publish page, the text from rich-text will disappear. I tested it with windows and linux, both with chrome. Got any ideias about this?

**Comment by rgbk** [comment]
New Wagtail user here!

I seem to be having this issue too, the output of the RichTextField is very unreliable. It seems that the first line entered, even if not copy and pasted, doesn't get wrapped in a <p> tag but just outputs within a string (" ").

It's often inserting <br> wrapped in <p> tags in funny places also. I've tried wrangling it as best I can but can't seem to get the bottom of it, even though I have hallo-requireparagraphs seemingly enabled too.

**Comment by thibaudcolas** [comment]
This should be solved when switching to Draftail, where there is no direct relation between the formatting of what is pasted into the editor and the formatting output on the site's frontend. Still present for Hallo though.
