### ISSUE TITLE
Failing .annotate_score() when using specific models in query

### ISSUE THREAD

**Issue by roodie** [wagtail/wagtail#5601]
### Issue Summary

If you use .specific() in a query then search() it, the .annotate_score() values are lost.

### Steps to Reproduce

A simple test will show it (if you have any Indexed pages):

```python
from wagtail.search.backends import get_search_backend
from wagtail.core.models import Page

with_specific = s.search("test", Page.objects.live().specific()).annotate_score('_score')
for result in with_specific:
    print(result.title, result._score)
```
And the result is:
> AttributeError: 'NewsPage' object has no attribute '_score'

Everything is fine if you remove the .specific() part.

### Technical details

* Python version: Python 3.6.8
* Django version: 2.2.6
* Wagtail version: 2.6.2
* Search backend: Postgres (from contrib)

**Comment by lb-** [comment]
Fixed in f43db1e69e67946b08207aeb39e2949f907bba2e 
Resolved via #6026
