### ISSUE TITLE
Embeds app inserts unnecessary padding.

### ISSUE THREAD

**Issue by evistream** [wagtail/wagtail#5609]
(I'm novice of OSS and English. So, this sentences may be appropriate.)

### Issue Summary

Template of Embeds block has a bad attribute 'padding-bottom'.
If inserting some embeds block, big padding is inserted too.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit home/models.py as follows
```python
from django.db import models

from wagtail.core.models import Page
from wagtail.core.fields import StreamField
from wagtail.admin.edit_handlers import StreamFieldPanel
from wagtail.embeds.blocks import EmbedBlock


class HomePage(Page):
    body = StreamField([
        ('embed', EmbedBlock()),
    ])

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]
```
and edit home/templates/home/home_page.html as follows
```
{% extends "base.html" %}

{% load wagtailcore_tags %}

{% block body_class %}template-homepage{% endblock %}

{% block content %}
    {% include_block page.body %}
{% endblock %}
```

3. `cd myproject` `./manage.py migrate` `./manage.py createsuperuser` `./manage.py runserver`
4. access http://127.0.0.1:8000/admin/pages/
5. add Homepage, and add two embeds to Homepage. url example: https://www.youtube.com/watch?v=0oYrRCxo30k
6. preview the page
7. there is a lot of padding

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

this code is involved.
https://github.com/wagtail/wagtail/blob/f4cc454e13c23161490b995da970cd2f33ec92fa/wagtail/embeds/templates/wagtailembeds/embed_frontend.html#L1

6 years ago, the attribute 'pudding-bottom' was added.
But, I don't have idea what the code intend.
https://github.com/wagtail/wagtail/commit/17aa3fc89e5587032dbe7f688269915266998d73

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Python 3.7.0
* Django version: Version: 2.2.6
* Wagtail version: Version: 2.6.2

**Comment by gasman** [comment]
Hi @evistream - please see #1495.
