### ISSUE TITLE
Add get_document_model_string()

### ISSUE THREAD

**Issue by Thomasvdh92** [wagtail/wagtail#5614]
When implementing the custom document model, wagtail provides a method called get_document_model to retrieve the document model. For some reason, I get the error: `django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.`

After some try and error, I've found that referring to the model using a dotted string works. When implementing the custom image model, a method is provided called get_image_model_string, which is basically the same. 

### Describe the solution you'd like

I would like to request that the same method is created for the document model, so that a wagtail site can use the same method on every model: get_document_model_string(). This would prevent wagtail from throwing the error above and would add consistency overall.

**Comment by gasman** [comment]
Thanks for the suggestion @Thomasvdh92! This sounds good to me.

For anyone interested in picking this up: it would make sense for this to go in `wagtail/documents/__init__.py` along with the `get_document_model` function that currently exists in `wagtail/documents/models.py` - i.e. replicate the changes that were made for images in #3075.

**Comment by urandu** [comment]
@gasman I`d like to pick this up

**Comment by gasman** [comment]
@urandu Sure, go for it!

**Comment by WinterComes** [comment]
I sent some changes related to this issue, would love if someone will take a look on this. Thanks

**Comment by lb-** [comment]
Resolved via #5652
