### ISSUE TITLE
error on template ordering by date 

### ISSUE THREAD

**Issue by ivan-vilches** [wagtail/wagtail#5618]
i am getting and error trying to order by a fecha_inicio_evento date field on my model https://gist.github.com/9d3e1b3874eb43e6932699b7ea4b13c6   this is the screenshot of my error https://i.imgur.com/ifJzKc0.jpg ,
can you give me a hand folks not sure what i do wrong.

**Comment by loicteixeira** [comment]
Hi @ivan-vilches, please respect the time and effort of volunteers, by not asking the same question in multiple places. At best, you’ll be spamming the same set of people each time; at worst, you’ll waste the effort of volunteers who spend time answering a question unaware that it has already been answered elsewhere.
