### ISSUE TITLE
Feature Request: add additional hooks when documents are uploaded in admin screen

### ISSUE THREAD

**Issue by lingster** [wagtail/wagtail#5620]
Hi, 

as per the title, I'd like to add some additional hooks for when documents are uploaded. 
I think it would be a simple case of adding the following lines of code to `documents.views.multiple.py` in the `add/change()` functions: 

```
for fn in hooks.get_hooks('multiple_document_added'):
    result = fn(doc, request)
    if isinstance(result, HttpResponse):
        return result
```
If no objections, I can submit a PR in due course.
Thanks,
Ling

**Comment by gasman** [comment]
Hi @lingster - thanks for the suggestion.

Is there anything you'd like to do with this hook that can't already be achieved using a Django [post_save signal](https://docs.djangoproject.com/en/stable/ref/signals/#post-save) on the Document model? Normally we'd only recommend hooks for customising view / workflow behaviour - for example, redirecting to a custom dashboard page after creating an item - and I don't think that applies here, as the add/edit action is an AJAX request.

**Comment by lingster** [comment]
Hi @gasman, 

I was planning on being able to perform some processing on documents that have been uploaded, so for instance running OCR and indexing for search (via solr server). Looks like I can also achieve this with the post_save signal. As someone relatively new to Wagtail, from the [docs](https://docs.wagtail.io/en/v2.6.2/reference/hooks.html) it was hard to determine when to use hooks or when to use signals.

**Comment by gasman** [comment]
Have now opened #5621 to add some advice to the docs regarding signals versus hooks.
