### ISSUE TITLE
Admin API shouldn't be affected by global REST_FRAMEWORK configuration

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#5628]
For example, if you remove the `SessionAuthentication` class from the `default_authentication_classes` key of the `REST_FRAMEWORK` setting, the explorer menu will break.

The admin API should override all defaults so it won't break if any are changed.

**Comment by inostia** [comment]
@kaedroho I just saw this issue. See my comment here: https://github.com/wagtail/wagtail/issues/5585#issuecomment-543313909

**Comment by thibaudcolas** [comment]
Closing in favour of #4083.
