### ISSUE TITLE
Disabled field styles aren't accessible or visible on low contrast screens 

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#5649]
Fields that have a value but aren't editable use a very light grey font style which isn't visible on all screens and won't meet AA accessibility. 

<img width="985" alt="Screenshot 2019-10-23 at 14 43 30" src="https://user-images.githubusercontent.com/7290588/67399347-05aa4f80-f5a4-11e9-81a5-cebac13a840b.png">

**Comment by nicklee** [comment]
Aesthetically I feel like the lighter input and placeholder text is more pleasing, so can see why we originally went down this route, but we’re never going to pass accessibility tests going down that route... feels like Bootstrap does a decent job of this: https://getbootstrap.com/docs/4.0/components/forms/#disabled-forms

I’d suggest we make the normal input background a darker colour and lighten the text inside it whilst still passing the aa accessibility threshold. Might also be worth exploring a “disabled” cursor style, few options: https://codepen.io/chriscoyier/pen/uCwfB

**Comment by nimasmi** [comment]
Here's `color-grey-2` #4d4d4d foreground on `color-grey-4` background. It has a contrast ratio of 6.96:1, and passes WCAG AA standard at normal text size, but not AAA.

Does it look disabled enough?

![Screenshot_2019-10-24 Wagtail - Editing client](https://user-images.githubusercontent.com/1473980/67472392-efa29a80-f648-11e9-8c6b-878a27bd97ca.png)

**Comment by nicklee** [comment]
Is there a slight border on that (i'm on a tiny display and it's hard to tell)? If so would be good to match the background colour to the border, other than that this looks good to me. We should use the `cursor: not-allowed;` pointer style as well to reinforce the disabled state on non-touch devices

**Comment by nimasmi** [comment]
There is a border, and it is now coincidentally the same as the background. The cursor property value is currently `default`.
