### ISSUE TITLE
Changelog for 2.6.3 indicates incorrect release date

### ISSUE THREAD

**Issue by dwasyl** [wagtail/wagtail#5650]
### Issue Summary

Changelog indicates 2.6.3 was released on 2.6.3 `22.01.2019` rather than `22.10.2019`. Very minor, but should be fixed to avoid any confusion.

**Comment by loicteixeira** [comment]
Nice catch. Would you want to make your first contribution to Wagtail by [proposing a Pull Request](https://docs.wagtail.io/en/v2.6.3/contributing/index.html#pull-requests)?

**Comment by dwasyl** [comment]
@loicteixeira I've made a couple eons ago :) Just getting trying to figure out all of the changes since I last was heavily focused on Wagtail.

I'll see about pulling it down and making it, but if another PR gets submitted first I get it!

**Comment by loicteixeira** [comment]
I see #5651 has been merged now. Nice one 😄
