### ISSUE TITLE
Settings reference

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#5662]
There isn't currently a document that contains a reference of all of Wagtail's settings.

**Comment by gasman** [comment]
http://docs.wagtail.io/en/v2.6.3/advanced_topics/settings.html currently serves that purpose, but is disguised as a guide to integrating Wagtail into an existing Django project. Splitting that list off into its own page under Reference would definitely be a good thing.

**Comment by saevarom** [comment]
@gasman this issue is probably resolved by https://github.com/wagtail/wagtail/commit/23145382e96ad99ab4c00f6fa2b8c9c232b2063c#diff-5ea3baddff3f7632f31e141e18e5e577

**Comment by gasman** [comment]
@saevarom Good catch, thanks!

Fixed in #5692.

**Comment by saevarom** [comment]
One less issue to worry about!
