### ISSUE TITLE
Calling add_error for a StreamField causes errors

### ISSUE THREAD

**Issue by strindhaug** [wagtail/wagtail#5663]
### Issue Summary
In a WagtailAdminPageForm subclass with a custom clean method, trying to use self.add_error with for a StreamField causes AttributeError `'NoneType' object has no attribute 'get'`

### Steps to Reproduce

1. Create a model (affects both `django.db.models.Model` and `wagtail.core.models.Page` subclasses) with an optional StreamField
2. Create a WagtailAdminPageForm with a clean method.
3. In the clean method call `self.add_error` with the name of the optional StreamField as the first arg.

**Expected result:**
I'd expect this to work like any other field, flagging the input as invalid and showing an error, and at least not cause a crash.

**Actual result**
AttributeError with the text `'NoneType' object has no attribute 'get'`
and the line ` {{ field|render_with_errors }}` highlighted, see attached screenshot:

![wagtail_streamfield_error_error](https://user-images.githubusercontent.com/2144849/67675562-b6876480-f97f-11e9-9970-02ec8573838e.png)
(This is with a Page model, but it works just the same with a normal model)

### Technical details

* Python version:  Python 3.6.8
* Django version: 2.2.6
* Wagtail version: 2.6.3 
* Browser version: Opera (but not relevant, as it's a crash in the backend)

**Comment by strindhaug** [comment]
A minimal example model and form that demonstrates the issue:

models.py:
```python
from django.db import models
from django.utils.translation import ugettext_lazy as _
from wagtail.core.fields import StreamField
from django.core.exceptions import ValidationError
from wagtail.core import blocks
from wagtail.admin.edit_handlers import (
    FieldPanel,
    StreamFieldPanel,
    TabbedInterface,
    ObjectList,
)
from common.richtext import EXTENDED_RICHTEXT_FEATURES
from wagtail.admin.forms import WagtailAdminPageForm


class EventPageForm(WagtailAdminPageForm):

    def clean(self):
        cleaned_data = super().clean()
        title_nb = cleaned_data['title_nb']
        title_en = cleaned_data['title_en']
        content_nb = cleaned_data['content_nb']
        content_en = cleaned_data['content_en']

        # Make sure title and content exists for at least one language:
        if title_nb:
            if not content_nb:
                # THIS CAUSES THE ERROR
                # Fill in Norwegian title but not the content and save to trigger
                self.add_error('content_nb', _('This field is required.'))
                raise ValidationError([
                    ValidationError(_('You need to set a title and content for at least one language.')),
                ])
        elif title_en:
            if not content_en:
                # THIS CAUSES THE ERROR
                # Fill in English title but not the content and save to trigger
                self.add_error('content_en', _('This field is required.'))
                raise ValidationError([
                    ValidationError(_('You need to set a title and content for at least one language.')),
                ])

        else:
            # This works as expected:
            # Leave whole form blank to trigger
            self.add_error('title_nb', _('This field is required.'))
            self.add_error('title_en', _('This field is required.'))
            raise ValidationError([
                ValidationError(_('You need to set a title and content for at least one language.')),
            ])

        return cleaned_data


class Event(models.Model):

    active = models.BooleanField(verbose_name=_('active'), help_text=_('Check to publish'),)

    title_en = models.CharField(max_length=255, verbose_name=_('English title'), blank=True)
    title_nb = models.CharField(max_length=255, verbose_name=_('Norwegian title'), blank=True)

    COMMON_BLOCKS = [
        ('paragraph', blocks.RichTextBlock(label=_('Body text'), features=EXTENDED_RICHTEXT_FEATURES)),
    ]
    content_en = StreamField(COMMON_BLOCKS, verbose_name=_('content'), help_text=_('The main content of the page'), blank=True)

    content_nb = StreamField(COMMON_BLOCKS, verbose_name=_('content'), help_text=_('The main content of the page'), blank=True)

    common_panels = [
        FieldPanel('active'),
    ]
    en_panels = [
        FieldPanel('title_en'),
        StreamFieldPanel('content_en'),
    ]
    nb_panels = [
        FieldPanel('title_nb'),
        StreamFieldPanel('content_nb'),
    ]

    edit_handler = TabbedInterface([
        ObjectList(common_panels, heading=_('Metadata')),
        ObjectList(en_panels, heading=_('English')),
        ObjectList(nb_panels, heading=_('Norwegian')),
    ])

    base_form_class = EventPageForm
```

admin.py
```python
from django.utils.translation import ugettext_lazy as _
from wagtail.contrib.modeladmin.options import (
    modeladmin_register,
    ModelAdmin,
)

from .models import Event


class EventAdming(ModelAdmin):
    model = Event
    menu_label = _('Events')
    list_display = ['title_en', 'title_nb']    


modeladmin_register(EventAdming)

```

**Comment by strindhaug** [comment]
I think you also get the same error if you try to raise ValidationError inside a clean method of the model itself as well, cause that's the first thing I tried before rewriting using a WagtailAdminPageForm. 
It seems to me the issue is with the StreamField or StreamFieldPanel when django tries to render it with custom errors, no matter how you set the custom errors.

**Comment by easherma** [comment]
I've run into this problem as well.

**Comment by gasman** [comment]
Possibly related to #5300 - validation errors thrown _within_ StreamField blocks work on the assumption that the exception object passed to `render_with_errors` is the same one thrown by that block's `clean` method (which allows for the possibility of it stashing inner exceptions from child blocks in `params`), and it may well be that exceptions attached to the top-level StreamField object are being handled according to the same assumption.

**Comment by gasman** [comment]
This bug is still present on current Wagtail (5.0a0), but as of the Telepath rewrite in 2.13 the corresponding rendering code is client-side, and so it manifests as a Javascript error:

```
StreamBlock.js?5481:313 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at StreamBlock.setError (StreamBlock.js?5481:313:1)
    at new StreamBlock (StreamBlock.js?5481:182:1)
    at StreamBlockDefinition.render (StreamBlock.js?5481:346:1)
    at initBlockWidget (blocks.js?33ae:39:1)
    at (index):574:21
```

Specifically, `BlockWidget.render_with_errors` correctly recognises the presence of a validation error and telepath-serialises it to pass on the `data-errors` attribute, which is subsequently unpacked by the client-side StreamBlock class; only at this point does it fail because StreamBlock is expecting a StreamBlockValidationError.
