### ISSUE TITLE
Document how to override permissions_for_user

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#5671]
### Is your proposal related to a problem?

From @spapas on Slack:

>  is it possible to add edit/moderate permissions to a group only for the homepage of a wagtail site? i want these editors to be able to edit the homepage but not all its children.

### Describe the solution you'd like

Document how to override the permissions for a Page model based on a set of project-specific conditions

### Additional context

@allcaps helpfully pointed out:

> coenvanderkamp 08:39
> Your Homepage is a subclass of Page and has the permissions_for_user. It returns a PagePermissionsTester object defining what actions the user can perform on the page. This is a nice place to hook into that code and return YourCustomPagePermissionsTester. A subclass of PagePermissionsTester with overrides of the relevant permission parts.
https://github.com/wagtail/wagtail/blob/master/wagtail/core/models.py#L1215

> Serafeim 08:43
> @coenvanderkamp very nice thank you! i guess i'll just need to override the `CustomPagePermissionTester.can_edit` method (https://github.com/wagtail/wagtail/blob/6ce9f3a717abd3cb7a9ae35364ae274f141c267b/wagtail/core/models.py#L1843) to check if the user belongs to a `homepage_editors` group

> coenvanderkamp 08:46
> Yes, make sure to call super for all other users. Something like:
>
> ```python
> def can_edit(self):
>     val = super().can_edit()
>     if Group.objects.get(name="Some group").user_set.filter(id=self.user.id).exists():
>        return True
>    return val
> ```

ie. the implementation would be something along the lines of:

```python
class CustomPagePermissionTester(PagePermissionTester):
    def can_edit(self):
        val = super().can_edit()
        if Group.objects.get(name="Some group").user_set.filter(id=self.user.id).exists():
           return True
       return val


class MyPageModel(Page):
    # ...
    def permissions_for_user(self):
        return MyCustomPagePermissionTester(self, page)
```

**Comment by gasman** [comment]
See the discussion on #2907 - I believe there are good reasons not to officially support customisations of the permission model as it currently stands.

Will close this as a duplicate - it's not an exact match (documenting what's already possible vs adding further customisation overrides) but the work is effectively the same (determining what the documented external API for the permission model should be).

**Comment by zerolab** [comment]
Gah, my search-foo has failed me! Thank you @gasman
