### ISSUE TITLE
ForeignObjectComparison breaks when related model has custom primary key

### ISSUE THREAD

**Issue by haplo** [wagtail/wagtail#5678]
### Issue Summary

Comparing page revisions raises an exception when one of the changed fields is a `ForeignKey` to a model that uses a [custom primary key](https://docs.djangoproject.com/en/2.2/topics/db/models/#automatic-primary-key-fields) (i.e. not `id`).

This looks very similar to #4180, but it's currently failing in 2.6.x.

### Steps to Reproduce

1. Create a page model with a `ForeignKey` to a model with a [custom primary key](https://docs.djangoproject.com/en/2.2/topics/db/models/#automatic-primary-key-fields).
2. Add an initial revision with a value for the related model.
3. Add another revision changing the value of the related model.
4. Try to compare both revisions.
5. Uncaught exception error: *FieldError: Cannot resolve keyword 'id' into field.*

Expected: comparing revisions works correctly, displays the changed foreign key.

I haven't checked with a fresh Wagtail install, but the error happens on our production Wagtail.

### Technical details

* Python version: 3.7.3
* Django version: 2.2.4
* Wagtail version: 2.6.1

**Comment by haplo** [comment]
I have a fix ready, will add a regression test and send a PR.

**Comment by gasman** [comment]
Fixed in #5681
