### ISSUE TITLE
Structblock in Streamfield on regular Django model errors out when editing attempted

### ISSUE THREAD

**Issue by DanielSwain** [wagtail/wagtail#5682]
### Issue Summary

Editing a StreamField that is a property on a regular Django model and that is made up of StructBlocks does not work.

### Steps to Reproduce

1. Add a StreamField property to a regular Django model (the following also uses [Wagtail Font Awesome](https://pypi.org/project/wagtailfontawesome/)):

```python
from wagtail.core import blocks

RICH_TEXT_STANDARD_FEATURES = ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'undo', 'redo', 'link', 'document-link', 'image', 'embed']

class OneColumnBlock(blocks.StructBlock):
    class Meta:
        icon = 'form'
        label = 'Full-width'
        template = 'snippets/columns_1.html'

    content = blocks.RichTextBlock(icon="fa-paragraph", features=RICH_TEXT_STANDARD_FEATURES)

class ImageLinkBlock(blocks.StructBlock):
    class Meta:
        icon='image'
        label = 'Image Link block'
        template = 'snippets/image_link_block.html'

    image = ImageChooserBlock(required=True)
    external_url = blocks.URLBlock(label="external URL", required=True)

class BlogPost(models.Model):
    content = StreamField([
        ('one_column', OneColumnBlock()),
        ('image_link', ImageLinkBlock()),        
    ], default='')

    panels = [
        FieldPanel('content'),
    ]
```

2. Click on one of the StructBlocks to choose it.  The following error shows in the console:

```
stream.js:87 Uncaught TypeError: Cannot read property 'initializer' of undefined
    at Object.onInitializeMember (stream.js:87)
    at postInsertMember (sequence.js:102)
    at Object.self.insertMemberAtStart (sequence.js:203)
    at Object.onChooseBlock (stream.js:140)
    at HTMLButtonElement.<anonymous> (stream.js:60)
    at HTMLButtonElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.2.1.min.js:3)
```

I have tried this on a couple of different regular Django models, and it fails the same on both.  It works fine when `content` is a property on a `Page`-type model.

**Update:**  This error is also occurring with Wagtail 2.7.  The same error message comes up in the console.

### Technical details

* Python version:  3.6.9
* Django version:  2.2.6
* Wagtail version:  2.6.2
* Browser version:  Chrome 78 (also fails in latest Firefox)

**Note:**  Template files left out here because not necessary to verify above behavior.

**Comment by DanielSwain** [comment]
I found the problem - turns out it wasn't a bug, but it is odd behavior - and I will leave this issue up in case it helps someone else.   I was puzzled because the exact same panel definition for `content` (using `FieldPanel` in the panels definition for `content`) actually works in the editor when `content` is a property of a **`Page`**-based model.  The solution, of course, was to use `StreamFieldPanel` in the panels definition for `content` when it is a property on a regular Django model.

**Comment by pySilver** [comment]
Warning would be really nice :)
