### ISSUE TITLE
versioned_static problems with ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by tomkins** [wagtail/wagtail#5693]
### Issue Summary

Feels like a continuation of #5632.

Before Wagtail 2.7 it was possible to run commands such as `./manage.py makemigrations  --dry-run --check` *before* running collectstatic, which can be useful for testing missing migrations in CI. However since 2.7 it results in a `ValueError: Missing staticfiles manifest entry` error.

There's a few places with rich text editor plugins where versioned_static is being called when other code is imported, instead of when `.media` is being called on a form or widget. This probably shouldn't happen.

### Steps to Reproduce

```shell
pip install wagtail==2.7
wagtail start versionedstaticdemo
cd versionedstaticdemo
echo "SECRET_KEY='secret'" > versionedstaticdemo/settings/local.py
cat > home/models.py <<EOF
from django.db import models

from wagtail.admin.edit_handlers import FieldPanel
from wagtail.core.models import Page
from wagtail.core.fields import RichTextField


class HomePage(Page):
    rich_text = RichTextField()

    content_panels = Page.content_panels + [
        FieldPanel("rich_text", classname="full"),
    ]
EOF
./manage.py makemigrations --settings=versionedstaticdemo.settings.production --dry-run --check
```

Results in:

```
ValueError: Missing staticfiles manifest entry for 'wagtailadmin/js/draftail.js'
```

### Technical details

* Python version: 3.7 (any)
* Django version: 2.2 (any)
* Wagtail version: 2.7+ / master

**Comment by safaci2000** [comment]
I'm seeing this exact error as well.  Please let me know if there is a work around / fix.

**Comment by zerolab** [comment]
@safaci2000 are you able to test #5694 ?

**Comment by safaci2000** [comment]
I somehow managed to generate this error again on a different code base while using the latest version.  Looking at #5694

**Comment by safaci2000** [comment]
I somehow managed to generate this error again on a different code base while using the latest version (2.7).  Looking at #5694.  Installing the dev version of master gets rid of this error, but gives me a different set of issues.  What causes this? it seems odd that this made the cut for the 2.7 release if it's so buggy?

**Comment by evan-rosa** [comment]
I was having a similar issue. What worked for me was running collectstatic (i.e. ./manage.py collectstatic) then adding the staticfiles directory to your 
STATICFILES_DIRS within your settings.py.
