### ISSUE TITLE
Improve access to StructValue values from StructBlock

### ISSUE THREAD

**Issue by hammygoonan** [wagtail/wagtail#5696]
### Is your proposal related to a problem?

Take the current example in the [documentation](http://docs.wagtail.io/en/v2.7/topics/streamfield.html#custom-value-class-for-structblock):

```
class LinkStructValue(StructValue):
    def url(self):
        external_url = self.get('external_url')
        page = self.get('page')
        if external_url:
            return external_url
        elif page:
            return page.url


class QuickLinkBlock(StructBlock):
    text = CharBlock(label="link text", required=True)
    page = PageChooserBlock(label="page", required=False)
    external_url = URLBlock(label="external URL", required=False)

    class Meta:
        icon = 'site'
        value_class = LinkStructValue
```

Now, I want to override `QuickLinkBlock`s `get_api_representation` method.

The neatest solution I've found looks like this:

```
def get_api_representation(self, value, context=None):
        struct_value = self._to_struct_value(value)  # calling what's meant to be a private method
        return {
            "style": value["style"],
            "link": struct_value.link(),  # accessing it as a method, rather than a property or attribute, I also need to know that link is a method for LinkStructValue
        }
```

It would be nice if there was one method I could call that would return a Python representation of *all* the values, including the additional ones I've added via the `value_class`

**Comment by gasman** [comment]
Hi @hammygoonan - thanks for the suggestion.

Are you sure `value.link()` doesn't work here? I'm 99% certain that `get_api_representation` is always passed a value in the block's native type, which in this case means the relevant `StructValue` subclass - so calling `_to_struct_value` on that value is redundant.

**Comment by hammygoonan** [comment]
Thanks for the response @gasman.

I just had a bit of a dig around, the `value` argument is just being passed a `dict` so `_to_struct_value` is required as far as I can tell.

The method is called in two places: [here](https://github.com/wagtail/wagtail/blob/e1d3390a1f62ae4b30c0ef38e7cfa5070d8565dc/wagtail/core/blocks/stream_block.py#L270) in the `BaseStreamBlock` and [here](https://github.com/wagtail/wagtail/blob/882f8f3cf8ddd79c30e611a48882b309e90dad0c/wagtail/api/v2/serializers.py#L221) in the `StreamField` serializer. Perhaps it's different in each. I guess my tests are for the Serializer.

I also think it would be nice if you could use [items()](https://docs.python.org/3/library/stdtypes.html?highlight=items#dict-views) on the value that is passed to `get_api_representation` so you don't have to know anything about the `StructValue` either.

**Comment by hammygoonan** [comment]
@gasman As I dig around a little further, it appears it depends on the block.

`EmbedBlock` receives a `EmbedValue`, but a standard `StructBlock` receives a `dict`.

**Comment by gasman** [comment]
How are you checking the object type? Be aware that `StructValue` is a subclass of `OrderedDict`, so many of its behaviours (e.g. `print`ing the value or looping over it) will make it look like a `dict`.

**Comment by gasman** [comment]
Closing as unable to replicate - when testing with the code below, the API representation shows the result of `LinkStructValue.url()` as expected.

```
class LinkStructValue(StructValue):
    def url(self):
        external_url = self.get('external_url')
        page = self.get('page')
        if external_url:
            return external_url
        elif page:
            return page.url


class QuickLinkBlock(StructBlock):
    text = CharBlock(label="link text", required=True)
    page = PageChooserBlock(label="page", required=False)
    external_url = URLBlock(label="external URL", required=False)

    def get_api_representation(self, value, context=None):
        return {
            "text": value["text"],
            "url": value.url(),
        }

    class Meta:
        icon = 'site'
        value_class = LinkStructValue
```
