### ISSUE TITLE
Infer panel definitions from field types

### ISSUE THREAD

**Issue by DanielSwain** [wagtail/wagtail#5701]
To address the problem I ran into [here](https://github.com/wagtail/wagtail/issues/5682#issuecomment-551333741), I propose that only panel types that fall into the Structural section [here](https://docs.wagtail.io/en/latest/topics/pages.html#editor-panels) be required in `panels`/`content_panels` definitions.  Basic and Chooser-type panels could still be explicitly specified when the user needs to provide class names or specify alternative widgets, but it seems like, otherwise, the panel type could be inferred from the field definition.  I think that not requiring the specification of a panel type would be more DRY, and less typing would mean faster development.  If this feature request is not implemented, then at the very least it would be nice if some kind of warning would be given when `FieldPanel` is inadvertently specified rather than `StreamFieldPanel` for a `StreamField`.

This feature request relates to, and somewhat expands, [this request](https://github.com/wagtail/wagtail/issues/1127) by @kaedroho.

**Comment by zerolab** [comment]
#7684 does away with most specialized field panels.

**Comment by gasman** [comment]
Yep, agreed.
