### ISSUE TITLE
Documents: file_size and file_hash not updated when document file changed

### ISSUE THREAD

**Issue by Quadric** [wagtail/wagtail#5704]
### Issue Summary

In `edit` function in file https://github.com/wagtail/wagtail/blob/master/wagtail/documents/views/documents.py#L143 

```
        if form.is_valid():
            doc = form.save()
            if 'file' in form.changed_data:
                doc.file_size = doc.file.size

                # Set new document file hash
                doc.file.seek(0)
                doc._set_file_hash(doc.file.read())
                doc.file.seek(0)

                # if providing a new document file, delete the old one.
                # NB Doing this via original_file.delete() clears the file field,
                # which definitely isn't what we want...
                original_file.storage.delete(original_file.name)

            # Reindex the document to make sure all tags are indexed
            search_index.insert_or_update_object(doc)

            messages.success(request, _("Document '{0}' updated").format(doc.title), buttons=[
                messages.button(reverse('wagtaildocs:edit', args=(doc.id,)), _('Edit'))
            ])
            return redirect('wagtaildocs:index')

            # --------------------------------------
            # Where doc is saved?
            # --------------------------------------
```

we see that document form is being saved... then... when "file" was changed it updates its "file_size" and "file_hash" property but it does not save "doc" object anywhere so that these properties remains unchanged

### Steps to Reproduce

1. Add new document
2. Check file_size and file_hash in database
3. Edit uploaded document - change file and save
4. File has changed but file_hash and file_size is unchanged

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.6.4
* Django version: 2.2.6
* Wagtail version: 2.6.3

**Comment by lb-** [comment]
Resolved via #5705
