### ISSUE TITLE
GrapesJS integration or similar functionality

### ISSUE THREAD

**Issue by florian-rabis** [wagtail/wagtail#5716]
Hi,
are you planning to integrate GrapesJS or something like this.
I'm a big fan of wagtail and your streamfield-concept but I miss a front-end editing functionality where you can edit the rendered page. Shortly I found GrapesJS. Do you think if it is possible to integrate it as an editor or to develope streamfield more in this direction?

Best regards

**Comment by gasman** [comment]
Hi @florian-rabis - thanks for the suggestion. We're keen to find ways to improve the user experience of StreamField - however, GrapesJS seems to be more oriented towards designing page layouts, which is not what StreamField is intended for. Our aim with StreamField and Wagtail in general is to allow editors to enter content in a way that isn't tied to a particular page design.

Having said that, I think this could be a good candidate for a third-party add-on.
