### ISSUE TITLE
ValueError: Missing staticfiles manifest entry for 'wagtailadmin/css/panels/rich-text.css'

### ISSUE THREAD

**Issue by hieu292** [wagtail/wagtail#5717]
# Issue Summary

Wagtail admin page get an error when setting DEBUG = False

### Steps to Reproduce
1. Set DEBUG = False
2. When adding a new page in the wagtail admin site, my server get unexpected error below (but when DEBUG = True, it works as normal) :

web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1    |     response = get_response(request)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1    |     response = self.process_exception_by_middleware(e, request)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/wagtail/admin/urls/__init__.py", line 105, in wrapper
web_1    |     return view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/wagtail/admin/auth.py", line 167, in decorated_view
web_1    |     return view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/wagtail/admin/views/pages.py", line 319, in create
web_1    |     'has_unsaved_changes': has_unsaved_changes,
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
web_1    |     content = loader.render_to_string(template_name, context, request, using=using)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
web_1    |     return template.render(context, request)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
web_1    |     return self.template.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
web_1    |     return self._render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
web_1    |     return self.nodelist.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
web_1    |     bit = node.render_annotated(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
web_1    |     return self.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
web_1    |     return compiled_parent._render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
web_1    |     return self.nodelist.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
web_1    |     bit = node.render_annotated(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
web_1    |     return self.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
web_1    |     return compiled_parent._render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
web_1    |     return self.nodelist.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
web_1    |     bit = node.render_annotated(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
web_1    |     return self.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
web_1    |     return compiled_parent._render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
web_1    |     return self.nodelist.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
web_1    |     bit = node.render_annotated(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
web_1    |     return self.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
web_1    |     result = block.nodelist.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
web_1    |     bit = node.render_annotated(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
web_1    |     return self.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
web_1    |     result = block.nodelist.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
web_1    |     bit = node.render_annotated(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
web_1    |     return self.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 188, in render
web_1    |     return template.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 173, in render
web_1    |     return self._render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
web_1    |     return self.nodelist.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
web_1    |     bit = node.render_annotated(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
web_1    |     return self.render(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/templatetags/static.py", line 106, in render
web_1    |     url = self.url(context)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/templatetags/static.py", line 103, in url
web_1    |     return self.handle_simple(path)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/templatetags/static.py", line 118, in handle_simple
web_1    |     return staticfiles_storage.url(path)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 153, in url
web_1    |     return self._url(self.stored_name, name, force)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 132, in _url
web_1    |     hashed_name = hashed_name_func(*args)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 420, in stored_name
web_1    |     raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
web_1    | ValueError: Missing staticfiles manifest entry for 'wagtailadmin/css/panels/rich-text.css'

* I looked up in `wagtailadmin/css/panels`, but not found file rich-text.css at both lib and staticfiles directories

### Technical details

* Python version: 3.7.
* Django version: 2.2.7
* Wagtail version: 2.7

**Comment by gasman** [comment]
Hi @hieu292,
Sorry, we can't provide assistance with deployment here - please check https://docs.djangoproject.com/en/2.2/howto/static-files/deployment/ and see our [support channels](http://docs.wagtail.io/en/v2.7/support.html) if you need further assistance.

To handle this as a bug report, we would need to see full steps for reproducing this starting from a fresh Wagtail instance.

**Comment by monkut** [comment]
Seeing the same issue here, it seems to related to the `myproject.urls.py` configuration here:
```
if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r"", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r"^pages/", include(wagtail_urls)),
]

```

In my case I'm using django-storages, and I don't think including ` staticfiles_urlpatterns()` and `static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)` outside of debug is an issue.
