### ISSUE TITLE
Feature Request: Add additional fields to edit in Page Copy

### ISSUE THREAD

**Issue by bmoe872** [wagtail/wagtail#5722]
### Is your proposal related to a problem?

If I set a field as 'unique' on a Page model, but then want to copy that page. I can't because the field is set to unique, so therefor the copy fails. 

It would be nice to be able to add additional fields to change on the copy page, so that you could change the unique field and then copy the page. 

### Describe the solution you'd like

I think it would be nice if this worked really similarly to the `exclude_fields_in_copy` property. 

maybe: `editable_fields_in_copy` as the property.

### Describe alternatives you've considered

I considered using the `before_copy_page` hook and writing my own view, but there is a lot of logic in the copy function that I'd have to rewrite just to get an additional field, and at that point I'd be writing out this feature.

**Comment by lb-** [comment]
I think this has been fixed as part of the ability to customize the copy form (Wagtail 6.0)
https://docs.wagtail.org/en/stable/advanced_topics/customisation/page_editing_interface.html#custom-page-copy-form

See https://github.com/wagtail/wagtail/pull/11396 (note: issue title is for a specific use case, but the PR was a generic solution to override the copy form).

I will close this issue as completed but if there is something missing, let's discuss.
