### ISSUE TITLE
revision_index template bug

### ISSUE THREAD

**Issue by cybelew** [wagtail/wagtail#5723]
Revision index (e.g. /page/<id>/revisions/) is throwing a `django.urls.exceptions.NoReverseMatch
` Exception:

`django.urls.exceptions.NoReverseMatch: Reverse for 'revisions_compare' with arguments '(3, 'NULL', 1)' not found. 1 pattern(s) tried: ['cms/pages/(\\d+)/revisions/compare/(live|earliest|\\d+)\\.\\.\\.(live|latest|\\d+)/$']`

Looking at the template, there's a bit here where it tries to check the previous_revision

```
                            {% with revision.get_previous as previous_revision %}
                            {% if previous_revision %}
                                <li><a href="{% url 'wagtailadmin_pages:revisions_compare' page.id previous_revision.id revision.id %}" class="button button-small button-secondary">{% trans 'Compare with previous revision' %}</a></li>
                            {% endif %}
                            {% endwith %}
```

PageRevision.get_previous_revision() raises a PageRevision.DoesNotExist error if there's no previous revision, but the Django `with` templatetag converts it to a string `"NULL"` instead of a `None` value, which is not caught by the check for previous_revision.

* Python 3.7.5
* Django 2.2.7
* Wagtail 2.6.3 & Wagtail 2.7

**Comment by gasman** [comment]
Hi @cybelew - please can you give steps for reproducing this, starting from a fresh Wagtail instance (or from the [bakerydemo](https://github.com/wagtail/bakerydemo) project)? I'm not seeing this behaviour when testing against bakerydemo, and I'm pretty sure the `{% with %}` tag doesn't do any string conversion.

**Comment by cybelew** [comment]
@gasman Oh my word, I figured out the issue.  Had 'string_if_invalid' turned on, god knows why.

Sorry!  Closing this ticket -_-
