### ISSUE TITLE
Default sizes of CharField and TextField seem to be reversed in ModelAdmin

### ISSUE THREAD

**Issue by RNCTX** [wagtail/wagtail#5729]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Wagtail seems to apply wrong sizes to text areas of models imported via ModelAdmin

### Steps to Reproduce

1. Start a new Django 2.2 project, install the head version of django-post-office from its git repo... 
`pip install git+git://github.com/ui/django-post_office.git@master#egg=post_office` 
...add to installed apps (`'post_office',`), makemigrations && migrate, createsuperuser and log into the admin.  Start a new email from the `Emails` section of the Django admin, like so...

![Screen Shot 2019-12-04 at 9 11 01 PM](https://user-images.githubusercontent.com/13775820/70202503-81d59e00-16df-11ea-857a-42c2c3b9049e.png)

2. Create a new Wagtail 2.7 project, install the same version of django-post-office...
`pip install git+git://github.com/ui/django-post_office.git@master#egg=post_office`
...add `'post_office',` to installed apps again, and add the relevant parts of the `Emails` class to your app's wagtail_hooks.py as a ModelAdmin, along with its required imports like so...

```
from django import forms
from django.conf import settings
from django.db import models
from django.utils import six
from django.utils.text import Truncator
from django.utils.translation import ugettext_lazy as _
from wagtail.admin.edit_handlers import FieldPanel, MultiFieldPanel
from wagtail.contrib.modeladmin.options import ModelAdmin, ModelAdminGroup, modeladmin_register
from post_office.fields import CommaSeparatedEmailField
from post_office.models import Attachment, Log, Email, EmailTemplate, STATUS
from post_office.admin import EmailTemplateInline, SubjectField, AttachmentInline, LogInline, CommaSeparatedEmailWidget, get_message_preview, requeue

class EmailAdmin(ModelAdmin):
	model = Email
	menu_icon = 'edit'
	menu_label = 'Emails'
	list_display = ('id', 'to_display', 'subject', 'template', 'status', 'last_updated')
	search_fields = ['to', 'subject']
	date_hierarchy = 'last_updated'
	inlines = [AttachmentInline, LogInline]
	list_filter = ['status', 'template__language', 'template__name']
	formfield_overrides = {
		CommaSeparatedEmailField: {'widget': CommaSeparatedEmailWidget}
	}
	actions = [requeue]

	def get_queryset(self, request):
		return super(EmailAdmin, self).get_queryset(request).select_related('template')

	def to_display(self, instance):
		return ', '.join(instance.to)

	to_display.short_description = 'to'
	to_display.admin_order_field = 'to'

	panels = [
		MultiFieldPanel(
			[
				FieldPanel('from_email'),
				FieldPanel('to'),
				FieldPanel('cc'),
				FieldPanel('bcc'),
				FieldPanel('subject'),
				FieldPanel('message'),
				FieldPanel('html_message'),
				FieldPanel('template'),
			],
			_('Email Fields'),
		),
		MultiFieldPanel(
			[
				FieldPanel('status'),
				FieldPanel('priority'),
				FieldPanel('scheduled_time'),
			],
			_('Scheduling Options'),
		),
		MultiFieldPanel(
			[
				FieldPanel('headers'),
				FieldPanel('context'),
				FieldPanel('backend_alias'),
			],
			_('Uncommon Options'),
		)
	]

modeladmin_register(EmailAdmin)
```

3. makemigrations && migrate, createsuperuser, and log into the wagtail admin and check out the `Emails` form...

![Screen Shot 2019-12-04 at 9 22 20 PM](https://user-images.githubusercontent.com/13775820/70203930-49848e80-16e4-11ea-93d4-388a23449102.png)
![Screen Shot 2019-12-04 at 9 23 06 PM](https://user-images.githubusercontent.com/13775820/70203933-4ab5bb80-16e4-11ea-8e5d-2a393e518b3f.png)

It seems that Wagtail has reversed CharField and TextField default text area sizes in the ModelAdmin styling perhaps?  The post_office project's code does have some explicit max_length declarations on these email address CharFields but there are no styles applied to the widgets in their models.  Django's admin seems to get the defaults right.

If I give the FieldPanels an explicit widget property of TextInput or Textarea, they display as they should, this only seems to affect the defaults if no widget property is given.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7.5
* Django version: 2.2.7
* Wagtail version: 2.7
* Browser version: Chrome 78

**Comment by gasman** [comment]
From a quick look, it seems that django-post_office is using [a custom field type derived from models.TextField](https://github.com/ui/django-post_office/blob/418bbae700e6cb4c69f922da01d8616ab4040213/post_office/fields.py#L8) for the address fields, not CharField. I think the height difference is happening because Wagtail adds a class attribute derived from the field's class name, and applies the custom height and auto-sizing behaviour to text areas based on that - but that doesn't happen for these fields because the class name is showing up as CommaSeparatedEmailField rather than TextField. The one thing Wagtail could improve here (short of giving django-post_office special-case treatment) is to not rely on python-classname-based class attributes for these fields.

**Comment by RNCTX** [comment]
Yes, I noticed that after a second look at django-post-office too, it's using `formfield_override` which I have not used before, and see no mention of in Wagtail's flavor of ModelAdmin, so I assume it's not supported.

I suppose this brings up another conundrum...

I understand after reading up on these why Wagtail has a subset `widget` to style fields with rather than the 10 pound hammer of `formfield_override`, but what is the recommended Wagtail-way for something like this situation?  In which we need to show a user a free-form list box (of email addresses is a good example), but not require them to provide the brackets and quotes to turn their data into a valid list?
