### ISSUE TITLE
template Image based error

### ISSUE THREAD

**Issue by jossingram** [wagtail/wagtail#573]
value too long for type character varying(100) image

Happens when we uploaded an image with a filename containing filter information in its filename and is displayed in a template, (we think) if template is trying to render it with filter information of dimensions bigger than it's physical size.

Also happened in image admin at one point, and had to reset the db. 

the image filename was Victoria-Parsons.focus-3618-1640-4557x3146.max-900x682.jpg

if the template tried to render it with  
 {% image carousel_item.image fill-900x600 as carouselimagedata %} it was fine, but when we wanted a bigger version in our template we used 
               {% image carousel_item.image fill-1000x600 as carouselimagedata %} 
and the error appeared when trying to access the page with that image.

to make sure the image wasn't corrupt, we renamed a different image with the same filename, and it happened again. We also tried smaller images than the new bigger dimensions, and they didn't cause an error.

**Comment by fabienheureux** [comment]
Hi, sorry to reopen this issue, but I think that the fix provided causes an issue on one of my projects. 
I will try to be as clear as possible:

1/ A contributor uploaded images with these filenames: 
- La_fille_de_Brest_realisation_emmanuelle_**Bercot_Irene_Franchon_KuB3.jpg**
- La_fille_de_Brest_realisation_emmanuelle_**Bercot_Irene_Franchon_KuB4.jpg**

2/ I am generating various versions of those files using a custom image model (I tried with the default image model, and the same issue occurs), that generates a _customwidth-url_, that I finally get from the API in an external app (last part is quite off topic though). 

3/ When I try to access the original file, from Wagtail admin, I get the following filename: La_fille_de_Brest_realisation_emmanuelle_**Bercot.original.jpg**

So, it seems clear that all the renditions are based on a same file, and are all identical.
I can ask my contributors to rename their files before upload, but it could may be a better idea to truncate a file from the beginning of its filename ?

Thanks
