### ISSUE TITLE
UX: Initially unclear how to edit page children

### ISSUE THREAD

**Issue by indirectlylit** [wagtail/wagtail#5743]
### Is your proposal related to a problem?

I was following the [getting started tutorial](https://docs.wagtail.io/en/v2.7/getting_started/tutorial.html), which has these instructions:

> ![image](https://user-images.githubusercontent.com/2367265/71483613-af8d9e80-27d6-11ea-9dc0-3fa5612d1188.png)

I couldn't for the life of me figure out how to do this, because my page looked like this:

![image](https://user-images.githubusercontent.com/2367265/71483629-c502c880-27d6-11ea-93bb-4805a94187b4.png)

It took me an embarrassingly long time to realize that there are "kinds" of page editing, confusingly accessed by two independent links:

![image](https://user-images.githubusercontent.com/2367265/71483728-317dc780-27d7-11ea-9544-c085ebfe2920.png)

Even worse, while it's possible to do this flow:

1. edit children
2. edit details

It's _not_ possible to do this flow

1. edit details
2. edit children

 ![2019-12-26 11 51 38](https://user-images.githubusercontent.com/2367265/71483781-668a1a00-27d7-11ea-9762-e0f84fbc898b.gif)

Note that hovering over any part of the the page card causes the "right arrow" button to get highlighted, which led me to believe that it was purely decorative. I didn't realize the right arrow was an independent button

### Describe the solution you'd like

Two ideas:

Rather than using the right arrow button, use a standard edit button:

![image](https://user-images.githubusercontent.com/2367265/71483955-0c3d8900-27d8-11ea-8071-1961bd32d07d.png)

Add an 'Edit children' link or similar to the main editor page:

![image](https://user-images.githubusercontent.com/2367265/71484048-72c2a700-27d8-11ea-8ab6-5903a72db9b9.png)

**Comment by tmsndrs** [comment]
Definitely agree with this as a problem. After using Wagtail for year I still don't have a constant approach to taking these actions even though I know how it works. 

The idea of adding a 'Edit children' button on the edit screen itself is interesting. My concern would be you can't see what the child pages are from this position.

**Comment by thibaudcolas** [comment]
I believe this should have been addressed by the addition of the current page in the breadcrumb. Also worth mentioning #7783.
