### ISSUE TITLE
Ensure PageChooserPanel works correctly on nested InlinePanel

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#5748]
### Is your proposal related to a problem?

There has been some recent work to allow a nested `InlinePanel` to display properly:
- #1952 
- #5566 

However, the test scenario uses only `FieldPanel` instances on the nested inline entity, as was introduced in https://github.com/wagtail/wagtail/commit/4001516a275d88943be438d75582883b890b274d:

https://github.com/wagtail/wagtail/blob/4001516a275d88943be438d75582883b890b274d/wagtail/tests/testapp/models.py#L201-L209

### Describe the solution you'd like
I hope that a `PageChooserPanel` will also render correctly when displayed in a nested `InlineModel`.

```py
class Issue(Page):
    content_panels = Page.content_panels + [
        InlinePanel(
            "articles",
            heading="Articles",
        )
    ]


class Article(Orderable, ClusterableModel):
    issue = ParentalKey(
        to="magazine.Issue",
        on_delete=models.CASCADE,
        related_name="articles"
    )

    panels = [
        InlinePanel(
            "authors",
            heading="Authors",
            help_text="Select one or more authors who contributed to this article",
        ),
    ]


class ArticleAuthor(Orderable):
    article = ParentalKey(
        "magazine.Article",
        null=True,
        on_delete=models.CASCADE,
        related_name="authors",
    )
    author = models.ForeignKey(
        "wagtailcore.Page", null=True, on_delete=models.CASCADE, related_name="archive_articles_authored"
    )

    panels = [
        PageChooserPanel("author"),
    ]
```

### Describe alternatives you've considered
I have looked into the Wagtail ecosystem for third-party field widgets, but it would be good to stick close to Wagtail Core, if possible.

**Comment by gasman** [comment]
Hi @brylie - thanks for the report. This is covered by #5126.

**Comment by brylie** [comment]
Thanks for the quick response, as usual, @gasman :-)
