### ISSUE TITLE
A TableBlock with large number of columns overstretches, in the admin, the table and other fields within a Orderable related model instance

### ISSUE THREAD

**Issue by bogdangoie** [wagtail/wagtail#5763]
### Issue Summary

A TableBlock with a large number of rows / columns, after the values in the table are modified, messes up with the display of the table field & other fields in the admin within a Orderable related model instance. 

The displayed inputs of the table and the other fields in the same block get overstretched to the point where you can't see the entire value / can't interact with them as they are partially out of view.

New wagtail instalation
![Screenshot 2020-01-14 at 09 17 07](https://user-images.githubusercontent.com/5082567/72331827-c37b4080-36b0-11ea-9b65-7973492733ac.png)

Prod example (I removed table data from screenshot but you can see the overstretched inputs including the table).

![Screenshot 2020-01-14 at 09 16 20](https://user-images.githubusercontent.com/5082567/72331922-f32a4880-36b0-11ea-9122-4f150e7a11ba.png)

### Steps to Reproduce

1. Create a related Orderable model that contains a TableBlock streamfield
2. Add the related model to a Page via an InlinePanel
3. In the admin, add a large number of rows and a few columns in an instance of the Orderable 
related model and save the page. Once you come back and modify table fields, the display of the fields within the Orderable related model instance gets modified & overstretched
4. In prod I also modified the table options to set `'autoColumnSize': False` but the issue gets even worse

Example code I added in a new Wagtail installation with one TableBlock stream field on it's own and one in a Orderable related model.: 

```
class HomePage(Page):
    streamfield_table = StreamField([
        ('table', TableBlock('Detail Table'))]) # This also has issues but not as big as the Orderable related one
    content_panels = [
        MultiFieldPanel([
            FieldPanel('title'),
            StreamFieldPanel('streamfield_table'),
            InlinePanel('related_tables', label='Related Tables'),
        ], heading='Main section'),
    ]


class HomePageRelatedTableBlock(Orderable):
    page = ParentalKey(HomePage, on_delete=models.CASCADE,
                       related_name='related_tables')
    char1 = models.CharField(max_length=255, null=True)
    char2 = models.CharField(max_length=255, null=True)
    detail_tables = StreamField([
        ('detail_table', TableBlock('Detail Table')),
    ])  # This has big issues with admin display (itself and char1 / char2 fields) once values within it change 

    panels = [
        FieldPanel('char1'),
        FieldPanel('char2'),
        StreamFieldPanel('detail_tables'),
    ]
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: YES

### Technical details

* Python version:  3.7.3
* Django version: 2.2.9
* Wagtail version: 2.7.1
* Browser version: Chrome 79.0.3945.117 , Firefox  72.0.1

**Comment by thibaudcolas** [comment]
This is no longer as much of an issue with the current UI. Closing in favour of #9717
