### ISSUE TITLE
Nested InlinePanel fails to save when creating >=2 items

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#5770]
### Issue Summary

When adding new objects within nested InlinePanels, the form fields of the grandchild objects are not allocated unique IDs / names, leading to failures in initialising JS and saving.

### Steps to Reproduce

1. Start a new project with `wagtail start eventdemo`
2. Edit home/models.py as follows:
    ```
    from django.db import models

    from modelcluster.fields import ParentalKey
    from modelcluster.models import ClusterableModel
    from wagtail.core.models import Page, Orderable
    from wagtail.admin.edit_handlers import FieldPanel, InlinePanel


    class Event(Orderable):
        venue = ParentalKey('Venue', related_name='events', on_delete=models.CASCADE)
        name = models.CharField(max_length=255)
        date = models.DateField()

        panels = [
            FieldPanel('name'),
            FieldPanel('date'),
        ]


    class Venue(ClusterableModel, Orderable):
        page = ParentalKey('HomePage', related_name='venues', on_delete=models.CASCADE)
        name = models.CharField(max_length=255)

        panels = [
            FieldPanel('name'),
            InlinePanel('events', label="Events"),
        ]


    class HomePage(Page):
        content_panels = [
            InlinePanel('venues', label="Venues"),
        ]
    ```
3. `./manage.py makemigrations`, `./manage.py migrate`, `./manage.py createsuperuser`, `./manage.py runserver 0:8000`
4. Log in to admin, edit the homepage and add a venue and two events. Note that the second date field does not provide a date picker.
5. Click 'save draft'. Note that only one of the events has been saved.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

The root cause of both issues is in the mechanism for adding child objects to the form: the HTML fragment to be inserted is stored in the page as a `<script type="text/django-form-template">` block, with `__prefix__` placeholders that get replaced with the correct index number (by search-and-replace on the HTML string) when a child is added. When InlinePanels are nested, the template block itself contains another template block also using `__prefix__` as the placeholder string, so we can't distinguish between first-level and second-level placeholders:

```
<script type="text/django-form-template" id="id_venues-EMPTY_FORM_TEMPLATE">
    <li data-inline-panel-child id="inline_child_venues-__prefix__">

        ...
        <label for="id_venues-__prefix__-name">Name:</label>
        <input type="text" name="venues-__prefix__-name" maxlength="255" id="id_venues-__prefix__-name">
        ....

        <script type="text/django-form-template" id="id_venues-__prefix__-events-EMPTY_FORM_TEMPLATE">
            <li data-inline-panel-child id="inline_child_venues-__prefix__-events-__prefix__">

                ...
                <label for="id_venues-__prefix__-events-__prefix__-name">Name:</label>
                <input type="text" name="venues-__prefix__-events-__prefix__-name" maxlength="255" id="id_venues-__prefix__-events-__prefix__-name">
                ...
                <label for="id_venues-__prefix__-events-__prefix__-date">Date:</label>
                <input type="text" name="venues-__prefix__-events-__prefix__-date" autocomplete="new-date" id="id_venues-__prefix__-events-__prefix__-date">
                <script>initDateChooser("id_venues\u002D__prefix__\u002Devents\u002D__prefix__\u002Ddate", {"dayOfWeekStart": 0, "format": "Y-m-d"});<--/script>
                ...

            </li>
        <-/script>
    </li>
</script>
```

### Technical details

* Python version: 3.6.8
* Django version: 2.2.6
* Wagtail version: Git master (2.8a0)
* Browser version: Chrome 79.0.3945.117

**Comment by thaxy** [comment]
I was looking into this and tried with regex parsing only the first ``__prefix`` before giving up. Any thoughts on how to monkey patch this or how a working solution could look like?

**Comment by itraveribon** [comment]
I can confirm I am suffering the same problem and that the solution of @thaxy worked for me.

**Comment by the5thbeatle** [comment]
The solution from @thaxy worked for me as well, but I had to add `.replace(new RegExp(``${pre}\\\\u002D__prefix__``, 'g'), ``${pre}\\u002D${formCount}``)`. Without that line, a `RichTextField` wouldn't be added to the form correctly.

**Comment by robicano22** [comment]
should the script from @thaxy be placed in the root app or in the app where I've registered the page w/ the nested inline panels?

**Comment by TabishB** [comment]
@robicano22 Hey, I think i've ran into this issue the same time as you. I've added @thaxy's file inside the static folder of my app. For example `/<your_app_name>/static/wagtailadmin/js/expanding_formset.js`. This seems to override the js file the wagtailadmin static folder.

**Comment by robicano22** [comment]
> @robicano22 Hey, I think i've ran into this issue the same time as you. I've added @thaxy's file inside the static folder of my app. For example `/<your_app_name>/static/wagtailadmin/js/expanding_formset.js`. This seems to override the js file inside the wagtailadmin static folder.

@TabishB  thanks for reaching out. Excuse my ignorance on this, but I still can't override the expanding_formset function.

I've placed @thaxy 's snippet in the source app for the wagatil admin, as well as in the app where I've defined the models with the nested inline panels, at the proper directory path (see below), but the issues persist.

`/<admin-source-app>/static/wagtailadmin/js/expanding_formset.js`
`/<app-with-nested-inlines>/static/wagtailadmin/js/expanding_formset.js`


The console.log() statement does not show in the browser either.  Any thoughts on that?

**Comment by startprojekt** [comment]
Hey @robicano22 in my case I created an extra "wagtail_hacks" app and put it **before** any wagtail applications in INSTALLED_APPS. In "wagtail_hacks" folder you simply place @thaxy 's file i.e. "wagtail_hacks/static/wagtailadmin/js/expanding_formset.js"

**Comment by joshuadavidthomas** [comment]
+1 on the modifications from @thaxy and @the5thbeatle, though I had to edit it to `.replace(new RegExp(``${pre}\\\\u002D__prefix__``, 'g'), ``${pre}\\u002D${formCount}``)` added after the first `RegExp` line from @thaxy's script.
