### ISSUE TITLE
sibling_of missing in Page model reference documentation

### ISSUE THREAD

**Issue by bmoe872** [wagtail/wagtail#5772]
### Issue Summary

The function `sibling_of` on page models is not documented on the page model reference here:
http://docs.wagtail.io/en/v2.7.1/reference/pages/model_reference.html

This would likely not take much, but adding it to the reference would be helpful so if people are looking for that type of functionality they would know it exists by using the reference.

**Comment by gasman** [comment]
Hi @bmoe872,
`sibling_of` and the other queryset methods are covered in http://docs.wagtail.io/en/v2.7.1/reference/pages/queryset_reference.html.

**Comment by bmoe872** [comment]
o shoot, my bad. Thanks @gasman
