### ISSUE TITLE
Remove undo/redo buttons from rich text toolbar

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#5791]
### Is your proposal related to a problem?

Currently we show undo-redo buttons in the toolbar, which don’t feel particularly useful, and add to the clutter of icons:

<img width="785" alt="buttons-clutter" src="https://user-images.githubusercontent.com/877585/73112563-cb37b200-3f06-11ea-8a57-99d2054913a3.png">

### Describe the solution you'd like

In https://github.com/wagtail/wagtail/issues/4997#issuecomment-577705230, @benenright suggests removing them. This would just remove the buttons, but people would still be able to use OS-level controls to undo/redo (keyboard shortcuts, virtual keyboard on mobile devices). I can see a few different ways to go with this:

1. Remove the buttons, but add a new `undo-redo` rich text feature, not enabled by default, which makes both buttons appear as they do currently.
2. Remove the buttons, adding another way to make their presence configurable.
3. Remove the buttons, without any option to re-add them.

---

I’d be interested in feedback on which of the 3 ways to implement this sounds best.

**Comment by tomdyson** [comment]
I'm in favour of removing them, and I like the first option.

**Comment by gasman** [comment]
Option 1 sounds good to me too. Toolbar buttons for undo/redo have a very Windows 95 vibe... :-)

(It's a shame the Undo / Redo options in the browser's edit menu don't seem to work within rich text, as they'd be a possible fallback for editors unfamiliar with the keyboard shortcuts - but that's probably a very narrow case, and allowing the toolbar buttons to be re-enabled through rich text features is adequate to cover that.)

**Comment by thibaudcolas** [comment]
Just to note that as part of the page editor 2022 project we’re going to go for option 3 – remove the buttons altogether (but undo-redo is still possible). Implementing this will just be a matter of removing two lines: https://github.com/wagtail/wagtail/blob/ab92256b093b3817ac58aff5c1e2b1b04af8c10f/client/src/components/Draftail/index.js#L116-L117

and updating any related test cases (if any, not sure).

**Comment by thibaudcolas** [comment]
Done in #8806, shipping in Wagtail 4!
