### ISSUE TITLE
Multiparent pages.

### ISSUE THREAD

**Issue by i4x** [wagtail/wagtail#5795]
### Is your proposal related to a problem?

I try to have nodes (like [wagtail.core.model.Page](http://docs.wagtail.io/en/v2.0/reference/pages/model_reference.html#wagtail.core.models.Page)), that have multiple parents, and a method `.get_parents()` and `.get_children()`. However, current implementation only has one parent. Not sufficiently generalized.

### Describe the solution you'd like

When using Django, I would use:
```{python}
class Page(models.Model):
    parents = models.ManyToManyField(
        'self', blank=True, symmetrical=False, related_name='children')
```
to model this situation. Perhaps something along the lines of this could be done to generalize the Page model?

### Describe alternatives you've considered

Actually, I've considered:
https://github.com/wagtail/wagtail/issues/231#issuecomment-42259691
https://github.com/wagtail/wagtail/issues/1767

Also, 

```{python}
class Topic(Page):

    parents = StreamField([
        ('node', PageChooserBlock())
    ], blank=True)

    content_panels = Page.content_panels + [
        StreamFieldPanel("parents"),
    ]
```

which seem to work well, except there's no "`ADD PARENT PAGE`" option, which would be desirable.

### Additional context

Well, if that would affect performance, then I would like to have this feature as optional, being able to turn on in configuration.

**Comment by gasman** [comment]
Hi @i4x - thanks for the suggestion.
The current page tree structure is a fundamental design feature of Wagtail, used for everything from URL construction to permission handling and multi-language support, as well as minor details like deciding where to redirect a user after they publish a page - changing that would have massive repercussions for the whole of Wagtail, and I don't think it's going to be feasible to make that change.

As you note, there are various ways to set up additional many-to-many relations between pages which don't involve the tree structure - for example, the [categorisation example in the tutorial](http://docs.wagtail.io/en/stable/getting_started/tutorial.html#categories) could be extended to allow browsing blog posts by category, giving the appearance that a blog post is a child page of multiple categories. I think this kind of setup is going to be the best approach here.

**Comment by kaedroho** [comment]
If you're looking for a way to display your page in multiple locations in the frontend, you can use [`RoutablePageMixin`](http://docs.wagtail.io/en/v2.1.1/reference/contrib/routablepage.html) for this. 

Just define a sub-view on the parent page that fetches the page to be aliased and calls the `.serve()` method on it to render it. Something like:

```python
class MyIndex(RoutablePageMixin, Page):

    @route(r'(\w+)/')
    def render_alias(self, request, slug):
        return MyPage.objects.live().get(slug=slug).serve(request)
```
