### ISSUE TITLE
View all Users assigned to a particular Group

### ISSUE THREAD

**Issue by isandunk** [wagtail/wagtail#5801]
### Is your proposal related to a problem?

**When you add a User to a Group in Wagtail, you cannot easily see a list of Users that belong to that Group.**

For example, we have added a number of Users to a "Pathology" Group over a long period of time. Now, we are trying to see which Users belong to that Group. 

### Describe the solution you'd like

When viewing the Group in the wagtail admin, list the Users which have been added to the Group. The items in the list could hyperlink to the relevant User page.

### Describe alternatives you've considered

AFAIK there is only a manual (and impractical) method of sorting through all of our users to see if they have been set to an Admin, and then to check the Roles tab to see which Group they belong to. Plus, we have thousands of users, and it is not possible to sort them by "Level".

### Additional context

This issue may not be an issue on smaller sites that do not have a lot of users. On our setup, we have thousands of users.

**Comment by karranb** [comment]
Hey, can I proceed to implement this issue?
What about Instead of listing the users in the group admin just adding `group` to the users' admin filter? 😄

**Comment by gasman** [comment]
@karranb Sure, go ahead! Adding group as a filter on the user listing could work too, but it might get unwieldy on sites with lots of groups (>100 would not be too unusual).

**Comment by lb-** [comment]
Implemented via #5854
