### ISSUE TITLE
Page editor should 'remember' the scroll distance after saving a draft

### ISSUE THREAD

**Issue by jckpn** [wagtail/wagtail#5809]
I save drafts very often out of habit, however with Wagtail I'm always reluctant to do so as it makes the page refresh (and scroll to the top as a result of this). It can be a bit jarring and can hinder workflow. I'd expect it to 'remember' the part I was editing and scroll back down to it, or ideally save the draft without totally refreshing the page.

See https://gfycat.com/gratefulwhimsicalconure

**Comment by thibaudcolas** [comment]
For people interested in this, we are going to address this as part of the [page editor 2022](https://github.com/wagtail/wagtail/discussions/7739) project – we’ll have autosave, so there won’t be as much of a need to remember scroll positions after editing a page.

**Comment by thibaudcolas** [comment]
I’m going to close this in favour of [Autosave #24](https://github.com/wagtail/roadmap/issues/24) for the Wagtail roadmap. I don’t see ourselves ever implementing scroll restoration for drafts, but we will implement mechanisms to minimize the amount of full page reloads.
