### ISSUE TITLE
Replace the image and document admin pages with generic views

### ISSUE THREAD

**Issue by Hopiu** [wagtail/wagtail#5812]
### Is your proposal related to a problem?

For Wagtail 2.8 I added the possibility to filter images on the admin page by their tags. However I'm not satisfied with how it's implemented and it seems to me, that other problems will arise, especially in edge cases. (For example when searching an filtering by tag at the same time, when filtering by tag on the Nth page, etc...)

### Describe the solution you'd like

I'd like to create a pull request implementing the image admin page derived from `ModelAdmin`.

### Describe alternatives you've considered

I looked into implementing faceted search for the image admin pages, but I think that using what is already there is the way to go.

### Additional context

Here is some code how I'd implement it:
```
from wagtail.images import get_image_model

class ImageAdmin(ModelAdmin):
    """ Put image admin page in sidebar """
    model = get_image_model()
    menu_icon = 'image'
    menu_order = 300
    add_to_settings_menu = False
    exclude_from_explorer = True
    list_filter = ('tags', 'collection', 'created_at', )
    search_fields = ('title', )
    ordering = ('-created_at', )
    list_per_page = 25

modeladmin_register(ImageAdmin)
```
It would also need some adjustments of the template.

Have a look at the screenshot how it might look.

![Bildschirmfoto 2020-02-07 um 11 31 45](https://user-images.githubusercontent.com/671294/74022105-205ed380-499d-11ea-87d2-68845a34d8f0.png)

**Comment by thibaudcolas** [comment]
See #8851 and https://github.com/wagtail/wagtail/discussions/8609, as part of which we’re introducing generic filtering functionality to generic views that aren’t ModelAdmin. I believe this is generally the direction we want to take to other parts of the admin, so will rename this accordingly.

**Comment by lb-** [comment]
Need to check. This may have recently been done through the Universal Listings work.

**Comment by lb-** [comment]
Yep. Documents and Image index views now use class based views, I'll close this as complete. It looks like the original conversion was done a while ago but recent Universal Listings work will make this much easier to customise. 

https://github.com/wagtail/wagtail/pull/11709
https://github.com/wagtail/wagtail/pull/11698

Also related - https://github.com/wagtail/wagtail/issues/8365
