### ISSUE TITLE
project_template still uses 2.9rc1

### ISSUE THREAD

**Issue by jnsdrtlf** [wagtail/wagtail#5815]
### Issue Summary

The [`requirements.txt`](https://github.com/wagtail/wagtail/blob/47f677577e1df485c57cd6155b9e5fa68afbd69d/wagtail/project_template/requirements.txt#L2) file inside *project_template* still uses wagtail version **2.9rc1**. To my understanding, this should be changed to **2.9**

```requirements.txt
wagtail==2.9rc1
#        ^^^^^^ should be 2.9
```

**Comment by jnsdrtlf** [comment]
I'd be happy to submit a pull request. However, this is probably not worth an extra pull request.

Also, I am not sure about how you manage releases on PyPI. As a new wagtail build has to be submitted to PyPI, this might actually have to wait for the next release which will (hopefully) update `requirements.txt` anyway during version bump.

**Comment by gasman** [comment]
Hi @jnsdrtlf - thanks for the report. The version number on git master is generally one release ahead of the last release available on PyPI, but set to an alpha release - so it should have been 2.9a0. Now fixed in 2b797f4a2e3b36523c405f4e6bcd3e190ca82e25.

**Comment by jnsdrtlf** [comment]
Oh right, I totally forgot that we are currently on 2.8 not 2.9... Sorry for that
