### ISSUE TITLE
typo in django.po

### ISSUE THREAD

**Issue by diveru4i** [wagtail/wagtail#5830]
admin/locale/ru/LC_MESSAGES/django.po:360

```python
msgid "Sunday"
msgstr "Воскрксенье"
```

Thats a typo. Russian for "Sunday" is "Воскр**е**сенье"

**Comment by gasman** [comment]
Thanks @diveru4i! I've now updated this at https://www.transifex.com/torchbox/wagtail/ , so it'll be fixed when we next fetch the translations.
