### ISSUE TITLE
No warning when deleting a page which has foreign keys

### ISSUE THREAD

**Issue by jeffagc** [wagtail/wagtail#5839]
I have a page that is linked to a custom model courses which has submissions. On deleting the course page there is no indicator that warns me that the submission wil be lost or that there will be no reference for the future. With debug mode on you get a protected error when you click on delete after you are asked to confirm the deletion of the page. On production this is a 400 error which is not proper if I may say. 

Technical details

- Python version: Python 3.6.5
- Django version: Version: 2.2.10
- Wagtail version: Version: 2.8

**Comment by gasman** [comment]
Hi @jeffagc - thanks for the report. This is covered by the existing issue #1602, and there's work on a fix in progress at #4702.
