### ISSUE TITLE
Formbuilder forms do not save all values entered in 'Checkboxes' field

### ISSUE THREAD

**Issue by tmtlbt** [wagtail/wagtail#584]
Steps to reproduce:

1) Create a new Form page using Formbuilder.
2) Add a new form field. Set the field type to 'Checkboxes'. Make sure that there are at least two choices.
3) Publish the form and view it.
4) Tick at least two checkboxes. Submit the form.
6) Click 'Forms' in the admin menu and view the form data just submitted. Look for the data entered into the 'Checkboxes' field.
-> Only the last ticked value in the list appears.

**Comment by anteatersa** [comment]
This may be fixed on newer versions of Wagtail but I fixed by changing:

**form.data.get(x[0])** to **form.cleaned_data.get(x[0])** in the AbstractEmailForm -> process_form_submission in **wagtailforms/models.py**
