### ISSUE TITLE
Add Sonic as a search backend

### ISSUE THREAD

**Issue by andreasnuesslein** [wagtail/wagtail#5841]
So recently I searched for "Elasticsearch lightweight alternatives" or something like that. Most of our customers don't really need _ES_ for their daily needs but it would be nice if their queries were sped-up nonetheless.

 And I was kind of hoping/expecting that a Go or Rust-based **ES-protocol-compatible** implementation would pop up. Sadly nothing did BUT i stumbled over [**sonic**](https://github.com/valeriansaliou/sonic).

It says it needs only a few megabytes of RAM (compared to the JVM with easily 0.5-1GB) and it seems to cover most of the standard wagtail-cases I think.

So my question is, whether this would be something other people might be interested in as well. I'd be willing to look into this if it would be likely be included in Wagtail.

PS: Here's a python library for it: https://github.com/moshe/asonic

**Comment by zerolab** [comment]
Hi @andreasnuesslein,

I would recommend looking into it if it solves your use case. You can take a look at https://github.com/wagtail/wagtail-whoosh or the [Postgres backend](https://github.com/wagtail/wagtail/tree/master/wagtail/contrib/postgres_search) for examples.

As with Whoosh, this is best suited for a contributed package, in that it is a narrow enough use case that it will likely add unnecessary maintenance burden on Wagtail.

**Comment by tomdyson** [comment]
@andreasnuesslein this looks really interesting. My colleague @kaedroho - one of the core Wagtail developers - made some progress on this ES alternative in Rust:

https://github.com/kaedroho/rusticsearch

AFAIK he built enough of the API that it could be used as a drop in replacement for ES.

**Comment by kaedroho** [comment]
I had a look at sonic a few months ago, it doesn't seem to support filtering and only uses basic TF/IDF scoring. So if we did support it in its current state it probably won't be much faster than PostgreSQL and the results would be of similar quality, I think.

I think one to look out for is [Toshi](https://github.com/toshi-search/Toshi) which aims to support the ES query language. Also, [Tantivy](https://github.com/tantivy-search/tantivy) which is a reimplementation of Lucene and has gradually been gaining the features we would need to build a search backend out of it.

**Comment by andreasnuesslein** [comment]
Okay cool.
Thanks everybody for the insights! To me this feels like a "wait and see" moment now, where at some point a Rust-option will emerge which will either just be ES-compatible or big enough that it's worth to implement something for.

Cheers :relaxed:  :wave:
