### ISSUE TITLE
Avoid outputting href="None" links in the admin for non-routable pages

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#5851]
There are a number of situations where a page is considered live but is not accessible at any URL: namely, when the page is outside of any site root, or (as of #4276) the `wagtail_serve` URL route has been removed. Various templates in the admin do not check this when linking to live pages, resulting in links that look like `<a href="None">` - ones that I found in a very brief search were:

* wagtail/admin/templates/wagtailadmin/home/recent_edits.html
* wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html
* the wagtail.contrib.sitemaps app

We should do a more thorough search for these, and fix them where found: 'view live' action buttons (as in recent_edits.html) should not be displayed if there is no URL, and status indicators (as in page_status_tag.html) should be displayed but not linked.

**Comment by karranb** [comment]
Hi, Can I work on this issue?

**Comment by gasman** [comment]
@karranb Yes, please do!

**Comment by chosak** [comment]
I've merged @karranb's fix from #5867 in 36e777418f308fd6aa359e1c953afcf4ab041571, which partially addresses this PR.

@gasman because `wagtail_serve` either will or won't be registered for the entire Wagtail application, does it make sense to pull [this logic](https://github.com/wagtail/wagtail/blob/36e777418f308fd6aa359e1c953afcf4ab041571/wagtail/core/models.py#L832-L838) out somewhere so it can be checked directly? Relatedly, in wagtail.contrib.sitemaps, doesn't this only need to be checked once, because an entire Site either will or won't have URLs?

**Comment by TUSHAR-VERMA-star** [comment]
hey !! Can I take this issue ?

**Comment by gasman** [comment]
@TUSHAR-VERMA-star Yes, go ahead! The 'View live' and page status links were previously handled in #5867, but it looks like the sitemaps app is still in need of a fix, and there may be others. Even if you find that there's nothing else to fix, reporting that here will be useful information for us.

**Comment by TUSHAR-VERMA-star** [comment]
Ok Sir

**Comment by TUSHAR-VERMA-star** [comment]
According to me sitemaps app need not to fix.

**Comment by ParitoshKabra** [comment]
Is anyone still working on this issue? Can I move on with it @TUSHAR-VERMA-star @lb-  😅 ?

**Comment by SanskarGosavi2003** [comment]
Hey, is there someone still working on this? Can I start with this as my very first issue to open source?

**Comment by lb-** [comment]
Go for it @SanskarGosavi2003 - I don't think the previous person submitted a PR.

**Comment by SanskarGosavi2003** [comment]
I searched through the code of wagtail/contrib/sitemaps and couldn't find any issues with the current code

**Comment by gasman** [comment]
I can't recall what issues I originally found with the sitemaps app, and looking at the current code I can't see any places where non-routable pages might cause a problem: sitemap responses are constrained to the Site record for the current request, so pages outside a site root never enter into it; and if someone removes the `wagtail_serve` URL route (e.g. as part of implementing a headless site), then clearly the sitemaps app is not going to be useful in its out-of-the-box form anyway.

As such, I'm happy to close this. Thanks to everyone who provided feedback!
