### ISSUE TITLE
Change chooser panel terminology

### ISSUE THREAD

**Issue by jimmymorrisuk** [wagtail/wagtail#586]
Once you've added an image you get a button next to it that says "Choose another image". What this button actually does it change the image I've already uploaded but what it could mean is add another images as well as the image I've already chosen. 

This button should probably read something like: Use a different image / Change this image / Replace image.

**Comment by thibaudcolas** [comment]
The core team has reviewed this today – this is still relevant but needs further UI prototyping (and/or a proposed PR) to be considered further.

**Comment by thibaudcolas** [comment]
I can’t track down when this happened but the button is now "Change image", so I imagine we’ve made this switch to address this in particular – closing.
