### ISSUE TITLE
Django 2.1 added view permission to admin models. In Wagtail, they are not present (yet).

### ISSUE THREAD

**Issue by wimfeijen** [wagtail/wagtail#5862]
Hi,

Django 2.1 added a view permission to models.
https://docs.djangoproject.com/en/3.0/releases/2.1/#model-view-permission
so we can allow admin users to view certain models by setting permissions of a user or group.

In Wagtail 2.8, as far as I can see, view permissions are not present. 

I'd like Wagtail to add a new row of checkboxes for view permissions to for example: /admin/groups/2/ , so I can set view permissions for specific groups (and users), so it offers the same options as the default Django admin interface.

Thanks for your consideration,

Wim

**Comment by gasman** [comment]
Hi @wimfeijen - thanks for the suggestion. There's an existing issue covering this, at #5482.

**Comment by wimfeijen** [comment]
Hi gasman, thanks for your kind reply and for the pointer to the issue I was unable to find by myself due to my apparently lacking search abilities :} :P
