### ISSUE TITLE
remove submenu item

### ISSUE THREAD

**Issue by pimarc** [wagtail/wagtail#5866]
### Issue Summary

Didn't find a way to remove a submenu item. Not sure this is a bug and maybe I missed something. In this case please let me know how I can do that.

### Steps to Reproduce
set this code in wagtail_hooks.py:

```
@hooks.register('construct_main_menu')
def hide_sub_menu(request, menu_items):
  menu_items[:] = [item for item in menu_items if item.name != 'groups']

```
The submenu item is not removed. If you change for a main menu item (ex snippets) this is ok.

Typical use case: you define some snippet but you want this snippet to appear only in your own menu and not in the snippet menu.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)
yes

### Technical details

* Python version: 3.8.1.
* Django version: 2.2.
* Wagtail version: 2.8.

**Comment by gasman** [comment]
Hi @pimarc,
You need to use `construct_settings_menu` instead of `construct_main_menu` (or whatever has been passed as `construct_hook_name` when setting up the menu):
https://github.com/wagtail/wagtail/blob/122575d2ee5a3f4bc3cf7c689b3972a666f0a8b9/wagtail/admin/menu.py#L116-L118

**Comment by pimarc** [comment]
Thanks for your answer but in fact I'm searching for a kind of of 'construct_snippet_menu' hook that doesn't seam to exist.
I'd like to remove some of my snippets from the snippet menu but not all.
Didn't find any way to do that except removing the whole main snippet menu that is not what I(d like to do.

**Comment by gasman** [comment]
In the default setup, Snippets is not a submenu - is this a customisation you've made yourself? If so, you need to specify `construct_hook_name` at the point that you create and register that menu.

**Comment by pimarc** [comment]
mmm probably something I missed and didn't understand.
In fact, in my application, I'm registering models as snippets using @register_snippet. At this time these snippets are automatically inserted by wagtail in a 'Snippets' main menu.
ex:
```
@register_snippet
class TestSnippet(models.Model):
    name = models.CharField(max_length=255)

    panels = [
        FieldPanel('name'),
    ]
```
Now I created a new main menu called 'Elements" where I also inserted these snippets. Everything is Ok at this point.
But now , I'd like these snippets to appear only in my "Elements" menu but not in the 'Snippets' menu but I don't find any way to tell wagtail to not display them in Snippets menu.
Wagtail is creating this snippet menu, not me (or I don't know how)

**Comment by pimarc** [comment]
Well absolutly my fault. Sorry for your time.
I just had to not register as a snippet. In fact I thought that registering a snippet was something more than just displaying it in the snippets menu.

**Comment by pimarc** [comment]
Finaly no
In fact if don't register as snippet, I cannot use the SnippetChooserPannel.
So I rellay need a way to register as snippet but to not display a snippet in the snippet menu.
Maybe an option when registering a snippet ?

**Comment by gasman** [comment]
There are various add-on packages that implement chooser interfaces for non-snippet models:
https://github.com/wagtail/wagtail-generic-chooser
https://github.com/Naeka/wagtailmodelchooser/
https://github.com/neon-jungle/wagtailmodelchooser
https://github.com/springload/wagtailmodelchoosers
https://github.com/wagtail/wagtail-autocomplete

In the longer term we plan to refactor the way snippets, modeladmin and other areas of Wagtail admin work, so that choosers are independent of the model-editing views.

**Comment by pimarc** [comment]
Thanks

This helps
