### ISSUE TITLE
Deleting user on wagtail+social_auth throws ForeignKeyViolation error 

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#5871]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When trying to delete a user that was created by python_social_auth through a google login, the django part of Wagtail crashes with an `IntegrityError at /admin/users/<numerical id>/delete/`, withj the following stack trace:

```bash
postgres_1            | ERROR:  update or delete on table "auth_user" violates foreign key constraint "core_sitepermission_user_id_0a3cbb11_fk_auth_user_id" on table "core_sitepermission"
postgres_1            | DETAIL:  Key (id)=(19) is still referenced from table "core_sitepermission".
postgres_1            | STATEMENT:  COMMIT
backend_1             | Internal Server Error: /cms/users/19/delete/
backend_1             | Traceback (most recent call last):
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/db/backends/base/base.py", line 240, in _commit
backend_1             |     return self.connection.commit()
backend_1             | psycopg2.errors.ForeignKeyViolation: update or delete on table "auth_user" violates foreign key constraint "core_sitepermission_user_id_0a3cbb11_fk_auth_user_id" on table "core_sitepermission"
backend_1             | DETAIL:  Key (id)=(19) is still referenced from table "core_sitepermission".
backend_1             |
backend_1             |
backend_1             | The above exception was the direct cause of the following exception:
backend_1             |
backend_1             | Traceback (most recent call last):
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
backend_1             |     response = get_response(request)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
backend_1             |     response = self.process_exception_by_middleware(e, request)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
backend_1             |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend_1             |   File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
backend_1             |     return func(*args, **kwds)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/db/transaction.py", line 240, in __exit__
backend_1             |     connection.commit()
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/db/backends/base/base.py", line 262, in commit
backend_1             |     self._commit()
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/db/backends/base/base.py", line 240, in _commit
backend_1             |     return self.connection.commit()
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
backend_1             |     raise dj_exc_value.with_traceback(traceback) from exc_value
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/db/backends/base/base.py", line 240, in _commit
backend_1             |     return self.connection.commit()
backend_1             | django.db.utils.IntegrityError: update or delete on table "auth_user" violates foreign key constraint "core_sitepermission_user_id_0a3cbb11_fk_auth_user_id" on table "core_sitepermission"
backend_1             | DETAIL:  Key (id)=(19) is still referenced from table "core_sitepermission".
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no, primarily because this requires an incredible amount of work to turn into an mcve, which might not be necessary if this is a known issue that can actually be solved with some documentation that explains what additional steps are required to delete correctly users when using a custom auth backend

### Technical details

* Python version: 3.7
* Django version: 2.2.10
* Wagtail version: 2.6.3
* Browser version: n/a
* Python-social-auth version: 3.1.0

**Comment by gasman** [comment]
Hi @Pomax,
is the `core` app - and specifically the `core.SitePermission` model - part of python-social-auth, or your own project? From the stack trace, it looks like changing the foreign key to User to `on_delete=CASCADE` would solve this.

**Comment by Pomax** [comment]
As far as I know that's python-social-auth, and we don't specify any custom User model for it to use, so I'm not sure where we'd change that deletion policy =S

**Comment by Pomax** [comment]
As far as I can tell, the social auth disconnect needs to happen _before_ the user gets deleted by wagtail - is there a hook that can be used to tap into the user deletion signal, so that a bit of custom code can be run to ensure the social auth disconnect happens first?

I had a look at https://github.com/wagtail/wagtail/blob/master/wagtail/users/views/users.py#L179-L200 but I'm not sure I quite understand what it does: it looks like the `before_delete_user` hook can trigger before we actually know we're dealing with a delete POST (since it triggers outside of the `if request.method == 'POST'` scope), and `after_delete_user` is too late in this case, as the problem comes from the `user.delete()` call, near as I can figure.

**Comment by Pomax** [comment]
It also looks like the user model that social-auth uses is already set to cascade: https://github.com/python-social-auth/social-app-django/blob/751b5722b14cbaaf1c946bb8d7cfb88942b1614f/social_django/models.py#L33

**Comment by gasman** [comment]
For logic that only applies to the model level, you're better off using [the `pre_delete` signal provided by Django](https://docs.djangoproject.com/en/3.0/topics/signals/) - the `before_delete_user` hook primarily exists for things that need to customise view-level logic (e.g. redirecting the user away if they fail a permission check).

I'm not seeing anything in social_django's models.py that matches the name `core.SitePermission`. All Google results for that model name seem to point to it being part of Mezzanine - does that sound plausible for your project?

**Comment by Pomax** [comment]
Well that's a nice little heartattack - plausible: no, but possible? yes. We were using mezzanine before we moved to Wagtail, but we _supposely_ started with a clean set of user accounts when we made that switch... guess it's "oh god I hope not" digging time, thanks O_o

**Comment by Pomax** [comment]
Yep, it's totally legacy tables that shouldn't even exist causing integrity errors thanks to foreign key indexing. Many thanks for the mezzanine hint, and we'll get on deleting 26 dead tables that may or may not (or, in one case, _definitely_) interfere with wagtail's operations.
