### ISSUE TITLE
Blocker: Long pages fail to "save draft" in a way that allows subsequent editing. 

### ISSUE THREAD

**Issue by stevejalim** [wagtail/wagtail#5872]
### Issue Summary

_Note: am still trying to determine whether this is infrastructure related, but an initial point of view would be welcome. I think the triggering change is related to page content though._

In the page editor UI, when a page's StreamField becomes sufficiently[1] long, Wagtail will save the page content when `Save Draft` is clicked, but then reloading the page after the POST does not complete, leaving the page unsaveable because the Save controls panel does not re-appear. Reloading the editor page afresh (even hard reloading) does not fix this. Sometimes opening the page in a new tab will result in a clean/unblocked load featuring the save panel, but not all times. 

[1] "Sufficiently" is hard to measure, but a page with 32 elements in it (some rich text, some button elements, some raw HTML) definitely fails, and it can happen with as little as 10 elements in some test cases. (This is on https://github.com/mdn/developer-portal FWIW)

What I'm noticing is both the POST and the GET upon `Save draft` seem to not complete. Hitting 'esc' to kill the load, or waiting for the backend to time out, does not then allow the "Save panel" to appear.

**NOTE: the changes made when `Save Draft` is first clicked HAVE been saved in the DB.**

The page has multiple revisions and a live version - all of which worked without issue when the page's StreamField had fewer elements 

The payload size for the POST is around 270KB.

This is with Wagtail 2.8 and 2.7.1 and happens in Firefox main release, Firefox Developer and latest Chrome at least.

Restarting the server makes no difference.

Cold/warm browser cache makes no difference.

JS console shows no errors. 

Logging shows no errors.

### Steps to Reproduce

1. Add 25 items to a StreamField, ideally including rich text and other elements
2. Save the page as a draft.
3. Look for whether the page reload completes and the save panel appears - it does not for us once a page gets "too" long

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **NO** not yet. Indeed, right now I am struggling to replicate on localhost, but it's definitely replicable on deployed k8s environments, where the assets the edit page are all loaded but the actual response for the main edit page can land 30 secs after them (according to nginx logs), assuming it doesn't time out after 120 secs)

### Technical details

* Python version: 3.7.6
* Django version: 2.2.10 and 2.2.11
* Wagtail version: 2.7.1 and 2.8
* Browser version: Firefox main release, Firefox Developer and latest Chrome at least.

**Comment by stevejalim** [comment]
BTW, I know this is one of _those_ kind of bug reports. Sorry for that. Am digging away on my side, but have raised this in case it rings any bells

**Comment by stevejalim** [comment]
WIP update: this looks like it could be a load-balancer issue or something similar in infra. Will update/close this ticket accordingly when I know more.

**Comment by stevejalim** [comment]
Adding extra intel: interestingly, the _same_ `content_json` on the latest `PageRevision` will cause the issue on one type of `Page` subclass, but will work fine in a different subclass.

**Comment by loicteixeira** [comment]
It doesn't quite look like the same issue, but when talking about long pages, #3062 and #4521 come to mind.

Maybe dealing with large payload is CPU intensive and hit the limit of your k8s pod?

Marking the issue as "need more info" until it can be reproduced on a fresh install on localhost.

**Comment by stevejalim** [comment]
Thanks @loicteixeira - I'll try those approaches now. Certainly the JSON for the page content is fairly large for a text document.

Reproducing it on localhost hasn't been possible, but I did discover that moving the same content to a different, simpler Page subclass within the project would make the streamfield content work on that simpler page... until we added even more streamfield blocks and then it started hanging again.

Will investigate CPU and memory now

**Comment by stevejalim** [comment]
Also, if I force a GET of the preview for a hanging page, we get this:


![Screenshot 2020-03-10 at 12 01 48](https://user-images.githubusercontent.com/101457/76310635-0fb8ba80-62c7-11ea-9018-283d2d9f3e9c.png)

Am not sure if this is an accurate error message or not, beacuse the page did save, and therefore must have passed validation.

**Comment by stevejalim** [comment]
Hi folks - quick update 

Unsurprisingly, given I couldn't replicate this on localhost, this was not a Wagtail issue nor a k8s/resources one. The project was originally using Meinheld workers with gunicorn - once we switched to an alternative one (gevent in our case) the hanging issue went away.

Hopefully, that helps somoene else in the future too!
