### ISSUE TITLE
Impossible to create custom DocumentLinkHandler

### ISSUE THREAD

**Issue by nigimaxx** [wagtail/wagtail#5874]
### Is your proposal related to a problem?

I couldn't find an easy way to create a custom DocumentLinkHandler, that for example opens the document on a new page or displays an icon directly before it. 

For external links I found an easy solution, but this doesn't apply to the DocumentLinkHandler.

```py
class NewWindowExternalLinkHandler(LinkHandler):
    identifier = 'external'

    @classmethod
    def expand_db_attributes(cls, attrs):
        href = attrs["href"]
        return '<a href="%s" target="_blank" rel="noopener noreferrer follow">' % escape(href)

@hooks.register('register_rich_text_features')
def register_external_link(features):
    features.register_link_type(NewWindowExternalLinkHandler)
```

### Describe the solution you'd like

If you could add some code similar to this one, to your `wagtail_hooks.py` it would be perfect.

```py
class NewDocumentLinkHandler(DocumentLinkHandler):
    @classmethod
    def expand_db_attributes(cls, attrs):
        try:
            doc = cls.get_instance(attrs)
            return '<a href="%s" target="_blank" rel="noopener noreferrer follow">' % escape(doc.url)
        except (ObjectDoesNotExist, KeyError):
            return "<a>"


@hooks.register('register_rich_text_features')
def register_document_link(features):
    features.register_link_type(NewDocumentLinkHandler)
```

### Describe alternatives you've considered

Alternatively you can create your own link type with all the different handlers involved which essentially replaces the document link type, but this creates a lot of redundant code.

Another really ugly option is, to remove line 71 in [wagtail/documents/wagtail_hooks.py](https://github.com/wagtail/wagtail/blob/master/wagtail/documents/wagtail_hooks.py#L71).

**Comment by gasman** [comment]
Hi @nigimaxx,
Did you try [setting an `order` argument on `hooks.register`](https://docs.wagtail.io/en/v2.8/reference/hooks.html) (or adjusting the order of INSTALLED_APPS) to ensure that your hook runs after the one in wagtail.documents?

**Comment by nigimaxx** [comment]
Thanks @gasman, this helped.
