### ISSUE TITLE
API Child Pages - Object of type Page is not JSON serializable 

### ISSUE THREAD

**Issue by supermanzer** [wagtail/wagtail#5882]
### Issue Summary

I am attempting to return a list of child pages as part of the Detail view of a single Parent page.

### Steps to Reproduce

1. Create Parent and Child page models without an explicit link, simply using the `parent_page_types` and `subpage_types` attributes.
2. Define a property on the Parent page that returns the child pages
    ```
    @ property
    def children(self):
        return self.get_children()
    ```
3. Add the newly defined `children` property to the `api_fields` attribute.
4.  Attempt to access the detail view of the parent page in the API.

#### What I expected:
   I expected to return a list view of the related children as an element of the JSON returned for the detail view of the parent page.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version:3.7
* Django version: 3.0.3
* Wagtail version: 2.8
* Browser version: Firefox 74

**Comment by gasman** [comment]
Hi @supermanzer,
This is expected behaviour. `get_children` returns a queryset of Page objects, and these are not representable directly as JSON because there's nothing to specify which fields of the page should be part of the response. You can either modify your `children` method to return a JSON-valid value, e.g.

    @property
    def children(self):
        return [
            {'id': child.id, 'title': child.title} for child in self.get_children()
        ]

or set a [`serializer` argument](https://docs.wagtail.io/en/v2.8/advanced_topics/api/v2/configuration.html#custom-serialisers) on the `APIField` to handle the conversion to JSON.

**Comment by supermanzer** [comment]
@gasman 
My apologies for being unclear.  I am using the PageSerializer in the APIField definition:
```
...
APIField('children', serializer=PageSerializer)
...
```
And I still receive the `Page object is not JSON serializable` error.  How else can I apply the serialization?

**Comment by supermanzer** [comment]
@gasman 

Would it make sense to apply the PageSerializer in the list comprehension to return python dictionaries containing the serialized pages?  If so what would be the best way to implement it?

**Comment by gasman** [comment]
@supermanzer Probably best to ask on [our support channels](https://docs.wagtail.io/en/stable/support.html) - this seems like more of a django-rest-framework implementation question than a Wagtail issue.

**Comment by supermanzer** [comment]
@gasman That may be the case but it is still true that attempting to return a queryset via the API using the `serializer=PageSerializer` argument fails to produce the expected list view of child pages.
