### ISSUE TITLE
Collections in 'Upload' tab of Document chooser not ordered correctly

### ISSUE THREAD

**Issue by tleguijt** [wagtail/wagtail#5887]
### Issue Summary

Collections are sorted correctly on the first tab of the image/document chooser (using `Collection.order_for_display`. This sort method is not used for the 'Upload' tab.

### Steps to Reproduce

1. Create an new empty project
2. Create a couple of collections with some random names which are not in the correct alphabetical order (they should appear sorted in any Collection dropdown)
3. Open op the image chooser on any page. You'll notice the collections are sorted correctly on the 'search' tab but not on the 'upload' tab.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7.6
* Django version: 2.2.11
* Wagtail version: 2.8

**Comment by lb-** [comment]
Confirmed this is reproducible as at Wagtail 2.9, also the 'sorted' one does a case sensitive sort.



<img width="1517" alt="collections-inconsistent-sorting-dropdowns-2020-04-26" src="https://user-images.githubusercontent.com/1396140/80297709-278dc480-87c9-11ea-98b1-d4a0c7cb6748.png">

**Comment by gasman** [comment]
This is now handled by the nested collections feature coming in 2.11 (#6141). Collections will automatically be maintained in alphabetical order within each parent - on upgrading you'll just need to run a management command as per https://docs.wagtail.io/en/latest/releases/2.11.html#run-fixtree-to-prevent-collection-creation-issues.
