### ISSUE TITLE
'Locked Pages' report overrides language preference

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#5893]
### Issue Summary

[As reported by Вадим Козячий on the Google group](https://groups.google.com/forum/#!topic/wagtail/5gqURJMoMM8) - visiting the Locked Pages report overrides the logged-in user's language setting.

### Steps to Reproduce

1. On a fresh instance of bakerydemo, go to Account settings -> Language preferences and set language to German
2. Go to Berichte -> Gesperrte Seiten
3. Note that the interface is now in English
4. Browse elsewhere in the admin - the interface is now in German again

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.6.8
* Django version: 3.0.4
* Wagtail version: master (2.9a0)
* Browser version: Chrome 80.0.3987.132

**Comment by jacobtoppm** [comment]
Thanks for raising this! After testing, I believe this might actually be a problem common to views returning a `TemplateResponse`, which includes for example Collections views: the `require_admin_access` decorator we normally use to activate the language does not seem to be compatible with these. Forcing a render in the decorator worked when I tested, so this might work as a fix, or we might need to try a different translation approach - I intend to look into this a bit more.

**Comment by gasman** [comment]
Fixed in #5910
