### ISSUE TITLE
Rendering issue of FieldRowPanel inside MultiFieldPanel

### ISSUE THREAD

**Issue by jeromelebleu** [wagtail/wagtail#5904]
### Issue Summary

There is extra top-padding when rendering a FieldRowPanel inside a MultiFieldPanel in the admin - since #5707.

### Steps to Reproduce

Create a model with the following panels:
```python
panels = [
    MultiFieldPanel(
        [
            FieldRowPanel([
                FieldPanel('field1'),
                FieldPanel('field2'),
            ]),
            FieldPanel('field3'),
        ],
        heading="Collection of Fields"
    ),
]
```

### Technical details

* Python version: 3.7.6
* Django version: 3.0.4
* Wagtail version: 2.8

**Comment by lb-** [comment]
Merged in via #5905
