### ISSUE TITLE
Improve error validation UX on user account creation

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#5906]
I just spent ten minutes trying to figure out why it was saying that my password was too common over and over even though I was entering really long, random strings. 

When creating a new user in Wagtail settings, the process is as follows: 

1. Enter user details including password
2. click roles button
3. add user roles
4. click add user button 

Currently the content entered at step one doesn't get validated until step 4. This is particularly confusing because when you then update the content at step 1 (such as picking a more secure password) then click the roles button again, the original validation message still displays which makes it appear your update still has errors when it in fact will only validate again by clicking add user. I've added a video that hopefully explains this better than I can in words.

The simplest solution would be to validate on step 2  rather than step 4. 

[password-usability-issue.mov.zip](https://github.com/wagtail/wagtail/files/4376765/password-usability-issue.mov.zip)

**Comment by thibaudcolas** [comment]
This seems to me like a general problem in Wagtail which we would want to address with [Autosave](https://github.com/wagtail/roadmap/issues/24) (including auto-validation), rather than a change specifically to the user account form. Closing.
