### ISSUE TITLE
Page titles in the admin view show up in the preferred language of the last editor

### ISSUE THREAD

**Issue by TheoChevalier** [wagtail/wagtail#5908]
### Issue Summary

When using Wagtail in a different language, and after editing pages, all other users of the Wagtail instance will see the page titles in this language in the admin panel.

### Steps to Reproduce

1. Change your Wagtail language preferences to French from `account/language_preferences/`
2. Edit a CMS page that is translated in French (and has at least a translated title)

**Actual**: All CMS users will see the page title in French in the navigation tree

**Expected**: The page title is in English. Changing language preferences for one user shouldn’t impact other CMS users.

Here’s a screenshot from a colleague seeing the page title in French:
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/1068783/77499751-2ce5a100-6e10-11ea-8a8b-7407059cf720.png">

Note: We’re using `wagtail-modeltranslation` 0.10.7 for localization. It may be a `wagtail-modeltranslation` issue?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: No

### Technical details

* Python version: `3.7`.
* Django version:  `2.2.11`.
* Wagtail version: `2.6.3`.
* Browser version: Firefox Nightly 76

**Comment by gasman** [comment]
Hi @TheoChevalier - thanks for the report.
Wagtail itself does not have a concept of the language a specific is in, so this issue is indeed specific to wagtail-modeltranslation.
