### ISSUE TITLE
Let Developer(or Designer) can write theme for Wagtail admin

### ISSUE THREAD

**Issue by michael-yin** [wagtail/wagtail#5912]
I received similar feedback from my clients and I find it is hard to do it. Sometimes if the color scheme of admin is the same as the website, it would be awesome!

### Roadmap

I think maybe we can try to create a `dark theme` for Wagtail admin, so Wagtail admin can have two `theme` files and people would know how to make it happen.

### Some points

I already did a quick test in my local env and below are some notes which can help

The version I am checking is Wagtail 2.7(LTS)

1. Wagtail use `jQuery taggit` and the theme is a css file, so it is hard to customize it

2. For some React components (Richtext editor, Streamfield), it is not easy to customize the color.

**Comment by gasman** [comment]
Hi @michael-yin,
There's an existing issue for this open at #2943. Unfortunately this isn't a particularly easy thing to implement, since the branding colours are defined in SCSS variables and standard Wagtail installations don't include the toolchain for compiling these to CSS.
