### ISSUE TITLE
Document popup paginator BUG

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#5913]
# Issue Summary
When you have many documents in a "collection". And want to select a document in that collection on page 2 or higher then its unreachable. 
The paginator regresses to the general paginator.

### Steps to Reproduce

1. upload "many" documents
2. put "many" document under a collection
3. See bottom how many pages in collection if you see 1 of 2
4. Go to page 2 you will notice that the paginator suddenly is the root collection and will show page 1 of 10

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
It's kinda annoying bug. I haven't confirmed the bug yet in 2.8 but my guess is this will be still there.

### Technical details

* Python version: 3.7.
* Django version: 2.2
* Wagtail version: 2.7.1
* Browser version: latest chrome

**Comment by thibaudcolas** [comment]
Thank you for reporting this @onno-timmerman, I’ve merged #6529 which should address this, and the fix will be released in Wagtail 2.12 in February.
