### ISSUE TITLE
Draft preview doesn't show last <script> tags from template

### ISSUE THREAD

**Issue by Mrfuyu** [wagtail/wagtail#5916]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I found **no problem in the published view**, but if I open the preview of a draft the last `<script></script>` is not showing up in the source code.

### Steps to Reproduce

**Template: base.html**
![image](https://user-images.githubusercontent.com/14253537/77823391-22baef80-70fb-11ea-8d71-2fe96600df5e.png)

**Resulting source code in browser in draft preview**

**Chrome**
![image](https://user-images.githubusercontent.com/14253537/77823421-61e94080-70fb-11ea-825f-3b4ceb1fb5db.png)

**Firefox**
![image](https://user-images.githubusercontent.com/14253537/77823827-64996500-70fe-11ea-86a2-6afb2e60a421.png)

**Resulting source code in browser in normal published view**
![image](https://user-images.githubusercontent.com/14253537/77823484-c4424100-70fb-11ea-9c2e-bd60e726d6b0.png)

If I import the boostrap.js twice it works for the first one and the page can be loaded:
![image](https://user-images.githubusercontent.com/14253537/77823933-fef9a880-70fe-11ea-8b86-5967100d97cf.png)

### Technical details

* Python version: 3.7.4
* Django version: 3.0.4
* Wagtail version: 2.8

**Comment by thibaudcolas** [comment]
I would be surprised if this was a bug in Wagtail so will close this now 🤔 If our draft view ate people’s content I would assume others would have reported this by now.
