### ISSUE TITLE
Nested orderable inline panels have the same sort arrows as their orderable parent

### ISSUE THREAD

**Issue by mel-mason** [wagtail/wagtail#5919]
### Issue Summary

I have a page which displays a list of Carousels, grouped into CarouselGroups. Both models are Orderable, and are displayed using InlinePanels. When the edit page loads, each CarouselGroup has the correct sort arrows - just down for the first one, up/down for middle ones, and just up for the last one. But the list of Carousels under each CarouselGroup has the same set of arrows for each one in the list: just down for the Carousels under CarouselGroup 1, up/down for the Carousels under CarouselGroup2, etc. If I change the sort order for one of the Carousels, the arrows change to what they should be (i.e. down for the first, up/down for the middle ones, and up for the last).

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py as follows...
```
from django.db import models
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel
from wagtail.admin.edit_handlers import InlinePanel, FieldPanel

from wagtail.core.models import Page, Orderable


class HomePage(Page):
    content_panels = Page.content_panels + [
        InlinePanel('parent_panels', label="Parent panels")
    ]


class Parent(ClusterableModel, Orderable):
    page = ParentalKey(HomePage, related_name='parent_panels')
    title = models.TextField()
    panels = [
        FieldPanel('title'),
        InlinePanel('child_panels', label="Children", min_num=1)
    ]


class Child(Orderable, models.Model):
    title = models.TextField()
    page = ParentalKey(Parent,
                       on_delete=models.CASCADE,
                       related_name='child_panels')
    panels = [
        FieldPanel('title')
    ]
```
3. Edit the home page in the wagtail admin
3. Add a Parent panel and 3 child panels
4. Click save draft (or publish) - the 3 child panels will not have a sort arrow as the parent panel does not
5 . Add a second parent panel and 3 child panels
6. Save draft. The sort arrows in the first child list will all point down, and in the second will all point up
7. Click one of the child sort arrows. The arrows will now display correctly

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.6.7 and 3.6.9
* Django version: 3.0.4
* Wagtail version: 2.8
* Browser version: Firefox 74 on linux, Chrome 80 on windows, another browser on Mac

**Comment by sonnybaker** [comment]
Finding this is still the case in 5.2.1 (at least in Snippets) - the scope of the nested `InlinePanel` sort arrows seems to be hooked to the parent - is there a known workaround? Existing code below:

```
class AssessmentPractice(ClusterableModel, Orderable):

    title = models.CharField(
        null=False,
        blank=False,
        max_length=255,
    )

    panels = [
        FieldPanel('title'),
        InlinePanel('indicators'),
    ]

    def __str__(self):
        return self.title


class AssessmentIndicator(ClusterableModel, Orderable):
    title = models.CharField(
        null=False,
        blank=False,
        max_length=255,
    )
    practice = ParentalKey(
        AssessmentPractice,
        on_delete=models.CASCADE,
        related_name='indicators',
    )

    panels = [
        FieldPanel('title'),
        NestedInlinePanel('questions'),
    ]

    def __str__(self):
        return self.title


class AssessmentQuestion(ClusterableModel, Orderable):
    question = models.CharField(
        null=False,
        blank=False,
        max_length=255,
    )

    indicator = ParentalKey(
        AssessmentIndicator,
        on_delete=models.CASCADE,
        related_name='questions',
    )

    def __str__(self):
        return self.question


class AssessmentPracticeViewSet(SnippetViewSet):
    model = AssessmentPractice
    icon = "crosshairs"
    menu_label = "Assessment Practice"
    menu_name = "assessment-practice"
    menu_order = 300
    add_to_admin_menu = True


register_snippet(AssessmentPracticeViewSet)
```

**Comment by Ross-Clark** [comment]
I am having the same problem on 5.1.3

**Comment by hamadr** [comment]
Hello everyone,
I'm starting to work on that issue. I'll keep you in touch.
Cheers

**Comment by hamadr** [comment]
I opened a PR https://github.com/wagtail/wagtail/pull/11576. Feel free to review :)

**Comment by lb-** [comment]
Thanks @hamadr  - the PR you have looks good.

I am hopeful that long term we can avoid reliance on more and more complex ID/Selector matching in the future but for now I think it's a good solution.

---

Note for all - we have https://github.com/wagtail/wagtail/issues/7915 with a way forward to move InlinePanel to Stimulus, with better support for nesting and DOM events for added customisations and a robust baseline of unit tests for this critical component. Any feedback welcome on that issue or the initial PR https://github.com/wagtail/wagtail/pull/11633

**Comment by harrislapiroff** [comment]
For anyone who comes across this bug in the future but, like me, can't upgrade yet, here's a workaround that exposes the sort_order field for editors to manually edit instead of using the javascript controls:

```python
class WorkaroundOrderable(models.Model):
    """
    This is a drop-in replacement for Orderable that works around a bug in
    Wagtail <6.1. For more details on the bug, see:

    https://github.com/wagtail/wagtail/issues/5919

    Using this model disables the ordering javascript in the admin. You can
    manually expose the sort_order field in the admin by adding it to the
    `panels` attribute of the model as `FieldPanel('sort_order')`.

    TODO: Replace this with the standard Orderable model when we upgrade to
    Wagtail 6.1 or later.

    """
    sort_order = models.IntegerField(null=True, blank=True)

    class Meta:
        abstract = True
        ordering = ["sort_order"]


class PeoplePageOrderable(WorkaroundOrderable, ClusterableModel):
    heading = models.CharField(
        max_length=200,
        blank=True,
        help_text='Heading shown for a people section, e.g. Staff, Contributors.',
    )
    parent_page = ParentalKey('blog.PeoplePage', related_name='people_section')
    panels = [
        FieldPanel('heading'),
        FieldPanel('sort_order'),
        InlinePanel(
            'people',
            label='People'
        ),
    ]
```
