### ISSUE TITLE
Infinite scroll on image library

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#592]
Pagination makes comparison difficult and editors have to remember what page an image is on if they are browsing.

**Comment by rishabhDev2700** [comment]
Hey, I would like to give this issue a try. Can I please get some more details?

**Comment by gasman** [comment]
Given the age of this issue, and the fact that the images index has been through numerous design revisions since 2014 without this ever being brought up as an issue again, I don't think this is something we want to pursue. Thanks for raising it @rishabhDev2700!

**Comment by rishabhDev2700** [comment]
okay thanks
