### ISSUE TITLE
Admin localization Japanese language setting does not work

### ISSUE THREAD

**Issue by tanb** [wagtail/wagtail#5925]
![Screen Shot 2020-04-01 at 21 40 09](https://user-images.githubusercontent.com/291175/78138250-98a7b980-7461-11ea-894d-f29bab7046ce.png)

### Issue Summary
Hello. I am a Japanese person and have been using this framework, I think the Japanese translation is very good. However, while using wagtail==2.8, I noticed that the Japanese language setting does not work. Below, I have listed the problem, as well as a solution to fix it. 

It's a wrong locale name here [/wagtail/admin/localization.py#L25](https://github.com/wagtail/wagtail/blob/8c1a234f139cdd77dd20cce9ee087ec309709851/wagtail/admin/localization.py#L25)

I think It should be 'ja'.

### Steps to Reproduce

1. Open [http://localhost:8000/admin/account/language_preferences/](http://localhost:8000/admin/account/language_preferences/)
2. Select Japanese.

### Technical details

I checked Japanese translation is working itself if UserProfile.preferred_language is 'ja' as follows.

![Screen Shot 2020-04-01 at 21 41 20](https://user-images.githubusercontent.com/291175/78138277-a3624e80-7461-11ea-9d89-eb840c4186f0.png)

```
>>> from wagtail.users.models import UserProfile
>>> profile = UserProfile.objects.all()[0]
>>> profile.preferred_language
'jp'
>>> profile.preferred_language = 'ja'
>>> profile.save()
```

**Comment by gasman** [comment]
Thanks for the report @tanb! Now fixed in f06270345f95550fbf425173dc57cc3a8718fbb5.
