### ISSUE TITLE
Typo in translation file

### ISSUE THREAD

**Issue by toptalo** [wagtail/wagtail#5947]
In file `wagtail/admin/locale/ru/LC_MESSAGES/django.po` on line `361` should be "Воскресенье" instead of "Воскрксенье"

**Comment by zerolab** [comment]
Note: translations should be submitted to https://www.transifex.com/torchbox/wagtail/ so they can be kept in sync

This is outlined in the [README](https://github.com/wagtail/wagtail#contributing):
> We also welcome translations for Wagtail's interface. Translation work should be submitted through Transifex.

**Comment by toptalo** [comment]
Ok I make it! Please update it ASAP

**Comment by toptalo** [comment]
Any updates here?

**Comment by gasman** [comment]
@toptalo We always fetch new translations from Transifex when preparing a new Wagtail release (and sometimes more frequently, when there have been significant changes to text in the Wagtail code), so the fix will definitely be in the next release.
