### ISSUE TITLE
SymLink rather than Copy

### ISSUE THREAD

**Issue by AWinterman** [wagtail/wagtail#5951]
### Is your proposal related to a problem?

We have a use case where a single wagtail installation serves content for whitelabelled versions of our site. In other words, we have sites a.com and b.com that are both our product, which has homepage, z.com, a, b, and z have different CSS, and *some* different content and *some* common content.

Right now, we have been simply keeping common content at a single place in the tree at z.com, and allowing users to leave their whitelabelled experience to access that content, but that leads to some problems we really actually need to avoid, like having to explain the relationship between the different sites.

We're about to embark an alternative, where we copy common content from one site to the other, which is probably fine but has it's own maintainability concerns because we will inevitably have to update content.

### Describe the solution you'd like

We would like to be able to "SymLink" content from one site to another. Put another way, we would like to be able to make the same page tree available from multiple domains, with specific overrides. Put another way, we'd like to be able to make the same specific pages available at several different URLs.
### Describe alternatives you've considered

As mentioned above we have a) simple not solved this problem and b) used the existing copy functionality.

**Comment by allcaps** [comment]
Wagtail page tree, or rather tree beard, isn't designed to do what you want.

You might work around the issue by creating a content snippet to store the shared content:

```
from django.db import models

from wagtail.admin.edit_handlers import FieldPanel
from wagtail.snippets.models import register_snippet

@register_snippet
class Content(models.Model):
    text = models.CharField(max_length=255)
    ... # all other content that is displayed on a shared page.
    panels = [
        FieldPanel('text'),
    ]
```
And create a shared page type that you can add anywhere in your trees. Selecting the shared content.

```
from wagtail.snippets.edit_handlers import SnippetChooserPanel

class SharedPage(Page):
    content = models.ForeignKey(
        'demo.Content',
        on_delete=models.SET_NULL,
        related_name='+'
    )

    content_panels = Page.content_panels + [
        SnippetChooserPanel('content'),
    ]
```

This gives you:
- A single place to manage shared content (the snippet).
- The ability to put add the content at various places in the page trees (the SharedPage).
- Default Wagtail, so nothing special.

**Comment by thibaudcolas** [comment]
This sounds to me like it has likely been solved by [page aliases](https://docs.wagtail.io/en/latest/editor_manual/copying_aliasing_existing_pages.html#aliasing-pages), so I’ll close this now.
