### ISSUE TITLE
Integration JWT Authentication (for example django backend use drf jwt)

### ISSUE THREAD

**Issue by Allan-Nava** [wagtail/wagtail#5962]
### Is your proposal related to a problem?

Is not possible to integrate inside a wagtail an external authentication flow, like jwt ?

### Describe the solution you'd like

I'm trying to implement the frontend with wagtail and create a django api backend for the programmatically data like events etc

**Comment by gasman** [comment]
Hi @Allan-Nava,
Wagtail uses Django's standard authentication framework, so Django add-on packages such as [python-social-auth](https://github.com/python-social-auth/social-app-django) should work. See https://wagtail.io/blog/azure-ad-authentication/ for a description of this in use.
