### ISSUE TITLE
API router does not respect WAGTAIL_APPEND_SLASH setting

### ISSUE THREAD

**Issue by kmohrf** [wagtail/wagtail#5968]
### Issue Summary

The API router will append slashes whether the `WAGTAIL_APPEND_SLASH` is set to `True` or `False`. The behaviour is hardcoded in [`wagtail.api.v2.router.py`](https://github.com/wagtail/wagtail/blob/master/wagtail/api/v2/router.py#L72).

Changing the behaviour in the router might qualify as a breaking change, if the slash is just removed in case `WAGTAIL_APPEND_SLASH` is set to `False`. Right now clients are redirected from *endpoint_without_slash* to *endpoint_with_slash* with `WAGTAIL_APPEND_SLASH`, but that won’t happen automatically the other way around.

DRF has the `trailing_slash` argument for its router implementations so this might be a compromise to make the behaviour configurable while maintaining backwards compatibility until a breaking change is possible in the next (major?) version.

I’ll gladly submit a PR for a fix once we settled for a solution.

Thank you for your time!

### Steps to Reproduce

1. Follow the instructions [in the documentation](http://docs.wagtail.io/en/v2.8.1/advanced_topics/api/v2/configuration.html) to setup the API
2. Set `WAGTAIL_APPEND_SLASH` to `False` in settings
3. Start the dev server
3. Goto `/api/v2/pages` (which is immediately redirected to `/api/v2/pages/`.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.8.2
* Django version: 3.0.5
* Wagtail version: 2.8.1
* Browser version: Chromium 81

**Comment by kmohrf** [comment]
Unfortunately it’s not only the router that generates URLs with trailing slashes. When overriding the `get_urlpatterns` method of the Wagtail router I noticed that detail URLs will contain the object id as part of the basename so they started looking like `/api/images4/`. This is because the `get_urlpatterns` method of the `BaseAPIViewSet` class also hardcodes slashes at fixed positions.

**Comment by kmohrf** [comment]
Though unrelated to the REST API router: another documented interface that does not respect the `WAGTAIL_APPEND_SLASH` setting is the [`RoutablePageMixin`](https://docs.wagtail.io/en/latest/reference/contrib/routablepage.html#module-wagtail.contrib.routable_page.models). Both the `get_resolver` and `route` functions are based on the assumption that the slash is appended to URLs and ignore the `WAGTAIL_APPEND_SLASH` setting.

**Comment by shipskin** [comment]
I would really like to be able to configure slashes as well. Commenting for traction

**Comment by zerolab** [comment]
Hey @kmohrf, @shipskin,

If you have the time, a PR would be highly appreciated and help us push this forward.

**Comment by shipskin** [comment]
created a PR https://github.com/wagtail/wagtail/pull/7921

**Comment by kaedroho** [comment]
Unless there is a good reason for it, I'm against us making this change.

 - ``WAGTAIL_APPEND_SLASH`` is only supposed to apply to page URLs as these are what appear in a users browser and may be hand typed.
 - It doubles the amount of URLs we might have to cache and invalidate from a cache
 - It makes Wagtail implementations slightly different from one another making it more difficult to write a single client library that works across many Wagtail sites

**Comment by gasman** [comment]
This was separately proposed and rejected in #7421 - sorry for not catching this earlier.
