### ISSUE TITLE
Flyout menu isn't scrollable 

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#5980]
If you have more items in the flyout menu than visible vertical space it's not possible to scroll to hidden items. 

Video attached. 

[Wagtail-flyout.mov.zip](https://github.com/wagtail/wagtail/files/4517327/Wagtail-flyout.mov.zip)

**Comment by gasman** [comment]
Hi @tmsndrs,
This has been fixed in the forthcoming Wagtail 2.9 release - original report is #5358, PR is #5927.
