### ISSUE TITLE
Required fields in stream fields are not showing red asterisk after labels.

### ISSUE THREAD

**Issue by williamegomezo** [wagtail/wagtail#5983]
### Issue Summary

When a admin user is working with stream fields and struct blocks, the asterisk for the required fields is not being shown. This asterisk was shown in previous wagtail versions. It can be a specificity problem in the CSS due to markup has changed a little bit.

### Steps to Reproduce

1. Start a new project with `wagtail start mysite`
2. Edit models.py adding a StreamField, and create a model for StructBlock:

```
class Template(Page):
    body = StreamField([
          ('MyRichText', MyRichText()),
    ])

class MyRichText(StructBlock):
     text = RichTextBlock(required=True)
```

3. Run the server.

Actual:
![image (1)](https://user-images.githubusercontent.com/33497419/80228482-bad1c900-8614-11ea-8b63-c93ca7cd120e.png)

Expected:
![image (3)](https://user-images.githubusercontent.com/33497419/80228579-d341e380-8614-11ea-8ad8-3433a0ca967f.png)

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Python 3.7.6
* Django version: 2.2.11
* Wagtail version: 2.7.2
* Browser version: Chrome 80.

**Comment by mjlabe** [comment]
I was just going to report this. This is also in 2.8.1.
