### ISSUE TITLE
Gunicorn worker stops when using wagtail.core.middleware.SiteMiddleware and postgresql

### ISSUE THREAD

**Issue by wipoulou** [wagtail/wagtail#5984]
### Issue Summary

Gunicorn worker don't get responses when using wagtail and postgresql.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Setup allowed_hosts
3. Add the wagtail installed apps 
```
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',
    'wagtail.contrib.settings',
    'modelcluster',
    'taggit',
```
4. Add the middleware
```
    'wagtail.core.middleware.SiteMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
```
5. Setup Database
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PWD'),
        'HOST': os.environ.get('DB_IP'),
        'PORT': os.environ.get('DB_PORT'),
        'OPTIONS': {'sslmode': 'require', },
    }
}
```
Or I can do it even faster using wagtail start site
1. wagtail start site
2. 
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PWD'),
        'HOST': os.environ.get('DB_IP'),
        'PORT': os.environ.get('DB_PORT'),
        'OPTIONS': {'sslmode': 'require', },
    }
}
```
3. python manage.py migrate

Then try to serve the app with gunicorn: ```gunicorn mysite.wsgi:application --bind 0.0.0.0```
And there is a loop of booting worker and a "The connection was reset", or a crash on heroku, depending on how you try to deploy it.

### Technical details

* Python version: 3.6.9 and 3.7.6
* Django version: 3.0.5 and 2.2.12
* Wagtail version: 2.8.1 and 2.8.0
* Gunicorn version: 20.0.4 and 20.0.4

**Comment by wipoulou** [comment]
Looks like it's a bug with an other library that just need to be installed, not even called. Probably django-honeypot but I'm not sure about it.
Anyway I'm not sure there is a point in trying to get to the bottom of this bug.

**Comment by wipoulou** [comment]
After further testing, it looks like the problem came from 
```
numpy==1.18.3
opencv-python==4.2.0.34
```
Since the "feature detection" with those two libraries is in the docs, I'm reopening the issue.

**Comment by gasman** [comment]
Hi @wipoulou - please could you provide a set of steps that reproduces the problem, starting from a clean environment?

**Comment by wipoulou** [comment]
I haven't tested it from a fresh start in that exact setup yet, (although I've been struggling with this problem for days now) but it should be the same as my first comment, but you also install opencv-python and numpy.

So it would be :
* ```pip install wagtail opencv-python```
* ```wagtail start site```
* setup a postgresql database on a server (I used digital ocean)
* ```python manage migrate```
* ```gunicorn mysite.wsgi```
* Try to access your app, the worker should loop between exit and start

**Comment by gasman** [comment]
I'm unable to reproduce this with the following steps (from a clean virtualenv created with `mkvirtualenv gunicorntest --python=python3.7`):

    pip install wagtail opencv-python psycopg2 gunicorn
    wagtail start gunicorntest
    cd gunicorntest
    createdb gunicorntest

edit gunicorntest/settings/base.py to contain:

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'gunicorntest',
        }
    }

then

    ./manage.py migrate
    gunicorn gunicorntest.wsgi

After this, visiting http://localhost:8000/ succeeds with no issues.

**Comment by wipoulou** [comment]
Maybe it's because in my setup the database is on an other server. I just posted it in case someone has the same problem, so they don't have to struggle for days.
