### ISSUE TITLE
Cannot custom admin UI with hooks

### ISSUE THREAD

**Issue by github-yd** [wagtail/wagtail#5985]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I want to customize some pageeditor and streamfield editor styles in site admin. However after poking around I realized that their default style files are loaded AFTER `insert_global_admin_css` or `insert_editor_css` hook. Therefore any custom styles for pageeditor and streamfield editor are not respected, they're override by default styles instead.

### Steps to Reproduce

1. Add `insert_global_admin_css ` or `insert_editor_css` hook to an app `myapp` in `wagtail_hooks.py`, which both load 'static/mysite/mystyle.css'
2. Put the app name at the last of INSTALLED_APPS in `myapp/setting.py`
3. load admin page

my mystyle.css contains this style
```
.c-sf-block {
    background: #ddd8;
}
````
and this style is not respected in the browser (while other pure personal classes style work fine). When I dig deeper in browser I see this mystyle.css is actually loaded BEFORE 
`/static/wagtailadmin/css/layouts/page-editor.cs` and `/static/wagtailadmin/css/panels/draftail.css`

I would suggest that this behavior be overridden and allow the custom styles to be loaded AFTER any default styles.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no) yes

### Technical details

* changing order doesn't change when the hook get loaded, I tried order=100000 already
* I can set the style to `!important` to override default styles, but it's very cumbersome.
```
.c-sf-block {
    background: #ddd8 !important;
}
````

**Comment by gasman** [comment]
Hi @github-yd,
Thanks for the report - this is covered by #5955. (That one is currently closed, but I think it makes sense to keep the discussion on there)
