### ISSUE TITLE
CustomHandler is not hooked in StreamField RichTextBlock

### ISSUE THREAD

**Issue by Vibrat** [wagtail/wagtail#5988]
### Issue Summary

When creates a `Custom Embed Handler`, and insert into `wagtail_hooks.py`, the `wysiwyg` triggers new `Handler` when using `from wagtail.core.fields.RichTextField`  but not get called when using `StreamField wagtail.core.blocks.RichTextBlock`

### Steps to Reproduce

1. Register a wagtail hooks for image handler:

```python
## ImageHandler
import os
from wagtail.core.rich_text import EmbedHandler
from wagtail.images.models import Image
from django.conf import settings


class ImageHandler(EmbedHandler):
    identifier = 'image'

    @classmethod
    def expand_db_attributes(cls, attrs):
        STORAGE_ENGINE = os.environ.get("STORAGE_ENGINE", "")

        if STORAGE_ENGINE == "aws":
            CONTENT_STATIC_BASE_PATH = ""
        else:
            CONTENT_STATIC_BASE_PATH = getattr(
                settings, 'CONTENT_STATIC_BASE_PATH', "/")

        image = Image.objects.get(pk=attrs['id'])
        rendered_image = image.get_rendition(
            'fill-%sx%s' % (image.width, image.height))

        image_endpoint = CONTENT_STATIC_BASE_PATH + rendered_image.url
        response_format = '<p><img class="%s" src="%s" alt="%s" /></p>'
        return response_format % (
            attrs['format'],
            image_endpoint,
            attrs['alt'])
```

```python
from wagtail.core import hooks
from source.wysiwyg.image import ImageHandler


@hooks.register('register_rich_text_features', order=10)
def register_my_feature(features):
    features.register_embed_type(ImageHandler)
```

3. Go to RichTextField and adding a image. In RichTextBlock, the image should return as `<img ... />`, not default embed type `<embed />`

### Technical details

* Python version: `3.7.3`
* Django version: `>=2.2,<2.3`
* Wagtail version: `2.7.1`
* Browser version: `Chrome 81`

**Comment by gasman** [comment]
Hi @Vibrat,
I'm unable to replicate this issue as described. Starting from a fresh `wagtail start` project, I placed your two code snippets into `home/image.py` and `home/wagtail_hooks.py` (and changed the import in the latter to `from home.image import ImageHandler). I then made these additional changes:

home/models.py:
```
from django.db import models

from wagtail.core.models import Page
from wagtail.core.blocks import RichTextBlock
from wagtail.core.fields import RichTextField, StreamField
from wagtail.admin.edit_handlers import FieldPanel, StreamFieldPanel


class HomePage(Page):
    body1 = RichTextField(null=True, blank=True)
    body2 = StreamField([
        ('paragraph', RichTextBlock()),
    ], null=True, blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('body1'),
        StreamFieldPanel('body2'),
    ]
```

home/templates/home/home_page.html:
```
{% extends "base.html" %}
{% load static wagtailcore_tags %}

{% block body_class %}template-homepage{% endblock %}

{% block extra_css %}
{% endblock extra_css %}

{% block content %}
    <h1>{{ page.title }}</h1>

    {{ page.body1|richtext }}

    {% include_block page.body2 %}
{% endblock content %}
```

I then edited the homepage and added an image to both fields, which gave the resulting HTML:

```
<div class="rich-text"><p>Image in rich text field:</p><p></p><p><img class="fullwidth" src="//media/images/potato.2e16d0ba.fill-390x560.png" alt="potato" /></p><p></p></div>
<div class="block-paragraph"><div class="rich-text"><p>Image in rich text block:</p><p></p><p><img class="fullwidth" src="//media/images/potato.2e16d0ba.fill-390x560.png" alt="potato" /></p><p></p></div></div>
```

Here the image URLs are both broken as I don't have `CONTENT_STATIC_BASE_PATH` set to anything meaningful, but the rendering is consistent on both blocks. If you can provide working steps to reproduce the issue, I'll be happy to reopen and investigate further.

**Comment by Vibrat** [comment]
@gasman  

Thanks for helping us. 

The problem that i experienced is when calling [Page API](https://docs.wagtail.io/en/v2.1.1/advanced_topics/api/v2/usage.html#custom-page-fields-in-the-api), the `ImageHandler` is not getting hooked and images are returned as `embed` type, while the rendering into html working normally. 

Here is a sample response of page api after  using `ImageHandler`, my expectation is that page api should listen the `ImageHandler` and return something as `<p><img class="fullwidth" src="//media/images/potato.2e16d0ba.fill-390x560.png" alt="potato" /></p>`

**Endpoint**: `pages/?fields=*`
```json
{
    "id": 7,
    "meta": {
        "type": "support_article.SupportArticle",
        "detail_url": "http://localhost/en/api/v1/pages/7/",
        "html_url": "http://localhost/support-article-root/downloading-app/",
        "slug": "downloading-app",
        "show_in_menus": false,
        "seo_title": "",
        "search_description": "",
        "first_published_at": "2020-03-24T08:45:22.355000Z"
    },
    "title": "Downloading the app",
    "last_published_at": "2020-05-20T03:11:48.460151Z",
    "data_en": [
        {
            "type": "Section",
            "value": [
                {
                    "type": "paragraph",
                    "value": "<p></p><embed alt=\"news-article-3.png\" embedtype=\"image\" format=\"fullwidth\" id=\"20\"/><p></p>",
                    "id": "ab2cabf0-333c-425f-aa32-4acb48769306"
                }
            ],
            "id": "aed666aa-04ba-44f1-95cb-f8bd21a4d7e4"
        }
    ]
}
```

**Comment by gasman** [comment]
Thanks for the clarification - this is covered by #2695, and there are some suggested workarounds on that ticket.
