### ISSUE TITLE
Unresponsive rich text

### ISSUE THREAD

**Issue by neowenshun** [wagtail/wagtail#6005]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Hello i have been trying to make wagtail responsive for mobile platforms. However it has not been successful

### Steps to Reproduce

1. I am using vw to set the font size based on the viewports

It does not seem to do anything and is specific only to rich texts

**Comment by gasman** [comment]
There's not enough detail to handle this as a bug report, sorry. Additionally, Wagtail does not apply any styling to front-end pages, so it's highly unlikely that this is a Wagtail issue.
