### ISSUE TITLE
Documentation for adding reports should cover permission restrictions

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#6014]
The "Pages with unpublished changes" example on https://docs.wagtail.io/en/stable/advanced_topics/adding_reports.html uses `AdminOnlyMenuItem` to make the report only available to superusers, but there is no corresponding permission check for the report itself, so any logged-in user who knows the URL can still access it.

The example should be extended to cover setting up a permission restriction on the report view itself.

**Comment by gasman** [comment]
Wagtail provides a (currently undocumented) `PermissionCheckedMixin` in `wagtail.core.views.generic`. This is based around Wagtail's concept of permission policies, which map to model permissions - this would fit well for reports that are available to "anyone who can edit model X", but is probably over-complicated for a simple "superuser only" check.

It should be possible to add a basic is_superuser code to a report (or any other class-based view) by adding the following `dispatch` method, either directly or through a mixin class:

(NB currently untested)

    from wagtail.admin.auth import permission_denied

    class MyReport(ReportView):
        def dispatch(self, request, *args, **kwargs):
            if not self.request.user.is_superuser:
                return permission_denied(request)
            return super().dispatch(request, *args, **kwargs)

**Comment by gasman** [comment]
@Nazi-pikachu Yes, go for it!

**Comment by Nazi-pikachu** [comment]
Hi @gasman i have opened a PR, Can you please provide some feedback on it.

**Comment by gasman** [comment]
Completed in #9859
