### ISSUE TITLE
Add quick access to footer actions on editor pages

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#6020]
### Is your proposal related to a problem?

Currently on really long page edit views, the user has to scroll all the way to the bottom to see the footer on mobile devices.

This was added intentionally in #5946 to resolve issues where the footer content was sticky but took up a large part of the viewport on mobile devices.

Note: the footer contains primary page action buttons like save draft and preview.

### Proposed Solution

It would be great to have some quick way to get to the bottom of the page (e.g. an anchor link) that would be visible when the footer is not in view.

Maybe a circle button that sticks to the bottom right with a down arrow, this would appear only if you have at least one full height below you (i.e. cannot see the footer). Once you scroll down low enough, this link should not appear.

Accessibility needs to be considered, maybe this should sit in the DOM at the top of the edit page so if tabbing through it will be one of the earlier elements in focus.

Also, need to consider non-page edit views as others can have footer actions.

### Alternatives

We could leave this as is, it might not be an issue that is a big problem.

**Comment by thibaudcolas** [comment]
I believe this will be solved by #8673, which also helps with this for keyboard users.

**Comment by thibaudcolas** [comment]
Closing as per #8673.
