### ISSUE TITLE
generate_image_url does not use the MEDIA_URL setting

### ISSUE THREAD

**Issue by mwharrison** [wagtail/wagtail#6035]
### Issue Summary

When using the generate URL button on the image, it does not return the MEDIA_URL link. So for example, if you are using S3 with Wagtail, it doesn't work properly.

### Steps to Reproduce

1. Create a Wagtail site that uses S3 for storing media assets
2. Upload new image (with renditions enabled)
3. Click generate URL, notice the URL is incorrect.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7
* Django version: 3.0.4
* Wagtail version: 2.8.1
* Browser version: Not browser-specific. Confirmed in Chrome, Safari, and Firefox.

**Comment by kaedroho** [comment]
This is actually the intended behaviour. The generator is supposed to generate image URLs for external sites to reference. URLs to renditions on S3 tend to not be stable (you might later want to clear out renditions to save space, switch webhosts, or put it behind cloudfront).

The URL that's generated goes to a view served by Wagtail that will regenerate the rendition if it needs to, depending on how it's set up, this would then redirect to the rendition on S3 or serve it directly. A cache-control header is returned so the response can be easily cached using a cache server or CDN.
