### ISSUE TITLE
Pages disappearing after a merge

### ISSUE THREAD

**Issue by loleg** [wagtail/wagtail#6043]
I have not yet managed to isolate the problem in more detail, or do more research to see if people have experienced this problem - but it is an urgent issue for a customer so am posting it here. I'm not even sure if it's a bug or a missing feature.

### Issue Summary

Loading the dumped data into a new Wagtail instance from two separate sites, which had _completely separate_ page collections, results in some sub-pages mysteriously missing.

### Steps to Reproduce

I have not yet managed to reproduce this on a fresh instance. If someone wants a copy of my customer's data for testing, please contac tme directly.

### Technical details

* Tested on Python 3.7 and Wagtail 2.9

**Comment by jacobtoppm** [comment]
@loleg To clarify, you loaded dumped data from two completely separate Wagtail instances into one? If this is the case, this is likely because some pages have the same ids, so overwrite each other: you could use a solution like Wagtail Transfer (https://github.com/wagtail/wagtail-transfer) to work around these types of issues

**Comment by gasman** [comment]
@jacobtoppm beat me to it :-) Looking at the Django docs, it seems that loaddata is only really intended for populating an empty database with initial data. I don't think it would be feasible to support merging multiple data sets that way, particularly as Wagtail's page tree adds an extra level of complication (the internal `path` and `numchild` fields need to be set up to account for parent/child relations, and importing these from elsewhere is liable to produce inconsistent data). I reckon wagtail-transfer is indeed the way to go here.

**Comment by loleg** [comment]
Thanks a lot for the advice!

To be precise, one server's database was an extension of the other, not completely separate / divergent trees, but thanks for the pointer, I agree that Page ID creep is the most likely problem. Strange that this is not being detected in the import, e.g. through UNIQUE constraints.

I _still_ think there is an issue here, albeit a slightly different one that was originally posted: namely, that the current documentation makes no mention of Wagtail Transfer - which I'll need to dig into and learn more about - or `dumpdata`, for that matter, except in the section about fixtures, even though I find it a very versatile tool for maintenance & recovery.
