### ISSUE TITLE
Add Media Upload area or allow link to original file

### ISSUE THREAD

**Issue by josephkohlmaier** [wagtail/wagtail#6058]
Now that the `<video>` tag is more fully supported also by iOS and other mobile devices, it offers a lightweight approach to animation and film on websites, less expensive than gifs in many cases.

Currently, however, the only way to upload an mp4 file to Wagtail is by using the Documents area. But when you call the `{{ file.url }}`, Wagtail does not, in fact, deliver the original file. I am not sure what changes, but the mp4 file no longer plays in Safari (it does on other browsers) – whereas if I drop the file in to the static folder and call it from there, it plays without a problem.

Solution: add someting like a `{{ file.original }}` or similar selector; or add a media upload (i.e. Images, Documents, Media) that always honours the original file, unadulterated and with the correct headers, as that's what we need for sound and vision.

**Comment by gasman** [comment]
If I recall correctly, Safari requires media files to be served from a server that supports [range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests), which isn't the case for documents served through a Django view. If I recall correctly, you can get the direct link by using `{{ document.file.url }}` where `document` is the Document object, as opposed to `{{ document.url }}`.

As an alternative, you can use the [wagtailmedia](https://pypi.org/project/wagtailmedia/) package - there are no current plans to bring that into Wagtail core, although it's on our wishlist to standardise the internal APIs to make it easier to build subapps like wagtailmedia.
