### ISSUE TITLE
Automatic code formatting with Prettier

### ISSUE THREAD

**Issue by yhoiseth** [wagtail/wagtail#6059]
Extracted from #6056 where @thibaudcolas wrote:

> For reference, we’ve also discussed using Prettier as well (for JS, SCSS, Markdown, JSON, YAML). Here I think it’s just a matter of someone putting a small proposal together (in a new issue), and then making the change – we’re all in agreement we’d love to see this happen.

I’ll give it a go.

**Comment by yhoiseth** [comment]
Okay… I’m getting some mysterious CI failures in #6061. Going to try with a more incremental approach.

**Comment by gasman** [comment]
Those CI failures are from a separate ongoing issue - #6063

**Comment by yhoiseth** [comment]
@gasman I see. Thanks for letting me know 🙂

**Comment by thibaudcolas** [comment]
Hey @yhoiseth, just looking at your PRs – at this stage I think it’s too early to make PRs for this. As I said in my comment what we really need right now is a proposal so we can discuss what we want to do.

If we take the black DEP as a reference – I think what we need is just the [Reference implementation](https://github.com/django/deps/blob/master/accepted/0008-black.rst#reference-implementation), with details of the steps involved.

Here’s what to cover:

- How we should configure Prettier, based on our existing styleguide(s) and best practices
- Updating our ESLint and stylelint configurations to be compatible
- Formatting the code – how we do (personally I’d rather have this *not* done in the same PR as with the other changes, as it will make it go outdated all the time)
- Enforcement - where do we run Prettier in CI, and what changes do we need to make
- Documentation – where do we need to upgrade our code styleguide, and where do we need instructions on Prettier usage.

**Comment by yhoiseth** [comment]
Ah, I see. I should have read your comment more thoroughly. 

As a first step, I think it would be useful to know the _why_ here. What is insufficient about the current setup?

**Comment by thibaudcolas** [comment]
👍 I think we can pretty much paraphrase Django’s black DEP in this case, along with Prettier’s own "Why" https://prettier.io/docs/en/why-prettier.html.

**Comment by thibaudcolas** [comment]
Merged!

Here are the updated steps I would suggest to rebase existing PRs with the reformatting:

```
# Make a copy of your branch
git branch save/my-existing-branch my-existing-branch
# Make sure you have the latest `main` from Wagtail
git remote add upstream git@github.com:wagtail/wagtail.git
git checkout main
git pull upstream main
# Rebase your work onto the commit preceding the reformatting to resolve conflicts that would have been present anyway.
git checkout my-existing-branchqgb
git rebase af942a27e41b47e257b6cd46c01a13cd381fed04^1
# Install Prettier and other Wagtail development dependencies (make sure you use the correct version of Node)
node --version
npm --version
npm install 
# Test-run Prettier – this should show formatting errors.
npm run lint:format
# Rebase again, this time with the reformatting as the base,
# always preserving your changes in case of conflicts, and automatically reformatting with Prettier.
git rebase --strategy-option=theirs --exec '(npm run format || true) && git add . && git commit --amend --no-edit --no-verify' af942a27e41b47e257b6cd46c01a13cd381fed04
# Test-run Prettier – this should show no formatting errors.
npm run lint:format
# Finally rebase onto the latest version from Wagtail main, as per usual.
git rebase main
```
