### ISSUE TITLE
AbstractEmailForm and RoutablePageMixin did not work together

### ISSUE THREAD

**Issue by tombreit** [wagtail/wagtail#6062]
### Issue Summary

Trying to mix `AbstractEmailForm` and `RoutablePageMixin`  to provide a form and a custom route does not work - only one of these two functionalities does work.

### Steps to Reproduce

Add a page model with a _Form builder_-form and a (secondary) custom route

Depending on the order of inheritance:
``` python
class MyPage(AbstractEmailForm, RoutablePageMixin, Page):
    @route(r'^ics/$')
    def get_ics_for_event(self, request):
        return ical_response(
            events=self.get_events,
            filename='{}.ics'.format(self.slug)
        )
```
vs. 

``` python
class MyPage(RoutablePageMixin, AbstractEmailForm, Page):
    @route(r'^ics/$')
    def get_ics_for_event(self, request):
        return ical_response(
            events=self.get_events,
            filename='{}.ics'.format(self.slug)
        )
```
I get a form **or** my custom `@route`, but not both. 

I did not overwrite the default route and assumed to get both the form and the route working:

> By default a route for r'^$' exists, which serves the content exactly like a regular Page would. It can be overridden by using @route(r'^$') on any other method of the inheriting class.

_(from https://docs.wagtail.io/en/v2.9/reference/contrib/routablepage.html)_

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: 
sorry, not yet

### Technical details

* Python version: Python 3.8.3rc1
* Django version: Django               3.0.6
* Wagtail version: wagtail              2.9

**Comment by lb-** [comment]
@tombreit thanks for reporting this, I have been able to reproduce this issue, more context below.

* In the example above, the `Page` is not needed as `AbstractEmailForm` already extends `Page`.
* Hence, the only problem would be this scenario `class MyPage(RoutablePageMixin, AbstractEmailForm):`

Some rough notes:
* When `RoutablePageMixin` us added `route` uses the view from index `/` which returns without calling the super serve (which means the `form` is not provided to context). https://github.com/wagtail/wagtail/blob/2.9/wagtail/contrib/routable_page/models.py#L40
* `AbstractEmailForm` extends the `serve` method which means adding things to the context this way will never work when using the mixin. https://github.com/wagtail/wagtail/blob/2.9/wagtail/contrib/forms/models.py#L237
* This appears to be a problem with the `RoutablePageMixin` not using the `super().serve` method on the default/index route.
* I think the best way forward would be to revise `RoutablePageMixin` `index_route` method.

**Comment by tombreit** [comment]
Dear @lb- , thanks a lot for your prompt response. As I am not able to fix this, I temporarily swapped the `RoutablePageMixin` for a cutom `serve()` method (shameless copy of https://docs.wagtail.io/en/v2.9/reference/pages/model_recipes.html?highlight=route#overriding-the-serve-method)

With this implementation, I keep my ical export functionality and the `AbstractEmailForm` on my page class.

**Comment by gasman** [comment]
I don't think it's realistic to fix this. Wagtailforms and RoutablePageMixin are two different abstractions that have been built on top of Wagtail's `serve` mechanism, and there's no expectation for them to both work at the same time. If you need something that combines the functionality of both of them, you need to implement that yourself on top of `serve` (as you have done).

**Comment by lb-** [comment]
@gasman I actually have a patch for this drafted locally, I was just workings on unit tests and handling serve preview scenarios. 

I think this problem will be an issue for more than just abstract email form. In fact, any routable mixing added will ignore existing serve calls on the parent class. 

E.g. the AMP example in the docs would not work if used with routable mixin. Or this recipe - https://docs.wagtail.io/en/stable/reference/pages/model_recipes.html#overriding-the-serve-method

Plus, the routable page mixin already has handling of falling back to the parent serve method, which mostly works, except that the default index view does not use it. 

https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/routable_page/models.py#L121

Do you think I should still pursue this fix or not?

**Comment by gasman** [comment]
@lb- I'm happy to take a look if you have a working version, but I'm not convinced it's a good idea. The index view method is being called _from_ the `serve` method, so without additional hacks, calling `serve` from a view method will send things round in circles. Conceptually I don't think it really makes sense either - the purpose of RoutablePageMixin is to embed Django-style view functions into the page serve mechanism, so once you're inside one of those functions things should proceed as per a standard Django view (i.e. returning an HttpRespose via `render` or similar). Delegating that task back to Wagtail mechanisms such as `Page.serve` is mixing up different levels of abstraction.

As far as I can see the AMP example doesn't involve overriding `Page.serve`, only the top-level `serve` view, so it's unaffected by this. The "overriding the serve method" example will break, but I don't see that as a bug - it's demonstrating a low-level API that can be used to build things such as RoutablePageMixin.

**Comment by lb-** [comment]
@tombreit thanks for your issue submission, as per discussion on #6088 - we cannot really risk creating a code path that is too complex or hard to reason about.

I would love to see our contrib modules be compatible with each other but cannot think of a nicer way around this, if we split the Form logic into get_context/get_template parts, then our 'form processing' is happening in the seemingly wrong place.

Maybe we could resolve this with some docs on the forms side, I'll have a think and raise a new issue if I come with any ideas, if you have any more thoughts let us know.

For now, you can probably use the approach on that PR for your internal project.
