### ISSUE TITLE
Variation in success message of multiple upload of images and documents

### ISSUE THREAD

**Issue by mabdullahabid** [wagtail/wagtail#6064]
### Issue Summary

The multiple upload template and js files for image and document modules have different code for upload success. For images, when you upload an image, it displays a message and also shows a green success message bar at the top. However, for documents, it only displays a message but does not show a green success message bar at the top. I looked at the code for both and found that the documents template and js are missing the CSS class being appended to the code on the successful upload of a document as it is being done in images.

Wagtail 2.9

**Comment by marteinn** [comment]
Hi @mabdullahabid and thanks for filing an issue! I tried to recreate the issue but saw the green success text on the document uploader (see my screenshots below for comparison), could you provide screenshots? Thanks

![Screenshot 2020-05-24 at 06 45 57](https://user-images.githubusercontent.com/286534/82745953-7f005f80-9d8a-11ea-8b4f-f7f240153855.png)
![Screenshot 2020-05-24 at 06 45 46](https://user-images.githubusercontent.com/286534/82745955-80318c80-9d8a-11ea-8235-08fb857758c6.png)

**Comment by mabdullahabid** [comment]
Hi @marteinn ,

Thanks for responding. I am referring to the green success bar (django messages framework) that shows up at the top. It wouldn't be on the screens you have posted, rather the screen that is displayed after you click update. The screens you have displayed are good and exactly how they are supposed to be.

**Comment by marteinn** [comment]
Thanks for clarifying @mabdullahabid! Now I see, it seems like the documents view are missing the success message altogether. 

As it sounds like you have already done some research, would you be willing to submit a PR with a fix? If not, that's ok too :)

**Comment by paqman85** [comment]
I'd like to take over this one if there is no progress on it yet. I believe I found the code to fix the bug - just need to test.

**Comment by allcaps** [comment]
Go for it.

**Comment by paqman85** [comment]
I'm saving it for Hacktoberfest now. :D Thanks!

**Comment by kaedroho** [comment]
Fixed by #6427
