### ISSUE TITLE
Users should be able to configure API renderer_classes

### ISSUE THREAD

**Issue by narun4sk** [wagtail/wagtail#6066]
### Issue Summary

Users should be able to configure API `renderer_classes`, currently these are hardcoded to `[JSONRenderer, BrowsableAPIRenderer]`: https://github.com/wagtail/wagtail/blob/1958bba2476c32069acafd6837514749a4d3ceea/wagtail/api/v2/views.py#L26

### Steps to Reproduce

Configure pages endpoint as usual, but do not include `rest_framework` in the `INSTALLED_APPS`. Try to open configured endpoint in the browser, the app will throw an exception:

```
Internal Server Error: /rest/p/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 723, in render
    template = loader.get_template(self.template)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
```

### Technical details

- Python Version: 3.8.2
- Django Version: 3.0
- Wagtail Version: 2.9

---

Currently I'm using this nasty trick:

```
from django.conf import settings
from wagtail.api.v2.views import PagesAPIViewSet
from wagtail.api.v2.router import WagtailAPIRouter

if not settings.DEBUG:
    from rest_framework.renderers import JSONRenderer

    class ProdPagesAPIViewSet(PagesAPIViewSet):
        renderer_classes = [JSONRenderer]

    PagesAPIViewSet = ProdPagesAPIViewSet

# Create the router. "wagtailapi" is the URL namespace
api_router = WagtailAPIRouter("wagtailapi")

api_router.register_endpoint("p", PagesAPIViewSet)
```

**Comment by marteinn** [comment]
Thanks for filing an issue @narun4sk! How would you envision the api for setting “rendered_classes”? I think creating a subclass and overriding “rendered_classes” is the way you would do it in DRF as well.

**Comment by phptek** [comment]
I've been looking to do something very similar myself, without copy-pasting all the Wagtail page-specific renderer logic into a subclass. Tried with JSON+HAL last week using https://github.com/seebass/drf-hal-json/ but just couldn't get it to work.

I'm going to try with JSON:API next, but imagine I will encounter the same underlying modification problems (See: https://github.com/django-json-api/django-rest-framework-json-api). Maybe some docs that describe how developers might go about modifying the Wagtail-specific JSON format? That would help heaps :-)

**Comment by narun4sk** [comment]
@marteinn in DRF we have this luxury in `settings` like:

```
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}
```

IMO it's not too difficult to implement the same idea, isn't it? :thinking: 

Something like:

```
WAGTAIL_API = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}
```

Then if I don't like the defaults I would just set:

```
WAGTAIL_API["DEFAULT_RENDERER_CLASSES"] = ["rest_framework.renderers.JSONRenderer"]
```

**Comment by marteinn** [comment]
Many thanks @narun4sk and @phptek. This is a design decision so I will raise the issue with the core team, will report back here when we have discussed.

**Comment by m-aciek** [comment]
Hi, any updates on that?

It forces API users to enable DRF browsable API, otherwise there's an error raised, see https://stackoverflow.com/questions/61961099/wagtail-api-v2-django-template-exceptions-templatedoesnotexist.

**Comment by mdfathi99** [comment]
I have solved this issue. Here is the simple code in `api.py`
```
from rest_framework.renderers import JSONRenderer

...

class ProdPagesAPIViewSet(PagesAPIViewSet):
    renderer_classes = [JSONRenderer]
    name = "pages"

api_router.register_endpoint("pages", ProdPagesAPIViewSet)
```

**Comment by salty-ivy** [comment]
https://docs.wagtail.org/en/stable/advanced_topics/api/v2/configuration.html#
already states that we can subclass these APIViewSet classes
![image](https://user-images.githubusercontent.com/74553951/212752891-1948f340-232d-4676-b58c-3366c3123791.png)

although it, doesn't show how so i would just add a code snippet to show that
