### ISSUE TITLE
Accessibility issue for dropdowns in Wagtail Admin

### ISSUE THREAD

**Issue by rinti** [wagtail/wagtail#6072]
### Is your proposal related to a problem?

There are several places in the wagtail admin where dropdowns have no indicator they are dropdowns. Examples:

**Site settings:**
<img width="1203" alt="Screenshot 2020-05-26 at 14 03 06" src="https://user-images.githubusercontent.com/156781/82898887-5202a700-9f5a-11ea-84ce-c3716170ed52.png">

**Adding documents:**
![Screenshot 2020-07-19 at 19 57 02](https://user-images.githubusercontent.com/156781/87881549-4bdcf400-c9fa-11ea-8d59-310e246da2c0.png)

**Adding images:**
![Screenshot 2020-07-19 at 20 00 13](https://user-images.githubusercontent.com/156781/87881579-86df2780-c9fa-11ea-9717-41fb91bafaff.png)

### Describe the solution you'd like

Add an indicator that makes it clear it's a dropdown. Like for example here:
![Screenshot 2020-07-19 at 20 01 03](https://user-images.githubusercontent.com/156781/87881591-9a8a8e00-c9fa-11ea-9589-5c7b60097b02.png)

**Comment by allcaps** [comment]
Accessibility issues are labeled as bug because Wagtail aims to be WCAG2.1 AA.

**Comment by rinti** [comment]
I've revised the issue a bit since I found some more places where there's no indicator and a good example of how I think it should look like.
