### ISSUE TITLE
Integrate merge cells on TableBlock 

### ISSUE THREAD

**Issue by jkevingutierrez** [wagtail/wagtail#6074]
### Is your proposal related to a problem?

Handsontable provides an option to mergecells (https://handsontable.com/docs/6.2.2/demo-merged-cells.html).

Right now, if someone activates that option on Wagtail it allows the user to merge cells, but when you save and refresh the page, it shows the table as it was before merging the cells.

### Describe the solution you'd like

If the cells of the TableBlock are merged using the Handsontable mergeCells option, it should be reflected on the Admin and also on the template rendered.

**Comment by jkevingutierrez** [comment]
Duplicated of #5503

**Comment by aliceni** [comment]
I also have the same problem.
rolspan and rowspan are not stored actually.
