### ISSUE TITLE
InlinePanel message does not take max_num into account

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#6080]
### Issue Summary

The `InlinePanel` default message when using `min_num` does not take `max_num` into account.

### Steps to Reproduce

I'm using this inlinepanel:

```
        InlinePanel(
            'featured_pages',
            label='Featured',
            help_text='Choose two blog pages to feature',
            min_num=2,
            max_num=2,
        )
```

And after removing the stubbed empty fields on the CMS page, it reports this:

![](https://user-images.githubusercontent.com/2896608/82950268-dbfe4000-9f59-11ea-80a7-33a46d2191e0.png)

That should probably read `Please submit X forms` when `min_num` and `max_num` are the same value.

### Technical details

* Wagtail version: 2.8.2

**Comment by Pomax** [comment]
Also, if I leave the empty stubs in place, the message is wrong "the other way":

![image](https://user-images.githubusercontent.com/177243/83054862-ebd45d80-a007-11ea-9fd1-739bba8f620b.png)

where it now seems to not take `min_num` into account.

**Comment by meghanabhange** [comment]
Hi, can I take this up?

**Comment by gasman** [comment]
@meghanabhange Yes please!

**Comment by tomdyson** [comment]
Go for it @meghanabhange!

https://docs.wagtail.io/en/stable/contributing/developing.html is a good starting point, if you haven't seen it already. In particular, [vagrant-wagtail-develop](https://github.com/wagtail/vagrant-wagtail-develop) or [docker-wagtail-develop](https://github.com/wagtail/docker-wagtail-develop) are useful tools for getting a developer environment set up quickly. Alternatively there's the new browser-based [gitpod-wagtail-develop](https://github.com/wagtail/gitpod-wagtail-develop).

**Comment by meghanabhange** [comment]
So currently, this is what I’ve discovered -

This error actually is coming from Django formset and not Wagtail.

- What is happening here is that the validation of min and max is happening [here](https://github.com/django/django/blob/162765d6c3182e36095d29543e21b44b908625fc/django/forms/formsets.py#L341-L355) on Django's end where it's not checking for the case when `min_num` == `max_num` and when both validate_min and validate_max flag are set to true. 
- Wagtail passes min_num and max_num and the validation flags [here](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/edit_handlers.py#L673-L682) and when there is a `post` request made to `/admin/pages/62/edit/ `the formset creates a non_form_error which is read directly in [inline-panel-template](https://github.com/wagtail/wagtail/blob/3d7f2d090592beae373c227edc8a072cb3c1b3f2/wagtail/admin/templates/wagtailadmin/edit_handlers/inline_panel.html#L9) and then displayed.
- Ideal case, the fix could be in Django shown how the fix could be in Django in [this fork](https://github.com/meghanabhange/django/blob/validateminmax-fix/django/forms/formsets.py#L341-L353) (added another condition where Django is doing validation for min and max) but other than this I'm stuck and don't know how to fix this

**Comment by lb-** [comment]
Hey Megs, I agree wit Pomax, this is probably something that should be raised on the Django side.
I could not find any existing bug relating to this - https://code.djangoproject.com/search?q=min_num+max_num&noquickjump=1&changeset=on&milestone=on&ticket=on&wiki=on

There does not appear to be anything in the [Formset docs](https://docs.djangoproject.com/en/3.1/topics/forms/formsets/) that advise against setting `min_num` and `max_num`. There is a Stackoverflow question about [setting formsets to show exactly X forms](https://stackoverflow.com/questions/34846646/django-formset-creating-a-formset-of-just-one-form) and it recommends setting both.

**Comment by meghanabhange** [comment]
I have raised a [ticket on Django ticket tracker for this issue](https://code.djangoproject.com/ticket/32042) and submitted a [PR to resolve it as well](https://github.com/django/django/pull/13458)  
Once it gets accepted/reviewed this issue will be resolved ✨

**Comment by meghanabhange** [comment]
Update - The [PR is merged with Django](https://github.com/django/django/pull/13458#event-3812705424) ✨

**Comment by Pomax** [comment]
That's fantastic, thanks for your persistence, @meghanabhange!
