### ISSUE TITLE
Wagtail middleware (too) slow

### ISSUE THREAD

**Issue by velis74** [wagtail/wagtail#6082]
### Issue Summary

Takes 25 out of 33 milliseconds for a REST request that is not related to wagtail in any way

### Steps to Reproduce

1. include wagtail middleware in project settings, specifically RedirectMiddleware and SiteMiddleware
2. Watch your performance plummet (6ms for redirect & 19 for site)

I believe this is a bug for the following reasons: the middleware is fixed and gets executed for any request, regardless if it is needed or not. I would expect the objects produced in the middleware to be at least lazy ones. Also, the middleware executes for paths that do not concern it.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7.3
* Django version: 2.2.12
* Wagtail version: 2.8.1
* Browser version: curl 7.68.0

**Comment by gasman** [comment]
Hi @velis74 - thanks for the report.

This has been addressed in Wagtail 2.9 - SiteMiddleware has been deprecated and is disabled on new projects by default. https://docs.wagtail.io/en/stable/releases/2.9.html#sitemiddleware-and-request-site-deprecated

RedirectMiddleware immediately returns on non-404 responses, and any 404 URL could potentially have a Wagtail redirect associated with it, so I can't see any way to optimise this further - if you can point me to any specific thing that RedirectMiddleware is doing inefficiently, I'd be happy to investigate further. In any case, redirects are non-essential functionality and can be disabled by removing the middleware and INSTALLED_APPS entry if performance is a concern.
