### ISSUE TITLE
Broken image tags when image is changed with rendition caching enabled

### ISSUE THREAD

**Issue by pascalw** [wagtail/wagtail#6096]
### Issue Summary

With rendition caching enabled, changing an image results in broken image tags (old file paths remain cached).

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. [Enable rendition caching](https://docs.wagtail.io/en/v2.9/advanced_topics/performance.html?highlight=RENDITIONS#caching-image-renditions)
3. Edit home/models.py as follows
```python
from django.db import models

from wagtail.core.models import Page
from wagtail.images.edit_handlers import ImageChooserPanel


class HomePage(Page):
    image = models.ForeignKey(
        'wagtailimages.Image', on_delete=models.SET_NULL, related_name='+', null=True, blank=True
    )

    content_panels = Page.content_panels + [
        ImageChooserPanel('image')
    ]
```
4. Edit home/templates/home/home_page.html as follows
```html
{% extends "base.html" %}
{% load static wagtailimages_tags %}

{% block content %}
{% image page.image width-200 %}
{% endblock content %}
```
5. Open the page in the frontend, ensure the rendition is cached
6. Change the image in the Wagtail admin (Change image file)
7. Reload the page from step 5, a broken image tag is now rendered because an old image path is still cached

I would expect the cache to be cleared when the image is changed.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.8.2
* Django version: 3.0.5
* Wagtail version: 2.9.0

**Comment by pascalw** [comment]
Looking at the code this issue happens because the cache key only includes the `image id`, `filter.spec` and some other cache key (`Filter.get_cache_key`) that is based off the operations on the filter?

In any case, if the image is changed in any way (file change, focal point change) then the cache is not busted. One way to solve this would be to include the timestamp when the image was last changed in the cache key. Unfortunately the Wagtail image model currently doesn't track an updated timestamp.

**Comment by pascalw** [comment]
I looked into this some more. It seems that when the image (file) is changed, the renditions are destroyed. So instead of making the cache key more robust, an alternative could be to destroy the cached renditions using signals when they are removed. Now, this could still leave some other scenarios where the cache might go stale?

@tomdyson maybe you have some more insight into this?

**Comment by zerolab** [comment]
@pascalw thank you for outlining the issue (and testing cached renditions!)
IMHO, the rendition cache should be cleared when the image changes.

Would you be happy to submit a PR to speed things up?

**Comment by tomdyson** [comment]
Thank you very much for the report and investigations, @pascalw. I'm sorry for introducing this bug.

I think the cache key can be made robust enough by including the file hash, i.e.:

```python
# images/models.py, line 286
rendition_cache_key = "image-{}-{}-{}-{}".format(
    self.id,
    self.file_hash,
    cache_key,
    filter.spec
)
```

I've tested this successfully with file and focal point changes.

**Comment by pascalw** [comment]
@tomdyson no need to apologize for bugs! (https://blog.danslimmon.com/2019/08/02/stop-apologizing-for-bugs/)

I'm not sure though that adding the file_hash is a good solution. It indeed will work most of the time, but for example it doesn't in this case:

1. Upload an image
2. Make sure renditions are cached
3. Change the image (upload a new file)
4. Change the image back to the previous file
→ Cache is poisoned

Now granted, this is a bit of an edge case but it's annoying to recover from.
Also if in the future new attributes or functionality are added to Images or Renditions, new scenario's might be introduced where the cache is poisoned in a similar way.

What do you think about using signals to purge the cache when renditions are destroyed or updated? This seems pretty robust and cover all current and future cases, and we don't have to add a column to the image table.

```python
def post_delete_purge_cache(instance, **kwargs):
    transaction.on_commit(lambda: purge_rendition_cache(instance))

def register():
    Image = get_image_model()
    Rendition = Image.get_rendition_model()

    post_delete.connect(post_delete_purge_cache, sender=Rendition)
```

**Comment by gasman** [comment]
> I'm not sure though that only adding the `file_hash` to the cache key is a full solution. It indeed will work most of the time, but for example it doesn't in this case:
> 
> 1. Upload an image
> 2. Make sure renditions are cached
> 3. Change the image (upload a new file)
> 4. Change the image back to the previous file
>    → Cache is poisoned

@pascalw I'm not sure what you mean here. If you change the image back to the previous file, then `file_hash` will change back to the original value, and the rendition retrieved from the cache will be the one that was originally cached before the change of file - which is the correct one, isn't it?

**Comment by gasman** [comment]
Ah, now I see the problem - the rendition files are deleted when the image file is changed, so the cache returns a path to an image file that no longer exists (but _would_ have been the right image, if it still existed :-) ).

**Comment by pascalw** [comment]
@gasman exactly that's it: the files are deleted but the key will still be in the cache and thus point to an image that no longer exists.

**Comment by gasman** [comment]
PR created: #6183

(Followed @pascalw's suggestion, but left out the `on_commit`, as we want the cache purging to happen immediately if there's a sequence of lookups and updates inside a transaction - which is primarily an issue for unit tests, but could come up in 'real world' situations too...)
