### ISSUE TITLE
Hide a StreamBlock

### ISSUE THREAD

**Issue by gassan** [wagtail/wagtail#6103]
### Is your proposal related to a problem?

I would like to have a ToDo StreamBlock, thats will be shown under certain circumstances (for example only to an author) on frontend. I can do it, but I can not suppress the empty outer <div class="block-todo"/>

### Describe the solution you'd like

could wie have in _class BaseStreamBlock_ something like:
``` 
    def render_basic(self, value, context=None):
        return format_html_join(
            '\n', '<div class="block-{1}">{0}</div>',
            [
                (child.render(context=context), child.block_type)
                for child in value  *****if child.block ....*****
            ]
        )
```

**Comment by gasman** [comment]
Hi @gassan,
I think this would be a bad idea, sorry. It's an important design principle of StreamField that interactions between parent and child blocks are kept as simple as possible - a container block should not change its behaviour based on inspecting properties of a child block.

If you don't want the wrapper `<div>`s, you can easily provide your own rendering by defining a template for the StreamBlock, or just by looping over the StreamField value in your page template as in the second example under https://docs.wagtail.io/en/stable/topics/streamfield.html#template-rendering.

**Comment by gassan** [comment]
Probably not python conform - supress if child.render() returns None?
