### ISSUE TITLE
Prevent security vulnerabilities in JavaScript dependencies

### ISSUE THREAD

**Issue by yhoiseth** [wagtail/wagtail#6106]
### Is your proposal related to a problem?

Sometimes, security vulnerabilities in NPM packages Wagtail depends on are disclosed. We don’t currently have a working system to address such vulnerabilities. The lack of a working system can result in security vulnerabilities in Wagtail to go unpatched until someone happens to notice.

### Describe the solution you'd like

We can set up monitoring to, at a minimum, notify security@wagtail.io whenever a relevant vulnerability is disclosed. It would also be nice if the monitoring service automatically created pull requests.

My impression is that [GitHub Dependabot](https://help.github.com/en/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates) is a good choice.

#### Alternative monitoring services

There are multiple alternatives to GitHub Dependabot, such as [Snyk](https://snyk.io/) and [Libraries.io](https://libraries.io/). For more, see [_Dependency Monitoring_ on Stackshare](https://stackshare.io/dependency-monitoring).

#### Continuous integration

As an alternative, we can set CI to fail if `npm audit` discovers security vulnerabilities. However, that will probably cause annoyance and delays for core members and contributors when builds suddenly start failing.

### Additional context

I haven’t actually tried any of the mentioned services, so I’m not very confident in my recommendation.

**Comment by yhoiseth** [comment]
Dependabot seems to have been automatically configured for an issue reproduction repository I created recently. [This pull request](https://github.com/yhoiseth/wagtail-elasticsearch-7.7.0/pull/1) provides an example of a security fix suggested by Dependabot.

**Comment by thibaudcolas** [comment]
I believe we do have Dependabot doing this so I’ll close this now.
