### ISSUE TITLE
Resizing doesn't work on TableBlock

### ISSUE THREAD

**Issue by jkevingutierrez** [wagtail/wagtail#6112]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Handsontable provides the ability to resize rows and columns:

https://handsontable.com/docs/6.2.2/demo-resizing.html

When setting the values to True I get the functionality of resizing cells and columns. It works as expected, but, all resizes made got lost when I saved the page.
 

### Steps to Reproduce

1. Start a new project
2. Add a TableBlock
3. Use a config like the next in the Table block:

```
table_options = {
        'colHeaders': True,
        'rowHeaders': True,
        'manualColumnResize': True,
        'manualRowResize': True,
    }
```
4. Resize some cells and columns
5. Save and refresh the page

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Run `python --version`. Python 3.7.7
* Django version: 3.0.7
* Wagtail version: 2.9
* Browser version: Chrome 83.

**Comment by gasman** [comment]
Hi @jkevingutierrez,
This is out of scope for what TableBlock is designed for - it's only intended to be a way of inputting tabular data. It's not meant to be a full-featured spreadsheet UI, even if that functionality exists in the underlying handsontable library.
