### ISSUE TITLE
Document chooser’s "Search" tab broken after a failed upload

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#6126]
### Issue Summary

The document chooser has two separate tabs: "Search" to select existing documents, and "Upload" to create a new document. If the user goes to the upload tab and encounters a validation error, then moves back to Search, the tab is partially broken:

![document-chooser-bypass](https://user-images.githubusercontent.com/877585/84029845-f9d09980-a98a-11ea-964b-2671d98eb5ca.gif)

- The search form disappeared
- Collections filtering disappeared
- Pagination no longer works – all of the site’s documents are displayed at once (on larger sites with hundreds of documents this might make the upload form validation response take a lot of time)
- Documents are displayed without having been processed by the [`construct_document_chooser_queryset` hook](https://docs.wagtail.io/en/v2.9/reference/hooks.html#construct-document-chooser-queryset)
- We’re also missing a few more things that are cosmetic only (`documents_exist`, `is_searching`)

This is due to the chooser’s implementation which always has to re-create all tabs whenever interacting with either of the tabs. The upload view’s "failed validation" response does not correctly set the template context for all of the above to work:

https://github.com/wagtail/wagtail/blob/6e9bcef5db84d254686811b27fee0bf8c0210f9a/wagtail/documents/views/chooser.py#L154-L160

### Steps to Reproduce

1. On any Wagtail site, open the document chooser. See what’s displayed in the "Search" tab.
2. Switch to the Upload tab
3. Submit, receiving a validation error
4. Switch to the Search tab

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Wagtail version: v2.7.1 and v2.9

---

## Security considerations & suggested solution

There are security implications due to bypassing `construct_document_chooser_queryset` – this makes it possible for a malicious user to see all documents on a given Wagtail instance, even if otherwise set up with collection-level permissions and the queryset hook to restrict this for the choosers as well. Discussing this with @gasman, the hook doesn’t come with particular security guarantees so this is only tracked as a bug rather than "security vulnerability".

In an ideal world we would change the choosers’ API to only re-render separate tabs rather than the whole modal. Practically, fixing the existing implementation is a matter of replicating processing done in the main chooser view in the `upload` view:

https://github.com/wagtail/wagtail/blob/6e9bcef5db84d254686811b27fee0bf8c0210f9a/wagtail/documents/views/chooser.py#L54-L58

and 

https://github.com/wagtail/wagtail/blob/6e9bcef5db84d254686811b27fee0bf8c0210f9a/wagtail/documents/views/chooser.py#L91-L111

Similar changes have been done to the images’ chooser view (which had the same issues, but had been fixed) – so it might be worth borrowing the image chooser’s implementation, and tests

- https://github.com/wagtail/wagtail/blob/6e9bcef5db84d254686811b27fee0bf8c0210f9a/wagtail/images/views/chooser.py
- https://github.com/wagtail/wagtail/issues/4548
- https://github.com/wagtail/wagtail/pull/4553
- https://github.com/wagtail/wagtail/commit/cd0f8381cddb875172d15bc904fca5ebeadc43fe

**Comment by gasman** [comment]
Looks like this has been fixed as part of the chooser refactoring in 4.0, most likely in #8776.
