### ISSUE TITLE
Dynamic image serve view’s signature check is vulnerable to timing attacks

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#6127]
### Issue Summary

The [Dynamic image serve view](https://docs.wagtail.io/en/stable/advanced_topics/images/image_serve_view.html) is a way to dynamically generate image renditions by providing an image id and a rendition format string (e.g. `fill-100x100`). Renditions can be computationally expensive to create, and take up disk space, so this API endpoint is protected with a signature check to prevent abuse – however the implementation is vulnerable to a timing attack, due to not using a constant-time comparison function:

https://github.com/wagtail/wagtail/blob/301d1bc7f52fffc18b8cb34fbde01633bc1599ee/wagtail/images/views/serve.py#L37

The implications are that:

1. An attacker can try to overwhelm the server by relying on a timing attack to bypass this check and create arbitrary renditions.
2. An attacker can use the fact that images are queried by id to list all of the site’s images. This is because ids are numerical, auto-incremented, so you can just query id 1, 2, 3, etc.

### Steps to Reproduce

I’ve only investigated this by looking at the code. If someone wanted to try this out, they’d need to make a timing attack on a site that has this view set up (it’s opt-in).

---

### Security implications & solution

Point 1. feels rather hypothetical – by nature timing attacks on the web rely on making a high number of requests, which already have [DoS](https://en.wikipedia.org/wiki/Denial-of-service_attack) potential on their own, without having to create any renditions. Creating renditions consumes disk space – this might be more problematic, but feels relatively far-fetched.

The second "enumeration vulnerability" point feels more concerning, but talking to @gasman we agreed that Wagtail doesn’t make particular guarantees that images are private (accessing an image is just a matter of "guessing" its public URL), so this doesn’t feel like it’s worth handling as a security vulnerability – hence why I made this public issue.

The fix for both of those issues is to use a constant-time comparison function, like https://github.com/wagtail/wagtail/commit/3c030490ed575bb9cd01dfb3a890477dcaeb2edf did for password-protected pages with Django’s `constant_time_compare`.

**Comment by RealOrangeOne** [comment]
Because image signatures are verified before requesting the image, an attacker doesn't know whether the signature is invalid because the signature is invalid or because the image id is invalid. They'd need a valid signature to enumerate files with this view, after which all bets are off security wise.

A potential belt-and-braces approach to this would be to make "unknown image" and "invalid signature" responses look the same.

The timing issue is fixed in #10589.
