### ISSUE TITLE
small bug with WAGTAIL_USAGE_COUNT_ENABLED = True

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#6135]
### Issue Summary

Using WAGTAIL_USAGE_COUNT_ENABLED = True
Gives some wrong results if you use it with streamfields. The document chooser show 0 while the document is used in some streamfield block.

If it's not correct a user could be under the impression the document is not used.

### Steps to Reproduce

1. enable WAGTAIL_USAGE_COUNT_ENABLED = True
2. add document to streamfield
3. look if usage go's up

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: ( no) (but nearly fresh)

### Technical details
* Python version: Run `python --3.8`.
* Django version: 3.0.7
* Wagtail version: 2.9

**Comment by gasman** [comment]
Hi @onno-timmerman,
This is a documented limitation, mentioned under https://docs.wagtail.io/en/stable/reference/settings.html#usage-for-images-documents-and-snippets. An improved method is currently in progress, at #4702.
