### ISSUE TITLE
Images in rich text have oversized image icon (SVG regression)

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#6142]
### Issue Summary

On current master, inserting an image into rich text results in an oversized image icon:
![Screenshot 2020-06-11 at 22 46 58](https://user-images.githubusercontent.com/85097/84445127-39251180-ac3b-11ea-9926-5c087a57a6a1.png)

This seems to have been introduced by the SVG icon update - eed16e00348c6ddfe8f997e1150006a3211a1216

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes (on fresh bakerydemo instance)

### Technical details

* Python version: 3.6.9
* Django version: 3.0.7
* Wagtail version: 2.10a0 (master)
* Browser version: Chrome 83

**Comment by zerolab** [comment]
I was thinking of making svg.icon have some defaults ([like 1em width/height](https://github.com/wagtail/wagtail/pull/6121#discussion_r437291284)), but that will need further amendments (e.g. to the menu item icons)

Currently you have the same issue pretty much anywhere you add a new svg icon that hasn't had a specific style defined

**Comment by zerolab** [comment]
the quick and dirty fix would be

```scss
.MediaBlock__icon-wrapper .icon {
    width: 1.5em;
    height: 1.5em;
}
```

**Comment by allcaps** [comment]
> I was thinking of making svg.icon have some defaults ([like 1em width/height](https://github.com/wagtail/wagtail/pull/6121#discussion_r437291284)), but that will need further amendments (e.g. to the menu item icons)
> 
> Currently you have the same issue pretty much anywhere you add a new svg icon that hasn't had a specific style defined

@zerolab This is a question of style (pun intended).

Creating a default style and overriding it in specific cases scatters the definition and is therefore more fragile and harder to maintain. The cascading part of CSS is often it's weakness. The more BEM style approach with specific class names that do not use cascading, isolates, gives more control and is easier to maintain. Yet using the SCSS mixin keeps it dry and explicit.

The font icon only required a class name and a centralised icon style definition made sense. The SVG icons add a HTML tag inline, keeping the styling coupled to the UI element the icon belongs too makes sense too.

I guess you would be right if the majority of the situations would require the same style. As far as I can see every situation is a little bit different. There is no to true default.

The SVG icon and font icon implementations are both supported and should never collide.

I also like it when an icon obviously failsvto render correctly. Like is happening with the regression. It is a clear signal that styling is missing. Having a default makes that less obvious and easier to miss.

The menu item icons maybe should use the mixin too.

**Comment by zerolab** [comment]
Good arguments against a default, @allcaps. Especially the obvious fail to render part.

We do have some modifiers (such as `.bicolor` or `.text-replace` that don't follow BEM, but are widely used. In that vein I would propose we add modifier for the most common sizes (1em and 1.5em) -- it is easier to add a class than fiddle with the stylesheet. And it will make it easier for anyone providing their own admin templates to add icons without the need for extra CSS.

**Comment by zerolab** [comment]
The issues here stems from the fact that the MediaBlock icon doesn't not get the proper `MediaBlock__icon` class

We have the style for it https://github.com/wagtail/wagtail/blob/master/client/src/components/Draftail/blocks/MediaBlock.scss#L19

The MediaBlock component passes it https://github.com/wagtail/wagtail/blob/master/client/src/components/Draftail/blocks/MediaBlock.js#L91, but it doesn't get picked up in https://github.com/wagtail/wagtail/blob/master/client/src/components/Icon/Icon.js#L9

/me needs to brush up React knowldge to untangle this.
