### ISSUE TITLE
Currently not possible for a user to change their own email address, username, first or last name

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#615]
Ideally rather than having a separate form containing just the password fields at `/admin/account/change_password/`, it should be possible for users to edit their own account by being taken directly to the normal edit page for their account (with a few fields hidden as appropriate, such as their active state and group allocation)

**Comment by kevinhowbrook** [comment]
Things have moved on a lot since this issue, but I have added a PR to allow users to change their first and last name:

https://github.com/wagtail/wagtail/pull/5425

**Comment by lb-** [comment]
Fixed in PR #5425  & merged in via https://github.com/wagtail/wagtail/commit/31e3dab4ec3ddad9d18e342df206ca7dcc925e8f
