### ISSUE TITLE
Drag and drop for ListBlock in StreamField

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#6150]
### Is your proposal related to a problem?
I made a site that has many items. It uses inline Orderable and on some other page streamfields with ListBlocks.
Some pages have over 40 items. The problem when you add an item you add it to the bottom. However the user might want it to have the item at the top list. This would force the user to click 39 times the arrow up button.

The same problem is you have in the streamfield ListBlock. An item can be added to the end of a list but not at the beginning. Again the user has rather large lists like 20 to 30 items.

### Describe the solution you'd like
Besides the up and down arrow it would be nice to have a clear arrow to move an item to the top of the list. Or simple drag and drop to order your list.

### Describe alternatives you've considered
Currently I'm considering my options to make it more user friendly.

**Comment by thibaudcolas** [comment]
We’ve considered this as part of the [page editor 2022](https://github.com/wagtail/wagtail/discussions/7739) redesign – at this stage we’d suggest doing this with drag'n'drop capability, but don’t intend to implement this this time around.

**Comment by zerolab** [comment]
#1033 is related (in that it is for `StreamField`s in general)

**Comment by thibaudcolas** [comment]
I’m going to close this in favour of #1033. At this stage if we implemented drag-and-drop it would most likely be for all of StreamField, and most likely InlinePanel at the same time (everything that can be ordered).
