### ISSUE TITLE
Snippets to be more reusable/extendable idea

### ISSUE THREAD

**Issue by Quadric** [wagtail/wagtail#6154]
### Is your proposal related to a problem?

this sentence fits perfectly to my problem: "I'm always frustrated when..."

I really like the idea of "Snippets" as a "container" for instances of different types of models grouped together in a one list - but for me it's not enough. I need to have many "snippet like" groups in my menu... for example i have a dedicated 1:1 copy of snippets for "calculators" where different parts of system and different "plugin like" apps may register it's own calculator. And another case. i have a 1:1 copy of snippets for "layouts" where different parts of system and different "plugin like" apps may register it's own layout.... and so on... I've renamed "snippet" word to "calculator" and "layout" and i have a dedicated "register_calculator" and "register_layout"  decorators...

I can't have all this "snippet like" models in this in a one "Snippets" list because it's impractical and unreadable. 

Why i did a 1:1 copy? Because "snippets" was not created with this kind of extensibility in mind - so making a similar functionality without copying almost anything is impossible. Of course copying snippets 1:1 everytime is a total madness so i'd like to find another solution.

### Describe the solution you'd like

I'd like to have a simple or at least DRY solution to make a separate group of "snippet like" models which i can register in a menu. So i'd like to have a separate group of snippets for "calculators", "layouts" and so on.

How to achieve that? There are some ideas to consider:

1) Make additional level in url and snippets implementation to have some "groups", so without changing "register_snippet" decorator it may allow for param: "group", so for example:

```python
@register_snippet
class StandardSnippet:
    pass

@register_snippet('calculators')
class CalculatorType1:
    pass

@register_snippet('layouts')
class LayoutType1:
    pass
```

2) Make additional "level" of `SNIPPET_MODELS` form file `wagtail/snippets/models.py` constant to have been splitted into groups which for default of snippets will be in "default" group. Then i could be easy to create own decorator which may register to a different "list" of snippet models. For example it may look like this:

```python
def register_snippet(model, group="default"):
    if model not in SNIPPET_MODELS[group]:
        model.get_usage = get_object_usage
        model.usage_url = get_snippet_usage_url
        SNIPPET_MODELS[group].append(model)
        SNIPPET_MODELS[group].sort(key=lambda x: x._meta.verbose_name)

        @checks.register('panels')
        def modeladmin_model_check(app_configs, **kwargs):
            errors = check_panels_in_model(model, 'snippets')
            return errors

    return model
```

so to create a dedicated decorator we may change only a "group" from default to something else
```python
def register_calculator(model):
   return register_snippet(model, 'calculators')
```

3) We need to have this "other snippet" list registered somewhere in menu. I believe this should be as easy as registering modeladmin in wagtail_hooks - but currently i have no idea for that.

4) Choosing "snippets" from panels and streamfields: that's a different story:

I've tried not to copy 1:1 everything from snippets for at least eliminating a "chooser" views from snippets and use some 3rd party app for choosing model instances.

I've tried so far:
 - https://github.com/neon-jungle/wagtailmodelchooser
It's ok but it has a simple "chooser" interface which need to be extended for thing which we have on snippets "for free"

 - https://github.com/ixc/wagtail-instance-selector
Different approach by "iframing" internal admin views of instance list - so we have a full functionality but it has a caveat for X_FRAME_OPTIONS must be set to SAMEORIGIN which may be not acceptable for some projects.

### Summarizing:
I don't have a clear idea/solution for how to achieve that. I think this could be useful in many cases. As Wagtail is able to "register" menu elements and "group menu" elements which gives us a 1 and 2 levels of menu but this solution may give as a some kind of "3rd" level system organization which is useful for very complex systems.

### Clearly:
I'd like to have this kind of "snippets" idea for just more than one issue in my system. If extending idea for snippets is not a good solution maybe there is some "ready to go" 3rd party apps for Wagtail which act's like snippets but are repeatable. I didn't found anything on net...

Many thanks to the authors and the whole Wagtail community. This is one of the greatest software i've been working at so far.

**Comment by thibaudcolas** [comment]
I’m going to close this in favour of #8609 – I believe this is largely the same idea, and it’s better for us if we have large discussions like this over in GitHub Discussions threads.
