### ISSUE TITLE
do not translate anchors in tab links

### ISSUE THREAD

**Issue by JanMalte** [wagtail/wagtail#6165]
translating the tab links makes it much more complicated to create links from the outside to a specific edit page tab

https://github.com/wagtail/wagtail/blob/4349c6c4dd150e07b88cbdacad206d671edc5d44/wagtail/admin/templates/wagtailadmin/edit_handlers/tabbed_interface.html#L5
https://github.com/wagtail/wagtail/blob/4349c6c4dd150e07b88cbdacad206d671edc5d44/wagtail/admin/templates/wagtailadmin/edit_handlers/tabbed_interface.html#L12

**Comment by thibaudcolas** [comment]
Hi @JanMalte, we’re reworking the tabs currently in #8266 so I’m reviewing opened issues. I’m having trouble understanding what you’re reporting here, could you please follow our bug report template and provide more informations?

**Comment by JanMalte** [comment]
@thibaudcolas the HTML element ID is using a slugified string from the tab `heading`. As the `heading` is translated into the users language, the ID may very depding on the language. Using a untranslated slugify string would be better.

**Comment by thibaudcolas** [comment]
👍  not sure I’d agree it’s a bad thing, but if you want to suggest a change to this please create a new issue (or update this one) following our template: https://github.com/wagtail/wagtail/blob/main/.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
