### ISSUE TITLE
Drop support for IE11

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#6170]
This is a tracking issue to discuss what it would look like for Wagtail to drop its support for IE11. 

Edit: [November 2020 update](https://github.com/wagtail/wagtail/issues/6170#issuecomment-722665899). **We are now through the process of gradually removing support for IE11**.

Edit: [September 2020 update](https://github.com/wagtail/wagtail/issues/6170#issuecomment-693523810). As of September 2020, we intend to gradually remove support for IE11 over the coming Wagtail releases. If this is something you rely on we would love to hear from you.

~**As of June 2020 there are no short-term plans to remove support, but if this is something you rely on we would love to hear from you.**~

This is prompted by a similar change to the Django admin – view [Django 3.1’s release notes](https://docs.djangoproject.com/en/3.1/releases/3.1/#contrib-admin-browser-support). Although I assume the Django admin might still work mostly as expected in IE11, it’s a good milestone for us to pay attention to, and feels like a good time for us to start planning for this in Wagtail.

**Particularly, it would be great to hear from people who do rely on IE11 in their organisation**, as the cost of supporting IE11 is pretty clear, while the benefits aren’t always so apparent. If you’re in this situation please take a moment to describe your situation – which Wagtail version you’re using, why you’re still using IE11, whether there are alternatives available, and what’s your plan with other suppliers/technologies dropping support.

---

### Known bugs

- #5914
- #5903
- #5297
- Some of #4274
- #6447

### Potential improvements

- #6107 some of the implementation options would require more work for IE11 support
- #1240 could switch to logical properties for RTL styles
- #2943 could start using CSS variables for easy theming
- #6130 could remove `.woff` font files 
- #3804 Would speed up code reviews
- #6059 We might be able to set up Prettier on the whole codebase, with ES2017 function parameter trailing commas for un-compiled code too.
- #5015 could use CSS grid and flexbox as part of our refactoring.
- Could reduce our static files’ size by switching to compiling JS for only the browser support we need.
- Could start loading Wagtail’s JS code as ES modules, with asynchronous loading, without having to polyfill / compile this.
- JS polyfills we include are only needed for IE11 support
- We could likely remove Modernizr (might be able to do this already regardless)

### Tech debt cleanup

- [GitHub search for "IE11"](https://github.com/wagtail/wagtail/search?q=IE11&unscoped_q=IE11)
- Remove legacy IE conditional comments (can do this regardless)

---

## IE11 market share

As of May 2020, IE has a 1.4% market share in Europe according to [statcounter’s data](https://gs.statcounter.com/browser-market-share/all/europe#monthly-201905-202005). [caniuse’s usage table](https://caniuse.com/usage-table) has IE11 at 1.42% globally (same underlying data source). Update September 2020: 1.2% Update February 2021: 0.7%.

**Comment by thibaudcolas** [comment]
We’ve discussed this on today’s team meeting, there is some general agreement that we want this to be a gradual change and not unnecessarily break features as much as possible – but still drop support as a general policy, so we will be able to no longer support IE11 in a "breaking" way when appropriate.

For now, the plan is to:

- In Wagtail 2.11 (LTS), introduce an admin-only, IE11-only warning message on the Wagtail dashboard, alongside the existing upgrade notification.
- In Wagtail 2.12, change this same warning message to be displayed for all users regardless of roles. Potentially also tweak the wording?
- In a future version (2.13? 2.14?), display the same message on all pages. Again, potentially with different wording.

**Comment by thibaudcolas** [comment]
We now have a defined plan to gradually remove supported, detailed at https://docs.wagtail.io/en/stable/editor_manual/browser_issues.html#ie11.

Here are the important dates, based on [Wagtail’s release schedule](https://github.com/wagtail/wagtail/wiki/Release-schedule):

- v2.14, due in August 2021, will be the first release to no longer support IE11.
- v2.11 LTS, which got released recently, supports IE11, and will be supported until February 2022.

**Comment by thibaudcolas** [comment]
Next step: #6947. This makes the message much more visible. According to [StatCounter](https://gs.statcounter.com/browser-version-market-share), IE11 usage was around the 0.7% mark as of February 2021.

**Comment by Stormheg** [comment]
Looks like we forgot to 'officially' drop IE11 support in Wagtail 2.14.
Internet Explorer 11 is still listed as supported in the docs:

- https://docs.wagtail.io/en/latest/contributing/developing.html?highlight=IE#browser-and-device-support
- https://docs.wagtail.io/en/latest/editor_manual/browser_issues.html#ie11

**Comment by lb-** [comment]
@Stormheg  I just noticed this tonight also and have put up a PR https://github.com/wagtail/wagtail/pull/7535 

Probably not a big issue we missed this one, gives users another month or so to migrate, but we definitely want to drop IE11 for our 2.15 LTS
