### ISSUE TITLE
A hook to let documents served through Wagtail be given the proper content type.

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#6180]
### Is your proposal related to a problem?

When serving remote-hosted documents through `WAGTAILDOCS_SERVE_METHOD = 'serve_view'`, every file is given the `application/octet-stream` content type and marked as an attachment. This forces the browser to download the file, no matter what type it is. This is undesirable for things like PDFs, which should open within the browser, but cannot when served in this way.

I understand why Wagtail does this (vagaries regarding how each particular remote file backend provides info about the file's actual content type), but when the developer _knows_ what the backend is, it'd be nice for them to be able to tell Wagtail how to retrieve the content type from the backend.

### Describe the solution you'd like

I'd like to add a hook which fires in the final `else` block of `wagtail.documents.views.serve.serve()`, and sends the `doc` object into the hooked function, letting said function return the content type of that `Document`.

### Describe alternatives you've considered

We currently get around this limitation by monkey-patching the entire `wagtail.documents.views.serve.serve()` function, which is major overkill just to change two lines near the end of the function. Having a hook we could implement would be much cleaner.

### Additional context

I realize that `WAGTAILDOCS_SERVE_METHOD = 'serve_view'` isn't really intended for use with remote file system backends. We decided that it needed to be used for our servers because documents uploaded to our sites are sometimes highly secure material, and we need to make absolutely certain that viable S3 links to them cannot leak out to the public (which the `redirect` serve method would potentially allow). We already use the `before_serve_document` hook to implement our own additional protections, so it'd be really nice if we could use another hook to let us get rid of our monkey-patch.

After writing all of this up, I'm now fairly confident that I could make a PR for this, if you guys would be willing to accept such a change.

**Comment by gasman** [comment]
Hi @coredumperror,
I've previously written up a proposed approach for this at https://github.com/wagtail/wagtail/issues/1158#issuecomment-520545163, and would be very happy to see a PR for this.

I'd like to avoid hooks for this, because I think 99% of people want the same thing here (i.e. PDFs opening in the browser) and it makes sense for that to become the out-of-the-box behaviour with no further configuration; and for people with truly custom requirements, a custom document model is the logical place for that to go.

**Comment by coredumperror** [comment]
Alright, I'll put that PR on my TODO list.
