### ISSUE TITLE
'classname' kwarg not being rendered in CharBlock in StreamField

### ISSUE THREAD

**Issue by pdcribeiro** [wagtail/wagtail#6184]
### Issue Summary

Following the docs on [using StreamField](https://docs.wagtail.io/en/stable/topics/streamfield.html#using-streamfield), the class passed as the `classname` kwarg to `blocks.CharBlock()` is not being rendered.

```
class BlogPage(Page):
    ...
    body = StreamField([
        ('heading', blocks.CharBlock(classname="full title")),
        ('paragraph', blocks.RichTextBlock()),
        ('image', ImageChooserBlock()),
    ])
    ...
```

### Steps to Reproduce

1. Follow the docs on [using StreamField](https://docs.wagtail.io/en/stable/topics/streamfield.html#using-streamfield).

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7.3
* Django version: 3.0.7
* Wagtail version: 2.9
* Browser version: Firefox 68

**Comment by gasman** [comment]
This works for me. The [bakerydemo](https://github.com/wagtail/bakerydemo) project uses `classname="title"` for heading blocks, and this shows up in the editor form as expected:

https://github.com/wagtail/bakerydemo/blob/2ec4475f75b364c630c5d0191c5a477ca6e1bad6/bakerydemo/base/blocks.py#L26

![charblock-classname](https://user-images.githubusercontent.com/85097/86109921-d21dae80-babc-11ea-896d-6dad8cba6e7e.png)

Perhaps you were expecting the classname to show up in the front-end rendering instead? We should clarify this in the docs (and consider changing the name to `form_classname` for consistency with structblock and others: #5100)
