### ISSUE TITLE
Allow folding of page field sections in admin interface

### ISSUE THREAD

**Issue by pdcribeiro** [wagtail/wagtail#6187]
### Is your proposal related to a problem?

My page editing screens in the admin interface are getting large and complex.

### Describe the solution you'd like

It would be nice to be able to fold each page field section at the red header.

**Comment by zerolab** [comment]
A few notes:

Currently you can only collapse [`MultiFieldPanel`s](https://docs.wagtail.io/en/stable/reference/pages/panels.html#multifieldpanel)

Relevant bit of code: https://github.com/wagtail/wagtail/blob/master/wagtail/admin/static_src/wagtailadmin/js/page-editor.js#L238

The solution would be change the selector to `$('.object.collapsible')` and update the panels documentation

**Comment by pdcribeiro** [comment]
Wow, thank you for your help! Didn't know about that.

Do you mean I should change that and make a pull request? Sorry, I'm just starting out 😆

**Comment by zerolab** [comment]
Hey @pdcribeiro,

> Do you mean I should change that and make a pull request? Sorry, I'm just starting out 😆
Yes please. I think you made a sensible suggestion.

**Comment by pdcribeiro** [comment]
I'll do that then! Thank you for your help :)

**Comment by zerolab** [comment]
Adding as reference (from [#6201 (comment)](https://github.com/wagtail/wagtail/pull/6201#discussion_r449530557))

> Also, the collapse/expand icon isn't focusable, so from a brief look I think this is likely to be inaccessible to screenreader users. Collapsing/expanding may not be a big deal to them, but I'd be cautious about making that decision, because on a page with lots of info like this I think it would be a useful tool (especially as I believe hide uses display: none so is accessible automatically?)

**Comment by pdcribeiro** [comment]
Thank you for the additional information. However, I stopped using Wagtail for now and never found the time to implement this. Just to let everyone know I'm not working on it and won't be doing it in the near future :/

Thank you again for your help :)

**Comment by pyarun** [comment]
https://github.com/wagtail/wagtail-react-streamfield#meta-attributes-or-passed-to-__init

Fixes this issue.

**Comment by rjmackay** [comment]
@zerolab what other sections should be collapsible beyond the existing MultiFieldPanels?

It seems like ideally the collapsible/expand behaviour would be separated from the visual presentation. Right now it's closely tied to both the `.multi-field` class and also the `.title-wrapper`.

**Comment by zerolab** [comment]
@rjmackay just thinking out loud here:

* at the very least, we'd want any of the panels to be collapsible. That is `.object.collapsible` (with a `.title-wrapper` and `.object-layout` element)
  > It would be nice to be able to fold each page field section at the red header.
* provide a generic way of doing this via data attributes on the container (data-collapsible, data-collapsible-title, data-collapsible-content)

**Comment by rjmackay** [comment]
The problem I can see with using data attributes on the container is that Fields don't have any way to inject data attributes. They do already have a simple way to add extra classes. I'll start with cleaning up but still using classes and then see where I go from there.

**Comment by rjmackay** [comment]
@zerolab I've sent a PR for a pretty basic solution to this. It's enough to solve it for most panels.

However - as mentioned on the PR - I'd also like it if I could collapse each Inline child in the InlinePanel. That's what I was looking for in the first place. I could implement something like a `child_classname` argument on the InlinePanel constructor so someone could add a `collapsible` class to each child. I'd still need a way to add a heading or expand control to each child though. I'm happy to try implementing something like `child_header_from_field` (similar to https://github.com/wagtail/wagtail-condensedinlinepanel) but wanted to know if that's something you accept a PR for?

**Comment by zerolab** [comment]
@rjmackay will consult with the others at the core meeting for a decision on this

**Comment by zerolab** [comment]
Hey @rjmackay, sorry for the delay on getting back at this.
There was quite a bit of back and forth, but the team agrees that a `classname`/ `child_classname` approach is viable for InlinePanel. `child_header_from_field` would be a solution for it. I do wonder though, why not use https://github.com/wagtail/wagtail-condensedinlinepanel which provides added benefits?

**Comment by rjmackay** [comment]
> why not use https://github.com/wagtail/wagtail-condensedinlinepanel which provides added benefits?

I tried that but found it was very buggy. I couldn't get it to save data at all when including tag fields in the inline panel. I'm not sure if that was a clash with modelcluster or taggit, but it seemed a fragile approach to move so much data handling to JS just to get small UI improvements.

**Comment by zerolab** [comment]
@rjmackay thank you for the context 👍 If you do have the capacity, please do go ahead with this

**Comment by rjmackay** [comment]
It'll probably be a week or so, but definitely planning to get to it.
