### ISSUE TITLE
Control over documents extensions

### ISSUE THREAD

**Issue by starkyller** [wagtail/wagtail#6197]
### Is your proposal related to a problem?

I tell people to only upload pdf files but they sometimes upload .docx

### Describe the solution you'd like

A simple key on the settings file like:
WAGTAIL_DOCS_EXTENSIONS = ['pdf', 'another_extension']

and then on the files upload validate if the inserted file has one of the defined extensions

django already has the FileExtensionValidator so I'm thinking a small update in the AbstractDocument ?

**Comment by meghanabhange** [comment]
Can I pick this up?

**Comment by tomdyson** [comment]
@meghanabhange go for it!

**Comment by loicteixeira** [comment]
Implemented in #6423. Great contribution 👏
