### ISSUE TITLE
500 Bad Request – page too complex?

### ISSUE THREAD

**Issue by josephkohlmaier** [wagtail/wagtail#6198]
We have been building The School of Art, Architecture and Design website with Wagtail – liveness.org.uk. There are some pages which have considerable content which we construct using a streamfield – such as this page: https://liveness.org.uk/2020/culture/critical-and-contextual-studies/ – with some pages containing as many as 30 or 40 streamfield elements, sometimes with nested content such as images and slideshows. In addition, with a large team working on this project, there are often dozens of page revisions. There is a point where, the more complex the pages get, we get a 500 Bad Request error on save. Is it possible that the streamfields, or revision histories etc. at some point hit some point of limit that the database/app can't cope with anymore? This has now happened a few times, only on pages that have extensive content, and had extensive editing.

**Comment by zerolab** [comment]
Hi @josephkohlmaier,

Would you be able to get hold of the logs? A 500 error indicates an application error, but that is difficult to debug without logs. We have seen pages with very large Streamfields (think 80 to a 100) without an issue

**Comment by gasman** [comment]
Some previous discussions of streamfield performance:
https://github.com/wagtail/wagtail/issues/3062
https://github.com/wagtail/wagtail/issues/5872
[Enabling Django's cached template loader](https://docs.wagtail.io/en/stable/advanced_topics/performance.html#templates) is also reported to help, although this should normally be enabled by default in production mode anyhow.

**Comment by josephkohlmaier** [comment]
Here's the error; transcript attached. I will look at Tom's links.

[error.txt](https://github.com/wagtail/wagtail/files/4869036/error.txt)
<img width="1184" alt="Screenshot 2020-07-03 at 10 48 19" src="https://user-images.githubusercontent.com/40425066/86457001-e8c14100-bd1a-11ea-8097-c61cea8fd01d.png">

**Comment by josephkohlmaier** [comment]
@gasman – I can get a developer on this if you could suggest what to try first, and if in the links you sent there is actually a solution. We will break up pages – it's better practice anyway to be honest; our tutors and students just need to edit a bit more. But it's still an issue we might face; especially not wanting to have to rebuild the pages where this happens in smaller chunks.

**Comment by gasman** [comment]
This is fixable by increasing the `DATA_UPLOAD_MAX_NUMBER_FIELDS` setting: https://docs.djangoproject.com/en/3.0/ref/settings/#data-upload-max-number-fields

**Comment by josephkohlmaier** [comment]
Thank you.
