### ISSUE TITLE
Table Block language option is not respected

### ISSUE THREAD

**Issue by pinktig** [wagtail/wagtail#6206]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When using table block, language set by [table options](https://docs.wagtail.io/en/stable/reference/contrib/table_block.html?highlight=tableblock#changing-the-default-table-options) are not respected in admin editing interface. 
It seems that wagtail is correctly setting language option as given in table option, but the language file needed by handson table library is not included in wagtail default admin js scripts. 
I've tried to add language script file of current included version of handson table (6.2.2) myself via include  [(insert_editor_js hook)](https://docs.wagtail.io/en/stable/reference/hooks.html#insert-editor-js) but, as this hook include script files before handson table it didn't work. 

So, I've managed to make it work by adding script via custom admin_base template. [wagtailadmin/admin_base.html](https://docs.wagtail.io/en/stable/advanced_topics/customisation/admin_templates.html#customising-admin-templates). 

And, the following was working solution: 

{% extends "wagtailadmin/admin_base.html" %}
{% load static %}
{% block js %}
  {{ block.super }}
  <script src="{% static 'js/hanson-table-language-file.min.js' %}"></script>
{% endblock %}

I think it would be nice if wagtail includes language file from handson table library in future version. 

### Steps to Reproduce

1. Add "wagtail.contrib.table_block" to INSTALLED_APPS
2. Import table block and use it in any stream_block with table_options language set to any language other than 'en'. (in my case it was 'ko-KR'. 
3. open any edit page that uses table block via wagtail admin interface. 

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details
* Python version: 3.7.6
* Django version: 2.2.7
* Wagtail version: 2.9
* Browser version: safari 13 on macOS 10.15.5 (Catalina)

**Comment by gasman** [comment]
Hi @pinktig - thanks for the report. This is covered by the existing issue #5504.
