### ISSUE TITLE
It should be possible to fully control a page from within the page editing screen

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#622]
At present if a user creates a page, saves it, then decides it should be moved elsewhere, it's not possible to do this from the editing interface, only the explorer. 

This proves a particular problem when the page title falls mid-way through the alphabetic sorting by title, and there are a lot of other pages at the same level. Without [the ability to order by recent edits](https://github.com/torchbox/wagtail/issues/418) this situation requires the user to scroll through an unknown number of pages-of-pages before they find their page and can then move it.

Being able to order by recent edits and the "your most recent edits" on the dashboard are partial solutions, but there's no sense in not being able to fully control a Thing from within the main editing screen of that Thing.

"Copy" is another action that would benefit from being added.

**Comment by phildexter** [comment]
We are planning on adding this functionality in through the [new page editor designs](https://github.com/wagtail/wagtail/discussions/7739), which introduces a new secondary menu next to the page breadcrumb.

These designs will take some time to be implemented, but in the meantime I think we should do something similar on the existing page editor. Here is a mockup of it that uses existing styles.

![image](https://user-images.githubusercontent.com/34743669/145986161-f20b496b-3efb-403e-b1b7-8a63f5803049.png)

Other packages can also add to this menu, such as wagtail-localize for page translation actions.

**Comment by thibaudcolas** [comment]
Done in #7783.
