### ISSUE TITLE
Remove support for Hallo editor

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#6228]
This is a tracking issue to discuss removing support for Hallo in Wagtail core. **As of July 2020 there are no short-term plans to remove support, but if this is something you rely on we would love to hear from you.** We’re actively considering removing Hallo support to make way for new features.

Hallo has been [deprecated since Wagtail 2.0](https://docs.wagtail.io/en/stable/advanced_topics/customisation/extending_hallo.html), released in February 2018. As of now it doesn’t cost us much to keep support, but it does represent a burden when considering changes to rich text. It’s important that rich text keeps on being pluggable to allow third-party editors – it just doesn’t feel worthwhile anymore for Hallo to get special treatment by being in Wagtail core.

We’ve discussed this in today’s core meeting, and there are two practical reasons that make me want to suggest this now:

- Hallo’s inappropriate handling of HTML and editor input – it’s not reliable, has browser-specific behavior, not a good user experience.
  - Apart from CMS user experience, this is also a constant source of security concerns (XSS injections, or generally injection of undesirable content or formatting)
  - It also causes issues for accessibility – markup being unreliable leads to undesirable formatting (e.g. images in headings, or headings in lists), that is hard to troubleshoot.
- The current rich text representation in the database is heavily influenced by Hallo’s legacy. I think it’s great for Wagtail to be editor-agnostic, but Hallo’s content model isn’t a good foundation for this, and if there are opportunities for us to reconsider this then it’s worthwhile.

----

We haven’t discussed what it would mean to "remove support" (thoughts welcome!), my personal take on this would be to:

1. Move all Hallo-related code to a third-party package on the `wagtail` GitHub account, changing it as little as possible otherwise.
2. Clearly state on there what Wagtail versions it supports.
3. Document the setup with the new package, and migration steps (changing config only, no DB migration needed)
4. Have a notice saying we’re looking for maintainers for this package for future support.
5. If no one steps in, the package will eventually stop being compatible with Wagtail if / when any incompatible changes are introduced, as with any other third-party packages.

**Comment by lb-** [comment]
@thibaudcolas I have put this on the UI Team project and would like to propose we make this a pre-req for the work on the new page editor. Maybe it can be discussed at the next core team meeting. 

However, we may need to add a warning for 2.17 (might be too late to put in 2.16 as RC just went out) then actually remove in the release after that.

As noted on the jQuery UI investigation, this is one of the main usages of that library plus potentially a CSP risk if used. 

https://github.com/wagtail/wagtail/issues/7053

**Comment by zerolab** [comment]
@lb- one to discuss at the next core meeting. IMHO, should be OK to add a warning in 2.16 since we're not changing anything functionally.

As an aside, we discussed that dropping Halo from core needs to come with a contrib package, as outlined by @thibaudcolas above.

**Comment by lb-** [comment]
Really rough start, seeing if I can get an 'app' working inside bakerydemo that uses the isolated Hallo editor.

https://github.com/wagtail/bakerydemo/compare/master...lb-:hallo-editor-package

I have started with the cookiecutter by using the cookiecutter (thanks @kaedroho ) https://github.com/wagtail/cookiecutter-wagtail-package
 
Then deleting each part I find in Wagtail and copying over to the bakerydemo folder.

Here are the removals so far https://github.com/wagtail/wagtail/compare/main...lb-:feature/hallo-editor-removal

Not sure if I will have time to get this fully worked through but will try to chip at it.

**Comment by cnk** [comment]
@lb- Yes Caltech is going to need to keep hallo.js for the foreseeable future so I'll need to work on extracting it and then maintaining. I'll take a look at your work above and see if I understand your approach

**Comment by lb-** [comment]
Update - the above branches are a little bit closer
* Wagtail branch has all Hallo references removed in docs/js/css/html/python and admin loads, have not run tests yet
* Bakerydemo branch with temporary package loads but not fully functional yet

**Comment by lb-** [comment]
## Update

I have a functional package on a seperate GitHub repo, now works, with styles in a plain FieldPanel and StreamField usage.

https://github.com/lb-/wagtail-legacy-hallo-editor

This is not in pypi yet but following the development instructions should allow this to be cloned locally and tested against something like bakery demo or a local project. 

I have opted for a no build frontend setup (so ES5 JS only, CSS only) but have added linting/formatting and unit test tooling. 

No tests are functional on the repo but this is hopefully at a point where others can start smoke testing in their own projects.

Important - Wagtail will still load Hallo resources in some cases so testing this requires a local version of Wagtail to be running on this Branch https://github.com/lb-/wagtail/tree/feature/hallo-editor-removal

AND running `npm run build` 

## Next steps
- Wagtail python tests
- Update readme with the notes from this comment, add project files like changelog, contributors, fix readme links, add clarity about the package being not supported activity after 2.17
- Get some kind of package test working
- Work out if Telepath code is actually used and how 
- Test an InlinePanel scenario
- Test a Snippet usage scenario
- Check with core team on when best to move repo to wagtail organisation in GitHub

**Help requested**
- Someone review the package repo who has made a Django package and check for any major problems - I'll reach out in core team chat for this one
- Someone using Hallo in a real world app somke test their code locally using the package and the Wagtail branch. @cnk maybe?

**Comment by lb-** [comment]
As per feedback from @thibaudcolas  the package will be named `wagtail-hallo`, I have not yet put in the Wagtail org but have renamed the project on my profile + all internal files, should work with the updated readme instructions.

https://github.com/lb-/wagtail-hallo

**Comment by lb-** [comment]
Updates from core team meeting

* A few more python tests and then move to Wagtail repo later this week / early next week
* Based on core team chat, Telepath code is likely not needed and was just 'stubbed out', check a 'copy' of a Streamfield that uses Hallo first but likely not used (code will still be in new repo though)
* @zerolab is good to help publish the package, but apparently pypi allows you to add 'collaborators' to a package for future core team and maybe external maintainers with release permissions
* Pretty close to marking the PR as ready
* Confirmed that the html whitelister code should be kept in Wagtail core as it is documented separately from teh Hallo editor and could be used by other editors

**Comment by cnk** [comment]
Sorry it took me so long to get testing. The new wagatail-hallo package (+ wagtail from https://github.com/lb-/wagtail/tree/feature/hallo-editor-removal) works fine on my out-of-the-box Wagtail project. Moving on to testing this on our more complicated project that also has halo.js plugins / customizations.

**Comment by lb-** [comment]
@cnk super great to hear that, thank you so much, hopefully the other tests go well.

**Comment by cnk** [comment]
@lb- Looking good! My plugins all work - all I had to do was change the import statement. I haven't looked at the code in the PR but as for functional testing, https://github.com/lb-/wagtail/tree/feature/hallo-editor-removal works for me - including a custom "edit the html" button and expanded WhitelistRules.
