### ISSUE TITLE
Form builder creates different names in other language

### ISSUE THREAD

**Issue by marciusl** [wagtail/wagtail#6254]
### Issue Summary

We have few languages and form builder. For example label name is "Name" and in Dutch it is "Naam". So in frontend it generates input with name="name" and name="naam". While in backend it should be name_nl. And when you go to forms submissions in admin it shows None if you have english language selected. If you select dutch then those None disappears and it shows correct data. So in general you can only see one language form submissions and other language just shows None. 

### Technical details

* Python version: 3.7
* Django version: >3.0
* Wagtail version: 2.8.2
* Browser version: Latest

**Comment by gasman** [comment]
Hi @marciusl - thanks for the report.
Wagtail itself does not currently have any concept of multi-language content, so this is an issue with whatever package is providing the `name_nl` functionality (I'm guessing `wagtail-modeltranslation`).
