### ISSUE TITLE
Wagtail Write API

### ISSUE THREAD

**Issue by venkata-penumatsa** [wagtail/wagtail#6258]
### Is your proposal related to a problem?

Just curious to know, If Wagtail has any plans to implement WriteAPI directly into page models?
Because few of my models I am trying to import data via the Django REST framework. and expose data via Wagtail API.
Instead, if Wagtail provides both read and write API directly into page models that would be a great feature

### Describe the solution you'd like

For writing, I am using the Django REST API framework. Instead, Wagtail provides Write(Insert data) directly into page models that would be helpful

**Comment by kaedroho** [comment]
Yep, this is on the roadmap. The API for this is partially designed here: https://github.com/wagtail/rfcs/blob/master/text/015-revisions-api-revised.md

That deals with updates, but authentication and creating new pages haven't been thought about much yet.

**Comment by abhishekraj272** [comment]
Can anyone explain, what I have to add?

**Comment by kaedroho** [comment]
@abhishekraj272 
If you want this feature, you'll either need to wait for someone to implement it or you could implement your own using Django REST Framework

**Comment by thibaudcolas** [comment]
I see this is already opened at #4667. Will close in favour of that other issue.
