### ISSUE TITLE
Missing SVG icons for optional rich text features

### ISSUE THREAD

**Issue by stefanistrate** [wagtail/wagtail#6261]
### Issue Summary

Wagtail doesn't provide SVG icons for optional rich text features like strikethrough, superscript and subscript. It would also be a good addition to provide an SVG icon for underline as well, even though this rich feature is not implemented at the moment.

### Steps to Reproduce

1. Enable the "strikethrough" rich feature:

```python
class RichTextBlock(blocks.RichTextBlock):

    def __init__(self, **kwargs):
        super().__init__(
            features=[
                'bold',
                'italic',
                'strikethrough',
            ],
            **kwargs)
```

2. Check the rich editor menu and see the empty space where it's supposed to be an icon.

![Screenshot 2020-07-28 at 13 30 58](https://user-images.githubusercontent.com/3457859/88666048-70f6f400-d0d7-11ea-8499-36f0f7989803.png)

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

Yes

### Technical details

* Python version: Run `python --version`.
```
Python 3.8.3
```
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
```
Version: 3.0.8
```
* Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
```
Version: 2.10rc1
```
* Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
```
Chrome 84
```

**Comment by zerolab** [comment]
The icons that need adding are:

Name | FontAwesome link
------|-------------------
superscript | https://fontawesome.com/icons/superscript?style=solid
subscript | https://fontawesome.com/icons/subscript?style=solid
strikethrough | https://fontawesome.com/icons/strikethrough?style=solid
