### ISSUE TITLE
InlinePanel Orderable is not working after first click on element to move

### ISSUE THREAD

**Issue by bplociennik** [wagtail/wagtail#6274]
### Issue Summary

I'm using `Orderable` model as an `InlinePanel` in another model in my app. I have an issue with changing the order of items on the wagtail admin panel - it doesn't work when I click the first time on the element. After the first click, it starts working.

Is related to jquery script: `/wagtailadmin/js/page-editor.js?v=8b6dafbe` (starts from line 39)

```
class PhoneNumber(Orderable):
    general_setting = ParentalKey(
        "wagtail_settings.GeneralSetting",
        on_delete=models.CASCADE,
        related_name="phone_numbers",
    )
    phone = models.CharField(_("phone"), max_length=30)
    panels = [FieldPanel("phone")]
```

I have this problem with all InlinePanels using `Orderable` feature.

### Steps to Reproduce

1. Create a new `models.Model` with `@register_setting` decorator
2. Use `PhoneNumber` model mentioned above and add proper `ParentalKey` to your model from step 1
3. Add InlinePanel `MultiFieldPanel([InlinePanel("phone_numbers")], heading=_("phone numbers"))` to your model from step 1
3. Visit Wagtail dashboard and open your registered model - add few records
4. Save and refresh the page, click on the last item to move it up
5. You will see animation because it's not related to move functionality but the element will stay in the same place
6. Click again and element will move up correctly

Effect before and after first click:
<img width="927" alt="Zrzut ekranu 2020-07-31 o 11 14 48" src="https://user-images.githubusercontent.com/6594923/89020441-31224d80-d31f-11ea-858a-50efefc9c8f5.png">

### Excepted behavior
It should be possible to change item order on the first click

### Technical details

* Python version: `3.8.2`.
* Django version: `3.0.7`.
* Wagtail version: `2.9`.
* Browser version: Chrome 83.

**Comment by gasman** [comment]
Hi @bplociennik - thanks for the report. Just to confirm, have you been able to replicate this on a clean newly-created Wagtail project?

**Comment by bplociennik** [comment]
hey @gasman I didn't have time to check it on fresh version. I will try check it in the next week.

**Comment by gasman** [comment]
Thanks! If you do manage to replicate it on a new project, it'd be really helpful if you could share the complete models.py - that makes it much easier for us to verify the issue independently.

**Comment by gasman** [comment]
Closing as unconfirmed.
