### ISSUE TITLE
IE 11: Focus ring not appearing on every-other element

### ISSUE THREAD

**Issue by Scotchester** [wagtail/wagtail#6283]
When tabbing through the items in a page's explorer view in Internet Explorer 11, the focus ring only appears on every second tab stop. Here's a screencap of this behavior in action:

![Tabbing through items in IE11 and only seeing the focus ring every other tab](https://user-images.githubusercontent.com/1044670/89109002-5ee4c080-d40b-11ea-877d-9d22c283f06e.gif)

@thibaudcolas has a hunch of what might be causing this.

**Comment by thibaudcolas** [comment]
#6170 🌈
