### ISSUE TITLE
Cannot create root-level Page instance when having deleted the default root-level Page

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#6294]
Cross-posted from Reddit: https://www.reddit.com/r/django/comments/i3amz3/root_page_and_wagtail_cms/

When working with a fresh Wagtail instance, it is possible for the content editor to delete the site root page (the default Wagtail Page instance). 

![Screenshot from 2020-08-05 13-27-04](https://user-images.githubusercontent.com/17307/89402569-c064a200-d71f-11ea-8919-9983f4c462bf.png)

Deleting the site root page will automatically delete the default site as well.

![Screenshot from 2020-08-05 13-27-44](https://user-images.githubusercontent.com/17307/89402585-c65a8300-d71f-11ea-9069-2c79a1adab10.png)

With both the initial root Page and Site deleted, the user cannot initialize a new Page hierarchy or create a new site.

![Screenshot from 2020-08-05 13-28-11](https://user-images.githubusercontent.com/17307/89402604-cbb7cd80-d71f-11ea-9d43-7c0823cc11af.png)

I believe this is a **usability bug** because it leaves the user with a broken site. There would ideally be a way to recover from this "rootless" state through the Wagtail Admin UI.

## Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Log in with superuser
3. Delete the welcome page

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.8.3
* Django version: 3.0.9
* Wagtail version: 2.9.3
* Browser version: Firefox 79.0

**Comment by gasman** [comment]
Hi @brylie,

> There would ideally be a way to recover from this "rootless" state through the Wagtail Admin UI.

There is a way: create a page, and then create a site record pointing to it. The purpose of a site record is to define which page should be served up for a given hostname, so it's not meaningful to create a site record while no pages exist. How else would you see this working?

**Comment by brylie** [comment]
@gasman the OP mentions they are not able to create a new Page instance. I have verified there is no way to create a new Page instance in a rootless Wagtail. Ideally, the user could recover from this state by Wagtail allowing them to create a new Root Page.

**Comment by brylie** [comment]
A couple of strategies for handling this type of situation might be *recovery* or *prevention*.

## Recovery
When Wagtail renders the pages list with a count of zero page instances, it could allow the user to create a new basic Page instance. 

## Prevention
Conversely, Wagtail could *prevent* the user from getting into this situation by not allowing the initial Page instance to be deleted without at least one other Page, or inherited model, instance available.

**Comment by brylie** [comment]
> There is a way: create a page, and then create a site record pointing to it. 

That was my initial advice. However, there doesn't seem to be a way to create a new Page instance via the UI.

**Comment by gasman** [comment]
This is what I see as a superuser when I delete the initial homepage, on a site that has just been created with `wagtail start` with no code changes:

![Screenshot 2020-08-05 at 11 52 20](https://user-images.githubusercontent.com/85097/89404641-3d891a80-d712-11ea-9e61-3cc0dbef8265.png)

So, I do still get the option for creating a new page. Is that not the case for you? (I can see there would be issues if you were logged in as an ordinary editor, or deleted the HomePage model, but that doesn't seem to be what's being described here.)

**Comment by brylie** [comment]
OK, I will update the steps-to-reproduce to mention that Wagtail is being integrated into an existing Django site.

**Comment by gasman** [comment]
Ah - I see that the original poster on Reddit is following the "Integration with Django" steps, so their codebase won't have the HomePage model defined. As a result, there are no page types available to create. Once they've installed Wagtail into their project, they need to continue following the main tutorial from here: https://docs.wagtail.io/en/v2.9.3/getting_started/tutorial.html#extend-the-homepage-model

**Comment by ocuna** [comment]
This happened to me.   Probably because I didn't finish the last paragraph "Start Developing" 
https://docs.wagtail.io/en/v2.14.1/getting_started/integrating_into_django.html#start-developing
I opened the site up, deleted the default home page.  I couldn't create a new site and I didn't see any new page types and didn't understand that I needed to create those.  I was unsure if Wagtail would generate them itself.  I reloaded a database backup, re-did the migrations and started over by creating a new app, a page model  and a template.

**Comment by brylie** [comment]
I'm bumping into this issue again, this time while writing unit tests that need to set up and tear down a Wagtail site structure in order to test various sections of our website. It would be really helpful if the Wagtail documentation had sections on testing and content migration since these are common concerns. While many aspects of testing and content migration are indeed unique to each project there are still some general patterns that could be added to the Wagtail documentation.

**Comment by gasman** [comment]
Hi @brylie - as far as I can see, this issue is about a usability gotcha that arises when integrating Wagtail into an existing site, and deleting the initial homepage without having first defined any page models of your own. I can't see how that relates to unit testing - please can you open a new issue expanding on what you feel is missing from the documentation?

**Comment by JenteOtte** [comment]
It maybe sounds stupid, but I also faced this problem of not being able to add new (child) pages. But I wasn't able to do it, even when before I deleted my initial root page. I'm new to Wagtail, but I just simply forgot to add my new Django app with the Page model to my INSTALLED_APPS. This didn't raise any errors, just a simple oversight, but i ended up in this issue, so for some this information might help!

**Comment by raimondi1337** [comment]
This issue still exists. I deleted the root page and now can not create a site or a new page.

I still see page ID 1 in `wagtailcore_page` but it appears to be inaccessible.
Can I flip a bit in one of the columns to re-enable it or run an SQL insert to replace it?

**Comment by gasman** [comment]
@raimondi1337 You need to define a HomePage model. https://docs.wagtail.org/en/stable/getting_started/tutorial.html#extend-the-homepage-model

**Comment by raimondi1337** [comment]
> @raimondi1337 You need to define a HomePage model. https://docs.wagtail.org/en/stable/getting_started/tutorial.html#extend-the-homepage-model

I fixed it by dropping every wagtail table, deleting every wagtail django migration, and rerunning django migrations

**Comment by gasman** [comment]
@raimondi1337 Deleting the migrations that are shipped within Wagtail is liable to break your database in ways that are very difficult to recover from - at the very least, it'll prevent you from upgrading to future Wagtail releases. If you think it's fixed things, then fine, but we won't be able to provide any support from this point forward.

**Comment by raimondi1337** [comment]
> @raimondi1337 Deleting the migrations that are shipped within Wagtail is liable to break your database in ways that are very difficult to recover from - at the very least, it'll prevent you from upgrading to future Wagtail releases. If you think it's fixed things, then fine, but we won't be able to provide any support from this point forward.

I just deleted the migration completed rows in `django_migrations` table, not the migrations themselves.
Nothing ***should** be orphaned 🤞 
I'll update my comment to not mislead anyone else that reads it.

I had to go do most of the stuff in your link anyways. The "Integrate Django into an existing project" documentation implied to me that I could skip all of the other Getting Started steps. Some different phrasing in the docs could prevent idiots like me from doing the same in the future.

Thanks for the support!

**Comment by CDWimmer** [comment]
I've managed to get myself in this situation today - I'd set my homepage model to have an empty list for `parent_page_types` as I guess I imagined this would only allow it to exist on root, and the tutorial gives no indication of how to specify "This can only be a root page" (Or I suppose, "this can only be child of root, x, y, or z")
