### ISSUE TITLE
users shouldn't be allowed to create superusers

### ISSUE THREAD

**Issue by zeroepix** [wagtail/wagtail#6307]
### Issue Summary

Currently, superusers cannot remove themselves from being a superuser, and equally a user cannot promote themselves to a superuser, but a user with Add/Edit privileges can create a regular user and promote that new user to superuser, thereby giving themselves superuser access. This isn't a problem for simple websites, but it is for sites where you want to give untrusted users some form of user or page control. 

### Steps to Reproduce

1. as superuser, create a "user_manager" group with add/edit/delete privileges for User, along with admin view access only. 
2. as superuser, add a new user "non_superuser" and add them to the user_manager group you made.
3. open a private window and go to your admin user url (e.g. [http://localhost:8000/admin/users/](http://localhost:8000/admin/users)), logging in as non_superuser.
4. as non_superuser, create a new user "future_superuser", and in roles tick administrator, then click add user.
5. you now have your very own superuser.
6. to rub salt in the wound, while still as non_superuser, edit your normal superuser account, go to roles, untick "Administrator", and save.
7. then also as non-superuser, click delete on your normal superuser account and wave it goodbye.

#### Any other relevant information. 

This may not be a bug specifically and instead a design decision, but I do want to raise this topic specifically because I think it presents a potentially dangerous situation due to administrators misunderstanding how powerful users managers are.

Logically, only superusers should be able to add, edit and delete other superusers in all circumstances. It is clearly a group with unlimited power and should be protected appropriately. Right now, all users with user Add privilege are superusers. 

For non-superusers deleting superusers, in [users.utils](wagtail/users/utils.py) user_can_delete_user checks for this: 
```
    if user_to_delete.is_superuser and not current_user.is_superuser:
        # ordinary users may not delete superusers
        return False
```
but it's made ineffective by the fact non-superusers can demote superusers before deleting them. We shouldn't allow non-superusers to add, edit or delete superusers at all. 

### Possible workaround
I've been trying to work around the issue while making the most of the existing wagtail codebase, and it seems to me the easiest fixes lie in the files [wagtail.users.views.users](wagtail/users/views/users.py), [wagtail.users.forms](/wagtail/users/forms.py) and possibly [wagtail.users.utils.users](wagtail/users/utils/users.py) for deletes. 

UserEditForm already checks for self editing:
```
def __init__(self, *args, **kwargs):
        editing_self = kwargs.pop('editing_self', False)
        ...
        if editing_self:
            del self.fields["is_active"]
            del self.fields["is_superuser"]
```

A "self_is_superuser" status can be introduced and passed along to the form constructors, which can be added to the self_editing check on those forms before sending them out or saving them.

e.g. 
```
def create(request):
        ...
        if request.method == "POST":
                form = get_user_creation_form()(request.POST, request.FILES, self_is_superuser=request.user.is_superuser)
                if form.is_valid():
                        ...
        else:
                form = get_user_creation_form()(self_is_superuser=request.user.is_superuser)
        ...
        

def edit(request, user_id):
        ....
        if request.method == "POST":
                form = get_user_edit_form()(request.POST, request.FILES, instance=user, editing_self=editing_self, self_is_superuser=request.user.is_superuser)
                if form.is_valid():
                        ...
        else:
                form = get_user_edit_form()(instance=user, editing_self=editing_self, self_is_superuser=request.user.is_superuser)
        ...
```
and in Forms:
```
class UserCreationForm(UserForm):

    def __init__(self, *args, **kwargs):
        self_is_superuser = kwargs.pop('self_is_superuser', False)

        super().__init__(*args, **kwargs)

        if not self_is_superuser:
            del self.fields["is_superuser"]

    class Meta:
        model = User
        fields = set([User.USERNAME_FIELD]) | standard_fields | custom_fields
        widgets = {
            'groups': forms.CheckboxSelectMultiple
        }


class UserEditForm(UserForm):
    password_required = False

    def __init__(self, *args, **kwargs):
        editing_self = kwargs.pop('editing_self', False)
        self_is_superuser = kwargs.pop('self_is_superuser', False)
        
        super().__init__(*args, **kwargs)

        if editing_self or not self_is_superuser:
            del self.fields["is_active"]
            del self.fields["is_superuser"]
    class Meta:
        model = User
        fields = set([User.USERNAME_FIELD, "is_active"]) | standard_fields | custom_fields
        widgets = {
            'groups': forms.CheckboxSelectMultiple
        }
```

There is also an is_superuser field in GroupForm which is currently inactive in the default templates which might also need the same checks.

I've tested the above changes and they seem to work as intended but I'm not sure if there are deeper ramifications that might affect other parts, so I'm posting this here for consideration. In order to perform these checks without modifying the above wagtail functions I can use the before_create_user / before_edit_user hooks and return my own rendered user page, but I'll miss out on positive future updates here unless I constantly monitor it. I'm happy to try and figure out how to produce a pull-request if it's a worthwhile idea.

**Comment by zeroepix** [comment]
I've just realized a further problem to the above, even with my proposed solution. A user can still edit superuser passwords!

That means it has to go beyond just removing the is_superuser field, and either not show or not accept forms where the target user is a superuser and the requesting user isn't.

**Comment by allcaps** [comment]
Related: https://github.com/wagtail/wagtail/issues/537#issuecomment-477269836

**Comment by gasman** [comment]
As per the discussion on #537, the 'reset password' loophole means that there's (probably) no reasonable way to lock down the user management interface to prevent privilege escalation, without totally blocking off all of the useful actions that you'd expect a "non-superuser-level admin" to perform. With that in mind, I think the right way forward is to handle this through better messaging ("only give this permission to fully trusted users"), so I'll close this in favour of #5188.

**Comment by Luk5553** [comment]
Solution: https://github.com/wagtail/wagtail/pull/11469
