### ISSUE TITLE
Django 3.1 support

### ISSUE THREAD

**Issue by AdrienLemaire** [wagtail/wagtail#6314]
Please add support for Django 3.1 support and its async views/middleware goodies.

**Comment by kaedroho** [comment]
Django 3.1 support is coming in 2.10 https://github.com/wagtail/wagtail/blob/437e3b9258c87229498c43a70b43ea8739eca988/CHANGELOG.txt#L19

We haven't added any support for async views/middleware into Wagtail itself, as we need to maintain support for older versions of Django for now. But these can be used in your own app/third party plugin.
