### ISSUE TITLE
[2.10] FieldError on page history view when custom user class doesn't have the username field

### ISSUE THREAD

**Issue by berekuk** [wagtail/wagtail#6317]
### Issue Summary

I'm getting an error on wagtail admin's `pages/{id}/history/` route:

```
FieldError at /wagtail/pages/12/history/

Cannot resolve keyword 'username' into field. Choices are: ...
```

### Steps to Reproduce

1. Create a wagtail project with custom AUTH_USER_MODEL which is missing the `username` field but defines the USERNAME_FIELD.
2. Navigate to page history view in wagtail admin.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **no**
(but I'm pretty sure this is a real and reproducible issue)

### Technical details

* Python version: 3.8.3
* Django version: 3.1
* Wagtail version: 2.10 (I didn't have this problem with 2.9)
* Browser version: latest Firefox on macOS

### Other notes

The stack trace mentions [wagtail/admin/templates/wagtailadmin/skeleton.html](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/templates/wagtailadmin/skeleton.html) which doesn't mention username at all.

<s>The culprit is probably:
* the code in [wagtail/admin/templates/wagtailadmin/pages/history.html](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/templates/wagtailadmin/pages/history.html)
* and possibly [wagtail/admin/templates/wagtailadmin/reports/site_history.html](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/templates/wagtailadmin/reports/site_history.html)

The line `{% include "wagtailadmin/shared/user_avatar.html" with user=entry.user username=entry.username %}` is suspicious, but I haven't checked yet if replacing `username` with `get_username` fixes the problem. (Upd: this might be wrong, since it's entry.username and not user.username... I'm not sure and I'm looking into the code right now.)</s>

**Comment by berekuk** [comment]
Here's a reproduction repo: https://github.com/berekuk/wagtail-username-bug

**Comment by zerolab** [comment]
🤔 that should be `entry.get_username`

**Comment by berekuk** [comment]
Ok, it's not an issue with the template.

The actual reason is this code:
```
def get_audit_log_users_queryset(request):
    return get_user_model().objects.filter(
        pk__in=set(PageLogEntry.objects.values_list('user__pk', flat=True))
    ).order_by('username')
```

From https://github.com/wagtail/wagtail/blob/v2.10/wagtail/admin/filters.py#L178

**Comment by drcongo** [comment]
Even though this is closed, I just though I'd add that the same thing happens on the `/admin/reports/workflow/` route too and I've not seen that mentioned in any other issues. Let me know if you want that opened as a new bug.

**Comment by gasman** [comment]
@drcongo This issue isn't closed. As per #6319 I'm currently looking at adding full test coverage for user models without a username field, so if #6319 doesn't already fix `/admin/reports/workflow/` then the new tests should flag it up.

**Comment by drcongo** [comment]
My mistake, sorry. Thanks @gasman.
