### ISSUE TITLE
New page history throws username missing field error

### ISSUE THREAD

**Issue by robmoorman** [wagtail/wagtail#6326]
# Issue Summary

`get_audit_log_users_queryset` expects `username` is present on the User model, which isn't is all cases (email is used a lot as USERNAME field).

### Steps to Reproduce

1. Custom User model with another field (eg. email) as username
2. Go to history of a page

### Technical details

* Python version: 3.7.x (any)
* Django version: any
* Wagtail version: 2.10

**Comment by gasman** [comment]
Thanks for the report @robmoorman! There's an existing issue open for this at #6317.
