### ISSUE TITLE
Wagtail 2.10 menu "Reports" item is misaligned -- design regression

### ISSUE THREAD

**Issue by picturedots** [wagtail/wagtail#6327]
### Issue Summary

Compared to 2.93, the "Reports" item in the top level CMS menu is misaligned -- it has shifted a few pixels to the right and now does not line up with the other menu items.

### Steps to Reproduce

To reproduce, compare a 2.10 instance with a 2.93 instance, as shown in these attached images

<img width="200" alt="wagtail 2 93 menu" src="https://user-images.githubusercontent.com/766699/90202027-7d9f6b80-ddaa-11ea-938d-5064fb1c8954.png"> 2.93 menu

<img width="200" alt="wagtail 2 10 menu" src="https://user-images.githubusercontent.com/766699/90202026-7d06d500-ddaa-11ea-8ebe-32b056ab8f48.png"> 2.10 menu -- note the placement of "Reports"

### Technical details

* Python version: 3.8
* Django version: 3.1
* Wagtail version: 2.10
* Browser version: Chrome 83, Firefox 75

**Comment by zerolab** [comment]
Hi @picturedots, thank you for reporting this.
It has already been reported in #6297. We introduced SVG icons, but the task to replace the icon font everywhere was quite large (see the full explanation at https://github.com/wagtail/wagtail/issues/6297#issuecomment-670391986)

Closing as per #6297 / #6298. #6107 is the issue tracking the rest of the work needed. A PR changing the menu icons to SVG is very welcome.

**Comment by gasman** [comment]
@zerolab I thought that the conclusion in #6297 was that there was a mixture of SVG and font icons from custom and third-party add-ons, and this would fix itself once the add-ons migrated to SVG? Surely this shouldn't happen on a fresh Wagtail instance, then?

**Comment by zerolab** [comment]
@gasman 

hmm, https://github.com/wagtail/wagtail/issues/6297#issuecomment-670391986 mentions
> The only way out of this is to stop using font icons, and migrate all menu items to SVG. The SVG icons have a fixed ratio, and thus a fixed width.

I thought both @allcaps and you closing the #6297 / #6297 meant we'll deal with it as part of #6107, but it looks we miscommunicated there. Re-opening

**Comment by gasman** [comment]
Fixed in #6329
