### ISSUE TITLE
get_context() not being called for routable page

### ISSUE THREAD

**Issue by DanielSwain** [wagtail/wagtail#6346]
### Issue Summary

I'm creating a blog as part of a client's site.  I have created a `BlogPage` and set it up with `RoutablePageMixin`.  Different routes render with different templates (`blog-posts-listing.html`  and  `blog-post.html`).  In the footer of each template I want to show links to the blog archives by year, so I set up `BlogPage`'s `get_context()` method to return this information.  When I render any route for the page, the `get_context()` method is never called.  I have confirmed that this issue can be reproduced as described on another Wagtail project that uses `RoutablePageMixin`, and I have confirmed that `get_context()` **IS** called when the page is rendered by setting its `template =xxxxxxxxxxx` attribute and removing the Base Route noted below.

### Steps to Reproduce (models)

```
class BlogPost():
	title = models.CharField(_("Title"), max_length=255, default='')
	slug = models.SlugField(_("Slug"), max_length=255, unique=True, db_index=True, blank=True)
	content = RichTextField(default='', features=['italic', 'ol', 'ul', 'undo', 'redo', 'link', 'document-link'])
	image = models.OneToOneField('wagtailimages.Image', null=True, blank=True, on_delete=models.SET_NULL, related_name='+',  help_text='Image for post (optional)')
        date_created = models.DateTimeField(auto_now_add=True, editable=False)

	def __str__(self):
		return self.title

	panels = [
		MultiFieldPanel([
			FieldPanel('title'),
			ImageChooserPanel('image'),
			FieldPanel('content'),
		])		
	]


class BlogPage(RoutablePageMixin, Page):

	def get_context(self, request):
		context = super().get_context(request)
		posts_by_year = BlogPost.objects.all().annotate(year=TruncYear).values('date_created').annotate(Count('items'))
		context['posts_by_year'] = posts_by_year
		return context

        # Base Route
	@route(r'^$')
	def posts(self, request, name='post_list'):
		blog_posts = BlogPost.objects.all()
		page = request.GET.get('page', 1)
		paginator = Paginator(blog_posts, 12)
		try:
			blog_posts = paginator.page(page)
		except PageNotAnInteger:
			blog_posts = paginator.page(1)
		except EmptyPage:
			blog_posts = paginator.page(paginator.num_pages)
		return render(request, 'blog-posts-listing.html', {
			'page': self,
			'blog_posts': blog_posts
		})

	@route(r'^(?P<slug>[\w-]+)/$', name='single_post')
	def single_post(self, request, slug):
		post = get_object_or_404(BlogPost, slug=slug)
		return render(request, 'blog-post.html', {
			'page': self,
			'post': post,
		})	

	@route(r'^year/(\d+)/$')
	@route(r'^year/current/$')
	def posts_for_year(self, request, year=None):
		if year is None:
			year = datetime.date.today().year

		blog_posts = BlogPost.objects.filter(date_created__year=year)

		return render(request, 'blog-post-list.html', {
			'page': self,
			'blog_posts': blog_posts
		})
```

**Caveat:**  The code for `posts_by_year` is untested.

### Why I Think This is a Bug
The [documentation here](https://docs.wagtail.io/en/v2.10/topics/pages.html#more-control-over-page-rendering) says:

> All page classes have a serve() method that internally calls the get_context and get_template methods and renders the template.

I have verified that the `serve()` method is, in fact, called for each routable page route.  While I can see that `serve()` should not call `get_template()` for routable page routes, is there any reason `serve()` should not call `get_context()` for routable page routes?  Based upon the documentation above, I was thinking that `get_context()` **WOULD** be called.  If it is not useful to consider modifying Wagtail to call `get_context()` for routable page routes, would a note in the documentation about this behavior be in order?  I don't know if this is really a bug, but to me it certainly was unexpected behavior.

### Technical details

* Python version: 3.6
* Django version: 3.1
* Wagtail version: 2.10
* Browser version: N/A

**Comment by gasman** [comment]
Have opened #6363 to address this.
