### ISSUE TITLE
TableBlock content missing from admin when not on first tab

### ISSUE THREAD

**Issue by alexalligator** [wagtail/wagtail#6351]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The content of a TableBlock is missing from admin when the StreamField it belongs to is not the initially selected tab when the page is loaded. The table metadata fields (row header checkbox, table caption etc) are there, but not the actual table.

![Screenshot 2020-08-24 at 10 12 57](https://user-images.githubusercontent.com/22177249/91020170-6bb39900-e5f2-11ea-8f68-a00863af648a.png)

If the streamfield the tableblock belongs to is on tab 2 and you open the page editor, the table content will be missing as described above. If you select tab 2 and then reload the page editor the content will appear. So the problem isn't that the tableblock must be on the Content tab, but rather that the streamfield must be visible when the page editor is loaded.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Install `wagtail.contrib.table_block` in `base.py`
3. Add a `StreamField` to the `HomePage` that contains a `TableBlock`
4. Add the accompanying `StreamFieldPanel` to `promote_panels` (not `content_panels`)
```python
from wagtail.core.models import Page
from wagtail.core.fields import StreamField
from wagtail.core import blocks
from wagtail.admin.edit_handlers import StreamFieldPanel

from wagtail.contrib.table_block.blocks import TableBlock


class HomePage(Page):
    sidebar = StreamField(
        [("paragraph", blocks.RichTextBlock()), ("table", TableBlock(label="Tabell"))],
        blank=True,
    )

    promote_panels = Page.promote_panels + [StreamFieldPanel("sidebar")]
```
5. `migrate`, `createsuperuser` and open the home page editor in admin.
6. Add some content to the `StreamField`, including a`TableBlock` with some cell data
7. Save the page.
8. Reopen the home page editor
9. Open the Promote tab. The `TableBlock` is there but not the table widget with the cell data
10. Whilst still on the Promote tab, refresh the page. The table content should not appear.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes
* The table data is saved to the db and the front end works fine. It's just the table editing widget doesn't get initialised properly when its block is not visible on page load.

### Technical details

* Python version: 3.8.2
* Django version: Checked with 2.2 and 3.0.
* Wagtail version: Bug present in 2.10 and back at least as far as 2.8.1.
* Browser version: You can use Chrome 84.

**Comment by gasman** [comment]
Thanks for the report @alexalligator! I believe this is covered by the existing issue at #2687.

**Comment by alexalligator** [comment]
Sorry, did a search of issues but somehow didn't spot that one. Thanks! 👍
