### ISSUE TITLE
Custom user model regression in 2.10 for History view

### ISSUE THREAD

**Issue by Koed00** [wagtail/wagtail#6357]
### Issue Summary

Wagtail raises a "Cannot resolve keyword 'username' into a field" on the history view of pages.
This was working fine in 2.9.3 but broke in 2.10. Reverting to 2.9.3 solves the issue

### Steps to Reproduce

This only happens if you have a custom User model that has no `username` field but instead uses i.e. `USERNAME_FIELD='email'`
to indicate the substitute field. When `get_username` is called on the User model it then returns the email field value as the username.

By reverting to 2.9.3, the Revision page is now working correctly and is showing the emails as usernames in the history.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.8.5
* Django version: 3.0.9
* Wagtail version: 2.10

**Comment by gasman** [comment]
Hi @Koed00 - thanks for the report. This has been fixed in #6319 and will be part of Wagtail 2.10.1, to be released shortly.
