### ISSUE TITLE
Programmatically created pages with RichText field, do not preserve markup on publish

### ISSUE THREAD

**Issue by dcentrica** [wagtail/wagtail#6359]
### Issue Summary

We are programmatically creating `Page` subclasses in standard Django migrations, and most of these pages utilise Wagtail's `RichTextField`, each of which specifies a `default` attr - but _without_ markup.

The problem is that those fields that should be rich-text (having been declared using `RichTextField`), are saved to the database without markup (Kind of expected I suppose, given that we defined `default` sans markup), but when we go to publish these pages in the CMS itself, the markup is then saved into the DB - OK so far - but: We have many pages built like this, so I thought that by simply creating a new revision, saving and publishing it, as part of our existing migration logic, would deal to the problem, but it doesn't - basically sort of "pre-empting" a "Publish" operation that might ordinarily occur within the CMS, but done so in code.

Looking at the `RichTextField` class def itself, I see the following comment (We're using 2.8.1, but the same comment exists in `master:HEAD` also on GH in `fields.py:13`):

```
# TODO: preserve 'editor' and 'features' when deconstructing for migrations
```

Is this relevant to the problem?

Here's how I'm trying to deal with this in a migration:

**0001_add_pages.py**

```
from app import utils
from app.cms.page.root_page import ParentPage
import logging
...
...
log = logging.getLogger(__name__)


class Migration(migrations.Migration):
    dependencies = [
        ...
        ...
    ]

    def create(apps, schema_editor):
        page_types = [
            SomePageType,
            SomeOtherPageType,
        ]

        for child_page in page_types:
            try:
                utils.create_cms_page(ParentPage, child_page)
            except:
                log.error('Unable to pre-build CMS page: {}'.format(child_page.__name__))
                continue

    operations = [
        migrations.RunPython(create, reverse_code=migrations.RunPython.noop, hints={}),
    ]
```

**utils.py:**

``` 
def create_cms_page(root_cls, child_page, publish=True):
    """
    Utility method covering generic CMS page-creation logic from within migrations.
    """
    root_page = root_cls.objects.all().first()
    path_init = int('000100020003') # The last value for `path` from 0007_initialise_site_ttm.py
    title_raw = child_page.__name__.replace('Page', '')

    # Create instance of page (not yet stored in DB)
    page = child_page(
        title=convert_camel_to_human(title_raw),
        slug=title_raw.lower(),
        show_in_menus=True,
        content_type=ContentType.objects.get_for_model(child_page),
        path=path_init + 1,
        depth=2
    )

    # Add new page as child of the root_page (adds new record to DB)
    new_page = root_page.add_child(instance=page)

    if publish is True:
        # Create page revision to be published _now_
        new_page.save_revision().publish()
        # Create page revision - without publishing
        new_page.save_revision()
```

I'm happy to concede that some of these fields are not necessary / shouldn't or _needn't_ be added (New to Wagtail, DJango and Python in the last 4 months)

### Steps to Reproduce

1. [OK] Create a basic `Page` subclass containing a single field declared as `RichTextField` with a `default` attr comprising text _without_ markup
2. [OK] Create a migration as per the code above
3. [OK] Run the migration
4. [OK] Observe the page is created within the CMS
5. [FAIL] Observe that this page's DB record, contains markup for the relevant field (despite publishing within the migration)
6. [OK] Press the "Publish" button in the CMS
5. [OK] Observe that this page's DB record, now contains markup for the relevant field

What's different therefore between a "Publish" action performed from within the CMS, and one issued programatically in a migration?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: No

### Technical details

* Python version: 3.6
* Django version: 2.2
* Wagtail version: 2.8.1
* Browser version: Brave.latest

**Comment by dcentrica** [comment]
I have an idea what's going on - if I had thought about it (even longer!) I'd have figured it out! The page _is_ being published, but the markup isn't being added becuase _that is a client side thing_ - the JavaScript WYSIWG editor is the thing that performs the formatting! ...

**Comment by gasman** [comment]
It's not a client-side thing exactly - constructing the appropriate markup happens in the server-side code of the form field (`wagtail.admin.rich_text.editors.draftail.DraftailRichTextArea`), as opposed to the RichTextField model field. But yes, the outcome is the same - if you don't have the round-trip to a form field and back, a rich text value with missing or incorrect markup will remain unchanged on save or publish.

Closing as this is working as designed.
