### ISSUE TITLE
Load static files in django 3.0+

### ISSUE THREAD

**Issue by Weltfern** [wagtail/wagtail#6367]
### Is your proposal related to a problem?

 Static files loading problem in wagtail with django 3.0+ ... {% load staticfiles %}

### Describe the solution you'd like

Try to use  {% load static %} instead of  {% load staticfiles %}

### Describe alternatives you've considered

Also, Please include in the documents that user has to be make 'static' folder as well as 'templates'. you guys just mentioned 'templates' folder.

### Additional context

It's in this link  https://docs.wagtail.io/en/v2.0/advanced_topics/customisation/admin_templates.html

**Comment by gasman** [comment]
Hi @Weltfern,
You're looking at the documentation for Wagtail 2.0... the [current version](https://docs.wagtail.io/en/v2.10.1/advanced_topics/customisation/admin_templates.html) already uses `{% load static %}`.
