### ISSUE TITLE
Is nesting MultiFieldPanel supported?

### ISSUE THREAD

**Issue by Pithikos** [wagtail/wagtail#6374]
I am able to nest `MultiFieldPanel` without an issue. However the sub-headings don't show.

<img width="500px" src="https://user-images.githubusercontent.com/400048/92496741-6eb4a900-f1f0-11ea-9692-7d6247d9d070.png"></img>

models.py
```
      content_panels = [
        ..
        MultiFieldPanel([
            MultiFieldPanel([
                FieldPanel('primary_cta_button_label'),
                FieldPanel('primary_cta_url'),
                PageChooserPanel('primary_cta_page'),
            ], heading="Primary"),
            MultiFieldPanel([
                FieldPanel('secondary_cta_button_label'),
                FieldPanel('secondary_cta_url'),
                PageChooserPanel('secondary_cta_page'),
            ], heading="Secondary"),
        ], "Call to action")
        ..
      ]
```

I couldn't find much information on this and since I don't get any errors, I'd assume it might be a feature. It would be quite helpful since there are not any stylistic panels like dividers or headers from what I looked. Or am I doing something wrong?

**Comment by thibaudcolas** [comment]
This has been fixed as of Wagtail 4. Headings will show with a smaller font size when nested.

I don’t think this is explicitly documented anywhere, but we do expect built-in panels to be relatively flexible to support use cases like this.
