### ISSUE TITLE
Custom order not respected in snippet chooser

### ISSUE THREAD

**Issue by dany-nonstop** [wagtail/wagtail#6380]
In a project I'm working on, I have a Django Book model imported with the class Meta definition

````python
class Meta:
    proxy = True
    ordering = [F('rank').asc(nulls_last=True)] 
````

with the ElasticSearch search backend, I was wondering why the returned results are not in the right order.

As I dig deeper in wagtail's code here
https://github.com/wagtail/wagtail/blob/5e6a6746869d351eb2c55e092d6e669da1af896f/wagtail/snippets/views/chooser.py#L18-L37
I think I found the problem:

this is the query from `model.objects.all().query`
````sql
SELECT book.* FROM book ORDER BY book."rank" ASC NULLS LAST
````

However this is the compiled body for ElasticSearch query
````json
{
  "query": {
    "bool": {
      "must": {
        "multi_match": {
          "query": "text to search",
          "fields": [
            "_all_text",
            "_edgengrams"
          ]
        }
      }
    }
  }
}
````
Obviously there is no sort section in this query JSON and will get results *without* my defined order (order by "rank").

if I manually add this section to JSON query body, I would be able to get correctly ordered results
````json
{
  "sort": [
    {
      "rank_filter": {
        "order": "asc",
        "missing": "_last",
        "unmapped_type": "long"
      }
    }
  ]
}
````
Please advise if I understand the code wrong, and suggest how I could change this behavior.

**Comment by gasman** [comment]
Hi @dany-nonstop,
The default behaviour for search in Wagtail is to order by relevance, as determined by the search backend: https://docs.wagtail.io/en/stable/topics/search/searching.html#custom-ordering. This is consistent with how search results in general are expected to work - you'd want a website's search results page to return them in order of relevance even if the underlying model has `ordering = ['title']` specified.

Unless there's a strong reason for the snippet chooser's search to _not_ follow this convention, I'd say this is working as intended.

**Comment by dany-nonstop** [comment]
Hi @gasman thanks for the explanation. Actually even though this is the desired behavior, could you kindly advise, how to change the Book's meta or model manager, to enable custom search? I don't find a place to call the backend's .search() method in that proxy Book model.

The reason I need the custom search, is this: in our current database of 5 million records, many have same name (therefore same relevance score), just imagine how hard to use the snippet chooser to find the select from hundreds with matched titles.  Therefore I want to promote the ones with lower internal ranks to make the result more relevant. thanks again for the prompt reply.
