### ISSUE TITLE
NoReverseMatch at /sitemap.xml Reverse for 'entry_page_serve_slug' with keyword arguments '{'blog_path': '', 'year': '2020', 'month': '08', 'day': '22', 'slug': 'algorithmic-trading-the-basics-part-1'}' not found. 1 pattern(s) tried: ['(?P<slug>[^/]+)/$']

### ISSUE THREAD

**Issue by zzm88** [wagtail/wagtail#6381]
This happens when I try to use sitemap as the documentation of Wagtail.

C:\Users\zzm\OneDrive\projects\subtitle_library\sub-library3.8\lib\site-packages\django\urls\resolvers.py in _reverse_with_prefix

line 677. raise NoReverseMatch(msg) 

Variable | Value
-- | --
_prefix | '/'
arg_msg | ("keyword arguments '{'blog_path': '', 'year': '2020', 'month': '08', 'day': "  "'22', 'slug': 'algorithmic-trading-the-basics-part-1'}'")
args | ()
converters | {'slug': <django.urls.converters.StringConverter object at 0x0547D250>}
defaults | {}
kwargs | {'blog_path': '',  'day': '22',  'month': '08',  'slug': 'algorithmic-trading-the-basics-part-1',  'year': '2020'}
lookup_view | 'entry_page_serve_slug'
lookup_view_s | 'entry_page_serve_slug'
m | None
msg | ("Reverse for 'entry_page_serve_slug' with keyword arguments '{'blog_path': "  "'', 'year': '2020', 'month': '08', 'day': '22', 'slug': "  "'algorithmic-trading-the-basics-part-1'}' not found. 1 pattern(s) tried: "  "['(?P<slug>[^/]+)/$']")
n | None
params | ['slug']
pattern | '(?P<slug>[^/]+)/$'
patterns | ['(?P<slug>[^/]+)/$']
possibilities | [([('%(slug)s/', ['slug'])],   '(?P<slug>[^/]+)/$',   {},   {'slug': <django.urls.converters.StringConverter object at 0x0547D250>})]
possibility | [('%(slug)s/', ['slug'])]
result | '%(slug)s/'
self | <URLResolver 'mysite.urls' (None:None) '^/'>

**Comment by gasman** [comment]
Hi @zzm88,
The error here is happening on the URL route `entry_page_serve_slug`, which doesn't match anything in Wagtail itself, so I believe this is caused by your own code.

If you're able to replicate this on a fresh Wagtail project, please open a new issue, giving full details of how to reproduce it independently, and the full stack trace of the error.
