### ISSUE TITLE
Reports main menu item has extra left padding

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#6382]
In the main menu, the "Reports" item doesn't line up with the others. For some reason, it has more left padding than the others

![image (5)](https://user-images.githubusercontent.com/1093808/93082726-58439d00-f689-11ea-9ef6-810660c9bc33.png)

Confirmed on 2.10 and master. This has probably been like this since 2.9 when we introduced this item.

**Comment by gasman** [comment]
This was reported earlier in #6327 and fixed in #6329 for 2.10.1 - is it possible you didn't rebuild CSS when testing on master?

**Comment by kaedroho** [comment]
Nice, thanks!
