### ISSUE TITLE
Stop using <input type="button" ...

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#6388]
### Issue Summary

It looks like we _do_ use `<input type="button" ...` in the style guide ([L508](https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html#L508), [L519](https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html#L519), [L530](https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html#L530)), which we probably should stop doing given that it says on that very same same page not to do so.

### Steps to Reproduce

1. Search te code for `<input type="button"

Refs: https://github.com/wagtail/wagtail/pull/6369#pullrequestreview-489947548

**Comment by Scotchester** [comment]
Closed via https://github.com/wagtail/wagtail/commit/3ab18aa901ddf6b7152e6d0a547cf7c2a7d054e3 in #6388
