### ISSUE TITLE
Center Align option for image formats 

### ISSUE THREAD

**Issue by JaredOzzy** [wagtail/wagtail#6390]
Im trying to add a center-align to my image formats for wagtail, im not sure where i can add this line of code to allow me to have the center-align option as full-width and center-align are definitely two different things.

since all these styles need to be manually created in the projects css it would be nice to have an extra option for center-align...

I would like to add this line of code somewhere to add the extra format option.
`register_image_format(Format('center', _('Center-aligned'), 'richtext-image center', 'width-500'))`

Here is the source from where i see it being done.
https://github.com/wagtail/wagtail/blob/bb2e460c0b92fba802fc3f369730004d6b648e64/wagtail/images/formats.py#L94

I am using this in a StreamBlock, i have added the image to the richtext editor even though i know it has been removed. 
For my case the client doesn't want to add a new stream block image item, then add the image then create a new streamblock richtext item to finish off the article text.

I have looked at the following question which is similar but not ideal:
https://stackoverflow.com/questions/62629225/image-with-full-width-format-not-centered-in-wagtails-richtextfield

**Comment by gasman** [comment]
Hi @JaredOzzy - this is documented at https://docs.wagtail.io/en/stable/advanced_topics/customisation/page_editing_interface.html#image-formats-in-the-rich-text-editor.

**Comment by JaredOzzy** [comment]
Wow thanks, apologies i was literally on that page looking for an answer and stopped scrolling before that part.
