### ISSUE TITLE
Gigantic buttons in moderation panel on the admin dashboard

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#6396]
# Issue Summary

![image](https://user-images.githubusercontent.com/1093808/93866488-9f501480-fcbf-11ea-9a1e-729bd9d8d02f.png)

### Technical details

This looks like it was caused by adding `page-editor.css` to the dashboard (sidenote: the fact that we have to keep doing this indicates we have a wider issue with how we're bundling CSS).

This CSS file contains a rule that adds `font-size: 2em;` to the selector `.title input`: https://github.com/wagtail/wagtail/blob/33e4c0ec7b889131740ee66a954f4ca2293fc2dd/wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss#L419-L424

By coincidence, this rule matches the action buttons in the moderation panel on the dashboard, making the buttons appear large:

`.title` class added here: https://github.com/wagtail/wagtail/blob/1267468c4cee8104ed7a13e67c3b6621fa5b40a6/wagtail/admin/templates/wagtailadmin/home/pages_for_moderation.html#L23
`input` tag here: https://github.com/wagtail/wagtail/blob/1267468c4cee8104ed7a13e67c3b6621fa5b40a6/wagtail/admin/templates/wagtailadmin/home/pages_for_moderation.html#L40

* Wagtail version: 2.10.1
* Browser version: Firefox 80

**Comment by zerolab** [comment]
Aside from the fact that page-editor.css is included, the button issue is similar to #6369 in that we are overly broad with inputs

**Comment by gasman** [comment]
Fixed in #6397
