### ISSUE TITLE
Orderable InlinePanel is not order elements correctly after save on Wagtail panel

### ISSUE THREAD

**Issue by bplociennik** [wagtail/wagtail#6404]
### Issue Summary

I'm using `InlinePanel` on my model and when I change order on it and save after reloads I still see the same ordering - I think by ID not by `sort_order`.

```
class PhoneNumber(Orderable):
    general_setting = ParentalKey(
        "wagtail_settings.GeneralSetting",
        on_delete=models.CASCADE,
        related_name="phone_numbers",
    )
    phone = models.CharField(_("phone"), max_length=30)
    panels = [FieldPanel("phone")]

    def __str__(self):
        return self.phone

    class Meta:
        verbose_name = _("phone number")
        verbose_name_plural = _("phone numbers")
```

In my another I'm inserting it to my model using:
```
MultiFieldPanel([InlinePanel("phone_numbers")], heading=_("phone numbers"))
```

![image](https://user-images.githubusercontent.com/6594923/94116657-9ab86700-fe4b-11ea-8ffa-a5bd2d1c28dc.png)

`sort_order` from the first image:
```
[
        {
            "sort_order": 1,
            "phone": "aaaaaa"
        },
        {
            "sort_order": 2,
            "phone": "bbbbbb"
        },
        {
            "sort_order": 3,
            "phone": "cccccc"
        }
    ]
```
I made some clicking to set another ordering for elements:
```
[
        {
            "sort_order": 1,
            "phone": "aaaaaa"
        },
        {
            "sort_order": 0,
            "phone": "bbbbbb"
        },
        {
            "sort_order": 2,
            "phone": "cccccc"
        }
    ]
```
On wagtail frontend it still showing the same ordering:
![image](https://user-images.githubusercontent.com/6594923/94117328-5e393b00-fe4c-11ea-8d94-f229de671544.png)

It looks like this Panel is not respecting `ordering` from Orderable abstract model:
```
    class Meta:
        abstract = True
        ordering = ['sort_order']
```

Backend saves `sort_order` correctly.
Excepted behaviour: records should be sort by `sort_order` if we are using `Orderable model`

### Steps to Reproduce

1. use my model above and add to some fresh model
2. insert InlinePanel in fresh model to see
3. check

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: I'm not sure

### Technical details

* Python version: `3.8.2`.
* Django version: `3.1.1`.
* Wagtail version: `2.10.1`.
* Browser version: `Chrome 85`

**Comment by gasman** [comment]
Hi @bplociennik,
When you use `class Meta` on a model that inherits from `Orderable`, you need to [specify the inheritance on the Meta class too](https://docs.djangoproject.com/en/3.1/topics/db/models/#meta-inheritance):

    class PhoneNumber(Orderable):
        # ...
        class Meta(Orderable.Meta):
            verbose_name = _("phone number")
            verbose_name_plural = _("phone numbers")

We're currently working on adding a system check to warn if this is missing: #6273

**Comment by bplociennik** [comment]
Thanks, @gasman ohh yes is working. I know why it didn't work for me because there is option to have the same `sort_order` value and it's why I just removed `Orderable.Meta`.

```
[
        {
            "sort_order": 1,
            "phone": "cccccc"
        },
        {
            "sort_order": 2,
            "phone": "bbbbbb"
        },
        {
            "sort_order": 2,
            "phone": "aaaaaa"
        }
    ]
```
so it's shouldn't be an option to have the same values here ^
