### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by joeshua** [wagtail/wagtail#6416]
**Any one click droplets which are coming up in the near future in the DO or another services?**

**Comment by gasman** [comment]
Hi @joeshua,
That would really be a question for those services, rather than Wagtail itself...
[Divio](https://www.divio.com/) and [CodeRed](https://www.coderedcorp.com/blog/calling-all-django-wagtail-devs-beta-testers-wante/) both offer cloud hosting solutions for Wagtail.
