### ISSUE TITLE
Checkboxes broken on Edge (legacy)

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#6421]
Checkboxes are being displayed like this on Edge (and they don't appear to do anything when clicked):

![image](https://user-images.githubusercontent.com/1093808/94793681-c4850700-03d2-11eb-8639-0d529a34459f.png)

I'm testing with:
Microsoft Edge 44.19041.423.0
Microsoft EdgeHTML 18.19041

Wagtail master with i18n and alias pages

Note that Edge Legacy is the default browser that ships with Windows 10

**Comment by loicteixeira** [comment]
Maybe related to #6439?

**Comment by kaedroho** [comment]
I think it might be actually! I'll give that PR another try on IE and see if it fixes it

**Comment by kaedroho** [comment]
This doesn't affect IE11, or the Chromium version of Edge. Only Edge Legacy

**Comment by lb-** [comment]
Fixed with #6441 
Screenshot below (Edge 18)
![download](https://user-images.githubusercontent.com/1396140/99899944-90560480-2cf8-11eb-9783-c8419fbf7a04.png)
