### ISSUE TITLE
Checkbox and radio inputs visually off in admin

### ISSUE THREAD

**Issue by cole** [wagtail/wagtail#6439]
### Issue Summary

Checkboxes and radio buttons look broken in 2.10.2. Downgrading to 2.10.1 fixes the issue.

<img width="206" alt="Screen Shot 2020-10-05 at 7 08 07 PM" src="https://user-images.githubusercontent.com/134694/95151131-b884a680-073e-11eb-96ef-4d896c35ee75.png">

Notice the grey box and the alignment of the checkbox.
This seems to have been caused by adding `:not([type=submit])` to inputs, increasing the selector specificity.

### Steps to Reproduce

1. Have a page with a boolean field visible via Wagtail admin.
2. View the checkbox on the admin page

### Technical details

* Python version: 3.7.7
* Django version: 3.0.10
* Wagtail version: 2.10.2
* Browser version: Safari 14 / Chrome 85 / Firefox 81

**Comment by lb-** [comment]
Fixed via #6441 

![Screenshot_2020-11-22 Wagtail - Editing Form page Contact Us](https://user-images.githubusercontent.com/1396140/99899995-107c6a00-2cf9-11eb-9a69-8aae886a924d.png)
![Screenshot_2020-11-22 Wagtail - Editing Breads index page Breads](https://user-images.githubusercontent.com/1396140/99899997-11ad9700-2cf9-11eb-87c6-af1278a26ae5.png)
