### ISSUE TITLE
Support large document uploads

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#6444]
I asked a question in slack and didn't get a response.   I occasionally have large documents (i.e. product pdfs and such) that should be downloadable.  However, I don't want to allow arbitrarily large uploads through nginx or whatever frontend is in use.  I do not see a simple way to hook in here.

In [wagtailmedia we allowed the site to provide a custom base form](https://github.com/torchbox/wagtailmedia/blob/master/wagtailmedia/forms.py#L47) to set custom widgets to handle this case.  Would you accept this approach?

Since very large documents are out of the ordinary, it doesn't concern me that they are not compatible with the multi-uploader javascript so I would be happy if it was restricted to the single document upload form.  But it would be helpful if there was a handy link on the multi-upload form users reach by default to upload a single document.  And perhaps a way to nudge users to use this form if their upload fails because the file is too large

**Comment by gasman** [comment]
Hi @thenewguy,
I'm not really clear on how a custom widget will help to get around upload size limits - can you give an example?

**Comment by thenewguy** [comment]
@gasman We use a widget that stores chunks of a file in a different model uploaded using resumable.js - so it lets you upload lots of segments of 1mb or whatever - and then use a celery task to join them and present that as the uploaded file

**Comment by thenewguy** [comment]
I could come up with some other examples if you need them - for example I am sure you could write a widget that integrated with something like s3 direct upload - but that's the one I wrote and settled on

**Comment by thenewguy** [comment]
@gasman Have you given this any thought?  I am in the process of sampling the newer changes to wagtail by converting an older site.  I just uploaded a 222mb video file using this approach in wagtailmedia without any trouble.  Regular file uploads (documents for example) in the wagtail dashboard fail on files over 10mb on this particular site

**Comment by gasman** [comment]
@thenewguy Thanks for clarifying! Yes, that sounds like a good plan - we do need a more flexible way of customising those forms beyond just passing a list of field names.

I'm not a huge fan of adding settings, and longer term, I'd like to move away from customising Wagtail apps through settings and hooks, in favour of something more Pythonic where the functionality of an app like wagtail.documents is encapsulated in a Python class, and the models, forms and views are properties that can be overridden. ([Viewsets](https://github.com/wagtail/wagtail/blob/master/wagtail/sites/views.py) were a step in that direction...) But there's a lot of figuring-out and refactoring required for that to happen, so in the interest of not getting held up, I think a setting for the base form is indeed the way to go for now.

**Comment by gasman** [comment]
Implemented in #6462.
