### ISSUE TITLE
Privacy button cut off in settings if there are additional panels

### ISSUE THREAD

**Issue by nmorduch** [wagtail/wagtail#6446]
### Issue Summary

Privacy button is cut off at the bottom if there are more panels after it. This is in part because of `.field-row`'s negative margin bottom, but removing that still leaves it without white space between the button and the next panel.
 
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/1051450/95220094-16a79d00-07c4-11eb-8a85-79a617e148ae.png">

### Steps to Reproduce

Add another `FieldPanel` to the `settings_panels` after the privacy panel

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **No**

### Technical details

* Python version: 3.6.4
* Django version: 3.0.7
* Wagtail version: 2.10.2
* Browser version: Firefox 82, Chrome 85

**Comment by gasman** [comment]
Fixed in #6454
