### ISSUE TITLE
IE11 focus highlight on every other element

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#6447]
### Issue Summary

When using tab to navigate the admin in IE11, every other element is not highlighted.
On `tab` the body class `focus-outline-on` changes to `focus-outline-off`.

### Steps to Reproduce

1. Open the admin in IE11
2. Open the developer console to inspect the body class
2. Click in the page and press tab a couple of times
3. Every other item has the focus outline

### Technical details

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: YES
* Current master via https://github.com/wagtail/gitpod-wagtail-develop
* Browser stack IE11

**Comment by gasman** [comment]
Closing as IE11 support is being dropped in 2.15.
