### ISSUE TITLE
News items from multi-site incorrectly displayed in Main site

### ISSUE THREAD

**Issue by e-mojo** [wagtail/wagtail#6448]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Articles end up on two websites, even though only created at 1 website within the multi-site structure. The strange thing is that it is 1 way, the main site lists items from other sites, but not the other way around.

### Steps to Reproduce

I have created a Wagtail multi-site. Within it, I have a BlogOverviewPage where all Blog items are listed. The problem is that the "main site" also lists Blog items for other sites. I have been experimenting using different queries in get_context, but without any luck. 

```python
def get_context(self, request):
    context = super().get_context(request)
    context['blogpages'] = self.get_children().live().order_by('-go_live_at')
    return context
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I consider it a bug, since the article ends up on two websites. Even though the particular article isn't a CHILD of the MAIN SITE.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

Haven't tried this

### Technical details

* Python version: Run `python --version`. Python 3.7.9
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`. Django 3.1
* Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`. Version 2.10.2
* Browser version: You can use https://www.whatsmybrowser.org/ to find this out. Chrome 85

**Comment by gasman** [comment]
Not sure we'll be able to do much here without a full reproducible test case... however, one thing to try is running `./manage.py fixtree` and see if reports any issues.

**Comment by e-mojo** [comment]
When running fixtree, there were no issues. I have however managed to solve it through:
```
        site = Site.find_for_request(request)
        return BlogPage.objects.live().in_site(site).order_by('-go_live_at')
```
I will see if this was a local problem, or not, at a later stage and inform you accordingly (and re-open the ticket). Thanks!
