### ISSUE TITLE
INTERNAL SERVER ERROR ON Orderable.save()

### ISSUE THREAD

**Issue by alvindera97** [wagtail/wagtail#6455]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
**INTERNAL SERVER ERROR** when saving an `Orderable` item with or without a corresponding `Page` object. The error is of the nature:

 **Internal server error**
**Sorry, there seems to be an error. Please try again soon.**
(this [above] is the only text displayed on the browser widow)

_**A summary of the issue**._
This error happens specifically when [programmatically] saving an `Orderable` object with the call to `save()`. This `Orderable` object may be associated with a `Page` object (as described in the sample code below). After _defining_, _saving_ and _publishing_ the `Page` object, the `Orderable` object is defined (with the `ParentKey` pointing at the `Page` object). A call to `save()` on the `Orderable` object produces a **Internal Server Error** on initialization of the test. A call to **save()** on the **Page** object (this is the second call to **save()** for the **Page** object after the initial save following `save_revision().publish()`) produces the same **Internal Server Error** on initialization of the test. 

**The test is a functional test using Chrome as the web driver.** 

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Edit **models.py** as follows...

• **home / models.py**
```
class HomePage(Page):
    content_panels = Page.content_panels + [
        InlinePanel('homepage_content', label="Homepage Content")
    ]
    template = 'home.html'


class HomePageContent(Orderable):
    page = ParentalKey(HomePage, on_delete=models.SET_NULL, related_name='homepage_content', null=True)
    principal_welcome_message = models.TextField()
    the_way_we_teach = RichTextField()
    meet_our_teachers = RichTextField()
    meet_our_students = RichTextField()

    # Editor panels configuration

    panels = [
        FieldPanel('principal_welcome_message'),
        FieldPanel('the_way_we_teach'),
        FieldPanel('meet_our_teachers'),
        FieldPanel('meet_our_students'),
    ]

```

3. Edit **tests.py** as follows...

• **home / test.py**

```
class HomePageTestCase(StaticLiveServerTestCase, TestCase):
    browser: object
    empty_link: str
    link_back_to_the_home_page: str
    carousel_link: str

    @classmethod
    def setUpClass(cls):
        if Page.objects.count() == 0:  # if there is no page object (specifically we are targeting the root page's existence)
            cls.root = Page.objects.create(title="Root", path='001', depth=1)  # set up a root page
        else:
            cls.root = Page.objects.get(title="Root").specific

        # set up the home page
        cls.school_home_page = HomePage(title="Home Page")
        cls.root.add_child(instance=cls.school_home_page).save_revision().publish()  # publish the home page

        # Create site object if there isn't any
        if Site.objects.first():
            cls.site = Site.objects.first()
        else:
            cls.site = Site.objects.create(
                site_name="localhost",
                is_default_site=True,
                root_page=cls.root
            )

        cls.site.root_page = cls.school_home_page
        cls.site.save()
        super(HomePageTestCase, cls).setUpClass()

        # set up the HomePageContent object
        cls.home_page_content = HomePageContent(
            page=cls.school_home_page,
            principal_welcome_message="Default statement",
            the_way_we_teach="Default Tech",
            meet_our_teachers="Default developers",
            meet_our_students="Default analysts"
        )
        cls.home_page_content.save()

    def setUp(self):
        self.browser = webdriver.Chrome()
        self.browser.implicitly_wait(3)
        self.empty_link = self.live_server_url + '/#'
        self.link_back_to_the_home_page = self.live_server_url + '/'
        self.carousel_link = self.live_server_url + '/#what-our-customers-are-saying'

    def tearDown(self):
        self.browser.quit()

    def check_displayed(self, element: WebElement) -> None:
        self.assertTrue(element.is_displayed(), True)

    def test_home_page_loads_correctly(self):
        self.browser.get(self.live_server_url)
        # the rest of the test can go in here. What I am trying to point out is that
        # there is an internal server error even before the test methods are executed.
        # Any assertions made here would show in the console trace back as AssertionErrors or AttributeErrors or 
        # NoSuchElementExceptions. 
```

4. Run the test [via the terminal]: `python manage.py test home`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
_I consider this a bug because, if you don't call_ `home_page_content.save()`, _the test would run fine, but clearly there is no_ `HomePageContent` _object_. 

**_The aim of setting up a_** `HomePageContent` **_object in_** `setUpClass` **_is defeated an the rest of the test carries on without any issues._** 

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

• **ANOTHER THING I WOULD LIKE TO NOTE IS THAT I HAVE USED MULTIPLE INHERITANCE IN THE TEST CLASS BECAUSE WHEN THIS TEST CLASS IS RUNNING MULTIPLE TEST CASES, IT FAILS TO KEEP ALL SETUP DATA IN MEMORY (FROM WHAT I RESEARCHED, WHEN THE BROWSER CLOSES, ALL DATABASE INFORMATION AND SCHEMA ARE LOST TOO)**.

• **MULTIPLE INHERITANCE OF** `StaticLiveServerTestCase` **AND** `TestCase` **WORK FINE AND DATABASE INTEGRITY IS MAINTAINED DURING MULTIPLE TESTS.**

### Technical details

* Python version: **Python 3.6.9**
* Django version: **3.1.2**
* Wagtail version: **2.10.2**
* Browser version: https://www.whatsmybrowser.org/b/Y8H8M

**Comment by gasman** [comment]
Hi @alvindera97 - thanks for the report.
I followed the steps as described and received the Internal Server Error, but after I created a template at `home/templates/home.html` the test completed successfully.

I don't have a lot of experience with Selenium, so I don't know whether it's expected behaviour for it to return an Internal Server Error rather than a more meaningful error message - but either way, that's a Django / Selenium issue rather than a Wagtail one.

**Comment by alvindera97** [comment]
I would like to ask, why is it that the [dreaded] **Internal Server Error** is the only thing a developer is left with? You have to basically start poking in the dark to try and solve whatever might have caused this issue. It makes development with Wagtail a mortifying experience especially when Test Driven Development is involved. 

From Wagtail's documentation, there is absolutely no [serious] interest in the encouragement of tests. All [relevant] classes are not described to their absolute base. 

I abandoned the initial process I was following up [this issue]: https://github.com/wagtail/wagtail/issues/6455#issue-718890480, and tried other methods hoping that I would make headway. The lack of a vibrant question answering community with wagtail takes life with Wagtail Development to a whole new level of pain. 

At the company I work at, Wagtail is first in line to be removed from the tech stack as it just doesn't encourage testing [at least from the documentation]. Wagtail's test suite is mediocre in size and it simply just feels that it's there for the sake of "testing".... I have been revolving around the same set of unbelievably small issues for almost 4 days now. It's very very very very unattractive. 

I love the effort and work that you've put into this project, however, debugging and trace backs are the life line of any python developer. Debugging in wagtail is painful. Very little cues at to what's going on and what's gone wrong. 

Since StackOverflow is a graveyard of people only interested in answering simple questions, I figured that the best way to get results would be from opening issues here.
