### ISSUE TITLE
Red fields in UI give error impression 

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#6476]
### Problem

On a Wagtail YouTube video https://youtu.be/nBNb7k0BMP4 a comment is placed about reds in the admin ui:

> vinny142
> So are you going to change the red field label color to something that does not keep making me thing there's an error? :-) Please? I've shown Wagtail to lots of potential users and they all keep asking me why there are errors on the screen when they open it.

### Solution

Do not use reds in a UI, unless it is an error or error related indicator.

### Additional context

Maybe this is one of those things that surprises new users. Quickly forgotten once you get used to it. 
But it is the wrong first impression, and easy to avoid. 

I also don't know any user interface with reds near input fields (probably for the same obvious reasons).

**Comment by thibaudcolas** [comment]
We’ve significantly changed the designs for forms’ layout in Wagtail 4, as of #8921. Closing!
