### ISSUE TITLE
If you add an ' or a " to the StreamField block name the UI does not open

### ISSUE THREAD

**Issue by heav1811** [wagtail/wagtail#6482]
When creating a StreamField, if your block's name has a ' or a ", the UI will not open.

Example: 
`section = StreamField([("PageColumn's", somerandomstreamblock())],)`

version is 2.10.1
python 3.8
django 3.1

**Comment by gasman** [comment]
Hi @heav1811,
As per the docs, [block names must be valid Python variable names](https://docs.wagtail.io/en/stable/topics/streamfield.html#using-streamfield):
> ‘name’ is used to identify the block type within templates and the internal JSON representation (and should follow standard Python conventions for variable names: lower-case and underscores, no spaces)

In Wagtail 2.11 we've introduced a stronger check for this, and invalid names will throw an error on startup: #6295
