### ISSUE TITLE
StreamField blocks are below menu in admin page. Should have margin

### ISSUE THREAD

**Issue by ivaniclixx** [wagtail/wagtail#6496]
### Issue Summary

StreamField is shown below menu on the left, in the admin page
Screenshot: [image](https://ibb.co/mFNkv0m)

<img width="1097" alt="Screen Shot 2020-10-25 at 22 57 09" src="https://user-images.githubusercontent.com/16993298/97120540-05ddad80-1718-11eb-9aa6-98eae319c5f2.png">

### Steps to Reproduce
Just add an StreamField in your Page model and try to add a Block.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

- Wagtail 2.10.2 fresh installation.
- Firefox 81.0.2
- Chrome 86.0.4240.111

**Comment by gasman** [comment]
Hi @ivaniclixx - thanks for the report.

Please can you share the page model code you're using? This doesn't happen when testing against the [bakerydemo](https://github.com/wagtail/bakerydemo) project, so I suspect this must be something specific to your code (e.g. the `content_panels` definition). Also, please try force-refreshing the page in your browser - it's possible that you have CSS from an older Wagtail version cached.

**Comment by ivaniclixx** [comment]
You are right about the models.py, I was using a "full" classname. Sorry for the trouble, It's now looking right.

Thank you for the quick support.
