### ISSUE TITLE
Table tags in RichTextField

### ISSUE THREAD

**Issue by alramalho** [wagtail/wagtail#6497]
### Is your proposal related to a problem?

Yes,
I was programmatically uploading a product to my wagtail CMS, and wanted to save some fields as a `<table>` tag. 
When doing so, these got unformatted and I had to go with list (`<li>`), which is not perfect.

### Describe the solution you'd like

Support for `<table>` tags in `RichTextField` would suffice. 

### Describe alternatives you've considered

I used `<ul>` and `<li>` tags.

**Comment by zerolab** [comment]
Hi @alramalho 

Tables are deliberately not supported in `RichTextField`. You can read the reasoning behind it at https://torchbox.com/blog/rich-text-fields-and-faster-horses/

You can get decent support for tables with the https://docs.wagtail.io/en/stable/reference/contrib/table_block.html StreamField block. Or, if you **_absolutely_** must support tables in `RichTextField` then you https://docs.wagtail.io/en/stable/advanced_topics/customisation/extending_draftail.html lays the foundation on how that can be achieved.
