### ISSUE TITLE
Pasting content into Hallo rich text fields retains HTML text styles from source

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#65]
If you copy any section of text from wagtail.io (for example) and paste it into a text area, it retains lots of styles you wouldn't want to be copied into your site. 

Of course _wagtail strips style attribute upon saving_ but I'd expect most users would probably grimace and try to somehow undo it, fail, and get themselves in a complete mess before thinking of saving.

This example is somewhat contrived, but as we know from users of Word, people paste anything from anywhere without thinking, and why not? If we're to make content entry the experience we want it to be, this needs addressing.

**Comment by thibaudcolas** [comment]
This issue isn't present in Draftail, but of course still present in Hallo. Draftail doesn't display any kind of message, it just strips the formattings that are not whitelisted.
