### ISSUE TITLE
Internationalisation documentation issue 2.11rc1

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#6504]
Maybe docs need to improve slightly.
I have setup wagtail. According docs. International seems to work. I see in admin hen creating a page choice for language.  I also see in API the locale tag. So I think I set everything correct up.

However Its unclear how to translate a page. I don't see any button or any way to translate.

I do the following:
1. create homepage (english)
2. link that homepage in wagtail setting as root page
3. ???

- tried to copy the page
- tried to make extra homepage in dutch
- tried to create 2 wagtail configurations
- tried to reconfigure, restart project etc ... 

Nothing works to setup the translation. Nor the ?translation_of=... gives me translations

I'm missing some crucial information how to start and how the wagtail tree is copied over. I more ore less expect a button so I can jump from the english version to the dutch version.

Or some setting in base.py where you can say copy_tree=True ... 

My request how to make docs a bit more clear? I must doing something wrong?

The docs say

_Translated homepages
_When you set up a site in Wagtail, you select the site’s homepage in the ‘root page’ field and all requests to that site’s root URL will be routed to that page._

_Multi-lingual sites have a separate homepage for each locale that exist as siblings in the page tree. Wagtail finds the other homepages by looking for translations of the site’s ‘root page’._

_This means that to make a site available in another locale, you just need to translate and publish its homepage in that new locale._

_If Wagtail can’t find a homepage that matches the user’s language, it will fall back to the page that is selected as the ‘root page’ on the site record, so you can use this field to specify the default language of your site._

**Comment by gasman** [comment]
Hi @onno-timmerman,
The internationalisation support built into Wagtail 2.11 only provides the infrastructure for creating and serving content in multiple languages - for managing translations between languages, you additionally need the [wagtail-localize](https://github.com/wagtail/wagtail-localize) app. Will update the docs to make this clearer.

**Comment by Warqus** [comment]
A follow up question for me would be how to link multiple languages to one site in site settings? 
It would be nice if you can link one site to multiple roots (with each different language of course) in the site settings.
