### ISSUE TITLE
SnippetChooserPanel shows all snippets, instead of just the language of the page you're editing

### ISSUE THREAD

**Issue by Warqus** [wagtail/wagtail#6505]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Whenever adding internationalization to snippets (in my case a header), you can do so in a selected language; see image below:

English headers:
![image](https://user-images.githubusercontent.com/14151318/97843068-f0085380-1ce8-11eb-818e-b3a0615a01de.png)

Dutch headers:
![image](https://user-images.githubusercontent.com/14151318/97843028-e121a100-1ce8-11eb-854e-a6b002c701b0.png)

However, whenever I want to choose a header in my (English) homepage, I see all header snippets (without their language option); see below:

![image](https://user-images.githubusercontent.com/14151318/97842841-9acc4200-1ce8-11eb-98fb-d2cb0b1b877f.png)

I would assume only the English headers would be visible.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. add a Snippet with TranslatableMixin
3. add Snippet in wagtail admin interface
4. add Snippet option to custom page

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I would assume only the English headers would be visible.
* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7
* Django version: 3.1.2
* Wagtail version: 2.11rc1

**Comment by zerolab** [comment]
I believe this relates to #6230

**Comment by gasman** [comment]
@kaedroho Just to check - can you confirm that this has been intentionally left out of the 2.11 release (not just overlooked)?

**Comment by Warqus** [comment]
@kaedroho Can you provide an answer to Gasman's question? That would really help me out. If the answer is that it is intentionally left out, will it be included in the future?

**Comment by zerolab** [comment]
@Warqus I believe this was fixed by #6699 and available in 2.15
Can you check/confirm?

**Comment by lb-** [comment]
can confirm this is fixed as of 2.15 and re-validated on 4.1a (in development)

Page in a language will automatically show only the snippets in that language, can be switched with a drop-down within the chooser though.

<img width="1448" alt="Screen Shot 2022-09-19 at 9 28 32 pm" src="https://user-images.githubusercontent.com/1396140/191007631-9c770009-0ba0-45e8-97f0-0ecf8162c7d4.png">
<img width="1294" alt="Screen Shot 2022-09-19 at 9 28 24 pm" src="https://user-images.githubusercontent.com/1396140/191007642-5a72d52e-c95e-476f-8572-55954a8ff26e.png">
<img width="1329" alt="Screen Shot 2022-09-19 at 9 28 19 pm" src="https://user-images.githubusercontent.com/1396140/191007643-48155ace-31fb-4c4c-b637-d7cf8dce0e36.png">
