### ISSUE TITLE
Wrong Live URLs in admin if preferred language is set

### ISSUE THREAD

**Issue by jozo** [wagtail/wagtail#6531]
### Issue Summary

Wrong URLs are created in Wagtail admin if user's preferred language is not one of the LANGUAGES defined settings.py. User can for example select in their account's settings that they prefer "czech" language. Even though only available LANGUAGES in settings.py are "slovak" and "english". The "Live" buttons urls are prefixed as for czech language and so returns 404.

### Steps to Reproduce
1. In settings.py I have:

```python
LANGUAGES = [
    ("en", _("English")),
    ("sk", _("Slovak")),
]
WAGTAIL_CONTENT_LANGUAGES = [
    ("en", _("English")),
    ("sk", _("Slovak")),
]
```

in urls.py:
```python
urlpatterns += i18n_patterns(
    url(r"", include(wagtail_urls)),
)
```

2. Login to Wagtail and set Prefered language to different than "en" or "sk".
3. Check URLs in "Live" - they are prefixed with the preferred language even though the url return 404.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I expect URLs will be prefixed with one of the available lanugages.

The problem is in /wagtail/admin/auth.py > require_admin_access
```python
if hasattr(user, 'wagtail_userprofile'):
    preferred_language = user.wagtail_userprofile.get_preferred_language()
    l18n.set_language(preferred_language)
```

**Also note**: If user selects as prefered language "Slovak" it still doesn't work because it's saved as `sk-sk` and so URLs are prefixed with `sk-sk` insteand of `sk` and so it still returns 404.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.8.6
* Django version: 3.1.3
* Wagtail version: 2.11.1
* Browser version: Firefox 82

**Comment by gasman** [comment]
Hi @jozo - thanks for the report.

The only way I can replicate this behaviour is by leaving `WAGTAIL_I18N_ENABLED` set to False - given that you're setting `WAGTAIL_CONTENT_LANGUAGES`, I'm assuming that you're intending to use Wagtail 2.11's i18n support? If so, setting `WAGTAIL_I18N_ENABLED = True` should fix this.

(Using `i18n_patterns` without Wagtail's i18n support is still valid, but in that case, you'll need to implement your own logic to ensure that the URL prefixes match up with what the front-end is able to serve. If you had a custom i18n implementation that worked in Wagtail <=2.10 but is now broken, then that would count as a bug - if so, please provide a full test case that demonstrates the issue and I'll be happy to investigate further.)

**Comment by vladox** [comment]
Hi @gasman 
We have a similar issue but we are not setting `WAGTAIL_CONTENT_LANGUAGES` we are only using the following in our settings.py:

```
WAGTAILADMIN_PERMITTED_LANGUAGES = [('en', 'English'),
                                    ('de', 'German'),
                                    ('fr', 'French')]

# list of activated languages
LANGUAGES = (
    ('de', _('German')),
    ('fr', _('French')),
)
```
`WAGTAIL_I18N_ENABLED` is not set so it should be the default value.

Now we are getting the same behaviour as the original poster, do we need to `WAGTAIL_I18N_ENABLED` to True and define `WAGTAIL_CONTENT_LANGUAGES` for the live links to work properly?

**Comment by gasman** [comment]
Hi @vladox,
You don't have to use `WAGTAIL_I18N_ENABLED`, but if you don't, then Wagtail will not give any special treatment to the `i18n_patterns` prefixes - it will leave them as whatever language the logged-in user has active. It's your responsibility to decide what the 'correct' prefix should be and generate the appropriate URLs yourself (possibly by overriding `Page.get_url_parts`). As mentioned above:

> Using i18n_patterns without Wagtail's i18n support is still valid, but in that case, you'll need to implement your own logic to ensure that the URL prefixes match up with what the front-end is able to serve. If you had a custom i18n implementation that worked in Wagtail <=2.10 but is now broken, then that would count as a bug - if so, please provide a full test case that demonstrates the issue and I'll be happy to investigate further.

**Comment by vladox** [comment]
Hi @gasman 
We have tried the approach of enabling `WAGTAIL_I18N_ENABLED` and defining `WAGTAIL_CONTENT_LANGUAGES` on a site that's using [wagtail-modeltranslation](https://wagtail-modeltranslation-docs.readthedocs.io/en/latest/) for i18n support and the result is that all links in the navigation are being built using the default language in this case German ("de") on all the languages no matter what.
Our current workaround is to disable `WAGTAIL_I18N` altogether and implement `urls.py` based redirections for the live links.
Since this approach was working before the introduction of `WAGTAIL_I18N` support and was one of the recommended methods in the documentation, can this be considered a bug?

**Comment by gasman** [comment]
@vladox If you have a wagtail-modeltranslation setup that worked in Wagtail 2.10 but fails after upgrading to 2.11.2 (with no other config changes), then that would count as a bug, yes. Best of all would be if you could isolate the problem on a test project, and open a new issue detailing how to reproduce it.

**Comment by kleingeist** [comment]
although this issue is closed and quite old i just wanted to leave this comment with a little hacky workaround. we did run into the same problem and solved it by adding a redirect view that matches urls starting with `/xx-yy/...` and redirects them to `/xx/...`

https://gist.github.com/kleingeist/4cae1496af90e13f5531689db81a437e
