### ISSUE TITLE
FormBuilder preview: no clean_name

### ISSUE THREAD

**Issue by Sekun** [wagtail/wagtail#6555]
### Issue Summary

When creating a AbstractForm page, there are no `clean_name` for any `form_fields` attributes when previewing the page.  So only one is shown. When the page is published, fields related to this AbstractForm page are created, an they appear normally.

### Steps to Reproduce

```
git clone https://github.com/Sekun/wagtail-issue-formbuilder
cd wagtail-issue-formbuilder
python3 -m venv .env
source .env/bin/activate
pip install -r requirements.txt
./manage.py migrate
./manage.py loaddata dump.json.gz
```

- Go to page /admin/pages/3/edit/
- Click on preview
- Only one field is shown.

There are no `clean_name` in wagtail revision: `"form_fields":[{"pk": null, "sort_order": 0, "clean_name": "", "label": "test", "field_type": "number", "required": true, "choices": "", "default_value": "", "help_text": "", "page": 3}...`

-    I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Fix ?

Update `get_form_fields`: set `clean_name` if not defined.

```py
class BuilderPage(AbstractForm):
    content_panels = Page.content_panels + [
        InlinePanel("form_fields", label="Form fields"),
    ]


class CustomField(AbstractFormField):
    page = ParentalKey(
        BuilderPage, on_delete=models.CASCADE, related_name="form_fields"
    )

    def get_form_fields(self):
        fields = super().get_form_fields().all()
        for field in fields:
            if not field.clean_name:
                field.clean_name = get_field_clean_name(field.label)
        return fields
```

### Technical details

* Python version: Python 3.8.6
* Django version: Django==2.2.17
* Wagtail version: wagtail==2.11.1

**Comment by bmihelac** [comment]
Same issue is present in wagtail 2.13

Proposed fix works, but `get_form_fields` should be added to `AbstractForm` subclass:

```python
class BuilderPage(AbstractForm):

    def get_form_fields(self):
        fields = super().get_form_fields().all()
        for field in fields:
            if not field.clean_name:
                field.clean_name = get_field_clean_name(field.label)
        return fields
```
