### ISSUE TITLE
Groups read only admin

### ISSUE THREAD

**Issue by VadymP-python** [wagtail/wagtail#6558]
### Is your proposal related to a problem?

My problem is the following during the creation of the admin pannels I wanted to create read-only permissions to pages.
![image](https://user-images.githubusercontent.com/67046495/99462568-a51f4a80-293c-11eb-8282-9e09e2878a72.png)
 but there is not so feature for just listing and viewing if I do something similar the menu item just disappears.

I would appreciate any help with this.

**Comment by gasman** [comment]
Hi @VadymP-python - thanks for the suggestion.
There's an existing issue discussing this, at #5482 - in summary, it's unlikely that Wagtail will provide a 'view' permission type in its default configuration, as there are too many different interpretations of what it should mean, and these overlap with Wagtail's existing 'private pages' feature and the upcoming 'choose' permission (#4488).
