### ISSUE TITLE
Add support for lazy loading iFrames

### ISSUE THREAD

**Issue by siquick** [wagtail/wagtail#6560]
[Chrome 76+ now supports lazy loading iFrame](https://web.dev/iframe-lazy-loading/),  using `loading=lazy`

Can we add in support for this to all Embeds? For example

`<iframe src="<YOUTUBE_URL>" loading="lazy" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" width="480" height="270" frameborder="0"></iframe>`

**Comment by gasman** [comment]
Hi @siquick - thanks for the suggestion.
In the current implementation of embeds, the HTML fragment originates from the third-party service being embedded, so the attributes on the iframe (and indeed the choice to use an iframe at all) are outside of Wagtail's control. However, it would be possible to write custom code to override this on a per-provider basis, as described at https://wagtail.io/blog/fixing-youtubes-oembed-implementation-custom-finder-class/ .
