### ISSUE TITLE
Add screenshots to the documentation

### ISSUE THREAD

**Issue by jrobchin** [wagtail/wagtail#6564]
### Is your proposal related to a problem?

It would be super useful for those new to Wagtail to have a screenshot of how features manifest in the admin portal.

For example, it would be a lot easier to learn the purpose of a snippet if there were a screenshot of how they're used.

### Describe the solution you'd like

Add screenshots to (among others):

https://github.com/wagtail/wagtail/blob/ecf3950426bc4d117f7be24b8bf6746e89484c7c/docs/topics/pages.rst
https://github.com/wagtail/wagtail/blob/ecf3950426bc4d117f7be24b8bf6746e89484c7c/docs/topics/snippets.rst
https://github.com/wagtail/wagtail/blob/ecf3950426bc4d117f7be24b8bf6746e89484c7c/docs/topics/streamfield.rst
https://github.com/wagtail/wagtail/blob/ecf3950426bc4d117f7be24b8bf6746e89484c7c/docs/advanced_topics/custom_tasks.rst

### Describe alternatives you've considered

The `Using Wagtail: an Editor’s guide` page is really useful for this, but it doesn't give a 1-1 view of what the code snippets - for example in the snippets documentation - translates to in the admin portal.

### Additional context

I would be happy to add screenshots as I go through examples if there is a standard to doing so already.

Screenshots would be added similarly to how it's done here: https://github.com/wagtail/wagtail/blob/ecf3950426bc4d117f7be24b8bf6746e89484c7c/docs/editor_manual/getting_started.rst

**Comment by zerolab** [comment]
Hey @jrobchin,

Thank you for the suggestion. One of the difficult bits with lots of screenshots is keeping them up to date when parts or all of the UI changes (e.g. the page edit form in 2.10)

Coincidentally we will be holding a documentation sprint in early January. See https://wagtail.io/blog/documentation-sprint-2021/ for details. One of the points of focus will be restructuring and updating the docs. Would be great if you could join us.

**Comment by tomdyson** [comment]
Thanks @jrobchin! See also @allcaps's interesting ideas about this: https://github.com/wagtail/wagtail/pull/5889

**Comment by thibaudcolas** [comment]
I’m going to close this in favour of #11156. It’s a massive pain for us to maintain up-to-date screenshots for one site, so I’d rather focus on making more use of that site.

Also happy for us to take requests for very specific screenshots that seem particularly high-value.
