### ISSUE TITLE
Page remains cached after publishing new version

### ISSUE THREAD

**Issue by stefanistrate** [wagtail/wagtail#6581]
### Issue Summary

When I'm modifying and publishing a page, as long as I'm still logged in, the live version is still the old one.

### Steps to Reproduce

1. Start a new project and use a cache backend. I use Redis.
2. Create a page and publish it.
3. View live page in browser.
4. Edit page and publish again.
5. View live page again in browser. The old version appears.

I expect that after publishing a page, the cached version would be invalidated and the new version would be available right away. The new version only appears after 10 minutes or more.

Things that I tried:
- Refreshed the live page. It didn't work.
- Cleared the browser cache and refreshed the page. It didn't work.
- Opened the page in incognito mode. It worked. Refresh the page in non-incognito mode. It didn't work.
- Logged out from admin. It worked.

It seems that the caching of the old version happens only when I'm logged in.

### Technical details

* Python version: 3.8.6
* Django version: 3.1.3
* Wagtail version: 2.11.2
* Browser version: Chrome 86

**Comment by stefanistrate** [comment]
To make things easier to reproduce, here's the content of a few files I had to modify starting with a clean Wagtail site.

**home/models.py**
```
from django.db import models

from wagtail.core.models import Page
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel


class HomePage(Page):
    text = RichTextField(null=True)

    content_panels = Page.content_panels + [
        FieldPanel('text'),
    ]
```

**home/templates/home/welcome_page.html**
```
{% load i18n wagtailcore_tags %}

<main>
  {{ page.text|richtext }}
</main>
```

**mysite/settings/base.py**
```
...

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

    'wagtail.contrib.redirects.middleware.RedirectMiddleware',

    'django.middleware.cache.FetchFromCacheMiddleware',
]

...
```

**mysite/settings/dev.py**
```
from .base import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4nnd3qi5h@ia$((@9^)$d(nf@a^@v7z-m0w_65dl_cfalpgb=z'

# SECURITY WARNING: define the correct hosts in production!
ALLOWED_HOSTS = ['*']

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


try:
    from .local import *
except ImportError:
    pass
```

Am I doing anything wrong?

**Comment by tomdyson** [comment]
It looks like you've added Django's per-site cache middleware, and that it's behaving in the way that the docs describe:

https://docs.djangoproject.com/en/3.1/topics/cache/#the-per-site-cache

I'd recommend https://github.com/coderedcorp/wagtail-cache as an alternative, with built-in invalidation.

**Comment by stefanistrate** [comment]
In that sense Django's per-site cache middleware works in the way it's supposed to work. But also, when I publish a new page version in Wagtail and open it in incognito mode, Django also knows to invalidate the previous version. The question is: why doesn't Django know to invalidate the previous version if I'm logged in? Does Wagtail have to instruct it to do so?

**Comment by ababic** [comment]
I am closing this issue, as I'm pretty sure Wagtail is not at fault here. Wagtail makes no promises about invalidating Django's per-site cache middleware, and nor should it really. The per-site cache middleware is not really designed to be invalidated piecemeal in this way.
