### ISSUE TITLE
Display issues with the action menu on a thin browser

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#6591]
When your browser is thin and the main menu packs away, the action menu has a massive gap from the bottom of the page and the icons are clipped with the left side of the screen.

![image](https://user-images.githubusercontent.com/1093808/100458619-fad1c080-30bb-11eb-9f0e-071850781ab6.png)

Firefox 80.1

**Comment by kaedroho** [comment]
The left clipping didn't show up on the screenshot above which was taken with Firefox's screenshot feature, but it's definitely there in the final composition. Might be a clue as to what's going on?

![image](https://user-images.githubusercontent.com/1093808/100458959-89464200-30bc-11eb-8674-4ed6a95fa9d2.png)

**Comment by thibaudcolas** [comment]
I believe this is no longer an issue so will close this now.
