### ISSUE TITLE
Hitting enter in a char block opens the page privacy menu

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#6592]
Seems to happen on every Wagtail build I know of, including a new 2.11 one I just created with Wagtail start.

1) Create a page with a stream field, add an instance of a char block and save it
2) On the edit view, put your cursor in that char block and press enter
3) The page privacy modal will open

**Comment by zerolab** [comment]
Did a quick check: the "set page privacy: element is a `button` which seems to take precedence over the page action buttons. Changing to an `a` element solves this

**Comment by paqman85** [comment]
I'd like to help with this one if it's still open.

@zerolab I believe I found the element you are referencing.

wagtailadmin>pages>privacy_switch_panel.html
`        {% if page.id and page_perms.can_set_view_restrictions %}
            <button data-url="{% url 'wagtailadmin_pages:set_privacy' page.id %}" class="button action-set-privacy">
                {% trans "Set page privacy" %}
            </button>
        {% endif %}`

and this can be changed to 
`        {% if page.id and page_perms.can_set_view_restrictions %}
            <a data-url="{% url 'wagtailadmin_pages:set_privacy' page.id %}" class="button action-set-privacy">
                {% trans "Set page privacy" %}
            </a>
        {% endif %}`

to solve the issue. Is this correct?

**Comment by rinti** [comment]
I would argue that a `<button>` is semantically correct here, for accessibility reasons, since it performs an action. The `<a>` tag should never be used without `href`.

**Comment by zerolab** [comment]
@rinti I concur. that is why it was used in the first place. Did some more digging. In order to prevent `<button>` elements from capturing the enter key event, they need to be defined as `<button type="button>". TIL!

**Comment by sagar-wal** [comment]
Hi ! Can I work on this ?

I tried it out locally, changing `<button>` to `<a>` , or to `<button type="button">` , both cause the 'Save Draft' button to be pressed on hitting Enter.

**Comment by gasman** [comment]
Fixed in #6882
