### ISSUE TITLE
SnippetChooserBlock and internationalisation

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#6599]
### Is your proposal related to a problem?

Make a international snippets model with severlanguages
Make a streamfield, add snippetchoocer block.

Go to admin and choose a snippet. you will notice all languages are presented in the choocerblock. 

### Describe the solution you'd like

We would need at least a filter to select the right snippet block. I propose in right corner of popup you can select the language. Maybe its possible to by default the language where you are editing in?

**Comment by kaedroho** [comment]
I've done a basic implementation of this in https://github.com/wagtail/wagtail/pull/6230, just needs tests

**Comment by gassan** [comment]
it would be better to pass locale parameter (model_name+locale)? to the snippet or page choose:
I have tried it, but


``
class LocaleAdminSnippetChooser(AdminSnippetChooser):
    def __init__(self, model, **kwargs):
        self.page_locale = kwargs.pop('page_locale', None)
        super().__init__(model, **kwargs)

    def render_js_init(self, id_, name, value):
        model = self.target_model

        return "createSnippetChooser({id}, {model});".format(
            id=json.dumps(id_),
            model=json.dumps('{app}/{model}{locale}'.format(
                app=model._meta.app_label,
                model=model._meta.model_name,
                locale='' if not self.page_locale else '+' + self.page_locale.language_code)))
               #  snippets/<app_label>/<model_name[+de]>
```

and here  needed locala can be guessed by instance

```
class LocaleSnippetChooserPanel(SnippetChooserPanel):
    field_template = 'wagtailadmin/edit_handlers/field_panel_field.html'

    object_template = 'wagtailadmin/edit_handlers/single_field_panel.html'

    def __init__(self, field_name, *args, **kwargs):
        super().__init__(field_name, args, kwargs)
        self.page_locale = Locale.get_default()

    def guess_locale(self):
        if self.instance:
            guess_f = getattr(self.instance, 'snippet_chooser_locale', None)
            if callable(guess_f):
                self.page_locale = guess_f(field_name=self.field_name)
            elif isinstance(self.instance, TranslatableMixin):
                    self.page_locale = self.instance.locale
            else:
                pass  # ???


    def widget_overrides(self):
        self.guess_locale()
        return {self.field_name: LocaleAdminSnippetChooser(
            model=self.target_model,
            locale=self.page_locale,
        )}
```

**Comment by zerolab** [comment]
#6699 added an implmenetation for the locale chooser in the snippet modal

**Comment by zerolab** [comment]
Marking this as closed on the basis that #6699 added this and it is available since 2.14
