### ISSUE TITLE
Protecting objects that are referenced by a Page, from being changed / deleted.

### ISSUE THREAD

**Issue by HsnVahedi** [wagtail/wagtail#6600]
### Is your proposal related to a problem?

Suppose we have a page:

```python
class PersonalPage(Page):
    person = models.ForeignKey(
        Person, on_delete=models.SET_NULL, null=True, blank=True
    )

    content_panels = Page.content_panels + [
        SnippetChooserPanel('person')
    ]
```

Suppose that:
    1) "user A" has permission to edit a PersonalPage, but not to publish.
    2) "user A" has permission to edit Person objects.

As an administrator, I don't want people without publish permission to be able to change a published (live) page. But in this scenario, "user A" can change the PersonalPage.person whenever he wants. in other words, "user A" can change the html file generated by the live PersonalPage, whenever he wants.

### Describe the solution you'd like

I want wagtail to compute permission on edit/delete objects dynamically, and prevent the edit/delete if a live page is referencing the object and the user doesn't have publish permission on that page.

### Describe alternatives you've considered

I have also reported this as [a bug](https://github.com/wagtail/wagtail/issues/6594).

**Comment by thibaudcolas** [comment]
I’m going to close this so we don’t split the discussion between here and #6594. Let me know if I missed a reason for which it’s better for there to be two issues.

**Comment by HsnVahedi** [comment]
I've mentioned a simpler approach here. @thibaudcolas

**Comment by thibaudcolas** [comment]
Yes, to clarify I think either of your proposed approaches are valid. I’d just rather have both discussions in #6594, since there are already people discussing this there. We may well end up implementing both changes, but it’s easier to consider them both as part of the same discussion.
