### ISSUE TITLE
Checkbox label not properly lining out within a InlinePanel

### ISSUE THREAD

**Issue by leewesleyv** [wagtail/wagtail#6602]
### Issue Summary

Using a FieldPanel with `widget=CheckboxSelectMultiple` within an InlinePanel styles the form not properly within the ModelAdmin.

### Steps to Reproduce

For a model question, I have registered a ModelAdmin in the Wagtail admin. The question model panels field contains an InlinePanel with answers. The answer model panels field contains a FieldPanel to (m2m field) options. 

<img width="1481" alt="Screenshot 2020-12-01 at 13 58 03" src="https://user-images.githubusercontent.com/32985132/100745292-5adba600-33df-11eb-9d1d-7eb4cac119a7.png">

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (**yes** / no)
* Looks like this is specific to 2.10.2. I could not reproduce this on 2.10.1 nor 2.10.

### Technical details

* Python version: 3.8.0
* Django version: 3.1.2
* Wagtail version: 2.10.2
* Browser version: Chrome 87

**Comment by gasman** [comment]
Hi @leewesleyv - thanks for the report. This has been fixed in 2.11: https://github.com/wagtail/wagtail/pull/6441
