### ISSUE TITLE
Lightbox for regular RichtextField Images

### ISSUE THREAD

**Issue by andreasnuesslein** [wagtail/wagtail#6610]
### Is your proposal related to a problem?

I often find myself needing a "lightbox" feature for images, both from a Streamfield-Image-Block as well as for the RichtextField-Images.

For the Streamfield block it's easy to add a corresponding checkbox, but for the RichtextField you either have to overlay a bunch of functions, urls and functions or you kind of have to hack it in there by using different "image formats", like "full width", "full width with lightbox"

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/320080/101053538-cbb9c400-357f-11eb-8b19-fe78d1a371a6.png)

I would add a "lightbox" Boolean to the `ImageInsertionForm` (images/forms.py) under "Alt text".

I would also create the PR for this, just wanted to know in advance if this is something you think makes sense?

Alternatively I could create a PR that exposes the `Form` to the settings somehow so that you can more easily replace the form and the template without having to clone functions over.

**Comment by gasman** [comment]
Hi @andreasnuesslein - thanks for the offer of a PR!
I'd say this is a case where we would 100% encourage developers to use StreamField, though. Any kind of non-trivial embedded content beyond simple images, where template authors are likely to want to customise the generated HTML, is much better handled in StreamField where the template code for those elements is readily accessible.

This way, we also avoid making Wagtail 'opinionated' about the front-end code - if we were to offer a lightbox option out of the box, we'd have to choose a Javascript library to ship as part of the initial project and ensure it's included in the default base template.

Having said that, this could be a good fit for a third-party add-on module - if there are any general-purpose customisation hooks that we'd need to add to Wagtail to make that work (e.g. being able to extend `ImageInsertionForm`) then I'd be happy to consider those.

**Comment by andreasnuesslein** [comment]
Ahoy @gasman , I hear you. 
Although the discrete distinction then between "this is an Image in a RichtextField" and "this is an ImageBlock" is really hard to explain to editors/users (I guess that's not news ;).

And tbh, off the bat I wouldn't dare to make ImageBlock and RichtextBlock inline both in a way so that I could have a left-align'ed ImageBlock where the RichtextBlock flows around (at a specific place where I'd like to put the image).

Hmm.. how would you solve it, if your editor said "I want a left-aligned picture, that I can neatly put in a place in my text where I see fit and if I want it should also 'do X', e.g. lightbox, or maybe be 75% wide instead of the regular width." ? 
Of course I can make another Streamfield block that has "image left, richtext right" properties or similar; again not great from an editors perspective.

I think I shall look into the hooks some more :+1:  - would you say that that should then also go to the `image_formats.py` file?

Cheers
