### ISSUE TITLE
Providing a restful api to interact with admin interface.

### ISSUE THREAD

**Issue by HsnVahedi** [wagtail/wagtail#6613]
### Is your proposal related to a problem?

Wagtail is probably the most customizable and advanced CMS that exists. To make it more customizable, someone might want to overwrite the default admin interface that wagtail generates. I personally, like to use a material ui designed admin interface.

### Describe the solution you'd like

If wagtail provides a restful api for interacting with admin interface, front end developers could create their own front end interfaces. So wagtail could be used with different frontend frameworks (React, Vue.js, Angular, ...).

Using modern front end frameworks, instead of generating html using django templates, adds a lot of advantages.

**Comment by gasman** [comment]
Hi @HsnVahedi - thanks for the suggestion. There's an existing issue for this at #6258.
