### ISSUE TITLE
Support RTL languages in admin interface

### ISSUE THREAD

**Issue by HsnVahedi** [wagtail/wagtail#6619]
### Is your proposal related to a problem?

Wagtail supports internationalization, But wagtail admin interface doesn't support right to left (RTL) layout for languages written from right to left. There are some important languages (Persian, Arabic, Hebrew, ...) that are written from right to left.

### Describe the solution you'd like

I want wagtail admin templates to provide an RTL layout (for example the sidebar should be on the right of the page) when the language is right to left.

**Comment by gasman** [comment]
Hi @HsnVahedi - thanks for the report. There's an existing open issue for this here: #1240
