### ISSUE TITLE
Make it possible to disable login/logout/account management

### ISSUE THREAD

**Issue by pelme** [wagtail/wagtail#6630]
### Is your proposal related to a problem?

We have an existing Django project where we recently integrated Wagtail. We are heavy users of a custom user model and Django admin. We have overridden the default Django admin login view to enforce 2FA verification.

We want to use our existing login/logout/password reset/account management. Wagtails login page allows any of our existing users to login without the 2FA check. It also allows account management operations that is restricted with our current policies/setup.

### Describe the solution you'd like

I would like to be able to use Wagtail for the CMS tasks without having the user/account management active. Care will have to be taken to support the full API of the user model that Wagtaill expects.

I am not sure exactly how it would be configured. Maybe a setting like `WAGTAIL_ENABLE_AUTH`? 

### Describe alternatives you've considered

For now, my urlconf looks like this:
```py
def wagtailadmin_urls():
    def blocked404(request):
        raise Http404

    def redirect_to_real_login(request):
        wagtailadmin_home = reverse("wagtailadmin_home")
        return HttpResponseRedirect(
            reverse("admin:login")
            + "?"
            + urlencode({"next": request.GET.get("next", "") or wagtailadmin_home})
        )

    def redirect_to_real_logout(request):
        return redirect("admin:logout")

    return [
        re_path(r"^admin/wagtail/login/", redirect_to_real_login),
        re_path(r"^admin/wagtail/logout/", redirect_to_real_logout),
        re_path(r"^admin/wagtail/users/", blocked404),
        re_path(r"^admin/wagtail/groups/", blocked404),
        re_path(r"^admin/wagtail/account/", blocked404),
        re_path(r"^admin/wagtail/", include(wagtailadmin_urls)),
    ]
```

This works but has a number of obvious down sides:
* Care needs to be taken in the future to block potentially new/changed account management URLs.
* The menu and Wagtail UI still contains links to these views. It will take the user to a 404 page.

**Comment by gasman** [comment]
Hi @pelme - thanks for the report.

Overriding the `/login` URL is the recommended way to swap out the login view - we have this in use in various sites in production.

The users / groups admin views (and menu items) are controlled by standard Django permissions, so removing the edit user/group permission from your users would be the preferred approach. If this really isn't an option then you can remove the menu items via the `construct_main_menu` hook. (Ideally it would be possible to remove `wagtail.users` from INSTALLED_APPS, but that's blocked by #3657.)

Finally, the account management area has various settings for disabling options when accounts are managed externally: https://docs.wagtail.io/en/stable/reference/settings.html#password-management

**Comment by pelme** [comment]
@gasman Thank you so much for your response! I missed those settings and the fact that Wagtail respects the user/group permissions. This solves all of my problems.
