### ISSUE TITLE
UserCreationForm requires custom user models to have certain fileds

### ISSUE THREAD

**Issue by dakaza98** [wagtail/wagtail#6647]
According to the documentation about custom user models, [found here](https://docs.wagtail.io/en/v2.11.3/advanced_topics/customisation/custom_user_models.html), the minimum for using UserCreationForm is to inherit AbstractBaseUser and PermissionsMixin:

> Create a custom user model. This must at minimum inherit from AbstractBaseUser and PermissionsMixin.

However, the UserCreationForm still has some standard fields defined that all custom user models must have:
https://github.com/wagtail/wagtail/blob/e48c1704cb13e222740d1ccc1ebbdc0e1ca92f44/wagtail/users/forms.py#L184

The standard fields are defined here
https://github.com/wagtail/wagtail/blob/e48c1704cb13e222740d1ccc1ebbdc0e1ca92f44/wagtail/users/forms.py#L32

This means that if I have a user model that does not use `first_name` and `last_name`, I stumble upon many problems. I assume that this is something that remains from when the model was required to be an AbstractUser (which was changed in [this commit](https://github.com/wagtail/wagtail/commit/d65532dd0f0bf297523a4925fd79286b1d403a5d#diff-e22c4c9af0117a237de54b50fc964ef9a06e475500c0b6c596833da251424576R10)). Or perhaps it is a typo in the documentation? Either way this would be a good thing to sort out

**Comment by favoyang** [comment]
The docs said,

> Create a custom user model. This must at minimum inherit from AbstractBaseUser and PermissionsMixin. In this case we extend the AbstractUser class and add two fields. The foreign key references another model (not shown).

The example is based on extending from AbstractUser class, which provided all the standard_fields you mentioned. If you inherit from AbstractBaseUser and PermissionsMixin, then you need to create these forms from scratch.

**Comment by dakaza98** [comment]
Ah of course! They are just forms that can be overridden. Not the most optimal way to do it but it works. Thanks for pointing me in the right direction!
