### ISSUE TITLE
Three layered clusterable model with orderables causes issues

### ISSUE THREAD

**Issue by CherryChopsticks** [wagtail/wagtail#6650]
### Issue Summary

When creating a clusterablemodel with an orderable that contains an orderable on it's own as well, the code seems to break for the last orderable. 

### Steps to Reproduce

1. create a model structure as followed

```python
  class Schedule(ClusterableModel):
      base_form_class = ActivityScheduleForm
  
      page = models.OneToOneField(
          'wagtailcore.Page',
          null=True,
          blank=True,
          on_delete=models.SET_NULL,
          related_name='schedule',
      )
  
      panels = [
          PageChooserPanel('pagename'),
          InlinePanel('available_days'),
      ]
  
  
  class AvailableDay(ClusterableModel, Orderable):
      day = models.CharField(
          choices=settings.DAYS,
          max_length=max([len(choice[0]) for choice in settings.DAYS]),
          verbose_name=_("day"),
      )
      schedule = ParentalKey(
          Schedule,
          verbose_name=_("schedule"),
          related_name='available_days',
      )
  
      panels = [
          FieldPanel('day'),
          InlinePanel('timeframes'),
      ]
  
  
  class AvailableTime(Orderable):
      start_time = models.TimeField(
          verbose_name=_("start time"),
      )
      end_time = models.TimeField(
          verbose_name=_("end time"),
      )
      available_day = ParentalKey(
          AvailableDay,
          verbose_name=_("available day"),
          related_name='timeframes',
      )
  
      panels = [
          FieldPanel('start_time'),
          FieldPanel('end_time'),
      ]
```

note: settings.DAYS is structured as followed

```python
    DAYS = [
        ('monday', _("Monday")),
        ('tuesday', _("Tuesday")),
        ('wednesday', _("Wednesday")),
        ('thursday', _("Thursday")),
        ('friday', _("Friday")),
        ('saturday', _("Saturday")),
        ('sunday', _("Sunday")),
    ]
```

2. Edit admin.py as followed

```python
  @modeladmin_register
  class ScheduleAdmin(ModelAdmin):
      model = Schedule
      menu_label = _("Activity schedule")
      menu_icon = 'date'
```

Steps to reproduce bug:

    Go to the schedule admin page

    Click on the “add” button and add a day

    Click once more on the “add” button and add two timeframes

    The first one will show you an option for times. The second one however will have no functionality, nor will it save it’s data when trying to save.

Notes:

This only happens on the initial creation of a day+timeframe. After the initial creation you can add as many time timeframes without it breaking for that specific day.

When adding two different timeframes, it doesn’t recognize the fact that there is two but when saved it takes the times of the last created one.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

* Python version: Python 3.8.5.
* Django version: Version: 3.1.3.
* Wagtail version: Version: 2.10.1
* Browser version: Firefox 83

**Comment by gasman** [comment]
Hi @CherryChopsticks - thanks for the report. This is a known issue, covered here - #5770
