### ISSUE TITLE
View permissions for collections don't restrict image view access

### ISSUE THREAD

**Issue by mr-klint** [wagtail/wagtail#6655]
**Issue description:**
When trying to set image/document permissions according to the documentation (https://docs.wagtail.io/en/v2.11.3/topics/permissions.html) by adding them to a collection and restricting it's permission (for example to only viewable for logged in users). However, the possibility to view the images in the collection is still viewable for everyone

**Proposal:**
When checking the code the page restriction is handled by the use of executing the hook 'before_serve_page' before serving the page. However, even though most logic seems to be in place, such a construct don't seem to be in place for images. Therefore my proposal would be to add a new hook 'before_image_rendition' in the AbstractRendition.

**Questions:**
What might be needed also is for sure what should happen when an image is not permitted to view, should nothing be displayed or should there be a sign in field or something entirely different?

Have I misunderstood the functionality or are there a better solution than the one proposed above?

**Comment by mr-klint** [comment]
Forgot to write but issue is verified in a fresh install of wagtail 2.11.3

**Comment by gasman** [comment]
Hi @mr-klint - thanks for the report. There's an existing issue open for this, at #3880.
