### ISSUE TITLE
YouTube embeds no longer working

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#6656]
### Issue Summary

Using a wagtail embed tag like `{% embed 'https://youtube.com/...' %}` renders empty. Nothing at all.

### Steps to Reproduce

1. Edit any template and add an embed tag with a YouTube link you haven't yet embedded on the site before.
2. Refresh the page.
3. The video won't be displayed.

I think that YouTube itself may have broken this by changing the format.

**Comment by alexgleason** [comment]
As a workaround I simply inserted my video into the Postgres cache like this :shrug: 

```sql
INSERT INTO wagtailembeds_embed (url, type, html, title, author_name, provider_name, thumbnail_url, width, height, last_updated)
VALUES ('https://youtu.be/jmTpi3JPDAk?feature=oembed', 'video', '<iframe width="560" height="315" src="https://www.youtube.com/embed/jmTpi3JPDAk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>', 'David Vera testimonial on Project TIER', 'Norm Medeiros', 'YouTube', 'https://i.ytimg.com/vi_webp/jmTpi3JPDAk/maxresdefault.webp', 560, 315, '2020-12-22 00:00:00+00');
```

**Comment by gasman** [comment]
@alexgleason Which Wagtail version are you running? Youtube has recently become stricter about using https, which affects versions prior to 2.11.

**Comment by alexgleason** [comment]
We're on 2.9 so that's probably it. Thank you!

**Comment by pinktig** [comment]
I had similar issue with Youtube Embeds, and some of my clients sites were on versions prior to 2.11. 
For anyone who's having the same issue, but can't upgrade to version 2.11 or up, here's how monkey patched this issue. 

As Wagtail allows you to customize individual provider (as documented in [here](https://docs.wagtail.io/en/stable/advanced_topics/embeds.html#customising-an-individual-provider))

In your settings add/modify WAGTAILEMBEDS_FINDERS setting as below: 

`
WAGTAILEMBEDS_FINDERS = [
    {
        'class': 'wagtail.embeds.finders.oembed',
        'providers': [
            {
                "endpoint": "https://www.youtube.com/oembed",
                "urls": [
                    r'^https?://(?:[-\w]+\.)?youtube\.com/watch.+$',
                    r'^https?://(?:[-\w]+\.)?youtube\.com/v/.+$',
                    r'^https?://youtu\.be/.+$',
                    r'^https?://(?:[-\w]+\.)?youtube\.com/user/.+$',
                    r'^https?://(?:[-\w]+\.)?youtube\.com/[^#?/]+#[^#?/]+/.+$',
                    r'^https?://m\.youtube\.com/index.+$',
                    r'^https?://(?:[-\w]+\.)?youtube\.com/profile.+$',
                    r'^https?://(?:[-\w]+\.)?youtube\.com/view_play_list.+$',
                    r'^https?://(?:[-\w]+\.)?youtube\.com/playlist.+$',
                ],
            }
        ],
        'options': {'scheme': 'https'}
    },
    {
        'class': 'wagtail.embeds.finders.oembed',
    }
]
`

Hope this helps someone in a similar situation.
