### ISSUE TITLE
Make Wagtail’s icon set easier to browse

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#6667]
The nitpicking of the day :) :)

When using wagtail.contrib.styleguide I mostly use it to see the icons that are availalble. I think that is for most developers.
However the icons are at the bottom of the page. Maybe as a very small improvement this is better placed at the top.

**Comment by thibaudcolas** [comment]
Hey @onno-timmerman, I like this suggestion. Alternatively we’ve been wondering whether it would be better to have the icons directly in the Wagtail docs: https://github.com/wagtail/wagtail/pull/6028#discussion_r590144224

Do you think that would work well / better?

**Comment by onno-timmerman** [comment]
yes absolute in docs so you can refrence to them

**Comment by thibaudcolas** [comment]
For anyone interested in this – I’ll be working on this in a couple of weeks. I’m leaning towards adding all the icons to `docs.wagtail.org`, so I’ll try this first.
