### ISSUE TITLE
Multiple clicks on image "Update" button results in duplicate images in the system

### ISSUE THREAD

**Issue by m3brown** [wagtail/wagtail#6675]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

It is possible for consecutive clicks to create duplicate images in the create_from_uploaded_image form. In my case, this issue is exacerbated because of a post_save signal on Image creation, which pauses the form UI for a second or two. In other words, it's a race condition that probably doesn't affect most users.

I imagine the same issue exists for documents.

This issue is related to #305.

### Steps to Reproduce

1. Create a post_save signal to pause image creation for a second or two
2. Upload an image
3. At the `Upload successful. Please update this image...` prompt, click "Update" several times until the form disappears.
4. Visit the image list view, and multiple copies of the image will be present.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

From my observations, the root of the issue is that the form button is not disabled on click, leaving the door open to more than one click. Since the transaction is usually pretty fast, this isn't typically an issue, but I still think it should be fixed for use cases where the backend may not be as responsive as we'd like.

The CSS styling of this solution isn't create, but one example of a workaround is to add the following line above the post in [add-multiple.js](https://github.com/wagtail/wagtail/blob/cf38b2457dba521d029d3a6e5024a7d0c3f5faf6/wagtail/images/static_src/wagtailimages/js/add-multiple.js#L137):

```javascript
$(this).find(':submit').prop("disabled", true);
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.6.
* Django version: 2.2.17
* Wagtail version: 2.11.3
* Browser version: Edge 87

**Comment by gasman** [comment]
Fixed in #6676.
