### ISSUE TITLE
Chevron missing in collection_choice_field select widgets

### ISSUE THREAD

**Issue by m3brown** [wagtail/wagtail#6682]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Select elements in wagtail forms that render a collection dropdown are missing the chevron icon on the right.

![image](https://user-images.githubusercontent.com/2699164/104227378-498eac00-5417-11eb-9b64-3046fbda7b50.png)

Expected style:

![image](https://user-images.githubusercontent.com/2699164/104227340-354aaf00-5417-11eb-9dc4-9baf0ae5193b.png)

It appears this issue is related to #6141, where the css class is now rendered as "collection_choice_field".

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Go to the Images page from the left panel
3. Add an image
4. Edit the image
5. Observe the "collection" dropdown does not have chevron icon

The missing icon is in several other places, notably:
- in the "add an image" form, which looks to be a case of a missing span that is not the same as this bug.
- in the right hand sidebar form in Reports (site history, etc.), which is a different problem than this bug.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.6
* Django version: 2.2.17
* Wagtail version: 2.11.3
* Browser version: Edge 87, Firefox 83

**Comment by gasman** [comment]
Fixed in #6683.
