### ISSUE TITLE
Make 'Documentation' an 'issue type' 

### ISSUE THREAD

**Issue by JoanEliot** [wagtail/wagtail#6684]
In the spirit of the upcoming documentation sprint, I suggest listing Documentation as a separate issue type [here](https://github.com/wagtail/wagtail/issues/new/choose) with its own special little icon. You'd of course provide appropriate prompts when the issue is opened: Where exactly in the documentation? What type of suggestions (typo or grammar correction, correction of substantive error, request for clarification, request for an example or more detailed examples, etc.)? 

I'm aware of the relevant tag(s) but think that you'd get more and better suggestions on the docs if you set up a separate, full-fledged issue type for them.

**Comment by thibaudcolas** [comment]
Hey @JoanEliot, good idea! Would you be up for making a first draft of this? I imagine we could start from our [feature request issue template](https://github.com/wagtail/wagtail/tree/master/.github/ISSUE_TEMPLATE), which is rather generic. Might also be worth checking what people have reported in [existing issues tagged Documentation](https://github.com/wagtail/wagtail/issues?page=5&q=label%3ADocumentation+is%3Aclosed).

**Comment by JoanEliot** [comment]
Yes, I'd be happy to draft a preliminary version. Timing is uncertain but I'll try to come up with something this week. I don't know from pull requests so will just attach the md file here.

**Comment by thibaudcolas** [comment]
Great 👍 . Our preference would be to do this via a pull request, but I imagine we can create one based on what you propose if you’d rather not use PRs.

If you’re interested to try but not sure where to start – for single-file changes like this, you can make PRs directly in GitHub:

Head to https://github.com/wagtail/wagtail/tree/master/.github/ISSUE_TEMPLATE, then "Add file" > "Create new file". This will create a fork of the project for you, from which you can then create the pull request.

![2021-01-25-new-issue-template](https://user-images.githubusercontent.com/877585/105699072-b7020880-5efe-11eb-9be7-8e641f66df44.png)

Make sure to follow the expected file format from https://raw.githubusercontent.com/wagtail/wagtail/master/.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, with all the relevant metadata, so the issue template displays as expected on the [new issue chooser](https://github.com/wagtail/wagtail/issues/new/choose).

**Comment by JoanEliot** [comment]
Ok, it's in—that was easy, of course, thanks for the details. I stuck to the format except that I took the liberty of adding a markdown table, but it's not a crucial feature of the template. A selection of possibly appropriate emojis is included, though I didn't think any of them are great.

**Comment by thibaudcolas** [comment]
Thank you @JoanEliot! I took the liberty to merge this after having applied some of my suggestions to make the template smaller, as I think we might as well start using that template for our current documentation work. 

If anyone wants to make further changes to the template, we can have further PRs to refine it.

**Comment by tomdyson** [comment]
Thank you @JoanEliot and @thibaudcolas !
