### ISSUE TITLE
Feature Request: Allow sorting of Draftail default features

### ISSUE THREAD

**Issue by RandomJo** [wagtail/wagtail#6689]
It is wonderful to have the ability to add default features to rich text fields, but the usability of my added features is not ideal. For example, I wanted to add the H5 by default but it looks like all manually added features are added to the front of their respective sections without any control to reorder. This results in H5 being before H2, H3, and H4. I tried setting features.default_features to an ordered list based on my preference, but that just added more than one version of the system's default buttons.

If there is a way to get into the guts of the thing and modify the order of button display, I'd appreciate the advice. Otherwise, I think it would be a great feature addition.

I'm working from Wagtail 2.7.4

**Comment by gasman** [comment]
Hi @RandomJo,
If you add an `order` argument to your `@hooks.register('register_rich_text_features')` line as described at the top of the [hooks documentation](https://docs.wagtail.io/en/stable/reference/hooks.html), that'll specify whether your hook runs before or after the built-in ones, which I _think_ will determine the ordering in the toolbar. Would that give you enough control?

**Comment by RandomJo** [comment]
Thanks so much for the quick response! That totally did the trick. By making my hook run after the one in `wagtail.core`, I can override `features.default_features` to be my intentionally ordered list of features. Yay!

For anyone running into the same issue, here is my finalized code placed within a wagtail_hooks.py file:
```
@hooks.register('register_rich_text_features', order=1)
# @hooks.register('register_rich_text_features')
def register_predefined_default_feature(features):
    features.default_features = [
        'bold',
        'italic',
        'superscript',
        'subscript',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'ol',
        'ul',
        'hr',
        'break',
        'embed',
        'link',
        'document-link',
        'image',
        'undo',
        'redo',
    ]
```

Note that this will have the side effect of not taking any new default features that may be introduced to Wagtail in a future version. If you wanted to support that, then you could write some code that places your desired features after specific items in the list by searching for the placement and inserting.

Thanks so much, @gasman!
