### ISSUE TITLE
Additional filter criteria for PageChooserPanel

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#670]
The PageChooserPanel allows restricting the pages that one can choose based on model. That is extremely helpul, however there are cases where editors have to rely entirely on their knowledge of the content to pick pages of a given model that match some criteria. e.g. choose Media pages that have an audio embed.

I imagine this as working the same way an override `serve()` or `route()` method does. It would be the developer's responsibility to return the filtered set.

**Comment by lb-** [comment]
Closing as this is can be merged into newer #1250
