### ISSUE TITLE
Documentation typo in code example

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#6707]
https://docs.wagtail.io/en/v2.5/advanced_topics/customisation/rich_text_internals.html#FeatureRegistry.register_link_type

We see the following code example: 

note "indetifer" should be "identifier"

```
from django.utils.html import escape
from wagtail.core import hooks
from wagtail.core.rich_text import LinkHandler

class NoFollowExternalLinkHandler(LinkHandler):
    identifer = 'external'

    @classmethod
    def expand_db_attributes(cls, attrs):
        href = attrs["href"]
        return '<a href="%s" rel="nofollow">' % escape(href)

@hooks.register('register_rich_text_features')
def register_external_link(features):
    features.register_link_type(NoFollowExternalLinkHandler)
```

**Comment by gasman** [comment]
Hi @onno-timmerman - thanks for the report. This has been fixed in current versions of the documentation: https://docs.wagtail.io/en/stable/advanced_topics/customisation/rich_text_internals.html#FeatureRegistry.register_link_type

**Comment by onno-timmerman** [comment]
ouch, didn't pay attention to version sorry...
