### ISSUE TITLE
Ability to batch move documents/images to collections

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/wagtail#6709]
### Is your proposal related to a problem?

Consider an existing project with many documents and images. At some point the admins/editors realize that they should make use of Wagtails collections feature. The admins/editors will now have to edit every single document and image separately. 

### Describe the solution you'd like

I would be great if you could apply the same change to multiple documents/images at the same time. 
E.g. in the index view each row could have a checkbox on the left. Checking the checkbox activates an action toolbar. The checkbox can be activated for multiple rows at once. 

Potential actions for the action toolbar could be "Move to collection", "Delete", "Add tag"

### Describe alternatives you've considered

Manually changing each separate document/image is of course possible but can get labor intensive in larger projects that have ignored the collections feature for too long. 

It would also be possible to create a one off script to perform the batch action. This requires developer expertise though. Then communicating all the document/image ids from the editors to the devs is basically the same labor that it takes to manually edit each element.

**Comment by thibaudcolas** [comment]
This sounds a lot like #7573 :) Coming in Wagtail 2.15.
