### ISSUE TITLE
Nested Orderables validation errors in wagtail-admin

### ISSUE THREAD

**Issue by JOJ0** [wagtail/wagtail#6714]
Hi, I know this is not the right place for usage questions. I tried stackoverflow, slack and the matrix room already to find out if my issues is a usage error on my end or a bug in wagtail. It's been about 2 weeks now and I did not get any response at all there. That's why I decided to post it here. Also because to me it feels like a bug and as far as I understand that it is supposed to work as I coded it.

But let's find out if it's a bug or not!

This is my detailed post with screenshots and bells and whistles on stackoverflow: https://stackoverflow.com/questions/65680004/nested-orderables-validation-errors-in-wagtail-admin

I am aware of that I am not following the github issue bug filing guidlines right now. If you would like me to prettifiy my report here as suggested in the guidlines I am very happy to do it properly :-)

For now please anyone might want to have a look on the stackoverflow post and tell me if my design is the problem or if it could be considered a bug in wagtail!

many many thanks in advance for an answer and also for a great piece of software!
Jojo

**Comment by gasman** [comment]
Hi @JOJ0 - thanks for the report. Yes, this is a known bug, covered here: #5770

**Comment by JOJ0** [comment]
@gasman thanks a lot for the quick reply! appreciated! I will take a look on the workaround described in #5770 and/or wait for 2.9.
