### ISSUE TITLE
Deleting snippets enhancement 

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#675]
Currently you can only delete a snippet directly within the edit page for the snippet. It would be good if you could delete them from the snippet listing, ideally in batch to improve UX.

**Comment by lb-** [comment]
@gasman I would like to take on this Issue and have a proposed UI flow in mind.

I understand this does not cover the full Bulk Actions as per #121 but it will mean we have solved a simple use case.

**View 1 - No Items Selected**
* New column 5% wide that will contain checkboxes.
* By default no items will be selected on any Snippets listing.
* Column will have no header.
* `Delete Selected` button is disabled in the header.

![wagtail - snippets - view 1 - no items selected](https://user-images.githubusercontent.com/1396140/29581132-a2220ed0-8778-11e7-9667-bf5662ad1b68.png)

**View 2 - One or More Items Selected**
* When an item is selected, this is indicated by the row being a different colour.
* I would need direction on what colour/css class would be suitable.
* `Delete Selected` button is now enabled in the header with red `serious` class.

![wagtail - snippets - view 2 - one item selected](https://user-images.githubusercontent.com/1396140/29581250-01d00a3a-8779-11e7-803c-6ec28d702c17.png)

**View 3 - Delete Snippets Confirmation**
* When the `Delete Selected` button is clicked, the behaviour will be similar to a single page being deleted.
* A new view at a URL like `/admin/snippets/demo/advert/multiple/delete/?id=1` will contain the View for confirming the delete action.
* The view will list the titles (or whatever is set) for reference.

![wagtail - snippets - view 3 - delete snippets confirmation](https://user-images.githubusercontent.com/1396140/29581417-7a6d83e6-8779-11e7-8088-1aa44354ba57.png)

**Comment by gasman** [comment]
Thanks @lb- - all looks good to me!

**Comment by lb-** [comment]
Epic - @gasman I have started progress on my own fork, you can see the branch here:

https://github.com/lb-/wagtail/tree/675_deleting_snippets_enhancement

**Question:** Where should I put my custom Javascript for the specific template in admin (should I use hooks to put it in?)

**Comment by gasman** [comment]
@lb- Use a `{% block extra_js %}` section, preferably with the Javascript in an external file (rather than inline on the page), like this: https://github.com/wagtail/wagtail/blob/5278e005a0c77f9d8ea82215057d38c7fc512fc9/wagtail/wagtailimages/templates/wagtailimages/images/url_generator.html#L37-L42

**Comment by lb-** [comment]
@gasman epic, that helps heaps.

**Comment by lb-** [comment]
Pull request includes the changes described above with a few modifications:
* Added a 'select all' checkbox on the header row
* delete-multiple url will act like delete url if one snippet ID is provided

**Comment by lb-** [comment]
I need to add a js function call on page load to sync up the view when users click back still

**Comment by gasman** [comment]
Completed in #3802 / #4610.
