### ISSUE TITLE
Reordered pages not logged properly

### ISSUE THREAD

**Issue by Stormheg** [wagtail/wagtail#6761]
### Issue Summary

Reordering a page shows up in Wagtail's Site History report as having been performed by the 'system' user. Instead of the user that has actually performed the action.

The description of the reordering action could also be improved upon. 'Moved from [parent page] to [parent page].' is not very clear to the end user. '[reordered page] was reordered.' or something like that would seem clearer to me (suggestions welcome).

Screenshot of the issue:
![Screenshot from 2021-02-03 16-50-21](https://user-images.githubusercontent.com/13856515/106772089-f38cdd00-663f-11eb-8de9-1295869e6a82.png)

### Steps to Reproduce

1. Install [Wagtail Bakerydemo](https://github.com/wagtail/bakerydemo) and update it to Wagtail 2.12 (The bakerydemo is still on 2.11 as of writing).
2. Go to 'Breads' page in the Wagtail admin.
3. Click the 'Sort' link (screenshot included). ![Screenshot from 2021-02-03 16-56-22](https://user-images.githubusercontent.com/13856515/106773262-2b485480-6641-11eb-81f1-2426aa1948ed.png)
4. Try dragging a page to a new position. Move the Bagel page to the top for example :).
5. Now go to the Site History report (`Reports -> Site History` in the menu bar).

The report should show your action as having been performed by the 'system' user. It should also show the confusing description as stated in the issue summary.

**Expectation:** the report should show the actual user who has performed the action, not 'system'.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.9.1.
* Django version: 3.1.6.
* Wagtail version: 2.12 final
* Browser version: Chrome 88 on Fedora Linux.

**Comment by Stormheg** [comment]
The offending code is in [`wagtail/admin/views/pages/ordering.py`](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/views/pages/ordering.py#L8).

`set_page_position()` should pass the current user to the `page_to_move.move()`.

**Comment by zerolab** [comment]
Nice find @Stormheg
Thank you in advance for the PR. I think pos `left` and `right` can count as re-order rather than move and I wonder if the log message should reflect that.

**Comment by Stormheg** [comment]
Merged in https://github.com/wagtail/wagtail/commit/520fa23ced80f3c4eb3b71842923848a2812a1fd and https://github.com/wagtail/wagtail/commit/1ff679f861b21d93dd8061561666b0984249dfcc :tada:
