### ISSUE TITLE
Documentation design changes

### ISSUE THREAD

**Issue by nmorduch** [wagtail/wagtail#6793]
## Done during sprint

- [x] TOC, hide show in desktop/mobile
- [x] TOC, hide om some pages (index/landing pages)
- [x] Remove quote block wrapping code.
- [x] Version picker.
- [x] Version warning banner check (is this JS injected?). Checked. Yes, JS
- [x] Remove Typo3 refs hardcoded and via conf.
- [x] White on white text. /advanced_topics/images/custom_image_model.html
- [x] Load Roboto font

## Should

- [x] Increase total width
- [ ] Version picker styling improvements.
- [ ] TOC, to the right, sticky and scrollable, if possible.
- [ ] Branding, font-size, colour scheme. See [Olly's design](https://www.figma.com/proto/hFjWqQeEjGd8NtTsEHcc4i/Wagtail-Docs?node-id=1%3A2&viewport=983%2C953%2C1&scaling=min-zoom&hide-ui=1)
- [ ] Beter understand template overrides, maybe override only some blocks and not complete templates.

# Changes to #6792

 From Slack

- [x] Remove view source button
- [ ] the contrast of the inline code elements needs to be much better
- [ ] Should the main navigation on the left be sticky, too? Decision needed.
- [ ] Change the "system" font stack on body to include a better system font than Arial on Windows. Use 'Segoe UI'.
- [ ] syntax highlighting failing to initialize due to a JS syntax error. there is some template syntax issue here: https://github.com/allcaps/wagtail/blob/docs-theme/docs/_templates/layout.html#L175-L178
- [ ] Enable default styling so code is readable even if the syntax highlighting fails to initialise.
- [x] Tone down the github button (could style it like the view source button)
- [ ] Reduce the padding of the code blocks so they don’t nearly crash into each other vertically. if we can do this and slightly increase the font size of the blocks that’d be great.
- [ ] Increase line height
- [ ] Slightly reduce the blackness of the large code blocks (they feel a bit heavy)
- [ ] Consider going a bit less black with the Page contents section, to make it less distracting and indicate that it’s ‘secondary’ content
- [ ] Colours of notes and info blocks clash with Wagtail teal
- [x] If possible, remove the Page contents block when there’s only one heading
- [x] Hover state in navigation is missing.
- [ ] Tab focus styling
- [ ] Remove quote block wrapping around automatically generated documentation (see https://wagtail--6792.org.readthedocs.build/en/6792/reference/hooks.html#register-snippet-action-menu-item)
- [ ] Sphinx 1.8 on RTD vs 3.4 local. `ul li p content` on the local build. Where does this paragraph come form? Is it related to quote block? Investigate to keep the versions in sync?

**Comment by ollywillans** [comment]
> ## Nice to have
> * [] TOC, to the right, sticky and scrollable, if possible.
> * [ ]  Branding, font-size, colour scheme.

This has been created to represent the desired branding, based on Wagtail.io
https://www.figma.com/proto/hFjWqQeEjGd8NtTsEHcc4i/Wagtail-Docs?node-id=1%3A2&viewport=983%2C953%2C1&scaling=min-zoom&hide-ui=1

**Comment by Stormheg** [comment]
When https://github.com/allcaps/wagtail/pull/5 gets merged we can tick:
- [x] Remove Typo3 refs hardcoded and via conf.
- [x] Remove view source button

**Comment by allcaps** [comment]
The new theme is live. All issues on the theme via https://github.com/wagtail/sphinx_wagtail_theme

**Comment by SalahAdDin** [comment]
The old one was more "wagtail-wise".
