### ISSUE TITLE
Add a full_url property to image rendition objects

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#6803]
### Is your proposal related to a problem?

To include a Twitter 'share' image on a template, you'd typically do something like:

    {% image page.social_image fill-1200x1200 as social_img %}
    <meta name="twitter:image" content="{{ social_img.url }}">

However, this may return either a local URL (`/media/images/foo.jpg`) or an absolute URL (`https://media.example.com/images/foo.jpg`) depending on how media files are configured at the Django level. There's no good way to consistently return a full absolute URL, as required for the 'share' image to work.

### Describe the solution you'd like

Add a `full_url` property to the image Rendition model, which prepends `settings.BASE_URL` to the rendition's `url` property if it begins with a `/`, and returns the url unchanged if not. This will then allow us to write

    <meta name="twitter:image" content="{{ social_img.full_url }}">

(Using `settings.BASE_URL` isn't perfect - it's only an informal convention for Wagtail sites to define it, and it doesn't account for multi-site installations - but it's probably good enough for most purposes.)

**Comment by nicklee** [comment]
@kevinhowbrook has applied a fix for this on RCA:
https://github.com/torchbox/rca-wagtail-2019/pull/551/files

**Comment by sankalpmukim** [comment]
It looks like this fix still needs to be implemented. Can you guys assign this issue to me?

**Comment by sankalpmukim** [comment]
I'm really sorry, I've not finished this yet. I was having trouble setting it up on my windows machine but now I've got it setup. The issue seems pretty straightforward but just to confirm, do I need to do anything else other than adding a full_url method in wagtail/images/models.py right? No need to add any documentation of any sort?
I'm a beginner to open source contributions so help would be really appreciated.

**Comment by gasman** [comment]
Hi @sankalpmukim,
Yes, this will need to be added to the documentation - I'd suggest updating the section at https://github.com/wagtail/wagtail/blob/main/docs/topics/images.rst#more-control-over-the-img-tag to mention the new method.

Additionally, you'll need to write some unit tests to show that the new method is working as intended (which helps us to spot if this feature gets broken by any future code changes) - see https://docs.wagtail.io/en/stable/contributing/developing.html#testing.

**Comment by sankalpmukim** [comment]
Alright thanks, this will be part of a single PR and this issue right? Also, do I mention the issue number in each commit(if tests, method and documentation are 3 different commits) or do in 1 commit? Again, thank you for cooperating with noob me!

**Comment by gasman** [comment]
@sankalpmukim Yes, one PR with individual commits for implementation, tests and documentation is usually a good way to arrange it. No need to mention the issue number in every commit - having a commit message that's immediately understandable is more important. I'd probably use something like:

* Implement full_url property on image renditions. Fixes #6803
* Add tests for Rendition.full_url property
* Add documentation for Rendition.full_url

**Comment by sankalpmukim** [comment]
Hi. I faced a lot of issues setting up the repository on my computer so feel free to take this one! It's not at all a complicated one.

**Comment by shreyashsrivastava** [comment]
@sankalpmukim yeah, I am a newbie to the open source and this might be the good head start, thankyou.

**Comment by shreyashsrivastava** [comment]
Hello @gasman, I already started to getting familiar with the code structure, would you please assign this issue to me.

**Comment by gasman** [comment]
@shreyashsrivastava Thanks for your interest! We don't really do assignments on this project - feel free to pick this up.

**Comment by shreyashsrivastava** [comment]
Hey, thankyou for the response. As I can see that there is no BASE_URL variable in the settings defined, should I define the BASE_URL in the settings, If yes, then Is this the right way to do this ?

`if "PRIMARY_HOST" in os.environ:`
`    BASE_URL = "https://{}".format(os.environ.get("PRIMARY_HOST"))`
`else:`
`    BASE_URL = "https://example.com"`

**Comment by shreyashsrivastava** [comment]
Hello, I created a pull request for the same, by keeping in mind all the things you told, and from the past discussions. Pardon me, If I have made any mistakes. Thank You.
