### ISSUE TITLE
Upstream change in django-treebeard 4.5 requires a new wagtail core migration

### ISSUE THREAD

**Issue by bretth** [wagtail/wagtail#6820]
Default MP_Node depth has changed to 1.

https://github.com/django-treebeard/django-treebeard/commit/454be8f29ac2b4b4fbe6512357b5afc1eb422bab#diff-35501ef525349cd39e4713d1a9f64a249fa4fbd31d875513e3a15e65988701a2

**Comment by gasman** [comment]
@bretth Thanks for the report! Looks like this change could potentially make things pretty messy, and I think we'll have to get a patch release out as soon as possible to pin to <4.5 - as it stands, if someone upgrades to 4.5 now and runs `./manage.py makemigrations`, it'll create a spurious 'auto' migration inside the wagtail.core app which will then be lost on subsequent Wagtail upgrades.

**Comment by ababic** [comment]
For anyone who may be experiencing lingering issues after upgrading, I'm hoping this helps:

### If on Wagtail 2.12:

1. Search your project for migrations with a dependency on a `wagtailcore` migration with a name starting with `0062_auto` and update those dependency lines to `("wagtailcore", "0061_change_promote_tab_helpt_text_and_verbose_names")`.
2. Commit your changes and deploy them wherever they need deploying.
3. From a bash console run the following to reverse the spurious migration in any environment that may have created/run it:
```
echo "DELETE FROM django_migrations WHERE app='wagtailcore' AND name LIKE '0062_auto%'" | python manage.py dbshell
```

### If on Wagtail 2.11:

1. Search your project for migrations with a dependency on a `wagtailcore` migration with a name starting with `0060_auto` and update those dependency lines to `("wagtailcore", "0059_apply_collection_ordering")`.
2. Commit your changes and deploy them wherever they need deploying.
3. From a bash console run the following to reverse the spurious migration in any environment that may have created/run it:
```
echo "DELETE FROM django_migrations WHERE app='wagtailcore' AND name LIKE '0060_auto%'" | python manage.py dbshell
```


### If on Wagtail 2.10:

1. Search your project for migrations with a dependency on a `wagtailcore` migration with a name starting with `0034_auto` and update those dependency lines to `("wagtailcore", "0033_remove_golive_expiry_help_text")`.
2. Commit your changes and deploy them wherever they need deploying.
3. From a bash console run the following to reverse the spurious migration in any environment that may have created/run it:
```
echo "DELETE FROM django_migrations WHERE app='wagtailcore' AND name LIKE '0034_auto%'" | python manage.py dbshell
```

**Comment by gasman** [comment]
Now that treebeard 4.5.1 has been released with the model change reverted (and the 4.5 release pulled), we can un-pin the dependency - tagging this to be done in the next 2.11 (and 2.12) release.
