### ISSUE TITLE
Extending the Draftail Editor -  new  entities stoped working

### ISSUE THREAD

**Issue by noampolak** [wagtail/wagtail#6831]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
2 of my new entities which I created a year ago are causing the richtext block when trying to add them to crash  after upgrading to wagtail 2.11.3
![image](https://user-images.githubusercontent.com/53046870/108985979-54855f00-769a-11eb-9883-d4dfca9cbe8d.png)
after clicking on the &nbsp button:
![image](https://user-images.githubusercontent.com/53046870/108986150-80084980-769a-11eb-9a89-69a9fa8ee37e.png)
The error in the browser console  is too dim:

react-dom.production.min.js:209 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Pl (react-dom.production.min.js:275)
    at c (react-dom.production.min.js:141)
    at h (react-dom.production.min.js:144)
    at v (react-dom.production.min.js:145)
    at react-dom.production.min.js:149
    at Mu (react-dom.production.min.js:173)
    at ya (react-dom.production.min.js:265)
    at cl (react-dom.production.min.js:246)
    at al (react-dom.production.min.js:246)
    at Za (react-dom.production.min.js:239)
ea @ react-dom.production.min.js:209

### Steps to Reproduce
1. start a wagtail project
2. add a wagtail_hooks.py file
3. add my new feature:

**Here is my code:**
**"wagtail_hooks.py"**

```
@hooks.register('register_rich_text_features')
def register_nblspace_feature(features):
    """
    Registering the `&nbsp` feature, which uses the `&NBSP` Draft.js entity type,
    and is stored as HTML with a `<span data-nbsp>` tag.
    """
    feature_name = 'nblspace'
    type_ = '&NBSP'

    control = {
        'type': type_,
        'label': '&nbsp',
        'description': '&nbsp',
    }

    features.register_editor_plugin(
        'draftail', feature_name, draftail_features.EntityFeature(control))
    features.default_features.append(feature_name)

    features.register_converter_rule('contentstate', feature_name, {
        # Note here that the conversion is more complicated than for blocks and inline styles.
        'from_database_format': {'span[data-nbsp]': NBSPEntityElementHandler(type_)},
        'to_database_format': {'entity_decorators': {type_: nbsp_entity_decorator}},
    })


# spcial handler to nbsp feature
def nbsp_entity_decorator(props):
    """
    Draft.js ContentState to database HTML.
    Converts the NBSP entities into a span tag.
    """
    logging.info(props)
    return DOM.create_element('span', {
        'data-nbsp': props['nbsp'],
    }, props['children'])


class NBSPEntityElementHandler(InlineEntityElementHandler):
    """
    Database HTML to Draft.js ContentState.
    Converts the span tag into a NBSP entity, with the right data.
    """
    mutability = 'IMMUTABLE'

    def get_attribute_data(self, attrs):
        """
        Take the ``nbsp`` value from the ``data-nbsp`` HTML attribute.
        """
        return {
            'nbsp': attrs['data-nbsp'],
        }

@hooks.register('insert_editor_js')
def add_editor_js():
    js_files = [
        'wagtailadmin/js/draftail.js',
        'wagtail_draftail_nbsp.js'
    ]
    logging.info(settings.STATIC_URL + 'wagtail_draftail_nbsp.js')
    js_includes =format_html_join('\n', '<script src="{0}{1}"></script>',
        ((settings.STATIC_URL, filename) for filename in js_files)
    )
    return js_includes

```
4. add a wagtail_draftail_nbsp.js to static folder with this code:
```
(() => {
    'use strict';
  
    const React = window.React;
    const Modifier = window.DraftJS.Modifier;
    const EditorState = window.DraftJS.EditorState;

    // Not a real React component – just creates the entities as soon as it is rendered.
    class NBSPSource extends React.Component {
        componentDidMount() {
            const { editorState, entityType, onComplete } = this.props;
            
            const content = editorState.getCurrentContent();
            const selection = editorState.getSelection();
  
  
            // Uses the Draft.js API to create a new entity with the right data.
            const contentWithEntity = content.createEntity(entityType.type, 'IMMUTABLE', {
                nbsp: '&nbsp',
            });
            const entityKey = contentWithEntity.getLastCreatedEntityKey();
  
            // We also add some text for the entity to be activated on.
  
            const newContent = Modifier.replaceText(content, selection, '&nbsp', null, entityKey);
            const nextState = EditorState.push(editorState, newContent, 'insert-characters');
  
            onComplete(nextState);
        }
  
        render() {
            return null;
        }
    }
  

    window.draftail.registerPlugin({
      type: '&NBSP',
      source: NBSPSource,
    //   decorator: Nbsp,
    });
  })();
```
5. In models.py in wagtail_admin at one of the models which has blocks.RichTextBlock and add the nbsp feature
```
text = blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'underline', 'nblspace')
```
6. open the wagtail editor and try to add the new &NBSP entitie - 
7.BOOM - A BUG
* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.8.7
* Django version:3.1.5
* Wagtail version: 2.11.3
* Browser version: Chrome 87

**Comment by gasman** [comment]
Hi @noampolak - thanks for the report.

Please see #6724 and [the corresponding PR for fixing wagtailcolourpicker](https://github.com/Vadim-Karpenko/wagtailcolourpicker/pull/1) - rather than using the `insert_editor_js` hook to insert the `wagtail_draftail_nbsp.js` JS include, you should pass that as part of the `draftail_features.EntityFeature` call.

**Comment by noampolak** [comment]
Hi Thank you @gasman 
It worked
