### ISSUE TITLE
Random urlencode in page_listing_more_buttons

### ISSUE THREAD

**Issue by frasern** [wagtail/wagtail#6832]
### Issue Summary

There is a random unused `urlencode` in the `page_listing_more_buttons` function; line 207:

https://github.com/wagtail/wagtail/blob/ba6f94def17b8bbc66002cbc7af60ed422658ff1/wagtail/admin/wagtail_hooks.py#L202-L213

**Comment by zerolab** [comment]
Looks like it sneaked in e1a8dbf09e45e749d424cdc475711d63679f446a.
