### ISSUE TITLE
Can't specify ordering on construct_explorer_page_queryset hook

### ISSUE THREAD

**Issue by amxfonseca** [wagtail/wagtail#6848]
### Issue Summary

The wagtail page explorer sidebar ignores the ordering of the QuerySet returned by the `construct_explorer_page_queryset` hook.

Since wagtail 2.8 (probably due to the migration of the admin pages api) the ordering of the items for the explorer items is broken. Any custom ordering is ignored and the items are always ordered by `path`.

The problem is caused by the following line: https://github.com/wagtail/wagtail/blob/3c040acc88abd052c9d12c1d3b94a54166e2eb6a/wagtail/admin/api/filters.py#L39

Then `&` removes any existing order and sets it to `path`, because that's the default value that is present on the manager:
https://github.com/wagtail/wagtail/blob/3c040acc88abd052c9d12c1d3b94a54166e2eb6a/wagtail/core/models.py#L676

The order can still be set for the main explorer, only the sidebar explorer is broken since the main page listing does not use the api.

### Technical details

* Python version: N/A
* Django version: N/A
* Wagtail version: Wagtail >= 2.8
* Browser version: N/A

**Comment by amxfonseca** [comment]
I can see some possible quick solutions for this issue:

1. Change the place where we apply  the`queryset = queryset & user_perms.explorable_pages()` operation by doing it before we call the hooks
2. Make sure that the `user_perms.explorable_pages()` doesn't return any order information (`user_perms.explorable_pages().order_by()` restores the old behaviour)
3. Reverse the order of the operands of the `&` operation (`queryset = user_perms.explorable_pages() & queryset`)

The first approach is easier but it introduces some possible issues, because we may end up displaying pages that the user may not be allowed to see.

The second approach keeps the current filtering logic intact, but it requires some extra changes to the ` UserPagePermissionsProxy`

The last approach is also quite simple. I don't know the internal application of the `&` operator, but I assume it is commutative, so it should not impact the final result (when it comes to filtering)

**Comment by Stormheg** [comment]
Fixed in https://github.com/wagtail/wagtail/commit/6e77e0d415a9e127bb3593db9c69bc60b88e06ed (main) and https://github.com/wagtail/wagtail/commit/fa94ffc76b52f35e918c35e222b099a12b6cde08 + parents (stable/2.13.x) :tada:
