### ISSUE TITLE
Customizable name for the MenuItem in modeladmin

### ISSUE THREAD

**Issue by ARogovskyy** [wagtail/wagtail#6859]
There is currently no way to explicitly set the name of the `MenuItem` generated by `modeladmin`. This can be an issue if we want to, say, register two ModelAdmin's with the same label (for example for superuser and one for others, with different permissions). Then the name of the `MenuItem` is autogenerated from the label which leads to conflicts. An easy solution would be to add a `menu_name` to `ModelAdmin` which then gets passed to the `MenuItem` constructor in `ModelAdminMenuItem`. I could make a PR for this.

**Comment by nickmoreton** [comment]
I think that's already in place @ARogovskyy https://docs.wagtail.io/en/stable/reference/contrib/modeladmin/menu_item.html 

ModelAdmin.menu_label and Groups could be used to only view/edit the one the account can access?

**Comment by ARogovskyy** [comment]
As far as I see it, it is not implemented yet. `menu_label` is not the same as my proposed `menu_name`. The label is what's shown and the name is a unique identifier for the `MenuItem`. Currently, there is no way to set the label and name to different things.
