### ISSUE TITLE
When viewing users in a group, clicking next page brings you to list of all users

### ISSUE THREAD

**Issue by bmoe872** [wagtail/wagtail#6874]
### Issue Summary

When clicking to view users within a group. The pagination brings you to the list of ALL users, not the users within a specific group.

### Steps to Reproduce

1. Go to edit a group within wagtail
2. Click "View users in this group" in the top right.
3. If you have enough users in this group to necessitate pagination, click "next"

You'll now be viewing *all* users, not just the users within that group.

### Technical details

* Python version: 3.7.7
* Django version: 3.1.6.
* Wagtail version: 2.12

I believe it's due to this line:
https://github.com/wagtail/wagtail/blob/main/wagtail/users/templates/wagtailusers/users/results.html#L17

Where it's passing in the link url as `wagtailusers_users:index` - I think this needs to be a different named url, however I could not find the named url that matches the pattern: `wagtail/groups/<group id here>/users/`

**Comment by sagar-wal** [comment]
Hi ! I'd like to work on this.

**Comment by sagar-wal** [comment]
I was able to reproduce the bug. The above linked PR fixes it.

**Comment by gasman** [comment]
Fixed in #6880
