### ISSUE TITLE
Large amount of queries in wagtail admin

### ISSUE THREAD

**Issue by dest81** [wagtail/wagtail#6876]
### Issue Summary

I have noticed that sometimes wagtail admin is very slow when DEBUG=True. Quick look into django-debug-toolbar shows hundreds of queries.

### Steps to Reproduce

1. Install wagtail with debug_toolbar
2. Add simple custom Page into models.py
```
    class MyPage(Page):
          pass
```
3.  Run server
4.  Open wagtail admin and create MyPage
5.  Save MyPage and open edit view again  - you will see around 60 SQL queries in the debug_toolbar
6.  Submit for moderators approvals and then open page in edit view - now you will see around 400 queries

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes

### Technical details

* Python version:  3.8.2.
* Django version:  3.1.6.
* Wagtail version: 2.12.

Short investigation showed that function [current_workflow_state](https://github.com/wagtail/wagtail/blob/main/wagtail/core/models.py#L2834) is called few hundreds times. 
For example function [current_workflow_task_state](https://github.com/wagtail/wagtail/blob/main/wagtail/core/models.py#L2844) trigger function current_workflow_state 4 times per one call.

If I wrap current_workflow_task in cached_property decorator then number of queries goes down to 60.

Is it known issue? Shell I send a PR?

**Comment by femto113** [comment]
I wonder if this is something that recently got worse?  I just noticed it as well and put in this PR #6878

**Comment by KalobTaulien** [comment]
Hi @dest81 

This is a good note, thanks for bringing this up. 

So this is going to largely depend on the page you're viewing. If you're viewing the Images section (listing page) with 100 images per page, that's going to get very costly very quickly (especially when running renditions against each one for the first time). 

Likewise, on views that list lots of pages, or semi-custom views like using Wagtails ModelAdmin where you can define your own fields, this can get expensive as well. 

Middleware and context processors can play a role in adding queries as well. 

On a fresh install with ~100 pages and ~100 images and ~100 documents (any number is fine to test) are you still seeing 100's of database queries? Or is this only on an existing installation?

**Comment by dest81** [comment]
Hi @KalobTaulien, 

This is on fresh installed instance. I added simple custom page model (without images) into models.py and create one object of it. Issue I am talking about can be seen only if you open EditPage view and page is submitted for moderators approvals.
So it's not about list view, that's why I found it very strange. @femto113 PR would work, I was going to send similar.
I think it is safe to use cached_property as page is not going to be change during opening in edit mode. 
However maybe you want to know what is calling 400 times current_workflow_task function...
I didn't spend too much time investigating it as I wasn't sure it is unknown issue.
As I wrote in the description function current_workflow_task_state
triggers four times so if we improve it number of queries will be 3 times lower. But it won't make sense if we will use cached_property decorator with current_workflow_task.

**Comment by femto113** [comment]
My first guess would be the reference in `PagePermissionsTester.page_locked`, it wouldn't surprise me if it gets touched a lot by various pieces of the UI deciding which controls to show
https://github.com/wagtail/wagtail/blob/e05081a1abe0f98666f3c8702265ce38c811a0e5/wagtail/core/models.py#L3313

**Comment by femto113** [comment]
Maybe became a (bigger) issue with this commit? https://github.com/wagtail/wagtail/commit/f4a1467b7e38a1571ba94f68923bd66229640030

**Comment by ababic** [comment]
@femto113 Out of interest, do you see any improvement after disabling the `debug_toolbar.panels.templates.TemplatesPanel` panel from `django-debug-toolbar`? You can do this using the `DEBUG_TOOLBAR_PANELS` setting.

**Comment by femto113** [comment]
@ababic I don't have the debug toolbar enabled (or even installed).

**Comment by zerolab** [comment]
Fixed in b215573 + parents via #6946. Thank you all!
