### ISSUE TITLE
Documentation search: tweak search term highlight design

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#6885]
Follow-up to #6833 from Tom: https://github.com/wagtail/wagtail/pull/6833#issuecomment-786558723:

> I dislike the standard RTD search term highlighting, and I usually remove the `?highlight=video` param before sharing search results, e.g. in responses to support questions on Slack. I'd be in favour of removing that styling here - what do others think?

Here is the code that handles this. I think removing the highlight would just be a matter of removing this code: https://github.com/wagtail/wagtail/blob/23f146c7e115fc1daa342b6084ee94531cbe44dd/docs/_templates/search.html#L61-L64

**Comment by Scotchester** [comment]
What if we just made the styling less obnoxious / more easy to read? The current link color and regular text color massively fail a contrast check:

![color contrast calculation for link text on highlight background](https://user-images.githubusercontent.com/1044670/110348404-9d74d600-7fff-11eb-9634-05fd7604c472.png)

![color contrast calculation for link text on highlight background](https://user-images.githubusercontent.com/1044670/110348688-e9c01600-7fff-11eb-92c9-88e26a44c7d9.png)

Just significantly lightening the background color would help a lot.

**Comment by tomdyson** [comment]
Or could we just embolden, like Google results?

<img width="733" alt="screenshot 2021-03-08 at 17 10 43@2x" src="https://user-images.githubusercontent.com/15543/110462848-1db33e00-80c9-11eb-906a-a435f53c2ab7.png">

**Comment by thibaudcolas** [comment]
As far as I understand this issue is only about highlighting matching terms on pages linked from search results with the `?highlight=demo` parameter: https://docs.wagtail.io/en/latest/getting_started/demo_site.html?highlight=demo

More problematic example color-wise: https://docs.wagtail.io/en/latest/getting_started/demo_site.html?highlight=start

If we remove this then it’s just a matter of not adding those `highlight` query parameters in search results.

If we want to retain the feature, I think it’s important for it to have styles that are relatively jarring so the highlight can’t be confused with the page’s normal formatting. However, we could use bold for the highlight in the DocSearch autocomplete, and on the search results page, if we’re happy to have different styles from the `?highlight` feature.

**Comment by Scotchester** [comment]
I think the feature is worth retaining. My query for Tom was whether less-jarring highlighting would appease his original concern. From his reply to this issue, it seems like it would.

I think you're right, Thibaud, that it should be jarring enough not to be confused with regular formatting – I'm not sure just bolding would suffice – but whatever we land on, it does still need to meet minimum color contrast requirements.

**Comment by tomdyson** [comment]
Can we vote on this comment to gauge opinion? 

 👍🏼 = 'we should keep highlighting'
 👎🏼 = 'we should remove highlighting'

**Comment by thibaudcolas** [comment]
I forget how and when we went about this, but it looks like the current highlighting styles match the requirements outlined above of providing high enough contrast, while not messing with spacing. So I’ll close this now.

Screenshot for reference: 

![wagtail docs highlight screenshot, with high-contrast grey over yellow background for highlighted text](https://user-images.githubusercontent.com/877585/135456251-249c5042-dc80-4a83-a578-28a55bc53882.png)

Code where those styles are defined if we want to revisit this: https://github.com/wagtail/sphinx_wagtail_theme/blob/b6f35d5ca5a47f0a3df4ef4446e1a3176d9f0889/sass/_component_search.scss#L31-L37
