### ISSUE TITLE
Documentation search: pagination for results page

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#6886]
Follow-up to #6833 – it would be nice to add pagination to our search results page, which is currently limited to the top 50 results: https://docs.wagtail.io/en/latest/search.html?q=pages.

The results page is mostly custom, and currently "50" is hard-coded. We’d need to implement the pagination logic, and UI: https://github.com/wagtail/wagtail/blob/23f146c7e115fc1daa342b6084ee94531cbe44dd/docs/_templates/search.html#L34.

**Comment by Tijani-Dia** [comment]
Hello, I would like to implement the pagination logic and UI if someone isn't already working on it.
However I have a question here because I don't know how can I live preview the documentation website.
So how can I know if what I am doing is right or not ?
Thanks in advance

**Comment by thibaudcolas** [comment]
There is a WIP implementation of pagination in #6902, which I had to close because the PR’s source branch has been removed. I don’t think this was too far off from being merge-able if you want to resume this @Tijani-Dia, or if someone else wants to take over.

Here are the further changes I think are needed: https://github.com/wagtail/wagtail/pull/6902#pullrequestreview-859538745.

**Comment by zerolab** [comment]
The changes are available as a diff - https://patch-diff.githubusercontent.com/raw/wagtail/wagtail/pull/6902.diff - if needed

**Comment by PaarthAgarwal** [comment]
I am starting to work on this issue

**Comment by lb-** [comment]
@PaarthAgarwal here are the docs on how to compile the docs. 

https://docs.wagtail.org/en/stable/contributing/developing.html#compiling-the-documentation

Does that help?

**Comment by PaarthAgarwal** [comment]
That'll do. Thanks! @lb-

**Comment by PaarthAgarwal** [comment]
I have made changes as suggested by @thibaudcolas. Also to maintain consistency in UI I have modified docs pagination nav style to be consistent with that of wagtail admin's. It will look like this: 
![image](https://user-images.githubusercontent.com/86092410/158794063-dbb45e9e-98f1-4502-953f-493caa57f007.png)

**Comment by PaarthAgarwal** [comment]
Need a review on #8178.
