### ISSUE TITLE
New documentation search lacking results for Wagtail settings

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#6887]
With the new Algolia DocSearch merged (#6833), there are a few cases where the results aren’t as good as they could be – in this instance, Wagtail settings such as `WAGTAILIMAGES_INDEX_PAGE_SIZE`, because they’re only used in code blocks, which aren’t indexed.

### Describe the solution you'd like

We should add a heading for each setting on https://docs.wagtail.io/en/stable/reference/settings.html, so the setting variable is in the non-code-block content, and so we can link to the documentation about a specific setting. I would suggest keeping the existing headings as-is, and just adding sub-headings, so we can keep all existing links.

### Additional context

- Current DocSearch results: https://docs.wagtail.io/en/latest/search.html?q=WAGTAILIMAGES_INDEX_PAGE_SIZE
- Previous RTD results: https://docs.wagtail.io/en/stable/search.html?q=WAGTAILIMAGES_INDEX_PAGE_SIZE

**Comment by zerolab** [comment]
https://github.com/algolia/docsearch-configs/blob/c184ae3c34206cfa326fc218f6ad912119ddbce6/configs/wagtail.json is the configuration for our docs. 

We could ask to add `code[lang=python]` to the selectors, but this may dillute results. Algolia suggest key code snippets to be included in headings/regular content

https://github.com/facebook/docusaurus/issues/3172 has more relevant information in this space

**Comment by thibaudcolas** [comment]
Yes, I should have mentioned the above is based on Algolia’s recommendation at https://docsearch.algolia.com/docs/faq/#can-you-index-code-samples.
