### ISSUE TITLE
No explanation why pg search backend is archived

### ISSUE THREAD

**Issue by abitrolly** [wagtail/wagtail#6896]
Is https://github.com/wagtail/wagtail-pg-search-backend deprecated? When? How to port old code? Which `wagtail` version still supports it? Thanks. )

Would be nice to get some clarifications to the repo description or to the top of its `README.md`.

**Comment by gasman** [comment]
Hi @abitrolly,
The wagtail-pg-search-backend project is archived as this functionality is now [included in Wagtail](https://docs.wagtail.io/en/stable/reference/contrib/postgres_search.html) - have now updated the readme to clarify this.

**Comment by abitrolly** [comment]
@gasman nice to know. Which version of Wagtail already includes these changes?

**Comment by gasman** [comment]
It's been included since Wagtail 1.10.
