### ISSUE TITLE
Documentation and support for autocomplete on postgres backend

### ISSUE THREAD

**Issue by magicaljellybeans** [wagtail/wagtail#6900]
I've seen from [this PR](https://github.com/wagtail/wagtail/pull/5960) that we can unofficially use partial-matching on a postgres backend, at least for `title`.

Is this in the scope for being documented at some point, and further, is there a possibility of having multiple AutocompleteFields in a model?

We have a search function whereby people can search normally, but then also by `url_path` when specifying 'path:' as a prefix in their search. I was unable to implement this and from what I understand from the above PR, this is the expected behaviour?

**Comment by gasman** [comment]
AutocompleteField is now documented at https://docs.wagtail.org/en/stable/topics/search/indexing.html#index-autocompletefield, and as of 5.0, is used consistently by all search backends.
