### ISSUE TITLE
Allow subclasses to override how AbstractFormField.clean_name is set

### ISSUE THREAD

**Issue by jsma** [wagtail/wagtail#6903]
### Is your proposal related to a problem?

In Wagtail 2.10,  ``AbstractFormField.clean_name`` became a proper model field (introduced in #6093) and the ``save()`` method handles setting the value based on ``self.label``. 

We have heavily customized subclasses of ``AbstractFormField`` which are used for questionnaires. The questions can be quite long so we overrode ``label = models.TextField()``.  We in turn overrode ``self.clean_data`` to be a property that simply returned ``str(self.sort_order)`` as a quick hack to create a unique value since using the label would be ridiculous in our scenario. The customized property unfortunately masked the upgrade incompatibilities since the new model field was not detected by ``makemigrations`` and ``AbstractFormField._migrate_legacy_clean_name()`` didn't catch this since it queried against a non-existent field. We only uncovered this issue because someone tried to add a new question which raised ``AttributeError: can't set attribute``. 

I realize that heavy customizations almost always get their revenge and they are our responsibility, but there aren't any obvious and acceptable options forward for us. The least ugly workaround was to create an intermediate abstract class to override ``AbstractFormField.save()`` so we can set ``self.clean_name`` but this means that instead of calling ``super()``, we have to bypass that in the MRO and call ``Orderable.save(self, *args, **kwargs)`` instead. I am unhappy with this workaround since we'll now have to closely track any updates to ``AbstractFormField.save()`` but this solved the immediate issue (we also wrote our own data migration to populate existing rows since ``_migrate_legacy_clean_name`` will not work in our case).

### Describe the solution you'd like

A simple change to how ``clean_name`` is set would allow us to more cleanly override this specific bit while still being able to allow the normal ``super().save()``.

Instead of:

```python
def save(self, *args, **kwargs):
    """
    When new fields are created, generate a template safe ascii name to use as the
    JSON storage reference for this field. Previously created fields will be updated
    to use the legacy unidecode method via checks & _migrate_legacy_clean_name.
    """

    is_new = self.pk is None
    if is_new:
        clean_name = get_field_clean_name(self.label)
        self.clean_name = clean_name

    super().save(*args, **kwargs)
```

What about moving this out so subclasses can decide how to best generate ``clean_name``?

```python
def get_field_clean_name():
    return get_field_clean_name(self.label)

def save(self, *args, **kwargs):
    """
    When new fields are created, generate a template safe ascii name to use as the
    JSON storage reference for this field. Previously created fields will be updated
    to use the legacy unidecode method via checks & _migrate_legacy_clean_name.
    """

    is_new = self.pk is None
    if is_new:
        clean_name = self.get_field_clean_name()
        self.clean_name = clean_name

    super().save(*args, **kwargs)
```

This would let us simply override the single ``self.get_field_clean_name()`` in our implementation and everything else will work as usual.

I can write up a PR if this would be an acceptable change. Thanks!

**Comment by spapas** [comment]
Hello this is a nice approach; I also have problems with the way this works currently because if the label of a field is in greek it results to a unicode mess (check my faq https://github.com/spapas/wagtail-faq#whats-that-unicode-related-mess-i-see-in-my-field-names-when-i-use-non-english-characters-as-labels-in-my-wagtail-forms). 

To solve this I also rely on using the grand-parent save trickery but I'd be happy to use something better :)

**Comment by lb-** [comment]
Others on Slack having similar issues and wanting more fine grained control over how the clean name is used.

https://wagtailcms.slack.com/archives/C81FGJR2S/p1644836238191899
![Screen Shot 2022-02-17 at 9 14 45 pm](https://user-images.githubusercontent.com/1396140/154470287-c3e7eb09-25a3-4c3f-906f-58df45ecd832.png)

https://wagtailcms.slack.com/archives/C8
![Screen Shot 2022-02-17 at 9 15 41 pm](https://user-images.githubusercontent.com/1396140/154470589-b05cae2d-2e48-462d-9775-75c431f75991.png)
1FGJR2S/p1635249238104500?thread_ts=1635161889.081800&cid=C81FGJR2S

**Comment by lb-** [comment]
@jsma I would love your thoughts on https://github.com/wagtail/wagtail/pull/8008 (including the documentation added for it).

Specifically this commit https://github.com/wagtail/wagtail/pull/8008/commits/d0a79b485f7c004a578b914af8d01af7a73dbd0b

**Comment by lb-** [comment]
Also @jsma I have just now read your full issue and I realise now that the way we implemented the migration approach was not ideal.

I re-read the release notes from 2.10 and while they do mention this change it very much could have been clearer how the data migration takes place (via the checks).

**Comment by jsma** [comment]
Thanks for the reply and your work on this! Reviewing now but so far looks like this will resolve our issue. Thanks again!
