### ISSUE TITLE
modeladmin: Breadcrumbs visual bugs

### ISSUE THREAD

**Issue by thatguystone** [wagtail/wagtail#6904]
### Issue Summary

In modeladmin's inspect views, the breadcrumbs are not aligned correctly (relative to the ones in the page explorer).

On desktop:
![breadcrumbs-desktop](https://user-images.githubusercontent.com/921573/110705298-0e0c2600-81ab-11eb-8b7d-a1d06b6047e4.png)

On mobile:
![breadcrumbs-mobile](https://user-images.githubusercontent.com/921573/110705305-0fd5e980-81ab-11eb-9fd3-7211ef178c49.png)

### Steps to Reproduce

1. Create a model
2. Create the corresponding ModelAdmin register it.
3. Set inspect_view_enabled to True on that ModelAdmin
4. Navigate to the ModelAdmin index page.
5. Click Inspect on one of the instances.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.9.1
* Django version: 3.1.7
* Wagtail version: 2.12.3
* Browser version: chrome 89

**Comment by lb-** [comment]
This was fixed with the new sidebar rework in 3.0 but in 4.0 these breadcrumbs will be removed.
