### ISSUE TITLE
Documentation pages auto-scroll down on load

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#6935]
As of https://github.com/wagtail/wagtail/commit/328e7012fccb3a61aefbfe1ede9c9e61ff2b0d91 , visiting a documentation page such as https://docs.wagtail.io/en/latest/releases/2.5.html causes the page to jump down so that the current menu item is aligned to the top of the window. Previously, the menu had an independent scrollbar, so this auto-scrolling happened without affecting the main page content.

* Browser version: Chrome 89.0.4389.82 and Firefox 86.0

**Comment by thibaudcolas** [comment]
Fixed by #7015.
