### ISSUE TITLE
after_publish hooks do not run if "Approve and publish" is chosen by a moderator

### ISSUE THREAD

**Issue by jmichalicek** [wagtail/wagtail#6949]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

after_publish hooks do not run when a moderator selects "Approve and publish"

### Steps to Reproduce

1. Create an "after_publish" wagtail hook. I like to use one which prints to stdout so I can easily watch django dev server output in my terminal.
2. Create a page or a revision and select "Submit for moderation"
3. Edit the page as a moderator and select "Approve and publish"
3. See that the hook did not run
4. Validate by just choosing publish to verify that it does run then.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no) Yes.

### Technical details

* Python version: Python 3.9.2
* Django version: 3.1.7
* Wagtail version: 2.12.3
* Browser version: Firefox 87

**Comment by jmichalicek** [comment]
Just took a quick look at how that is implemented. I suspect for my current use case I could make use of `page_published` signal, although that does fire more often and at a different time and so is not necessarily always a good replacement.

Would it be a good idea to have something along the lines of `wagtail.core.models.WorkflowState` inherit from `HookResponseMixin` `wagtail.core.workflows.publish_workflow_state` call `workflow_state.publish_action()`? I haven't tested yet, but it looks like that would work unless there's a reason not to do so. That could be weird or not feasible because of the hooks taking a request as an arg and potentially returning a response.

**Comment by jacobtoppm** [comment]
The workflow model doesn't usually deal with the request directly, and a workflow doesn't have to publish on finish - it could do other things. I think it might be better to have some check in the view that calls the hook if the publication happens - at its simplest, maybe just by checking if `live_revision` changes after the action - but I'll have to think about the best way to do this!

**Comment by jmichalicek** [comment]
Thanks for looking into it. It's certainly interesting. I would expect `after_publish` to always be fired after a publish, however that happens be it hitting publish, a workflow, and possibly when calling page.publish(). But at first glance all of the obvious places to make that happen would also change when in the overall process that is happening which could effect people and as mentioned, they don't all have a request or any reason to have one.

Thanks, again. I've got other solutions which will work for my use case with the signals or just overriding publish().

**Comment by jacobtoppm** [comment]
So our general rule for those hooks is that they're to modify admin behaviour, so they can depend on the path through the admin. For model level behaviour, ie if you want something to trigger even if an action happens programmatically, it's definitely best to use signals.

**Comment by lb-** [comment]
Closing as this seems to be solved with using signals, and the behaviour requested does not align with how the hooks should be working.
