### ISSUE TITLE
IE11 support currently broken for Draftail/telepath

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#6961]
We switched to using the TypeScript compiler for building both JavaScript and TypeScript to make it easy to integrate the two. The problem is TSC is not converting ES6 JavaScript to ES5 JavaScript, as it only compiles TypeScript to ES5.

This means that ES6 JS components (telepath and Draftail) are currently broken on IE11.

**Comment by gasman** [comment]
Closed as per #6968
