### ISSUE TITLE
Formalise Django 3.2 support

### ISSUE THREAD

**Issue by ahumeau** [wagtail/wagtail#6981]
Django 3.2 has just been [released](https://www.djangoproject.com/weblog/2021/apr/06/django-32-released/)!
Although Wagtail seems to support it (I've seen tests are run against Django master) it is excluded in `setup.py` (`"Django>=2.2,<3.2"`).

It is an issue because the [Poetry](https://python-poetry.org/) package manager cannot install packages declared as being incompatible ([source](https://github.com/python-poetry/poetry/issues/697#issuecomment-470431668)). That means that people currently using Wagtail and Poetry (me for example :D) cannot upgrade to Django 3.2 (not easily at least).

**Comment by kelvan** [comment]
hi, is it planned to include this in wagtail 2.11(.8) LTS?

**Comment by gasman** [comment]
@kelvan No, the LTS branch only receives stability / security fixes, and support for new Django versions wouldn't fall in that category.

**Comment by kelvan** [comment]
@gasman thanks for the info
