### ISSUE TITLE
Add filtering by page type to the page explorer view

### ISSUE THREAD

**Issue by ArthurConan** [wagtail/wagtail#6982]
Hi!
Sometimes Parent Page has many child pages with different type. And when amount of these pages is huge - it's difficult to find/edit the necessary type. 
For example, Blog page has Post pages, Author pages, Tag pages etc. Each type of pages has about 45-100 instances. And you want to edit ONLY Post Pages. So you need firstly to filter them, but Wagtail Page Explorer doesn't have such feature. ### **What about to have it?** 
* ModelAdmin sometimes doesn't fit due to project requirements and issues with localize features.
* _construct_explorer_page_queryse_t hook also doesn't fit - cause it works on a constant basis and you can't turn on/off it.

If Wagtail Admin Explorer has such functionality - I am really sorry for distracting you!!!
Thanks!

**Comment by laymonage** [comment]
I believe this will be covered in #10446.

**Comment by thibaudcolas** [comment]
Implemented in #11339 by @gasman 🌈
