### ISSUE TITLE
Those who don't have publish access are able to see "Waiting you review" section

### ISSUE THREAD

**Issue by SysSn13** [wagtail/wagtail#6995]
### Issue Summary

I am using wagtail for a website and I have created a group for editors which has add and edit permission for all the pages. Editors have to submit pages for moderation for publishing but they are also getting the Awaiting your review section on the home page and they have the right to publish a page in that section. I don't know why this is happening. Is there any bug or Am I missing something?
![Home admin page](https://user-images.githubusercontent.com/48723832/114347472-9dc63b00-9b82-11eb-8590-cd8bf53a03bd.png)
![Group settings](https://user-images.githubusercontent.com/48723832/114347525-b0d90b00-9b82-11eb-94bd-ed5a048bb711.png)
### Steps to Reproduce

1. Create ​a group with **add** and **edit** permissions for the root page.
2. Add a user to this group.
3. Make some changes to a page by this user and submit for moderation. 
4. Now open the home page of the admin panel where you see Awaiting your review section.
5. You can approve your own changes.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

* Python version:  **3.8.5**
* Django version: **3.1.2**
* Wagtail version:  **2.11.1**
* Browser version: **Chrome 89**

**Comment by gasman** [comment]
Hi @SysSn13 - thanks for the report.
I can't replicate this as described when testing against the [bakerydemo](https://github.com/wagtail/bakerydemo) test project, with the following setup:

* Added group 'test editors', with permission 'Can access Wagtail admin' and Add / Edit page permissions on root
* Created user as a member of 'test editors', all other options unchecked
* Logged in as that user, edited the 'Contact us' page and clicked "Submit to moderators approval"
* On the dashboard, the panels shown are "Your pages in a workflow" and "Your most recent edits" - there is no "Awaiting your review" section.

Did you tick the Administrator checkbox when creating the user, perhaps? This will override the group-based permissions and give that user all permissions including publishing.

Closing for now as unable to replicate, but happy to investigate further if you can provide working steps that reproduce the issue.

**Comment by SysSn13** [comment]
No, I didn't tick any other checkbox. You can see the screenshot of user roles.
![user permissions](https://user-images.githubusercontent.com/48723832/114376350-2bb21e00-9ba3-11eb-87e5-9e1b1b308f34.png)

**Comment by gasman** [comment]
I notice that the menu in your first screenshot has the "Settings" item, which wouldn't happen for an editor with the permissions shown here, so it seems that there's something else in your site configuration that's giving them extra permissions. Again, if you can provide detailed steps for replicating this on a _new_ Wagtail instance (using either `wagtail start` or the bakerydemo project as a starting point) then I can investigate further.
