### ISSUE TITLE
Remove deprecated chooser_panel.html template

### ISSUE THREAD

**Issue by Stormheg** [wagtail/wagtail#6997]
### Issue Summary

While working on [refactoring icons to use svg icons](https://github.com/wagtail/wagtail/issues/6107) I noticed we have a  [wagtail/admin/templates/wagtailadmin/edit_handlers/chooser_panel.html](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/edit_handlers/chooser_panel.html)
which was marked as deprecated 6 years ago: https://github.com/wagtail/wagtail/commit/13e1811c544b8694408b0b40740e4ade935eae4a

> 
<pre>
    ------
    DEPRECATED - provided for backwards compatibility with custom (third-party) chooser panels
    created prior to Wagtail 0.9. New choosers should subclass wagtail.admin.widgets.AdminChooser,
    with a template that extends wagtailadmin/widgets/chooser.html.
    ------
</pre>

Perhaps the time has come to finally remove it?

**Comment by amelia291** [comment]
This is still visible in the latest version 2.15.1 - I also think it's time to clean this up.
