### ISSUE TITLE
Broken background styling on documentation menu

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#7004]
Similar to #6935, another documentation styling regression introduced in 328e7012fccb3a61aefbfe1ede9c9e61ff2b0d91 - on a URL such as https://docs.wagtail.io/en/latest/reference/index.html , menu items below the current expanded section are missing the expected black background and end up showing as light grey on light grey.

<img width="313" alt="Screenshot 2021-04-14 at 11 17 35" src="https://user-images.githubusercontent.com/85097/114695128-2a9ffe80-9d13-11eb-88a4-4a17c95a6ca2.png">

**Comment by thibaudcolas** [comment]
This issue will be partly addressed in #7015 – it’ll still happen, but only when the search dropdown is open.

**Comment by gasman** [comment]
Thanks @thibaudcolas! On the current version I'm not seeing it even with the search active, so happy to call this done.
