### ISSUE TITLE
Add ancestor_of filter to Wagtail pages API

### ISSUE THREAD

**Issue by jaap3** [wagtail/wagtail#7007]
We're using Wagtail as an headless CMS for a Vue/Nuxt site and recently had the need to find ancestors of a page to show a breadcrumb trail. Currently the API has a descendent_of filter, but not the other way around.

We've implemented a filter (heavily inspired by Wagtail's existing `DescendantOfFilter`) and added it to the `PagesAPIViewSet`, but it seems like a nice addition to API in general.

We've also found another use case for this filter. When a site has multiple index pages for a specific page type the `ancestor_of` filter can be combined with the `type` filter to find a specific type of ancestor for the current page.

Would this be accepted in Wagtail?

```
class AncestorOfFilter(BaseFilterBackend):
    """
    Implements the ?ancestor filter which limits the set of pages to a
    particular branch of the page tree.
    """
    def filter_queryset(self, request, queryset, view):
        if 'ancestor_of' in request.GET:
            try:
                descendant_page_id = int(request.GET['ancestor_of'])
                if descendant_page_id < 0:
                    raise ValueError()

                descendant_page = view.get_base_queryset().get(id=descendant_page_id)
            except ValueError:
                raise BadRequestError("ancestor_of must be a positive integer")
            except Page.DoesNotExist:
                raise BadRequestError("descendant page doesn't exist")

            queryset = queryset.ancestor_of(descendant_page)

        return queryset
```

**Comment by kaedroho** [comment]
Thanks @jaap3, yes a pull request for this would be very welcome!

**Comment by jaap3** [comment]
I'll try to find some time soon to work on a PR with tests and docs
