### ISSUE TITLE
Add alias_of to page meta in api response

### ISSUE THREAD

**Issue by jaap3** [wagtail/wagtail#7009]
We started using aliases and needed to find a way to determine if the current page is an alias in order to set a rel=canonical header pointing to the original page.

The API currently doesn't provide a way to distinguish a normal page from an alias.

As noted in [this stackoverflow answer](https://stackoverflow.com/questions/66581694/expose-page-alias-in-wagtail-api/67107694) this can be achieved be serializing the alias_of relation.

```
from rest_framework import serializers

from wagtail.api import APIField
from wagtail.core.models import Page

class AliasPageSerializer(serializers.ModelSerializer):
    class Meta:
        model = Page
        fields = ('id', 'full_url')

class BasePage(Page):
    class Meta:
        abstract = True

    api_meta_fields = [
        APIField('alias_of', serializer=AliasPageSerializer()),
    ]
```

Would you consider adding this to Wagtail?

**Comment by nmalacarne** [comment]
@jaap3 Are you working on this or do you mind if I do?

**Comment by jaap3** [comment]
@nmalacarne  Go ahead, I'm not working on it
