### ISSUE TITLE
Add instructions on copying and aliasing pages to the Editor's guide

### ISSUE THREAD

**Issue by jaap3** [wagtail/wagtail#7010]
Currently there's no information on how to copy/alias a page in Wagtail. This feature is very nice, but hard to discover. Editors could benefit from some pointers and screenshots in the Editor's guide section of the Wagtail docs.

**Comment by vladutmd** [comment]
I got started on this using the wagtail bakery demo site. For copying a page, the uses/reasons can be many. I decided to focus on the following use:

**Copy a page when one wants to recreate a page with a few changes.**

For aliasing a page, however, would the following use case be the right one to choose?

**Alias a page when one wants to have a (synchronised) copy of it in a different location**. e.g. a Bread page that would appear in the list of Breads but could also appear in a Features/Favourites section. 

Are those use cases appropriate for explaining the copy/alias instructions?

**Comment by jaap3** [comment]
I think those are reasonable use cases. For the alias example in context of the bakery demo site I could imagine that a page about [brioche](https://en.wikipedia.org/wiki/Brioche) could go in the both the bread and pastry sections as a topical example.

**Comment by zerolab** [comment]
Fixed in f54e7e1 via #7068
