### ISSUE TITLE
SearchFields system checks

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#702]
We should make use of Django 1.7 system checks to validate the SearchFields configuration.

Checks:
- All search and filter fields must be an attribute of the class
- ~~Filter fields cannot contain callables (as theres no way to make a Django ORM query for these)~~

**Comment by lb-** [comment]
@kaedroho  / @timheap  - I could be wrong but it appears that this may have been implemented in 2016

https://github.com/wagtail/wagtail/commit/1dad100695060435b597545cd61c3ee420afee9f

And current state of file

https://github.com/wagtail/wagtail/blob/master/wagtail/search/index.py#L110

**Comment by lb-** [comment]
Closing this ticket as this appears to have been implemented, feel free to reopen if that is not the case.
