### ISSUE TITLE
Locale filter in the page chooser

### ISSUE THREAD

**Issue by finnjbm** [wagtail/wagtail#7039]
When selecting a root page in a site in the admin interface, the helpful tags displayed on the page explorer aren't displayed. e.g., instead of `My Home Page [English]` it would just be `My Home Page`. Because of this, with multiple locales it just appears as having duplicate pages.

The fix would obviously just be adding a locale tag to the page names.

**Comment by kaedroho** [comment]
Thanks for reporting this!

Basically, we need a locale selector on the page chooser. This is something we know about but haven't got a ticket for at the moment.

**Comment by zerolab** [comment]
Note that this is pretty much done via:

* #7862
* #7837
* #7839
* #7867

The site history report is WIP in #7895 as it needs more work

**Comment by zerolab** [comment]
Closing on the basis that the original scope was completed in #7862
