### ISSUE TITLE
Help text of StructBlock showing with comma's in v.2.13rc1

### ISSUE THREAD

**Issue by Warqus** [wagtail/wagtail#7059]
### Issue Summary

Thanks for the new Wagtail update! I noticed a small bug with the following code:

```
from django.utils.translation import ugettext_lazy as _

from wagtail.core import blocks


class BlockPluginWrapper(blocks.StructBlock):
    plugin_background = blocks.BooleanBlock(
        required=False,
        default=False,
        help_text=_('if true, the background will be gray.'),
        group='wrapper'
    )
    plugin_title = blocks.CharBlock(
        max_length=150,
        required=False,
        help_text=_('optional'),
        group='wrapper'
    )

    class Meta:
        form_template = 'blocks/block_plugin_wrapper.html'
```

I get the following help text shown in the admin:

![image](https://user-images.githubusercontent.com/14151318/115554198-80921a80-a2ae-11eb-83e9-b5154a603416.png)

Without the django.utils.translation.ugettext_lazy tag, it is showing properly.

### Technical details

* Python version: 3.7.9.
* Django version: 3.2.
* Wagtail version: v2.13rc1.

**Comment by gasman** [comment]
Thanks for the report @Warqus! I suspect [telepath isn't recognising the lazy translation object as a string](https://github.com/wagtail/telepath/blob/1385fb9fbd3eb7bddc1d1220e92c57917260b405/telepath/__init__.py#L215) when encoding it to pass to the front-end, so instead it's recognising that it's iterable and treating it as a list.
