### ISSUE TITLE
Comments float in strange places when written in a collapsed MultiFieldPanel

### ISSUE THREAD

**Issue by KalobTaulien** [wagtail/wagtail#7064]
When writing a comment a MultiFieldPanel that's collapsed by default in Wagtail 2.13rc1 the comment boxes float in slightly strange places.

Preview: 

https://user-images.githubusercontent.com/4743971/115608882-11afc400-a2a4-11eb-87b4-f1c0c6103c3b.mp4

And when I delete a comment that's inside a MultiFieldPanel, the _other_ comment (from the video demo) jumps to the top. Example below:
![image](https://user-images.githubusercontent.com/4743971/115609191-779c4b80-a2a4-11eb-9cbd-057b3963b4bb.png)

**Comment by jacobtoppm** [comment]
Thanks for catching this! This was also a problem with collapsed streamfield blocks. Hopefully the link PR will address this now.
