### ISSUE TITLE
Bulk adding redirects

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#707]
I would expect this to work by uploading a CSV file or something along those lines. Would be useful for SEO work and when replacing an old site with a Wagtail site where the sitemap has changed considerably. This can be done server side but this way it can be managed by editors.

**Comment by davidjamesharris** [comment]
+1 on this after experience with CIFF and CEB

**Comment by gasman** [comment]
A third-party module exists for this: https://github.com/Frojd/wagtail-redirect-importer

**Comment by zerolab** [comment]
#5949 is the PR that adds the above module to core.

**Comment by gasman** [comment]
Completed in #5949
