### ISSUE TITLE
Field panels play a transition every times the admin page loads - v2.13rc1

### ISSUE THREAD

**Issue by fabienheureux** [wagtail/wagtail#7075]
### Issue Summary

Every times a page loads in Wagtail admin 2.13rc1, the transition resizing the fields plays.   
It is supposed to play when comment feature is triggered, but seems a bit odd to have it play on first page load. 

### Steps to Reproduce

1. Update wagtail to v2.13rc1
2. Edit a page in the admin 
3. The fields expands to fill the page

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Python 3.8.9
* Django version: Version: 3.1.8
* Wagtail version: Version: 2.13rc1
* Browser version: Firefox 88

**Comment by fabienheureux** [comment]
The transition has been introduced in this commit: https://github.com/wagtail/wagtail/commit/2cbeed858f67a7bd82bdaf04257d2d07579c0a96 
At this line exactly: https://github.com/wagtail/wagtail/blob/2cbeed858f67a7bd82bdaf04257d2d07579c0a96/wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss#L484

**Comment by fabienheureux** [comment]
It looks like comments are enabled by default on first load:
https://github.com/wagtail/wagtail/blob/2cbeed858f67a7bd82bdaf04257d2d07579c0a96/wagtail/admin/templates/wagtailadmin/edit_handlers/tabbed_interface.html#L30

Then disabled using JavaScript
https://github.com/wagtail/wagtail/blob/2cbeed858f67a7bd82bdaf04257d2d07579c0a96/client/src/entrypoints/admin/page-editor.js#L388

**Comment by kaedroho** [comment]
Thanks @fabienheureux!

We've decided to remove this transition entirely since it looks a little weird on some fields.
