### ISSUE TITLE
Comment feature is enabled on RichTextField in Snippets in v2.13rc1 but does not work

### ISSUE THREAD

**Issue by fabienheureux** [wagtail/wagtail#7076]
### Issue Summary

Using a `RichTextField` in a snippet displays the comment icon in Draftail, but clicking it does nothing. 
I am not sure if it is supposed to be enabled on non-page models. 

### Steps to Reproduce

1. Update wagtail to v2.13rc1
2. Edit a snippet containing a RichTextField in the admin
3. The comment icon displays
4. Clicking the icon turns the text to green but does nothing

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Python 3.8.9
* Django version: Version: 3.1.8
* Wagtail version: Version: 2.13rc1
* Browser version: Firefox 88

![image](https://user-images.githubusercontent.com/1702255/115705367-bbf31e80-a36c-11eb-867a-ea90c6812513.png)

**Comment by jacobtoppm** [comment]
You're correct, comments should not be enabled on non page models. I'll look into this, thanks!
