### ISSUE TITLE
blocks.BooleanBlock not working in Streamfield in 2.13rc1

### ISSUE THREAD

**Issue by Warqus** [wagtail/wagtail#7083]
### Issue Summary

Whenever I select blocks.BooleanBlock in a streamfield, when saved, the value is not stored.

### Steps to Reproduce

```
from django.utils.translation import ugettext_lazy as _

from wagtail.core import blocks


class BlockPluginWrapper(blocks.StructBlock):
    plugin_background = blocks.BooleanBlock(
        required=False,
        default=False,
        help_text=_('if true, the background will be gray.'),
        group='wrapper'
    )
    plugin_title = blocks.CharBlock(
        max_length=150,
        required=False,
        help_text=_('optional'),
        group='wrapper'
    )

    def clean(self, value):
        print(value)

        return super().clean(value)

    class Meta:
        form_template = 'blocks/block_plugin_wrapper.html'
```

In the clean method the following is printed, even though plugin_background should be True:

```
StructValue([('plugin_background', False), ('plugin_title', 'test')])
```

Streamfield:

```
content = StreamField(
        [
            ('test', BlockPluginWrapper())
        ],
        null=True,
        blank=True
    )
```

### Technical details

* Python version: 3.7.9
* Django version: 3.1.8
* Wagtail version: 2.13rc1

**Comment by gasman** [comment]
Thanks for the report @Warqus! I think I see what's going on here - we didn't specify any special case handling for checkbox inputs in the front-end code, so they're falling into the general handling of `<input>` elements, which includes populating the initial state of the field by setting the `value` property. For checkboxes, this is incorrect - it should be setting `checked`. As it stands, we're setting the value of an initially-unset checkbox to none, which means that even when it's checked it will never be recognised as a 'true' value. Should hopefully be a quick fix...

**Comment by Warqus** [comment]
@gasman Thanks for the quick reply! I already suspected something like that. Hopefully it is indeed a quick fix!
