### ISSUE TITLE
Overriding edit_handler breaks CommentPanel if show_comment_panel kwarg is not there

### ISSUE THREAD

**Issue by fabienheureux** [wagtail/wagtail#7090]
### Issue Summary

The new comment panel icon coming from `CommentPanel` does not display if I have the following in the python class (which inherits from Page):
```python
edit_handler = TabbedInterface([
  ObjectList(content_panels, heading="Content"),
  ObjectList(Page.settings_panels, heading="Settings")
])
```

### Steps to Reproduce

1. Update wagtail to v2.13rc1
2. Load Wagtail admin for a page type with overriden `edit_handler`

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes
* I have read the upgrade considerations here: https://docs.wagtail.io/en/latest/releases/2.13.html#commentpanel 

### Technical details

* Python version: Python 3.8.9
* Django version: Version: 3.1.8
* Wagtail version: Version: 2.13rc1
* Browser version: Firefox 88

**Comment by fabienheureux** [comment]
Could it be related to this change: https://github.com/wagtail/wagtail/compare/v2.12.4...v2.13rc1#diff-d9a60e3559da7bbba51922466e3e16c9e369bd0964d94379f8ffab94fe62c0c7R937 ?

**Comment by fabienheureux** [comment]
Ah, found the issue. The kwargd `show_comments_toggle=True` is needed to get the comment toggle to show up 
```
edit_handler = TabbedInterface([
  ObjectList(content_panels, heading="Content"),
  ObjectList(Page.settings_panels, heading="Settings")
], show_comment_toggle=True)
```
  
Is it a documentation issue ? Or should the TabbedInterface set this kwarg by default to True ?

**Comment by jacobtoppm** [comment]
Thanks for flagging this up! I'm hoping the attached PR will resolve it by setting that based on the fields.
