### ISSUE TITLE
Enforce the use of a single string formatting mechanism for translation source strings

### ISSUE THREAD

**Issue by loicteixeira** [wagtail/wagtail#7111]
### Is your proposal related to a problem?

Python has numerous ways of formatting strings which are all surfaced differently within Transifex.

Across the codebase, translation strings use different formatting: `{}`, `{0}`, `{named}`, `%s` and `%(named)s`. This can not only be confusing for new translation but all those tags aren’t treated equally in Transifex.

In addition to the different formatting styles, there is a case to be made for positional placeholders (i.e. {}, {0} and %s) which are problematic as it does not allow the target language to reorder them.

### Describe the solution you'd like

Enforce named and old style formatting:

```python
# In Python
_("Welcome to the %(site_name)s Wagtail CMS") % {"site_name": request.site.site_name}
```

```
<!-- In Templates -->
{% blocktrans %}Welcome to the {{ site_name }} Wagtail CMS{% endblocktrans %}
```

### Additional context

Formatting Option | Screenshot | Notes
-- | -- | --
{}, {0} and {named} |![Brackets_Positional_Empty](https://user-images.githubusercontent.com/6834938/116188305-801ed700-a727-11eb-98ea-a523dc32ed98.png)  ![Brackets_Positional_Numbers](https://user-images.githubusercontent.com/6834938/116188357-92991080-a727-11eb-8272-078f7655be3f.png) ![Brackets_Named](https://user-images.githubusercontent.com/6834938/116188377-97f65b00-a727-11eb-94ab-76bb471f0e9c.png) ![Brackets_Missing](https://user-images.githubusercontent.com/6834938/116188403-a17fc300-a727-11eb-87a4-c24e468d7f74.png)| There is no special treatment about them.When the name of a placeholder matches a glossary term, it displays an unrelevant warning.
%s and %(named)s |![PercentS_Positional](https://user-images.githubusercontent.com/6834938/116188451-b5c3c000-a727-11eb-893c-a02d97f7512f.png) ![PercentS_Named](https://user-images.githubusercontent.com/6834938/116188470-bf4d2800-a727-11eb-8878-ace745cfcd1b.png) ![PercentS_Question](https://user-images.githubusercontent.com/6834938/116188479-c4aa7280-a727-11eb-9175-37c60bf232b9.png)| The placeholders are clickable, it is clear they are not meant to be translated.Note that there were questions around the use of %s, but it was raised before placeholders were made clickable, so it probably isn’t an issue any more.
Missing {}, {0} or {named} | ![Brackets_Missing](https://user-images.githubusercontent.com/6834938/116188549-e4da3180-a727-11eb-9f68-f4db084ddae6.png) | Missing placeholders produce a warning which needs to be interpreted.
Missing%s and %(named)s | ![PercentS_Missing](https://user-images.githubusercontent.com/6834938/116188580-f0c5f380-a727-11eb-89b9-9b9a33a843ad.png) | Missing placeholders produce an error.
f-strings | N/A | They cannot be used as the placeholders would already be replaced by their final value before the translation kicks-in.

### Next Steps

The proposed solution was discussed and agreed in Core Team meetings, however no changes will be made to the codebase until we have a way to enforce the style.

Therefore, the next step is to work on some sort of linter (run as either an actual linter or a test in the test suite) to enforce a single string formatting mechanism across Python and HTML files.

Only then we can open a PR to fix the existing source strings.

### WARNING

Changing placeholder would make old translation strings invalid. Therefore, we should wait for the beginning of a release cycle (maybe a week or two after a new release) and notify translators immediately in order to give them as much time as possible to go through the now broken/missing translations.

**Comment by thibaudcolas** [comment]
Similarly to https://github.com/wagtail/wagtail/issues/7113#issuecomment-828296857 I think a templates linting rule for this wouldn’t be too hard to put together. However in the case of templates isn’t there already a single named, non-positional style? How would you do interpolation in blocktrans otherwise?

**Comment by loicteixeira** [comment]
Indeed, I believe the named and non-positional style is the only one available for `blocktrans` (renamed to `blocktranslate` in Django 3.1 btw), but I wasn't sure on how it would be converted over to the PO files.

It appears that `{% blocktrans %}Welcome to the {{ site_name }} Wagtail CMS{% endblocktrans %}` will convert to `Welcome to the %(site_name)s Wagtail CMS` so we should be fine, and indeed can ignore linting templates.

It is important however that we make sure that the style generated from the template and the style we choose in Python are the same, so we don't end up with 2 different styles in the PO file (which is why I included it in the example, but I can see how this can be confusing).

**Comment by loicteixeira** [comment]
I'm slowly working on this 👍

**Comment by lb-** [comment]
Implemented via https://github.com/wagtail/wagtail/pull/9377 & https://github.com/wagtail/wagtail/commit/5c1c2c8f531d96f4568f6dfa6ce71bc32dd9d16c
