### ISSUE TITLE
Invite users to collaborate

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#7133]
Currently the workflow for adding new users to a Wagtail site exposes the site to security issues due to human error and adds effort for admin. An admin has to create a new user by defining, user name, password, name etc, they then have to communicate the password to the user or ask them to reset their password using the email address the admin defined. 

We should consider an invite bases approach where admin can invite users to collaborate, triggering an email to the new user and asking them to define a password for themselves.

**Comment by gasman** [comment]
Hi @tmsndrs - this is covered by the existing issue #1577.
