### ISSUE TITLE
No warning is displayed when a FieldPanel is used with a StreamField

### ISSUE THREAD

**Issue by LauraLmsr** [wagtail/wagtail#7139]
### Is your proposal related to a problem?

As a Wagtail newbie I spent some time debugging this issue : I noticed it was possible to provide a FieldPanel for a StreamField instead of a StreamFieldPanel in models.py's class panels. The field is visible but unusable in Wagtail admin. No message alerts that a mistake was made. 

### Describe the solution you'd like

To improve developper experience I would suggest a warning message saying something like : "You are using a FieldPanel to display a StreamField, are you sure you are using the right panel?"

**Comment by kaedroho** [comment]
Thanks for this! We could probably use a system check to detect this (in [this function](https://github.com/wagtail/wagtail/blob/cee245e7015b8462f2aa921e42803cd7d0962b8b/wagtail/core/models.py#L1121))

**Comment by gasman** [comment]
Fixed in #7276.
