### ISSUE TITLE
UI for the delete button is confusing

### ISSUE THREAD

**Issue by Ermite-bossu** [wagtail/wagtail#7143]
### Is your proposal related to a problem?

When hovering the delete button, the color change from red to green, and it's pretty confusing

### Describe the solution you'd like

As you can see on my exemple, the best practice is that the delete button is filled with red instead of green

_P.S. I'm a graphic designer and a noob with Github, please don't flog me_ 

![Good_Bad_button](https://user-images.githubusercontent.com/83450946/116711950-a4064500-a9d3-11eb-93bc-68596b2e9584.gif)

**Comment by tbrlpld** [comment]
This appears to be closed by #7302
