### ISSUE TITLE
Improving streamfield UI

### ISSUE THREAD

**Issue by Ermite-bossu** [wagtail/wagtail#7147]
![9a79a3642698c8c7681848100c0c3e9e](https://user-images.githubusercontent.com/83450946/116906606-c650ca80-ac40-11eb-8afe-42733dd69355.gif)

It would improve the visibility and the UX of the streamfield block by adding a button with a text.

**Comment by gasman** [comment]
Thanks for the suggestion @Ermite-bossu!

I'll let our design and accessibility folks make the call on this, but using the button styling for this seems a bit 'heavyweight'. To me, clicking a button implies that we're immediately performing some sort of (possibly destructive) action, like saving or deleting an object. Here we're only expanding or collapsing a menu, so making it look like a final action is misleading.

**Comment by thibaudcolas** [comment]
We’ve re-implemented StreamField styling for the upcoming Wagtail 4 release, so I’ll close this now. For the "Add" button in particular, it would be problematic if it was as prominent as suggested here. Like the "Duplicate" and "Remove" buttons, we have to display one "Add" per block, even though users might never want to interact with it in a given location. So it’s important it doesn’t call for attention too much.
