### ISSUE TITLE
Respect already selected collection when adding new documents or images

### ISSUE THREAD

**Issue by bmihelac** [wagtail/wagtail#7160]
### Is your proposal related to a problem?

Documents and Images list views allows filtering by Collection. Choosing a collection and clicking on "Add a document" opens a new view, where first (Root) collection is selected. This causes confusion to some users and makes them make mistakes where the document would be uploaded.

### Describe the solution you'd like

It would be great if a button to add new documents would transfer currently selected collection id as parameter to multiple add view.  This way current user would upload files to already choosen collection, which looks like right thing to do, especially if there are more then few collections.

![wagtail-current-collection-in-add-view](https://user-images.githubusercontent.com/13813/117170977-c2e94a80-adca-11eb-8216-1d083e1682c4.png)

### Describe alternatives you've considered

Did not found any other alternative for this.

### Additional context

This should be pretty easy to implement, in few steps:

1. [AddView](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/generic/multiple_upload.py#L160) would accept optional query parameter `collection_id` and pass it to template, which would select current collection.
2. [document index template](https://github.com/wagtail/wagtail/blob/main/wagtail/documents/templates/wagtaildocs/documents/index.html) already has `current_collection`, so the only change required here would be to pass it to `wagtaildocs:add_multiple` url
3. change in second step would be made in [image index template](https://github.com/wagtail/wagtail/blob/main/wagtail/images/templates/wagtailimages/images/index.html)

If there are no objections for this, I can prepare pull request.

**Comment by ababic** [comment]
A nice additional touch here would be to have `AddView` and `EditView` both pick up the `collection_id` from the URL and redirect back to a collection-filtered listing for that collection once the item is saved.

**Comment by bmihelac** [comment]
I'm working on it

**Comment by bmihelac** [comment]
> A nice additional touch here would be to have AddView and EditView both pick up the collection_id from the URL and redirect back to a collection-filtered listing once the item is saved

@ababic `AddView` for multiple adding does not redirect, as far as I know. `EditView` does redirect, if this PR is ok, I can extend it to pass `querystring` to `EditView` and redirect after.

**Comment by ababic** [comment]
@bmihelac sure thing! That was by no means a requirement for the work... Just a nice to have. For the edit view, I guess returning to the Collection the item is from (even if it was changed) makes sense, so tacking `f"? collection=obj.collection_id"` onto the end here would probably  be fine: https://github.com/wagtail/wagtail/blob/main/wagtail/documents/views/documents.py#L182

**Comment by lb-** [comment]
Might be fixed from https://github.com/wagtail/wagtail/pull/7810

**Comment by lb-** [comment]
Update

* https://github.com/wagtail/wagtail/pull/7810 made a lot improvements to how the collection ID can be passed around to the various add/edit pages
* It does not fix this issue though
* PR https://github.com/wagtail/wagtail/pull/7756 is looking close but now needs to be rebased on main and refactored to account for the new approach that #7810 brought in

@bmihelac  - Are you still keen on pursuing this fix you started but with the new approach? https://github.com/wagtail/wagtail/pull/7756

**Comment by salty-ivy** [comment]
> Update
> 
> * [Redirect to collection listing after editing/deleting an item from it #7810](https://github.com/wagtail/wagtail/pull/7810) made a lot improvements to how the collection ID can be passed around to the various add/edit pages
> * It does not fix this issue though
> * PR [Respect selected collection when adding documents or images (#7160) #7756](https://github.com/wagtail/wagtail/pull/7756) is looking close but now needs to be rebased on main and refactored to account for the new approach that [Redirect to collection listing after editing/deleting an item from it #7810](https://github.com/wagtail/wagtail/pull/7810) brought in
> 
> @bmihelac - Are you still keen on pursuing this fix you started but with the new approach? #7756

@lb-  can i pursue this one with a new PR?

**Comment by bmihelac** [comment]
@lb-  sorry for late reply. 

Mi@salty-ivy if you have done spare time it would be great to look into that, I would not be able to dedicate time at least on next few weeks

**Comment by ArijeetBanerjee** [comment]
I want to work on this issue. kindly give me permission and access to work on this issue
