### ISSUE TITLE
BaseLogEntry.comment property removed but still referenced in docs

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#7163]
As noted on https://github.com/wagtail/wagtail/commit/122f509b1d6d7ec5afa3da5ba1bc4165c2e2d105#r50371417, moving the comment formatting logic from BaseLogEntry to LogActionRegistry has broken a documented API:

> The `comment` property here is part of the documented API for BaseLogEntry at https://github.com/wagtail/wagtail/blob/main/docs/reference/pages/model_reference.rst#baselogentry, so this probably needs to be preserved (or formally deprecated) - as it stands, this is throwing a warning when building the docs.

**Comment by jacobtoppm** [comment]
Good catch, thanks! I agree we should replace/formally deprecate this, but I believe this code should only be in `main` and not `stable/2.13.x` as we're targetting 2.14 for any audit logging changes - so I think this shouldn't block the 2.13 release, unless I'm missing something.

**Comment by gasman** [comment]
Ah yep - was panicking too much there :-) Thanks!
