### ISSUE TITLE
Add option to disable moderation notifications without disabling moderation entirely

### ISSUE THREAD

**Issue by wimkeir** [wagtail/wagtail#7187]
### Is your proposal related to a problem?

In our CMS, certain pages are related to a Region model, and moderators are assigned to one or more Regions at a time (this can change dynamically). When a page is submitted for moderation, we'd like to send out a notification email *only* to the moderators assigned to that page's Region at the time. Wagtail's built-in notification system sends emails out to all moderators with publish access to the page in question, which includes users not assigned to that page's Region.

### Describe the solution you'd like

We've built our own notification system that listens on the `workflow_submitted` signal to handle sending of notifications to the relevant moderators, but we'd like to disable the built-in Wagtail notifications to prevent duplicate emails while still keeping moderation enabled.

Ideally this would be a setting like `WAGTAIL_SEND_MODERATION_NOTIFICATIONS` or something to that effect.

### Describe alternatives you've considered

Using the built-in notification was considered but given the context described above was deemed unsuitable for our approach. Changing the design of the CMS to ensure that only moderators in Region X have publish permission on pages in Region X would require an overhaul of the entire CMS which is quite large and already running in a production environment, and in any case does not fit our use case as this introduces new and unnecessary restrictions to the moderators.

If there are any alternative approaches that might work for our use case without this feature then I would be glad to consider them. However I feel that even so this would be a useful feature for Wagtail to incorporate.

**Comment by gasman** [comment]
I'm pretty sure it should be possible to do this within the existing [custom workflow support](https://docs.wagtail.io/en/stable/editor_manual/administrator_tasks/managing_workflows.html), but happy to reopen if it turns out there are requirements that aren't covered there.
