### ISSUE TITLE
Too many Collections with `depth=1` shows no Collections and cant run migrations for 2.12. 

### ISSUE THREAD

**Issue by KalobTaulien** [wagtail/wagtail#7195]
### Issue Summary

When there is one or more Collection with `Collection.objects.filter(depth=1)` no collections show up in the Settings/Collections area of the admin. When I delete every other collection with a depth of 1 (except the root collection) the problem solves itself. 

The `0011_add_choose_permissions.py` migration also fails because it uses:

```python
Collection.objects.get(depth=1)
```
But we have managed to create more than one _somehow_ and there doesn't seem to be a solution to fix the problem. 

I've tried running these commands and no luck. 
```python
collection.fix_tree()  # In the shell
root_collection.find_problems() # In the shell
python manage.py fixtree  # On the command line 
```

### Technical details

* Python version: 3.7.8.
* Django version: 3.0.14
* Wagtail version: 2.12.4
* Browser version: Irrelevant

### The bug itself
... seems to be with the admin view, if there is more than one Collection with `depth=1`, none show up. 

I'm not sure if the fix_tree() and find_problems() commands are working correctly, and I suspect that's a treebeard thing, not a Wagtail thing.

**Comment by hazho** [comment]
can't you use the django_shell to list the duplicated depths? and then change them as you need ..!

**Comment by gasman** [comment]
Hi @KalobTaulien,
It really shouldn't be possible to create additional root collections - I'd suspect something like wagtail-transfer as the culprit. If you can track it down to something within Wagtail itself, then obviously that's a bug that we should fix. It would be possible to prevent it from failing outright by e.g. changing `Collection.get(depth=1)` to `Collection.get_first_root_node()`, but this would only really be sweeping the problem under the carpet, and you'd run into others further down the line - for example, there'd be no way to navigate between the trees, so if the 'other' root contains images/documents, they'd end up being unreachable.

Treebeard _does_ allow for multiple root nodes, so its own methods for detecting / fixing inconsistencies don't regard this as a problem.
