### ISSUE TITLE
Wagtail 2.13 Can't add user in admin panel

### ISSUE THREAD

**Issue by ArthurConan** [wagtail/wagtail#7200]
### Issue Summary
After upgrade Wagtail to version 2.13 I can't create User.
I click on _Add user_ button, redirect to url _http://127.0.0.1:8000/admin/users/add/_ and try to create user - I can't do it, the system doesn't react to any my actions

### Steps to Reproduce

1. Go to Settings/Users
2. Click button Add user
3. Fill all fields 
4. Try to click Roles button - nothing happen
5. Try to switch to Roles tab (near Account tab) - nothing happen
(even if I don't fill fields and try to click on button - it doesn't even get me error to fill all fields) 

So I just can't create user. 

![Screenshot from 2021-05-20 13-21-34](https://user-images.githubusercontent.com/25877951/118962966-9eff3a80-b96e-11eb-8a87-e62e7dd0775a.png)

**Comment by gasman** [comment]
Hi @ArthurConan - have you replicated this on a fresh Wagtail installation?

**Comment by ArthurConan** [comment]
No. I have existed project and I updated it.

**Comment by gasman** [comment]
OK - unfortunately we can't handle this as a bug report, as there's no way for us to diagnose which customisations or third-party extensions might have caused the problem. You may be able to get some assistance from [our support channels](https://docs.wagtail.io/en/stable/support.html), though.

**Comment by ArthurConan** [comment]
Sorry, but it's problem with your JS
with accounts and roles
no customization and third-party 
![fLxC9oz](https://user-images.githubusercontent.com/25877951/118972246-0326fc00-b979-11eb-838b-771f9edc8e97.jpeg)

**Comment by gasman** [comment]
Your screenshots are showing a non-standard colour scheme, so there's clearly _some_ customisation - I have no way to know how deep that customisation goes.

If this is indeed a problem in Wagtail itself, then you'll be able to show it happening on a fresh Wagtail project, and that will give us the information we need to investigate further.
