### ISSUE TITLE
IntegrityError when trying to submit already existent unique together with inline form in wagtail admin

### ISSUE THREAD

**Issue by Warqus** [wagtail/wagtail#7201]
### Issue Summary

This is my model:

```
class EntityType(Orderable):
    identifier = IdentifierField(unique=False)
    site = models.ForeignKey(
        to=Site,                                    # Wagtail Site object
        related_name='+',
        on_delete=models.PROTECT,
        null=False,
        blank=False,
        verbose_name=_('site')
    )

    name = models.CharField('name', max_length=100, null=False, blank=False)
    icon = SVGField(upload_to='entity_type_icons')
    color = models.CharField(
        'color',
        validators=[validator_color_hex],
        max_length=7,
        null=False,
        blank=True,
        default=""
    )

    entity_type_category = ParentalKey(
        to=entity_type_category.EntityTypeCategory,
        db_column='entity_type_category_id',
        related_name='entity_type',
        on_delete=models.CASCADE,
        null=False,
        blank=False,
    )

    class Meta:
        unique_together = ['site', 'identifier']

    def __str__(self):
        return self.identifier
```

I have EntityTypeCategory as ModelAdmin with an edit handler that contains EntityType as inline panel. 

Imagine the following situation: I have two type categories; EnitityTypeCategory_1 and EnitityTypeCategory_2.
If EnitityTypeCategory_1 contains EntityType with identifier 'type_1' and I try to add 'type_1' as identifier to EnitityTypeCategory_2 as well (see below)

![image](https://user-images.githubusercontent.com/14151318/119012682-87d44300-b996-11eb-9250-275290a1506b.png)

I get an IntegrityError:

```
duplicate key value violates unique constraint "app_entity_entitytype_site_id_identifier_b306f93b_uniq"
DETAIL:  Key (site_id, identifier)=(6, type_1) already exists.
```

### Technical details

* Python version: 3.7.9.
* Django version: 3.2.3.
* Wagtail version: 2.13.

**Comment by ababic** [comment]
@Warqus. I'm not sure I'm following what you are trying to do here. How is `site` being set on `EntityType` if you do not display a field for it? If the unique restriction is set on the `site` and `identifier` combination, but `site` is always `None` - that's equivalent to just putting a unique restraint on `identifier`.

**Comment by Warqus** [comment]
@ababic Thanks for the reply. EntityTypeCategory has a field Site which is choosable. Before saving EntityType, the site on EntityType is set to the same site as EntityTypeCategory.

```
    def save(self, **kwargs):
        if self.site_id is None:
            self.site_id = self.entity_type_category.site_id

        super().save(**kwargs)
```

Wagtail does not support multi tenancy yet. That's why I add site to each model. Each user has permission to certain sites and it makes sure they can or cannot see certain types. EntityType and EntityTypeCategory should have the same site. That's why I don't want the user to choose a site for EntityType.

I tried adding 'site' as FieldPanel. If I do, I do not get the error described above and I get indeed a clean error message within wagtail admin (which is good). But having 'site' as field is undesirable due to the issue described in the above paragraph.

**Comment by ababic** [comment]
@Warqus okay, that all makes sense. It appears that the problem lies in your custom code somewhere. Validation will take place before saving happens - so perhaps you need to look at overriding `clean()` or `full_clean()` to set the `site` value instead. I would also consider ditching the `site` field completely... if the `EntityTypeCategory` itself has that relationship, and all `EntityType` are associated with an `EntityTypeCategory` - that association already exists.

**Comment by gasman** [comment]
I think this is a general Django coding issue rather than a Wagtail-specific one - form-level validation (which is what Wagtail's admin forms catch and handle cleanly) can't catch errors that only arise during the `save()` step.
