### ISSUE TITLE
UI Issue - Empty checkbox is shown while customising tabbed interface

### ISSUE THREAD

**Issue by kpsaurus** [wagtail/wagtail#7203]
### Issue Summary

I've recently upgraded to 2.13. When customising the tabbed interface, if I commented out the settings panel from the edit handler, an empty checkbox (comment_notifications) will appear on the bottom left of the page.

### Steps to Reproduce

1. In any Page, customise the edit_handler and leave out settings_panels from the list:
```
edit_handler = TabbedInterface([
        ObjectList(content_panels, heading='Content'),
        ObjectList(promote_panels, heading='Promote'),
        # ObjectList(Page.settings_panels, heading='Settings')
    ])
```
Screenshots are given below:

![ss1](https://user-images.githubusercontent.com/59389473/119128970-f62b0b00-ba53-11eb-9cdb-52e8e5b96d4d.jpg)
![ss2](https://user-images.githubusercontent.com/59389473/119128995-fcb98280-ba53-11eb-8279-cfafb968df63.jpg)

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes

### Technical details

* Python version: 3.9.1
* Django version: 3.2.3
* Wagtail version: 2.13
* Browser version: Safari 14

**Comment by TabishB** [comment]
I've noticed this being introduced with wagtail 2.13 as well. Inspecting the element showed that the checkbox seems to be for the new `comments-notification` feature. I have `WAGTAILADMIN_COMMENTS_ENABLED=False` in my settings, but the random checkbox still persists on every subclass of `Page`.
