### ISSUE TITLE
How to  prevent  asking parent page during create a page

### ISSUE THREAD

**Issue by MySecondLanguage** [wagtail/wagtail#7211]
I dont like this step, I want to add page and there should not be any parent or child. it will stand alone a page only.

Like when i click on creating a page from wagtail hooks or wagtail snippet it should direct redirect me to content creation panels instead of asking parent or like this screenshot.

I dont want my page should have any parent or child. and even i hate this step of asking parent page.

I have added this variable there but yet it showing this steps.

```
class ListingPage(Page):
   
    parent_page_type = []
    subpage_types = [
    ]
```

![image](https://user-images.githubusercontent.com/45510606/119451623-50c7ae00-bd57-11eb-9bfc-ca90b515a234.png)

**Comment by gasman** [comment]
Have answered at https://stackoverflow.com/a/67684670/1853523.
