### ISSUE TITLE
User primary key UUID and wagtail 2.13 comments

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#7235]
I integrated wagtail in a project where the user has a UUID as primary key. This was working fine in 2.12 but in 2.13 we got the new comment system. This give a bug with a UUID key.

'''TypeError: keys must be str, int, float, bool or None, not UUID'''

If you turn of the comment system: 
WAGTAILADMIN_COMMENTS_ENABLED = False

Then the problem go's away

### Technical details
* Wagtail version:2.13

**Comment by gasman** [comment]
Hi @onno-timmerman - this has been fixed in Wagtail 2.13.1. #7216

**Comment by onno-timmerman** [comment]
yeah I just see it in the release notes :)
