### ISSUE TITLE
Improve visibility of error messages

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/wagtail#7241]
### Is your proposal related to a problem?

When ever I have validation errors when trying to save a page (or other model) in the Wagtail admin, I find it hard to identify the field with the error. 

I believe this is particularly hard for me as I have a form of "deuteranomalia" which causes "red" for me to be less saturated than for other people. As a result, the small red error text appears basically grey to me and is hard to distinguish from the rest of the page content. 

On simple field like text inputs this is less annoying since the entire field changes its styling. But, especially on chooser fields there is no indication apart from the small text. 

### Describe the solution you'd like

I could imagine the style to be updated in the following order of usefulness (most to least):

- Add a icon at the beginning of the error text (something like this maybe ❌)
- Use a bold font. 
- Increase the font size. 
- Use a brighter red.

I understand that might be ugly from a design perspective, but this is only visible when something is amiss and important information needs to be transported to the user. 

### Describe alternatives you've considered

Not much I can do but slowly scroll the pages. 

### Additional context

Here is an example comparison:

<img width="706" alt="Screenshot 2021-06-07 at 13 22 07" src="https://user-images.githubusercontent.com/24797493/121083166-efaacc00-c793-11eb-9d57-46a69d5d1016.png">

<img width="706" alt="Screenshot 2021-06-07 at 13 23 48" src="https://user-images.githubusercontent.com/24797493/121083179-f33e5300-c793-11eb-8cbe-f818701671a2.png">

Here is the changed `.error-message` class I have used:

```css
.error-message {
    color: #d93030;
    font-weight: bold;
    font-size: small;
}
```

**Comment by thibaudcolas** [comment]
Thank you for the very solid initial report @tbrlpld, and thank you to @Wicked7000 for making the PR. This will be released in v2.16, due in a few weeks.
