### ISSUE TITLE
500 error while filtering search results in admin

### ISSUE THREAD

**Issue by cspollar** [wagtail/wagtail#7244]
### Issue Summary

Malformed query strings cause the app to crash while filtering search results in the admin.

Manually adding a period to the content_type in the URL's query string will cause the admin site to 500.

This is a minor issue, the only downside is occasional noisy logs and confused users that are trying to be clever while searching.

I've created a pull request to address this issue. https://github.com/wagtail/wagtail/pull/6755

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Log in to admin
3. Visit URL http://127.0.01:8000/admin/pages/search/?content_type=demosite.standardpage.broken

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Malformed URLS should 404, or return no search results.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Python 3.8.3
* Django version: Version: 3.2.3
* Wagtail version: Version: 2.13
* Browser version: N/A

**Comment by gasman** [comment]
Fixed in #6755
