### ISSUE TITLE
Firefox problem with collections select field in Admin

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#7246]
### Issue Summary
I recently switched to Firefox browser (89.0). When I want to use the select field for selecting a collection the behavior is kinda strange. Sometimes opening the select field it works fine. Other times the select field get stuck and you can select an item. An other occasions the selection is erratic.

* Wagtail version: 2.13.0
* Browser version: Firefox 89

**Comment by thibaudcolas** [comment]
We’ve significantly changed the implementation of the `<select>` in #8921, so I’m going to close this now. As far as I could tell, the selects work as expected in all browsers, and there shouldn’t be anything special about the collections one.
