### ISSUE TITLE
Document all wagtail settings

### ISSUE THREAD

**Issue by jsma** [wagtail/wagtail#726]
This ticket proposes to have all wagtail settings documented in a single location much like [Django does](https://docs.djangoproject.com/en/1.7/ref/settings/). Many of these settings are mentioned, if not fully documented, in howto/settings.rst but as you can see below some are not mentioned at all in the docs. 

howto/settings.rst is a general guide on "how to get your settings file configured for Django & wagtail" and includes a full example settings file as well as urls. I propose cleaning this document up and moving the documentation of the settings themselves to a dedicated page like Django has for all user overridable settings and then have the rest of the documentation link to this.

For reference, here is the list of all overridable settings and where they are currently referenced in the docs (if at all):
- WAGTAILFRONTENDCACHE
  - wagtail/docs/contrib_components/frontendcache.rst
- WAGTAILFRONTENDCACHE_LOCATION
- WAGTAILADMIN_NOTIFICATION_FROM_EMAIL
  - wagtail/docs/howto/settings.rst
- WAGTAIL_USAGE_COUNT_ENABLED
  - wagtail/docs/releases/0.5.rst
- WAGTAIL_PASSWORD_MANAGEMENT_ENABLED
- WAGTAIL_SITE_NAME
  - wagtail/docs/howto/settings.rst
- WAGTAILEMBEDS_EMBED_FINDER
  - wagtail/docs/howto/settings.rst
- WAGTAILIMAGES_IMAGE_MODEL
  - wagtail/docs/howto/settings.rst
  - wagtail/docs/releases/0.5.rst
- WAGTAILIMAGES_FEATURE_DETECTION_ENABLED
  - wagtail/docs/core_components/images/feature_detection.rst
  - wagtail/docs/getting_started/installation.rst
- WAGTAILSEARCH_BACKENDS
  - wagtail/docs/core_components/search/backends.rst
  - wagtail/docs/core_components/search/indexing.rst
  - wagtail/docs/getting_started/installation.rst
  - wagtail/docs/howto/settings.rst
  - wagtail/docs/reference/management_commands.rst
  - wagtail/docs/releases/0.7.rst
- WAGTAILSEARCH_RESULTS_TEMPLATE
  - wagtail/docs/core_components/search/searching.rst
  - wagtail/docs/howto/settings.rst
- WAGTAILSEARCH_RESULTS_TEMPLATE_AJAX
  - wagtail/docs/core_components/search/searching.rst
  - wagtail/docs/howto/settings.rst

**Comment by kaedroho** [comment]
Wagtailembeds settings documented in https://github.com/wagtail/wagtail/pull/2127

**Comment by lb-** [comment]
Fixed in https://github.com/wagtail/wagtail/commit/b2e139bbd39ab2eb1923eefa632a615f0bc7abaa
