### ISSUE TITLE
Allow creating of language variants of a page in edit mode

### ISSUE THREAD

**Issue by hpoul** [wagtail/wagtail#7260]
### Is your proposal related to a problem?

Currently when editing a page a language selector is shown if there are existing translations. The only way to create a new language variant is to go to the page list select More -> Translate.

### Describe the solution you'd like

It would be nice if the language switcher shows all configured site languages, and if a page translation does not exist for that language offer to create that copy.

### Additional context

I am using a custom `ModelAdmin` for a `Page` model so editors will not necessarily navigate through the page tree to get to the page, but rather through the flat list of the `ModelAdmin`. In this list there is no `More -> Translate` action available. So there is no (easy) way to create a translation for a page.

**Comment by thibaudcolas** [comment]
This has been implemented in time for the upcoming Wagtail 4 release. Here is what it will look like:

<img width="629" alt="translate-page" src="https://user-images.githubusercontent.com/877585/184858222-f679bd3e-bd6c-442a-af37-9bd66d35a7fe.png">
