### ISSUE TITLE
Orderable missing db_index

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#7280]
[Orderable](https://github.com/wagtail/wagtail/blob/431549c427fa1c0c21a2c4113e4fb77af1dde648/wagtail/core/models/__init__.py#L2343) doesn't specify `db_index=True` on it's `sort_order` field.

Since it sets the default ordering to this field, it probably should.

**Comment by gasman** [comment]
Hi @thenewguy,
I'm not sure that it will make any real difference, given that we'll almost always be filtering those queries on the model's ParentalKey, and each parent instance is only going to have a few hundred children at most. On a site that's large enough for indexing to be significant, it's likely that you'll have thousands of pages with ~10 child objects on each, meaning that the `sort_order` column will contain thousands of repeats of the values 1 to 10; I don't think a DB index on that individual column will be able to do anything useful.

Happy to reconsider if you're up for researching this further and putting some performance figures together, but I suspect that the disruption of rolling this change out (and requiring a migration on all existing tables when users next upgrade) would outweigh the benefits.
