### ISSUE TITLE
spin animation in styleguide may have useless translateY(0.6em)

### ISSUE THREAD

**Issue by adsee42** [wagtail/wagtail#7289]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
![image](https://user-images.githubusercontent.com/54787881/123499430-37bd6000-d669-11eb-8621-22e3ac216ded.png)

I don't get that translate. Is this intended behavior?
And in `core.css`, not `translateY`, just `rotate`.

It's also affecting buttons:
![image](https://user-images.githubusercontent.com/54787881/123499290-435c5700-d668-11eb-9612-24b43ba3e53f.png)

### Steps to Reproduce

1. enable styleguide

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)
yes

### Technical details

* Python version: 3.8.1* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
* Wagtail version: 2.13.2
* Browser version: chrome 90

**Comment by thibaudcolas** [comment]
👋 this has been fixed, not sure when. https://static-wagtail-v5-2.netlify.app/admin/styleguide/
