### ISSUE TITLE
Elements that were styled with custom colours in 2.12.x revert to wagtail teal in 2.13.x

### ISSUE THREAD

**Issue by MrWeeble** [wagtail/wagtail#7294]
### Issue Summary

We have added a custom theme to wagtail by setting a primary colour hue to a colour that matches our brand. We have just updated to 2.13.2, and some elements have become unthemed

### Steps to Reproduce

1. install wagtail 2.12.3 (also tested with 2.12.5)

2. create a css file containing

```css
:root {
    --color-primary-hue: 237;
}
```

3. include it with `@hooks.register("insert_global_admin_css")` as per documentation

4. Observe that e.g. the tab bar on the edit page is Blue matching the hue specified

5. Update to Wagtail 2.13.0 (also tested with 2.13.2)

Expected: the e.g. the tab bar on the edit page should remain as it was in wagtail 2.12
Actual:  certain UI elements (possibly anything set to "primary-color-darker"?) are now teal

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: No

### Technical details

* Python version: 3.7.9
* Django version: 2.2.24
* Wagtail version: 2.13.0,2.13.2
* Browser version: Chrome 91.0.4472.114

**Comment by gasman** [comment]
Thanks for reporting @MrWeeble! Looks like this was introduced in this commit: bbbc31ff600a032aa0b7a247e1d951b77a17f89e
