### ISSUE TITLE
Custom user interface colors not applying correctly.

### ISSUE THREAD

**Issue by SunnyR** [wagtail/wagtail#7303]
### Issue Summary

I recently implemented the Custom user interface colors for wagtail to have a blue skin however, in some sections of the admin interface the color's don't seem to be applying correctly. I've used django-debug-toolbar to look into any overiding tremplates or static files being loaded, removed any third-party apps as well, and still see the issue. 

* **Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?**
The wagtail admin seems to be loading core.css to apply colors and the variables aren't being used as set (see screenshot). I would like it to use the colors provided for the breakcrumb bar and buttons on the page.

* **I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)**
Not yet

### Technical details

* Python version: 3.6.9
* Django version: 3.1.2
* Wagtail version: 2.13.2
* Browser version: Chrome 91

### Screenshot
![image](https://user-images.githubusercontent.com/1923481/124000414-c6471f80-d990-11eb-821d-6163daa079bb.png)

**Comment by gasman** [comment]
Hi @SunnyR - thanks for the report. This has been reported earlier in #7294 and a fix is now awaiting review - #7298
