### ISSUE TITLE
wagtail editing multiple pages

### ISSUE THREAD

**Issue by cvhorie** [wagtail/wagtail#7311]
### Is your proposal related to a problem?

I am the content provider/inputter into a Wagtail based website. 
The content is an hierachical database, In general, the pages and children pages are identical in structure and very similar in content.  They are arranged:
R.001 Text a
   R.001 a
   R.001 b
   R.001 c
   R.001 d
   R.001 e
R.002 Text b
   R.002 a
   R.002 b
   R.002 c
   R.002 d
   R.002 e
R.003  ...

I cannot find a tool to copy one group to make another by editing.
### Describe the solution you'd like

How do I copy the group of R.001 and children to a new R001 and children? 
Then do a gobal edit on the new R.001 and children to change to R.002?  
There are a number of text and numerical data elements in the each group which need changing. 
This would be done by a text change, "R.001" > "R.002" etc
I have about 800 of these R.xxx

Is such an editing tool available, and is there a wider need? 

### Describe alternatives you've considered

At the moment, I am copying individual pages - it is getting repetitive and prone to error. 

### Additional context

(Write your answer here.)

**Comment by cvhorie** [comment]
PS the indentation before R.001 a etc has been deleted, so making the hierarchy levels less visible - CVH

**Comment by thibaudcolas** [comment]
Hi @cvhorie, only getting to this now, which I suppose is better than never!

As of Wagtail 2.15, we support bulk actions, and in particular [custom bulk actions](https://docs.wagtail.org/en/stable/extending/custom_bulk_actions.html#custom-bulk-actions). I believe this is the missing capability you would be after. This would allow you to create a custom bulk pages copy, as part of which you could have a form to systematically change some of the page’s fields.

Here are relevant packages which could also help with your needs:

- https://github.com/wagtail/wagtail-transfer
- https://github.com/torchbox/wagtail-content-import

I’ll close this now. Please use our [Slack](https://github.com/wagtail/wagtail/wiki/Slack) or GitHub Discussions if you want to discuss this further with other Wagtail implementers / contributors, or comment here / open a new issue if you think we need extra core capabilities to support this better.

**Comment by cvhorie** [comment]
Thibaud

Thank you.
I shall make sure that our (Manchester University) wagtail is updated.
Then report back.

--
Velson Horie
www.horie.co.uk
