### ISSUE TITLE
Pip install -e step in setting up the Wagtail codebase section is not working on Windows

### ISSUE THREAD

**Issue by kkomninos** [wagtail/wagtail#7312]
Trying to set up the Wagtail codebase from the documentation, stucks in a pip error on Windows.

### Pertinent section of the Wagtail docs 

https://docs.wagtail.io/en/stable/contributing/developing.html#setting-up-the-wagtail-codebase

### Details

The documentation instructs to clone the project from git and then install packages using pip.

The command:
`$ pip install -e '.[testing,docs]' -U`
 leads to the error:
`ERROR: '.[testing,docs]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL`

I had to remove '' : 
`$ pip install -e .[testing,docs] -U`
and it worked.

Maybe this should be stated.

**Comment by gasman** [comment]
Thanks for the report @kkomninos! Looking at previous PRs (#3461, #6768), the quotes were added to ensure compatibility with zsh. Looks like we need to give both versions, then - I'll open a PR for this.
