### ISSUE TITLE
Broken links in getting_started tutorial

### ISSUE THREAD

**Issue by kkomninos** [wagtail/wagtail#7317]
### Several sections in getting_started/tutorial.md

https://github.com/wagtail/wagtail/blob/main/docs/getting_started/tutorial.md#where-next

### Details

There are 8 internal links that point to github documentation pages and are all **broken**. It seems that the extensions are missing from the links.

E.g. all the links at the bottom of the page in section Where Next are broken. 

I have checked them and I made a pull request in case it is handy.

**Comment by zerolab** [comment]
Closing due to reasons outlined in #7316
