### ISSUE TITLE
High-contrast mode: Dashboard icons are hard to see and should use link text color

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7325]
This is a bug specific to [Windows high-contrast mode](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/). cc @kbayliss who did the testing for this. Details from his report:

---

Icons have a low opacity which makes them difficult to see on dark backgrounds.

Current: `opacity: .2; color: #fff`
Proposed: `opacity: 1; color: LinkText`

Current:

![Current](https://user-images.githubusercontent.com/877585/125081169-9baa4480-e0bd-11eb-9679-798a424fa1e7.png)

Proposed: 

![Proposed](https://user-images.githubusercontent.com/877585/125081185-a1078f00-e0bd-11eb-8948-71e0a20cc6a8.png)

**Comment by thibaudcolas** [comment]
Marking as a good first issue – I think the proposed fix could work well with the [forced-colors](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors) media query, without expert knowledge of Wagtail required. Note testing this does require having access to Windows high-contrast mode.

**Comment by SakshiUppoor** [comment]
I would like to work on this issue.
