### ISSUE TITLE
High-contrast mode: SVG icons within links, buttons, plain text, should match text colour

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7326]
This is a bug specific to [Windows high-contrast mode](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/). cc @kbayliss who did the testing for this.

---

Current: `fill: currentColor`
Proposed: `fill: LinkText`, or `fill: CanvasText`.

Places to fix:

- [ ] Main navigation icons
- [ ] Pagination left/right arrows
- [ ] Breadcrumb globe icon
- [ ] `<a class='button'>` icons
- [ ] Rich text toolbar button icons
- [ ] Plain-text, for example help icons

Current:

![Current](https://user-images.githubusercontent.com/877585/125081649-268b3f00-e0be-11eb-8f98-5dd1bb302072.png)

Proposed:

![Proposed](https://user-images.githubusercontent.com/877585/125081655-27bc6c00-e0be-11eb-837b-bddbb55757fb.png)

**Comment by thibaudcolas** [comment]
Marking as a good first issue – I think the proposed fix could work well with the [forced-colors](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors) media query, or even applied directly whenever the icon and text color match already. Note testing this does require having access to Windows high-contrast mode.

**Comment by thibaudcolas** [comment]
Additionally adding the case of icons in text:

![7326-2](https://user-images.githubusercontent.com/877585/129974341-ef5322b4-1f06-41e9-83f4-7afce4d8e80f.png)

**Comment by lb-** [comment]
Fixed via fb66c1fd1732f462a1983edb5410192a9b8963da / #7460
