### ISSUE TITLE
High-contrast mode: Explorer wagtail icon is hard to see on dark background

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7329]
This is a bug specific to [Windows high-contrast mode](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/). cc @kbayliss who did the testing for this.

---

We could watch out for dark background and swap to a light variant?

![Current](https://user-images.githubusercontent.com/877585/125085202-36a51d80-e0c2-11eb-9002-5a25fb4af3c2.png)

**Comment by lb-** [comment]
Fixed via fb66c1fd1732f462a1983edb5410192a9b8963da / #7460
