### ISSUE TITLE
High-contrast mode: Comments icon should match link colour

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7331]
This is a bug specific to [Windows high-contrast mode](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/). cc @kbayliss who did the testing for this.

---

Current:

![Current](https://user-images.githubusercontent.com/877585/125113646-d40f4a00-e0e0-11eb-9a5a-3d6cc38800eb.png)

Proposed:

![Proposed](https://user-images.githubusercontent.com/877585/125113640-d2458680-e0e0-11eb-8c09-5ebd5484b9fd.png)

**Comment by thibaudcolas** [comment]
Marking as a good first issue – I think the proposed fix could work well with the [forced-colors](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors) media query, or even applied directly whenever the icon and text color match already. Note testing this does require having access to Windows high-contrast mode.

**Comment by lb-** [comment]
Fixed via fb66c1fd1732f462a1983edb5410192a9b8963da / #7460
