### ISSUE TITLE
Collapsible panels in edit UIs are impossible to open or close with keyboards or screen readers

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7332]
Spotted thanks to a high-contrast mode audit by @kbayliss. In the "Edit" UI, the open/close trigger for panels is a `<div>`. This means it doesn’t look clickable in high-contrast mode… and doesn’t support keyboard interactions, whether `tab` or with a screen reader.

This is a major blocker for people who rely on either forms of navigation – if the panels are collapsed by default, then the fields are impossible to reach.

**Comment by lb-** [comment]
@anujaraj / @Scotchester - this may now be fixed on main, if not, I recommend this be looked at with the forced colors work.

**Comment by thibaudcolas** [comment]
This is indeed fixed #8921. The only difference in forced colors mode is the hover styles, using borders rather than a background:

![forced-colors-collapsible](https://user-images.githubusercontent.com/877585/184857781-0782c909-8eda-4982-a65d-9b17a6c00462.gif)
