### ISSUE TITLE
ModelAdmin IndexView not keyboard navigable

### ISSUE THREAD

**Issue by jessemenn** [wagtail/wagtail#7333]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The default ModelAdmin IndexView isn't keyboard navigable. Without using a mouse, there's no way to use the edit or delete (or, presumably, other added buttons of that view) of a particular item. This also affects screen reader users.

### Steps to Reproduce

1. Use ModelAdmin to register a menu item. 
2. Try to tab to an item's edit or delete buttons. 
3. Alternatively, in the bakery demo, navigate to anything under Bread Categories or Bread Misc, and then edit something via keyboard. 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

At first glance, changing these to operate in the same manner as the page and snippets indexview works seems appropriate, where each item is a link that can be targetted, thus triggering the `.focus-within` of the `td` or `tr`.  

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Wagtail version: 2.13.3
* Browser version: Chrome, Safari, FirefoxESR (all Mac OS). I presume IE and Edge, as well.

**Comment by thibaudcolas** [comment]
Thank you @jessemenn, re-reading this I remember testing it as well after you had mentioned it and finding out the same thing.

I believe a potential workaround we had discussed was to follow the same pattern as page listings – have the title of the item be a link to the edit view, so focus can be moved within each row. Then, we can use `:focus-within` on the row to reveal the buttons that are currently revealed on hover only.

Another option would be to have a focusable trigger element for this sole purpose – but it feels like it’d be simpler and more useful to all to make the title a link instead.

**Comment by thibaudcolas** [comment]
Marking this as a good first issue as I believe this would be possible for someone to pick up with minimal Wagtail knowledge – the problem can be replicated directly in our bakerydemo development environment.

It looks like we would need to change this line to wrap `item` in an anchor tag: https://github.com/wagtail/wagtail/blob/952264a2abffd1c01e08611bae26ceaf8d958d43/wagtail/contrib/modeladmin/templates/modeladmin/includes/result_row_value.html#L2

Here is the code which currently generates the URL for the Edit buttons: https://github.com/wagtail/wagtail/blob/952264a2abffd1c01e08611bae26ceaf8d958d43/wagtail/contrib/modeladmin/views.py#L186
