### ISSUE TITLE
Set up auto-assignment bot

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#7335]
PRs often get stuck for a while waiting for someone to review. To help mitigate this, we introduced a list of reviewers who can be directly assigned PRs to review. The idea is once someone is made responsible for reviewing a PR, it's more likely to be done quickly. The reviewer has the option of reviewing the PR or passing it on to someone else on the list.

The next problem is actually assigning PRs to those people to review, for a while we have tried to do this manually but it seems to get forgotten about.

Our proposed solution to this, is to insert these names into an Airtable database and write a bot that automatically assigns PRs to someone on that list.

**Comment by thibaudcolas** [comment]
It seems we haven’t acted upon this despite it feeling like a good idea in 2021, so I’ll close this now. If we still want to have that kind of bot I’d recommend bringing this to core team discussions again.
