### ISSUE TITLE
Change release notification to link to latest major release notes

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#7336]
Wagtail has a notifcation on the dashboard that is shown if the Wagtail installation is out of date:

![image](https://user-images.githubusercontent.com/1093808/125284628-95aca180-e311-11eb-82cf-797a38e2d7d1.png)

This notification always links to the latest patch release. So clicking the link in the above screenshot will take the user to https://docs.wagtail.io/en/stable/releases/2.13.3.html

The problem with this is that this Wagtail site is a major version behind, so the release notes of the point release aren't relevant to this user since we only fix new regressions in point releases.

We should instead be pointing to the [2.13 release notes](https://docs.wagtail.io/en/stable/releases/2.13.html), which is much more relevant and interesting to someone on Wagtail 2.12.

**Comment by kaedroho** [comment]
@gasman please could you add a separate link to the major release notes to releases.wagtail.io/latest.txt ?

**Comment by gasman** [comment]
@kaedroho Sure. I figure we might as well add the data for the latest LTS release at the same time, so that we can potentially add a settings flag for people on LTS releases to ignore notifications for non-LTS upgrades - how about the following structure?

```
{
    "version": "2.13.4",
    "url":     "https://docs.wagtail.io/en/stable/releases/2.13.4.html",
    "majorUrl": "https://docs.wagtail.io/en/stable/releases/2.13.html",
    "lts": {
        "version": "2.11.8",
        "url": "https://docs.wagtail.io/en/stable/releases/2.11.8.html",
        "majorUrl": "https://docs.wagtail.io/en/stable/releases/2.11.html"
    }
}
```

If that looks good, let me know and I'll upload that to mark today's (non-urgent) 2.13.4 release.

**Comment by kaedroho** [comment]
@gasman Looks good to me!

**Comment by gasman** [comment]
OK, done (but it may take 24h for the cache to clear).

**Comment by tbrlpld** [comment]
@gasman I have created #7671 to adjust the `latest.txt` according to your comment. Let me know if that works.

**Comment by tbrlpld** [comment]
@gasman Do you have a preferred name for the LTS upgrade notification flag setting? 

Or should that whole topic be covered in a separate PR?

**Comment by gasman** [comment]
@tbrlpld A separate PR for the LTS handling makes sense, I think.

**Comment by tbrlpld** [comment]
Added the follow-up PR with the LTS: #7752
