### ISSUE TITLE
WARNING: tablib 0.14.0 does not provide the extra 'xlsx'

### ISSUE THREAD

**Issue by heydonovan** [wagtail/wagtail#7363]
### Issue Summary

I'm using the license scanning feature from GitLab, which does all sorts of things behind the scenes, but it errors out on this tablib issue. I've replicated it outside of this with a `requirements.in` file with just `wagtail` in it:

```
$ cat requirements.in
wagtail

$ pip-compile --no-emit-index-url --output-file requirements.txt requirements.in

$ cat requirements.txt
...
tablib[xls,xlsx]==0.14.0
    # via wagtail
urllib3==1.25.6
    # via requests
wagtail==2.12.6
    # via -r requirements.in
```

And if I try to install that manually:

```
❯ pip install tablib[xls,xlsx]==0.14.0
Requirement already satisfied: tablib[xls,xlsx]==0.14.0 in ./.virtualenv/lib/python3.7/site-packages (0.14.0)
WARNING: tablib 0.14.0 does not provide the extra 'xls'
WARNING: tablib 0.14.0 does not provide the extra 'xlsx'
Requirement already satisfied: odfpy in ./.virtualenv/lib/python3.7/site-packages (from tablib[xls,xlsx]==0.14.0) (1.4.1)
Requirement already satisfied: xlwt in ./.virtualenv/lib/python3.7/site-packages (from tablib[xls,xlsx]==0.14.0) (1.3.0)
Requirement already satisfied: pyyaml in ./.virtualenv/lib/python3.7/site-packages (from tablib[xls,xlsx]==0.14.0) (5.3)
Requirement already satisfied: xlrd in ./.virtualenv/lib/python3.7/site-packages (from tablib[xls,xlsx]==0.14.0) (1.2.0)
Requirement already satisfied: openpyxl>=2.4.0 in ./.virtualenv/lib/python3.7/site-packages (from tablib[xls,xlsx]==0.14.0) (3.0.3)
Requirement already satisfied: markuppy in ./.virtualenv/lib/python3.7/site-packages (from tablib[xls,xlsx]==0.14.0) (1.14)
Requirement already satisfied: jdcal in ./.virtualenv/lib/python3.7/site-packages (from openpyxl>=2.4.0->tablib[xls,xlsx]==0.14.0) (1.4.1)
Requirement already satisfied: et-xmlfile in ./.virtualenv/lib/python3.7/site-packages (from openpyxl>=2.4.0->tablib[xls,xlsx]==0.14.0) (1.0.1)
Requirement already satisfied: defusedxml in ./.virtualenv/lib/python3.7/site-packages (from odfpy->tablib[xls,xlsx]==0.14.0) (0.6.0)
```

How do we get wagtail to not include those brackets? Cause it works just fine if I go that route.

### Technical details

```
$ python --version
Python 3.7.4

$ pip show django | grep Version
Version: 2.2.18

$ pip show wagtail | grep Version
Version: 2.12.6
```

**Comment by gasman** [comment]
Hi @heydonovan,
It looks like tablib only started specifying optional dependencies in version 1.0.0, which is why they're not recognised in 0.14.0. It could probably be fixed by changing Wagtail to require `tablib[xls,xlsx]>=1.0.0` instead, but this seems like a bit of an esoteric case...

* Is there a reason why this tool is choosing to install the oldest available version of tablib, rather than the newest?
* Does it actually cause any problems (given that this is a warning rather than an error)?

**Comment by heydonovan** [comment]
The tool just takes whatever is in requirements.txt. I think it's better to ask why wagtail requires such an old version of tablib. That's what I was trying to show in my example, that even outside their tool, that warning is still thrown.

Here is the error from the license scanning tool though:

```
license_management report --no-prepare --format=json --save=gl-license-scanning-report.json --no-recursive --no-debug --quiet
[v3.29.1] Traceback (most recent call last):
  File "/opt/asdf/installs/python/3.7.4/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2741, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'xlsx'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/license_finder-6.13.0/bin/license_finder_pip.py", line 39, in <module>
    in pkg_resources.working_set.resolve(requirements)]
  File "/opt/asdf/installs/python/3.7.4/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 794, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/opt/asdf/installs/python/3.7.4/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2744, in requires
    "%s has no such extra feature %r" % (self, ext)
pip._vendor.pkg_resources.UnknownExtra: tablib 0.14.0 has no such extra feature 'xlsx'
```

**Comment by gasman** [comment]
> I think it's better to ask why wagtail requires such an old version of tablib

It doesn't - the dependency is `tablib[xls,xlsx]>=0.14.0`, so while it _can_ work with a version of tablib as old as that, any real-world installation of wagtail will use the newest available version. That's why I'm puzzled why it's choosing to install the oldest possible version allowed by the dependency. (But then I don't know what this tool is supposed to be doing - maybe it does make sense in context.)

**Comment by heydonovan** [comment]
Oh interesting! Thought wagtail was enforcing that version for some reason. Looks like I’ve more digging to do.

I’ll get back to you once I’ve more information. Thanks!

**Comment by heydonovan** [comment]
You can close this, figured it out. From the pip-tools README:

```
Note: If pip-compile finds an existing requirements.txt file that fulfils the dependencies then no changes will be made, even if updates are available. To compile from scratch, first delete the existing requirements.txt file, or see Updating requirements for alternative approaches.
```

Once I deleted the `requirements.txt`, and re-ran it, it had the latest version of tablib:

```
$ cat requirements.txt | grep -C3 '^tablib'
    # via beautifulsoup4
sqlparse==0.4.1
    # via django
tablib[xls,xlsx]==3.0.0
    # via wagtail
tenacity==8.0.1
    # via ddtrace
```
