### ISSUE TITLE
Make more panels collapsible

### ISSUE THREAD

**Issue by fabienheureux** [wagtail/wagtail#7364]
### Is your proposal related to a problem?

Currently, it seems that only `MultiFieldPanel` are collapsible. 
https://docs.wagtail.io/en/stable/reference/pages/panels.html#multifieldpanel

However, more panel types can support being collapsible, for example using `StreamFieldPanel("body", classname="collapsible multi-field")` to match [this selector ](https://github.com/wagtail/wagtail/blob/35132296cc45ea22a5f7db35df75685f2c3465be/client/src/entrypoints/admin/page-editor.js#L245)makes the panel collapsible. 

### Describe the solution you'd like

Updating the selector to match `.object.collapsible` should do the trick

### Describe alternatives you've considered

Update the documentation to suggest using the `multi-field` classname in the panel definition. However...this is more a hack than a proper way to achieve this.

**Comment by gasman** [comment]
Thanks for the suggestion @fabienheureux! Would you be willing to submit a PR with this change?

**Comment by fabienheureux** [comment]
Absolutely, I wanted to first check that it was not working this way on purpose.

**Comment by zerolab** [comment]
#6187 discusses this in more detail and #6342 is the implementation which is very similar to #7365. @fabienheureux  can you check #6342 and bring in the home template changes and see double check the documentation changes?

**Comment by fabienheureux** [comment]
Thanks for this comment @zerolab, sure I will update my PR shortly. 
I searched for open issues about this topic but did not think of searching in PR...
