### ISSUE TITLE
Page editing actions dropdown doesn’t support keyboard or screen reader navigation

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7366]
### Issue Summary

Initially reported by @jessemenn. On the page editing UI, the actions dropdown is very brittle with keyboard and screen reader navigation:

- The dropdown’s toggle button isn’t focusable
- Items within the dropdown are focusable even when hidden.

### Steps to Reproduce

1. Go to the page editing UI on any Wagtail site
2. Reach the "Save draft" button
3. Try to reach any action within the dropdown

---

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

Tested in Chrome macOS & Safari VoiceOver. I’d expect this to be an issue for all browsers, all screen readers, in all Wagtail releases over the last few years at least.

**Comment by thibaudcolas** [comment]
Based on reviewing available resources, it seems there are two documented ARIA patterns we could use for this:

- Progressive disclosure, similar to https://www.w3.org/TR/wai-aria-practices-1.1/examples/disclosure/disclosure-navigation.html
- Or the menubar & menu pattern: https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html

In both cases there are many more keyboard interactions to support than my initial issue description suggests.

**Comment by thibaudcolas** [comment]
As part of refactoring this we should also make sure to consistently use the same element (button or link) for all menu items, so screen reader announcements and high-contrast mode display is more consistent:

![7366](https://user-images.githubusercontent.com/877585/129975685-4b93eb30-903f-409a-8364-fa5c579b3367.png)

**Comment by Desaiakshata** [comment]
I can work on this issue

**Comment by lb-** [comment]
Some improvement has been made to this, thanks to @Desaiakshata  https://github.com/wagtail/wagtail/commit/997ac738b0bd04db0e737a11fa6304586865eab5

**Comment by thibaudcolas** [comment]
@thibaudcolas to re-test

**Comment by PreciousArinda** [comment]
Hello @thibaudcolas  I'm seeing this issue is to be re-tested. 
I believe I can contribute to this issue.
Can I take it on?

**Comment by ArijeetBanerjee** [comment]
I want to work on this issue. kindly give me permission and access to work on this issue
