### ISSUE TITLE
TaggableManager is broken

### ISSUE THREAD

**Issue by OneEyeDoll** [wagtail/wagtail#7371]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I can't add TaggableObject to the panel, because when i do so an error appears.

### Steps to Reproduce

Add to Models.py this new model:
`class BlogPageTag(TaggedItemBase):
    content_object = ParentalKey(
        'BlogPage',
        related_name='tagged_items',
        on_delete=models.CASCADE,
    )
`
Then add to another Model a taggable manager field:

`    tags = TaggableManager(through=BlogPageTag)
`
Then Migrate. An error appears:

`AttributeError: '_TaggableManager' object has no attribute 'rel'`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I expected a succesful migrations, because there are no obvious errors. I figured out that this happens when the method "    new.on_model_bound()" is called with _TaggableManager parameter. I tried to edit the method, using the _TaggableManager properties, but seems like that every of them is not what Wagtail expects.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)
 no

### Technical details

* Python version: Run `python --version`. 
3.9.2
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
 3.2.5
* Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
2.13.4
* Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

**Comment by gasman** [comment]
Are you following the example on https://docs.wagtail.io/en/stable/reference/pages/model_recipes.html#tagging ? That uses `ClusterTaggableManager`, not `TaggableManager`.

**Comment by OneEyeDoll** [comment]
Yeah, i'm sorry. The problem was with InlineField, with PanelField everything seems good. Except that it won't save new tags.
