### ISSUE TITLE
Page aliases have null values in last_published_at and first_published_at

### ISSUE THREAD

**Issue by hpoul** [wagtail/wagtail#7373]
Not sure if this is intended behavior, but when creating page aliases which are published, both `last_published_at` and `first_published_at` are null.

### Steps to Reproduce

1. Create a new page, publish it.
2. Copy the page with "keep in sync" (ie. create an alias)
3. Select 'Publish page'

I would have expected this to have either the current date, or the values from the original Page in `last_published_at` and `first_published_at`, but instead both values are null even though live=True.

### Technical details

* Python version: 3.8.11
* Django version: 3.2
* Wagtail version: 2.14rc1

I would have exptected when setting `live=True` that it would also update publish timestamps?

https://github.com/wagtail/wagtail/blob/1a7563406e32f0532cf396927e043a649c9c89e2/wagtail/core/models/__init__.py#L978-L980

Is this by design, or a bug?

**Comment by zerolab** [comment]
@hpoul I was not able to replicate the issue you describe with >=Wagtail 2.15, see https://youtu.be/52X5RSO1G5k - do you still experience the same issue with 2.15?

I did however find and fixed the issue @richbrennan is describing. PR coming shortly

**Comment by zerolab** [comment]
This should now be fixed in #7788
