### ISSUE TITLE
Reduce the amount of Excel file read/writing libraries

### ISSUE THREAD

**Issue by jaap3** [wagtail/wagtail#7374]
Wagtail has a fairly large number of (in)direct dependencies. By installing Wagtail in an empty virtualenv I ended up with 32 unique Python packages. Of those 32 packages 4 deal with reading/writing Excel files.

1. `XlsxWriter` (referenced directly in Wagtail's `setup.py`)
    _XlsxWriter is a Python module for writing files in the Excel 2007+ XLSX file format_
2. `openpyxl` (referenced directly in Wagtail's `setup.py`, and pulled in by the `tablib[xlsx]` dependency)
    _A Python library to read/write Excel 2010 xlsx/xlsm files_
3. `xlrd` (pulled in by the `tablib[xls]` dependency)
    _xlrd is a library for reading data and formatting information from Excel files in the historical .xls format._
4. `xlwt` (pulled in by the `tablib[xls]` dependency)
    _This is a library for developers to use to generate spreadsheet files compatible with Microsoft Excel versions 95 to 2003._

I personally don't associate Wagtail with Excel, so I was wondering where those dependencies came from.

## XlsxWriter

The only usage I could find in the Wagtail codebase is the (undocumented) `wagtail.admin.views.SpreadsheetExportMixin`. This mixin is used by the Wagtail forms and modeladmin contrib apps.

## openpyxl / xlrd

These two are used by the redirects contrib app to support the import (and export?) of redirects. In addition `openpyxl` is used to test the output generated by `SpreadsheetExportMixin` for the forms and modeladmin contrib apps.

## xlwt

I could not find any usages by Wagtail, the only reason it is installed is because of the `tablib[xls]` dependency.

## Suggestion

1. There is significant overlap between the `XlsxWriter` and `openpyxl` packages. Their APIs are also very similar, the only difference is the minimal supported Excel version (2007 v.s. 2010). Wagtail already uses `openpyxl` to verify the output created by `XlsxWriter`. Would it be acceptable to rewrite the `SpreadsheetExportMixin` to use `openpyxl` instead of `XlsxWriter`, and drop the `XlsxWriter` dependency?

2. Drop support for the import (and export?) of redirects in xls format. This format is severely outdated and doesn't warrant two additional dependencies in Wagtail. If someone has an xls format they can just as easily convert it to csv and import it that way.

## Result

Please consider this proposal, I'm willing to provide PRs to achieve this goal. If accepted the number of Excel file readers/writers would drop from 4 to just one (`openpyxl`).

**Comment by jaap3** [comment]
Additional info:

In commit 41bf6010dff29c3990dbe6e6deed4a641ea0dd56 Wagtail started using `openpyxl` to verify the generated Excel files. The reason to keep using XlsxWriter was performance and a nicer API.

The `tablib` dependency (and the resulting `openpyxl`, `xlwt` and `xlrd`) dependencies were added in commit 301d1bc7f52fffc18b8cb34fbde01633bc1599ee.

**Comment by gasman** [comment]
The `[xls]` option on tablib is probably redundant and should be removed - I don't think Wagtail ever does anything with .xls files.

Beyond that, I don't see the duplication of functionality between XlsxWriter and openpyxl to be an issue. That's just the nature of writing software in a language with a rich package ecosystem... Wagtail should use whichever packages are best for the job - which happens to be XlsxWriter in the case of writing xlsx files - and the fact that tablib happened to choose openpyxl for its own internal use shouldn't have a bearing on that decision.

**Comment by jaap3** [comment]
Wagtail directly uses `openpyxl` (in non test code) here: https://github.com/wagtail/wagtail/blob/99f05d67cb97465127c095fc2664ff161e1b049a/wagtail/contrib/redirects/base_formats.py#L203

and `xlrd` here: https://github.com/wagtail/wagtail/blob/99f05d67cb97465127c095fc2664ff161e1b049a/wagtail/contrib/redirects/base_formats.py#L182

The main reason for my request to reduce the amount of libraries used is twofold:

1. When running automated tests these dependencies need to be installed in the test pipeline, which adds overhead (even though we don't actually use them, Wagtail does require them).
2. When upgrading packages we need to audit changes, even if those packages are not directly used by us (being ISO/IEC 27001 we have to take these things very seriously).

If at least the `xlwt` and `xlrd` dependencies can be omitted it would already be a significant improvement. I'd also be happy to get rid of `openpyxl` in "main" Wagtail code (which would also remove the `et-xmlfile` subdependency). The easiest way to do so is to drop Excel imports for the redirects importer altogether (there's still plenty of options available looking at https://github.com/wagtail/wagtail/blob/99f05d67cb97465127c095fc2664ff161e1b049a/wagtail/contrib/redirects/base_formats.py).
