### ISSUE TITLE
Sorting/filtering throughout the admin

### ISSUE THREAD

**Issue by nmorduch** [wagtail/wagtail#7400]
### Problem

It can be frustrating to try to find things like:
- All active users
- All users with admin permissions
- All active users with admin permissions
- Active users who haven't logged in in the past year
- All pages of Foo type that are children of a specific page
- In the history of a page, only the times it has been published, or only actions by a specific person

### Solution I'd like

- [ ] Every table of information in the admin to be sortable by every heading
- [ ] Ideally add filtering as well as sorting, for most headings
  - [ ] For things like page type and user, a list of checkboxes for the ones you want to filter by
  - [ ] For things like date, a range to filter for (ideally with an option for not having a date)
  - [ ] Should be able to filter by multiple things at a time

### Alternatives I've considered

- Just add filtering to a few specific places, such as viewing users
- Add a "show inactive users" button, equivalent to "show disabled tasks" on the workflow tasks index page

**Comment by gasman** [comment]
Currently working on some improvements to the [generic index view](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/generic/models.py#L14-L30) that should make it much easier to build views with properly-working sortable tables, and adding filtering shouldn't be a massive leap from there. Some preliminary work on this is already in flight on #7381 and #7397 - the rest to follow shortly...

**Comment by nmorduch** [comment]
I'm excited to hear that! Thanks @gasman!

**Comment by thibaudcolas** [comment]
I believe this is covered by #10446 :) @nmorduch if you see a need for more specific functionality not covered in that project, I think it’d now be better to have individual issues for specific sorting/filtering requirements (specific fields, specific views).
