### ISSUE TITLE
Hide disabled workflow tasks when adding tasks to a workflow

### ISSUE THREAD

**Issue by nmorduch** [wagtail/wagtail#7401]
### Problem

This isn't really a big deal for me, but it's a little annoying: I've disabled many builtin workflow tasks and added a small number that we actually use. In the list of workflow tasks (/admin/workflows/tasks/index/), the disabled tasks are hidden unless I click "show disabled tasks," which is a setup that works well for me. However, when adding tasks to a workflow, the list of existing workflow tasks includes all of the disabled ones, and there are a lot of them to sort through. It also makes it feel inaccurate to describe those workflow tasks as "disabled;" it's more like "hidden from the main list."

### Desired solution

Hide disabled workflow tasks in the chooser when adding/editing tasks in a workflow. Could also add a button to show the disabled tasks, but it seems reasonable to me that one would need to re-enable a task in order for it to show there.

**Comment by lb-** [comment]
@nmorduch I have implemented the simpler desired solution, would love your thoughts https://github.com/wagtail/wagtail/pull/7486
