### ISSUE TITLE
Add a settings flag for people on LTS releases to ignore notifications for non-LTS upgrades

### ISSUE THREAD

**Issue by mojeto** [wagtail/wagtail#7405]
### Is your proposal related to a problem?

We run LTS version of Wagtail and because of that our content editors see upgrade available banner
![image](https://user-images.githubusercontent.com/5433957/128315792-d8d4c955-9fdf-43cb-8d19-50691d3385b6.png)
most of the time to the point they learn to ignore it.

### Describe the solution you'd like

Add configuration to display upgrade available banner only if new version of Wagtail LTS available. 

### Describe alternatives you've considered

We considered to disable/hide this banner completely, because it doesn't provide useful information for websites using LTS to LTS upgrade strategy.

### Additional context

This should be now possible, because LTS information added into https://releases.wagtail.io/latest.txt recently to enable this feature https://github.com/wagtail/wagtail/issues/7336#issuecomment-879176660

**Comment by gasman** [comment]
Hi @mojeto - thanks for the suggestion. This is covered by the existing issue #3938.
