### ISSUE TITLE
StreamField of StreamBlocks not being rendered at the editor

### ISSUE THREAD

**Issue by MrCordeiro** [wagtail/wagtail#7424]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I have a StreamField with the following structure:

- StreamField > StreamBlock > StructBlock

This is to create a list of customizable price cards. We used a StreamBlock instead of a ListBlock because ListBlocks are not translatable on Wagtail 2.12. Since we updated to Wagtail 2.14, the following error appear when trying to edit the price list:

```
Uncaught TypeError: e.replace is not a function
    at Object.t.escapeHtml (text.ts:7)
    at StreamBlock.js:112
    at Array.forEach (<anonymous>)
    at StreamBlock.js:111
    at Array.forEach (<anonymous>)
    at t.renderMenu (StreamBlock.js:103)
    at t.open (StreamBlock.js:160)
    at t.toggle (StreamBlock.js:153)
    at HTMLButtonElement.<anonymous> (StreamBlock.js:84)
    at HTMLButtonElement.dispatch (jquery-3.5.1.min.dc5e7f18c8d3.js:2)
```

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py as follows...

```
class PricingPage(BasePage):
    plans = StreamField([("plans", PlanListBlock())])

class PlanListBlock(blocks.StreamBlock):
    """A collection of price cards"""
    plan = PlanCardBlock()

    class Meta:
        icon = ("list-ul",)

class PlanCardBlock(blocks.StructBlock):
    """Price Cards with a plan's name, price, unit and features"""

    title = blocks.CharBlock(required=True, help_text="Plan's title")
    description = blocks.TextBlock(required=True, help_text="Plan's description")
    unit_amount = blocks.DecimalBlock(min_value=0, max_value=100)
    billing_scheme = blocks.CharBlock(
        required=False,
        help_text="Describes how the plan is to be charged",
    )
    features = blocks.StreamBlock(
        [("feature", blocks.CharBlock(label="Feature", icon="tick"))]
    )
```
3. Edit the page on Wagtail Admin

### Technical details

* Python version: Python 3.9.6.
* Django version: django==3.1.8;
* Wagtail version: 2.14.0
* Browser version: Opera 77 on Windows 10

**Comment by gasman** [comment]
Hi @MrCordeiro - thanks for the report. Just to confirm, have you been able to replicate the bug outside of your existing project by following the "Steps to Reproduce" given here?

**Comment by MrCordeiro** [comment]
The problem was in the `icon` Meta option, which should be receiving a tuple.
Sorry for the false alarm (´。＿。｀)
