### ISSUE TITLE
Allow ordering by multiple fields on the Wagtail API

### ISSUE THREAD

**Issue by mixxorz** [wagtail/wagtail#7429]
### Is your proposal related to a problem?

The Wagtail API does not allow ordering by multiple fields at the same time. For example, let's say I want a list of blog pages sorted by type and in reverse chronological order. This is currently not possible in the API.

### Describe the solution you'd like

`[GET] /api/v2/pages/?type=blog.BlogPage&order=-published_at,blog_type`

The result should be the same as if this query was run:

```python
BlogPage.objects.order_by('-published_at', 'blog_type')
```

### Describe alternatives you've considered

In the meantime, we're going to add this functionality ad-hoc.

### Additional context

This is for a headless website.

**Comment by lb-** [comment]
Labelling as a good first issue for anyone interested in the API - there's an older PR that could be redone and polished up for review also. 

https://github.com/wagtail/wagtail/pull/7433

**Comment by shaikhmudassir** [comment]
@lb- I will work on this issue. please assign it to me

**Comment by lb-** [comment]
@shaikhmudassir we don't assign issues, just get started and do a PR when you're ready. 

See https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html#how-can-i-be-assigned-an-issue-to-contribute-to (also, this guide has lots of helpful info for your first contribution).

**Comment by Davidlred** [comment]
hello!! i am beginning work on this issue, can i have it assigned to me. Thanks

**Comment by zerolab** [comment]
@Davidlred there is already a PR for this #10981. I suggest reviewing.testing it and perhaps help with anything outstandin.

I would also suggest you read https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html as it has lots of information
