### ISSUE TITLE
"Blog Index and Posts" section of tutorial: specify 'PUBLISH' when making new child pages

### ISSUE THREAD

**Issue by jacksorjacksor** [wagtail/wagtail#7430]
In the "Blog Index and Posts" section of the "Getting Started" tutorial, please add "Make sure you specify 'PUBLISH' when making new child pages instead of 'SAVE DRAFT' for this tutorial" or similar.

### Pertinent section of the Wagtail docs 

https://docs.wagtail.io/en/stable/getting_started/tutorial.html#blog-index-and-posts

### Details

In the "Getting Started" tutorial, the learner is instructed to "create a few blog posts" - however, the default option when publishing is "Save Draft". Because I'm logged in and am just exploring things locally, I hadn't noticed this/the importance of everything I've made so far being a "Draft".

This only becomes relevant when working through the "Overriding Context" section, which uses:
```python
blogpages = self.get_children().live().order_by('-first_published_at')
```
This was returning empty for me, so after a bit of hacking I realised it was because none of my child pages satisfied "live()", as they were all drafts. For this to work successfully the pages need to have "PUBLISH" selected, which I don't believe is currently specified.

Thanks!

Rich

**Comment by CullenSharp** [comment]
Hello, I'd like to take this issue on.

**Comment by jacobtoppm** [comment]
Addressed in https://github.com/wagtail/wagtail/commit/2d741386c4f384f1825b9d45522e03806391c239, thanks for raising!
