### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_inc_path' when creating a new child page after a failed previous attempt

### ISSUE THREAD

**Issue by igrekus** [wagtail/wagtail#7434]
### Issue Summary

I was creating fixtures for a legacy site and stumbled upon an error when creating a new child page for a parent page after a failed (an exception from the code I was debugging was raised) previous attempt to create this child page.

### Steps to Reproduce

1. Define parent and child pages for a project
2. Create parent page
3. Click add child page
4. Make child page creation faiil due to any exception
5. Fix exception
6. Try to create child page again
7. Observe mentioned error

### Other relevant information

Unfortunately, I can't share logs due to company policy, but I think I found the cause for this error -- when a child page creation fails, the database is left in the inconsistent state, more precisely `numchild` value for the parent page in the `wagtailcore_page` table is incremented but no actual child page is added, leaving the database in the broken state, which forbids further creation of child pages for this particular parent page. Indirect evidence in favor of this cause was that I fixed the child page creation process when I reset the `numchild` value for that parent page back to zero directly via the database.

The error is raised on this line: `django-treebeard/mp_tree.py/377`: https://github.com/django-treebeard/django-treebeard/blob/cb5131a04e293ce6347465a6fef833e80c5d4f40/treebeard/mp_tree.py#L377

### Technical details

* Python version: Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
* Django version: 3.2.5
* Wagtail version: 2.13.4
* Browser version: 92.0.4515.131 (Official build), (64 bit)

**Comment by gasman** [comment]
Hi @igrekus - yep, it's not unknown for the tree state to get corrupted in this way when errors occur during page creation. The [`manage.py fixtree` command](https://docs.wagtail.io/en/stable/reference/management_commands.html#fixtree) should be able to fix these issues when they occur.
Any instances where this happening as a result of working with pages within Wagtail itself would be our top priority to fix - unfortunately we have limited ability to deal with these kinds of errors happening in user code.

**Comment by igrekus** [comment]
Sorry for bothering you once again, @gasman , out of curiosity -- isn't it possible to increment `numchild` counter after successful child page creation?

Thanks for provided fix, I've missed it in the docs!

**Comment by gasman** [comment]
`numchild` should automatically be incremented on page creation, as long as you go through [the Treebeard API](https://django-treebeard.readthedocs.io/en/latest/api.html) when creating it - usually that would be the `add_child` method.

    new_page = MyPage(title="Hello world")
    # populate other fields of new_page as required
    parent_page.add_child(instance=new_page)
