### ISSUE TITLE
Broken Links in Documentation

### ISSUE THREAD

**Issue by ephes** [wagtail/wagtail#7435]
### Issue Summary

I was reading the [Page models](https://docs.wagtail.io/en/stable/topics/pages.html) documentation today and noticed that the links to all panel types reference documentation did not work. Here's an [example](https://docs.wagtail.io/reference/pages/panels.html#wagtail.admin.edit_handlers.FieldPanel).

### Steps to Reproduce

1. Go to the [page models documentation page](https://docs.wagtail.io/en/stable/topics/pages.html)
2. Click on one of the [panel reference documentation links](https://docs.wagtail.io/reference/pages/panels.html#wagtail.admin.edit_handlers.InlinePanel)
3. Get redirected to an read the docs error page

**Comment by gasman** [comment]
Thanks for the report @ephes! There's an open PR dealing with this at #7390.

**Comment by ephes** [comment]
Oh ok, ups - did a quick search in the open issues, but missed the PR :).
