### ISSUE TITLE
High-contrast mode: Success/Warning/Error help-block content needs a border to be more identifiable

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7447]
This is a bug specific to [Windows high-contrast mode](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/). cc @kbayliss who did the testing for this.

In high-contrast mode, our help blocks don’t have a background, so it’s harder to visually identify them:

![Current](https://user-images.githubusercontent.com/877585/129968683-95f5233b-c5ef-473c-8ba4-3c79a41af670.png)

We propose adding a border matching the color of the background for each, so the blocks become distinguishable in high-contrast mode, without any visible change otherwise.

**Comment by monalisha31** [comment]
@zerolab can i work on this?

**Comment by shariq1989** [comment]
@monalisha31, please respond if you are still planning on working on this otherwise I can finish it up.

**Comment by lb-** [comment]
Merged in via #7660  with changes 28d9ded998587d37680e4143b33081075a85df2a
