### ISSUE TITLE
High-contrast mode: dropdown menu needs custom styles 

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7450]
This is a bug specific to [Windows high-contrast mode](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/). cc @kbayliss who did the testing for this.

There are two issues – first, the trigger needs a border so it can be identified as a button:

![7450 png](https://user-images.githubusercontent.com/877585/129970426-4283f203-4f58-44f4-a8ac-c5a85ba7f00e.png)

Then, we need to customise the styles of the opened dropdown so its contents stands out better compared to the top-level button:

![7450-2](https://user-images.githubusercontent.com/877585/129970552-11ece66e-6c1c-4d51-a3f7-2fbe4281c256.png)

**Comment by anurag629** [comment]
sir, please assign me.
I want to contribute

**Comment by lb-** [comment]
@anurag629 - if you see an issue you want to pick up, no need to have it assigned to you, just add a comment with something like 'I will take a look at this'.

Or simply just put up a PR (pull request) with the potential fix.
