### ISSUE TITLE
High-contrast mode: Switches do not visually convey their state

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7451]
This is a bug specific to [Windows high-contrast mode](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/). cc @kbayliss who did the testing for this.

On and off switch states are identical:

![7451](https://user-images.githubusercontent.com/877585/129970697-5d5f468f-dad1-4138-a858-1935d7d204c8.png)

Fixing this would likely be a matter of re-implementing the state indicator with a border rather than a background.

**Comment by SakshiUppoor** [comment]
Hi, I would like to work on this issue.
