### ISSUE TITLE
High-contrast mode: vertical separation between field panels is lost

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7455]
This is a bug specific to [Windows high-contrast mode](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/). cc @kbayliss who did the testing for this.

Bringing back this vertical separation would just be a matter of adding a border. Current:

![7455-Current](https://user-images.githubusercontent.com/877585/129972397-2ead82f7-0142-4e9d-8925-7b89e33d16a4.png)

Proposed: 

![7455-Proposed](https://user-images.githubusercontent.com/877585/129972414-75d2f787-0125-4786-9fff-4ce4b9babe4c.png)

**Comment by Chakita** [comment]
@thibaudcolas May I work on this issue? 
I am new to open source, any guidance will be greatly appreciated! :)

**Comment by thibaudcolas** [comment]
Hi @Chakita, if you’re keen that would be a smashing first contribution. If you haven’t already, have a look at our [Contributing to Wagtail](https://docs.wagtail.io/en/latest/contributing/index.html) guide first.

Once you’re set up to contribute to Wagtail, have a look through our styles and test the CMS in Windows high-contrast mode as shown in my screenshot, and let us know if you can figure out where this change needs to be made (I’m not too sure at this stage).

**Comment by lb-** [comment]
Fixed via #7472
