### ISSUE TITLE
High-contrast mode: sidebar needs visual separation with main content

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7456]
This is a bug specific to [Windows high-contrast mode](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/). cc @kbayliss who did the testing for this.

Due to how high-contrast mode works, there is no visual separation between the sidebar and the main content:

![7456-Current](https://user-images.githubusercontent.com/877585/129973711-ba4339c3-997c-4ac9-a2b6-0e3764b016c0.png)

We should add a `border-right` matching the background color so this is retained in high-contrast mode.

**Comment by FDGod99** [comment]
hey @thibaudcolas , im new in open source project, can i work on this?

**Comment by lb-** [comment]
Implemented via #7475
