### ISSUE TITLE
Formatting including hyperlink support in Table cells

### ISSUE THREAD

**Issue by Caylu** [wagtail/wagtail#7482]
The Table Cell have pretty limited functionality. Where just new row or column can be added or deleted. 

Currently, table cells cannot have links, formatting like superscript or subscript, bold, underlined text, background and foreground color

We use images where we need some formatted table. But this is not an elegant solution.

Proper formatting options for the table cells will be a nice addition to the product.

**Comment by zerolab** [comment]
There is an early draft/WIP PR #7470 that should hopefully cover this

**Comment by gasman** [comment]
Hi @Caylu - this is being worked on in https://github.com/wagtail/wagtail/pull/7470.
