### ISSUE TITLE
Internationalisation didn't support language locale containing both script and region.

### ISSUE THREAD

**Issue by sih4sing5hong5** [wagtail/wagtail#7487]
### Issue Summary

The `wagtail_urls` always 302 redirects to `LANGUAGE_CODE` locale if current locale contains both script and region, like `en-latn-us` or `en-Latn-US`.

Given `settings.py`
```python

LANGUAGE_CODE = 'en-us'

WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [
    ('en-us', "English"),
    ('en-latn-us', "Latin English"),
    ('en-Latn-US', "BCP 47 case format"),
    ('fr', 'French'),
]
```

- The response of `http://localhost:8001/en-us/` is 200 `Welcome to your new Wagtail site!`.
- The response of `http://localhost:8001/fr/` is 200 `Welcome to your new Wagtail site!`.
- The response of `http://localhost:8001/en-lat-us/` is 302 redirection to `http://localhost:8001/en-us/en-lat-us/`
- The response of `http://localhost:8001/en-Latn-US/` is 302 redirection to `http://localhost:8001/en-us/en-Latn-US/`

### Steps to Reproduce
1. Start a new project with `wagtail start mysite mysite`
2. Append to `mysite/settings/base.py` as follows
```
WAGTAIL_I18N_ENABLED = True
WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [
    ('en-us', "English"),
    ('en-latn-us', "Latin English"),
    ('en-Latn-US', "BCP 47 case format"),
    ('fr', 'French'),
]
INSTALLED_APPS += [
    'wagtail.locales',
]
MIDDLEWARE += [
    'django.middleware.locale.LocaleMiddleware',
]
```
3. Edit `mysite/urls.py` by removing `path("", include(wagtail_urls)),` and adding as follows
```
from django.conf.urls.i18n import i18n_patterns
urlpatterns += i18n_patterns(
    path('', include(wagtail_urls)),
)
```
4. `python manage.py migrate`
5. `python manage.py runserver 0.0.0.0:8001`
6. The results

- The response of `http://localhost:8001/en-us/` is 200 `Welcome to your new Wagtail site!`.
- The response of `http://localhost:8001/fr/` is 200 `Welcome to your new Wagtail site!`.
- The response of `http://localhost:8001/en-lat-us/` is 302 redirection to `http://localhost:8001/en-us/en-lat-us/`
- The response of `http://localhost:8001/en-Latn-US/` is 302 redirection to `http://localhost:8001/en-us/en-Latn-US/`

#### Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
The response of `http://localhost:8001/en-lat-us/` and `http://localhost:8001/en-Latn-US/` should be 200 `Welcome to your new Wagtail site!`.

The `en-Latn-US` tag follows format defined in [RFC 5646](https://www.rfc-editor.org/info/rfc5646). The i18n [doc](https://docs.wagtail.io/en/stable/advanced_topics/i18n.html#locales) follows [BCP 47](https://www.rfc-editor.org/info/bcp47). The [RFC 5646](https://www.rfc-editor.org/info/rfc5646) of BCP 47 defined `langtag` as follow:
```
langtag       = language
                 ["-" script]
                 ["-" region]
                 *("-" variant)
                 *("-" extension)
                 ["-" privateuse]

 language      = 2*3ALPHA            ; shortest ISO 639 code
                 ["-" extlang]       ; sometimes followed by
                                     ; extended language subtags
               / 4ALPHA              ; or reserved for future use
               / 5*8ALPHA            ; or registered language subtag

 extlang       = 3ALPHA              ; selected ISO 639 codes
                 *2("-" 3ALPHA)      ; permanently reserved

 script        = 4ALPHA              ; ISO 15924 code

 region        = 2ALPHA              ; ISO 3166-1 code
               / 3DIGIT              ; UN M.49 code
```
About case:
```

   These conventions include:

   o  [ISO639-1] recommends that language codes be written in lowercase
      ('mn' Mongolian).

   o  [ISO15924] recommends that script codes use lowercase with the
      initial letter capitalized ('Cyrl' Cyrillic).

   o  [ISO3166-1] recommends that country codes be capitalized ('MN'
      Mongolia).
```

#### I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)
yes

### Technical details

* Python version: Run `python --version`.
  *  Python 3.7.5
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
  *  Version: 3.2.6
* Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
  * Version: 2.14.1
* Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
  *  You’re using Firefox 91.

**Comment by gasman** [comment]
Hi @sih4sing5hong5 - thanks for the report.
It looks like the behaviour you describe is entirely within the `i18n_patterns` function, so this is Django's responsibility rather than Wagtail's. Specifically, `en-Latn-US` does not match Django's [`language_code_prefix_re `](https://github.com/django/django/blob/af10e97531a59e4af09b5ec0c1a3ea476f2b6015/django/utils/translation/trans_real.py#L46) pattern, so it isn't recognised as a valid language code prefix.
