### ISSUE TITLE
External link in richtext editor should have option to open in new tab

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail#7502]
### Is your proposal related to a problem?

Currently, an external link in a rich text field sends the visitor to the linked site in the same tab. This is really bad practice, you've lost the visitor as soon as that happens. 

### Describe the solution you'd like

Either treat all external links to be opened in new tabs or, preferably, have a checkbox (true by default) to open the link in a new tab to insert the target='_blank'. Option is better as you may need to link to internal non-wagtail pages.

**Comment by gasman** [comment]
Hi @enzedonline - please see the discussion on #1167. Wagtail deliberately does not offer this out of the box as it goes against UX best practice, but it can be configured via custom code.
