### ISSUE TITLE
Document Chooser with Populate Title

### ISSUE THREAD

**Issue by aliceni** [wagtail/wagtail#7508]
Hi, I found that Document Chooser cannot populate the updated file title but Image Chooser does.
I think its good to add this feature and its not hard to implement it because the function already exists in image-chooser-modal.js

**Comment by zerolab** [comment]
The relevant bits in the image chooser code are:

https://github.com/wagtail/wagtail/blob/main/wagtail/images/static_src/wagtailimages/js/image-chooser-modal.js#L116-L130

**Comment by akshay-kapase** [comment]
Is this already done?

**Comment by zerolab** [comment]
@akshay-kapase no. Feel free to pick this up.

**Comment by Vruttant** [comment]
Hi, Can I work on this issue?

**Comment by lb-** [comment]
FYI, #7534 enhances the image title population with an override function, it might be good to copy this approach for the document files.

See also #4945 for context
