### ISSUE TITLE
Documentation on RoutablePageMixin should include information on dynamic slug URL parameters

### ISSUE THREAD

**Issue by ocuna** [wagtail/wagtail#7516]
### Pertinent section of the Wagtail docs 

https://docs.wagtail.io/en/stable/reference/contrib/routablepage.html#module-wagtail.contrib.routable_page.models

### Details

It was difficult for me to understand how to add parameters to the @route decorators.  Some tutorials online did provide some assistance, but they often recommend the Wagtail Documentation.  I couldn't find the necessary documentation for dynamic slug URL parameters.

**Comment by ocuna** [comment]
Here are some links from around the web that helped me find the answers:
https://learnwagtail.com/tutorials/routable-page-categories-and-years/
https://www.youtube.com/watch?v=g_csyhvWrBg
https://www.accordbox.com/blog/wagtail-tutorials-routable-page/
https://stackoverflow.com/questions/54185499/wagtail-custom-url-based-on-slugs-using-routablepagemixin

**Comment by lb-** [comment]
@ocuna  please advise what aspect is missing.

I can see in the section above https://docs.wagtail.org/en/stable/reference/contrib/routablepage.html#the-basics

There are documented examples of dynamic URL parts, e.g. see the multiple routes comment, this contains what I think you where asking about.

```
    # Multiple routes!
    @route(r'^year/(\d+)/$')
    @route(r'^year/current/$')
    def events_for_year(self, request, year=None):
```

Is it that the docs do not explicitly point this out in the models section or that maybe we could be clearer that the URL parsing uses the same logic as Django's?

I have looked through the answers linked and cannot see anything too different to what we have in the docs, except it s more verbose.

Maybe a bit more guidance as to what you think we can add to the docs would help.

**Comment by ocuna** [comment]
Thanks @lb for taking the time to consider this.

I was looking for how to send parameters to the view.  Django does have a published code example that shows how the parameter becomes an argument in the view: https://docs.djangoproject.com/en/4.0/topics/http/urls/#specifying-defaults-for-view-arguments

Since last year,  (and at Wagtail Space US this year) I've learned to rely more on Django documentation for example features.  When I was getting started with Wagtail, I was fairly new at Django at the same time.

**Comment by lb-** [comment]
Thanks for responding @ocuna - it's hard to find a balance in the docs between when to explain how Django works vs what Wagtail.does / does not add on top. Glad you have had some success with learning this.
