### ISSUE TITLE
Page programatic chagnes not reflected in admin backoffice

### ISSUE THREAD

**Issue by alramalho** [wagtail/wagtail#7539]
### Issue Summary

When I call the `save` method on the Page class, the changes are not reflected in the admin interface.

### Steps to Reproduce

1. Programatically call the `save` method on any page
2. Check the same page in backoffice

`Expected: `
The `updated on` tab would reflect the time when save was called

`Actual:`
It doesn't

`Notes:`
I am actually calling the save method as `page.save(user=request.user)` since I do have access to the request object, hoping that it would be reflected in the user personal admin dashboard as well. (It also doesn't)

Wagtail version 2.11

**Comment by gasman** [comment]
Hi @alramalho,
As per https://docs.wagtail.io/en/stable/reference/pages/model_reference.html#pagerevision , you need to call `page.save_revision()`. This is necessary to accommodate pages being saved as draft - the Page model itself reflects the live published state of the page, so the admin backend needs to use the page revision history to retrieve the up-to-date version including any draft edits.
