### ISSUE TITLE
Use Full URL for ImageRenditionField.

### ISSUE THREAD

**Issue by hammygoonan** [wagtail/wagtail#7558]
### Is your proposal related to a problem?

I'm a big fan of the new `full_url` field that images have and would like them to be easily used in the API.

Assuming one's frontend app is living on a different domain to the Wagtail API then the default relative URLs aren't as useful.

### Describe the solution you'd like

Add `full_url` to the output of `ImageRenditionField`.

I propose it just replace the `url` field altogether, but both could be returned.

### Describe alternatives you've considered

I've been extending the `ImageRenditionField` for use in my own projects

### Additional context

(Write your answer here.)

**Comment by lb-** [comment]
As a small enhancement we could add the full url alongside existing url, this way we don't have a backwards compatibility issue. 

Marking as a good first issue for someone who wants to look at how the API works. 

Also recommend we do the same change for documents.

**Comment by PaarthAgarwal** [comment]
I'll give it a shot

**Comment by PaarthAgarwal** [comment]
I've made the necessary changes in the code. How should I update docs?

**Comment by lb-** [comment]
Yeah. I would assume this change needs to come with a docs update also. Thanks @PaarthAgarwal

**Comment by PaarthAgarwal** [comment]
Ahh I was asking how should I update docs😅

**Comment by lb-** [comment]
I think we would probably only need to update the docs example here. 

https://docs.wagtail.org/en/latest/advanced_topics/api/v2/configuration.html#images-in-the-api

**Comment by lb-** [comment]
Removing documents label as they work differently and probably best to keep this issue focused.
