### ISSUE TITLE
Refine audit logging for alias pages

### ISSUE THREAD

**Issue by phildexter** [wagtail/wagtail#7593]
Currently when using alias pages, the site history report gets pretty busy as any change to a page with alias pages is shown multiple times (one per alias page). This is making things tricky for those who have many locales.

It's also not that useful more generally to log every publish or change as a change to every alias page.

The suggestion is that for alias pages we should only log actions on the alias page, rather than actions that are inherited from the source page. These would be:
 - Creation
 - Deletion
 - Conversion to regular page
 - Move page

**Comment by zerolab** [comment]
@phildexter I've been looking at this and so far the only additional things that get looged for aliases are the publish/unpublish actions which are relevant as this propagates from the source page and is an action that actually happens.

We could potentially add an "include alias page" checkbox filter that would help with the report. Let's chat

**Comment by zerolab** [comment]
Having discussed this further offline, removed publish/unpublish log actions in #7937
