### ISSUE TITLE
Inconsistent output from RichTextField and RichTextBlock

### ISSUE THREAD

**Issue by gajus11** [wagtail/wagtail#7664]
### Issue Summary

Inconsistent output from RichTextField and RichTextBlock (Wagtail API v2).
 
For example if we use Internal link handled by PageLinkHandler:

RichTextField output:
`<html><body><p data-block-key=\"ca20z\">Test internal link</p><p data-block-key=\"d12am\"><a href=\"/\">Home</a></p></body></html>`

RichTextBlock output:
`<p data-block-key=\"s1g1a\">Test internal link</p><p data-block-key=\"b5i7\"><a id=\"5\" linktype=\"page\">Home</a></p>`

As you can see `a` tags are different.
RichTextBlock doesn't return actual path.

### Steps to Reproduce

1. Insert "Internal link" into RichTextField
2. Insert the same "Internal link" into RichTextBlock
3. Check outputs

**Comment by gasman** [comment]
This is covered by #2695 (and the discussion there gives some workarounds).
