### ISSUE TITLE
wagtail 2.15 missing "Enable ordering of child pages" in table-headers 

### ISSUE THREAD

**Issue by danhayden** [wagtail/wagtail#7680]
### Issue Summary

I have upgraded a wagtail project from 2.14.2 to 2.15 and now seem to have no way to sort child pages. 

The sort feature appears to have been replaced by the bulk actions feature.. Was it intentional to remove sorting?

Sort option showing in 2.14:
![wagtail 2 14](https://user-images.githubusercontent.com/1385253/140320581-4c2f7950-6944-4688-bafc-d24da1e97101.png)

### Steps to Reproduce
1. Update to wagtail 2.15
2. Navigate to home admin page

Sort option missing in 2.15
![wagtail 2 15](https://user-images.githubusercontent.com/1385253/140320595-bab4d20f-cd80-41b7-84f8-e14483512ddc.png)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.9.7
* Django version: 3.2.9
* Wagtail version: 2.15
* Browser version: Firefox 93

**Comment by gasman** [comment]
Hi @danhayden,
This can now be found in the More dropdown - "Sort menu order".

**Comment by danhayden** [comment]
I have just noticed that the sort feature can be found in the more menu..

![wagtail 2 15 more menu](https://user-images.githubusercontent.com/1385253/140322461-5f4ffa9b-bbc7-40f9-83b8-a3594a4f19e5.png)

I find this UI a little odd, when you select 'Sort menu order' you then lose the bulk actions with no clear way to get them back 

![wagtail 2 15 more menu 2](https://user-images.githubusercontent.com/1385253/140322867-ec4dcc6c-bc4b-452a-9eb6-5905aa806db2.png)

**Comment by danhayden** [comment]
> Hi @danhayden, This can now be found in the More dropdown - "Sort menu order".

Thanks @gasman, I had spotted it when play around a little more. Is there a way to restore the bulk actions options after selecting 'Sort menu order'

**Comment by allcaps** [comment]
Yes, click the sort icon.

https://user-images.githubusercontent.com/1969342/140406689-0abc72f1-3e7a-46b7-8f12-0f99ed655559.mov
