### ISSUE TITLE
Stray checkbox on locked pages report

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#7681]
### Issue Summary

The Locked Pages report (and possibly others inheriting from PageReportView) has a stray additional column with a checkbox, presumably from the bulk actions feature, which causes the column headings to get out of step:

![Screenshot 2021-11-04 at 14 38 33](https://user-images.githubusercontent.com/85097/140334621-38a41691-f20d-48b5-b38c-3d2d7ed69519.png)

Thanks to @Tijani-Dia for reporting.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject` / `./manage.py migrate` / `./manage.py createsuperuser`
2. Log in, edit the homepage, select 'Lock' from the action menu
3. Go to Reports -> Locked pages

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.8.0
* Django version: 3.2.8
* Wagtail version: 2.15
* Browser version: Chrome 95.0.4638.54

**Comment by laymonage** [comment]
Hi, I made a PR for this in #7687. Let me know if there are any other changes needed. Thanks!
