### ISSUE TITLE
csrf_token missing for admin dashboard workflow actions (resulting in 403)

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#7688]
### Issue Summary

When a `POST` is made to the workflow URLs `admin/pages/workflow/action/` via the dashboard buttons (e.g. Approve) it does not contain the `csrfToken` resulting in a 403 each time.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Create a new page & publish
3. Edit that same page but this time put to moderator's approval
4. Go to the dashboard (admin home)
5. Click 'Approve'
6. Expected: Should work & approve the page's moderation, Actual: user is shown a 403 error

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: No - Wagtail bakerydemo without changes only.

<img width="1873" alt="Screen Shot 2021-11-08 at 9 10 12 pm" src="https://user-images.githubusercontent.com/1396140/140733351-f955d1ed-283b-45b8-a85e-fc3ce20b6d49.png">

<img width="1873" alt="Screen Shot 2021-11-08 at 9 10 36 pm" src="https://user-images.githubusercontent.com/1396140/140733360-6657420b-6e14-4f28-9233-f81c95812305.png">

### Technical details

* Python version: 2.7.6
* Django version: 3.2.6
* Wagtail version: 2.15
* Browser version: Chrome 95 https://www.whatsmybrowser.org/b/VAX8V

### Likely root cause

* Dashboard renders buttons with `data-workflow-action-url` to indicate the action URL to POST to.
* `client/src/entrypoints/admin/workflow-action.js` has a function `ActivateWorkflowActionsForDashboard` which accepts a `csrfToken` and for non-modal workflow actions (e.g. approve but not approve with comment) it will `POST` to `buttonElement.dataset.workflowActionUrl` which in the approve case is something like `admin/pages/workflow/action/`
* This function is initiated in the template `wagtail/admin/templates/wagtailadmin/home/workflow_pages_to_moderate.html` - see `document.addEventListener('DOMContentLoaded', ActivateWorkflowActionsForDashboard('{{ csrf_token|escapejs }}'));`
* This template is used by `wagtail/admin/views/home.py` - see
* ```class WorkflowPagesToModeratePanel(Component):
    name = 'workflow_pages_to_moderate'
    template_name = 'wagtailadmin/home/workflow_pages_to_moderate.html'
    order = 220```
* However, the `get_context_data` does not appear to return the context variable `csrf_token` at all

### Recommended fix

* It is probably best to align the `csrf_token` with the Django tag usage instead of passing it down as a variable through the component's context.
* However, it appears that a similar approach has been taken for wagtail/admin/templates/wagtailadmin/home/locked_pages.html (not sure if that is broken also) - but it seems like there is an intentional escapejs usage

**Comment by mpoli** [comment]
I experience this same issue with:

python 3.10
django 3.2.9
**wagtail 2.15**
chrome 95
cookiecutter-django installation

**Comment by lb-** [comment]
Fix coming in 2.15.1
