### ISSUE TITLE
`default_app_config` in `__init__.py` deprecated since Django 3.2

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/wagtail#7692]
### Is your proposal related to a problem?

Since Django 3.2 it is not necessary anymore to declare a `default_app_config` is only a single app config is present in the `apps.py`. 

With that declaration, Django throws deprecation warnings like so:
```
/venv/lib/python3.8/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'wagtail.core' defines default_app_config = 'wagtail.core.apps.WagtailCoreAppConfig'. Django now detects this configuration automatically. You can remove default_app_config.
```

### Describe the solution you'd like

Only define `default_app_config` for Django versions before 3.2. 

```python
# __init__.py
import django 

if django.VERSION < (3, 2):
    default_app_config = 'wagtail.core.apps.WagtailCoreAppConfig'
```

### Additional context

See also
https://docs.djangoproject.com/en/3.2/releases/3.2/#automatic-appconfig-discovery

**Comment by gasman** [comment]
Fixed in #7721
