### ISSUE TITLE
Auto-collapsing StreamField blocks in the admin while editing a page

### ISSUE THREAD

**Issue by kunambi** [wagtail/wagtail#7705]
### Is your proposal related to a problem?

My clients love the Wagtail CMS but are getting increasingly frustrated when editing their pages. The major complain is that it's very difficult to have an overview of all the StreamField blocks as their pages become more content-rich.

### Describe the solution you'd like

Previously we used [wagtail-react-streamfield](https://github.com/wagtail/wagtail-react-streamfield) which had the exact feature I'd like re-implemented—on page load it's **auto-collapsing all the StreamField blocks** which allows faster scrolling and overview.

Since wagtail-react-streamfield isn't supported any longer, there's no way to have clean overview.

### Describe alternatives you've considered

Another alternative would perhaps to have a "remote control" in the top right corner of the page with in-page anchors to every StreamField block. However, this remote control would have to be updated dynamically every time a block is moved, added, or deleted.

### Additional context

Decided to create a feature request after discussion on Slack, worrying that the conversation would disappear into the void.

**Comment by bitwise-gmbh** [comment]
> My clients love the Wagtail CMS but are getting increasingly frustrated when editing their pages. The major complain is that it's very difficult to have an overview of all the StreamField blocks as their pages become more content-rich.

I get the very same feedback. People love putting together content using StreamField but get overwhelmed by the confusing amount of visible editing fields.

A solution would be highly appreciated.

Thank you for your great work on Wagtail!

**Comment by roodie** [comment]
I would also appreciate any solution. The flexibility and usability of the streamfield means that we are using it for different purposes - not just article pages, but sometimes to display structured data in an easy to edit format. For these, the ability to collapse the elements is a boon.

Even a "Collapse all/expand all" button/function would do fine for the time being, with the option to set the initial state when you define the stream field.

**Comment by zerolab** [comment]
Hey all, 
I'd be happy to review a PR that implements this.

In the meantime you could achieve this with a bit of custom JS added via [`insert_editor_js`](https://docs.wagtail.io/en/stable/reference/hooks.html#insert-editor-js):

```js
// jQuery
$('div.c-sf-block__content[aria-hidden="false"]').each(function() {
  $('.c-sf-block__header', $(this).parent()).click()
})
```
I'd use plain Javascript though:

```js
const blocks = document.querySelectorAll('div.c-sf-block__content[aria-hidden="false"]');

blocks.forEach(function(block) {
    block.parentNode.querySelector('.c-sf-block__header').dispatchEvent(new MouseEvent("click"));
});
```

**Comment by bitwise-gmbh** [comment]
> Hey all, I'd be happy to review a PR that implements this functionality.
> 
> In the meantime you could achieve this with a bit of custom JS added via [`insert_editor_js`](https://docs.wagtail.io/en/stable/reference/hooks.html#insert-editor-js):
> 
> 
> ```js
> const blocks = document.querySelectorAll('div.c-sf-block__content[aria-hidden="false"]');
> 
> blocks.forEach(function(block) {
>     block.parentNode.querySelector('.c-sf-block__header').dispatchEvent(new MouseEvent("click"));
> });
> ```

Thank you, this works for me.

My wagtail_hooks.py now looks like this:

`from django.utils.html import format_html_join
from django.utils.safestring import mark_safe
from django.templatetags.static import static

from wagtail.core import hooks

@hooks.register('insert_editor_js')
def editor_js():

    return mark_safe(
        """
        <script>
        document.addEventListener('DOMContentLoaded', function () {
            const blocks = document.querySelectorAll('div.c-sf-block__content[aria-hidden="false"]');

            blocks.forEach(function(block) {
                console.log('tdfhrtfgh');
                block.parentNode.querySelector('.c-sf-block__header').dispatchEvent(new MouseEvent("click"));
            });
        });
        </script>
        """
    )`

Now all blocks in my StreamFields are collapsed by default when editing a page.

By default on collapsed blocks, the value of the first sub-block in the StructBlock is shown as their name/description which can be confusing.
So I am now using the label_format parameter on my StreamField blocks, e.g. label_format='Intro-Section') to rename them for clarity. You need wagtail 2.15 for this to work.

This seems like a good interim solution to me. Thank you!

**Comment by gasman** [comment]
PR: #7738
