### ISSUE TITLE
Warn users when they create a redirect for an existing page

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#7714]
Currently the redirect just fails if a page exists with the url defined in the redirect.

**Comment by lb-** [comment]
@tmsndrs can you please provide more information, please can you rewrite this following the 'feature' template.

see https://github.com/wagtail/wagtail/issues/new?assignees=&labels=type%3AEnhancement&template=FEATURE_REQUEST.md&title=

For example, it is unclear if you mean that the `old_path` should be validated against an existing page or the `redirect_page_route_path`

**Comment by gasman** [comment]
Closing due to lack of updates.
