### ISSUE TITLE
AttributeError: 'User' object has no attribute 'first_name' with slim sidebar

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#7716]
### Issue Summary

We have a [custom user model](https://github.com/WesternFriend/WF-website/blob/65d6a87c377cbdf6320c872b873fc3457f78bd98/accounts/models.py#L11) where we have removed the `first_name` and `last_name` attributes. When enabling the slim sidebar, we get the following traceback

```py
File "/media/brylie/SecondHD/Code/WesternFriend/WF-website/.venv/lib/python3.9/site-packages/wagtail/admin/ui/sidebar.py", line 164, in js_args
    'name': self.user.first_name or self.user.get_username(),
  File "/media/brylie/SecondHD/Code/WesternFriend/WF-website/.venv/lib/python3.9/site-packages/django/utils/functional.py", line 247, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'first_name'
```

### Steps to Reproduce

1. define a custom user model without the `first_name` or `last_name` fields
2. enable the slim sidebar with `WAGTAIL_EXPERIMENTAL_FEATURES = ["slim-sidebar",]`
3. observe the `AttributeError`

## Make custom user models more simple

It is often advised for projects to define a custom user model early on. Similarly, many custom user models opt-out of personally identifiable `first_name` and `last_name` fields.

There should be a bit clearer documentation around defining custom user models while Wagtail core could be made more resilient to the available properties.

https://github.com/wagtail/wagtail/issues/7410

### Technical details

* Python version: 3.9.5
* Django version: 3.2.9
* Wagtail version: 2.15.1

**Comment by thibaudcolas** [comment]
Thank you @brylie, I can confirm the issue, and am working on a fix.
