### ISSUE TITLE
Search fails on MySQL with missing `invert` attribute

### ISSUE THREAD

**Issue by ACMCMC** [wagtail/wagtail#7725]
### Issue Summary

When doing a three-word (or more) search query, such as:

```python3
search("W1 W2 W3", myModel, operator='and')
```

It errors with `AttributeError: 'CombinedLexeme' object has no attribute 'invert'`.

Originally reported by @cnk on #7719.

### Steps to Reproduce

1. In the `wagtail.search.tests.test_backends.BackendTests.test_search_and_operator` method, change the search query to `"JavaScript Definitive Guide"` instead of `"JavaScript Definitive"`.
2. Run the test on a MySQL database environment.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.9.1
* Django version: 3.1.13
* Wagtail version: 2.16a0

**Comment by ACMCMC** [comment]
I have found the solution. I will submit a PR solving the issue and reference it.

**Comment by gasman** [comment]
Fixed in #7726
