### ISSUE TITLE
Updating the `README.md` file in the default branch

### ISSUE THREAD

**Issue by FahimFBA** [wagtail/wagtail#7744]
I think accepting the following diff would be beneficial.

```diff
- Wagtail is used by NASA, Google, .....
+ Wagtail is used by [NASA](https://www.nasa.gov/), [Google](https://www.google.com/), ......
```

### Pertinent section of the Wagtail docs 
https://github.com/wagtail/wagtail/blob/main/README.md

### Details

If you would add the URL to the relevant companies then if anyone is unfamiliar with any of them they can simply check those companies out easily.

**Comment by vupham04** [comment]
I think this issue is addressed through commit https://github.com/wagtail/wagtail/commit/66237d09e758aa605523c6e1494ea66546c19926 right? I think the issue should be closed

**Comment by gasman** [comment]
@vupham04 Thanks for pointing this out!
