### ISSUE TITLE
Extraneous action button when creating/editing Workflow Tasks

### ISSUE THREAD

**Issue by alxbridge** [wagtail/wagtail#7758]
### Issue Summary

When creating or editing a Workflow Task in Wagtail 2.15.x, a thin (text-less) action button appears in the top right corner of the interface, linking to the URL already loaded.

![Screenshot 2021-12-07 at 11-43-22 Wagtail - New workflow task](https://user-images.githubusercontent.com/8955716/145023358-af89216d-fc8a-49b0-ac81-effc9202c8fe.png)

### Steps to Reproduce

1. Log in to the Wagtail admin
2. Navigate to _Settings_->_Workflow tasks_
3. Press the _New workflow task_ button: the button will appear on the admin page which loads

I've traced this issue back to https://github.com/wagtail/wagtail/commit/b89e298c084fd0c55c147e255f1eb51e57f3f5f9 - specifically, the lines in _wagtail/admin/views/generic/models.py_ which add `context['action_url']` in the `get_context_data()` method of the [`CreateView`](https://github.com/wagtail/wagtail/commit/b89e298c084fd0c55c147e255f1eb51e57f3f5f9#diff-e1bcd86f7d82181d10043d53e7cc8eda34f657fe28c7a75c3768b707ad000e10R60) and [`EditView`](https://github.com/wagtail/wagtail/commit/b89e298c084fd0c55c147e255f1eb51e57f3f5f9#diff-e1bcd86f7d82181d10043d53e7cc8eda34f657fe28c7a75c3768b707ad000e10R155) classes.

I assume that these lines can't simply be removed, as this is intended to be generic code. One possible fix might be to alter the template which is responsible for outputting the action button (_wagtail/admin/templates/wagtailadmin/shared/header.html_) to only do so in particular circumstances - e.g. if the `action_url` doesn't match the current URL, or if both an `action_url` and `action_text` are provided. I'm happy to submit a PR if either of those solutions seem viable.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes

### Technical details

* Python version: 3.6.9
* Django version: 3.2.10
* Wagtail version: 2.15.1
* Browser version: Firefox 94.0 (Linux) and others

**Comment by gasman** [comment]
Thanks for the report @alxbridge! I think the fix for this is included in #7657, currently awaiting review.
