### ISSUE TITLE
Extend azurerm_virtual_machine_data_disk_attachment capability to VMSS

### ISSUE THREAD

**Issue by anujtechnet** [wagtail/wagtail#7784]
### Is your proposal related to a problem?

We would like to use terraform for attaching managed data disks to VMSS instances outside of scale-set model so that in case of a disaster or vertical scaling we can safely detach them and attach to new VMSS instances. We have tried azurerm_virtual_machine_data_disk_attachment resource which worked fine with a standalone VM but failed to attach disk to a VMSS instance. We have created #14580 to confirm if its a bug but seems its the intended behaviour. 

### Describe the solution you'd like

azurerm_virtual_machine_data_disk_attachment or a new resource should be able to perform operations on VMSS instances where a disk can be attach/detach by passing an VMSS instance id. 

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by zerolab** [comment]
@anujtechnet I believe you confused the projects.
Wagtail has nothing relating to VMSS or `azurerm_virtual_machine_data_disk_attachment`

**Comment by anujtechnet** [comment]
@zerolab Sorry for the inconvenience, I didn't realize that request created in the wrong project.
