### ISSUE TITLE
Wanted: Better control over StreamField search indexing

### ISSUE THREAD

**Issue by chosak** [wagtail/wagtail#7787]
### Is your proposal related to a problem?

Wagtail search allows for indexing of StreamFields, but doesn't easily allow for customization of how StreamField content gets indexed, for example ignoring specific blocks or block types.

Although it is possible to override [`get_searchable_content`](https://github.com/wagtail/wagtail/blob/8413d00bdd03c447900019961d604186e17d2870/wagtail/core/blocks/base.py#L236) on a specific block or StructBlock type, this isn't documented. Additionally, overriding this on a particular block type changes how it gets indexed in every place it gets used, whereas it might be desirable to index it for some pages but not for others.

The default behavior of StreamFields which is to index the content of every sub-block. It might not be obvious to users that this has some unexpected side effects that could leak non-public data.

1. First, consider the case where some block content is entered by the page editor but deliberately excluded from the page template. Say for example a public-facing summary with some internal notes:
   
   ```py
   # blocks.py
   class SummaryBlock(blocks.StructBlock):
       summary = blocks.RichTextBlock()
       notes = blocks.RichTextBlock()

       class Meta:
          template = 'summary_with_notes.html'
   ```
   
   ```jinja
   <!-- summary_with_notes.html -->
   <!-- note that value.notes is deliberately not rendered here -->
   {{ value.summary }}
   ```
   
   Users might not expect that indexing a StreamField containing a SummaryBlock would also index any notes blocks. Even though this data presumably wouldn't be rendered in search results, it could be leaked via a search, for example if someone searches on a phrase used in the private notes. Pages being returned in search results would then indicate that the search term was being used on an internal field.

2. Similarly, if StreamField blocks are used for configuration purposes (as opposed to for data), the use of CharBlock and similar base blocks for non-public settings could be problematic. Consider a case where a StreamField block is used to insert dynamic placement of some kind of submission form that makes an API call. In this case, the block data might contain some private or secret configuration data:
   
   ```py
   # blocks.py
   class FormBlock(blocks.StructBlock):
       content = blocks.RichTextBlock()
       secret_api_key_used_when_form_is_submitted = blocks.CharBlock()
   ```
   
   (I realize that there may be better ways to implement this than with a StreamField block, but believe me that implementations like this exist.)

   In this case, because CharBlocks are indexed by default, the content of the secret key will be searchable, most likely unexpectedly. This may not be a serious problem, depending on how guessable a particular secret value is, but it's not ideal.

Even setting aside these data leakage scenarios, it's also the case that, when creating complex StreamFields and StructBlocks, certain blocks may be less useful to search than others. If we consider [the `PersonBlock` example from the StreamField tutorial](https://docs.wagtail.io/en/stable/topics/streamfield.html#structblock), one might easily imagine that you might like `first_name` and `surname` to be exposed to search, but not `biography`.

### Describe the solution you'd like

At a minimum, it would be nice if the Wagtail documentation mentioned how search works with StreamFields, maybe

- in a new "Search considerations" section on the [How to use StreamField for mixed content](https://docs.wagtail.io/en/stable/topics/streamfield.html) page
- somewhere under "Indexing extra fields" on the [Indexing](https://docs.wagtail.io/en/stable/topics/search/indexing.html#indexing-extra-fields) page

[`get_searchable_content`](https://github.com/wagtail/wagtail/blob/8413d00bdd03c447900019961d604186e17d2870/wagtail/core/blocks/base.py#L236) could then be made an "official" API and added to the documentation, with an example of how to override this for custom block types.

### Describe alternatives you've considered

@gasman had a nice idea back in 2016 on https://github.com/wagtail/wagtail/issues/2500#issuecomment-212158853 about indexing SnippetChooserBlocks, which requires similar consideration. Although unfortunately not implemented yet, the proposal there was to allow for customization of indexing when a field is added to an index:

```py
class Article(Page):
    body = StreamField([
        ('paragraph', RichTextBlock()),
        ('city', SnippetChooserBlock(City)),
    ])

    search_fields = [
        index.SearchField('title'),
        index.SearchStreamField('body', {
            'paragraph': True,  # always index paragraph blocks in full
            'city': ['name'],  # only index the 'name' field of city blocks
        })
    ]
```

It might be more complicated to support something similar for deeply-nested StructBlocks. Ideally users would have the flexibility to implement indexing customizations both at the block class level (via `get_searchable_content`) and at the specific field via some mechanism like this.

**Comment by gasman** [comment]
Have opened a new issue #11127 outlining a preferred solution to this - I propose adding a `search_index` option (defaulting to True) to all relevant blocks. This will be much simpler to implement than the `SearchStreamField` route, which I think is overengineering things a bit... Closing this in favour of that one.
