### ISSUE TITLE
PageChooserPanel not having the heading option

### ISSUE THREAD

**Issue by jffr** [wagtail/wagtail#7789]
### Issue Summary

All the panels have an option for adding a custom heading. The PageChooserPanel doesn't have that option.

```python
MultiFieldPanel(
    [
        FieldPanel("cta_label", heading="Label"),
        PageChooserPanel("cta_page"),
        FieldPanel("cta_url", heading="URL")
    ],
    heading=_("Call to action")
),
```

This results into the following:

![Screenshot 2021-12-16 at 11 06 54](https://user-images.githubusercontent.com/74216106/146351453-1622e768-539b-469e-beab-2cddb25ceeec.png)

**Comment by vihaanthora** [comment]
@jffr Hi, I tried to look more into this issue, and found out that some other panels such as StreamFieldPanel and FieldRowPanel were also missing the heading parameter in the function args. Is it possible that this is not a bug, but has been done intentionally?

**Comment by jffr** [comment]
@vihaanthora Thank you for your answer! Maybe you're right and it has been done intentionally. I am still new to Wagtail, but `verbose_name` did solve my issue for labeling the `PageChooserPanel`. It would be nice if `heading` was available for all the panels to stay consistent. But then again, I can solve this with `verbose_name`. I will mark this as closed!
