### ISSUE TITLE
Issues with MariaDB not seen in MySQL

### ISSUE THREAD

**Issue by Amondale** [wagtail/wagtail#7792]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

during manage.py migrate, the following warning is displayed:
WARNINGS:
wagtailcore.WorkflowState: (models.W036) MariaDB does not support unique constraints with conditions.
	HINT: A constraint won't be created. Silence this warning if you don't care about it.

### Steps to Reproduce

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
after migrate completes, I attempt to run `manage.py load_initial_data` and errors out with:

  File "/xxxx3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry '2-1-1' for key 'wagtailcore_groupcollect_group_id_collection_id_p_a21cefe9_uniq'")

fixtures/bakerydemo.json was created with manage.py dumpdata >bakerydemo.json (SQLITE import of same json file is OK)

Running MariaDB 10.6.5 database server

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

* Python version: Run `python --version`.  3.9.9
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`  Django>=3.2,<3.3. 
* Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`. Name: wagtail
Version: 2.15.1

* Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
Firefox 95.1-1

Wondering if there's a MariaDB setting that could ignore/jump over this error?

**Comment by Amondale** [comment]
mysqlclient 1.3.1 seemed to take care of the issue. The same warning is shown for native mysql, and I think I was missing an optional parameter when I attempted to dumpdata.

**Comment by Seeyouagainqz** [comment]
请问这个问题确定原因了吗，解决了吗
