### ISSUE TITLE
Sidebar language picker does not display correctly when slim sidebar is enabled

### ISSUE THREAD

**Issue by chris48s** [wagtail/wagtail#7806]
### Issue Summary

Sidebar language picker does not display correctly when slim sidebar is enabled:

![Screenshot at 2021-12-21 11-14-26](https://user-images.githubusercontent.com/6025893/146961156-8a9eebad-b933-4246-bf11-ec686dd2521f.png)

### Steps to Reproduce

Start a clean wagtail app + do a minimal localization setup. I'm showing `simple_translation` here for minimal repro case. Also reproduces with wagtail-localize:

```py
INSTALLED_APPS = INSTALLED_APPS + [
    'wagtail.locales',
    'wagtail.contrib.simple_translation',
]

WAGTAIL_I18N_ENABLED = True

WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [
    ("en-us", "English"),
    ("fr", "French"),
]
```

Turn on slim sidebar

```py
WAGTAIL_EXPERIMENTAL_FEATURES = ["slim-sidebar"]
```

Create enough content through the frontend (1 level of hierarchy) and translate it so that the sidebar language picker is shown

with `WAGTAIL_EXPERIMENTAL_FEATURES = ["slim-sidebar"]` on:

![Screenshot at 2021-12-21 11-14-26](https://user-images.githubusercontent.com/6025893/146961290-a4e9b7a4-489b-408b-9a0b-268b8c745517.png)

with `WAGTAIL_EXPERIMENTAL_FEATURES = ["slim-sidebar"]` off:

![Screenshot at 2021-12-21 11-14-04](https://user-images.githubusercontent.com/6025893/146961304-0c6115b7-fa9e-44c1-a64a-557576225b80.png)

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Python 3.8.10
* Django version: 3.1.13
* Wagtail version: 2.15.1
* Browser version: Screenshots are from Firefox but also reproduces in Chromium

**Comment by thibaudcolas** [comment]
Thank you @chris48s, I was able to reproduce this and will work on a fix.
