### ISSUE TITLE
The Pages Api doesn't include port in the URLs is generates

### ISSUE THREAD

**Issue by ruilvo** [wagtail/wagtail#7807]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Using wagtails API, nagivating to `/api/v2/wagtail/pages/` (where I have the endpoint), I see this:
```json
{
    "meta": {
        "total_count": 1
    },
    "items": [
        {
            "id": 2,
            "meta": {
                "type": "wagtailcore.Page",
                "detail_url": "http://localhost/api/v2/wagtail/pages/2/",
                "html_url": "http://localhost/cms/pages/",
                "slug": "home",
                "first_published_at": null
            },
            "title": "Welcome to your new Wagtail site!"
        }
    ]
}
```

The problem is that `http://localhost/api/v2/wagtail/pages/2/` 404s because it's running on the dev server and so the URL would be `localhost::8000`.

### Steps to Reproduce

Very the API results when using the Django development server on port 8000.

**Any other relevant information** 
Wagtail was added after the fact to an existing app, thus the reason the endpoints are not standard.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no, because of above.

### Technical details

* Python version: Python 3.9.9
* Django version: Version: 3.2.10
* Wagtail version: Version: 2.15.1
* Browser version: Firefox 95

**Comment by zerolab** [comment]
@ruilvo have you updated the port in Settings > Sites?

In short, Wagtail support multi-site setups, but out of the box it comes with a single site definition which defaults to port 80. Given we don't have control over what port people run their sites locally, we're not making any further assumptions, but give anyone the means to update things as needed.

Model reference: https://docs.wagtail.io/en/stable/reference/pages/model_reference.html#site-model-ref

**Comment by ruilvo** [comment]
Thanks. Sorry for missing the docs. 
Btw, is there a way to control the port setting programatically? So I can change it from 8000 to whatever according to my current config?

I'll close, but please feel free to answer :)

**Comment by zerolab** [comment]
See the model reference I linked to in my previous reply. With that in hand you can write a management command, [fabric](https://www.fabfile.org/) script or anything else that suits your needs for local development.

I suggest continuing this type of support questions in the Wagtail `#support` Slack channel ;)
