### ISSUE TITLE
Ability to collapse StructBlock / Streamfield's by default. 

### ISSUE THREAD

**Issue by IAmNatch** [wagtail/wagtail#7818]
### Is your proposal related to a problem?
The current streamfield implementation supports collapsed streamblocks, but does not allow for them to be set as collapsed by default. I've tried adding collapsed=True via meta on struct blocks, however they are not in approved args, and therefore are not passed down to the streamblock implementation. 

### Describe the solution you'd like
It would be great for for large collections of streamblocks to be collapsed by default, since label templates allow us to customize exactly how content is previewed. 

Adding collapsed=True to a streamfield, or streamblock, should make at least this field, if not all it's children, start collapsed by default when loaded into the admin. 

### Additional context
https://github.com/wagtail/wagtail-react-streamfield/issues/65
It seems as though this was partially working in the react branch during development, but didn't make it over to the final wagtail release.

**Comment by gasman** [comment]
Hi @IAmNatch - this has been implemented in #7738 and will be part of the next release.

**Comment by IAmNatch** [comment]
That's awesome, I didn't catch that! Thanks taking that on!

**Comment by robmoorman** [comment]
Love this one great works getting this in.
