### ISSUE TITLE
Update feature detection docs for OpenCV 3

### ISSUE THREAD

**Issue by edrex** [wagtail/wagtail#784]
I'm not sure if it's too early for this, but opencv 3.0 alpha with support for Python 3 is available, and it would be nice if Wagtail were updated to work with this version if available.
- http://opencv.org/opencv-3-0-alpha.html
- http://code.opencv.org/issues/2811

**Comment by maxpeterson** [comment]
Any plan to upgrade to opencv 3.0?

**Comment by elmcrest** [comment]
any news on this?
so far I figured that in a opencv with python3 environment you need to import via `import cv2` so current code will break.

**Comment by gasman** [comment]
OpenCV 3 support was added to Willow in 1.0, so this may work already - if not, we definitely want it in time for Wagtail 2.0 since we're dropping Python 2 support. ping @kaedroho

**Comment by kaedroho** [comment]
Yep, OpenCV 3 should work since https://github.com/wagtail/wagtail/pull/3828, which made it in to Wagtail 1.13.

**Comment by elmcrest** [comment]
Ok thx for the replies.

Are there any updated docs somewhere? at least the suggested `import cv` which is also still present in sources doesn't work for me. `import cv2` does work

for a quick test you could try https://hub.docker.com/r/jjanzic/docker-python3-opencv/

**Comment by hsleep** [comment]
I have tested that Wagtail 1.13.1 works well with python3 and opencv3.

**Comment by gasman** [comment]
Completed in #5419.
