### ISSUE TITLE
Add internationalisation UI to modeladmin

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#7856]
#6230 set to add the locale filter on the modeladmin index, but was closed and it looks the changes never made it in

Needs:

- [ ] Locale switcher/filter on modeladmin index (most of the code in #6230)
- [ ] Locale switcher on modeladmin edit

**Comment by andresmrm** [comment]
Hi! I started to work on it here #7857 but it seems it won't be so simple like copying code from #6230. Not sure if I'll be able to fix it until tomorrow. :disappointed: 
I need to stop now, but I will try to continue later this day.

**Comment by lb-** [comment]
@zerolab is this done now?
As https://github.com/wagtail/wagtail/pull/7857 is merged in.

**Comment by zerolab** [comment]
Good shout, @lb-
