### ISSUE TITLE
Search icon in search input in header is misaligned

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#7863]
The Search icon in the search box that appears in the header of the search page looks a bit high.

![image](https://user-images.githubusercontent.com/1093808/149507482-d2aefa83-5c21-48cb-acbb-7449ef7a3ff4.png)

Wagtail 2.16a0 (current main)
Tested on Firefox 93 and Brave 1.34.80 (Chromium 97). Both on Linux

**Comment by gasman** [comment]
@amelia291 It's in the header of the results page that you get after running a search, e.g. http://localhost:8000/admin/pages/search/?q=test

**Comment by amelia291** [comment]
I cannot identify the bug mentioned in the issue. It seems like this has been fixed.
<img width="931" alt="Screen Shot 2022-01-28 at 13 40 46" src="https://user-images.githubusercontent.com/60367635/151603301-626b0217-2a26-4da3-8cef-e2c188bfcbcf.png">

**Comment by seanpaulharsevoort** [comment]
Looks like the search icon in the page chooser is misaligned on version 2.16.1 .

<img width="1431" alt="Screenshot 2022-02-22 at 21 19 10" src="https://user-images.githubusercontent.com/38066215/155212888-133e882e-0f53-47b6-ae38-8d407a7b5782.png">

**Comment by thibaudcolas** [comment]
Fixed in #8310.
