### ISSUE TITLE
`@route()` unintended functionality with url encoding

### ISSUE THREAD

**Issue by G-kodes** [wagtail/wagtail#7886]
### Issue Summary

The `{% routablepageurl %}` does not decode the URL generated when passing to an `@route()` decorator.

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Create a class that inherits from `RouutablePageMixin`
3. Add a route that accepts some variable that contains a `/` character in the middle by nature (E.g. DOI's for academic papers)
4. Write a RegEx for that route (E.g. `r"(?P<doi>10.\d{4,9}\/[-._;()\/:a-z0-9A-Z]+\/{0,1})"`)
5. Use the `{% routablepageurl %}` to generate a link for the page (E.g. `{% routablepageurl page 'study' doi=study.doi %}`)

> It may be an ugly or over-simple RegEx, but it did the job! XD

While it is good practice to encode URLs for many, MANY reasons, it was not clear from the documentation whether or not decoding (or lack thereof for the purposes of an `@route()` decorator) was an intended philosophy/approach from TorchBox. As such, my default assumption (and feel free to correct me here) is that if you encode a URL, then you must decode it downstream for the purpose of things like RegEx expressions.

If that is a supported assumption by Wagtail, then this is a bug. If it is an incorrect assumption, then it is a request for an update to the documentation for `RoutabelPageMixin` to explicitly declare that you need to accommodate encoded URLs in RegEx's.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: `Python 3.9.9`
* Django version: `3.2.11`.
* Wagtail version: `2.15.1`
* Browser version:  `Chrome 97`

**Comment by Megs47** [comment]
I have also experienced this issue.

**Comment by gasman** [comment]
Can you provide some example code demonstrating this issue, please?

**Comment by gasman** [comment]
This description isn't really something we can work with in its current form, I'm afraid - we really need to see some specific code that demonstrates the problem, rather than just a text description of some hypothetical code. I'm willing to believe there's a legitimate issue here, but as it stands this is more like a programming assignment that we have to solve to find out what it is :-)

Closing for now, but happy to reopen if you can provide the necessary detail.
