### ISSUE TITLE
Add a way to exclude page subtype from search index

### ISSUE THREAD

**Issue by cnk** [wagtail/wagtail#7890]
### Is your proposal related to a problem?

In our project, we have a number of page types that exist to be the index page for some other page, e.g. BlogIndex is the parent for BlogPost pages. We don't want BlogIndex offered as a search result; we would rather have our search results link directly to the BlogPost pages. Until now we have been achieving that by defining BlogIndex's as `search_fields = []` but in Wagtail 2.16, the check command now tells us `Core Page fields missing in search_fields`. I can silence that warning globally but I would rather be able to explicitly configure BlogIndex to be excluded from search. That way the check command will still be able to tell me when I have incorrectly configured one of my other page types.

### Describe the solution you'd like

I asked the Slack channel if there was an existing option and got: 

> I don't think there is currently a flag for "don't index this model", but it would make logical sense to add one, alongside the search_auto_update one... https://docs.wagtail.io/en/stable/topics/search/indexing.html#disabling-auto-update-signal-handlers-for-a-model

I am filing this issue to remind myself - or anyone else who wants to give it a try - to look into adding a flag for excluding a page model from the search index.

**Comment by cnk** [comment]
This is fixed in Wagtail 5.0 by #9821 From the release notes: 

- Add the ability to [disable model indexing](https://docs.wagtail.org/en/latest/topics/search/indexing.html#wagtailsearch-disable-indexing) by setting search_fields = [] (Daniel Kirkham)

**Comment by lb-** [comment]
Nice. Good find @cnk
