### ISSUE TITLE
Support for page revisions

### ISSUE THREAD

**Issue by prismic** [wagtail/wagtail#79]
One of the features we really wanted in Mezzanine (but couldn't get) is page revision support.  Are there any plans to add this features into Wagtail?

**Comment by Alp-Phone** [comment]
Can these revisions be used to restore a previous version of the page?

**Comment by zerolab** [comment]
Hi @Alp-Phone, see #640. We are focusing on releasing v1.0 after which we will be looking at enhancing revisions and other often-asked features.

**Comment by Alp-Phone** [comment]
Excellent, thank you!
