### ISSUE TITLE
Wagtail should have own 404, 403, 413, 500 error pages

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#790]
Having just attempted to upload a (too) large doc to a client's site's Document library, I received a basic nginx 413 Requested Entity Too Large error page.

Receiving the error at all is nasty, but the fact it wasn't styled added aesthetic insult to injury.

Indeed if you put a foot wrong in the admin and raise a 404, you get the 404 from the front end of the site. Given that implementers may have several websites in wagtail, each with a different livery, this makes the display of the 'default' site's 404 even more jarring.

Wagtail should have wagtail-branded error pages.

**Comment by SalahAdDin** [comment]
Well guys, anything have a style for the template? i have some page, but, the styles are very bad.

**Comment by zerolab** [comment]
Is https://github.com/sprymix/wagtail/commit/467594ab53ea46963a4f07cfa5b968e45de1feda a good fix for the 413 error issue?

**Comment by SalahAdDin** [comment]
And my templates? are so terrible?

**Comment by zerolab** [comment]
@SalahAdDin they are not terrible. However there needs to be some design/front-end direction. And it is best to submit a pull request as it makes the life of the maintainers a whole lot easier.

Cheers,
Dan

**Comment by kaedroho** [comment]
Quick note for whoever wants to implement this:

It may be possible to make use of some of the refactoring in
https://github.com/torchbox/wagtail/pull/912 to write some code that will
catch all 4xx errors raised within the admin views and display a custom
template.

**Comment by SalahAdDin** [comment]
Ok Zerolab, when i test the templates in production i'll do a pull? i want help with this great project.

**Comment by gasman** [comment]
A 404 error page was implemented in #3705 - as discussed there, we won't extend this to other errors, since in those cases we either have an existing pattern for reporting the error (403 / permission denied), or they indicate a failure of the Wagtail installation itself and cannot sensibly be caught within Wagtail (413 / 500).
