### ISSUE TITLE
RichTextField is not working, throwing javascript console error

### ISSUE THREAD

**Issue by lapinvert** [wagtail/wagtail#7902]
### Issue Summary

When I declare RichTextField it does not render as wysiwyg editor in wagtail admin, but instead throws a javascript error.

### Steps to Reproduce

1. In model use:
```
class MyDocument(AbstractDocument):
    content = RichTextField()
    (...)
```

2. Go to wagtail admin, content is not rendering as wysiwyg editor

![image](https://user-images.githubusercontent.com/3294841/151695577-ef98cbfe-4cf1-4a91-be85-095ab6c5543e.png)

### Technical details

* Python version: `3.8.1`
* Django version: `3.2.3`
* Wagtail version: `2.13`

**Comment by gasman** [comment]
I believe this was fixed in 2.13.3: #7268. When reporting bugs, please make sure you're testing against an up-to-date Wagtail version.
