### ISSUE TITLE
 Image has no corresponding size in media  folder

### ISSUE THREAD

**Issue by jhihwei** [wagtail/wagtail#7903]
### Issue Summary

image tag in template not work for fill-300x300 and fill-480x640 but fill-300x200 was work, 

I check the media folder that have no size of 300x300

Do I need to provide any information for reference?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.10
* Django version: 3.2.8
* Wagtail version: 2.15.1
* Browser version: Chrome 97

**Comment by zerolab** [comment]
Hey @jhihwei 

I'm afraid this is too little information to consider this a bug. Can you provide a minimum repeatable case? Are you seeing any errors in the logs?

Perhaps you should bring this question in the `#support` channel in the [Wagtail Slack](https://github.com/wagtail/wagtail/wiki/Slack) as it feels more of an implementation detail than a Wagtail bug.

**Comment by gasman** [comment]
The following issues seem possibly related, but the details don't quite match up...

* https://github.com/wagtail/wagtail/issues/6993 - ad blocker blocking certain image sizes (although this wouldn't stop the file from appearing in the media folder)
* https://github.com/wagtail/wagtail/issues/7766 - certain source image sizes failing to resize correctly under Wand (although in their case changing `max` to `fill` apparently fixed it)

**Comment by gasman** [comment]
Closing due to lack of update.
