### ISSUE TITLE
Remove `dateformat` library used in comments

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7904]
### Issue Summary

Our CommentHeader UI component [uses the `dateformat`](https://github.com/wagtail/wagtail/search?q=dateformat) library, even though it’s not declared in the project’s `dependencies`. I can see two issues here:

- Our dependencies should be declared in the package.json – not pulled from transitive dependencies. This should be enforced with ESLint, and will be once #7876 is merged.
- It’s expensive to load a dependency worth 5kb of JavaScript just for the single date format. We should consider using native browser APIs for this instead.

### Steps to Reproduce

Inspect the code at:

https://github.com/wagtail/wagtail/blob/cfadc59acc173ca5b3082192eda831d6548e4474/client/src/components/CommentApp/components/CommentHeader/index.tsx#L159

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

---

My preference would be to replace this with the [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) API, or any similar standard API compatible with our browser support targets. I don’t think we have to keep the exact same date format if it’s not readily available, although I assume it would be nice to not depart from it too much.

**Comment by lb-** [comment]
```
console.log(new Intl.DateTimeFormat([],{ dateStyle: 'medium', timeStyle: 'short' }).format(new Date()));
```
Outputs `1 Feb 2022, 7:30 am` in my locale, this should be dynamic based on the browser's locale also (passing an empty array to the first param)

**Comment by lb-** [comment]
PR coming
