### ISSUE TITLE
Wagtail 2.16 - Slim Sidebar cookie SameSite issue

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#7910]
### Issue Summary

* When collapsing the new slim sidebar, then refreshing, in Firefox 96 a warning appears advising that the cookie's SameSite attribute is incorrect.

### Steps to Reproduce

1. Open the bakerydemo running 2.16rc (or latest master)
2. Use Firefox 96 (or a recent version of Firefox)
3. Sign in to the CMS admin
4. Collapse the sidebar (to be small)
5. Refresh the page
6. Observe the browser console for a warning
<img width="1576" alt="Screen Shot 2022-02-02 at 7 58 39 am" src="https://user-images.githubusercontent.com/1396140/152058770-d15540b4-c008-46e6-87d6-61436c9f6ff7.png">

> Cookie “wagtail_sidebar_collapsed” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

* SameSite cookie info https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#samesitenone_requires_secure
* Wagtail version: 2.16rc
* Browser version: Firefox 96 on OS X 10.15 

## Potential Solution

* client/src/components/Sidebar/index.tsx https://github.com/wagtail/wagtail/blob/main/client/src/components/Sidebar/index.tsx#L34
* A. Set the sameSite attribute to Lax `sameSite: 'lax/Lax?`
* B. OR set the cookie to secure (however, this will cause issues in local development)
* https://github.com/js-cookie/js-cookie#samesite
* We could use localstorage but that does not provide a way for this to be set by the server which is not ideal

**Comment by Stormheg** [comment]
[I'm the one who originally wrote this code](https://github.com/wagtail/wagtail/commit/952264a2abffd1c01e08611bae26ceaf8d958d43#diff-d719062876b861b8f1447c4a9b0e58cb8e4079737e1632c2e6e190af0990e1a8R33) and never bothered to check the sameSite attribute 😅  
Thank you for noticing and taking the effort to raise this issue @lb- 👍 💯 

Setting the `sameSite` attribute to `lax` sounds like the way to go.

**Comment by lb-** [comment]
Epic thanks for taking a look @Stormheg
