### ISSUE TITLE
Replacing image with different image but same name crashes /admin/images

### ISSUE THREAD

**Issue by funkhaus-phil** [wagtail/wagtail#7913]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Replacing an Image at "/admin/images/[any-id]" with a different image named exactly the same as the original, creates the following error and crashes the whole "/admin/images" page:

```
NoSuchKey at /admin/images/
NoSuchKey: message: The specified key does not exist.

Request Method: GET
-- | --
http://admin.hotel-neptun.de/admin/images/
3.1.13
NoSuchKey
NoSuchKey: message: The specified key does not exist.
/usr/local/lib/python3.8/site-packages/minio/api.py, line 2226, in _url_open
/usr/local/bin/python
3.8.11
['/app',  '/usr/local/bin',  '/usr/local/lib/python38.zip',  '/usr/local/lib/python3.8',  '/usr/local/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/site-packages']
Wed, 02 Feb 2022 15:09:18 +0100

Error during template rendering In template /usr/local/lib/python3.8/site-packages/wagtail/images/templates/wagtailimages/images/results_image.html, error at line 18
```

### Steps to Reproduce

In advance, the critical part of this bug is that i can only reproduce it in production stage. The dev stage works fine and as expected. I know our setup is quite specific, but i hope you can still help us identifying the problem and come up with a solution.
1. Create a new instance of a fresh wagtail project in production stage
  1.1 Set up a Server, get caprover running https://caprover.com/docs/get-started.html
  1.2 Create a new app [projectname] in caprover
    1.2.1 Add the neccessary env variables (provided in screenshot section tagged **env_vars**)
    1.2.2 dont miss minIO credentials and database credentials as env vars
  1.3 Create a production stage mysql database, collation: utf8mb4_unicode_ci
  1.4 Set up minIO https://docs.min.io/docs/minio-quickstart-guide.html
  1.5 create a storage container "[projectname]-media"
2. Start a new wagtail project
```
mkdir [projectname]
cd [projectname]
python3 -m venv env
source mysite/env/bin/activate
pip install wagtail
wagtail start mysite [projectname]
```
3. Edit requirements.txt (provided in files section tagged **requirements.txt**)
4. Edit mysite/settings/base.py and mysite/settings/production.py (provided in files section tagged settings)
5. Create a new git repository [projectname]
6. Init git in Projectfolder and connect remote url
  6.1
```
cd project_folder
git init
git remote add origin ssh://git@code.funkhaus.io:2222/funkhaus/wagtail-test.git
```
7. Edit Dockerfile (provided in files section tagged Dockerfile)
8. Add start.sh to /[projectname] (provided in files section tagged start.sh)
9. Add captain-definition to /[projectname] (provided in files section tagged captain-definition)
9. Edit .gitignore (provided in files section tagged gitignore)
10. Install requirements local once to see if the installation works
`pip install -r requirements.txt`
11. Commit project to git repo
```
git add .
git commit -m "Initial commit"
```
12. install caprover on your mashine
`npm install -g caprover`
13. Deploy the Project
`caprover deploy`
  13.1 provide the information to your just setup server and to wich app you want to deploy
14. create superuser
```
ssh to root@[server-ip]
docker ps
```
  copy the cointainer id of the app with [projectname]
```
docker exec -it [container-id] /bin/bash
python3 manage.py createsuperuser --settings=mysite.settings.production
```
  provide username, password and repeat password
15. log into the admin (adress can be found in the the caprover app)
16. navigate to images
17. upload an image (in our case banner.jpg)
  17.1 check file storage for the new image (good)
18. navigate back to images again
19. click on the uploaded image
20. change image file
  20.1 select a different image from another path with the exact same name banner.jpg or hotswap the name before you upload
  20.1 save
21. /admin/images shows the error provided int the introduction
22. check filestorage again (original image was deleted, new image is missing)
23. check database wagtailimages_images table and wagtailimages_renditions table

**now you will find the entry for the image in wagtailimages_images but no entries in wagtailimages_renditions
deleting the entry in wagtailimages_images will fix /admin/images again, so you can reproduce the error over and over again**

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
I expected the image to be replaced, but got the whole site "/admin/images" in the admin not working anymore.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)
yes, but django-minio-storage is added and connected
and if overread, the error occurs only in production stage
seems like turning debug off/on doesnt change the behaviour

### Technical details

* Python version: 3.8
* Django version: 3.2.12
* Wagtail version: 2.15.3
* mysqlclient version: 2.1.0
* django-minio-storage version: 0.3.10
* Browser version: Chrome 97

### Screenshots
env_vars
![Bildschirmfoto 2022-02-02 um 18 43 57](https://user-images.githubusercontent.com/74963047/152208382-44b45adb-4f6d-4d3f-a498-803f3608d44b.png)

### Files
Dockerfile contents (filetype not supported)
```
FROM python:3.8-alpine

RUN apk add --no-cache \
	build-base py-pip jpeg-dev zlib-dev python3-dev \
	bash linux-headers pcre-dev \
	mariadb-dev mariadb-client

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir uwsgi mysqlclient gunicorn
RUN pip install --no-cache-dir --use-deprecated=legacy-resolver -r /requirements.txt

RUN mkdir -p /app
RUN mkdir -p /usr/src/static
RUN mkdir -p /usr/src/data

COPY ./ /app
WORKDIR /app

ARG DB_HOST=${DB_HOST}
ARG DB_PASSWORD=${DB_PASSWORD}
ARG MODULE_NAME=${MODULE_NAME}
ARG VARIABLE_NAME=${VARIABLE_NAME}
ARG DEBUG=${DEBUG}
ARG ALLOWED_HOSTS=${ALLOWED_HOSTS}
ARG EMAIL_HOST=${EMAIL_HOST}
ARG EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
ARG MINIO_STORAGE_ENDPOINT=${MINIO_STORAGE_ENDPOINT}
ARG MINIO_STORAGE_ACCESS_KEY=${MINIO_STORAGE_ACCESS_KEY}
ARG MINIO_STORAGE_SECRET_KEY=${MINIO_STORAGE_SECRET_KEY}
ARG WAGTAIL_SITE_NAME=${WAGTAIL_SITE_NAME}
ARG BASE_URL=${BASE_URL}

EXPOSE 80

RUN chmod +x start.sh
ENTRYPOINT ["./start.sh"]
```

start.sh contents (filetype not supported)
```
#! /usr/bin/env bash
# Run collect static and migrations
python manage.py collectstatic --noinput --settings=mysite.settings.production
python manage.py migrate --settings=mysite.settings.production
gunicorn mysite.wsgi:application --access-logfile=- --error-logfile=- -w 4 -t 120 --bind 0.0.0.0:80
```

gitignore contents (filetype not supported)
```
.DS_Store
*.pyc
__pycache__
# home/migrations/*
!home/migrations/__init__.py
media/
static_files/
__MACOSX
tmp/
env
```

requirements
[requirements.txt](https://github.com/wagtail/wagtail/files/7988751/requirements.txt)

base.py contents (filetype not supported)
```
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)

ALPHACODE = "wagtail-test"
SECRET_KEY = os.environ.get('SECRET_KEY', '')
WAGTAILAPI_LIMIT_MAX = None
WAGTAILIMAGES_MAX_UPLOAD_SIZE = 50 * 1024 * 1024 # i.e. 50MB
WAGTAIL_ENABLE_UPDATE_CHECK = False

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'home',
    'search',
    'minio_storage',

    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',

    'modelcluster',
    'taggit',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': os.environ.get('DB_DATABASE', ALPHACODE),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, 'static'),
]

# ManifestStaticFilesStorage is recommended in production, to prevent outdated
# JavaScript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
# See https://docs.djangoproject.com/en/3.1/ref/contrib/staticfiles/#manifeststaticfilesstorage
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'


STATIC_URL = '/static/'
STATIC_ROOT = './static_files/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

WAGTAILDOCS_SERVE_METHOD = "direct"

DEFAULT_FILE_STORAGE = 'minio_storage.storage.MinioMediaStorage'


MINIO_STORAGE_ENDPOINT = os.environ.get('MINIO_STORAGE_ENDPOINT', '')
MINIO_STORAGE_ACCESS_KEY = os.environ.get('MINIO_STORAGE_ACCESS_KEY', '')
MINIO_STORAGE_SECRET_KEY = os.environ.get('MINIO_STORAGE_SECRET_KEY', '')
MINIO_STORAGE_USE_HTTPS = True
MINIO_STORAGE_MEDIA_BUCKET_NAME = ALPHACODE + '-media'
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
MINIO_STORAGE_MEDIA_USE_PRESIGNED = False


# Wagtail settings

WAGTAIL_SITE_NAME = os.environ.get('WAGTAIL_SITE_NAME', 'mysite')

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
BASE_URL = os.environ.get('BASE_URL', '')
```

production.py contents (filetype not supported)
```
from .base import *
import os
import json


DEBUG = os.environ.get('DEBUG', "False") == 'TRUE' or os.environ.get('DEBUG', "False") == 'True'

try:
    from .local import *
except ImportError:
    pass
```

**Comment by gasman** [comment]
Hi @funkhaus-phil - thanks for the report.

We often find that third-party Django storage backends don't implement the [`get_available_name`](https://docs.djangoproject.com/en/4.0/ref/files/storage/#django.core.files.storage.Storage.get_available_name) method correctly, and silently overwrite existing files instead of returning a unique name. In the case of django-storages it's possible to set `AWS_S3_FILE_OVERWRITE = False` to obtain the correct behaviour, but unfortunately it looks like django-minio-storage [doesn't currently have an equivalent](https://github.com/py-pa/django-minio-storage/issues/78) - this means Wagtail can't support it as a backend until #4567 is resolved.

**Comment by funkhaus-phil** [comment]
Hello again. Thank you for the hints in the right direction on this one. You were completely right with your suggestion @gasman and since we had no time to wait on a guy who had not updated anything on the adapter for 2 years, we ended up fixing the known django-minio-adapter ourselfes.

If anyone else stumbles on this Problem, here is a quickfix to replace the original package for minio version 7+ (git, update history and an updated readme follows when i got the spare time on a weekend for it):
[django-minio-storage7plus](https://pypi.org/project/django-minio-storage7plus/)
