### ISSUE TITLE
Sidebar style updates

### ISSUE THREAD

**Issue by stevedya** [wagtail/wagtail#7919]
## Tasks
- Background colour change to wagtail's new primary colour
- Update top “expand” icon to match designs
- Move search icon left when sidebar is expanded
- Wagtail logo size decrease to circular when sidebar is in slim (collapsed) mode
- Change profile image to be circular
- Styling of account and logout links to match design
- Ensure colour constrast still meets WCAG 2.1 standard

## Acceptance criteria

- [ ] Matches Figma designs
- [ ] Works on all supported browsers

## Testing / review plan

**Comment by sumit-158** [comment]
Hi there, @thibaudcolas can I work on this?

**Comment by thibaudcolas** [comment]
@sumit-158 this is assigned to @stevedya
