### ISSUE TITLE
Performance issue when using a subclass of PagesAPIViewSet 

### ISSUE THREAD

**Issue by cnk** [wagtail/wagtail#7923]
### Issue Summary

After I deployed our site using `wagtail-2.16rc2`, the performance on the listing_view for our `NewsPagesAPIViewSet(PagesAPIViewSet)` went to hell. A query for a single page went from ~1 second on Wagtail 2.15.2 to over 3 minutes on Wagtail 2.16rc2. I eventually tracked this to the privacy check introduced in https://github.com/wagtail/wagtail/commit/c6b985770d0d67bdc5f1d8a9f60fa46c4156f7e5. This is looping over all 53k records in my pages table to do the checks. I am using an authenticated API because I do want my endpoint to return unpublished pages. But I did not anticipate needing to override get_base_queryset after this upgrade. 

### Steps to Reproduce

I am afraid I haven't had the time to make a demo of this behavior. 

### Technical details

* Python version:  Python 3.7.10
* Django version:  Django 3.2.11
* Wagtail version:  wagtail 2.16.0rc2 
* NewsPagesAPIViewSet is using `authentication_classes = [TokenAuthentication]`

**Comment by lb-** [comment]
PR that relates to the commit mentioned above https://github.com/wagtail/wagtail/pull/7385

**Comment by gasman** [comment]
Fixed in #7925
