### ISSUE TITLE
Bug to fix image rendition logging error not merged to 2.15

### ISSUE THREAD

**Issue by easherma** [wagtail/wagtail#7936]
### Issue Summary

Hey folks!

Looks like part of a fix for a bug introduced in 2.15 was fixed here in 2.16..but this commit should probably be patched to a 2.15 version as well. I think 

Change missing in 2.15x:
https://github.com/wagtail/wagtail/commit/db408ca37d86b301160b08636c26ad272edfe122

The original PR to fix the bug: 
https://github.com/wagtail/wagtail/pull/7694

The bug still existing in 2.15.3:
https://github.com/wagtail/wagtail/blob/26f85ab7d38780bd240be9007af1529dede12e59/wagtail/images/models.py#L314

### Steps to Reproduce

This broke some of our test coverage, but the problem is pretty clear in the code itself.

**Comment by gasman** [comment]
Thanks for reporting, @easherma! Looks like I probably used `git cherry-pick` to copy the fix from the main branch to stable/2.15.x, but missed the fact that there were two commits in the PR, and ended up only copying the second one - oops.

**Comment by RealOrangeOne** [comment]
The typo that keeps on giving :see_no_evil:

**Comment by gasman** [comment]
Merged in 0fd344d19c72ce7503da81f7a256dd71965f480d.
