### ISSUE TITLE
Image & document count on dashboard invalid due permissions while page count is correct

### ISSUE THREAD

**Issue by robmoorman** [wagtail/wagtail#7958]
### Issue Summary

Entering the CMS on the dashboard page shows invalid image & document counts.
This is confusing as you click on e.g. the image count you see no images (but tags are present also which doesn't make sense).

### Steps to Reproduce

1. Create multiple collections with images in it
2. Create a new users and group with limited persmissions to a single collection
3. Login in as that user and you will see the image (and document) count is invalid

### Technical details
- Python version: any
- Django version: any
- Wagtail version: any
- Browser version: Any supported browser

<img width="912" alt="Screen Shot 2022-02-11 at 10 21 48" src="https://user-images.githubusercontent.com/529396/153566291-f427515e-26d6-4e01-9113-2a5d760cf3e5.png">
<img width="1290" alt="Screen Shot 2022-02-11 at 10 21 42" src="https://user-images.githubusercontent.com/529396/153566298-085cd935-8512-4f4f-9922-4751ceab8daf.png">

**Comment by gasman** [comment]
Thanks @robmoorman! This was previously raised in #5129, but that was before [the image/document 'choose' permission](https://github.com/wagtail/wagtail/pull/6466) was implemented, which provides an answer to the problem raised there. The counts here should be updated to reflect the collections that they have any permission for, _including choose permission_ - ones with only choose permission won't show in the images / documents admin area, so there's still a possibility of confusion when users click through and see fewer images than stated, but it's less misleading than showing the full count across the whole system.

**Comment by robmoorman** [comment]
I agree @gasman thanks for the more detailed information. We are building quite some "multitenant/multisite" platforms a.t.m. we'll see if we can pick these fixes into our roadmap :).
