### ISSUE TITLE
Dynamic model at run time?

### ISSUE THREAD

**Issue by saileshkush95** [wagtail/wagtail#7974]
Thank you for this awesome project, But i think it is missing one features i.e dynamic model creations at run time, something like strapi.

**Comment by gasman** [comment]
Thanks for the suggestion! However, it's a deliberate design decision for Wagtail to not include this feature - see https://docs.wagtail.org/en/stable/getting_started/the_zen_of_wagtail.html#the-best-user-interface-for-a-programmer-is-usually-a-programming-language.
