### ISSUE TITLE
Table of contents generator (Based on Title, H1, h2, h3... headings)

### ISSUE THREAD

**Issue by sowinski** [wagtail/wagtail#7983]
Hi,

it would be very nice to have something to generate a table of contents within a page based on there title, h1, h2, h3... headings.

What do you think?

**Comment by lb-** [comment]
Hi @sowinski thanks for suggesting an idea.

It would be great to get a bit more context of what you mean;
* Do you mean within the page editor or within the public facing content?
* Also, what is the source of these headings (rich text editor or other fields)?
* Do you have a code example or even a mock up of what you are thinking?

Normally Wagtail does not provide too much in the way of rendering content for the public site. There are of course generic exceptions to this for things like embeds, basic streamblock rendering and bare HTML output from rich text fields.

However, a feature like this would have to make a lot of assumptions in regards to what heading levels to use, what format to output, injection of internal hrefs (if needed) and it may be better suited as an external package.

Nonetheless, please flesh out the idea a bit and maybe others can add their thoughts also.

**Comment by sowinski** [comment]
>> Do you mean within the page editor or within the public facing content?
Actually only the public facing content. But to manage a website with a lot of content it could be handy to have a table of content for each article within the page editor.

>> Also, what is the source of these headings (rich text editor or other fields)?
Both, there should be a kind of field in the model to specify which fields should be used to build the table of contents.
Another field should be used to define which html tags should be used for the table of contents. For example:
toc_lookup_fields = [ 'some_rhichtextfields', ...]
toc_tags = ['h1', 'h2', 'h3', 'img']

>> Do you have a code example or even a mock up of what you are thinking?
I started something on my own. Once I am done, I will share it here.

**Comment by lb-** [comment]
Thanks for the feedback, I think something like this is better served as an external package first.

Normally Wagtail tries to be agnostic when it comes to front/public facing content. This solution also needs to make lots of assumptions about how blocks are being used. 

I will close this for now and we can re-open if anyone disagrees. 

@sowinski if you do build something - I recommend maybe writing a blog post or even posting a GitHub Gist on this issue and others may be keen to build a package out of it. 

Also there is work planned to make a 'page navigator for the page editor' which should make it easier to work with large page editing experiences. 

See https://github.com/wagtail/wagtail/discussions/7739
