### ISSUE TITLE
Wagtail CMS admin does not show custom link handlers in RichText set by `wagtail_hooks.py`. 

### ISSUE THREAD

**Issue by rob101** [wagtail/wagtail#7991]
### Issue Summary

Wagtail CMS admin does not show custom link handlers in RichText set by `wagtail_hooks.py`. 

### Steps to Reproduce

Create a custom link handler, per the Wagtail docs:

myapp.handlers.py

```
    from django.contrib.auth import get_user_model
    from wagtail.core.rich_text import LinkHandler
    
    class UserLinkHandler(LinkHandler):
        identifier = 'user'
    
        @staticmethod
        def get_model():
            return get_user_model()
    
        @classmethod
        def get_instance(cls, attrs):
            model = cls.get_model()
            return model.objects.get(username=attrs['username'])
    
        @classmethod
        def expand_db_attributes(cls, attrs):
            user = cls.get_instance(attrs)
            return '<a href="mailto:%s">' % user.email

my_app/wagtail_hooks.py

    from wagtail.core import hooks
    from my_app.handlers import MyCustomLinkHandler
    
    @hooks.register('register_rich_text_features')
    def register_link_handler(features):
        features.register_link_type(LinkHandler)
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Expected behaviour

The new `user` identifier should show up in the PageLink chooser but [it does not](https://i.stack.imgur.com/U7AHd.png).

**Comment by gasman** [comment]
Thanks for the report - however, this is not part of `register_link_type`'s functionality. A link type handler only defines the mapping between the database representation of a link and the final HTML output - it doesn't provide any user interface support for actually inserting those links. [As the documentation notes](https://docs.wagtail.org/en/stable/extending/rich_text_internals.html#rewrite-handlers), "This example assumes that equivalent front-end functionality has been added to allow users to insert these kinds of links into their rich text editor." For that, you'll need to consult https://docs.wagtail.org/en/stable/extending/extending_draftail.html.

**Comment by TadeasFrycak** [comment]
@rob101 have you made a solution for that?
