### ISSUE TITLE
Remove IE11 warning message in Wagtail admin

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7993]
### Is your proposal related to a problem?

We still have our "Wagtail has removed support for IE11" warning message in the admin UI, even though Wagtail no longer supports IE11 since a few versions ago. I think it would be nice to remove it now.

### Describe the solution you'd like

We need to remove the block from the template: https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/skeleton.html#L79-L85

And also remove the `initIE11Warning` files, as well as the `IS_IE11` constant in our configuration.

**Comment by PushanAgrawal** [comment]
Hello , can I work on this issue?
