### ISSUE TITLE
Remove legacy sidebar implementation

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7995]
Based on recent discussions, we’re expecting Wagtail’s next release to be a major version bump, so I think this would be a good time to remove the legacy sidebar implementation.

This would involve:

- Removing the `Explorer` component including styles
- Removing `slim_sidebar_enabled`
- Removing `initSubmenus`
- Removing `_main-nav.scss` styles, and related styles 
- Moving `sidebar.scss`, making sure components defined there are moved to `core.scss`
- Removing the `branding_logo` customisation backwards compatibility code

**Comment by lb-** [comment]
When done this should hopefully resolve https://github.com/wagtail/wagtail/issues/7943

**Comment by lb-** [comment]
See - https://github.com/wagtail/wagtail/issues/8087
