### ISSUE TITLE
Normalize.css overrides the new font stack for some elements

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8016]
### Issue Summary

* A new font stack has been introduced via #7972 (using system fonts) - see also related #7724
* However, this font stack is not honoured by the more specific global font family on some elements set by normalize.css

### Steps to Reproduce

* Open a Wagtail instance, the test app or bakerydemo for example
* Open up the sidebar
* Look at the font on any link used (e.g. a direct link to images) and observe the font is the system font family
* Now look at any button also in the sidebar (to open as submenu like reports) and this is using the font family `sans-serif`
* Expected - the font families should be the same globally across all elements and inherit the body font family.

### Technical details

* Wagtail master (as at 19/02/2022 - 2.17a)
* Browser - Firefox 97 on macOS 11.6
* [normalize.css](https://github.com/wagtail/wagtail/blob/af942a27e41b47e257b6cd46c01a13cd381fed04/wagtail/admin/static_src/wagtailadmin/css/normalize.css#L90) contains 
```css
button, html, input, select, textarea {
  font-family: sans-serif;
}
```
which takes precedence over the font definition of the body (`Open Sans,Arial,sans-serif`). Take a look at this screenshot: 

_Originally posted by @thijskramer in https://github.com/wagtail/wagtail/issues/8015#issuecomment-1045961473_

## Recommended actions

* The usage of normalize.css is in review so it is possible we plan to remove it and replace it with our own version
* Otherwise we could add an override of normalize that sets the correct font-family on those elements.

### direct comparison - pages button vs pages link (sidebar)

The upper Pages is a `button`, the lower Pages is the `a` tag.

<img width="199" alt="154791877-b58fe10b-9487-4358-961c-ebce27ecfe4e" src="https://user-images.githubusercontent.com/1396140/154796571-2f714b86-417a-40a6-84a7-2d14f26cf7e9.png">

### full screenshots with css info

<img width="1578" alt="Screen Shot 2022-02-19 at 8 12 20 pm" src="https://user-images.githubusercontent.com/1396140/154796622-80e54f99-6aa8-4b57-9e60-feeba927b2a0.png">

<img width="1565" alt="Screen Shot 2022-02-19 at 8 00 27 pm" src="https://user-images.githubusercontent.com/1396140/154796630-b2eb4048-4df1-4151-ab9f-31f10d58e571.png">

<img width="1567" alt="Screen Shot 2022-02-19 at 8 00 15 pm" src="https://user-images.githubusercontent.com/1396140/154796635-0f0297b7-f16a-4008-a677-a81b4c631c5f.png">

**Comment by lb-** [comment]
@thibaudcolas fyi - in the context of discussions around normalize.css usage

**Comment by PaarthAgarwal** [comment]
@lb so should we remove these lines from normalize.css or add an override?
>button, html, input, select, textarea {
> font-family: sans-serif;
>}

**Comment by lb-** [comment]
I am pretty sure that will work, please do some research though - maybe some browsers still set this font and hence an override is still needed. The override could be inherit maybe. 

Also, it's possible that the normalize CSS will be removed in the near future. However, it's probably still good to fix this in case that does not happen for the next release.

**Comment by PaarthAgarwal** [comment]
Sure. I'll do

**Comment by Scotchester** [comment]
> I am pretty sure that will work, please do some research though - maybe some browsers still set this font and hence an override is still needed. The override could be inherit maybe.

@PaarthAgarwal, LB was right that just removing the rule doesn't fix it in all browsers. In Firefox, at least, the default browser style sets it to `system-ui`, resulting in a different incorrect font (San Franscisco, instead of Helvetica, on macOS Big Sur 11.6.4). I tested out the idea of using the `inherit` keyword and that seems to work well.

**Comment by PaarthAgarwal** [comment]
Thanks for the heads up @Scotchester.  I'll try it out as well.
