### ISSUE TITLE
Adding `q=...` to admin filtered image admin listing causes crash.

### ISSUE THREAD

**Issue by danthedeckie** [wagtail/wagtail#8029]
### Issue Summary

If you try to combine `?q=` search type URL with filtering by collection in the Image view, you get a crash. (`AttributeError at /admin/images/`)

```
  File "/Users/daniel/tmp/search-crash/.v/lib/python3.10/site-packages/wagtail/images/views/images.py", line 96, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/Users/daniel/tmp/search-crash/.v/lib/python3.10/site-packages/wagtail/images/views/images.py", line 67, in get_context_data
    images = images.filter(collection=self.current_collection)

Exception Type: AttributeError at /admin/images/
Exception Value: 'SQLiteSearchResults' object has no attribute 'filter'
```

(We have a client who wants to be able to search within an image collection, so were exploring options)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. `cd myproject`
2. `./manage.py migrate`
3. `./manage.py createsuperuser`
4. `./manage.py runserver`
5. http://localhost:8000/admin/images/?collection_id=1&q=1

Crash.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

* Python version: 3.8, 3.9, 3.10
* Django version: 3.2, 4.0
* Wagtail version: 2.15, 2.16.1
* Browser version: N/A
* Search backends: SQLLite, Postgres (database backend) and ElasticSearch backends all have this.

e.g:
```
'SQLiteSearchResults' object has no attribute 'filter'
```
```
'Elasticsearch6SearchResults' object has no attribute 'filter'
```
```
'PostgresSearchResults' object has no attribute 'filter'
```

**Comment by lb-** [comment]
My guess is it's this line. 

https://github.com/wagtail/wagtail/blob/main/wagtail/images/views/images.py#L56

We could add some checks to ensure the q GET Param has a value here before trying to build the search query results.

**Comment by ParitoshKabra** [comment]
can i work on this issue as a starter task? @lb-  😅

**Comment by lb-** [comment]
Go for it. Nothing stopping you or anyone picking up a bug to fix. @ParitoshKabra 

I would recommend for something like this you start with the unit test, sometimes finding where to add a test can be tricky and PRs must come with a test to ensure won't break this again in the future.

**Comment by ParitoshKabra** [comment]
I had a doubt @lb- , the image search which is there in the attached small video, is it intended to always search in all collections? That is, when we pick a collection and then perform a search, even then the search page gets refreshed and it searches against all collections. As a part of this issue, shall that also be changed?





https://user-images.githubusercontent.com/76113183/157580102-594d0159-6905-4987-bcb1-4fc3d3b12067.mov

**Comment by ParitoshKabra** [comment]
Also one more thing, when we search for an image, we need to actually add its complete name, shouldn't it be some `startsWith` type of a thing?

**Comment by lb-** [comment]
Thanks for digging into this @ParitoshKabra 

1. The search losing the collection is a known issue - https://github.com/wagtail/wagtail/issues/4073 (feel free to investigate)
2. Search indexing by default is basic, it depends on the search backend used.  https://docs.wagtail.org/en/stable/topics/search/backends.html - I'm not very skilled in the search area though so maybe that could also be improved

There is also this issue that may be related. https://github.com/wagtail/wagtail/issues/3746
