### ISSUE TITLE
The interpreter does not appear in VSCode

### ISSUE THREAD

**Issue by buhosiliscodirococo** [wagtail/wagtail#8034]
### Issue Summary

When doing the "Your first Wagtail site" tutorial I had the same problem on several attempts, and that is that I cannot set the interpreter of the virtual environment created with the command that wagtail delivers. That makes me unable to use autocomplete and VS code drives me crazy showing me errors in the errors tab.

The only "patch" solution I could find was the one mentioned at the beginning of this post, which uses pipenv
[pipenv for function/code completion](https://gist.github.com/kevinhowbrook/d2f1ff081a437da4156fc6742a424c2a)

with "Create and activate a virtual environment" step, it just doesn't show up in VScode.

### Steps to Reproduce

1. python3 -m venv mysite/env
2. source mysite/env/bin/activate
3. and it doesn't show up in VScode

I don't know if it's a VScode or Wagtail bug, but I would like to know if the only solution to that is to use pipenv or am I doing something wrong?

thanks

### Technical details

* Python version: Python 3.10.2
* Django version: 4.0.2
* Wagtail version: 2.16.1

**Comment by gasman** [comment]
Closing this as VSCode configuration is out of scope for Wagtail, but you may be able to get further pointers from people on [our support channels](https://docs.wagtail.io/en/stable/support.html).
