### ISSUE TITLE
Add Go Back button in Redirects (breadcrumbs)

### ISSUE THREAD

**Issue by aliceni81** [wagtail/wagtail#8037]
I found that there is no way to go back to the Redirect listing page when adding/editing redirection, except by clicking "Redirects" in "Settings" on side bar menu.
![image](https://user-images.githubusercontent.com/81170508/155470581-4ff61d0a-6134-46cb-8f17-e66a5dbc3643.png)

**Comment by gitkaarma** [comment]
@aliceni81 @zerolab I am interested to contribute to this issue. Can you please guide me how to approach this issue as I am new to the codebase.

**Comment by zerolab** [comment]
I set out to provide some instructions on doing this and realised that we don't really have "go back" button or anything else anywhere but pages doing destructive actions (i.e. delete confirmation pages). As such I think this needs a wider interface decision.

@gitkaarma as for contributing, please see https://docs.wagtail.org/en/stable/contributing/index.html on how to set up Wagtail for development. Create a fork of the Wagtail repository and for each feature that you work on, create a branch of the `main` branch.

As for any issue you work on, first find it in the UI/replicate it locally, then find the relevant bit in code and take it from there. If it is a backend-specific issue, starting with a test that replicates the issue is always a good start.

**Comment by thibaudcolas** [comment]
@aliceni81 thank you for the suggestion! This strikes me as something that could be solved everywhere in Wagtail with a breadcrumb, rather than a "back" button.

Can you expand upon why this would be important for redirects in particular?

**Comment by aliceni81** [comment]
@thibaudcolas Actually its not only important for redirects, but also for other models shown in Wagtail admin settings, like users, groups, sites and so on.

**Comment by lb-** [comment]
https://github.com/wagtail/wagtail/issues/8767 created to solve for the generic case of this now that breadcrumbs have been cleaned up via https://github.com/wagtail/wagtail/issues/8645

**Comment by lb-** [comment]
As of Wagtail 4.0 - the concept of 'back' buttons or similar in Wagtail has been adopted for Snippets and is now an 'approved' usage via breadcrumbs.

https://github.com/wagtail/wagtail/issues/8767  will need to be implemented ideally before this is picked up but I have now removed the 'needs design decision'.

**Comment by KaluBuikem** [comment]
# Return Button for redirect Pages

A use case of where a return button would be needed. After the upload of an image, there is no way of going to the previous page without clicking on the images tab


![Screenshot of the Use case of this ticket on the images pagel](https://user-images.githubusercontent.com/67438668/196906773-8568087e-78a5-4776-b665-1843e4fd70de.png)

**Comment by laymonage** [comment]
Tried looking into this in #10884 but just noticed that the views code still uses function-based views. If someone wants to work on this, ideally the views should be refactored to use the generic model views (and potentially wrapped in a `ModelViewSet` subclass). Then adding the breadcrumbs shouldn't be too hard, following the examples seen in that PR.

**Comment by uju-juelle** [comment]
I would love to work on this as I have the knowledge required for it @aliceni81 @laymonage

**Comment by lb-** [comment]
There is now a PR up for moving redirects to class based views.

https://github.com/wagtail/wagtail/pull/11035


There's also still a bit of discussion happening about when to use Breadcrumbs/back buttons and when not to. 

I'd recommend this issue not be picked up by new contributors for now until there is a solid guideline as to when we want to use these navigation patterns. See https://github.com/wagtail/wagtail/pull/10915 for context.

**Comment by thibaudcolas** [comment]
This has been implemented [in Wagtail 6.1](https://docs.wagtail.org/en/stable/releases/6.1.html#universal-listings-continued).

**Comment by laymonage** [comment]
The breadcrumbs are still missing for the "add" view, but the view code needs to be refactored to CBV first. I guess we can leave this closed in favour of the views listed in https://github.com/wagtail/wagtail/issues/8365#issuecomment-2061032553.
