### ISSUE TITLE
Allow specifying a custom base URL when registering ModelAdmin

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#8038]
### Is your proposal related to a problem?

Prompted by https://stackoverflow.com/q/71248504/1853523, where a user set up ModelAdmin for a model in an app named 'users', which resulted in it registering URLs under `/admin/users/` that clashed with Wagtail's own URLs from `wagtail.users`. It seems that there's currently no straightforward way to customise the URL path that ModelAdmin registers - you need to override AdminURLHelper instead.

### Describe the solution you'd like

ModelAdmin could support a `base_url_path` option, e.g.

    class BookAdmin(ModelAdmin):
        model = Book
        base_url_path = 'library'  # make URLs appear under `/admin/library/` instead of `/admin/myapp/books/`

This could be implemented as follows:

* Extend `wagtail.contrib.modeladmin.helpers.url.AdminURLHelper.__init__` to accept an optional `base_url_path` keyword argument
* In `_get_action_url_pattern`, use this to build the URL string, falling back on `{app_label}/{model_name}` if not specified
* Update `wagtail.contrib.modeladmin.options.ModelAdmin` to add `base_url_path` to the list of config attributes, and pass this on when initialising `self.url_helper`. Note that we need to deal with the possibility that a user might have created a subclass of AdminURLHelper in their own code and overridden `__init__`, as in this case their code won't know about the new argument - I'd suggest using [`accepts_kwarg`](https://github.com/wagtail/wagtail/blob/e2b30c1690fb231abbb2e896e5553119db24cf8b/wagtail/core/utils.py#L166) to check this before calling it, and outputting a deprecation warning if it doesn't. We can then remove that extra check in a future release.
* Add tests and documentation

**Comment by Nawarrr** [comment]
Can I work on this ? 
It would be my first contribution

**Comment by gasman** [comment]
@Nawarrr Yes, go ahead!

**Comment by Nawarrr** [comment]
I have a little question regarding accepts_kwarg, I'm not sure where exactly I should be checking before calling it, but that's what came up to my mind, the 
`    def get_url_helper_class(self):
        if not accepts_kwarg(AdminURLHelper.__init__, 'base_url_path'):
            raise DeprecationWarning("AdminURLHelper.__init__ is Depricated")
            
        if self.url_helper_class:
            return self.url_helper_class
        if self.is_pagemodel:
            return PageAdminURLHelper
        return AdminURLHelper
`
this is the line where self.url_helper is initialized 
`
self.url_helper = self.get_url_helper_class()(self.model , self.base_url_path)
`
I'm new to opensource, sorry if It's supposed to be obvious

**Comment by Nawarrr** [comment]
I have a little question regarding accepts_kwarg, I'm not sure where exactly I should be checking before calling it, but that's what came up to my mind, the 

```
def get_url_helper_class(self): 
        if not accepts_kwarg(AdminURLHelper.__init__, 'base_url_path'):
            raise DeprecationWarning("AdminURLHelper.__init__ is Depricated")
        if self.url_helper_class:
            return self.url_helper_class
        if self.is_pagemodel:
            return PageAdminURLHelper
        return AdminURLHelper
```

this is the line where self.url_helper is initialized 

`self.url_helper = self.get_url_helper_class()(self.model , self.base_url_path)`

I'm new to opensource, sorry if It's supposed to be obvious

**Comment by gasman** [comment]
The `accepts_kwarg` check would go just before we create the AdminURLHelper instance, to make sure the constructor actually accepts the arguments we want to pass it. So, the line `self.url_helper = self.get_url_helper_class()(self.model , self.base_url_path)` would become something like:

    url_helper_class = self.get_url_helper_class()
    # make sure the url_helper_class constructor accepts a base_url_path argument before we call it
    if accepts_kwarg(url_helper_class, 'base_url_path'):
        self.url_helper = url_helper_class(self.model, base_url_path=self.base_url_path)
    else:
        warn(
            "%s.__init__ needs to be updated to accept a base_url_path keyword argument" % url_helper_class.__name__,
            category=RemovedInWagtail219Warning
        )
        # fall back to calling the old signature, so that we're not breaking existing code
        self.url_helper = url_helper_class(self.model)

**Comment by vupham04** [comment]
Hi, because @Nawarrr hasn't commented in 2 weeks, so I have worked on this issue and come up with a solution.

1. About the tests, I'm thinking about editing a Model in wagtail\test\modeladmintest\wagtail_hooks.py to include base_url_path, and then in wagtail\contrib\modeladmin\tests\test_modeladmin_edit_handlers.py, in response = self.client.get(...) for the appropriate model, I will edit the URL there to fit base_url_path. Is it okay?

2. For documentation, in [ModelAdmin](https://docs.wagtail.org/en/latest/reference/contrib/modeladmin/index.html#want-to-know-more-about-customising-modeladmin), should we create a sub-page for customizing base URL, or can I just add it to the [Additional tips and tricks](https://docs.wagtail.org/en/latest/reference/contrib/modeladmin/tips_and_tricks/index.html)?

Should I still create a pull request without tests and documentations, and amend it later?
