### ISSUE TITLE
MultipleImagesPanel conflicts with the custom structblock.

### ISSUE THREAD

**Issue by JerryLin2022** [wagtail/wagtail#8040]
This is a bug in MultipleImagesPanel , which conflicts with the custom structblock.

`class InlineVideoBlock(blocks.StructBlock):
    caption = blocks.CharBlock(required=True, label=_("视频标题"), max_length=64)
    url = URLBlock(required=True, label=_("视频网址"), max_length=256)
    cover = ImageChooserBlock(label="视频封面", required=True)
    intro = blocks.CharBlock(required=False, label=_("视频说明"), max_length=128)

    class Meta:
        icon = 'media'

class UserHomePage(Page):
    parent_page_types = ["home.HomePage"]
    subpage_types = ["home.BlogPostPage"]
    intro = models.CharField("一句话简介", max_length=256, blank=True)
    template = models.CharField(verbose_name="显示风格", db_column="template", default="default", max_length=150,
                                choices=get_template_choise())
    headimg = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
        verbose_name="头像"
    )
    edubackground = RichTextField("教育背景", blank=True, features=RichTextField_Features)
    special_intro = RichTextField("自我介绍", blank=True, features=RichTextField_Features)

    addr = models.CharField("联络地址", max_length=256, blank=True)
    tel = models.CharField("联络电话", max_length=256, blank=True)
    wechat = models.CharField("微信", max_length=256, blank=True)
    qq = models.CharField("QQ", max_length=256, blank=True)
    email = models.CharField("email", max_length=256, blank=True)
    others = RichTextField("其他联络方式", blank=True, features=RichTextField_Features)

    stream_body = StreamField([
        ('video', InlineVideoBlock(label="公开的视频")),
        ('document', DocumentChooserBlock(label="公开的文档")),
        ('url', InlineUrlBlock(label="公开的链接")),
    ], verbose_name="更多设置", blank=True)

    search_fields = Page.search_fields + [
        index.SearchField('intro'),
        index.SearchField('edubackground'),
        index.SearchField('special_intro'),
        index.SearchField('stream_body'),
    ]

    content_panels = Page.content_panels + [
        FieldPanel('template', classname="full"),
        MultiFieldPanel([
            ImageChooserPanel('headimg'),
            FieldPanel('intro', classname="full"),
            FieldPanel('edubackground'),
            FieldPanel('special_intro'),
        ], heading="我的简介"),
        MultiFieldPanel([
            FieldPanel('addr'),
            FieldPanel('tel'),
            FieldPanel('wechat'),
            FieldPanel('qq'),
            FieldPanel('email'),
            FieldPanel('others'),
        ], heading="联络方式"),
        MultipleImagesPanel("gallery_images", label="公开的图集", image_field_name="image"),
        StreamFieldPanel('stream_body'),
    ]`

![error](https://user-images.githubusercontent.com/100368228/155559170-c9e9aced-cd76-4e2d-a94d-5a8c5b1367d3.png)

When I remove the code related to MultipleImagesPanel , the cover image in the custom structblock will be displayed normally, and the error prompt of JS will disappear

**Comment by gasman** [comment]
Hi @JerryLin2022,
Wagtail does not provide a `MultipleImagesPanel`. If this is a bug in a third-party package, please report it there.

**Comment by JerryLin2022** [comment]
Yes, this is a third-party package, list on wagtail.io

> Hi @JerryLin2022, Wagtail does not provide a `MultipleImagesPanel`. If this is a bug in a third-party package, please report it there.
Yes it is a third-party package, list on wagtail.io
