### ISSUE TITLE
Wagtail monospace font

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8043]
This is a follow-up to #7724. We display things in monospace in quite a few places around the Wagtail world. The CMS itself supports `<code>` formatting in rich text, and some of our debugging code uses monospace. Outside the CMS, wagtail.org and the documentation display code snippets.

It’d be nice if we had an official "Wagtail monospace" font, at least to use in the CMS, and elsewhere as needed.

### Describe the solution you'd like

We should do this as a [system font stack](http://markdotto.com/2018/02/07/github-system-fonts/), like we did for the main branding font. We’d need to review a few existing implementations, decide as a group, and add the font to our [design tokens](https://github.com/wagtail/wagtail/blob/main/client/src/tokens/typography.js#L19).

### Describe alternatives you've considered

None

### Additional context

Related: #3864

---

Here are existing implementations I’d suggest looking at:

- GitHub
- Bootstrap
- Ant Design
- USWDS
- [Draftail](https://github.com/springload/draftail/blob/main/lib/api/constants.js#L62) (`Consolas, Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, sans-serif`).

**Comment by thibaudcolas** [comment]
Marking this as a `good first issue` because minimal knowledge of Wagtail is required – this is primarily a research task (find existing implementations, review them, compare, decide what to propose for Wagtail). The actual code changes needed will be very minimal.

**Comment by SuryanshBisht** [comment]
I would like to work on this issue to get started with contributing to wagtail

**Comment by devraj4522** [comment]
Hi, Can you please guide me how can I start working on it?

**Comment by thibaudcolas** [comment]
@SuryanshBisht cool! Please let me know if you have questions.

@devraj4522 looks like this is already taken.

**Comment by devraj4522** [comment]
Ok, I am looking for other issues, I want to pick a starting point to understand the codebase.

**Comment by thibaudcolas** [comment]
@SuryanshBisht how are you getting on with this?

**Comment by acnologia** [comment]
@lb- @thibaudcolas I've created a PR #8338

**Comment by lb-** [comment]
Resolved via 7861014316baed908e0773c7f80f65a78f7a877c  & https://github.com/wagtail/wagtail/pull/8338
