### ISSUE TITLE
Bulk actions for page listing introduces new UX issues

### ISSUE THREAD

**Issue by robmoorman** [wagtail/wagtail#8045]
### Issue Summary

Some UX feedback from our e2e tests.

Many of the content editors we see are using the bulk mode of the edited page instead of the listing pages.

They expect to be the checked listing pages to be deleted, but do often accidentally remove (although a confirmation is shown), move or copy a complete parent page(tree).

It's totally not clear for them the taken action is for the page on top rather than the selected items.
The bar on the bottom on the page is not noticed.

### Steps to Reproduce

1. Go to a listing page in the explorer
2. Tick some boxes for the child pages

<img width="1265" alt="Screen Shot 2022-02-25 at 15 37 33" src="https://user-images.githubusercontent.com/529396/155734217-92c2c9fc-01a7-47e3-99c2-700aaf499f25.png">

**Comment by robmoorman** [comment]
He @zerolab they want to delete the checked listing pages. They expect them to be removed but the delete (or copy, move) the parent page instead.

**Comment by zerolab** [comment]
Erm, I would have thought the action bar the appears at the bottom of the page when they tick at least one checkbox is prominent enough? 🤔

What would you suggest, from your editors point of view?

**Comment by robmoorman** [comment]
Njeh they don't notice I'see in quite some cases. They are focussed (and used) to have their tools on top. (I also didn't expect these issues but jeah we do a lot of Wagtail hahaha).

From their feedback they expect that the actions on top always apply to the checked items.
So the buttons in the header are to close to checked with makes them think it's related to each other, which is not.

More space between them (or with contrasts, the page actions for the parent in another box or so) would make this assumption go away (I know we don't want that we we want more space for editing the pages instead). But for a listing I give them right in some way...

Fyi most of the content editors are used to other platforms first, so wordpress, drupal, etc. I noticed that they all have their bulk actions on top. Which makes them expect this to be se same.

For example wordpress:
![bulk-editing-products-01](https://user-images.githubusercontent.com/529396/155737593-e898f128-617d-4569-be4f-cd46852644a1.png)

**Comment by zerolab** [comment]
cc @benenright @phildexter

**Comment by phildexter** [comment]
Yes I can see how this could happen easily. A way to resolve this would be to hide the buttons that relate to the parent page once you select any of the child pages - this would also help give focus to the action in hand.

**Comment by robmoorman** [comment]
Thanks @thibaudcolas
