### ISSUE TITLE
Make it possible to disable the slim mode of the new sidebar

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#8055]
### Is your proposal related to a problem?

As of 2.16, there is a "slim sidebar", with collapse/expand UI, which as of 2.18 will be the only option available without the option to force the sidebar to always be full expanded.

There are a few reasons why forcing users into a "thin sidebar" may be problematic.

1. accessibility: not everyone "registers" icons. For those folks, always showing actual text without forcing them to take extra steps is important.
2. accessibility: while by default all icons are distinct, this is _not_ true for folks with custom, additional sidebar options that use "the most appropriate icon" even if that icon is a duplicate of another option.
4. discoverability: some folks may be intimately familiar with their CMS options, but anyone who isn't (e.g. staff who only incidentally need to use the CMS) can immediately navigate their way to where they need to be, whereas a slim sidebar adds extra steps for -what feels like- a purely cosmetic gain.
5. usability: the UI elements for collapsing/expanding take up a fair bit of vertical sidebar real estate, and may trigger a menu scrollbar where there previously wasn't one. 

### Describe the solution you'd like

First and foremost, don't remove the `WAGTAIL_SLIM_SIDEBAR` env var, so that admins can ensure that the maximum amount of information is present in the sidebar. Note that this does not mean "keeping the _old_ sidebar", but means "making sure that if that var set to `False`, the sidebar generates with whatever CSS classes are necessary to start expanded, and the UI for collapsing it not loaded". 

If this variable _has_ to go, then this really ought to be a user preference tied to a user-account associated profile. Not a CMS-global setting. I'm sure there are users that like the look of a slim bar, and I would love to let them use the CMS with a slim sidebar if that works for them, but in a trade off between being able to do my job administering the CMS with as little friction, and a nice cosmetic update, I'm going to pick the former.

### Describe alternatives you've considered

If there is not going to be any way to control this in the future, then to at least make my job less frustrating I'll probably just duplicate the bits of the admin interface template that control the sidebar, with the slim bits removed, so that it always loads fully expanded without collapsing UI.

### Additional context

A change like this affects two user groups with completely different needs out of a CMS: users, who absolutely benefit from shiny compact themes, and admins, who absolutely don't and want as much and as clear information presented as possible. It feels like the sidebar controls have been improved with only the first group in mind. Which is understandable, but I'd like to make sure the second group's needs aren't forgotten.

**Comment by gasman** [comment]
This seems fair enough to me - there's an unwritten(?) design rule for Wagtail that we should aim to eliminate UI elements until the point where they're actually needed, so if indeed there's no possibility of the collapsible sidebar being useful to your editors, it's reasonable to remove that button.

If the proposed new behaviour of the setting flag is simply to remove the collapse option rather than to switch out the whole sidebar implementation, I'd suggest renaming it to something like WAGTAIL_SIDEBAR_COLLAPSE_ENABLED, and/or moving it into the appconf for the Wagtail admin app as we did for [customising the users app](https://docs.wagtail.org/en/stable/extending/customising_group_views.html#custom-edit-create-forms).

**Comment by jacobtoppm** [comment]
Personally, rather than keeping the setting (or moving it into appconf), I'd much rather see it become a per-user setting - this feels like a user preference for most of the issues above (reuse of icons aside, which can be easily prevented by just... not reusing menu icons). (Accessibility wise, the text should apparently be accessible just from tabbing through when using a screenreader from talking to @kaedroho)

That said, it should already remember collapsed/uncollapsed status in a cookie, so it sounds like if you're leaving it uncollapsed, the only difference between that and never collapsing would be that the arrow for collapsing is still shown.

**Comment by gasman** [comment]
I don't think a user preference makes sense here - if a user decides for themselves that they don't like the collapsing behaviour, they can simply not use it :-) There's no reason a user would seek out a setting to take an option away from themselves.

What I'm taking from @Pomax's request is that this is an executive decision made by the site owner, on the basis that having the button there at all is going to add visual clutter on a user's first experience of the Wagtail admin, and negatively affect their first impression.

**Comment by jacobtoppm** [comment]
> If this variable has to go, then this really ought to be a user preference tied to a user-account associated profile. Not a CMS-global setting. I'm sure there are users that like the look of a slim bar, and I would love to let them use the CMS with a slim sidebar if that works for them, but in a trade off between being able to do my job administering the CMS with as little friction, and a nice cosmetic update, I'm going to pick the former.

A lot of the reasons above seem pretty person-dependent to me- "not everyone "registers" icons. For those folks, always showing actual text without forcing them to take extra steps is important." for instance, or people who are familiar with the CMS vs not very familiar - rather than really site level issues. Personally, I think the remembering expanded state based on the cookie probably is sufficient for most people, but for people who never want to use the slim version even between sessions, I can see a user setting being useful. If the site setting turns out to be what people prefer, I'm not incredibly strongly against it, but the divides in @Pomax's issue seem pretty person-specific to me.

**Comment by Pomax** [comment]
> What I'm taking from @Pomax's request is that this is an executive decision made by the site owner, on the basis that having the button there at all is going to add visual clutter on a user's first experience of the Wagtail admin, and negatively affect their first impression.

No, it also impacts the day to day use of the CMS by people like myself. A UI element that isn't going to get used, but pushes meaningful content off the screen, is not a first-impression-only issue =)

I would fully back @gasman's idea of keeping the setting, but renaming it. A `WAGTAIL_SIDEBAR_COLLAPSE_ENABLED` that can be set to `False` (in lieu of being able to set this as a personal preference for a logged in user's personal settings, because it sounds like that's not where folks what this option to end up living) would certainly work for the day to day admin use of Wagtail in our case.

**Comment by lb-** [comment]
Just adding some thoughts. 

- Mobile view - not sure if it's a concern but just a reminder that on small device breakpoints the menu goes into 'hamburger' mode, when clicked it only shows the expanded mode. 
- Naming - I think whatever setting or approach we do we should err towards `menu` or `main_menu` as the naming, while sidebar is used in some docs, all hoooks and settings refer to it as the main menu. I think that our different naming of this as sidebar may have caused some confusion if someone is searching in the docs. 
- Setting or Hook - if we are implementing this and want to avoid a new settings, we could leverage a third Arg ok the `construct_main_menu` hook

```python
from wagtail.core import hooks

@hooks.register('construct_main_menu')
def keep_main_menu_collapsed(request, menu_items, menu_options):
  menu_options[`expanded`] = False

```
- https://docs.wagtail.org/en/stable/reference/hooks.html#construct-main-menu
- This approach can work both ways, always expanded, always collapsed and if not set auto (cookies based)

**Comment by thibaudcolas** [comment]
Couple things I want to note on the UX side:

- This is a moving target – we’re already planning UX changes to (partly) help with the issues reported here, #7918
- The main UX goal with this is to make more space for the side panels we’re introducing on the right-hand side of the page editor

**Comment by thibaudcolas** [comment]
Getting back to this as we’re almost ready to launch the revamped slim sidebar, I want to respond to a few more points:

> For those folks, always showing actual text without forcing them to take extra steps is important.

We’re not forcing anyone to use the slim mode of the sidebar. The sidebar shows expanded by default, if someone wants to use the slim version they’ve consciously made that choice (and can change it again at any point in time).

> usability: the UI elements for collapsing/expanding take up a fair bit of vertical sidebar real estate, and may trigger a menu scrollbar where there previously wasn't one.

Yes, on a 1024x768 viewport the legacy sidebar supports 11.6 menu items (text partly visible for the 12th but descenders are cropped), while the new sidebar supports 10.9 menu items (effectively 11, no cropping visible). In a previous iteration we had made the menu items smaller to allow the same amount without scrolling, but ended up backtracking on this.

> Naming - I think whatever setting or approach we do we should err towards menu or main_menu as the naming, while sidebar is used in some docs, all hoooks and settings refer to it as the main menu.

Not sure if this is a useful distinction but "sidebar" is the whole of the bar, while "main menu" refers to the scrollable area with links and sub-menu panels.

**Comment by gasman** [comment]
I'd tend to agree. Adding config options for UI details increases the maintenance burden and the number of permutations we have to consider when redesigning, and so it's only really justifiable if _the collapse mechanism itself_ is the thing causing problems for users. It sounds like the main objections here are about the knock-on effects, such as the difficulty of specifying distinct icons and the added vertical space taken up by the control - and those are things that can (and will) be addressed separately.

**Comment by thibaudcolas** [comment]
It’s been a month so I’ll now close this as something we’ll leave as-is, based on my and @gasman’s points. We can still revisit in the future if relevant.

On icons, it’s worth noting we have much better support for customisations in the upcoming Wagtail 5.0 release than ever before. After a dev reads through our [icons documentation](https://docs.wagtail.org/en/latest/advanced_topics/icons.html), I’d expect it’d take on the order of 10 minutes to add a new icon to their project from any arbitrary SVG icon set (or fully custom).

And for the vertical space, this is just exploratory at this stage but we’re considering optimising this by compacting the branding in the sidebar. Aside from this issue we’ve not really had much public discussion about Wagtail’s abilities to structure admin views in its main menu. Current design on the left, and compact version on the right:

![branding vertical space exploration](https://user-images.githubusercontent.com/877585/232052071-a7b7922a-23b5-4d57-bbb1-614703ba6f84.png)
