### ISSUE TITLE
`Site.get_site_root_paths()` Restricts Caching to Pickling or Memory

### ISSUE THREAD

**Issue by the5thbeatle** [wagtail/wagtail#8062]
### Issue Summary

`wagtail.core.models.Site.get_site_root_paths()` makes assumptions about the default cache, so using a Redis cache with JSON serializer leads to attribute errors. `wagtail.core.models.Site.get_site_root_paths()` returns type `list[list[int, str, str, str]]` instead of `list[SiteRootPath]` when loading from `cache`. This causes `wagtail.core.models.Page._get_relevant_site_root_paths()` to raise an exception.

When `get_site_root_paths()` is first called, the result is indeed a list of `namedtuple` objects, but subsequent calls return lists of lists.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Pin dependencies from technical details below
3. Add `django-redis` dependency to `requirements.txt` and install
4. Create superuser
5. Start a redis instance
6. Add the following to `mysite/settings/base.py`, replacing `REDIS_HOST`, `REDIS_PORT`, `REDIS_DB` for redis instance:
   ```py
   CACHES = {
       "default": {
           "BACKEND": "django_redis.cache.RedisCache",
           "LOCATION": "redis://REDIS_HOST:REDIS_PORT/REDIS_DB",
           "OPTIONS": {
               "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
           },
       }
   }
   ```
7. Attempt to sign in to admin site

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.9.7
* Django version: 3.2
* Wagtail version: 2.16

**Comment by Siburg** [comment]
Apologies for "me too" comment, but I just encountered this bug today when trying to upgrade wagtail from version 2.15. My first Googling of the issue led to this: https://stackoverflow.com/questions/74748261/issues-upgrading-from-wagtail-2-15-6-to-2-16-breaks-all-pages-except-home-page, so I'm not the only one. It is blocking me from upgrading, so I'm keen to see the PR from @jaap3 deployed in a next release.
