### ISSUE TITLE
Change sidebar (main menu) search input field into a menu item

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#8063]
# Current

In recent Wagtail the border and focus highlight of the search input disappeared. Is that on purpose?
<img width="1624" alt="Screenshot 2022-03-01 at 22 01 15" src="https://user-images.githubusercontent.com/1969342/156248516-c34e5733-9876-4bee-9e1e-36bfab036e1d.png">

This change made me review the search functionality. I noticed the following:
- The search result page has two search input fields. One in the sidebar and one in the header.
- A query entered in the sidebar is moved to the header on submit.
- The 'Pages' menu item is active, but the current page is 'Search'.
- Searching without a query yields an error message. But the contents of the result page is fine.
- The alignment of elements in the header need attention.
- The 'loop and search' combo appear twice. The loop in the input is redundant. The placeholder in the input might be "Pages, images, or other content".
- The submit button is not visible.

<img width="1624" alt="Screenshot 2022-03-01 at 22 23 22" src="https://user-images.githubusercontent.com/1969342/156251303-916a06f0-0190-42d2-9a14-62cbf4e8eb83.png">

# Suggestion

- Change the search input in the main navigation into a regular menu item.
- A click will open the search result page with focus on the input field.
- A empty search should not raise an error.
- The search menu item should have the active state.

The auto focus makes the effort to enter a search query the same as before: click, type, submit.

Mockups:

<img width="1624" alt="Screenshot 2022-03-01 at 22 01 04" src="https://user-images.githubusercontent.com/1969342/156248567-fcf4b87b-aa0f-4a4a-a535-b32bc3784519.png">

<img width="1624" alt="Screenshot 2022-03-01 at 23 07 13" src="https://user-images.githubusercontent.com/1969342/156256999-ae52094d-11c8-4d12-a32a-1b5c987ffcaf.png">

**Comment by lb-** [comment]
Adding some thoughts (posted in Slack already)
---

I think there are a few issues here
1. The empty query bug has been raised - https://github.com/wagtail/wagtail/issues/8029
2. The search input focus bug does not appear to be raised, maybe it is best to raise it in  isolation.
3. I have also made this suggestion which could help in customising the ordering of the menu in general and in theory could make it easier to remove/change the search field into a link in custom setups. https://github.com/wagtail/wagtail/issues/7960#issuecomment-1051311370I 


Personally think the field in the menu is nice and should be kept but I understand your rationale.

As an aside, I think the naming of it as Sidebar and not Menu makes it a bit hard to find issues, Python side calls it MainMenu and MenuItem and JavaScript side calls it Sidebar (but also mixed with MenuItem sometimes). Naming things is not easy but having multiple names for the same thing makes tickets/docs harder to find.

**Comment by thibaudcolas** [comment]
Adding to the list – personally I find it very confusing that the "Search" feature in the sidebar looks exactly like all other menu items, even though it’s actually a form. Here is the design shipping with Wagtail 3.0:

![search-form-design](https://user-images.githubusercontent.com/877585/165064132-d974332a-273c-406e-b835-4c0d49f3a428.png)

The part that trips me up in particular is the icon - there’s no indication that it’s a button, and clicking this will start a relatively expensive search that retrieves all pages of the site, while showing the error message "Field is required".

**Comment by thibaudcolas** [comment]
We’ve discussed this in the weekly page editor design review meeting with @benenright and @phildexter. We’re quite keen to replace the search field with a link, for the following reasons:

- Visually in the latest design, the form looks identical to other menu items. So it’s odd it behaves differently.
- Having the form’s "Submit" button to the left helps with the scan-ability of the menu items, but makes the button hard to identify as such.
- A link resolves the "active menu item" issue mentioned by Coen
- A link will make it clearer what the search is currently operating on – in the current model, the search is entered in a single form, whereas from the functionality on the page it’s actually only pages that are being searched.
- A link also resolves the behavior of the sidebar in slim mode – on click, the sidebar can remain slim, rather than having to move back to expanded.

This last point is important – right now both the search form and the "Account" sub-menu cause the collapsed sidebar to expand. This feels a bit jarring for end users – who presumably would rather always keep it in slim mode if that’s what they chose. So we’d also look into replacing the "Account" sub-menu with a single link to the user’s profile edit view (the logout form would also be moved to this view).

**Comment by thibaudcolas** [comment]
Marking this as "Needs Design Decision" alongside #8474 so we collate more feedback on this.

**Comment by Scotchester** [comment]
While I appreciate the current issues with the design, I think it would be disappointing to not be able to search from anywhere in the admin without a page load to get to the search page. I feel like searching from a field on every page in the admin is pretty core functionality in any kind of application like this.

My preference would be to restore the design of the Search item in the sidebar to something looking more like a search field and less like a regular menu item.

Regarding knowing what the search is currently operating on, I think it would be nice to change the design of the results page such that it would display the top results for any type of content being searched, and then you could filter down to only one particular type of content if you wanted. Or perhaps it could default to pages if you search from within the explorer, images if you search from within the image library, etc.

As for the potentially-jarring behavior of search expanding the collapsed sidebar, perhaps it could instead pop up a small modal with the search field in it?

I recognize that those last two items would take significant additional work beyond addressing the styling concerns, but if this is targeting 4.0, maybe we have time for that. If not, restoring a more field-like look to the Search sidebar item seems like a reasonable approach that at least maintains the behavior long-time users expect out of that search field.

**Comment by allcaps** [comment]
This is one of these issues that has a lot of pros and cons. The extra page load is certainly not nice. But I agree with @thibaudcolas that the proposed changes will solve the most issues.

I always found a double search input (in the menu and on the search result page) weird and confusing. Especially because the search result page input field has live search (direct search without pressing enter) and the input in the menu has not.

If we would make the item open a search dialog/overlay on the current page, we speed up the interface and have a single search input, with live search!

I like @Scotchester s suggestion that this also allows to take the current context into account. For example, search in this section that would reveal only the descendant pages of the current page.

**Comment by allcaps** [comment]
We have discussed this issue in the core team meeting.

- Thanks to everybody who contributes to the discussion.
- We like to give people time to respond to this issue.
- There is consensus that a full page load before search is undesirable.

We where with a small group and will put it on the agenda for next week.

**Comment by lb-** [comment]
I would also like to suggest we keep the field input, it does create a few UI headaches to work around but provides a much better experience in my opinion.

Clicking search and then having to type in the field (even if the focus is taken directly to the field on load) feels a bit jarring to me.
