### ISSUE TITLE
unpublishing a page does not clear the publication date fields

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#8066]
### Issue Summary

When unpublishing a page, wagtail does not seem to clear the "first published at" field, even though the act of unpublishing should "void" this fields. There is no publication anymore, only a draft page.

This leads to the undesirable situation where if a page is moved from draft to published (not "re"published - drafts are just drafts) a few weeks later, the "first published at" date isn't the day and time of publication, but a very wrong date in the past.

### Steps to Reproduce

1. Run any test db
2. Load any page that shows the first_published_at date/time 
3. In the admin, unpublish that page, then republish the page
4. Reload the live page, and notice that its first_published_at information hasn't changed at all.

### Technical details

* Wagtail version: 2.16 and every version below as far as I know.

**Comment by tbrlpld** [comment]
@Pomax had pointed out (please correct me if I am wrong) that pages are often unpublished to "redefine" the content. In this case, the new content would be published for the first time, which then would make sense to clear the `first_published_date`. 

My response to that was that the page does not have a concept of the content and can therefore not differentiate when the content is "updated" (e.g. fixing a typo) vs. "redefined" (e.g. writing about different subjects). In case of redefining content, it would seem more appropriate to create a new page (potentially from a copy). This page will start in a "unpublished" state and will be first published when the new content is ready. This would be reflected in the `first_published_at` field. 

So it seems that adjusting the workflow could remedy this as an issue.

**Comment by gasman** [comment]
By a literal interpretation of "first published at", Wagtail is doing the right thing (if I'm not mistaken), and there will certainly be users expecting that behaviour to continue working that way. If you have a workflow where a page that's unpublished and then published with new content is not considered the same page, then that's a customisation (and one that I think you could do quite easily with a [`page_unpublished`](https://docs.wagtail.org/en/stable/reference/signals.html#page-unpublished) signal).

The `first_published_at` field is not editable out of the box, but can be made editable by [adding it as a panel](https://github.com/wagtail/wagtail/pull/3498#issuecomment-308403159) - so I think all bases are covered.

**Comment by Pomax** [comment]
We do have that value in a settings panel already, and I was able to change it, so after checking with our staff it turns out that they were updating the first_published_at date of a different page without realising, and reporting a problem with the data not changing based on that. So: this issue isn't actually an issue and I'll close it =)
