### ISSUE TITLE
Change documentation website Markdown parser from recommonmark to MyST

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8074]
We added support for Markdown in our documentation between January and March last year, using [recommonmark](https://recommonmark.readthedocs.io/en/latest/), which unfortunately got deprecated a few months later, in favour of [MyST](https://myst-parser.readthedocs.io/en/latest/).

- Here are the [official Sphinx + Markdown docs](https://www.sphinx-doc.org/en/master/usage/markdown.html).
- And [further details of how this happened](https://github.com/readthedocs/recommonmark/issues/221).

I think we should switch to MyST – recommonmark had plenty of rough edges, which will hopefully have been addressed in this alternative, which seems to have stronger support in the Sphinx / Read the Docs world.

---

The first task would simply be to switch parsers while keeping everything else more or less identical. Then we can try out the different improvements that MyST will bring (for example things to help with #8073).

I’m hoping all of the changes will just be a matter of changing the Sphinx configuration: https://github.com/wagtail/wagtail/blob/ef2fa2e3944a7844b08aa070552f5046d5433a7f/docs/conf.py#L57-L62

There might be an official recommonmark -> MyST migration guide somewhere, particularly for our usage of Autostructify.

**Comment by thibaudcolas** [comment]
Tagging this as a good first issue – there is very little prerequisite knowledge of Wagtail needed since this only affects our documentation, which is a pretty standard Sphinx website.

**Comment by lb-** [comment]
This looks great, the MyST docs are pretty good and it looks like a robust solution for the future. 

There is also a conversion tool from RST to MD - https://rst-to-myst.readthedocs.io/en/latest/ (although it may not work out of the box).

**Comment by zerolab** [comment]
@harshlancer #8084 already does it. You could help by reviewing the changes and testing locally if you can.

**Comment by laymonage** [comment]
Leaving this here before I forget, will try to bring this up at the next core team meeting:

We should probably consider replacing `sphinx.ext.autodoc` with [`sphinx-autodoc2`](https://github.com/sphinx-extensions2/sphinx-autodoc2) so that we can write API references in Markdown as well:

https://myst-parser.readthedocs.io/en/latest/syntax/code_and_apis.html#sphinx-autodoc2

**Comment by lb-** [comment]
@laymonage - issue raised from your comment.
https://github.com/wagtail/wagtail/issues/10426

Please check I have explained it correctly.
