### ISSUE TITLE
Instagram Embed Finder missing support for new Instagram Reels

### ISSUE THREAD

**Issue by originell** [wagtail/wagtail#8077]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When wanting to embed an Instagram Reel (like [this one](https://www.instagram.com/reel/CZMs3O_I22w/)), it doesn't allow for that.

### Steps to Reproduce

1. Enable Facebook/Instagram Embeds [as shown in the docs](https://docs.wagtail.org/en/stable/advanced_topics/embeds.html#facebook-and-instagram-embeds)
2. Create a new page with a StreamField. Use the embed block in that StreamField and insert "https://www.instagram.com/reel/CZMs3O_I22w/" into the url field
3. Try to publish the page. It will say it can not embed the given URL.

### Technical details

This happens because the `wagtail/embeds/finders/instagram.py` is missing a matching regex in `INSTAGRAM_URL_PATTERNS`

### Fix

The fix can be found in #8075

**Comment by lb-** [comment]
Marking as enhancement as embed URLs can easily be customised.

**Comment by amelia291** [comment]
I see that the pull request for this bug has already been merged - maybe we can close this issue.

**Comment by lb-** [comment]
Resolved via https://github.com/wagtail/wagtail/pull/8075

https://github.com/wagtail/wagtail/commit/23895120b056179edb44c25a42e0ba0a7ef8bff5
