### ISSUE TITLE
Custom models using jQuery doesn't work

### ISSUE THREAD

**Issue by ronaldlangeveld** [wagtail/wagtail#8078]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I'm trying to use a custom modelfield inside Wagtail. In my case, Django-Recurrence. 

I then get greeted with the following error, which I believe is caused by the jQuery dependency, colliding with Wagtail's React use.

<img width="930" alt="Screenshot 2022-03-04 at 14 00 19" src="https://user-images.githubusercontent.com/19263291/156763385-7bf311ec-009e-4214-9e4c-be8985c23c70.png">

Here's my models.py

```
from django.db import models
from recurrence.fields import RecurrenceField
from modelcluster.fields import ParentalKey
from wagtail.core import hooks
from wagtail.core.models import Page, Orderable
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel, MultiFieldPanel, InlinePanel
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.search import index

class PartnerPage(Page):
    logo = models.ForeignKey(
        'wagtailimages.Image', related_name='partner_logo', null=True, blank=True, on_delete=models.SET_NULL
    )
    banner = models.ForeignKey(
        'wagtailimages.Image', related_name='partner_banner', null=True, blank=True, on_delete=models.SET_NULL
    )
    body = RichTextField(null=True, blank=True)
    feed_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='feed_image'
    )
    

    search_fields = Page.search_fields + [
        index.SearchField('body'),
    ]

    content_panels = Page.content_panels + [
        ImageChooserPanel('logo'),
        ImageChooserPanel('banner'),
        FieldPanel('body', classname="full"),
        InlinePanel('gallery', label="Partner Gallery"),
    ]

    promote_panels = [
        MultiFieldPanel(Page.promote_panels, "Common page configuration"),
        ImageChooserPanel('feed_image'),
    ]

    settings_panels = [
        MultiFieldPanel(Page.settings_panels, "Common page configuration"),
        InlinePanel('events', label="Events", heading="Sorry this doesn't work yet in Wagtail, use Django-admin instead"),
        
    ]


class PartnerPageRelatedLink(Orderable):
    page = ParentalKey(PartnerPage, on_delete=models.CASCADE, related_name='related_links')
    name = models.CharField(max_length=255)
    url = models.URLField()

    panels = [
        FieldPanel('name'),
        FieldPanel('url'),
    ]


class PartnerGallery(models.Model):
    page = ParentalKey(PartnerPage, on_delete=models.CASCADE, related_name='gallery')
    image = models.ForeignKey(
        'wagtailimages.Image', on_delete=models.CASCADE, related_name='+'
    )
    caption = models.CharField(blank=True, max_length=250)

    panels = [
        ImageChooserPanel('image'),
        FieldPanel('caption'),
    ]

class PartnerEvents(models.Model):
    partner = ParentalKey(PartnerPage, on_delete=models.CASCADE, related_name='events')
    name = models.CharField(max_length=255, null=True, blank=True)
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    recurrences = RecurrenceField(null=True, blank=True)

    panels = [
        FieldPanel('name'),
        FieldPanel('start_time'),
        FieldPanel('end_time'),
        FieldPanel('recurrences'),
    ]
    
    def __str__(self):
        return self.name


@hooks.register('insert_editor_js')
def editor_js():
    return '<script src="/django-admin/jsi18n/"></script>'
```

### Steps to Reproduce

1. On an existing or new Django / Wagtail entity run `pip install django-recurrence`
2. Setup Django Recurrence using [these instructions](https://django-recurrence.readthedocs.io/en/latest/usage/getting_started.html).
3. Add a hook to the Wagtail model where you want to use Django Recurrence. (as seen in this issue https://github.com/jazzband/django-recurrence/issues/99)
4. There's where it stops.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.10
* Django version: 4.0.3.
* Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:` 2.16.1 .
* Browser version: Safari 15
* Django-recurrence version: 1.11.1

**Comment by lb-** [comment]
@ronaldlangeveld could you please update the description with the relevant parts of your Page model. 

I might be wrong but it looks like you are using `InlinePanel` or `StreamField` with this? This may be causing some nuance of the issue.

This is unlikely to be a React and jQuery collision issue but possibly a DOM id issue. 

`	const targetNode = document.getElementById('container');`
https://github.com/jazzband/django-recurrence/blob/b96e305befca25db995e8c5fe3fc5351819f6745/recurrence/static/recurrence/js/recurrence-widget.init.js#L5

It appears that this line in recurrence is the issue but it is unclear why it cannot find the `#container` element without more details as to your model definition. 

Can you also advise as to what django-recurrence package version you are using.

**Comment by ronaldlangeveld** [comment]
@lb- Done :) 

I noticed something interesting,

When recurrence field is empty, Wagtail doesn't pick up Recurrence.
<img width="1198" alt="Screenshot 2022-03-05 at 08 43 29" src="https://user-images.githubusercontent.com/19263291/156871960-f65c7d9c-91c4-4952-98ad-3e9d0ab786e2.png">

However, when I populate the field within the Django-Admin, and then go back to Wagtail, then it loads fine without any problems. 

<img width="1111" alt="Screenshot 2022-03-05 at 08 46 52" src="https://user-images.githubusercontent.com/19263291/156872018-80869469-6fbd-4ee9-98f6-e6b230ec7b08.png">

**Comment by lb-** [comment]
`InlinePanel` works by dynamically adding html to the DOM whenever you add a new sub-item. 

Under the hood this is based on Django's format system - https://docs.djangoproject.com/en/4.0/topics/forms/formsets/


This allows for an 'empy' template version of a sub form (the `PartnerEvents` model in your case). This template is read and copied into the DOM whenever you add or start with an empty set and need to begin with one blank form to start with. 

If you look at the recurrence code, it will only initially set up (aka initialise) the forms that are in the DOM on first load. 

However, it does create a DOM observer to listen for additional recurrence fields added dynamically. 

This code is the code that is breaking but the looks of things, it does not appear to be related to jQuery or react or necessarily InlinePanel but rather there is no element with the id `container` to hook into. 

I re-read the docs for django-recurrence and cannot see a mention of this container being needed, and unless I missed something I cannot see it when [searching in the code](https://github.com/jazzband/django-recurrence/search?q=container+&type=).

I would recommend adding a wrapper div to the form with the ID 'container' and see if that fixes the problem.

A way to do this is to create a class that extends FieldRowPanel and use a different template on the class that adds a wrapper div. 

https://docs.wagtail.org/en/stable/reference/pages/panels.html#fieldrowpanel

Alternatively, override a core template and add a wrapper div. https://docs.wagtail.org/en/stable/advanced_topics/customisation/admin_templates.html#customising-admin-templates

If this works, then the issue is probably the documentation on the django-recurrence side not making it clear that dynamically adding fields requires an element with the id container for wherever new fields may be added.

**Comment by lb-** [comment]
@ronaldlangeveld ok, there are more problems with the recurrence code, it looks like it has been set up to work with dynamic content in a `#container` element, however it does not filter out text nodes.

Here is a really rough way to get this working, I have just done a minimal version of your model, created a `ContainerFieldRowPanel` that will wrap the `InlinePanel` and uses it to add a script and an id of container on the wrapper.

https://github.com/lb-/bakerydemo/commit/ccdd48ee520f40301453eb4e0bd3ca5ffd984b78

`models.py`
```
from django.db import models

from modelcluster.fields import ParentalKey
from recurrence.fields import RecurrenceField

from wagtail.admin.edit_handlers import (FieldPanel, FieldRowPanel, InlinePanel)
from wagtail.core.models import Page, Orderable


class ContainerFieldRowPanel(FieldRowPanel):
    template = "events/edit_handlers/container_field_row_panel.html"


class ConferencePage(Page):
    content_panels = Page.content_panels + [
        ContainerFieldRowPanel([InlinePanel('events', min_num=1)]),
    ]


class Event(Orderable, models.Model):
    page = ParentalKey(
        'events.ConferencePage',
        related_name='events',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255, null=True, blank=True)
    recurrences = RecurrenceField(null=True, blank=True)

    panels = [
        FieldPanel('name'),
        FieldPanel('recurrences'),
    ]
    
    def __str__(self):
        return self.name
```


`templates/events/edit_handlers/container_field_row_panel.html`
```
<div id="container">
  <script>
		// IMPORTANT: this script should be moved to an isolated file so it does not load every time this panel is used
    document.addEventListener("DOMContentLoaded", function () {
      const targetNode = document.getElementById("container");
      const config = { attributes: false, childList: true, subtree: true };
      const callback = function (mutationsList, observer2) {
        for (const mutation of mutationsList) {
          if (mutation.type === "childList") {
            // Check if nodes were added
            // ADDED - also ignore nodes that are only text nodes
            const addedNodes = Array.from(mutation.addedNodes).filter(function (
              element
            ) {
              return element.nodeName !== "#text";
            });
            if (addedNodes.length > 0) {
              const $addedRecurrenceField = django
                .jQuery(addedNodes[0])
                .find(".recurrence-widget");
              console.log("$addedRecurrenceField", $addedRecurrenceField);
              // Length has to be 1, to prevent cases when draging inlines returns length 0 or more than 1.
              if ($addedRecurrenceField.length === 1) {
                initRecurrenceWidget($addedRecurrenceField);
              }
            }
          }
        }
      };
      // cannot use observer as the recurrence code adds a global
      const observer2 = new MutationObserver(callback);
      observer2.observe(targetNode, config);
    });
  </script>
  {% include "wagtailadmin/edit_handlers/field_row_panel.html" %}
</div>
```

**Comment by lb-** [comment]
@ronaldlangeveld  as per above, I do not think this is a bug with `InlinePanel` but rather a factor of a few things

1. Documentation for `InlinePanel` - it could be clearer how this functionality works with JavaScript initialisation, but work is already underway to address common init script issues https://github.com/wagtail/rfcs/pull/33 and how we can refactor our existing JS https://github.com/wagtail/wagtail/discussions/7689#discussioncomment-2037913
    * If you see this as a room for improvement, please can you add a discussion item to https://github.com/wagtail/wagtail/discussions/7689


2. Django Recurrence JavaScript issues - it appears that the code as built in Django recurrence does not handle text nodes being added dynamically either side of added elements. This could be improved on that library but I understand why that has probably not come up yet.
    * If you want to maybe revise https://github.com/jazzband/django-recurrence/issues/198 to be focused on the text node issue that would be a good idea I think - the bug raised on that repo in its current state is unlikely to get looked at as it is a bit vague.
    * I also recommend you raise a new issue with Django Recurrence that asks for the `#container` requirement to be documented, it probably works as is in Django's modeladmin but maybe could be clearer in the docs or better yet, configurable somehow.

**Comment by ronaldlangeveld** [comment]
Great thanks for the feedback @lb- , much appreciated. 👍
