### ISSUE TITLE
Error occurs at editing a page when the number of sub pages is 52

### ISSUE THREAD

**Issue by JerryLin2022** [wagtail/wagtail#8083]
### Issue Summary

A summary of the issue.
AssertionError at /admin/pages/120/edit/
**Exception Value:** li element found outside of an enclosing list element
**Exception Location:** /www/wwwroot/cms/cms_env/lib/python3.7/site-packages/wagtail/admin/rich_text/converters/html_to_contentstate.py, line 126, in create_block
**Wagtail Version:** Wagtail v.2.15.1
**Python Version:** 3.7.8
**Django Version:** 3.2.11

<details>
<summary>Traceback screenshot</summary>

![2022-03-05_124335](https://user-images.githubusercontent.com/100368228/156868246-d16171c7-085b-4139-bb4e-93ba7c7cdc8e.png)

</details>

### Steps to Reproduce
I made a crawler article collector。 

1. The system will add the collected content "autogen_page" to the "page" ， by using page.add_child(instance=autogen_page) function.
![image](https://user-images.githubusercontent.com/100368228/156868446-37ef8300-5398-4181-986e-34b1e0049e85.png)

Page structure：
page| 
        |--autogen_page(1)
        |--autogen_page(2)
        |--autogen_page(n)

2. The page can be accessed normally for public：

"page" visit url: https://www.linxiaowei.cn/jerry/%E4%B9%8C%E5%85%8B%E5%85%B0/

"autogen_page" visit urls: 
>https://www.linxiaowei.cn/jerry/%E4%B9%8C%E5%85%8B%E5%85%B0/%E8%BD%AC%E8%BD%BD%E6%99%AE%E4%BA%AC%E5%87%BA%E5%85%B5%E4%B9%8C%E5%85%8B%E5%85%B0%E5%88%B0%E5%BA%95%E4%B8%BA%E5%95%A5/
>https://www.linxiaowei.cn/jerry/%E4%B9%8C%E5%85%8B%E5%85%B0/%E8%BD%AC%E8%BD%BD%E4%B9%8C%E5%85%8B%E5%85%B0%E5%B1%80%E5%8A%BF%E5%8F%88%E7%B4%A7%E5%BC%A0%E4%BA%86%E6%99%AE%E4%BA%AC%E5%92%8C%E6%8B%9C%E7%99%BB%E8%B0%81%E7%9D%80%E6%80%A5/
> ... ...

3. When the number of sub pages("autogen_page") is less than 5 maybe (page.get_children().count() < 5)， I can edit the "page" and "autogen_page" by wagtail admin. 

4.  When the number of sub pages is more than 5 maybe (page.get_children().count() >= 5)， Error occured. I can not edit the "page" content, but still can edit the subpage "autogen_page" content by wagtail admin.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project:  Yes

### Technical details

* Python version: 3.7.8
* Django version: 3.2.11
* Wagtail version: Wagtail v.2.15.1
* Browser version: Chrome 98.0.4758.102

**Comment by gasman** [comment]
Hi @JerryLin2022,
The error is as the message indicates - you have an `<li>` that isn't contained in a `<ul>` or `<ol>`. Rich text fields have strict requirements about structure - generally you can't insert HTML from an external source without validation.

**Comment by soukainakhalkhouli** [comment]
hello @JerryLin2022 

I'm getting also the same error,
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/71095703/158550518-15ba2fd6-1ef6-4568-85de-778a79f06ba9.png">
 how did you solve it
