### ISSUE TITLE
Add unique constraint for default site

### ISSUE THREAD

**Issue by byshen** [wagtail/wagtail#8089]
### Issue Summary

In file `wagtail/core/models/sites.py`, class `Site` is defined to be unique with the following constraints. But this may not be enough.

```python
class Site(models.Model):
    ...
    class Meta:
        unique_together = ("hostname", "port")
        verbose_name = _("site")
        verbose_name_plural = _("sites")
```

However, there are multiple places where special logic are added to handle the case that the default site is not unique. 
```python
    try:
        default = Site.objects.get(is_default_site=True)
    except Site.DoesNotExist:
        pass
    except Site.MultipleObjectsReturned:
        raise
```

I am just wondering that if we can create a unique constraint to enforce this when the data is injected.

```python
class Meta:
    ...
    constraints = [
        models.UniqueConstraint(
            fields=["is_default_site"],
            condition=models.Q(is_default_site=True)),
    ]
```

For example, we can add a constraint

Please let me know your thoughts. I can help create a pull request if you think this makes sense. Thanks a lot :D 
### Technical details

* Python version:3 .8.8
* Django version: 4.0.2
* Wagtail version: 2.17a0
* Browser version: Chrome/99.0.4844.51 Safari/537.36

**Comment by ParitoshKabra** [comment]
@byshen  I would like to go ahead with this issue as a beginner task 😅

**Comment by byshen** [comment]
@lb- could you please have a look? I can help create a PR to fix this if you think this is needed. Thanks!

**Comment by gasman** [comment]
Hi @byshen - it's not totally clear to me what problem this is solving. Does it fix a bug, improve performance, make the code simpler, or something else?

**Comment by byshen** [comment]
Hi @gasman, the current code logic implies that there should be only one default site. I think we can create a DB constraint to prevent the potential errors of more than one default site. Thanks

**Comment by gasman** [comment]
OK, yes, I see - the rule should be enforced at the model / database level, not just in the admin views, so that it doesn't get broken by custom code or data imports (for example). Yes, I'd be happy to see a PR for that - thanks!

**Comment by byshen** [comment]
Sure. I will create a PR soon. 

Also, could you please take a look at #8088 #8090? These two are similar issues. I can create a PR to fix them in the same PR. Thanks!

**Comment by lb-** [comment]
Update: it appears that constraints with the `condition` is not supported in some DBs

https://docs.djangoproject.com/en/dev/ref/models/indexes/#condition
> The condition argument is ignored with MySQL and MariaDB as neither supports conditional indexes.

For now I will flag this as a optimisation as I think this is not really a bug, we could still add the DB logic and know it will not be supported in some DBs but as per comment https://github.com/wagtail/wagtail/pull/8152#issuecomment-1077516036 . I am not sure if this creates more complexity for a small benefit.

Will let others chime in.

**Comment by lb-** [comment]
As per comment - https://github.com/wagtail/wagtail/pull/8152#issuecomment-1103677236

This feature would be helpful but the non-full DB support creates added complexity and moving parts that outweighs the benefits.

I will close this and the related issues for now, but we can reopen if condition/UniqueConstraint is supported by all DBs Django supports in the future.

Alternatively, there may be another way to enforce strictness for data imports which can be raises as a separate enhancement issue.

Thanks so much for suggesting this @byshen
