### ISSUE TITLE
Add button to RichTextField to edit the generated HTML directly

### ISSUE THREAD

**Issue by lapinvert** [wagtail/wagtail#8100]
### Is your proposal related to a problem?
As a website owner who knows what you are doing, its often handy to be able to edit directly html.
Most Rich text / wysiwyg editors out there allow that feature.

### Describe the solution you'd like

Add a new optional button on rich text field element that would toggle "html mode".

**Comment by gasman** [comment]
Hi @lapinvert - thanks for the suggestion.
This isn't really possible, because the Draftail rich text editor has its own data representation that isn't HTML. There's a more detailed explanation here: https://stackoverflow.com/a/71357362/1853523
