### ISSUE TITLE
Documentation - migrate editor's guide (editor manual) to markdown instead of rst

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8106]
### Pertinent section of the Wagtail docs 

* `docs/editor_manual`
* https://docs.wagtail.org/en/stable/editor_manual/index.html

### Details

* As part of the ongoing discussion into moving the editor's guide into a separate repo or website https://github.com/wagtail/wagtail/discussions/7824
* It would be easier to work with markdown syntax instead of RST
* The Watail main branch recently moved to MyST https://myst-parser.readthedocs.io/en/latest/ which uses a syntax that is much closer to markdown than the previous usage
* Migrating to markdown will mean we have a format that is easier to work with for future work and also helps move more of our existing documentation into markdown (long term goal)
* https://rst-to-myst.readthedocs.io/en/latest/ may be useful

**Comment by ShwetKhatri2001** [comment]
Hi @lb! I'd like to work on this issue and start my open source journey with wagtail.

**Comment by lb-** [comment]
@ShwetKhatri2001 go for it, reach out if you need a hand.

**Comment by ShwetKhatri2001** [comment]
I'm done with the rst-to-myst convertions, now should I still keep the `.rst` files along with `.md` files?
Also any more changes required so that `.md` files can be used on [ documentation website](https://docs.wagtail.org/en/stable/editor_manual/index.html)

**Comment by lb-** [comment]
Hey. No need to keep the rst files - otherwise there will be duplicated content in the documentation. 

I'd recommend that you prepare a pull request for the changes in this area only to start. 

Longer term we do want to migrate all .rst to .md but this is best done in smaller pull requests.

**Comment by nish-ahmd** [comment]
Is this issue still exists?

**Comment by lb-** [comment]
@nish-ahmd please see the comments and linked pull requests above, a PR is already raised for this issue.

**Comment by lb-** [comment]
@nish-ahmd  if you wanted a good candidate for an area of the docs that also needs this conversion, may I suggest you look into the folder `docs/advanced_topics/images` - there are not too many files and most can translate pretty easily to the markdown file.

There is no issue for this raised so simply create a pull request when you are ready, this goes for any parts of the docs, even if you want to give a single page a go.

Please review the preferred markdown syntax her https://docs.wagtail.org/en/latest/contributing/documentation_guidelines.html (note `latest` in the URL, this tracks against main). For other syntax or general understanding of how the markdown syntax works see here https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html .

Thanks for being keen on getting involved!
