### ISSUE TITLE
Images management command to purge and regenerate renditions

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8107]
### Is your proposal related to a problem?

- Occasionally, you can create problems when syncing data from production environments or you just want to clear out unused renditions.
- There are also cases where there is a need to clear space on a server and we may want to intentionally only load image renditions when requested.

### Describe the solution you'd like

A new management command, in the images app, that provides the ability to regenerate image renditions. With an optional argument to also purge any existing ones.

* `manage.py update_image_renditions` - will regenerate all the rendition images (not the DB entries)
* `manage.py update_image_renditions --purge` - will first purge all rendition images and then regenerate all the rendition images
* `manage.py update_image_renditions --purge-only` - will ONLY purge all rendition images

### Describe alternatives you've considered

- Use something like `rm -rf` within the media folder, however this risks removing images that are not renditions, plus will mean that the next load for users will be slow for each image needed.

### Additional context

- See the documented method of writing Django Management commands https://docs.djangoproject.com/en/4.0/howto/custom-management-commands/
- There is an old PR that started this https://github.com/wagtail/wagtail/pull/759 - could be a good reference
- There is also this PR that may be covering similar functionality https://github.com/wagtail/wagtail/pull/6595
- Use the Django documented `self.stdout.write("Unterminated line", ending='')` and `            self.stdout.write(self.style.SUCCESS('Successfully closed poll "%s"' % poll_id))` for messages, not `print`
- Should have documentation added to the page https://docs.wagtail.org/en/stable/reference/management_commands.html
- Needs unit tests

**Comment by Hitansh-Shah** [comment]
@lb- I am new to wagtail and I want to become familiar with how it works. I have done mysite tutorial with wagtail. I would like to give this issue a try. Can you assign it to me?

**Comment by lb-** [comment]
Hey @Hitansh-Shah - no need to assign this to you, simply get started on it and give it a go. 

Please read through these PRs in full (code changes, comments) as they are  previous attempts at this and will help you understand the problem and potential solutions.

- https://github.com/wagtail/wagtail/pull/759
- https://github.com/wagtail/wagtail/pull/6595

It's ok to start small, even a PR that does not include the Purge parts is great. Better a small change with unit tests and docs than a big change that gets to complex and can never be merged.

Also, it might be worth reading this PR - https://github.com/wagtail/wagtail/pull/8069 - it ha some related functionality that may be worth understanding.

**Comment by Hitansh-Shah** [comment]
Thanks @lb- . I will go through the resources you have attached and try to brew something. I will let you know if I am stuck somewhere.

**Comment by Hitansh-Shah** [comment]
Hey @lb- , so I looked into the resources and the requirements of this issue. So I am just confirming what I understood so far and what I am planning to do. For regenerating the renditions I will just loop through all the renditions and for each rendition I will use the `get_rendition` method on `rendition.image` with `rendition.filter` as the parameter (all of this in the command function obviously). This will regenerate each and every rendition. I don't know if I have caught on to the problem, please correct me if I am wrong. If I am in the right direction do let me know so that I can open a draft Pr to work further. Thanks

**Comment by lb-** [comment]
That makes sense and appears to summarise correctly @Hitansh-Shah 

As noted above, feel free to start with a simple version of this that simply purges (deletes) renditions (even if that means a different name is needed. 

Please also namespace the command. `wagtail_update_image_renditions` 

See https://github.com/wagtail/wagtail/issues/8162 for context
