### ISSUE TITLE
Code cleanup: remove unneeded text-transform styles from stylesheets

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8121]
This is a follow-up to #7624 / #8111, and https://github.com/wagtail/stylelint-config-wagtail/pull/16. Now that our admin UI almost never uses `text-transform: uppercase`, we should:

## Refactor code

- Remove the `text-transform: none`, `text-transform: inherit`, and `text-transform: initial` overrides still present in the stylesheets – which don’t do anything useful anymore.

## Update linting

- Update to the latest version of `stylelint-config-wagtail`, which will enforce it’s not used in new styles (`npm install --save-dev @wagtail/stylelint-config-wagtail@0.5.0`)
- Add `// stylelint-disable-next-line property-disallowed-list` to the right lines for the three components where we do want to retain uppercasing: `_status-tag.scss`, `PublicationStatus.scss`, and the page editor’s `button--live`.

## Configure Tailwind

- Disable the text-transform Tailwind plugin, since we’ll never want to use it (add `textTransform: false` to the `corePlugins` in `tailwind.config.js`)

**Comment by KhushiRana2003** [comment]
Please Assign this Issue to me.. I want to work on this Issue..

**Comment by lb-** [comment]
@KhushiRana2003 thanks for your interest in this issue, however if you look at the linked PRs it appears that https://github.com/wagtail/wagtail/pull/8129 has already been raised to resolve this issue.

**Comment by KhushiRana2003** [comment]
@lb- Means this issue is already resolved??

**Comment by PaarthAgarwal** [comment]
Need a review on #8129.

**Comment by lb-** [comment]
Resolved via https://github.com/wagtail/wagtail/pull/8129
