### ISSUE TITLE
Review (and clean up) over-reliance on inset positioning in styles

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8125]
Follow-up to #8051, based on @wagtail/ui team discussions (LB - Thibaud in particular). We have way too many styles reliant on absolute and relative positioning in Wagtail – which we suspect leads to issues with general multilingual support, and RTL support (#7793) in particular. 

At this stage, @lb- started reviewing existing usage of this type of positioning, and it would be useful for contributors to:

- [ ] Further review usage of relative & absolute positioning – whether this is indeed the best approach for the specific cases it’s used for, or whether we could refactor the code.
- [ ] Where possible – refactor the code to more modern positioning approaches (CSS grid or flexbox layouts in particular).
- [ ] Consider whether we should prevent usage of inset positioning with linting checks.
- [ ] Update our upcoming UI guidelines (#8044) accordingly

First high-level review by @lb- from https://github.com/wagtail/wagtail/pull/8051#issuecomment-1057924657:

| File                                                        | Usage | Type                          | Selector                                                                |
|--------------------------------------|--------|---------------------|--------------------------------------------|
| client/scss/components/_button.scss | Icon | `position` | `.bicolor:before`, `span.icon-spinner:after`, `.controls` |
| client/scss/components/_button.scss | Other | `border-radius`   | `.bicolor .icon-wrapper`                                |
| client/scss/components/_comments-controls.scss | Icon | `position` | `&__icon` |
| client/scss/components/_comments-notification-dropdown.scss | Dropdown | `position` | `::before ` |
| client/scss/components/_dropdown.legacy.scss | Dropdown | `position` | `.dropdown` |
| client/scss/components/_dropdown.legacy | Dropdown | `position` | `.c-dropdown__button` |
| client/scss/overrides/_utilities.dropdowns.scss | Dropdown | `position` | `.u-arrow--tl:before` |
| client/scss/components/_footer.scss | Other | `position` | `.avatar` |
| client/scss/components/_forms.scss | Controls | `position` | `select ~ span:after ` |
| client/scss/components/_forms.scss | Icon | `position` | `...fields :before/:after ` |
| client/scss/components/_forms.scss | Controls | `position` | `.field-comment-control` |
| client/scss/components/_help-block.scss | Icon | `position` | `.help... &:before` |
| client/scss/components/_listing.scss | Icon  | `position` | `th.icon`, `.privacy-indicator` |
| client/scss/components/_loading-mask.scss | Other | `position` | `.loading-mask` |
| client/scss/components/_main-nav.scss | Icon | `position` | `.menu-item a:after`, `icon--submenu-trigger` |
| client/scss/components/_main-nav.scss | Other | `position` | `.nav-wrapper` + lots more |
| client/scss/components/_modals.scss | Other | `position` | `.modal`, `.modal-backdrop` |
| client/scss/components/_skiplink.scss | Other | `position` | `.skiplink` |
| client/scss/components/_tabs.scss | Controls | `position` | `.a.errors` |
| client/scss/components/_tooltips.scss | Controls | `position` | all |
| client/scss/elements/_elements.scss | Unsure | `position` | `.body:after` |
| client/scss/elements/_forms.scss | Icon | `position` | `input[type='radio']:before` |
| client/scss/objects/_avatar.scss | Other | `position` | `.avatar img` |

**Comment by Dev-Liz** [comment]
Hello @thibaudcolas I'd love to work on this if it's still up for grabs.

**Comment by thibaudcolas** [comment]
We’ve solved the biggest problem here in #9914, so I’ll close this now.

We’d still want to limit reliance on inset positioning as much as possible, but I don’t think a blanket refactoring or even a review is in order anymore.
