### ISSUE TITLE
Logo contrast issues on Github dark mode 

### ISSUE THREAD

**Issue by stevedya** [wagtail/wagtail#8135]
### Issue Summary

When using Github on dark mode the wagtail logo contrast on the main README is illegible.  

### Steps to Reproduce

1. Switch your Github profile theme to dark mode.
2. View the wagtail repository readme

<img width="1044" alt="Screen Shot 2022-03-16 at 10 16 12 AM" src="https://user-images.githubusercontent.com/25041665/158569904-c129cb5c-01fb-4bfd-bdf7-215f501528b6.png">

### How we could address this issue

Github offers a special ID for it's theme which allows you to specify which image to use:
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

An example of how this would look in the README.md would be:
`![GitHub Dark](https://github.com/path-to-dark-compatible-image-here.png#gh-dark-mode-only)`
`![GitHub Light](https://github.com/path-to-light-compatible-image-here.png#gh-light-mode-only)`

### Technical details

* Browser version: Chrome 99

**Comment by sumit-158** [comment]
Hi @thibaudcolas Can I work on this?

**Comment by PaarthAgarwal** [comment]
I noticed earlier that dark mode reduced wagtail logo's visibility, but it never occurred that GitHub has a great fix.
