### ISSUE TITLE
Namespace Wagtail Management Commands

### ISSUE THREAD

**Issue by jlchilders11** [wagtail/wagtail#8162]
### Is your proposal related to a problem?

Currently, wagtail management commands use generic command names, such as `update_index`. While this is fine for simple projects, or projects where wagtail is the only package in play, it causes conflicts in some instances. In particular, `update_index` is also used in the package haystack, completely breaking its indexing functionality if they are added to apps in the wrong order.

### Describe the solution you'd like

Wagtail management commands should be namespaced such that they have no chance of unintentionally colliding with other package command names. 

e.g. `update_index` -> `wagtail_update_index`

### Describe alternatives you've considered

While this problem can be worked around through manipulation of installed apps, this is unintuitive to do, and may be impossible in certain deployment scenarios.

### Additional context

@vsalvino

**Comment by gasman** [comment]
`update_index` is aliased as `wagtail_update_index` for this reason: https://docs.wagtail.org/en/stable/reference/management_commands.html#wagtail-update-index . I don't think there's ever a situation where resolving the conflict is impossible - in the worst case you can insert an app at the top of INSTALLED_APPS that does nothing but import the command modules under your desired alternative aliases.

**Comment by lb-** [comment]
I think we can close this. Unless there is a reason to deprecate the unpredicted command but it seems like this is a non issue for the update index command.
