### ISSUE TITLE
get_extra_restriction() missing 1 required positional argument: 'remote_alias'

### ISSUE THREAD

**Issue by hazho** [wagtail/wagtail#8168]
On one of the project..
while an admin **searching for something**, the "Internal Server Error"  appears, after investigating for a while, it turns out that the 
/wagtail/contrib/postgres_search/models.py L:18 is expecting some thing form the DB, but not getting any

* Python version: 3.9
* Django version: 4.0.1
* Wagtail version: 2.15.1 (not tested on other versions)

**Comment by gasman** [comment]
Hi @hazho,
Sorry, there's not enough detail here for us to investigate this as a bug. Please try to reproduce this on a fresh Wagtail installation, and open a new bug report filling in the full issue template.
