### ISSUE TITLE
Implement bulk actions for snippet listings

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8183]
### Is your proposal related to a problem?

* [Bulk actions](https://docs.wagtail.org/en/stable/releases/2.15.html#bulk-actions) was released in Wagtail 2.15
* This supports Page, User, Image and Document models
* However, it would be great to have this also support Snippet listings
* Initially this would be a layout change to match other content, however the main benefit is extending behaviour through custom bulk actions.

### Describe the solution you'd like

* When navigating to a snippet listing, the ability to check all / some and then delete these should match the user interface of other listings where bulk actions are supported.
* It should also be possible to add additional bulk actions as documented https://docs.wagtail.org/en/stable/extending/custom_bulk_actions.html#registering-a-custom-bulk-action

### Describe alternatives you've considered

* Advising users to be aware that the UI is different in form builder.
* Building additional custom actions or buttons through customisations.

### Additional context

Screenshot of current (2.16) snippets listing with something selected

<img width="1634" alt="Screen Shot 2022-03-21 at 8 02 01 pm" src="https://user-images.githubusercontent.com/1396140/159240499-76923ad3-1f85-4880-87e9-28564707233a.png">

Screenshot of document listing bulk actions for comparison

![What’s New in Wagtail 5 - 2 15 Features (DRAFT)](https://user-images.githubusercontent.com/1396140/159239986-ee976728-a014-4681-9539-7405feef1c2e.png)

**Comment by KIRA009** [comment]
@lb- Can I pick this up?

**Comment by lb-** [comment]
> @lb- Can I pick this up?

Go for it, there are some things to be aware of

* Snippets are in a bit of a flux at the moment, so keep an eye on any PRs that may conflict in that area (most are sitting as draft right now though).
* Bulk actions PR for form submissions on going (feel free to add any feedback to that if you want to) https://github.com/wagtail/wagtail/pull/8542
* Frontend changes ongoing to try to get shift + click working to select multiple at once, should not be a conflict with working on this but just FYI https://github.com/wagtail/wagtail/pull/8540

**Comment by lb-** [comment]
Has been implemented via https://github.com/wagtail/wagtail/pull/8574 & released in 4.0 but looks like it got missed on any release notes or changelog (will add shortly).
