### ISSUE TITLE
Ability to add data attributes to main menu (sidebar) items

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8199]
### Is your proposal related to a problem?

- Wagtail 2.16 introduced a new sidebar (main menu) architecture based on React, the interaction of this menu is much nicer however this also meant that support was dropped for arbitrary html and element attributes on link items. 
- This has created a problem where I'd you want to leverage the menu system (e.g. hooks) to do much more than a different URL or class name has become exceedingly complex (essentially you need to rebuild the react components from source and copy/paste code. 

#### Examples

- https://github.com/wagtail/wagtail/issues/8196 - this would have been partially possible with the old menu system by subclassing the `MenuItem` class
- a tutorial I wrote that relies on some custom JS behaviour linked to the menu item links is no longer possible https://dev.to/lb/how-to-build-an-interactive-guide-for-users-in-the-wagtail-cms-admin-2dcp (note. Technically with much more JS wrangling it would be doable)
- https://github.com/wagtail/wagtail/issues/8087 would have been possible before but is not now (although, allowing target blank on links is questionable)
- Showing some simple text in the menu flow is not possible (e.g. a label), hooking in extra JS behaviour easily (add event listeners) is more difficult without a nice way to determine which links we want to listen to. 

### Describe the solution you'd like

- Similar to `attrs` in Django field widgets, allow for a dict if attrs that will be written to the html element. These can be filtered so that target and some other attributes won't be allowed if needed. This would be almost the same as the previous attrs support. https://docs.wagtail.org/en/v2.15.4/reference/hooks.html#register-admin-menu-item
- Alternatively something like `data_attrs` which will be a dict of data only html attributes that will be output in the link element.
- Ability to declare a link as a non-link, or disabled somehow, so that a simple use case of arbitrary content (just text) can be supported in the menu list.
- Maybe this should be a separate issue - but having some custom events dispatched when the menu is expanded and sub-menu items are expanded/collapsed would be super helpful. 

### Describe alternatives you've considered

- DOMutationObserver can be used to listen to Dom changes and then patch in any classes or attributes as needed, but this means the callbacks would be fighting with Reacts updates. 
- Not using the new sidebar by keeping the setting of the old one. 
- Copying the react code used and making a new version of the JS code that does handle more kinds of content customisations.
- Use CSS classes only to achieve what we can. 

### Additional context

- Not sure if we want to go this far but allowing full custom MenuItems would be good, either through the Wagtail Components system or telepath or similar.

**Comment by thibaudcolas** [comment]
Implemented in #8310.
