### ISSUE TITLE
FormField.clean_name is not updated when FormField.label changes

### ISSUE THREAD

**Issue by jams2** [wagtail/wagtail#8200]
### Issue Summary

`FormField.clean_name` is populated when a `FormField` instance is first saved, but not on subsequent updates. As the `clean_name` value is a function of `FormField.label`, this is unintuitive - my expectation is that the `clean_name` would be updated correspondingly.

### Steps to Reproduce

1. Create a new Form builder page
2. Add a form field to the page and save
3. Edit the label of the existing form field and save again

This issue can be verified by then inspecting the form submission data in Python, and also by checking the `name` attribute of the corresponding HTML input element - in both cases, the value will be the original `clean_name`, which may no longer correspond to the label.

A simple fix is to unconditionally update the `clean_name` on `FormField.save`. I can submit a patch for this, but want to check if there are any reasons why the current behaviour exists, or if there are any assumptions that I'm not aware of.

### Technical details

Wagtail Version: 2.16

**Comment by gasman** [comment]
Hi @jams2,
Form submission data is stored as a JSON dict, with the keys being the `clean_name` - so if we were to update the clean name on any changes to the label, that would invalidate any previously submitted data.
