### ISSUE TITLE
When moving pages, no option to move to root

### ISSUE THREAD

**Issue by jessemenn** [wagtail/wagtail#8206]
### Issue Summary

2.16.1 seems to have changed how pages are moved. If a site has Pages A/B/C/D nested in that mmanner, when trying to move Page D, only Page C will be available, not A or B or Root. I'm adding an animated gif.

![move-to-root](https://user-images.githubusercontent.com/1834167/160155978-92b207bd-f860-408e-8ab5-04f3a4b6cc78.gif)

### Steps to Reproduce

1. In 2.16.1, try to move a page.

I can use the breadcrumbs to move the page into Root or some other higher level page, but that's rather unexpected and I wouldn't have thought to try it if someone hadn't specifically asked about it.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

* Python version: 3.9
* Django version: 3.2.12
* Wagtail version: 2.16.1
* Browser version: All of em

**Comment by aliceni81** [comment]
To move to root, you should click the "earth" icon and then select "Root".

![image](https://user-images.githubusercontent.com/81170508/160221968-17a3b6fc-082d-4e12-a811-70dd20a869f8.png)

**Comment by Tijani-Dia** [comment]
I don't think that this should be labelled as a bug. Admittedly, the UX is quite confusing if you were used to the previous behaviour where you could move pages starting from the root level.

Maybe we should document the new behaviour somewhere in the docs or in the move view itself?

Cc: @phildexter

**Comment by thibaudcolas** [comment]
As of #8689 / #8647, the "Move" UI now uses the page chooser to select the new parent page, which solves this issue. The page chooser currently shows the root level by default, and even if we were to change it, I’d expect the breadcrumb within it would be much more natural to use than the previous UI’s breadcrumb.
