### ISSUE TITLE
Ability to upload image directly to S3

### ISSUE THREAD

**Issue by antimora** [wagtail/wagtail#821]
I am planning to host an instance of wagtail on EC2 and I want all content stored separately from the host machine. It would be ideal if I could upload images directly to S3 and serve them from there.

**Comment by sixpearls** [comment]
Hi all,

I was able to implement a remote storage backend (FTP, in my case). I suspect that S3 is not very different. See https://github.com/sixpearls/wagtail-storageimage

Right now it's dependent on a couple pull requests. An FTP specific PR for django-storages-redux and small tweak to Willow to handle the stream object that the FTP backend holds in memory.

Uploading and creating renditions is slow. If I figure out the best way to generate the renditions on creation, it may not be too bad.
