### ISSUE TITLE
Missing translations in workflow templates

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8214]
In those two templates:

```
wagtail/admin/templates/wagtailadmin/workflows/confirm_disable.html
wagtail/admin/templates/wagtailadmin/workflows/confirm_disable_task.html
```

We use the "No" string without having it set up for translations. We need to use `{% trans 'No' %}` instead.

**Comment by thibaudcolas** [comment]
Assigning to @fibonacciTrees as a good first issue.

**Comment by anujaraj** [comment]
Hello,
Can I work on this issue too?

**Comment by anujaraj** [comment]
Hello,
I found that trans is missing in the following file:
wagtail/admin/templates/wagtailadmin/workflows/confirm_delete.html

Can I send a PR for adding - {% trans 'No' %}
Thank you

**Comment by anujaraj** [comment]
i have added a PR to the forked repository

**Comment by FibonacciTrees** [comment]
I didn't have time to address this until this weekend and found it's already closed. I'm new to open source: what's the protocol for how this issue played out? Should I have commented saying when I'd have time to work on it? Is it okay that others fixed it before I could work on it?

**Comment by lb-** [comment]
@FibonacciTrees from what I can see, it looked like another person picked this up and prepared a solution via this PR https://github.com/wagtail/wagtail/pull/8240 (although they did not link to this issue unfortunately).

Also in the meantime, https://github.com/wagtail/wagtail/pull/8238 was prepared, which fixed some related issues.

I think with any issue, if a PR is up it will be assessed, with some people learning open source themselves it appears they did not correctly link to this issue which meant it kind of was left 'open' but a fix was already underway.

If you are still keen to get involved I recommend you look at any other good first issues https://github.com/wagtail/wagtail/labels/good%20first%20issue or try to find any other missing translations in the code through a bit of searching.

**Comment by FibonacciTrees** [comment]
Thank you for the explanation @lb- . I'll take a look at the other "good first issue" tags.

**Comment by 0saurabh0** [comment]
hey @FibonacciTrees I mistakenly picked up this issue (raised PR without noticing that it was assigned to you).
Really sorry for your inconvenience.
If you want i can help you find some documentation typos or errors, they're also good to get started.
