### ISSUE TITLE
Ability to control the timeout of button-longrunning 

### ISSUE THREAD

**Issue by awhileback** [wagtail/wagtail#8232]
### Is your proposal related to a problem?

The `button-longrunning` class currently provides a UI indication via the submit button animation that a long running form submission is being processed, but it doesn't take into account the server response, so it times out and shows complete even though the task is not.

### Describe the solution you'd like

The button-longrunning class should take into account the server's response, if possible.  For example I have my Nginx timeout set to 300 seconds, the max body size set to 300mb, and the gunicorn worker timeout set to 300 seconds to allow for > 100mb audio file uploads for podcast episodes, but after seemingly 30 seconds, the `button-longrunning` animation expires, leaving the user with an erroneous form display.

The task completes if they ignore the UI, but that is obviously not optimal.

**Comment by lb-** [comment]
Not a solution but some extra context. 

I see this component as a really good  example for where we can make this work better for those customising Wagtail through adoption of a lightweight framework. 

I have an example here of how this could work. 
https://github.com/lb-/bakerydemo/blob/ui-experiments/lightweight-frontend-framework-investigation-2022.md#use-case-3---long-running-button

These are all ideas for now and may not end up in Wagtail. 

Additional links

- full research into a lightweight framework https://github.com/wagtail/wagtail/discussions/7689#discussioncomment-2037913
- RFC to make it easier to use custom JS against html with some data attributes without needing to call init everywhere. https://github.com/wagtail/rfcs/pull/33

**Comment by thibaudcolas** [comment]
Nice catch @awhileback, thank you for the solid report. It looks like the implementation intentionally does this to make it possible to click the button again (we disable it after click currently), on the assumption the user might have cancelled the request or there might have been a network error.

Here is the implementation: https://github.com/wagtail/wagtail/blob/main/client/src/entrypoints/admin/core.js#L462-L523

I’ll research this a bit more and try to propose a new approach that side-steps this problem.

**Comment by awhileback** [comment]
Thanks! I suppose this should tag @zerolab since part of it specific to wagtailmedia is mention of a chunked uploader for larger files, as well.

I debated which of wagtail and wagtailmedia to post this in, but at the end of the day it seemed like both projects would be better for taking a look / think about it.

**Comment by lb-** [comment]
Having a fixed timeout is important, remember it is not simple to track if a Promise never resolves without some central shared handling using something like Promise.race.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race

Hence it is difficult to know if the network has failed/never resolved/ timed out somewhere and then if the user can safely click the button again.

**Comment by lb-** [comment]
RFC up for adoption of Stimulus JS with a potential path forward on this issue through a `data-*` attributes driven API on the button element, irrespective of where used (even when added to a modal dynamically) it would attach the JS behaviour as desired.

https://github.com/wagtail/rfcs/pull/78

Feedback welcome on that RFC's PR.

**Comment by thibaudcolas** [comment]
Thinking of the UX of this more, my recommendation would be for:

- Having a progress indicator separate from the button. Then we can show it until actual completion of the request, without a timeout. This also solves accessibility issues with this UI: the loading indicator doesn’t work with screen readers, and doesn’t pass contrast requirements since disabled buttons have very low contrast
- Allowing the button to be clicked again at any point, with an extra confirmation step from end users when there is a request still pending (a `window.confirm` should be plenty enough). This covers the reason why we disable the button to start with, and why we re-enable it at some point. It avoids [accessibility issues with disabled buttons](https://axesslab.com/disabled-buttons-suck/).

**Comment by lb-** [comment]
Note: This timeout customisation will likely be solved in some form via the WIP https://github.com/wagtail/wagtail/pull/9956

@Lovelyfin00 when you get a chance can you read the rest of this issue and see what other gaps we may need to discuss.

**Comment by Lovelyfin00** [comment]
Sure
