### ISSUE TITLE
[Docs] Update README to include Twitter

### ISSUE THREAD

**Issue by guelate** [wagtail/wagtail#8253]
### Pertinent section of the Wagtail docs 

I propose to add a dependency for Twitter. I think it is important to put forward the community.

### Details

[![Twitter follow](https://img.shields.io/twitter/follow/WagtailCMS?style=social)](https://twitter.com/WagtailCMS)

**here**
![aaa](https://user-images.githubusercontent.com/47215234/160903085-24fd85ea-527a-428c-a92a-99b198e2dd33.png)

**Comment by guelate** [comment]
@[KalobTaulien](https://github.com/KalobTaulien) , @[zerolab](https://github.com/zerolab) This is my PR : https://github.com/wagtail/wagtail/pull/8256 :)

**Comment by jadesola123** [comment]
Hi @guelate and @lb-, I am a potential Outreachy intern interested in the Wagtail documentation project and would love to fix this issue.
I opened a PR with my proposed solution. I am open to any feedback and learning😊

**Comment by Scotchester** [comment]
Completed in #9295

**Comment by Scotchester** [comment]
@guelate Thank you for your original work on this!
