### ISSUE TITLE
ModelAdmin title-column always links to "edit" page

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#8261]
### Issue Summary

Even if a user does not have the "change" permission, the `ModelAdmin` still renders a link to the "edit"-view, which then results in a permission error for this user. For example, we often use ModelAdmins which use `inspect_view_enabled = True` and only allow inspect and delete.

This worked before https://github.com/wagtail/wagtail/pull/7408 (wagtail < 2.15), because the title column has not been linked and the "Edit"-button did not appear if the user didn't have the permission.

I don't know, what's the best way to solve it. Falling back to the inspect view only works, if it has been enabled. Skipping the link if the permission is missing maybe re-creates the issue #7333 in some cases, or at least needs some extra work to improve the html for screen readers?

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Create a simple model and a `ModelAdmin` for it
3. Create a user in the "Moderators" group and only add the "view" permission for the new model to the group.
4. Create an instance with a superuser and find the linked item with the newly created moderator.

### Technical details

* Wagtail version: >= 2.15

**Comment by th3hamm0r** [comment]
After looking at the code again, I would propose the following solution:

Instead of only using the "edit"-URL here
https://github.com/wagtail/wagtail/blob/820c27fca9abec82406dad0ca6cbbf66c7e9ed7d/wagtail/contrib/modeladmin/templatetags/modeladmin_tags.py#L74-L84
I would instead use the `ModelAdmin`s `button_helper.get_buttons_for_obj()`, and use the URL of the first button, which defines a non-empty "url".
With that the developer can easily change the "default" action by reordering the buttons returned by the button helper.

If that's ok, I could make a PR for that.

**Comment by ababic** [comment]
Suggested fix: Since button helpers have access to all of the necessary mechanisms and are easily customisable, I would suggest adding a new `get_primary_action_link()` method for this purpose.

**Comment by th3hamm0r** [comment]
@ababic sounds good! I think I could make a PR for that during the next week. Ok?

**Comment by ababic** [comment]
@th3hamm0r that would be fantastic, thank you!
