### ISSUE TITLE
ThumbnailMixin does not display in header the value defined under thumb_col_header_text 

### ISSUE THREAD

**Issue by jstacoder** [wagtail/wagtail#8269]
### Issue Summary

When adding ThumbnailMixin to a ModelAdmin, and giving it the `thumb_col_header_text` attribute, should display that on the list header for the thumbnail. but it always uses the default defined 'image' 

![image](https://user-images.githubusercontent.com/4082254/161403611-d75291b5-6db8-413a-82fa-447aab5fe69a.png)

![image](https://user-images.githubusercontent.com/4082254/161403594-1b2bd39b-2332-40a8-b539-cae4d72a57e6.png)

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. in models.py add a new model (non page) with a forignkey to wagtailimages.Image 
3. add model admin definition in wagtail_hooks.py
4. add ThumbnailMixin to model admin super classes
5. add some value to thumb_col_header_text
6. register new model admin
7. load app
8. add new instance of your new model with an image
9. in list header for your image it will say 'image' not what you defined in thumb_col_header_text

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)
* i already know why this is happening and will submit a pull request shortly

### Technical details

* Python version: 3.9.7
* Django version: 4.0.3
* Wagtail version: 2.16.1
* Browser version: Chrome Version 100.0.4896.60 (Official Build) (x86_64)

**Comment by lb-** [comment]
Can confirm this appears to be a bug, we clearly state in the docs that you can override `thumb_col_header_text` in your `FooModelAdmin` class and it should be reflected in the header but it is not.

Removing `unconfirmed` label.
