### ISSUE TITLE
Api caal is returnig 404

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#8273]
After updating a wagtail 2.9.3 project to 2.15 I’ve got a problem with te page explorer.
Running a dev version is working fine.
But after deployment I got a 404.

Dev
<img width="1242" alt="Schermafbeelding 2022-04-03 om 17 14 59" src="https://user-images.githubusercontent.com/8074866/161434901-623a8f3b-118b-4eb1-a4d7-64e5651b2658.png">

Deploy
<img width="971" alt="Schermafbeelding 2022-04-03 om 17 10 43" src="https://user-images.githubusercontent.com/8074866/161434923-28839454-87ea-481c-94ce-c861dd3349ee.png">

**Comment by gasman** [comment]
Sorry, we can't provide troubleshooting for deployment problems here - please use our [support channels](http://docs.wagtail.io/en/stable/support.html).

**Comment by robslotboom** [comment]
Hey Gasman,

Found it, stupid me, it’s in NginX conf...

location ~ (\.php|\.aspx|\.asp|\.jsp|myadmin|wp-content|Autodiscover|console\**api**) {
        return 404;
}
