### ISSUE TITLE
Improve CI runs and concurrency

### ISSUE THREAD

**Issue by vinitkumar** [wagtail/wagtail#8276]
Github Actions are a nice CI system, the issue is that for concurrent runs, you have to wait for the previous job to finish and it gets annoying really fast. 

I helped implement a nice feature in django-cms, where you can cancel the past builds on a PR when new commits are pushed in the existing PR where a build was running.

**Comment by thibaudcolas** [comment]
Looks like we implemented this enhancement in #8277 – thank you @vinitkumar!
