### ISSUE TITLE
How to install the wagtail on mac os 

### ISSUE THREAD

**Issue by hrabizadeh** [wagtail/wagtail#829]
I run the pip command according your documentation and install all package, but when i create the mysampleproject with the "wagtail start mysampleproject" and then run the "python manage.py migrate" i encountered with this error:
/Library/Python/2.7/site-packages/treebeard/mp_tree.py:102: RemovedInDjango18Warning: `MP_NodeManager.get_query_set` method should be renamed `get_queryset`.
  class MP_NodeManager(models.Manager):

**Comment by jwogrady** [comment]
I agree. No dice brewing zlib1g-dev.
