### ISSUE TITLE
Admin displaying unstyled images and documents results listing

### ISSUE THREAD

**Issue by marts** [wagtail/wagtail#8291]
### Issue Summary

When searching images or documents in the Wagtail Admin it is possible to arrive at an unstyled results listing page. 

### Steps to Reproduce

1. Create a project,  login to admin and add some images and/or documents
2. Click Images on Wagtail sidebar
3. Start typing in a search term to filter the images (don't press return)
4. Check the urls for the images by hovering over them (?next=/admin/images/results/?q=[search term])
5. Select an image from the listing
6. Modify the image (e.g. change focal point) and press Save
7. Redirected to the 'next' view that is rendered without styling

I would expect we should be returned to the correct image listing but it seems the `/results/` in the 'next' parameter is messing things up ... remove this and the listing is correct.

I think it might be related to the `listing_results` change in 2.15:

"Isolate admin URLs for Documents and Images search listing results with the name `'listing_results'`"

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes (well a pretty fresh project)

### Technical details

* Python version: 3.9
* Django version: 4.0.3 and 3.2.12
* Wagtail version: 2.16.1
* Browser version: Firefox 98.0.2

**Comment by gasman** [comment]
Thanks for catching this, and for the detailed report! Looks like this was introduced in 2.16, in this commit: bafb4352ce9df41c1110555dcbf0c1f568775d7d
