### ISSUE TITLE
topic:: styling missing in Sphinx Theme documentation

### ISSUE THREAD

**Issue by dkirkham** [wagtail/wagtail#8323]
### Styling for topic:: in documentation is missing in Sphinx theme

There are four instances in the documentation that use the topic:: markup eg. [docs/advanced_topics/images/custom_image_model.rst#L53](https://github.com/wagtail/wagtail/blob/main/docs/advanced_topics/images/custom_image_model.rst#L53) where the text "Migrating from the builtin image model" appears.

These lines are written as headers, and the final HTML has them marked up with .topic and .topic-title styles but there is no corresponding CSS to style them.

### Steps to Reproduce

1. Compare https://docs.wagtail.org/en/stable/advanced_topics/images/custom_image_model.html#custom-image-model with https://docs.wagtail.org/en/v2.12.5/advanced_topics/images/custom_image_model.html. Note that in the latter, the text in question is in bold.

Latest:

<img width="904" alt="Screen Shot 2022-04-10 at 10 32 28" src="https://user-images.githubusercontent.com/1977376/162596267-4a92faa4-d504-46f6-9b2b-9eb4a1b8bf4d.png">

v2.12:

<img width="718" alt="Screen Shot 2022-04-10 at 10 34 27" src="https://user-images.githubusercontent.com/1977376/162596271-1c0bf264-bce2-4bfa-99c6-367f7bd75492.png">

These lines of "topic" text should appear in bold or some other more distinctive style. This could be solved with a change to Sphinx Wagtail Theme, or they should be migrated to an alternative header markup.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: N/A

### Technical details

* Wagtail version: problems appears from v2.13 onwards
* Four files affected:
  * docs/advanced_topics/embeds.rst
  * docs/advanced_topics/images/custom_image_model.rst
  * docs/reference/pages/panels.rst
  * docs/topics/search/indexing.rst

**Comment by lb-** [comment]
I think the solution would be to migrate these pages to markdown (this is our eventual goal) and then not use the topic directive but rather just plain headings.

**Comment by lb-** [comment]
Marking as good first issue. If anyone wants to pick this up. 
The four documentation pages linked above should be converted to markdown as per the documentation (latest linked). 
https://docs.wagtail.org/en/latest/contributing/documentation_guidelines.html

Remove the topic usage and instead replace with headers and maybe a reference if needed.

Ensure that any other usage of the topic throughout the docs gets replaced with the appropriate internal reference link.

**Comment by dkirkham** [comment]
Hi @lb-, 

Thanks for the pointers, I'll look at preparing a PR in coming days.

I only found four instances of topic:: across the entire documentation, so changing them to align with the rest of the doco makes sense.

**Comment by dkirkham** [comment]
Hopefully this isn't opening a can of worms. One of the four files, docs/advanced_topics/embeds.rst (see [Embeds](https://docs.wagtail.org/en/latest/advanced_topics/embeds.html) includes a list of attributes from a class near the bottom. I haven't found any Markdown versions in the overall documentation to give me a template to follow.

The existing rendering uses a definition list (dl/dt/dd). In the markdown version, I can get a rendering that is very similar _if_ I enable the Myst extension "deflist" - so that is something the core contributors might want to consider for endorsement before I go too far further.

The only visual difference I've noted is that the definition terms do not have permalink, unlike the original reStructuredText version. What I've read so far of the Sphinx doco suggests there might be a way to template the HTML, maybe a Sphinx guru will know if this is really possible. And there is a legitimate question regarding whether that permalink is worthwhile preserving?

For reference, the current reStructuredText-sourced HTML looks like this:

```html
<dl class="py attribute">
  <dt class="sig sig-object py" id="wagtail.embeds.models.Embed.url">
    <span class="sig-name descname">
      <span class="pre">url</span>
    </span>
    <a class="headerlink" href="#wagtail.embeds.models.Embed.url" title="Permalink to this definition"></a>
  </dt>
  <dd>
    <p>(text)</p>
    <p>The URL of the original content of this embed.</p>
  </dd>
</dl>
```

whereas the Markdown-sourced equivalent looks like this:

```html
<dl class="simple myst">
  <dt>url</dt>
  <dd><p>(text)</p></dd>
  <dd><p>The URL of the original content of this embed.</p></dd>
  ...
</dl>
```

**Comment by lb-** [comment]
Just wrap that class / attributes syntax in

```
```{eval-rst}
```

That's the escape hatch if we need to embed rst and there is not a nice markdown equivalent. 

For this syntax we would want to preserve the way rst shows it so that's fine.
