### ISSUE TITLE
Slim header issues

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8341]
- [x] The breadcrumbs toggle and all breadcrumb items should take up the full height of the header rather than leaving a gap at the bottom. The "More actions" trigger should also take the full height of the header.
- [x] For the same height issue, the breadcrumbs / toggle / "more actions" sit too high in the header bar compared to the center line.
- [x] Support issues with breadcrumbs toggle via keyboard:
  - [x] When activating the breadcrumbs’ toggle with the keyboard, the toggle icon doesn’t change.
  - [x] When closing the breadcrumbs with the keyboard, the toggle icon changes on the first trigger, and it takes a second trigger to have the breadcrumb closes
  - [x] After closing the breadcrumbs with the keyboard, it’s impossible to open them again.
- [x] When creating a page at the root level, the breadcrumb doesn’t display the usual "New: {page type}" last item
- [x] When creating a page at the root level, hovering the breadcrumb toggle causes a scrollbar to appear under it for a brief moment
- [ ] On mobile viewports, banner messages push the sidebar toggle out of position
- [x] When hovering the breadcrumbs, then activating the "More actions" dropdown toggle, the breadcrumbs subsequently close, leaving the More actions dropdown open out of alignment with its toggle
- [x] The "More actions" trigger is missing its tooltip to help understand its function
- [x] The focus outline of items within the "More actions" dropdown should stay within the dropdown

**Comment by phildexter** [comment]
+

[] Tooltip for secondary page menu three dots that says “Actions” on hover
[] Make the three dots actions menu part of the breadcrumb hover area when it’s open (so that it stays expanded), but not when it’s closed (so it doesn’t expand).

**Comment by thibaudcolas** [comment]
Closing – created https://github.com/wagtail/wagtail/issues/8449 for the last remaining item.
