### ISSUE TITLE
TableBlock throws Internal Server Error (500) on Debug=False mode.

### ISSUE THREAD

**Issue by thuwarakeshm** [wagtail/wagtail#8370]
### Issue Summary
I am **trying to add TableBlock** to my Streamfield body. I followed the instructions outlined in the official docs.
https://docs.wagtail.org/en/stable/reference/contrib/table_block.html

My Streamfield look like this:

```python
body = StreamField(
        [
            (
                "article",
                blocks.RichTextBlock(
                    features=[
                        "h1",
                        "h2",
                        "h3",
                        "h4",
                        "h5",
                        "h6",
                        "bold",
                        "italic",
                        "ol",
                        "ul",
                        "hr",
                        "link",
                        "document-link",
                        "image",
                        "embed",
                        "code",
                        "superscript",
                        "subscript",
                        "strikethrough",
                        "blockquote",
                    ]
                ),
            ),
            ("markdown", MarkdownBlock()),
            ("image", ImageChooserBlock()),
            ("quote", blocks.BlockQuoteBlock()),
            ("code", CodeBlock()),
            ("raw", blocks.RawHTMLBlock()),
            ("table", TableBlock()),
        ]
    )
```

This works perfectly in the development mode (`debug=True`)

Even when `debug=False` rendered pages are working fine. Yet, if I want to edit a page or add a new page I get an Internal Server error (the wagtail generated one.)

If I just turn `debug=True` again, the edit page works immediately. 

### Steps to Reproduce

1. Setup a basic wagtail project
2. Create a Blog Page model with stream field as instructed [this official doc](https://docs.wagtail.org/en/stable/topics/streamfield.html) 
3. Include `"wagtail.contrib.table_block"` to installed apps. 
4. add a table block (`from wagtail.contrib.table_block.blocks import TableBlock`) to the stream field. Mine was `("table", TableBlock()),` (see above code block)
5. In your settings (dev.py if you're using `runserver`, production.py if you're using it with gunicorn) toggle `debug` settings between `True` and `False`.
6. In the admin try adding a new page to the tree.

When debug=False, you get internal server error. 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes 

### Technical details

* Python version: 3.8.10.
* Django version: 4.0.3.
* Wagtail version: 2.16.1.
* Browser version: Chrome 100.

**Comment by Scotchester** [comment]
Could you please post the full stack trace for the Internal Server Error?

**Comment by thuwarakeshm** [comment]
Thanks @Scotchester for getting back to this. I resolved this issue. It's simply a missing static file. I ran `debug=False` without running `collectstatic`. 

But it's worth documenting the usage of staticfiles in the official doc : https://docs.wagtail.org/en/stable/reference/contrib/table_block.html

Something like, "This module uses static files, therefore you should run `python manage.py collectstatic` before you go to production.

**Comment by lb-** [comment]
We do state that you need to run collectstatic in the documentation for any upgrades. 

https://docs.wagtail.org/en/stable/releases/upgrading.html
