### ISSUE TITLE
Save/Preview Buttons icon and text layout issues in new Page Editor

### ISSUE THREAD

**Issue by dkirkham** [wagtail/wagtail#8377]
### Issue Summary

The Save Draft and Preview buttons at the bottom of the new Page Editor have a variety of issues with the layout of the text and icons within them.

### Steps to Reproduce

1. Start a project using the new page editor, eg. with Wagtail 3.0rc1
2. Navigate to an existing page and select edit
3. Observe the misaligned text baseline between the "Save draft" and "Preview":

<img width="504" alt="save-preview-firefox-wagtail-3 0rc1" src="https://user-images.githubusercontent.com/1977376/163704835-e7345e44-a841-4525-9beb-41b8571425f2.png">

4. In another browser tab, navigate to another page and add a child page
5. Observe that the "Save draft" and "Preview" baselines are better aligned but still not perfect:

<img width="517" alt="add-save-preview-firefox-wagtail-3 0rc1" src="https://user-images.githubusercontent.com/1977376/163705155-2cf620e9-1299-4f02-94ee-6ae885a679a4.png">

6. Observe that between the Add and Edit versions of the page, the icon in the "Preview" button is different in design and size; and that the button size consequentially is different
7. Observe that the Draft icon in the Save Draft button is slightly cropped on its right.

The new 3.0rc1 layout looks irregular and could be tidied up.
- Ideally the baselines of the text should align, and not be _slightly_ out of alignment - especially for nearby text in the same font/size.
- Ideally the icons should be displayed identically for the Add and Edit versions of the page, and better horizontally centred with the text.

Note. There were some alignment problems in older releases (like 2.15), but not so pronounced:
<img width="517" alt="save-preview-firefox-wagtail-2 15" src="https://user-images.githubusercontent.com/1977376/163705475-472de12c-d834-4285-ab84-5b34446d8879.png">

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: No, but some of these faults are visible in the hero image at https://github.com/wagtail/wagtail/discussions/8362

### Technical details

* Python version: 3.8, but unlikely to matter
* Django version: 3.2.13, but unlikely to matter
* Wagtail version: 3.0rc1
* Browser version: confirmed with Firefox 98.0.2 and Chrome 100.0.4896.127, both on MacOS 12.3.1; probably impacts other browsers.

**Comment by lb-** [comment]
Can confirm this is an issue, have validated myself.
I have also put this in the page editor 2022 project - FYI @thibaudcolas 

<img width="2048" alt="Screen Shot 2022-04-18 at 2 24 50 pm" src="https://user-images.githubusercontent.com/1396140/163755079-5f71abcc-24aa-4b89-8a49-b94ed2576ecd.png">

**Comment by lb-** [comment]
Thanks for raising this @dkirkham

**Comment by gasman** [comment]
Fixed in #8456.
