### ISSUE TITLE
Page content overlays on footer container

### ISSUE THREAD

**Issue by PaarthAgarwal** [wagtail/wagtail#8378]
### Issue Summary
Page content gets overlayed on the footer container containing "save draft" and "preview" buttons. I believe this is happening due to incorrect z indexing of content or of footer container.

### Steps to Reproduce

1. Go to Wagtail bakery demo admin.
2. In the page explorer go to the "About" or "Contact Us" page.
3. Scroll down and you will find content overlaying on the footer container.

Relevant screenshots:
![image](https://user-images.githubusercontent.com/86092410/163708961-3cb90576-9818-41ab-91a4-92f437f97830.png)
Further Illustrating:

https://user-images.githubusercontent.com/86092410/163709067-da82426a-19da-4915-9cf1-4c7c144a52b0.mp4

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

* Python version: Python 3.8.10
* Django version: Django 4.0.3 
* Wagtail version: Wagtail 3.0a0 
* Browser version: Chrome 98

**Comment by lb-** [comment]
@PaarthAgarwal I am having trouble reproducing this, I have tested on a few different browsers (see below), please can you double check you were running the latest `3.0` candidate branch and had run `npm ci` & then `npm run build`.

Seems odd to me that this would be an Edge or Windows only thing. Unless it is something funky with sidebars somehow?

All tested on macOS 12.3
* Firefox 99
* Chrome 102 & 100 (I do not have 98)
* Safari 15.4

<img width="2048" alt="Screen Shot 2022-04-18 at 2 24 50 pm" src="https://user-images.githubusercontent.com/1396140/163754309-10247622-d1d9-4358-bfef-bf9c2415c73c.png">

**Comment by PaarthAgarwal** [comment]
My branch was a few commits behind, which might have caused this. After fetching commits and rebuilding the frontend, it got fixed.
