### ISSUE TITLE
☂️ Migrate RST docs to Markdown - ongoing good first issue

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8383]
>  ☂️ **This is an epic / umbrella issue** 
> We expect this to be done in multiple PRs as it's better to change a few pages at a time, please reference this issue in any new PRs

### Description

* In early 2021 Wagtail began the move to Markdown documentation instead of RST (ReStructured Text) to make it easier for new developers to get started with the docs. 
* Our goal is to migrate all documentation to Markdown (.md) files. 
* If you want to contribute to these efforts it is a great way to get started with Wagtail contributions as you get to read the documentation and learn about our PR process. 

### How to work on this

* First, pick a section you feel you can migrate, see the list below, add a comment to this issue with what area you are keen to work on.
* Be sure to read the latest docs on how to use the markdown syntax - https://docs.wagtail.org/en/latest/contributing/documentation_guidelines.html
* A nice to have, but not required, is to also format the resulting markdown file with prettier, this can be done by commenting out the `.md` temporarily in the `.prettierignore` file and also updating the package.json formatting script by adding `.md` - then run your formatting on the files changed. Be sure not to commit the changes to the prettier config or package file though. 
* see the related PRs below for references to how this has been done for some parts of the docs already. 

### Sections

* [x] `docs/advanced_topics/api` - https://github.com/wagtail/wagtail/pull/8569
* [x] `docs/advanced_topics/customisation` - https://github.com/wagtail/wagtail/pull/8596
* [x] `docs/advanced_topics/images` - https://github.com/wagtail/wagtail/pull/8601
* [x] `docs/advanced_topics` (direct files only) - https://github.com/wagtail/wagtail/pull/8643
* [x] `docs/extending/**` - https://github.com/wagtail/wagtail/pull/8701
* [x] `docs/topics/search` - https://github.com/wagtail/wagtail/pull/8754
* [x] `docs/topics` (direct files only) - https://github.com/wagtail/wagtail/pull/8721
* [x] `docs/reference/contrib/modeladmin` https://github.com/wagtail/wagtail/pull/8443
* [x] `docs/reference/streamfield` - https://github.com/wagtail/wagtail/pull/8444
* [x] `docs/reference/contrib/**` (files within reference/contrib folder) https://github.com/wagtail/wagtail/pull/8568
* [x] `docs/support` (single page) https://github.com/wagtail/wagtail/pull/8756
* [x] `docs/releases/upgrading` (single page) https://github.com/wagtail/wagtail/pull/8769
* [x] `docs/reference` (direct files only) - https://github.com/wagtail/wagtail/pull/8759
* [x] `docs/contributing` - https://github.com/wagtail/wagtail/pull/8784
* [x] `docs/reference/pages` - https://github.com/wagtail/wagtail/pull/8881
* [x] `docs/reference/contrib` - https://github.com/wagtail/wagtail/pull/8779

### Previous PRs

* https://github.com/wagtail/wagtail/pull/8114
* https://github.com/wagtail/wagtail/pull/8372
* https://github.com/wagtail/wagtail/pull/8007

**Comment by lb-** [comment]
API pages done via https://github.com/wagtail/wagtail/pull/8569

**Comment by souzathg** [comment]
I'll continue working on this issue doing the '*docs/advanced_topics/customisation*' task

**Comment by lb-** [comment]
> I'll continue working on this issue doing the '_docs/advanced_topics/customisation_' task

Awesome! Just a reminder to build the docs locally and check for any errors. It's also a good idea to run `make clean` before `make html` after large changes. These commands are to be run inside the docs folder. Let me know if you need a hand.

**Comment by souzathg** [comment]
Thanks for the tipsand the willingness to help!
I got it! This time I'll use `make livehtml` also!

**Comment by souzathg** [comment]
Just for information, I'm currently working on converting `docs/advanced_topics` direct files

**Comment by lb-** [comment]
Awesome thanks @souzathg

**Comment by beingnoble03** [comment]
@lb- I would like to work on `docs/extending`.

**Comment by lb-** [comment]
> @lb- I would like to work on `docs/extending`.

Go for it

**Comment by saevarom** [comment]
I'd like to take `docs/topics`

**Comment by lb-** [comment]
> I'd like to take `docs/topics`

Go for it.

**Comment by lb-** [comment]
PR up for docs/topics/search/** https://github.com/wagtail/wagtail/pull/8754

**Comment by sandeep280993** [comment]
Hi @lb-  I would like to work on `docs/reference/pages`

**Comment by lb-** [comment]
@sandeep280993 go for it - however that docs section is a bit confusing with a large amount of it requiring use of `eval-rst` - if you wanted to go for a section that was a bit simpler first may I suggest one of the following;

* docs/reference/contrib (direct files only) 
* docs/reference (direct files only)
* or `docs/releases/upgrading.rst` (single file)

Up to you though, thanks for putting your hand up to help.

**Comment by sandeep280993** [comment]
Hi @lb- I would like to work on `docs/reference/pages`

**Comment by sandeep280993** [comment]
> 

OK. I'll take up `docs/releases/upgrading.rst` first

**Comment by lb-** [comment]
> OK. I'll take up `docs/releases/upgrading.rst` first

Awesome - thank you

**Comment by SilvestriStefano** [comment]
Hello, could I start working on `docs/contributing` ?

**Comment by lb-** [comment]
> Hello, could I start working on `docs/contributing` ?

Hi @SilvestriStefano thanks for putting your hand up to contribute. I recommend you look at a few files from the sections below if you are just getting started. You can just do one or two files initially to get a feel for the pull request process. 

docs/reference/contrib (direct files only)
docs/reference (direct files only)

**Comment by SilvestriStefano** [comment]
Sure I can start in `docs/reference` if you prefer.

**Comment by lb-** [comment]
I am aiming to pick up `docs/reference/contrib`

**Comment by saevarom** [comment]
I'd like to work on `docs/contributing`

**Comment by sandeep280993** [comment]
@lb- I would like to work on pending files, if available.

**Comment by lb-** [comment]
> @lb- I would like to work on pending files, if available.

Go for it. The only section left is docs/reference/pages. Have a look and see how you go. It's ok if you put a PR up with just a few in that folder.

**Comment by lb-** [comment]
As of Wagtail 4.0 - all core documentation will be in markdown and not RST - finishing off a ~18 month migration to markdown.

Thanks to everyone who took time to contribute to this, it will now be much easier for new contributors to be able to update the documentation.
