### ISSUE TITLE
Login brute forcing protection

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#839]
Does Django/Wagtail already block login hammering? As its popularity increases it's inevitable a site will come to the attention of ne'er-do-wells. It would be good if it were as secure as possible before that occurs.

**Comment by gasman** [comment]
Django's use of computationally-intensive hash functions (with a work factor that's regularly raised in new Django releases) will tend to mitigate password brute-force attacks. Additional measures, such as rate-limiting or blocking after a certain number of failed logins, would be better handled outside of Wagtail core I think.

**Comment by stevejalim** [comment]
If anyone lands here via search results, this is how I used django-ratelimit with Wagtail a while ago, and the pattern still seems to hold up

https://github.com/mdn/developer-portal/pull/1673
