### ISSUE TITLE
PageChooser widget behaviour settings

### ISSUE THREAD

**Issue by OndraRehounek** [wagtail/wagtail#8401]
### Is your proposal related to a problem?

We are building Wagtail CMS for tens of (similar) sites and we are kind of struggling to manage content when we are selecting site in PageChooserPanel or PageChooserBlock. We are facing two obstacles we weren't able to resolve on our own.
 - Page size for chooser is hardcoded on admin.views.chooser:183
 - We canot prevent editors to select pages only for the site of page edited

### Describe the solution you'd like

Have page_size option for the page chooser widget (and/or) option to limit selection to the site of the edited page.

### Describe alternatives you've considered

We tried to filter page_queryset in the "construct_page_chooser_queryset" hook . However we weren't able to find robust solution to get current page site (we used regex of `request.META.get("HTTP_REFERER")` to extract edited page id or parent page id when adding new page) plus it's kind of inconvinient to have this hook registered for all the modules (apps) since we need this feature only for cca 10 of 100 Page models in our project.

### Additional context

We have considered if it could be helped using page permissions but the issue https://github.com/wagtail/wagtail/issues/7099 which led us eventually to the discussion https://github.com/wagtail/wagtail/discussions/7521 and it seems that idea of more segrated pages is rather a distant future feature.

We can also try to come up with our own solution and create PR but little push in the right direction would be appreciated.

**Comment by lb-** [comment]
https://github.com/wagtail/wagtail-generic-chooser is a good option if you are trying to do more complex page choosing scenarios.

The plan is, eventually, to bring parts of that code into Wagtail core.

It might be a good chance for you to use that library and see if it fits your needs, if so please report back or otherwise raise an issue on that repo.

**Comment by OndraRehounek** [comment]
@lb- thank you very much! I will report back as soon as possible.

**Comment by lb-** [comment]
@OndraRehounek could you please put your specific use case and ideas on 

https://github.com/wagtail/wagtail/issues/1250

I know that issue is older but it has a lot more context and comments and duplicates (I think) the same goal raised here.
