### ISSUE TITLE
Feature request for adding a caption to images in the library

### ISSUE THREAD

**Issue by wimfeijen** [wagtail/wagtail#8405]
Hi,
 
As a mature CMS, I would like images to have captions by default. 

I know I can create them using https://docs.wagtail.org/en/stable/advanced_topics/images/custom_image_model.html, but I believe Wagtail CMS would be more complete by supporting a caption field out of the box. The field would be optional, so not in the way.

I would be more than happy to write a pull request.

Thanks,

Wim

**Comment by gasman** [comment]
Hi @wimfeijen,
We've chosen not to do this for the default image model, for reasons detailed in https://github.com/wagtail/wagtail/issues/6034#issuecomment-629424087.

**Comment by wimfeijen** [comment]
Hi @gasman , thanks for your response and investment in Wagtail! 

In my opinion, it would be preferable for Wagtail to follow other mainstream CMSes, like for example WordPress. I think adding a caption would not be in the way of other programmers striving for a more perfect solution in an ideal world, because they can easily program their own solution. 

Also my personal belief is that such a perfect context-related solution would be difficult to use for editors.

Finally, according to the Zen of Python: "Simple is better than complex." 

Thanks for hearing me out, and again thanks your time and investment in Wagtail. No matter what your decision is, please do see my opinion as a way to make Wagtail more beautiful.

**Comment by tomdyson** [comment]
Thanks for your thoughts @wimfeijen! We really appreciate your participation.
