### ISSUE TITLE
Original renditions not really original 

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/wagtail#8425]
### Issue Summary

When uploading an animated WebP image to Wagtail and rendering it with the `original` option, the image is not animated anymore. 

It appears that some conversion of the image is applied although the original is requested. I am not sure if this is a bug or if I am looking for a feature to by pass the image manipulation during rendition generation. E.g. a "copy" option, which only copies the image file from `original_images` to `images` without any manipulation applied. 
 

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit the following files
```python
# home/models.py
from django.db import models

from wagtail.core.models import Page
from wagtail.images import get_image_model_string, edit_handlers


class HomePage(Page):
    image = models.ForeignKey(
        get_image_model_string(),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    content_panels = Page.content_panels + [
        edit_handlers.ImageChooserPanel('image')
    ]

```

```html+django
{% extends "base.html" %}
{% load static wagtailimages_tags %}

{% block content %}
    <h1>Home</h1>
    {% image page.image original %}
{% endblock content %}

```

```
# myproject/settings/base.py
...

WAGTAILIMAGES_FORMAT_CONVERSIONS = {
    'webp': 'webp',
}

```

4. Make migration, apply migrations.
5. Create a super user, start the server, visit the admin
6. Upload an animated WebP image. E.g. https://ezgif.com/images/format-demo/butterfly-small.webp
7. Select the uploaded image as the image on the home page.
8. View the home page and notice that the image is not animated anymore. 

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (**yes** / no)

### Technical details

* Python version: 3.9.9
* Django version: 4.0.4
* Wagtail version: 2.16.2
* Browser version: Firefox Nightly 101.0a1, Safari 15.4

**Comment by chosak** [comment]
Hi @tbrlpld - this reminds me of #3210. On that issue there's a comment https://github.com/wagtail/wagtail/issues/3210#issuecomment-285027754 (albeit from 2017, so may warrant reconsideration) with a recommended workaround to use `image.file.url` as a way to serve the raw, original image, bypassing any Wagtail rendition code. Would this work for your purpose?

**Comment by tbrlpld** [comment]
Wow. Thanks @chosak, that issue describes what I was thinking but way more eloquent and succinctly! Thank for the pointer! I somehow missed that one in my search.

My issue is also fairly similar. I only started thinking of animated WEBP after GIF resizing with Wand was crashing my containers and servers.

I guess the `image.file.url` work around should work. It will just require a custom image model and some form of detection logic (or a flag). 

Since you are also already suggesting the "raw" filter in #3210 already, this issue is not really adding anything new to the discussion and I will close in favor of that one.
