### ISSUE TITLE
Avatar image cropping doesn't render as a square when uploaded avatar image isn't a perfect square. 

### ISSUE THREAD

**Issue by KalobTaulien** [wagtail/wagtail#8428]
### Issue Summary
When uploading a new user avatar and the image is not a perfect square, the image gets cut off and doesn't display properly. 
![image](https://user-images.githubusercontent.com/4743971/165134303-7ffa296e-2a2f-4819-af13-ec05af6d4613.png)

### Steps to Reproduce

1. Open your user settings.
2. Upload a non-square image and save
3. Renditions don't show up as squares (rounded by CSS) 

### Technical details

* Python version: 3.9
* Django version: 4.0.3
* Wagtail version: 4.0a0
* Browser version: https://www.whatismybrowser.com/w/R6C7DFC

**Comment by lb-** [comment]
Can confirm, this is an issue but it looks like it has been an issue for a while, I do not think this is a 3.0 regression.

Square image - renders ok

<img width="1459" alt="Screen Shot 2022-05-11 at 9 57 16 pm" src="https://user-images.githubusercontent.com/1396140/167845188-dda8eb98-8f60-4232-ac5f-d5112245434c.png">


Non-square image - cut off

<img width="1470" alt="Screen Shot 2022-05-11 at 10 02 54 pm" src="https://user-images.githubusercontent.com/1396140/167845249-f728e869-e9a5-48f9-b630-38cc1b3cee6a.png">
