### ISSUE TITLE
Even superadmin don't have permission to a maysterious area "when copying a page into itself" !

### ISSUE THREAD

**Issue by hazho** [wagtail/wagtail#8432]
When copying a page into itself the view raises an error and include it in message notification telling that "you don't have permissions to access this area" Even if the user is superadmin and the area is not known "maysterious area"

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project

### Technical details

* Python version: 3.9.
* Django version: 4.04
* Wagtail version: both (2.16.2 & 3.0-rc2)
* Browser version: multiple browser

**Comment by hazho** [comment]
![image](https://user-images.githubusercontent.com/20362375/165156590-d4fe9c22-f9ae-4144-ac34-01fce18a6c6f.png)
![image](https://user-images.githubusercontent.com/20362375/165156670-12482062-91e3-476a-ab4f-5a261d966c6b.png)

**Comment by hazho** [comment]
![image](https://user-images.githubusercontent.com/20362375/165156797-3a08c0a0-be68-4596-8b10-9d09832c8b08.png)

**Comment by lb-** [comment]
@hazho this worked fine for me, I could copy a page onto itself, where the new copy would be a 'child' of the page that is being copied.

Please can you provide more detail to reproduce, for now I think we can close this based on the steps provided.
