### ISSUE TITLE
Docs request: Explanation of 'wagtail start' structure

### ISSUE THREAD

**Issue by JoanEliot** [wagtail/wagtail#8437]
[Wagtail central tells ](https://docs.wagtail.io/en/v2.11.2/getting_started/demo_site.html) newcomers to use `wagtail start` and also to refer to the bakerydemo, but the two resources seem to involve wildly different project structures. This novice is confused. 

Is there a document that compares and contrasts the two (types of) structures and explains how to switch between them? How do we take the output of `wagtail start` and modify it in imitation of the bakery demo (and still have a working site)? 

If it's not practical to modify the structure of a `wagtail start-`based project so that it's similar to that of the bakery demo, maybe you could just add a clear caveat to that effect in the readme. Something like: "Alert: don't try to change the structure of a project you create with `wagtail start`to correspond to that of the bakery demo, or vice versa. It's too easy to break things. If you want a structure like the one we use in this project you'll need to create your project from scratch."

In any case, please consider revising the "Next steps" section of the readme. Aside from the possible circular reference problem, some brief word of caution about the divergent structures and the (hours of) confusion those differences may cause seems in order before we are advised to run `wagtail start` as a next step. (That paragraph back at Wagtail central could use some similar edits.)

[Differences: A `wagtail start`-based project locates its apps in the root folder, it separates out the home page into this curious, tiny 'home' app, and it puts templates and static files into app-specific subfolders. The bakery demo by contrast treats all the apps as subsidiaries of one "master app," it provides global template and static folders, and it pleasingly integrates the home page into a "miscellaneous" app, base.]

**Comment by sayantani11** [comment]
@thibaudcolas I can try this

**Comment by gasman** [comment]
I think this might already be covered by https://docs.wagtail.org/en/stable/reference/project_template.html.

**Comment by thibaudcolas** [comment]
Hmm indeed! I’ll close this now, but @sayantani11 if you want to make a pull request to help with this – I think adding a link to https://docs.wagtail.org/en/stable/reference/project_template.html mentioned by Matt might go a long way.

For example adding a link here: https://github.com/wagtail/wagtail/blob/main/docs/getting_started/tutorial.md#generate-your-site. Something along the lines of "For an overview of everything this command generates, take a look at our project template reference".
