### ISSUE TITLE
Prompt the user about unsaved changes for snippets

### ISSUE THREAD

**Issue by RandomJo** [wagtail/wagtail#8453]
### Describe the solution you'd like

It would be great if the check for unsaved changes could happen for snippets like it does for pages in Wagtail.

### Describe alternatives you've considered

I was able to get this working in my project by overriding the snippet edit and create template files. Here's an example with the create template:
 
```
{% extends "wagtailsnippets/snippets/create.html" %}
{% load i18n %}

{% block extra_js %}
    {{ block.super }}

    {% trans "This page has unsaved changes." as confirmation_message %}
    <script>
        $(function() {
            enableDirtyFormCheck(
                'form[action*="snippets"]',
                {
                    confirmationMessage: '{{ confirmation_message|escapejs }}',
                    {% if edit_handler.form.errors %}
                        alwaysDirty: true
                    {% endif %}
                }
            );
        });
    </script>
{% endblock %}
```

This would be more resilient though if the create/edit forms had an actual id for targeting with jQuery. The way I'm targeting the action could possibly change in the future if the URL for the action changes. Heads up that I'm using Wagtail 2.11 currently. I believe newer versions include some other options to enableDirtyFormCheck, which is why I'm just logging an issue rather than forking and submitting a pull request. I'm not certain how the new options might affect the finished code.

**Comment by lb-** [comment]
While not specifically dirty form check, some pre-work to make it easier to share this logic across non-page forms has been created #10091

**Comment by lb-** [comment]
Once https://github.com/wagtail/wagtail/pull/11373 is merged, we will have a clear path forward to adding unsaved warnings to the Snippets form.

Note that `enableDirtyFormCheck` will still work for a few releases but will be removed in the future, it's an undocumented approach to do this.

**Comment by lb-** [comment]
This feature will be in Wagtail 6.3
