### ISSUE TITLE
Tippy.js warning message in the console

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8462]
The functionality seems to be working as expected but worth having a look:

> tippy.esm.js?6f9a:304 tippy.js`multiple` is not a valid prop. You may have spelled it incorrectly, or if it's a plugin, forgot to pass it in an array as props.plugins. All props: https://atomiks.github.io/tippyjs/v6/all-props/. Plugins: https://atomiks.github.io/tippyjs/v6/plugins/👷‍ This is a development-only message. It will be removed in production.

![tippy-warning](https://user-images.githubusercontent.com/877585/165984839-0071a4a1-589f-419d-9c53-5d0efdf4b356.png)

**Comment by stevedya** [comment]
This will be addressed as part of #8468

**Comment by thibaudcolas** [comment]
Fixed in #8468.
