### ISSUE TITLE
Bulk Actions - Ability to use modifier (shift) + click to select multiple items at once

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8490]
### Is your proposal related to a problem?

When using Gmail, Google Drive, or Jira - bulk select provides an intuitive way to select multiple adjacent items at once with the keyboard `shift` + click modifier.

When doing the same action with Wagtail's bulk actions, the checkboxes are not all selected and the text between the last checked item and the just checked item gets highlighted.

![Screen Shot 2022-05-05 at 7 23 36 pm](https://user-images.githubusercontent.com/1396140/166897128-c1dd8c14-f2a8-4f54-8a81-3df2634cab88.png)

### Describe the solution you'd like

* On any pages within Wagtail admin that provide the bulk actions functionality there should be the ability to select multiple using the `shift` keyboard modifier when clicking.
* Example: Items 1, 2, 3 are checked, user checks item 4, then holds shift, clicking item 6 should also select item 5 (between them)
* Example: Item 3 is checked, user checks item 1, then holds shift to select item 4, item 2 (the previously unchecked one betweeN0 and item 4 get checked.
* Keyboard modifier may need to be different on different operating systems, `shift` is used as the example but it might need to be something else like `alt` on some devices.
* The existing bulk actions code would need to be modified to track the 'last' checked item for this to be built.

### Describe alternatives you've considered

* It would be possible to build this with some custom JS added via a hook
* Not implement this due to not all users knowing about the ability to use click modifiers

### Additional context

* Breakdown of how the shift/alt + click works for Google drive (see item 2) https://uxdesign.cc/the-bulk-experience-7fcca8080f82 plus other approaches
* UX Stack exchange discussion of this https://ux.stackexchange.com/a/113913
* `client/src/entrypoints/admin/bulk-actions.js` - `onSelectIndividualCheckbox` would need to keep track of the last checked item and also accept a new param (isMultiSelect) and then if the modifier key is active, recursively call `onSelectIndividualCheckbox` for the 'previous' checkbox in the DOM until it gets to the stored last checked item. Finally, it would update the last checked item for any subsequent clicks.

**Comment by Hitansh-Shah** [comment]
Hey @lb- . can I work on this issue? I would love to research on this.

**Comment by lb-** [comment]
@Hitansh-Shah go for it - the code is in [`client/src/entrypoints/admin/bulk-actions.js`](https://github.com/wagtail/wagtail/blob/main/client/src/entrypoints/admin/bulk-actions.js)

I would start by adding some logging to the `onSelectIndividualCheckbox` and seeing if you can keep track of the 'previously clicked' checkbox and work out the checkboxes between the last clicked one.

Note: We may also want to handle un-check behaviour.
