### ISSUE TITLE
Project template settings files causes unexpected behavior

### ISSUE THREAD

**Issue by sethrh** [wagtail/wagtail#850]
In the project template, the django settings are broken out into base, dev, production, etc. 

The `__init__.py` file, however, does this: 

```
from .dev import *
```

This means that when you set the DJANGO_SETTINGS_FILE to 'settings.production', python loads modules something like this: 
- dev.py
- base.py (imported in dev.py)
- local.py (if it exists, imported in dev.py)
- production.py
- base.py (imported again in production.py, but since it's already been imported nothing here will apply)
- local.py (if it exists, but again, it's already been imported so nothing will apply)

This causes unexpected development settings to appear in my production deployments. 

This method of using settings is really complex and the side-effects are subtle (I've probably got the load order wrong).

I suggest refactoring it to a simpler method - such as a settings.py which is a good default for development settings, and then a settings_production.py which imports and overrides the defaults where appropriate.

**Comment by miracle2k** [comment]
The auto-generated dev settings file contains this line:

    for template_engine in TEMPLATES:
        template_engine['OPTIONS']['debug'] = True

Unless I am mistaken, this is the problem described here in action. These changes will leak into the production settings.

**Comment by gasman** [comment]
I believe those particular lines are redundant - it just needs someone to double-check that: #2078
