### ISSUE TITLE
Comment-Overlays outside the view in the new Page Editor

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#8500]
### Issue Summary

On long editor pages, when you've scrolled down, clicking on the comment icon of any block in the current view opens the comment-overlay, but you have to scroll up to find it somewhere.
Further, if you click somewhere on these overlays (e.g. the text field), they jump up/down depending on your scroll position.

### Steps to Reproduce

1. Start a new project described [here](https://github.com/wagtail/wagtail#-getting-started) with wagtail [3.0rc3](https://github.com/wagtail/wagtail/releases/tag/v3.0rc3)
2. runserver
3. Open the created home page in the CMS: http://127.0.0.1:8000/admin/pages/3/edit/
4. You can simulate a large content area by resizing the browser to a height of 300px, open the [promote tab](http://127.0.0.1:8000/admin/pages/3/edit/#tab-promote)
5. Start commenting by clicking the "Comments" icon at the top, scroll down to "Show in menus" for example and click the icon to add a comment.
6. Now, there is no overlay in the current view, you have to scroll up. Also check, what happens if you click into the text field of the overlay, or somewhere else (sry, this effect reminds me a bit of https://www.youtube.com/watch?v=yUdpj3gJofQ).

I've tested it with the latest 2.16.2, no problems here, with the new page editor in 3.0 those issues occur.

### Technical details

* Python version: 3.10
* Django version: 4.0.4
* Wagtail version: 3.0rc3
* Browser version:
  * Google Chrome 101.0.4951.54 (Linux Mint/Ubuntu)
  * Firefox 100.0 (Linux Mint/Ubuntu)

**Comment by gasman** [comment]
Confirmed, thanks! From a bit of experimenting, I think the bug is that it's finding the vertical offset of the form field relative to the browser viewport (_not_ the document), and positioning the comment box that far down from the top of the document.
