### ISSUE TITLE
Remove trailing slash from WAGTAILADMIN_BASE_URL  in Docs

### ISSUE THREAD

**Issue by marts** [wagtail/wagtail#8512]
Remove trailing slash from WAGTAILADMIN_BASE_URL  in `/docs/reference/settings.rst` for consistency with the project template

### Pertinent section of the Wagtail docs 

https://github.com/wagtail/wagtail/blob/main/docs/reference/settings.rst#wagtailadmin_base_url

### Details

The current project template has this:

```
# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"
```

See: https://github.com/wagtail/wagtail/blob/74ed301562af6bdfabe2b0c0d3d7789b319b5ce2/wagtail/project_template/project_name/settings/base.py#L164

The reference docs include the trailing slash in the URL...

```
WAGTAILADMIN_BASE_URL = 'http://example.com/'
```

Probably just need to be consistent here as to what is the correct setting, which I'm assuming means removing the trailing slash from the example given in the reference docs.

**Comment by lb-** [comment]
Flagging as good first issue.

**Comment by PaarthAgarwal** [comment]
I'm on it
