### ISSUE TITLE
Dropping Safari 14 support (late 2023)

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8520]
|:warning: **Only to be done after Safari 17 is released**|
|-----|

Follow up from https://github.com/wagtail/wagtail/pull/8051 & https://github.com/wagtail/wagtail/pull/8497 where the goal is to use [CSS logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) only for positioning.

Support for `border-start-start-radius`, `border-start-end-radius`, `border-end-start-radius` and `border-end-end-radius` properties are not included until [Safari 14](https://caniuse.com/css-logical-props) and our current support is for the last 3 versions of Safari.

**Comment by zerolab** [comment]
Once we drop Safari 14, let's us drop the default webp to png conversion from https://github.com/wagtail/wagtail/blob/32ff36446b0913c3180d23848552287726a228cc/wagtail/images/models.py#L933 (ref: https://caniuse.com/webp)

**Comment by lb-** [comment]
With Safari 17 now out - this issue can be reviewed. 

https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes

**Comment by thibaudcolas** [comment]
@lb- I’m working on this currently :)

---

[View caniuse Safari 14 vs 15.6](https://caniuse.com/?compare=safari+14.1,safari+15.6&compareCats=CSS,HTML5,JS,JS%20API,Other,Security,SVG)

### JavaScript

Nothing particularly substantial – view [ES2016+ compat table](https://compat-table.github.io/compat-table/es2016plus/)

- ECMA2022 except _[Class static initialization blocks](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Static_initialization_blocks)_. See [ECMA 2022 compat data](https://caniuse.com/?feats=mdn-javascript_builtins_array_at,mdn-javascript_builtins_regexp_hasindices,mdn-javascript_builtins_object_hasown,mdn-javascript_builtins_error_cause,mdn-javascript_operators_await_top_level,mdn-javascript_classes_private_class_fields,mdn-javascript_classes_private_class_methods,mdn-javascript_classes_static_class_fields,mdn-javascript_classes_static_initialization_blocks).
- ECMA2023 (Array.findLast, Array.findLastIndex, Hashbang)

### CSS

- `color()` function
- Logical Properties
- Small, Large, and Dynamic viewport units
- CSS Scroll-behavior
- LCH and Lab color values
- :has() CSS relational pseudo-class
- CSS Containment
- CSS Cascade Layers

## DOM APIs

- [createImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap)

## HTML

- theme-color meta tag

**Comment by thibaudcolas** [comment]
This is out of date and should have been closed, my bad.

@zerolab when we make changes based on support targets it’s generally about the admin UI. I think dropping this conversion has merits but it’s very different to change how the Wagtail admin works for its editors / admin users, and how the site would work for end users. So I’d recommend a separate ticket for that (see #11681).
