### ISSUE TITLE
"page_description" does not work with lazily translated strings

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#8523]
### Is your proposal related to a problem?

The new, optional `page_description` attribute added with wagtail 3.0 (https://github.com/wagtail/wagtail/pull/8164) currently only allows simple `str` values. This does not work well in multi-language environments, where these class attributes will have to be lazily translated strings (using `gettext_lazy`).

You can still override the classmethod `wagtail.models.Page.get_page_description()`, so it is not a big issue, but it would be nice to be able to write something like the following (taken from the docs https://docs.wagtail.org/en/latest/topics/pages.html#page-descriptions):
```python
from django.utils.translation import gettext_lazy as _
...
class LandingPage(Page):
    page_description = _("Use this page for converting users")
```

### Describe the solution you'd like

I don't have a perfect solution right now, but maybe check the "_meta" for existing fields instead of the current `isinstance` check?
https://github.com/wagtail/wagtail/blob/091cc4589182ec1cdd45576cd99445c73439425f/wagtail/models/__init__.py#L1510

**Comment by gasman** [comment]
Thanks for reporting!

[Elsewhere](https://github.com/wagtail/telepath/blob/f4165bbd2950e30066fddfbd30db89ab8a2190aa/telepath/__init__.py#L343) I've used `isinstance(obj, Promise) and obj._delegate_text` this for identifying lazy translation strings (actually that should probably be `getattr(obj, '_delegate_text', None)`) - maybe that would work here?

**Comment by th3hamm0r** [comment]
Sounds good, I searched for such a "lazy()"-detection, but missed that. Now, with your info, I can try a PR.

**Comment by th3hamm0r** [comment]
Done with #8527
