### ISSUE TITLE
Remove Page.get_static_site_paths

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#8535]
Wagtail's ``Page`` model has a ``get_static_site_paths`` method that was originally added because Wagtail had a contrib module for static site generation.

That contrib module was removed years ago so I think we should remove this unused method and its tests

https://github.com/wagtail/wagtail/blob/7d384e70c12f857c1932a18caf1d511c64ef3999/wagtail/models/__init__.py#L1868-L1879

**Comment by PaarthAgarwal** [comment]
I'll give it a try

**Comment by gasman** [comment]
Presumably there's a fair chance that third-party packages (e.g. wagtail-bakery) are depending on this? If so, this should probably go through the deprecation process.

**Comment by zerolab** [comment]
fwiw, https://cs.github.com/?q=.get_static_site_paths() doesn't reveal anything of note

**Comment by nimasmi** [comment]
> fwiw, https://cs.github.com/?q=.get_static_site_paths() doesn't reveal anything of note

It's used in the wagtail bakery tests: https://github.com/wagtail/wagtail-bakery/blob/ff85d6b068a7e7bc2a707fb90df7aef8562f6b9a/tests/models.py#L26

**Comment by ArijeetBanerjee** [comment]
I want to work on this issue. kindly give me permission and access to work on this issue
