### ISSUE TITLE
Upgrade notification (dashboard/home) is not translated 

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8537]
### Issue Summary

Upgrade notification is not translated 

### Steps to Reproduce

1. Change your admin user language to non-english 
2. Be on an older version of Wagtail 
3. Sign in as an admin user
4. Observe the admin upgrade notification
5. Expected - it should match the user's language
6. Actual - it is still in English

Any other relevant information. We may no consider this a bug or we may not have addressed it as the translation would contain a lot of HTML. 

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

https://github.com/wagtail/wagtail/blob/33552136559f1d6b33950858e8bd89364087240c/wagtail/admin/templates/wagtailadmin/home/upgrade_notification.html#L4

**Comment by rme7** [comment]
I would like to give this one a shot if it is not in the works yet

**Comment by lb-** [comment]
Go for it. 

I have a potential fix in a different PR I am working on. 

See this file. 

https://github.com/lb-/wagtail/blob/f6be7dc8ed40f5f39c29d9ec4d1410921a3e57e3/wagtail/admin/templates/wagtailadmin/home/upgrade_notification.html

You could use that code (but without the data attribute changes)

Hope that makes sense. 

Note - to test this out is a bit tricky - you will either have to get a browser extension to fake a different response or temporarily change the version template tag to return something like '2.0'.

**Comment by lb-** [comment]
@rme7  sorry for the confusion but some other PRs were working on the same area of code so it made sense to fix this issue up as part of that.

Let us know if you are still keen to pick up something for a Wagtail PR.
