### ISSUE TITLE
Setting WAGTAILSEARCH_BACKENDS=None fails on search instead of using default search backend

### ISSUE THREAD

**Issue by pmlanger** [wagtail/wagtail#8546]
### Issue Summary

In my Django settings, I define the `WAGTAILSEARCH_BACKENDS` setting with the return value of a function: Depending on an environment variable passed in, this function returns `None` to tell Wagtail to use the default search backend, or the actual config:

```python
# Django settings file
WAGTAILSEARCH_BACKENDS = search_config()
```

```python
def search_config():
  if os.environ.get('USE_MY_SEARCH_BACKEND'):
    return { some_config }
  return None
```

This code makes the [search_backends variable here](https://github.com/wagtail/wagtail/blob/main/wagtail/search/backends/__init__.py#L17) be set to `None`, which is why calling `setdefault` on [that variable here](https://github.com/wagtail/wagtail/blob/main/wagtail/search/backends/__init__.py#L20) fails with: 

```
[  ...  ]
  File "lib/python3.7/site-packages/wagtail/search/backends/__init__.py", line 52, in get_search_backend
    search_backends = get_search_backend_config()
  File "lib/python3.7/site-packages/wagtail/search/backends/__init__.py", line 20, in get_search_backend_config
    search_backends.setdefault('default', {
AttributeError: 'NoneType' object has no attribute 'setdefault'
```

### Steps to Reproduce

1. Set `WAGTAILSEARCH_BACKENDS=None`
2. Run server, go to `http://localhost:8000/admin/pages/search/?q=hi` (change host/port accordingly, value of `q` could be anything)
3. Observe the error mentioned above.

> Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I would have expected the `WAGTAILSEARCH_BACKENDS` setting, when set to `None`, to default to the default search backend (and not fail). 

> I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

_(Should be independent of all these, because that's what the code in main still does)_

* Python version: `Python 3.7.9`
* Django version: `Version: 3.2.12`
* Wagtail version: `Version: 2.15.4`

If you should agree to make this change, I would be happy to help with a PR.

**Comment by gasman** [comment]
> I would have expected the `WAGTAILSEARCH_BACKENDS` setting, when set to `None`, to default to the default search backend (and not fail).

I don't think this is a valid expectation - there's no precedent set by Django that a setting with the value None should be interpreted as "use the default". For example, setting `TEMPLATES = None` also fails in a similar way.

**Comment by pmlanger** [comment]
I don't know about precedence in Django, but in general I would prefer an error at "server start time" (or a reasonable default that avoids it) over one at runtime (as the case here).
