### ISSUE TITLE
Django 4.1 compatibility - log out view change to POST

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8559]
## Overview

* In Django 4.1 - Logging out via GET requests to the built-in logout view is deprecated. Use POST requests instead.
* https://docs.djangoproject.com/en/dev/releases/4.1/#log-out-via-get
* This could possibly break our log out links (e.g. the sidebar admin sub-menu) and should be reviewed as we look to Django 4.1 support

## Details

* We have a custom view [`LogoutView`](
https://github.com/wagtail/wagtail/blob/52e5abfe62547cdfd90ea7dfeb8bf5a52f16324c/wagtail/admin/views/account.py#L378) that may cause this to be non-issue
* We have the log out link provided as a link only - see https://github.com/wagtail/wagtail/blob/52e5abfe62547cdfd90ea7dfeb8bf5a52f16324c/wagtail/admin/templatetags/wagtailadmin_tags.py#L840-L842
```
        sidebar.LinkMenuItem(
            "logout", _("Log out"), reverse("wagtailadmin_logout"), icon_name="logout"
        ),
```

**Comment by kaedroho** [comment]
We currently have our own log out view, so this might not affect us now. If it doesn't, I think we should consider updating this to match Django.

https://github.com/wagtail/wagtail/blob/2a403337701337a00c8bff405ff005160a69a5ff/wagtail/admin/views/account.py#L375-L395

**Comment by gasman** [comment]
Adding to the 5.2 milestone as I believe this will need to be addressed when we start supporting Django 5.0 (which removes the ability to log out through a GET request from LogoutView). Having our own LogoutView class doesn't help us, as it's just wrapping Django's implementation - I suspect the call to `super().dispatch` will fail with an 'unsupported HTTP method' error.

**Comment by laymonage** [comment]
@gasman Hasn't this been addressed in https://github.com/wagtail/wagtail/pull/9974?

**Comment by gasman** [comment]
@laymonage It has indeed! That must be why our CI test run against Django main isn't reporting any failures relating to logouts, then :-)
