### ISSUE TITLE
User and ModelAdmin Chooser

### ISSUE THREAD

**Issue by uroybd** [wagtail/wagtail#8561]
If we want a Chooser modal except for Page, we have to register them as snippets.

However, Users and Models registered using ModelAdmin are already available to edit.

UserChooser will be a very good UX improvement in many cases. For example, allow the `owner` field to be editable by Admin and Moderator and add that in the Page's editing interface. It will currently show a list widget since the user model is not marked as a snippet.

Similarly, Models registered with ModelAdmin must have a SnippetChooser-like interface without the redundant registering.

**Comment by gasman** [comment]
Thanks for the suggestion! We're currently working on adding the ability to set up a chooser for any model type, and the work on this is being tracked in #8480. In the meantime there are a few add-on packages to provide this feature, such as https://github.com/wagtail/wagtail-generic-chooser.
