### ISSUE TITLE
Replace human-readable-date hover switcheroo pattern with accessible tooltips

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8566]
We have a well-established pattern in the admin interface, to show relative times by default ("3 months ago"), with a switch to absolute date-times on hover:

![human-readable-date](https://user-images.githubusercontent.com/877585/169317860-806cf880-3dc4-4082-8caa-8bd6d79ebaa7.gif)

Here is the markup:

```html
<div class="human-readable-date" title="May 19, 2022, 1:31 p.m.">Just now</div>
```

This feels a bit basic, and there are a number of issues stemming from this approach:

- There is no affordance of this capability – you have to have stumbled upon it once to become aware of the pattern.
- Since this isn’t applied on interactive HTML elements, it’s impossible for keyboard users to see the date-times.
- Changing the text on hover is a bit inelegant – makes it hard to read text under the mouse, and the hover target moves upon activation

---

## Proposed solution

We’d like to refactor this to use our new tooltip styles, similarly to #8565.

- We can use a `button` so this can be triggered by keyboard users
- We can still style this very minimally – potentially with a `border-bottom: 1px dotted grey` similarly to the `<abbr>` element to convey there is a tooltip
- A tooltip will mean the interactive target won’t move around upon activation
- Our Tippy.js implementation means the text within the tooltip will still be available to screen reader users, like `title` is.

**Comment by lb-** [comment]
We should also try to use the `time` element, it provides a more semantic approach and more accessible
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

**Comment by berndfourdigits** [comment]
I've made a PR replacing all human-readable-date elements https://github.com/wagtail/wagtail/pull/8697 :)
