### ISSUE TITLE
Adding Live Subscription to History(Logging) Using Server EventSource

### ISSUE THREAD

**Issue by hazho** [wagtail/wagtail#8580]
Currently the Site History and other custom logging has no (on browser live notifications), it would be very helpful that all subscribed admins/editors see the live notifications wherever of the admin site they are.
inicially this one would be helpful:
https://developer.mozilla.org/en-US/docs/Web/API/EventSource

**Comment by hazho** [comment]
Based on the Documentations, this is better for Users

>Unlike [WebSockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API), server-sent events are unidirectional; that is, data messages are delivered in one direction, from the server to the client (such as a user's web browser). That makes them an excellent choice when there's no need to send data from the client to the server in message form. For example, EventSource is a useful approach for handling things like social media status updates, news feeds, or delivering data into a [client-side storage](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage) mechanism like [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) or [web storage](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API).

**Comment by gasman** [comment]
Is there really much need for people to watch log entries arriving in real time? I think this would be a better fit for an add-on package.

**Comment by hazho** [comment]
I agree, can you add label (third-party or add-on) to this and the similar topics that their issue had been closed?
 so later any developer want to filter issues by that label, would be easier to find the add-on listed feature-requested-issues..!
