### ISSUE TITLE
Scheduled publishing fails if the approved revision's author does not have publish permission

### ISSUE THREAD

**Issue by jacobtoppm** [wagtail/wagtail#8585]
### Issue Summary

If a user without publish permission authors a revision and fills in scheduled publishing, and this revision is then published/approved via workflow, the `publish_scheduled_pages` management command will fail with a `PublishPagePermissionError`.

### Steps to Reproduce

1. Create a superuser, and a user in a group with only edit permissions
2. As the edit-only user, create a new revision of the homepage by saving a draft, with a go live date set very soon, submit to a workflow
3. As the superuser, approve the workflow so the page is set to publish
4. Once the go live date date is passed, run the `publish_scheduled_pages` management command

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no, currently working on this)

### Technical details

* Wagtail version: 2.16.2

**Comment by gasman** [comment]
Confirmed on current main (4.0a0).

I propose that we handle this by just [not passing the `user` argument to the `publish` method](https://github.com/wagtail/wagtail/blob/cb43536f07f0a43412b3ff1c8c0d8ed61af5b3db/wagtail/management/commands/publish_scheduled_pages.py#L115) - the user isn't really performing the publish action here, after all.
