### ISSUE TITLE
Specific snippets list language picker not properly styled

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#8588]
Ref: https://github.com/wagtail/wagtail-localize/issues/576

To reproduce:
- add `TranslatableMixin` to one of the snippets
- go to snippets > the translatable snippet
- the specific snippets list

![image](https://user-images.githubusercontent.com/72310199/169782488-d8f26b9e-1762-47e3-b3a6-d9ed535e1a53.png)

when you hover, it shows as expected:

![image](https://user-images.githubusercontent.com/72310199/169782689-4197b3cc-4e63-4e24-8289-2e8160222728.png)

**Comment by laymonage** [comment]
PR: #8589

**Comment by lb-** [comment]
Fix cherry picked to stable 3.0 branch 511f44fa4843581debcda6f1afdcc07022b698bf
