### ISSUE TITLE
Oembed services sometimes return http uri scheme in html

### ISSUE THREAD

**Issue by akrawchyk** [wagtail/wagtail#860]
When wagtailembeds sends [requests to an oembed provider](https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailembeds/embeds.py#L111), the provider sometimes returns the html property with a http uri scheme regardless if the url parameter is an https scheme. This breaks embeds on sites with https enabled.

At least for YouTube, based on [this discussion](https://groups.google.com/forum/#!topic/youtube-api-gdata/S9Fa-Zw2Ma8), chances are oembed providers are not going to return matching uri schemes. However, appending the [scheme parameter](https://groups.google.com/d/msg/youtube-api-gdata/S9Fa-Zw2Ma8/1V7Y_K9_vIEJ) may help this, but again is limited to provider implementation.

[Youtube w/o scheme](https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=3QzP_ypBWDE)

[Youtube w/scheme](https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=3QzP_ypBWDE&scheme=https)

[Vimeo oembeds](http://vimeo.com/api/oembed.json/?url=https://vimeo.com/channels/staffpicks/113868429) do not have uri scheme associated with them, allowing the browser to choose based on what scheme was served.

**Comment by kaedroho** [comment]
This can be worked around for now by creating a custom embed finder. See: https://gist.github.com/kaedroho/ec2b2e83f2f4ecfb9677 for an example

**Comment by akrawchyk** [comment]
Thanks for the continued effort on this @kaedroho!

**Comment by kaedroho** [comment]
I think, where possible, we should make Wagtail always ask embed providers for https urls. Is there a major downside to doing that?

**Comment by davecranwell** [comment]
Very occasionally I've experienced issues where a third party, https asset, is served through a CDN server with a lapsed certificate. In those situations modern browsers can throw their full-page error messages with dire warnings about security. If the asset were merely over http, your site would get a warning padlock, but nothing that terrible. That's the worst thing I'm aware of.

**Comment by gasman** [comment]
Happy to always go with https where available.
