### ISSUE TITLE
Add `construct_snippet_chooser_queryset` hook

### ISSUE THREAD

**Issue by katzmo** [wagtail/wagtail#8610]
### Is your proposal related to a problem?

Sometimes it is necessary to filter the queryset of the snippets chooser to restrict the snippets that can be chosen by a user. For example to filter snippets by site as suggested in the "mutlitenancy" section of the documentation.

### Describe the solution you'd like

In addition to `construct_page_chooser_queryset`, `construct_document_chooser_queryset` and `construct_image_chooser_queryset`, it would be awesome to have a similar hook `construct_snippet_chooser_queryset` for customizing snippets listed in the snippets chooser.

### Describe alternatives you've considered

The documentation recommends to use the `wagtail-modelchooser` plugin instead of the snippet chooser. That plugin has not been updated to Wagtail 3.0 yet.

As another workaround, I tried modifying the snippet field queryset on a custom admin form. However, that queryset is ignored by the AdminSnippetChooser. It needs to be replaced by a default select widget, which means loosing all of the chooser functionality.

### Additional context

It feels wrong having to use a 3rd party plugin for snippets when wagtail already provides a hook to solve the same problem for pages, documents and images…

**Comment by thibaudcolas** [comment]
@zerolab @katzmo do you think this is still needed or covered enough by generic chooser work?

**Comment by zerolab** [comment]
I would say that with https://docs.wagtail.org/en/stable/reference/viewsets.html#wagtail.snippets.views.snippets.SnippetViewSet.chooser_viewset_class, with a custom [`chosen_view_class`](https://docs.wagtail.org/en/stable/reference/viewsets.html#wagtail.admin.viewsets.chooser.ChooserViewSet.chosen_view_class) inheriting from `SnippetChosenView` and implementing [`get_object_list()`](https://github.com/wagtail/wagtail/blob/2b061ac96e5ffdad2759e39bfdbca0fc242ae854/wagtail/snippets/views/chooser.py#L72) we are covered.

(I wrote up more at https://zerolab.org/posts/wagtail-generic-choosers/)

**Comment by katzmo** [comment]
Yes, with a custom `choose_view_class` it is now possible to override the query, which solves my original issue. However, registering your own view set with custom views is more complex than implementing a simple hook like the ones available for pages, images and documents. It still feels to me that a `construct_snippet_chooser_queryset` hook should exist as well.

**Comment by gasman** [comment]
Custom view classes are definitely the better solution architecturally - they keep the code in logically related places, unlike hooks that have the effect of "jump out of this code so that other modules can hack around with it". If anything, I'd like to move pages/images/documents away from the hook pattern and towards customising via subclasses.

**Comment by thibaudcolas** [comment]
Based on discussions here and internally I’ll also close https://github.com/wagtail/roadmap/issues/25 from our roadmap – looks like we’ve done enough work on this (for now).
