### ISSUE TITLE
Displaced loading-icon's animation in page editor

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#8615]
### Issue Summary

![Peek 2022-06-01 08-04](https://user-images.githubusercontent.com/468164/171338809-6014649f-88c5-47af-b279-5fdac1955bcc.gif)

There is a `padding-inline-end: .5rem;` at the loading-svg, which seems to cause this displaced animation.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Login to admin
3. Save the draft of a page
4. Watch the funny animation

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.10.4
* Django version: 4.0.4
* Wagtail version: 3.0
* Browser version (Linux Mint/Ubuntu): Firefox 100, Chrome 102

**Comment by zerolab** [comment]
Confirmed this, thank you @th3hamm0r

**Comment by lb-** [comment]
Can confirm this is an issue and broke with changes for 3.0
`client/scss/components/_button.scss` `&-active {` on line 232 should not have justify content centre
`client/scss/layouts/_page-editor.scss` padding added to `footer .actions, footer .preview {  .button {` should not be padding but margin so animated icons do not include that spacing

<img width="1393" alt="Screen Shot 2022-06-12 at 11 02 24 am" src="https://user-images.githubusercontent.com/1396140/173210420-f82acee6-ffd3-4069-b12d-d3228eb9a148.png">

**Comment by lb-** [comment]
PR with fix https://github.com/wagtail/wagtail/pull/8670
