### ISSUE TITLE
Add custom code to RichTextBlock

### ISSUE THREAD

**Issue by SohumDamani** [wagtail/wagtail#8620]
### I feel like a block that takes in input a code input as simple text and replaces it with the given template feature.

class Heading(blocks.StructBlock):
    title = blocks.CharBlock(max_length=255)
    template = blocks.CodeBlock(required=False)

content = blocks.StreamBlock([
    ('heading',Heading())
])

Sample template

{% for block in page.code %}
{%  if block.value.template %} 
paste block.value.template
{% else %}
{% include_block block %}
{% endif %}
{%  endfor %}

Let say the template has the following: 
`<h1 style="color:blue;">{{self.value.title}}</h1
`
The output should be  HEADING_VALUE in blue color

This adding template feature will be visible to only a specific user which has technical skill and permission. By this, there can be a basic template for a page whose specific feature can be changed. This reduces the load of creating separate pages just to change a small block of code.

**Comment by lb-** [comment]
@SohumDamani 
I do not think this is something that will be part of the core code, you may be better off implementing this ad hoc yourself. 

This could open up a huge risk vector for everything from non-accessible html through to severe security vulnerabilities. 

Managing the code to html output would be a large undertaking. 

For now we will close this but feel free to get support on the support channel of you need help building parts of this as Draftail plugins. 


Also have a read of the RFC (which has been approved) that may solve your use case in a more generic and safe way. 

https://github.com/wagtail/rfcs/pull/46

Also see the Zen of Wagtail which kind of guides some of these architectural directions https://docs.wagtail.org/en/stable/getting_started/the_zen_of_wagtail.html

One more note for future - please try to follow the new issue templates for enhancement requests as they make it much easier to read requests and also help you, the requestor, provide useful context.

**Comment by Scotchester** [comment]
@SohumDamani I also want to point out that the existing [RawHTMLBlock](https://docs.wagtail.org/en/stable/reference/streamfield/blocks.html#wagtail.blocks.RawHTMLBlock) may get you most of what you want.

**Comment by lb-** [comment]
Thanks @Scotchester

**Comment by SohumDamani** [comment]
Thanks, @lb- 
Thanks @Scotchester RawHtmlBlock works for me
