### ISSUE TITLE
Adopt generic class based view for page listing (explorer)

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8628]
| Part of the Epic https://github.com/wagtail/wagtail/issues/8365 |
|-----------------------------------------------|

### Is your proposal related to a problem?

* Wagtail 2.12 added generic class based views for use across Wagtail's admin.
* Many parts of the Wagtail admin are not yet migrated to this new approach, which makes it harder to share UI logic and styling/layouts.
* This issue specifically covers the page listing view (or folder/explorer view) and making this a class based view.

### Describe the solution you'd like

* Migrate the function views in [`wagtail/admin/views/pages/listing.py`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/pages/listing.py#L15) to class base Index view.
* The generic model index listing class `IndexView` can be found in [`wagtail/admin/views/generic/models.py`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/generic/models.py#L60)
* The template for the view should also extend the generic model index class view version [`wagtail/admin/templates/wagtailadmin/generic/index.html`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/generic/index.html)

### Describe alternatives you've considered

* Leave as is, however this will make it harder to share UI elements and layout between similar listing views.

### Additional context

* This is part of a larger epic work to adopt class based views throughout wagtail - https://github.com/wagtail/wagtail/issues/8365
* There is some complexity here due to the nature of the index listing view handling search, sorting (i.e. re-ordering page children and bulk actions)

### Screenshots

<img width="1445" alt="Screen Shot 2022-06-05 at 8 04 38 pm" src="https://user-images.githubusercontent.com/1396140/172045584-edf7f480-0939-4efa-96c2-b1b9f88f91cc.png">
<img width="1450" alt="Screen Shot 2022-06-05 at 8 04 26 pm" src="https://user-images.githubusercontent.com/1396140/172045587-ff83074f-f342-4d33-a08d-cb6e069d294b.png">
<img width="1449" alt="Screen Shot 2022-06-05 at 8 04 17 pm" src="https://user-images.githubusercontent.com/1396140/172045588-05defe9e-8afc-493f-bf76-910358a9ff1a.png">

**Comment by lb-** [comment]
Note: I have made some progress on this here https://github.com/lb-/wagtail/commits/cleanup/page-listing-explorer-class-based-view

Anyone is free to pick this up and continue with it if it gets focused on during the Wagtail sprints this week, just add a comment

**Comment by GeekGawd** [comment]
@lb- Hi! Should we be using a permission class rather than a decorator if we are shifting to Class Based Views.

Also, which tests in the wagtail, test all the page listing explorer functionalities.

**Comment by lb-** [comment]
@GeekGawd - not sure on the permission class approach sorry - I think we already have a permissions handling approach for the shared classes. 

See PermissionCheckMixin https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/generic/permissions.py#L4

As for the unit tests location - pretty sure it's these files. 

https://github.com/wagtail/wagtail/blob/main/wagtail/admin/tests/pages/test_explorer_view.py

https://github.com/wagtail/wagtail/blob/main/wagtail/admin/tests/pages/test_page_search.py

Or at least that folder.

**Comment by Temidayo32** [comment]
@lb- I will like to take on this issue. I have made contribution to the Wagtail project in the past. However, taking on this issue, will be as part of contribution as an Outreachy applicant. Taking on this issue is also in reference to to the instruction below given in the project description on the Outreachy page.

> Potential applicants are advised to demonstrate their skills in these particular areas before selecting this project idea.

In essence, this would be a good way to demonstrate my ability to handle this project if I am selected for it.

**Comment by Temidayo32** [comment]
@lb- Oh, I just checked the codebase. It appears this is done already.
![9gGGVikRhm](https://github.com/wagtail/wagtail/assets/87539866/2f91b809-6eec-4cee-be8d-e054bea98eb7)

**Comment by laymonage** [comment]
Hey @Temidayo32, good to see you again! Yep I believe this has been done in #10592.

It seems the users views have also been migrated to class-based views as well, so that means all the core views have been migrated to use class-based views. Though I think there will be further work to do in that area by grouping the views in a `ModelViewSet`.

In the mean time if you're still keen on making such contributions, I'd suggest refactoring the views in `wagtail/contrib/redirects/views.py` as mentioned in #8365. Thanks for your interest!

**Comment by Temidayo32** [comment]
@laymonage thanks for the warm welcome. Oh, didn't realise there was refactoring issue from #8365 . Thanks for pointing it out.
