### ISSUE TITLE
Adopt generic class based view for user account editing

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8629]
| Part of the Epic https://github.com/wagtail/wagtail/issues/8365 |
|-----------------------------------------------|

### Is your proposal related to a problem?

* Wagtail 2.12 added generic class based views for use across Wagtail's admin.
* Many parts of the Wagtail admin are not yet migrated to this new approach, which makes it harder to share UI logic and styling/layouts.
* This issue specifically covers the user account view (when you edit / manage your own account).

### Describe the solution you'd like

* Migrate the function view `account` in [`wagtail/admin/views/account.py`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/account.py#L211) to class based view.
* Extend the `WagtailAdminTemplateMixin` & `TemplateView` if `EditView` similar to what was dome for the dashboard view (see context below)
* The template for the view should also extend the generic model index class view version [`wagtail/admin/templates/wagtailadmin/generic/edit.html`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/generic/edit.html)

### Describe alternatives you've considered

* Leave as is, however this will make it harder to share UI elements and layout between similar listing views.

### Additional context

* This is part of a larger epic work to adopt class based views throughout wagtail - https://github.com/wagtail/wagtail/issues/8365
* Dashboard view change https://github.com/wagtail/wagtail/pull/8382

### Screenshot

<img width="1448" alt="Screen Shot 2022-06-05 at 8 11 22 pm" src="https://user-images.githubusercontent.com/1396140/172045668-32238c1c-1aa1-4202-b60c-8ff8e4a49859.png">

**Comment by kaedroho** [comment]
Thanks @lb-!

The form on this view is constructed a lot differently to the way our other generic edit views work. This one might be one worth keeping separate.

**Comment by lb-** [comment]
@kaedroho I think it is still worthwhile making this a class based view - just using the basic Wagtail template mixin. 

I agree this does not need to use the model one - I can reword the issue accordingly. 

Class based views make it much easier to override/ extend the existing behaviour without having to copy/ paste the entire view function. 

I see this as similar to the dashboard class based view change. 
https://github.com/wagtail/wagtail/pull/8382

**Comment by lb-** [comment]
Update made.

**Comment by laymonage** [comment]
I believe this has been done in #9114, #9141, #9196, and #9204. Though I think it would be nice to wrap the views in a `ModelViewSet` subclass like the views for groups.

**Comment by BobadeKenny** [comment]
Hi @lb- @laymonage. I've been able to make progress on this issue and just opened a PR [here](https://github.com/wagtail/wagtail/pull/11052)

**Comment by lb-** [comment]
Sorry. GitHub closed automatically despite my best efforts with a commit message that did not say fixes or closes. 😅

**Comment by lb-** [comment]
My apologies, this is meant to be closed by the PR #11052 - thank you @BobadeKenny
