### ISSUE TITLE
Add new Breadcrumbs examples to the Pattern Library (Storybook)

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8631]
### Is your proposal related to a problem?

The pattern library (storybook) currently shows the old breadcrumbs design.
![Image](https://user-images.githubusercontent.com/1396140/172103848-30b6f9fd-f044-4fcc-b487-103b80e82b57.png)

As we will be adopting the new breadcrumbs, it would be better to have this as the one used in the pattern library.

![Image](https://user-images.githubusercontent.com/1396140/172109485-6c77d3dc-cd1b-44fc-a07e-566a27fd9151.png)

### Describe the solution you'd like

* Remove the legacy breadcrumbs from the pattern library
* Show the new breadcrumbs with a few variations
   * one item
   * five items
   * 3 items with `trailing_breadcrumb_title` set
* ensure it is interactive (JS working)

### Additional context

* Refer to the pattern library docs for how to use this https://torchbox.github.io/django-pattern-library/guides/usage-tips/
* New breadcrumbs (aka next) is locate in the `wagtail/admin/templates/wagtailadmin/shared/breadcrumb-next.html` file
* Document the variables that the template accepts using the pattern library syntax
* Remember to update the {% comment "text/markdown" %} to include text/markdown as needed so that the docs show correctly in the pattern library.

**Comment by PaarthAgarwal** [comment]
I've assumed by one item you mean root item + one item. Let me know if it's otherwise.
