### ISSUE TITLE
Admin role interface layout is misaligned

### ISSUE THREAD

**Issue by slifty** [wagtail/wagtail#8633]
### Issue Summary

It looks like the layout in the admin interface is a bit wonky when editing user "roles"

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/208884/172205045-9a7fe8d9-8e1b-40c0-9ea7-570352f51c48.png">

I would expect each role to be on its own line, with the label to the right of the check box and vertical alignment.

### Steps to Reproduce

1. Follow the "Getting Started" guide to set up a fresh installation of wagtail.
2. Log in
3. Go to the admin interface
4. Edit a user
5. Click "Roles"

### Technical details

-   Python version: 3.10.3
-   Django version: 4.0.5
-   Wagtail version: 3.0
-   Browser version: Firefox 101

**Comment by gasman** [comment]
Thanks for the report! This should be fixed in the next release, by https://github.com/wagtail/wagtail/pull/8494.
