### ISSUE TITLE
Error in forms listing in admin

### ISSUE THREAD

**Issue by cesar-benjamin** [wagtail/wagtail#8636]
### Issue Summary

I have a site which i was working well with wagtail -2.16.x, i'm making a renewal and migration of the whole site, i have a few forms, but when i did try to test it, seems to work twice, but when i look in admin section 'Forms' an error appears about 'str' object is not a mapping

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py to add a AbstractFormField model, and a AbstractEmailForm model:

class FormularioFormField(AbstractFormField):
    pagina = ParentalKey("Formulario", on_delete=models.CASCADE, related_name="campos_formulario")
...

class Formulario(PaginaBaseAbstract, AbstractEmailForm):
...    

4. Create a few pages in admin of type 'Formulario'
5. Go to public view fo that form and fill a few forms.
6. return to wagtail admin, and go to forms
7. open your forms with data filled
8. see that error jumps...

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: YES

### Technical details

-   Python version: 3.10
-   Django version: 4.0.1
-   Wagtail version: 3.0
-   Browser version: Firefox 99

btw, i found the solution, in the file wagtail/contrib/forms/models.py 

line 57 (into get_data func):

**self.form_data,

    def get_data(self):
         """
         Returns dict with form data.
         You can override this method to add additional data.
         """
         return {
             **self.form_data,
             "submit_time": self.submit_time,
         }

checking the same file in 2.16 y change a bit to make it similar, so i change it to:

    def get_data(self):
         form_data = json.loads(self.form_data)
         form_data.update({'submit_time': self.submit_time})
         return form_data

obviously must import json first

**Comment by zerolab** [comment]
Hey @cesar-benjamin, #8230 changed the `form_data` field to use a `JSONField`.

Can I double check that you ran all migrations?

**Comment by gasman** [comment]
For reference, the same thing [has been reported on the Wagtail Slack support channel](https://wagtailcms.slack.com/archives/C81FGJR2S/p1653794968915449) but is unresolved there - if this does turn out to be a missed step in the upgrade process then we should highlight this in the release notes.

**Comment by cesar-benjamin** [comment]
> 

i'm not sure if is an upgrade issue only, i havent use 3.0 with a new project with forms (yet) but looking the code and the field that now is JSONField instead of TextField but for a reason the representation appears yet as text, i guess that have to jsonize all the times, i'm not able to try in a new project for now but my data have no forms submissions yet because i'm close to release my new site next week, so, no submissions exists yet, in fact i tried for the first time before release.

**Comment by hazho** [comment]
I had the same issue, at the new project, this error had not been raised, but at the existing one does, I thought it was because of the old data, because once I reseted all data and created the db again, error gone, but if what you are saying is the case, then maybe I missed something, maybe I changed something that kicked away the error...!
for example a dependency that had been upgraded due to wagtail3.0 requirements while the older version of the mysterious dependency is fine version.

**Comment by hazho** [comment]
My assumption maybe true only when there Data, but when there are no Data, the error won't be raised, which mean, the dependency that causes the issue only does when there are old text based data, but still we need more cases like this to be sure 100%
or an intensive manual testing

**Comment by cesar-benjamin** [comment]
> My assumption maybe true only when there Data, but when there are no Data, the error won't be raised, which mean, the dependency that causes the issue only does when there are old text based data, but still we need more cases like this to be sure 100% or an intensive manual testing

what do you mean 'when there data'? i had upgrade with no forms data, i have created a few form pages but there is no data yet. I'm building a new site, i'm close to publish it, but the form data will be create by users in the future. 

I'm not sure if you say 'data' as form submisions or form pages. But i can tell that there is not form submissions data yet, only form pages. When i tried to check the list of form submissions (sure, clean, without any registry) the error appears, i tried a pair of submisions and then the error keeps, then i delete all the submisions in django shell but the error remains.

**Comment by hazho** [comment]
by Data I mean both, if there are form pages before upgrading and running (migrate) command, the error could be raised by a chance of (90%), but when there are no data at all before upgrading, or when the project is new (`wagtail start project`) most probably this won't rais any error..!

**Comment by hazho** [comment]
by the way, what is your OS? I tested mine on Windows

**Comment by gasman** [comment]
Hi @cesar-benjamin,
I'm unable to replicate this issue following the steps you provided. Starting from a new `wagtail start` project, I edited home/models.py as follows:

```python
from django.db import models

from wagtail.models import Page
from modelcluster.fields import ParentalKey
from wagtail.contrib.forms.models import AbstractEmailForm, AbstractFormField
from wagtail.admin.panels import FieldPanel, InlinePanel

class HomePage(Page):
    pass


class FormularioFormField(AbstractFormField):
    pagina = ParentalKey("Formulario", on_delete=models.CASCADE, related_name="form_fields")


class PaginaBaseAbstract(Page):
    class Meta:
        abstract = True


class Formulario(PaginaBaseAbstract, AbstractEmailForm):
    intro = models.TextField(blank=True)

    content_panels = AbstractEmailForm.content_panels + [
        FieldPanel('intro'),
        InlinePanel('form_fields'),
        FieldPanel('from_address'),
        FieldPanel('to_address'),
        FieldPanel('subject'),
    ]
```

(note: your code above was incorrect, as AbstractEmailForm requires the relation with AbstractFormField to be named `form_fields`, not `campos_formulario`)

and created templates formulario.html and formulario_landing.html:

```html+django
{% load wagtailcore_tags %}
<html>
    <head>
        <title>{{ page.title }}</title>
    </head>
    <body>
        <h1>{{ page.title }}</h1>
        {{ page.intro }}
        <form action="{% pageurl page %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    </body>
</html>
```

```html+django
{% load wagtailcore_tags %}
<html>
    <head>
        <title>{{ page.title }}</title>
    </head>
    <body>
        <h1>{{ page.title }}</h1>
        <p>Thank you for your submission.</p>
    </body>
</html>
```

After running `./manage.py makemigrations` / `./manage.py migrate` I was then able to successfully create several form pages, submit the form on them, and view the form submissions.

If you're able to replicate the problem on a fresh Wagtail project, please open a new issue giving _complete_ steps including the full model code, and we'll be happy to investigate further.

**Comment by tbrlpld** [comment]
I just ran into this issue too. It looks like I had a bad record in the database. I guess that record was created after the migration ran to convert the table to JSON but before I had updated the `process_form_submission` to not use `json.dumps` anymore.

Here you can see the bad record in the database with id 4.

```SQL
picnic=# select * from myforms_myformsubmission
picnic-# ;
 id |              form_data               |          submit_time          | page_id | user_id 
----+--------------------------------------+-------------------------------+---------+---------
  1 | {"what_is_your_name": "Alice"}       | 2022-10-11 14:11:16.587711+00 |       5 |       1
  2 | {"what_is_your_name": "Bob"}         | 2022-10-11 14:11:23.633996+00 |       5 |       1
  3 | {"what_is_your_name": "Alice again"} | 2022-10-17 15:30:33.813545+00 |       5 |        
  4 | "{\"what_is_your_name\": \"Test\"}"  | 2022-10-19 13:47:23.80316+00  |       5 |        
  5 | {"what_is_your_name": "Test"}        | 2022-10-19 13:48:12.425547+00 |       5 |        
(5 rows)

picnic=# delete from myforms_myformsubmission where id=4
picnic-# ;
DELETE 1
picnic=# select * from myforms_myformsubmission
;
 id |              form_data               |          submit_time          | page_id | user_id 
----+--------------------------------------+-------------------------------+---------+---------
  1 | {"what_is_your_name": "Alice"}       | 2022-10-11 14:11:16.587711+00 |       5 |       1
  2 | {"what_is_your_name": "Bob"}         | 2022-10-11 14:11:23.633996+00 |       5 |       1
  3 | {"what_is_your_name": "Alice again"} | 2022-10-17 15:30:33.813545+00 |       5 |        
  5 | {"what_is_your_name": "Test"}        | 2022-10-19 13:48:12.425547+00 |       5 |        

```
