### ISSUE TITLE
Allow sorting and searching when moving a page

### ISSUE THREAD

**Issue by TommasoAmici** [wagtail/wagtail#8647]
### Is your proposal related to a problem?

When moving a page from one parent to another, there is no way to easily go to the destination without clicking many times in the UI.

This is especially frustrating when a page has many children (think >100) as there is no way to search directly for the destination or even to sort the table. See screenshot attached where I have deleted some elements of the table to fit everything, but you can see 28 pages of children with no way of sorting them or filtering.

### Describe the solution you'd like

Other sections of Wagtail allow searching and sorting, I'd like to see those options available also when moving pages.

### Describe alternatives you've considered

I haven't been able to think of alternatives

### Additional context

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/424525/172622813-95f54888-1f75-4cb4-b6c8-8c045ea4543c.png">

**Comment by lb-** [comment]
Note - sorting is not solved as yet with the PR that has been merged but there are plans to redo parts of the page chooser modal and that may result in the ability to sort better.

Closing though as the core intent of this enhancement has now been implemented.
