### ISSUE TITLE
Changing page field type from TextField to Snippet ForgeinKey crashes the page on edit

### ISSUE THREAD

**Issue by raindeer** [wagtail/wagtail#8653]
### Issue Summary
Changing page field type from TextField to Snippet ForgeinKey crashes the page when trying to edit it.

### Steps to Reproduce

Create a page model, and add a Textfield like:

`a_field = blocks.TextField()`

Make and run migrations. Create a page and store "xyz" in a_field.

Create a snippet SomeSnippetModel, and Change a_field to:
```
a_field = models.ForeignKey(
       'SomeSnippetModel',
       ...
    )
```
Make and run migrations.

Try to edit the page in the wagtail editor, and you get a ValidationError with the message:
['“xyz” value must be an integer.']

Stacktrace:
```
/python/lib/python3.9/site-packages/wagtail/core/models/__init__.py, line 1849, in with_content_json
        obj = self.specific_class.from_serializable_data(data)
/python/lib/python3.9/site-packages/modelcluster/models.py, line 244, in from_serializable_data
        obj = model_from_serializable_data(cls, data, check_fks=check_fks, strict_fks=strict_fks)
/python/lib/python3.9/site-packages/modelcluster/models.py, line 87, in model_from_serializable_data
                clean_value = field.remote_field.model._meta.get_field(field.remote_field.field_name).to_python(field_value)
/python/lib/python3.9/site-packages/django/db/models/fields/__init__.py, line 1838, in to_python
            raise exceptions.ValidationError(
```

The stored "xyz" string is in conflict with the id of the snippet. It seems like the old string data should just be ignored in this case.
To resolve the problem a_field needs to be renamed, or the page recreated from scratch.

### Technical details

-   Python version: 3.9.12
-   Django version: 3.2.11
-   Wagtail version: 2.16.2, 
-  django-modelcluster version: 5.2

**Comment by lb-** [comment]
@raindeer  - just looking at this - I would think that this kind of migration change may not be the best way to do this, you would probably need a custom migration to change something from a text field to a `ForeignKey`.

I will close this for now as I do not think this is a use case that could be supported without breaking other issues under the hood.

Here is a good tutorial on how do to this kind of thing https://marcolcl.medium.com/converting-text-field-to-foreign-key-in-django-34e191845bbe
