### ISSUE TITLE
Refactor Status tag styles into UI component

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8656]
### Is your proposal related to a problem?

We currently have a "status tag" component as reusable CSS styles that are copy-pasted with the relevant HTML across the admin.

### Describe the solution you'd like

This feels like a good candidate to refactor to a UI component, this is an approach where we use a template tag to abstract away the HTML.

This shouldn’t change the component’s rendering in any way, just how it’s included in different places (and introduce a way for us to test the variations more easily in Storybook). For example, we will not adjust the class names, even though these are somewhat confusing.

#### Requirements

- [ ] Create a new shared template partial (`wagtail/admin/templates/wagtailadmin/shared/status_tag.html`)
- [ ] Create a new template tag that uses this partial in `wagtail/admin/templatetags/wagtailadmin_tags.py`
- [ ] Ensure the template tag works with the `classname` kwarg
- [ ] Add a Storybook stories for different variations of this new component ( similar to `wagtail/admin/templates/wagtailadmin/shared/header.stories.tsx`)
- [ ] With a template partial in the `shared` folder for us to `{% include %}` where needed (update all locations)
- [ ] Ensure that the styleguide is also updated to use the new template partial `wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html`

### Additional context

* The help_block is a good example of how this has been done before https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/help_block.html & https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templatetags/wagtailadmin_tags.py#L1059-L1063
* Current primary SCSS https://github.com/wagtail/wagtail/blob/main/client/scss/components/_status-tag.scss
* Secondary class re-use https://github.com/wagtail/wagtail/blob/main/client/scss/components/_listing.scss
* See also https://github.com/wagtail/wagtail/blob/main/client/scss/layouts/_report.scss#L11
* It may be really tricky to do this one wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html (we may need to put the link inside the status tag or the other way around
* Follow up items (once this is done) - we should ...
* [ ] Refactor `status' classes to align with `w-status-tag` and use BEM classes for the `primary` & `disabled` variants

**Comment by lb-** [comment]
We should also try to refactor the CSS to be consistently using the `w-` prefix and move styles files from scss/objects to scss/components

**Comment by lb-** [comment]
No problems at all - that can be split / done when it if needed. Same goes for the others. I got a bit confused and saw this in up for grabs so figured anyone would pick this up. I didn't see Steve assigned.

**Comment by lb-** [comment]
@salty-ivy let me know if this is something you may be keen on picking up - it's not really a JS thing but a Django templates thing but would be great to get this one resolved.

**Comment by lb-** [comment]
See related issue https://github.com/wagtail/wagtail/issues/5778 (status tag contrast)

**Comment by salty-ivy** [comment]
> @salty-ivy let me know if this is something you may be keen on picking up - it's not really a JS thing but a Django templates thing but would be great to get this one resolved.
> 
> 

@lb- sure why not, I am fine with python/Django work got better experience with that.
Open to all kinds !

**Comment by salty-ivy** [comment]
Would look into it asap.

**Comment by salty-ivy** [comment]
> @salty-ivy let me know if this is something you may be keen on picking up - it's not really a JS thing but a Django templates thing but would be great to get this one resolved.

@lb- could you please give me a heads up, probably like  what exactly needs to be done (pin pointed file as its little tedious to look for it in the codebase as i am new to it) ? would be appreciated

**Comment by lb-** [comment]
@salty-ivy  issue is updated - hopefully it's a bit clearer

**Comment by salty-ivy** [comment]
Alright thanks a lot !

**Comment by salty-ivy** [comment]
@lb-  could you please tell me what's the use of
wagtail/admin/templates/wagtailadmin/shared/page_status_tag_new.html
because there's already 
wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html

**Comment by lb-** [comment]
@salty-ivy good question, I might need to defer to @thibaudcolas as to the long term plan here but here's my best guess.

From the looks of these, they are a specific usage of the status tag to show the page's love status only. 

So I think that `page_status_tag` would end up using the new component you create. 

Then... The new one is a new design that uses Tippy for the same purpose. So I guess a long term approach would be to adopt the new design for the status tag generic component in the future. However, Tailwind makes this a bit more complex, not sure where we are heading with this approach as we are yet to provide a clear direction for new Css. 

Nonetheless, I think that this issue does not conflict with those templates, the non-new one would just adopt the generic template tag. 

Hope that makes sense


## Links

- https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html
- https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/page_status_tag_new.html

**Comment by salty-ivy** [comment]
Alright, I see it now

**Comment by salty-ivy** [comment]
@lb-  i had  a doubt should the satus _tag only include the logic of ```live``` or ```live``` and ```draft``` both, if both wouldn't it be better to just convert the whole logic of ```page_status_tag``` into tag

**Comment by salty-ivy** [comment]
@lb-  @thibaudcolas  PR is ready for review, kindly check it out at your ease and let me know for any suggestions, thanks you

**Comment by salty-ivy** [comment]
@lb-  PR https://github.com/wagtail/wagtail/pull/9721 is also ready although i have some small doubts, but i hope most of the work is done, and rest would be clear once it will be reviewed.

**Comment by lb-** [comment]
@salty-ivy  I have put some comments on the PR but I think it would be best to start with the non-page status ones (the ones that use spans for the 80% use case).

If you search through the code for `status-tag` you will find about ~20 files that are quite simple status-tag variants, a span with a classname and some content inside.

I think it's best we cover this first - and then revisit the more complex ones later. Namely `wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html` - which uses `a` link & `wagtail/admin/templates/wagtailadmin/shared/page_status_tag_new.html` - which is a completely different approach using tailwind classes & tooltips.

Below is an example of how I anticipate we would use the generic status tag template tag, just calling it `status` probably makes more sense.

### Example - page-title-cell

`wagtail/admin/templates/wagtailadmin/chooser/tables/page_title_cell.html`
https://github.com/wagtail/wagtail/blob/da90061ca83170bd1da1c7ca77106690e21f7f49/wagtail/admin/templates/wagtailadmin/chooser/tables/page_title_cell.html#L9-L11

New usage
```html
        {% if column.show_locale_labels and page.depth == 2 %}
            {% status classname="status-tag--label" %}{{ page.locale.get_display_name }}{% endstatus %}
        {% endif %}
```

### Example - page history

`wagtail/admin/templates/wagtailadmin/pages/history.html`
https://github.com/wagtail/wagtail/blob/da90061ca83170bd1da1c7ca77106690e21f7f49/wagtail/admin/templates/wagtailadmin/pages/history.html#L37-L44

New usage

```
                            {% if entry.revision %}
                                {% if entry.action == 'wagtail.publish' %}
                                    {% if entry.revision_id == page.live_revision_id %}{% status classname="primary" %}{% trans 'Live version' %}{% endstatus %}{% endif %}
                                {% elif entry.content_changed %}
                                    {% if entry.revision == page_latest_revision %}{% status classname="primary" %}{% trans 'Current draft' %}{% endstatus %}{% endif %}
                                    {% include "wagtailadmin/pages/revisions/_actions.html" with revision=entry.revision %}
                                {% endif %}
                            {% endif %}
```

### Example template tag code

In `wagtail/admin/templatetags/wagtailadmin_tags.py` you will be able to see how we can easily create these block/endblock style template tags (using `BlockInclusionNode`). Below is a rough bit of working code (without `classname` support).

```python
class StatusTagNode(BlockInclusionNode):
    template = "wagtailadmin/shared/status_tag.html"


register.tag("status", HelpBlockNode.handle)
# register.tag("status_tag", HelpBlockNode.handle) OR status_tag
```

**Comment by salty-ivy** [comment]
ahh, i see it now @lb- sorry for the trouble i got some confusion from the ```page_status_tag```  code and then tried to refactor that only , i was little confused over how to cover different ```status_tag``` from single component .

**Comment by lb-** [comment]
No problems - it's a bit of a confusing situation at the moment - thanks for taking the time to understand.

**Comment by salty-ivy** [comment]
@lb-  @thibaudcolas  i have updated the PR . kindly review at your ease thank you
