### ISSUE TITLE
Pattern library (Storybook) UI cleanup

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8659]
Briefly discussed with Steve – very simple cleanup tasks:

- [ ] Set the background to white for Storybook stories
- [ ] Add better text examples to our "Type scale" story

**Comment by albinazs** [comment]
Hello @thibaudcolas! I'm an Outreachy applicant and I would love to work on this issue! Can you assign this to me please?

**Comment by thibaudcolas** [comment]
@albinazs go for it! In the future you can claim any issues by just posting a comment. We can unfortunately only use GitHub’s "assignees" feature for people who are core contributors to Wagtail

**Comment by albinazs** [comment]
Dear @thibaudcolas,
I have almost solved this issue, but before creating PR I want to ask a couple of questions on #2 task - “Add better text examples to our "Type scale" story”:
  1) I moved the 'large body text' element up as the other elements are in descending order - is it OK?
  2) Do we actually need h4 element here - as in documentation it is recommended to avoid levels other than h1, h2 and h3
    https://docs.wagtail.org/en/stable/advanced_topics/accessibility_considerations.html#available-heading-levels
    https://docs.wagtail.org/en/stable/contributing/documentation_guidelines.html#heading-levels
  3) I put better text styles descriptions as on the screenshot - are they OK, or shall I put there some other texts?
![image](https://user-images.githubusercontent.com/51043550/194948358-906e672f-d24c-42d5-8084-15d89d22ffef.png)

**Comment by thibaudcolas** [comment]
@albinazs this all looks EXCELLENT! So yes, yes, and yes. For h4 and below – yes in this instance we do want to see all text styles.

**Comment by albinazs** [comment]
thank you, @thibaudcolas, for you quick response and support in resolving this! now proceeding with my PR
