### ISSUE TITLE
Search icon too small (UI fix issue)

### ISSUE THREAD

**Issue by cool-man-vk** [wagtail/wagtail#8681]
### Search icon is small

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes )
![image](https://user-images.githubusercontent.com/76818423/173598540-b0fc27ea-f90c-4b6f-8112-73e395603dc3.png)

**Comment by gasman** [comment]
This has been updated for the next release:
<img width="542" alt="Screenshot 2022-06-14 at 16 28 06" src="https://user-images.githubusercontent.com/85097/173602456-44be548e-2697-4c20-854a-3d93e31b5f5e.png">
