### ISSUE TITLE
Profile photo not loaded

### ISSUE THREAD

**Issue by cool-man-vk** [wagtail/wagtail#8682]
### Issue Summary

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

**Comment by gasman** [comment]
This doesn't give us enough information to work with, sorry.

**Comment by cool-man-vk** [comment]
Profile photo in account information in the user panel is not loaded

**Comment by gasman** [comment]
Which versions of Wagtail, Django and Python are you running?
What are the exact steps leading up to this problem (starting from `wagtail start myproject`)? Did you make any code customisations?
Are you running with the Django development server (`./manage.py runserver`) or a production webserver?
Does this happen with all image types, or just one specific image?

**Comment by cool-man-vk** [comment]
Sorry to say that , its my mistake I didn't notice that . It works perfectly fine
