### ISSUE TITLE
Editing a page from the preview tab results in loss of data if the user edits in a new tab

### ISSUE THREAD

**Issue by saevarom** [wagtail/wagtail#8765]
### Issue Summary
When a user edits a page and clicks Preview, a new tab is opened with the preview and the tab is somehow registered. The edit bird (userbar) is displayed on the preview page since the user is logged in. If the user then clicks the edit link on the preview tab and edits something and clicks preview again, the edit interface is loaded from the database and the user assumes the data is lost (it is still present in the previous edit tab).

Possible solutions to this are
1. Do not render the edit bird (userbar) when the request is a preview (easy fix)
2. Somehow de-register the preview tab when the user clicks the edit link in the preview tab. This would leave the previous tab with the previously changed data somehow still open and cause more confusion, I think.

I would prefer solution nr. 1

### Steps to Reproduce

1. Edit a page
2. Click preview which opens in a new tab
3. Click the edit bird in the new preview tab
4. All the changes made in the previous tab are not present and the user thinks the data is lost.

### Technical details

-   Python version: 3.8.13.
-   Django version: 4.0.5
-   Wagtail version: main branch
-   Browser version: Chrome 102 on macOS (Monterey)

**Comment by lb-** [comment]
Not sure that this is a bug, it is definitely a confusing behaviour  though, the data is not lost it is just still there unsaved in the previous tab right?

What if we took the user back to the previous window when they click (not sure if that is possible).

Not sure that blocking the whole user bar completely is really a good solution - feels a bit too heavy handed.

**Comment by saevarom** [comment]
Yes, it's unsaved in the previous tab. And very confusing even though it's not a bug per se. It's definitely a bug in the user experience for some people. 

I think that this needs to be solved in some way though.

**Comment by lb-** [comment]
Not sure if this is a solution but Wagtail 4.0 should come with a live preview - it may mean that many users won't need to use the separate tab preview. 

Another thing that is in the works (but not started) is some kind of popup to advise that the page is being edited elsewhere. Maybe that feature can include when being edited by the same user.

**Comment by lb-** [comment]
Resolved via https://github.com/wagtail/wagtail/commit/34734d252fcda6f6f554d8295808eb114ef476eb & https://github.com/wagtail/wagtail/pull/8766

Edit link will no longer render when in preview mode.
