### ISSUE TITLE
Markdown field in Admin

### ISSUE THREAD

**Issue by thinkingcomputing** [wagtail/wagtail#8787]
### Issue Summary

I use wagtail markdown. I've recently upgraded my sites to Wagtail 3.0.1. If I use the admin to edit my page content the wagtail markdown field is blank until I click on the empty box which is when it then appears.

### Steps to Reproduce

1. Use admin to edit a page that has a wagtail markdown field.
2. It is blank for me until I click on the empty field

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no - occurred after an upgrade)

### Technical details

-   Python version: Run `python --version`. **3.8.10**
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`. **3.2.13**
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`. **3.0.1**
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out. **Chrome 102 plus Firefox**

**Comment by gasman** [comment]
Hi @thinkingcomputing,
Please open this as a bug against the wagtail-markdown project - it's quite likely it needs updating for Wagtail 3.
