### ISSUE TITLE
UX Unification - button component with variations

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8790]
## Overview

In the Wagtail design system, we have new designs for our [button component](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=5172%3A30751). Those need to be implemented. This will allow us to generally improve the consistency of Wagtail’s UI, and fix issues such as #3823.

## Button variations

All existing variations are listed in our [styleguide base.html](https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html#L394). Here is a before-after, with our current button variations and how they are changing.

Visual reference:

![buttons-visual-reference](https://user-images.githubusercontent.com/877585/176917546-5adf162e-f97d-4681-9726-e42f2dd9c85a.png)

Aside from the appearance, there are other points worth highlighting, that have been discussed with @wagtail/ui:

- [x] For naming, we want to retain the existing primary/secondary nomenclature rather than the designs’ "default" and "ghost".
- [x] The existing "yes" button variation doesn’t seem to be used anywhere and should be removed (regex for code search: `(button yes|button-small yes| button-secondary yes| yes")`)
- [x] ~~The existing "no" button variant,listed in the designs as "destructive" should be renamed to "critical", to match our naming conventions elsewhere (regex: `(button no|button-small no| button-secondary no| no"|button serious|button-small serious| button-secondary serious| serious")`).~~ Important: De-scoped - not renaming any classes but just removing those not used. 
- [x] Remove the `unbutton` styles

The following component variations should be covered:

- [x] Button
- [ ] Button with icon
- [x] Secondary button
- [ ] Secondary button with icon
- [x] Critical button
- [x] Small button
- [ ] Small button with icon
- [ ] Small secondary button
- [ ] Small secondary button with icon
- [ ] Small critical button
- [ ] (not in the designs) icon-only variations of the above

For each, the button should have:

- [x] Disabled ("Inactive") styles
- [x] Hover styles implemented as per the designs (only if active)
- [x] Focus (`focus-visible`) styles using the hover styles + our standard outline (only if active)

The following variations are out of scope:

- New style of small ghost button with icon
- Drop-up
- Button groups

## Implementation

Buttons are relatively consistently implemented with class names, so there isn’t necessarily a need to do any refactorings to how they are defined, though this would be valuable (suggestions welcome). We need to make sure the button styles keep working with the three target elements: `a`, `button`, `input type="submit"`.

**Comment by lb-** [comment]
@PaarthAgarwal  as per discussion - please start to have a read of this in full and start to look at the styles.

Now that 4.0 is almost at RC - we may want to consider using a `w-button` base classname for buttons.

**Comment by lb-** [comment]
Discussed this a bit today

* Should aim to use the html as is (except for scenarios where the tag is incorrect), including the classes
* There will be a huge amount of classes copied/pasted in other code (including packages) so breaking this may be an issue

**Comment by lb-** [comment]
Some useful links about buttons.

https://css-tricks.com/a-complete-guide-to-links-and-buttons/
https://www.buttoncheatsheet.com/
https://a11y-101.com/design/button-vs-link

**Comment by Scotchester** [comment]
> * (not in the designs) icon-only variations of the above

I noticed that in the current styleguide on main that icon-only buttons have no border or background of any kind, which seems potentially problematic.

![Icon-only buttons with no border or background](https://user-images.githubusercontent.com/1044670/186442963-a586b780-259c-4b0e-b04a-c0253f062ea6.png)

A cursory search indicates that this could affect at least:
- Modal close buttons (I know Paarth is already looking at those)
- Inline panel up/down/delete buttons
- TypedTableBlock interface buttons

**Comment by helenb** [comment]
@Scotchester's point has made me think that we should also be considering the high contrast work that @janehughes is mentoring in the button styling changes - one thing to consider is that even if there are no visible borders, it will be good to add a border with the same colour as the background in order to allow the buttons to stand out clearly in high contrast mode. It would be great if @janehughes could give us any other guidance points we should follow here.

**Comment by lb-** [comment]
@thibaudcolas  what is the plan for the `warning` buttons - it appears they are used for scenarios where you want to remove or publish a revision for pages / snippets.

This is not covered anywhere on the Figma or current discussions.

<img width="1445" alt="Screen Shot 2022-09-07 at 8 09 10 am" src="https://user-images.githubusercontent.com/1396140/188749279-862f283c-6013-4175-a930-b3310166f100.png">

**Comment by lb-** [comment]
Just flagging - I recommend we do not remove focus outlines for disabled buttons.

* When using an actual `button` with `disabled` - it is not focusable so this is a non issue
* When using the class `.disabled` (e.g. a link styled as a button OR cases where a button still just adds the disabled class) - the button is still focusable, so removing focus outline will cause an odd 'gap' when tabbing around the UI

We should instead avoid this problem where we can by only using `disabled` attributes on buttons and for links it is probably a non issue for now as disabling the link will require additional JS which is unlikely to be implemented. Long term we should probably just avoid the `disabled class from being available at all.

**Comment by lb-** [comment]
Action from final UX Unification call today

* LB to review this issue, split out anything critical that is left over to new issue/s OR update other existing issues with notes & clarity
* The ghost (aka secondary) button with icon is a new styling and is not really required for the unification work, can be done in isolation if needed in the future.
* The core work of this issue is done and upgrade considerations (for removed classes) are in the 4.1 release notes.

I will process these actions this week and assign myself this issue.

**Comment by lb-** [comment]
button secondary with icon work has been split to https://github.com/wagtail/wagtail/issues/9198
