### ISSUE TITLE
UX Unification – help block component with variations

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8791]
## Overview

We need to update our help block component’s appearance (colors in particular) to match its [appearance in our new design system](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=5181%3A33560):

![help block](https://user-images.githubusercontent.com/877585/176918684-ad854cbf-971e-4c15-be92-cfd2e9c85831.png)

## Variations

[See Wagtail 3 as-is, 4 to-be side by side](https://www.figma.com/file/3SZAkXYKTo52047weXDvb9/Wagtail-3-UI-Inventory?node-id=6674%3A34717). There are three color themes to change:

- [ ] Info
- [ ] Warning
- [ ] Critical

The color combinations have already been implelemented in our dialog component, for reference: https://github.com/wagtail/wagtail/blob/main/client/scss/components/_dialog.scss#L102

```scss
    &--info {
      background: theme('colors.info.50');
      color: theme('colors.info.100');
    }

    &--warning {
      background: theme('colors.warning.50');
      color: theme('colors.primary.DEFAULT');
    }

    &--critical {
      background: theme('colors.critical.50');
      color: theme('colors.critical.200');
    }
```

Here, `color` corresponds to the color of the _icon_ only. In all three cases, the text color should be `color: theme('colors.grey.600')`.

## Implementation

Compared to the designs, there are three important aspects to highlight for the implementation:

- [ ] The warning icon needs to be `color: theme('colors.primary.DEFAULT')` rather than the dark yellow, to pass contrast checks
- [ ] Similarly, links inside the help blocks need to be `color: theme('colors.secondary.200')` to offer enough contrast
- [ ] And the links need to have an underline by default, no underline on hover, so they can be identified compared to normal text
- [ ] Bonus points: for RTL languages, we should horizontally mirror the icon so the question mark points the other way. (#8127)

The help block styles are already quite well defined so there isn’t necessarily a need to refactor their usage, but any suggestions are welcome.

**Comment by PaarthAgarwal** [comment]
When I try to add color:theme('colors.teal.200') the console throws error:

`'colors.teal.200' does not exist in your theme config. 'colors' has the following keys: 'black', 'grey', 'white', 'primary', 'secondary', 'info', 'positive', 'warning', 'critical', 'white-15', 'white-50', 'white-80', 'white-85', 'black-10', 'black-20', 'black-35', 'black-50', 'inherit', 'current', 'transparent', 'LinkText''colors.teal.200' does not exist in your theme config. 'colors' has the following keys: 'black', 'grey', 'white', 'primary', 'secondary', 'info', 'positive', 'warning', 'critical', 'white-15', 'white-50', 'white-80', 'white-85', 'black-10', 'black-20', 'black-35', 'black-50', 'inherit', 'current', 'transparent', 'LinkText''colors.teal.200' does not exist in your theme config. 'colors' has the following keys: 'black', 'grey', 'white', 'primary', 'secondary', 'info', 'positive', 'warning', 'critical', 'white-15', 'white-50', 'white-80', 'white-85', 'black-10', 'black-20', 'black-35', 'black-50', 'inherit', 'current', 'transparent', 'LinkText'`

**Comment by lb-** [comment]
RTL icons not done but the rest of the items are resolved via https://github.com/wagtail/wagtail/pull/8896
Closing issue
