### ISSUE TITLE
Pin beautifulsoup4 to a newer version

### ISSUE THREAD

**Issue by sephii** [wagtail/wagtail#8797]
### Is your proposal related to a problem?

The current `install_requires` requires `beautifulsoup4>=4.8,<4.10`. The latest release of Beautifulsoup4 4.9 goes back to 2020. The problem with this release is that it relies on a `use_2to3` feature removed in setuptools 58+, meaning Wagtail can’t be installed in environments that use setuptools 58+.

### Describe the solution you'd like

Upgrade the pinned version of Beautifulsoup4. I’m using 4.11.1 in a personal project and everything works fine and the Wagtail tests pass.

### Describe alternatives you've considered

None.

### Additional context

None.

**Comment by gasman** [comment]
Done in #8801 - thanks for flagging this, @sephii!
