### ISSUE TITLE
patternlibrary_override_tags breaks all non-development installations

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#8798]
#8665 added a `patternlibrary_override_tags` tag library to wagtail.admin, which depends on the django-pattern-library package listed in our testing_extras dependencies. However, this tag library will be loaded on all environments that have `wagtail.admin` in their INSTALLED_APPS, so any Wagtail installation that doesn't include testing_extras is currently broken.

As a non-frontend dev, I don't know what this tag library is for, and there's no documentation for me to find out. Deleting it and uninstalling django-pattern-library doesn't break any tests, so it seems to me that it doesn't really belong in the testing dependencies. (If it really is a testing dependency, I'd suggest that moving patternlibrary_override_tags.py into one of the test apps in wagtail/test/ would let it do whatever it's meant to do without breaking non-testing environments.)

**Comment by lb-** [comment]
@gasman my apologies - I assumed that was installed as we use pattern library already.

To be honest - not super sure on how to work around this so maybe I should just revert that PR for now?

I might not have time to look into this fully sorry. But agree this should be documented correctly.

cc @thibaudcolas

**Comment by lb-** [comment]
PR up to revert for now https://github.com/wagtail/wagtail/pull/8800

**Comment by lb-** [comment]
Thanks for the info @gasman - will try to keep an eye out for that kind of issue again in the future.
