### ISSUE TITLE
UX Unification – restyle dashboard summary metrics

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8818]
### Is your proposal related to a problem?

Dashboard summary metrics look a bit dated.

### Describe the solution you'd like

Here is the proposed design for this component:

![dashboard-header-latest](https://user-images.githubusercontent.com/877585/177798876-96bbeaeb-a2e2-44b6-8377-18510bcf9c14.png)

[Figma link](https://www.figma.com/proto/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=6087%3A36870&viewport=3489%2C1106%2C0.51&scaling=min-zoom&starting-point-node-id=6899%3A41010&show-proto-sidebar=1&hide-ui=1)

The goal is to reskin the component while keeping the implementation more or less the same. We could nonetheless consider:

- Adding a Storybook story for it
- Refactoring the markup so the `site_summary.html`’s `section` has a `aria-labelledby` pointing at the heading.
- Moving the CSS for this from `_home.scss` to its own component file
- Removing all usage of `float`, `clear`, and position relative/absolute from this code (#8125, #8126).

**Comment by lb-** [comment]
@PaarthAgarwal  for now let's use the non-inverse variants of the icons for the doc/page

* icon-doc-empty - for page
* icon-doc-full - for documents

**Comment by lb-** [comment]
@PaarthAgarwal  we probably also need a description 'slot' under the header, this is useful for showing additional info that is not suitable in the `h1` subtitle. maybe this could be added and then used instead of the subtitle for the username in the dashboard header.

something like this.


wagtail/admin/templates/wagtailadmin/shared/header.html

```
            <div class="col">
                <h1 class="w-header__title">
                    {% if icon %}
                        {% icon class_name="w-header__glyph" name=icon %}
                    {% elif avatar %}
                        <div class="w-header__glyph avatar"><img src="{{ avatar }}" alt="" /></div>
                    {% endif %}
                    {{ title }}{% if subtitle %} <span class="w-header__subtitle">{{ subtitle }}</span>{% endif %}
                </h1>
                {% if desciption %} <span class="w-header__description">{{ desciption }}</span>{% endif %}
            </div>
```
