### ISSUE TITLE
Contrast themes – Invisible login & password reset fields in WHCM

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8837]
In WHCM, with our login/password reset form styles, the fields are invisible:

![Image](https://user-images.githubusercontent.com/877585/178256216-68d844b9-9dac-4d69-8e22-b02f78568bd0.png)

Figma link: https://www.figma.com/file/O81E48wieOZ7e6AivvksWn/Contrast-themes%3A-Wagtail-audit?node-id=6613%3A43817

Form the "Login" form, you can still tell where the field might be thanks to the placeholder. For the Reset form, it’s impossible to tell where the field is.

In both cases, we should add a transparent border so the fields can be located in forced-colors mode.

**Comment by lb-** [comment]
Fixed via d2529cad9211434532bd27fa69c2ad0c0f1437ed /  #8925 

Note: logo could be better but not sure that it is a critical issue.

## dark

<img width="1675" alt="Screen Shot 2022-08-06 at 10 03 41 pm" src="https://user-images.githubusercontent.com/1396140/183248261-4fe52611-2242-4f32-a5ff-13fed343fc44.png">

## light

<img width="665" alt="Screen Shot 2022-08-06 at 10 04 12 pm" src="https://user-images.githubusercontent.com/1396140/183248252-d41cb895-1b6a-4ab8-bc34-edabf8fff583.png">
<img width="1664" alt="Screen Shot 2022-08-06 at 10 04 00 pm" src="https://user-images.githubusercontent.com/1396140/183248255-5b4ee4d6-3e1f-4ca4-af11-2441cec48f0c.png">



cc @anujaraj
