### ISSUE TITLE
Workflow reports showing for user with limited permissions.

### ISSUE THREAD

**Issue by cnk** [wagtail/wagtail#8845]
### Issue Summary

I have a user belonging to a group with very limited permissions and no permissions assigned at the user level. The Wagtail admin is correctly limiting which snippet models this user can see, but I am surprised they can see Workflow and Aging Pages reports. I expected the admin menu to only show "Snippets". 

<img width="434" alt="Screen Shot 2022-07-12 at 12 25 18 PM" src="https://user-images.githubusercontent.com/5952/178578684-db6ef16d-e7c5-4514-964b-2415c480ec77.png">

<img width="824" alt="Screen Shot 2022-07-12 at 12 24 44 PM" src="https://user-images.githubusercontent.com/5952/178578725-afc8f5bc-1c0a-4301-ac48-f5cb6c37f1ef.png">

<img width="474" alt="Screen Shot 2022-07-12 at 12 25 04 PM" src="https://user-images.githubusercontent.com/5952/178578761-7bd6f835-8b26-41b2-9abf-a0a654dddb8e.png">

### Technical details

Python version: 3.8.5
Django version: 4.0.6
Wagtail version: GitHub main as of July 11 SHA: https://github.com/wagtail/wagtail/commit/22cf8c240d5459b2837a67319fb385f11f54492d

**Comment by Dolidodzik** [comment]
I checked that and it's just visual

![image](https://user-images.githubusercontent.com/45403119/179059112-2d4b5d38-e8b3-4224-ab05-1992901a9223.png)
![image](https://user-images.githubusercontent.com/45403119/179059006-c509ee20-8d78-404b-a182-da0d56acffd3.png)

**Comment by Dolidodzik** [comment]
I think this issue can be solved only with changes to admin frontend - users without permissions for reports shouldn't see that tab in sidebar at all, and I think I am capable of making that fix.

**Comment by Dolidodzik** [comment]
So, I started working on this issue, and before opening PR I'd like to ask someone more experienced a question (maybe @cnk 
 or @zerolab) - how can I check if user is supposed to see aging pages or not? I couldn't find a permission for that anywhere.

I already changed display of workflow items in navbar (by basically checking for `wagtailcore.view_workflowpage` permission in `WorkflowReportMenuItem `), and it works fine - moderators/editors/administrators have workflow options in navbar, and limited users don't. Only thing is, limited users still can see aging pages, which I guess they shouldn't.

**Comment by Dolidodzik** [comment]
Thank you for help @zerolab! Yeah this solution seems much cleaner, last time I tried to re-invent a wheel on my own. I created PR with fix, and it should be ready to review.

**Comment by rohitsrma** [comment]
@lb- Can i work on this?

**Comment by zerolab** [comment]
@rohitsrma go for it as there is no PR for it.

Also, leaving https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html here, and https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html#contributing-a-solution in particular

**Comment by rohitsrma** [comment]
@zerolab I apologize for not following the contribution guidelines.

I would be glad to collaborate with @Dolidodzik  on this. However, it seems that he has not been actively working on #8872  for almost a year. If you permit, I can proceed with creating a PR.

**Comment by zerolab** [comment]
@rohitsrma not a problem. Please proceed with an updated PR based on #8845. Can you please reference this issue and add a note about superceding #8845 when you open your PR? We'll then close #8845, but I'd like to credit @Dolidodzik on it too.

**Comment by gasman** [comment]
Fixed in #11205
