### ISSUE TITLE
Documentation - Avoid Latin abbreviations for common English phrases

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8860]
- Currently mixed “eg” and “For example”, but always corrected by Tom to full version in past
- Google + Microsoft standards recommend avoiding latin abbreviations
- We should be consistent with this and the general consensus from the core team meeting  (6th of July) was to go for non-Latin versions

### Pertinent section of the Wagtail docs

* Add a sub-section to the Language part of https://docs.wagtail.org/en/latest/contributing/general_guidelines.html
* The Microsoft guideline (with the table of examples) is a good way to start.
* Update any existing usage to the new preferred variant.

---

* Avoid non-English words or phrases, such as _de facto_ or _ad hoc_.
* Avoid Latin abbreviations for common English phrases.
* **Exception** It’s OK to use _etc.,_ in situations where space is limited.

Use this | Instead of this
-- | --
for example | e.g.
that is | i.e.
namely | viz.
therefore | ergo

### Examples

* https://docs.microsoft.com/en-us/style-guide/word-choice/use-us-spelling-avoid-non-english-words
* https://developers.google.com/style/abbreviations#dont-use

**Comment by lb-** [comment]
@kaedroho FYI - created this from the meeting minutes the other week.
Marking as a good first issue for anyone to pick up.

**Comment by Dolidodzik** [comment]
I think I can pickup this issue, seems like an easy one.

**Comment by lb-** [comment]
Go for it. Just be sure to search for variations like `e.g.` and `eg`

**Comment by lb-** [comment]
Also. Be sure to check documentation in python and JavaScript files. For example docstrings and JSDOC

**Comment by Dolidodzik** [comment]
Sure, I'll keep that in mind

**Comment by kaedroho** [comment]
@lb- Thanks for creating this!

**Comment by Dolidodzik** [comment]
I think my PR (#8861) replaced all of latin abbreviations. The thing is, I was using automated searching with grep (for example `grep -ir "e\.g" --exclude-dir="releases" --exclude-dir="_build"`), so something could slip past me.
