### ISSUE TITLE
Improve organisation of settings reference page

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#8863]
### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/latest/reference/settings.html

### Details

The Settings reference page is ostensibly organised into category subheadings ("Site name", "Append Slash"...), but since settings generally get added one-by-one with no plan for how they relate to each other, most of the subheadings only have one or two items in them, and so people end up having to read through the whole list to find the one setting they're interested in. I'd like to see these organised into fewer, broader categories.

The "correct" categorisation is a matter of opinion, of course, but I think that anyone with a basic familiarity with Wagtail's feature set could make an improvement here. My suggestions are:

* ensure all headings are named consistently, in particular: don't capitalise ADMIN BASE URL, and change "API Settings" to just "API" (everything here is a setting, so the word Settings is redundant...)
* Categories that map to a specific sub-app of Wagtail (Search, Embeds, Images, Documents, API, Frontend cache, Redirects, Form builder) should stay
* WAGTAIL_SITE_NAME and WAGTAILADMIN_BASE_URL should go together under a heading **"Sites"** or similar
* WAGTAIL_GRAVATAR_PROVIDER_URL, WAGTAIL_USER_TIME_ZONES and WAGTAILADMIN_PERMITTED_LANGUAGES go together under a heading "User preferences"
* TAGGIT_CASE_INSENSITIVE, TAG_SPACES_ALLOWED, TAG_LIMIT go together under a heading **"Tags"**
* WAGTAILADMIN_COMMENTS_ENABLED, WAGTAIL_ALLOW_UNICODE_SLUGS, WAGTAIL_AUTO_UPDATE_PREVIEW, WAGTAIL_AUTO_UPDATE_PREVIEW_INTERVAL, WAGTAILADMIN_GLOBAL_PAGE_EDIT_LOCK, WAGTAILADMIN_UNSAFE_PAGE_DELETION_LIMIT go together under a heading **"Page editing"** - _maybe_ WAGTAILADMIN_RICH_TEXT_EDITORS and WAGTAILADMIN_EXTERNAL_LINK_CONVERSION go here too
* Everything under "Password management" and "Custom user edit forms", plus WAGTAILADMIN_USER_LOGIN_FORM, can go together under a heading **"User management"**
* "Private pages / documents" and the remaining items under "Login page" can become a new heading **"Front-end authentication"**

Other ideas are welcome!

**Comment by Akash-Kumar-Sen** [comment]
Hello @gasman  I was trying to set up the wagtail codebase in my computer. I followed the exact steps mentioned in https://docs.wagtail.org/en/latest/contributing/developing.html#developing-for-wagtail and while running the test part 'python runtests.py' It is giving some errors. The issue  looks like mostly documentation oriented, so if you can guide me and show how to edit or change the documentation it would be really helpful. I am a newcomer one small help from your side can be a milestone in my entire open-source journey. Please help me.

**Comment by gasman** [comment]
Hi @Akash-Kumar-Sen,
The [Wagtail Slack workspace](https://github.com/wagtail/wagtail/wiki/Slack) is the best place for getting help with this - or see [the Support page in the documentation](https://docs.wagtail.io/en/stable/support.html) for other options.

**Comment by lb-** [comment]
Fixed via 827bcf3dbf3a007e9218d3955b3d9998041d63e8 / #8950
