### ISSUE TITLE
UX Unification - Cleanup for slim header in page listing

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#8864]
### Issue Summary

#8792 introduced some issues due to conflict with other PRs that have been merged previously. In addition, there are also other improvements that can be made.

### Details

- [ ] When moving `.form-side` styles to its own `_form-side.scss` file, some updates introduced in #8671 weren't carried over. By the way, should this be in `components` rather than `layouts`?
  **Original:** https://github.com/wagtail/wagtail/blob/0693eed2454240b4d0f31da5166772bdd106dbb9/client/scss/layouts/_page-editor.scss#L61-L103
  **Moved:** https://github.com/wagtail/wagtail/blob/35b5ed350a30dfb626d55c0b2c021976c1f65761/client/scss/layouts/_form-side.scss#L5-L47
- [ ] When moving side panel init code to a separate `sidePanel.js` file, the original code in `page-editor.js` hasn't been removed. This results in the event listeners being registered twice, making the side panels inaccessible in the page editor (it immediately closes again). To fix this, remove the following: https://github.com/wagtail/wagtail/blob/35b5ed350a30dfb626d55c0b2c021976c1f65761/client/src/entrypoints/admin/page-editor.js#L333-L407
- [ ] The locale selector in the side panel should take the user to the localised page in the **page explorer**. Right now, it brings you to the editor instead. Possible solutions: add another keyword argument to `PageSidePanels`, e.g. `in_explorer`, or make a subclass e.g. `PageExplorerSidePanels` in case we need more customisations in the future.

There may be other issues I haven't noticed. Will update later if I find more.

**Comment by PaarthAgarwal** [comment]
> ### Issue Summary
> #8781 introduced some issues due to conflict with other PRs that have been merged previously. In addition, there are also other improvements that can be made.

Did you mean to tag #8792 ?

**Comment by laymonage** [comment]
> Did you mean to tag #8792 ?

Oops. Yep, thanks!

PR: #8865.
