### ISSUE TITLE
Page listing header: new designs

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8868]
Follow-up to #8792.

We need to implement the target design for the page listing’s slim header:

![listing-header-latest](https://user-images.githubusercontent.com/877585/177798199-bea5285e-993a-4c17-b7bf-9f4c2df12df7.png)

[Figma link](https://www.figma.com/proto/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=6891%3A36234&viewport=3489%2C1106%2C0.51&scaling=min-zoom&starting-point-node-id=6899%3A41010&show-proto-sidebar=1&hide-ui=1)

If possible, we should implement this with either utility classes or BEM rather than complex selectors, removing [the current intermediary step](https://github.com/wagtail/wagtail/blob/efaad2593217001c3505c5f1ce7a558a882737a2/client/scss/components/_listing.scss#L471-L478).

**Comment by lb-** [comment]
PR up https://github.com/wagtail/wagtail/pull/8920
While this does not rework the whole CSS of the header it is good enough to meet the designs so will flag that that PR will close this.

If we need to redo the styles in the future we still can (for slim header) but will leave it as is until it's really needed.

**Comment by lb-** [comment]
@thibaudcolas  maybe it's best we wait for any refactoring of the overall styles (moving back away from full on utility classes) until we have a clearer UI development guideline. I went to raise two new issues for breadcrumbs/slim header to be easier to maintain but it might be best to land on our desired approach as a team before raising more refactoring tickets.
