### ISSUE TITLE
Choose parent page, radio buttons overlap

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#8869]
# Issue Summary

The 'Choose parent page' view is broken: The radio button labels overlap.

## Current

<img width="1800" alt="current" src="https://user-images.githubusercontent.com/1969342/179691599-ca7ff876-3fc1-4116-ba38-1c78f2b5359f.png">

## Expected

<img width="1800" alt="expected" src="https://user-images.githubusercontent.com/1969342/179691591-0ad83a0a-316d-410a-9c04-84ecd47943dc.png">

# Steps to Reproduce

1. In bakerydemo, create a new file `blog/wagtail_hooks.py`
  ```
  from wagtail.contrib.modeladmin.options import ModelAdmin, modeladmin_register
  
  from .models import BlogPage
  
  
  class BlogAdmin(ModelAdmin):
      model = BlogPage
  
  
  modeladmin_register(BlogAdmin)
  ```

2. Stop/start the server to pickup the hooks file.
3. You need multiple `Blog index page` items for the choose parent view to show.
4. Go to `/admin/blog/blogpage/choose_parent/`
5. The radio select alignment is broken.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: YES

# Technical details

-   Python version: Python 3.9.9
-   Django version: 4.0.6
-   Wagtail version: 3.0.1
-   Browser version: latest Chrome, latest FireFox.

# Workaround

I've created an app called `adminfix` the layout is:

```
├── adminfix
│   ├── __init__.py
│   ├── __pycache__
│   │   └── __init__.cpython-39.pyc
│   └── static
│       └── wagtailmodeladmin
│           └── css
│               └── choose_parent_page.css
```
It should come before wagtail in `INSTALLED_APPS`, so that `choose_parent_page.css` overrides Wagtails `choose_parent_page.css`.

The Wagtail contents of `choose_parent_page.css` file is:
```
#id_parent_page li { margin:15px 0 }
#id_parent_page li label{ float:none }
```
The override of `choose_parent_page.css` contains:
```
#id_parent_page div { margin:15px 0 }
#id_parent_page div label { float:none }
```

# Workaround 2

Don't upgrade to Django 4, keep using Django LTS 3.2.x.

**Comment by gasman** [comment]
Thanks for reporting, @allcaps!
Looks like another instance of #8494 - I'm guessing this page doesn't use our standard form markup, so the CSS fixes there aren't picked up.

**Comment by allcaps** [comment]
Do we want to fix the CSS like in the other issue? OR do we want to fix the HTML markup?

I'll submit a PR.

**Comment by thibaudcolas** [comment]
I’m already working on form styles for Wagtail 4 that will fix this. If you want to address it in a Wagtail 3, the CSS hack seems like a fair approach. Note the `choose_parent_page.css` has been removed in `main`, the corresponding styles are now in: https://github.com/wagtail/wagtail/blob/main/client/scss/layouts/_modeladmin-choose-parent-page.scss
