### ISSUE TITLE
TableBlock is impossible to reach with the keyboard

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8893]
### Issue Summary

Wagtail’s TableBlock table widget is impossible to reach with a keyboard:

![table-block-widget](https://user-images.githubusercontent.com/877585/180469434-5ad4bc9a-4604-420a-bc8b-4d142b5a2f61.gif)

### Steps to Reproduce

1. In StreamField, add a TableBlock
2. Try to navigate to its Handsontable table widget

**Comment by Akash-Kumar-Sen** [comment]
Hi @thibaudcolas I want to work on this issue. Can you please assign this to me

**Comment by lb-** [comment]
Go for it @Akash-Kumar-Sen - we don't really assign issues to those outside of core team so just a comment that you are interested is good enough. 

Really appreciate your interest in this and let us know if you need a hand.
