### ISSUE TITLE
Adopt core shared header for ModelAdmin headers

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8907]
### Is your proposal related to a problem?

`ModelAdmin` header is one of the last major header usage within the admin that is not using the using the core (non-slim) shared header template.

### Describe the solution you'd like

* Using either a template that extends the shared header OR the template include, ensure that the  [wagtail/contrib/modeladmin/templates/modeladmin/index.html](https://github.com/wagtail/wagtail/blob/main/wagtail/contrib/modeladmin/templates/modeladmin/index.html) view uses the shared header.
* This is so that shared styles will all work the same and do not need to be maintained across multiple files.
* Must preserve existing ability to override the modeladmin header and relevant templates to add custom content.

### Describe alternatives you've considered

* Leave as is, ok to maintain these in isolation for the most part.

### Additional context

* Any blocks must be preserved, especially for modeladmin, as developers will often extend templates to add custom content.
* Split from initial work to unify headers https://github.com/wagtail/wagtail/issues/8539

### Notes for potential implementation approach

* Most likely need to use template inheritance for this, create a new `wagtail/contrib/modeladmin/templates/modeladmin/includes/header.html` that extends `wagtail/admin/templates/wagtailadmin/shared/header.html`
* Add suitable blocks to the shared/header if needed, rough outline below; (note: as this is an extends, we will probably need a `with` added in the `wagtail/contrib/modeladmin/templates/modeladmin/index.html` to pass down the right variables.
  * `{% block h1 %}` inside `<div class="col">`
  * `{% if view.header_icon %}` will need to be replace with that icon being passed into the include
  * `view.get_page_title` will need to be passed into the include
  * `self.get_page_subtitle` will need to be passed into the include
  * `{% include 'modeladmin/includes/result_count.html' %}` will need to be passed into the include as `description` (with a release note change that this now appears outside the `h1` tag (which makes sense)
  * `{% if search_url %}` will need to be wrapped in a block `{% block search %}`
  * `{% block header_extra %}` should probably be set up as a fragment and passed into `extra_actions` on the include (this is a small breaking change, this block will no longer render outside `.right` column but this should be ok to 
* Clean up - we should drop the support of `block` `right_column_classname` and ensure the styles still work, remove any now unused styles, add release note about this no longer being supported.

**Comment by salty-ivy** [comment]
@lb- working on this one first followed by https://github.com/wagtail/wagtail/issues/9227 as you suggested.

**Comment by salty-ivy** [comment]
@lb- [PR](https://github.com/wagtail/wagtail/pull/9993) is Ready.

**Comment by lb-** [comment]
Thanks. I'll flag it for review.

**Comment by lb-** [comment]
Will need to raise a new issue after this - the clean up step above and probably should try to align the right/left class names with BEM naming if possible.
