### ISSUE TITLE
On a GIF file, get_rendition("original") returns a PNG instead of a GIF 

### ISSUE THREAD

**Issue by fabienheureux** [wagtail/wagtail#8910]
### Issue Summary

When working with gif images, the `original` filter passed to the `get_rendition()` method returns a .png.

#### Example repo 

1. Clone this repo https://github.com/fabienheureux/wagtail_debug_gif_issue 
2. Install dependencies (`pip i -r requirements.txt` or `poetry install`)
3. `./manage.py runserver` (a sample db and media directory contains enough data to reproduce the issue)
4. Connect with **admin** / **admin** 
5. Go to http://localhost:8000/admin/images/1/
6. Click on the filename 
7. The loaded url is a .png file 

#### From an existing wagtail website
1. Upload this gif 
![eclamation-v4-@2x](https://user-images.githubusercontent.com/1702255/181200970-599fe974-e1bd-4548-81f9-244d6afd68a3.gif)
2. From the wagtail image edit view, click on the filename 
<img width="602" alt="image" src="https://user-images.githubusercontent.com/1702255/181201111-769a01a5-5980-491d-a13f-5bbc4e0012b1.png">
3. Check that the url loads a `.png` file `http://localhost:8000/media/images/eclamation-v4-2x.original.png` for example 

#### From a django shell
1. Query a gif image, for example `Image.objects.filter(file__endswith=".gif").first().get_rendition("original").file`
2. Check that the returned filename is a png `<ImageFieldFile: images/eclamation-v4-2x.original.png>`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10
-   Django version: 4.0.6
-   Wagtail version: 3.0.1

**Comment by lb-** [comment]
I might be missing something, but Wagtail does not support animated gifs out of the box.
https://docs.wagtail.org/en/stable/advanced_topics/images/animated_gifs.html

Maybe this is why the gif upload is not working?

**Comment by lb-** [comment]
ok looks like those docs are out of date https://github.com/wagtail/Willow
https://github.com/wagtail/wagtail/blob/bcb5b2baacbfec5da0c82b96da3b19dbddf70b5a/setup.py#L33

**Comment by fabienheureux** [comment]
Thanks @lb- ! 
Well, I forgot that native support for gif required Wand, but the project I work on has Wand installed and gifs were working properly until recently. 

I added wand to my debug repo and things are working properly there. 
I am closing this issue as I am now 99% sure it comes from my project's code. 

If I find something interesting I will comment with the source of the original issue.
