### ISSUE TITLE
__str__ method doesn't return a string.

### ISSUE THREAD

**Issue by xbello** [wagtail/wagtail#8927]
This code sample:

    >>> from wagtail.contrib.forms.models import FormSubmission

    >>> FormSubmission.objects.count()
    1
    >>> FormSubmission.objects.first()
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "lib64/python3.10/site-packages/django/db/models/base.py", line 580, in __repr__
        return "<%s: %s>" % (self.__class__.__name__, self)
      TypeError: __str__ returned non-string (type dict)

This method:

https://github.com/wagtail/wagtail/blob/18ad15a18f8e533b858ccde7d060b9d4e85dcfd4/wagtail/contrib/forms/models.py#L61-L62

should be:

    def __str__(self):
        return f"{self.form_data}"

**Comment by lb-** [comment]
Looks like this broke with https://github.com/wagtail/wagtail/pull/8230

Have confirmed it's an issue

Thanks for raising @xbello

**Comment by lb-** [comment]
PR up https://github.com/wagtail/wagtail/pull/8940
