### ISSUE TITLE
Sidebar (main menu) - page explorer - styling issue with header item on small breakpoints

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8939]
### Issue Summary

On small breakpoints, and mobile devices, the height of the header item (e.g. the current 'tree') selected in the page explorer appears to be slightly off.

This is more noticeable when hovering over that item, you can see that there is a ~5px gap above and to the left of the item when compared to the open/close toggle button.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject` or load in gitpod
2. Sign in to the admin page
3. Make your browser with less than ~795px wide to show the smaller breakpoint
4. Open the sidebar, select the page explorer
5. Hover over the header at the top of the expanded sidebar's page explorer

Expected behaviour - this header item should be the same height as the toggle and come in 'tight' against the toggle without a visible gap.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Potential solution

It appears that the styling of `c-page-explorer__header` (link below) has not considered the small device case? Or maybe is a bit of legacy code.

https://github.com/wagtail/wagtail/blob/405af5d4515d44c846e1134aa355352a37ff3377/client/src/components/PageExplorer/PageExplorer.scss#L47-L48

### Technical details

-   Python version: 3.9
-   Django version: 4.0
-   Wagtail version: 4.0 WIP / RC
-   Browser version: Screenshots below of Safari Version 15.4 (17613.1.17.1.6), Firefox 103.0, Chrome 105 on macOS 12.3

### Screenshots

Each screenshot contains the header item in hovered state so the issue is more visible.

#### Firefox

<img width="1627" alt="Screen Shot 2022-08-04 at 7 28 34 am" src="https://user-images.githubusercontent.com/1396140/182717510-67a8d87e-c3f7-4ea8-89a1-5e0ac623f60f.png">

#### Chrome

<img width="674" alt="Screen Shot 2022-08-04 at 7 36 19 am" src="https://user-images.githubusercontent.com/1396140/182717539-3f1bf88e-c940-46a2-9bcc-ca4ac9813565.png">

#### Safari

<img width="645" alt="Screen Shot 2022-08-04 at 7 34 47 am" src="https://user-images.githubusercontent.com/1396140/182717572-4ff947db-33e7-498d-a8fe-e32e21cca24a.png">

**Comment by Akash-Kumar-Sen** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/71623442/183275191-27380a8a-66a6-4cb7-8d85-16c1db122ac5.png)
@lb-  Is this the expected look? Or any modification required?

**Comment by lb-** [comment]
That is looking good @Akash-Kumar-Sen  but if you look closely there is still a small bottom border showing for the pages part and a small top border.

**Comment by lb-** [comment]
Also - remember to check the focus outline with any changes made - it should be fully visible, but with these adjustments we may need to use focus outline offset -1 or -2px 

https://developer.mozilla.org/en-US/docs/Web/CSS/outline-offset

**Comment by Akash-Kumar-Sen** [comment]
Okay, I will update that. The outline offset is only for the header item or I should update the toggle button also?

**Comment by lb-** [comment]
As long as both have a clearly visible focus overlay - that is the goal.

**Comment by Akash-Kumar-Sen** [comment]
![Screenshot (41)](https://user-images.githubusercontent.com/71623442/183279485-2bd35e0e-97fe-4f90-b7e7-de6c1bf5d4e5.png)
Came this far...any suggestion?

**Comment by lb-** [comment]
Maybe do a draft PR and I can comment. Hard to give advice without seeing the code.
