### ISSUE TITLE
Invalid expression in wagtail-4.0 (dev20220804) header template

### ISSUE THREAD

**Issue by danhayden** [wagtail/wagtail#8942]
### Issue Summary

I'm trying out the [wagtail nightly](https://releases.wagtail.org/nightly/dist/wagtail-4.0.dev20220804-py3-none-any.whl) to see if my project works with the progress so far on wagtail 4

I have this line added to my template settings that will render a string if the there is an invalid expression in the template `"string_if_invalid": "INVALID EXPRESSION: [%s]"` (recommended in [two-scoops-of-django-3-x](https://www.feldroy.com/books/two-scoops-of-django-3-x)).

Since updating to the nightly it renders `INVALID EXPRESSION: [extra_actions]` in several page and model headers as can be seen in the screenshot below.

![Screen Shot 2022-08-04 at 12 18 07](https://user-images.githubusercontent.com/1385253/182843554-c39f6098-8539-4ffb-8d37-75e4e09d5532.png)

Is there an issue in the new header template?
Perhaps just needs to check if extra_actions exists like `{% if extra_actions %}{{ extra_actions }}{% endif %}`

### Steps to Reproduce

1. add `"string_if_invalid": "INVALID EXPRESSION: [%s]"` to template settings:
```
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "OPTIONS": {
            "context_processors": [...],
            "string_if_invalid": "INVALID EXPRESSION: [%s]",
        },
    },
]
```
2. Navigate to admin

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10.6
-   Django version: 3.2.15
-   Wagtail version: wagtail-4.0.dev20220804-py3-none-any.whl
-   Browser version: Firefox 103

**Comment by lb-** [comment]
@PaarthAgarwal  can you take a look at this one.

Looks like we need some extra logic around the `extra_actions` usage.
https://github.com/wagtail/wagtail/blob/6429f8d40b34d181c50d170f0e011c1f1cba506e/wagtail/admin/templates/wagtailadmin/shared/header.html#L59

Please follow the steps above to make the error more visible, should probably be just a matter of updating line 59 to 

```
            {% if extra_actions %}{{ extra_actions }}{% endif %}
```

**Comment by lb-** [comment]
Probably not a bug but it is a change that we should refine for 4.0 and avoid introducing without some guard rails around it.


Here are the Django docs about how invalid (empty/undefined) variables are handled. https://docs.djangoproject.com/en/4.1/ref/templates/api/#how-invalid-variables-are-handled

**Comment by PaarthAgarwal** [comment]
I see
