### ISSUE TITLE
Page queryset method not_public returns public pages

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#8952]
### Issue Summary

When no ‘restricted pages’ exists, Page.objects.not_public() returns public pages.

### Steps to Reproduce

Create some pages without a privacy setting.
Run: $ python manage.py shell

from wagtail.core.models import Page
restricted_pages =  Page.objects.not_public()
restricted_pages
<PageQuerySet [<Page: Root>, <Page: Welkom bij Confetti>, <Page: Zoek op deze site>,

### Technical details

Python 3.7.9
Django 3.2.14
Wagtail 2.16.2

### Workaround

```
not_public = queryset.not_public()
if set(queryset) == set(not_public):
    return queryset.none()
else:
    return not_public
```

**Comment by chosak** [comment]
I can confirm this, on main (pre-4.0). With a brand new database:

```
>>> from wagtail.models import Page
>>> Page.objects.all()
<PageQuerySet [<Page: Root>, <Page: Home>]>
>>> Page.objects.public()
<PageQuerySet [<Page: Root>, <Page: Home>]>
>>> Page.objects.not_public()
<PageQuerySet [<Page: Root>, <Page: Home>]>
```

The reason for this is the [`Page.objects.public_q` logic](https://github.com/wagtail/wagtail/blob/71dfb4090bead76c34aae780582fc7efb280adb1/wagtail/query.py#L238-L256) used to implement this functionality defines "public" as

> (not in private section 1) + (not in private section 2) + ...

and then private as

> all pages - public pages

which translates to

> all pages - ((not in private section 1) + (not in private section 2) + ...)

But if there are no private sections, then the above simplifies to just "all pages".

A possible fix to this would be to instead define public and private in terms of a new `Page.objects.private_q` method that covers all pages in all private sections. Then using `filter` and `exclude` on that Q object should work properly.
