### ISSUE TITLE
RichText Toolbar is no longer sticky

### ISSUE THREAD

**Issue by danpaulson** [wagtail/wagtail#8955]
### Issue Summary

In some recent version of Wagtail, the toolbar has become "unsticky", in that it no longer travels with the user as they traverse the document. This has lead to a few mentions on Slack, and feels like a step back in terms of usability.

### Steps to Reproduce

Seems to be out of the box functionality on a base install.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / **no**)

### Technical details

The following CSS re-enables stickyness:

```
{% block extra_css %}
<style>
.Draftail-Toolbar {
    position: sticky !important;
    top: calc(1rem + 51px) !important;
    z-index: 10 !important;
}
</style>
{% endblock %}
```

**Comment by lb-** [comment]
Not sure but this ifwhr issue may be related. 

https://github.com/wagtail/wagtail/issues/8915

**Comment by thibaudcolas** [comment]
Hi @danpaulson, could you provide a screenshot of what this looks like for you? Make sure to follow our full report templates, including technical details:

```markdown
### Technical details

-   Python version: Run `python --version`.
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
```

It’s unclear to me whether you’re referring to the same issue as #8915, which is in Wagtail 3.0+, or more recent changes which were only on `main` in git at the point of your comment.

**Comment by gasman** [comment]
Closing due to lack of response - the rich text toolbar has been redesigned in Wagtail 4.0, and without further information it's unclear whether this has now been addressed. If the problem here is still outstanding, please open a new issue with the full information as requested.
