### ISSUE TITLE
Client-side (frontend) approach to deprecation warnings

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8956]
### Is your proposal related to a problem?

As Wagtail refactors parts of the JavaScript code, including documented APIs such as the chooser interface, it would be good to provide communication to developers (not just contributors) about deprecations.

### Describe the solution you'd like

In a similar way to the Django approach of a `warnings` module that we extend here https://github.com/wagtail/wagtail/blob/main/wagtail/utils/deprecation.py

We could build an equivalent client-side module that is only loaded / set up when in development mode (DEBUG=True in Django). This means that those building ON Wagtail with client-side APIs can see warnings in the console when they add custom features such as Chooser or Draftail implementations.

#### Potential approach

* Create a new includes/ file for 'warnings' that will return a function that instantiates a class (returning that class)
* The file also exports some functions for specific warnings to call (which can then be imported in other files)
* If we want to create a warning we do something like `import { removedInWagtail50Warning } from 'utils/warnings';` and then call it with `RemovedInWagtail50(`createDocumentChooser(${id}) should be replaced with new DocumentChooser(${id})`)`.
* When called, if NOT in DEBUG mode this warning will do nothing.
* When called, if in Django debug mode this will either a. fire console.warn with the message + some generic content about the release version. OR throw an error.
* If we throw an error - this may be too 'destructive' and instead we should probably stick to console.warn OR throw the error inside a promise so that the existing code does not break.
* When Django / Python warnings trigger - they do not break the existing code but merely log so the developer can be made aware of it and I think that approach makes sense.
* We then add an `entrypoints/development.ts` file that imports this class and instantiates it somehow or activates it so the logging works.
* Note: We will need to add a contid

```javascript
// warnings.ts


class Warnings {
  constructor() {
    this.isEnabled = false;
  }

  enable() {
    // alternatively provide an event listener API but that may be a bit too indirect.
    this.isEnabled = true;
  }

  warn(version, message, data) {
    if (!this.isEnabled) return;
    console.warn(version, message, data);
  }

  removedInWagtail50Warning(message, data) {
    this.warn(5.0, message, data)
  }
}


export warnings = new Warnings();

export removedInWagtail50Warning = warnings.removedInWagtail50Warning;

```

```javascript
// entrypoints/development.js

import { warnings } from 'utils/warnings';

warnings.enable();

```

### Describe alternatives you've considered

* No change, developers may not really open the console in the browser when using the JavaScript APIs and hence this provides little value.
* Alternatively, this may create too much console 'noise' that is unhelpful.

### Additional context

* _Originally discussed in https://github.com/wagtail/wagtail/pull/8711#discussion_r909115885_
* First use case for this would be https://github.com/wagtail/wagtail/blob/main/client/src/entrypoints/documents/document-chooser.js
* Python warnings module docs https://docs.python.org/3/library/warnings.html
* MDN docs for `console.warn` https://developer.mozilla.org/en-US/docs/Web/API/console/warn
* MDN docs for error https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error
* This makes way for further helpful warnings/messages in the client for those that are building on Wagtail's front-end code

**Comment by thibaudcolas** [comment]
I’m not sure this provides enough value to warrant the implementation effort. Perhaps if this called an API endpoint so deprecation warnings show up in the Django server logs, rather than in the browser console?

**Comment by lb-** [comment]
Fair enough - will close this for now - if there is a need for this in the future we can reopen or revisit.

**Comment by lb-** [comment]
Patch file for future if needed.

[wagtail-950b39a-add ability to trigger client-side deprecation warnings.patch.txt](https://github.com/wagtail/wagtail/files/9495485/wagtail-950b39a-add.ability.to.trigger.client-side.deprecation.warnings.patch.txt)
