### ISSUE TITLE
When on site history report page and opening page menu (AND the window is maximised), click on home opens CSV download?

### ISSUE THREAD

**Issue by robvdl** [wagtail/wagtail#8980]
### Issue Summary

While I am on the site history report page, and I open the "Pages" slideout menu and click on Home, it goes to download a CSV of the site history.

When I am on another page, it doesn't do that, very strange.

### Steps to Reproduce

1. Go to reports, site-history
2. Click Pages menu
3. Click Home

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: 3.8
-   Django version: 3.2
-   Wagtail version: 3.0.1
-   Browser version: Chrome 104.0.5112.79

**Comment by robvdl** [comment]
When inspecting the HTML element under the "Home" link, it seems some JS has replaced it with a Download CSV link.

I think the Download CSV button JS code is somehow targetting the menu item.

**Comment by lb-** [comment]
@robvdl please can you add a screenshot of what you mean. I have tried to follow the steps to reproduce and cannot trigger this same issue.

Note: I am testing on the latest `main` branch (future release 4.0).

I tried each of the buttons with boxes around them (below screenshot) and none of them downloaded the CSV.

Also - can you rule out that your project has no custom JS running in it that could be doing something odd.

<img width="988" alt="Screen Shot 2022-08-12 at 5 45 17 pm" src="https://user-images.githubusercontent.com/1396140/184308802-eba9d0f5-e3ff-454e-a0ae-17fe455fe03a.png">

**Comment by robvdl** [comment]
I made some very interesting discoveries. I don't even know where to start but it seems to be tied to maximising the window. it just doesn't make sense.

See first I took a screenshot, notice the hover link is fine it says /admin/pages/3/ when hovering over:

![image](https://user-images.githubusercontent.com/1018674/184325555-34633bd0-29b8-4bf5-a025-18850bb51202.png)

Then I played around with maximising and unmaximising the window, reloading the page just to be sure, and now the hover link changes to /admin/reports/site-history/?export=csv

See:

![image](https://user-images.githubusercontent.com/1018674/184325764-f1335185-e809-4609-ae12-48e4f689e2d5.png)

I also did some testing if there are multiple menu items, I go into a submenu under the pages menu, and in that case only the top menu item is affected, the remaining menu items are fine.

![image](https://user-images.githubusercontent.com/1018674/184325961-69c511b4-3de2-4690-89fe-9e6ec29f6b0a.png)

**Comment by robvdl** [comment]
The thing that makes this even more interesting is maximising/unmaximising the browser window changes the link change backwards and forward between the correct and incorrect lnk, you don't even need to refresh the page.

**Comment by gasman** [comment]
I'm also unable to replicate this, testing on a fresh Wagtail 3.0 installation on Chrome and Firefox at various window sizes.

It sounds like this could be a CSS issue - the link on the 'Download' button somehow being set to full screen width and being given a z-index that overlaps the menu. Do you have any CSS customisations on your project?

**Comment by robvdl** [comment]
I don't but a CSS issue makes total sense, I'll do some debugging with the browser tools.

I have Web Developer toolbar installed, it can highlight boxes around CSS elements.

**Comment by robvdl** [comment]
This is with "outline block level elements". If you hover over the red box area and to the right of it, you get the wrong link:

![image](https://user-images.githubusercontent.com/1018674/184334423-daa01e33-ef5a-4d6e-94f0-8a555a477268.png)

If you hover your mouse just above it, you get the right link:

![image](https://user-images.githubusercontent.com/1018674/184334517-4a833587-cd7c-41a2-891c-5b92ce1556dc.png)

**Comment by robvdl** [comment]
I'll try with topography turned on, might give some more insight of overlapping CSS elements.

**Comment by robvdl** [comment]
Unfortunately topographic information didn't give any additional insight, I'll keep debugging:

![image](https://user-images.githubusercontent.com/1018674/184335059-13de1d2e-94d9-45aa-9c3a-ec654b94d3a4.png)

**Comment by robvdl** [comment]
fyi Firefox is doing it too

**Comment by gasman** [comment]
Closing for now as unable to replicate, but we'll be happy to take another look if you can reproduce this on a fresh Wagtail installation.
