### ISSUE TITLE
Images and Documents need "last modified by".

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#899]
In lieu of chronological logging (#496) it would be nice to know who last edited an image/document and when. 

Any system where multiple users can edit something requires a way of indicating to users that things may have changed since they last paid attention.

**Comment by thibaudcolas** [comment]
I’m going to close this in favour of our corresponding roadmap item: [Media versioning #58](https://github.com/wagtail/roadmap/issues/58). I like the simplicity of "last modified by" but we’ve gone much further with Snippets and arbitrary models recently. And at this stage, it feels to me like further ideation in this space would be better done in GitHub Discussions or an RFC, not a very specific feature request.
