### ISSUE TITLE
4.0 - Updated Screenshot (Readme)

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8997]
* Readme page needs an updated screenshot for 4.0

**Comment by Akash-Kumar-Sen** [comment]
By 4.0 you mean the Wagtail 4.0 version? Is it released yet? Then I can do the job.

**Comment by lb-** [comment]
Thanks but I might see if @KalobTaulien is ok to do it as he did the last update and I don't know how (kind of looks like safari but no url bar).

**Comment by lb-** [comment]
Here are the instructions to do this

* Updated the screenshot in the README to reflect Wagtail 3 changes. Also shows off the commenting feature.
* Used browserframe.com for the frame; Used TinyPNG to compress the image.
* As per the last update https://github.com/wagtail/wagtail/pull/8331

**Comment by lb-** [comment]
Here are the instructions to do this

* Updated the screenshot in the README to reflect Wagtail 3 changes. Also shows off the commenting feature.
* Used browserframe.com for the frame; Used TinyPNG to compress the image.
* As per the last update https://github.com/wagtail/wagtail/pull/8331

**Comment by lb-** [comment]
PR up https://github.com/wagtail/wagtail/pull/9051
