### ISSUE TITLE
Add test for manage.py collectstatic to CI

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#9002]
### Is your proposal related to a problem?

See https://github.com/wagtail/wagtail/issues/8988#issuecomment-1214980292 - the wagtailadmin CSS referenced a missing SVG file, which caused the `./manage.py collectstatic` command to fail. Since we don't routinely run collectstatic during local development, and our CI environments don't run it either, this went un-noticed until the release candidate.

### Describe the solution you'd like

Add a test somewhere in our CI setup that verifies that `./manage.py collectstatic` is able to complete with no errors (and ensure that it does indeed fail in a case like this where a file is missing.

Currently our GitHub Actions tests avoid dealing with node - they don't install it, don't build static assets, and run the tests with the default StaticFilesStorage rather than ManifestStaticFilesStorage, which means it wouldn't pick up this failure case. As such, it probably makes more sense to add this to our CircleCI setup, but I think that'll need a new base image with both Node and Python available, and that's beyond my Docker knowledge...

Tentatively marking this as a good first issue since it doesn't require in-depth Wagtail knowledge, although it'll need some familiarity with Node, Docker and/or CircleCI (or willingness to get up to speed with them).

**Comment by thibaudcolas** [comment]
We already have a CircleCI job that depends on both Python & Node, will see if I can make a PR to either add this or share pseudo-code here.

**Comment by logan-bobo** [comment]
@thibaudcolas happy to pick this up as I am familiar with impelling CI changes and docker :raised_hands:

**Comment by gasman** [comment]
@logan-bobo Thanks - go for it!

**Comment by logan-bobo** [comment]
Is there any chance I could grab an invitation to the slack channel as my domain is not on the allow list. I have some ideas but would like somewhere to discuss. My email is logan.bobofed@gmail.com. Will leave them here also. 

Would we want this test to be ran as part of the `frontend`, `backend` or `nightlybuild` job. I can see that the `nightly-build` job is running on an agent that has both python and node installed and you want to make sure that this command is running as expected. So `nightly-build` looks like a good place for the check to run. 

Taking a look at the Django docs and your previous MR, we should be able to run `./manage.py collectstatic --noinput` to gather the static content and it should be placed in the `STATIC_ROOT` defined in the project based on where Django thinks the static content lives. I will do some local testing on running this command when all of the content exists vs when a file is missing and then feed this back in to the CI job.

**Comment by gasman** [comment]
> Is there any chance I could grab an invitation to the slack channel as my domain is not on the allow list. I have some ideas but would like somewhere to discuss.

Please give https://wagtail.io/slack another go - have just regenerated the invitation link. (It only works for 100 people at a time, and it looks like we hit that limit...)

> Would we want this test to be ran as part of the `frontend`, `backend` or `nightlybuild` job. I can see that the `nightly-build` job is running on an agent that has both python and node installed and you want to make sure that this command is running as expected. So `nightly-build` looks like a good place for the check to run.

I'd suggest the `ui_tests` one - that's the one I was trying to use in #9001, and (I think) the one @thibaudcolas was referring to above as having both the Python and Node environments. I don't think `nightly-build` will fit here, as that one is scheduled to run once per day, and we'd want this test to run on every pull request.

I think the step I missed in #9001 was that `collectstatic` only fails when `STATICFILES_STORAGE` is set to `"django.contrib.staticfiles.storage.ManifestStaticFilesStorage"`, which _isn't_ the case for [our test settings](https://github.com/wagtail/wagtail/blob/main/wagtail/test/settings.py) - and we don't want to change that for all test runs (since the Github Actions tests need to be able to run without the static files being built), so it probably calls for us to pass in an environment variable to configure that from outside, like we do for the database settings.

**Comment by gasman** [comment]
Fixed in #9077
