### ISSUE TITLE
ChooserBlocks always have hidden edit-links (4.0rc1)

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9008]
### Issue Summary

The edit-button is in the HTML, but it has the `w-hidden` css class.
I assume that this is because the `StreamField` widgets are rendered on the JS-side and in that case the `edit_url` is always empty:
https://github.com/wagtail/wagtail/blob/666cc5e8e5889bc95b527b8ef2af3841ffe0d2b7/wagtail/admin/templates/wagtailadmin/widgets/chooser.html#L28

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py and add a `StreamField` with an `ImageChooserBlock`, `PageChooserBlock` and/or `DocumentChooserBlock`
3. makemigrations + migrate
4. Edit a page and find the hidden "edit"-link when an instance has been chosen

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10
-   Django version: 4.1
-   Wagtail version: 4.0rc1
-   Browser version: Firefox 103

**Comment by gasman** [comment]
Confirmed... looks like this was introduced in 21b5ad5ce9e6698e9912abeeab23ccb2db54ad70.

**Comment by gasman** [comment]
OK, that fix was more straightforward than I expected :-) #9011
