### ISSUE TITLE
Document chooser upload form no longer populates title from filename

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#9010]
### Issue Summary

Within the upload form on the document chooser modal, when you select a document file, the title field is no longer populated from the filename.

### Steps to Reproduce

1. Set up a project with a homepage model containing a StreamField containing a DocumentChooserBlock, as per https://github.com/wagtail/wagtail/issues/8989#issuecomment-1213331089
2. Add a block and open the document chooser
3. Switch to the Upload tab
4. Select a file to upload

Expected: the Title field should be updated to a cleaned version of the filename
Actual: it remains blank

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.8.0.
-   Django version: 4.0.7
-   Wagtail version: 4.0rc1
-   Browser version: Chrome 104.0.5112.79

**Comment by gasman** [comment]
Seems to have been introduced in 252f9dcc1fee3faec11a1aeefcfa5bd24cb7c4cf - I'm guessing the logic in ChooserViewSet for constructing the block class is failing to hook up the AdminDocumentChooser widget that implements this custom behaviour, and is just using the BaseChooser implementation.

**Comment by mehrdadmoradii** [comment]
> Seems to have been introduced in [252f9dc](https://github.com/wagtail/wagtail/commit/252f9dcc1fee3faec11a1aeefcfa5bd24cb7c4cf) - I'm guessing the logic in ChooserViewSet for constructing the block class is failing to hook up the AdminDocumentChooser widget that implements this custom behaviour, and is just using the BaseChooser implementation.

As I am following the same steps, I can reproduce the bug - Wagtail version 4.0rc1. However, as I am using the development version of Wagtail the widget does not even display. Also, the browser console logs some client-side errors. 

<img width="1440" alt="Screen Shot 2022-08-16 at 12 11 10 PM" src="https://user-images.githubusercontent.com/63321262/184928145-d58dd05f-e39f-4415-b751-1881d5ad6f1d.png">
