### ISSUE TITLE
Modal's close button hard to see (4.0rc1)

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9014]
### Issue Summary

Shouldn't it be white, similar to the title?
![wagtail_modal_close_button](https://user-images.githubusercontent.com/468164/185060003-2c08a5a1-5612-4049-87b3-afdc4e1a1b44.gif)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Add a `StreamField` with an `ImageChooserBlock` for example
3. makemigrations & migrate

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10
-   Django version: 4.1
-   Wagtail version: 4.0rc1 (nightly https://releases.wagtail.org/nightly/dist/wagtail-4.0.dev20220816-py3-none-any.whl)
-   Browser version: Firefox 103

**Comment by lb-** [comment]
@PaarthAgarwal please also look at this - it's possible the explicit addition of the shared header icon has meant that this icon lost some of it's styles.  

I know this is assigned to @stevedya but let's try to help out and get this resolved. 

We will need to focus on these header fixes above the button styling. Hopefully a quick fix.

**Comment by PaarthAgarwal** [comment]
I can see we want a white icon over there, but what hover behaviour do we want?

**Comment by lb-** [comment]
@PaarthAgarwal here is what 3.0 looks like.

<img width="1874" alt="Screen Shot 2022-08-22 at 6 25 43 am" src="https://user-images.githubusercontent.com/1396140/185809542-c6cded86-f4c1-41ad-80d7-c74acd039593.png">

<img width="1880" alt="Screen Shot 2022-08-22 at 6 25 25 am" src="https://user-images.githubusercontent.com/1396140/185809551-aa072315-dd61-4e66-b304-fec256c09006.png">

If you ever need to see what the latest version (non-main) looks like you can load up bakerydemo in gitpod.

https://github.com/wagtail/bakerydemo#setup-with-gitpod
https://gitpod.io/#https://github.com/wagtail/bakerydemo/

**Comment by PaarthAgarwal** [comment]
> @PaarthAgarwal here is what 3.0 looks like.
> 
> <img alt="Screen Shot 2022-08-22 at 6 25 43 am" width="1874" src="https://user-images.githubusercontent.com/1396140/185809542-c6cded86-f4c1-41ad-80d7-c74acd039593.png">
> 

Awesome. That's what I assumed.

> <img alt="Screen Shot 2022-08-22 at 6 25 25 am" width="1880" src="https://user-images.githubusercontent.com/1396140/185809551-aa072315-dd61-4e66-b304-fec256c09006.png">
> 
> If you ever need to see what the latest version (non-main) looks like you can load up bakerydemo in gitpod.
> 
> https://github.com/wagtail/bakerydemo#setup-with-gitpod https://gitpod.io/#https://github.com/wagtail/bakerydemo/

Sure. Thanks LB!
