### ISSUE TITLE
Draftail BlockToolbar: Items not clickable when opened with "/" (4.0rc1)

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9017]
### Issue Summary

If you open the block toolbar by clicking the "+"-icon, you can select an item with the mouse, but if you open it with "/", clicking an item only closes the toolbar, but does not insert anything.

_Below: First I'm adding a block with the "+"-icon, then after deleting it, I'm retrying with "/". Directly starting with "/" doesn't change anything._
![wagtail_draftail_toolbar_issue](https://user-images.githubusercontent.com/468164/185087525-1d2288b1-014b-4b10-b5f1-57bf03ba5db5.gif)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Insert a RichTextField/RichTextBlock

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10
-   Django version: 4.1
-   Wagtail version: 4.0rc1 (nightly https://releases.wagtail.org/nightly/dist/wagtail-4.0.dev20220816-py3-none-any.whl)
-   Browser version: Firefox 103

**Comment by gasman** [comment]
Seeing the same issue on Chrome 104.0.5112.79... thanks for reporting!

**Comment by gasman** [comment]
Looks like it's been this way since this feature was first introduced in b070ce1cd3b8cc29b543db454e28b314b3fe298a - @thibaudcolas please can you investigate?

**Comment by thibaudcolas** [comment]
Thank you both, looks like I missed this scenario in my testing of the functionality. I’ve made #9022 to fix this (directly in Draftail). This case needs special handling, as we need the focus to remain within the editor during this interaction (similarly to how clicking the toolbar’s buttons works). The "+" block toolbar already works with focus outside the editor, hence why it worked there.
