### ISSUE TITLE
Chooser upload form validation failures return raw JSON

### ISSUE THREAD

**Issue by chosak** [wagtail/wagtail#9019]
### Issue Summary

Found while testing #9018, although this seems to apply to both documents and images.

### Steps to Reproduce

1. Set up a new project with a homepage model containing a StreamField containing a DocumentChooserBlock and ImageChooserBlock:

<details>
<summary>for example this code</summary>

```py
# home/models.py
from django.db import models

from wagtail.admin.panels import FieldPanel
from wagtail.blocks import CharBlock, StreamBlock, StructBlock
from wagtail.documents.blocks import DocumentChooserBlock
from wagtail.images.blocks import ImageChooserBlock
from wagtail.fields import StreamField
from wagtail.models import Page


class ResourceBlock(StructBlock):
    title = CharBlock()
    document = DocumentChooserBlock()
    image = ImageChooserBlock()


class DemoStreamBlock(StreamBlock):
    resource = ResourceBlock()


class HomePage(Page):
    content = StreamField(DemoStreamBlock, use_json_field=True, blank=True)

    content_panels = Page.content_panels + [
        FieldPanel("content", classname="full"),
    ]
```
</details>

2. [Edit the home page](http://localhost:8000/admin/pages/3/edit/), add a Resource block, then click "Choose an image". The image chooser opens.
3. Switch to the upload tab and upload an image. The (required) title field will be autopopulated.
4. Delete the title field so it is empty, and click Upload. You'll be looking at a raw JSON response in your browser:

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/654645/185190724-7dd00cb6-1eba-4d14-9195-bcbd20de99b6.png">

The same thing happens with documents (the bug in #9010 and fix in #9018 seem irrelevant).

### Technical details

-   Python version: 3.10.4
-   Django version: 4.0.7
-   Wagtail version: repeatable on current main (cc4675aa5ed41ffde68960fa697b3e3e682d71fc) and 4.0rc1. Bug doesn't exist on 3.0.1.

**Comment by gasman** [comment]
Looks like this was introduced in eac5e0bc2cda0d78d1ffb13da32b8cc8410f2b0b.

**Comment by chosak** [comment]
+1, the specific error happens because of an uncaught exception from these lines:

https://github.com/wagtail/wagtail/blob/eac5e0bc2cda0d78d1ffb13da32b8cc8410f2b0b/client/src/includes/chooserModal.js#L16-L17

because the first line querySelector call returns null.
