### ISSUE TITLE
Update rich text Link/Document Tooltip styles to match the styles of the inline toolbar

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9023]
Follow-up to #8964. With the introduction of the rich text editor’s floating / inline toolbar, we now need to update our Link/Document tooltips to similarly match the designs.

Screenshot of the tooltip as-is:

![Image](https://user-images.githubusercontent.com/877585/185301368-ac0a72c3-42f3-43b2-8e6b-89e0b617600a.png)

I believe our [design system](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=225%3A3) has the intended styles for this defined either in one of the clickable prototypes, or in legacy screens. If not, the styles need to at least be updated so this tooltip:

- [ ] Has the same height and padding as the inline toolbar: uses `button-small` class on all buttons
- [ ] Has button styles that work with Wagtail’s new color palette: keep as-is until we check with Ben
- [ ] No longer has a tooltip arrow: remove
- [ ] Has the same spacing between the tooltip and the link, as we’d have between the inline toolbar and text: adjust once the arrow is gone

**Comment by Theresa-o** [comment]
@thibaudcolas I would like to take up this issue and work on it however I'm unable to access the design system (https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=225%3A3) to see the referenced design I can use to work on this.

May I have access or a screenshot of the relevant information needed to resolve this issue?

> I believe our [design system](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=225%3A3)

Or should I work with this information:

If not, the styles need to at least be updated so this tooltip:

Has the same height and padding as the inline toolbar
Has button styles that work with Wagtail’s new color palette
No longer has a tooltip arrow
Has the same spacing between the tooltip and the link, as we’d have between the inline toolbar and text
