### ISSUE TITLE
Comment button positioning / styling issues

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9025]
Follow-up to #8921. The comment annotations are leaving a lot to be desired across the UI.

![Image](https://user-images.githubusercontent.com/877585/185306056-ad230952-3855-4284-9bae-9b38a48c70c2.gif)

Problematic issues:

- [x] In field rows, the comment button is overlapping with fields. It needs tighter spacing to fit in column gaps.
- [x] In rich text fields, the comment text annotation color isn’t the one intended in the designs (current has way too low contrast)

Spacing / cosmetic issues:

- [x] The fields should no longer become shorter in commenting mode. Instead, comment buttons can be positioned off to the side of the form.
- [x] For all single-line 42px fields, the comment button should be horizontally centred
- [x] For larger fields, the comment button can be at the same top offset as for single-line fields
- [x] In field rows, the comment button is too close to fields.
- [x] Bold text in rich text comment highlights moves the field’s content around.

Nice to have:

- [x] For chooser widgets, have the comment button center-aligned with the other chooser buttons 
- [x] For the title field, have the comment button center-aligned with the field

**Comment by gasman** [comment]
bumping to 4.1 to cover the points that weren't handled in the final 4.0-merged version of #9072

**Comment by thibaudcolas** [comment]
I have updated the issue description based on changes done in Wagtail 4.0 – the two problematic issues have been fixed. We still have cosmetic / alignment issues to go through, which are now in #9111.
