### ISSUE TITLE
Update block chooser flyout styles based on latest designs

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9026]
Follow-up to #8964. Our rich text block toolbar is missing some of its styles:

![Image](https://user-images.githubusercontent.com/877585/185303520-42a7c1a9-1dbd-4f78-9237-f6de1c4f4fc2.gif)

- [ ] Alignment between the icons and labels is off
- [ ] The "No results" state has incorrect padding
- [ ] The first and last items do not have the correct top and bottom padding (particularly the `/-command` variant without the search field
- [ ] The hover styles aren’t as per the designs
- [ ] Hovered items need a `cursor: pointer`
- [ ] The height of the element (set in vh) is higher than intended
- [ ] Replace whole-page backdrop with shadow

And for the variant within StreamField:

![Image](https://user-images.githubusercontent.com/877585/185303874-b4a2402b-4955-4e84-9149-b4d61e1f4207.png)

- Styles for each option group label are a bit off
- We’re missing the red error styles when reaching the maximum block count ("0 / 2")

**Comment by fyunusa** [comment]
Hi, @thibaudcolas can i take up on this to fix the styling issues

**Comment by fyunusa** [comment]
is it something i'll be able to work on ?

**Comment by Scotchester** [comment]
Hey @fyunusa, no need to ask, just state that you intend to work on it 🙂

**Comment by fyunusa** [comment]
Oh yeah, I'm on it already thanks

**Comment by thibaudcolas** [comment]
Closing this in favour of #9754 which has the latest designs for this part of the UI.
