### ISSUE TITLE
New styles for footer actions

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9030]
Here are the styles of this specific component:

![Image](https://user-images.githubusercontent.com/877585/185321319-a589ada0-95b6-4c9c-8fea-f1359f169a52.png)

And more generally of all dropdowns like this: https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=1241%3A18660

Ideally we’d only get to this after @wagtail/gsoc-ux-unification has implemented their changes to the JS side of this. 

Note for footer actions – there is much more than just the dropdown, we also need to make sure the new styles work with the bulk chooser’s components, and with our dirty form check messages.

As part of this, we could also add this component to the user creation screen to help with #5906. Ideally #7366, #6591, #7650 will have also been fixed.

Sub-tasks:

- [x] Re-implement dropdown buttons with Tippy
- [x] Re-implement bulk actions + button styles according to new designs
- [x] Include styleguide improvements for warning buttons https://github.com/wagtail/wagtail/pull/10449#discussion_r1221309056

**Comment by thibaudcolas** [comment]
This should ideally involve fixing #6591.

**Comment by ForJessicaSake** [comment]
Hi @thibaudcolas I was wondering if this is still open for anyone to work on?

**Comment by thibaudcolas** [comment]
Hi @ForJessicaSake, yep, I don’t think anyone else has worked on this.

**Comment by ForJessicaSake** [comment]
Okay great,  I’ll work on it can you please assign it to me 😊 thank you!

**Comment by lb-** [comment]
@ForJessicaSake  we do not assign issues (outside of core team) so feel free to just start on this.

**Comment by ForJessicaSake** [comment]
Okay noted, I’ll do just that

**Comment by thibaudcolas** [comment]
Hi @ForJessicaSake, can you let us know where you got to with this? Please let us know if you have any questions.

**Comment by Seremba** [comment]
Hi @ForJessicaSake are you still working on this please?

**Comment by Seremba** [comment]
Hi @thibaudcolas, is anyone working on this issue?

**Comment by lb-** [comment]
@Seremba feel free to give this a go as we have not heard back from @ForJessicaSake for some time.

**Comment by Seremba** [comment]
Hi @thibaudcolas @lb- would you mind helping me locate the file for these changes?

**Comment by lb-** [comment]
@Seremba have a look at this PR - it touches the same area of the UI. 

https://github.com/wagtail/wagtail/pull/9643

However, it's good to learn how to find these things yourself. The best way is to look at the CSS classes in the DOM and search through the code in your editor.

**Comment by thibaudcolas** [comment]
I’ve done quite a bit of the work on this in #11456 – the footer actions code is much simpler now, so should be easier for us to complete this ticket. There were a few snags:

- The proposed widths for the sticky actions would mean a lot more wrapping of text to two lines for languages longer than english (so I stopped at 310px rather than the 250px in the designs)
- The designs in Ben’s original screenshot here have too low contrast between the footer actions background and the page background in my opinion. Not sure this is an actual issue but I found it hard on the eye to not know exactly what part of the page was sticky and what was within. Something I’d like to discuss at least.

And more generally:

- Those styles need to work for both footer actions on "forms", and bulk actions. Currently we only have designs for very simple "form" footer actions, while the bulk actions are more complex visually
- We need to make sure the footer actions also support having text within, the "unsaved page data" warning and also meta text for bulk actions.

---

Another snag was that footer actions markup currently is copy-pasted all over the place, with lots of inconsistencies. So as part of completing this I think we need to refactor the code to have an implementation that’s easier to reuse. Particularly in the context of #9869.

**Comment by thibaudcolas** [comment]
Assigning back to @benenright for a review of how we can tweak the designs to complete this, based on my notes above. Here are specific problem scenarios that might warrant design changes.

## Footer actions with warning message

![footer actions with warning text](https://github.com/user-attachments/assets/bc5047f4-3c0f-4a7c-8204-1c05d22ce08f)

## Bulk actions

![bulk actions](https://github.com/user-attachments/assets/617842e4-7555-4a08-90df-694bd26c9db3)

## Bulk actions with "Select all" link

![bulk actions select all](https://github.com/user-attachments/assets/24193d16-b622-4ba6-95e5-5fb8a58f5945)

**Comment by benenright** [comment]
I think that we should keep the background indigo, as I don't think there is much value in trying to make a light background work behind these actions, and the potential usability issues outway the original intention...

The original intention was to reduce the visual weight of the form footer actions - being something that sticks on the browser bottom edge, it felt like this was worth trying. But in the context of the bulk actions, that only appear once triggered by selecting a checkbox, the dark background helps users to notice it, and if we move to a lower contrast background, it risks them not being noticed (some usability testing we did a while back showed that some users expected these bulk actions to appear at the top of the listing (as per Gmail for eg), but since the indigo bg was high contrast with the page bg, people did notice it at bottom).

I do think it would be worth revisiting how we ensure good contrast for this type of panel specifically in dark mode (as the low contrast means we likely have that usability issue where people don't notice it appear):

![image](https://github.com/user-attachments/assets/dd765207-2ec9-43d8-848a-6ed80329ce7d)

**Comment by thibaudcolas** [comment]
@benenright I forgot one other variation on footer actions, which is used when viewing a past version of a page:

![footer actions past revision](https://github.com/user-attachments/assets/efd9f4ab-d9d0-4b13-9542-8734d73bc1f9)

This is testable on this [past revision demo page](https://static-wagtail-v6-2.netlify.app/admin/pages/82/revisions/60/revert/). Could you give us design guidance for that as well?

---

re bulk actions, anecdotally we received related feedback from low-vision users (though it’s low on details so I’m following up):

> Given the page layout it wasn’t immediately apparent that it was possible to affect the pages from the list view

**Comment by benenright** [comment]
Hi

In this view, I don't know the history as to why the button is orange, but to me it feels like the top banner is doing enough to alert people this is a previous version of this page. I feel like for that reason we _could_ just revert the buttons to be teal here...

However, maybe it's likely that people who have become used to seeing the buttons orange will get confused if they go back to teal). So for that reason it's prob safer just to address the fact that the white text on orange is not high enough contrast... and we should change it to use the same text colour as in the alert banner. 

![Image](https://github.com/user-attachments/assets/abb57da0-c0d1-463c-983c-1a8c3d603ae4)

----

While we're here. could we fix this UI glitch where the button loses it's top left and top right border radius after you open then close the options:

Before:
![Image](https://github.com/user-attachments/assets/8bef9039-0fa3-4f3e-a443-130f04096f0c)


After:
![Image](https://github.com/user-attachments/assets/83549eb9-4781-4d39-b71c-b0010147eaa4)

**Comment by thibaudcolas** [comment]
👍 sounds good to me that we’d have the button consistently teal. As you say the banner is already doing a good job warning users, and the button text is different as well. Also agree re keeping the indigo background in the light theme.

Will leave it with @laymonage to figure out where to place the "Delete" buttons we occasionally have in forms, that could either go in a "footer actions" dropdown, or in a "slim header" falafel actions menu 👀
