### ISSUE TITLE
Form styles design review feedback

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9033]
Relatively minor fixes, which it would be nice to do for Wagtail 4.0 if their implementation is simple enough.

- [ ] Center-align fields within group permission tables
- [ ] Checkbox & radio option label should be grey
- [ ] Field row horizontal spacing
- [ ] Spacing between error icon and message

**Comment by stevedya** [comment]
Hey @thibaudcolas could I get a little more context on this bullet 
 - [ ] Field row horizontal spacing
