### ISSUE TITLE
Generic choosers: hide/remove locale filter if i18n is not enabled (4.0rc1)

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9038]
First: the new generic choosers (#8480) seem to work very good so far in our tests, we can finally replace the various (often outdated) model chooser implementations with this flexible core feature, amazing work! 👍

### Issue Summary

We often use model choosers for specific page models, so they can be searched/selected easily, without using the page tree (used by the PageChooser).
Migrating our code to a `ChooserViewSet` for this page model for projects without wagtail-i18n (no translations) now shows a language dropdown in the chooser modal with only the single (untranslated) default language:
 
![wagtail_generic_chooser_single_locale](https://user-images.githubusercontent.com/468164/185344631-5a49f3d8-e82c-41ca-9abc-bfc7d063fdce.gif)

This could also happen for other (thirdparty) models, which use the `TranslatableMixin`, when used in a project with only a single language (no wagtail i18n enabled).

The chooser works, so it is not really a blocker, but I hope a fix will make it into the final 4.0 :pray: 

**Possible solution:**
Maybe check for `WAGTAIL_I18N_ENABLED` when the `LocaleFilterMixin` gets added to the filter form here:
https://github.com/wagtail/wagtail/blob/1fcf4cacbb3c5f34daa10e4e375cb5d75a2c8aae/wagtail/admin/views/generic/chooser.py#L112-L113

There is other code that already uses this option, e.g.:
https://github.com/wagtail/wagtail/blob/1fcf4cacbb3c5f34daa10e4e375cb5d75a2c8aae/wagtail/admin/views/chooser.py#L206

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Create a `home/viewsets.py`:
```python
from wagtail.admin.viewsets.chooser import ChooserViewSet

class HomePageChooserViewSet(ChooserViewSet):
    model = "home.HomePage"

home_page_chooser_viewset = HomePageChooserViewSet("home_page_chooser")
```
3. Create `home/blocks.py`:
```python
from .viewsets import home_page_chooser_viewset

HomePageChooserBlock = home_page_chooser_viewset.get_block_class(
    name="HomePageChooserBlock", module_path="home.blocks"
)
```
4. Create `home/wagtail_hooks.py`:
```python
from wagtail import hooks
from .viewsets import home_page_chooser_viewset

@hooks.register("register_admin_viewset")
def register_viewset():
    return home_page_chooser_viewset
```
5. Edit `home/models.py` as follows:
```python
from wagtail.admin.panels import FieldPanel
from wagtail.fields import StreamField
from wagtail.models import Page
from .blocks import HomePageChooserBlock

class HomePage(Page):
    content_panels = Page.content_panels + [FieldPanel("content")]
    content = StreamField(
        [
            ("home", HomePageChooserBlock()),
        ],
        blank=True,
        use_json_field=True,
    )
```
6. `./manage.py makemigrations && ./manage.py migrate && ./manage.py createsuperuser && ./manage.py runserver`
7. In the CMS, edit the home page and add a home block using the chooser.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10
-   Django version: 4.1
-   Wagtail version: 4.0rc1 (nightly https://releases.wagtail.org/nightly/dist/wagtail-4.0.dev20220817-py3-none-any.whl)
-   Browser version: Firefox 103

**Comment by gasman** [comment]
Thanks for the detailed report and steps to reproduce, @th3hamm0r - really helpful!

PR created: #9056

**Comment by lb-** [comment]
Just wanted to say again - steps to reproduce here are incredibly helpful. Was able to validate the fix easily.
Feel free to raise bugs any time @th3hamm0r  - haha but hopefully you do not find too many more in 4.0 RC :D

**Comment by th3hamm0r** [comment]
You're welcome 😁 No, it looks very promising atm thanks to the fast reactions and fixes!
