### ISSUE TITLE
Wrong Italian translation of ImageChooserBlock in Wagtail 4.0rc2

### ISSUE THREAD

**Issue by lelit** [wagtail/wagtail#9045]
Trying out recently released rc, I found a glitch in the Italian translation that is particularly confusing.

This is a screenshot of how an ImageChooserBlock appears in `v4.0rc2`:
![w4](https://user-images.githubusercontent.com/412797/185446603-352c8fe0-f4cc-47fa-bbd1-f4da03ef47b5.png)

where you can see that both buttons carry the same translation.

For reference, this is how it appears in `v3.0.1`:
![w3](https://user-images.githubusercontent.com/412797/185446814-3891d683-ae71-4368-89d2-9ddc76893d83.png)

**Comment by gasman** [comment]
Thanks for the report - I've now updated the translation strings on https://explore.transifex.com/torchbox/wagtail/ so that "Change" is "Cambia".

**Comment by lelit** [comment]
Thanks!

**Comment by lb-** [comment]
Added a bit of a summary of this underlying issue and learnings here https://github.com/wagtail/wagtail/discussions/8017#discussioncomment-3639114

Any feedback on that sub-comment would be appreciated.
