### ISSUE TITLE
Extend Custom user interface colors for sidebar and page explorer

### ISSUE THREAD

**Issue by lukasalexanderweber** [wagtail/wagtail#9052]
### Is your proposal related to a problem?

I'm able to easily adjust some colors of the admin page. I used the [documentation](https://docs.wagtail.org/en/stable/advanced_topics/customisation/admin_templates.html#custom-user-interface-colors) to customize the interface and setted the css to 

```
:root {
    --color-primary: red; 
    --color-primary-darker: red;
    --color-primary-dark: red;
    --color-primary-lighter: red;
    --color-primary-light: red;
    --color-input-focus: red;
    --color-input-focus-border: red;
}
```

However, I find it somehow inconsistent that the sidebar and page explorers are not able to be adjusted.

### Describe the solution you'd like

I would like to modify the purple colors just like the possible settings above.

### Describe alternatives you've considered

I can hack into the css:

```
.sidebar__inner{
    background-color: black;
}

.hover\:w-bg-primary-200:hover{
    background-color: black;
}

.w-bg-primary{
	background-color: black;
}
```

 however I think this could be bypassed by the really nice cusumization functionality described above.

### Additional context

With the two css combined I get the following result:

![result](https://user-images.githubusercontent.com/32765578/185580567-3038473b-df14-4c7a-89af-ae7a32d63c7f.PNG)

As you see, I would need to hack into lots of other css variables to replace all purple with e.g. black.

With a good editor it doesn't seem as much of an issue to replace identical color values with css variables. But maybe I'm wrong. If you point me to the right files I could then open a PR with adjustable colors for sidebar and page explorer (and branding_welcome)

**Comment by gasman** [comment]
Hi @lukasalexanderweber - which version are you running? Support for colour customisation has been greatly extended in the upcoming Wagtail 4.0 - https://github.com/wagtail/wagtail/pull/8824

**Comment by lukasalexanderweber** [comment]
ahh nice [I see](https://docs.wagtail.org/en/latest/advanced_topics/customisation/admin_templates.html#custom-user-interface-colours)

I'm running on 3.0.1., but now can't wait till 4.0 is released 🚀 

thanks for the info @gasman!
