### ISSUE TITLE
Clicking outside the modal not always closes it

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9053]
### Issue Summary

This is not really a big issue, but I just found out, that there are some areas outside the modal, which when clicked, won't close the modal. I've also tested other projects down to wagtail 2.15, which also have this issue.

Basically, the area of `div.modal-dialog` including its paddings block the click (blue and purple area in the examples below). For its content that makes sense of course, but unfortunately more space around its content actually blocks the click handler.
![wagtail_modal_close_area_issue](https://user-images.githubusercontent.com/468164/185580375-798380b0-03ba-4214-8dcc-bbe4ae41e36b.png)

On smaller screens a padding is also added to the left of the modal, which prevents it from being closed there:
![wagtail_modal_close_area_issue_2](https://user-images.githubusercontent.com/468164/185583741-fee413eb-6d48-46ca-bb8c-7d02dc666088.png)

On screens with enough horizontal space this is not an issue, because if you have enough images and documents, their modals probably span the whole vertical screen size. But the PageChooser for example, by default starts with the root page, so as in the examples above, the modal is not very high if you have only a single root.
Also the left padding may be present for all choosers on smaller screens.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. `./manage.py makemigrations && ./manage.py migrate && ./manage.py createsuperuser && ./manage.py runserver`
3. Go to /admin/redirects/add/ to create a redirect, use the page chooser to select an internal page (this is the place of the above screenshot)
4. Try to close the modal in one of the mentioned areas

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10
-   Wagtail version: 2.15.5 (django 3.2), 3.0.1 (django 3.2), 4.0rc2 (django 4.1)
-   Browser version: Firefox 103, Google Chrome 104

**Comment by lb-** [comment]
@PaarthAgarwal can you take a look at this and try to reproduce it. 

My guess is that this is caused by the header styling changes, maybe the addition of the `w-header` usage? 

I'll put this in the UX Unification project - please focus on this issue over the newer buttons work.

**Comment by PaarthAgarwal** [comment]
> @PaarthAgarwal can you take a look at this and try to reproduce it.
> 
> My guess is that this is caused by the header styling changes, maybe the addition of the `w-header` usage?
> 
> I'll put this in the UX Unification project - please focus on this issue over the newer buttons work.

I'm on it

**Comment by PaarthAgarwal** [comment]
One solution to this issue is to remove that extra padding from the left and compensate for it with margin on the left. Opening a PR for it

**Comment by lb-** [comment]
This is actually a problem with 3.0 - likely introduced with the new sidebar adoption.

But yes @PaarthAgarwal  - let's do that, thank you.

<img width="1881" alt="Screen Shot 2022-08-22 at 6 24 48 am" src="https://user-images.githubusercontent.com/1396140/185809613-62596829-9ede-4f80-9eaf-faf52f43c8c8.png">

We should fix this immediate issue but we have also got https://github.com/wagtail/wagtail/issues/8906 to try and fix the root cause of this - alignment with the various side-bar content should not rely on padding/inset/fixed positions on the content on the header to work.
