### ISSUE TITLE
With extra bottom menu buttons the bottom menu hides content

### ISSUE THREAD

**Issue by sighmon** [wagtail/wagtail#9073]
### Issue Summary

When adding extra buttons to the `Save/Publish/Lock/Delete/Preview` bottom menu, it hides other `add` buttons below it on smaller screens (e.g. MacBook 13").

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
1. Add a model
1. Override and add some buttons to `app/model/templates/wagtailadmin/pages/edit.html`
1. Open the Wagtail admin, reduce the browser width and note it covers up the bottom most `add` button on a scrolling page

```python
# app/model/templates/wagtailadmin/pages/edit.html
{% extends "wagtailadmin/pages/edit.html" %}

{% block extra_footer_actions %}
{% if page.content_type.name == "event page" or  page.content_type.name == "education event" %}
  <li class="additional">
    <p>
      <a
        class="button"
        href="#"
        >Send to Trello</a>
    </p>
  </li>
  <li class="additional">
    <p>
      <a
        class="button"
        href="#"
        >Sync with Tessitura</a>
    </p>
  </li>
{% endif %}
{% endblock %}
```

**Bug**: content is hidden (`+ ADD OCCURRENCES` button is hidden in our example below)

<img width="1400" alt="admin-v1" src="https://user-images.githubusercontent.com/314298/186310014-54150fab-3ae3-40ee-b568-9f004bb4049e.png">

**Workaround**: reduce left menu size as highlighted in above screenshot in pink

<img width="1400" alt="admin-v2" src="https://user-images.githubusercontent.com/314298/186310041-639764d8-9e48-40af-8c1b-75ef1da6ff2f.png">

**Ideal future**: bottom padding of the scroll view increases to match the bottom menu height

### Technical details

-   Browser version: Safari 15.6.1, Chrome 104.0.5112.101

**Comment by gasman** [comment]
Hi @sighmon - thanks for the report.
You haven't mentioned which Wagtail version you're running, but the screenshot seems to be from Wagtail 2.16 or earlier - there have been major changes to the page editor UI since then, and this may well have been fixed already.

Please can you test this against Wagtail 4.0rc2 (install with `pip install wagtail==4.0rc2`), and if the problem still occurs, open a new issue with full details?

**Comment by sighmon** [comment]
@gasman So sorry! You're right - we're on `2.16.2`.
