### ISSUE TITLE
Draftail (Rich text) commenting causes console error 'Unsupported style...'

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9081]
### Issue Summary

* When using the Draftail (rich text editor) and adding a comment on a selected text block a console error throws `Unsupported style property background-color. Did you mean backgroundColor?`

### Steps to Reproduce

1. Open bakerydemo to any page with existing Rich Text (home page or a blog page)
2. Add a comment to a single word
3. Add a new comment to multiple words that overlap the previous single word
4. Click the comment for the single word (focus on it)
5. Expected: Should have a slightly different background colour to help differentiate the two comments
6. Actual: Colours are not set correctly
7. Note: Open the browser console and see the error

#### Error

```
Warning: Unsupported style property background-color. Did you mean backgroundColor?
    in span (created by DraftEditorLeaf)
    in DraftEditorLeaf (created by DraftEditorBlock)
    in span (created by CommentDecorator)
    in CommentDecorator (created by Decorated(CommentDecorator))
    in Decorated(CommentDecorator) (created by DraftEditorBlock)
    in div (created by DraftEditorBlock)
    in DraftEditorBlock (created by DraftEditorContents)
    in div (created by DraftEditorContents)
    in div (created by DraftEditorContents)
    in DraftEditorContents (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in DraftEditor (created by PluginEditor)
    in PluginEditor (created by DraftailEditor)
    in div (created by DraftailEditor)
    in DraftailEditor (created by CommentableEditor)
    in CommentableEditor (created by DynamicOptionsEditorWrapper)
    in Provider (created by DynamicOptionsEditorWrapper)
    in DynamicOptionsEditorWrapper
    in EditorFallback
```

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

-   Wagtail version: 4.0rc
-   Browser version: Firefox 103, Safari 15.4, Chrome 106 on MacOS 12.3

**Comment by thibaudcolas** [comment]
Nice find @lb-! As mentioned this should be fixed in #9072.
