### ISSUE TITLE
Tabs in storybook are broken

### ISSUE THREAD

**Issue by PaarthAgarwal** [wagtail/wagtail#9092]
Tabs are no longer appearing in storybook. The console is throwing errors.

![Screenshot from 2022-08-26 22-44-21](https://user-images.githubusercontent.com/86092410/186959722-600fb370-492b-4bcc-b98e-d15fd53db12c.png)

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

-   Wagtail version: Latest main branch
-   Browser version: Chrome 98 (Edge on Ubuntu)

**Comment by lb-** [comment]
Confirmed as broken - not sure when as the underlying template change appears to have happened 2 months before the storybook file changed (maybe an older PR that got merged in).

Fix up https://github.com/wagtail/wagtail/pull/9097
