### ISSUE TITLE
Python 3.10 support in 2.16.x

### ISSUE THREAD

**Issue by dustinblanchard** [wagtail/wagtail#9095]
### Is your proposal related to a problem?

Currently there is a problem using Python 3.10 with the 2.16.x versions of Wagtail. `/wagtail/utils/utils.py` directly calls `collections.Mapping` which is deprecated in 310

(Write your answer here.)

### Describe the solution you'd like

This file should import Mapping from `collections.abc.Mapping` instead.

**Comment by lb-** [comment]
Thanks for raising the issue @dustinblanchard but 2.16 is no longer actively supported. 

https://github.com/wagtail/wagtail/wiki/Release-schedule

From what I can see - Wagtail 3.0 supports Python 3.10 as per this PR 
https://github.com/wagtail/wagtail/pull/8394

Is there a possibility you can update your Wagtail version to a supported one?

**Comment by dustinblanchard** [comment]
It's in our longer-term roadmap, but unfortunately we have a lot of custom code, so there are a lot of breaking changes when we install 3.0. It will be a significant undertaking for us. We're also waiting on some external packages like wagtail-autocomplete to support 3.0.

**Comment by lb-** [comment]
Ok. Can you possibly downgrade your environments to Python 3.9 or try to monkey patch the module?

**Comment by lb-** [comment]
Closing this for now as I do not see us putting a backwards patch for 2.16.x that is not a critical bug /security fix.

**Comment by gasman** [comment]
Reopening - it's looking fairly likely that we'll be doing a new 2.15 / 2.16 release for https://github.com/wagtail/wagtail/pull/9119, and if so, it makes sense for this to go in.

**Comment by saevarom** [comment]
Second that, we are running some projects on Wagtail 2.15.5 with python 3.10. Wagtail 2.15 is a LTS release so support for python 3.10 should be in place.

**Comment by gasman** [comment]
Have now backported the fix from #8394 to stable/2.15.x (721e5ba0df0317287bef8e77c008f43aeee11ad4) and stable/2.16.x (ae5d00f7a139b9ce2be8c33b043aad42196d62bc). Will plan to do a release to coincide with 3.0.3 and 4.0.1, probably next week.

**Comment by lb-** [comment]
Thanks @gasman

**Comment by lb-** [comment]
https://github.com/wagtail/wagtail/releases/tag/v2.15.6
https://github.com/wagtail/wagtail/releases/tag/v2.16.3 

Releases have gone out with Python 3.10 support

**Comment by saevarom** [comment]
Great, thanks! Already in production on two websites :)
