### ISSUE TITLE
Add JavaScript events for InlinePanel added/removed and potentially changed on inputs

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9105]
### Is your proposal related to a problem?

* Wagtail's `InlinePanel` solution is very powerful but does not easily allow JavaScript customisations.
* When an item is added or removed, there is no way to listen to that 'event' without having your own custom JavaScript code having full control over the InlinePanel being called (by passing in `opts.onAdd` for example).

### Describe the solution you'd like

* At a minimum it would be good to have some simple [CustomEvents](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent) dispatched for the added/removed that bubble up in the DOM so they can be listened to.
  * These must **not** be jQuery events but rather proper browser events
  * The dispatch element target should probably be the form elements container `formsElt`
  * Event should bubble but not be cancellable (the default, but good to be explicit)
  * Naming: `wagtail:inline-panel-added` & `wagtail:inline-panel-removed` would be suitable
  * It would be good to pass some useful info into the `detail` of the event such as the `maxForms`, `canOrder` options & current item count (after the add or remove)
* Additionally, it would be good to fire `change` events on the count/deleted/order inputs used throughout, so they could be listened to individually.
* Would need documentation (see the link to the Django approach below) with an example - currently the client-side customisation in the docs is here https://docs.wagtail.org/en/latest/advanced_topics/customisation/admin_templates.html#extending-client-side-components + it would be good to have a cross-reference here https://docs.wagtail.org/en/latest/reference/pages/panels.html#inlinepanel

### Describe alternatives you've considered

* Override the template `wagtail/admin/templates/wagtailadmin/panels/inline_panel.html` and copy/paste everything except for the inline script and then re-write the inline script with the onAdd ops or similar with the `buildExpandingFormset`
* Use MutationObserver to keep track of when things change inside InlinePanel - similar to this blog post https://dev.to/lb/creating-a-schematic-editor-within-the-wagtail-cms-with-stimulusjs-n5j

### Additional context

* Django 4.1 introduced `formset:added` and `formset:removed` events for a similar use case https://docs.djangoproject.com/en/4.1/ref/contrib/admin/javascript/#inline-form-events
* Note: There are two functions `buildExpandingFormset` & `InlinePanel` - these are related but most likely this change would be done in the `InlinePanel` code.
* https://github.com/wagtail/wagtail/blob/main/client/src/entrypoints/admin/page-editor.js#L5
* https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent

**Comment by 0saurabh0** [comment]
@lb- I want to work on this.
Anything for getting started.

**Comment by lb-** [comment]
@0saurabh0 go for it - just read the description in full and be sure you understand a use case for this and can reproduce it locally. Form builder is a good page that uses InlinePanel out of the box. 

Also I think maybe the page admin_templates should be split with the 'client side components' being its own page as a sibling of this one. Write the docs part and see how it feels all on this one page. 

https://docs.wagtail.org/en/latest/advanced_topics/customisation/admin_templates.html#extending-client-side-components

**Comment by xomcodes** [comment]
@yokwejuste are you working on this?

**Comment by lb-** [comment]
@yokwejuste & @xomcodes - as per comment in Slack - let's give @0saurabh0 a chance to see if it's still being worked on. 

@0saurabh0 - please can you advise if you are still giving this a go, all good if not, some others may take a look.

**Comment by 0saurabh0** [comment]
@lb- thanks for the chance. 
My bad I didn't tell, I'm very busy with my uni academics for some time  that's why I couldn't get a chance to work on this wholeheartedly.
So if anyone wants to work on this, can go for it.

**Comment by lb-** [comment]
No problems at all @0saurabh0 - wish you all the best for your study.

**Comment by lb-** [comment]
See a similar fix done for choosers, other libraries depend on browser events to initialise behaviour.

https://github.com/wagtail/wagtail/pull/10187
https://github.com/wagtail/wagtail/issues/10186

Keen for anyone to pick this up, happy to support with PR reviews. Let me know if you are keen for this one also @gsakkis 😉
