### ISSUE TITLE
Chooser button text: "Change" vs. "Edit" (vs. "Clear")

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9113]
### Is your proposal related to a problem?

Currently the buttons "Change" and "Edit" lead to confusion, which button actually changes what:
![chooser_buttons](https://user-images.githubusercontent.com/468164/187713067-d9a04730-1ba2-4f01-ac51-85537919baa4.png)

It is defined here:
https://github.com/wagtail/wagtail/blob/9e5250521f9db9ba39adf4102b8e854d68064126/wagtail/admin/viewsets/chooser.py#L23-L30
but also in other places, e.g.:
https://github.com/wagtail/wagtail/blob/9e5250521f9db9ba39adf4102b8e854d68064126/wagtail/admin/widgets/chooser.py#L24-L27

In german, I wanted to change that for the buttons to the german version of "Change selection", but unfortunately the id "Change" is also used by the permission tables in the settings, which overrides it atm:
https://github.com/wagtail/wagtail/blob/9e5250521f9db9ba39adf4102b8e854d68064126/wagtail/users/templates/wagtailusers/groups/includes/formatted_permissions.html#L20

Similar to that I also wanted to change the text for "Clear" to something like "Clear selection" in german. So at the end the user has the buttons "Change selection", "Edit" and "Clear selection".

### Describe the solution you'd like

Can we use a gettext context value or change the text for "Change" (and maybe "Clear") to something else?

**Comment by gasman** [comment]
See also #9045. Previously the label for this button was "Choose another", but this became "Change" in #8934 - clearly the new text is causing problems. cc @wagtail/page-editor-2022

**Comment by thibaudcolas** [comment]
Thanks for the report @th3hamm0r! I’m unclear on the rationale for this change myself but will follow up with our UX/design people.

**Comment by gasman** [comment]
Same issue in the French translation (#9193) - bumping this up to be handled in 4.0.2.

**Comment by lb-** [comment]
Added a bit of a summary of this underlying issue and learnings here https://github.com/wagtail/wagtail/discussions/8017#discussioncomment-3639114

Any feedback on that sub-comment would be appreciated.

**Comment by thibaudcolas** [comment]
@gasman did you check on this with Ben in the end? Again I don’t know what his rationale was for changing the button labels, but I assume there was one. At least to me the switch to shorter button labels made sense, as it made the position of the buttons much more predictable.

**Comment by thibaudcolas** [comment]
Looking at the code, "Change" is the word we use for Django’s change permission. I could only see it in use on the groups’ permission form, though there could be other places: https://github.com/wagtail/wagtail/blob/main/wagtail/users/templates/wagtailusers/groups/includes/formatted_permissions.html#L20

It’s important that buttons next to one-another display clear-enough labels in all languages, but even across separate pages it’s inappropriate for translations to use the same word for concepts we chose to name differently in the english version. So – we should switch this "Change" permission label to "Edit" if we think the translations are correct, or update the translations to use a different term.

In French, though "Changer" sounds very inelegant, it seems like a much more correct descriptor of what "Change" conveys in English (not much to start with)

**Comment by th3hamm0r** [comment]
@thibaudcolas 
> @gasman did you check on this with Ben in the end? Again I don’t know what his rationale was for changing the button labels, but I assume there was one. At least to me the switch to shorter button labels made sense, as it made the position of the buttons much more predictable.

Of course, that makes sense, but I really doubt that every language can express this only in single short words without confusing the user, what those buttons actually do. So even if expressed with a short text, I think you have to assume that those buttons are larger in other languages.

I'm not a native english speaker, but I also think that "Edit" and "Change" could lead to confusion. As a developer, I can help myself quickly by hovering the buttons, knowing that the button which changes the selection does not have an URL. Any other user will probably try what happens.

That's why in german we would like to use "Auswahl ändern" (bascially "change selection"), "Bearbeiten" ("edit"), "Auswahl zurücksetzen" ("clear selection"), if that would be possible, which is also the reason I've created this ticket ;)

**Comment by gasman** [comment]
> @gasman did you check on this with Ben in the end?

Not directly, but 1) he would have got a notification from the `@wagtail/page-editor-2022` ping above, 2) you said above that you'd follow up with our UX/design people, 3) I asked on Slack (on a channel that Ben is in) about the best way of this for designer attention and "contact Ben directly" wasn't mentioned as an answer, and 4) I did raise it in passing with our DM when talking about getting some of Ben's time for an unrelated task. I know Ben's time is valuable and we shouldn't expect him to be on call to respond to day-to-day Wagtail issues, but in that case we shouldn't let critical bugs be blocked awaiting his input - it feels a bit like [licking the cookie](https://devblogs.microsoft.com/oldnewthing/20091201-00/?p=15843).

I think we can reasonably close this issue, since it's about a specific bug reported by multiple people which has now been fixed in #9194. @thibaudcolas, if you believe there's a new issue that has been introduced by rolling back the change of label then I suggest you open a new ticket about it - but it seems to me that right now we're only speculating about what Ben's intentions were.

**Comment by thibaudcolas** [comment]
Sorry, I probably shouldn’t have reopened this, it’s definitely better as separate issues. Here is #9200 for us to review the label for choosers again, and #9201 to look into the conflating of terminology.

Moving forward on this without Ben’s input seems fine to me as a short term bug fix – but we do try to have him lick the cookie for all UI/UX decisions. It feels important to me that there’s centralised input / decision making for this as Wagtail’s UX and visual design direction isn’t as mature as what we have for technical direction.
