### ISSUE TITLE
StructBlock in StreamField inside standard Django Model (models.Model) that used as snippet works incorrectly in versions 3.0.2 and 4.0

### ISSUE THREAD

**Issue by rt-em** [wagtail/wagtail#9117]
### Issue Summary

I faced this issue after upgrading one of my projects to Wagtail 4.0 from Wagtail 3.0.1.

I have snippet for page footer to use it through all website pages.
I use StreamField to populate footer with social network icons. Every Icon represents StructBlock with two field.

```
...

from wagtail.snippets.models import register_snippet

...

@register_snippet
class Footer(models.Model):
    social_links = StreamField([
        ('external_link', blocks.StructBlock([
            ('code', DocumentChooserBlock(label='SVG File')),
            ('link', blocks.URLBlock(label='Link')),
        ], label='Link', icon='link-external')),
    ], blank=True, null=True, use_json_field=True)
...

```
**What I expect to see in Snippet menu for Footer model in admin:**
1. When I click on 'Link' block button in admin there is form of two fields (SVGfile and Link) appears.
2. If i click (+) button and then on 'Link' button another form of two fields appears, etc.
3. When I click up or down arrows 'Link' block follows up and down respectively.
4. When I click on Trash bin buttons 'Link' block disapears.
This is how this snippet behaves in Wagtail 3.0.1

**What I see in versions 3.0.2 and 4.0:**
1. When I click on 'Link' block button there is form with only one field appears(SVG File). It Appears not instaed of the 'Link' button, but below it. There are no (+) buttons appears above and below form of 'Link' block.
2. If I click 'Link' block button one more time there is another form with one field appers. Up and down buttons disabled, Trash bin button collapses the form instead of deleting it. It is not posible to expand form back again.

Dev console in browser shows this error:
```
Uncaught TypeError: this.block is undefined
    getTextLabel http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    collapse http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    toggleCollapsedState http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    e http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    jQuery 9
    e http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    e http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    _createChild http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    _insert http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    _onRequestInsert http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    onRequestInsert http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    renderMenu http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    jQuery 9
    renderMenu http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    renderMenu http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    renderMenu http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    open http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    setState http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    e http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    render http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    initBlockWidget http://127.0.0.1:8000/static/wagtailadmin/js/telepath/blocks.js?v=4677dac8:1
    <anonymous> http://127.0.0.1:8000/admin/snippets/home/footer/add/:522
blocks.js:1:13966

```

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Add abovementioned code to home/models.py
4. `makemigrations` and `migrate`
5. `runserver` and check work of Footer snippet in admin

- I did `collectstatic` to ensure that new JS files are pulled into static folder
- I tried to drop existing database and migrate from zero with Wagtil 4.0
- Downgrade to Wagtail 3.0.1 makes everything works fine.

### Technical details

-   Python version: 3.8
-   Django version: 4.0.7
-   Wagtail version: 3.0.2 and 4.0
-   Browser version: Firefox 104, Edge 104

**Comment by gasman** [comment]
Fixed in #9124
