### ISSUE TITLE
JavaScript error when rendering snippet containing a streamfield

### ISSUE THREAD

**Issue by vsalvino** [wagtail/wagtail#9126]
The streamfield editing within a snippet works in 3.0.1, but seems to throw js errors in the browser console in 3.0.2.

As far as I'm aware, there were not any API changes between these releases.

Follow the issue here: https://github.com/coderedcorp/coderedcms/issues/522

This can be reproduced by creating a fresh `coderedcms` project, with Wagtail 3.0.2 installed. Trying to create a navbar snippet for example throws the error in the browser console. This same behavior works OK in Wagtail 3.0.1.

The code for the navbar snippet is relatively vanilla, can be seen here. The key issue seems to be putting a StreamField in a snippet. Snippets without StreamFields work ok. https://github.com/coderedcorp/coderedcms/blob/aec431be55a8a04f179ac4e7ec88d469c2856856/coderedcms/models/snippet_models.py#L219-L262

**Comment by gasman** [comment]
Hi @vsalvino - I think this is the same as #9117. Please shout if not!

**Comment by vsalvino** [comment]
Looks like the same thing, thanks for the quick response!
