### ISSUE TITLE
Tag autocomplete dropdown has transparent background

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#9128]
### Issue Summary

The tag autocomplete dropdown has a transparent background on 4.0.

Testing on any blog page on bakerydemo:

Wagtail 4.0
![Screenshot 2022-09-02 at 12 18 48](https://user-images.githubusercontent.com/85097/188129046-b1265979-e568-4fd2-958f-71a0925bad37.png)

Wagtail 3.0
![Screenshot 2022-09-02 at 12 18 19](https://user-images.githubusercontent.com/85097/188129083-70788af3-b65f-4d78-a20b-27f5e794d9dc.png)

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.8.0
-   Django version: 3.2.15
-   Wagtail version: 4.0 / main
-   Browser version: Chrome 104.0.5112.101

**Comment by lb-** [comment]
Can confirm this issue exists and I think I found the commit that caused this 4eb35dbc0a6588d3a7e0ae083f14f7c8faf4adde

https://github.com/wagtail/wagtail/pull/8564

It looks like the removal of the background urls also removed the background colours, there are about 9 instances of this that appear to be required to put back in some form.

`client/scss/vendor/jquery-ui-1.10.3.verdant.css`

```
.ui-widget-content {
	border: 1px solid #d8d8d8;
	background: #ffffff url("images/ui-bg_flat_100_ffffff_40x100.png") 50% 50% repeat-x;
	/* background: #ffffff url("images/ui-bg_flat_100_ffffff_40x100.png") 50% 50% repeat-x; */
	color: #222222;
}
```

Putting these back (without the URL, just the background colour) looks like this.
<img width="496" alt="Screen Shot 2022-09-06 at 4 33 04 pm" src="https://user-images.githubusercontent.com/1396140/188563662-a8a146e9-a6ff-4014-aef9-8b9731a54441.png">

**Comment by lb-** [comment]
PR up for a fix https://github.com/wagtail/wagtail/pull/9146
