### ISSUE TITLE
User Management views are missing security testing

### ISSUE THREAD

**Issue by mehrdadmoradii** [wagtail/wagtail#9142]
### Issue Summary
Views in the User Management component are not tested against unauthorized users.

### Steps to Reproduce

1. Remove all authorization decorators in `wagtail.users.views.users`.
2. Run `./runtests.py`

All the tests will pass as a result of executing the test runner.

**Comment by lb-** [comment]
Nice find. We should definitely add tests for this.

**Comment by lb-** [comment]
@mehrdadmoradii did you want to give this a go?

**Comment by mehrdadmoradii** [comment]
@lb- I am working on that. But I think it needs more time than I expected!

**Comment by lb-** [comment]
No problems - reach out if you need a hand.

**Comment by mehrdadmoradii** [comment]
@lb- Thanks a lot, I will!
