### ISSUE TITLE
Allow override Fields from non-abstract Pages

### ISSUE THREAD

**Issue by jkevingutierrez** [wagtail/wagtail#9154]
### Is your proposal related to a problem?

There are some cases where a field is defined in a non-abstract parent Page, and some properties of that field (help_text, blank, verbose_name) needs to be overridden in the children pages.

### Describe the solution you'd like

Overriding field properties should be allowed for non-abstract classes, or there should be an easy an reliable way to modify the properties in the constructor or in the init method of the pages that should apply only for that case without conflicting with other overrides.

Solution 1 allow override fields from non abstract pages:

```python
class ArticlePage(Page):
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
       help_text="Image"
    )
```

```python
# here we want to make the image required
class SpecificArticlePage(ArticlePage):
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=False,
        blank=False,
        on_delete=models.SET_NULL,
        help_text="Image"
    )
```

```python
# here we want to make the image required and modify the help_text
class OtherSpecificArticlePage(ArticlePage):
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=False,
        blank=False,
        on_delete=models.SET_NULL,
        help_text="16:9 image"
    )
```

Solution 2 add a way to override the properties in the fields without conflicting with other overrides:

```python
class ArticlePage(Page):
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
       help_text="Image"
    )
```

```python
# here we want to make the image required
class SpecificArticlePage(ArticlePage):

    def __init__():
        self.image.blank = False
        self.image.null = False
```

```python
# here we want to make the image required and modify the help_text
class OtherSpecificArticlePage(ArticlePage):
        def __init__():
        self.image.blank = False
        self.image.null = False
        self.image.help_text = "16:9 image"
```

### Describe alternatives you've considered

There is a hacky way to achieve this right now: https://stackoverflow.com/a/57498309

But when there are multiple children objects that needs to override multiple properties, the admin interface shows the values randomly

### Additional context

(Write your answer here.)

**Comment by chosak** [comment]
Hi @jkevingutierrez - this isn't generally possible for model field properties due to a limitation of Django model fields; please see [Field name “hiding” is not permitted](https://docs.djangoproject.com/en/4.1/topics/db/models/#field-name-hiding-is-not-permitted) in the Django docs:

> In normal Python class inheritance, it is permissible for a child class to override any attribute from the parent class. In Django, this isn’t usually permitted for model fields. If a non-abstract model base class has a field called author, you can’t create another model field or define an attribute called author in any class that inherits from that base class.

As you suggest, one way around this is to use abstract Page classes.

**Comment by gasman** [comment]
Closing as this is something that would have to be supported at the Django level.
