### ISSUE TITLE
"Media files" text on dashboard is large and overlapping

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#9163]
### Issue Summary
When viewing the Wagtail 4.0.1 dashboard, the "Media files" text is really large and overlapping itself.

![image](https://user-images.githubusercontent.com/17307/188934047-e074bc84-170d-4b7d-a528-ef2aedc66bea.png)

### Steps to Reproduce

1. log in to the Wagtail 4.0.1 dashboard
2. see the "media files" text

### Technical details

-   Wagtail version: 4.0.1

**Comment by gasman** [comment]
This comes from the wagtailmedia package, not Wagtail itself - you probably need to update it to v0.11: https://github.com/torchbox/wagtailmedia/releases/tag/v0.11.0
