### ISSUE TITLE
Embed chooser modal is missing vertical padding

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9182]
Raised in https://github.com/wagtail/wagtail/pull/9172#discussion_r968303131.

In Wagtail 4, the embed chooser modal is missing its vertical padding between the header and form:

!["Insert embed" modal dialog, with a single URL field and an Insert button under](https://raw.githubusercontent.com/wagtail/wagtail/77e6505f97a819ee53b919ed3ea14a8622e2c217/docs/_static/images/screen20_insert_video_form.png)

This should be resolved as part of redesigning the choosers.

**Comment by lb-** [comment]
PR up with a fix https://github.com/wagtail/wagtail/pull/9186
