### ISSUE TITLE
Broken dashboard JS due to notifier’s version processing failing for nightly release versions

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9184]
Version numbers from our [nightly releases](https://releases.wagtail.io/nightly/index.html) are incorrectly formatted according to our upgrade notifier [version processing](https://github.com/wagtail/wagtail/blob/6b238454359c7b9aeb412e095777c63ff3592d8c/client/src/utils/version.js#L29-L32).

Sample version this fails on: `wagtail-4.1.dev20220912`

Looking at our version processing regex, it seems we’re missing support for `dev` releases, and there are other issues that would either require more changes, or require us to change formatting in `releases.wagtail.io`

Error in the browser console:

```
Uncaught 
t
message: "Version number '4.1.dev20220912' is not formatted correctly."
[[Prototype]]: Error
```

And here is where we generate version numbers: https://github.com/wagtail/wagtail/blob/6b238454359c7b9aeb412e095777c63ff3592d8c/scripts/nightly/get_version.py#L11-L32

**Comment by lb-** [comment]
<img width="2048" alt="Screen Shot 2022-09-13 at 3 11 23 pm" src="https://user-images.githubusercontent.com/1396140/189814347-02c41376-0988-480a-b303-cf409aa76d47.png">

Confirmed

**Comment by sdmoran** [comment]
Hi, I'm interested in working on this issue. It seems as though this specific version could be made to match by changing the `preReleaseStep` capture group to `(?<preReleaseStep>a|b|rc|\.dev)`:
![image](https://user-images.githubusercontent.com/33131675/195491128-29da2f48-a09e-4d11-ac41-e6ae999478db.png)

It does feel a little hacky to have dev builds formatted differently than a/b/rc though, would it be better to change the Python code for generating the version so dev build formats match a/b/rc? @thibaudcolas can you elaborate on what other issues there are that would require more changes?

**Comment by lb-** [comment]
I think it's ok to update our JS. We can just not throw and error in this case - and no need to try to match the versions to try to show the message here as it will never happen.

**Comment by thibaudcolas** [comment]
@sdmoran I’m not sure what I meant by "other issues" definitely fixing one issue will be a good start 😛
