### ISSUE TITLE
releases.wagtail.org fails to load due to CORS

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9192]
Our README documents <https://releases.wagtail.org/nightly/index.html> as the page to look at the latest nightly release. Unfortunately on this page the data fails to load due to CORS, as we load the data from the old domain:

> Access to fetch at 'https://releases.wagtail.io/nightly/latest.json' from origin 'https://releases.wagtail.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Fetching the data with the `.org` domain directly works as expected (`curl https://releases.wagtail.org/nightly/latest.json`), so I think we need to update this page to change the domain this is fetching from. Ideally fetch from `/nightly/latest.json` so we don’t have this issue in the future.

**Comment by thibaudcolas** [comment]
@kaedroho I believe you had set this up initially, could you point us to where the HTML/JS code is for `releases.wagtail.org` so we can update it?

**Comment by lb-** [comment]
Not sure if this PR is relevant but maybe I should re-open this https://github.com/wagtail/wagtail/pull/7906

**Comment by th3hamm0r** [comment]
Fyi: I've also stumbled over this and created an issue here: https://github.com/wagtail/wagtail.org/issues/223
I thought that was the right place 😅

**Comment by thibaudcolas** [comment]
Ah! Nice one @th3hamm0r, I’m not too sure which of those two would be most appropriate tbh.

It looks like someone fixed this – I now see `access-control-allow-origin: *` on https://releases.wagtail.io/nightly/latest.json. So will close this now.

@lb- I believe the S3 bucket name doesn’t really matter, as long as resources served from it by Cloudfront work for both `releases.wagtail.org` and the legacy `releases.wagtail.io`. I’ll open a sysadmin ticket at torchbox to rename the bucket, and then we can re-open #7906.
