### ISSUE TITLE
No distinction between "Edit" and "Change" on image panel in french

### ISSUE THREAD

**Issue by sephii** [wagtail/wagtail#9193]
### Issue Summary

The french translation translates both "Edit" and "Change" to "Modifier", which makes the 2 buttons in the image panel have the same label (although they’re doing different things). Here’s what you get in english (correct):

![screen](https://user-images.githubusercontent.com/754333/189930701-7362edc3-27b5-4361-a175-9611771e2df4.png)

And in french (incorrect):

![screen2](https://user-images.githubusercontent.com/754333/189930766-c5552b6d-112c-4505-91f8-2c20526bdd50.png)

The fix would be to change the translation of "Change" to "Changer".

### Steps to Reproduce

Switch to french language and edit a page with an image chooser. I think the issue started appearing in Wagtail 4.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.9.13
-   Django version: 4.1.1
-   Wagtail version: 4.0.1
-   Browser version: n/a

**Comment by gasman** [comment]
Thanks for the report @sephii! It seems the same thing happened for the Italian translation (#9045) - there's an open ticket #9113 proposing that we change the label back to "Choose another", so I'll close this as a duplicate and bump #9113 up in priority to 4.0.2.

**Comment by sephii** [comment]
Thanks!

**Comment by lb-** [comment]
Added a bit of a summary of this underlying issue and learnings here https://github.com/wagtail/wagtail/discussions/8017#discussioncomment-3639114

Any feedback on that sub-comment would be appreciated.
