### ISSUE TITLE
Delete link from the page edit view redirects back to a 404

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#9195]
### Issue Summary

The "Delete" link in the top menu on the page edit view has a `?next` URL parameter that points back to the current page. This means that after confirming deletion, the user is redirected back to the edit view for the page that no longer exists, resulting in a 404 error.

### Steps to Reproduce

1. On a fresh bakerydemo instance, log in to http://localhost:8000/admin/ and go to http://localhost:8000/admin/pages/77/edit/
2. From the top menu, select Delete
3. Observe that the URL of the confirmation page is http://localhost:8000/admin/pages/77/delete/?next=%2Fadmin%2Fpages%2F77%2Fedit%2F
4. Click "Yes, delete it"
5. You are redirected back to http://localhost:8000/admin/pages/77/edit/ , which is now a 404

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.8.0
-   Django version: 3.2.15
-   Wagtail version: 4.0.1 and main (d1908ee07f3959abfdd1d317ff2fa3598a27579e)

**Comment by gasman** [comment]
Looks like this was introduced in 887a25972365a7a63d5ae5f1f45551e2f683baea. cc @PaarthAgarwal @lb-

**Comment by lb-** [comment]
Thanks @gasman I will investigate.

**Comment by lb-** [comment]
Can confirm this problem exists.

**Comment by lb-** [comment]
Looks like there is an additional issue here - when we do correctly remove the next_url for explorer listing the `next_url` is set to `None` for any subsequent buttons.

This means that the unpublish button on the page listing more button has no next url (as the one above, delete, removes it).

Code was added on this commit.
https://github.com/wagtail/wagtail/commit/35b5ed350a30dfb626d55c0b2c021976c1f65761#diff-36df4ec1db3007baedd8eba9ad2f5709f514c93c7136b7285a9e811ab5c37c00R415-R434

Working on a fix now.

**Comment by lb-** [comment]
PR up with a fix https://github.com/wagtail/wagtail/pull/9197
