### ISSUE TITLE
Design update - secondary button with icon - Wagtail Design System

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9198]
> **Good first issue** for someone confident with SCSS/CSS

### Is your proposal related to a problem?

* There is not yet a officially supported button with icon that aligns with the secondary button styles (outline only button)
* If `button-secondary` is applied to the current `bicolor` button styles, it works but should align with the new official Wagtail Design System

### Describe the solution you'd like

* [ ] Add support for the with icon (secondary, aka ghost) buttons as per the [design system Figma](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=5172%3A30751)
* [x] Add new variants using `.button-secondary` with `bicolor button-icon` in the styleguide https://github.com/wagtail/wagtail/blob/main/wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
* [x] Add new variants using `.button-secondary` with `bicolor button-icon` in the pattern library https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/button.stories.tsx
* [ ] Add styles for these variants in https://github.com/wagtail/wagtail/blob/main/client/scss/components/_button.scss
* [ ] Must work in all supported browsers https://docs.wagtail.org/en/stable/contributing/developing.html#browser-and-device-support

#### Normal size button-secondary with icon

Very similar to the `bicolor` currently but with different colours, must support all existing supported DOM elements for buttons (`a`, `button`, and `input[submit`).

* Default
* Hover
* Disabled
* Focus state (existing global focus outline)

<img width="1097" alt="Screen Shot 2022-09-14 at 4 55 27 pm" src="https://user-images.githubusercontent.com/1396140/190082626-a0c1c6a8-6e15-4f8a-a52f-a1c5d4f09aa2.png">

#### Normal size button-secondary with icon

When small and secondary the border is dropped, must support all existing supported DOM elements for buttons (`a`, `button`, and `input[submit`).

* Default
* Hover
* Disabled (not shown)
* Focus state (existing global focus outline)

<img width="563" alt="Screen Shot 2022-09-14 at 4 56 31 pm" src="https://user-images.githubusercontent.com/1396140/190082863-d8e43d2a-f857-4453-a868-32d7be310327.png">

### Describe alternatives you've considered

Leave as current state and do not document `.button-secondary` when used with `.bicolor`.

| `button bicolor button--icon button-secondary` | `button bicolor button--icon button-secondary button-small` |
| --- | --- |
| <img width="661" alt="Screen Shot 2022-09-14 at 4 51 53 pm" src="https://user-images.githubusercontent.com/1396140/190081963-b72d60cf-6b85-4e4d-9d62-55fef4ef1ed3.png"> | <img width="658" alt="Screen Shot 2022-09-14 at 4 51 40 pm" src="https://user-images.githubusercontent.com/1396140/190081978-a4bd27ac-eb05-4fd8-95e3-a0585cf133fb.png"> |

### Additional context

* The bulk of the original button designs issue was completed via https://github.com/wagtail/wagtail/issues/8790
* As this button type was not officially supported or used, it ended up being out of scope.

**Comment by lb-** [comment]
Marking as good first issue - split from https://github.com/wagtail/wagtail/issues/8790
@thibaudcolas  please have a read when you get the chance.

**Comment by Adinapunyo-Banerjee** [comment]
Hi, I am new to the Wagtail codebase. I would like to work on this design issue. Could someone please help me out with the directory of the css source files?
Also, I quite didn't understand what the issue really is. Any help would be very helpful. Thanks!

**Comment by lb-** [comment]
@Adinapunyo-Banerjee the issue description clearly calls out exactly what file to update with the new styles. 

Maybe a different good first issue might be more suitable - but have a full read of the description again and see how you go.

**Comment by Adinapunyo-Banerjee** [comment]
Okay, thanks!

**Comment by Adinapunyo-Banerjee** [comment]
@lb- Hey, I have been trying to work on this issue. The UI Styleguide seems to be static and making changes to the base.html does not reflect on the style guide (as mentioned in the UI Styleguide `https://docs.wagtail.org/en/latest/contributing/styleguide.html` documentation).

![code](https://user-images.githubusercontent.com/110435416/191292988-5281b6fe-206e-42fc-a813-e9e07cb1678e.JPG)

When I change "Contents" to "Contents SHOULD CHANGE"

![should change](https://user-images.githubusercontent.com/110435416/191292955-fe3aa9ef-5efa-42f9-aa1e-46d40649c247.JPG)

It does not reflect.

How do I make changes to this page and review it?

(Might be a dumb question)

**Comment by gasman** [comment]
@Adinapunyo-Banerjee It's possible that your Python environment is still running a copy of Wagtail that's been installed as a package (with `pip install wagtail`), rather than the one you checked out from Github. Try running `pip freeze` - if the output includes a line like `Wagtail==4.0.1` then it's running a packaged version. If so, run the following from the `wagtail` folder where you checked out the Wagtail codebase:

    pip uninstall Wagtail
    pip install -e .[testing,docs]

**Comment by Adinapunyo-Banerjee** [comment]
Thanks @gasman, I realized what the problem was. Could have directly worked on the Wagtail package.

**Comment by rydanstar01** [comment]
Hello Sir/Madam, I would like to contribute to this issue.

**Comment by zerolab** [comment]
@rydanstar01 thank you for offering.

Just above your comment, there is a reference to #9243 which is a PR that aims to address this. So the best way to contribute is to test that PR and add your feedback on it.

**Comment by lb-** [comment]
Partial work completed - pattern library & styleguide have been updated via https://github.com/wagtail/wagtail/pull/9243

Thanks @Adinapunyo-Banerjee

**Comment by Seremba** [comment]
Hi @lb-, @Adinapunyo-Banerjee is this issue assigned to anyone or I can go on and work on it

**Comment by Seremba** [comment]
Hi @lb-, I have finished working on this issue. I am kindly asking for your review and suggestions on how to improve. 

Thanks  a lot
