### ISSUE TITLE
Contents of the status panel available at a glance

### ISSUE THREAD

**Issue by minusf** [wagtail/wagtail#9216]
### Issue Summary

The current language of the article and other useful information is hidden away under the status icon.

We are in the process of rolling out a 7 language site and this is becoming super frustrating very quickly. There is a ton of whitespace on the editing page and important stuff that needs to be accessible at a glance was all hidden away into animated side panels. Aside from the design decisions (which many of those i personally disagree) important information should not be hidden away when the editing page itself is "half empty". Please reconsider this design decision.

### Steps to Reproduce

1. Install wagtail
2. Edit a page

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.9.10
-   Django version: 4.0.7
-   Wagtail version: 4.0.1
-   Browser version: firefox

**Comment by thibaudcolas** [comment]
Hi @minusf, have a read through #7739 if you want a better understanding of those design decisions. Is it the only the page’s language that you find missing? The page type?  Obviously there is a lot of empty space on the page when none of the panels are opened, but the point of having the space is so panels can be shown alongside the form, with contents visible without people having to spend a lot of time scrolling up and down the page.

We were planning to have the Info panel opened by default when arriving on the page editing UI, would that solve your issues?

**Comment by minusf** [comment]
> We were planning to have the Info panel opened by default when arriving on the page editing UI, would that solve your issues?

That would basically mean on every notebook (and not some 34" external display) one forced click before starting editing the article. Swapping one frustration for another...

I understand that design is hard and I am not a designer. But i dont have to be a designer to see that this UI is not good UX.

It's a clear red flag to me when there are huge areas of blinding white in the editor interface and one has to click around to see useful information that should be available at first glance for anything more than a boutique site with 4 pages to edit...  I am talking about sites with thousands of pages in multiple languages. 

I had only a very quick look at the discussion, it would take days to go through it. I see that the panel information was at some point crammed into the "header".  But I dont understand why it has to be a binary decision, show in header/show in a hidden panel.  There is so much _space_, why not put these things _under_ the header into its dedicated status section?  And sure, the panel can be used when already scrolled away from the top in a very long document.

**Comment by thibaudcolas** [comment]
Right now we display the form and the side panels side-by-side for screen widths starting at 1200px. Here’s what it looks like for reference, with the collapsed sidebar (also works with it expanded):

![wagtail-4-side-panel-status-collapsed-sidebar](https://user-images.githubusercontent.com/877585/191217085-1c840242-eaf1-489c-a2df-d3f48ca6236a.png)

That feels like it would work fine on all notebooks I’m aware of, no need for anyone to reach for a 34" display. 

> But I dont understand why it has to be a binary decision, show in header/show in a hidden panel.

We can definitely duplicate key bits of information (we already do for the page’s "Live" status"), but again if you want to suggest this it’d be more useful for you to state which bits of information you think warrant this treatment.

One of the goals with this design was to minimise the amount of scrolling required when editing pages, and to me it feels like the "panels" approach does this quite well – we can add arbitrary amounts of metadata in the Info side panel without it always taking up space regardless of whether people need this info or not.

**Comment by minusf** [comment]
Yes, with the collapsed side menu, this approaches usable, but that is neither the default, nor preferred by everyone. With the full menu the editing interface becomes very small.

And yes, the Live button survived the redesign, and I imagine the eye inside it is "Visible to all" and there is the History button as well. This means that from the 7 items/actions in the side panel, 3 are always visible already and made redundant in the side panel...

On the other hand 2 features that for some do not need to be present all the time and take up space are History and Preview...

What I am trying to say is: different information has different importance to different editors. What stays on the editor and what goes into panel decisions can never please everyone. And I think that's why the side panel should be converted into a panel strip under the breadcrumbs (which needs all the space it can get as we already need to scroll on most of our pages. also it would be much more useful if it showed the ending bit in full, not the root of the site...) and sticky scroll together with it.

I'd like to ask: were these changes implemented based on feedback from actual editors?

**Comment by thibaudcolas** [comment]
I chose 1200px as that’s the _minimum_ we currently make work. This isn’t reliant on the sidebar being collapsed at all – if using the default sidebar, there’ll just be less space for the form at that specific width. At a more realistic 1280px width, the full sidebar + form + panel look completely fine.

This isn’t even the final designs anyway, with the work in #9036 / #9090, we’re intending to make this combination of "full sidebar + form + side panel" possible even at a width of 1024px.

Between this and our intention to keep the last-used side panel opened on page loads (#9269) and of resizing side panels (#9276), I believe there’ll be plenty of opportunity for users who want it to constantly have this information available and make the most of their screen.

> On the other hand 2 features that for some do not need to be present all the time and take up space are History and Preview...

I don’t think this is a fair comparison. Those two are just icon buttons, which is the least amount of space a link or button like this can take. And they take up the same space regardless of the page’s state and user language. Page metadata on the other hand is much harder to fit into a navbar like this due to its dynamic nature.

> I'd like to ask: were these changes implemented based on feedback from actual editors?

Yes. I believe this redesign project is the one we’ve spent the most effort gathering feedback for ever, much earlier in the process than usual.

**Comment by thibaudcolas** [comment]
I’ve closed this now as of #9269 – I believe this fits the bill in terms of seeing the page info at a glance. #9036 will be next, and then #9276 after.
