### ISSUE TITLE
Adopt core shared header for Snippet type listing header

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9227]
### Is your proposal related to a problem?

The Snippet type listing header is one of the last major header usages within the admin that is not using the using the core (non-slim) shared header template or include.

### Describe the solution you'd like

* Using either a template that extends the shared header OR the template include, ensure that the  [wagtail/snippets/templates/wagtailsnippets/snippets/type_index.html](wagtail/snippets/templates/wagtailsnippets/snippets/type_index.html) view uses the shared header.
* This is so that shared styles will all work the same and do not need to be maintained across multiple files.

### Describe alternatives you've considered

* Leave as is, ok to maintain these in isolation for the most part.

### Additional context

* See initial work to unify headers https://github.com/wagtail/wagtail/issues/8539
* See a very similar work for the model admin header - https://github.com/wagtail/wagtail/issues/8907 (it may make sense to do that first as some blocks/args will be required for that which could be used for this issue)

### Notes for potential implementation approach

`wagtail/snippets/templates/wagtailsnippets/snippets/type_index.html`

* Firstly, you will likely need to create a new template that extends OR includes the header.
* Firstly, set up a fragment that uses `{% include 'wagtailsnippets/snippets/headers/list_header.html' %}` (this should be just breadcrumbs) and pass it into the block breadcrumbs (be careful here as it may not render in the same way, investigate this usage carefully)
* Pass in the icon name `snippet` instead of rendering it on its own
* `model_opts.verbose_name_plural|capfirst` becomes the title arg
* The search URL looks like a copy verbatim of the existing search in the shared template
* `{% if locales %}` - this may not have a home (adds an extra col), see if there is a nicer way to achieve this goal
* If we are happy to reverse the order, the locale selector can go into `extra_actions` and the `action_url` should be sufficient for `can_add_snippet`

**Comment by lb-** [comment]
Split from https://github.com/wagtail/wagtail/issues/8907 which was split from https://github.com/wagtail/wagtail/issues/8539

Note: This is for the Snippets type listing, not Snippets editing etc (these use the new slim header)

<img width="1457" alt="Screen Shot 2022-09-19 at 8 58 28 pm" src="https://user-images.githubusercontent.com/1396140/191002949-33f1c208-b8ed-4b21-8aa1-de0647d2f5d4.png">

**Comment by lb-** [comment]
This might be a issue for someone confident with Django templates and willing to pick up something slightly more complex that preserves existing behaviour but makes the code much easier to maintain.

**Comment by akshay-gupta7** [comment]
@lb- , can I get started on this.

**Comment by lb-** [comment]
Go for it @akshay-gupta7

**Comment by lb-** [comment]
@akshay-gupta7  are you still working on this? It's OK if not - just trying to get a sense of things.

**Comment by akshay-gupta7** [comment]
@lb- yes I'm working on this, I'll provide you with an update by this weekend.

**Comment by lb-** [comment]
@akshay-gupta7 no problems at all & no rush. Just add a comment to this issue if you're stuck with anything or have any questions.

**Comment by akshay-gupta7** [comment]
Appreciate the support @lb- !

**Comment by salty-ivy** [comment]
@akshay-gupta7 should i take this one up? if you not working on it?

**Comment by salty-ivy** [comment]
@lb-  let me know if i can give this one a try

**Comment by akshay-gupta7** [comment]
@salty-ivy sure go for it

**Comment by lb-** [comment]
Note - once https://github.com/wagtail/wagtail/pull/9993 is merged - this issue will be much easier to resolve.

**Comment by salty-ivy** [comment]
a simpler solution could be to just `fragment` the whole include statement and put is as `breadcrumb`  argument in `wagtailadmin/shared/hearder`

**Comment by salty-ivy** [comment]
@lb-  you can have a review at this one https://github.com/wagtail/wagtail/pull/10169 at your ease, thank you.
