### ISSUE TITLE
Majority of `StreamField` and `StreamBlock` UI elements not visible or missing when rendered within a `MultiFieldPanel`

### ISSUE THREAD

**Issue by kbayliss** [wagtail/wagtail#9232]
### Issue Summary

When a `StreamField` is rendered within a `MultiFieldPanel` (including any child StreamField's via `StreamBlock`s), the majority of the StreamField UI becomes invisible (with opacity set to `0`).

As one example, there seems to be some overridden/conflicting CSS on the `.c-sf-add-button--visible` element.

Some specifics:

1. The top-level `StreamField` does not show the left-most grey dotted line on hover (this may be intentional)
2. 'Add' buttons to insert new blocks are not visible on hover
3. 'Close' buttons to close StreamField choosers (i.e. what shows the available blocks) are not visible on hover
4. `StreamBlocks` within the `StreamFIeld` are also affected, though not to the same degree (disabled buttons, e.g. when validation prevents additional blocks from being inserted, are shown. It's just the clickable ones that are not shown). 

There are no JS errors, and no validation is being applied that would restrict the number of allowed blocks.

### Steps to Reproduce

For StreamFields: place any StreamField within a MultiFieldPanel, e.g.:

```
class MyWorkingPage():
    content = StreamField(...)

    content_panels = [
        FieldPanel("content")
    ]

class MyBrokenPage():
    content = StreamField(...)

    content_panels = [
        MultiFieldPanel(
            [
                FieldPanel("content")
            ]
        )
    ]
```

For StreamBlocks: repeat the above, but with a nested StreamBlock(s) 

##### Correctly working outside of MultiFieldPanel

![StreamField hover](https://user-images.githubusercontent.com/3009233/191223066-8edeab9e-2e83-4382-8ed9-944cce7ac6ae.png)

##### Not working when used within MultiFieldPanel

![StreamField hover (MultiFieldPanel)](https://user-images.githubusercontent.com/3009233/191223051-64b4b8f8-df22-4da5-b155-fe1eb045b34b.png)

##### Correctly working outside of MultiFieldPanel

![StreamField block added](https://user-images.githubusercontent.com/3009233/191223063-62f89de0-3169-416d-b202-622b0c590ef6.png)

##### Not working when used within MultiFieldPanel

![StreamField block added (MultiFieldPanel)](https://user-images.githubusercontent.com/3009233/191223059-6a0af830-e0b1-468e-bf6d-0a14bfc926ea.png)

##### Correctly working outside of MultiFieldPanel

![StreamField block chooser](https://user-images.githubusercontent.com/3009233/191223040-c2a44a6f-3524-4a25-90c2-16da1114ff68.png)

##### Not working when used within MultiFieldPanel

![StreamField block chooser (MultiFieldPanel)](https://user-images.githubusercontent.com/3009233/191223065-a239435b-cdef-41fa-820b-603281157f01.png)

#### Example of overriding CSS

![Overriding CSS](https://user-images.githubusercontent.com/3009233/191223055-13c7f534-2153-435f-abe0-7f725d424fe7.png)

### Technical details

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes
-   Wagtail version: `4.0.1`

**Comment by kbayliss** [comment]
Just to clarify, I am hovering over the `StreamField` for each of the screenshots... it just doesn't look like I am most of the time (hence the issue!).

**Comment by lb-** [comment]
Can confirm this issue.

There should be the `+` button as I am hovered over the StreamField.

<img width="1051" alt="Screen Shot 2022-09-22 at 2 56 40 pm" src="https://user-images.githubusercontent.com/1396140/191661699-df679b4a-bbc1-4b09-b999-c654f28bc181.png">


When NOT in an MultiFieldPanel - this is what it looks like.

<img width="1076" alt="Screen Shot 2022-09-22 at 2 57 19 pm" src="https://user-images.githubusercontent.com/1396140/191661784-f7d366f4-bce7-4af6-b20c-2c88ca93a27f.png">

**Comment by allcaps** [comment]
A bit late, but might be useful in the future: https://github.com/wagtail/bakerydemo/pull/368
