### ISSUE TITLE
Track Python tests coverage

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#9283]
We used https://coveralls.io at one point according to #4143 (and in fact there's a link to it on the current version of https://wagtail.org/features if you squint hard enough), but it hasn't been updated since 2016.

We used https://codecov.com for our frontend code as of #4219. There were changes to our Python coverage configuration in #6054 but it's not reflected in any of our CI setups. The coverage badge was removed in #7179 as the data only reflects our JS coverage.

We didn't reintroduce the badge in #8082 because we couldn't find the representative coverage data for the whole Wagtail project. Why? Well, because none of our CI setups run the Python tests with coverage, so we don't really have the data yet 😄

I think we should update our CI setup, at least the GitHub Actions workflow, to run the tests with coverage and show the report. This might be a bit tricky because there are tests specifically written for certain database backends and setups only (e.g. PostgreSQL, SQLite, search with ElasticSearch, etc.).

What we could try to do is run the tests with coveragepy's `--parallel-mode` argument, upload the partial coverage data as artifacts, and [`combine`](https://coverage.readthedocs.io/en/stable/cmd.html#combining-data-files-coverage-combine) them together after all tests have passed. Then, we should be able to get the full coverage report from all the test runs combined, which can then be shown on the CI output and possibly sent to codecov under a different flag (e.g. `backend` instead of [`frontend`](https://github.com/wagtail/wagtail/blob/466a911e54faae0be5f1411c92b36a18c8eb9b04/.circleci/config.yml#L56)). I've done this previously for [one of my projects](https://github.com/laymonage/django-jsonfield-backport/blob/master/tox.ini#L35), but that was with Coveralls instead of Codecov.

Then, hopefully, we'll have the representative coverage percentage (Python + JavaScript either combined or separate) that we can show on the README...

Useful resource: https://nedbatchelder.com/blog/202209/making_a_coverage_badge.html

**Comment by lb-** [comment]
I think this would be great to see. Test coverage is a good indicator for project health and quality. 

Maybe a good first step for the readme badge would be to run the coverage only on a successful merge into `main`. This will hopefully avoid some complexity and CI overhead for CI only running on PRs.

As an aside - we currently do not push for much JS test coverage but I personally think it's important. Having the ability to report on this in isolation would be a good step in the future of improving our JS coverage.
