### ISSUE TITLE
Changing the slug of a draft page to allow reusing it does not work

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9285]
### Issue Summary

Actually, this issue is not only limited to the slug, its a general issue:
When you create a new draft page, the initial content is stored in the `Page`'s table (and also as a new revision). All further edits only create new revisions.
This leads to the problem, that this page now "blocks" its initially defined slug. You cannot  rename the slug to use it for another page, because the new slug is only stored in a revision.
Currently, you can only move it to another location, or publish it with a different slug and unpublish it afterwards...

This is really an issue for one of our sites, where the customer has thousands of pages and sometimes reuses slugs for yearly promotions. The old promotion usually gets unpublished (automatically), but it is kept for documentation. In the next year, a new page with the same slug, at the same location should be placed. In the previous system, where we've used a different CMS, the customer found the validation error "slug in use", renamed the old (draft) page, and then saved the new one. This isn't possible with wagtail at the moment.

### Possible Solution

Similar on how the creation of an initially drafted page writes into the `Page`'s table AND creates a new revision, this should also be done for pages that are not live (`page.live == False`).

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. `./manage.py makemigrations && ./manage.py migrate && ./manage.py createsuperuser && ./manage.py runserver`
3. Login to the CMS
4. Create a new draft page with the slug "test"
5. Change the slug to "test2" (only save as draft, so the page is still not published)
6. Again, create a second page with the slug "test" and see the validation issue ("This slug is already in use")

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10
-   Django version: 4.1
-   Wagtail version: 4.0.2

**Comment by yokwejuste** [comment]
Hey @th3hamm0r This is really a bug just from following your steps and getting a validation error!

Normally an unused slug should be reusable if not more in use.

### Screenshots
![image](https://user-images.githubusercontent.com/71908316/195405191-633e2d74-a694-4fb3-9266-ce489e6479fc.png)

**Comment by allcaps** [comment]
Would it be a logical strategy to _only_ check live pages for duplicate slugs? 

If Wagtail would check slug uniqueness on publish, the duplicate slugs in drafts would be irrelevant.

I'm probably forgetting about scenario's which refute this proposal... :)

**Comment by th3hamm0r** [comment]
I think this would increase the probability of shooting yourself in the foot 😉
The current solution is not bad, because it also validates uniqueness for scheduled publications for example. Django just validates all unique fields against the db, just before we write all the data into a new revision.

I think the only inconsistency left is, that the initial creation of a draft writes into the page table(s), all further edits, while the page is still unpublished, are written to the revisions only, which is unnecessary. In that case we could just write into the page tables directly (+ create a revision) and avoid blocking unique values with data, which may be stale already.

I think I will look into this and try to submit a PR.
