### ISSUE TITLE
RichTextBlock Loses space if it's written in Bold mode

### ISSUE THREAD

**Issue by GiorgiMatcharashvili** [wagtail/wagtail#9288]
### Issue Summary

Bolded spaces doesn't shows up on the front.

### Steps to Reproduce

1. Create RichTextBlock.
2. Add some bold text and add space(make sure that bold mode is on)
3. turn off the bold mode and add normal text.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

- None, this can be reproduce on any project.

**Comment by gasman** [comment]
Closing due to lack of information.
