### ISSUE TITLE
Wagtail userbar displays incorrect font

### ISSUE THREAD

**Issue by nicklee** [wagtail/wagtail#9290]
### Issue Summary

The latest version of wagtail has introduced a bug with the userbar (the button that displays on the front-end of your website when you're logged in) where the incorrect font is outputted. 

It seems to reference a css custom property (`--w-font-sans`) that doesn't exist, so the browser reverts to the default of `font-family: serif`

### Steps to Reproduce

1. Login to your instance of /admin
2. Visit a page on the front-end
3. Click the floating wagtail (bottom right)

### Technical details

-   Wagtail version: Wagtail v.4.0.2
-   Browser version: FF 105.0.2 

Screenshot of the issue:
![image (1)](https://user-images.githubusercontent.com/298766/194352125-1ae658b2-f531-4f99-ae9a-be590f4567ea.png)

Screenshot of previous versions of wagtail:
![image (2)](https://user-images.githubusercontent.com/298766/194352148-5c12b094-e2fa-4855-ac7a-fc0338540287.png)

**Comment by fyunusa** [comment]
Hi, i've confirmed the issue persist. and i'm currently making a fix for it.
I'll be sending update soon

**Comment by julianavmgiusti** [comment]
Hi! I'm an Outreachy applicant and I'd like to be assigned to an issue please @thibaudcolas

**Comment by yokwejuste** [comment]
hi @nicklee I would like to work on this issue!

**Comment by PreciousOritsedere** [comment]
Hi I'm an outreachy intern, can I work on this issue?

**Comment by lb-** [comment]
Hi @julianavmgiusti @yokwejuste & @PreciousOritsedere 

Please read the above comment - https://github.com/wagtail/wagtail/issues/9290#issuecomment-1273775612

This is already being worked on, I know it's a bit tricky to find things to pick up sometimes but I encourage you to always read the entire issue and comments before seeing if something is 'ready' to be worked on. 

Thanks for your interest in this but let's give @fyunusa some time to progress on their planned fix.

**Comment by fyunusa** [comment]
> Hi @julianavmgiusti @yokwejuste & @PreciousOritsedere
> 
> Please read the above comment - [#9290 (comment)](https://github.com/wagtail/wagtail/issues/9290#issuecomment-1273775612)
> 
> This is already being worked on, I know it's a bit tricky to find things to pick up sometimes but I encourage you to always read the entire issue and comments before seeing if something is 'ready' to be worked on.
> 
> Thanks for your interest in this but let's give @fyunusa some time to progress on their planned fix.

Yes give me more time, i hope to send in a pull request soon

**Comment by yokwejuste** [comment]
Thanks @lb-
