### ISSUE TITLE
Add a copy button to code snippets 

### ISSUE THREAD

**Issue by mohammadareeb95** [wagtail/wagtail#9296]
### Describe the solution you'd like

As a new contributor to the Wagtail ecosystem, I think it would be good to have a [copy button](https://www.w3schools.com/howto/howto_js_copy_clipboard.asp) to the code snippets in the [Getting Started](https://docs.wagtail.org/en/stable/getting_started/tutorial.html) guide. 

### Screenshot
![image](https://user-images.githubusercontent.com/77102111/194763011-714489f8-ce17-43ad-8e60-6b0736135fb1.png)

**Comment by mohammadareeb95** [comment]
If agreed, I would like to work on this issue.

**Comment by Adinapunyo-Banerjee** [comment]
I think this would be pretty helpful

**Comment by Scotchester** [comment]
I agree that this would be helpful! One thing that should be considered when implementing this: we should make sure that the copied text does not include shell prompt indicators (like the `>` and `$` characters in the snipped in the screenshot), and it should only copy one command at a time, so either each line should get its own copy button, or if that's not possible, snippets with multiple lines should be broken into two snippets.

**Comment by mohammadareeb95** [comment]
Sure thing @Scotchester! I'm an Outreachy applicant, can I consider it as my first issue?

**Comment by Scotchester** [comment]
@mohammadareeb95 Yes, go for it!

**Comment by mohammadareeb95** [comment]
Hey! I'm not actually sure on `where` to add this button.
Can anyone guide me please? @tbrlpld @thibaudcolas

**Comment by zerolab** [comment]
https://github.com/wagtail/sphinx_wagtail_theme would be the best place to add this functionality in

**Comment by lb-** [comment]
I think we should close this in favour of the existing issue in the Wagtail theme repo. 

https://github.com/wagtail/sphinx_wagtail_theme/issues/45

Anyone is free to look at and prepare a PR for issues on that repo also.

**Comment by tomdyson** [comment]
This has now been addressed - see https://github.com/wagtail/sphinx_wagtail_theme/issues/45

Thanks @mohammadareeb95!
