### ISSUE TITLE
formbuilde date field type

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#9309]
### Issue Summary
Formbuilder field types should reflect choices. Example date fieldtype

### Steps to Reproduce
Create form with form builder and make field date.

_(ps. there is no placeholder field in formbuilder)_

### Technical details
-   Wagtail version: 4

**Comment by gasman** [comment]
There's not enough detail here to understand what you mean, sorry. Please open a new issue detailing some exact steps to take, and describing what currently happens, and what you'd like to happen instead.
