### ISSUE TITLE
Document chooser action buttons do not show for Custom Document in Wagtail admin

### ISSUE THREAD

**Issue by aliceni81** [wagtail/wagtail#9310]
When I create a custom document and define it as a field in HomePage, the document chooser action buttons do not show even when the mouse is over on that. But the action buttons show if I use native Wagtail document.
![image](https://user-images.githubusercontent.com/81170508/195102219-82520fa3-8706-46d8-be3e-40020cbf0be5.png)

django version: 4.1.2
wagtail version: 4.0.2
python: 3.10

**Comment by zerolab** [comment]
This a duplicate of #9260, scheduled for 4.0.3
cc @thibaudcolas
