### ISSUE TITLE
Lightmode flashes between links when on Darkmode

### ISSUE THREAD

**Issue by Yekasumah** [wagtail/wagtail#9328]
In the documentation site, when moving from one section to another, there's a flash of the light mode which is disrupting to the eye. Happens when in Dark mode.

### Steps to Reproduce

1. Open the Documentation site https://docs.wagtail.org/en/stable/contributing/developing.html
2. Switch to dark mode
3. Navigate to another section of the doc.

Do look into it and see if you're able to reproduce it.
i'd like to work on it, if its been confirmed.

**Comment by lb-** [comment]
Thanks for flagging, however, this is already covered via the sphinx wagtail theme repo.

https://github.com/wagtail/sphinx_wagtail_theme/issues/213
with a PR up for a fix https://github.com/wagtail/sphinx_wagtail_theme/pull/217

Just awaiting review from other core team member on that repo.
