### ISSUE TITLE
Documentation guidelines for code snippets are missing "rendered output"

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9331]
Follow-up to #9321. In our documentation guidelines for code snippets, we’re missing the "rendered output" blocks which we have for other sections.

### Pertinent section of the Wagtail docs

https://github.com/wagtail/wagtail/blob/main/docs/contributing/documentation_guidelines.md#code-blocks

### Details

We’d need to add two "rendered output" blocks, one for the main "Code blocks" section and one for "When using console (terminal) code blocks".

I think they should look something like this. First one:

    <details>

    <summary>Rendered output</summary>

    ```python
    INSTALLED_APPS = [
        ...
        "wagtail",
        ...
    ]
    ```

    </details>

And second one:

    <details>

    <summary>Rendered output</summary>

    `sh`:

    ```sh
    # some comment
    some command
    ```

    `doscon`:

    ```doscon
    # some comment
    some command
    ```

    </details>

**Comment by thibaudcolas** [comment]
Tagging this as good first issue because it’s a newcomer-friendly task. For Outreachy participants, please only consider working on this if you’re interested in contributing to the **User guide / User documentation** project.

**Comment by mruqqie** [comment]
Hello @thibaudcolas, I would like to work on this issue. Could you assign it to me?

**Comment by thibaudcolas** [comment]
@mruqqie 👋go for it! No need to ask, you can just get going as long as you let people know in a comment.

**Comment by mruqqie** [comment]
@thibaudcolas Thank you!

**Comment by Dev-Liz** [comment]
Can more than one person work on it? @thibaudcolas
