### ISSUE TITLE
Add ability to customise userbar items via a hook or similar

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9334]
### Is your proposal related to a problem?

At the moment there is no simple way to modify what buttons appear in the userbar (the Wagtail bird button that gets added to front facing sites).

This would be very useful for cases where we could add custom debug tooling or hide some buttons we don't want to make available to the user for certain pages.

### Describe the solution you'd like

The simplest solution would be to provide a Wagtail hook `construct_userbar_menu` that mimics the existing `construct_main_menu`. 

https://docs.wagtail.org/en/stable/reference/hooks.html#construct-main-menu

This would get called with the resolved userbar menu items and then they can be modified accordingly. It should also get the request context at a minimum and maybe the current Page instance.

It would be nice if we could also call this hook even if we are not currently showing the userbar (when not signed in) with just an empty list. This way developers could add the userbar based on some other request data (e.g. scoped IP address range or for known preview only environments).

### Describe alternatives you've considered

- JS html injection could do this but it requires JS knowledge and is fragile
- Could copy & paste the template tag or somehow register your own that calls the Wagtail one and changes the resulting HTML
- Monkey patching could possibly work for some changes 

### Additional context

- Looks like this was attempted in 2019 - https://github.com/wagtail/wagtail/pull/5675
- Related issue for passing context into this template tag - https://github.com/wagtail/wagtail/issues/3847
- The planned accessibility checker could leverage this hook if implemented as a contrib module or external package. https://github.com/wagtail/wagtail/discussions/9262 (or it would make it easy to remove this if developers do not want this for some pages)
- Opens up an opportunity for third party packages to add behaviour to this userbar.

**Comment by vicky1312** [comment]
@lb- I would love to take this up.

**Comment by lb-** [comment]
Sorry I must have completely missed this. 

https://docs.wagtail.org/en/stable/reference/hooks.html#construct-wagtail-userbar

Closing issue.

**Comment by hazho** [comment]
Can this be done by the admins? 
(i.e., a hovered menu above/beside each of the admin menu items prompting the admins to include that item in user bar)
and store the configured data into the local storage of the browser
(I have mentioned this in the discussion as well https://github.com/wagtail/wagtail/discussions/9302 )
