### ISSUE TITLE
Update screenshot in getting started tutorial

### ISSUE THREAD

**Issue by Julietadeboye** [wagtail/wagtail#9341]
### Pertinent section of the Wagtail docs

[Section](https://docs.wagtail.org/en/stable/getting_started/tutorial.html?_ga=2.209345426.1239746541.1651239819-1126786067.1648068945#a-basic-blog)

### Details

The screenshot, as seen attached is a bit misleading. To create a blog post as a child of the index page, the add child page selected should be the one attached to the Blog Index page as opposed to the home page as shown int the screenshot.

A pull request for this will be submitted shortly.

![Screenshot (422)](https://user-images.githubusercontent.com/62646559/195593893-cd18dadf-106e-469f-a5ba-4956cb77be16.png)

**Comment by gasman** [comment]
Thanks for the report @Julietadeboye! This has already been handled by @activus-d in #9303, and the fix will be visible in the next version of the docs.

**Comment by Julietadeboye** [comment]
Alright, thanks @gasman
