### ISSUE TITLE
Changes to some instructions in the tutorial.md file

### ISSUE THREAD

**Issue by DokuaAsiedu** [wagtail/wagtail#9343]
Link to pull request with suggested changes: #9329

**Comment by bolarinwa-ajayi1** [comment]
Hi, I'm outreachy applicant, i will be working on this issue.

**Comment by DokuaAsiedu** [comment]
> Hi, I'm outreachy applicant, i will be working on this issue.

Hello, I already made a pull request suggesting some changes so you can look through more of the documentation and check for more issues to fix.

**Comment by bolarinwa-ajayi1** [comment]
noted, thanks

**Comment by DokuaAsiedu** [comment]
Welcome, have you been through the contributor checklist for documentation?

**Comment by DokuaAsiedu** [comment]
> noted, thanks

Welcome, have you been through the contributor checklist for documentation?

**Comment by bolarinwa-ajayi1** [comment]
yes, i launched to get started with wagtail tutorial

**Comment by thibaudcolas** [comment]
@DokuaAsiedu when opening an issue, make sure to describe a specific problem / feature request / change you think is needed. Just opening an issue to link to a pull request only creates noise for people who triage Wagtail’s issues.

**Comment by DokuaAsiedu** [comment]
> @DokuaAsiedu when opening an issue, make sure to describe a specific problem / feature request / change you think is needed. Just opening an issue to link to a pull request only creates noise for people who triage Wagtail’s issues.

Alright sorry about that
