### ISSUE TITLE
Login / forgot password forms need a border in Windows high contrast mode

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9350]
## Template

⚠ This issue is specific to Windows High contrast mode / Contrast themes. To troubleshoot this, you will need to [simulate forced-colors mode](https://developer.chrome.com/blog/new-in-devtools-98/#forced-colors) in browser DevTools.

This is tagged as a [**good first issue**](https://github.com/wagtail/wagtail/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) – if you want to take it on, please leave a comment below to say so, no need to ask for permission, first come first serve! State your intent and share any questions / plans you have on how to approach the task.

### Issue Summary

We introduced new login form designs in Wagtail 4.0. They rely on a white background over a colored background. The distinction isn’t visible in Windows high contrast mode, where the background colors are all overridden.

Comparison screenshot:

<img width="307" alt="b Login form forced-colors 2" src="https://user-images.githubusercontent.com/877585/195652796-c8148210-608a-4d8e-a4a3-29b5f11b3314.png">

### Steps to Reproduce

1. Enable forced colors emulation in your browser
2. Go to Wagtail’s login screen

### Proposed solution

We should add a border around the form so the two areas can be distinguished / so it looks better. Here is the code where I believe this needs to happen: https://github.com/wagtail/wagtail/blob/main/client/scss/layouts/_login.scss#L21

The border to add would be something like:

```css
@media (forced-colors: active) {
    border: 5px solid transparent;
}
```

**Comment by Lovelyfin00** [comment]
I would love to work on this

**Comment by thibaudcolas** [comment]
@Lovelyfin00 only one issue at a time please!

**Comment by Lovelyfin00** [comment]
I'll work on this then @thibaudcolas

**Comment by Lovelyfin00** [comment]
@thibaudcolas 
Created a PR for this at #9354

**Comment by 4the4ryushin** [comment]
i have a pr ready for this ? can i make the request?

**Comment by 4the4ryushin** [comment]
use of inline would be better approach

**Comment by 4the4ryushin** [comment]
ohh , sure i would recommend you to use inline there
