### ISSUE TITLE
Wagtail version number in admin has an extra dot

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9352]
This is tagged as a [**good first issue**](https://github.com/wagtail/wagtail/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) – if you want to take it on, please leave a comment below to say so, no need to ask for permission, first come first serve! State your intent and share any questions / plans you have on how to approach the task.

### Issue Summary

In the Settings menu, we display Wagtail’s version number at the bottom:

<img width="409" alt="dot-menu" src="https://user-images.githubusercontent.com/877585/195653500-98c8c982-f39f-4f24-a8df-3ebbc7401af1.png">

This has been there for a while and I don’t think there is a specific reason for it. It’d be nice to display the version numbers the same as what we do in the docs.

So rather than `v.2.16.1` – `v2.16.1`.

### Steps to Reproduce

1. Open the Wagtail admin
2. Open the Settings menu and look at the bottom

### Technical details

-   Wagtail version: tested in v.2.16.1

### Proposed solution

I believe this could be as simple as removing the "." here: https://github.com/wagtail/wagtail/blob/main/wagtail/admin/wagtail_hooks.py#L105

```diff
-footer_text="Wagtail v." + __version__,
+footer_text="Wagtail v" + __version__,
```

We’d need to test that this doesn’t affect our other code relying on version numbers.

**Comment by vicky1312** [comment]
I would love to work on this @thibaudcolas

**Comment by Lovelyfin00** [comment]
I would love to work on this

**Comment by vicky1312** [comment]
@Lovelyfin00 please work on it, I have trouble pushing my code

**Comment by Lovelyfin00** [comment]
Alright
I'll work on it today
Thanks

**Comment by Lovelyfin00** [comment]
Hi @thibaudcolas 
Any resources on testing against the different versions of wagtail?

**Comment by lb-** [comment]
Confirmed this issue
