### ISSUE TITLE
Opening edit page view with preview-panel closed results in 3 preview requests

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9360]
### Issue Summary

Currently, if you open a page for editing (so the side panel is closed), this results in 3 preview requests (beside other xhr requests related to the preview) in the background! I've expected 0 preview requests ;)
I think those requests should only be executed, when the preview panel is opened by the user.

![wagtail_preview_requests](https://user-images.githubusercontent.com/468164/195858560-3d0a8ff6-c4d9-401f-bb7c-c0a8377bc04c.png)

On one of our website, which has many active editors, this leads to many, I think unnecessary requests, because often those people don't use the preview at all.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. `./manage.py makemigrations && ./manage.py migrate && ./manage.py createsuperuser && ./manage.py runserver`
3. Login to the CMS
4. Create a new draft page (you can publish it and open the edit page again, same result)
5. Find the request orgy in your dev tools

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10
-   Django version: 3.2, 4.1
-   Wagtail version: 4.0.2
-   Browser version: Firefox 105

**Comment by AnishaSingh0118** [comment]
I would Like to take up this issue.

**Comment by AnishaSingh0118** [comment]
> @AnishaSingh0118 go for it. Please ensure you understand and can reproduce the issue first. Maybe follow the steps and take a screenshot - this way we can remove the unconfirmed label.

Yes, Thank you for your response :)

**Comment by sdmoran** [comment]
Hi @AnishaSingh0118, are you still working on this? I'm interested in taking a look if not

**Comment by AnishaSingh0118** [comment]
> Hi @AnishaSingh0118, are you still working on this? I'm interested in taking a look if not

Actually I have been stuck at the set up part. After following the documentation it is saying that wagtail command not found, did you faced it too?
