### ISSUE TITLE
No horizontal scroll bar in header section of admin pages 

### ISSUE THREAD

**Issue by vicky1312** [wagtail/wagtail#9368]
### Issue Summary

<!-- On opening pages in wagtail admin, the horizontal scrollbar doesn't show if the pages are too much to fit. The edit page, on the other hand, shows a scroll bar.

### Steps to Reproduce

1. Open wagtail admin
2. Head to pages and choose multiple pages
3. Look for a horizontal scroll bar

The pages cut off in the absence of the scroll bar.
-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: 

- I have opened the site on both chrome and firefox to test if the problem persists across different web browsers 

https://user-images.githubusercontent.com/63854917/195962221-3127b1ab-5008-411f-aca3-fc327e66f638.mp4

**Comment by vicky1312** [comment]
### Issue Summary
The horizontal scroll bar does not appear in the header section of the wagtail admin pages.
### Steps to Reproduce

1. Open wagtail admin
2. Navigate to pages
3. Open multiple pages

A horizontal scroll bar should appear if the pages are to0 large to fit the space, but it doesn't. The scroll bar, however, appears when editing.
-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project
I have opened the site on both Chrome and Firefox to confirm that the issue persists across different browsers

https://user-images.githubusercontent.com/63854917/195962337-f688d2ab-f9da-4384-bf78-3edbc27690e6.mp4

**Comment by vicky1312** [comment]
https://user-images.githubusercontent.com/63854917/195962985-a98752f1-d4e7-4e51-9624-7482728865e1.mp4

Tested on firefox

**Comment by zerolab** [comment]
Thank you @vicky1312.
This looks like the confirmation of #9218. Would be great to have the details on that ticket as requested by @lb- in https://github.com/wagtail/wagtail/issues/9218#issuecomment-1275520125, so that we do not duplicate issues.

**Comment by vicky1312** [comment]
@zerolab Okay, I've just done that. I'm guessing I should close this issue now?
