### ISSUE TITLE
Wrong translation – Dutch

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#9378]
### Issue Summary
Not realy an issue but a wrong translation.

### Steps to Reproduce
Create a Wagtail site and add these lines to settings.py

LANGUAGE_CODE = 'nl'
LANGUAGES = WAGTAILADMIN_PERMITTED_LANGUAGES = [('nl', _('Dutch')),]

Create a ModelAdmin
Add a filter using admin.SimpleListFilter

In the admin interface the caption above the filter starts with "Door" which schould be "Op".  

Location:
wagtail/contrib/modeladmin/locale/nl/LC_MESSAGES/django.po

Change from:
msgid "By %(filter_title)s"
msgstr "Door %(filter_title)s"

To:
msgid "By %(filter_title)s"
msgstr "Op %(filter_title)s"

### Technical details
-   Python 3.7.9
-   Django version: Version: 3.2.15
-   Wagtail version: 4.0.2
-   Browser version: N.A

**Comment by gasman** [comment]
Hi @robslotboom - thanks for the report.

For future reference, you can make fixes to translations yourself through [Transifex](https://explore.transifex.com/torchbox/wagtail/) - I've updated this one now.

**Comment by robslotboom** [comment]
Hi matt,

Thanks, I’ll have a look at Transifex.

**Comment by gasman** [comment]
The list of apps in Transifex is a flat list, so there's no separate 'contrib' section - the contrib apps appear alongside the core ones as "wagtailmodeladmin", "wagtailredirects" and so on.

**Comment by robslotboom** [comment]
Clear, thanks Matt
