### ISSUE TITLE
Add branch naming convention on issue_tracking.md section 

### ISSUE THREAD

**Issue by banjo-tech** [wagtail/wagtail#9380]
To promote better communication among the developers, the issue tracking section needs a branch name system.
Before creating a pull request, the developers should be familiar with this naming convention.

### Issue_tracking.md

  https://docs.wagtail.org/en/stable/contributing/issue_tracking.html

### Details

(Write your answer here.)

**Comment by banjo-tech** [comment]
I would like to work on this

**Comment by lb-** [comment]
Sorry. Just saw the PR for this. 

I'm not sure this is actually really necessary - the branches that get created for PRs do not actually effect anything in the final code. The commit message does, but when merging a core member will usually clean this up if needed. 

If you're referring to the blog post that talks about branch naming - https://wagtail.org/blog/ten-tasty-ingredients-for-a-delicious-pull-request/ - that is more about individual developers managing their own PRs/branches on their machine or clone. Less about it being a requirement for contributing to Wagtail. 

Nothing's wrong with `patch-1` as a branch name, but if you do everything on you own clone of `main` if will work but be frustrating. I also don't anticipate may developers sticking to a naming convention unless it really made a difference. Plus this may be an unnecessary barrier to entry for new contributors. 

Maybe can you expand a bit more on what kind of problem this documentation is aiming to solve with some examples.

It's really great that you have this suggestion for improvement - we just want to help understand why this is needed or if maybe the ad-hoc approach is good enough.

**Comment by banjo-tech** [comment]
Thank you for the feedback @lb- While this explanation makes perfect sense I had initially thought that having a branch naming convention would make it easier to locate a branch but since it could hinder peoples ability to contribute I would agree that the issue be closed

**Comment by lb-** [comment]
No problems. There's a lot to take in - really appreciate the initiative on this.
