### ISSUE TITLE
Comment dropdown overlaying on the collapse all button

### ISSUE THREAD

**Issue by xomcodes** [wagtail/wagtail#9387]
### Issue Summary
When I created a new page and tried viewing the comment, I noticed the comment dropdown overlaying on the collapse all button. I checked for all screen sizes and the issue still persisted.

### Steps to Reproduce

1. Open the Wagtail bakery live
2. Login into the admin panel
3. Create a post
4. On the edit page, click on the comment icon, the dropdown is overlaying on the collapse all button.

![wagtail_issh](https://user-images.githubusercontent.com/82041329/196145514-661f5a99-db61-493f-a8bc-bcf75ec90005.PNG)

### Proposed Fix
1. This issue can be fixed by adding margin-top: 3rem

![wagtail_resolve](https://user-images.githubusercontent.com/82041329/196146355-979e0778-60dd-4ce9-8eb9-739e2014878c.PNG)

### Technical details

-   Python version: Run `python --version`.
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

**Comment by thibaudcolas** [comment]
Thanks @xomcodes! This will be fixed in #9345.

**Comment by thibaudcolas** [comment]
Fixed via #9345.

**Comment by xomcodes** [comment]
Okay. Thanks for the feedback.
