### ISSUE TITLE
Grammatical adjustments for `Writing templates` usage guide not addressed in PR #9395,

### ISSUE THREAD

**Issue by activus-d** [wagtail/wagtail#9400]
## Issue Summary
Grammatical adjustments, which were not addressed in PR #9395, are needed on the [Writing Templates](https://github.com/wagtail/wagtail/blob/main/docs/topics/writing_templates.md#writing-templates) section of the Usage guide, which were not addressed in [issue #9395](https://github.com/wagtail/wagtail/pull/9403) to enhance readability

**Comment by activus-d** [comment]
I'm working on this already.

**Comment by thibaudcolas** [comment]
@activus-d if all you’re changing is grammar then there is no need to open a new issue. Grammar problems are apparent from the pull request alone.
