### ISSUE TITLE
Wagtail icon on login page doesn't show well on windows high contrast forced mode dark

### ISSUE THREAD

**Issue by Lovelyfin00** [wagtail/wagtail#9428]
### Issue Summary

Wagtail svg icon on the login page doesn't show well on high contrast mode but it's alright on light mode and without forced mode

### Steps to Reproduce

1. Open wagtail bakery demo
2. Access the admin login page
3.  Switch to css forced mode dark

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The svg icon is supposed to have the appropriate color regardless of the mode the login page is accessed.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no) yes

-   Browser version: Chrome  Version 106.0.5249.119 (Official Build) 

On light mode

![image](https://user-images.githubusercontent.com/38161296/196691288-ab18d0c0-8246-47b9-b9da-14ec034f0652.png)

On dark mode

![image](https://user-images.githubusercontent.com/38161296/196691393-dbd9005b-c4da-4bbc-9471-a30655483054.png)

Without forced colors

![image](https://user-images.githubusercontent.com/38161296/196691465-d09424ec-e653-4e4d-bd20-eba32ac9e9f5.png)

**Comment by lb-** [comment]
@Lovelyfin00  what are you you thinking for this solution?

Ideally we should avoid adding two variants of the image, maybe css filter invert could be useful here ? https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/invert

**Comment by Lovelyfin00** [comment]
Hi @lb- 
The filter method worked. I specified that on prefered-colors dark that the image filter should be inverted at 100% and it works fine. I'll created a PR now for this with the necessary screenshots
