### ISSUE TITLE
Scheduled publishing overlay only opens on settings tab with custom settings_panels (4.1rc1)

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9452]
### Issue Summary

In the (new) default wagtail setup the settings tab is not visible, but the `settings_panels` are still used for the `CommentPanel` and the `PublishingPanel`.
If you add custom panels to the `settings_panels`, which is a very common thing, the settings tab gets visible, but then, the schedule overlay (when clicking on "Set schedule" in the sidebar) only gets visible, when you navigate to the settings tab.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit the `home/models.py`:
```python
from django.db import models
from wagtail.admin.panels import FieldPanel
from wagtail.models import Page

class HomePage(Page):
    subtitle = models.CharField(
        max_length=255,
        blank=True,
    )

    settings_panels = Page.settings_panels + [
        FieldPanel("subtitle"),
    ]
```
3. `./manage.py makemigrations && ./manage.py migrate && ./manage.py createsuperuser && ./manage.py runserver`
4. Login to the CMS and edit the home page
5. On any other tab then the settings tab, try to open the schedule overlay. Only when you navigate to the settings tab, you will see it...

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10
-   Django version: 4.1
-   Wagtail version: 4.1rc1
-   Browser version: Firefox 105

**Comment by Yekasumah** [comment]
Hi, I would like to work on this issue. Following the steps to reproduce as described.

**Comment by Headon1729** [comment]
Hey @Yekasumah 
Are you still working on this issue ?

**Comment by laymonage** [comment]
Thanks for the report! I managed to replicate the issue and found the cause.

When there are fields in the Settings tab that are visible in the page editor furniture (`show_panel_furniture()` returns `True`), we render all panels in `settings_panels` inside the tab. Unfortunately, when viewing a different tab, other tabs have a `hidden` attribute set, which effectively hides all descendant elements of the tab content.

I fixed this by targeting the editor form as the root for the dialog element in #9518.

Also, sorry @Yekasumah and @Headon1729, I haven't seen any of you confirming this issue, and considering that this is a release blocker for 4.1 (with a deadline coming in the near future), I decided to go ahead with this one. Thanks for the interest, I hope you can find other issues to work on!
