### ISSUE TITLE
Stackoverflow post claiming our register_account_settings_panel docs are wrong

### ISSUE THREAD

**Issue by cnk** [wagtail/wagtail#9453]
In this [stackoverflow post](https://stackoverflow.com/a/74157215/52325), the user reports that putting [this example code](https://docs.wagtail.org/en/latest/extending/custom_account_settings.html) in `hooks.py` does not work but moving it to `wagtail_hooks.py` makes it work. 

Can someone please verify that the code only works if placed in wagtail_hooks.py? If that is correct, please submit a PR to update the documentation changing `hooks.py` to `wagtail_hooks.py` in the example filenames.

**Comment by RealOrangeOne** [comment]
`wagtail_hooks.py` is definitely the correct name: https://github.com/wagtail/wagtail/blob/b356fe683f49c37b9ba8838747602a5c5ecc892b/wagtail/hooks.py#L106

**Comment by MaryAyobami** [comment]
@cnk  I'd love to work on this

**Comment by PreciousArinda** [comment]
@cnk I've fixed it in #9462.

**Comment by lb-** [comment]
@PreciousArinda thanks for the PR, it solvea the problem, but please ensure you read comments before picking things up though. 

@MaryAyobami had already commented about 9 hours before you.

All good for now but let's try to respect other users who may have already started working on something.

**Comment by PreciousArinda** [comment]
@MaryAyobami @lb- I acknowledge my mistake and regret any inconvenience caused. I commit to do better next time.
