### ISSUE TITLE
Potential data loss when upgrading sub-classes of BaseLogEntry (Wagtail 2.16 -> Wagtail 3.0)

### ISSUE THREAD

**Issue by dkirkham** [wagtail/wagtail#9459]
### BaseLogEntry
https://docs.wagtail.org/en/stable/reference/pages/model_reference.html#baselogentry

### Wagtail 3.0 Upgrade Considerations - Replaced data_json TextField with data JSONField in BaseLogEntry
https://docs.wagtail.org/en/stable/releases/3.0.html#replaced-data-json-textfield-with-data-jsonfield-in-baselogentry

### Details
These entries document that these fields have changed from `data_json` (a `TextField`) to `data` (a `JSONField`).

However, if (like me) you have a sub-class of `BaseLogEntry`, the automatically generated migration will result in loss of the log data, because it generates the following migration operations:

```
    operations = [
        migrations.RemoveField(
            model_name='objectdatalogentry',
            name='data_json',
        ),
        migrations.AddField(
            model_name='objectdatalogentry',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
```

Note: this migration was automatically generated by Django 4.0.8, while upgrading from Wagtail 2.16.3 to 3.0.3. I haven't tested with other Django versions.

Similar migrations in the Wagtail core code, have migration operations like this:

eg. https://github.com/wagtail/wagtail/blob/main/wagtail/migrations/0069_log_entry_jsonfield.py#L12

```
    operations = [
        migrations.AlterField(
            model_name="modellogentry",
            name="data_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RenameField(
            model_name="modellogentry",
            old_name="data_json",
            new_name="data",
        ),
```

There is a warning against the `BaseLogEntry` documentation about the change in the field, but I think it would be helpful to have an additional warning suggesting the migration be carefully scrutinised, and potentially replaced with something like the example above. A similar warning in the Upgrade Considerations section pointing to this would also be useful - especially for those who are considering upgrading from 2.15 LTS to the imminent 4.1 LTS release.

I've raised this as a documentation issue, because I doubt there is anything that can be done within the Wagtail code base (or Django for that matter) to solve this problem.

**Comment by Dev-Liz** [comment]
I'd love to work on this

**Comment by Dev-Liz** [comment]
@thibaudcolas any comment on this before I proceed, please??

**Comment by Headon1729** [comment]
Hey @Dev-Liz 
If you are working on this issue, I would love to work on it

**Comment by Dev-Liz** [comment]
Hello @Headon1729, I think I need more explanations to get started with it.
Please go ahead and fix it if you understand it better. :)

**Comment by jacobtoppm** [comment]
I think that's a good call. @laymonage would you be happy to add this?

**Comment by laymonage** [comment]
Thanks for the report! PR: #9640 

I assume the same could also happen with subclasses of `AbstractFormSubmission` and `PageRevision`. I added the same callout for `AbstractFormSubmission`, but I didn't bother with `PageRevision` as I don't see why people would subclass that model (and we renamed it to `Revision` in 4.0 anyway).
