### ISSUE TITLE
HelpPanels not Collapsible

### ISSUE THREAD

**Issue by dkirkham** [wagtail/wagtail#9467]
### Help Panels are not collapsible, doco says "all panels" are.

[HelpPanels](https://docs.wagtail.org/en/stable/reference/pages/panels.html#helppanel) are not collapsible, despite the [doco](https://docs.wagtail.org/en/stable/reference/pages/panels.html#collapsible) saying that "All panels are now collapsible by default.".

This is somewhere between a bug and a feature request; filed as a bug since the behaviour contradicts the documentation.
Even if not considered a bug, the feature appears desirable.

### Steps to Reproduce

1. Start a fresh bakery demo and confirm it is working
2. Edit bakerydemo/base/models.py as follows...

Add a `HelpPanel` import near the top:
```
from wagtail.admin.panels import (
    FieldPanel,
    FieldRowPanel,
    InlinePanel,
    MultiFieldPanel,
    PublishingPanel,
    HelpPanel,
)
```

And near line 187, add a `HelpPanel` into the `content_panels`:
```
    content_panels = Page.content_panels + [
        HelpPanel("This may be a <b>long</b> complicated bit of help text"),
        FieldPanel("introduction", classname="full"),
        FieldPanel("body"),
        FieldPanel("image"),
    ]
```

3. Restart Wagtail and add or edit a StandardPage via the Admin page
4. Observe the lack of a caret next to the HelpPanel text.

<img width="432" alt="Screen Shot 2022-10-23 at 16 09 01" src="https://user-images.githubusercontent.com/1977376/197375000-281a4cc7-b677-4c16-b80e-8d56bc33e038.png">

Instead, there should be a caret and the panel should be collapsible by pressing that caret.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (**yes**)

### Technical details

-   Python version: 3.9, but probably irrelevant
-   Django version: 4.0.8, but probably irrelevant
-   Wagtail version: 4.0.4, probably any of the 4.0 releases, also 4.1rc1
-   Browser version: Mac Firefox, but probably irrelevant

**Comment by mohammadareeb95** [comment]
I'd like to work on this

**Comment by dkirkham** [comment]
Hi @mohammadareeb95, it might be worth seeing if you can replicate the issue. But I'd wait for someone from the Wagtail core team to decide if a design decision is required or not.

**Comment by mohammadareeb95** [comment]
@dkirkham okay, that makes sense!

**Comment by thibaudcolas** [comment]
Thank you for the report @dkirkham. HelpPanel doesn’t support collapsing, never has, the documentation should state "All panels that support collapsing are now collapsible by default." (or equivalent).

All of the panels that are collapsible by default require a heading so there is appropriate text to convey the location and nature of the panel when collapsed. How would you expect this to work for HelpPanel? Would we make its `heading` required?

When you say this appears desirable – can you state more about the use case for this? I’m not clear on why hiding help text independently of the parts of the form it’s for would be desirable.

**Comment by dkirkham** [comment]
Hi @thibaudcolas, yes, I thought the subject of a suitable heading to collapse to would come up.

The use case I had was where there is a fairly extensive set of instructions at the top of the editor page - say 8+ lines - which contextualises all the fields in the page (or other model), particularly for new editors or as a quick reference for the more experienced editors. It would be nice (but certainly not a show-stopper) to be able to collapse that help text so that the fields become visible.

@cnk also expressed interest in this (on [Slack](https://wagtailcms.slack.com/archives/C81FGJR2S/p1666484788184119)), and may be able to add her view.

**Comment by lb-** [comment]
@dkirkham - what if you wrap your long help panel/s within a MultiFieldPanel? Pretty sure they can collapse.

**Comment by dkirkham** [comment]
Hmmm, good idea @lb-. The other option that occurred to me is to put the help panel onto a separate tab.

**Comment by dkirkham** [comment]
Confirming @lb- the `MultiFieldPanel` wrapping the `HelpPanel` works well to put the help at the top of the editor page:

```
    content_panels = Page.content_panels + [
        MultiFieldPanel(
            [
                HelpPanel("This may be a <b>long</b> complicated bit of help text"),
            ],
            heading="Page Help",
        ),
        FieldPanel("introduction", classname="full"),
        FieldPanel("body"),
        FieldPanel("image"),
    ]
```

<img width="455" alt="image" src="https://user-images.githubusercontent.com/1977376/197502621-43a89b28-0bd1-45f5-958c-0050a201628b.png">

**Comment by dkirkham** [comment]
@thibaudcolas, will close because the two workarounds appear quite adequate.
