### ISSUE TITLE
Add More Padding to the Admin User and Header Text in Admin Dashboard

### ISSUE THREAD

**Issue by Yekasumah** [wagtail/wagtail#9471]
This isn't necessarily a bug. I just think it would look better if there was a little more space right after the profile image section (header text - welcome to Wagtail CMS). 

### Steps to Reproduce

1. Start a new project with `wagtail start my project'
2. Log in to Admin Dashboard

The problem;

<img width="317" alt="Screenshot 2022-10-23 at 18 35 55" src="https://user-images.githubusercontent.com/105293813/197407268-e479377c-4a17-441e-b873-88ac3228e97d.png">

The solution;
<img width="222" alt="Screenshot 2022-10-23 at 18 35 29" src="https://user-images.githubusercontent.com/105293813/197407524-1c68e10a-0c31-4221-b142-ffd96a802829.png">

**Comment by lb-** [comment]
Thanks @Yekasumah but there is already an issue raised for the same kind of header design refinements.

https://github.com/wagtail/wagtail/issues/9034

And a PR in progress. 

https://github.com/wagtail/wagtail/pull/9188
