### ISSUE TITLE
Lock page button in the status side panel does not work on page listing

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9481]
### Issue Summary

The new status side panel (wagtail 3(?)/4) is also available on the page listing. Unfortunately the lock-button there does not work (change privacy works :heavy_check_mark: , the view-history-link works :heavy_check_mark: ), so clicking on it does nothing:
![wagtail_status_sidepanel_lock](https://user-images.githubusercontent.com/468164/197738214-081a0f7f-7cdd-4e9b-874d-5f924e189cfb.png)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. `./manage.py makemigrations && ./manage.py migrate && ./manage.py createsuperuser && ./manage.py runserver`
3. Login to the CMS and open the page listing of the home page (`/admin/pages/3/`)
4. Open the status side panel (:information_source:  icon) and click on "Lock"

On the edit-page (`/admin/pages/3/edit/`) it works.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10
-   Django version: 3.2, 4.1
-   Wagtail version: 4.0.4, 4.1rc1
-   Browser version: Firefox 106

**Comment by xomcodes** [comment]
@th3hamm0r can i work on this issue? I would reproduce and give you feedback.

**Comment by th3hamm0r** [comment]
@xomcodes Sorry, for my late reply. I've already found the issue: It looks like the relevant `LockUnlockAction` js is not called in the index view. I will make a PR for that.

**Comment by gasman** [comment]
Fixed in #9528
