### ISSUE TITLE
Pull out `escapeHtml` from core.js into utils/text.ts

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9492]
### Is your proposal related to a problem?

**`escapeHtml` should move from `core.js` to `utils/text.ts`**

Wagtail's JavaScript `core.js` is quite large and many items can be pulled out to shared utils or includes to help make the code more maintainable and supported with base unit tests.

Pulling some basic utils out lets us put these into TypeScript (type safety) but also document and unit test them better.

### Describe the solution you'd like

The function `escapeHtml` should be moved from
https://github.com/wagtail/wagtail/blob/aaea8710c21ba4d5368d3825781bc54e1869c561/client/src/entrypoints/admin/core.js#L18-L28

To the shared utils/text.ts file https://github.com/wagtail/wagtail/blob/main/client/src/utils/text.ts

From there it can be imported and set to the same global (`window.escapeHtml`) as per current state.

#### Requirements

* [ ] Move the function to the utils/text TypeScript file and set up correct types - https://www.typescriptlang.org/
* [ ] Add a [JSDOC](https://jsdoc.app/) description to the function
* [ ] Add a basic set of unit tests for this function in https://github.com/wagtail/wagtail/blob/main/client/src/utils/text.test.js (follow the current convention in that file with each util having its own `describe` block - using [Jest](https://jestjs.io/)
* [ ] Ensure the util is imported in core.js correctly so that `window.escapeHtml` and any other usage within that function still acts the same way.

### Additional context

* This has been created as part of the Outreachy program to help new contributors that are interested in the Stimulus project.

**Comment by IvyJeptoo** [comment]
i claim this issue

**Comment by Jordan-Rob** [comment]
Let me get started on this

**Comment by Jordan-Rob** [comment]
This Issue instructed me to transfer the `escapeHtml` function from core.js  to text.ts but there seems to be a similar function within `text.ts`  already refer to the screenshot below. I'm thinking of deleting the one in `core.js` and maintaining the one in `text.ts`

<img width="1470" alt="Screen Shot 2022-10-28 at 10 07 17 AM" src="https://user-images.githubusercontent.com/40763160/198824391-b8291133-779c-4985-ab3f-05d091efdde7.png">

**Comment by lb-** [comment]
Yeah I agree - it looks like these two functions do the exact same thing. Great find, there may already be unit tests for the existing utils `escapeHtml` also.
