### ISSUE TITLE
🎛️ Migrate `addMessage` from core.js to a Stimulus Controller `w-messages`

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9493]
> ℹ️ **Part of the [Stimulus  🎛️ RFC 78](https://github.com/wagtail/rfcs/pull/78)**

### Is your proposal related to a problem?

There is an ad-hoc JS implementation to dynamically add messages to a specific part of the UI (top page messages), this would be best done via a Stimulus controller and a more formal API.

The existing implementation of `addMessage`is in...
https://github.com/wagtail/wagtail/blob/aaea8710c21ba4d5368d3825781bc54e1869c561/client/src/entrypoints/admin/core.js#L4-L14

Wagtail's JavaScript `core.js` is quite large and many items can be pulled out to shared utils or includes to help make the code more maintainable and supported with unit tests and consistent implementations.

### Describe the solution you'd like

**`addMessage` should move from `core.js` and the functionality be provided as a Stimulus controller `client/src/controllers/MessagesController.ts`**

Currently the `addMessage` code appends a message to the shared template's message container in [`wagtail/admin/templates/wagtailadmin/base.html`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/base.html). This HTML container should be the controlled element and have an update similar to the following:

```html
            {# Always show messages div so it can be appended to by JS #}
            <div class="messages" role="status" data-controller="w-messages" data-action="w-messages:add@document->w-messages#add">
                <ul data-target="messages">
                    {% if messages %}
                        {% for message in messages %}
                            {% message_level_tag message as level_tag %}
                            <li class="{% message_tags message %}">
                                {% if level_tag == "error" %}
                                    {# There is no error icon, use warning icon instead #}
                                    {% icon name="warning" classname="messages-icon" %}
                                {% elif message.extra_tags == "lock" %}
                                    {% icon name="lock" classname="messages-icon" %}
                                {% elif message.extra_tags == "unlock" %}
                                    {% icon name="lock-open" classname="messages-icon" %}
                                {% else %}
                                    {% icon name=level_tag classname="messages-icon" %}
                                {% endif %}
                                {{ message|safe }}
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
                <template data-target="templates">
                    {% comment %} just an example - goal here is to ensure that the HTML rendered contains the icons and classes {% endcomment %}
                    <li class="error" data-message-status="error">{% icon name="warning" classname="messages-icon" %}<span></span></li>
                    <li class="warning" data-message-status="warning">{% icon name="warning" classname="messages-icon" %}<span></span></li>
                    <li class="success" data-message-status="success">{% icon name="success" classname="messages-icon" %}<span></span></li>
                    {% comment %} OTHER? {% endcomment %}
                    <li class="other">{% icon name="warning" classname="messages-icon" %}<span></span></li>
                </template>
            </div>
```

**Key notes**

* The controlled element has an action to listen to a custom event at the document (or any events that bubble up to the document)
* The `ul` is always rendered (different to current state) and is the messages target
* We need a way to ensure that appended messages have some kind of icon (if possible) and a way to inject the html message content.

**Controller implementation**

* Targets: `templates` & `messages`
* Methods: `add` - pulling in `status` & `text` from the event's detail in the method call
* Classes: `hasMessages` (for when a new message exists) and `show` (for the class that is to be added to the dynamically injected message after 100ms)

#### Requirements

* [ ] Move the function to the the new TypeScript controller file and set up correct types - https://www.typescriptlang.org/
* [ ] Add a [JSDOC](https://jsdoc.app/) description to the class with a description and `@example`
* [ ] Add a basic set of unit tests for this controller `client/src/controllers/MessagesController.test.js` file using [Jest](https://jestjs.io/) - look at client/src/includes/breadcrumbs.test.js for an example of mocking some HTML to then trigger some behaviour on that HTML
* [ ] Remove the `addMessage` global
* [ ] Update all usage of `addMessage` to be a [custom event](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent) dispatching similar to `document.dispatchEvent(new CustomEvent('w-messages:add', { status: 'success', text: 'Something'  }));`

### Additional context

* This is not a good first issue but should be enough detail for someone to pick up who has read the Stimulus docs and has had a read of some existing Stimulus controller implementations in Wagtail.

**Comment by IvyJeptoo** [comment]
working on it.

**Comment by AnishaSingh0118** [comment]
Can I work with .JS file because currently there are some complications with .ts file.

**Comment by AnishaSingh0118** [comment]
Hello @lb- I am trying to make the issues as one and has already came up with a solution in my PR https://github.com/wagtail/wagtail/pull/9614
This PR is fixing:
Pull out addMessage from core.js into includes/message.ts #9496 as well as #9493 as well.

I would love to hear from you.

**Comment by lb-** [comment]
@AnishaSingh0118 as per the other comment - https://github.com/wagtail/wagtail/issues/9496#issuecomment-1304702368

Another user @IvyJeptoo has already been assigned and indicated the are working on this.

**Comment by salty-ivy** [comment]
alright, got it.

**Comment by lb-** [comment]
@salty-ivy @IvyJeptoo @AnishaSingh0118  - I have reworked this issue to be the desired messages implementation as a Stimulus controller.

Anyone is free to pick this up but for now I will assume that this work has not been started as it's been a few months without comments or a PR. Anyone keen to do this - please re-read and then comment, it's ok if none of you are wanting to do this one at this time.

cc @Lovelyfin00  @thibaudcolas

**Comment by salty-ivy** [comment]
@lb-  would give it a try, would try to get this one done  faster and with more proficiency.

**Comment by lb-** [comment]
Thanks @salty-ivy - reach out if you need a hand.

**Comment by lb-** [comment]
@salty-ivy  as per your PR, the images upload (oddly, only images, not documents) page will clear any existing messages before adding new ones.

https://github.com/wagtail/wagtail/blob/main/wagtail/images/static_src/wagtailimages/js/add-multiple.js#L22

This approach was probably added to ensure that if you upload consecutive things, you do not get stacks of success messages.

However, this will unintentionally clear any messages added to that container from server side rendering.

As noted, this issue will need to add support for clearing any dynamically added messages, here is an idea for an approach.

* Add a new `target` - `item` (something generic, not `message`)
* In the template code, add the `data-w-messages-target="item"` to each potentially cloned message.
* Add a new method to the controller `clear` or `clean` which will do something like the following (below).
* Allow that clear method to be called, similar to `add` with a global event listener on the DOM.
* Finally, update the `add: function (e, data) {` to dispatch that event AND do the same in the documents upload, so that their behaviour is in sync (I do not see a reason why these should not have the same behaviour here).

```js
{
  clear() {
    this.itemTargets.forEach((item) => {
      item.remove();
    });
  }
}
```

**Comment by salty-ivy** [comment]
@lb- thanks for the update 
I knew it was js but didn't look out for it 😅, should have given a look before asking, sorry for the trouble.

**Comment by salty-ivy** [comment]
> @salty-ivy as per your PR, the images upload (oddly, only images, not documents) page will clear any existing messages before adding new ones.
> 
> https://github.com/wagtail/wagtail/blob/main/wagtail/images/static_src/wagtailimages/js/add-multiple.js#L22
> 
> This approach was probably added to ensure that if you upload consecutive things, you do not get stacks of success messages.
> 
> However, this will unintentionally clear any messages added to that container from server side rendering.
> 
> As noted, this issue will need to add support for clearing any dynamically added messages, here is an idea for an approach.
> 
>     * Add a new `target` - `item` (something generic, not `message`)
> 
>     * In the template code, add the `data-w-messages-target="item"` to each potentially cloned message.
> 
>     * Add a new method to the controller `clear` or `clean` which will do something like the following (below).
> 
>     * Allow that clear method to be called, similar to `add` with a global event listener on the DOM.
> 
>     * Finally, update the `add: function (e, data) {` to dispatch that event AND do the same in the documents upload, so that their behaviour is in sync (I do not see a reason why these should not have the same behaviour here).
> 
> 
> ```js
> {
>   clear() {
>     this.itemTargets.forEach((item) => {
>       item.remove();
>     });
>   }
> }
> ```

why don't we take care of it while adding a new message in `add` method? we can make a check to see if `ul` is empty or not?
and empty it if not and then append the new `message li item` into that `ul`?

**Comment by lb-** [comment]
@salty-ivy good call, that's much simpler. Maybe we can add another item to the event details like 'clear: true` and if true it will clear any existing items before adding a new one.

Alternatively, we can add `keep: true` and the default is false, but I feel that the default behaviour should probably be not to clear existing messages. 

This way it can be used to append a message OR clear and add a new message in the one event.

**Comment by salty-ivy** [comment]
we can make it `var text = $('.status-msg.update-success').first().text();` as its always going to return `Document uploaded.`

**Comment by salty-ivy** [comment]
@lb- i think its ready to be reviewed. thanks for following this through.
