### ISSUE TITLE
Pull out `initButtonSelects` from core.js into includes/initButtonSelects.ts

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9494]
### Is your proposal related to a problem?

**`initButtonSelects` should move from `core.js` to a new file `client/src/includes/initButtonSelects.ts`**

Wagtail's JavaScript `core.js` is quite large and many items can be pulled out to shared utils or includes to help make the code more maintainable and supported with base unit tests.

Pulling some basic functions out lets us put these into TypeScript (type safety) but also document and unit test them better.

### Describe the solution you'd like

The function `initButtonSelects` should be moved from
https://github.com/wagtail/wagtail/blob/aaea8710c21ba4d5368d3825781bc54e1869c561/client/src/entrypoints/admin/core.js#L607-L631

To a new file `client/src/includes/initButtonSelects.ts` (note: TypeScript ts not JavaScript js)

From there it can be imported and triggered the same way (see line 633) `$(document).ready(initButtonSelects);`.

#### Requirements

* [ ] Move the function to the the new TypeScript file and set up correct types - https://www.typescriptlang.org/
* [ ] Add a [JSDOC](https://jsdoc.app/) description to the function
* [ ] Add a basic set unit test (just one is fine) for this function in a new `client/src/includes/messages.test.js` file using [Jest](https://jestjs.io/) - look at client/src/includes/breadcrumbs.test.js for an example of mocking some HTML to then trigger some behaviour on that HTML
* [ ] Ensure the util is imported in core.js correctly so that the select buttons correctly initialise (take a screenshot of a usage that is correctly functioning after the change for the PR)

### Additional context

* This has been created as part of the Outreachy program to help new contributors that are interested in the Stimulus project.

**Comment by lb-** [comment]
@Lovelyfin00 - if you want - feel free to claim this one as per Slack chat.

**Comment by Lovelyfin00** [comment]
Awesome thanks😁😁
I'm on it

**Comment by lb-** [comment]
As per slack

You will have to search for the CSS class that gets used button-select
Which uses wagtail-new/wagtail/admin/templates/wagtailadmin/widgets/button_select.html
Which uses this python file wagtail-new/wagtail/admin/widgets/button_select.py

Which is used in these files
* wagtail-new/wagtail/contrib/redirects/filters.py
* wagtail-new/wagtail/admin/views/reports/workflows.py

so based on that, it looks like you could check the workflow UI and also the filtering (used in reporting pages I think)
