### ISSUE TITLE
Add basic unit tests & JSDOC for `initDismissibles.ts`

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9495]
### Is your proposal related to a problem?

**`initDismissibles` was added in https://github.com/wagtail/wagtail/pull/9344 but no JS unit tests were included**

So that we can have a basic confidence that code changes will not lead to widget regressions, and in prep for some widgets migrating to Stimulus it would be good to have a basic test coverage of this new component.

It would be good to also include some basic JSDOC for each exported function in that file.

### Describe the solution you'd like

The functions in https://github.com/wagtail/wagtail/blob/main/client/src/includes/initDismissibles.ts should both have unit tests covering their basic behaviour in a new file `client/src/includes/initDismissibles.test.ts`

Additionally, there should be a basic JSDOC entry describing the purpose and behaviour of each of the functions in the file - `updateDismissibles` & `initDismissibles`.

#### Requirements

* [ ] Add a [JSDOC](https://jsdoc.app/) description to the functions (note: some comments in `initDismissibles` can move to JSDOC)
* [ ] Add a basic set unit test for each one in the newly created test file, there should be one for each function and one that checks the behaviour on fetch error.

### Additional context

* This has been created as part of the Outreachy program to help new contributors that are interested in the Stimulus project.
*  look at client/src/includes/breadcrumbs.test.js for an example of mocking some HTML to then trigger some behaviour on that HTML, look at client/src/includes/initUpgradeNotification.test.js for examples of mocking fetch.

**Comment by Yekasumah** [comment]
Thank you, I'll work on it.

**Comment by Yekasumah** [comment]
Hi @lb-, I have created a new PR for this issue adding the JSdoc to the functions.
https://github.com/wagtail/wagtail/pull/9597
