### ISSUE TITLE
Pull out `initTagField` from core.js into includes/initTagField.ts

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9496]
### Is your proposal related to a problem?

**`initTagField` should move from `core.js` to a new file `client/src/includes/initTagField.ts`**

Wagtail's JavaScript `core.js` is quite large and many items can be pulled out to shared utils or includes to help make the code more maintainable and supported with base unit tests.

Pulling some basic functions out lets us put these into TypeScript (type safety) but also document and unit test them better.

### Describe the solution you'd like

The function `initTagField` should be moved from
https://github.com/wagtail/wagtail/blob/aaea8710c21ba4d5368d3825781bc54e1869c561/client/src/entrypoints/admin/core.js#L32-L50

To a new file `client/src/includes/initTagField.ts` (note: TypeScript ts not JavaScript js)

From there it can be imported and triggered the same way (added to a global back in core.js)

#### Requirements

* [ ] Move the function to the the new TypeScript file and set up correct types - https://www.typescriptlang.org/ 
* [ ] Add a [JSDOC](https://jsdoc.app/) description to the function
* [ ] Add a basic set unit test (just one is fine) for this function in a new `client/src/includes/initTagField.test.js` file using [Jest](https://jestjs.io/)
* [ ] Ensure the util is imported in core.js correctly and the window variables `window.initTagField` works, take as screenshot of a tag field working after your change fo rthe PR

### Additional context

* This has been created as part of the Outreachy program to help new contributors that are interested in the Stimulus project.
* Look at client/src/includes/breadcrumbs.test.js for an example of mocking some HTML to then trigger some behaviour on that HTML
* Note that this will be a bit tricky as `tagit` is a jquery plugin and is a global, so TypeScript may not like this, you will need to look at other TypeScript files or search online for how to ensure that TypeScript will allow this global. See client/src/utils/text.ts for an example of declaring a global for Typescript.
* Testing jquery unit tests will require you to set up window.$ - see client/src/entrypoints/admin/telepath/widgets.test.js as an example, you may also need to mock (Jest mocks) the `tagit` function.
* **Important:** The unit test does not need to test the full functionality of the tagit plugin, only that it was called.

**Comment by xomcodes** [comment]
Thank you @lb- 
I would work on this.

**Comment by AnishaSingh0118** [comment]
Can I work with .JS file because currently there are some complications with .ts file.

**Comment by xomcodes** [comment]
I am working on it

**Comment by AnishaSingh0118** [comment]
Hey @lb- I have come up with a PR https://github.com/wagtail/wagtail/pull/9614 which is fixing 2 issues at once.
Issue 1:
https://github.com/wagtail/wagtail/issues/9496
Issue 2: 
https://github.com/wagtail/wagtail/issues/9493

**Comment by lb-** [comment]
@AnishaSingh0118 thanks but as per the previous comments and already linked PR it hopefully was quite clear that @xomcodes is actively working on this issue. 

I appreciate your enthusiasm but stepping in over someone who is trying to learn is not ideal. 

For now, can you close the PR that covers both issues and I suggest that @xomcodes you take a look at the PR for any inspiration.

**Comment by AnishaSingh0118** [comment]
> @AnishaSingh0118 thanks but as per the previous comments and already linked PR it hopefully was quite clear that @xomcodes is actively working on this issue.
> 
> I appreciate your enthusiasm but stepping in over someone who is trying to learn is not ideal.
> 
> For now, can you close the PR that covers both issues and I suggest that @xomcodes you take a look at the PR for any inspiration.

Ok, sure I am just trying from my end to help as much I can by constantly working and understanding the issues and coming up with a approach and get feedback. I am sorry if I came in way of someone else I have read somewhere "no need to ask if you have resolved the issue you could provide the efforts". So I got confused now 😅
