### ISSUE TITLE
Incorrect pluralisation for "{num} errors" in minimap

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#9497]
### Issue Summary

The `aria-label` attribute on the "number of errors" badge always uses "{num} errors" as the format string, without considering the correct pluralisation on the word "errors":

https://github.com/wagtail/wagtail/blob/aaea8710c21ba4d5368d3825781bc54e1869c561/client/src/components/Minimap/MinimapItem.tsx#L38

This means that it shows "1 errors" instead of "1 error", and languages with different pluralisation rules will have different errors. This should be updated to use [the `ngettext` utility function](https://github.com/wagtail/wagtail/blob/main/client/src/utils/gettext.ts#L25-L52) instead of `gettext`.

### Steps to Reproduce

1. On bakerydemo, edit a page, create a validation error (e.g. insert a Paragraph block with no content) and click "Save draft"
2. When the form is re-shown, hover over the minimap on the right-hand edge of the page to expand it
3. Right-click on the red "1" icon and inspect it in your browser's developer tools
4. Observe that the `aria-label` attribute is "1 errors"

![Screenshot 2022-10-26 at 13 17 31](https://user-images.githubusercontent.com/85097/198026719-121662d8-f9f3-42a7-a511-2739e1e7ee0e.png)

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.8.0
-   Django version: 4.1.2
-   Wagtail version: 4.1rc1

**Comment by Buduzz** [comment]
hi @gasman, I would to pickup this issue. ok? 
I am an outreachy intern

**Comment by Buduzz** [comment]
hi @gasman I have made the changes, however, I am experiencing difficulties running it. The changes are not reflecting on the work. could you help

**Comment by gasman** [comment]
Hi @Buduzz - thanks for looking into this. However, as there's quite a bit of time pressure on this fix (it needs to be reviewed and passed on to translators in time for the 4.1 release, due on Tuesday) I'll pick this up myself now.
