### ISSUE TITLE
Show "Add child page" in slim header rather than inside "…" three dots menu

### ISSUE THREAD

**Issue by maartenkling** [wagtail/wagtail#9499]
### Is your proposal related to a problem?

User interface is hard for users not using wagtail everyday. There task is to add a new page and this is hidden under de ... menu next to the breadcrumbs. 

![image](https://user-images.githubusercontent.com/946684/198051716-a905d158-f4a1-47cf-9042-63dd3c25a67f.png)

### Describe the solution you'd like

Show a + directly. 

![image](https://user-images.githubusercontent.com/946684/198051712-c7e47491-ac4e-4f93-9980-20c35c2bb873.png)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by 4the4ryushin** [comment]
So does the add + button should be removed from the menu, or let it be there also?

**Comment by maartenkling** [comment]
i'm not a UX designer, i think at both places.

**Comment by AnishaSingh0118** [comment]
Can I put my efforts to this issue ?

**Comment by salty-ivy** [comment]
> Hello @maartenkling Can I put my efforts to this issue ?
> 
> If it is still unresolved.

Hi @AnishaSingh0118 if you are a first time contributor I would recommend you to start with good first issues

**Comment by AnishaSingh0118** [comment]
> > Hello @maartenkling Can I put my efforts to this issue ?
> > If it is still unresolved.
> 
> Hi @AnishaSingh0118 if you are a first time contributor I would recommend you to start with good first issues

Oh! Ok.

**Comment by nicklee** [comment]
Hi all,

I've attached two mockups illustrating how this could potentially work:

![page-editor_no-popup](https://user-images.githubusercontent.com/298766/205936439-9b264ec1-b94d-41b6-b9f0-f672eded111e.png)

![page-editor_pop-up](https://user-images.githubusercontent.com/298766/205936428-adb0aaa2-a78c-4aad-9829-1a8e3280d72d.png)

- I've placed the add new child page icon before the meatball menu (...), as typically these reveal more, so if we're exposing something, we should do this prior to the expose more functionality
- We've removed the "new child page" option from the meatball menu, having it in two places isn't a complete no-no, but when they are in such close proximity i'd worry it adds to cognitive load, and doesn't really add much.

**Downsides:**

- UI is a little more cluttered

**Positives:**

- Adding a new child page is one less click
- Findability of the add new child page is much improved

Note: I've tackled this alongside the breadcrumb issue (https://github.com/wagtail/wagtail/issues/9498), so the full breadcrumb is also revealed in these mockups, I'll add comments relating to this aspect on the relevant ticket.

**Comment by nicklee** [comment]
Couple of other alternative buttons which would give the "add child page" button more prominence 

![option-2](https://user-images.githubusercontent.com/298766/207094254-53eaf49c-2858-4d7a-ac19-25da6605699e.png)
![option-3](https://user-images.githubusercontent.com/298766/207094265-f47f2913-7b32-4def-b015-bcf9abae90dc.png)

**Comment by nicklee** [comment]
This has now been narrowed down to two versions, both of which are very similar, the second version simply having the addition of the label to ensure it's fully obvious to the user what they should expect.

Initial thoughts are that we don't use labels for the meatball menu, status, history, comments or preview options, so it would be consistent if this was omitted. 

Going for the non-label approach has the additional benefit of there being less chance of wrapping on smaller browser sizes too. The original goal and reason for it being moved to the meatball menu was to pare back the interface by removing all items that weren't primary actions, with this in mind, it feels like the non-label option, fixes the issue, whilst ensuring as little additional noise is added to the experience.

### Only icon
![Image](https://user-images.githubusercontent.com/298766/210520382-d1813489-998e-466b-9cd1-c3c23df1981d.png)

### Only icon - with active tooltip
![Image](https://user-images.githubusercontent.com/298766/210520385-3314a358-6cf4-4473-9e5a-fb9b75957ffc.png)

### Icon and label
![Image](https://user-images.githubusercontent.com/298766/210520384-db063b1d-ad57-4f75-a8ee-b07d68dcae78.png)

**Comment by benenright** [comment]
Exposing the 'Add child page' button and reducing the no. of clicks to add a child page feels like a good idea on listing pages where it's a more common action than other functions within the 3-dot menu. And because people often end up navigating to the edit page when looking to add a child, it seems that editors would expect to have the exposed button on the edit page too.

I'd love us to test the single '+' to see if the label is needed. My feeling is that a tooltip is enough for users to learn this pattern and then not having a label keeps the UI cleaner. (considering this header is sticky too). 

Hard to think of a strong rationale for this button having a label, whilst the icons in the right side of the header do not, and also rely on a tooltip and users learning their function  - in the interest of a cleaner UI). Perhaps because it is a distinct action whereas the functions on the right are more UI controls (opening panels etc). But I think we could test the '+' first before committing to a persistent label?

**Comment by thibaudcolas** [comment]
This shipped in Wagtail 5.2 I believe :) See https://static-wagtail-v5-2.netlify.app/admin/pages/60/.
