### ISSUE TITLE
Convert initTooltips.js to TypeScript & add unit tests

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9505]
### Is your proposal related to a problem?

**`initTooltips` was added in https://github.com/wagtail/wagtail/pull/8231 but as JavaScript not TypeScript & no unit tests were included**

So that we can have a basic confidence that code changes will not lead to widget regressions, and in prep for some widgets migrating to Stimulus it would be good to have a basic test coverage of this component util.

It would be good to also include some basic JSDOC for each function in that file.

### Describe the solution you'd like

The file https://github.com/wagtail/wagtail/blob/main/client/src/includes/initTooltips.js should be converted to TypeScript (`.ts`) and any required types be added.

Along with this we should add some basic unit tests to cover the init functions' basic behaviour in a new file `client/src/includes/initTooltips.test.js` (note: .js for tests)

Additionally, there should be a basic JSDOC entry describing the purpose and behaviour of each of the functions in the file - if not already included.

#### Requirements

* [ ] Convert the file to [TypeScript](https://www.typescriptlang.org/) 
* [ ] Add a [JSDOC](https://jsdoc.app/) description to the functions if needed (e.g. `hideTooltipOnEsc` does not have one)
* [ ] Add a basic set unit test for each one in the newly created test file, there should be one for each function and one that checks the behaviour on fetch error.

### Additional context

* This has been created as part of the Outreachy program to help new contributors that are interested in the Stimulus project.
* Look at client/src/includes/breadcrumbs.test.js for an example of mocking some HTML to then trigger some behaviour on that HTML.
* Reminder: JSDOC needs to be directly above the function line to work correctly (e.g. the line break below on line 94 will mean some editors will not pick up the JSDOC)

https://github.com/wagtail/wagtail/blob/aaea8710c21ba4d5368d3825781bc54e1869c561/client/src/includes/initTooltips.js#L93-L95

**Comment by lb-** [comment]
To assign to Fatuma.

**Comment by FatumaA** [comment]
Thanks!
