### ISSUE TITLE
Invalid parameter for FieldPanel

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#9516]
### Pertinent section of the Wagtail docs
https://docs.wagtail.org/en/stable/reference/pages/panels.html#fieldpanel

### Details
help_text(optional)

This parameter is not suported

**Comment by gasman** [comment]
help_text on FieldPanel should be fully supported as of 4.0.3: https://github.com/wagtail/wagtail/pull/9240

**Comment by robslotboom** [comment]
Oeps, I have wagtail 4.0.2
