### ISSUE TITLE
Documentation: No frequently asked questions page, or page dedicated to solving common issues encountered while using/installing Wagtail. 

### ISSUE THREAD

**Issue by Teebarh** [wagtail/wagtail#9523]
As an Outreachy applicant, I noticed some of the other participants had issues setting up Wagtail on their local machines. That led me to think of creating a file with the problems they encountered and the solutions offered. I also noticed the documentation has no section specifically for this, so, I'm creating this issue to volunteer to work on this and get reviews on this from my mentors @thibaudcolas and @lb-

**Comment by thibaudcolas** [comment]
@Teebarh thank you for the suggestion. Could you share examples of similar projects to Wagtail that have such a page?

I like the idea in theory but I’m not sure how well it would work in practice, as I’d expect those pages to be hard to maintain over time. I think it would help to look at how other projects do this well, to see what kind of content they add on those kinds of pages.

**Comment by Teebarh** [comment]
@thibaudcolas sure! This [WordPress](https://wordpress.org/support/article/common-wordpress-errors/) documentation page shows common errors encountered while setting up or using the CMS, and how to solve them. It also has a link to a [support forum](https://wordpress.org/support/forums/) where you can ask questions or describe issues that aren't available in the documentation.

**Comment by lb-** [comment]
I have created a discussion about how we can better support absolute beginners with getting started developing on or with Wagtail. 

https://github.com/wagtail/wagtail/discussions/9557

This issue may cover a different kind of thing but I propose we close this issue and move the FAQ page into a comment on that discussion.

**Comment by thibaudcolas** [comment]
👍 sounds good to me. Thanks again for the report @Teebarh, we’ll keep discussing this in #9557.
