### ISSUE TITLE
UX page title has no focus

### ISSUE THREAD

**Issue by maartenkling** [wagtail/wagtail#9526]
### Is your proposal related to a problem?

In the new Wagtail 4.x UI the Page title is a label and not shown as an input
<img width="716" alt="Screenshot 2022-10-28 at 08 52 51" src="https://user-images.githubusercontent.com/946684/198522577-0ee14b2b-7f7f-4059-b8dd-d2779e86728d.png">
This makes it hard for user to understand they need to fill in a title.

### Describe the solution you'd like

Show a border. Im not a designer :)
<img width="926" alt="Screenshot 2022-10-28 at 08 53 37" src="https://user-images.githubusercontent.com/946684/198522714-8c62efae-a118-42b8-9af5-0baf555cf921.png">

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by gasman** [comment]
Thanks for the report @maartenkling - there's an existing open issue about this at #9318.

**Comment by Seremba** [comment]
Hi @lb- requesting to work on this issue
