### ISSUE TITLE
Add a note to install a package manager for Windows users to prevent errors using the `make` command

### ISSUE THREAD

**Issue by DokuaAsiedu** [wagtail/wagtail#9540]
### Summary
When compiling the documentation using Sphinx with this command:  
`make html`, Windows users might run into this error:  
_make is not recognized as an internal or external command, operable program or batch file_

### Details
In the [Development](https://docs.wagtail.org/en/stable/contributing/developing.html#compiling-the-documentation) page of Wagtail's documentation, a note callout could be placed in the _[Compiling the Documentation](https://docs.wagtail.org/en/stable/contributing/developing.html#compiling-the-documentation)_ section, notifying Windows users of a likely error, they could encounter when running: `make html`.  
  
If the error is: _make is not recognized as an internal or external command, operable program or batch file_, the callout could suggest that the user use a package manager like _Chocolatey_ to install the _make_ tool.

**Comment by DokuaAsiedu** [comment]
@lb- I would like to find out from you if you think this is needed. It was something I struggled with so I thought it might be beneficial to future users if this note was included.

**Comment by lb-** [comment]
Yeah maybe we need a heading under - https://docs.wagtail.org/en/latest/contributing/developing.html#setting-up-the-wagtail-codebase

Maybe just before the next `testing` heading. 

### Development with Windows

... Some preamble about how development on Windows is not as well documented as we would like and recommend that the Docker/vagrant approaches would be better. 

Then document some additional set up steps that will be needed. 

- CRLF setup
- Installing Make
- Terminal/PowerShell or all the options?

----

Start with the note about Make but just thinking that it may be good to gather feedback on Slack from Windows users.

**Comment by DokuaAsiedu** [comment]
> Yeah maybe we need a heading under - https://docs.wagtail.org/en/latest/contributing/developing.html#setting-up-the-wagtail-codebase
> 
> Maybe just before the next `testing` heading.
> 
> ### Development with Windows
> ... Some preamble about how development on Windows is not as well documented as we would like and recommend that the Docker/vagrant approaches would be better.
> 
> Then document some additional set up steps that will be needed.
> 
> * CRLF setup
> * Installing Make
> * Terminal/PowerShell or all the options?
> 
> Start with the note about Make but just thinking that it may be good to gather feedback on Slack from Windows users.

Okay thanks, will work on that
