### ISSUE TITLE
Django Treebeard Methods in Page models

### ISSUE THREAD

**Issue by Temidayo32** [wagtail/wagtail#9545]
### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/stable/reference/pages/model_reference.html?

### Details

In a pull request #9517 I made, @lb- think a separate documentation on how Treebeard is used in Wagtail Page model would be better than the current solution I wanted merged (I added links to some of its methods in the docs page above).  I agree with this, as there is indeed a documentation gap, and it would help developers using the documentation better understand the internal mechanics of the Page model.

**Comment by thibaudcolas** [comment]
I believe this has been addressed by #9517? This is a different solution so we might want to do more but at least for the time being the relationship with treebeard seems clear to me.
