### ISSUE TITLE
Add tests for dummy requests (follow-up on #946)

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#956]
#946 requires tests.

Possibly using `@override_settings()`

**Comment by lb-** [comment]
closing as the code this relates to was for the old style (pre Django 1.10 `MIDDLEWARE_CLASSES` setting).

This has since been deprecated https://docs.djangoproject.com/en/dev/releases/1.10/#new-style-middleware and Wagtail code no longer has this code anywhere.
