### ISSUE TITLE
rebuild_references_index command should respect verbosity=0

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#9563]
### Is your proposal related to a problem?

The `./manage.py rebuild_references_index` command generates a lot of output, which may crowd out more useful messages when running setup scripts.

### Describe the solution you'd like

This command should respect the conventional `--verbosity=0` flag to suppress output:

    ./manage.py rebuild_references_index --verbosity=0

This is supported by similar commands such as `./manage.py update_index` - for anyone interested in picking this up, I'd recommend referring to how this was done in #9271, and applying a similar change to [wagtail/management/commands/rebuild_references_index.py](https://github.com/wagtail/wagtail/blob/main/wagtail/management/commands/rebuild_references_index.py).

**Comment by MRZHD1** [comment]
Hi! I'm relatively inexperienced but I'd like to give this a shot if that's okay.

**Comment by gasman** [comment]
@MRZHD1 Sure, go for it!

**Comment by Buduzz** [comment]
hi @gasman do you permit collaboration on issues like what we have here

**Comment by MRZHD1** [comment]
Hi @Buddz I already implemented it, I'm just testing it now, and I'm having issues on my system so I'll just try and make it work tomorrow.

**Comment by 4the4ryushin** [comment]
@MRZHD1 are you still working on its test? or should i make the PR, or even happy to help out thank you

**Comment by MRZHD1** [comment]
Hi @4the4ryushin. I've finished the issue already, just having issues with git to pull it to my machine for some reason it keeps breaking. I'm going to try on another computer.

**Comment by 4the4ryushin** [comment]
> Hi @4the4ryushin. I've finished the issue already, just having issues with git to pull it to my machine for some reason it keeps breaking. I'm going to try on another computer. 

it's alright, lemme know I can be any help

**Comment by MRZHD1** [comment]
Okay, I can't seem to pull it to my computer for some reason. @4the4ryushin / @Buduzz, I will open a draft PR if one of you could test if the code works I would appreciate it :+1:.

(It is #9602)

**Comment by 4the4ryushin** [comment]
Sure go ahead make the pr and I will deal with the tests or anything that would be lacking

**Comment by MRZHD1** [comment]
No problem, take your time. Thank you :)

**Comment by MRZHD1** [comment]
I didn't write documentation yet either, but I could definitely add that if the tests pass.

**Comment by gasman** [comment]
Completed in #9602
