### ISSUE TITLE
Refactor page fetching logic and cache on request

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#9564]
Reference: https://github.com/wagtail/wagtail/issues/3066#issuecomment-1292028660 from @gasman 

> So, in terms of the change to be made to Wagtail itself, this would just involve building, documenting and testing the find_page_for_request helper - nothing about that needs to indicate that it's intended for use in middleware / CSRF handling. (If you were to subsequently write up a recipe detailing how to use this for CSRF control, I'd sure that would be welcomed, but probably out of scope for the main Wagtail docs and a better fit for a blog post or similar.) For the tests, we'd just need to validate that `find_page_for_request` returns the right result and that `assertNumQueries` gives 0 for any calls after the initial one.

**Comment by zerolab** [comment]
Fixd via #11683
