### ISSUE TITLE
Broken 'Unlock' link on "Your locked pages" dashboard panel

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#9576]
### Issue Summary

The "Unlock" link on the "Your locked pages" dashboard panel on the admin homepage is broken.

### Steps to Reproduce

1. From a fresh bakerydemo installation, edit the homepage and lock it from the status sidebar
2. Go back to the admin homepage, where a "Your locked pages" panel now appears
3. Click the "Unlock" button under the homepage item. You arrive at the URL http://localhost:8000/admin/undefined, with the error message:

> RuntimeError at /admin/undefined
> You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/admin/undefined/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.

### Technical details

-   Python version: 3.8.0
-   Django version: 4.1.2
-   Wagtail version: main (4.2a0)
-   Browser version: Chrome 106.0.5249.119

**Comment by gasman** [comment]
Looks like this has been broken since 3.0... current behaviour started in 6f10ae45c76b9f5533e92c749bc1856f86df3d06, and before that the button didn't respond at all. (It did work in 2.16)

**Comment by gasman** [comment]
Original breakage (button not responding) happened in f323d887658c1f82d71960cd48d8929e233ff473.

**Comment by th3hamm0r** [comment]
That's interesting, I think I've tested this either for #9528 or for #9530, and it worked. Maybe #9530 actually fixes it, I thought it was only "cosmetic" :sweat_smile:

**Comment by lb-** [comment]
Confirming this is broken. Also may be fixed with merged https://github.com/wagtail/wagtail/pull/9530

**Comment by lb-** [comment]
Fixed via https://github.com/wagtail/wagtail/pull/9530 

5086257539c54f8674a33b48b52f39a61a76126e
5584b44ca72e091fadd5fb4d4ac3b116900da371 (4.1 stable)
