### ISSUE TITLE
Add styles on Windows high contrast mode to indicate "active" state

### ISSUE THREAD

**Issue by mohammadareeb95** [wagtail/wagtail#9578]
### Issue Summary
On normal rendering, we can see the "Documents" tab has a different style – so we know it’s the "active" one.
We’re missing this in the Windows high contrast mode version, where the "Documents" tab just looks like the other ones

### Normal mode
![image](https://user-images.githubusercontent.com/77102111/199545439-e14a28e5-4fac-4d6c-8ffc-80a8ea2a1201.png)

### High-contrast mode
![image](https://user-images.githubusercontent.com/77102111/199545173-6be16e93-6faf-4308-a92d-705f9aa4c1e0.png)

### Proposed Solution 
We should ideally add a bottom border underneath that tab in high-contrast mode, so it’s clearly indicated as "active"
### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Migrate and start the server
3. Open the Wagtail admin interface
4. Select "Documents" 
5. Enable high-contrast mode

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no) yes

**Comment by lb-** [comment]
Can confirm this bug exists.
