### ISSUE TITLE
Several date formatting issues (no TZ conversion, no i18n)

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9581]
### Issue Summary

There are several places in the python code, where `strftime("%d %b %Y %H:%M")` is used to format dates. This does not convert the date to the currently active timezone nor does it use the current language.

For example, if you access a scheduled/locked page, the notification at the top does not use the correct TZ (should be Europe/Vienna, not UTC in that example) and it's in english instead of german (see the correct date in the status panel on the right):
![wagtail_date_format_and_timezone_issues](https://user-images.githubusercontent.com/468164/199565906-fbc46855-7dd4-40c9-a444-427ffda70fd8.png)

### Possible Solution

In the templates you normally use the date filter from django, in wagtail most dates use the `human_readable_date` tag, which uses [this template](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/human_readable_date.html), which uses django's date filter.
So I think we should convert those dates to local time using django's `django.utils.timezone.localtime()` and use `django.utils.formats.date_format()` to format it.

When searching for `strftime("%d %b %Y %H:%M")`, I've basically found two categories of usages:

**1) Easy to fix:**
Usages which are rendered directly, e.g. all session messages, for example
https://github.com/wagtail/wagtail/blob/5a249d4e9c65ec742c8e920d44f2fda2038395e3/wagtail/locks.py#L47-L51

**2) Harder to fix (conceptual bugs):**
_Update: Fixing the correct formatting/timezone was easy (see #9590), but we should create a ticket to improve the storage of those timestamps._
Unfortunately, there are also some usages (only for audit logging I think), which are probably harder to fix, because the dates are actually stored in that format:
https://github.com/wagtail/wagtail/blob/5a249d4e9c65ec742c8e920d44f2fda2038395e3/wagtail/actions/publish_revision.py#L57-L72
I assume that's the case, because that storage is not really typed and it was easier to just use those ready-to-use date strings later.
Changing this in a clean way would probably require to store these dates in a standardized date string and convert all existing dates with a migration.

### Steps to Reproduce

To reproduce the above example from the screenshot:
1. In your new virtualenv: `pip install wagtail && wagtail start mysite && cd mysite && pip install -r requirements.txt && ./manage.py makemigrations && ./manage.py migrate && ./manage.py createsuperuser && ./manage.py runserver`
2. Login to the CMS
3. Go to the account settings, and at least change the timezone to something other than UTC (you could change the language to non-english later).
4. Add a new page (http://127.0.0.1:8000/admin/pages/add/home/homepage/3/) and save it as a draft.
5. Set a schedule by using the side panel and configure a date in the future. Publish (schedule) the page.
6. Open the edit-page again and find the now locked page with the notification.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10, 3.11
-   Django version: 3.2, 4.1.3
-   Wagtail version: 4.0.4, 4.1
-   Browser version: Firefox 106

**Comment by th3hamm0r** [comment]
Fyi: I think the 2. category is probably not hard to fix, I haven't looked at the outputting code yet, but we can parse the date, make it tz aware and convert it to local tz.

**Comment by allcaps** [comment]
We could use `django.template.defaultfilters.date` on the Python side.

```
from django.template.defaultfilters import date

date(value, "DATETIME_FORMAT")
date(value, "DATE_FORMAT")
date(value, "TIME_FORMAT")
```
Gives the EXACT SAME output as the template variant:
```
     {{ value|date:'DATETIME_FORMAT' }}
     {{ value|date:'DATE_FORMAT' }}
     {{ value|date:'TIME_FORMAT' }}
```
It respects the active locale does apply the current timezone conversion and date/time formatting rules.

It even respects the `formats.py` if the developer decides they want specific datetime formats in their projects.

**Comment by th3hamm0r** [comment]
@allcaps Yes, that was my initial idea too and I've tried that, but there is a major issue here: the `date` filter only converts the date to local time if used in the templates, so it looks like `expects_localtime=True` is only applied by the template engine.
I've actually used that in some projects too, so that was a good learning for me :+1:

**Comment by Zeki-Abdulhamid** [comment]
Helllo, May you please let me know the steps that you used to fix the date & time zone issue using Django

https://github.com/th3hamm0r

**Comment by zerolab** [comment]
@Zeki-Abdulhamid this is not a good first issue. And there is a draft PR (#9590) for it

**Comment by cyface** [comment]
I wanted to mention that this is an issue for my org as well.
