### ISSUE TITLE
Extend Limiting Links in RichTextField

### ISSUE THREAD

**Issue by FilterUnfiltered** [wagtail/wagtail#9587]
### Is your proposal related to a problem?

I am currently struggling with removing the Internal Link option from a project. Nobody who is working on it can figure out why, but Internal Link always becomes "None" when we pick a page, meaning it doesn't work at all, so we figured using external links works fine. However, we obviously don't want to ship a broken product, which is what Internal Links currently are, but there is absolutely no way to remove them. 

### Describe the solution you'd like

When using `RichTextField(features=['h2', 'h3', ...)` make it possible to pick specific link types, not just `link`

### Describe alternatives you've considered

I have tried using CSS to hide the option and then a hook to make the default External Link doesn't seem to work, because after making another link it defaults back to Internal Link. I also wanted to try to extend the admin templates to remove it, but the chooser/_link_types.html file is not extendable as it doesn't use any blocks.

### Additional context

The rest of the wagtailadmin pages that don't already should use blocks, so that one can extend them and modify them manually if what you are trying to do doesn't exist already.

**Comment by allcaps** [comment]
You seem to propose a complex workaround to Wagtail as a fix for a bug in your project...

I'm pretty sure that internal links in a clean Wagtail project work fine. Internal links are a core feature for a CMS.

I'd advice you to [seek support](https://docs.wagtail.org/en/stable/support.html#support) on fixing your internal link bug.

**Comment by FilterUnfiltered** [comment]
Regardless, it's a feature that would be nice to have.

**Comment by zerolab** [comment]
Using only external URLs (that is full URLs) is prone to issues. e.g. if the paths change.
Granted that is likely less of an issue as 2.16 which introduced automatic redirect creation.

As @allcaps mentioned internal links are a core feature. I would suggest creating your own link chooser plugin (see https://docs.wagtail.org/en/stable/extending/extending_draftail.html#extending-the-draftail-editor as a staring point)
