### ISSUE TITLE
Empty minimap when using side panels in non-standard interfaces

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#9604]
wagtail-localize uses the new side panels to output basic information when editing translations.
The editing interface uses the regular edit template with the content generated by React.

The new minimap (#9345) looks quite odd in that context. While I realise localize does things in an unorthodox way, the minimap and collapse/expand all should only be rendered if they have actual interaction points with the rest of the interface (IMHO)

![Screenshot 2022-11-04 at 12 58 54](https://user-images.githubusercontent.com/31622/199979008-b4868544-b049-432c-9f9d-788135687a8e.png)

The current workaround is to include `side_panels.html` with `in_explorer=False`. While it works, I can see this introducing other problems down the line.. e.g. what if panels start varying information based on `in_explorer`.

Potential solutions: 

1. wrap https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/side_panels.html#L15-L18 in a block so packages can extend the side panels template but exclude the minimap if not relevant.
2. update the JS logic to exit early if the expected triggers/anchors don't exist

**Comment by allenvtran** [comment]
@zerolab Just to clarify, is the issue regarding the collapse all panel where there doesn't seem to have any functionalities, and you want it to be showing off the minimap of the website instead?

**Comment by zerolab** [comment]
@allenvtran I would think the description is fairly clear and it is summarised by

> the minimap and collapse/expand all should only be rendered if they have actual interaction points with the rest of the interface

That is, do not show the minimap nor collapse all if the content area doesn't provide any headings to construct the minimap with, and no collapsible elements are available for "collapse all"

**Comment by albinazs** [comment]
This was fixed via [#10915](https://github.com/wagtail/wagtail/pull/10915/commits/fcad58091ea0765c068376f797dc7329ea80193a)

**Comment by zerolab** [comment]
Thank you @albinazs
