### ISSUE TITLE
Page editor footer truncates texts

### ISSUE THREAD

**Issue by vorlif** [wagtail/wagtail#9613]
### Issue Summary

I know, we Germans are not exactly known for our short words. But unfortunately, it is what it is, and often we have somewhat longer texts. Unfortunately, this leads to the page editor that the approval text in the footer is longer and does not fit in the footer. There are also small design failures in other languages.

Example German:
![image](https://user-images.githubusercontent.com/4333770/200004815-8bb4cf42-ed41-4106-a0fc-a0285784a2e9.png)

Example France, missing icon:

![image](https://user-images.githubusercontent.com/4333770/200007627-1e32c794-235d-4e7d-bc0d-cbe6e6cf3c3c.png)

Example Hungarian, small icon:

![image](https://user-images.githubusercontent.com/4333770/200007905-198fa0c9-200c-4b0d-a456-7da1748baf50.png)

Example Icelandic:

![image](https://user-images.githubusercontent.com/4333770/200008334-9eb3a29b-39c8-4044-8180-a521e06973ca.png)

Possible solutions:

* Allow the footer to fit the text
* Allow multi-line texts
* Truncate too long texts with ellipsis points

### Steps to Reproduce

1. Start a new project with `wagtail start myproject` or open an existing one
2. Change your user language to German
3. Create a page and submit to Moderators approval
4. Open the page again
5. Open the footer

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10.8
-   Django version: 4.1.1
-   Wagtail version: 4.1
-   Browser version: Chrome 107, Firefox 106

**Comment by Yekasumah** [comment]
Hi, I would like to work on this issue. I have been able to replicate the issue on my end. Please do you have any more suggestions that can be applied to solving this issue?

**Comment by grumpyp** [comment]
A pretty easy way to solve it for now would be `[:45]` where `45`. What do you think?

**Comment by Yekasumah** [comment]
I've had a look at it. I think there should be an icon before the "Approve with comments and publish", I don't think having a second line would fit the UI 


I also discovered this on the popup, the bottom isn't centered.
<img width="305" alt="Screenshot 2022-11-06 at 14 06 16" src="https://user-images.githubusercontent.com/105293813/200172466-b25a4d3e-da5e-42d5-9b3e-01f508324d11.png">

**Comment by vorlif** [comment]
I think the footer has a fixed width, and I believe the best solution would be for the footer to have a `min-width` and automatically grow with larger text. It should also have a `max-width` and cut off too long text with ellipsis points. The icon should always be displayed, regardless of the text.

The disadvantage of this solution would be that the footer would vary in width depending on the state of the page. Alternatively, we could simply increase the fixed width of the footer. :shrug:

**Comment by allcaps** [comment]
Confirmed! Reproduced by:

1. New project
2. Open page editor
3. Use the browser inspector to create a long button text

Results:
- Icon gone
- Text clipped

Note:
- `text-overflow: ellipsis` isn't accessible. So, not a real option.
- Custom workflow steps can add buttons with long texts. This isn't a German language issue.
- On mobile viewports we have limited width, wrapping to new lines might be our only option.
- Be careful with increasing the height of the footer. In the past we had issues with this footer overlapping the main content.

<img width="1539" alt="Screenshot 2022-11-10 at 01 22 57" src="https://user-images.githubusercontent.com/1969342/200970433-cc802c10-86dc-49fa-8ae3-1a6a282798ea.png">

**Comment by allcaps** [comment]
I've raised this issue on Slack in #ui and in #accesisibility

**Comment by allcaps** [comment]
Related issues:
- https://github.com/wagtail/wagtail/issues/4641
- https://github.com/wagtail/wagtail/issues/9073
- https://github.com/wagtail/wagtail/issues/9030
- https://github.com/wagtail/wagtail/issues/7366

**Comment by thibaudcolas** [comment]
Thank you for the report @vorlif! In this case I think the text could simply be displayed wrapped over multiple lines when it exceeds the width of the component. This would work regardless of the available width the dropdown is displayed at, which is important so this works on small screen widths too.

**Comment by thibaudcolas** [comment]
As far as I can see the base issue can be fixed by setting those buttons to `white-space: initial;` thus resetting the `nowrap` value set on all buttons. The icon issues can be fixed by setting `flex-shrink: 0;`. If we want to allow the text to wrap to more than two lines, we can override the `height` to `auto` and set the button’s `min-height` to 3em.

**Comment by allcaps** [comment]
Thank you for your guidance, I'll give it a go.

**Comment by AnishaSingh0118** [comment]
Can I work on this issue @thibaudcolas ?

**Comment by allcaps** [comment]
>  I'll give it a go. 

I'm working on it.

**Comment by thibaudcolas** [comment]
Thank you @allcaps! This will be fixed in v4.1.2 and the February release.
