### ISSUE TITLE
Redirects documentation misspells "middleware"

### ISSUE THREAD

**Issue by truthdoug** [wagtail/wagtail#9632]
In the [documentation for redirects](https://docs.wagtail.org/en/latest/reference/contrib/redirects.html) the code example includes `# all other django middlware first`. The word "middleware" is misspelled.

### Pertinent section of the Wagtail docs

https://docs.wagtail.org/en/latest/reference/contrib/redirects.html#installation

### Details

Fix the spelling

**Comment by Theresa-o** [comment]
Thank you for reporting this
