### ISSUE TITLE
Failing `DELETE` request on initial page editor load if custom CSRF header name is set

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#9635]
### Issue Summary

If a custom CSRF header name is set using Django's [`CSRF_HEADER_NAME`](https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-CSRF_HEADER_NAME) setting, the following function in `preview-panel.js` fails to send the request to the server as the header name is hardcoded:

https://github.com/wagtail/wagtail/blob/2af187127100e92c6792cdcc6f5e0803f86e22ab/client/src/entrypoints/admin/preview-panel.js#L146-L155

### Steps to Reproduce

1. Spin up bakerydemo
2. Add a custom `CSRF_HEADER_NAME` in the settings, e.g. `CSRF_HEADER_NAME = "HTTP_X_XSRF_TOKEN"`
3. Open the page editor in the admin
4. See a failing `DELETE` request after the page loads

This request is made to clear any stale preview data. It clears the preview data in the session with a `DELETE` request instead of `POST`ing the current form data because the data might not be valid to replace the stale preview data. As a result of the failing `DELETE` request, there's this bug:

- Create a new page with a certain page type (e.g. `StandardPage` in bakerydemo) as the child of a particular page
- Fill out the form until there's no validation error so that the preview is updated, but **do not** save the page
- Reload the browser
- You'll see the stale preview data even if you haven't filled out the form

---

- I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10.5
-   Django version: 4.0.8
-   Wagtail version: `main`

**Comment by gasman** [comment]
Fixed in #9636
