### ISSUE TITLE
Local setup Error for Safari Browser

### ISSUE THREAD

**Issue by AnishaSingh0118** [wagtail/wagtail#9645]
### Issue Summary

- No proper Documentation for Safari/LINUX (Ubuntu)

- User interface is broken in Safari Browser, functions are not working properly (settings, images nothing is working and if the page gets opened the contents are overlapping and are non-functional).

- Tried 2 different versions of Safari, still faced same issue.

- CSS_ throws error in safari browser, attaching a snap/video for better understanding.

https://user-images.githubusercontent.com/76876709/201339152-ea6bc4b2-0898-4c62-95a8-74932093628d.mp4

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Edit models.py as follows...(follow wagtail Documentation).
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   Yes, I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: `3.10.4`.
-   Django version: `4.1.3`.
-   Wagtail version: `4.1`.
-   Browser version: Safari `16.0`

**Comment by laymonage** [comment]
Safari 10 is old and it's no longer supported by Apple, thus I don't think we support it. Try using a more recent version of Safari (though you may need to use a more recent version of macOS).

**Comment by gasman** [comment]
See https://docs.wagtail.org/en/stable/contributing/developing.html#browser-and-device-support for the current range of supported browsers - macOS Safari is currently on version 16, so versions 14-16 are supported.

**Comment by AnishaSingh0118** [comment]
> Safari 10 is old (last release was in 2017) and it's no longer supported by Apple, thus I don't think we support it. Try using a more recent version of Safari (though you may need to use a more recent version of macOS).

I will try to reproduce this issue in new version. Thanks for letting me know.

**Comment by AnishaSingh0118** [comment]
> See https://docs.wagtail.org/en/stable/contributing/developing.html#browser-and-device-support for the current range of supported browsers - macOS Safari is currently on version 16, so versions 14-16 are supported.

Ok, Thanks for letting me know.

**Comment by AnishaSingh0118** [comment]
> Safari 10 is old (last release was in 2017) and it's no longer supported by Apple, thus I don't think we support it. Try using a more recent version of Safari (though you may need to use a more recent version of macOS).

Kindly open this issue again, i have updated my issue summary. 
Mac OS version: macOS Catalina `10.15.7`
 Safari version: `16.0`

**Comment by lb-** [comment]
Just flagging, I have been using Safari for some other testing this past month and have not run into any issues on Safari 16.1 

I am not sure if it was a specific version 16 issue (as at the time that was pretty new)

**Comment by gasman** [comment]
Not seeing this on Safari 16.2 either - will close for now, but happy to reopen if this can be independently verified.
