### ISSUE TITLE
template glitch in "Pages using ..."

### ISSUE THREAD

**Issue by minusf** [wagtail/wagtail#9646]
### Issue Summary

The `/usage/` urls template needs a small fix, as the listing header has checkboxes and the content doesn't:

<img width="837" alt="Screenshot 2022-11-11 at 13 26 52" src="https://user-images.githubusercontent.com/3632883/201340475-39086a91-78c0-4e4f-917f-511fd8afb997.png">

This seems to fix it for me:

```
--- usage_results.html     2022-11-11 13:35:58.000000000 +0100
+++ usage_results.html     2022-11-11 13:36:23.000000000 +0100
@@ -2,7 +2,7 @@

 <div class="nice-padding">
     {% if pages %}
-        {% include "wagtailadmin/pages/listing/_list_explore.html" with show_parent=0 %}
+        {% include "wagtailadmin/pages/listing/_list_explore.html" with show_parent=0 show_ordering_column=1 %}

         {% url 'wagtailadmin_pages:type_use' app_name content_type.model as pagination_base_url %}
         {% paginate pages base_url=pagination_base_url %}
```

### Steps to Reproduce

1. Start the process of adding a new page
2. Instead of adding a new page select `Pages using ...`
3. See listing with incorrect header

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: 3.10.8
-   Django version: 4.1.3
-   Wagtail version: 4.1
-   Browser version: FF 106.0.5

**Comment by gasman** [comment]
Fixed in #10004. Thanks for the report!
