### ISSUE TITLE
Crash when reverting to a revision on snippets with `PreviewableMixin` and `RevisionMixin`

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#9661]
### Issue Summary

When reverting to a revision on snippets with `PreviewableMixin` and `RevisionMixin` applied, the server crashes with a `NoReverseMatch` exception: `Reverse for 'None' not found. 'None' is not a valid view function or pattern name.`

This is because the `preview_url_name` is not passed from the `SnippetViewSet` to the `revisions_revert_view`. The revisions revert view class is a subclass of the edit view, and any `as_view()` arguments passed to the edit view must also be passed to the  revisions revert view:

https://github.com/wagtail/wagtail/blob/f77229da2a0dc93520b9083552d312217382de1a/wagtail/snippets/views/snippets.py#L735-L745

https://github.com/wagtail/wagtail/blob/f77229da2a0dc93520b9083552d312217382de1a/wagtail/snippets/views/snippets.py#L784-L794

### Steps to Reproduce

1. Spin up bakerydemo
2. Make some edits to the `FooterText` snippet
3. Open the snippet history page
4. Click `Review this version` on one of the revisions
5. See the error

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The revision revert (edit) page should open normally with the preview working.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes

**Comment by gasman** [comment]
Fixed in #9663
