### ISSUE TITLE
Code snippets should include import lines

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#9669]
https://docs.wagtail.org/en/stable/topics/streamfield.html#subclassing-structblock

You are programming but forget what to import for example for the above link. You want todo a quick lookup in docs for it.  Or even worse you are new to python and Django and Wagtail. And would like to start testing out what these docs say. Especialy in the latter case you can feel very lost to what to import and todo what. 

My suggestion is when you have an code snippet like on [this snippet](https://docs.wagtail.org/en/stable/topics/streamfield.html#subclassing-structblock)
The import should always be included in the docs. Maybe in the following form
```
...
from wagtail import blocks
...
class PersonBlock(blocks.StructBlock):
   first_name = blocks.CharBlock()
    surname = blocks.CharBlock()
    photo = ImageChooserBlock(required=False)
    biography = blocks.RichTextBlock()
```
or have the import is a special caption on top of the snippet.

Remember for those that start out understanding where things are is like 30% of the work :)

**Comment by allcaps** [comment]
The imports are introduced when needed. So the first snippet has most imports. Only if a new import is required, it is added. See a few snippets down, `import datetime` is introduced. This pattern is very consistent throughout the docs. 

Repeating all imports on each and every snippet will make the snippets longer than necessary. The repetition of similar imports will feel complex and bloated.

**Comment by gasman** [comment]
Closing as per @allcaps's reasoning.
