### ISSUE TITLE
Unschedule publishing view does not follow `next` parameter

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#9671]
### Issue Summary

When clicking on the `Cancel scheduled publish` button in the page editor, the response redirects to the page history view instead of returning to the same edit view.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/6379424/201938745-f11bf4e9-9793-47e4-8b8c-3ed938d22e4a.png">

This is a regression when we extracted the unschedule view into a generic class-based view in ae06030016, this method:

https://github.com/wagtail/wagtail/blob/ae0603001638e6b03556aef19bdcfa445f9f74c6/wagtail/admin/views/pages/revisions.py#L163-L167

should've been named `get_next_url`, per the base `RevisionsUnscheduleView` class:

https://github.com/wagtail/wagtail/blob/ae0603001638e6b03556aef19bdcfa445f9f74c6/wagtail/admin/views/generic/models.py#L1029-L1035

### Steps to Reproduce

1. Spin up bakerydemo
2. Schedule a page for publishing
3. Click the "Cancel scheduled publish" button in the page editor
4. Get redirected to the page history view instead of the page editor

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The response should redirect the user to the current page (the page editor), as per the behaviour in 4.0.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes

**Comment by gasman** [comment]
Fixed in #9672
