### ISSUE TITLE
image browser css GRID 

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#9674]
On the danger of **nitpicking** I got the following remark.  Installed fresh project wagtail 4.1 today and uploaded a first image.
When looking at the image browser I noticed that the image is in the middle. Inspecting the CSS panel I notice that the CSS is has css class of "listing.horiz" in there we find a a GRID css that says grid-template-columns: repeat(**auto-fit**,minmax(210px,1fr));

I think it would be better (auto-fill) instead of (auto-fit)

When its "auto-fill" the first image will be centralized. I you upload a second it will both be distributed with lots of whitespace.
With auto-fit the result is more the same. It also looks better on wide screens

It very small issue but might be more consistent result.

**Auto-fit:**
<img width="1677" alt="Images - Wagtail 2022-11-15 16-05-43" src="https://user-images.githubusercontent.com/178425/201953411-4758d9c9-1a69-4f7e-85c9-7b98664f000b.png">

**Auto-fill**
<img width="1659" alt="Images - Wagtail 2022-11-15 16-06-40" src="https://user-images.githubusercontent.com/178425/201953611-37265bda-ea64-46aa-bf6c-6a2bf60b78ff.png">

```
@media screen and (min-width: 50em)
.listing.horiz {
    align-items: flex-end;
    display: grid;
    grid-template-columns: repeat(auto-fill,minmax(210px,1fr));
    justify-items: legacy;
```

**Comment by Theresa-o** [comment]
Thank you for reporting @onno-timmerman, I would investigate this and provide feedback shortly.

**Comment by Theresa-o** [comment]
I have been able to reproduce this using 1 to 3 images to see how the image position changes with the suggestion made by @onno-timmerman and how the various images changed with the original repo code (auto-fit).

These are my observations and suggestions;

I reproduced the images with the original code and - when there is just one image, from my observation, the initial intention was for it to be at the middle. Please correct me if I'm wrong @thibaudcolas @lb- 

![wagimagecenterone](https://user-images.githubusercontent.com/62052443/202704281-9d3fcfeb-9aac-465f-9075-7891e6b0908f.PNG)

I also reproduced this with 2 and 3 images to see how their positions are altered.

![wagimagesfittwo](https://user-images.githubusercontent.com/62052443/202837583-f4601dd7-231c-4d60-a691-f141868e0e41.png)

![wagimagecentertwo](https://user-images.githubusercontent.com/62052443/202704448-bd57ee23-4642-4807-b88c-501c8a355aac.PNG)

![wagimagesfitthree](https://user-images.githubusercontent.com/62052443/202837811-0c1e37cd-9c78-4b2c-b450-b78d3baed5e0.png)

![wagimagecenterthree](https://user-images.githubusercontent.com/62052443/202704436-aa3d70e1-1b23-474d-8238-c786948a70f1.PNG)

I adjusted the code to see how 1 to 3 images would look with the code tweak (grid-template-columns: repeat(auto-fill,minmax(210px,1fr));

![wagimagesonefill](https://user-images.githubusercontent.com/62052443/202837464-368a64ee-9d61-403a-9a69-7c9029902eea.png)

![wagimagesonefillb](https://user-images.githubusercontent.com/62052443/202838011-98dd6c3d-ec96-4eff-b859-344d76e52a87.png)


![wagimagestwofill](https://user-images.githubusercontent.com/62052443/202837678-6b636f70-ec20-4e87-9d5a-d33023bb2eba.png)

![wagimagestwofillb](https://user-images.githubusercontent.com/62052443/202837955-caede322-3fca-42e0-b18f-67d8b6d79e33.png)


![wagimagesthreefill](https://user-images.githubusercontent.com/62052443/202837776-18be82d6-a6f8-4c52-a183-8e17dc0722c8.png)

![wagimagesthreefillb](https://user-images.githubusercontent.com/62052443/202837904-bbb5d822-0e09-4901-9bc6-97d0362ced7c.png)

**Comment by lb-** [comment]
Have confirmed this but flagging as an enhancement instead of a bug.
