### ISSUE TITLE
Wrong widgets when using a custom one

### ISSUE THREAD

**Issue by konsalex** [wagtail/wagtail#9679]
Using Wagtail `4.1.1` but also can confirm that happens to `4.0.4` also.

The issue as can see in the video below is that when I attach a custom widget to a field panel, the native DateTime field is not working as expected

https://user-images.githubusercontent.com/12672541/202036625-47cdac26-a981-4764-b163-2f186986877c.mp4

### Steps to Reproduce

1. Import a simple Django model with a DateTime field
2. Use `@register_snippet` to use it inside Wagtail admin panel 
3. Add to the panels a field with custom width
```
FieldPanel("your_field", widget=RandomWidget),
FieldPanel("your_datetime_field"),
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes
 
### Technical details

-   Python version: `Python 3.10.8`
-   Django version: `django==4.1.2`
-   Wagtail version: `4.1.1`

**Comment by konsalex** [comment]
Also when overriding the FieldPanel of  `your_datetime_field` with a widget of `widget=widgets.AdminDateTimeInput` it is still getting ignored

**Comment by konsalex** [comment]
Update: 
Actually it was working the issue was in the widget and a JS conflict with Jquery
```
@property
    def media(self):
        return forms.Media(js=("https://code.jquery.com/jquery-3.6.1.min.js",))
```

**Comment by gasman** [comment]
@konsalex Glad you got it sorted! Is #9654 the same issue?

**Comment by konsalex** [comment]
Hey @gasman no, the other is using a native one from Django-recurrence which works if the widget is not inline, so a fair guess would be not the same issue?
