### ISSUE TITLE
devdocs.io

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#9683]
Just found out today about devdocs.io. Its nifty to quick lookup docs even if you are offline. Ideal when you are on the road or without electricity/internet. 
However Wagtail is missing. Maybe its a good idea to add it?

https://github.com/freeCodeCamp/devdocs/blob/main/docs/adding-docs.md

**Comment by zerolab** [comment]
@onno-timmerman had a brief look at those instructions, and as far as I can understand it one needs to add a separate scraper to devdocs.

We already support [Dash](https://kapeli.com/dash) and [Zeal](https://zealdocs.org/) via community contributions. 
I am not sure we can accommodate multiple platforms as a core team, but there is nothing to stop the community from owning that, so feel free to contribute to devdocs ;)

**Comment by lb-** [comment]
I'll flag this as a good first issue - anyone is free to pick up this and go ahead with a PR on the external repo.

**Comment by vallabhtiwari** [comment]
Hi @onno-timmerman , I would like to work on this please? This would be my first good first issue so it may take some time. Also, devdocs are written in Ruby but I have never worked with it, but I will figure it out.

**Comment by vallabhtiwari** [comment]
Hi @tajbaba999 , I have already made the PR on the external repo. Soon it would be merged and this issue will be closed.

**Comment by zerolab** [comment]
https://github.com/freeCodeCamp/devdocs/pull/1879 for reference

**Comment by tajbaba999** [comment]
> Hi @tajbaba999, I have already made the PR on the external repo. Soon it would be merged and this issue will be closed.

Thank you for replying can you please help me in my open-source contribution journey? I tried to reach you on Twitter.

**Comment by zerolab** [comment]
@tajbaba999 I would recommend joining the Wagtail Slack - https://github.com/wagtail/wagtail/#-community-support, especially the `#new-contributors` channel.

**Comment by tajbaba999** [comment]
> @tajbaba999 I would recommend joining the Wagtail Slack - https://github.com/wagtail/wagtail/#-community-support, especially the `#new-contributors` channel.

I am already in the slack channel can you help me out me with the good first issues?

**Comment by vallabhtiwari** [comment]
Hi @tomdyson please check devdocs.io and confirm everything is fine. The PR has been merged.

**Comment by lb-** [comment]
Looking good! Thanks @vallabhtiwari 

Did you want to submit a pull request to the Wagtail repo - the 4.2 release notes - that devdocs now has the last main versions listed. 

Something similar to https://github.com/wagtail/wagtail/pull/9460

![Screenshot_20221222-065634](https://user-images.githubusercontent.com/1396140/209001410-211f8ea3-d660-4a83-bc19-ff63b304476c.png)
![Screenshot_20221222-065623](https://user-images.githubusercontent.com/1396140/209001421-1315df14-f40f-499f-81f0-0577316a65f3.png)

**Comment by lb-** [comment]
https://devdocs.io/wagtail/

**Comment by vallabhtiwari** [comment]
Actually I had added support for many versions, from the oldest to the newest including stable and latest.

![Screenshot from 2022-12-22 07-59-13](https://user-images.githubusercontent.com/87356031/209042749-e19d902b-22a1-49a6-b224-5c1a15274dba.png)

![Screenshot from 2022-12-22 08-06-39](https://user-images.githubusercontent.com/87356031/209042977-b85b3058-0e15-46c2-81bc-0f39ab0eca4b.png)

The scrapper in my forked repo [](https://github.com/vallabhtiwari/devdocs/blob/wagtail/lib/docs/scrapers/wagtail.rb) is different than what I had written. How could this be possible?

**Comment by vallabhtiwari** [comment]
[https://github.com/vallabhtiwari/devdocs/commit/624ac21c26c2506407d20bfb0ffd607b8abee5f7](https://github.com/vallabhtiwari/devdocs/commit/624ac21c26c2506407d20bfb0ffd607b8abee5f7)

**Comment by lb-** [comment]
@vallabhtiwari I think it's fine to only have a small subset of versions. Maybe the maintainers of that project want to keep the lists smaller/ only focus on LTS releases. 

Just a reminder to ensure you put up a PR in the Wagtail repo for adding this to the 4.2 release notes.

**Comment by vallabhtiwari** [comment]
Okay, understood...will do it
