### ISSUE TITLE
`django.db.utils.ProgrammingError: can't adapt type 'dict'` against Django main

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#9692]
### Issue Summary

As of https://github.com/django/django/commit/5c23d9f0c32f166c81ecb6f3f01d5077a6084318 in https://github.com/django/django/pull/16297, our tests fails against Django's `main` branch.

That commit separates how `JSONField` and its lookups serialise the data. Previously, the serialisation is handled in `get_prep_value()`, which is database-agnostic. As of that commit, the serialisation is put into `get_db_prep_value()` so that Django can do database-specific serialisation. In addition, the `DataContains` and `ContainedBy` lookups (that support JSON values for the right-hand side) now inherit from `FieldGetDbPrepValueMixin` so that it utilises the `get_db_prep_value()` in `JSONField`.

Meanwhile, our serialisation of `StreamField` is implemented in `get_prep_value()`, as we don't do database-specific handling. For handling non-`StreamValue` values, e.g. `dict` in `JSONField`'s `contains` lookup, we delegate `get_prep_value()` to `JSONField`:

https://github.com/wagtail/wagtail/blob/dd0d2c4b884436802e6464f5479641aa20c6f9d8/wagtail/fields.py#L213-L215

Now that `JSONField.get_prep_value()` does not handle serialisation, this delegation doesn't do anything. As a result, one of our tests that ensure `JSONField` lookups are compatible with `StreamField`s that have `use_json_field=True` has been failing. This shouldn't be a major concern for most users, as we don't have publicly documented use cases for querying `StreamField`s with `JSONField` lookups. However, we do document that the lookups are supported:

https://github.com/wagtail/wagtail/blob/119f288a3cf91775687aafffe19ac4c92bb45e0a/docs/reference/streamfield/blocks.md?plain=1#L13

Thus, it'd be nice to have this fixed.

---

By default, `get_prep_value(value)` is called by `get_db_prep_value(value, connection, prepared=False)` (if it's not overridden), dropping the `connection` reference in the process. Unfortunately, this means we can't change the delegation to `JSONField.get_db_prep_value()` because we no longer have the reference to the `connection` in `get_prep_value()`. We could import from `django.db.connection`, but that's the default connection (Django can have multiple connections, is that something we support?), so it's not ideal.

We can move our `StreamField` serialisation to `get_db_prep_value()`, e.g.

```diff
diff --git a/wagtail/fields.py b/wagtail/fields.py
index 15bdd60027..cac433d8e1 100644
--- a/wagtail/fields.py
+++ b/wagtail/fields.py
@@ -193,7 +193,7 @@ class StreamField(models.Field):
             # Test succeeded, so return as a StreamValue-ified version of that value
             return StreamValue(self.stream_block, value)
 
-    def get_prep_value(self, value):
+    def get_db_prep_value(self, value, connection, prepared=False):
         if (
             isinstance(value, StreamValue)
             and not (value)
@@ -210,9 +210,11 @@ class StreamField(models.Field):
             return json.dumps(
                 self.stream_block.get_prep_value(value), cls=DjangoJSONEncoder
             )
-        else:
+        elif connection:
             # When querying with JSONField features, the rhs might not be a StreamValue.
-            return self.json_field.get_prep_value(value)
+            return self.json_field.get_db_prep_value(value, connection, prepared)
+        else:
+            return json.dumps(value, cls=DjangoJSONEncoder)
 
     def from_db_value(self, value, expression, connection):
         if self.use_json_field and isinstance(expression, KeyTransform):
@@ -240,7 +242,7 @@ class StreamField(models.Field):
 
     def value_to_string(self, obj):
         value = self.value_from_object(obj)
-        return self.get_prep_value(value)
+        return self.get_db_prep_value(value, connection=None)
 
     def get_searchable_content(self, value):
         return self.stream_block.get_searchable_content(value)
```

but that feels risky because that means `get_prep_value()` will no longer be called, so if people extend `StreamField` and override `get_prep_value()` (do people do that?), this potentially breaks that. In addition, it's not consistent with how we mirror a similar API with `get_prep_value()` in our blocks definitions.

On the other hand, we don't really do database-specific serialisation handling anyway, so I'm thinking we can just drop the delegation entirely and just use `json.dumps()` directly:

```diff
diff --git a/wagtail/fields.py b/wagtail/fields.py
index 15bdd60027..7ce0086327 100644
--- a/wagtail/fields.py
+++ b/wagtail/fields.py
@@ -212,7 +212,7 @@ class StreamField(models.Field):
             )
         else:
             # When querying with JSONField features, the rhs might not be a StreamValue.
-            return self.json_field.get_prep_value(value)
+            return json.dumps(value, cls=DjangoJSONEncoder)
 
     def from_db_value(self, value, expression, connection):
         if self.use_json_field and isinstance(expression, KeyTransform):
```

**Comment by gasman** [comment]
Thanks @laymonage - I really appreciate your inside view on this. I can't imagine how long it would have taken to untangle this for myself!

So, to make sure I'm following this correctly:

* Despite StreamField not actually being a JSONField, the `filter(body__contains=value)` still (somehow) correctly identifies `django.db.models.fields.json.DataContains` as the lookup class it should be using.
* In the new Django 4.2 code, this now takes a code path through `FieldGetDbPrepValueMixin`, which calls the field's `get_db_prep_value` method.
* If our field was an actual JSONField, the custom `get_db_prep_value` method would then go on to call `adapt_json_value` and perform the backend-specific handling of the JSON value (which might be stringifying it, or converting it into a `Jsonb` value).
* However, StreamField _isn't_ a JSONField, so it ends up using the base `get_db_prep_value` method from `django.db.models.fields.Field`, which calls our `get_prep_value` method and never ends up doing any adapting of the raw JSON value.

If that's correct:

* Your proposed fix of applying `json.dumps` in `get_prep_value` is essentially replicating Django's old behaviour. However, I'm assuming that the motivation for this change in Django is that psycopg3 no longer accepts a serialized JSON string here, and insists on a `Jsonb` value instead. Doesn't that mean that this is going to break again once people start using psycopg3?
* Could we instead fix this by adding a `get_db_prep_value` method on StreamField that delegates to `self.json_field.get_db_prep_value`? If my theory is correct, this would only come into play for the lookups that use `FieldGetDbPrepValueMixin`, and our normal streamfield operations would continue to use `get_prep_value`.

**Comment by laymonage** [comment]
> * Despite StreamField not actually being a JSONField, the `filter(body__contains=value)` still (somehow) correctly identifies `django.db.models.fields.json.DataContains` as the lookup class it should be using.

Yep, it's because we have these overrides:

https://github.com/wagtail/wagtail/blob/682ed3b21fa6924b1e1a6023f80ce7beea570071/wagtail/fields.py#L130-L138

> * In the new Django 4.2 code, this now takes a code path through `FieldGetDbPrepValueMixin`, which calls the field's `get_db_prep_value` method.

Correct.

> * If our field was an actual JSONField, the custom `get_db_prep_value` method would then go on to call `adapt_json_value` and perform the backend-specific handling of the JSON value (which might be stringifying it, or converting it into a `Jsonb` value).

Correct.

> * However, StreamField _isn't_ a JSONField, so it ends up using the base `get_db_prep_value` method from `django.db.models.fields.Field`, which calls our `get_prep_value` method and never ends up doing any adapting of the raw JSON value.

Yes, but only when the method falls to the `else` block:

https://github.com/wagtail/wagtail/blob/682ed3b21fa6924b1e1a6023f80ce7beea570071/wagtail/fields.py#L196-L215

That happens when `get_prep_value()` is called by the `DataContains`/`ContainedBy` lookups (i.e. the `value` is not a `StreamValue`).

> * Your proposed fix of applying `json.dumps` in `get_prep_value` is essentially replicating Django's old behaviour. However, I'm assuming that the motivation for this change in Django is that psycopg3 no longer accepts a serialized JSON string here, and insists on a `Jsonb` value instead. Doesn't that mean that this is going to break again once people start using psycopg3?

I assume it won't just break (I haven't tried though), because it seems that passing serialised JSON string [still works](https://github.com/psycopg/psycopg/blob/a8168869b762c821e7f07d1fc52d3642f899711e/tests/test_adapt.py#L371), but does mean that it won't let psycopg3 do any further tinkering/optimisations with the data and yes, we'll be replicating Django's old behaviour.

> * Could we instead fix this by adding a `get_db_prep_value` method on StreamField that delegates to `self.json_field.get_db_prep_value`? If my theory is correct, this would only come into play for the lookups that use `FieldGetDbPrepValueMixin`, and our normal streamfield operations would continue to use `get_prep_value`.

Yes, but that means we'll have to add the `if` checks in `get_db_prep_value()`. Let me try...

**Comment by laymonage** [comment]
Updated #9693 with the new approach.
