### ISSUE TITLE
Setting to Pin Minimap by default

### ISSUE THREAD

**Issue by rgs258** [wagtail/wagtail#9704]
### Is your proposal related to a problem?

It'd be great if the Minimap could be loaded open/pinned on each page, and then dismissed by users who want it to only engage on hover. 

### Describe the solution you'd like

The easiest thing is probably to add a global setting to show the Minimap pinned. The better solution would be for the pinned state to be remembered for each user, the same as the left nav.

### Describe alternatives you've considered

Global setting or user selectable.

### Additional context

This would probably also help with accessibility, particularly if the Minimap always started out pinned, and then remembered state like the left nav.

Thanks for your consideration!

**Comment by LeanneEmans** [comment]
Hello. Just to add, we also would really appreciate this feature being developed - in order to give you a better idea of interest. We would like the mini map pinned/open. 
"The easiest thing is probably to add a global setting to show the Minimap pinned."
Thank you! 😄

**Comment by thibaudcolas** [comment]
👋 we’ve implemented this via #10344. The minimap stays expanded until collapsed, and that state is saved between page reloads.
