### ISSUE TITLE
Always-available comment buttons in page editor

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9716]
Discussed during design review with @benenright as a simple improvement to the commenting UX.

- [ ] The "Add" and "view existing comments" buttons could always be available, triggering the "comments" side panel to reveal when clicked.
- [ ] The "Add" button in rich text should also always be there
- [ ] Remove extra spacing to the right of fields

Related: #8147

---

Once we implement this, we need to make sure to do this for the two implementations of comment buttons’ rendering, in Django Templates and JS.

**Comment by zerolab** [comment]
Worth noting this should only be available with `WAGTAILADMIN_COMMENTS_ENABLED = True`

**Comment by Ananjan-R** [comment]
Would it be possible for me to attempt resolving this issue?

**Comment by thibaudcolas** [comment]
Implemented via #8345.
