### ISSUE TITLE
Add docs and tests for adding `publish` permissions for snippets

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#9720]
When we implemented the draft/publishing feature for snippets, the publishing action requires a `publish` permission on the snippet model. However, we haven't explicitly documented and tested that the permission should be set up (and how). We need to add the docs, tests, and possibly a helper function or mechanism within Wagtail to automatically show and create the permission objects and controls in the admin if the snippet model has the draft state feature enabled.

**Comment by robmoorman** [comment]
Just noticed the same. By default no publish permissions are possible to assign in a group. So content editors are not allowed to publish snippets, only create draft versions.

**Comment by gasman** [comment]
Completed in #9711
