### ISSUE TITLE
Wagtail requires django-taggit>=3.0, but setup.py specifies django-taggit>=2.0,<4.0

### ISSUE THREAD

**Issue by hvanness** [wagtail/wagtail#9730]
### Issue Summary

Wagtail requires django-taggit>=3.0, but setup.py specifies django-taggit>=2.0,<4.0

### Steps to Reproduce

Clicking an image tag in the image admin causes a server error:
File "[...]/lib/python3.8/site-packages/wagtail/images/views/images.py", line 116, in get_context_data
    images = images.filter(tags__name=self.current_tag)
*** django.core.exceptions.FieldError: Related Field got invalid lookup: name

The suggested solution at django-taggit was to upgrade from 2.1 to 3.0: https://github.com/jazzband/django-taggit/issues/825

Upgrading to django-taggit==3.0 worked to resolve the issue.

However wagtail/setup.py specifies django-taggit>=2.0,<4.0: https://github.com/wagtail/wagtail/blob/56d0fe8fbc56737c0d7729f1a32ae61a2cac6f1e/setup.py

Please update setup.py.

I have not confirmed that this issue can be reproduced as described on a fresh Wagtail project.

### Technical details

-   Python version: Python 3.8.2
-   Django version: Version: 4.1.2
-   Wagtail version: Version: 4.1
-   Browser version: Chrome 107

**Comment by gasman** [comment]
Hi @hvanness - please see the discussion on #9244. The requirement for django-taggit 3.0 comes from Django 4.1, rather than Wagtail - running Wagtail against an older Django version and django-taggit 2.x is still supported.
