### ISSUE TITLE
Additional control of models indexed with ReferenceIndex

### ISSUE THREAD

**Issue by dkirkham** [wagtail/wagtail#9731]
### Is your proposal related to a problem?

`ReferenceIndex`, and its related management command, `rebuild_references_index` will by default find relationships between all models in one's project, unless the models have the attribute `wagtail_reference_index_ignore` set to `True`.

This method poses a difficulty for 3rd-party apps that are loaded as a package, but even for "in-house" apps, one ends up with some strange Wagtail configuration for an app that has nothing to do with Wagtail.

### Describe the solution you'd like

Another method that excludes apps or selected models is required, which is configured in the project-specific code, and not in the non-Wagtail app.

### Describe alternatives you've considered

Ideas suggested so far:
* a new Django settings attribute (eg. `settings.WAGTAIL_REFERENCE_INDEX_IGNORE`) which is a list of apps, models or regexes thereof; if there is a match, the model isn't indexed
* a function registered within `wagtail-hooks.py` which specifies models to ignore (as a list of apps, models, or regexes)
* a global optional callable that `ReferenceIndex` could use to get a list of models to index
* allow a child class of `ReferenceIndex` to be registered as the version that will be used for the indexing; the developer can then override `model_is_indexable()` within that child class to control the models to be indexed.

**Comment by pelme** [comment]
We upgraded to Wagtail 4.1 last week. (From 2.16. It was amazing to see all new stuff!)

However, we did not catch this change. We run Wagtail together with a fairly large/high traffic Django project. We noticed slow downs and crashes in our other Django code that has nothing to do with Wagtail. Regular `SomeModel.objects.filter(id__in=[1,2,3,4])` caused huge amounts of query activity from these hooks and caused requests to time out / fail. These signal handlers has been creating >20 million rows in `wagtailcore_referenceindex`.

To mitigate this problem we now run `wagtail.signal_handlers.disconnect_reference_index_signal_handlers()` completely disable this and manually truncated the `wagtailcore_referenceindex` table.

Would you consider making this feature opt-in for models instead? Or just do automatic updates to actual Page or Snippet models?

**Comment by jsma** [comment]
Can @gasman or @kaedroho chime in on what the intention was behind the index? It seems to be doing far too much work as pointed out in the previous comments. 

Currently, the only documentation for this feature is in the release notes (@dkirkham has helpfully tried to address the lack of [documentation](https://github.com/wagtail/wagtail/pull/9935)), and it is brief:

> Images, documents and snippets now provide a usage report, listing the places where references to those objects appear. This report is powered by a new ReferenceIndex model which records cross-references between objects whenever those objects to save; this allows it to work more efficiently than the old report available through the WAGTAIL_USAGE_COUNT_ENABLED setting, as well as handling references within StreamField and rich text fields.

I naively assumed `rebuild_references_index` would take "Images, documents and snippets" models and simply do a reverse check for FKs in other models and then scan references in `StreamField` and `RichTextField`s (which only a subset of models have). I was surprised to run the command to see it evaluating _everything_, including models which are not editable/selectable/etc within Wagtail (e.g. Django `LogEntry`, `Permission`, etc.). From my perspective, these are models Wagtail should remain oblivious to and shouldn't require anyone to sprinkle their models with the currently undocumented `wagtail_reference_index_ignore = True` property.

We've been using a custom solution for tracking usages to prevent deletions that would break links on the site so we've had to customize all the `confirm_delete.html` templates to display our custom listing of references. It builds on the Django admin `NestedObjects` collector for following relations with additional code to evaluate `RichTextField` and `StreamField` to find references there as well. This is all done in real-time during the delete confirmation step, so it is of course getting slower as the site grows, but it at least starts from the perspective of only evaluating things that can possibly be dealt with by an editor in the Wagtail editing interface. We don't show editors "references" from irrelevant models (although some of this relies on a hard-coded list of models to ignore e.g. `Revision`, `IndexEntry`, etc.). I'm hoping we can eventually replace our homegrown solution with something that builds on Wagtail's new functionality (which would require addressing #4702 to extend this to page models), but share the concerns mentioned in the previous comments.

Does `ReferenceIndex` need to evaluate everything or can we narrow it's scope to only things managed by Wagtail?

**Comment by gasman** [comment]
The rationale for tracking all models was that the models we're interested in (images / documents / snippets etc) could potentially be referenced from models managed outside of Wagtail, and there are anticipated uses of the reference index where knowing about these is important - for example, knowing that a foreign key reference with `on_delete=PROTECT` is going to prevent an object from being deleted.

However, I accept your point, and the potential upsides to doing this are probably outweighed by the disruption it can cause to non-Wagtail apps.

I've now merged @dkirkham's documentation update from #9935, cherry-picked this into the 4.1.x and 4.2.x branches, and linked it from the relevant part of the 4.1 release notes - so users affected by this in current releases should be able to find the relevant reference to `wagtail_reference_index_ignore` and get themselves unstuck in the short term.

I'd be in favour of changing the behaviour from 5.0 onward so that we only track models that are:

1) built into Wagtail (e.g. Page, Image, Document)
2) user models registered as snippets, ModelAdmin or viewsets (with the ability to opt out of this via either `wagtail_reference_index_ignore` on the model or an option on the viewset)
3) other user models that explicitly opt in (probably via a 'register' function)

**Comment by jsma** [comment]
Thanks @gasman! That sounds like a reasonable plan forward.

> there are anticipated uses of the reference index where knowing about these is important - for example, knowing that a foreign key reference with on_delete=PROTECT is going to prevent an object from being deleted.

We have functionality in our in-house (but real-time/very slow) solution that takes into consideration the on_delete behavior, but I'm curious how this might work with a "cached" ReferenceIndex record, especially if a future migration changes the behavior from e.g. PROTECT to SET_NULL?

Is there a Slack or Github issue/discussion where the future of this feature is being discussed?

**Comment by gasman** [comment]
Fixed in #10364
