### ISSUE TITLE
Workflow information dialog uses hardcoded "Moderators approval" title

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#9734]
### Issue Summary

When a page is submitted to a workflow, we show an "In Moderation" information in the status side panel:

<img width="525" alt="image" src="https://user-images.githubusercontent.com/6379424/204793101-40c073ad-56d5-4517-bd54-2699a95e185b.png">

Upon clicking the "View details" button, a dialog pops up to show the details of the steps within the workflow.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/6379424/204793517-10e59d13-f3b4-42e4-8232-32caac58c611.png">

The dialog uses a hardcoded "Moderators approval" string as the title:

 https://github.com/wagtail/wagtail/blob/a31fa8589edd73b0509e00f7be5cd2776f4bf27b/wagtail/admin/templates/wagtailadmin/shared/side_panels/includes/status/workflow.html#L95

 Meanwhile, workflow names can be customised, and the term "Moderators" may not make sense in the workflow context. For example, my workflow is defined as "Sage's and editors approval":

<img width="734" alt="image" src="https://user-images.githubusercontent.com/6379424/204795746-754de310-12ea-40c7-be3f-d79a9903a5d2.png">

### Steps to Reproduce

1. Spin up bakerydemo
2. Go to Settings > Workflows
3. Rename the default "Moderators approval" workflow to something else
4. Edit a page and submit it to the workflow
5. Click "View details" on the "In Moderation" section of the status panel
6. See that the dialog's title still says "Moderators approval" instead of the new workflow name

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

This has been there since the 4.0 redesign, and I'm not sure if this was an oversight or a deliberate design decision. I'm leaning towards an oversight, as the default workflow name is "Moderators approval", and either the design team or the implementer forgot that the workflow name can be customised.

I don't know whether using the workflow's name would be a good idea though, as it may be long and a bit awkward to show as the title. Maybe just use "Workflow" or "In Moderation" instead?

Also, we might want to rename the "In Moderation" status as well, but I personally think that's fine as-is...

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

**Comment by vupham04** [comment]
Hi, I think that using the workflow name as the title makes perfect sense. 

I see that you mentioned this issue in #9880, and there is a pull request for that issue - I wonder if #9817 will address this issue? If not, I would love to help with this issue.

**Comment by laymonage** [comment]
Hi @vupham04, oops I forgot I already made an issue for this. Yep, #9817 will address this.

**Comment by laymonage** [comment]
Fixed in #9817.
