### ISSUE TITLE
Wagtail 4(.1) breaks mark_safe (HTML) in StaticBlock

### ISSUE THREAD

**Issue by robmoorman** [wagtail/wagtail#9737]
### Issue Summary

Html is not accepted anymore with the new streamfield UI, causing a js error:

```
vendor.js?v=6bc07103:2 Uncaught TypeError: e.replace is not a function
    at t.escapeHtml (vendor.js?v=6bc07103:2:257795)
    at new t (blocks.js?v=6bc07103:1:29649)
    at t.render (blocks.js?v=6bc07103:1:30013)
    at blocks.js?v=6bc07103:1:41011
    at Array.forEach (<anonymous>)
    at new t (blocks.js?v=6bc07103:1:40600)
    at t.render (blocks.js?v=6bc07103:1:42663)
    at e [as constructor] (blocks.js?v=6bc07103:1:13230)
    at new e (blocks.js?v=6bc07103:1:31349)
    at e._createChild (blocks.js?v=6bc07103:1:37098)
```

### Steps to Reproduce

Use StaticBlock with mark_safe in the admin_text

```python
class ExampleBlock(blocks.StructBlock):
    support = blocks.StaticBlock(label=_("Example"), admin_text=mark_safe(_("View an example of this block <a href='%s' target='_blank'>here</a>.")))
```

### Technical details

-   Python version: any compatible version
-   Django version: 4.x
-   Wagtail version: 4.x
-   Browser version: any compatible version

**Comment by zerolab** [comment]
Hey @robmoorman, I see you closed this. Was it because you solved it? Or was it an issue somewhere else? Would be great to get a note, if possible, in case others stumble on this

**Comment by robmoorman** [comment]
He @zerolab had to do something with django 4, changed the lazy translation otherwise with mark_safe. Din't found the root cause, but works. Initial thought was wagtail with the new UI (as nothing in code had changed).

**Comment by zerolab** [comment]
Thank you @robmoorman 🙌 Hopefully this will help others should be caught by this
