### ISSUE TITLE
 python manage.py migrate  failed！ ---in page getstarted

### ISSUE THREAD

**Issue by loveJasmine** [wagtail/wagtail#9742]
I following the guide https://docs.wagtail.org/en/stable/getting_started/tutorial.html

(env) PS C:\wagtail\mysite> python manage.py migrate
SystemCheckError: System check identified some issues:

ERRORS:
wagtailcore.ModelLogEntry: (fields.E180) SQLite does not support JSONFields.
wagtailcore.PageLogEntry: (fields.E180) SQLite does not support JSONFields.
wagtailcore.Revision: (fields.E180) SQLite does not support JSONFields.
wagtailforms.FormSubmission: (fields.E180) SQLite does not support JSONFields.
wagtailusers.UserProfile: (fields.E180) SQLite does not support JSONFields.

**Comment by lb-** [comment]
Wagtail requires JSON1 to be installed with Sqlite as of Wagtail 3.0

https://github.com/wagtail/wagtail/#-compatibility

https://docs.wagtail.org/en/stable/releases/3.0.html#sqlite-now-requires-the-json1-extension-enabled

**Comment by loveJasmine** [comment]
fixed
