### ISSUE TITLE
Can't enter letters with diacritics in RichTextBlock with Firefox

### ISSUE THREAD

**Issue by Ash-Crow** [wagtail/wagtail#9745]
### Issue Summary
With Firefox, hen I try to enter a letter with a separate diacritic in a RichTextBlock, the diacritic appears, then disappears when I type the letter, instead of being replaced by the letter with the diacritic.

If I try to do the same with Chromium, it works normally.

### Steps to Reproduce

1. Start a new project with `wagtail start mysite`
2. Add a Streamfield with a RichTextBlock to the automatically created HomePage model
```
from wagtail.core import blocks
from wagtail.core.fields import StreamField
from wagtail.core.blocks import field_block
from wagtail.models import Page
from wagtail.admin.edit_handlers import FieldPanel


class HomePage(Page):
    body = StreamField(
        [("section", blocks.RichTextBlock()), ("title", field_block.CharBlock())],
        blank=True,
        use_json_field=True,
    )

    content_panels = Page.content_panels + [
        FieldPanel("body", heading="Content"),
    ]
```

3. Make the migration, migrate and follow the rest of the installation tutorial
4. In Firefox, open the Wagtail admin panel and edit the home page
5.  add a "Section" field and type the diacritic (eg "^", "~" or "¨") then the letter (eg "e" or "n")
6.  Repeat step 5 with a "Title"

Result: in the "Section" field, no character is typed (eg, if I wanted to write "même", only "mme" appears)
Expected result: the character with the diacritic should appear in the "Section" field (as it correctly does on the "Title" field)

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details
```
$ python --version
Python 3.10.6
$ pip show django | grep Version
Version: 4.1.3
$ pip show wagtail | grep Version
```

-   Python version: Run `python --version`.
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
-   Browsers versions: Firefox 107.0 (bug is present), Chromium 108 (works normally)
-  Not sure if relevant, but it is tested from Ubuntu 22.04 in French with the "Français (variante)" keyboard disposition.

**Comment by zerolab** [comment]
This looks like a duplicate of #7386.

**Comment by Ash-Crow** [comment]
Sorry, I tried to find if the issue was present by searching "circumflex" and "diacritic", I forgot to look for "accented".

**Comment by zerolab** [comment]
No problems at all. I do hope we get to the bottom of it.
