### ISSUE TITLE
Docs search not working when looking at not-latest and not-stable version

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/wagtail#9752]
### Issue Summary

Search on the documentation site is not working when using a version other than "latest" or "stable".

### Steps to Reproduce

1. Go the the docs site for the "stable" version: https://docs.wagtail.org/en/stable/search.html
2. Enter "test" into the search bar and hit enter.
3. See the search results.
4. Switch the version in the bottom right corner to something other than "latest" or "stable", e.g. "2.16.3": https://docs.wagtail.org/en/v2.16.3/
5. Enter "test" into the search bar and hit enter.
6. See there are **no search results**.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Browser version: Independent of browser (Tried Safari and Firefox on macOS).

**Comment by lb-** [comment]
Pretty sure this already raised https://github.com/wagtail/wagtail/issues/8159

**Comment by gasman** [comment]
Closing as duplicate.
