### ISSUE TITLE
Review footer actions vs. standalone Submit buttons across Wagtail forms

### ISSUE THREAD

**Issue by nicklee** [wagtail/wagtail#9760]
Discuss during design review w/ Ben. Currently some of our forms use the sticky "footer actions" buttons (such as the page editor). Some use Submit / Save buttons inline within the page.

We’d like to review both patterns, potentially change which forms use which.

Specific issue to consider (though it could be considered fixed by the minimap): https://github.com/wagtail/wagtail/issues/6020

**Comment by nicklee** [comment]
also worth considering this previous mobile issue: https://github.com/wagtail/wagtail/pull/5946

**Comment by nicklee** [comment]
Some examples of the current save buttons:

Account page large breakpoint:
![Image](https://user-images.githubusercontent.com/298766/206168005-b70dcccf-ce53-4e6b-82f0-efb713600c7a.png)

Account page small breakpoint:
![Image](https://user-images.githubusercontent.com/298766/206168004-0d15e42e-8fe1-4811-9d24-5f4c44aa94d0.png)

**Comment by nicklee** [comment]
### Current setup

**Disadvantages:**

- Users have to scroll the full height of the page to save their changes
- We have multiple ways of displaying save button functionality, sticky on editor pages, inline within standard form pages

**Advantages:**

- Users have more viewport space on mobile viewport

### Proposed solution

- Uses the sticky version for all forms throughout wagtail, this gives a level of consistency that users will become familiar with, they're already used to this in the editor page, so it won't be a large learning curve
- Users will be able to save from whichever point of the page they are on, speeding up the process of creating small edits
- Secondary actions (Cancel, Delete etc) are stored within the expand button interface which users are familiar with from the editor page setup, this reduces clutter from the page.

**Examples:**

![Image](https://user-images.githubusercontent.com/298766/206170619-0c8ae000-05ae-4392-b85c-f0c58a5f8ac2.png)
![Image](https://user-images.githubusercontent.com/298766/206170620-c00578e7-32fc-4e05-9b97-dad18f65b67c.png)
![Image](https://user-images.githubusercontent.com/298766/206170618-5f9ea3b4-784f-4f64-ad2b-6e70f59f84e4.png)

Note:

This does slightly revert the issue here: https://github.com/wagtail/wagtail/pull/5946, however we've greatly reduced the height that the sticky save bar takes up, as it now only shows the button, meaning it's less intrusive to users.

**Comment by benenright** [comment]
Despite the sticky footer button feeling strangely detached from very short forms on taller viewports, having the action button sticky feels like it offers better consistency and is indeed useful on the longer forms where you might want to save without having to scroll to the bottom.

However this does mean we are going to be hiding some actions that were previously exposed by default. Here's an example: 

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/4907819/211299213-e54542cd-f4b7-4743-ab49-c7f0c960380b.png">

Maybe it's worth some rogue testing with editors on screens like this with dual actions (not sure there are many more tbh) to check people can understand where to now find 'Delete image' once it's hidden in the sticky drop-up menu?

**Comment by nicklee** [comment]
I'm definitely up for usability testing these!

I've attached an example showing where delete could potentially sit:

**Initial view**
![Images (short page)](https://user-images.githubusercontent.com/298766/211325257-92fc5f14-cb6f-4458-8a15-109e5cb1a70d.png)

**expanded view**
![Images (short page) - expanded](https://user-images.githubusercontent.com/298766/211325252-918f37da-9113-459f-a543-7d3a559efaa4.png)

**Alternative delete position**
![Images (short page) - alternative](https://user-images.githubusercontent.com/298766/211325244-1e5d58ff-2ace-4a8c-a403-51a54417d806.png)

It feels like the alternative could be a strong option if we discover users are struggling to locate the delete button when it's condensed within the new fixed button. However I'd like to understand the rational/rules of when we currently put an action in the top right area of the page, as this might go against these @benenright

**Comment by nicklee** [comment]
Designs approved using the same "expanding" button as the editor page's exprience, this is now ready for implementation in the future.
