### ISSUE TITLE
Replace getURLParam with URLSearchParams - JavaScript clean up 

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9765]
### Is your proposal related to a problem?

Currently we have code that uses regex parse the URL location to get the query param (e.g. `q=foo`).

https://github.com/wagtail/wagtail/blob/f31cce6786fbe2a385367a19a16bcdd6d014a5f1/client/src/entrypoints/admin/core.js#L308-L317

### Describe the solution you'd like

* Replace this usage with the URLSearchParams approach used elsewhere in the code - https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get

Essentially, copy this code

https://github.com/wagtail/wagtail/blob/f31cce6786fbe2a385367a19a16bcdd6d014a5f1/client/src/entrypoints/admin/core.js#L281-L282

### Describe alternatives you've considered

* This is a small bit of clean up work that avoids complex functions when the browser now supports this with native APIs, recommend we just get this done.

### Additional context

* This is part of prep work for the Stimulus project, cleaning up things before we pull them out to Stimulus controllers

**Comment by lb-** [comment]
@Lovelyfin00  @thibaudcolas  - as discussed yesterday, this small task would be good to get out of the way.

Note: Turns out other code, within the same file, is already using the Browser API `URLSearchParams` so instead of making a new function that does the same, we should just adopt this approach.

Ready for you to pick up when you have worked through the other starter items Loveth.

**Comment by Lovelyfin00** [comment]
I'll start on it today
