### ISSUE TITLE
Validation error for scheduled publishing expiry is not indicated or easy to find

### ISSUE THREAD

**Issue by danthedeckie** [wagtail/wagtail#9767]
### Issue Summary

If a page has passed it's publishing-schedule expiry date/time, you can no longer save / publish the page, and the validation error is not indicated anywhere except if you know to look inside the **Set Schedule** popup in the "i" section.  You only get a generic "The page could not be saved due to validation errors" message visible.

### Steps to Reproduce
1. set up a blank wagtail project
```sh
wagtail start myproject
cd myproject
./manage.py migrate
./manage.py createsuperuser
./manage.py runserver
```

2. http://localhost:8000/admin/pages/3/edit/
3. "ℹ" icon to get the info-right-sidebar, and in there 'Set Schedule' 
   ![image](https://user-images.githubusercontent.com/1070206/206405325-3961a9b3-7a5c-4b7c-8b19-af84c78cdf4d.png)
4. Set the expires date to the past and click 'Save schedule'  ![image](https://user-images.githubusercontent.com/1070206/206405664-a9636453-2af9-41fb-9118-53a9ff950b31.png)
5. You're now directed back to the page, with the generic error at the top, but no way to know that the validation error is inside the 'Set Schedule' popup. ![image](https://user-images.githubusercontent.com/1070206/206405782-1ec590ac-4292-4a84-b210-d4d32a21f716.png)

### Any other relevant information.

This is especially hard to find on a page which was published, expired eventually, and then you try to edit it later on, not realising that it expired.
eg.
![image](https://user-images.githubusercontent.com/1070206/206406080-14f62f65-1453-45af-a162-4627859387c1.png)

Only after clicking 'i' -> 'Set schedule', can you find the error: 
![image](https://user-images.githubusercontent.com/1070206/206406219-b2b92f92-41cf-42a4-8e28-1ac8ec881baa.png)

At the very least, the "i" icon needs to be highlighted if there's a validation error there - and preferably the "Publishing Schedule" one too?

#### Desired Mockup:

![image](https://user-images.githubusercontent.com/1070206/206407439-73c9dc7f-4532-45ab-8146-d64ac481cb67.png)

Where the "i" is highlighted to show that's where the problem is, likewise the Schedule, and the sidebar is open if there's a problem in that section.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **yes**

### Technical details

-   Python version: 3.8.2
-   Django version: 4.1.4
-   Wagtail version: 4.1.1
-   Browser version: Firefox 107

**Comment by tjwalch** [comment]
It's not even visible if you only open the info panel, you need to click "set schedule" to open the schedule modal to see the error.
