### ISSUE TITLE
Preserve original filename when replacing a document file

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#9776]
Currently, when a document is edited and a new file is uploaded to replace the old one, the sequence of file operations is arranged so that (on a correctly-behaving storage backend) the new file is assigned a distinct filename, in order to bust cached copies of the old document. This was implemented in #3821.

However, the consensus reached on #4567 is that this behaviour is unwanted, particularly as it breaks existing bookmarks / links pointing to either the direct document URL or the 'serve' view, and the desired behaviour is as described in https://github.com/wagtail/wagtail/pull/4567#issuecomment-555224245 - preserve the filename as uploaded, unless it clashes with a _different_ document.

(As a side effect, it also causes the default `AWS_S3_FILE_OVERWRITE=True` configuration of django-storages to be promoted from "broken by design in subtle but potentially catastrophic ways" to "conspicuously and consistently broken", in that we don't just silently overwrite documents with clashing filenames, but delete the just-uploaded document instead.)

ETag support was implemented in #5736, which _hopefully_ makes the cache-busting behaviour of #3821 redundant. I believe the remaining steps are therefore:

* Verify that the caching strategy as implemented in `wagtail.documents.views.serve` allows us to drop the cache-busting-by-renaming mechanism, and fix it if not. In particular, I'm uncertain whether the current combination of ETag and Cache-Control max-age is interpreted as "cache the response for 1 hour; if any further requests for the same URL are made during that hour, send an If-None-Match header so that the server so that it can potentially send a 304 Not Modified response in place of the document" or "cache the response for 1 hour; if any further requests for the same URL are made during that hour then return the document from the local cache instead of hitting the server". IMO the latter is not acceptable - Wagtail out-of-the-box should not be making the assumption that 1 hour is an acceptable timespan to be serving potentially-stale responses.
* Revert the change to `wagtail.documents.views.documents` that was made in #3821, so that the deletion happens before the new document is saved, as you'd expect
* Check that this satisfies the criteria listed in https://github.com/wagtail/wagtail/pull/4567#issuecomment-555224245, and write / update tests to back this up
* ~~If possible, add a [Django system check](https://docs.djangoproject.com/en/4.1/topics/checks/) to warn if a django-storages backend with the default "silently overwrite files" behaviour is active.~~ **(Updated: Now moved to a separate issue #9790)** With this fix in place, reuploading a document will now work correctly on these backends, but there is still no guard against uploading a filename that clashes with some other document. Arguably Wagtail could mitigate this by performing its own "does this file exist" check, but this would just be duplicating the check that a correctly-conforming backend _should_ be doing, and I don't think it's Wagtail's responsibility to overrule broken backends that have deliberately chosen to do the wrong thing.

**Comment by GeekGawd** [comment]
Hi! @gasman I would like to work on this issue and will need some guidance on this.

**Comment by gasman** [comment]
@GeekGawd I don't have capacity to provide mentoring support at this time, sorry. In the description above I've given a detailed breakdown of the steps required - in particular, the first step really needs some independent research, so it's not really something I can give step-by-step directions on.

**Comment by GeekGawd** [comment]
Current progress on the issue...

1) The current etag implementation in `wagtail.documents.views.serve` doesnt work, 304 response is not returned. Current breaking behaviour is such that the file when uploaded two times, caches the file with respect to the filename, as the etag is the same with respect to filename.

To Reproduce:

- Upload a file to documents
- Link it to something in wagtail, for example pages
- Download the file from the wagtail page... This is important as a etag will be generated for the file
- Change the file content without changing the filename. (File will be stored with a new filename)
- Change the file content again without changing the filename. (filename in wagtail will revert back to original_filename)
- Download the file the file from the linked wagtail page. (File will have the contents of the first upload)

https://user-images.githubusercontent.com/89455838/208591475-7179ddf3-476c-43d1-bf6c-6a01ec6fdeba.mp4

Proposal to a solution:

Etag surprisingly already works in the http even if I remove the @etag decorator. If the file hasn't changed and i call download the file again it gives back 304 Not_Modified status code. The only thing we need to look out for in that case is lets say the admin has changed the file, and the user is still on the old version of the page, the url will give him/her a 404 not found error, as the url would have changed. 

2) If I am not wrong that just require me to shift the logic of `self.original_file.storage.delete(self.original_file.name)` from file `images\forms.py` line 56 to `views\documents.py` right?

**Comment by gasman** [comment]
@GeekGawd Thanks for looking into this! I can replicate the behaviour you describe, but I think this is the fault of the Cache-Control header, not the Etag logic: on the third download, the `./manage.py runserver` console shows that the server isn't being sent a request at all - evidently the browser is returning the version from its local cache as permitted by the max-age=3600 setting, i.e. the second of the two possibilities I mentioned earlier:

> "cache the response for 1 hour; if any further requests for the same URL are made during that hour then return the document from the local cache instead of hitting the server". IMO the latter is not acceptable - Wagtail out-of-the-box should not be making the assumption that 1 hour is an acceptable timespan to be serving potentially-stale responses.

I think the correct course of action is to remove the `@cache_control` decorator completely - setting `max_age=0` as you did in #9820 is probably equivalent, but I think we also want to get rid of the `public=True` since Wagtail documents can be made private and shouldn't be cached in a shared cache.

> Etag surprisingly already works in the http even if I remove the `@etag` decorator.

Not sure what you mean by "in the http" - do you mean using a real webserver rather than `./manage.py runserver`? When I test via `./manage.py runserver`, I do see an Etag header in the response when the decorator is in place, and not when the decorator is missing, which matches what I would expect.

> If I am not wrong that just require me to shift the logic of `self.original_file.storage.delete(self.original_file.name)` from file `images\forms.py` line 56 to `views\documents.py` right?

The change you made in #9820 (moving the `super().save(commit=commit)` line in documents/forms.py) is correct, I think, although I'll need to double-check that.

Will do some final testing tomorrow (mainly, checking that the browser does actually take advantage of the ETag when there's no cache-control header) and hopefully merge after that.

**Comment by gasman** [comment]
Completed in #9820.
