### ISSUE TITLE
DecimalBlock return value crashes when value is null  

### ISSUE THREAD

**Issue by fodmap-technical** [wagtail/wagtail#9777]
### Issue Summary

When a decimal block is created with a required field of false, Wagtail assumes that the value is always present and tries to return the value as a decimal. 

### Steps to Reproduce

1. Create A DecimalBlock to a model `block_metric_weight = DecimalBlock(required=False, decimal_places=2)`
2. Make Migrations
3. Run Migrate
4. Add a record for the model with null value for the decimal field
5. The server will crash and display "conversion from NoneType to Decimal is not supported"

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Possible fix

Change line of codes in field_block

Current version: 
`def to_python(self, value):
        return Decimal(value)`

Proposed Edit:
`def to_python(self, value):
    if value is None:
        return value
    else:
        return Decimal(value)`

**Comment by lb-** [comment]
I am able to reproduce this
<img width="962" alt="Screen Shot 2022-12-13 at 7 40 12 am" src="https://user-images.githubusercontent.com/1396140/207160393-16535b64-e5fe-401b-aa97-9d18522e2034.png">

Quick bakerydemo snippet for reference

```
class StandardPage(Page):
    """
    A generic content page. On this demo site we use it for an about page but
    it could be used for any type of page content that only needs a title,
    image, introduction and body field
    """

    units =  StreamField(
        [('metric', DecimalBlock(required=False, decimal_places=2))], blank=True, use_json_field=True
    )
    content_panels = Page.content_panels + [
        FieldPanel("introduction"),
        FieldPanel("body"),
        FieldPanel('units'),
        FieldPanel("image"),
    ]
```

**Comment by lb-** [comment]
Fixed via https://github.com/wagtail/wagtail/pull/9781
