### ISSUE TITLE
Documentation build in CI does not flag some kinds of errors

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9778]
### Is your proposal related to a problem?

When I am editing the documentation and I build the docs locally I often see that there are missing images or references that somehow are not being flagged at the CI level.

### Describe the solution you'd like

All warnings should fail the CI build for documentation.

### Describe alternatives you've considered

* We somehow change these warnings to errors (which may fail the CI)
* We just ignore these and hope that developers see these and fix these up manually

### Additional context

Example output from December 2022 - note that there are missing images and missing links (many happened when we moved the guide out).

* /code/wagtail/docs/advanced_topics/add_to_django_project.md:98: WARNING: 'myst' reference target not found: inserting_videos
* /code/wagtail/docs/advanced_topics/deploying.md:70: WARNING: 'myst' reference target not found: collection_privacy_settings
* /code/wagtail/docs/reference/contrib/redirects.md:36: WARNING: 'myst' reference target not found: managing_redirects
* /code/wagtail/docs/reference/pages/panels.md:1: WARNING: undefined label: 'commenting'

Full stack

```
root@e4e1af4133fa:/code/wagtail# cd docs/
root@e4e1af4133fa:/code/wagtail/docs# make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v5.3.0
Initializing Spelling Checker 5.4.0
making output directory... done
loading intersphinx inventory from https://docs.djangoproject.com/en/stable/_objects/...
intersphinx inventory has moved: https://docs.djangoproject.com/en/stable/_objects/ -> https://docs.djangoproject.com/en/4.1/_objects/
myst v0.18.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=[], disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=None, heading_slug_func=None, footnote_transition=True, words_per_minute=200, sub_delimiters=('{', '}'), linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area')
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 266 source files that are out of date
updating environment: [new config] 266 added, 0 changed, 0 removed
reading sources... [100%] topics/writing_templates                                                                                                     
/code/wagtail/docs/extending/extending_draftail.md:152: WARNING: image file not readable: _static/images/draftail_entity_stock_source.gif
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] topics/writing_templates                                                                                                      
/code/wagtail/docs/advanced_topics/add_to_django_project.md:98: WARNING: 'myst' reference target not found: inserting_videos
/code/wagtail/docs/advanced_topics/deploying.md:70: WARNING: 'myst' reference target not found: collection_privacy_settings
/code/wagtail/docs/reference/contrib/redirects.md:36: WARNING: 'myst' reference target not found: managing_redirects
/code/wagtail/docs/reference/pages/panels.md:1: WARNING: undefined label: 'commenting'
/code/wagtail/docs/reference/settings.md:386: WARNING: 'myst' reference target not found: collection_privacy_settings
/code/wagtail/docs/releases/2.10.rst:20: WARNING: undefined label: 'managing_workflows'
/code/wagtail/docs/releases/2.10.rst:154: WARNING: undefined label: 'managing_workflows'
/code/wagtail/docs/releases/2.11.rst:142: WARNING: undefined label: 'ie11'
/code/wagtail/docs/releases/2.13.rst:34: WARNING: undefined label: 'commenting'
/code/wagtail/docs/releases/4.2.md:72: WARNING: 'myst' reference target not found: performance
/code/wagtail/docs/topics/snippets.md:413: WARNING: more than one target found for 'myst' cross-reference permissions: could be :std:ref:`Permissions` or :std:doc:`Permissions` [myst.ref]
/code/wagtail/docs/topics/writing_templates.md:63: WARNING: 'myst' reference target not found: inserting_images
generating indices... py-modindex done
writing additional pages... search done
copying images... [100%] _static/images/image_filter_fill_focal_close.png                                                                              
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 13 warnings.

The HTML pages are in _build/html.

Build finished. The HTML pages are in _build/html.
```

**Comment by lb-** [comment]
There are some issues that I cannot easily resolve, as noted, these are not flagged in the CI.

```
/code/wagtail/docs/advanced_topics/deploying.md:61: WARNING: 'myst' reference target not found: django:topics/cache/index
/code/wagtail/docs/extending/rich_text_internals.md:18: WARNING: more than one target found for 'myst' cross-reference rich_text: could be :std:ref:`RichTextField` or :py:func:`wagtail.test.utils.form_data.rich_text` [myst.ref]
/code/wagtail/docs/releases/5.2.md:400: WARNING: Could not lex literal_block as "html+django". Highlighting skipped.
/code/wagtail/docs/topics/images.md:297: WARNING: more than one target found for 'myst' cross-reference rich_text: could be :std:ref:`Rich Text (HTML)` or :py:func:`wagtail.test.utils.form_data.rich_text` [myst.ref]
```

I tried changing the django topics one to `django:topics/cache/` and it did not work, just flagged a different error.

I also have no idea what's causing the `html+django` issue in one code snippet, I tried a bunch of stuff and cannot see any obvious reason why this would somehow not work.

**Comment by lb-** [comment]
Sorry. This issue still exists, it's about getting our CI to check for documentation build errors.

**Comment by lb-** [comment]
Had a look at this in the context of  https://github.com/wagtail/wagtail/pull/11194

I think we can add one line to the docs make file and this will fail when there are errors.
`docs/Makefile`

```diff
# You can set these variables from the command line.
--SPHINXOPTS    =
++SPHINXOPTS    = -W --keep-going -n
SPHINXBUILD   = sphinx-build
PAPER         =
BUILDDIR      = _build
```

https://stackoverflow.com/questions/38048945/how-to-turn-warnings-into-errors-when-building-sphinx-documentation-with-setupto

@NXPY123  - might be a good item to do after the MyST update?

**Comment by NXPY123** [comment]
I'll look into this 🙌

**Comment by NXPY123** [comment]
> Had a look at this in the context of #11194
> 
> I think we can add one line to the docs make file and this will fail when there are errors. `docs/Makefile`
> 
> ```diff
> # You can set these variables from the command line.
> --SPHINXOPTS    =
> ++SPHINXOPTS    = -W --keep-going -n
> SPHINXBUILD   = sphinx-build
> PAPER         =
> BUILDDIR      = _build
> ```
> 
> https://stackoverflow.com/questions/38048945/how-to-turn-warnings-into-errors-when-building-sphinx-documentation-with-setupto
> 
> @NXPY123 - might be a good item to do after the MyST update?

Should I add this as part of #11194? It would prevent the docs from being built until all the warnings are fixed though.

**Comment by lb-** [comment]
@NXPY123 I think we should try to get the upgrade into core first and then tackle this issue (CI checks) along with any other clean up. Thanks for looking into it.

**Comment by lb-** [comment]
@NXPY123 this should be good for you or someone else to pick up now that https://github.com/wagtail/wagtail/pull/11194 is done.  

Than you so much.
