### ISSUE TITLE
Custom permission not visible in group dashboard

### ISSUE THREAD

**Issue by ghost** [wagtail/wagtail#9786]
I am using the below code and the permissions are not listing in the group dashboard

```py
@hooks.register('register_permissions')
def view_custom_permission():
    return Permission.objects.filter(codename="view_custom_permission")

@hooks.register('register_permissions')
def register_permissions():
    app = 'test'
    model = 'test'
    return Permission.objects.filter(content_type__app_label=app, codename__in=[f"custom_{model}"])
```

**Comment by laymonage** [comment]
Thanks for the report!

Have you confirmed that those `Permission` objects exist in the database? If they do, they should normally show up under the "Object permissions > Custom permissions" section. Or, if you used Wagtail's `Admin` content type, it should show up under the "Other permissions" section.

I couldn't reproduce your issue, so if you could provide a minimal reproduction of the issue, that'd be great.

**Comment by praveenwissend** [comment]
My wagtail_hooks.py code
`from django.contrib.auth.models import Permission
from wagtail import hooks


@hooks.register('register_permissions')
def view_custom_permission():
    return Permission.objects.filter(codename="view_custom_permission")

@hooks.register('register_permissions')
def register_permissions():
    app = 'wagtailadmin'
    model = 'admin'
    return Permission.objects.filter(content_type__app_label=app, codename__in=[f"custom_{model}"])
`

![image](https://user-images.githubusercontent.com/47108694/207528832-1083a6c7-cb99-4c72-871b-0057a9d69bb2.png)

not able to view the custom permission @laymonage

**Comment by laymonage** [comment]
Yes, I can see your hooks, but the question is: do those `Permission` objects you're querying exist in the database?

To confirm, run:

```sh
python manage.py shell
```

And let us know the output for the following:

```pycon
>>> from django.contrib.auth.models import permission
>>> Permission.objects.filter(codename="view_custom_permission")
>>> # What's the output?
>>> Permission.objects.filter(content_type__app_label=app, codename__in=[f"custom_{model}"])
>>> # What's the output?
```

**Comment by praveenwissend** [comment]
getting empty queryset @laymonage 
![image](https://user-images.githubusercontent.com/47108694/207558362-6584729f-f767-4a47-90fe-5a6d31fbc41f.png)

**Comment by laymonage** [comment]
There's the problem :)

You need to create the `Permission` objects first, e.g. using `Permission.objects.create()`. See [Django docs](https://docs.djangoproject.com/en/4.1/topics/auth/default/#programmatically-creating-permissions) for more details.

**Comment by praveenwissend** [comment]
ah ok thanks :) @laymonage
