### ISSUE TITLE
Validating image duplicates in admin causes issues with image renditions using AWS S3 as file storage.

### ISSUE THREAD

**Issue by marekarendt** [wagtail/wagtail#9789]
### Issue Summary
It looks like feature that validates duplicates of images added to wagtail-admin causes issues with renditions when using AWS S3 as file storage.
Below some screenshots :
<img width="1980" alt="adding duplicated image" src="https://user-images.githubusercontent.com/54432734/207309226-382fdc7a-c725-4741-81e5-258b9679a883.png">

<img width="2292" alt="Images admin preview" src="https://user-images.githubusercontent.com/54432734/207309044-57187c58-38e7-46a2-bbb0-a4c227c8c491.png">
<img width="2292" alt="Image edit view" src="https://user-images.githubusercontent.com/54432734/207309248-be15c941-1ca1-46a7-b18a-75db5f5fa39b.png">

### Steps to Reproduce

1. add any valid image to admin
2. try to add the same image
3. use "delete new image" button to prevent duplicates
4. go to "Images" tab - renditions are broken 
5. go to "edit view" - renditions are broken

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I've tested this using default `django.core.files.storage.FileSystemStorage` and everything works correctly. 

### Technical details

-   Python version: 3.10.5
-   Django version: 4.0.8
-   Wagtail version: 4.1.1
-   boto3: 1.26.27

**Comment by gasman** [comment]
Standard question for anything involving S3 and file deletion - have you set `AWS_S3_FILE_OVERWRITE=False` in your settings? (If you don't have this set, django-storages defaults to silently overwriting files on upload, which violates the Django storage spec and breaks various features in Wagtail.)

**Comment by marekarendt** [comment]
Thanks for quick response ! Adding this setting helped, we missed that.
