### ISSUE TITLE
Search appears to be broken on documentation site

### ISSUE THREAD

**Issue by RandomJo** [wagtail/wagtail#9798]
### Issue Summary

Search appears to be completely broken for the documentation site. I've entered several different search terms that I can see on documentation pages, and nothing seems to bring back a result.

<img width="596" alt="Screen Shot 2022-12-16 at 10 08 58 AM" src="https://user-images.githubusercontent.com/230458/208141083-bb88b073-9faa-4446-bcc5-7552537cfc2a.png">

### Steps to Reproduce

1. Go to Wagtail documentation
2. Type "button" in the search bar
3. You'll see "no results" listed as you type and also if you hit enter to go to the search page

### Technical details

-   Documentation version: 4.1.1 (but I believe it's occurring for all versions)
-   Browser version: Chrome 108 (also tried in Firefox)

**Comment by gasman** [comment]
Thanks for reporting! This is covered by the existing issue #8159.
