### ISSUE TITLE
Page type report

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/wagtail#9809]
### Is your proposal related to a problem?

I find it hard during development to find example pages for certain page types. 
I need to find a page based on type frequently, e.g. to investigate bug reports or plan new features for certain pages. 

### Describe the solution you'd like

A screen that is easy to reach, e.g. a report, that displays all pages and is either grouped or filterable by page type. 

### Describe alternatives you've considered

There is a similar view that can be reached when using the "add child page" screen. 
But, in many cases the page types have only certain allowed parents or a max number of instances. 
This means I have to hunt down a possible parent page first, then go to the "add child page" screen and then click on the report screen for that page type.

**Comment by tbrlpld** [comment]
cc @helenb

**Comment by thibaudcolas** [comment]
Hey Tibor, thank you for the suggestion. Reports are one of the parts of the CMS that are most customisable – I’m not sure how we decide which reports to have available out of the box or not, but do you think an alternative would be to create this per site, or as a third-party package?

One potential point of concern if we did this as a core feature is that we’d need to take page permissions into account. As much as possible, users should only be able to see page instances from parts of the page tree they have access to. I’m not entirely sure how well supported this is within the reporting APIs.

**Comment by tbrlpld** [comment]
Thanks for your consideration @thibaudcolas. The permissions question is a great point. 

A report was just one idea how this could be implemented. 

I have opened the issue because this has been coming up in many conversations and I feel the need on basically every project. Even if the idea is rejected from core, I think is helpful to have the idea and considerations discoverable in the repo.

A third party package is definitely an option that I would be happy to take on 👍

**Comment by thibaudcolas** [comment]
Done in #10850 :) Shipping in Wagtail 6.0.
