### ISSUE TITLE
Wagtail tutorial template location results in error

### ISSUE THREAD

**Issue by spencerpro** [wagtail/wagtail#9837]
In the tutorial "Docs:Getting started:Your first Wagtail site:Blog Index and Posts (https://docs.wagtail.org/en/v4.1.1/getting_started/tutorial.html#blog-index-and-posts) it states "To create a template for the BlogIndexPage model, create a file at the location blog/templates/blog/blog_index_page.html.", but that results inTemplateDoesNotExist error. Looking at the Template-loader postmortem, "Django tried loading these templates, in this order:" it does not include the path given in the turorial (above). If I move the template to one of the locations in the path, eg. mysite/home/templates or myrinath/myrinath/templates it works fine. Did I miss a step somewhere or is the tutorial wrong?

**Comment by allcaps** [comment]
Is blog in installed apps?

> Add the new blog app to INSTALLED_APPS in mysite/settings/base.py.
