### ISSUE TITLE
Labels and ordering of items within 'streamfield block chooser'

### ISSUE THREAD

**Issue by nicklee** [wagtail/wagtail#9840]

**Comment by nicklee** [comment]
I've produced two examples of the new two column streamfield block chooser.

**1. Order as chosen by the team that build the items** 

This allows for prioritisation based on how important the developer feels the element is. The downside being that new users won't be familiar with the order, meaning it's more difficult to scan.

![Image](https://user-images.githubusercontent.com/298766/210381235-473361e0-22f2-414d-95c5-e3a8e780b999.png)

**2. Alphabetical** 

Ordered A-Z, meaning it's easier for users to scan the list. We'll want to consider whether the order of items should go across the row, or down the column. The design shows across the row, as the English language is left to right, however there are articles which suggest lists like this can be easier to scan when they go down the column.

![Image](https://user-images.githubusercontent.com/298766/210381234-3b6a74f1-cfaf-4623-b009-2e5638bd1c00.png)

Both versions have the formatting options first (heading, lists, image, embed etc), followed by streamfield blocks, then actions.

You'll also note that the alphabetical option only has a single item shown for 'heading'. This ensures the dropdown is as compact as possible. The thinking is that clicking this would make the selected text, or next typed text, a h2 (the most commonly used heading type when within a RTE), but that the user could change this via the floating formatting bar, which would have the h2, h3, h4 options in (and potentially h5).

**Comment by gasman** [comment]
The standard StreamField block menu lists the available blocks in the order they are defined in the code. There's also an option to group them under subheadings (see `group` under https://docs.wagtail.org/en/stable/reference/streamfield/blocks.html#block-options), in which case the subheadings will be ordered alphabetically (but within each subheading the blocks still appear in definition order).

There have been some requests for making the order more configurable (https://stackoverflow.com/questions/74488997/is-there-a-way-to-order-wagtail-blocks-in-the-admin-panel/74489612#74489612 - I also recall someone raising the point that if you progressively build up the list of blocks by subclassing StreamBlock several levels deep, the blocks added in the sub-sub-class always get added to the end of the list with no way to override that).

I don't know how closely the StreamField menu on rich text blocks follows these conventions, but it's safe to say that developers want to be able to specify this order, and will not welcome it being forced into alphabetical order.

**Comment by nicklee** [comment]
Thanks @gasman, it sounds like for the time being ordering will be in the developers hands then. 

I wonder if in the future we could order alphabetically by default unless a specific override flag is added? 

I'd be interested to know how developers usually order these, is it done by how important they feel the block is? how often they think it'll be used? I guess every build will be slightly different.

**Comment by gasman** [comment]
> I wonder if in the future we could order alphabetically by default unless a specific override flag is added?

That would hurt developer experience and discoverability a lot. If a developer feels that the list needs to be reordered, and they can see it matches the order defined in the code, it's clear what they need to do (and it will rarely be more than a one-minute job to do so). However, if Wagtail imposes alphabetical ordering by default, then the developer has to hunt in the documentation to find out how to turn that off.

In practice, I think that most of the time a sensible order will emerge naturally even if the developer isn't consciously thinking about it, simply because they'll generally implement the most important blocks (headings, paragraphs...) first and thus put them first in the list.

**Comment by nicklee** [comment]
Thanks @gasman, with this in mind it sounds like we're best keeping the way ordering works the same as currently. 

Ultimately this is the developer's decision, from an editor experience perspective we'd recommend that items are ordered alphabetically as this aids users when they are scanning for a specific block, but understand that sometimes there is a good reason to order them differently.
