### ISSUE TITLE
Updating documentation for contributing to wagtail for Windows Users

### ISSUE THREAD

**Issue by Nazi-pikachu** [wagtail/wagtail#9847]
### Pertinent section of the Wagtail docs
[Setting up the Wagtail codebase
](https://docs.wagtail.org/en/stable/contributing/developing.html#setting-up-the-wagtail-codebase)

### Details

Current documentation on setting up the wagtail codebase especially on windows machine without using docker is not very clear and intutive to a newcomer. I propose to update this section of the documentation to make it more friendly for the new developer to contribute.

**Comment by lb-** [comment]
Note that we already have a similar discussion here https://github.com/wagtail/wagtail/discussions/9557

I'll close this for now as it does not add anything new to the known issues. Any details and specific suggestions would be appreciated - on the discussion for now if that's ok.
