### ISSUE TITLE
Implement new userbar designs

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9866]
New treatment of the userbar’s visual design to bring it in line with the visual language of other parts of the CMS.

Screenshot (incl. unrelated prototyping on the accessibility checker):

![Image](https://user-images.githubusercontent.com/877585/211531594-800663ee-86c6-4b03-8f86-41c2f1e4ad51.png)

Figma link: [Wagtail Design System - Wagtail 4.2 - Sa11y](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=9710%3A92870&t=M2PUepD2VWfgxaH1-4)

---

As part of this, we’ll also need to make sure the focus styles work as expected for items within the userbar. It seems we broke this in #9816. If we don’t get to the new designs in time for Wagtail v4.2, we will need to make a bug fix change just for this (`@apply w-outline-offset-inside`).

**Comment by albinazs** [comment]
figma link doesn't work for me, is there any other way to view the files?
