### ISSUE TITLE
Implement sticky form actions across all forms

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9869]
### Is your proposal related to a problem?

See #9760 for further context. Blocked by #9030, #7366. On some of the forms in the CMS, we have the "Submit" and other action buttons at the end of the form, while on others we use a "sticky footer actions" component. For consistency, we’d like to switch all forms to "sticky actions" wherever possible.

### Describe the solution you'd like

- The Save/Submit button of a form should be sticky at the bottom of the screen.
- Any secondary action buttons ("Delete") should live within the dropdown

### Describe alternatives you've considered

See UX research in #9760.

**Comment by Nazi-pikachu** [comment]
Hi @thibaudcolas i would like to work on this issue, is it up for grab?

**Comment by thibaudcolas** [comment]
@Nazi-pikachu no as you can see in my description above this is blocked by two other issues.
