### ISSUE TITLE
Moderation workflow needs feedback

### ISSUE THREAD

**Issue by mhnbcu** [wagtail/wagtail#987]
When rejecting a page after moderation there is no mechanism in Wagtail to either [A] annotate the content or [B] provide a general comment to accompany the e-mail to an editor. 

Currently the e-mail received using the demo is such:

```
The page "A new blog page" has been rejected.

You can edit the page here: http://localhost:8111/admin/pages/24/edit/

Edit your notification preferences here: http://localhost:8111/admin/account/notification_preferences/
```

With option [B] this could instead be more useful:

```
The page "A new blog page" has been rejected with the following comments.

---
The title is too generic.

---

You can edit the page here: http://localhost:8111/admin/pages/24/edit/

Edit your notification preferences here: http://localhost:8111/admin/account/notification_preferences/
```

There are a few other wishlist concepts that would make the moderation workflow pretty amazing:
1. Option to receive a screenshot attachment of the preview (could use phantomjs or something similar) so that in times where one cannot login they can see a preview.
2. Option to have rejection email with Reply-To set to the moderator that performed the moderation and other moderators on CC so the editor can directly reply for any discussion that will occur over e-mail.
3. Option to have a markdown version of the page in the e-mail so a moderator can review the page without a visual preview or logging into the CMS.
4. Option to Approve / Reject by response to e-mail.

**Comment by thibaudcolas** [comment]
Potentially related: https://github.com/wagtail/rfcs/pull/24 (it's for revisions of accepted changes, not for rejections, but is also about extending the publication workflow).

**Comment by thibaudcolas** [comment]
Wagtail 2.10 ships with big improvements to moderation workflows, so I’m going to close this on the basis that it’s either addressed, or no longer relevant.

Release notes: https://docs.wagtail.io/en/latest/releases/2.10.html#what-s-new

**Comment by zerolab** [comment]
Relevant bit of docs related to notifications: https://docs.wagtail.io/en/latest/advanced_topics/custom_tasks.html#adding-notifications
