### ISSUE TITLE
Notification emails do not load the correct tab when linking to the account page

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9873]
### Issue Summary

When clicking the link in Wagtail notifications to edit your notification preferences, the link does not correctly load the notifications tab by default.

<img width="1438" alt="Screen Shot 2023-01-11 at 6 38 33 am" src="https://user-images.githubusercontent.com/1396140/211658051-c0d1a9f8-3428-45d2-a2b5-5585847a0144.png">

### Steps to Reproduce

1. Set up a Wagtail instance where there is at least one non-admin user that is part of a workflow moderation group
2. As a different user (maybe the admin) submit a new page for moderation/approval
3. Check the email (or logs) of the non-admin user to see that an email should be sent (e.g. `The page "Manage snippets" has been submitted to workflow "Moderators approval"`)
4. In the email there should be a link to edit the notification preferences (e.g. `Edit your notification preferences here: https://guide.wagtail.org/admin/account/#notifications`)
5. Click the link
6. Expected: The link should take the user to their account page in Wagtail and show the notifications tab
7. Actual: The account page loads but is on the 'profile' tab

#### Additional details

* Note: the correct URL should be `#tab-notifications` not `#notifications`
* wagtail/admin/templates/wagtailadmin/notifications/base.html
* wagtail/admin/templates/wagtailadmin/notifications/base.txt
* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

-   Python version: 3.9
-   Django version: 3.2
-   Wagtail version: 4.0.4
-   Browser version: Firefox 108 on MacOS 12.6.2

**Comment by laymonage** [comment]
I can confirm that this is an issue.
