### ISSUE TITLE
Moderation workflow needs stages or capability for multiple review

### ISSUE THREAD

**Issue by mhnbcu** [wagtail/wagtail#988]
We have moderators that perform different "types" of moderation. In our case we sometimes have content that will need to be approved by a legal person, a senior editor and a senior management person. In these cases being able to indicate that a content requires approval from multiple moderator roles (in additional to editorial moderation) is desirable for example:

```
Settings Tab
Additional Moderation: [ x ] legal [ _ ] leadership
```

This is one way to satisfy cases where editorial approval alone would not publish content that requires approval from other roles / moderator types.

**Comment by thibaudcolas** [comment]
See [workflows](https://docs.wagtail.io/en/stable/releases/2.10.html#moderation-workflow) from Wagtail 2.10.
