### ISSUE TITLE
Document 404 "doc.filename" does not match "document_filename" when uppercase letters involved

### ISSUE THREAD

**Issue by tannerrimes12** [wagtail/wagtail#9883]
On Wagtail 4.1.1, I'm running into and issue on both dev and prod with Documents. 

Prod is using S3 and uploading documents correctly to the bucket, however when I try to view this document on the server I get a 404. Same case if I try to view this locally as well.

I noticed only one of documents is loading and the only difference is it's filename is all lowercase.

I did some debugging and inside 'wagtail.documents.views.serve' I'm raising this error inside the serve() function.

```
if doc.filename != document_filename:
        raise Http404("This document does not match the given filename.")
```

Where
``` 
doc.filename = 'Guide-To-Installation.pdf'
document_filename = 'guide-to-installation.pdf'
```

My workaround is to overwrite that file locally and change the above to:
```
# check with doc.filename lowercase
if doc.filename.lower() != document_filename: 
    raise Http404("This document does not match the given filename.")
```
and it proceeds.

However this keeps me from getting updates to this functionality in the future.

**Comment by gasman** [comment]
Thanks for the report! Please could you try replicating this on a newly-created Wagtail project, and let us know the exact steps that lead up to the error, including installing the package that provides the S3 backend (`django-storages` I assume?) and any changes made to the project settings? This will greatly assist us in determining whether this is a Wagtail bug or something specific to your project.

**Comment by gasman** [comment]
Closing due to lack of updates.
