### ISSUE TITLE
Settings settable Abrastract Base Page

### ISSUE THREAD

**Issue by TonisPiip** [wagtail/wagtail#9897]
### Is your proposal related to a problem?

Wanting to change anything about the fields in the Page model.

Other projects (including Wagtail plugins): import the abstract class via a string defined in settings. 
This allows for customization of built-in fields, help-texts, defaults etc.  One thing which I'd want to do is change Slug field into an AutoSlugField. But can't as it's on the Page, and if you're inheriting from  a non-abstract model, you can't modify its fields, as they are on another table, and accessed via a JOIN.  

### Describe the solution you'd like

Have AbstractPage have more fields which are being defined in Page (title, slug etc). 
AndOr have the the Page class inhert from a class which is able to override the native wagtail fields. 

. Example from puput: https://github.com/APSL/puput/blob/master/puput/models.py
```
Entry = import_model(getattr(settings, "PUPUT_ENTRY_MODEL", EntryAbstract))
Blog = import_model(getattr(settings, "PUPUT_BLOG_MODEL", BlogAbstract))


class BlogPage(BlogRoutes, Page, Blog):
    ....
```

**Comment by gasman** [comment]
Thanks for the suggestion! There's an existing open issue about this - #836
