### ISSUE TITLE
Make test suite work against normal search backends

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#9901]
### Issue Summary

Currently, the settings file for the test environment [sets the default search backend to `wagtail.search.backends.database.fallback`](https://github.com/wagtail/wagtail/blob/c8981416ef0263b4c6ea960885e70e780a181f8d/wagtail/test/settings.py#L180). Additional backends are configured alongside it depending on the availability of postgres / elasticsearch etc, but these are only used in selected tests that are looking at backend-specific behaviour (e.g. within `wagtail.search.tests`).

As a result, most of the test suite runs against a backend which is not representative of real-world usage, and backend-specific issues such as #7720 are liable to be missed. Changing this setup to test against the proper backends is non-trivial, as there are currently numerous tests that fail against anything other than the fallback backend.

### Steps to Reproduce

1. Change [this line](https://github.com/wagtail/wagtail/blob/c8981416ef0263b4c6ea960885e70e780a181f8d/wagtail/test/settings.py#L180) to `wagtail.search.backends.database`
2. run `./runtests.py` or `./runtests.py --postgres`
3. observe numerous test failures

### Technical details

-   Python version: 3.8.0
-   Django version: 4.0.8
-   Wagtail version: main (f3776c5bbbb8add90a138f0b695e30a9498dfef7)

**Comment by RajPaliwal10** [comment]
Hi there I ran the test cases here what I got 

![Screenshot 2023-02-02 192918](https://user-images.githubusercontent.com/88249606/216344786-19a65b45-4d25-4066-ba39-e650c0b2e042.png)

can you please give me some guidance

**Comment by gasman** [comment]
@RyanWalker277 Yes, that would be very welcome!

**Comment by RyanWalker277** [comment]
Sure! Will try to close it as soon as possible

**Comment by RyanWalker277** [comment]
Hey @gasman ! I reproduced the issue at my end. The only fix in this case seems to change the existing testcases according to the new backend but that would'nt be much optimal. Is there any other fix to this other than changind the entirity of testcases?

**Comment by gasman** [comment]
@RyanWalker277 I don't think there's going to be a quick fix for this, no. We need to look at each failing test and determine whether it's testing behaviour that's expected to be consistent across all search backends (in which case the backends need be fixed) or relying on behaviour that's only expected to work on the fallback backend (in which case the test needs to be updated).

It's a big task, but it doesn't have to be done all in one go, and in many cases it's likely that fixing one problem will immediately fix a bunch of tests.

**Comment by RyanWalker277** [comment]
Understood @gasman ! Will start working on it and raise a PR covering some tests , that PR can be used as a draft and future contributors who take up this issue can add the updated tests.

**Comment by gasman** [comment]
Completed in #10208
