### ISSUE TITLE
Provide a consistent autocomplete method across all backends

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#9903]
### Issue Summary

https://docs.wagtail.org/en/latest/topics/search/searching.html#searching-pages has this not-entirely-accurate information:

> Before the `autocomplete()` method was introduced, the search method also did partial matching. This behaviour is deprecated and you should either switch to the new `autocomplete()` method or pass `partial_match=False` into the search method to opt-in to the new behaviour. The partial matching in `search()` will be completely removed in a future release.

[The previous version of this text](https://github.com/wagtail/wagtail/commit/d2b9ca94302ebdfdd8db39f9c7046c0d63d1f646) said "This behaviour is will be deprecated", which aptly sums up how muddled the actual situation has become. Based on my testing so far:

* The new database FTS backends in 2.15 have already prematurely dropped the deprecated behaviour: `search()` always performs a non-partial match regardless of the `partial_match` kwarg, and the only way to get an autocomplete search is to set `AutocompleteField()` on the model and use `autocomplete()`.
* The fallback database backend (used when FTS support is unavailable) has a `search()` method that _only_ performs partial matches (entirely ignoring the `search_fields` setup), and `autocomplete()` throws a NotImplementedError
* The Elasticsearch backend (untested) appears to have implementations for both `search(partial_match=True)` and `autocomplete()`,  but as per #9657 it's questionable whether they do what they're meant to

As a result, there is currently no autocomplete method that works across all backends. We badly need to provide one, document what it is, and actually initiate the deprecation process for the no-longer-supported one.

**Comment by gasman** [comment]
> The new database FTS backends in 2.15 have already prematurely dropped the deprecated behaviour: `search()` always performs a non-partial match regardless of the `partial_match` kwarg, and the only way to get an autocomplete search is to set `AutocompleteField()` on the model and use `autocomplete()`.

Unfortunately it's worse than this - the sqlite and mysql FTS backends had a broken implementation of `autocomplete()` and thus do not support autocompletion at all. As of #9900 these now raise a `NotImplementedError` (rather than crashing with an undefined `autocomplete_config`).

**Comment by GeekGawd** [comment]
I will start working on this issue... The requirements seems clear to me, I will explore and hopefully report soon on this issue.

**Comment by laymonage** [comment]
@gasman Not exactly related but still on the topic of autocomplete: I was reviewing #10336 and wagtail/bakerydemo#406 and noticed that we don't use autocomplete on index views. I vaguely remember reading that this was a deliberate decision (to only enable autocomplete by default on chooser views). Was that indeed the case or do we actually want to have it on index views as well?

**Comment by gasman** [comment]
@laymonage Hmm... I don't remember any discussions specifically about that point, but I'd be in favour of using autocomplete on any interface that has "show results as you type" behaviour.
