### ISSUE TITLE
RTL: inline comments 

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#9915]
Follow up to #9914.

The inline comment icon doesn't show if you start in RTL mode

<details>
<summary>📹 screencast of issue with comments</summary>

[rtl-and-comments.webm](https://user-images.githubusercontent.com/31622/213414912-2099588e-2f02-4664-b801-53c6a8c16970.webm)
</details>

**Comment by thibaudcolas** [comment]
👋 I believe this has been fixed already. See https://static-wagtail-v5-2.netlify.app/admin/pages/60/edit/ (manually edit the dir attribute to rtl).
