### ISSUE TITLE
Search on listing views doesn't work unless the `?q=` param exists in the URL

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#9918]
### Issue Summary

Possible regression in https://github.com/wagtail/wagtail/pull/9768

The `URLSearchParams.get()` returns `null` if the param doesn't exist, so the following code:

https://github.com/wagtail/wagtail/blob/a3f10acae17c892d843c419495e4204adb3ed991/client/src/entrypoints/admin/core.js#L270-L276

will crash during `currentQuery.trim()` when searching on the listing views (snippets, images, etc.) if the `?q=` param doesn't exist in the URL.

Might be a good time to add `required=False` in here as well:

https://github.com/wagtail/wagtail/blob/a3f10acae17c892d843c419495e4204adb3ed991/wagtail/admin/forms/search.py#L12

to remove this silly error when `q` is an empty string:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/6379424/213499685-ce37c064-2635-434f-952f-e85fae4ab9af.png">

### Steps to Reproduce

1. Spin up bakerydemo
2. Open the images listing
3. Try to search

**Comment by lb-** [comment]
Looking at this now

**Comment by lb-** [comment]
Have confirmed both issues exist and raised PRs for fixes

**Comment by laymonage** [comment]
FYI: #9923.

Wasn't sure to add `|| ''` on the `newQuery` as well, as I think `.val()` in this case always returns a string, but I suppose it's alright just to be safe.
