### ISSUE TITLE
Typing '/' to trigger the block toolbar sometimes stops working

### ISSUE THREAD

**Issue by jstamp** [wagtail/wagtail#9937]
### Issue Summary

This seems to happen when the block toolbar is deactivated with a mouse click.

### Steps to Reproduce

  1. In Bakerydemo, create a Standard page and add a paragraph block in the page body.
  2. Type the '/' key in the paragraph block. The block toolbar will appear.
  3. Click the mouse somewhere else on the page.  The toolbar will disappear.
  4. At this point you can no longer trigger the block toolbar again with the '/' key.  Try deleting the '/' char and typing it again.
  5. Additionally, if any line has a slash as the last char, the return key will not work for that line only.  Typing a space after the slash lets return work again for that line.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11.1
-   Django version: 4.1.5
-   Wagtail version: 4.2rc1

**Comment by th3hamm0r** [comment]
Can confirm it, there are issues with the new "/"-handling (#9905).
As soon as the block picker of a RichText field is broken, it won't come back unless you reload the page. Newly added RichText fields will work (until you break it :grimacing: ).

**Comment by thibaudcolas** [comment]
Thank you for looking into this! We made the dismissal of the block toolbar stricter than in the last release, so this is probably what’s happening here – we store what the text was when it was last dismissed (`/`), and ignore any further appearance of this prefix.

I’ll look into the fix for this, and also fix this "Enter" issue.
