### ISSUE TITLE
Search for a streamfield block can inadvertently create one

### ISSUE THREAD

**Issue by jstamp** [wagtail/wagtail#9938]
### Issue Summary

If you search for a streamfield block, clicking the 'esc' key to exit the search will create the first block that it found.

### Steps to Reproduce

  1. In Bakerydemo, create a Standard page.
  2. In the page body click the '+' to select a block.
  3. In the 'Search options...' input, type one character ('a' for instance).
  4. Press the escape key to exit.  The popup will close and a block will be created for the first filtered block.

It seems like there should be some sort of distinction between hitting 'esc' and 'return'.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11.1
-   Django version: 4.1.5
-   Wagtail version: 4.2rc1

**Comment by th3hamm0r** [comment]
Thx for the reporting @jstamp. Unfortunately, I cannot reproduce this with your provided steps. In my case, ESC always closes the picker and no block gets added.
I've used Firefox 109 and Chrome 109 on linux, the other technical details (python, django, wagtail) are exactly the same in my case.

**Comment by jstamp** [comment]
Ah.  OK, I see now.  It only happens when I have the Vimium plugin enabled.  Sorry, totally forgot to disable plugins while trying to figure out what's going on.

The new ComboBox.tsx highlights the first filtered item "to speed up selection" and then hitting esc for some reason causes Vimium to activate it.

Anyway, it works as expected with the plugin disabled.  Sorry about the noise.
