### ISSUE TITLE
The block toolbar button to the left of a rich text block does not toggle properly

### ISSUE THREAD

**Issue by jstamp** [wagtail/wagtail#9942]
### Issue Summary

In a streamfield, the 'insert a block' button will toggle a popup each time you click it.  However, the block toolbar for a rich text block only *shows* the popup. You can't toggle it closed by clicking it.

### Steps to Reproduce

  1. In Bakerydemo, create a Standard page and add a paragraph block in the page body.
  2. Give the paragraph block focus. A '+' icon will appear to the left of the block.
  3. Click the '+' icon to toggle it open.
  4. Click it again.  Notice it keeps getting triggered open.  Actually, mouse down seems to deactivate it, mouse up activates it again.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11.1
-   Django version: 4.1.5
-   Wagtail version: 4.2rc1

**Comment by lb-** [comment]
Is this the same as https://github.com/wagtail/wagtail/issues/9937 ?

**Comment by th3hamm0r** [comment]
I think this is a separate issue: in the previous version, once open, you could click everywhere outside the picker, including the "+"-icon, to close the picker.
In the new version, you cannot click at the "+" to close it, it will close and reopen.
Personally, not as blocking as #9937, but it would be nice to be able to toggle it by only clicking the icon again.

**Comment by thibaudcolas** [comment]
Thank you for reporting this! It looks like this was an issue in past versions too – but in past versions, we showed a backdrop across the whole page, which took over the clicks targeting this button.

On it!
