### ISSUE TITLE
Field and block UI hierarchy

### ISSUE THREAD

**Issue by benenright** [wagtail/wagtail#9945]
Review the type scale used for section and field labels in the page editor form, particularly for StreamField.

Scenarios for us to review:

- Section label
- Child block label for StreamBlock or ListBlock
- Child block label for StructBlock
- Field label

**Comment by benenright** [comment]
This will also encompass help text and min/max block counts UI as raised on [#9784](https://github.com/wagtail/wagtail/issues/9784)

**Comment by benenright** [comment]
Some other things we are addressing here:


### **Sibling fields within a section don’t share the same label size when one is a Streamfield. Which causes hierarchy issues.**

![Image](https://user-images.githubusercontent.com/4907819/214540995-bc2bf3c9-256c-4f58-9bff-c16202e55958.png)

![Image](https://user-images.githubusercontent.com/4907819/214541031-50a87fa7-801f-4567-9067-4c2b7c15471d.png)



### **Placing help text at the bottom of fields/streamfields/blocks means that it loses it's context once content/blocks are added**

![Image](https://user-images.githubusercontent.com/4907819/214541424-39f87642-d203-4afe-b46b-bfaeec4f8a52.png)



### **Various alignment inconsistencies we can improve**

![Image](https://user-images.githubusercontent.com/4907819/214541807-17144eb4-d464-4aac-8625-67af9a0b409e.png)

![Image](https://user-images.githubusercontent.com/4907819/214541841-bda0bc3d-2215-4968-bc10-9d38aea839e1.png)

![Image](https://user-images.githubusercontent.com/4907819/214541910-9837a4a0-4dcd-4731-8143-776bb848ce14.png)

![Image](https://user-images.githubusercontent.com/4907819/214542094-a28089b7-7e89-4e14-a06a-1f6d14f9f024.png)

![Image](https://user-images.githubusercontent.com/4907819/214542152-d8aae80f-63f3-44a1-b2c7-69df7f30dd90.png)



### **Generally tricky to see where sections/blocks end/begin when you scan - particularly if you are not hovering over the area**

![Image](https://user-images.githubusercontent.com/4907819/214542474-c5a15dfa-e2ae-430f-8035-198c8441d9f2.png)

**Comment by benenright** [comment]
Here are some links to Figma prototypes where we are tackling the issues outlined above:

**StreamField nesting:** 
https://www.figma.com/proto/h67EsVXdWsfu38WGGxWfpi/Wagtail-CMS?node-id=9895%3A99294&viewport=-3955%2C-17505%2C0.25&scaling=min-zoom&starting-point-node-id=9895%3A99294&show-proto-sidebar=1&hide-ui=1

**Combination of Sections, StreamFields and InlinePanels/MultiFieldPanels (unpopulated)**
https://www.figma.com/proto/h67EsVXdWsfu38WGGxWfpi/Wagtail-CMS?node-id=10098%3A125192&viewport=-3955%2C-17505%2C0.25&scaling=min-zoom&starting-point-node-id=10098%3A125192&show-proto-sidebar=1&hide-ui=1

**Combination of Sections, StreamFields and InlinePanels/MultiFieldPanels (populated)**
https://www.figma.com/proto/h67EsVXdWsfu38WGGxWfpi/Wagtail-CMS?node-id=10204%3A122561&viewport=-3955%2C-17505%2C0.25&scaling=min-zoom&starting-point-node-id=10204%3A122561&show-proto-sidebar=1&hide-ui=1
(exploring some variants of a MultiFieldPanel at the bottom of this one)

**Key points:**
- More consistent indentation spacing (30px)
- A more solid default icon ([circle-chevron-down](https://fontawesome.com/icons/circle-chevron-down?s=solid&f=classic))
- A different default '[stack](https://fontawesome.com/icons/layer-group?s=solid&f=classic)' icon for StreamField, InlinePanel, MultiFieldPanel to imply the dynamic nature of them
- Simplified from 3 to 2 label sizes
- Large label size for **top level** Section label, Field label (single), StreamField label, InlinePanel label, MultiFieldPanel label
- Small label size for any Child Field label inc StreamBlock, ListBlock, StructBlock)
- Help text moved up to underneath Field/Section/StreamField/InlinePanel/MultiFieldPanel labels in all instances
- Persistent faint dashed left&top border on StreamField, StreamBlock, InlinePanel, MultiFieldPanel, ListBlock ...aswell as a persistent StreamField '+' button to give more clarity to the level of nesting and make it easier to scan the start/end of blocks (without relying on hover)
- Exploring further UI devices to show the 'end' of a StreamField, InlinePanel, MultiFieldPanel area (still WIP)

**Comment by thibaudcolas** [comment]
Closing, over to https://github.com/wagtail/wagtail/issues/9755 for implementation.
