### ISSUE TITLE
Improve the Contribution Guide by describing how install wagtail for projects

### ISSUE THREAD

**Issue by GeekGawd** [wagtail/wagtail#9949]
A lot of people and even me when I started contributing to wagtail, needs a way so that when changes are done to the wagtail package locally, they are auto reflected with the hot-reload feature of Django. I had gotten of the wrong direction at first using Docker, though it worked Docker is extremely slow for Windows user due to the WSL overhead.

I know I am pretty stupid for not doing the obvious, i.e, `pip install -e /path/to/wagtail` in the wagtail project.

However, I have seen a lot of people in slack ask for the same. 

My suggestion is to add it as just another step in "Setting up the Wagtail codebase"

### Pertinent section of the Wagtail docs
https://docs.wagtail.org/en/latest/contributing/developing.html

### Details

This could just be added as another step in "Setting up the Wagtail codebase" subheading.

**Comment by laymonage** [comment]
I'm not sure I understand what you mean, but isn't that exactly part of the instructions in the docs?

<img width="997" alt="image" src="https://user-images.githubusercontent.com/6379424/214252777-e93eaaaf-2e60-439c-a5a0-e3590fa23186.png">

**Comment by GeekGawd** [comment]
Hi! So, what I gathered from this line was that I needed to install wagtail inside the wagtail repo with a virtualenv activated, not for the project like bakerydemo...

`pip install -e path/to/wagtail_repo"[testing, docs]" -U`

I think this slight modification is much more readable and understandable than just specifying .(dot)

**Comment by laymonage** [comment]
But the line just above it tells you to `git clone` and `cd wagtail`, so that means you're in the Wagtail repo directory at that point, hence it uses `.`

If we wrote `path/to/wagtail_repo`, you can also argue that it's more confusing as some people might just copy and paste the instructions, then finding out later that it failed to install because `path/to/wagtail_repo` is not a real directory.

I think the last paragraph in the screenshot there clarifies the situation, but yeah I agree that we could make this clearer. Maybe we could improve it by adding *another* code block showing that command, instead of replacing the existing one, e.g.

> Any Wagtail sites you start up in this virtualenv will now run against this development instance of Wagtail. We recommend using the [Wagtail Bakery demo site](https://github.com/wagtail/bakerydemo/) as a basis for developing Wagtail. Keep in mind that the setup steps for a Wagtail site may include installing a release version of Wagtail, which will override the development version you've just set up. In this case, you should install the site before running the `pip install -e` step, or re-run that step after the site is installed:
> 
> ```sh
> pip install -e path/to/wagtail"[testing, docs]" -U
> ```

**Comment by msaini0r** [comment]
Just a small suggestion, Why don't we just create a video and explain every step and add it in this page. Because beginners tend to skip the documentation reading part.

**Comment by gasman** [comment]
@msaini0r Videos are more work to produce, and harder to update if they become outdated.

**Comment by msaini0r** [comment]
@gasman seems true. Just a small request. I am new to wagtail, so please let me know if you come across an interesting new issue. Other than that, I am trying my best to contribute.
