### ISSUE TITLE
Ability to support outer double quotes in `wagtail.search.utils.parse_query_string`

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9951]
### Is your proposal related to a problem?

In #7961 (PR #9875) the util `wagtail.search.utils.parse_query_string` was updated to support more than one key/value syntax as a string being parsed into an Object for the query.

However, it was found that the support only works (originally, and with the changes) when the outer quotations are single quotation not double quotations.

### Describe the solution you'd like

All the following combinations of single/multi key value pairs and usage of outer double or single quotations should work the same. This support should also be documented here https://docs.wagtail.org/en/stable/topics/search/searching.html#query-string-parsing

```shell
>>> from wagtail.search.utils import parse_query_string
>>> parse_query_string('key1:"hello key1"')
({'key1': 'hello key1'}, <Not <MatchAll>>)
>>> parse_query_string('key1:"hello key1" key2:"hello key2"')
({'key1': 'hello key1', 'key2': 'hello key2'}, <Not <MatchAll>>)
>>> parse_query_string("key1:'hello key1'")
({}, <PlainText "key1:'hello key1'" operator='and' boost=1>)
>>> parse_query_string("key1:'hello key1' key2:'hello key 2'")
({}, <PlainText "key1:'hello key1' key2:'hello key 2'" operator='and' boost=1>)
```

Observe above that the outer double quotations are treated a single string, but the outer single quotations are treated as a set of filters.

### Describe alternatives you've considered

* We could close this issue as not needing to be implemented and/or document that only one form of quotations are supported and provide an example of escaping instead.

### Additional info

> @tomdyson should I raise a new issue for that additional edge case?

I think so, yes please @lb-. Unless the quote type gets normalised further up the stack? I had a look but couldn't find anything.

_Originally posted by @tomdyson in https://github.com/wagtail/wagtail/issues/9875#issuecomment-1396804696_

**Comment by salty-ivy** [comment]
adding few additional regEX check would be good to go
![image](https://user-images.githubusercontent.com/74553951/214525392-c5def778-685c-4c07-87bc-3bce150c5608.png)
this is working perfect gonna test a little, then make a PR

**Comment by salty-ivy** [comment]
additionally eg in the docs is wrong as \w does not count `-` it only accounts for `_` 
![image](https://user-images.githubusercontent.com/74553951/214531682-462efe58-85b5-4758-8e20-a428d5aa49b6.png)
![image](https://user-images.githubusercontent.com/74553951/214531743-5516fa4b-ef46-489f-bbbe-5d3e77c7b553.png)
