### ISSUE TITLE
Latest storybook version is not rendering components 

### ISSUE THREAD

**Issue by salty-ivy** [wagtail/wagtail#9958]
### Issue Summary
storybook is not rendering components.

### Steps to Reproduce

1.follow https://docs.wagtail.org/en/stable/contributing/developing.html#using-the-pattern-library to start storybooks 
for wagtail's UI components

2. click on different components to check if they rendering or not 

### Screenshots
![image](https://user-images.githubusercontent.com/74553951/214374509-1004f82b-db38-44c4-8fed-1a1045976388.png)
![image](https://user-images.githubusercontent.com/74553951/214374580-0c8205b4-ad38-448f-ba64-1bf65131966b.png)

### Additional context
i even checked it on fresh wagtail local develoment setup, didn't work.
not sure what's causing the issue

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

-   Python version: Run `3.10.4`
-   Django version: `4.0.8`
-   Wagtail version: `latest development version`.
-   Browser version: firefox 109, https://www.whatsmybrowser.org/b/R69KU

**Comment by lb-** [comment]
@Lovelyfin00 I think you said that you had this issue also? Can you confirm - maybe take a screenshot. 

At the moment I'm running into issues where I can't use Storybook locally either but it's because I haven't had a chance to work around the docker problem. https://github.com/wagtail/docker-wagtail-develop/issues/47

**Comment by Lovelyfin00** [comment]
I’ve not tried it recently. But yes, I had issues. None of the components displayed. It showed icon-sprite error. I’ll post a screenshot when my pc is on

**Comment by Lovelyfin00** [comment]
This is the  only errors it shows on mine. 

![image](https://user-images.githubusercontent.com/38161296/214428586-c112f4d0-d841-4490-a2b7-e3f1bf9d9eb4.png)

![image](https://user-images.githubusercontent.com/38161296/214428667-042e08d0-7c6d-40c2-ab12-6914949a8beb.png)

**Comment by salty-ivy** [comment]
So none of the components are rendering? 
It's pretty recent I guess it's working in my older branches

**Comment by lb-** [comment]
@thibaudcolas  as discussed, we agreed that some form of basic CI check would be really helpful for us to have that the Storybook build (or even runs).

We could use the test runner (even if there is only one or maybe it will work with no specific tests) https://storybook.js.org/docs/react/writing-tests/test-runner in the CI. Alternatively we could just build the static output, check that it exits ok and that may be enough for some starting points of checks.

Also related to previous discussions https://github.com/wagtail/wagtail/issues/8660

Thanks Thibaud - appreciate your help with this.

**Comment by salty-ivy** [comment]
> This is the only errors it shows on mine.
> 
> ![image](https://user-images.githubusercontent.com/38161296/214428586-c112f4d0-d841-4490-a2b7-e3f1bf9d9eb4.png)
> 
> ![image](https://user-images.githubusercontent.com/38161296/214428667-042e08d0-7c6d-40c2-ab12-6914949a8beb.png)

i guess, this part of https://github.com/wagtail/wagtail/issues/9306

**Comment by thibaudcolas** [comment]
I believe this has been fixed as of #10089. There were quite a few issues – hopefully similar problems will be caught by the build step we’ve added in that PR.

#8660 still feels very promising to me, just takes time to set that up correctly which we’ve not had yet.
