### ISSUE TITLE
Make time window of "your most recent edits" on dashboard longer

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#996]
Given the nature of "test" or "foo" titles etc, the "your most recent edits" is actually the best way of finding the test page I was working with most recently during template development, but it would be better if it were more than 5 items. 

Suggest it links through to a page listing all edits chronologically, paged. Or just displays more by default, perhaps with an expanding view frame on hover to avoid taking up too much dashboard space.

**Comment by mhnbcu** [comment]
:+1:

**Comment by SalahAdDin** [comment]
:+1:

**Comment by maartenkling** [comment]
https://github.com/wagtail/wagtail/pull/3483
This adds an option to configure the number, i think 5 is okay by default. If you need more, use the setting.
