### ISSUE TITLE
small import typo (route, repath) in docs in RoutableMixin

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#9963]
The docs show you can use re_path here: https://docs.wagtail.org/en/stable/reference/contrib/routablepage.html#changing-route-names

But re_path is not imported but route is imported.

**Comment by salty-ivy** [comment]
@onno-timmerman should i push with https://github.com/wagtail/wagtail/pull/9966 some part of it deals with improving the docs as well, a separate PR for this one might not be worth it

**Comment by gasman** [comment]
@salty-ivy A one-line PR is always much better for us to handle than a bugfix mixed in with unrelated work :-)

**Comment by salty-ivy** [comment]
yea, well from reviewing point of you, that is true XD

**Comment by salty-ivy** [comment]
In that case, i would make a new one

**Comment by gasman** [comment]
Fixed in #9970
