### ISSUE TITLE
Update djhtml to support Stimulus `data-action` attributes

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9965]
### Is your proposal related to a problem?

Using `click->` caused the HTML formatter to cause issues.

```
<a class="skiplink button" href="#main" data-controller="w-skip-link" data-action="click->w-skip-link#skip">{% trans 'Skip to main content' %}</a>
```

The formatter has a problem with `>` in HTML attributes.

### Describe the solution you'd like

Upgrading dhtml should solve this https://github.com/rtts/djhtml/issues/57

### Describe alternatives you've considered

We can use `verbatim` as a work around for now.

Using the shorthand version did not make the formatter freak out https://stimulus.hotwired.dev/reference/actions#event-shorthand

```
<a class="skiplink button" href="#main" data-controller="w-skip-link" data-action="w-skip-link#skip">{% trans 'Skip to main content' %}</a>
```

### Additional context

* https://github.com/wagtail/wagtail/pull/9818#discussion_r1066393372
* _Originally posted by @lb- in https://github.com/wagtail/wagtail/pull/9952#discussion_r1085993495_
* https://github.com/rtts/djhtml/issues/57

**Comment by lb-** [comment]
@Lovelyfin00  this should be simply a matter of updating the reference in `setup.py`

https://github.com/wagtail/wagtail/blob/main/setup.py#L68

From `"djhtml==1.4.13",` to "djhtml==1.5.2",`

**Comment by Lovelyfin00** [comment]
Great thanks 
Will do that👍

**Comment by lb-** [comment]
Loveth - once updated locally, you will need to do a pip install again and then also run the formatter - there may be some subtle changes to the existing formatting from the new version.

Also see the actual fix that was put into the library for reference https://github.com/rtts/djhtml/pull/62
