### ISSUE TITLE
Account menu: UI-issue with long usernames

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9979]
### Issue Summary

With long usernames or emails (if you use email as the username-field), the account menu in the footer of the sidebar has its issues:
![wagtail_account_menu_issue](https://user-images.githubusercontent.com/468164/215073396-63d557ed-ec7f-4f36-a19b-167cfe16a582.png)

I've reproduced it with 4.0.4 and 4.2rc1, but not with 2.15, its probably related to the major UI changes in 3.x/4.x.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. `./manage.py makemigrations && ./manage.py migrate && ./manage.py createsuperuser && ./manage.py runserver`
   When `createsuperuser` is run, use a long username.
4. Login to the CMS

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11
-   Django version: 4.1.5
-   Wagtail version: 4.0.4, 4.2rc1
-   Browser version: Firefox 109, Chrome 109

**Comment by TensaCoder** [comment]
Hi, I would like to work on this issue!

Could you please assign this to me.

**Comment by zerolab** [comment]
@TensaCoder we do not assign anything to folks outside the core team. 
Feel free to work on it. While at it, please read https://dev.to/lb/ten-tasty-ingredients-for-a-delicious-pull-request-hgc

**Comment by gasman** [comment]
@th3hamm0r I'm pretty sure that the "..." truncation was designed with exactly this situation in mind. Can you elaborate further on why you feel this isn't a suitable way of handling overly long usernames? (And what would you suggest we do instead?)

**Comment by th3hamm0r** [comment]
@gasman Nothing against the "...", I wouldn't dare change that 😅, but look at the arrow, which is displaced. That's the issue, I should have been more clear, sry.
The main menu items have no problem with large titles.

**Comment by laymonage** [comment]
Yeah, I can confirm this.

The fix is:

```scss
.sidebar-footer {
  &__account-toggle {
    min-width: 0;

    .icon {
      flex-shrink: 0;
    }
  }
}
```

Before:
<img width="208" alt="image" src="https://user-images.githubusercontent.com/6379424/215197201-ddc97e27-60dd-42a1-b877-8abb28e9ea7f.png">

After:
<img width="208" alt="image" src="https://user-images.githubusercontent.com/6379424/215197053-46b2a81b-5697-4f13-a887-16d1a296b719.png">

**Comment by salty-ivy** [comment]
@laymonage i guess we can add the style directly into the existing toggle selector 
don't need to re-select it 

`&__account {

    &-toggle {
      min-width: 0;

      .icon {
        flex-shrink: 0;
      }
    }
 }`

**Comment by laymonage** [comment]
> @laymonage i guess we can add the style directly into the existing toggle selector don't need to re-select it

I know, that was just a pointer so you can see what the class is. If I only wrote `&__account { &-toggle`, it's not very clear is it 😄

**Comment by salty-ivy** [comment]
I see I thought you meant it that way XD, sorry.
