### ISSUE TITLE
Not showing main StreamField in admin of existing page if new field was added to any of included blocks.

### ISSUE THREAD

**Issue by HolidayMan** [wagtail/wagtail#9986]
### Issue Summary

I can't just figure out why this happens, as locally everything works, but on production doesn't. I have **body** field in my page, which is StreamField. Page is already saved in database. I created new StructBlock and used it as a new field in one of included blocks in StreamField. After that my **body** in admin page on production is empty. In console I get a few errors, one of them is *ReferenceError: initBlockWidget is not defined*. It must be imported on loading page from blocks.js, but it is not defined on rendering. When I just type in browser console by myself **initBlockWidget('body')**, it suddenly works and renders my **body** field.  

Empty body
<img width="466" alt="Empty Body" src="https://user-images.githubusercontent.com/37782099/215516535-90e795ed-72f7-4946-b0bc-1711725df371.png">

Erorrs in browser console
<img width="991" alt="Errors in browser console" src="https://user-images.githubusercontent.com/37782099/215518628-4d7de545-042c-4edd-9edb-5413d396a52d.png">

### Steps to Reproduce
It happens only on production, unfortunately I can't reproduce this bug on localhost, even if environment is the same as on production (I run project in Docker). 

### Technical details

-   Python version: 3.10 in Docker (python:3.10-alpine).
-   Django version: 4.1.
-   Wagtail version: 4.1.1.
-   Browser version: Firefox 109.

**Comment by gasman** [comment]
Unfortunately without any known steps to reproduce, we are unable to handle this as a bug report, sorry. You may be able to get some assistance from [our support channels](https://docs.wagtail.io/en/stable/support.html), though.
