### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'getTextLabel') in admin and missing stream blocks. 

### ISSUE THREAD

**Issue by dopry** [wagtail/wagtail#9990]
### Issue Summary
I had a custom structblock 

```
class MyRichTextBlock(TnStructBlock):
    richtext = RichTextBlock()

    class Meta:
        icon = "doc-full"
        label_format = "Rich Text, {text}"
```

Which would cause the console error `Uncaught TypeError: Cannot read properties of undefined (reading 'getTextLabel') in admin` whenever I would add it in the admin. It was also not saved with the streamfield.  When the label builders is building the label and reads the {text} token, it looks for the text token in object, but it's not present.  I would expect unfound tokens to just return an empty string, not crash the admin. In this case my editors lost all of the streamfield following the rich text blocks when they edited it. 

I don't know where the source for this is but in my console I have
```
t.prototype.getTextLabel = function(t) {
  var e, n, o = this;
  if (this.blockDef.meta.labelFormat)
      return this.blockDef.meta.labelFormat.replace(/\{(\w+)\}/g, (function(e, n) {
          var i = o.childBlocks[n];
          return i.getTextLabel ? i.getTextLabel(t) : ""
      }
      ));
  ....
```
the problem is that i is undefined...`return i.getTextLabel ` should read like `return i && i.getTextLabel && i.getTextLabel(t) || ""`

### Steps to Reproduce

1. put an invalid token in a struct block label_name
2.  add it to your stream field, 
3. try to save a draft.

### Technical details

-   Python version: 3.10.9
-   Django version: 3.2.9
-   Wagtail version: 4.1

**Comment by Aadijindal07** [comment]
i know how to do it kindly assign it to me

**Comment by Aadijindal07** [comment]
@zerolab this is the code 

t.prototype.getTextLabel = function(t) {
  var e, n, o = this;
  if (this.blockDef.meta.labelFormat)
      return this.blockDef.meta.labelFormat.replace(/\{(\w+)\}/g, (function(e, n) {
          var i = o.childBlocks[n];
          return i && i.getTextLabel ? i.getTextLabel(t) : ""
      }
      ));
  ....

it will possibly work 
actually I want to crack gsoc as it will improve my profile for university and i just know how to code i dont know how to like use this shitty github can you guide me little bit how to like crack gsoc ,  if any other thing you want from me i will be very happy to solve it i dont know how to pull request

**Comment by gasman** [comment]
@Aadijindal07 Did you read the article @zerolab linked to? It provides various resources for learning Github.

**Comment by Aadijindal07** [comment]
@gasman yes i read but it was so boringgggggg.....

**Comment by Aadijindal07** [comment]
@gasman how can i crack gsoc

**Comment by Aadijindal07** [comment]
@gasman  you might feel i am dumb but i am not able to join slack can you help

**Comment by dopry** [comment]
@Aadijindal07 well if you want to participate in an opensource community and GSOC you **need** to do it. If you want to perform well in school and make software development a career, learning how to use source control and collaboration platforms like Github/GitLab/BitBucket/etc is as important as knowing how to code. We're not here to hold your hand while you first learn to walk. I would also recommend that you avoid using taboo words like `shi**y`. It's generally frowned upon by most Community Guidelines.

**Comment by Aadijindal07** [comment]
@dopry ya totally agree man thanks for advice

**Comment by salty-ivy** [comment]
@dopry this is the code you are referring to ? https://github.com/wagtail/wagtail/blob/bf3ec15209178b6d1f2df3317a6c6469a38f554c/client/src/components/StreamField/blocks/StructBlock.js#L137

**Comment by dopry** [comment]
Looks like line 144 is the culprit.

**Comment by salty-ivy** [comment]
could you provide a little bit more detailed steps to reproduce ? that would be helpful for me to quickly reproduce the error

**Comment by Aadijindal07** [comment]
First-time contributors require maintainers to approve workflows in order to run. Kindly do it is running properly you can check.
