### ISSUE TITLE
At the admin/users/ there is a label called level and this is unclear

### ISSUE THREAD

**Issue by maartenkling** [wagtail/wagtail#9991]
### Is your proposal related to a problem?

At the admin/users/ there is a label called level and its showing if you are admin or not. 

https://wagtailcms.slack.com/archives/C014L7KJH3N/p1674474823661809

### Describe the solution you'd like

That probably should say "Access level" to be more explicit. Or at least we need to add context for translators. Can't think of a better name. e.g. "role" would not quite fit as that could also be a group, but in many contexts that would be a role in an organisation or team.

Change the label.

**Comment by RajPaliwal10** [comment]
I think "Access Control" would better describe levels of access and privileges granted to users within a system.

**Comment by gasman** [comment]
"Access Control" feels a bit too technical for this purpose - it's a broad subject covering things like authentication and mapping permissions to resources, but here we're just talking about one piece of information (namely, whether they're a superuser or not).

I think "Access level" would work well here.

**Comment by RajPaliwal10** [comment]
Yeah I am agree with you also

**Comment by Ananjan-R** [comment]
Hey could I undertake this task?

**Comment by vallabhtiwari** [comment]
Hi @gasman , I tried to work on this and have got this.
![Screenshot from 2023-02-04 00-15-45](https://user-images.githubusercontent.com/87356031/216682944-93ea885c-63d8-4231-a1ce-21cd75a3ea66.png)

But things are not working in different language codes. Could you give any hint or explanation please?
![Screenshot from 2023-02-04 00-18-16](https://user-images.githubusercontent.com/87356031/216683117-ea0e80d1-7803-4b68-bea6-97aec726c78d.png)

**Comment by gasman** [comment]
@vallabhtiwari As long as you've kept the `_("...")` wrapper or `{% trans %}` tag from the old code, it's all fine. Translations are managed externally through [Transifex](https://explore.transifex.com/torchbox/wagtail/), so at the moment there won't be a translation available for "Access level" - some time before the next release we'll push the updated set of strings to Transifex so that translators can fill them in.

**Comment by vallabhtiwari** [comment]
So this means I can make a PR now?

**Comment by gasman** [comment]
@vallabhtiwari Yep!

**Comment by Ananjan-R** [comment]
Does this mean that I can't work on this issue anymore?

**Comment by Pritimayasahoo** [comment]
I want to work on this issue please assign me this issue

**Comment by lb-** [comment]
@Pritimayasahoo - please take a moment to always read the full issue's comments and linked items. 

So far there has already been two PRs for this change that have come in already. 

https://github.com/wagtail/wagtail/pull/10019
https://github.com/wagtail/wagtail/pull/10017
