### ISSUE TITLE
Cannot edit a page/snippet after cancelling a workflow until the next reload

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail#9992]
### Issue Summary

If you are not a superuser and you submit a page/snippet to a workflow and cancel the workflow, the page will be in a locked state and you will not be able to edit it until you reload the page. In addition, an error message saying "The page could not be saved as it is locked" is shown.

There are some nuances to this issue:

- In older releases, the page was not locked but the error message is shown, and it says "The page cannot be saved due to validation errors". I haven't verified how far back this goes, but this existed in 4.0-prerelease, so I'd assume it's been there since workflows were introduced.

  <details>

  <summary>Screenshot</summary>

  <img width="860" alt="image" src="https://user-images.githubusercontent.com/6379424/215728232-46bcd71f-c1e3-4b1a-b48c-112bb0f42d87.png">

  </details>

- Then, in 315d9a938a, the error message was changed to "The page could not be saved as it is locked" when the `Lock` objects were introduced.

  <details>

  <summary>Screenshot</summary>

  <img width="860" alt="image" src="https://user-images.githubusercontent.com/6379424/215733212-b1ea2622-1867-4f18-b229-123edade8a37.png">

  </details>

- In 40c1227edcfb516f052bc26325370d17bd4cebb0, the action menu uses the `Lock` objects to determine the locked state. This results in the page getting "locked" and you cannot edit the page. If you reload the page, the editor loads normally.

  <details>

  <summary>Screenshot</summary>

  <img width="860" alt="image" src="https://user-images.githubusercontent.com/6379424/215736105-3b7e8aa9-19ef-4690-b748-653f6fac0dc0.png">

  </details> 

I believe this is because of the reuse of a stale lock object. We get the lock object at the start of the view's request-response cycle. When the workflow is cancelled, the lock object is still referencing the stale `WorkflowLock`. The view doesn't return a redirect response, so the stale lock object is reused in the context to render the template.

### Steps to Reproduce

1. Spin up bakerydemo
2. Add a user with the Editor role
3. Log in as the editor user
4. Submit a page to a workflow
5. Cancel the workflow
6. See result

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The page shouldn't be locked, and the error message shouldn't be shown, because the "Cancel workflow" action is a valid action in this case.

**Comment by Aadijindal07** [comment]
To resolve this issue, a check should be added in the view's request-response cycle to determine if the workflow is cancelled, and if it is, the lock object should not be reused. This way, the stale lock object will not be referencing the cancelled WorkflowLock and the page will not be locked. Additionally, the error message should be changed or removed to reflect that the "Cancel workflow" action is a valid action.

If you will not be able to do then assign it to me

**Comment by gasman** [comment]
Fixed in #9994
