### ISSUE TITLE
`RichTextField` Placeholder without block or with only blocks—misleading editors

### ISSUE THREAD

**Issue by Zogsha** [wagtail/wagtail#9997]
### Issue Summary

The `RichTextField ` placeholder always says “Write something or type '/' to insert a block”.
Furthermore, without blocks, the slash command is working but returns nothing.
I think it misleads editors when there are no blocks or only blocks.

I think it should only say “Write something” when there is no block available, and the slash command should be deactivated. When there are only blocks, it should say “type '/' to insert a block” with the slash command activated.

### Steps to Reproduce

Just open a `RichTextField` in the editor interface.

**Comment by gasman** [comment]
Thanks for the report @Zogsha! I think this is already covered by #9706.
